SUMO - Simulation of Urban MObility: MSNet::VehicleStateListener Class Reference
MSNet::VehicleStateListener Class Reference abstract
Interface for objects listening to vehicle state changes.
#include <MSNet.h>
Public Member Functions
virtual void vehicleStateChanged (const SUMOVehicle *const vehicle, VehicleState to)=0
Called if a vehicle changes its state.
VehicleStateListener ()
Constructor.
virtual ~VehicleStateListener ()
Destructor.
Detailed Description
Interface for objects listening to vehicle state changes.
Definition at line 564 of file MSNet.h.
Constructor & Destructor Documentation
MSNet::VehicleStateListener::VehicleStateListener () inline
Constructor.
Definition at line 567 of file MSNet.h.
virtual MSNet::VehicleStateListener::~VehicleStateListener () inline virtual
Destructor.
Definition at line 570 of file MSNet.h.
References MSNet::addVehicleStateListener(), MSNet::getEffort(), MSNet::getLanesRTree(), MSNet::getPedestrianRouter(), MSNet::getRouterEffort(), MSNet::getRouterTT(), MSNet::getTravelTime(), MSNet::informVehicleStateListener(), MSNet::removeVehicleStateListener(), SUMOReal, and vehicleStateChanged().
Member Function Documentation
virtual void MSNet::VehicleStateListener::vehicleStateChanged (const SUMOVehicle *const vehicle, VehicleState to) pure virtual
Called if a vehicle changes its state.
Parameters
[in] vehicle The vehicle which changed its state
[in] to The state the vehicle has changed to
Implemented in MSDevice_Vehroutes::StateListener, and TraCIServer.
Referenced by ~VehicleStateListener().
The documentation for this class was generated from the following file:
MSNet.h