SUMO - Simulation of Urban MObility: GNERerouter::routeProbReroute Class Reference
GNERerouter::routeProbReroute Class Reference
#include <GNERerouter.h>
Public Member Functions
std::string getNewRouteId () const
get new route id
SUMOReal getProbability () const
get probability
routeProbReroute (std::string newRouteId, SUMOReal probability)
constructor
void setProbability (SUMOReal probability)
set probability
~routeProbReroute ()
destructor
Private Attributes
std::string myNewRouteId
id of new route
SUMOReal myProbability
probability with which a vehicle will use the given edge as destination
Detailed Description
Definition at line 133 of file GNERerouter.h.
Constructor & Destructor Documentation
GNERerouter::routeProbReroute::routeProbReroute (std::string newRouteId, SUMOReal probability)
constructor
Definition at line 194 of file GNERerouter.cpp.
GNERerouter::routeProbReroute::~routeProbReroute ()
destructor
Definition at line 200 of file GNERerouter.cpp.
Member Function Documentation
std::string GNERerouter::routeProbReroute::getNewRouteId () const
get new route id
Definition at line 205 of file GNERerouter.cpp.
References myNewRouteId, and SUMOReal.
Referenced by GNERerouter::rerouterInterval::insertRouteProbReroute(), and GNERerouter::rerouterInterval::removeRouteProbReroute().
SUMOReal GNERerouter::routeProbReroute::getProbability () const
get probability
Definition at line 211 of file GNERerouter.cpp.
References myProbability.
void GNERerouter::routeProbReroute::setProbability (SUMOReal probability)
set probability
Exceptions
InvalidArgument if probability isn't valid
Definition at line 217 of file GNERerouter.cpp.
References myProbability, and toString().
Field Documentation
std::string GNERerouter::routeProbReroute::myNewRouteId private
id of new route
Definition at line 153 of file GNERerouter.h.
Referenced by getNewRouteId().
SUMOReal GNERerouter::routeProbReroute::myProbability private
probability with which a vehicle will use the given edge as destination
Definition at line 156 of file GNERerouter.h.
Referenced by getProbability(), and setProbability().
The documentation for this class was generated from the following files:
GNERerouter.h
GNERerouter.cpp