SUMO - Simulation of Urban MObility: MSEdgeControl Class Reference
MSEdgeControl Class Reference
Stores edges and lanes, performs moving of vehicle.
#include <MSEdgeControl.h>
Data Structures
struct LaneUsage
A structure holding some basic information about a simulated lane.
Public Member Functions
void changeLanes (SUMOTime t)
Moves (precomputes) critical vehicles.
void detectCollisions (SUMOTime timestep, const std::string &stage)
Detect collisions.
std::vector< std::string > getEdgeNames () const
Returns the list of names of all known edges.
const MSEdgeVector & getEdges () const
Returns loaded edges.
void gotActive (MSLane *l)
Informs the control that the given lane got active.
MSEdgeControl (const std::vector< MSEdge * > &edges)
Constructor.
void patchActiveLanes ()
Resets information whether a lane is active for all lanes.
~MSEdgeControl ()
Destructor.
Interfaces for longitudinal vehicle movement
void planMovements (SUMOTime t)
Compute safe velocities for all vehicles based on positions and speeds from the last time step. Also registers ApproachingVehicleInformation for all links.
void executeMovements (SUMOTime t)
Executes planned vehicle movements with regards to right-of-way.
Private Types
typedef std::vector< LaneUsage > LaneUsageVector
Definition of a container about a lane's number of vehicles and neighbors.
Private Member Functions
MSEdgeControl (const MSEdgeControl &)
Copy constructor.
MSEdgeControl & operator= (const MSEdgeControl &)
Assignment operator.
Private Attributes
std::list< MSLane * > myActiveLanes
The list of active (not empty) lanes.
std::set< MSLane *, Named::ComparatorIdLess > myChangedStateLanes
Lanes which changed the state without informing the control.
MSEdgeVector myEdges
Loaded edges.
LaneUsageVector myLanes
Information about lanes' number of vehicles and neighbors.
std::vector< SUMOTime > myLastLaneChange
The list of active (not empty) lanes.
std::vector< MSLane * > myWithVehicles2Integrate
A storage for lanes which shall be integrated because vehicles have moved onto them.
Detailed Description
Stores edges and lanes, performs moving of vehicle.
In order to avoid touching all lanes, even the empty ones, this class stores and updates the information about "active" lanes, those that have at least one vehicle on them. During longitudinal movement, this can be simply achieved through return values of the MSLane-methods, signalling either that the lane got active or inactive. This is but not possible when changing lanes, we have to go through the lanes, here. Also, we have to add lanes on which a vehicle was inserted, separately, doing this into ("myChangedStateLanes") which entries are integrated at the begin of is step in "patchActiveLanes".
Definition at line 74 of file MSEdgeControl.h.
Member Typedef Documentation
typedef std::vector<LaneUsage> MSEdgeControl::LaneUsageVector private
Definition of a container about a lane's number of vehicles and neighbors.
Definition at line 209 of file MSEdgeControl.h.
Constructor & Destructor Documentation
MSEdgeControl::MSEdgeControl (const std::vector< MSEdge * > & edges)
Constructor.
Builds LaneUsage information for each lane and assigns them to lanes.
Parameters
[in] edges The loaded edges
Todo:
Assure both containers are not 0
Definition at line 50 of file MSEdgeControl.cpp.
References myEdges, myLanes, and myLastLaneChange.
MSEdgeControl::~MSEdgeControl ()
Destructor.
Definition at line 79 of file MSEdgeControl.cpp.
MSEdgeControl::MSEdgeControl (const MSEdgeControl &) private
Copy constructor.
Member Function Documentation
void MSEdgeControl::changeLanes (SUMOTime t)
Moves (precomputes) critical vehicles.
Calls "changeLanes" of each of the multi-lane edges. Check then for this edge whether a lane got active, adding it to "myActiveLanes" and marking it as active in such cases.
See also
MSEdge::changeLanes
Definition at line 150 of file MSEdgeControl.cpp.
References MSEdgeControl::LaneUsage::amActive, MSEdge::changeLanes(), MSEdge::getLanes(), MSEdge::getNumericalID(), MSEdgeControl::LaneUsage::haveNeighbors, myActiveLanes, myLanes, and myLastLaneChange.
Referenced by MSNet::simulationStep().
void MSEdgeControl::detectCollisions (SUMOTime timestep, const std::string & stage)
Detect collisions.
Calls "detectCollisions" of each lane. Shouldn't be necessary if model-implementation is correct. The parameter is simply passed to the lane-instance for reporting.
Parameters
[in] timestep The current time step
[in] stage The current stage within the simulation step
Note
see MSNet::simulationStep
Definition at line 184 of file MSEdgeControl.cpp.
References myActiveLanes.
Referenced by MSNet::simulationStep().
void MSEdgeControl::executeMovements (SUMOTime t)
Executes planned vehicle movements with regards to right-of-way.
This method goes through all active lanes calling their executeMovements method which causes vehicles to update their positions and speeds. Lanes which receive new vehicles are stored in myWithVehicles2Integrate After movements are executed the vehicles in myWithVehicles2Integrate are put onto their new lanes This method also updates the "active" status of lanes
See also
MSLane::executeMovements
MSLane::integrateNewVehicle
Todo:
When moving to parallel processing, the usage of myWithVehicles2Integrate would get insecure!!
Definition at line 116 of file MSEdgeControl.cpp.
References MSEdgeControl::LaneUsage::amActive, MSGlobals::gLateralResolution, MSEdgeControl::LaneUsage::haveNeighbors, myActiveLanes, myLanes, and myWithVehicles2Integrate.
Referenced by MSNet::simulationStep().
std::vector< std::string > MSEdgeControl::getEdgeNames () const
Returns the list of names of all known edges.
Returns
a vector of names of all known edges
Definition at line 193 of file MSEdgeControl.cpp.
References myEdges.
Referenced by TraCIServerAPI_Simulation::convertCartesianToRoadMap(), and getEdges().
const MSEdgeVector& MSEdgeControl::getEdges () const inline
Returns loaded edges.
Returns
the container storing one-lane edges
Todo:
Check: Is this secure?
Definition at line 159 of file MSEdgeControl.h.
References getEdgeNames(), gotActive(), and myEdges.
Referenced by MSDevice_Routing::adaptEdgeEfforts(), MSDevice_Routing::buildVehicleDevices(), MSNet::checkElevation(), TraCIServerAPI_Vehicle::getOrBuildVTDMap(), MSMeanData::init(), MSFCDExport::write(), MSXMLRawOut::write(), MSQueueExport::writeEdge(), MSFullExport::writeEdge(), and MSNet::writeOutput().
void MSEdgeControl::gotActive (MSLane * l)
Informs the control that the given lane got active.
Parameters
[in] l The activated lane
Todo:
Check for l==0?
Definition at line 203 of file MSEdgeControl.cpp.
References myChangedStateLanes.
Referenced by getEdges(), and MSLane::incorporateVehicle().
MSEdgeControl& MSEdgeControl::operator= (const MSEdgeControl &) private
Assignment operator.
void MSEdgeControl::patchActiveLanes ()
Resets information whether a lane is active for all lanes.
For each lane in "myChangedStateLanes": if the lane has at least one vehicle and is not marked as being active, it is added to the list og active lanes and marked as being active.
Definition at line 84 of file MSEdgeControl.cpp.
References MSEdgeControl::LaneUsage::amActive, MSEdgeControl::LaneUsage::haveNeighbors, myActiveLanes, myChangedStateLanes, and myLanes.
Referenced by MSNet::simulationStep().
void MSEdgeControl::planMovements (SUMOTime t)
Compute safe velocities for all vehicles based on positions and speeds from the last time step. Also registers ApproachingVehicleInformation for all links.
This method goes through all active lanes calling their "planMovements" method.
See also
MSLane::planMovements
Definition at line 102 of file MSEdgeControl.cpp.
References myActiveLanes, and myLanes.
Referenced by MSNet::simulationStep().
Field Documentation
std::list<MSLane*> MSEdgeControl::myActiveLanes private
The list of active (not empty) lanes.
Definition at line 215 of file MSEdgeControl.h.
Referenced by changeLanes(), detectCollisions(), executeMovements(), patchActiveLanes(), and planMovements().
std::set<MSLane*, Named::ComparatorIdLess> MSEdgeControl::myChangedStateLanes private
Lanes which changed the state without informing the control.
Definition at line 221 of file MSEdgeControl.h.
Referenced by gotActive(), and patchActiveLanes().
MSEdgeVector MSEdgeControl::myEdges private
Loaded edges.
Definition at line 206 of file MSEdgeControl.h.
Referenced by getEdgeNames(), getEdges(), and MSEdgeControl().
LaneUsageVector MSEdgeControl::myLanes private
Information about lanes' number of vehicles and neighbors.
Definition at line 212 of file MSEdgeControl.h.
Referenced by changeLanes(), executeMovements(), MSEdgeControl(), patchActiveLanes(), and planMovements().
std::vector<SUMOTime> MSEdgeControl::myLastLaneChange private
The list of active (not empty) lanes.
Definition at line 224 of file MSEdgeControl.h.
Referenced by changeLanes(), and MSEdgeControl().
std::vector<MSLane*> MSEdgeControl::myWithVehicles2Integrate private
A storage for lanes which shall be integrated because vehicles have moved onto them.
Definition at line 218 of file MSEdgeControl.h.
Referenced by executeMovements().
The documentation for this class was generated from the following files:
MSEdgeControl.h
MSEdgeControl.cpp