SUMO - Simulation of Urban MObility: NIVissimConnectionCluster::same_direction_sorter Class Reference
NIVissimConnectionCluster::same_direction_sorter Class Reference
Public Member Functions
int operator() (NIVissimConnection *c1, NIVissimConnection *c2) const
comparing operation
same_direction_sorter (SUMOReal angle)
constructor
Private Attributes
SUMOReal myAngle
Detailed Description
Definition at line 131 of file NIVissimConnectionCluster.h.
Constructor & Destructor Documentation
NIVissimConnectionCluster::same_direction_sorter::same_direction_sorter (SUMOReal angle) inline explicit
constructor
Definition at line 137 of file NIVissimConnectionCluster.h.
Member Function Documentation
int NIVissimConnectionCluster::same_direction_sorter::operator() (NIVissimConnection * c1, NIVissimConnection * c2) const inline
comparing operation
Definition at line 142 of file NIVissimConnectionCluster.h.
References NIVissimConnectionCluster::NodeSubCluster::add(), GeomHelper::angleDiff(), PositionVector::beginEndAngle(), NIVissimConnectionCluster::extendByToTreatAsSame(), NIVissimConnectionCluster::getDisturbanceParticipators(), NIVissimAbstractEdge::getGeometry(), NIVissimConnectionCluster::isWeakDistrictConnRealisation(), NIVissimConnectionCluster::joinable(), NIVissimConnectionCluster::liesOnSameEdgesEnd(), NIVissimConnectionCluster::recheckEdges(), NIVissimConnectionCluster::recomputeBoundary(), NIVissimConnectionCluster::removeConnections(), and SUMOReal.
Field Documentation
SUMOReal NIVissimConnectionCluster::same_direction_sorter::myAngle private
Definition at line 133 of file NIVissimConnectionCluster.h.
The documentation for this class was generated from the following file:
NIVissimConnectionCluster.h