SUMO - Simulation of Urban MObility: AGStreet Class Reference
AGStreet Class Reference
A model of the street in the city.
#include <AGStreet.h>
Data Structures
class Builder
Public Types
enum EdgeFunc {
ET_NORMAL, ET_DISTRICT, ET_SOURCE, ET_SINK,
ET_WALKINGAREA, ET_CROSSING, ET_INTERNAL
}
Possible functions of edges.
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
AGStreet (const std::string &id, RONode *from, RONode *to, int index, const int priority)
bool allows (const SUMOVehicleClass vclass) const
Returns whether the given vehicle class is allowed on this street.
SUMOReal getDistanceTo (const ROEdge *other) const
optimistic distance heuristic for use in routing
const RONode * getFromJunction () const
const std::string & getID () const
Returns the id.
const std::vector< ROLane * > & getLanes () const
Returns this edge's lanes.
SUMOReal getPopulation () const
Provides the number of persons living in this street.
int getPriority () const
get edge priority (road class)
const RONode * getToJunction () const
SUMOReal getWorkplaceNumber () const
Provides the number of work places in this street.
void print () const
Prints a summary of the properties of this street to standard output.
void setID (const std::string &newID)
resets the id
void setPopulation (const SUMOReal pop)
Modifies the number of persons living in this street.
void setWorkplaceNumber (const SUMOReal work)
Modifies the number of work places in this street.
Set-up methods
virtual void addLane (ROLane *lane)
Adds a lane to the edge while loading.
virtual void addSuccessor (ROEdge *s, std::string dir="")
Adds information about a connected edge.
void setFunc (EdgeFunc func)
Sets the function of the edge.
void setRestrictions (const std::map< SUMOVehicleClass, SUMOReal > *restrictions)
Sets the vehicle class specific speed limits of the edge.
bool isInternal () const
return whether this edge is an internal edge
bool isCrossing () const
return whether this edge is a pedestrian crossing
bool isWalkingArea () const
return whether this edge is walking area
void buildTimeLines (const std::string &measure, const bool boundariesOverride)
Builds the internal representation of the travel time/effort.
Getter methods
EdgeFunc getFunc () const
Returns the function of the edge.
SUMOReal getLength () const
Returns the length of the edge.
int getNumericalID () const
Returns the index (numeric id) of the edge.
SUMOReal getSpeed () const
Returns the speed allowed on this edge.
int getLaneNo () const
Returns the number of lanes this edge has.
bool isConnectedTo (const ROEdge *const e, const ROVehicle *const vehicle) const
returns the information whether this edge is directly connected to the given
bool prohibits (const ROVehicle *const vehicle) const
Returns whether this edge prohibits the given vehicle to pass it.
SVCPermissions getPermissions () const
bool allFollowersProhibit (const ROVehicle *const vehicle) const
Returns whether this edge succeeding edges prohibit the given vehicle to pass them.
Static Public Member Functions
static int dictSize ()
Returns the number of edges.
static const ROEdgeVector & getAllEdges ()
Returns all ROEdges.
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
static void setGlobalOptions (const bool interpolate)
Protected Member Functions
bool getStoredEffort (SUMOReal time, SUMOReal &ret) const
Retrieves the stored effort.
Protected Attributes
ROEdgeVector myApproachingEdges
List of edges that approached this edge.
std::map< SUMOVehicleClass, ROEdgeVector > myClassesSuccessorMap
The successors available for a given vClass.
SVCPermissions myCombinedPermissions
The list of allowed vehicle classes combined across lanes.
ValueTimeLine< SUMOReal > myEfforts
Container storing passing time varying over time for the edge.
ROEdgeVector myFollowingEdges
List of edges that may be approached from this edge.
RONode * myFromJunction
the junctions for this edge
EdgeFunc myFunc
The function of the edge.
std::string myID
The name of the object.
const int myIndex
The index (numeric id) of the edge.
std::vector< ROLane * > myLanes
This edge's lanes.
SUMOReal myLength
The length of the edge.
const int myPriority
The edge priority (road class)
const std::map< SUMOVehicleClass, SUMOReal > * myRestrictions
The vClass speed restrictions for this edge.
SUMOReal mySpeed
The maximum speed allowed on this edge.
RONode * myToJunction
ValueTimeLine< SUMOReal > myTravelTimes
Container storing passing time varying over time for the edge.
bool myUsingETimeLine
Information whether the time line shall be used instead of the length value.
bool myUsingTTTimeLine
Information whether the time line shall be used instead of the length value.
Static Protected Attributes
static ROEdgeVector myEdges
static bool myHaveEWarned = false
Information whether the edge has reported missing weights.
static bool myHaveTTWarned = false
Information whether the edge has reported missing weights.
static bool myInterpolate = false
Information whether to interpolate at interval boundaries.
Private Attributes
SUMOReal myNumWorkplaces
SUMOReal myPopulation
Methods for getting/setting travel time and cost information
void addEffort (SUMOReal value, SUMOReal timeBegin, SUMOReal timeEnd)
Adds a weight value.
void addTravelTime (SUMOReal value, SUMOReal timeBegin, SUMOReal timeEnd)
Adds a travel time value.
int getNumSuccessors () const
Returns the number of edges this edge is connected to.
const ROEdgeVector & getSuccessors () const
Returns the following edges.
const ROEdgeVector & getSuccessors (SUMOVehicleClass vClass) const
Returns the following edges, restricted by vClass.
int getNumPredecessors () const
Returns the number of edges connected to this edge.
const ROEdgeVector & getPredecessors () const
Returns the edge at the given position from the list of incoming edges.
SUMOReal getEffort (const ROVehicle *const veh, SUMOReal time) const
Returns the effort for this edge.
bool hasLoadedTravelTime (SUMOReal time) const
Returns whether a travel time for this edge was loaded.
SUMOReal getTravelTime (const ROVehicle *const veh, SUMOReal time) const
Returns the travel time for this edge.
SUMOReal getMinimumTravelTime (const ROVehicle *const veh) const
Returns a lower bound for the travel time on this edge without using any stored timeLine.
static SUMOReal getEffortStatic (const ROEdge *const edge, const ROVehicle *const veh, SUMOReal time)
Returns the effort for the given edge.
static SUMOReal getTravelTimeStatic (const ROEdge *const edge, const ROVehicle *const veh, SUMOReal time)
Returns the travel time for the given edge.
template<PollutantsInterface::EmissionType ET>
static SUMOReal getEmissionEffort (const ROEdge *const edge, const ROVehicle *const veh, SUMOReal time)
static SUMOReal getNoiseEffort (const ROEdge *const edge, const ROVehicle *const veh, SUMOReal time)
Detailed Description
A model of the street in the city.
AGStreet represents a street in the city. It contains all model relevant properties and is associated with a ROEdge of the routing network.
Definition at line 60 of file AGStreet.h.
Member Enumeration Documentation
enum ROEdge::EdgeFunc inherited
Possible functions of edges.
Enumerator
ET_NORMAL
A normal edge.
ET_DISTRICT
An edge representing a whole district.
ET_SOURCE
An edge where vehicles are inserted at (no vehicle may come from back)
ET_SINK
An edge where vehicles disappear (no vehicle may leave this edge)
ET_WALKINGAREA
An internal edge which models walking areas for pedestrians.
ET_CROSSING
An internal edge which models pedestrian crossings.
ET_INTERNAL
An internal edge which models vehicles driving across a junction. This is currently not used for routing.
Definition at line 83 of file ROEdge.h.
Constructor & Destructor Documentation
AGStreet::AGStreet (const std::string & id, RONode * from, RONode * to, int index, const int priority)
Definition at line 44 of file AGStreet.cpp.
Referenced by AGStreet::Builder::buildEdge().
Member Function Documentation
void ROEdge::addEffort (SUMOReal value, SUMOReal timeBegin, SUMOReal timeEnd) inherited
Adds a weight value.
Parameters
[in] value The value to add
[in] timeBegin The begin time of the interval the given value is valid for [s]
[in] timeEnd The end time of the interval the given value is valid for [s]
Definition at line 118 of file ROEdge.cpp.
References ValueTimeLine< T >::add(), ROEdge::myEfforts, and ROEdge::myUsingETimeLine.
Referenced by ROLoader::EdgeFloatTimeLineRetriever_EdgeWeight::addEdgeWeight(), and ROEdge::getPermissions().
void ROEdge::addLane (ROLane * lane) virtual inherited
Adds a lane to the edge while loading.
The lane's length is adapted. Additionally, the information about allowed/disallowed vehicle classes is patched using the information stored in the lane.
Parameters
[in] lane The lane to add
Todo:
What about vehicle-type aware connections?
Definition at line 96 of file ROEdge.cpp.
References ROLane::getLength(), ROLane::getPermissions(), ROLane::getSpeed(), ROEdge::myCombinedPermissions, ROEdge::myLanes, ROEdge::myLength, ROEdge::mySpeed, and SUMOReal.
Referenced by RONetHandler::parseLane().
void ROEdge::addSuccessor (ROEdge * s, std::string dir = "") virtual inherited
Adds information about a connected edge.
The edge s is added to "myFollowingEdges" and this edge is added as predecessor to s.
Parameters
[in] s The edge to add
Todo:
What about vehicle-type aware connections?
Reimplemented in ROMAEdge, and ROJTREdge.
Definition at line 109 of file ROEdge.cpp.
References ROEdge::myApproachingEdges, and ROEdge::myFollowingEdges.
Referenced by RONet::addDistrictEdge(), ROJTREdge::addSuccessor(), and ROMAEdge::addSuccessor().
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
void ROEdge::addTravelTime (SUMOReal value, SUMOReal timeBegin, SUMOReal timeEnd) inherited
Adds a travel time value.
Parameters
[in] value The value to add
[in] timeBegin The begin time of the interval the given value is valid for [s]
[in] timeEnd The end time of the interval the given value is valid for [s]
Definition at line 125 of file ROEdge.cpp.
References ValueTimeLine< T >::add(), ROEdge::myTravelTimes, ROEdge::myUsingTTTimeLine, and SUMOReal.
Referenced by ROLoader::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight(), ROEdge::getPermissions(), ROMAAssignments::incremental(), and ROMAAssignments::sue().
bool ROEdge::allFollowersProhibit (const ROVehicle *const vehicle) const inherited
Returns whether this edge succeeding edges prohibit the given vehicle to pass them.
Parameters
[in] vehicle The vehicle for which the information has to be returned
Returns
Whether the vehicle may continue its route on any of the following edges
Definition at line 271 of file ROEdge.cpp.
References ROEdge::myFollowingEdges.
Referenced by ROJTREdge::chooseNext(), and ROEdge::getPermissions().
bool AGStreet::allows (const SUMOVehicleClass vclass) const
Returns whether the given vehicle class is allowed on this street.
Parameters
[in] vclass the class (passenger or bus) in question
Returns
whether it is allowed on any of the lanes
Definition at line 80 of file AGStreet.cpp.
References ROEdge::getPermissions().
Referenced by AGStreet::Builder::buildEdge(), and AGWorkAndSchool::carsToTrips().
void ROEdge::buildTimeLines (const std::string & measure, const bool boundariesOverride) inherited
Builds the internal representation of the travel time/effort.
Should be called after weights / travel times have been loaded.
In the case "weight-attribute" is one of "CO", "CO2", "HC", "NOx", "PMx", "fuel", or "electricity" the proper value (departs/s) is computed and multiplied with the travel time.
Parameters
[in] measure The name of the measure to use.
Definition at line 237 of file ROEdge.cpp.
References PollutantsInterface::CO, PollutantsInterface::CO2, PollutantsInterface::compute(), PollutantsInterface::ELEC, ValueTimeLine< T >::fillGaps(), PollutantsInterface::FUEL, PollutantsInterface::getClassByName(), PollutantsInterface::HC, ROEdge::myEfforts, ROEdge::myLength, ROEdge::mySpeed, ROEdge::myTravelTimes, ROEdge::myUsingETimeLine, ROEdge::myUsingTTTimeLine, PollutantsInterface::NO_X, PollutantsInterface::PM_X, and SUMOReal.
Referenced by ROEdge::isWalkingArea().
static int ROEdge::dictSize () inline static inherited
Returns the number of edges.
Definition at line 409 of file ROEdge.h.
References ROEdge::myEdges.
const ROEdgeVector & ROEdge::getAllEdges () static inherited
Returns all ROEdges.
Definition at line 282 of file ROEdge.cpp.
References ROEdge::myEdges.
Referenced by computeAllPairs(), computeRoutes(), and ROEdge::getEmissionEffort().
SUMOReal ROEdge::getDistanceTo (const ROEdge * other) const inherited
optimistic distance heuristic for use in routing
Definition at line 142 of file ROEdge.cpp.
References Position::distanceTo2D(), ROEdge::getFromJunction(), RONode::getPosition(), and ROEdge::getToJunction().
Referenced by ROEdge::getEmissionEffort().
SUMOReal ROEdge::getEffort (const ROVehicle *const veh, SUMOReal time) const inherited
Returns the effort for this edge.
Parameters
[in] veh The vehicle for which the effort on this edge shall be retrieved
[in] time The tim for which the effort shall be returned [s]
Returns
The effort needed by the given vehicle to pass the edge at the given time
Todo:
Recheck whether the vehicle's maximum speed is considered
Definition at line 132 of file ROEdge.cpp.
References ROEdge::getStoredEffort(), RORoutable::getType(), SUMOVTypeParameter::maxSpeed, MIN2(), ROEdge::myLength, ROEdge::mySpeed, and SUMOReal.
Referenced by ROEdge::getEffortStatic(), ROMAAssignments::getPenalizedEffort(), and ROEdge::getPredecessors().
static SUMOReal ROEdge::getEffortStatic (const ROEdge *const edge, const ROVehicle *const veh, SUMOReal time) inline static inherited
Returns the effort for the given edge.
Parameters
[in] edge The edge for which the effort shall be retrieved
[in] veh The vehicle for which the effort on this edge shall be retrieved
[in] time The time for which the effort shall be returned [s]
Returns
The effort needed by the given vehicle to pass the edge at the given time
Todo:
Recheck whether the vehicle's maximum speed is considered
Definition at line 357 of file ROEdge.h.
References ROEdge::getEffort().
template<PollutantsInterface::EmissionType ET> static SUMOReal ROEdge::getEmissionEffort (const ROEdge *const edge, const ROVehicle *const veh, SUMOReal time) inline static inherited
Definition at line 385 of file ROEdge.h.
References PollutantsInterface::computeDefault(), SUMOVTypeParameter::emissionClass, ROEdge::getAllEdges(), SUMOVTypeParameter::getCFParam(), SUMOVTypeParameter::getDefaultAccel(), SUMOVTypeParameter::getDefaultImperfection(), ROEdge::getDistanceTo(), ROEdge::getNoiseEffort(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), RORoutable::getType(), SUMOVTypeParameter::maxSpeed, MIN2(), ROEdge::mySpeed, SUMO_ATTR_ACCEL, SUMO_ATTR_SIGMA, SUMOReal, and SUMOVTypeParameter::vehicleClass.
const RONode* ROEdge::getFromJunction () const inline inherited
Definition at line 422 of file ROEdge.h.
References ROEdge::myFromJunction.
Referenced by RODFNet::buildApproachList(), AGPosition::compute2dPosition(), and ROEdge::getDistanceTo().
EdgeFunc ROEdge::getFunc () const inline inherited
Returns the function of the edge.
Returns
This edge's basic function
See also
EdgeFunc
Definition at line 190 of file ROEdge.h.
References ROEdge::myFunc.
Referenced by RONet::addEdge(), ROMAAssignments::capacityConstraintFunction(), ROJTRRouter::compute(), ROMAAssignments::getCapacity(), ROEdge::getNumPredecessors(), ROEdge::getNumSuccessors(), and writeInterval().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciBusOrContainerStop(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNEConnectorFrame::buildIinternalLanes(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), NLDetectorBuilder::convUncontE2PosLength(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSVehicle::getBackPosition(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), GNEEdge::getDest(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), MSE2Collector::getEstimateQueueLength(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), GNEEdge::getSource(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSE2Collector::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_SL2015::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_LC2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_ArealDetector::processGet(), TraCIServerAPI_Lane::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), MSBaseVehicle::reroute(), MSLane::resetPartialOccupation(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), MSLane::saveState(), MSDevice_Battery::setAirDragCoefficient(), NBNodeCont::setAsTLControlled(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), MSDevice_Battery::setConstantPowerIntake(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), MSDevice_Battery::setFrontSurfaceArea(), MSDevice_Battery::setInternalMomentOfInertia(), GNEJunction::setLogicValid(), MSDevice_Battery::setMass(), MSDevice_Battery::setMaximumBatteryCapacity(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSDevice_Battery::setPropulsionEfficiency(), MSDevice_Battery::setRadialDragCoefficient(), MSDevice_Battery::setRecuperationEfficiency(), MSLink::setRequestInformation(), MSDevice_Battery::setRollDragCoefficient(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), operator<<(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
int ROEdge::getLaneNo () const inline inherited
Returns the number of lanes this edge has.
Returns
This edge's number of lanes
Definition at line 221 of file ROEdge.h.
References ROEdge::isConnectedTo(), and ROEdge::myLanes.
Referenced by ROMAAssignments::capacityConstraintFunction(), ROMAAssignments::getCapacity(), and RODFDetectorHandler::myStartElement().
const std::vector<ROLane*>& ROEdge::getLanes () const inline inherited
Returns this edge's lanes.
Returns
This edge's lanes
Definition at line 435 of file ROEdge.h.
References ROEdge::getStoredEffort(), ROEdge::myLanes, and SUMOReal.
Referenced by RONetHandler::parseConnection().
SUMOReal ROEdge::getLength () const inline inherited
Returns the length of the edge.
Returns
This edge's length
Definition at line 198 of file ROEdge.h.
References ROEdge::myLength.
Referenced by RORouteHandler::addStop(), RODFNet::buildRoutes(), ROMAAssignments::capacityConstraintFunction(), AGPosition::compute2dPosition(), RODFNet::getAbsPos(), getTravelTime(), RONetHandler::parseStoppingPlace(), AGActivityGenHandler::parseStreets(), print(), AGPosition::print(), AGPosition::randomPositionInStreet(), and writeInterval().
SUMOReal ROEdge::getMinimumTravelTime (const ROVehicle *const veh) const inline inherited
Returns a lower bound for the travel time on this edge without using any stored timeLine.
Parameters
[in] veh The vehicle for which the effort on this edge shall be retrieved
[in] time The time for which the effort shall be returned [s]
Definition at line 379 of file ROEdge.h.
References ROVehicle::getChosenSpeedFactor(), RORoutable::getType(), SUMOVTypeParameter::maxSpeed, MIN2(), ROEdge::myLength, and ROEdge::mySpeed.
Referenced by ROEdge::getTravelTime().
SUMOReal ROEdge::getNoiseEffort (const ROEdge *const edge, const ROVehicle *const veh, SUMOReal time) static inherited
Definition at line 183 of file ROEdge.cpp.
References HelpersHarmonoise::computeNoise(), SUMOVTypeParameter::emissionClass, ROEdge::getStoredEffort(), RORoutable::getType(), SUMOVTypeParameter::maxSpeed, MIN2(), ROEdge::mySpeed, and SUMOReal.
Referenced by computeRoutes(), and ROEdge::getEmissionEffort().
int ROEdge::getNumericalID () const inline inherited
Returns the index (numeric id) of the edge.
Returns
This edge's numerical id
Definition at line 205 of file ROEdge.h.
References ROEdge::myIndex.
Referenced by RONet::createBulkRouteRequests().
int ROEdge::getNumPredecessors () const inherited
Returns the number of edges connected to this edge.
If this edge's type is set to "source", 0 is returned, otherwise the number of edges stored in "myApproachingEdges".
Returns
The number of edges reaching into this edge
Definition at line 228 of file ROEdge.cpp.
References ROEdge::ET_SOURCE, ROEdge::getFunc(), and ROEdge::myApproachingEdges.
Referenced by ROEdge::getSuccessors(), and RORouteHandler::parseFromViaTo().
int ROEdge::getNumSuccessors () const inherited
Returns the number of edges this edge is connected to.
If this edge's type is set to "sink", 0 is returned, otherwise the number of edges stored in "myFollowingEdges".
Returns
The number of edges following this edge
Definition at line 219 of file ROEdge.cpp.
References ROEdge::ET_SINK, ROEdge::getFunc(), and ROEdge::myFollowingEdges.
Referenced by RODFDetector::computeSplitProbabilities(), ROEdge::getPermissions(), and RORouteHandler::parseFromViaTo().
SVCPermissions ROEdge::getPermissions () const inline inherited
Definition at line 244 of file ROEdge.h.
References ROEdge::addEffort(), ROEdge::addTravelTime(), ROEdge::allFollowersProhibit(), ROEdge::getNumSuccessors(), ROEdge::myCombinedPermissions, and SUMOReal.
Referenced by allows().
SUMOReal AGStreet::getPopulation () const
Provides the number of persons living in this street.
Returns
the number of inhabitants
Definition at line 56 of file AGStreet.cpp.
References myPopulation.
Referenced by AGStreet::Builder::buildEdge().
const ROEdgeVector& ROEdge::getPredecessors () const inline inherited
Returns the edge at the given position from the list of incoming edges.
Parameters
[in] pos The position of the list within the list of incoming
Returns
The incoming edge, stored at position pos
Definition at line 317 of file ROEdge.h.
References ROEdge::getEffort(), ROEdge::getTravelTime(), ROEdge::hasLoadedTravelTime(), ROEdge::myApproachingEdges, and SUMOReal.
Referenced by RODFDetector::computeSplitProbabilities().
int ROEdge::getPriority () const inline inherited
get edge priority (road class)
Definition at line 418 of file ROEdge.h.
References ROEdge::myPriority.
Referenced by ROMAAssignments::capacityConstraintFunction(), and ROMAAssignments::getCapacity().
SUMOReal ROEdge::getSpeed () const inline inherited
Returns the speed allowed on this edge.
Returns
The speed allowed on this edge
Definition at line 213 of file ROEdge.h.
References ROEdge::mySpeed.
Referenced by RODFNet::buildEdgeFlowMap(), RODFNet::buildRoutes(), ROMAAssignments::capacityConstraintFunction(), RODFNet::computeRoutesFor(), ROMAAssignments::getCapacity(), getTravelTime(), RODFNet::isDestination(), RODFNet::isFalseSource(), and RODFNet::isSource().
bool ROEdge::getStoredEffort (SUMOReal time, SUMOReal & ret) const protected inherited
Retrieves the stored effort.
Parameters
[in] veh The vehicle for which the effort on this edge shall be retrieved
[in] time The tim for which the effort shall be returned
Returns
Whether the effort is given
Definition at line 194 of file ROEdge.cpp.
References ValueTimeLine< T >::describesTime(), ValueTimeLine< T >::getSplitTime(), ValueTimeLine< T >::getValue(), ROEdge::myEfforts, ROEdge::myHaveEWarned, Named::myID, ROEdge::myInterpolate, ROEdge::myTravelTimes, ROEdge::myUsingETimeLine, SUMOReal, toString(), and WRITE_WARNING.
Referenced by ROEdge::getEffort(), ROEdge::getEmissionEffort(), ROEdge::getLanes(), and ROEdge::getNoiseEffort().
const ROEdgeVector& ROEdge::getSuccessors () const inline inherited
Returns the following edges.
Definition at line 291 of file ROEdge.h.
References ROEdge::getNumPredecessors(), and ROEdge::myFollowingEdges.
Referenced by RODFNet::buildApproachList(), and ROEdge::isConnectedTo().
const ROEdgeVector & ROEdge::getSuccessors (SUMOVehicleClass vClass) const inherited
Returns the following edges, restricted by vClass.
Parameters
[in] vClass The vClass for which to restrict the successors
Returns
The eligible following edges
Definition at line 288 of file ROEdge.cpp.
References ROEdge::ET_DISTRICT, ROLane::getEdge(), RONet::getInstance(), ROLane::getOutgoingLanes(), ROLane::getPermissions(), ROEdge::myClassesSuccessorMap, ROEdge::myFollowingEdges, ROEdge::myFunc, ROEdge::myLanes, and SVC_IGNORING.
const RONode* ROEdge::getToJunction () const inline inherited
Definition at line 426 of file ROEdge.h.
References ROEdge::myToJunction.
Referenced by RODFNet::buildApproachList(), AGPosition::compute2dPosition(), and ROEdge::getDistanceTo().
SUMOReal ROEdge::getTravelTime (const ROVehicle *const veh, SUMOReal time) const inherited
Returns the travel time for this edge.
Parameters
[in] veh The vehicle for which the travel time on this edge shall be retrieved
[in] time The time for which the travel time shall be returned [s]
Returns
The travel time needed by the given vehicle to pass the edge at the given time
Definition at line 159 of file ROEdge.cpp.
References ValueTimeLine< T >::describesTime(), ROEdge::getMinimumTravelTime(), ValueTimeLine< T >::getSplitTime(), RORoutable::getType(), ValueTimeLine< T >::getValue(), MAX2(), SUMOVTypeParameter::maxSpeed, MIN2(), ROEdge::myHaveTTWarned, Named::myID, ROEdge::myInterpolate, ROEdge::myLength, ROEdge::mySpeed, ROEdge::myTravelTimes, ROEdge::myUsingTTTimeLine, SUMOVTypeParameter::speedFactor, split(), SUMOReal, toString(), and WRITE_WARNING.
Referenced by ROJTRRouter::compute(), ROEdge::getEmissionEffort(), ROMAAssignments::getPenalizedTT(), ROEdge::getPredecessors(), ROMAAssignments::getTravelTime(), ROEdge::getTravelTimeStatic(), ROMAAssignments::incremental(), and writeInterval().
static SUMOReal ROEdge::getTravelTimeStatic (const ROEdge *const edge, const ROVehicle *const veh, SUMOReal time) inline static inherited
Returns the travel time for the given edge.
Parameters
[in] edge The edge for which the travel time shall be retrieved
[in] veh The vehicle for which the travel time on this edge shall be retrieved
[in] time The time for which the travel time shall be returned [s]
Returns
The traveltime needed by the given vehicle to pass the edge at the given time
Definition at line 369 of file ROEdge.h.
References ROEdge::getTravelTime().
Referenced by computeRoutes().
SUMOReal AGStreet::getWorkplaceNumber () const
Provides the number of work places in this street.
Returns
the number of work places
Definition at line 68 of file AGStreet.cpp.
References myNumWorkplaces.
Referenced by AGStreet::Builder::buildEdge().
bool ROEdge::hasLoadedTravelTime (SUMOReal time) const inherited
Returns whether a travel time for this edge was loaded.
Parameters
[in] time The time for which the travel time shall be returned [s]
Returns
whether a value was loaded
Definition at line 153 of file ROEdge.cpp.
References ValueTimeLine< T >::describesTime(), ROEdge::myTravelTimes, ROEdge::myUsingTTTimeLine, and SUMOReal.
Referenced by ROEdge::getPredecessors(), and ROMAAssignments::incremental().
bool ROEdge::isConnectedTo (const ROEdge *const e, const ROVehicle *const vehicle) const inherited
returns the information whether this edge is directly connected to the given
Parameters
[in] e The edge which may be connected
[in] vehicle The vehicle for which the connectivity is checked
Returns
Whether the given edge is a direct successor to this one
Definition at line 329 of file ROEdge.cpp.
References ROEdge::getSuccessors(), RORoutable::getVClass(), and SVC_IGNORING.
Referenced by ROEdge::getLaneNo().
bool ROEdge::isCrossing () const inline inherited
return whether this edge is a pedestrian crossing
Definition at line 160 of file ROEdge.h.
References ROEdge::ET_CROSSING, and ROEdge::myFunc.
bool ROEdge::isInternal () const inline inherited
return whether this edge is an internal edge
Definition at line 155 of file ROEdge.h.
References ROEdge::ET_INTERNAL, and ROEdge::myFunc.
bool ROEdge::isWalkingArea () const inline inherited
return whether this edge is walking area
Definition at line 165 of file ROEdge.h.
References ROEdge::buildTimeLines(), ROEdge::ET_WALKINGAREA, and ROEdge::myFunc.
void AGStreet::print () const
Prints a summary of the properties of this street to standard output.
Definition at line 50 of file AGStreet.cpp.
References Named::getID(), ROEdge::getLength(), myNumWorkplaces, myPopulation, and SUMOReal.
Referenced by AGStreet::Builder::buildEdge().
bool ROEdge::prohibits (const ROVehicle *const vehicle) const inline inherited
Returns whether this edge prohibits the given vehicle to pass it.
Parameters
[in] vehicle The vehicle for which the information has to be returned
Returns
Whether the vehicle must not enter this edge
Definition at line 239 of file ROEdge.h.
References RORoutable::getVClass(), and ROEdge::myCombinedPermissions.
Referenced by ROVehicle::addStop(), ROJTREdge::chooseNext(), and ROJTRRouter::compute().
void ROEdge::setFunc (EdgeFunc func) inline inherited
Sets the function of the edge.
Parameters
[in] func The new function for the edge
Definition at line 141 of file ROEdge.h.
References ROEdge::myFunc.
Referenced by RONet::addDistrict(), loadJTRDefinitions(), ROJTRTurnDefLoader::myStartElement(), and RONetHandler::parseEdge().
static void ROEdge::setGlobalOptions (const bool interpolate) inline static inherited
Definition at line 413 of file ROEdge.h.
References ROEdge::myInterpolate.
Referenced by initNet().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
void AGStreet::setPopulation (const SUMOReal pop)
Modifies the number of persons living in this street.
Parameters
[in] pop the new number of inhabitants
Definition at line 62 of file AGStreet.cpp.
References myPopulation, and SUMOReal.
Referenced by AGStreet::Builder::buildEdge(), and AGActivityGenHandler::parseStreets().
void ROEdge::setRestrictions (const std::map< SUMOVehicleClass, SUMOReal > * restrictions) inline inherited
Sets the vehicle class specific speed limits of the edge.
Parameters
[in] restrictions The restrictions for the edge
Definition at line 149 of file ROEdge.h.
References ROEdge::myRestrictions.
Referenced by RONetHandler::parseEdge().
void AGStreet::setWorkplaceNumber (const SUMOReal work)
Modifies the number of work places in this street.
Parameters
[in] work the new number of work places
Definition at line 74 of file AGStreet.cpp.
References myNumWorkplaces.
Referenced by AGStreet::Builder::buildEdge(), and AGActivityGenHandler::parseStreets().
Field Documentation
ROEdgeVector ROEdge::myApproachingEdges protected inherited
List of edges that approached this edge.
Definition at line 489 of file ROEdge.h.
Referenced by ROEdge::addSuccessor(), ROEdge::getNumPredecessors(), and ROEdge::getPredecessors().
std::map<SUMOVehicleClass, ROEdgeVector> ROEdge::myClassesSuccessorMap mutable protected inherited
The successors available for a given vClass.
Definition at line 507 of file ROEdge.h.
Referenced by ROEdge::getSuccessors().
SVCPermissions ROEdge::myCombinedPermissions protected inherited
The list of allowed vehicle classes combined across lanes.
Definition at line 501 of file ROEdge.h.
Referenced by ROEdge::addLane(), ROEdge::getPermissions(), ROEdge::prohibits(), and ROEdge::ROEdge().
ROEdgeVector ROEdge::myEdges static protected inherited
Definition at line 503 of file ROEdge.h.
Referenced by ROEdge::dictSize(), ROEdge::getAllEdges(), and ROEdge::ROEdge().
ValueTimeLine<SUMOReal> ROEdge::myEfforts mutable protected inherited
Container storing passing time varying over time for the edge.
Definition at line 473 of file ROEdge.h.
Referenced by ROEdge::addEffort(), ROEdge::buildTimeLines(), and ROEdge::getStoredEffort().
ROEdgeVector ROEdge::myFollowingEdges protected inherited
List of edges that may be approached from this edge.
Definition at line 486 of file ROEdge.h.
Referenced by ROEdge::addSuccessor(), ROEdge::allFollowersProhibit(), ROJTREdge::chooseNext(), ROEdge::getNumSuccessors(), ROEdge::getSuccessors(), and ROJTREdge::setTurnDefaults().
RONode* ROEdge::myFromJunction protected inherited
the junctions for this edge
Definition at line 451 of file ROEdge.h.
Referenced by ROEdge::getFromJunction().
EdgeFunc ROEdge::myFunc protected inherited
The function of the edge.
Definition at line 492 of file ROEdge.h.
Referenced by ROEdge::getFunc(), ROEdge::getSuccessors(), ROEdge::isCrossing(), ROEdge::isInternal(), ROEdge::isWalkingArea(), and ROEdge::setFunc().
bool ROEdge::myHaveEWarned = false static protected inherited
Information whether the edge has reported missing weights.
Definition at line 481 of file ROEdge.h.
Referenced by ROEdge::getStoredEffort().
bool ROEdge::myHaveTTWarned = false static protected inherited
Information whether the edge has reported missing weights.
Definition at line 483 of file ROEdge.h.
Referenced by ROEdge::getTravelTime().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
const int ROEdge::myIndex protected inherited
The index (numeric id) of the edge.
Definition at line 455 of file ROEdge.h.
Referenced by ROEdge::getNumericalID().
bool ROEdge::myInterpolate = false static protected inherited
Information whether to interpolate at interval boundaries.
Definition at line 478 of file ROEdge.h.
Referenced by ROEdge::getStoredEffort(), ROEdge::getTravelTime(), and ROEdge::setGlobalOptions().
std::vector<ROLane*> ROEdge::myLanes protected inherited
This edge's lanes.
Definition at line 498 of file ROEdge.h.
Referenced by ROEdge::addLane(), ROEdge::getLaneNo(), ROEdge::getLanes(), ROEdge::getSuccessors(), and ROEdge::~ROEdge().
SUMOReal ROEdge::myLength protected inherited
The length of the edge.
Definition at line 464 of file ROEdge.h.
Referenced by ROEdge::addLane(), ROEdge::buildTimeLines(), ROEdge::getEffort(), ROEdge::getLength(), ROEdge::getMinimumTravelTime(), and ROEdge::getTravelTime().
SUMOReal AGStreet::myNumWorkplaces private
Definition at line 117 of file AGStreet.h.
Referenced by getWorkplaceNumber(), print(), and setWorkplaceNumber().
SUMOReal AGStreet::myPopulation private
Definition at line 116 of file AGStreet.h.
Referenced by getPopulation(), print(), and setPopulation().
const int ROEdge::myPriority protected inherited
The edge priority (road class)
Definition at line 458 of file ROEdge.h.
Referenced by ROEdge::getPriority().
const std::map<SUMOVehicleClass, SUMOReal>* ROEdge::myRestrictions protected inherited
The vClass speed restrictions for this edge.
Definition at line 495 of file ROEdge.h.
Referenced by ROEdge::setRestrictions().
SUMOReal ROEdge::mySpeed protected inherited
The maximum speed allowed on this edge.
Definition at line 461 of file ROEdge.h.
Referenced by ROEdge::addLane(), ROEdge::buildTimeLines(), ROEdge::getEffort(), ROEdge::getEmissionEffort(), ROEdge::getMinimumTravelTime(), ROEdge::getNoiseEffort(), ROEdge::getSpeed(), and ROEdge::getTravelTime().
RONode* ROEdge::myToJunction protected inherited
Definition at line 452 of file ROEdge.h.
Referenced by ROEdge::getToJunction().
ValueTimeLine<SUMOReal> ROEdge::myTravelTimes mutable protected inherited
Container storing passing time varying over time for the edge.
Definition at line 468 of file ROEdge.h.
Referenced by ROEdge::addTravelTime(), ROEdge::buildTimeLines(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), and ROEdge::hasLoadedTravelTime().
bool ROEdge::myUsingETimeLine protected inherited
Information whether the time line shall be used instead of the length value.
Definition at line 475 of file ROEdge.h.
Referenced by ROEdge::addEffort(), ROEdge::buildTimeLines(), and ROEdge::getStoredEffort().
bool ROEdge::myUsingTTTimeLine protected inherited
Information whether the time line shall be used instead of the length value.
Definition at line 470 of file ROEdge.h.
Referenced by ROEdge::addTravelTime(), ROEdge::buildTimeLines(), ROEdge::getTravelTime(), and ROEdge::hasLoadedTravelTime().
The documentation for this class was generated from the following files:
AGStreet.h
AGStreet.cpp