SUMO - Simulation of Urban MObility: NBTrafficLightLogic::PhaseDefinition Class Reference
NBTrafficLightLogic::PhaseDefinition Class Reference
The definition of a single phase of the logic.
#include <NBTrafficLightLogic.h>
Public Member Functions
bool operator!= (const PhaseDefinition &pd) const
Comparison operator.
PhaseDefinition (SUMOTime durationArg, const std::string &stateArg)
Constructor.
~PhaseDefinition ()
Destructor.
Data Fields
SUMOTime duration
The duration of the phase in s.
std::string state
The state definition.
Detailed Description
The definition of a single phase of the logic.
Definition at line 65 of file NBTrafficLightLogic.h.
Constructor & Destructor Documentation
NBTrafficLightLogic::PhaseDefinition::PhaseDefinition (SUMOTime durationArg, const std::string & stateArg) inline
Constructor.
Parameters
[in] durationArg The duration of the phase
[in] stateArg Signals per link
Definition at line 77 of file NBTrafficLightLogic.h.
NBTrafficLightLogic::PhaseDefinition::~PhaseDefinition () inline
Destructor.
Definition at line 81 of file NBTrafficLightLogic.h.
Member Function Documentation
bool NBTrafficLightLogic::PhaseDefinition::operator!= (const PhaseDefinition & pd) const inline
Comparison operator.
Parameters
[in] pd A second phase
Returns
Whether this and the given phases are same
Definition at line 87 of file NBTrafficLightLogic.h.
References NBTrafficLightLogic::addStep(), NBTrafficLightLogic::closeBuilding(), NBTrafficLightLogic::deletePhase(), duration, NBTrafficLightLogic::getDuration(), NBTrafficLightLogic::NBTrafficLightLogic(), NBTrafficLightLogic::resetPhases(), NBTrafficLightLogic::setPhaseDuration(), NBTrafficLightLogic::setPhaseState(), state, TLTYPE_STATIC, and NBTrafficLightLogic::~NBTrafficLightLogic().
Field Documentation
SUMOTime NBTrafficLightLogic::PhaseDefinition::duration
The duration of the phase in s.
Definition at line 68 of file NBTrafficLightLogic.h.
Referenced by operator!=().
std::string NBTrafficLightLogic::PhaseDefinition::state
The state definition.
Definition at line 71 of file NBTrafficLightLogic.h.
Referenced by GNETLSEditorFrame::onCmdPhaseSwitch(), and operator!=().
The documentation for this class was generated from the following file:
NBTrafficLightLogic.h