SUMO - Simulation of Urban MObility: PCTypeMap Class Reference
PCTypeMap Class Reference
A storage for type mappings.
#include <PCTypeMap.h>
Data Structures
struct TypeDef
A single definition of values that shall be used for a given type.
Public Member Functions
bool add (const std::string &id, const std::string &newid, const std::string &color, const std::string &prefix, SUMOReal layer, bool discard, bool allowFill)
Adds a type definition.
const TypeDef & get (const std::string &id)
Returns a type definition.
const TypeDef & getDefault ()
get the default type according to the given options
bool has (const std::string &id)
Returns the information whether the named type is known.
PCTypeMap (const OptionsCont &oc)
Constructor. The default type is constructed based on the given options.
~PCTypeMap ()
Destructor.
Protected Attributes
TypeDef myDefaultType
std::map< std::string, TypeDef > myTypes
A map of type names to type definitions.
Detailed Description
A storage for type mappings.
This class holds the mappings between names of read polygon/poi types and the values (color, new type name etc.) that shall be assigned to them.
Definition at line 52 of file PCTypeMap.h.
Constructor & Destructor Documentation
PCTypeMap::PCTypeMap (const OptionsCont & oc)
Constructor. The default type is constructed based on the given options.
Definition at line 46 of file PCTypeMap.cpp.
References PCTypeMap::TypeDef::allowFill, PCTypeMap::TypeDef::color, PCTypeMap::TypeDef::discard, OptionsCont::getBool(), OptionsCont::getFloat(), OptionsCont::getString(), PCTypeMap::TypeDef::id, PCTypeMap::TypeDef::layer, myDefaultType, RGBColor::parseColor(), and PCTypeMap::TypeDef::prefix.
PCTypeMap::~PCTypeMap ()
Destructor.
Definition at line 56 of file PCTypeMap.cpp.
Member Function Documentation
bool PCTypeMap::add (const std::string & id, const std::string & newid, const std::string & color, const std::string & prefix, SUMOReal layer, bool discard, bool allowFill)
Adds a type definition.
Parameters
[in] id The original id of the type
[in] newid The new id (name) of the type
[in] color The color to set for imported objects of this type
[in] prefix The prefix to prepend to the read names of this type's objects
[in] layer The layer number to set for this type's objects
[in] discard Whether objects of this type shall be discarded
[in] allowFill Whether objects of this type may be filled
Returns
Whether the type could been added (was not known before)
Definition at line 60 of file PCTypeMap.cpp.
References PCTypeMap::TypeDef::allowFill, PCTypeMap::TypeDef::color, PCTypeMap::TypeDef::discard, has(), PCTypeMap::TypeDef::id, PCTypeMap::TypeDef::layer, myTypes, RGBColor::parseColor(), and PCTypeMap::TypeDef::prefix.
Referenced by PCTypeDefHandler::myStartElement().
const PCTypeMap::TypeDef & PCTypeMap::get (const std::string & id)
Returns a type definition.
This type definition MUST have been added otherwise the further process is undefined.
Parameters
[in] id The id of the type to get the definitions of
Returns
Definition of the named type
Definition at line 79 of file PCTypeMap.cpp.
References myTypes.
Referenced by PCLoaderVisum::load(), PCLoaderOSM::loadIfSet(), PCLoaderDlrNavteq::loadPOIFile(), PCLoaderDlrNavteq::loadPolyFile(), and PCLoaderXML::myStartElement().
const TypeDef& PCTypeMap::getDefault () inline
get the default type according to the given options
Definition at line 115 of file PCTypeMap.h.
References myDefaultType.
Referenced by PCLoaderOSM::loadIfSet().
bool PCTypeMap::has (const std::string & id)
Returns the information whether the named type is known.
Parameters
[in] id The id of the type
Returns
Whether a definition of the named type was added before
Definition at line 85 of file PCTypeMap.cpp.
References myTypes.
Referenced by add(), PCLoaderVisum::load(), PCLoaderOSM::loadIfSet(), PCLoaderDlrNavteq::loadPOIFile(), PCLoaderDlrNavteq::loadPolyFile(), and PCLoaderXML::myStartElement().
Field Documentation
TypeDef PCTypeMap::myDefaultType protected
Definition at line 123 of file PCTypeMap.h.
Referenced by getDefault(), and PCTypeMap().
std::map<std::string, TypeDef> PCTypeMap::myTypes protected
A map of type names to type definitions.
Definition at line 121 of file PCTypeMap.h.
Referenced by add(), get(), and has().
The documentation for this class was generated from the following files:
PCTypeMap.h
PCTypeMap.cpp