SUMO - Simulation of Urban MObility: MsgHandler Class Reference
MsgHandler Class Reference
#include <MsgHandler.h>
Public Types
enum MsgType { MT_MESSAGE, MT_WARNING, MT_ERROR }
Public Member Functions
void addRetriever (OutputDevice *retriever)
Adds a further retriever to the instance responsible for a certain msg type.
void beginProcessMsg (std::string msg, bool addType=true)
Begins a process information.
void clear ()
Clears information whether an error occured previously.
void endProcessMsg (std::string msg)
Ends a process information.
void inform (std::string msg, bool addType=true)
adds a new error to the list
bool isRetriever (OutputDevice *retriever) const
Returns whether the given output device retrieves messages from the handler.
template<class T >
MsgHandler & operator<< (const T &t)
Generic output operator.
void removeRetriever (OutputDevice *retriever)
Removes the retriever from the handler.
bool wasInformed () const
Returns the information whether any messages were added.
Static Public Member Functions
static void assignLock (AbstractMutex *lock)
Sets the lock to use The lock will not be deleted.
static void cleanupOnEnd ()
Removes pending handler.
static MsgHandler * getErrorInstance ()
Returns the instance to add errors to.
static MsgHandler * getMessageInstance ()
Returns the instance to add normal messages to.
static MsgHandler * getWarningInstance ()
Returns the instance to add warnings to.
static void initOutputOptions ()
Protected Member Functions
std::string build (const std::string &msg, bool addType)
Builds the string which includes the mml-message type.
Private Types
typedef std::vector< OutputDevice * > RetrieverVector
Definition of the list of retrievers to inform.
Private Member Functions
MsgHandler (MsgType type)
standard constructor
MsgHandler (const MsgHandler &s)
MsgHandler & operator= (const MsgHandler &s)
~MsgHandler ()
destructor
Private Attributes
RetrieverVector myRetrievers
The list of retrievers that shall be informed about new messages or errors.
MsgType myType
The type of the instance.
bool myWasInformed
information wehther an error occured at all
Static Private Attributes
static bool myAmProcessingProcess = false
Information whether a process information is printed to cout.
static MsgHandler * myErrorInstance = 0
The instance to handle errors.
static AbstractMutex * myLock = 0
The lock if any has to be used The lock will not be deleted.
static MsgHandler * myMessageInstance = 0
The instance to handle normal messages.
static MsgHandler * myWarningInstance = 0
The instance to handle warnings.
Detailed Description
MsgHandler
Definition at line 53 of file MsgHandler.h.
Member Typedef Documentation
typedef std::vector<OutputDevice*> MsgHandler::RetrieverVector private
Definition of the list of retrievers to inform.
Definition at line 182 of file MsgHandler.h.
Member Enumeration Documentation
enum MsgHandler::MsgType
An enumeration to differ between different types of messages (errors, warning and information)
Enumerator
MT_MESSAGE
The message is only something to show.
MT_WARNING
The message is a warning.
MT_ERROR
The message is an error.
Definition at line 60 of file MsgHandler.h.
Constructor & Destructor Documentation
MsgHandler::MsgHandler (MsgType type) private
standard constructor
Definition at line 258 of file MsgHandler.cpp.
References addRetriever(), OutputDevice::getDevice(), and MT_MESSAGE.
Referenced by build(), getErrorInstance(), getMessageInstance(), and getWarningInstance().
MsgHandler::~MsgHandler () private
destructor
Definition at line 268 of file MsgHandler.cpp.
Referenced by build().
MsgHandler::MsgHandler (const MsgHandler & s) private
invalid copy constructor
Member Function Documentation
void MsgHandler::addRetriever (OutputDevice * retriever)
Adds a further retriever to the instance responsible for a certain msg type.
Definition at line 161 of file MsgHandler.cpp.
References isRetriever(), AbstractMutex::lock(), myLock, myRetrievers, and AbstractMutex::unlock().
Referenced by GNELoadThread::GNELoadThread(), GUILoadThread::GUILoadThread(), GUIRunThread::init(), initOutputOptions(), MsgHandler(), GUIMessageWindow::registerMsgHandlers(), GNELoadThread::run(), and GUILoadThread::run().
void MsgHandler::assignLock (AbstractMutex * lock) static
Sets the lock to use The lock will not be deleted.
Definition at line 279 of file MsgHandler.cpp.
References myLock.
Referenced by main().
void MsgHandler::beginProcessMsg (std::string msg, bool addType = true)
Begins a process information.
When a longer action is started, this method should be used to inform the user about it. There will be no newline printed, but the message handler will be informed that a process message has been begun. If an error occurs, a newline will be printed. After the action has been performed, use endProcessMsg to inform the user about it.
Definition at line 112 of file MsgHandler.cpp.
References build(), AbstractMutex::lock(), myAmProcessingProcess, myLock, myRetrievers, myWasInformed, and AbstractMutex::unlock().
std::string MsgHandler::build (const std::string & msg, bool addType) inline protected
Builds the string which includes the mml-message type.
Definition at line 131 of file MsgHandler.h.
References MsgHandler(), MT_ERROR, MT_MESSAGE, MT_WARNING, myType, and ~MsgHandler().
Referenced by beginProcessMsg(), and inform().
void MsgHandler::cleanupOnEnd () static
Removes pending handler.
Definition at line 242 of file MsgHandler.cpp.
References AbstractMutex::lock(), myErrorInstance, myLock, myMessageInstance, myWarningInstance, and AbstractMutex::unlock().
Referenced by SystemFrame::close(), and GUIRunThread::deleteSim().
void MsgHandler::clear ()
Clears information whether an error occured previously.
Definition at line 149 of file MsgHandler.cpp.
References AbstractMutex::lock(), myLock, myWasInformed, and AbstractMutex::unlock().
Referenced by loadJTRDefinitions(), main(), NBLoadedTLDef::myCompute(), GNELoadThread::run(), and GUILoadThread::run().
void MsgHandler::endProcessMsg (std::string msg)
Ends a process information.
Definition at line 131 of file MsgHandler.cpp.
References AbstractMutex::lock(), myAmProcessingProcess, myLock, myRetrievers, myWasInformed, and AbstractMutex::unlock().
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy(), and NBHeightMapper::loadIfSet().
MsgHandler * MsgHandler::getErrorInstance () static
Returns the instance to add errors to.
Definition at line 80 of file MsgHandler.cpp.
References MsgHandler(), MT_ERROR, and myErrorInstance.
Referenced by NLHandler::addPhase(), MSRouteHandler::addStop(), NLBuilder::build(), MSSOTLTrafficLightLogic::checkPhases(), OutputDevice::closeAll(), RORouteHandler::closeFlow(), RORouteHandler::closeVehicle(), ROJTRRouter::compute(), GUIRunThread::deleteSim(), GNELoadThread::GNELoadThread(), GUILoadThread::GUILoadThread(), GUIRunThread::init(), initOutputOptions(), PCLoaderOSM::loadIfSet(), loadJTRDefinitions(), NIImporter_ArcView::loadNetwork(), main(), GUIRunThread::makeStep(), MSPhaseDefinition::MSPhaseDefinition(), ROLoader::openRoutes(), RORouteDef::preComputeCurrentRoute(), ROLoader::processRoutes(), GUIMessageWindow::registerMsgHandlers(), RORouteDef::repairCurrentRoute(), GNELoadThread::run(), GUILoadThread::run(), XMLSubSys::runParser(), RONet::saveAndRemoveRoutesUntil(), MSSOTLTrafficLightLogic::setToATargetPhase(), GUILoadThread::submitEndAndCleanup(), GNELoadThread::submitEndAndCleanup(), and GUIMessageWindow::unregisterMsgHandlers().
MsgHandler * MsgHandler::getMessageInstance () static
Returns the instance to add normal messages to.
Definition at line 62 of file MsgHandler.cpp.
References MsgHandler(), MT_MESSAGE, and myMessageInstance.
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), GUIRunThread::deleteSim(), inform(), GUIRunThread::init(), initOutputOptions(), NBHeightMapper::loadIfSet(), MSSOTLPhaseTrafficLightLogic::MSSOTLPhaseTrafficLightLogic(), MSSOTLPlatoonTrafficLightLogic::MSSOTLPlatoonTrafficLightLogic(), MSSOTLPolicyBasedTrafficLightLogic::MSSOTLPolicyBasedTrafficLightLogic(), MSSOTLRequestTrafficLightLogic::MSSOTLRequestTrafficLightLogic(), MSSOTLWaveTrafficLightLogic::MSSOTLWaveTrafficLightLogic(), GUIMessageWindow::registerMsgHandlers(), GNELoadThread::run(), GUILoadThread::run(), GUILoadThread::submitEndAndCleanup(), GNELoadThread::submitEndAndCleanup(), and GUIMessageWindow::unregisterMsgHandlers().
MsgHandler * MsgHandler::getWarningInstance () static
Returns the instance to add warnings to.
Definition at line 71 of file MsgHandler.cpp.
References MsgHandler(), MT_WARNING, and myWarningInstance.
Referenced by NLHandler::addPhase(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), CHRouter< E, V, PF >::clone(), ROJTRRouter::compute(), GUIRunThread::deleteSim(), GUIRunThread::init(), initOutputOptions(), PCLoaderOSM::loadIfSet(), NBLoadedTLDef::myCompute(), RORouteDef::preComputeCurrentRoute(), GUIMessageWindow::registerMsgHandlers(), RORouteDef::repairCurrentRoute(), GNELoadThread::run(), GUILoadThread::run(), RONet::saveAndRemoveRoutesUntil(), GUILoadThread::submitEndAndCleanup(), GNELoadThread::submitEndAndCleanup(), TraCIServer::TraCIServer(), and GUIMessageWindow::unregisterMsgHandlers().
void MsgHandler::inform (std::string msg, bool addType = true)
adds a new error to the list
Definition at line 89 of file MsgHandler.cpp.
References build(), getMessageInstance(), inform(), AbstractMutex::lock(), myAmProcessingProcess, myLock, myRetrievers, myWasInformed, and AbstractMutex::unlock().
Referenced by RORouteHandler::addPersonTrip(), NLHandler::addPhase(), RORouteHandler::addStop(), ROVehicle::addStop(), MSSOTLTrafficLightLogic::checkPhases(), RORouteHandler::closeFlow(), RORouteHandler::closeRoute(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), RORouteHandler::closeVehicleTypeDistribution(), ROJTRRouter::compute(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), CHRouter< E, V, PF >::compute(), ROPerson::computeIntermodal(), ROVehicle::computeRoute(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), inform(), GUIRunThread::init(), main(), GUIRunThread::makeStep(), MSPhaseDefinition::MSPhaseDefinition(), MSSOTLPhaseTrafficLightLogic::MSSOTLPhaseTrafficLightLogic(), MSSOTLPlatoonTrafficLightLogic::MSSOTLPlatoonTrafficLightLogic(), MSSOTLPolicyBasedTrafficLightLogic::MSSOTLPolicyBasedTrafficLightLogic(), MSSOTLRequestTrafficLightLogic::MSSOTLRequestTrafficLightLogic(), MSSOTLWaveTrafficLightLogic::MSSOTLWaveTrafficLightLogic(), NIXMLConnectionsHandler::myStartElement(), RORouteHandler::myStartElement(), PCLoaderOSM::NodesHandler::myStartElement(), PCLoaderOSM::RelationsHandler::myStartElement(), PCLoaderOSM::EdgesHandler::myStartElement(), RORouteHandler::openRoute(), RORouteHandler::openRouteDistribution(), NIXMLConnectionsHandler::parseConnection(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), RORouteHandler::parseEdges(), RORouteHandler::parseFromViaTo(), NIXMLConnectionsHandler::parseLaneBound(), SUMORouteHandler::parseStop(), RORouteDef::preComputeCurrentRoute(), RORouteDef::repairCurrentRoute(), GUILoadThread::run(), MSSOTLTrafficLightLogic::setToATargetPhase(), and TraCIServer::TraCIServer().
void MsgHandler::initOutputOptions () static
Definition at line 197 of file MsgHandler.cpp.
References addRetriever(), OptionsCont::getBool(), OutputDevice::getDevice(), getErrorInstance(), getMessageInstance(), OptionsCont::getOptions(), OptionsCont::getString(), getWarningInstance(), OptionsCont::isSet(), and removeRetriever().
Referenced by main(), GNELoadThread::run(), and GUILoadThread::run().
bool MsgHandler::isRetriever (OutputDevice * retriever) const
Returns whether the given output device retrieves messages from the handler.
Definition at line 191 of file MsgHandler.cpp.
References myRetrievers.
Referenced by addRetriever(), and OutputDevice::closeAll().
template<class T > MsgHandler& MsgHandler::operator<< (const T & t) inline
Generic output operator.
Returns
The MsgHandler for further processing
Definition at line 121 of file MsgHandler.h.
References myRetrievers.
MsgHandler& MsgHandler::operator= (const MsgHandler & s) private
invalid assignment operator
void MsgHandler::removeRetriever (OutputDevice * retriever)
Removes the retriever from the handler.
Definition at line 175 of file MsgHandler.cpp.
References AbstractMutex::lock(), myLock, myRetrievers, and AbstractMutex::unlock().
Referenced by GUIRunThread::deleteSim(), initOutputOptions(), GUILoadThread::run(), GUILoadThread::submitEndAndCleanup(), GNELoadThread::submitEndAndCleanup(), and GUIMessageWindow::unregisterMsgHandlers().
bool MsgHandler::wasInformed () const
Returns the information whether any messages were added.
Definition at line 273 of file MsgHandler.cpp.
References myWasInformed.
Referenced by NLBuilder::build(), ROLoader::openRoutes(), ROLoader::processRoutes(), and XMLSubSys::runParser().
Field Documentation
bool MsgHandler::myAmProcessingProcess = false static private
Information whether a process information is printed to cout.
Definition at line 168 of file MsgHandler.h.
Referenced by beginProcessMsg(), endProcessMsg(), and inform().
MsgHandler * MsgHandler::myErrorInstance = 0 static private
The instance to handle errors.
Definition at line 159 of file MsgHandler.h.
Referenced by cleanupOnEnd(), and getErrorInstance().
AbstractMutex * MsgHandler::myLock = 0 static private
The lock if any has to be used The lock will not be deleted.
Definition at line 172 of file MsgHandler.h.
Referenced by addRetriever(), assignLock(), beginProcessMsg(), cleanupOnEnd(), clear(), endProcessMsg(), inform(), and removeRetriever().
MsgHandler * MsgHandler::myMessageInstance = 0 static private
The instance to handle normal messages.
Definition at line 165 of file MsgHandler.h.
Referenced by cleanupOnEnd(), and getMessageInstance().
RetrieverVector MsgHandler::myRetrievers private
The list of retrievers that shall be informed about new messages or errors.
Definition at line 185 of file MsgHandler.h.
Referenced by addRetriever(), beginProcessMsg(), endProcessMsg(), inform(), isRetriever(), operator<<(), and removeRetriever().
MsgType MsgHandler::myType private
The type of the instance.
Definition at line 176 of file MsgHandler.h.
Referenced by build().
MsgHandler * MsgHandler::myWarningInstance = 0 static private
The instance to handle warnings.
Definition at line 162 of file MsgHandler.h.
Referenced by cleanupOnEnd(), and getWarningInstance().
bool MsgHandler::myWasInformed private
information wehther an error occured at all
Definition at line 179 of file MsgHandler.h.
Referenced by beginProcessMsg(), clear(), endProcessMsg(), inform(), and wasInformed().
The documentation for this class was generated from the following files:
MsgHandler.h
MsgHandler.cpp