SUMO - Simulation of Urban MObility: MSContainer::MSContainerStage_Tranship Class Reference
MSContainer::MSContainerStage_Tranship Class Reference
#include <MSContainer.h>
Public Member Functions
virtual void beginEventOutput (const MSTransportable &c, SUMOTime t, OutputDevice &os) const
Called for writing the events output.
virtual void endEventOutput (const MSTransportable &c, SUMOTime t, OutputDevice &os) const
Called for writing the events output (end of an action)
SUMOReal getAngle (SUMOTime now) const
Returns the angle of the container.
SUMOReal getArrivalPos () const
CState * getContainerState () const
SUMOReal getDepartPos () const
const MSEdge & getDestination () const
returns the destination edge
const MSStoppingPlace * getDestinationStop () const
returns the destination stop (if any)
const MSEdge * getEdge () const
Returns the current edge.
SUMOReal getEdgeAngle (const MSEdge *e, SUMOReal at) const
get angle of the edge at a certain position
SUMOReal getEdgePos (SUMOTime now) const
Returns the offset from the start of the current edge measured in its natural direction.
Position getEdgePosition (const MSEdge *e, SUMOReal at, SUMOReal offset) const
get position on edge e at length at with orthogonal offset
const MSEdge * getFromEdge () const
Returns first edge of the containers route.
Position getLanePosition (const MSLane *lane, SUMOReal at, SUMOReal offset) const
get position on lane at length at with orthogonal offset
SUMOReal getMaxSpeed () const
accessors to be used by MSCModel_NonInteracting
const MSEdge * getNextRouteEdge () const
Position getPosition (SUMOTime now) const
Returns the position of the container.
SUMOReal getSpeed () const
Returns the speed of the container.
std::string getStageDescription () const
Returns the current stage description as a string.
StageType getStageType () const
const MSEdge * getToEdge () const
Returns last edge of the containers route.
virtual SUMOVehicle * getVehicle () const
Whether the transportable waits for a vehicle.
SUMOTime getWaitingTime (SUMOTime now) const
Returns the time the container spent waiting.
virtual bool isWaiting4Vehicle () const
Whether the transportable waits for a vehicle.
virtual bool isWaitingFor (const std::string &line) const
Whether the transportable waits for a vehicle of the line specified.
bool moveToNextEdge (MSTransportable *container, SUMOTime currentTime, MSEdge *nextInternal=0)
move forward and return whether the container arrived
MSContainerStage_Tranship (const std::vector< const MSEdge * > &route, MSStoppingPlace *toStop, SUMOReal speed, SUMOReal departPos, SUMOReal arrivalPos)
constructor
virtual void proceed (MSNet *net, MSTransportable *container, SUMOTime now, Stage *previous)
proceeds to the next step
virtual void routeOutput (OutputDevice &os) const
Called on writing vehroute output.
void setArrived (SUMOTime now)
logs end of the step
void setDeparted (SUMOTime now)
logs end of the step
virtual void tripInfoOutput (OutputDevice &os) const
Called on writing tripinfo output.
~MSContainerStage_Tranship ()
destructor
Protected Attributes
SUMOReal myArrivalPos
the position at which we want to arrive
SUMOTime myArrived
the time at which this stage ended
SUMOTime myDeparted
the time at which this stage started
const MSEdge & myDestination
the next edge to reach by getting transported
MSStoppingPlace *const myDestinationStop
the stop to reach by getting transported (if any)
StageType myType
The type of this stage.
Private Member Functions
MSContainerStage_Tranship (const MSContainerStage_Tranship &)
Invalidated copy constructor.
MSContainerStage_Tranship & operator= (const MSContainerStage_Tranship &)
Invalidated assignment operator.
Private Attributes
CState * myContainerState
state that is to be manipulated by MSCModel
MSEdge * myCurrentInternalEdge
The current internal edge this container is on or 0.
SUMOReal myDepartPos
the depart position
std::vector< const MSEdge * > myRoute
The route of the container.
std::vector< const MSEdge * >::iterator myRouteStep
current step
SUMOReal mySpeed
the speed of the container
Friends
class MSCModel_NonInteracting
Detailed Description
A "real" stage performing the tranship of a container A container is in this stage if it gets transhipred between two stops that are assumed to be connected.
Definition at line 112 of file MSContainer.h.
Constructor & Destructor Documentation
MSContainer::MSContainerStage_Tranship::MSContainerStage_Tranship (const std::vector< const MSEdge * > & route, MSStoppingPlace * toStop, SUMOReal speed, SUMOReal departPos, SUMOReal arrivalPos)
constructor
Definition at line 114 of file MSContainer.cpp.
References SUMOVehicleParameter::interpretEdgePos(), myDepartPos, myRoute, and SUMO_ATTR_DEPARTPOS.
MSContainer::MSContainerStage_Tranship::~MSContainerStage_Tranship ()
destructor
Definition at line 125 of file MSContainer.cpp.
MSContainer::MSContainerStage_Tranship::MSContainerStage_Tranship (const MSContainerStage_Tranship &) private
Invalidated copy constructor.
Member Function Documentation
void MSContainer::MSContainerStage_Tranship::beginEventOutput (const MSTransportable & c, SUMOTime t, OutputDevice & os) const virtual
Called for writing the events output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 197 of file MSContainer.cpp.
References MSTransportable::getID(), myRoute, OutputDevice::openTag(), time2string(), and OutputDevice::writeAttr().
void MSContainer::MSContainerStage_Tranship::endEventOutput (const MSTransportable & c, SUMOTime t, OutputDevice & os) const virtual
Called for writing the events output (end of an action)
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 204 of file MSContainer.cpp.
References MSTransportable::getID(), myRoute, OutputDevice::openTag(), time2string(), and OutputDevice::writeAttr().
SUMOReal MSContainer::MSContainerStage_Tranship::getAngle (SUMOTime now) const virtual
Returns the angle of the container.
Implements MSTransportable::Stage.
Definition at line 167 of file MSContainer.cpp.
References CState::getAngle(), and myContainerState.
SUMOReal MSContainer::MSContainerStage_Tranship::getArrivalPos () const inline
Definition at line 191 of file MSContainer.h.
References MSTransportable::Stage::myArrivalPos.
Referenced by CState::computeTranshipTime().
CState* MSContainer::MSContainerStage_Tranship::getContainerState () const inline
Definition at line 199 of file MSContainer.h.
SUMOReal MSContainer::MSContainerStage_Tranship::getDepartPos () const inline
Definition at line 187 of file MSContainer.h.
Referenced by CState::computeTranshipTime().
const MSEdge & MSTransportable::Stage::getDestination () const inherited
returns the destination edge
Definition at line 63 of file MSTransportable.cpp.
References MSTransportable::Stage::myDestination.
Referenced by MSPModel_Striping::moveInDirectionOnLane(), MSContainer::MSContainerStage_Driving::routeOutput(), MSTransportable::Stage_Waiting::routeOutput(), and MSPerson::MSPersonStage_Driving::routeOutput().
const MSStoppingPlace* MSTransportable::Stage::getDestinationStop () const inline inherited
returns the destination stop (if any)
Definition at line 83 of file MSTransportable.h.
References MSTransportable::Stage::myDestinationStop.
Referenced by MSPModel_Striping::moveInDirectionOnLane(), MSContainer::MSContainerStage_Driving::proceed(), and MSPerson::MSPersonStage_Driving::proceed().
const MSEdge * MSContainer::MSContainerStage_Tranship::getEdge () const virtual
Returns the current edge.
Implements MSTransportable::Stage.
Definition at line 138 of file MSContainer.cpp.
References myCurrentInternalEdge, and myRouteStep.
Referenced by CState::getAngle(), and moveToNextEdge().
SUMOReal MSTransportable::Stage::getEdgeAngle (const MSEdge * e, SUMOReal at) const inherited
get angle of the edge at a certain position
Definition at line 96 of file MSTransportable.cpp.
References MSEdge::getLanes().
Referenced by MSPModel_NonInteracting::PState::getAngle(), CState::getAngle(), MSTransportable::Stage_Waiting::getAngle(), MSTransportable::Stage_Driving::getAngle(), and MSTransportable::Stage::getVehicle().
SUMOReal MSContainer::MSContainerStage_Tranship::getEdgePos (SUMOTime now) const virtual
Returns the offset from the start of the current edge measured in its natural direction.
Implements MSTransportable::Stage.
Definition at line 157 of file MSContainer.cpp.
References CState::getEdgePos(), and myContainerState.
Position MSTransportable::Stage::getEdgePosition (const MSEdge * e, SUMOReal at, SUMOReal offset) const inherited
get position on edge e at length at with orthogonal offset
Definition at line 86 of file MSTransportable.cpp.
References MSTransportable::Stage::getLanePosition(), and MSEdge::getLanes().
Referenced by MSTransportable::Stage_Waiting::getPosition(), MSTransportable::Stage_Driving::getPosition(), and MSTransportable::Stage::getVehicle().
const MSEdge * MSContainer::MSContainerStage_Tranship::getFromEdge () const virtual
Returns first edge of the containers route.
Implements MSTransportable::Stage.
Definition at line 147 of file MSContainer.cpp.
References myRoute.
Referenced by CState::computeTranshipTime().
Position MSTransportable::Stage::getLanePosition (const MSLane * lane, SUMOReal at, SUMOReal offset) const inherited
get position on lane at length at with orthogonal offset
Definition at line 91 of file MSTransportable.cpp.
References MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), PositionVector::positionAtOffset(), and SUMOReal.
Referenced by CState::computeTranshipTime(), MSTransportable::Stage::getEdgePosition(), MSPModel_NonInteracting::PState::getPosition(), MSPModel_Striping::PState::getPosition(), and MSTransportable::Stage::getVehicle().
SUMOReal MSContainer::MSContainerStage_Tranship::getMaxSpeed () const inline
accessors to be used by MSCModel_NonInteracting
Definition at line 183 of file MSContainer.h.
Referenced by CState::computeTranshipTime(), CState::getPosition(), and CState::getSpeed().
const MSEdge* MSContainer::MSContainerStage_Tranship::getNextRouteEdge () const inline
Definition at line 195 of file MSContainer.h.
Position MSContainer::MSContainerStage_Tranship::getPosition (SUMOTime now) const virtual
Returns the position of the container.
Implements MSTransportable::Stage.
Definition at line 162 of file MSContainer.cpp.
References CState::getPosition(), myContainerState, and SUMOReal.
SUMOReal MSContainer::MSContainerStage_Tranship::getSpeed () const virtual
Returns the speed of the container.
Implements MSTransportable::Stage.
Definition at line 177 of file MSContainer.cpp.
References CState::getSpeed(), and myContainerState.
std::string MSContainer::MSContainerStage_Tranship::getStageDescription () const inline virtual
Returns the current stage description as a string.
Implements MSTransportable::Stage.
Definition at line 150 of file MSContainer.h.
References MSTransportable::Stage_Driving::beginEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSContainer::MSContainerStage_Driving::routeOutput(), and MSContainer::MSContainerStage_Driving::tripInfoOutput().
StageType MSTransportable::Stage::getStageType () const inline inherited
Definition at line 103 of file MSTransportable.h.
References MSTransportable::Stage::getStageDescription(), MSTransportable::Stage::isWaitingFor(), MSTransportable::Stage::myType, MSTransportable::Stage::proceed(), MSTransportable::Stage::setArrived(), and MSTransportable::Stage::setDeparted().
const MSEdge * MSContainer::MSContainerStage_Tranship::getToEdge () const
Returns last edge of the containers route.
Definition at line 152 of file MSContainer.cpp.
References myRoute, and SUMOReal.
Referenced by CState::computeTranshipTime().
virtual SUMOVehicle* MSTransportable::Stage::getVehicle () const inline virtual inherited
Whether the transportable waits for a vehicle.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 128 of file MSTransportable.h.
References MSTransportable::Stage::beginEventOutput(), MSTransportable::Stage::endEventOutput(), MSTransportable::Stage::getEdgeAngle(), MSTransportable::Stage::getEdgePosition(), MSTransportable::Stage::getLanePosition(), MSTransportable::Stage::getSpeed(), MSTransportable::Stage::getWaitingTime(), MSTransportable::Stage::routeOutput(), SUMOReal, and MSTransportable::Stage::tripInfoOutput().
SUMOTime MSContainer::MSContainerStage_Tranship::getWaitingTime (SUMOTime now) const virtual
Returns the time the container spent waiting.
Implements MSTransportable::Stage.
Definition at line 172 of file MSContainer.cpp.
References SUMOReal.
virtual bool MSTransportable::Stage::isWaiting4Vehicle () const inline virtual inherited
Whether the transportable waits for a vehicle.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 123 of file MSTransportable.h.
bool MSTransportable::Stage::isWaitingFor (const std::string & line) const virtual inherited
Whether the transportable waits for a vehicle of the line specified.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 81 of file MSTransportable.cpp.
Referenced by MSTransportable::Stage::getStageType().
bool MSContainer::MSContainerStage_Tranship::moveToNextEdge (MSTransportable * container, SUMOTime currentTime, MSEdge * nextInternal = 0)
move forward and return whether the container arrived
Definition at line 210 of file MSContainer.cpp.
References MSStoppingPlace::addTransportable(), MSTransportableControl::erase(), MSNet::getContainerControl(), getEdge(), MSNet::getInstance(), myCurrentInternalEdge, MSTransportable::Stage::myDestinationStop, myRoute, myRouteStep, and MSTransportable::proceed().
MSContainerStage_Tranship& MSContainer::MSContainerStage_Tranship::operator= (const MSContainerStage_Tranship &) private
Invalidated assignment operator.
void MSContainer::MSContainerStage_Tranship::proceed (MSNet * net, MSTransportable * container, SUMOTime now, Stage * previous) virtual
proceeds to the next step
Implements MSTransportable::Stage.
Definition at line 129 of file MSContainer.cpp.
References MSCModel_NonInteracting::add(), MSTransportable::Stage::getEdge(), MSTransportable::Stage::getEdgePos(), MSCModel_NonInteracting::getModel(), myContainerState, myDepartPos, myRoute, myRouteStep, and MSEdge::removeContainer().
void MSContainer::MSContainerStage_Tranship::routeOutput (OutputDevice & os) const virtual
Called on writing vehroute output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 189 of file MSContainer.cpp.
References OutputDevice::closeTag(), myRoute, mySpeed, OutputDevice::openTag(), SUMO_ATTR_EDGES, SUMO_ATTR_SPEED, and OutputDevice::writeAttr().
void MSTransportable::Stage::setArrived (SUMOTime now) inherited
logs end of the step
Definition at line 76 of file MSTransportable.cpp.
References MSTransportable::Stage::myArrived.
Referenced by MSTransportable::Stage::getStageType(), MSContainer::proceed(), and MSPerson::proceed().
void MSTransportable::Stage::setDeparted (SUMOTime now) inherited
logs end of the step
Definition at line 69 of file MSTransportable.cpp.
References MSTransportable::Stage::myDeparted.
Referenced by MSTransportable::Stage::getStageType(), and MSTransportable::getVehicleType().
void MSContainer::MSContainerStage_Tranship::tripInfoOutput (OutputDevice & os) const virtual
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable::Stage.
Definition at line 183 of file MSContainer.cpp.
References OutputDevice::closeTag(), MSTransportable::Stage::myArrived, OutputDevice::openTag(), time2string(), and OutputDevice::writeAttr().
Friends And Related Function Documentation
friend class MSCModel_NonInteracting friend
Definition at line 113 of file MSContainer.h.
Field Documentation
SUMOReal MSTransportable::Stage::myArrivalPos protected inherited
the position at which we want to arrive
Definition at line 179 of file MSTransportable.h.
Referenced by MSPerson::MSPersonStage_Walking::computeAverageSpeed(), MSTransportable::Stage_Waiting::getAngle(), MSTransportable::Stage::getArrivalPos(), MSPerson::MSPersonStage_Walking::getArrivalPos(), getArrivalPos(), MSTransportable::Stage_Waiting::getEdgePos(), and MSTransportable::Stage_Waiting::getPosition().
SUMOTime MSTransportable::Stage::myArrived protected inherited
the time at which this stage ended
Definition at line 185 of file MSTransportable.h.
Referenced by MSTransportable::Stage::setArrived(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), MSPerson::MSPersonStage_Walking::tripInfoOutput(), tripInfoOutput(), MSTransportable::Stage_Waiting::tripInfoOutput(), and MSPerson::MSPersonStage_Driving::tripInfoOutput().
CState* MSContainer::MSContainerStage_Tranship::myContainerState private
state that is to be manipulated by MSCModel
Definition at line 217 of file MSContainer.h.
Referenced by getAngle(), getEdgePos(), getPosition(), getSpeed(), and proceed().
MSEdge* MSContainer::MSContainerStage_Tranship::myCurrentInternalEdge private
The current internal edge this container is on or 0.
Definition at line 220 of file MSContainer.h.
Referenced by getEdge(), and moveToNextEdge().
SUMOTime MSTransportable::Stage::myDeparted protected inherited
the time at which this stage started
Definition at line 182 of file MSTransportable.h.
Referenced by MSTransportable::Stage::setDeparted(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), and MSPerson::MSPersonStage_Driving::tripInfoOutput().
SUMOReal MSContainer::MSContainerStage_Tranship::myDepartPos private
the depart position
Definition at line 211 of file MSContainer.h.
Referenced by MSContainerStage_Tranship(), and proceed().
const MSEdge& MSTransportable::Stage::myDestination protected inherited
the next edge to reach by getting transported
Definition at line 173 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Waiting::getAngle(), MSTransportable::Stage::getDestination(), MSTransportable::Stage_Waiting::getEdge(), MSTransportable::Stage_Waiting::getFromEdge(), and MSTransportable::Stage_Waiting::getPosition().
MSStoppingPlace* const MSTransportable::Stage::myDestinationStop protected inherited
the stop to reach by getting transported (if any)
Definition at line 176 of file MSTransportable.h.
Referenced by MSTransportable::Stage::getDestinationStop(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), and moveToNextEdge().
std::vector<const MSEdge*> MSContainer::MSContainerStage_Tranship::myRoute private
The route of the container.
Definition at line 205 of file MSContainer.h.
Referenced by beginEventOutput(), endEventOutput(), getFromEdge(), getToEdge(), moveToNextEdge(), MSContainerStage_Tranship(), proceed(), and routeOutput().
std::vector<const MSEdge*>::iterator MSContainer::MSContainerStage_Tranship::myRouteStep private
current step
Definition at line 208 of file MSContainer.h.
Referenced by getEdge(), moveToNextEdge(), and proceed().
SUMOReal MSContainer::MSContainerStage_Tranship::mySpeed private
the speed of the container
Definition at line 214 of file MSContainer.h.
Referenced by routeOutput().
StageType MSTransportable::Stage::myType protected inherited
The type of this stage.
Definition at line 188 of file MSTransportable.h.
Referenced by MSTransportable::Stage::getStageType(), MSTransportable::Stage_Waiting::routeOutput(), and MSTransportable::Stage_Waiting::tripInfoOutput().
The documentation for this class was generated from the following files:
MSContainer.h
MSContainer.cpp