SUMO - Simulation of Urban MObility: Position Class Reference
Position Class Reference
A point in 2D or 3D with translation and scaling methods.
#include <Position.h>
Public Member Functions
void add (const Position &pos)
Adds the given position to this one.
void add (SUMOReal dx, SUMOReal dy)
Adds the given position to this one.
void add (SUMOReal dx, SUMOReal dy, SUMOReal dz)
Adds the given position to this one.
bool almostSame (const Position &p2, SUMOReal maxDiv=POSITION_EPS) const
SUMOReal angleTo2D (const Position &other) const
returns the angle in the plane of the vector pointing from here to the other position
Position crossProduct (const Position &pos)
returns the cross product between this point and the second one
SUMOReal distanceSquaredTo (const Position &p2) const
SUMOReal distanceSquaredTo2D (const Position &p2) const
SUMOReal distanceTo (const Position &p2) const
returns the euclidean distance in 3 dimension
SUMOReal distanceTo2D (const Position &p2) const
returns the euclidean distance in the x-y-plane
SUMOReal dotProduct (const Position &pos)
returns the dot product (scalar product) between this point and the second one
void mul (SUMOReal val)
Multiplies both positions with the given value.
void mul (SUMOReal mx, SUMOReal my)
Multiplies position with the given values.
void mul (SUMOReal mx, SUMOReal my, SUMOReal mz)
Multiplies position with the given values.
void norm2d ()
bool operator!= (const Position &p2) const
Position operator* (SUMOReal scalar) const
keep the direction but modify the length of the (location) vector to length * scalar
Position operator+ (const Position &p2) const
Position operator+ (SUMOReal offset) const
keep the direction but modify the length of the (location) vector to length + scalar
Position operator- (const Position &p2) const
bool operator< (const Position &p2) const
lexicographical sorting for use in maps and sets
bool operator== (const Position &p2) const
Position ()
default constructor
Position (SUMOReal x, SUMOReal y)
parametrised constructor
Position (SUMOReal x, SUMOReal y, SUMOReal z)
parametrised constructor
void set (SUMOReal x, SUMOReal y)
void set (SUMOReal x, SUMOReal y, SUMOReal z)
void set (const Position &pos)
void sub (SUMOReal dx, SUMOReal dy)
Substracts the given position from this one.
void sub (SUMOReal dx, SUMOReal dy, SUMOReal dz)
Substracts the given position from this one.
void sub (const Position &pos)
Substracts the given position from this one.
SUMOReal x () const
Returns the x-position.
SUMOReal y () const
Returns the y-position.
SUMOReal z () const
Returns the z-position.
~Position ()
Destructor.
Static Public Attributes
static const Position INVALID
Private Attributes
SUMOReal myX
The x-position.
SUMOReal myY
The y-position.
SUMOReal myZ
The z-position.
Friends
std::ostream & operator<< (std::ostream &os, const Position &p)
Prints to the output.
Detailed Description
A point in 2D or 3D with translation and scaling methods.
Definition at line 46 of file Position.h.
Constructor & Destructor Documentation
Position::Position () inline
default constructor
Definition at line 49 of file Position.h.
Referenced by crossProduct(), GUIPointOfInterest::drawGL(), operator*(), operator+(), and operator-().
Position::Position (SUMOReal x, SUMOReal y) inline
parametrised constructor
Definition at line 52 of file Position.h.
Position::Position (SUMOReal x, SUMOReal y, SUMOReal z) inline
parametrised constructor
Definition at line 56 of file Position.h.
Position::~Position () inline
Destructor.
Definition at line 60 of file Position.h.
Member Function Documentation
void Position::add (const Position & pos) inline
Adds the given position to this one.
Definition at line 119 of file Position.h.
References myX, myY, and myZ.
Referenced by NBNodeCont::analyzeCluster(), AGPosition::compute2dPosition(), NBNodeShapeComputer::computeNodeShapeDefault(), NIVissimDistrictConnection::dict_BuildDistrictNodes(), GNEEdge::drawGL(), GUIEdge::drawGL(), GLHelper::drawTextBox(), PositionVector::extrapolate(), PositionVector::extrapolate2D(), NBNode::getEmptyDir(), GeoConvHelper::moveConvertedBy(), NBDistrict::reshiftPosition(), NBNode::reshiftPosition(), GUISUMOAbstractView::showToolTipFor(), and GeoConvHelper::x2cartesian_const().
void Position::add (SUMOReal dx, SUMOReal dy) inline
Adds the given position to this one.
Definition at line 126 of file Position.h.
References myX, and myY.
void Position::add (SUMOReal dx, SUMOReal dy, SUMOReal dz) inline
Adds the given position to this one.
Definition at line 132 of file Position.h.
References myX, myY, and myZ.
bool Position::almostSame (const Position & p2, SUMOReal maxDiv = POSITION_EPS) const inline
Definition at line 215 of file Position.h.
References distanceTo().
Referenced by AGPosition::operator==(), PositionVector::push_back_noDoublePos(), and PositionVector::push_front_noDoublePos().
SUMOReal Position::angleTo2D (const Position & other) const inline
returns the angle in the plane of the vector pointing from here to the other position
Definition at line 243 of file Position.h.
References myX, and myY.
Referenced by NBNode::bezierControlPoints(), MSVehicle::computeAngle(), NBEdge::computeAngle(), GUIBusStop::drawGL(), GLHelper::drawTriangleAtEnd(), NBContHelper::relative_outgoing_edge_sorter::operator()(), NBContHelper::relative_incoming_edge_sorter::operator()(), PositionVector::rotationAtOffset(), GNEAdditionalSet::updateConnections(), and NWWriter_OpenDrive::writeGeomSmooth().
Position Position::crossProduct (const Position & pos) inline
returns the cross product between this point and the second one
Definition at line 249 of file Position.h.
References myX, myY, myZ, and Position().
Referenced by NBHeightMapper::Triangle::normalVector().
SUMOReal Position::distanceSquaredTo (const Position & p2) const inline
Definition at line 226 of file Position.h.
References myX, myY, and myZ.
Referenced by distanceTo().
SUMOReal Position::distanceSquaredTo2D (const Position & p2) const inline
Definition at line 237 of file Position.h.
References myX, and myY.
Referenced by distanceTo2D().
SUMOReal Position::distanceTo (const Position & p2) const inline
returns the euclidean distance in 3 dimension
Definition at line 221 of file Position.h.
References distanceSquaredTo().
Referenced by almostSame(), TraCIServerAPI_Vehicle::commandDistanceRequest(), TraCIServerAPI_Simulation::commandDistanceRequest(), NBHelpers::distance(), AGPosition::distanceTo(), GLHelper::drawBoxLines(), GLHelper::drawTriangleAtEnd(), PositionVector::extrapolate(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), PositionVector::indexOfClosest(), NBEdge::init(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), GUIViewTraffic::onGamingClick(), operator+(), PositionVector::positionAtOffset(), NIVissimEdge::remapOneOfNodes(), PositionVector::rotationAtOffset(), GUIBaseVehicle::setFunctionalColor(), PositionVector::slopeDegreeAtOffset(), GUILane::splitAtSegments(), GNEChargingStation::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEBusStop::updateGeometry(), GNEContainerStop::updateGeometry(), and MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility().
SUMOReal Position::distanceTo2D (const Position & p2) const inline
returns the euclidean distance in the x-y-plane
Definition at line 232 of file Position.h.
References distanceSquaredTo2D().
Referenced by NBNode::bezierControlPoints(), NBNode::buildWalkingAreas(), NGRandomNetBuilder::canConnect(), NBNode::checkCrossing(), GUIVehicle::computeSeats(), PositionVector::distance2D(), GUIVehicle::drawAction_drawRailCarriages(), GUIBusStop::drawGL(), PositionVector::extrapolate2D(), ROEdge::getDistanceTo(), MSEdge::getDistanceTo(), GNEInternalLane::GNEInternalLane(), GUILane::GUILane(), MSVehicle::Influencer::implicitDeltaPosVTD(), MSVehicle::Influencer::implicitSpeedVTD(), MSPModel_Striping::initWalkingAreaPaths(), PositionVector::insertAtClosest(), PositionVector::intersects(), PositionVector::intersectsAtLengths2D(), PositionVector::move2side(), GeomHelper::nearest_offset_on_line_to_point2D(), PositionVector::nearest_offset_to_point2D(), PositionVector::positionAtOffset2D(), PositionVector::removeClosest(), GNEEdge::resetEndpoint(), GNEEdge::setEndpoint(), PositionVector::sideOffset(), PositionVector::slopeDegreeAtOffset(), PositionVector::transformToVectorCoordinates(), GNEAdditionalSet::updateConnections(), GNEConnection::updateGeometry(), GNECrossing::updateGeometry(), GNELane::updateGeometry(), TraCIServerAPI_Vehicle::vtdMap(), NWWriter_OpenDrive::writeGeomLines(), and NWWriter_OpenDrive::writeGeomSmooth().
SUMOReal Position::dotProduct (const Position & pos) inline
returns the dot product (scalar product) between this point and the second one
Definition at line 257 of file Position.h.
References myX, myY, and myZ.
Referenced by NBHeightMapper::Triangle::getZ().
void Position::mul (SUMOReal val) inline
Multiplies both positions with the given value.
Definition at line 99 of file Position.h.
References myX, myY, and myZ.
Referenced by NIXMLNodesHandler::addNode(), NBNodeCont::analyzeCluster(), AGPosition::compute2dPosition(), GeoConvHelper::computeFinal(), NBNodeShapeComputer::computeNodeShapeDefault(), GNEEdge::drawGL(), GUIEdge::drawGL(), NBNode::getEmptyDir(), NBDistrict::mirrorX(), NBNode::mirrorX(), NWWriter_DlrNavteq::writeNodesUnsplitted(), and NWWriter_DlrNavteq::writeTrafficSignals().
void Position::mul (SUMOReal mx, SUMOReal my) inline
Multiplies position with the given values.
Definition at line 106 of file Position.h.
References myX, and myY.
void Position::mul (SUMOReal mx, SUMOReal my, SUMOReal mz) inline
Multiplies position with the given values.
Definition at line 112 of file Position.h.
References myX, myY, and myZ.
void Position::norm2d () inline
Definition at line 158 of file Position.h.
References myX, myY, and SUMOReal.
Referenced by NBNode::getEmptyDir().
bool Position::operator!= (const Position & p2) const inline
Definition at line 200 of file Position.h.
References myX, myY, and myZ.
Position Position::operator* (SUMOReal scalar) const inline
keep the direction but modify the length of the (location) vector to length * scalar
Definition at line 182 of file Position.h.
References myX, myY, myZ, and Position().
Position Position::operator+ (const Position & p2) const inline
Definition at line 173 of file Position.h.
References myX, myY, myZ, and Position().
Position Position::operator+ (SUMOReal offset) const inline
keep the direction but modify the length of the (location) vector to length + scalar
Definition at line 187 of file Position.h.
References distanceTo(), myX, myY, myZ, Position(), and SUMOReal.
Position Position::operator- (const Position & p2) const inline
Definition at line 177 of file Position.h.
References myX, myY, myZ, and Position().
bool Position::operator< (const Position & p2) const inline
lexicographical sorting for use in maps and sets
Definition at line 205 of file Position.h.
References myX, myY, and myZ.
bool Position::operator== (const Position & p2) const inline
Definition at line 196 of file Position.h.
References myX, myY, and myZ.
void Position::set (SUMOReal x, SUMOReal y) inline
Definition at line 78 of file Position.h.
References myX, myY, x(), and y().
Referenced by NIXMLNodesHandler::addNode(), ShapeHandler::addPOI(), NBNode::bezierControlPoints(), GeoConvHelper::cartesian2geo(), TraCIServerAPI_Vehicle::commandDistanceRequest(), TraCIServerAPI_Simulation::commandDistanceRequest(), TraCIServerAPI_Simulation::commandPositionConversion(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), GNEApplicationWindow::handleEvent_NetworkLoaded(), GUICompleteSchemeStorage::init(), NBHeightMapper::loadTiff(), GUISettingsHandler::myStartElement(), GNEViewNet::onLeftBtnPress(), GNEViewNet::onMouseMove(), NLJunctionControlBuilder::openJunction(), operator>>(), TraCIServerAPI_GUI::processSet(), TraCIServer::readTypeCheckingPosition2D(), GUICompleteSchemeStorage::saveViewport(), NGNode::setX(), NGNode::setY(), GeoConvHelper::x2cartesian(), and GeoConvHelper::x2cartesian_const().
void Position::set (SUMOReal x, SUMOReal y, SUMOReal z) inline
Definition at line 84 of file Position.h.
References myX, myY, myZ, x(), y(), and z().
void Position::set (const Position & pos) inline
Definition at line 91 of file Position.h.
References myX, myY, and myZ.
void Position::sub (SUMOReal dx, SUMOReal dy) inline
Substracts the given position from this one.
Definition at line 139 of file Position.h.
References myX, and myY.
Referenced by NBNode::bezierControlPoints(), GeoConvHelper::cartesian2geo(), AGPosition::compute2dPosition(), GLHelper::drawTextBox(), PositionVector::extrapolate(), PositionVector::extrapolate2D(), NBNode::getEmptyDir(), and NBHeightMapper::Triangle::getZ().
void Position::sub (SUMOReal dx, SUMOReal dy, SUMOReal dz) inline
Substracts the given position from this one.
Definition at line 145 of file Position.h.
References myX, myY, and myZ.
void Position::sub (const Position & pos) inline
Substracts the given position from this one.
Definition at line 152 of file Position.h.
References myX, myY, and myZ.
SUMOReal Position::x () const inline
Returns the x-position.
Definition at line 63 of file Position.h.
References myX.
Referenced by Boundary::add(), PositionVector::add(), NIXMLNodesHandler::addNode(), GeomHelper::angle2D(), GUISettingsHandler::applyViewport(), Boundary::around(), PositionVector::around(), bezier(), NBNode::bezierControlPoints(), NIImporter_OpenDrive::calculateStraightEndPoint(), GeoConvHelper::cartesian2geo(), GUIDanielPerspectiveChanger::centerTo(), NGRandomNetBuilder::checkAngles(), GUISUMOAbstractView::checkGDALImage(), TraCIServerAPI_Simulation::commandPositionConversion(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), NGRandomNetBuilder::createNewNode(), GNEViewNet::doPaintGL(), GUIVehicle::drawAction_drawRailCarriages(), GNELane::drawArrows(), GUILane::drawArrows(), GLHelper::drawBoxLine(), GLHelper::drawBoxLines(), GNEDetector::drawDetectorIcon(), GLHelper::drawFilledPoly(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEJunction::drawGL(), GUITrafficLightLogicWrapper::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GUIPerson::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GNEEdge::drawGL(), GNEChargingStation::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GNECalibrator::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GNELane::drawLane2LaneConnections(), GUILane::drawLane2LaneConnections(), GLHelper::drawLine(), GUIBaseVehicle::drawLinkItem(), GUILane::drawLinkRule(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GUIE3Collector::MyWrapper::drawSingleCrossing(), GLHelper::drawText(), GUILane::drawTextAtEnd(), GLHelper::drawTextBox(), GLHelper::drawTriangleAtEnd(), MSVTypeProbe::execute(), NBNodeCont::extract(), GeomHelper::findLineCircleIntersections(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorE2::getAttribute(), GNECalibrator::getAttribute(), GUIPointOfInterest::getCenteringBoundary(), NBNode::getEmptyDir(), MSPModel_Striping::getNextLaneObstacles(), GNEAdditional::getPopUpMenu(), GNEDetectorEntry::getPositionInView(), GNEDetectorExit::getPositionInView(), GNEDetectorE1::getPositionInView(), GNEStoppingPlace::getPositionInView(), GNEVaporizer::getPositionInView(), GNERouteProbe::getPositionInView(), GNEDetectorE2::getPositionInView(), GNEDetector::getPositionOverLane(), MSVTKExport::getPositions(), TraCIServerAPI_InductionLoop::getTree(), GUIDanielPerspectiveChanger::getXPos(), NBHeightMapper::getZ(), GNEInternalLane::GNEInternalLane(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), GUIJunctionWrapper::GUIJunctionWrapper(), GUILane::GUILane(), NBNodeCont::insert(), PositionVector::intersects(), isLeft(), PositionVector::isLeft(), NBHeightMapper::loadTiff(), GNEDetector::moveAdditional(), GNEEdge::moveGeometry(), MSPModel_Striping::moveInDirection(), GUISettingsHandler::myStartElement(), GUIMEInductLoop::MyWrapper::MyWrapper(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), GeomHelper::nearest_offset_on_line_to_point2D(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GNEViewNet::onMouseMove(), PositionVector::as_poly_cw_sorter::operator()(), PositionVector::increasing_x_y_sorter::operator()(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Junction::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_GUI::processSet(), NBNodeCont::retrieve(), set(), GNEAdditional::setBlockIconRotation(), GUIBaseVehicle::setFunctionalColor(), GNEJunction::setPosition(), GUIDialog_EditViewport::setValues(), GUICompleteSchemeStorage::setViewport(), GUISUMOAbstractView::setViewportFromTo(), NGNode::setY(), PositionVector::sideOffset(), NBEdge::startShapeAt(), NBNetBuilder::transformCoordinates(), GNEAdditionalSet::updateConnections(), GNEDetectorEntry::updateGeometry(), GNEDetectorExit::updateGeometry(), GNEConnection::updateGeometry(), GNEDetectorE1::updateGeometry(), GNECrossing::updateGeometry(), GNEChargingStation::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEContainerStop::updateGeometry(), GNEBusStop::updateGeometry(), GNECalibrator::updateGeometry(), GNEJunction::updateGeometry(), GNELane::updateGeometry(), GUISUMOAbstractView::updatePositionInformation(), MSEmissionExport::write(), MSBatteryExport::write(), MSFCDExport::write(), GNEDetectorEntry::writeAdditional(), GNEDetectorExit::writeAdditional(), GNEDetectorE1::writeAdditional(), GNEDetectorE2::writeAdditional(), GNEVariableSpeedSignal::writeAdditional(), GNEDetectorE3::writeAdditional(), GNECalibrator::writeAdditional(), GNERerouter::writeAdditional(), NBSign::writeAsPOI(), NWWriter_OpenDrive::writeGeomLines(), NWWriter_DlrNavteq::writeNodesUnsplitted(), BinaryFormatter::writePosition(), NWFrame::writePositionLong(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), GeoConvHelper::x2cartesian(), GeoConvHelper::x2cartesian_const(), and GUIDanielPerspectiveChanger::zoom().
SUMOReal Position::y () const inline
Returns the y-position.
Definition at line 68 of file Position.h.
References myY.
Referenced by Boundary::add(), PositionVector::add(), NIXMLNodesHandler::addNode(), GeomHelper::angle2D(), GUISettingsHandler::applyViewport(), Boundary::around(), PositionVector::around(), bezier(), NBNode::bezierControlPoints(), NIImporter_OpenDrive::calculateStraightEndPoint(), GeoConvHelper::cartesian2geo(), GUIDanielPerspectiveChanger::centerTo(), NGRandomNetBuilder::checkAngles(), GUISUMOAbstractView::checkGDALImage(), TraCIServerAPI_Simulation::commandPositionConversion(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), NGRandomNetBuilder::createNewNode(), GNEViewNet::doPaintGL(), GUIVehicle::drawAction_drawRailCarriages(), GNELane::drawArrows(), GUILane::drawArrows(), GLHelper::drawBoxLine(), GLHelper::drawBoxLines(), GNEDetector::drawDetectorIcon(), GLHelper::drawFilledPoly(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEJunction::drawGL(), GUITrafficLightLogicWrapper::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GUIPerson::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GNEEdge::drawGL(), GNEChargingStation::drawGL(), GUIChargingStation::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GNELane::drawLane2LaneConnections(), GUILane::drawLane2LaneConnections(), GLHelper::drawLine(), GUIBaseVehicle::drawLinkItem(), GUILane::drawLinkRule(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GUIE3Collector::MyWrapper::drawSingleCrossing(), GLHelper::drawText(), GUILane::drawTextAtEnd(), GLHelper::drawTextBox(), GLHelper::drawTriangleAtEnd(), MSVTypeProbe::execute(), NBNodeCont::extract(), GeomHelper::findLineCircleIntersections(), GUIPointOfInterest::getCenteringBoundary(), NBNode::getEmptyDir(), MSPModel_Striping::getNextLaneObstacles(), GNEAdditional::getPopUpMenu(), GNEVaporizer::getPositionInView(), GNERouteProbe::getPositionInView(), MSVTKExport::getPositions(), TraCIServerAPI_InductionLoop::getTree(), GUIDanielPerspectiveChanger::getYPos(), NBHeightMapper::getZ(), GNEInternalLane::GNEInternalLane(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), GUIJunctionWrapper::GUIJunctionWrapper(), GUILane::GUILane(), NBNodeCont::insert(), PositionVector::intersects(), isLeft(), PositionVector::isLeft(), NBHeightMapper::loadTiff(), GNEEdge::moveGeometry(), MSPModel_Striping::moveInDirection(), GUISettingsHandler::myStartElement(), GUIMEInductLoop::MyWrapper::MyWrapper(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), GeomHelper::nearest_offset_on_line_to_point2D(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), PositionVector::as_poly_cw_sorter::operator()(), PositionVector::increasing_x_y_sorter::operator()(), TraCIServerAPI_Junction::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_GUI::processSet(), NBNodeCont::retrieve(), set(), GUIBaseVehicle::setFunctionalColor(), GNEJunction::setPosition(), GUIDialog_EditViewport::setValues(), GUICompleteSchemeStorage::setViewport(), GUISUMOAbstractView::setViewportFromTo(), NGNode::setX(), PositionVector::sideOffset(), NBEdge::startShapeAt(), NBNetBuilder::transformCoordinates(), GNEAdditionalSet::updateConnections(), GNEConnection::updateGeometry(), GNECrossing::updateGeometry(), GNEChargingStation::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEContainerStop::updateGeometry(), GNEBusStop::updateGeometry(), GNEJunction::updateGeometry(), GNELane::updateGeometry(), GUISUMOAbstractView::updatePositionInformation(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), GNEVariableSpeedSignal::writeAdditional(), GNEDetectorE3::writeAdditional(), GNERerouter::writeAdditional(), NBSign::writeAsPOI(), NWWriter_OpenDrive::writeGeomLines(), NWWriter_DlrNavteq::writeNodesUnsplitted(), BinaryFormatter::writePosition(), NWFrame::writePositionLong(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), GeoConvHelper::x2cartesian(), GeoConvHelper::x2cartesian_const(), and GUIDanielPerspectiveChanger::zoom().
SUMOReal Position::z () const inline
Returns the z-position.
Definition at line 73 of file Position.h.
References myZ.
Referenced by PositionVector::add(), GUISettingsHandler::applyViewport(), NBNode::bezierControlPoints(), TraCIServerAPI_Simulation::commandPositionConversion(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), NBNode::computeSmoothShape(), MSVTypeProbe::execute(), GNELane::getPopUpMenu(), GUILane::getPopUpMenu(), MSVTKExport::getPositions(), PositionVector::move2side(), GNEEdge::moveGeometry(), GUISettingsHandler::myStartElement(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), GNENet::registerJunction(), set(), GUIDialog_EditViewport::setValues(), GUICompleteSchemeStorage::setViewport(), GUISUMOAbstractView::setViewportFromTo(), PositionVector::slopeDegreeAtOffset(), NBEdge::startShapeAt(), MSFCDExport::write(), NWWriter_OpenDrive::writeGeomLines(), BinaryFormatter::writePosition(), NWFrame::writePositionLong(), and MSFCDExport::writeTransportable().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Position & p) friend
Prints to the output.
Definition at line 165 of file Position.h.
Field Documentation
const Position Position::INVALID static
Definition at line 261 of file Position.h.
Referenced by NBNode::bezierControlPoints(), MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), MSVehicle::executeMove(), NLShapeHandler::getLanePos(), PCLoaderXML::getLanePos(), GNEApplicationWindow::GNEShapeHandler::getLanePos(), MSPModel_Striping::PState::getPosition(), MSTransportable::Stage_Driving::getPosition(), MSVehicle::getPosition(), PositionVector::intersectionPosition2D(), PositionVector::move2side(), MSPModel_Striping::moveInDirection(), GUIDialog_EditViewport::onCmdChanged(), GUIDialog_EditViewport::onCmdOk(), PositionVector::positionAtOffset(), PositionVector::positionAtOffset2D(), MSPerson::MSPersonStage_Driving::proceed(), GUISUMOAbstractView::showViewportEditor(), MSLaneChangerSublane::startChangeSublane(), and PositionVector::transformToVectorCoordinates().
SUMOReal Position::myX private
The x-position.
Definition at line 265 of file Position.h.
Referenced by add(), angleTo2D(), crossProduct(), distanceSquaredTo(), distanceSquaredTo2D(), dotProduct(), mul(), norm2d(), operator!=(), operator*(), operator+(), operator-(), operator<(), operator==(), set(), sub(), and x().
SUMOReal Position::myY private
The y-position.
Definition at line 268 of file Position.h.
Referenced by add(), angleTo2D(), crossProduct(), distanceSquaredTo(), distanceSquaredTo2D(), dotProduct(), mul(), norm2d(), operator!=(), operator*(), operator+(), operator-(), operator<(), operator==(), set(), sub(), and y().
SUMOReal Position::myZ private
The z-position.
Definition at line 271 of file Position.h.
Referenced by add(), crossProduct(), distanceSquaredTo(), dotProduct(), mul(), operator!=(), operator*(), operator+(), operator-(), operator<(), operator==(), set(), sub(), and z().
The documentation for this class was generated from the following files:
Position.h
Position.cpp