SUMO - Simulation of Urban MObility: NBNodeShapeComputer.cpp File Reference
NBNodeShapeComputer.cpp File Reference
#include <config.h>
#include <algorithm>
#include <iterator>
#include <utils/geom/PositionVector.h>
#include <utils/options/OptionsCont.h>
#include <utils/geom/GeomHelper.h>
#include <utils/common/StdDefs.h>
#include <utils/common/MsgHandler.h>
#include <utils/common/UtilExceptions.h>
#include <utils/common/ToString.h>
#include <utils/iodevices/OutputDevice.h>
#include "NBNode.h"
#include "NBNodeShapeComputer.h"
Functions
void computeSameEnd (PositionVector &l1, PositionVector &l2)
Detailed Description
Author
Daniel Krajzewicz
Jakob Erdmann
Michael Behrisch
Date
Sept 2002
Version
Id
NBNodeShapeComputer.cpp 20433 2016-04-13 08:00:14Z behrisch
Definition in file NBNodeShapeComputer.cpp.
Function Documentation
void computeSameEnd (PositionVector & l1, PositionVector & l2)
Definition at line 114 of file NBNodeShapeComputer.cpp.
References PositionVector::add(), PositionVector::extrapolate2D(), PositionVector::getSubpart2D(), PositionVector::intersects(), PositionVector::intersectsAtLengths2D(), PositionVector::length2D(), POSITION_EPS, PositionVector::positionAtOffset2D(), and SUMOReal.
Referenced by NBNodeShapeComputer::computeUniqueDirectionList().