SUMO - Simulation of Urban MObility: MSInductLoop Class Reference
MSInductLoop Class Reference
An unextended detector measuring at a fixed position on a fixed lane.
#include <MSInductLoop.h>
Data Structures
struct VehicleData
Struct to store the data of the counted vehicle internally.
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED
}
Definition of a vehicle state.
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
virtual std::vector< VehicleData > collectVehiclesOnDet (SUMOTime t, bool leaveTime=false) const
Returns vehicle data for vehicles that have been on the detector starting at the given time.
const std::string & getDescription () const
const std::string & getID () const
Returns the id.
const MSLane * getLane () const
Returns the lane the reminder works on.
SUMOReal getPosition () const
Returns the position of the detector on the lane.
MSInductLoop (const std::string &id, MSLane *const lane, SUMOReal positionInMeters, bool splitByType)
Constructor.
virtual void notifyMoveInternal (SUMOVehicle &veh, SUMOReal timeOnLane, SUMOReal speed)
Internal notification about the vehicle moves.
virtual void reset ()
Resets all generated values to allow computation of next interval.
void setDescription (const std::string &description)
void setID (const std::string &newID)
resets the id
~MSInductLoop ()
Destructor.
Methods inherited from MSMoveReminder
bool notifyEnter (SUMOVehicle &veh, Notification reason)
Checks whether the reminder is activated by a vehicle entering the lane.
bool notifyMove (SUMOVehicle &veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed)
Checks whether the vehicle shall be counted and/or shall still touch this MSMoveReminder.
bool notifyLeave (SUMOVehicle &veh, SUMOReal lastPos, MSMoveReminder::Notification reason)
Dismisses the vehicle if it is on the detector due to a lane change.
Methods returning current values
SUMOReal getCurrentSpeed () const
Returns the speed of the vehicle on the detector.
SUMOReal getCurrentLength () const
Returns the length of the vehicle on the detector.
SUMOReal getCurrentOccupancy () const
Returns the current occupancy.
int getCurrentPassedNumber () const
Returns the number of vehicles that have passed the detector.
std::vector< std::string > getCurrentVehicleIDs () const
Returns the ids of vehicles that have passed the detector.
SUMOReal getTimestepsSinceLastDetection () const
Returns the time since the last vehicle left the detector.
Methods inherited from MSDetectorFileOutput.
void writeXMLOutput (OutputDevice &dev, SUMOTime startTime, SUMOTime stopTime)
Writes collected values into the given stream.
void writeXMLDetectorProlog (OutputDevice &dev) const
Opens the XML-output using "detector" as root element.
Interface methods, to be derived by subclasses
void updateDetector (SUMOVehicle &veh, SUMOReal entryPos, SUMOReal leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp)
Virtual methods to implement by derived classes
virtual void detectorUpdate (const SUMOTime step)
Updates the detector (computes values)
virtual GUIDetectorWrapper * buildDetectorGUIRepresentation ()
Builds the graphical representation.
Static Public Member Functions
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
Protected Types
typedef std::deque< VehicleData > VehicleDataCont
Type of myVehicleDataCont.
typedef std::map< SUMOVehicle *, SUMOReal > VehicleMap
Type of myVehiclesOnDet.
Protected Member Functions
void removeFromVehicleUpdateValues (SUMOVehicle &veh)
void writeTypedXMLOutput (OutputDevice &dev, SUMOTime startTime, SUMOTime stopTime, const std::string &type, const VehicleDataCont &vdc, const VehicleMap &vm)
Methods that add and remove vehicles from internal container
virtual void enterDetectorByMove (SUMOVehicle &veh, SUMOReal entryTimestep)
Introduces a vehicle to the detector's map myVehiclesOnDet.
virtual void leaveDetectorByMove (SUMOVehicle &veh, SUMOReal leaveTimestep)
Processes a vehicle that leaves the detector.
virtual void leaveDetectorByLaneChange (SUMOVehicle &veh, SUMOReal lastPos)
Removes a vehicle from the detector's map myVehiclesOnDet.
Static Protected Member Functions
Function for summing up values
static SUMOReal speedSum (SUMOReal sumSoFar, const MSInductLoop::VehicleData &data)
Adds up VehicleData::speedM.
static SUMOReal lengthSum (SUMOReal sumSoFar, const MSInductLoop::VehicleData &data)
Adds up VehicleData::lengthM.
Protected Attributes
std::string myDescription
a description of this moveReminder
int myDismissedVehicleNumber
The number of dismissed vehicles.
std::string myID
The name of the object.
MSLane *const myLane
Lane on which the reminder works.
SUMOReal myLastLeaveTime
Leave-time of the last vehicle detected [s].
SUMOReal myLastOccupancy
Occupancy by the last vehicle detected.
VehicleDataCont myLastVehicleDataCont
Data of vehicles that have completely passed the detector in the last time interval.
const SUMOReal myPosition
Detector's position on lane [m].
bool mySplitByType
Whether additional information split by vehicle classes shall be generated.
VehicleDataCont myVehicleDataCont
Data of vehicles that have completely passed the detector.
VehicleMap myVehiclesOnDet
Data for vehicles that have entered the detector (vehicle -> enter time)
Private Member Functions
MSInductLoop (const MSInductLoop &)
Invalidated copy constructor.
MSInductLoop & operator= (const MSInductLoop &)
Invalidated assignment operator.
Detailed Description
An unextended detector measuring at a fixed position on a fixed lane.
Only vehicles that passed the entire detector are counted. We ignore vehicles that are emitted onto the detector and vehicles that change their lane while they are on the detector, because we cannot determine a meaningful enter/leave-times.
This detector uses the MSMoveReminder mechanism, i.e. the vehicles call the detector if they pass it.
See also
MSMoveReminder
MSDetectorFileOutput
Definition at line 71 of file MSInductLoop.h.
Member Typedef Documentation
typedef std::deque< VehicleData > MSInductLoop::VehicleDataCont protected
Type of myVehicleDataCont.
Definition at line 357 of file MSInductLoop.h.
typedef std::map< SUMOVehicle*, SUMOReal > MSInductLoop::VehicleMap protected
Type of myVehiclesOnDet.
Definition at line 367 of file MSInductLoop.h.
Member Enumeration Documentation
enum MSMoveReminder::Notification inherited
Definition of a vehicle state.
Enumerator
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network)
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only)
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only)
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted)
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
Definition at line 95 of file MSMoveReminder.h.
Constructor & Destructor Documentation
MSInductLoop::MSInductLoop (const std::string & id, MSLane *const lane, SUMOReal positionInMeters, bool splitByType)
Constructor.
Adds reminder to MSLane.
Parameters
[in] id Unique id
[in] lane Lane where detector woks on
[in] position Position of the detector within the lane
[in] splitByType Whether additional information split by vehicle classes shall be generated
Definition at line 60 of file MSInductLoop.cpp.
References myPosition, and reset().
MSInductLoop::~MSInductLoop ()
Destructor.
Definition at line 73 of file MSInductLoop.cpp.
MSInductLoop::MSInductLoop (const MSInductLoop &) private
Invalidated copy constructor.
Member Function Documentation
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
virtual GUIDetectorWrapper* MSDetectorFileOutput::buildDetectorGUIRepresentation () inline virtual inherited
Builds the graphical representation.
Meant to be overridden by graphical versions of the detectors
Returns
A wrapper for the detector which performs the user I/O within the GUI
Reimplemented in GUI_E2_ZS_Collector, GUIInductLoop, GUIE3Collector, GUI_E2_ZS_CollectorOverLanes, GUIInstantInductLoop, and GUIMEInductLoop.
Definition at line 123 of file MSDetectorFileOutput.h.
References MSDetectorFileOutput::MSDetectorFileOutput(), and MSDetectorFileOutput::operator=().
std::vector< MSInductLoop::VehicleData > MSInductLoop::collectVehiclesOnDet (SUMOTime t, bool leaveTime = false) const virtual
Returns vehicle data for vehicles that have been on the detector starting at the given time.
Parameters
[in] t The time from which vehicles shall be counted
[in] leaveTime Whether entryTime or leaveTime shall be compared against t (the latter gives a more complete picture but may include vehicles in multiple steps even if they did not stay on the detector)
Returns
The list of vehicles
Reimplemented in GUIInductLoop.
Definition at line 322 of file MSInductLoop.cpp.
References SUMOVehicle::getID(), MSVehicleType::getID(), MSVehicleType::getLength(), SUMOVehicle::getSpeed(), SUMOVehicle::getVehicleType(), HAS_NOT_LEFT_DETECTOR, myLastVehicleDataCont, myVehicleDataCont, myVehiclesOnDet, MSInductLoop::VehicleData::speedM, STEPS2TIME, and SUMOReal.
Referenced by GUIInductLoop::collectVehiclesOnDet(), getCurrentLength(), getCurrentOccupancy(), getCurrentPassedNumber(), getCurrentSpeed(), getCurrentVehicleIDs(), and TraCIServerAPI_InductionLoop::processGet().
virtual void MSDetectorFileOutput::detectorUpdate (const SUMOTime step) inline virtual inherited
Updates the detector (computes values)
Parameters
[in] step The current time step
Reimplemented in MSMeanData, MSE3Collector, MSMeanData_Harmonoise, and MSE2Collector.
Definition at line 113 of file MSDetectorFileOutput.h.
References UNUSED_PARAMETER.
void MSInductLoop::enterDetectorByMove (SUMOVehicle & veh, SUMOReal entryTimestep) protected virtual
Introduces a vehicle to the detector's map myVehiclesOnDet.
Parameters
veh The entering vehicle.
entryTimestep Timestep (not necessary integer) of entrance.
Reimplemented in GUIInductLoop.
Definition at line 289 of file MSInductLoop.cpp.
References myVehiclesOnDet.
Referenced by GUIInductLoop::enterDetectorByMove(), and notifyMove().
SUMOReal MSInductLoop::getCurrentLength () const
Returns the length of the vehicle on the detector.
If no vehicle is on the detector, -1 is returned, otherwise this vehicle's length.
Returns
The length [m] of the vehicle if one is on the detector, -1 otherwise
Definition at line 154 of file MSInductLoop.cpp.
References collectVehiclesOnDet(), DELTA_T, MSNet::getInstance(), lengthSum(), and SUMOReal.
Referenced by GUIInductLoop::MyWrapper::getParameterWindow(), getPosition(), and TraCIServerAPI_InductionLoop::processGet().
SUMOReal MSInductLoop::getCurrentOccupancy () const
Returns the current occupancy.
If a vehicle is on the detector, 1 is returned. If a vehicle has passed the detector in this timestep, its occupancy value is returned. If no vehicle has passed, 0 is returned.
Returns
This detector's current occupancy
Todo:
recheck (especially if more than one vehicle has passed)
Definition at line 163 of file MSInductLoop.cpp.
References collectVehiclesOnDet(), DELTA_T, MSNet::getCurrentTimeStep(), MSNet::getInstance(), HAS_NOT_LEFT_DETECTOR, MAX2(), MIN2(), STEPS2TIME, SUMOReal, and TS.
Referenced by GUIInductLoop::MyWrapper::getParameterWindow(), getPosition(), and TraCIServerAPI_InductionLoop::processGet().
int MSInductLoop::getCurrentPassedNumber () const
Returns the number of vehicles that have passed the detector.
If a vehicle is on the detector, 1 is returned. If a vehicle has passed the detector in this timestep, 1 is returned. If no vehicle has passed, 0 is returned.
Returns
The number of vehicles that have passed the detector
Todo:
recheck (especially if more than one vehicle has passed)
Definition at line 182 of file MSInductLoop.cpp.
References collectVehiclesOnDet(), DELTA_T, and MSNet::getInstance().
Referenced by GUIInductLoop::MyWrapper::getParameterWindow(), getPosition(), and TraCIServerAPI_InductionLoop::processGet().
SUMOReal MSInductLoop::getCurrentSpeed () const
Returns the speed of the vehicle on the detector.
If no vehicle is on the detector, -1 is returned, otherwise this vehicle's current speed.
Returns
The speed [m/s] of the vehicle if one is on the detector, -1 otherwise
Definition at line 145 of file MSInductLoop.cpp.
References collectVehiclesOnDet(), DELTA_T, MSNet::getInstance(), speedSum(), and SUMOReal.
Referenced by GUIInductLoop::MyWrapper::getParameterWindow(), getPosition(), and TraCIServerAPI_InductionLoop::processGet().
std::vector< std::string > MSInductLoop::getCurrentVehicleIDs () const
Returns the ids of vehicles that have passed the detector.
Returns
The ids of vehicles that have passed the detector
Todo:
recheck (especially if more than one vehicle has passed)
Definition at line 189 of file MSInductLoop.cpp.
References collectVehiclesOnDet(), DELTA_T, MSNet::getInstance(), and SUMOReal.
Referenced by getPosition(), and TraCIServerAPI_InductionLoop::processGet().
const std::string& MSMoveReminder::getDescription () const inline inherited
Definition at line 213 of file MSMoveReminder.h.
References MSMoveReminder::myDescription, and MSMoveReminder::removeFromVehicleUpdateValues().
Referenced by MSBaseVehicle::addStops().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciBusOrContainerStop(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNEConnectorFrame::buildIinternalLanes(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), NLDetectorBuilder::convUncontE2PosLength(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSVehicle::getBackPosition(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), GNEEdge::getDest(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), MSE2Collector::getEstimateQueueLength(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), GNEEdge::getSource(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSE2Collector::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_SL2015::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_LC2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_ArealDetector::processGet(), TraCIServerAPI_Lane::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), MSBaseVehicle::reroute(), MSLane::resetPartialOccupation(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), MSLane::saveState(), MSDevice_Battery::setAirDragCoefficient(), NBNodeCont::setAsTLControlled(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), MSDevice_Battery::setConstantPowerIntake(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), MSDevice_Battery::setFrontSurfaceArea(), MSDevice_Battery::setInternalMomentOfInertia(), GNEJunction::setLogicValid(), MSDevice_Battery::setMass(), MSDevice_Battery::setMaximumBatteryCapacity(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSDevice_Battery::setPropulsionEfficiency(), MSDevice_Battery::setRadialDragCoefficient(), MSDevice_Battery::setRecuperationEfficiency(), MSLink::setRequestInformation(), MSDevice_Battery::setRollDragCoefficient(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), operator<<(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
const MSLane* MSMoveReminder::getLane () const inline inherited
Returns the lane the reminder works on.
Returns
The lane the reminder works on.
Definition at line 89 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by MSDevice_Tripinfo::computeLengthAndDuration(), MSE2Collector::detectorUpdate(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_InductionLoop::getTree(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_ArealDetector::processGet(), and MSMeanData::writeEdge().
SUMOReal MSInductLoop::getPosition () const inline
Returns the position of the detector on the lane.
Returns
The detector's position in meters
Definition at line 100 of file MSInductLoop.h.
References getCurrentLength(), getCurrentOccupancy(), getCurrentPassedNumber(), getCurrentSpeed(), getCurrentVehicleIDs(), getTimestepsSinceLastDetection(), myPosition, notifyEnter(), notifyLeave(), notifyMove(), SUMOReal, writeXMLDetectorProlog(), and writeXMLOutput().
Referenced by TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_InductionLoop::getTree(), and TraCIServerAPI_InductionLoop::processGet().
SUMOReal MSInductLoop::getTimestepsSinceLastDetection () const
Returns the time since the last vehicle left the detector.
Returns
Timesteps from last leaving (detection) of the detector
Definition at line 200 of file MSInductLoop.cpp.
References MSNet::getInstance(), myLastLeaveTime, myVehiclesOnDet, and STEPS2TIME.
Referenced by MSActuatedTrafficLightLogic::gapControl(), GUIInductLoop::MyWrapper::getParameterWindow(), getPosition(), and TraCIServerAPI_InductionLoop::processGet().
void MSInductLoop::leaveDetectorByLaneChange (SUMOVehicle & veh, SUMOReal lastPos) protected virtual
Removes a vehicle from the detector's map myVehiclesOnDet.
Parameters
veh The leaving vehicle.
lastPos The last position of the leaving vehicle.
Reimplemented in GUIInductLoop.
Definition at line 311 of file MSInductLoop.cpp.
References myDismissedVehicleNumber, myPosition, and myVehiclesOnDet.
Referenced by GUIInductLoop::leaveDetectorByLaneChange(), and notifyLeave().
void MSInductLoop::leaveDetectorByMove (SUMOVehicle & veh, SUMOReal leaveTimestep) protected virtual
Processes a vehicle that leaves the detector.
Removes a vehicle from the detector's map myVehiclesOnDet and adds the vehicle data to the internal myVehicleDataCont.
Parameters
veh The leaving vehicle.
leaveTimestep Timestep (not necessary integer) of leaving.
Reimplemented in GUIInductLoop.
Definition at line 296 of file MSInductLoop.cpp.
References SUMOVehicle::getID(), MSVehicleType::getID(), MSVehicleType::getLength(), SUMOVehicle::getVehicleType(), myLastLeaveTime, myLastOccupancy, myVehicleDataCont, myVehiclesOnDet, and SUMOReal.
Referenced by GUIInductLoop::leaveDetectorByMove(), and notifyMove().
static SUMOReal MSInductLoop::lengthSum (SUMOReal sumSoFar, const MSInductLoop::VehicleData & data) inline static protected
Adds up VehicleData::lengthM.
Definition at line 333 of file MSInductLoop.h.
References MSInductLoop::VehicleData::lengthM.
Referenced by getCurrentLength(), and writeTypedXMLOutput().
bool MSInductLoop::notifyEnter (SUMOVehicle & veh, Notification reason) virtual
Checks whether the reminder is activated by a vehicle entering the lane.
Lane change means in this case that the vehicle changes to the lane the reminder is placed at.
Parameters
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns
True if vehicle enters the induction loop
See also
Notification
Reimplemented from MSMoveReminder.
Definition at line 86 of file MSInductLoop.cpp.
References MSNet::getInstance(), MSVehicleType::getLength(), SUMOVehicle::getPositionOnLane(), SUMOVehicle::getVehicleType(), myPosition, myVehiclesOnDet, MSMoveReminder::NOTIFICATION_DEPARTED, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSMoveReminder::NOTIFICATION_PARKING, MSMoveReminder::NOTIFICATION_TELEPORT, STEPS2TIME, and SUMOReal.
Referenced by getPosition().
bool MSInductLoop::notifyLeave (SUMOVehicle & veh, SUMOReal lastPos, MSMoveReminder::Notification reason) virtual
Dismisses the vehicle if it is on the detector due to a lane change.
If the vehicle is on the detector, it will be dismissed by incrementing myDismissedVehicleNumber and removing this vehicle's entering time from myVehiclesOnDet.
Parameters
[in] veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] isArrival whether the vehicle arrived at its destination
[in] isLaneChange whether the vehicle changed from the lane
See also
leaveDetectorByLaneChange
MSMoveReminder
MSMoveReminder::notifyLeave
Reimplemented from MSMoveReminder.
Definition at line 135 of file MSInductLoop.cpp.
References leaveDetectorByLaneChange(), MSMoveReminder::NOTIFICATION_JUNCTION, and SUMOReal.
Referenced by getPosition().
bool MSInductLoop::notifyMove (SUMOVehicle & veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed) virtual
Checks whether the vehicle shall be counted and/or shall still touch this MSMoveReminder.
As soon a vehicle enters the detector, its entry time is computed and stored in myVehiclesOnDet via enterDetectorByMove. If it passes the detector, the according leaving time is computed and stored, too, using leaveDetectorByMove.
Parameters
[in] veh Vehicle that asks this remider.
[in] oldPos Position before move.
[in] newPos Position after move with newSpeed.
[in] newSpeed Moving speed.
Returns
True if vehicle hasn't passed the detector completely.
See also
MSMoveReminder
MSMoveReminder::notifyMove
enterDetectorByMove
leaveDetectorByMove
Reimplemented from MSMoveReminder.
Definition at line 102 of file MSInductLoop.cpp.
References enterDetectorByMove(), MSNet::getInstance(), MSVehicleType::getLength(), SUMOVehicle::getVehicleType(), leaveDetectorByMove(), myPosition, myVehiclesOnDet, STEPS2TIME, and SUMOReal.
Referenced by getPosition().
virtual void MSMoveReminder::notifyMoveInternal (SUMOVehicle & veh, SUMOReal timeOnLane, SUMOReal speed) inline virtual inherited
Internal notification about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] timeOnLane time the vehicle spent on the lane.
[in] speed Moving speed.
Reimplemented in MSMeanData::MeanDataValueTracker, MSDevice_Tripinfo, MSMeanData_Net::MSLaneMeanDataValues, MSMeanData_Harmonoise::MSLaneMeanDataValues, MSMeanData_Amitran::MSLaneMeanDataValues, and MSMeanData_Emissions::MSLaneMeanDataValues.
Definition at line 201 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
Referenced by MSMeanData::MeanDataValues::notifyMove(), and MSMoveReminder::updateDetector().
MSInductLoop& MSInductLoop::operator= (const MSInductLoop &) private
Invalidated assignment operator.
void MSMoveReminder::removeFromVehicleUpdateValues (SUMOVehicle & veh) protected inherited
Definition at line 94 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues.
Referenced by MSMoveReminder::getDescription(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), and MSMoveReminder::updateDetector().
void MSInductLoop::reset () virtual
Resets all generated values to allow computation of next interval.
Reimplemented from MSDetectorFileOutput.
Reimplemented in GUIInductLoop.
Definition at line 78 of file MSInductLoop.cpp.
References myDismissedVehicleNumber, myLastVehicleDataCont, and myVehicleDataCont.
Referenced by MSInductLoop(), GUIInductLoop::reset(), and writeXMLOutput().
void MSMoveReminder::setDescription (const std::string & description) inline inherited
Definition at line 209 of file MSMoveReminder.h.
References MSMoveReminder::myDescription.
Referenced by MSMeanData::init(), MEInductLoop::MEInductLoop(), METriggeredCalibrator::METriggeredCalibrator(), and MSCalibrator::MSCalibrator().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
static SUMOReal MSInductLoop::speedSum (SUMOReal sumSoFar, const MSInductLoop::VehicleData & data) inline static protected
Adds up VehicleData::speedM.
Definition at line 328 of file MSInductLoop.h.
References MSInductLoop::VehicleData::speedM.
Referenced by getCurrentSpeed(), and writeTypedXMLOutput().
void MSMoveReminder::updateDetector (SUMOVehicle & veh, SUMOReal entryPos, SUMOReal leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp) inherited
Definition at line 51 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues, MSMoveReminder::notifyMoveInternal(), MSMoveReminder::removeFromVehicleUpdateValues(), STEPS2TIME, and SUMOReal.
Referenced by MSMoveReminder::notifyLeave(), and MEVehicle::updateDetectorForWriting().
void MSInductLoop::writeTypedXMLOutput (OutputDevice & dev, SUMOTime startTime, SUMOTime stopTime, const std::string & type, const VehicleDataCont & vdc, const VehicleMap & vm) protected
Definition at line 249 of file MSInductLoop.cpp.
References StringUtils::escapeXML(), Named::getID(), lengthSum(), MAX2(), MIN2(), myDismissedVehicleNumber, speedSum(), STEPS2TIME, SUMOReal, and time2string().
Referenced by writeXMLOutput().
void MSInductLoop::writeXMLDetectorProlog (OutputDevice & dev) const virtual
Opens the XML-output using "detector" as root element.
Parameters
[in] dev The output device to write the root into
See also
MSDetectorFileOutput::writeXMLDetectorProlog
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSDetectorFileOutput.
Definition at line 210 of file MSInductLoop.cpp.
References OutputDevice::writeXMLHeader().
Referenced by getPosition().
void MSInductLoop::writeXMLOutput (OutputDevice & dev, SUMOTime startTime, SUMOTime stopTime) virtual
Writes collected values into the given stream.
Parameters
[in] dev The output device to write the data into
[in] startTime First time step the data were gathered
[in] stopTime Last time step the data were gathered
See also
MSDetectorFileOutput::writeXMLOutput
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSDetectorFileOutput.
Definition at line 216 of file MSInductLoop.cpp.
References mySplitByType, myVehicleDataCont, myVehiclesOnDet, reset(), and writeTypedXMLOutput().
Referenced by getPosition().
Field Documentation
std::string MSMoveReminder::myDescription protected inherited
a description of this moveReminder
Definition at line 225 of file MSMoveReminder.h.
Referenced by MSMoveReminder::getDescription(), and MSMoveReminder::setDescription().
int MSInductLoop::myDismissedVehicleNumber protected
The number of dismissed vehicles.
Definition at line 353 of file MSInductLoop.h.
Referenced by leaveDetectorByLaneChange(), reset(), and writeTypedXMLOutput().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
MSLane* const MSMoveReminder::myLane protected inherited
Lane on which the reminder works.
Definition at line 223 of file MSMoveReminder.h.
Referenced by MSE2Collector::detectorUpdate(), MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSMoveReminder::getLane(), MSE2Collector::MSE2Collector(), MSMoveReminder::MSMoveReminder(), MSE2Collector::notifyEnter(), MSE2Collector::notifyMove(), MSE2Collector::by_vehicle_position_sorter::operator()(), and MSMeanData::MeanDataValueTracker::reset().
SUMOReal MSInductLoop::myLastLeaveTime protected
Leave-time of the last vehicle detected [s].
Definition at line 347 of file MSInductLoop.h.
Referenced by getTimestepsSinceLastDetection(), and leaveDetectorByMove().
SUMOReal MSInductLoop::myLastOccupancy protected
Occupancy by the last vehicle detected.
Definition at line 350 of file MSInductLoop.h.
Referenced by leaveDetectorByMove().
VehicleDataCont MSInductLoop::myLastVehicleDataCont protected
Data of vehicles that have completely passed the detector in the last time interval.
Definition at line 363 of file MSInductLoop.h.
Referenced by collectVehiclesOnDet(), and reset().
const SUMOReal MSInductLoop::myPosition protected
Detector's position on lane [m].
Definition at line 341 of file MSInductLoop.h.
Referenced by GUIInductLoop::buildDetectorGUIRepresentation(), getPosition(), leaveDetectorByLaneChange(), MSInductLoop(), notifyEnter(), and notifyMove().
bool MSInductLoop::mySplitByType protected
Whether additional information split by vehicle classes shall be generated.
Definition at line 344 of file MSInductLoop.h.
Referenced by writeXMLOutput().
VehicleDataCont MSInductLoop::myVehicleDataCont protected
Data of vehicles that have completely passed the detector.
Definition at line 360 of file MSInductLoop.h.
Referenced by collectVehiclesOnDet(), leaveDetectorByMove(), reset(), and writeXMLOutput().
VehicleMap MSInductLoop::myVehiclesOnDet protected
Data for vehicles that have entered the detector (vehicle -> enter time)
Definition at line 370 of file MSInductLoop.h.
Referenced by collectVehiclesOnDet(), enterDetectorByMove(), getTimestepsSinceLastDetection(), leaveDetectorByLaneChange(), leaveDetectorByMove(), notifyEnter(), notifyMove(), and writeXMLOutput().
The documentation for this class was generated from the following files:
MSInductLoop.h
MSInductLoop.cpp