SUMO - Simulation of Urban MObility: RORouteHandler Class Reference
RORouteHandler Class Reference
Parser and container for routes during their loading.
#include <RORouteHandler.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
SUMOTime getFirstDepart () const
returns the first departure time that was ever read
SUMOTime getLastDepart () const
Returns the last loaded depart time.
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
RORouteHandler (RONet &net, const std::string &file, const bool tryRepair, const bool emptyDestinationsAllowed, const bool ignoreErrors)
standard constructor
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
virtual ~RORouteHandler ()
standard destructor
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Static Public Member Functions
static bool checkStopPos (SUMOReal &startPos, SUMOReal &endPos, const SUMOReal laneLength, const SUMOReal minLength, const bool friendlyPos)
check start and end position of a stop
Protected Member Functions
void addParam (const SUMOSAXAttributes &attrs)
assign arbitrary vehicle parameters
bool addPersonTrip (const SUMOSAXAttributes &attrs)
add a routing request for a walking person
void addStop (const SUMOSAXAttributes &attrs)
Processing of a stop.
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
bool checkLastDepart ()
Checks whether the route file is sorted by departure time if needed.
void closeContainer ()
Ends the processing of a container.
void closeFlow ()
Ends the processing of a flow.
void closePerson ()
Ends the processing of a person.
void closeRoute (const bool mayBeDisconnected=false)
void closeRouteDistribution ()
void closeVehicle ()
Ends the processing of a vehicle.
void closeVehicleTypeDistribution ()
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
void openRoute (const SUMOSAXAttributes &attrs)
void openRouteDistribution (const SUMOSAXAttributes &attrs)
void openVehicleTypeDistribution (const SUMOSAXAttributes &attrs)
void parseEdges (const std::string &desc, ConstROEdgeVector &into, const std::string &rid)
Parse edges from strings.
void parseFromViaTo (std::string element, const SUMOSAXAttributes &attrs)
Called for parsing from and to and the corresponding taz attributes.
bool parseStop (SUMOVehicleParameter::Stop &stop, const SUMOSAXAttributes &attrs, std::string errorSuffix, MsgHandler *const errorOutput)
parses attributes common to all stops
void registerLastDepart ()
save last depart (only to be used if vehicle is not discarded)
inherited from GenericSAXHandler
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
virtual void myEndElement (int element)
Called when a closing tag occurs.
Protected Attributes
OutputDevice_String * myActiveContainerPlan
The plan of the current container.
int myActiveContainerPlanSize
The number of stages in myActiveContainerPlan.
ROPerson * myActivePerson
The plan of the current person.
ConstROEdgeVector myActiveRoute
The current route.
const RGBColor * myActiveRouteColor
The currently parsed route's color.
std::string myActiveRouteID
The id of the current route.
SUMOReal myActiveRouteProbability
The probability of the current route.
std::string myActiveRouteRefID
The id of the route the current route references to.
std::vector< SUMOVehicleParameter::Stop > myActiveRouteStops
List of the stops on the parsed route.
SUMOTime myBeginDefault
The default value for flow begins.
RORouteDef * myCurrentAlternatives
The currently parsed route alternatives.
SUMOReal myCurrentCosts
The currently parsed route costs.
SUMOVTypeParameter * myCurrentVType
The currently parsed vehicle type.
RandomDistributor< SUMOVTypeParameter * > * myCurrentVTypeDistribution
The currently parsed distribution of vehicle types (probability->vehicle type)
std::string myCurrentVTypeDistributionID
The id of the currently parsed vehicle type distribution.
const bool myEmptyDestinationsAllowed
Information whether the "to" attribute is mandatory.
SUMOTime myEndDefault
The default value for flow ends.
MsgHandler *const myErrorOutput
Depending on the "ignore-errors" option different outputs are used.
SUMOTime myFirstDepart
the first read departure time
IDSupplier myIdSupplier
generates numerical ids
int myInsertStopEdgesAt
where stop edges can be inserted into the current route (-1 means no insertion)
SUMOTime myLastDepart
The insertion time of the vehicle read last.
RONet & myNet
The current route.
const bool myTryRepair
Information whether routes shall be repaired.
SUMOVehicleParameter * myVehicleParameter
Parameter of the current vehicle, trip, person, container or flow.
Private Member Functions
RORouteHandler & operator= (const RORouteHandler &s)
Invalidated assignment operator.
RORouteHandler (const RORouteHandler &s)
Invalidated copy constructor.
Detailed Description
Parser and container for routes during their loading.
RORouteHandler is the container for routes while they are build until their transfering to the MSNet::RouteDict The result of the operations are single MSNet::Route-instances
Definition at line 66 of file RORouteHandler.h.
Constructor & Destructor Documentation
RORouteHandler::RORouteHandler (RONet & net, const std::string & file, const bool tryRepair, const bool emptyDestinationsAllowed, const bool ignoreErrors)
standard constructor
Definition at line 64 of file RORouteHandler.cpp.
References myActiveRoute.
RORouteHandler::~RORouteHandler () virtual
standard destructor
Definition at line 82 of file RORouteHandler.cpp.
RORouteHandler::RORouteHandler (const RORouteHandler & s) private
Invalidated copy constructor.
Member Function Documentation
void SUMORouteHandler::addParam (const SUMOSAXAttributes & attrs) protected inherited
assign arbitrary vehicle parameters
Definition at line 249 of file SUMORouteHandler.cpp.
References Parameterised::addParameter(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getString(), SUMOSAXAttributes::hasAttribute(), SUMORouteHandler::myCurrentVType, SUMORouteHandler::myVehicleParameter, SUMO_ATTR_KEY, and SUMO_ATTR_VALUE.
Referenced by SUMORouteHandler::getFirstDepart(), and SUMORouteHandler::myStartElement().
bool RORouteHandler::addPersonTrip (const SUMOSAXAttributes & attrs) protected
add a routing request for a walking person
Definition at line 683 of file RORouteHandler.cpp.
References ROPerson::addTrip(), SUMOSAXAttributes::get(), RONet::getEdge(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::hasAttribute(), StringTokenizer::hasNext(), SUMOVehicleParameter::id, MsgHandler::inform(), myActivePerson, myErrorOutput, myNet, SUMORouteHandler::myVehicleParameter, NUMERICAL_EPS, SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_BUS_STOP, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_EDGES, SUMO_ATTR_FROM, SUMO_ATTR_MODES, SUMO_ATTR_TO, SUMO_ATTR_VTYPES, SUMOReal, SVC_BICYCLE, SVC_BUS, and SVC_PASSENGER.
Referenced by myStartElement().
void RORouteHandler::addStop (const SUMOSAXAttributes & attrs) protected virtual
Processing of a stop.
Implements SUMORouteHandler.
Definition at line 585 of file RORouteHandler.cpp.
References ROPerson::addStop(), SUMOVehicleParameter::Stop::busstop, SUMORouteHandler::checkStopPos(), OutputDevice::closeTag(), SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::Stop::endPos, RONet::getBusStop(), RONet::getContainerStop(), RONet::getEdge(), ROEdge::getLength(), SUMOSAXAttributes::getOpt(), SUMOVehicleParameter::id, MsgHandler::inform(), SUMOVehicleParameter::Stop::lane, myActiveContainerPlan, myActiveContainerPlanSize, myActivePerson, myActiveRoute, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteStops, myErrorOutput, SUMORouteHandler::myInsertStopEdgesAt, myNet, SUMORouteHandler::myVehicleParameter, OutputDevice::openTag(), SUMORouteHandler::parseStop(), POSITION_EPS, SUMOVehicleParameter::Stop::startPos, SUMOVehicleParameter::stops, SUMO_ATTR_ENDPOS, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_LANE, SUMO_ATTR_STARTPOS, SUMO_TAG_STOP, and SUMOReal.
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 192 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 175 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
bool SUMORouteHandler::checkLastDepart () protected inherited
Checks whether the route file is sorted by departure time if needed.
Definition at line 78 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, SUMOVehicleParameter::id, SUMORouteHandler::myLastDepart, SUMORouteHandler::myVehicleParameter, and WRITE_WARNING.
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeVehicle(), and SUMORouteHandler::getFirstDepart().
bool SUMORouteHandler::checkStopPos (SUMOReal & startPos, SUMOReal & endPos, const SUMOReal laneLength, const SUMOReal minLength, const bool friendlyPos) static inherited
check start and end position of a stop
Definition at line 211 of file SUMORouteHandler.cpp.
Referenced by NLTriggerBuilder::addAccess(), MSRouteHandler::addStop(), addStop(), NLTriggerBuilder::parseAndBuildChargingStation(), NLTriggerBuilder::parseAndBuildStoppingPlace(), and RONetHandler::parseStoppingPlace().
void RORouteHandler::closeContainer () protected virtual
Ends the processing of a container.
Implements SUMORouteHandler.
Definition at line 522 of file RORouteHandler.cpp.
References RONet::addContainer(), OutputDevice::closeTag(), SUMOVehicleParameter::depart, OutputDevice_String::getString(), SUMOVehicleParameter::id, myActiveContainerPlan, myActiveContainerPlanSize, myNet, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), and WRITE_WARNING.
void RORouteHandler::closeFlow () protected virtual
Ends the processing of a flow.
Implements SUMORouteHandler.
Definition at line 539 of file RORouteHandler.cpp.
References RONet::addFlow(), closeRoute(), SUMOVehicleParameter::depart, OptionsCont::getBool(), MsgHandler::getErrorInstance(), OptionsCont::getOptions(), RONet::getRouteDef(), RONet::getVehicleTypeSecure(), SUMOVehicleParameter::id, MsgHandler::inform(), SUMORouteHandler::myActiveRouteID, myErrorOutput, SUMORouteHandler::myInsertStopEdgesAt, myNet, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), SUMOVehicleParameter::repetitionNumber, SUMOVehicleParameter::repetitionOffset, SUMOVehicleParameter::repetitionsDone, SUMOVehicleParameter::routeid, string2time(), and SUMOVehicleParameter::vtypeid.
void RORouteHandler::closePerson () protected virtual
Ends the processing of a person.
Implements SUMORouteHandler.
Definition at line 508 of file RORouteHandler.cpp.
References RONet::addPerson(), ROPerson::getPlan(), SUMOVehicleParameter::id, myActivePerson, myNet, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), and WRITE_WARNING.
void RORouteHandler::closeRoute (const bool mayBeDisconnected = false) protected virtual
closes (ends) the building of a route. Afterwards no edges may be added to it; this method may throw exceptions when a) the route is empty or b) another route with the same id already exists
Implements SUMORouteHandler.
Definition at line 365 of file RORouteHandler.cpp.
References RORouteDef::addAlternativeDef(), RORouteDef::addLoadedAlternative(), RONet::addRouteDef(), ROEdge::ET_DISTRICT, RONet::getRouteDef(), SUMOVehicleParameter::id, MsgHandler::inform(), myActiveRoute, SUMORouteHandler::myActiveRouteColor, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteProbability, SUMORouteHandler::myActiveRouteRefID, SUMORouteHandler::myActiveRouteStops, myCurrentAlternatives, SUMORouteHandler::myCurrentCosts, myErrorOutput, myNet, myTryRepair, and SUMORouteHandler::myVehicleParameter.
Referenced by closeFlow(), and myEndElement().
void RORouteHandler::closeRouteDistribution () protected virtual
closes (ends) the building of a distribution
Implements SUMORouteHandler.
Definition at line 459 of file RORouteHandler.cpp.
References RONet::addRouteDef(), Named::getID(), RORouteDef::getOverallProb(), MsgHandler::inform(), myCurrentAlternatives, myErrorOutput, and myNet.
void RORouteHandler::closeVehicle () protected virtual
Ends the processing of a vehicle.
Implements SUMORouteHandler.
Definition at line 474 of file RORouteHandler.cpp.
References RONet::addVehicle(), RORouteDef::copy(), DEFAULT_VTYPE_ID, SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, MsgHandler::getErrorInstance(), Named::getID(), OptionsCont::getOptions(), RONet::getRouteDef(), RONet::getVehicleTypeSecure(), SUMOVTypeParameter::id, SUMOVehicleParameter::id, MsgHandler::inform(), myErrorOutput, myNet, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), SUMOVehicleParameter::routeid, string2time(), and SUMOVehicleParameter::vtypeid.
Referenced by myEndElement().
void RORouteHandler::closeVehicleTypeDistribution () protected virtual
closes (ends) the building of a distribution
Implements SUMORouteHandler.
Definition at line 274 of file RORouteHandler.cpp.
References RONet::addVTypeDistribution(), RandomDistributor< T >::getOverallProb(), MsgHandler::inform(), myCurrentVTypeDistribution, myCurrentVTypeDistributionID, myErrorOutput, and myNet.
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 211 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), MSRouteHandler::myStartElement(), and MSRouteHandler::parseWalkPos().
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 217 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), MSStateHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
SUMOTime SUMORouteHandler::getFirstDepart () const inline inherited
returns the first departure time that was ever read
Definition at line 74 of file SUMORouteHandler.h.
References SUMORouteHandler::addParam(), SUMORouteHandler::addStop(), SUMORouteHandler::checkLastDepart(), SUMORouteHandler::closeContainer(), SUMORouteHandler::closeFlow(), SUMORouteHandler::closePerson(), SUMORouteHandler::closeRoute(), SUMORouteHandler::closeRouteDistribution(), SUMORouteHandler::closeVehicle(), SUMORouteHandler::closeVehicleTypeDistribution(), SUMORouteHandler::myEndElement(), SUMORouteHandler::myFirstDepart, SUMORouteHandler::myStartElement(), SUMORouteHandler::openRoute(), SUMORouteHandler::openRouteDistribution(), SUMORouteHandler::openVehicleTypeDistribution(), SUMORouteHandler::parseStop(), and SUMORouteHandler::registerLastDepart().
Referenced by SUMORouteLoader::getFirstDepart().
SUMOTime SUMORouteHandler::getLastDepart () const inherited
Returns the last loaded depart time.
Definition at line 72 of file SUMORouteHandler.cpp.
References SUMORouteHandler::myLastDepart.
Referenced by SUMORouteLoader::loadUntil().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 227 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void RORouteHandler::myEndElement (int element) protected virtual
Called when a closing tag occurs.
Parameters
[in] element ID of the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myEndElement
Reimplemented from SUMORouteHandler.
Definition at line 340 of file RORouteHandler.cpp.
References RandomDistributor< T >::add(), RONet::addVehicleType(), closeRoute(), closeVehicle(), SUMOVTypeParameter::defaultProbability, SUMORouteHandler::myCurrentVType, myCurrentVTypeDistribution, SUMORouteHandler::myEndElement(), SUMORouteHandler::myInsertStopEdgesAt, myNet, SUMORouteHandler::myVehicleParameter, SUMO_TAG_TRIP, and SUMO_TAG_VTYPE.
void RORouteHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from SUMORouteHandler.
Definition at line 141 of file RORouteHandler.cpp.
References addPersonTrip(), ROPerson::addRide(), ROPerson::addWalk(), OutputDevice::closeTag(), DEFAULT_PEDTYPE_ID, DEFAULT_VEH_PROB, SUMOSAXAttributes::get(), RONet::getEdge(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), ROPerson::getPlan(), RONet::getVehicleTypeSecure(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, MsgHandler::inform(), myActiveContainerPlan, myActiveContainerPlanSize, myActivePerson, myActiveRoute, SUMORouteHandler::myActiveRouteProbability, SUMORouteHandler::myCurrentVType, myErrorOutput, myNet, SUMORouteHandler::myStartElement(), SUMORouteHandler::myVehicleParameter, OutputDevice::openTag(), parseEdges(), parseFromViaTo(), SUMOVehicleParserHelper::parseVTypeEmbedded(), SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_BUS_STOP, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DURATION, SUMO_ATTR_EDGES, SUMO_ATTR_FROM, SUMO_ATTR_LINES, SUMO_ATTR_SPEED, SUMO_ATTR_TO, SUMO_TAG_CONTAINER, SUMO_TAG_FLOW, SUMO_TAG_PARAM, SUMO_TAG_PERSON, SUMO_TAG_PERSONTRIP, SUMO_TAG_RIDE, SUMO_TAG_TRANSHIP, SUMO_TAG_TRANSPORT, SUMO_TAG_TRIP, SUMO_TAG_VTYPE, SUMO_TAG_WALK, SUMOReal, and SUMOVehicleParameter::vtypeid.
void RORouteHandler::openRoute (const SUMOSAXAttributes & attrs) protected virtual
opens a route for reading
Implements SUMORouteHandler.
Definition at line 289 of file RORouteHandler.cpp.
References DEFAULT_VEH_PROB, SUMOSAXAttributes::get(), Named::getID(), SUMOSAXAttributes::getOpt(), RONet::getRouteDef(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, MsgHandler::inform(), myActiveRoute, SUMORouteHandler::myActiveRouteColor, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteProbability, SUMORouteHandler::myActiveRouteRefID, myCurrentAlternatives, SUMORouteHandler::myCurrentCosts, myErrorOutput, SUMORouteHandler::myInsertStopEdgesAt, myNet, SUMORouteHandler::myVehicleParameter, parseEdges(), SUMOVehicleParameter::routeid, SUMO_ATTR_COLOR, SUMO_ATTR_COST, SUMO_ATTR_EDGES, SUMO_ATTR_ID, SUMO_ATTR_PROB, SUMO_ATTR_REFID, SUMOReal, and WRITE_WARNING.
void RORouteHandler::openRouteDistribution (const SUMOSAXAttributes & attrs) protected virtual
opens a route distribution for reading
Implements SUMORouteHandler.
Definition at line 417 of file RORouteHandler.cpp.
References RORouteDef::addAlternativeDef(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), RONet::getRouteDef(), SUMOSAXAttributes::hasAttribute(), StringTokenizer::hasNext(), SUMOVehicleParameter::id, MsgHandler::inform(), myCurrentAlternatives, myErrorOutput, myNet, myTryRepair, SUMORouteHandler::myVehicleParameter, StringTokenizer::next(), SUMOVehicleParameter::routeid, SUMO_ATTR_ID, SUMO_ATTR_LAST, SUMO_ATTR_ROUTES, and WRITE_WARNING.
void RORouteHandler::openVehicleTypeDistribution (const SUMOSAXAttributes & attrs) protected virtual
opens a type distribution for reading
Implements SUMORouteHandler.
Definition at line 256 of file RORouteHandler.cpp.
References RandomDistributor< T >::add(), SUMOSAXAttributes::get(), RONet::getVehicleTypeSecure(), SUMOSAXAttributes::hasAttribute(), myCurrentVTypeDistribution, myCurrentVTypeDistributionID, myNet, SUMO_ATTR_ID, and SUMO_ATTR_VTYPES.
RORouteHandler& RORouteHandler::operator= (const RORouteHandler & s) private
Invalidated assignment operator.
void RORouteHandler::parseEdges (const std::string & desc, ConstROEdgeVector & into, const std::string & rid) protected
Parse edges from strings.
Definition at line 661 of file RORouteHandler.cpp.
References BinaryFormatter::BF_ROUTE, RONet::getEdge(), StringTokenizer::hasNext(), MsgHandler::inform(), myErrorOutput, myNet, and FileHelpers::readEdgeVector().
Referenced by myStartElement(), openRoute(), and parseFromViaTo().
void RORouteHandler::parseFromViaTo (std::string element, const SUMOSAXAttributes & attrs) protected
Called for parsing from and to and the corresponding taz attributes.
Parameters
[in] element description of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
Definition at line 87 of file RORouteHandler.cpp.
References SUMOVehicleParameter::fromTaz, OptionsCont::getBool(), RONet::getEdge(), ROEdge::getNumPredecessors(), ROEdge::getNumSuccessors(), SUMOSAXAttributes::getOpt(), OptionsCont::getOptions(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, MsgHandler::inform(), myActiveRoute, SUMORouteHandler::myActiveRouteID, myErrorOutput, SUMORouteHandler::myInsertStopEdgesAt, myNet, SUMORouteHandler::myVehicleParameter, parseEdges(), SUMOVehicleParameter::routeid, SUMO_ATTR_FROM, SUMO_ATTR_TO, SUMO_ATTR_VIA, SUMOVehicleParameter::toTaz, VEHPARS_FROM_TAZ_SET, VEHPARS_TO_TAZ_SET, SUMOVehicleParameter::via, SUMOVehicleParameter::wasSet(), and WRITE_WARNING.
Referenced by myStartElement().
bool SUMORouteHandler::parseStop (SUMOVehicleParameter::Stop & stop, const SUMOSAXAttributes & attrs, std::string errorSuffix, MsgHandler *const errorOutput) protected inherited
parses attributes common to all stops
Definition at line 263 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::Stop::awaitedContainers, SUMOVehicleParameter::Stop::awaitedPersons, SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::Stop::index, MsgHandler::inform(), SUMOVehicleParameter::Stop::lane, SUMOVehicleParameter::Stop::parking, SUMOSAXAttributes::parseStringSet(), SUMOVehicleParameter::Stop::setParameter, STOP_CONTAINER_TRIGGER_SET, STOP_END_SET, STOP_EXPECTED_CONTAINERS_SET, STOP_EXPECTED_SET, STOP_INDEX_END, STOP_INDEX_FIT, STOP_PARKING_SET, STOP_START_SET, STOP_TRIGGER_SET, SUMO_ATTR_BUS_STOP, SUMO_ATTR_CHARGING_STATION, SUMO_ATTR_CONTAINER_STOP, SUMO_ATTR_CONTAINER_TRIGGERED, SUMO_ATTR_DURATION, SUMO_ATTR_ENDPOS, SUMO_ATTR_EXPECTED, SUMO_ATTR_EXPECTED_CONTAINERS, SUMO_ATTR_INDEX, SUMO_ATTR_PARKING, SUMO_ATTR_STARTPOS, SUMO_ATTR_TRIGGERED, SUMO_ATTR_UNTIL, SUMOVehicleParameter::Stop::triggered, and SUMOVehicleParameter::Stop::until.
Referenced by MSRouteHandler::addStop(), addStop(), and SUMORouteHandler::getFirstDepart().
void SUMORouteHandler::registerLastDepart () protected inherited
save last depart (only to be used if vehicle is not discarded)
Definition at line 90 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, SUMOVehicleParameter::line, SUMORouteHandler::myFirstDepart, SUMORouteHandler::myLastDepart, and SUMORouteHandler::myVehicleParameter.
Referenced by MSRouteHandler::closeContainer(), closeContainer(), MSRouteHandler::closeFlow(), closeFlow(), MSRouteHandler::closePerson(), closePerson(), MSRouteHandler::closeVehicle(), closeVehicle(), and SUMORouteHandler::getFirstDepart().
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 167 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 205 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
OutputDevice_String* RORouteHandler::myActiveContainerPlan protected
The plan of the current container.
Definition at line 167 of file RORouteHandler.h.
Referenced by addStop(), closeContainer(), and myStartElement().
int RORouteHandler::myActiveContainerPlanSize protected
The number of stages in myActiveContainerPlan.
Definition at line 170 of file RORouteHandler.h.
Referenced by addStop(), closeContainer(), and myStartElement().
ROPerson* RORouteHandler::myActivePerson protected
The plan of the current person.
Definition at line 164 of file RORouteHandler.h.
Referenced by addPersonTrip(), addStop(), closePerson(), and myStartElement().
ConstROEdgeVector RORouteHandler::myActiveRoute protected
The current route.
Definition at line 161 of file RORouteHandler.h.
Referenced by addStop(), closeRoute(), myStartElement(), openRoute(), parseFromViaTo(), and RORouteHandler().
const RGBColor* SUMORouteHandler::myActiveRouteColor protected inherited
The currently parsed route's color.
Definition at line 169 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), closeRoute(), MSRouteHandler::openRoute(), and openRoute().
std::string SUMORouteHandler::myActiveRouteID protected inherited
The id of the current route.
Definition at line 160 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), addStop(), MSRouteHandler::closeFlow(), closeFlow(), MSRouteHandler::closeRoute(), closeRoute(), MSRouteHandler::closeVehicle(), MSRouteHandler::myStartElement(), SUMORouteHandler::myStartElement(), MSRouteHandler::openRoute(), openRoute(), MSRouteHandler::parseFromViaTo(), and parseFromViaTo().
SUMOReal SUMORouteHandler::myActiveRouteProbability protected inherited
The probability of the current route.
Definition at line 166 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), closeRoute(), myStartElement(), MSRouteHandler::openRoute(), and openRoute().
std::string SUMORouteHandler::myActiveRouteRefID protected inherited
The id of the route the current route references to.
Definition at line 163 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), closeRoute(), MSRouteHandler::openRoute(), and openRoute().
std::vector<SUMOVehicleParameter::Stop> SUMORouteHandler::myActiveRouteStops protected inherited
List of the stops on the parsed route.
Definition at line 175 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), addStop(), MSRouteHandler::closeRoute(), and closeRoute().
SUMOTime SUMORouteHandler::myBeginDefault protected inherited
The default value for flow begins.
Definition at line 184 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myEndElement(), and SUMORouteHandler::myStartElement().
RORouteDef* RORouteHandler::myCurrentAlternatives protected
The currently parsed route alternatives.
Definition at line 188 of file RORouteHandler.h.
Referenced by closeRoute(), closeRouteDistribution(), openRoute(), and openRouteDistribution().
SUMOReal SUMORouteHandler::myCurrentCosts protected inherited
The currently parsed route costs.
Definition at line 172 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), closeRoute(), MSRouteHandler::openRoute(), and openRoute().
SUMOVTypeParameter* SUMORouteHandler::myCurrentVType protected inherited
The currently parsed vehicle type.
Definition at line 178 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::addParam(), MSRouteHandler::myEndElement(), myEndElement(), SUMORouteHandler::myEndElement(), MSRouteHandler::myStartElement(), myStartElement(), SUMORouteHandler::myStartElement(), and SUMORouteHandler::~SUMORouteHandler().
RandomDistributor<SUMOVTypeParameter*>* RORouteHandler::myCurrentVTypeDistribution protected
The currently parsed distribution of vehicle types (probability->vehicle type)
Definition at line 182 of file RORouteHandler.h.
Referenced by closeVehicleTypeDistribution(), myEndElement(), and openVehicleTypeDistribution().
std::string RORouteHandler::myCurrentVTypeDistributionID protected
The id of the currently parsed vehicle type distribution.
Definition at line 185 of file RORouteHandler.h.
Referenced by closeVehicleTypeDistribution(), and openVehicleTypeDistribution().
const bool RORouteHandler::myEmptyDestinationsAllowed protected
Information whether the "to" attribute is mandatory.
Definition at line 176 of file RORouteHandler.h.
SUMOTime SUMORouteHandler::myEndDefault protected inherited
The default value for flow ends.
Definition at line 187 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myEndElement(), and SUMORouteHandler::myStartElement().
MsgHandler* const RORouteHandler::myErrorOutput protected
Depending on the "ignore-errors" option different outputs are used.
Definition at line 179 of file RORouteHandler.h.
Referenced by addPersonTrip(), addStop(), closeFlow(), closeRoute(), closeRouteDistribution(), closeVehicle(), closeVehicleTypeDistribution(), myStartElement(), openRoute(), openRouteDistribution(), parseEdges(), and parseFromViaTo().
SUMOTime SUMORouteHandler::myFirstDepart protected inherited
the first read departure time
Definition at line 190 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::getFirstDepart(), and SUMORouteHandler::registerLastDepart().
IDSupplier SUMORouteHandler::myIdSupplier protected inherited
generates numerical ids
Definition at line 181 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myStartElement().
int SUMORouteHandler::myInsertStopEdgesAt protected inherited
where stop edges can be inserted into the current route (-1 means no insertion)
Definition at line 193 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), addStop(), MSRouteHandler::closeFlow(), closeFlow(), MSRouteHandler::myEndElement(), myEndElement(), MSRouteHandler::openRoute(), openRoute(), MSRouteHandler::parseFromViaTo(), and parseFromViaTo().
SUMOTime SUMORouteHandler::myLastDepart protected inherited
The insertion time of the vehicle read last.
Definition at line 157 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::checkLastDepart(), SUMORouteHandler::getLastDepart(), and SUMORouteHandler::registerLastDepart().
RONet& RORouteHandler::myNet protected
The current route.
Definition at line 158 of file RORouteHandler.h.
Referenced by addPersonTrip(), addStop(), closeContainer(), closeFlow(), closePerson(), closeRoute(), closeRouteDistribution(), closeVehicle(), closeVehicleTypeDistribution(), myEndElement(), myStartElement(), openRoute(), openRouteDistribution(), openVehicleTypeDistribution(), parseEdges(), and parseFromViaTo().
const bool RORouteHandler::myTryRepair protected
Information whether routes shall be repaired.
Definition at line 173 of file RORouteHandler.h.
Referenced by closeRoute(), and openRouteDistribution().
SUMOVehicleParameter* SUMORouteHandler::myVehicleParameter protected inherited
Parameter of the current vehicle, trip, person, container or flow.
Definition at line 154 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::addParam(), addPersonTrip(), MSRouteHandler::addStop(), addStop(), SUMORouteHandler::checkLastDepart(), MSRouteHandler::closeContainer(), closeContainer(), MSRouteHandler::closeFlow(), closeFlow(), MSRouteHandler::closePerson(), closePerson(), MSRouteHandler::closeRoute(), closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::closeVehicle(), closeVehicle(), MSRouteHandler::myEndElement(), myEndElement(), SUMORouteHandler::myEndElement(), MSRouteHandler::myStartElement(), myStartElement(), SUMORouteHandler::myStartElement(), MSRouteHandler::openRoute(), openRoute(), MSRouteHandler::openRouteDistribution(), openRouteDistribution(), MSRouteHandler::parseFromViaTo(), parseFromViaTo(), and SUMORouteHandler::registerLastDepart().
The documentation for this class was generated from the following files:
RORouteHandler.h
RORouteHandler.cpp