SUMO - Simulation of Urban MObility: gl2psTest.c File Reference
gl2psTest.c File Reference
#include "gl2ps.h"
#include <string.h>
#include <GL/glut.h>
Functions
void cube ()
void display ()
void draw_multi ()
void draw_single ()
void extras ()
void image (float x, float y, GLboolean opaque)
void keyboard (unsigned char key, int x, int y)
int main (int argc, char **argv)
void motion (int x, int y)
void objects ()
void printstring (const char *string, float angle)
void reshape (int w, int h)
void text ()
void triangles ()
void writefile (int format, int sort, int options, int nbcol, const char *filename, const char *extension)
Variables
static GLboolean blend = GL_FALSE
static GLboolean display_multi = GL_TRUE
static const char * format_string = "Postscript"
static const char * pixmap []
static float rotation = -58.
static GLboolean teapot = GL_FALSE
static GLsizei window_h = 0
static GLsizei window_w = 0
Function Documentation
void cube ()
Definition at line 299 of file gl2psTest.c.
Referenced by draw_multi().
void display (void)
Definition at line 461 of file gl2psTest.c.
References blend, display_multi, draw_multi(), and draw_single().
Referenced by keyboard(), main(), motion(), and writefile().
void draw_multi ()
Definition at line 401 of file gl2psTest.c.
References cube(), extras(), gl2psBeginViewport(), gl2psEndViewport(), image(), objects(), rotation, text(), triangles(), window_h, and window_w.
Referenced by display().
void draw_single ()
Definition at line 389 of file gl2psTest.c.
References extras(), objects(), text(), triangles(), window_h, and window_w.
Referenced by display().
void extras ()
Definition at line 158 of file gl2psTest.c.
References GL2PS_LINE_STIPPLE, gl2psDisable(), gl2psEnable(), gl2psLineWidth(), and gl2psPointSize().
Referenced by draw_multi(), and draw_single().
void image (float x, float y, GLboolean opaque)
Definition at line 335 of file gl2psTest.c.
References gl2psDrawPixels(), and pixmap.
Referenced by draw_multi(), and gl2psCopyPixmap().
void keyboard (unsigned char key, int x, int y)
Definition at line 545 of file gl2psTest.c.
References blend, display(), display_multi, format_string, GL2PS_BEST_ROOT, GL2PS_BSP_SORT, GL2PS_COMPRESS, GL2PS_DRAW_BACKGROUND, GL2PS_EPS, GL2PS_EXTRA_VERSION, GL2PS_MAJOR_VERSION, GL2PS_MINOR_VERSION, GL2PS_NO_PS3_SHADING, GL2PS_NO_TEXT, GL2PS_OCCLUSION_CULL, GL2PS_PATCH_VERSION, GL2PS_PDF, GL2PS_PGF, GL2PS_PS, GL2PS_SIMPLE_SORT, GL2PS_SVG, GL2PS_TEX, GL2PS_TIGHT_BOUNDING_BOX, gl2psGetFileExtension(), gl2psGetFormatDescription(), reshape(), teapot, window_h, window_w, and writefile().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 621 of file gl2psTest.c.
References display(), keyboard(), motion(), and reshape().
void motion (int x, int y)
Definition at line 615 of file gl2psTest.c.
References display(), and rotation.
Referenced by main().
void objects ()
Definition at line 227 of file gl2psTest.c.
References rotation, and teapot.
Referenced by draw_multi(), and draw_single().
void printstring (const char * string, float angle)
Definition at line 243 of file gl2psTest.c.
References GL2PS_TEXT_BL, and gl2psTextOpt().
Referenced by text().
void reshape (int w, int h)
Definition at line 488 of file gl2psTest.c.
References window_h, and window_w.
Referenced by keyboard(), and main().
void text ()
Definition at line 260 of file gl2psTest.c.
References format_string, GL2PS_TEX, gl2psSpecial(), and printstring().
Referenced by GUIMessageWindow::appendMsg(), GUIUserIO::copyToClipboard(), GUISUMOAbstractView::displayLegend(), draw_multi(), draw_single(), MFXEditableTable::editEnd(), FXLinkLabel::fxexecute(), FXLinkLabel::FXLinkLabel(), FX::FXRealSpinDial::getCoarseIncrement(), GUIDialog_ViewSettings::getCurrentScheme(), MFXUtils::getFilename2Write(), GNEAdditionalFrame::getIdsSelected(), GNETLSEditorFrame::getSUMOTime(), gl2psCopyText(), GUIApplicationWindow::handleEvent_SimulationEnded(), GUILane::isClosed(), GUIDialog_ViewSettings::onCmdSaveSetting(), GUIMessageWindow::setCursorPos(), GNETLSEditorFrame::updateCycleDuration(), and GUISUMOAbstractView::updatePositionInformation().
void triangles ()
Definition at line 136 of file gl2psTest.c.
Referenced by NBHeightMapper::QueryResult::add(), draw_multi(), draw_single(), and gl2psPDFgroupListWriteObjects().
void writefile (int format, int sort, int options, int nbcol, const char * filename, const char * extension)
Definition at line 503 of file gl2psTest.c.
References display(), GL2PS_OVERFLOW, gl2psBeginPage(), gl2psEndPage(), window_h, and window_w.
Referenced by keyboard().
Variable Documentation
GLboolean blend = GL_FALSE static
Definition at line 66 of file gl2psTest.c.
Referenced by display(), and keyboard().
GLboolean display_multi = GL_TRUE static
Definition at line 65 of file gl2psTest.c.
Referenced by display(), and keyboard().
const char* format_string = "Postscript" static
Definition at line 61 of file gl2psTest.c.
Referenced by keyboard(), and text().
const char* pixmap[] static
Definition at line 68 of file gl2psTest.c.
Referenced by gl2psFreePixmap(), and image().
float rotation = -58. static
Definition at line 62 of file gl2psTest.c.
Referenced by draw_multi(), motion(), and objects().
GLboolean teapot = GL_FALSE static
Definition at line 67 of file gl2psTest.c.
Referenced by keyboard(), and objects().
GLsizei window_h = 0 static
Definition at line 64 of file gl2psTest.c.
Referenced by draw_multi(), draw_single(), keyboard(), reshape(), and writefile().
GLsizei window_w = 0 static
Definition at line 63 of file gl2psTest.c.
Referenced by draw_multi(), draw_single(), keyboard(), reshape(), and writefile().