SUMO - Simulation of Urban MObility: PedestrianRouterDijkstra< E, L, N, V > Class Template Reference
PedestrianRouterDijkstra< E, L, N, V > Class Template Reference
#include <PedestrianRouter.h>
Public Types
typedef IntermodalEdge< E, L, N, V > _IntermodalEdge
typedef IntermodalNetwork< E, L, N, V > _IntermodalNetwork
typedef IntermodalTrip< E, N, V > _IntermodalTrip
typedef SUMOReal(* Operation) (const E *const, const IntermodalTrip< E, N, V > *const, SUMOReal)
Type of the function that is used to retrieve the edge effort.
Public Member Functions
virtual SUMOAbstractRouter< E, _IntermodalTrip > * clone ()
bool compute (const E *from, const E *to, SUMOReal departPos, SUMOReal arrivalPos, SUMOReal speed, SUMOTime msTime, const N *onlyNode, std::vector< const E * > &into, bool allEdges=false)
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
bool compute (const E *, const E *, const _IntermodalTrip *const, SUMOTime, std::vector< const E * > &)
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
void endQuery (int visits)
SUMOReal getEffort (const E *const e, const IntermodalTrip< E, N, V > *const v, SUMOReal t) const
void prohibit (const std::vector< E * > &toProhibit)
SUMOReal recomputeCosts (const std::vector< const E * > &, const _IntermodalTrip *const, SUMOTime) const
void setBulkMode (const bool mode)
void startQuery ()
Protected Attributes
bool myBulkMode
whether we are currently operating several route queries in a bulk
Operation myOperation
The object's operation to perform.
Detailed Description
template<class E, class L, class N, class V>
class PedestrianRouterDijkstra< E, L, N, V >
Definition at line 164 of file PedestrianRouter.h.
Member Typedef Documentation
typedef IntermodalEdge<E, L, N, V> PedestrianRouter< E, L, N, V, DijkstraRouterTT< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::_IntermodalEdge inherited
Definition at line 58 of file PedestrianRouter.h.
typedef IntermodalNetwork<E, L, N, V> PedestrianRouter< E, L, N, V, DijkstraRouterTT< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::_IntermodalNetwork inherited
Definition at line 59 of file PedestrianRouter.h.
typedef IntermodalTrip<E, N, V> PedestrianRouter< E, L, N, V, DijkstraRouterTT< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::_IntermodalTrip inherited
Definition at line 60 of file PedestrianRouter.h.
typedef SUMOReal(* SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::Operation) (const E *const, const IntermodalTrip< E, N, V > *const, SUMOReal) inherited
Type of the function that is used to retrieve the edge effort.
Definition at line 56 of file SUMOAbstractRouter.h.
Member Function Documentation
virtual SUMOAbstractRouter<E, _IntermodalTrip>* PedestrianRouter< E, L, N, V, DijkstraRouterTT< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::clone () inline virtual inherited
Implements SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >.
Definition at line 83 of file PedestrianRouter.h.
References PedestrianRouter< E, L, N, V, INTERNALROUTER >::myPedNet.
bool PedestrianRouter< E, L, N, V, DijkstraRouterTT< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::compute (const E * from, const E * to, SUMOReal departPos, SUMOReal arrivalPos, SUMOReal speed, SUMOTime msTime, const N * onlyNode, std::vector< const E * > & into, bool allEdges = false) inline inherited
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Definition at line 89 of file PedestrianRouter.h.
References IntermodalNetwork< E, L, N, V >::getArrivalEdge(), IntermodalNetwork< E, L, N, V >::getDepartEdge(), PedestrianRouter< E, L, N, V, INTERNALROUTER >::myInternalRouter, PedestrianRouter< E, L, N, V, INTERNALROUTER >::myPedNet, SUMOReal, TIME2STEPS, toString(), and WRITE_WARNING.
bool PedestrianRouter< E, L, N, V, DijkstraRouterTT< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::compute (const E * , const E * , const _IntermodalTrip * const, SUMOTime , std::vector< const E * > &) inline virtual inherited
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Implements SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >.
Definition at line 132 of file PedestrianRouter.h.
void SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::endQuery (int visits) inline inherited
Definition at line 96 of file SUMOAbstractRouter.h.
References SysUtils::getCurrentMillis(), SUMOAbstractRouter< E, V >::myQueryStartTime, SUMOAbstractRouter< E, V >::myQueryTimeSum, and SUMOAbstractRouter< E, V >::myQueryVisits.
SUMOReal SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::getEffort (const E *const e, const IntermodalTrip< E, N, V > *const v, SUMOReal t) const inline inherited
Definition at line 87 of file SUMOAbstractRouter.h.
References SUMOAbstractRouter< E, V >::myOperation.
void PedestrianRouter< E, L, N, V, DijkstraRouterTT< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::prohibit (const std::vector< E * > & toProhibit) inline inherited
Definition at line 141 of file PedestrianRouter.h.
References IntermodalNetwork< E, L, N, V >::getBothDirections(), PedestrianRouter< E, L, N, V, INTERNALROUTER >::myInternalRouter, and PedestrianRouter< E, L, N, V, INTERNALROUTER >::myPedNet.
SUMOReal PedestrianRouter< E, L, N, V, DijkstraRouterTT< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >::recomputeCosts (const std::vector< const E * > & , const _IntermodalTrip * const, SUMOTime) const inline virtual inherited
Implements SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >.
Definition at line 137 of file PedestrianRouter.h.
void SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::setBulkMode (const bool mode) inline inherited
Definition at line 101 of file SUMOAbstractRouter.h.
References SUMOAbstractRouter< E, V >::myBulkMode.
void SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::startQuery () inline inherited
Definition at line 91 of file SUMOAbstractRouter.h.
References SysUtils::getCurrentMillis(), SUMOAbstractRouter< E, V >::myNumQueries, and SUMOAbstractRouter< E, V >::myQueryStartTime.
Field Documentation
bool SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::myBulkMode protected inherited
whether we are currently operating several route queries in a bulk
Definition at line 110 of file SUMOAbstractRouter.h.
Operation SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::myOperation protected inherited
The object's operation to perform.
Definition at line 107 of file SUMOAbstractRouter.h.
The documentation for this class was generated from the following file:
PedestrianRouter.h