SUMO - Simulation of Urban MObility: NBEdge::MainDirections Class Reference
NBEdge::MainDirections Class Reference
Public Types
enum Direction { DIR_RIGHTMOST, DIR_LEFTMOST, DIR_FORWARD }
enum of possible directions
Public Member Functions
bool empty () const
bool includes (Direction d) const
MainDirections (const EdgeVector &outgoing, NBEdge *parent, NBNode *to, int indexOfStraightest)
constructor
~MainDirections ()
destructor
Data Fields
std::vector< Direction > myDirs
Private Member Functions
MainDirections (const MainDirections &)
Invalidated copy constructor.
MainDirections & operator= (const MainDirections &)
Invalidated assignment operator.
Detailed Description
MainDirections Holds (- relative to the edge it is build from -!!!) the list of main directions a vehicle that drives on this street may take on the junction the edge ends in The back direction is not regarded
Definition at line 1170 of file NBEdge.h.
Member Enumeration Documentation
enum NBEdge::MainDirections::Direction
enum of possible directions
Enumerator
DIR_RIGHTMOST
DIR_LEFTMOST
DIR_FORWARD
Definition at line 1173 of file NBEdge.h.
Constructor & Destructor Documentation
NBEdge::MainDirections::MainDirections (const EdgeVector & outgoing, NBEdge * parent, NBNode * to, int indexOfStraightest)
constructor
Definition at line 119 of file NBEdge.cpp.
References DEBUGCOND, DIR_FORWARD, DIR_LEFTMOST, DIR_RIGHTMOST, NBNode::getDirection(), Named::getID(), NBEdge::getJunctionPriority(), NBNode::getType(), NBNode::isTrafficLight(), LINKDIR_PARTLEFT, LINKDIR_PARTRIGHT, LINKDIR_STRAIGHT, and toString().
NBEdge::MainDirections::~MainDirections ()
destructor
Definition at line 167 of file NBEdge.cpp.
NBEdge::MainDirections::MainDirections (const MainDirections &) private
Invalidated copy constructor.
Member Function Documentation
bool NBEdge::MainDirections::empty () const
returns the information whether no following street has a higher priority
Definition at line 171 of file NBEdge.cpp.
Referenced by NBEdge::prepareEdgePriorities().
bool NBEdge::MainDirections::includes (Direction d) const
returns the information whether the street in the given direction has a higher priority
Definition at line 177 of file NBEdge.cpp.
Referenced by NBEdge::prepareEdgePriorities().
MainDirections& NBEdge::MainDirections::operator= (const MainDirections &) private
Invalidated assignment operator.
Field Documentation
std::vector<Direction> NBEdge::MainDirections::myDirs
list of the main direction within the following junction relative to the edge
Definition at line 1177 of file NBEdge.h.
Referenced by NBEdge::prepareEdgePriorities().
The documentation for this class was generated from the following files:
NBEdge.h
NBEdge.cpp