SUMO - Simulation of Urban MObility: GUITransportableControl Class Reference
GUITransportableControl Class Reference
GUI-version of the transportable control for building gui persons and containers.
#include <GUITransportableControl.h>
Public Types
typedef std::map< std::string, MSTransportable * >::const_iterator constVehIt
Definition of the internal transportables map iterator.
typedef std::vector< MSTransportable * > TransportableVector
Definition of a list of transportables.
Public Member Functions
void abortWaiting ()
aborts the plan for any transportable that is still waiting for a ride
bool add (MSTransportable *transportable)
Adds a single transportable, returns false if an id clash occured.
void addWaiting (const MSEdge *edge, MSTransportable *person)
adds a transportable to the list of transportables waiting for a vehicle on the specified edge
bool boardAnyWaiting (MSEdge *edge, MSVehicle *vehicle, MSVehicle::Stop *stop)
board any applicable persons Boards any people who wait on that edge for the given vehicle and removes them from myWaiting
virtual MSTransportable * buildContainer (const SUMOVehicleParameter *pars, const MSVehicleType *vtype, MSTransportable::MSTransportablePlan *plan) const
Builds a new container.
virtual MSTransportable * buildPerson (const SUMOVehicleParameter *pars, const MSVehicleType *vtype, MSTransportable::MSTransportablePlan *plan) const
Builds a new person.
void checkWaiting (MSNet *net, const SUMOTime time)
checks whether any transportables waiting time is over
virtual void erase (MSTransportable *transportable)
removes a single transportable
MSTransportable * get (const std::string &id) const
Returns the named transportable, if existing.
GUITransportableControl ()
constructor
bool hasNonWaiting () const
checks whether any transportable is still engaged in walking / stopping
bool hasTransportables () const
checks whether any transportable waits to finish her plan
void insertPersonIDs (std::vector< GUIGlID > &into)
Returns the list of all known persons by gl-id.
bool loadAnyWaiting (MSEdge *edge, MSVehicle *vehicle, MSVehicle::Stop *stop)
load any applicable containers Loads any container that is waiting on that edge for the given vehicle and removes them from myWaiting
constVehIt loadedBegin () const
Returns the begin of the internal transportables map.
constVehIt loadedEnd () const
Returns the end of the internal transportables map.
void registerJammed ()
register a jammed transportable
void setWaitEnd (SUMOTime time, MSTransportable *transportable)
sets the arrival time for a waiting transportable
int size () const
Returns the number of known transportables.
virtual ~GUITransportableControl ()
destructor
Retrieval of transportable statistics (always accessable)
int getLoadedNumber () const
Returns the number of build transportables.
int getRunningNumber () const
Returns the number of build and inserted, but not yet deleted transportables.
int getJammedNumber () const
Returns the number of times a transportables was jammed.
Protected Attributes
bool myHaveNewWaiting
whether a new transportable waiting for a vehicle has been added in the last step
int myJammedNumber
The number of jammed transportables.
int myLoadedNumber
The number of build transportables.
int myRunningNumber
The number of transportables within the network (build and inserted but not removed)
std::map< std::string, MSTransportable * > myTransportables
all currently created transportables by id
std::map< SUMOTime, TransportableVector > myWaiting4Departure
Transportables waiting for departure.
std::map< const MSEdge *, TransportableVector > myWaiting4Vehicle
the lists of waiting transportables
int myWaitingForVehicleNumber
The number of transportables waiting for vehicles.
std::map< SUMOTime, TransportableVector > myWaitingUntil
the lists of walking / stopping transportables
Detailed Description
GUI-version of the transportable control for building gui persons and containers.
Definition at line 45 of file GUITransportableControl.h.
Member Typedef Documentation
typedef std::map<std::string, MSTransportable*>::const_iterator MSTransportableControl::constVehIt inherited
Definition of the internal transportables map iterator.
Definition at line 65 of file MSTransportableControl.h.
typedef std::vector<MSTransportable*> MSTransportableControl::TransportableVector inherited
Definition of a list of transportables.
Definition at line 62 of file MSTransportableControl.h.
Constructor & Destructor Documentation
GUITransportableControl::GUITransportableControl ()
constructor
Definition at line 48 of file GUITransportableControl.cpp.
GUITransportableControl::~GUITransportableControl () virtual
destructor
Definition at line 51 of file GUITransportableControl.cpp.
Member Function Documentation
void MSTransportableControl::abortWaiting () inherited
aborts the plan for any transportable that is still waiting for a ride
Definition at line 246 of file MSTransportableControl.cpp.
References MSTransportableControl::erase(), MSTransportable::getID(), MSTransportableControl::myWaiting4Vehicle, MSEdge::removeContainer(), MSEdge::removePerson(), and WRITE_WARNING.
Referenced by MSNet::simulationState().
bool MSTransportableControl::add (MSTransportable * transportable) inherited
Adds a single transportable, returns false if an id clash occured.
Parameters
[in] transportable The transportable to add
Returns
Whether the transportable could be added (none with the same id existed before)
Definition at line 72 of file MSTransportableControl.cpp.
References DELTA_T, SUMOVehicleParameter::depart, MSTransportable::getParameter(), SUMOVehicleParameter::id, MSTransportableControl::myLoadedNumber, MSTransportableControl::myTransportables, and MSTransportableControl::myWaiting4Departure.
void MSTransportableControl::addWaiting (const MSEdge * edge, MSTransportable * person) inherited
adds a transportable to the list of transportables waiting for a vehicle on the specified edge
Definition at line 148 of file MSTransportableControl.cpp.
References MSTransportableControl::myHaveNewWaiting, MSTransportableControl::myWaiting4Vehicle, and MSTransportableControl::myWaitingForVehicleNumber.
Referenced by MSContainer::MSContainerStage_Driving::proceed(), and MSPerson::MSPersonStage_Driving::proceed().
bool MSTransportableControl::boardAnyWaiting (MSEdge * edge, MSVehicle * vehicle, MSVehicle::Stop * stop) inherited
board any applicable persons Boards any people who wait on that edge for the given vehicle and removes them from myWaiting
Parameters
[in] the edge on which the boarding should take place
[in] the vehicle which is taking on passengers / goods
[in] the stop at which the vehicle is stopping
Returns
Whether any transportables have been boarded
Definition at line 156 of file MSTransportableControl.cpp.
References MSVehicle::addPerson(), DELTA_T, MSVehicle::Stop::duration, MSVehicle::Stop::endPos, MSVehicleType::getBoardingDuration(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSBaseVehicle::getParameter(), MSVehicleType::getPersonCapacity(), MSVehicle::getPersonNumber(), MSBaseVehicle::getVehicleType(), SUMOVehicleParameter::id, SUMOVehicleParameter::line, MSTransportableControl::myWaiting4Vehicle, MSTransportableControl::myWaitingForVehicleNumber, MSEdge::removePerson(), MSVehicle::Stop::startPos, and MSVehicle::Stop::timeToBoardNextPerson.
Referenced by MSVehicle::processNextStop().
MSTransportable * GUITransportableControl::buildContainer (const SUMOVehicleParameter * pars, const MSVehicleType * vtype, MSTransportable::MSTransportablePlan * plan) const virtual
Builds a new container.
Parameters
[in] pars The parameter
[in] vtype The type (reusing vehicle type container here)
[in] plan This container's plan
Reimplemented from MSTransportableControl.
Definition at line 62 of file GUITransportableControl.cpp.
MSTransportable * GUITransportableControl::buildPerson (const SUMOVehicleParameter * pars, const MSVehicleType * vtype, MSTransportable::MSTransportablePlan * plan) const virtual
Builds a new person.
Parameters
[in] pars The parameter
[in] vtype The type (reusing vehicle type container here)
[in] plan This person's plan
Reimplemented from MSTransportableControl.
Definition at line 56 of file GUITransportableControl.cpp.
void MSTransportableControl::checkWaiting (MSNet * net, const SUMOTime time) inherited
checks whether any transportables waiting time is over
Definition at line 120 of file MSTransportableControl.cpp.
References MSTransportableControl::erase(), MSTransportableControl::myHaveNewWaiting, MSTransportableControl::myRunningNumber, MSTransportableControl::myWaiting4Departure, and MSTransportableControl::myWaitingUntil.
Referenced by MSNet::simulationStep().
void MSTransportableControl::erase (MSTransportable * transportable) virtual inherited
removes a single transportable
Definition at line 96 of file MSTransportableControl.cpp.
References OutputDevice::getDeviceByOption(), MSTransportable::getID(), OptionsCont::getOptions(), MSTransportableControl::myRunningNumber, MSTransportableControl::myTransportables, MSTransportable::routeOutput(), and MSTransportable::tripInfoOutput().
Referenced by MSTransportableControl::abortWaiting(), MSTransportableControl::checkWaiting(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), MSContainer::MSContainerStage_Tranship::moveToNextEdge(), MSDevice_Transportable::notifyLeave(), MSDevice_Transportable::notifyMove(), and MSPerson::MSPersonStage_Walking::proceed().
MSTransportable * MSTransportableControl::get (const std::string & id) const inherited
Returns the named transportable, if existing.
Parameters
[in] id The id of the transportable
Returns
The named transportable, if existing, otherwise 0
Definition at line 86 of file MSTransportableControl.cpp.
References MSTransportableControl::myTransportables.
Referenced by TraCIServerAPI_Person::getPosition(), TraCIServerAPI_Person::processGet(), and TraCIServerAPI_Person::processSet().
int MSTransportableControl::getJammedNumber () const inline inherited
Returns the number of times a transportables was jammed.
Returns
The number of times transportables were jammed
Definition at line 193 of file MSTransportableControl.h.
References MSTransportableControl::myJammedNumber.
Referenced by MSNet::closeSimulation(), and GUINet::getParameterWindow().
int MSTransportableControl::getLoadedNumber () const inline inherited
Returns the number of build transportables.
Returns
The number of loaded (build) transportables
Definition at line 178 of file MSTransportableControl.h.
References MSTransportableControl::myLoadedNumber.
Referenced by MSNet::closeSimulation(), and GUINet::getParameterWindow().
int MSTransportableControl::getRunningNumber () const inline inherited
Returns the number of build and inserted, but not yet deleted transportables.
Returns
The number of simulated transportables
Definition at line 186 of file MSTransportableControl.h.
References MSTransportableControl::myRunningNumber.
Referenced by MSNet::closeSimulation(), GUINet::getParameterWindow(), and GUIApplicationWindow::handleEvent_SimulationStep().
bool MSTransportableControl::hasNonWaiting () const inherited
checks whether any transportable is still engaged in walking / stopping
Definition at line 240 of file MSTransportableControl.cpp.
References MSTransportableControl::myHaveNewWaiting, MSTransportableControl::myRunningNumber, MSTransportableControl::myWaiting4Departure, and MSTransportableControl::myWaitingForVehicleNumber.
Referenced by MSNet::simulationState().
bool MSTransportableControl::hasTransportables () const inherited
checks whether any transportable waits to finish her plan
Definition at line 234 of file MSTransportableControl.cpp.
References MSTransportableControl::myTransportables.
Referenced by MSNet::simulationStep(), and MSFCDExport::write().
void GUITransportableControl::insertPersonIDs (std::vector< GUIGlID > & into)
Returns the list of all known persons by gl-id.
Parameters
Definition at line 68 of file GUITransportableControl.cpp.
References MSTransportableControl::myTransportables, and MSTransportable::WAITING_FOR_DEPART.
bool MSTransportableControl::loadAnyWaiting (MSEdge * edge, MSVehicle * vehicle, MSVehicle::Stop * stop) inherited
load any applicable containers Loads any container that is waiting on that edge for the given vehicle and removes them from myWaiting
Parameters
[in] the edge on which the loading should take place
[in] the vehicle which is taking on containers
Returns
Whether any containers have been loaded
Definition at line 196 of file MSTransportableControl.cpp.
References MSVehicle::addContainer(), MSVehicle::Stop::duration, MSVehicle::Stop::endPos, MSVehicleType::getContainerCapacity(), MSVehicle::getContainerNumber(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSVehicleType::getLoadingDuration(), MSBaseVehicle::getParameter(), MSBaseVehicle::getVehicleType(), SUMOVehicleParameter::id, SUMOVehicleParameter::line, MSTransportableControl::myWaiting4Vehicle, MSTransportableControl::myWaitingForVehicleNumber, MSEdge::removeContainer(), MSVehicle::Stop::startPos, and MSVehicle::Stop::timeToLoadNextContainer.
Referenced by MSVehicle::processNextStop().
constVehIt MSTransportableControl::loadedBegin () const inline inherited
Returns the begin of the internal transportables map.
Returns
The begin of the internal transportables map
Definition at line 147 of file MSTransportableControl.h.
References MSTransportableControl::myTransportables.
Referenced by TraCIServerAPI_Person::processGet().
constVehIt MSTransportableControl::loadedEnd () const inline inherited
Returns the end of the internal transportables map.
Returns
The end of the internal transportables map
Definition at line 155 of file MSTransportableControl.h.
References MSTransportableControl::myTransportables.
Referenced by TraCIServerAPI_Person::processGet().
void MSTransportableControl::registerJammed () inline inherited
register a jammed transportable
Definition at line 168 of file MSTransportableControl.h.
References MSTransportableControl::myJammedNumber.
Referenced by MSPModel_Striping::PState::walk().
void MSTransportableControl::setWaitEnd (SUMOTime time, MSTransportable * transportable) inherited
sets the arrival time for a waiting transportable
Definition at line 113 of file MSTransportableControl.cpp.
References DELTA_T, and MSTransportableControl::myWaitingUntil.
Referenced by MSTransportable::Stage_Waiting::proceed().
int MSTransportableControl::size () const inline inherited
Returns the number of known transportables.
Returns
The number of stored transportables
Definition at line 163 of file MSTransportableControl.h.
References MSTransportableControl::myTransportables.
Referenced by TraCIServerAPI_Person::processGet().
Field Documentation
bool MSTransportableControl::myHaveNewWaiting protected inherited
whether a new transportable waiting for a vehicle has been added in the last step
Definition at line 225 of file MSTransportableControl.h.
Referenced by MSTransportableControl::addWaiting(), MSTransportableControl::checkWaiting(), and MSTransportableControl::hasNonWaiting().
int MSTransportableControl::myJammedNumber protected inherited
The number of jammed transportables.
Definition at line 219 of file MSTransportableControl.h.
Referenced by MSTransportableControl::getJammedNumber(), and MSTransportableControl::registerJammed().
int MSTransportableControl::myLoadedNumber protected inherited
The number of build transportables.
Definition at line 213 of file MSTransportableControl.h.
Referenced by MSTransportableControl::add(), and MSTransportableControl::getLoadedNumber().
int MSTransportableControl::myRunningNumber protected inherited
The number of transportables within the network (build and inserted but not removed)
Definition at line 216 of file MSTransportableControl.h.
Referenced by MSTransportableControl::checkWaiting(), MSTransportableControl::erase(), MSTransportableControl::getRunningNumber(), and MSTransportableControl::hasNonWaiting().
std::map<std::string, MSTransportable*> MSTransportableControl::myTransportables protected inherited
all currently created transportables by id
Definition at line 201 of file MSTransportableControl.h.
Referenced by MSTransportableControl::add(), MSTransportableControl::erase(), MSTransportableControl::get(), MSTransportableControl::hasTransportables(), insertPersonIDs(), MSTransportableControl::loadedBegin(), MSTransportableControl::loadedEnd(), MSTransportableControl::size(), and MSTransportableControl::~MSTransportableControl().
std::map<SUMOTime, TransportableVector> MSTransportableControl::myWaiting4Departure protected inherited
Transportables waiting for departure.
Definition at line 204 of file MSTransportableControl.h.
Referenced by MSTransportableControl::add(), MSTransportableControl::checkWaiting(), and MSTransportableControl::hasNonWaiting().
std::map<const MSEdge*, TransportableVector> MSTransportableControl::myWaiting4Vehicle protected inherited
the lists of waiting transportables
Definition at line 210 of file MSTransportableControl.h.
Referenced by MSTransportableControl::abortWaiting(), MSTransportableControl::addWaiting(), MSTransportableControl::boardAnyWaiting(), MSTransportableControl::loadAnyWaiting(), and MSTransportableControl::~MSTransportableControl().
int MSTransportableControl::myWaitingForVehicleNumber protected inherited
The number of transportables waiting for vehicles.
Definition at line 222 of file MSTransportableControl.h.
Referenced by MSTransportableControl::addWaiting(), MSTransportableControl::boardAnyWaiting(), MSTransportableControl::hasNonWaiting(), and MSTransportableControl::loadAnyWaiting().
std::map<SUMOTime, TransportableVector> MSTransportableControl::myWaitingUntil protected inherited
the lists of walking / stopping transportables
Definition at line 207 of file MSTransportableControl.h.
Referenced by MSTransportableControl::checkWaiting(), and MSTransportableControl::setWaitEnd().
The documentation for this class was generated from the following files:
GUITransportableControl.h
GUITransportableControl.cpp