SUMO - Simulation of Urban MObility: MSPModel_Striping::PState Class Reference
MSPModel_Striping::PState Class Reference
Container for pedestrian state and individual position update function.
#include <MSPModel_Striping.h>
Public Member Functions
SUMOReal distanceTo (const Obstacle &obs, const bool includeMinGap=true) const
SUMOReal distToLaneEnd () const
the absolute distance to the end of the lane in walking direction (or to the arrivalPos)
SUMOReal getImpatience (SUMOTime now) const
returns the impatience
SUMOReal getLength () const
return the length of the pedestrian
SUMOReal getMaxX (const bool includeMinGap=true) const
return the maximum position on the lane
SUMOReal getMinGap () const
return the minimum gap of the pedestrian
SUMOReal getMinX (const bool includeMinGap=true) const
return the minimum position on the lane
void mergeObstacles (Obstacles &into, const Obstacles &obs2)
replace obstacles in the first vector with obstacles from the second if they are closer to me
bool moveToNextLane (SUMOTime currentTime)
return whether this pedestrian has passed the end of the current lane and update myRelX if so
int otherStripe () const
int otherStripe (const SUMOReal relY) const
PState (MSPerson *person, MSPerson::MSPersonStage_Walking *stage, const MSLane *lane)
int stripe () const
int stripe (const SUMOReal relY) const
void walk (const Obstacles &obs, SUMOTime currentTime)
perform position update
~PState ()
SUMOReal getEdgePos (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const
abstract methods inherited from PedestrianState
Position getPosition (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const
return the network coordinate of the person
SUMOReal getAngle (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const
return the direction in which the person faces in degrees
SUMOTime getWaitingTime (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const
return the time the person spent standing
SUMOReal getSpeed (const MSPerson::MSPersonStage_Walking &stage) const
return the current speed of the person
const MSEdge * getNextEdge (const MSPerson::MSPersonStage_Walking &stage) const
return the list of internal edges if the pedestrian is on an intersection
Data Fields
bool myAmJammed
whether the person is jammed
int myDir
the walking direction on the current lane (1 forward, -1 backward)
const MSLane * myLane
the current lane of this pedestrian
NextLaneInfo myNLI
information about the upcoming lane
MSPerson * myPerson
SUMOReal myRelX
the advancement along the current lane
SUMOReal myRelY
the orthogonal shift on the current lane
SUMOReal mySpeed
the current walking speed
MSPerson::MSPersonStage_Walking * myStage
SUMOTime myWaitingTime
the consecutive time spent at speed 0
bool myWaitingToEnter
whether the pedestrian is waiting to start its walk
WalkingAreaPath * myWalkingAreaPath
the current walkingAreaPath or 0
Detailed Description
Container for pedestrian state and individual position update function.
Definition at line 230 of file MSPModel_Striping.h.
Constructor & Destructor Documentation
MSPModel_Striping::PState::PState (MSPerson * person, MSPerson::MSPersonStage_Walking * stage, const MSLane * lane)
Definition at line 797 of file MSPModel_Striping.cpp.
References MSPModel::BACKWARD, MSPModel::canTraverse(), PedestrianRouter< E, L, N, V, INTERNALROUTER >::compute(), DEBUGCOND, MSPModel::FORWARD, MSPerson::MSPersonStage_Walking::getArrivalPos(), MSLane::getEdge(), MSEdge::getFromJunction(), Named::getID(), MSTransportable::getID(), MSNet::getInstance(), MSPerson::MSPersonStage_Walking::getMaxSpeed(), MSPModel_Striping::getNextLane(), MSNet::getPedestrianRouter(), MSPerson::MSPersonStage_Walking::getRoute(), MSEdge::getToJunction(), MSEdge::isWalkingArea(), myDir, myNLI, myPerson, myRelX, myRelY, myStage, MSPModel_Striping::numStripes(), MSPModel_Striping::stripeWidth, SUMOReal, and toString().
MSPModel_Striping::PState::~PState () inline
Definition at line 245 of file MSPModel_Striping.h.
Member Function Documentation
SUMOReal MSPModel_Striping::PState::distanceTo (const Obstacle & obs, const bool includeMinGap = true) const
Definition at line 1270 of file MSPModel_Striping.cpp.
References DIST_BEHIND, DIST_OVERLAP, MSPModel::FORWARD, getMaxX(), getMinX(), myDir, SUMOReal, MSPModel_Striping::Obstacle::xBack, and MSPModel_Striping::Obstacle::xFwd.
Referenced by MSPModel_Striping::getNeighboringObstacles(), mergeObstacles(), MSPModel_Striping::moveInDirectionOnLane(), and walk().
SUMOReal MSPModel_Striping::PState::distToLaneEnd () const
the absolute distance to the end of the lane in walking direction (or to the arrivalPos)
Definition at line 921 of file MSPModel_Striping.cpp.
References MSPModel::FORWARD, MSPerson::MSPersonStage_Walking::getArrivalPos(), MSLane::getLength(), MSPerson::MSPersonStage_Walking::getNextRouteEdge(), MSPModel_Striping::WalkingAreaPath::length, myDir, myLane, myRelX, myStage, myWalkingAreaPath, POSITION_EPS, and SUMOReal.
Referenced by MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), and moveToNextLane().
SUMOReal MSPModel_Striping::PState::getAngle (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const virtual
return the direction in which the person faces in degrees
Implements PedestrianState.
Definition at line 1237 of file MSPModel_Striping.cpp.
References MSPModel::BACKWARD, MSLane::getShape(), M_PI, myDir, myLane, myRelX, myWalkingAreaPath, PositionVector::rotationAtOffset(), MSPModel_Striping::WalkingAreaPath::shape, and SUMOReal.
SUMOReal MSPModel_Striping::PState::getEdgePos (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const virtual
abstract methods inherited from PedestrianState
Implements PedestrianState.
Definition at line 1216 of file MSPModel_Striping.cpp.
References myRelX.
SUMOReal MSPModel_Striping::PState::getImpatience (SUMOTime now) const
returns the impatience
Definition at line 1208 of file MSPModel_Striping.cpp.
References MSVehicleType::getImpatience(), MSTransportable::getVehicleType(), MSPerson::MSPersonStage_Walking::getWaitingTime(), MAX2(), MSPModel_Striping::MAX_WAIT_TOLERANCE, MIN2(), myPerson, myStage, STEPS2TIME, and SUMOReal.
Referenced by MSPModel_Striping::moveInDirectionOnLane().
SUMOReal MSPModel_Striping::PState::getLength () const
return the length of the pedestrian
Definition at line 872 of file MSPModel_Striping.cpp.
References MSVehicleType::getLength(), MSTransportable::getVehicleType(), myPerson, and SUMOReal.
Referenced by MSPModel_Striping::blockedAtDist(), getMaxX(), getMinX(), and MSPModel_Striping::moveInDirectionOnLane().
SUMOReal MSPModel_Striping::PState::getMaxX (const bool includeMinGap = true) const
return the maximum position on the lane
Definition at line 862 of file MSPModel_Striping.cpp.
References MSPModel::FORWARD, getLength(), getMinGap(), myDir, myRelX, and SUMOReal.
Referenced by distanceTo(), and MSPModel_Striping::Obstacle::Obstacle().
SUMOReal MSPModel_Striping::PState::getMinGap () const
return the minimum gap of the pedestrian
Definition at line 878 of file MSPModel_Striping.cpp.
References MSVehicleType::getMinGap(), MSTransportable::getVehicleType(), and myPerson.
Referenced by getMaxX(), getMinX(), and MSPModel_Striping::moveInDirectionOnLane().
SUMOReal MSPModel_Striping::PState::getMinX (const bool includeMinGap = true) const
return the minimum position on the lane
Definition at line 852 of file MSPModel_Striping.cpp.
References MSPModel::FORWARD, getLength(), getMinGap(), myDir, myRelX, and SUMOReal.
Referenced by distanceTo(), and MSPModel_Striping::Obstacle::Obstacle().
const MSEdge * MSPModel_Striping::PState::getNextEdge (const MSPerson::MSPersonStage_Walking & stage) const virtual
return the list of internal edges if the pedestrian is on an intersection
Implements PedestrianState.
Definition at line 1264 of file MSPModel_Striping.cpp.
References MSLane::getEdge(), MSPModel_Striping::NextLaneInfo::lane, myNLI, and SUMOReal.
Position MSPModel_Striping::PState::getPosition (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const virtual
return the network coordinate of the person
Implements PedestrianState.
Definition at line 1222 of file MSPModel_Striping.cpp.
References MSTransportable::Stage::getLanePosition(), MSLane::getWidth(), Position::INVALID, myLane, myRelX, myRelY, myWalkingAreaPath, PositionVector::positionAtOffset(), MSPModel_Striping::WalkingAreaPath::shape, MSPModel_Striping::stripeWidth, and SUMOReal.
Referenced by MSPModel_Striping::getNextLaneObstacles(), and MSPModel_Striping::moveInDirection().
SUMOReal MSPModel_Striping::PState::getSpeed (const MSPerson::MSPersonStage_Walking & stage) const virtual
return the current speed of the person
Implements PedestrianState.
Definition at line 1258 of file MSPModel_Striping.cpp.
References mySpeed.
SUMOTime MSPModel_Striping::PState::getWaitingTime (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const virtual
return the time the person spent standing
Implements PedestrianState.
Definition at line 1252 of file MSPModel_Striping.cpp.
References myWaitingTime, and SUMOReal.
void MSPModel_Striping::PState::mergeObstacles (Obstacles & into, const Obstacles & obs2)
replace obstacles in the first vector with obstacles from the second if they are closer to me
Definition at line 1286 of file MSPModel_Striping.cpp.
References distanceTo(), and gDebugFlag1.
Referenced by MSPModel_Striping::moveInDirectionOnLane().
bool MSPModel_Striping::PState::moveToNextLane (SUMOTime currentTime)
return whether this pedestrian has passed the end of the current lane and update myRelX if so
Definition at line 932 of file MSPModel_Striping.cpp.
References MSPModel::BACKWARD, DEBUG1, DEBUGCOND, MSPModel_Striping::NextLaneInfo::dir, distToLaneEnd(), MSEdge::EDGEFUNCTION_NORMAL, MSPModel_Striping::WalkingAreaPath::from, MSPerson::MSPersonStage_Walking::getArrivalPos(), OptionsCont::getBool(), MSLane::getEdge(), Named::getID(), MSTransportable::getID(), MSLane::getLength(), MSPModel_Striping::getNextLane(), OptionsCont::getOptions(), MSEdge::getPurpose(), MSLane::getWidth(), MSEdge::isWalkingArea(), MSPModel_Striping::NextLaneInfo::lane, MSPModel_Striping::WalkingAreaPath::length, MSPerson::MSPersonStage_Walking::moveToNextEdge(), myDir, myLane, myNLI, myPerson, myRelX, myRelY, myStage, myWalkingAreaPath, MSPModel_Striping::myWalkingAreaPaths, MSPModel_Striping::WalkingAreaPath::shape, SIMTIME, MSPModel_Striping::stripeWidth, SUMOReal, MSPModel_Striping::WalkingAreaPath::to, and MSPModel::UNDEFINED_DIRECTION.
Referenced by MSPModel_Striping::moveInDirection().
int MSPModel_Striping::PState::otherStripe () const
Definition at line 915 of file MSPModel_Striping.cpp.
References MAX2(), MIN2(), myLane, myRelY, MSPModel_Striping::numStripes(), and SUMOReal.
Referenced by MSPModel_Striping::getNeighboringObstacles(), MSPModel_Striping::getNextLaneObstacles(), MSPModel_Striping::moveInDirectionOnLane(), and walk().
int MSPModel_Striping::PState::otherStripe (const SUMOReal relY) const
Definition at line 890 of file MSPModel_Striping.cpp.
References MSTransportable::getVehicleType(), MSVehicleType::getWidth(), MAX2(), myPerson, NUMERICAL_EPS, MSPModel_Striping::SQUEEZE, stripe(), MSPModel_Striping::stripeWidth, and SUMOReal.
int MSPModel_Striping::PState::stripe () const
Definition at line 909 of file MSPModel_Striping.cpp.
References MAX2(), MIN2(), myLane, myRelY, and MSPModel_Striping::numStripes().
Referenced by MSPModel_Striping::getNeighboringObstacles(), MSPModel_Striping::getNextLaneObstacles(), MSPModel_Striping::moveInDirectionOnLane(), otherStripe(), and walk().
int MSPModel_Striping::PState::stripe (const SUMOReal relY) const
Definition at line 884 of file MSPModel_Striping.cpp.
References MSPModel_Striping::stripeWidth.
void MSPModel_Striping::PState::walk (const Obstacles & obs, SUMOTime currentTime)
perform position update
Definition at line 1015 of file MSPModel_Striping.cpp.
References abs, MSPModel::BACKWARD, MSPModel_Striping::dawdling, MSPModel_Striping::DEBUG_PRINT(), DEBUGCOND, DELTA_T, DIST2SPEED, DIST_OVERLAP, distanceTo(), MSPModel::FORWARD, MSPerson::MSPersonStage_Walking::getEdge(), Named::getID(), MSTransportable::getID(), MSNet::getInstance(), MSPerson::MSPersonStage_Walking::getMaxSpeed(), MSNet::getPersonControl(), MSPerson::MSPersonStage_Walking::getWaitingTime(), MSPModel_Striping::INAPPROPRIATE_PENALTY, MSPModel_Striping::jamTime, MSPModel_Striping::LATERAL_PENALTY, MSPModel_Striping::LATERAL_SPEED_FACTOR, MSPModel_Striping::LOOKAHEAD_ONCOMING, MSPModel_Striping::LOOKAHEAD_SAMEDIR, MAX2(), MIN2(), MIN3(), MSPModel_Striping::MIN_STARTUP_DIST, myAmJammed, myDir, myLane, myPerson, myRelX, myRelY, mySpeed, myStage, myWaitingTime, myWaitingToEnter, NUMERICAL_EPS, MSPModel_Striping::numStripes(), MSPModel_Striping::OBSTRUCTED_PENALTY, MSPModel_Striping::OBSTRUCTION_THRESHOLD, MSPModel_Striping::ONCOMING_CONFLICT_PENALTY, otherStripe(), RandHelper::rand(), MSTransportableControl::registerJammed(), MSPModel_Striping::RESERVE_FOR_ONCOMING_FACTOR, SIMTIME, SPEED2DIST, stripe(), MSPModel_Striping::stripeWidth, SUMO_const_haltingSpeed, SUMOReal, time2string(), toString(), and WRITE_WARNING.
Referenced by MSPModel_Striping::moveInDirectionOnLane().
Field Documentation
bool MSPModel_Striping::PState::myAmJammed
whether the person is jammed
Definition at line 267 of file MSPModel_Striping.h.
Referenced by MSPModel_Striping::moveInDirectionOnLane(), and walk().
int MSPModel_Striping::PState::myDir
the walking direction on the current lane (1 forward, -1 backward)
Definition at line 255 of file MSPModel_Striping.h.
Referenced by MSPModel_Striping::blockedAtDist(), distanceTo(), distToLaneEnd(), MSPModel_Striping::MovePedestrians::execute(), getAngle(), getMaxX(), getMinX(), MSPModel_Striping::getNeighboringObstacles(), MSPModel_Striping::getNextLane(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), moveToNextLane(), MSPModel_Striping::Obstacle::Obstacle(), PState(), and walk().
const MSLane* MSPModel_Striping::PState::myLane
the current lane of this pedestrian
Definition at line 249 of file MSPModel_Striping.h.
Referenced by distToLaneEnd(), getAngle(), getPosition(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), moveToNextLane(), otherStripe(), stripe(), and walk().
NextLaneInfo MSPModel_Striping::PState::myNLI
information about the upcoming lane
Definition at line 263 of file MSPModel_Striping.h.
Referenced by getNextEdge(), MSPModel_Striping::moveInDirectionOnLane(), moveToNextLane(), and PState().
MSPerson* MSPModel_Striping::PState::myPerson
Definition at line 245 of file MSPModel_Striping.h.
Referenced by MSPModel_Striping::blockedAtDist(), MSPModel_Striping::MovePedestrians::execute(), getImpatience(), getLength(), getMinGap(), MSPModel_Striping::getNeighboringObstacles(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextLaneObstacles(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), moveToNextLane(), MSPModel_Striping::by_xpos_sorter::operator()(), otherStripe(), PState(), and walk().
SUMOReal MSPModel_Striping::PState::myRelX
the advancement along the current lane
Definition at line 251 of file MSPModel_Striping.h.
Referenced by MSPModel_Striping::blockedAtDist(), distToLaneEnd(), MSPModel_Striping::MovePedestrians::execute(), getAngle(), getEdgePos(), getMaxX(), getMinX(), getPosition(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), moveToNextLane(), MSPModel_Striping::by_xpos_sorter::operator()(), PState(), and walk().
SUMOReal MSPModel_Striping::PState::myRelY
the orthogonal shift on the current lane
Definition at line 253 of file MSPModel_Striping.h.
Referenced by MSPModel_Striping::MovePedestrians::execute(), MSPModel_Striping::getNextLaneObstacles(), getPosition(), MSPModel_Striping::moveInDirection(), moveToNextLane(), otherStripe(), PState(), stripe(), and walk().
SUMOReal MSPModel_Striping::PState::mySpeed
the current walking speed
Definition at line 257 of file MSPModel_Striping.h.
Referenced by getSpeed(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::Obstacle::Obstacle(), and walk().
MSPerson::MSPersonStage_Walking* MSPModel_Striping::PState::myStage
Definition at line 247 of file MSPModel_Striping.h.
Referenced by distToLaneEnd(), getImpatience(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextLaneObstacles(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), moveToNextLane(), PState(), and walk().
SUMOTime MSPModel_Striping::PState::myWaitingTime
the consecutive time spent at speed 0
Definition at line 261 of file MSPModel_Striping.h.
Referenced by getWaitingTime(), and walk().
bool MSPModel_Striping::PState::myWaitingToEnter
whether the pedestrian is waiting to start its walk
Definition at line 259 of file MSPModel_Striping.h.
Referenced by MSPModel_Striping::getNeighboringObstacles(), MSPModel_Striping::getNextLaneObstacles(), MSPModel_Striping::moveInDirectionOnLane(), MSPModel_Striping::Obstacle::Obstacle(), and walk().
WalkingAreaPath* MSPModel_Striping::PState::myWalkingAreaPath
the current walkingAreaPath or 0
Definition at line 265 of file MSPModel_Striping.h.
Referenced by distToLaneEnd(), GUIPerson::drawAction_drawWalkingareaPath(), getAngle(), getPosition(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), and moveToNextLane().
The documentation for this class was generated from the following files:
MSPModel_Striping.h
MSPModel_Striping.cpp