SUMO - Simulation of Urban MObility: RandHelper Class Reference
RandHelper Class Reference
Utility functions for using a global, resetable random number generator.
#include <RandHelper.h>
Static Public Member Functions
template<class T >
static const T & getRandomFrom (const std::vector< T > &v)
Returns a random element from the given vector.
static void initRandGlobal (MTRand *which=0)
Reads the given random number options and initialises the random number generator in accordance.
static void insertRandOptions ()
Initialises the given options container with random number options.
static SUMOReal rand ()
Returns a random real number in [0, 1)
static SUMOReal rand (SUMOReal maxV)
Returns a random real number in [0, maxV)
static SUMOReal rand (SUMOReal minV, SUMOReal maxV)
Returns a random real number in [minV, maxV)
static int rand (int maxV)
Returns a random integer in [0, maxV-1].
static int rand (int minV, int maxV)
Returns a random integer in [minV, maxV-1].
static long long int rand (long long int maxV)
Returns a random 64 bit integer in [0, maxV-1].
static long long int rand (long long int minV, long long int maxV)
Returns a random 64 bit integer in [minV, maxV-1].
static SUMOReal randNorm (SUMOReal mean, SUMOReal variance, MTRand *rng=0)
Access to a random number from a normal distribution.
Static Protected Attributes
static MTRand myRandomNumberGenerator
the random number generator to use
Detailed Description
Utility functions for using a global, resetable random number generator.
Definition at line 53 of file RandHelper.h.
Member Function Documentation
template<class T > static const T& RandHelper::getRandomFrom (const std::vector< T > & v) inline static
Returns a random element from the given vector.
Definition at line 114 of file RandHelper.h.
References rand().
Referenced by MSEdge::getDepartLane(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), AGCity::getRandomStreet(), and AGAdult::randomFreeWorkPosition().
void RandHelper::initRandGlobal (MTRand * which = 0) static
Reads the given random number options and initialises the random number generator in accordance.
Definition at line 68 of file RandHelper.cpp.
References OptionsCont::getBool(), OptionsCont::getInt(), OptionsCont::getOptions(), MTRand::hash(), myRandomNumberGenerator, and MTRand::seed().
Referenced by main(), GNELoadThread::run(), and GUILoadThread::run().
void RandHelper::insertRandOptions () static
Initialises the given options container with random number options.
Definition at line 53 of file RandHelper.cpp.
References OptionsCont::addDescription(), OptionsCont::addOptionSubTopic(), OptionsCont::addSynonyme(), OptionsCont::doRegister(), and OptionsCont::getOptions().
Referenced by RODFFrame::fillOptions(), AGFrame::fillOptions(), ROJTRFrame::fillOptions(), RODUAFrame::fillOptions(), ROMAFrame::fillOptions(), fillOptions(), MSFrame::fillOptions(), and GNELoadThread::fillOptions().
static SUMOReal RandHelper::rand () inline static
Returns a random real number in [0, 1)
Definition at line 62 of file RandHelper.h.
References myRandomNumberGenerator, MTRand::randExc(), and SUMOReal.
Referenced by RORouteDef::addAlternative(), RONet::addFlow(), MSBaseVehicle::calculateArrivalParams(), RONet::checkFlows(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODMatrix::computeDeparts(), NGRandomNetBuilder::createNet(), NGRandomNetBuilder::createNewNode(), MSCFModel_Kerner::createVehicleVariables(), MSCFModel_Krauss::dawdle(), MSCFModel_Daniel1::dawdle(), MSCFModel_SmartSK::dawdle(), MSCFModel_KraussOrig1::dawdle(), GLHelper::debugVertices(), AGPerson::decide(), MSSwarmTrafficLightLogic::decidePolicy(), AGFreeTime::decideTypeOfTrip(), MSInsertionControl::determineCandidates(), MSDevice::equippedByDefaultAssignmentOptions(), MSCFModel_PWag2009::followSpeed(), AGHousehold::generateCars(), AGWorkPosition::generateClosingTime(), AGWorkPosition::generateOpeningTime(), AGCity::generatePopulation(), AGActivities::generateRandomTraffic(), RandomDistributor< SUMOVTypeParameter * >::get(), MSLane::getDepartSpeed(), MSDevice_Routing::getEffort(), AGDataAndStatistics::getInverseExpRandomValue(), AGDataAndStatistics::getPoissonsNumberOfChildren(), AGDataAndStatistics::getRandom(), AGDataAndStatistics::getRandomCityGateByIncoming(), AGDataAndStatistics::getRandomCityGateByOutgoing(), getRandomFrom(), AGDataAndStatistics::getRandomPopDistributed(), MSLane::insertVehicle(), MSEdge::insertVehicle(), MSSOTLTrafficLightLogic::isThresholdPassed(), MSCFModel_Kerner::moveHelper(), MSTriggeredRerouter::notifyEnter(), TNeighbourDistribution::num(), MESegment::overtake(), rand(), AGPosition::randomPositionInStreet(), AGActivity::randomTimeBetween(), MELoop::setApproaching(), SigmoidLogic::sigmoidLogic(), NGNet::toNB(), MSCFModel_SmartSK::updateMyHeadway(), and MSPModel_Striping::PState::walk().
static SUMOReal RandHelper::rand (SUMOReal maxV) inline static
Returns a random real number in [0, maxV)
Definition at line 67 of file RandHelper.h.
References rand().
static SUMOReal RandHelper::rand (SUMOReal minV, SUMOReal maxV) inline static
Returns a random real number in [minV, maxV)
Definition at line 72 of file RandHelper.h.
References rand().
static int RandHelper::rand (int maxV) inline static
Returns a random integer in [0, maxV-1].
Definition at line 77 of file RandHelper.h.
References myRandomNumberGenerator, and MTRand::randInt().
static int RandHelper::rand (int minV, int maxV) inline static
Returns a random integer in [minV, maxV-1].
Definition at line 82 of file RandHelper.h.
References rand().
static long long int RandHelper::rand (long long int maxV) inline static
Returns a random 64 bit integer in [0, maxV-1].
Definition at line 87 of file RandHelper.h.
References myRandomNumberGenerator, and MTRand::randInt64().
static long long int RandHelper::rand (long long int minV, long long int maxV) inline static
Returns a random 64 bit integer in [minV, maxV-1].
Definition at line 92 of file RandHelper.h.
References rand().
static SUMOReal RandHelper::randNorm (SUMOReal mean, SUMOReal variance, MTRand * rng = 0) inline static
Access to a random number from a normal distribution.
Definition at line 97 of file RandHelper.h.
References myRandomNumberGenerator, MTRand::randExc(), and SUMOReal.
Referenced by MSCFModel_Wiedemann::_v(), MSVehicleType::computeChosenSpeedDeviation(), and AGActivityGen::varDepTime().
Field Documentation
MTRand RandHelper::myRandomNumberGenerator static protected
the random number generator to use
Definition at line 122 of file RandHelper.h.
Referenced by initRandGlobal(), rand(), and randNorm().
The documentation for this class was generated from the following files:
RandHelper.h
RandHelper.cpp