SUMO - Simulation of Urban MObility: HelpersHarmonoise Class Reference
HelpersHarmonoise Class Reference
Helper methods for Harmonoise-based noise emission computation.
#include <HelpersHarmonoise.h>
Static Public Member Functions
static SUMOReal computeNoise (SUMOEmissionClass c, double v, double a)
Returns the noise produced by the a vehicle of the given type at the given speed.
static SUMOReal sum (SUMOReal val)
Computes the resulting noise.
Static Private Attributes
static double myAOctaveBandCorrection [27]
A-weighted correction for octave bands.
vehicle class noise emission coefficients
static double myR_A_C1_Parameter [27] = { 69.9, 69.9, 69.9, 74.9, 74.9, 74.9, 77.3, 77.5, 78.1, 78.3, 78.9, 77.8, 78.5, 81.9, 84.1, 86.5, 88.6, 88.2, 87.6, 85.8, 82.8, 80.2, 77.6, 75.0, 72.8, 70.4, 67.9 }
rolling component, light vehicles, alpha
static double myR_B_C1_Parameter [27] = { 33.0, 33.0, 33.0, 15.2, 15.2, 15.2, 41.0, 41.2, 42.3, 41.8, 38.6, 35.5, 31.7, 21.5, 21.2, 23.5, 29.1, 33.5, 34.1, 35.1, 36.4, 37.4, 38.9, 39.7, 39.7, 39.7, 39.7 }
rolling component, light vehicles, beta
static double myR_A_C3_Parameter [27] = { 80.5, 80.5, 80.5, 82.5, 83.5, 83.5, 86.5, 88.3, 88.7, 88.3, 91.4, 92.2, 96.0, 98.1, 97.8, 98.4, 97.2, 94.6, 95.9, 90.5, 87.1, 85.1, 83.2, 81.3, 81.3, 81.3, 81.3 }
rolling component, heavy vehicles, alpha
static double myR_B_C3_Parameter [27] = { 33.0, 33.0, 33.0, 30.0, 30.0, 30.0, 41.0, 41.2, 42.3, 41.8, 38.6, 35.5, 31.7, 21.5, 21.2, 23.5, 29.1, 33.5, 34.1, 35.1, 36.4, 37.4, 38.9, 39.7, 39.7, 39.7, 39.7 }
rolling component, heavy vehicles, beta
static double myT_A_C1_Parameter [27] = { 90.0, 92.0, 89.0, 91.0, 92.4, 94.8, 90.8, 86.8, 86.2, 84.5, 84.5, 84.8, 83.5, 81.8, 81.4, 79.0, 79.2, 81.4, 85.5, 85.8, 85.2, 82.9, 81.0, 78.2, 77.2, 75.2, 74.2 }
traction component, light vehicles, alpha
static double myT_B_C1_Parameter [27] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4 }
traction component, light vehicles, beta
static double myT_A_C3_Parameter [27] = { 97.7, 97.3, 98.2, 103.3, 109.5, 104.3, 99.8, 100.2, 98.9, 99.5, 100.7, 101.2, 100.6, 100.2, 97.4, 97.1, 97.8, 97.3, 95.8, 94.9, 92.7, 90.6, 89.9, 87.9, 85.9, 83.8, 82.2 }
traction component, heavy vehicles, alpha
static double myT_B_C3_Parameter [27] = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7 }
traction component, heavy vehicles, beta
Detailed Description
Helper methods for Harmonoise-based noise emission computation.
The stored values compute the recepted noise of either passenger or heavy duty vehicles for a distance of 10m from the noise source.
Definition at line 51 of file HelpersHarmonoise.h.
Member Function Documentation
SUMOReal HelpersHarmonoise::computeNoise (SUMOEmissionClass c, double v, double a) static
Returns the noise produced by the a vehicle of the given type at the given speed.
Parameters
[in] c The vehicle emission class
[in] v The vehicle's current velocity
[in] a The vehicle's current acceleration
Returns
The noise produced by the vehicle of the given class running with v and a
Definition at line 108 of file HelpersHarmonoise.cpp.
References PollutantsInterface::isHeavy(), PollutantsInterface::isSilent(), myAOctaveBandCorrection, myR_A_C1_Parameter, myR_A_C3_Parameter, myR_B_C1_Parameter, myR_B_C3_Parameter, myT_A_C1_Parameter, myT_A_C3_Parameter, myT_B_C1_Parameter, myT_B_C3_Parameter, and SUMOReal.
Referenced by MSVehicle::getHarmonoise_NoiseEmissions(), ROEdge::getNoiseEffort(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), MSEmissionExport::write(), and MSFullExport::writeVehicles().
static SUMOReal HelpersHarmonoise::sum (SUMOReal val) inline static
Computes the resulting noise.
Parameters
[in] val The sum of converted vehicle noises (pow(10., (<NOISE>/10.)))
Returns
The resulting sum
Definition at line 68 of file HelpersHarmonoise.h.
References SUMOReal.
Referenced by MSMeanData_Harmonoise::MSLaneMeanDataValues::addTo(), MSLane::getHarmonoise_NoiseEmissions(), TraCIServerAPI_Edge::processGet(), and MSMeanData_Harmonoise::MSLaneMeanDataValues::update().
Field Documentation
double HelpersHarmonoise::myAOctaveBandCorrection static private
Initial value:
= { -44.7, -39.4, -34.6, -30.2, -26.2, -22.5, -19.1, -16.1, -13.4,
                                                   -10.9, -8.6, -6.6, -4.8, -3.2, -1.9, -0.8, 0.0, +0.6,
                                                   +1.0, +1.2, +1.3, +1.2, +1.0, +0.5, -0.1, -1.1, -2.5
                                                 }
A-weighted correction for octave bands.
Definition at line 104 of file HelpersHarmonoise.h.
Referenced by computeNoise().
double HelpersHarmonoise::myR_A_C1_Parameter = { 69.9, 69.9, 69.9, 74.9, 74.9, 74.9, 77.3, 77.5, 78.1, 78.3, 78.9, 77.8, 78.5, 81.9, 84.1, 86.5, 88.6, 88.2, 87.6, 85.8, 82.8, 80.2, 77.6, 75.0, 72.8, 70.4, 67.9 } static private
rolling component, light vehicles, alpha
Definition at line 78 of file HelpersHarmonoise.h.
Referenced by computeNoise().
double HelpersHarmonoise::myR_A_C3_Parameter = { 80.5, 80.5, 80.5, 82.5, 83.5, 83.5, 86.5, 88.3, 88.7, 88.3, 91.4, 92.2, 96.0, 98.1, 97.8, 98.4, 97.2, 94.6, 95.9, 90.5, 87.1, 85.1, 83.2, 81.3, 81.3, 81.3, 81.3 } static private
rolling component, heavy vehicles, alpha
Definition at line 84 of file HelpersHarmonoise.h.
Referenced by computeNoise().
double HelpersHarmonoise::myR_B_C1_Parameter = { 33.0, 33.0, 33.0, 15.2, 15.2, 15.2, 41.0, 41.2, 42.3, 41.8, 38.6, 35.5, 31.7, 21.5, 21.2, 23.5, 29.1, 33.5, 34.1, 35.1, 36.4, 37.4, 38.9, 39.7, 39.7, 39.7, 39.7 } static private
rolling component, light vehicles, beta
Definition at line 81 of file HelpersHarmonoise.h.
Referenced by computeNoise().
double HelpersHarmonoise::myR_B_C3_Parameter = { 33.0, 33.0, 33.0, 30.0, 30.0, 30.0, 41.0, 41.2, 42.3, 41.8, 38.6, 35.5, 31.7, 21.5, 21.2, 23.5, 29.1, 33.5, 34.1, 35.1, 36.4, 37.4, 38.9, 39.7, 39.7, 39.7, 39.7 } static private
rolling component, heavy vehicles, beta
Definition at line 87 of file HelpersHarmonoise.h.
Referenced by computeNoise().
double HelpersHarmonoise::myT_A_C1_Parameter = { 90.0, 92.0, 89.0, 91.0, 92.4, 94.8, 90.8, 86.8, 86.2, 84.5, 84.5, 84.8, 83.5, 81.8, 81.4, 79.0, 79.2, 81.4, 85.5, 85.8, 85.2, 82.9, 81.0, 78.2, 77.2, 75.2, 74.2 } static private
traction component, light vehicles, alpha
Definition at line 90 of file HelpersHarmonoise.h.
Referenced by computeNoise().
double HelpersHarmonoise::myT_A_C3_Parameter = { 97.7, 97.3, 98.2, 103.3, 109.5, 104.3, 99.8, 100.2, 98.9, 99.5, 100.7, 101.2, 100.6, 100.2, 97.4, 97.1, 97.8, 97.3, 95.8, 94.9, 92.7, 90.6, 89.9, 87.9, 85.9, 83.8, 82.2 } static private
traction component, heavy vehicles, alpha
Definition at line 96 of file HelpersHarmonoise.h.
Referenced by computeNoise().
double HelpersHarmonoise::myT_B_C1_Parameter = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4, 9.4 } static private
traction component, light vehicles, beta
Definition at line 93 of file HelpersHarmonoise.h.
Referenced by computeNoise().
double HelpersHarmonoise::myT_B_C3_Parameter = { 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7, 11.7 } static private
traction component, heavy vehicles, beta
Definition at line 99 of file HelpersHarmonoise.h.
Referenced by computeNoise().
The documentation for this class was generated from the following files:
HelpersHarmonoise.h
HelpersHarmonoise.cpp