SUMO - Simulation of Urban MObility: AGSchool Class Reference
AGSchool Class Reference
#include <AGSchool.h>
Public Member Functions
bool acceptThisAge (int age)
bool addNewChild ()
AGSchool (int capacity_, AGPosition pos, int beginAge, int endAge, int open, int close)
int getBeginAge ()
int getClosingHour ()
int getEndAge ()
int getOpeningHour ()
int getPlaces ()
AGPosition getPosition ()
void print () const
bool removeChild ()
Private Attributes
int beginAge
int capacity
int closing
int endAge
int initCapacity
AGPosition location
int opening
Detailed Description
Definition at line 44 of file AGSchool.h.
Constructor & Destructor Documentation
AGSchool::AGSchool (int capacity_, AGPosition pos, int beginAge, int endAge, int open, int close) inline
Definition at line 46 of file AGSchool.h.
References acceptThisAge(), addNewChild(), getBeginAge(), getClosingHour(), getEndAge(), getOpeningHour(), getPlaces(), getPosition(), print(), and removeChild().
Member Function Documentation
bool AGSchool::acceptThisAge (int age)
Definition at line 73 of file AGSchool.cpp.
References beginAge.
Referenced by AGSchool().
bool AGSchool::addNewChild ()
Definition at line 55 of file AGSchool.cpp.
References capacity.
Referenced by AGSchool(), and AGChild::setSchool().
int AGSchool::getBeginAge ()
Definition at line 81 of file AGSchool.cpp.
References beginAge.
Referenced by AGSchool().
int AGSchool::getClosingHour ()
Definition at line 96 of file AGSchool.cpp.
References closing.
Referenced by AGSchool(), and AGChild::getSchoolClosing().
int AGSchool::getEndAge ()
Definition at line 86 of file AGSchool.cpp.
References endAge.
Referenced by AGSchool().
int AGSchool::getOpeningHour ()
Definition at line 101 of file AGSchool.cpp.
References opening.
Referenced by AGSchool(), and AGChild::getSchoolOpening().
int AGSchool::getPlaces ()
Definition at line 50 of file AGSchool.cpp.
References capacity.
Referenced by AGSchool().
AGPosition AGSchool::getPosition ()
Definition at line 91 of file AGSchool.cpp.
References location.
Referenced by AGSchool(), and AGChild::getSchoolLocation().
void AGSchool::print () const
Definition at line 45 of file AGSchool.cpp.
References beginAge, capacity, closing, endAge, and opening.
Referenced by AGSchool().
bool AGSchool::removeChild ()
Definition at line 64 of file AGSchool.cpp.
References capacity, and initCapacity.
Referenced by AGSchool(), and AGChild::leaveSchool().
Field Documentation
int AGSchool::beginAge private
Definition at line 66 of file AGSchool.h.
Referenced by acceptThisAge(), getBeginAge(), and print().
int AGSchool::capacity private
Definition at line 67 of file AGSchool.h.
Referenced by addNewChild(), getPlaces(), print(), and removeChild().
int AGSchool::closing private
Definition at line 70 of file AGSchool.h.
Referenced by getClosingHour(), and print().
int AGSchool::endAge private
Definition at line 66 of file AGSchool.h.
Referenced by getEndAge(), and print().
int AGSchool::initCapacity private
Definition at line 68 of file AGSchool.h.
Referenced by removeChild().
AGPosition AGSchool::location private
Definition at line 69 of file AGSchool.h.
Referenced by getPosition().
int AGSchool::opening private
Definition at line 70 of file AGSchool.h.
Referenced by getOpeningHour(), and print().
The documentation for this class was generated from the following files:
AGSchool.h
AGSchool.cpp