SUMO - Simulation of Urban MObility: MSStateHandler Class Reference
MSStateHandler Class Reference
Parser and output filter for routes and vehicles state saving and loading.
#include <MSStateHandler.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
SUMOTime getTime () const
MSStateHandler (const std::string &file, const SUMOTime offset)
standard constructor
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
virtual ~MSStateHandler ()
standard destructor
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Static Public Member Functions
static void saveState (const std::string &file, SUMOTime step)
Saves the current state.
Protected Member Functions
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
inherited from GenericSAXHandler
void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
void myEndElement (int element)
Called when a closing tag occurs.
Private Member Functions
MSStateHandler (const MSStateHandler &s)
Invalidated copy constructor.
MSStateHandler & operator= (const MSStateHandler &s)
Invalidated assignment operator.
Private Attributes
SUMOVTypeParameter * myCurrentVType
The currently parsed vehicle type.
std::pair< int, int > myEdgeAndLane
const SUMOTime myOffset
int myQueIndex
MESegment * mySegment
SUMOTime myTime
Detailed Description
Parser and output filter for routes and vehicles state saving and loading.
Definition at line 52 of file MSStateHandler.h.
Constructor & Destructor Documentation
MSStateHandler::MSStateHandler (const std::string & file, const SUMOTime offset)
standard constructor
Definition at line 62 of file MSStateHandler.cpp.
MSStateHandler::~MSStateHandler () virtual
standard destructor
Definition at line 70 of file MSStateHandler.cpp.
References myCurrentVType.
MSStateHandler::MSStateHandler (const MSStateHandler & s) private
Invalidated copy constructor.
Member Function Documentation
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 192 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 175 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 211 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), MSRouteHandler::myStartElement(), and MSRouteHandler::parseWalkPos().
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 217 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
SUMOTime MSStateHandler::getTime () const inline
Definition at line 66 of file MSStateHandler.h.
References myEndElement(), myStartElement(), and myTime.
Referenced by NLBuilder::build().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 227 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void MSStateHandler::myEndElement (int element) protected virtual
Called when a closing tag occurs.
Parameters
[in] element ID of the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myEndElement
Reimplemented from GenericSAXHandler.
Definition at line 243 of file MSStateHandler.cpp.
References MSVehicleControl::addVType(), MSVehicleType::build(), MSNet::getInstance(), MSNet::getVehicleControl(), myCurrentVType, and SUMO_TAG_VTYPE.
Referenced by getTime().
void MSStateHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 101 of file MSStateHandler.cpp.
References TplConvert::_2long(), RandomDistributor< T >::add(), MSInsertionControl::add(), MSRoute::addReference(), MSVehicleControl::addVehicle(), MSVehicleControl::addVTypeDistribution(), SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleControl::buildVehicle(), SUMOVehicleParameter::depart, MSRoute::dictionary(), MSVehicleControl::discountStateLoaded(), MSEdge::getAllEdges(), SUMOSAXAttributes::getBool(), MESegment::getEdge(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getFloat(), MSNet::getInsertionControl(), MSNet::getInstance(), SUMOSAXAttributes::getInt(), MESegment::getNextSegment(), MSEdge::getNumericalID(), MELoop::getSegmentForEdge(), SUMOSAXAttributes::getString(), MSVehicleControl::getVehicle(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), MSGlobals::gMesoNet, MSGlobals::gUseMesoSim, SUMOVehicleParameter::id, MESegment::loadState(), myCurrentVType, myEdgeAndLane, myOffset, myQueIndex, mySegment, myTime, MSMoveReminder::NOTIFICATION_DEPARTED, MSDevice_Routing::notifyEnter(), MSEdge::parseEdgesList(), SUMOSAXAttributes::parseStringVector(), SUMOVehicleParserHelper::parseVTypeEmbedded(), SUMOVehicleParameter::routeid, MSVehicleControl::setState(), string2time(), SUMO_ATTR_BEGIN, SUMO_ATTR_DEPART, SUMO_ATTR_EDGES, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_ATTR_NUMBER, SUMO_ATTR_PROBS, SUMO_ATTR_ROUTE, SUMO_ATTR_ROUTES, SUMO_ATTR_STATE, SUMO_ATTR_TIME, SUMO_ATTR_TYPE, SUMO_ATTR_VALUE, SUMO_ATTR_VERSION, SUMO_ATTR_VTYPES, SUMO_TAG_DELAY, SUMO_TAG_LANE, SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_DISTRIBUTION, SUMO_TAG_SEGMENT, SUMO_TAG_SNAPSHOT, SUMO_TAG_VEHICLE, SUMO_TAG_VIEWSETTINGS_VEHICLES, SUMO_TAG_VTYPE, SUMO_TAG_VTYPE_DISTRIBUTION, SUMOReal, VERSION_STRING, SUMOVehicleParameter::vtypeid, and WRITE_WARNING.
Referenced by getTime().
MSStateHandler& MSStateHandler::operator= (const MSStateHandler & s) private
Invalidated assignment operator.
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 167 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
void MSStateHandler::saveState (const std::string & file, SUMOTime step) static
Saves the current state.
Parameters
[in] file The file to write the state into
Definition at line 76 of file MSStateHandler.cpp.
References OutputDevice::close(), MSRoute::dict_saveState(), MSEdge::dictSize(), MSEdge::getAllEdges(), OutputDevice::getDevice(), MSNet::getInstance(), MSNet::getVehicleControl(), MSGlobals::gMesoNet, MSGlobals::gUseMesoSim, MSVehicleControl::saveState(), SUMO_ATTR_TIME, SUMO_ATTR_VERSION, SUMO_TAG_SNAPSHOT, time2string(), VERSION_STRING, OutputDevice::writeAttr(), and OutputDevice::writeHeader().
Referenced by TraCIServerAPI_Simulation::processSet(), and MSNet::simulationStep().
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 205 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
SUMOVTypeParameter* MSStateHandler::myCurrentVType private
The currently parsed vehicle type.
Definition at line 103 of file MSStateHandler.h.
Referenced by myEndElement(), myStartElement(), and ~MSStateHandler().
std::pair<int, int> MSStateHandler::myEdgeAndLane private
Definition at line 99 of file MSStateHandler.h.
Referenced by myStartElement().
const SUMOTime MSStateHandler::myOffset private
Definition at line 96 of file MSStateHandler.h.
Referenced by myStartElement().
int MSStateHandler::myQueIndex private
Definition at line 100 of file MSStateHandler.h.
Referenced by myStartElement().
MESegment* MSStateHandler::mySegment private
Definition at line 98 of file MSStateHandler.h.
Referenced by myStartElement().
SUMOTime MSStateHandler::myTime private
Definition at line 97 of file MSStateHandler.h.
Referenced by getTime(), and myStartElement().
The documentation for this class was generated from the following files:
MSStateHandler.h
MSStateHandler.cpp