SUMO - Simulation of Urban MObility: NBLoadedTLDef Class Reference
NBLoadedTLDef Class Reference
A loaded (complete) traffic light logic.
#include <NBLoadedTLDef.h>
Data Structures
class SignalGroup
A single signal group, may control several connections.
Public Types
typedef std::map< std::string, SignalGroup * > SignalGroupCont
Definition of the container for signal groups.
enum TLColor {
TLCOLOR_RED, TLCOLOR_YELLOW, TLCOLOR_REDYELLOW, TLCOLOR_GREEN,
TLCOLOR_BLINK
}
An enumeration of possible tl-signal states.
Public Member Functions
void addControlledInnerEdges (const std::vector< std::string > &edges)
Adds the given ids into the list of inner edges controlled by the tls.
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
void addSignalGroup (const std::string &id)
Adds a signal group.
void addSignalGroupPhaseBegin (const std::string &groupid, SUMOTime time, TLColor color)
Sets the information about the begin of a phase.
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
bool addToSignalGroup (const std::string &groupid, const NBConnection &connection)
Adds a connection to a signal group.
bool addToSignalGroup (const std::string &groupid, const NBConnectionVector &connections)
Adds a list of connections to a signal group.
void clearParameter ()
Clears the parameter map.
NBTrafficLightLogic * compute (OptionsCont &oc)
Computes the traffic light logic.
SignalGroup * findGroup (NBEdge *from, NBEdge *to) const
Returns the signal group which is responsible for the given connection.
bool foes (const NBEdge *const from1, const NBEdge *const to1, const NBEdge *const from2, const NBEdge *const to2) const
Returns the information whether the given flows cross.
bool forbids (const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, bool regardNonSignalisedLowerPriority, bool sameNodeOnly=false) const
Returns the information whether "prohibited" flow must let "prohibitor" flow pass.
std::vector< std::string > getControlledInnerEdges () const
Retrieve the ids of edges explicitly controlled by the tls.
const NBConnectionVector & getControlledLinks () const
returns the controlled links (depends on previous call to collectLinks)
const std::string & getID () const
Returns the id.
const EdgeVector & getIncomingEdges () const
Returns the list of incoming edges (must be build first)
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
SUMOTime getOffset ()
Returns the offset.
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
const std::string & getProgramID () const
Returns the ProgramID.
TrafficLightType getType () const
get the algorithm type (static etc..)
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
bool mustBrake (const NBEdge *const from, const NBEdge *const to) const
Returns the information whether the described flow must let any other flow pass.
bool mustBrake (const NBConnection &possProhibited, const NBConnection &possProhibitor, bool regardNonSignalisedLowerPriority) const
Returns the information whether the described flow must let the other flow pass.
bool mustBrake (const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, bool regardNonSignalisedLowerPriority) const
Returns the information whether the described flow must let any other flow pass.
NBLoadedTLDef (const NBEdgeCont &ec, const std::string &id, const std::vector< NBNode * > &junctions, SUMOTime offset, TrafficLightType type)
Constructor.
NBLoadedTLDef (const NBEdgeCont &ec, const std::string &id, NBNode *junction, SUMOTime offset, TrafficLightType type)
Constructor.
NBLoadedTLDef (const NBEdgeCont &ec, const std::string &id, SUMOTime offset, TrafficLightType type)
Constructor.
bool needsCont (const NBEdge *fromE, const NBEdge *toE, const NBEdge *otherFromE, const NBEdge *otherToE) const
virtual bool rightOnRedConflict (int index, int foeIndex) const
whether the given index must yield to the foeIndex while turing right on a red light
void setCycleDuration (int cycleDur)
Sets the duration of a cycle.
void setID (const std::string &newID)
resets the id
virtual void setParticipantsInformation ()
Builds the list of participating nodes/edges/links.
void setProgramID (const std::string &programID)
Sets the programID.
void setSignalYellowTimes (const std::string &groupid, SUMOTime tRedYellow, SUMOTime tYellow)
Sets the times the light is yellow or red/yellow.
virtual void shiftTLConnectionLaneIndex (NBEdge *edge, int offset)
patches (loaded) signal plans by modifying lane indices
~NBLoadedTLDef ()
Destructor.
Public methods from NBTrafficLightDefinition-interface
void setTLControllingInformation () const
Informs edges about being controlled by a tls.
void remapRemoved (NBEdge *removed, const EdgeVector &incoming, const EdgeVector &outgoing)
Replaces occurences of the removed edge in incoming/outgoing edges of all definitions.
void initNeedsContRelation () const
Access to controlled nodes
virtual void addNode (NBNode *node)
Adds a node to the traffic light logic.
virtual void removeNode (NBNode *node)
Removes the given node from the list of controlled nodes.
const std::vector< NBNode * > & getNodes () const
Returns the list of controlled nodes.
Static Public Member Functions
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
Static Public Attributes
static const std::string DefaultProgramID = "0"
Protected Types
typedef std::set< StreamPair > NeedsContRelation
typedef std::set< std::pair< int, int > > RightOnRedConflicts
Protected Member Functions
virtual bool amInvalid () const
void collectAllLinks ()
helper method for use in NBOwnTLDef and NBLoadedSUMOTLDef
virtual void collectEdges ()
Build the list of participating edges.
int computeBrakingTime (SUMOReal minDecel) const
Computes the time vehicles may need to brake.
Protected methods from NBTrafficLightDefinition-interface
NBTrafficLightLogic * myCompute (int brakingTimeSeconds)
Computes the traffic light logic finally in dependence to the type.
void collectNodes ()
Collects the nodes participating in this traffic light.
void collectLinks ()
Collects the links participating in this traffic light
Exceptions
ProcessError If a link could not be found.
bool mustBrake (const NBConnection &possProhibited, const std::string &state, int strmpos) const
Returns the information whether a connection must brake, given a phase.
void replaceRemoved (NBEdge *removed, int removedLane, NBEdge *by, int byLane)
Replaces a removed edge/lane.
Protected Attributes
std::set< std::string > myControlledInnerEdges
Set of inner edges that shall be controlled, though.
NBConnectionVector myControlledLinks
The list of controlled links.
std::vector< NBNode * > myControlledNodes
The container with participating nodes.
EdgeVector myEdgesWithin
The list of edges within the area controlled by the tls.
std::string myID
The name of the object.
EdgeVector myIncomingEdges
The list of incoming edges.
NeedsContRelation myNeedsContRelation
bool myNeedsContRelationReady
SUMOTime myOffset
The offset in the program.
RightOnRedConflicts myRightOnRedConflicts
bool myRightOnRedConflictsReady
std::string mySubID
The tls program's subid.
TrafficLightType myType
The algorithm type for the traffic light.
Static Protected Attributes
static const std::string DummyID = "dummy"
id for temporary definitions
Private Member Functions
std::string buildPhaseState (int time) const
Builds the phase for a given time.
Private Attributes
int myCycleDuration
The duration of a single cycle.
const NBEdgeCont * myEdgeCont
SignalGroupCont mySignalGroups
Controlled signal groups.
Detailed Description
A loaded (complete) traffic light logic.
Definition at line 49 of file NBLoadedTLDef.h.
Member Typedef Documentation
typedef std::set<StreamPair> NBTrafficLightDefinition::NeedsContRelation protected inherited
Definition at line 431 of file NBTrafficLightDefinition.h.
typedef std::set<std::pair<int, int> > NBTrafficLightDefinition::RightOnRedConflicts protected inherited
Definition at line 435 of file NBTrafficLightDefinition.h.
typedef std::map<std::string, SignalGroup*> NBLoadedTLDef::SignalGroupCont
Definition of the container for signal groups.
Definition at line 205 of file NBLoadedTLDef.h.
Member Enumeration Documentation
enum NBTrafficLightDefinition::TLColor inherited
An enumeration of possible tl-signal states.
Enumerator
TLCOLOR_RED
Signal shows red.
TLCOLOR_YELLOW
Signal shows yellow.
TLCOLOR_REDYELLOW
Signal shows red/yellow (unused)
TLCOLOR_GREEN
Signal shows green.
TLCOLOR_BLINK
Signal is blinking yellow.
Definition at line 84 of file NBTrafficLightDefinition.h.
Constructor & Destructor Documentation
NBLoadedTLDef::NBLoadedTLDef (const NBEdgeCont & ec, const std::string & id, const std::vector< NBNode * > & junctions, SUMOTime offset, TrafficLightType type)
Constructor.
Parameters
[in] id The id of the tls
[in] junctions Junctions controlled by this tls
[in] offset The offset of the plan
[in] type The algorithm type for the computed traffic light
Definition at line 268 of file NBLoadedTLDef.cpp.
NBLoadedTLDef::NBLoadedTLDef (const NBEdgeCont & ec, const std::string & id, NBNode * junction, SUMOTime offset, TrafficLightType type)
Constructor.
Parameters
[in] id The id of the tls
[in] junction The junction controlled by this tls
[in] offset The offset of the plan
[in] type The algorithm type for the computed traffic light
Definition at line 275 of file NBLoadedTLDef.cpp.
NBLoadedTLDef::NBLoadedTLDef (const NBEdgeCont & ec, const std::string & id, SUMOTime offset, TrafficLightType type)
Constructor.
Parameters
[in] id The id of the tls
[in] offset The offset of the plan
[in] type The algorithm type for the computed traffic light
Definition at line 281 of file NBLoadedTLDef.cpp.
NBLoadedTLDef::~NBLoadedTLDef ()
Destructor.
Definition at line 287 of file NBLoadedTLDef.cpp.
References mySignalGroups.
Member Function Documentation
void NBTrafficLightDefinition::addControlledInnerEdges (const std::vector< std::string > & edges) inherited
Adds the given ids into the list of inner edges controlled by the tls.
Parameters
[in] edges The list of edge ids which shall be controlled despite lying with the jointly controlled node cluster
Definition at line 398 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myControlledInnerEdges.
Referenced by NBTrafficLightDefinition::getNodes(), and NIXMLTrafficLightsHandler::initTrafficLightLogic().
void NBTrafficLightDefinition::addNode (NBNode * node) virtual inherited
Adds a node to the traffic light logic.
Parameters
[in] node A further node that shall be controlled by the tls
Definition at line 378 of file NBTrafficLightDefinition.cpp.
References NBNode::addTrafficLight(), and NBTrafficLightDefinition::myControlledNodes.
Referenced by NBLoadedSUMOTLDef::addConnection(), addToSignalGroup(), GNEJunction::addTrafficLight(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBNode::invalidateTLS(), and NBTrafficLightDefinition::NBTrafficLightDefinition().
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 53 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NBTrafficLightDefinition::compute(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::EdgesHandler::myStartElement(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_TLS::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_Polygon::processSet(), and TraCIServerAPI_Lane::processSet().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 59 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 67 of file Parameterised.cpp.
References Parameterised::myMap.
void NBLoadedTLDef::addSignalGroup (const std::string & id)
Adds a signal group.
Parameters
[in] id The id of the signal group
Definition at line 597 of file NBLoadedTLDef.cpp.
References mySignalGroups.
Referenced by NIVissimTL::NIVissimTLSignalGroup::addTo(), and NIVisumTL::build().
void NBLoadedTLDef::addSignalGroupPhaseBegin (const std::string & groupid, SUMOTime time, TLColor color)
Sets the information about the begin of a phase.
Parameters
[in] groupid The id of the signal group to add the phase to
[in] time The time the phase starts at
[in] color The color of the signal during this phase
Definition at line 604 of file NBLoadedTLDef.cpp.
References mySignalGroups.
Referenced by NIVissimTL::NIVissimTLSignalGroup::addTo(), and NIVisumTL::build().
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
bool NBLoadedTLDef::addToSignalGroup (const std::string & groupid, const NBConnection & connection)
Adds a connection to a signal group.
Parameters
[in] groupid The id of the signal group to add the connection to
[in] connection The connection to add
Definition at line 565 of file NBLoadedTLDef.cpp.
References NBTrafficLightDefinition::addNode(), NBNode::addTrafficLight(), NBConnection::getFrom(), NBEdge::getFromNode(), NBConnection::getTo(), NBEdge::getToNode(), and mySignalGroups.
Referenced by NIVissimTL::NIVissimTLSignal::addTo(), addToSignalGroup(), and NIVisumTL::build().
bool NBLoadedTLDef::addToSignalGroup (const std::string & groupid, const NBConnectionVector & connections)
Adds a list of connections to a signal group.
Parameters
[in] groupid The id of the signal group to add the connections to
[in] connections The connections to add
Definition at line 586 of file NBLoadedTLDef.cpp.
References addToSignalGroup().
bool NBTrafficLightDefinition::amInvalid () const protected virtual inherited
Reimplemented in NBLoadedSUMOTLDef.
Definition at line 139 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myControlledLinks.
Referenced by NBTrafficLightDefinition::compute(), and NBTrafficLightDefinition::initNeedsContRelation().
std::string NBLoadedTLDef::buildPhaseState (int time) const private
Builds the phase for a given time.
Parameters
[in] ec The edge control to use
[in] time The time to build the phase for
Returns
The phase of this tls for the given time
Definition at line 392 of file NBLoadedTLDef.cpp.
References NBConnection::check(), NBLoadedTLDef::SignalGroup::getConnection(), NBLoadedTLDef::SignalGroup::getLinkNo(), NBLoadedTLDef::SignalGroup::hasYellow(), NBLoadedTLDef::SignalGroup::mayDrive(), mustBrake(), myEdgeCont, and mySignalGroups.
Referenced by myCompute().
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 91 of file Parameterised.cpp.
References Parameterised::myMap.
void NBTrafficLightDefinition::collectAllLinks () protected inherited
helper method for use in NBOwnTLDef and NBLoadedSUMOTLDef
Definition at line 416 of file NBTrafficLightDefinition.cpp.
References NBEdge::Connection::fromLane, NBEdge::getConnectionsFromLane(), Named::getID(), NBEdge::getNumLanes(), NBEdge::getPermissions(), NBEdge::getToNode(), NBNode::getType(), isRailway(), NBEdge::mayBeTLSControlled(), NBTrafficLightDefinition::myControlledLinks, NBTrafficLightDefinition::myIncomingEdges, NODETYPE_RAIL_CROSSING, NBEdge::Connection::toEdge, NBEdge::Connection::toLane, and toString().
Referenced by NBLoadedSUMOTLDef::collectLinks(), and NBOwnTLDef::collectLinks().
void NBTrafficLightDefinition::collectEdges () protected virtual inherited
Build the list of participating edges.
Reimplemented in NBLoadedSUMOTLDef.
Definition at line 180 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::collectReachable(), NBTrafficLightDefinition::DummyID, NBNode::FORWARD, OptionsCont::getBool(), NBEdge::getFirstNonPedestrianLaneIndex(), Named::getID(), OptionsCont::getOptions(), NBTrafficLightDefinition::myControlledInnerEdges, NBTrafficLightDefinition::myControlledNodes, NBTrafficLightDefinition::myEdgesWithin, NBTrafficLightDefinition::myIncomingEdges, NBEdge::setIsInnerEdge(), and WRITE_WARNING.
Referenced by NBLoadedSUMOTLDef::collectEdges(), NBOwnTLDef::setParticipantsInformation(), and NBTrafficLightDefinition::setParticipantsInformation().
void NBLoadedTLDef::collectLinks () protected virtual
Collects the links participating in this traffic light
Exceptions
ProcessError If a link could not be found.
See also
NBTrafficLightDefinition::collectLinks
Implements NBTrafficLightDefinition.
Definition at line 504 of file NBLoadedTLDef.cpp.
References NBLoadedTLDef::SignalGroup::getConnection(), NBEdge::getConnectionsFromLane(), NBConnection::getFrom(), NBConnection::getFromLane(), Named::getID(), NBLoadedTLDef::SignalGroup::getLinkNo(), NBEdge::getNumLanes(), NBConnection::getTLIndex(), NBConnection::getTo(), NBConnection::getToLane(), NBConnection::InvalidTlIndex, NBTrafficLightDefinition::myControlledLinks, myEdgeCont, NBTrafficLightDefinition::myIncomingEdges, mySignalGroups, NBConnection::setTLIndex(), NBEdge::Connection::toEdge, NBEdge::Connection::toLane, and WRITE_WARNING.
void NBLoadedTLDef::collectNodes () protected
Collects the nodes participating in this traffic light.
See also
NBTrafficLightDefinition::collectNodes
Definition at line 486 of file NBLoadedTLDef.cpp.
References NBLoadedTLDef::SignalGroup::getConnection(), NBConnection::getFrom(), NBLoadedTLDef::SignalGroup::getLinkNo(), NBEdge::getToNode(), NBTrafficLightDefinition::myControlledNodes, and mySignalGroups.
NBTrafficLightLogic * NBTrafficLightDefinition::compute (OptionsCont & oc) inherited
Computes the traffic light logic.
Does some initialisation at first, then calls myCompute to finally build the tl-logic
Parameters
[in] oc The options container holding options needed during the building
Returns
The built logic (may be 0)
Definition at line 114 of file NBTrafficLightDefinition.cpp.
References Parameterised::addParameter(), NBTrafficLightDefinition::amInvalid(), NBTrafficLightDefinition::computeBrakingTime(), OptionsCont::getFloat(), Named::getID(), OptionsCont::getInt(), Parameterised::getMap(), OptionsCont::isSet(), NBTrafficLightDefinition::myCompute(), NBTrafficLightDefinition::myControlledNodes, and WRITE_WARNING.
Referenced by NBTrafficLightLogicCont::computeSingleLogic().
int NBTrafficLightDefinition::computeBrakingTime (SUMOReal minDecel) const protected inherited
Computes the time vehicles may need to brake.
This time depends on the maximum speed allowed on incoming junctions. It is computed as max_speed_allowed / minimum_vehicle_decleration
Definition at line 145 of file NBTrafficLightDefinition.cpp.
References NBContHelper::maxSpeed(), NBTrafficLightDefinition::myIncomingEdges, and SUMOReal.
Referenced by NBTrafficLightDefinition::compute().
NBLoadedTLDef::SignalGroup * NBLoadedTLDef::findGroup (NBEdge * from, NBEdge * to) const
Returns the signal group which is responsible for the given connection.
Parameters
[in] from The connection's start edge
[in] to The connection's end edge
Returns
The signal group which controls the given connection
Definition at line 554 of file NBLoadedTLDef.cpp.
References mySignalGroups.
bool NBTrafficLightDefinition::foes (const NBEdge *const from1, const NBEdge *const to1, const NBEdge *const from2, const NBEdge *const to2) const inherited
Returns the information whether the given flows cross.
Parameters
[in] from1 The starting edge of the first stream
[in] to1 The ending edge of the first stream
[in] from2 The starting edge of the second stream
[in] to2 The ending edge of the second stream
Returns
Whether both stream are foes (cross)
Definition at line 355 of file NBTrafficLightDefinition.cpp.
References NBNode::foes(), and NBTrafficLightDefinition::myControlledNodes.
Referenced by NBTrafficLightDefinition::getNodes(), and NBLoadedSUMOTLDef::initNeedsContRelation().
bool NBTrafficLightDefinition::forbids (const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, bool regardNonSignalisedLowerPriority, bool sameNodeOnly = false) const inherited
Returns the information whether "prohibited" flow must let "prohibitor" flow pass.
Parameters
[in] possProhibitedFrom The maybe prohibited connection's begin
[in] possProhibitedTo The maybe prohibited connection's end
[in] possProhibitorFrom The maybe prohibiting connection's begin
[in] possProhibitorTo The maybe prohibiting connection's end
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
[in] sameNodeOnly Whether the check shall only be performed if both edges are incoming to the same node
Returns
Whether the second flow prohibits the first one
See also
forbids
Definition at line 267 of file NBTrafficLightDefinition.cpp.
References NBNode::foes(), NBNode::forbids(), NBEdge::getConnectedEdges(), NBNode::getDirection(), LINKDIR_STRAIGHT, and NBTrafficLightDefinition::myControlledNodes.
Referenced by NBOwnTLDef::computeLogicAndConts(), NBOwnTLDef::computeUnblockedWeightedStreamNumber(), NBOwnTLDef::correctConflicting(), NBTrafficLightDefinition::getNodes(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBTrafficLightDefinition::mustBrake(), and myCompute().
std::vector< std::string > NBTrafficLightDefinition::getControlledInnerEdges () const inherited
Retrieve the ids of edges explicitly controlled by the tls.
Definition at line 404 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myControlledInnerEdges.
Referenced by NBTrafficLightDefinition::getNodes(), and NIXMLTrafficLightsHandler::initTrafficLightLogic().
const NBConnectionVector& NBTrafficLightDefinition::getControlledLinks () const inline inherited
returns the controlled links (depends on previous call to collectLinks)
Definition at line 292 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::myControlledLinks.
Referenced by GNETLSEditorFrame::buildIinternalLanes(), GNETLSEditorFrame::controlsEdge(), GNETLSEditorFrame::handleMultiChange(), and NBLoadedSUMOTLDef::NBLoadedSUMOTLDef().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciBusOrContainerStop(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNEConnectorFrame::buildIinternalLanes(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), NLDetectorBuilder::convUncontE2PosLength(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSVehicle::getBackPosition(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), GNEEdge::getDest(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), MSE2Collector::getEstimateQueueLength(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), GNEEdge::getSource(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_BTsender::notifyMove(), MSE2Collector::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_SL2015::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_LC2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_ArealDetector::processGet(), TraCIServerAPI_Lane::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), MSBaseVehicle::reroute(), MSLane::resetPartialOccupation(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), MSLane::saveState(), MSDevice_Battery::setAirDragCoefficient(), NBNodeCont::setAsTLControlled(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), MSDevice_Battery::setConstantPowerIntake(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), MSDevice_Battery::setFrontSurfaceArea(), MSDevice_Battery::setInternalMomentOfInertia(), GNEJunction::setLogicValid(), MSDevice_Battery::setMass(), MSDevice_Battery::setMaximumBatteryCapacity(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSDevice_Battery::setPropulsionEfficiency(), MSDevice_Battery::setRadialDragCoefficient(), MSDevice_Battery::setRecuperationEfficiency(), MSLink::setRequestInformation(), MSDevice_Battery::setRollDragCoefficient(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), operator<<(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
const EdgeVector & NBTrafficLightDefinition::getIncomingEdges () const inherited
Returns the list of incoming edges (must be build first)
Returns
The edges which are incoming into the tls
Definition at line 410 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myIncomingEdges.
Referenced by NBOwnTLDef::computeLogicAndConts(), and NBTrafficLightDefinition::shiftTLConnectionLaneIndex().
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 107 of file Parameterised.h.
References Parameterised::myMap.
Referenced by NBTrafficLightDefinition::compute(), MSDevice_Vehroutes::generateOutput(), GUIPerson::getParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), TraCIServerAPI_TLS::processGet(), ROVehicle::saveAsXML(), ROPerson::saveAsXML(), SUMOVTypeParameter::write(), PointOfInterest::writeXML(), and SUMO::Polygon::writeXML().
const std::vector<NBNode*>& NBTrafficLightDefinition::getNodes () const inline inherited
Returns the list of controlled nodes.
Returns
Controlled nodes
Definition at line 171 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::addControlledInnerEdges(), NBTrafficLightDefinition::foes(), NBTrafficLightDefinition::forbids(), NBTrafficLightDefinition::getControlledInnerEdges(), NBTrafficLightDefinition::mustBrake(), NBTrafficLightDefinition::myControlledNodes, NBTrafficLightDefinition::remapRemoved(), NBTrafficLightDefinition::replaceRemoved(), NBTrafficLightDefinition::setParticipantsInformation(), and NBTrafficLightDefinition::setTLControllingInformation().
Referenced by NIXMLTrafficLightsHandler::initTrafficLightLogic(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), NBLoadedSUMOTLDef::NBLoadedSUMOTLDef(), and GNETLSEditorFrame::onCmdOK().
SUMOTime NBTrafficLightDefinition::getOffset () inline inherited
Returns the offset.
Returns
Offset
Definition at line 316 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::myOffset.
Referenced by GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), and NBLoadedSUMOTLDef::NBLoadedSUMOTLDef().
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 81 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), MSSOTLPolicyDesirability::readParameter(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), and TraCIServerAPI_Vehicle::vtdMap().
const std::string& NBTrafficLightDefinition::getProgramID () const inline inherited
Returns the ProgramID.
Returns
The ID of the program (subID)
Definition at line 300 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::mySubID.
Referenced by NIImporter_SUMO::addPhase(), NBOwnTLDef::computeLogicAndConts(), NBTrafficLightLogicCont::computeSingleLogic(), NBTrafficLightLogicCont::extract(), NBTrafficLightLogicCont::insert(), GNEJunction::invalidateTLS(), myCompute(), NIImporter_SUMO::myEndElement(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), and NBLoadedSUMOTLDef::removeConnection().
TrafficLightType NBTrafficLightDefinition::getType () const inline inherited
get the algorithm type (static etc..)
Definition at line 322 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::initNeedsContRelation(), NBTrafficLightDefinition::myType, NBTrafficLightDefinition::needsCont(), and NBTrafficLightDefinition::rightOnRedConflict().
Referenced by NBOwnTLDef::correctConflicting(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), NBLoadedSUMOTLDef::NBLoadedSUMOTLDef(), and NIXMLNodesHandler::processTrafficLightDefinitions().
void NBLoadedTLDef::initNeedsContRelation () const virtual
Reimplemented from NBTrafficLightDefinition.
Definition at line 653 of file NBLoadedTLDef.cpp.
References NBTrafficLightDefinition::myNeedsContRelationReady.
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 75 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), and MSDevice::equippedByDefaultAssignmentOptions().
bool NBTrafficLightDefinition::mustBrake (const NBEdge *const from, const NBEdge *const to) const inherited
Returns the information whether the described flow must let any other flow pass.
If the from/to connection passes only one junction (from is incoming into same node as to outgoes from) the node is asked whether the flow must brake- Otherwise true is returned (recheck!) "from" must be an incoming edge into one of the participating nodes!
Parameters
[in] from The connection's start edge
[in] to The connection's end edge
Returns
Whether the described connection must brake (has higher priorised foes)
Definition at line 230 of file NBTrafficLightDefinition.cpp.
References NBNode::mustBrake(), and NBTrafficLightDefinition::myControlledNodes.
Referenced by NBTrafficLightDefinition::getNodes(), and mustBrake().
bool NBTrafficLightDefinition::mustBrake (const NBConnection & possProhibited, const NBConnection & possProhibitor, bool regardNonSignalisedLowerPriority) const inherited
Returns the information whether the described flow must let the other flow pass.
Parameters
[in] possProhibited The maybe prohibited connection
[in] possProhibitor The maybe prohibiting connection
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
Returns
Whether the second flow prohibits the first one
See also
forbids
Definition at line 257 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::forbids(), NBConnection::getFrom(), and NBConnection::getTo().
bool NBTrafficLightDefinition::mustBrake (const NBEdge *const possProhibitedFrom, const NBEdge *const possProhibitedTo, const NBEdge *const possProhibitorFrom, const NBEdge *const possProhibitorTo, bool regardNonSignalisedLowerPriority) const inherited
Returns the information whether the described flow must let any other flow pass.
Parameters
[in] possProhibitedFrom The maybe prohibited connection's begin
[in] possProhibitedTo The maybe prohibited connection's end
[in] possProhibitorFrom The maybe prohibiting connection's begin
[in] possProhibitorTo The maybe prohibiting connection's end
[in] regardNonSignalisedLowerPriority Whether the right of way rules without traffic lights shall be regarded
Returns
Whether the second flow prohibits the first one
See also
forbids
Definition at line 245 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::forbids().
bool NBLoadedTLDef::mustBrake (const NBConnection & possProhibited, const std::string & state, int strmpos) const protected
Returns the information whether a connection must brake, given a phase.
Parameters
[in] possProhibited The connection to investigate
[in] state The state
[in] strmpos The index of this connection within the masks
Returns
Whether the given connection must brake
Definition at line 446 of file NBLoadedTLDef.cpp.
References NBConnection::check(), NBLoadedTLDef::SignalGroup::getConnection(), NBConnection::getFrom(), NBLoadedTLDef::SignalGroup::getLinkNo(), NBTrafficLightDefinition::mustBrake(), myEdgeCont, and mySignalGroups.
Referenced by buildPhaseState().
NBTrafficLightLogic * NBLoadedTLDef::myCompute (int brakingTimeSeconds) protected virtual
Computes the traffic light logic finally in dependence to the type.
Parameters
[in] brakingTime Duration a vehicle needs for braking in front of the tls in seconds
Returns
The computed logic
See also
NBTrafficLightDefinition::myCompute
Implements NBTrafficLightDefinition.
Definition at line 295 of file NBLoadedTLDef.cpp.
References NBTrafficLightLogic::addStep(), buildPhaseState(), MsgHandler::clear(), NBTrafficLightLogic::closeBuilding(), NBTrafficLightDefinition::forbids(), OptionsCont::getBool(), NBConnection::getFrom(), NBConnection::getFromLane(), Named::getID(), OptionsCont::getOptions(), NBTrafficLightLogic::getPhases(), NBTrafficLightDefinition::getProgramID(), NBLoadedTLDef::SignalGroup::getTimes(), NBConnection::getTLIndex(), NBConnection::getTo(), MsgHandler::getWarningInstance(), NBConnection::InvalidTlIndex, NBTrafficLightDefinition::myControlledLinks, myCycleDuration, NBTrafficLightDefinition::myNeedsContRelation, NBTrafficLightDefinition::myNeedsContRelationReady, NBTrafficLightDefinition::myOffset, mySignalGroups, NBTrafficLightDefinition::myType, NBLoadedTLDef::SignalGroup::patchTYellow(), NBNode::rightTurnConflict(), NBLoadedTLDef::SignalGroup::sortPhases(), TIME2STEPS, and WRITE_WARNING.
bool NBTrafficLightDefinition::needsCont (const NBEdge * fromE, const NBEdge * toE, const NBEdge * otherFromE, const NBEdge * otherToE) const inherited
Definition at line 444 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::initNeedsContRelation(), NBTrafficLightDefinition::myNeedsContRelation, and NBTrafficLightDefinition::myNeedsContRelationReady.
Referenced by NBTrafficLightDefinition::getType().
void NBLoadedTLDef::remapRemoved (NBEdge * removed, const EdgeVector & incoming, const EdgeVector & outgoing) virtual
Replaces occurences of the removed edge in incoming/outgoing edges of all definitions.
Parameters
[in] removed The removed edge
[in] incoming The edges to use instead if an incoming edge was removed
[in] outgoing The edges to use instead if an outgoing edge was removed
See also
NBTrafficLightDefinition::remapRemoved
Implements NBTrafficLightDefinition.
Definition at line 625 of file NBLoadedTLDef.cpp.
References NBLoadedTLDef::SignalGroup::containsIncoming(), NBLoadedTLDef::SignalGroup::containsOutgoing(), mySignalGroups, NBLoadedTLDef::SignalGroup::remapIncoming(), and NBLoadedTLDef::SignalGroup::remapOutgoing().
void NBTrafficLightDefinition::removeNode (NBNode * node) virtual inherited
Removes the given node from the list of controlled nodes.
Parameters
[in] node The node that shall not be controlled by the tls any more
Definition at line 388 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::myControlledNodes.
Referenced by NBNode::removeTrafficLight().
void NBLoadedTLDef::replaceRemoved (NBEdge * removed, int removedLane, NBEdge * by, int byLane) protected virtual
Replaces a removed edge/lane.
Parameters
[in] removed The edge to replace
[in] removedLane The lane of this edge to replace
[in] by The edge to insert instead
[in] byLane This edge's lane to insert instead
See also
NBTrafficLightDefinition::replaceRemoved
Implements NBTrafficLightDefinition.
Definition at line 641 of file NBLoadedTLDef.cpp.
References NBLoadedTLDef::SignalGroup::containsIncoming(), NBLoadedTLDef::SignalGroup::containsOutgoing(), mySignalGroups, and NBLoadedTLDef::SignalGroup::remap().
bool NBTrafficLightDefinition::rightOnRedConflict (int index, int foeIndex) const virtual inherited
whether the given index must yield to the foeIndex while turing right on a red light
Reimplemented in NBLoadedSUMOTLDef.
Definition at line 469 of file NBTrafficLightDefinition.cpp.
References NBOwnTLDef::computeLogicAndConts(), NBTrafficLightDefinition::DummyID, NBTrafficLightDefinition::myControlledNodes, NBTrafficLightDefinition::myRightOnRedConflicts, NBTrafficLightDefinition::myRightOnRedConflictsReady, NBOwnTLDef::setParticipantsInformation(), and TLTYPE_STATIC.
Referenced by NBTrafficLightDefinition::getType().
void NBLoadedTLDef::setCycleDuration (int cycleDur)
Sets the duration of a cycle.
Parameters
[in] cycleDur The duration of the cycle
Definition at line 619 of file NBLoadedTLDef.cpp.
References myCycleDuration.
Referenced by NIVisumTL::build(), and NIVissimTL::dict_SetSignals().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
void NBTrafficLightDefinition::setParticipantsInformation () virtual inherited
Builds the list of participating nodes/edges/links.
Reimplemented in NBOwnTLDef.
Definition at line 152 of file NBTrafficLightDefinition.cpp.
References NBTrafficLightDefinition::collectEdges(), and NBTrafficLightDefinition::collectLinks().
Referenced by GNENet::computeJunction(), and NBTrafficLightDefinition::getNodes().
void NBTrafficLightDefinition::setProgramID (const std::string & programID) inline inherited
Sets the programID.
Parameters
[in] programID The new ID of the program (subID)
Definition at line 308 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::mySubID.
Referenced by NBTrafficLightLogicCont::insert(), and GNEJunction::invalidateTLS().
void NBLoadedTLDef::setSignalYellowTimes (const std::string & groupid, SUMOTime tRedYellow, SUMOTime tYellow)
Sets the times the light is yellow or red/yellow.
Parameters
[in] groupid The id of the signal group to add the phase to
[in] tRedYellow The duration of redyellow
[in] tYellow The duration of yellow
Definition at line 611 of file NBLoadedTLDef.cpp.
References mySignalGroups.
Referenced by NIVissimTL::NIVissimTLSignalGroup::addTo(), and NIVisumTL::build().
void NBLoadedTLDef::setTLControllingInformation () const virtual
Informs edges about being controlled by a tls.
Parameters
[in] ec The container of edges
See also
NBTrafficLightDefinition::setTLControllingInformation
Implements NBTrafficLightDefinition.
Definition at line 380 of file NBLoadedTLDef.cpp.
References NBConnection::getFrom(), Named::getID(), NBConnection::getTLIndex(), NBConnection::InvalidTlIndex, NBTrafficLightDefinition::myControlledLinks, and NBEdge::setControllingTLInformation().
virtual void NBTrafficLightDefinition::shiftTLConnectionLaneIndex (NBEdge * edge, int offset) inline virtual inherited
patches (loaded) signal plans by modifying lane indices
Reimplemented in NBLoadedSUMOTLDef.
Definition at line 280 of file NBTrafficLightDefinition.h.
References NBTrafficLightDefinition::getIncomingEdges(), and UNUSED_PARAMETER.
Field Documentation
const std::string NBTrafficLightDefinition::DefaultProgramID = "0" static inherited
Definition at line 78 of file NBTrafficLightDefinition.h.
Referenced by NIXMLTrafficLightsHandler::initTrafficLightLogic().
const std::string NBTrafficLightDefinition::DummyID = "dummy" static protected inherited
id for temporary definitions
Definition at line 341 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::collectEdges(), NBOwnTLDef::computeLogicAndConts(), NBOwnTLDef::initNeedsContRelation(), NBTrafficLightDefinition::initNeedsContRelation(), and NBTrafficLightDefinition::rightOnRedConflict().
std::set<std::string> NBTrafficLightDefinition::myControlledInnerEdges protected inherited
Set of inner edges that shall be controlled, though.
Definition at line 389 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::addControlledInnerEdges(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), and NBTrafficLightDefinition::getControlledInnerEdges().
NBConnectionVector NBTrafficLightDefinition::myControlledLinks protected inherited
The list of controlled links.
Definition at line 386 of file NBTrafficLightDefinition.h.
Referenced by NBLoadedSUMOTLDef::addConnection(), NBLoadedSUMOTLDef::amInvalid(), NBTrafficLightDefinition::amInvalid(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedSUMOTLDef::collectLinks(), collectLinks(), NBTrafficLightDefinition::getControlledLinks(), NBLoadedSUMOTLDef::initNeedsContRelation(), myCompute(), NBLoadedSUMOTLDef::NBLoadedSUMOTLDef(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), NBLoadedSUMOTLDef::removeConnection(), NBLoadedSUMOTLDef::replaceRemoved(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), setTLControllingInformation(), and NBLoadedSUMOTLDef::shiftTLConnectionLaneIndex().
std::vector<NBNode*> NBTrafficLightDefinition::myControlledNodes protected inherited
The container with participating nodes.
Definition at line 377 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::addNode(), NBLoadedSUMOTLDef::amInvalid(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectLinks(), collectNodes(), NBTrafficLightDefinition::compute(), NBOwnTLDef::computeLogicAndConts(), NBTrafficLightDefinition::foes(), NBTrafficLightDefinition::forbids(), NBTrafficLightDefinition::getNodes(), NBOwnTLDef::initNeedsContRelation(), NBTrafficLightDefinition::initNeedsContRelation(), NBTrafficLightDefinition::mustBrake(), NBLoadedSUMOTLDef::NBLoadedSUMOTLDef(), NBTrafficLightDefinition::NBTrafficLightDefinition(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), NBTrafficLightDefinition::removeNode(), and NBTrafficLightDefinition::rightOnRedConflict().
int NBLoadedTLDef::myCycleDuration private
The duration of a single cycle.
Definition at line 384 of file NBLoadedTLDef.h.
Referenced by myCompute(), and setCycleDuration().
const NBEdgeCont* NBLoadedTLDef::myEdgeCont private
Definition at line 376 of file NBLoadedTLDef.h.
Referenced by buildPhaseState(), collectLinks(), and mustBrake().
EdgeVector NBTrafficLightDefinition::myEdgesWithin protected inherited
The list of edges within the area controlled by the tls.
Definition at line 383 of file NBTrafficLightDefinition.h.
Referenced by NBLoadedSUMOTLDef::collectEdges(), and NBTrafficLightDefinition::collectEdges().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
EdgeVector NBTrafficLightDefinition::myIncomingEdges protected inherited
The list of incoming edges.
Definition at line 380 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), collectLinks(), NBTrafficLightDefinition::computeBrakingTime(), and NBTrafficLightDefinition::getIncomingEdges().
NeedsContRelation NBTrafficLightDefinition::myNeedsContRelation mutable protected inherited
Definition at line 432 of file NBTrafficLightDefinition.h.
Referenced by NBOwnTLDef::computeLogicAndConts(), NBOwnTLDef::correctConflicting(), NBOwnTLDef::initNeedsContRelation(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBTrafficLightDefinition::initNeedsContRelation(), myCompute(), and NBTrafficLightDefinition::needsCont().
bool NBTrafficLightDefinition::myNeedsContRelationReady mutable protected inherited
Definition at line 433 of file NBTrafficLightDefinition.h.
Referenced by NBOwnTLDef::computeLogicAndConts(), NBOwnTLDef::initNeedsContRelation(), NBLoadedSUMOTLDef::initNeedsContRelation(), initNeedsContRelation(), NBTrafficLightDefinition::initNeedsContRelation(), myCompute(), and NBTrafficLightDefinition::needsCont().
SUMOTime NBTrafficLightDefinition::myOffset protected inherited
The offset in the program.
Definition at line 395 of file NBTrafficLightDefinition.h.
Referenced by NBOwnTLDef::computeLogicAndConts(), NBTrafficLightDefinition::getOffset(), myCompute(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), NBLoadedSUMOTLDef::removeConnection(), and NBLoadedSUMOTLDef::setOffset().
RightOnRedConflicts NBTrafficLightDefinition::myRightOnRedConflicts mutable protected inherited
Definition at line 436 of file NBTrafficLightDefinition.h.
Referenced by NBOwnTLDef::computeLogicAndConts(), NBOwnTLDef::correctConflicting(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBLoadedSUMOTLDef::rightOnRedConflict(), and NBTrafficLightDefinition::rightOnRedConflict().
bool NBTrafficLightDefinition::myRightOnRedConflictsReady mutable protected inherited
Definition at line 437 of file NBTrafficLightDefinition.h.
Referenced by NBOwnTLDef::computeLogicAndConts(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBLoadedSUMOTLDef::rightOnRedConflict(), and NBTrafficLightDefinition::rightOnRedConflict().
SignalGroupCont NBLoadedTLDef::mySignalGroups private
Controlled signal groups.
Definition at line 381 of file NBLoadedTLDef.h.
Referenced by addSignalGroup(), addSignalGroupPhaseBegin(), addToSignalGroup(), buildPhaseState(), collectLinks(), collectNodes(), findGroup(), mustBrake(), myCompute(), remapRemoved(), replaceRemoved(), setSignalYellowTimes(), and ~NBLoadedTLDef().
std::string NBTrafficLightDefinition::mySubID protected inherited
The tls program's subid.
Definition at line 392 of file NBTrafficLightDefinition.h.
Referenced by NBTrafficLightDefinition::getProgramID(), and NBTrafficLightDefinition::setProgramID().
TrafficLightType NBTrafficLightDefinition::myType protected inherited
The algorithm type for the traffic light.
Definition at line 398 of file NBTrafficLightDefinition.h.
Referenced by NBOwnTLDef::computeLogicAndConts(), NBTrafficLightDefinition::getType(), myCompute(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), NBLoadedSUMOTLDef::removeConnection(), and NBLoadedSUMOTLDef::setType().
The documentation for this class was generated from the following files:
NBLoadedTLDef.h
NBLoadedTLDef.cpp