SUMO - Simulation of Urban MObility: polyfonts.h File Reference
polyfonts.h File Reference
#include <config.h>
#include "polyfonttypes.h"
Functions
SUMOReal pfdkGetStringWidth (const char *c)
int pfDrawChar (wchar_t c)
int pfDrawString (const char *c)
int pfDrawStringW (wchar_t *c)
wchar_t pfGetChar (int glyph)
SUMOReal pfGetCharAdvance (wchar_t c)
SUMOReal pfGetCharAscent (wchar_t c)
int pfGetCharBBox (wchar_t c, SUMOReal *minx, SUMOReal *miny, SUMOReal *maxx, SUMOReal *maxy)
SUMOReal pfGetCharDescent (wchar_t c)
SUMOReal pfGetCharHeight (wchar_t c)
SUMOReal pfGetCharWidth (wchar_t c)
pffont * pfGetCurrentFont ()
SUMOReal pfGetFontAscent ()
int pfGetFontBBox (SUMOReal *minx, SUMOReal *miny, SUMOReal *maxx, SUMOReal *maxy)
SUMOReal pfGetFontDescent ()
SUMOReal pfGetFontHeight ()
char * pfGetFontName ()
int pfGetFontNumGlyphs ()
SUMOReal pfGetFontWidth ()
void pfGetPosition (SUMOReal *x, SUMOReal *y)
void pfSetAngleD (SUMOReal a)
void pfSetAngleR (SUMOReal a)
void pfSetCenter (int onOff)
int pfSetFont (pffont *f)
void pfSetPosition (SUMOReal x, SUMOReal y)
void pfSetScale (SUMOReal s)
int pfSetScaleBox (char *c, SUMOReal w, SUMOReal h)
int pfSetScaleBoxW (wchar_t *c, SUMOReal w, SUMOReal h)
void pfSetScaleXY (SUMOReal sx, SUMOReal sy)
void pfSetSkew (SUMOReal s)
void pfSetWeight (int w)
void pfUnloadFont (pffont *f)
Function Documentation
SUMOReal pfdkGetStringWidth (const char * c)
Definition at line 1113 of file polyfonts.c.
References pfGetCharAdvance(), and SUMOReal.
Referenced by GNEVariableSpeedSignal::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GNECalibrator::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GNERerouter::drawGL(), GLHelper::drawText(), GLHelper::drawTextBox(), GUIParameterTracker::GUIParameterTrackerPanel::drawValue(), and GUITLLogicPhasesTrackerWindow::drawValues().
int pfDrawChar (wchar_t c)
Definition at line 1058 of file polyfonts.c.
References drawWideChar().
int pfDrawString (const char * c)
Definition at line 1074 of file polyfonts.c.
References drawWideChar().
Referenced by GUISUMOAbstractView::displayLegend(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEVariableSpeedSignal::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GNEChargingStation::drawGL(), GUIChargingStation::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GNERerouter::drawGL(), GLHelper::drawText(), GLHelper::drawTextBox(), GUIParameterTracker::GUIParameterTrackerPanel::drawValue(), and GUITLLogicPhasesTrackerWindow::drawValues().
int pfDrawStringW (wchar_t * c)
Definition at line 1093 of file polyfonts.c.
References drawWideChar(), and SUMOReal.
wchar_t pfGetChar (int glyph)
Definition at line 801 of file polyfonts.c.
References pfglyph::glyph, pffont::glyphs, and pffont::numglyphs.
SUMOReal pfGetCharAdvance (wchar_t c)
Definition at line 869 of file polyfonts.c.
References pfglyph::advance, pfGetGlyph(), and pfScaleX.
Referenced by pfdkGetStringWidth().
SUMOReal pfGetCharAscent (wchar_t c)
Definition at line 946 of file polyfonts.c.
References pfGetCharBBox(), and SUMOReal.
int pfGetCharBBox (wchar_t c, SUMOReal * minx, SUMOReal * miny, SUMOReal * maxx, SUMOReal * maxy)
Definition at line 883 of file polyfonts.c.
References getCharBBox(), pfScaleX, pfScaleY, pfSkew(), and pfTextSkew.
Referenced by pfGetCharAscent(), pfGetCharDescent(), pfGetCharHeight(), and pfGetCharWidth().
SUMOReal pfGetCharDescent (wchar_t c)
Definition at line 960 of file polyfonts.c.
References pfGetCharBBox(), and SUMOReal.
SUMOReal pfGetCharHeight (wchar_t c)
Definition at line 918 of file polyfonts.c.
References pfGetCharBBox(), and SUMOReal.
SUMOReal pfGetCharWidth (wchar_t c)
Definition at line 932 of file polyfonts.c.
References pfGetCharBBox(), and SUMOReal.
pffont* pfGetCurrentFont ()
Definition at line 692 of file polyfonts.c.
References pfCurrentFont.
SUMOReal pfGetFontAscent ()
Definition at line 761 of file polyfonts.c.
References pfGetFontBBox(), and SUMOReal.
int pfGetFontBBox (SUMOReal * minx, SUMOReal * miny, SUMOReal * maxx, SUMOReal * maxy)
Definition at line 699 of file polyfonts.c.
References pffont::maxx, pffont::maxy, pffont::minx, pffont::miny, pfScaleX, pfScaleY, pfSkew(), and pfTextSkew.
Referenced by pfGetFontAscent(), pfGetFontDescent(), pfGetFontHeight(), and pfGetFontWidth().
SUMOReal pfGetFontDescent ()
Definition at line 775 of file polyfonts.c.
References pfGetFontBBox(), and SUMOReal.
SUMOReal pfGetFontHeight ()
Definition at line 733 of file polyfonts.c.
References pfGetFontBBox(), and SUMOReal.
char* pfGetFontName ()
Definition at line 678 of file polyfonts.c.
References pffont::name.
int pfGetFontNumGlyphs ()
Definition at line 789 of file polyfonts.c.
References pffont::numglyphs.
SUMOReal pfGetFontWidth ()
Definition at line 747 of file polyfonts.c.
References pfGetFontBBox(), and SUMOReal.
void pfGetPosition (SUMOReal * x, SUMOReal * y)
Definition at line 488 of file polyfonts.c.
References pfTextX, and pfTextY.
void pfSetAngleD (SUMOReal a)
Definition at line 518 of file polyfonts.c.
References DtoR, and pfSetAngleR().
void pfSetAngleR (SUMOReal a)
Definition at line 510 of file polyfonts.c.
References pfTextCos, and pfTextSin.
Referenced by pfSetAngleD().
void pfSetCenter (int onOff)
Definition at line 525 of file polyfonts.c.
References pfCenter.
int pfSetFont (pffont * f)
Definition at line 152 of file polyfonts.c.
void pfSetPosition (SUMOReal x, SUMOReal y)
Definition at line 480 of file polyfonts.c.
References pfTextX, and pfTextY.
Referenced by GUISUMOAbstractView::displayLegend(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEVariableSpeedSignal::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GNEChargingStation::drawGL(), GUIChargingStation::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GNERerouter::drawGL(), GLHelper::drawText(), GLHelper::drawTextBox(), GUIParameterTracker::GUIParameterTrackerPanel::drawValue(), and GUITLLogicPhasesTrackerWindow::drawValues().
void pfSetScale (SUMOReal s)
Definition at line 465 of file polyfonts.c.
References pfScaleX, and pfScaleY.
Referenced by GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEVariableSpeedSignal::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GNEChargingStation::drawGL(), GUIChargingStation::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GNERerouter::drawGL(), GLHelper::drawText(), GLHelper::drawTextBox(), and GUIParameterTracker::GUIParameterTrackerPanel::drawValues().
int pfSetScaleBox (char * c, SUMOReal w, SUMOReal h)
Definition at line 638 of file polyfonts.c.
References getStringBox(), pfSetScaleXY(), and SUMOReal.
int pfSetScaleBoxW (wchar_t * c, SUMOReal w, SUMOReal h)
Definition at line 658 of file polyfonts.c.
References getStringBoxW(), pfSetScaleXY(), and SUMOReal.
void pfSetScaleXY (SUMOReal sx, SUMOReal sy)
Definition at line 472 of file polyfonts.c.
References pfScaleX, and pfScaleY.
Referenced by GUISUMOAbstractView::displayLegend(), GUIParameterTracker::GUIParameterTrackerPanel::drawValues(), GUITLLogicPhasesTrackerWindow::drawValues(), pfSetScaleBox(), and pfSetScaleBoxW().
void pfSetSkew (SUMOReal s)
Definition at line 496 of file polyfonts.c.
References max, min, and pfTextSkew.
void pfSetWeight (int w)
Definition at line 503 of file polyfonts.c.
References max, min, numWeights, and pfTextWeight.
void pfUnloadFont (pffont * f)
Definition at line 256 of file polyfonts.c.
References pffont::glyphs, pffont::loaded, lookupGlOp(), pffont::maxx, pffont::maxy, pffont::minx, pffont::miny, pffont::name, pffont::numglyphs, pfglyph::segments, and SUMOReal.