SUMO - Simulation of Urban MObility: MSLeaderInfo Class Reference
MSLeaderInfo Class Reference
#include <MSLeaderInfo.h>
Public Member Functions
virtual int addLeader (const MSVehicle *veh, bool beyond, SUMOReal latOffset=0)
virtual void clear ()
discard all information
void getSubLanes (const MSVehicle *veh, SUMOReal latOffset, int &rightmost, int &leftmost) const
bool hasStoppedVehicle () const
whether a stopped vehicle is leader
bool hasVehicles () const
MSLeaderInfo (const MSLane *lane, const MSVehicle *ego=0, SUMOReal latOffset=0)
Constructor.
int numFreeSublanes () const
int numSublanes () const
const MSVehicle * operator[] (int sublane) const
return the vehicle for the given sublane
virtual std::string toString () const
print a debugging representation
virtual ~MSLeaderInfo ()
Destructor.
Protected Attributes
int egoLeftMost
int egoRightMost
borders of the ego vehicle for filtering of free sublanes
int myFreeSublanes
the number of free sublanes
bool myHasVehicles
std::vector< const MSVehicle * > myVehicles
SUMOReal myWidth
the width of the lane to which this instance applies
Detailed Description
Definition at line 57 of file MSLeaderInfo.h.
Constructor & Destructor Documentation
MSLeaderInfo::MSLeaderInfo (const MSLane * lane, const MSVehicle * ego = 0, SUMOReal latOffset = 0)
Constructor.
Definition at line 53 of file MSLeaderInfo.cpp.
References egoLeftMost, egoRightMost, getSubLanes(), myFreeSublanes, and myVehicles.
MSLeaderInfo::~MSLeaderInfo () virtual
Destructor.
Definition at line 69 of file MSLeaderInfo.cpp.
Member Function Documentation
int MSLeaderInfo::addLeader (const MSVehicle * veh, bool beyond, SUMOReal latOffset = 0) virtual
Reimplemented in MSCriticalFollowerDistanceInfo, and MSLeaderDistanceInfo.
Definition at line 73 of file MSLeaderInfo.cpp.
References egoLeftMost, egoRightMost, getSubLanes(), myFreeSublanes, myHasVehicles, and myVehicles.
Referenced by MSLane::getFirstVehicleInformation(), MSLane::getLastVehicleInformation(), and MSLane::planMovements().
void MSLeaderInfo::clear () virtual
discard all information
Reimplemented in MSCriticalFollowerDistanceInfo, and MSLeaderDistanceInfo.
Definition at line 104 of file MSLeaderInfo.cpp.
References egoLeftMost, egoRightMost, myFreeSublanes, and myVehicles.
Referenced by MSLeaderDistanceInfo::addLeader(), MSCriticalFollowerDistanceInfo::addLeader(), and MSLeaderDistanceInfo::clear().
void MSLeaderInfo::getSubLanes (const MSVehicle * veh, SUMOReal latOffset, int & rightmost, int & leftmost) const
Definition at line 115 of file MSLeaderInfo.cpp.
References MSVehicle::getLateralPositionOnLane(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSGlobals::gLateralResolution, MAX2(), MIN2(), myVehicles, myWidth, NUMERICAL_EPS, and SUMOReal.
Referenced by MSVehicle::adaptToLeaders(), MSCriticalFollowerDistanceInfo::addFollower(), addLeader(), MSLeaderDistanceInfo::addLeader(), and MSLeaderInfo().
bool MSLeaderInfo::hasStoppedVehicle () const
whether a stopped vehicle is leader
Definition at line 166 of file MSLeaderInfo.cpp.
References myHasVehicles, and myVehicles.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSLCM_SL2015::checkStrategicChange(), and hasVehicles().
bool MSLeaderInfo::hasVehicles () const inline
Definition at line 94 of file MSLeaderInfo.h.
References hasStoppedVehicle(), myHasVehicles, and toString().
Referenced by MSLCM_SL2015::checkStrategicChange(), and MSLCM_SL2015::updateGaps().
int MSLeaderInfo::numFreeSublanes () const inline
Definition at line 90 of file MSLeaderInfo.h.
References myFreeSublanes.
Referenced by MSLane::getFollowersOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), and MSLane::isInsertionSuccess().
int MSLeaderInfo::numSublanes () const inline
Definition at line 86 of file MSLeaderInfo.h.
References myVehicles.
Referenced by MSLCM_SL2015::checkBlockingVehicles(), MSLCM_SL2015::computeSublaneShift(), MSLane::detectCollisions(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLCM_SL2015::getLongest(), MSLCM_SL2015::getSlowest(), MSEdge::initialize(), MSLane::isInsertionSuccess(), MSLane::safeInsertionSpeed(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), and MSLCM_SL2015::updateGaps().
const MSVehicle * MSLeaderInfo::operator[] (int sublane) const
return the vehicle for the given sublane
Definition at line 142 of file MSLeaderInfo.cpp.
References myVehicles.
Referenced by MSLeaderDistanceInfo::addLeader().
std::string MSLeaderInfo::toString () const virtual
print a debugging representation
Reimplemented in MSCriticalFollowerDistanceInfo, and MSLeaderDistanceInfo.
Definition at line 150 of file MSLeaderInfo.cpp.
References Named::getIDSecure(), myFreeSublanes, and myVehicles.
Referenced by MSVehicle::adaptToLeaders(), MSLeaderDistanceInfo::addLeader(), MSCriticalFollowerDistanceInfo::addLeader(), MSLane::getFollowersOnConsecutive(), MSLane::getLastVehicleInformation(), MSLane::getLeadersOnConsecutive(), hasVehicles(), MSLane::isInsertionSuccess(), and MSLane::planMovements().
Field Documentation
int MSLeaderInfo::egoLeftMost protected
Definition at line 119 of file MSLeaderInfo.h.
Referenced by MSCriticalFollowerDistanceInfo::addFollower(), addLeader(), MSLeaderDistanceInfo::addLeader(), clear(), and MSLeaderInfo().
int MSLeaderInfo::egoRightMost protected
borders of the ego vehicle for filtering of free sublanes
Definition at line 118 of file MSLeaderInfo.h.
Referenced by MSCriticalFollowerDistanceInfo::addFollower(), addLeader(), MSLeaderDistanceInfo::addLeader(), clear(), and MSLeaderInfo().
int MSLeaderInfo::myFreeSublanes protected
the number of free sublanes
Definition at line 115 of file MSLeaderInfo.h.
Referenced by MSCriticalFollowerDistanceInfo::addFollower(), addLeader(), MSLeaderDistanceInfo::addLeader(), clear(), MSLeaderInfo(), numFreeSublanes(), toString(), MSLeaderDistanceInfo::toString(), and MSCriticalFollowerDistanceInfo::toString().
bool MSLeaderInfo::myHasVehicles protected
Definition at line 121 of file MSLeaderInfo.h.
Referenced by MSCriticalFollowerDistanceInfo::addFollower(), addLeader(), MSLeaderDistanceInfo::addLeader(), hasStoppedVehicle(), and hasVehicles().
std::vector<const MSVehicle*> MSLeaderInfo::myVehicles protected
Definition at line 110 of file MSLeaderInfo.h.
Referenced by MSCriticalFollowerDistanceInfo::addFollower(), addLeader(), MSLeaderDistanceInfo::addLeader(), clear(), MSLeaderDistanceInfo::clear(), MSCriticalFollowerDistanceInfo::clear(), getSubLanes(), hasStoppedVehicle(), MSLeaderInfo(), numSublanes(), operator[](), MSLeaderDistanceInfo::operator[](), toString(), MSLeaderDistanceInfo::toString(), and MSCriticalFollowerDistanceInfo::toString().
SUMOReal MSLeaderInfo::myWidth protected
the width of the lane to which this instance applies
Definition at line 108 of file MSLeaderInfo.h.
Referenced by getSubLanes().
The documentation for this class was generated from the following files:
MSLeaderInfo.h
MSLeaderInfo.cpp