SUMO - Simulation of Urban MObility: SigmoidLogic Class Reference
SigmoidLogic Class Reference
#include <MSSOTLPolicy.h>
Protected Member Functions
void init (std::string prefix, const Parameterised *parameterised)
bool sigmoidLogic (SUMOTime elapsed, const MSPhaseDefinition *stage, int vehicleCount)
Protected Attributes
SUMOReal m_k
std::string m_prefix
bool m_useSigmoid
Detailed Description
Definition at line 56 of file MSSOTLPolicy.h.
Member Function Documentation
void SigmoidLogic::init (std::string prefix, const Parameterised * parameterised) protected
Definition at line 48 of file MSSOTLPolicy.cpp.
References TplConvert::_2SUMOReal(), Parameterised::getParameter(), PushButtonLogic::m_prefix, and WRITE_MESSAGE.
Referenced by MSSOTLPhasePolicy::init(), and MSSOTLPlatoonPolicy::init().
bool SigmoidLogic::sigmoidLogic (SUMOTime elapsed, const MSPhaseDefinition * stage, int vehicleCount) protected
Definition at line 64 of file MSSOTLPolicy.cpp.
References MSPhaseDefinition::duration, PushButtonLogic::m_prefix, RandHelper::rand(), SUMOReal, and WRITE_MESSAGE.
Referenced by MSSOTLPhasePolicy::canRelease(), and MSSOTLPlatoonPolicy::canRelease().
Field Documentation
SUMOReal SigmoidLogic::m_k protected
Definition at line 63 of file MSSOTLPolicy.h.
std::string SigmoidLogic::m_prefix protected
Definition at line 64 of file MSSOTLPolicy.h.
bool SigmoidLogic::m_useSigmoid protected
Definition at line 62 of file MSSOTLPolicy.h.
The documentation for this class was generated from the following files:
MSSOTLPolicy.h
MSSOTLPolicy.cpp