SUMO - Simulation of Urban MObility: Boundary Class Reference
Boundary Class Reference
A class that stores a 2D geometrical boundary.
#include <Boundary.h>
Public Member Functions
void add (SUMOReal x, SUMOReal y)
Makes the boundary include the given coordinate.
void add (const Position &p)
Makes the boundary include the given coordinate.
void add (const Boundary &p)
Makes the boundary include the given boundary.
bool around (const Position &p, SUMOReal offset=0) const
Returns whether the boundary contains the given coordinate.
Boundary ()
Constructor - the boundary is unset.
Boundary (SUMOReal x1, SUMOReal y1, SUMOReal x2, SUMOReal y2)
Constructor - the boundary will be build using the given values.
bool crosses (const Position &p1, const Position &p2) const
Returns whether the boundary crosses the given line.
void flipY ()
flips ymin and ymax
Position getCenter () const
Returns the center of the boundary.
SUMOReal getHeight () const
Returns the height of the boundary.
SUMOReal getWidth () const
Returns the width of the boudary.
Boundary & grow (SUMOReal by)
extends the boundary by the given amount
void growHeight (SUMOReal by)
void growWidth (SUMOReal by)
void moveby (SUMOReal x, SUMOReal y)
Moves the boundary by the given amount.
bool overlapsWith (const AbstractPoly &poly, SUMOReal offset=0) const
Returns whether the boundary overlaps with the given polygon.
bool partialWithin (const AbstractPoly &poly, SUMOReal offset=0) const
Returns whether the boundary is partially within the given polygon.
void reset ()
Resets the boundary.
void set (SUMOReal xmin, SUMOReal ymin, SUMOReal xmax, SUMOReal ymax)
Sets the boundary to the given values.
SUMOReal xmax () const
Returns maximum x-coordinate.
SUMOReal xmin () const
Returns minimum x-coordinate.
SUMOReal ymax () const
Returns maximum y-coordinate.
SUMOReal ymin () const
Returns minimum y-coordinate.
~Boundary ()
Destructor.
Private Attributes
bool myWasInitialised
Information whether the boundary was initialised.
SUMOReal myXmax
SUMOReal myXmin
The boundaries.
SUMOReal myYmax
SUMOReal myYmin
Friends
std::ostream & operator<< (std::ostream &os, const Boundary &b)
Output operator.
Detailed Description
A class that stores a 2D geometrical boundary.
Definition at line 48 of file Boundary.h.
Constructor & Destructor Documentation
Boundary::Boundary ()
Constructor - the boundary is unset.
Definition at line 47 of file Boundary.cpp.
Boundary::Boundary (SUMOReal x1, SUMOReal y1, SUMOReal x2, SUMOReal y2)
Constructor - the boundary will be build using the given values.
Definition at line 53 of file Boundary.cpp.
References add().
Boundary::~Boundary ()
Destructor.
Definition at line 62 of file Boundary.cpp.
Member Function Documentation
void Boundary::add (SUMOReal x, SUMOReal y)
Makes the boundary include the given coordinate.
Definition at line 76 of file Boundary.cpp.
References myWasInitialised, myXmax, myXmin, myYmax, and myYmin.
Referenced by add(), NIVissimConnectionCluster::NodeSubCluster::add(), NIVissimConnectionCluster::add(), Boundary(), GUIDanielPerspectiveChanger::centerTo(), NBNetBuilder::compute(), NIVissimDisturbance::computeBounding(), NIVissimConnection::computeBounding(), GNEEdge::getBoundary(), GUIEdge::getBoundary(), PositionVector::getBoxBoundary(), MSDevice_BTsender::VehicleInformation::getBoxBoundary(), GUITrafficLightLogicWrapper::getCenteringBoundary(), GUIContainer::getCenteringBoundary(), GUIPerson::getCenteringBoundary(), GUIPolygon::getCenteringBoundary(), GUIPointOfInterest::getCenteringBoundary(), GUIBaseVehicle::getCenteringBoundary(), GUILane::getCenteringBoundary(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GNENet::GNENet(), GUICalibrator::GUICalibrator(), GUILaneSpeedTrigger::GUILaneSpeedTrigger(), GUITriggeredRerouter::GUITriggeredRerouter(), GUITriggeredRerouter::GUITriggeredRerouterEdge::GUITriggeredRerouterEdge(), GUINet::initGUIStructures(), NBHeightMapper::loadShapeFile(), NBHeightMapper::loadTiff(), GNEViewNet::mergeJunctions(), GUITriggeredRerouter::myEndElement(), GUIMEInductLoop::MyWrapper::MyWrapper(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUI_E2_ZS_CollectorOverLanes::MyWrapper::MyWrapper(), GUIE3Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), GNEViewNet::onLeftBtnRelease(), NIVissimConnectionCluster::recomputeBoundary(), GNENet::registerEdge(), GNENet::registerJunction(), GUIDanielPerspectiveChanger::setViewport(), GNEJunction::updateGeometry(), and GeoConvHelper::x2cartesian().
void Boundary::add (const Position & p)
Makes the boundary include the given coordinate.
Definition at line 93 of file Boundary.cpp.
References add(), Position::x(), and Position::y().
void Boundary::add (const Boundary & p)
Makes the boundary include the given boundary.
Definition at line 99 of file Boundary.cpp.
References add(), xmax(), xmin(), ymax(), and ymin().
bool Boundary::around (const Position & p, SUMOReal offset = 0) const virtual
Returns whether the boundary contains the given coordinate.
Implements AbstractPoly.
Definition at line 148 of file Boundary.cpp.
References myXmax, myXmin, myYmax, myYmin, Position::x(), and Position::y().
Referenced by PCPolyContainer::add(), NIVissimConnectionCluster::around(), NBHeightMapper::getZ(), and NIVissimConnectionCluster::recheckEdges().
bool Boundary::crosses (const Position & p1, const Position & p2) const virtual
Returns whether the boundary crosses the given line.
Implements AbstractPoly.
Definition at line 177 of file Boundary.cpp.
References PositionVector::intersects(), myXmax, myXmin, myYmax, and myYmin.
void Boundary::flipY ()
flips ymin and ymax
Definition at line 223 of file Boundary.cpp.
References myYmax, myYmin, and SUMOReal.
Referenced by GeoConvHelper::computeFinal().
Position Boundary::getCenter () const
Returns the center of the boundary.
Definition at line 106 of file Boundary.cpp.
References myXmax, myXmin, myYmax, myYmin, and SUMOReal.
Referenced by GUISUMOAbstractView::centerTo(), GUIDanielPerspectiveChanger::getXPos(), GUIDanielPerspectiveChanger::getYPos(), NIVissimConnectionCluster::liesOnSameEdgesEnd(), GUIBaseVehicle::setFunctionalColor(), and GUIDanielPerspectiveChanger::zoom().
SUMOReal Boundary::getHeight () const
Returns the height of the boundary.
Definition at line 142 of file Boundary.cpp.
References myYmax, and myYmin.
Referenced by GUISUMOAbstractView::applyGLTransform(), GUIPolygon::drawGL(), GUISUMOAbstractView::getGridHeight(), GUISUMOAbstractView::getPositionInformation(), GNENet::GNENet(), GUIJunctionWrapper::GUIJunctionWrapper(), GUINet::initGUIStructures(), GUIDanielPerspectiveChanger::onKeyPress(), GUIPerspectiveChanger::patchedViewPort(), and GNEJunction::updateGeometry().
SUMOReal Boundary::getWidth () const
Returns the width of the boudary.
Definition at line 136 of file Boundary.cpp.
References myXmax, myXmin, and SUMOReal.
Referenced by GUISUMOAbstractView::applyGLTransform(), GUIPolygon::drawGL(), GUISUMOAbstractView::getGridWidth(), GUISUMOAbstractView::getPositionInformation(), GUIDanielPerspectiveChanger::getZoom(), GUIDanielPerspectiveChanger::getZPos(), GNENet::GNENet(), GUIJunctionWrapper::GUIJunctionWrapper(), GUINet::initGUIStructures(), GUISUMOAbstractView::m2p(), GUIDanielPerspectiveChanger::onKeyPress(), GUISUMOAbstractView::p2m(), GUIPerspectiveChanger::patchedViewPort(), and GNEJunction::updateGeometry().
Boundary & Boundary::grow (SUMOReal by)
extends the boundary by the given amount
The method returns a reference to the instance for further use
Definition at line 201 of file Boundary.cpp.
References myXmax, myXmin, myYmax, and myYmin.
Referenced by GUIDanielPerspectiveChanger::centerTo(), TraCIServer::collectObjectsInRange(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), MSLane::fill(), GNEEdge::getBoundary(), GUIEdge::getBoundary(), GNEInternalLane::getCenteringBoundary(), GNECrossing::getCenteringBoundary(), GUITrafficLightLogicWrapper::getCenteringBoundary(), GNEJunction::getCenteringBoundary(), GUIContainer::getCenteringBoundary(), GUIPerson::getCenteringBoundary(), GUIPolygon::getCenteringBoundary(), GUIInstantInductLoop::MyWrapper::getCenteringBoundary(), GUILaneSpeedTrigger::getCenteringBoundary(), GUICalibrator::getCenteringBoundary(), GUIPointOfInterest::getCenteringBoundary(), GNELane::getCenteringBoundary(), GNEEdge::getCenteringBoundary(), GUIMEInductLoop::MyWrapper::getCenteringBoundary(), GUIJunctionWrapper::getCenteringBoundary(), GUIE3Collector::MyWrapper::getCenteringBoundary(), GUITriggeredRerouter::getCenteringBoundary(), GUIChargingStation::getCenteringBoundary(), GUI_E2_ZS_Collector::MyWrapper::getCenteringBoundary(), GUIContainerStop::getCenteringBoundary(), GUIBusStop::getCenteringBoundary(), GUIEdge::getCenteringBoundary(), GUIInductLoop::MyWrapper::getCenteringBoundary(), GUIBaseVehicle::getCenteringBoundary(), GUITriggeredRerouter::GUITriggeredRerouterEdge::getCenteringBoundary(), GNEAdditional::getCenteringBoundary(), GUILane::getCenteringBoundary(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), NBEdgeCont::ignoreFilterMatch(), GUINet::initGUIStructures(), and GNEViewNet::mergeJunctions().
void Boundary::growHeight (SUMOReal by)
Definition at line 217 of file Boundary.cpp.
References myYmax, and myYmin.
Referenced by GUIPointOfInterest::getCenteringBoundary(), GUIPerspectiveChanger::patchedViewPort(), and GUIDanielPerspectiveChanger::setViewport().
void Boundary::growWidth (SUMOReal by)
Definition at line 210 of file Boundary.cpp.
References myXmax, and myXmin.
Referenced by GUIPointOfInterest::getCenteringBoundary(), GUIPerspectiveChanger::patchedViewPort(), and GUIDanielPerspectiveChanger::setViewport().
void Boundary::moveby (SUMOReal x, SUMOReal y)
Moves the boundary by the given amount.
Definition at line 250 of file Boundary.cpp.
References myXmax, myXmin, myYmax, and myYmin.
Referenced by GUIDanielPerspectiveChanger::centerTo(), GUIDanielPerspectiveChanger::move(), GeoConvHelper::moveConvertedBy(), GUIDanielPerspectiveChanger::onKeyPress(), and GNEJunction::setPosition().
bool Boundary::overlapsWith (const AbstractPoly & poly, SUMOReal offset = 0) const virtual
Returns whether the boundary overlaps with the given polygon.
Implements AbstractPoly.
Definition at line 156 of file Boundary.cpp.
References AbstractPoly::crosses(), myXmax, myXmin, myYmax, myYmin, AbstractPoly::partialWithin(), and partialWithin().
Referenced by NIVissimBoundedClusterObject::crosses(), NBEdgeCont::ignoreFilterMatch(), NIVissimConnectionCluster::overlapsWith(), and NIVissimConnectionCluster::NodeSubCluster::overlapsWith().
bool Boundary::partialWithin (const AbstractPoly & poly, SUMOReal offset = 0) const virtual
Returns whether the boundary is partially within the given polygon.
Implements AbstractPoly.
Definition at line 191 of file Boundary.cpp.
References AbstractPoly::around(), myXmax, myXmin, myYmax, and myYmin.
Referenced by PCPolyContainer::add(), and overlapsWith().
void Boundary::reset ()
Resets the boundary.
Definition at line 66 of file Boundary.cpp.
References myWasInitialised, myXmax, myXmin, myYmax, and myYmin.
Referenced by NBHeightMapper::clearData().
void Boundary::set (SUMOReal xmin, SUMOReal ymin, SUMOReal xmax, SUMOReal ymax)
Sets the boundary to the given values.
Definition at line 241 of file Boundary.cpp.
References myXmax, myXmin, myYmax, myYmin, xmax(), xmin(), ymax(), and ymin().
Referenced by TraCIServer::readTypeCheckingBoundary().
SUMOReal Boundary::xmax () const
Returns maximum x-coordinate.
Definition at line 118 of file Boundary.cpp.
References myXmax, and SUMOReal.
Referenced by add(), NIVissimConnectionCluster::add(), SUMORTree::addAdditionalGLObject(), NBHeightMapper::addTriangle(), NIVissimConnectionCluster::around(), NIVissimConnection::buildNodeClusters(), GUIDanielPerspectiveChanger::changeCanvassLeft(), TraCIServer::collectObjectsInRange(), NBNetBuilder::compute(), NIVissimDisturbance::computeBounding(), NIVissimBoundedClusterObject::crosses(), GeomHelper::crossPoint(), GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), MSLane::fill(), NIVissimConnection::getBoundingBox(), NIVissimConnectionCluster::getPositionForEdge(), TraCIServerAPI_Junction::getTree(), TraCIServerAPI_Polygon::getTree(), NBHeightMapper::getZ(), GUINet::initGUIStructures(), main(), GUISUMOAbstractView::makeSnapshot(), NIVissimConnectionCluster::NIVissimConnectionCluster(), NIVissimConnectionCluster::overlapsWith(), NIVissimConnectionCluster::NodeSubCluster::overlapsWith(), GUISUMOAbstractView::paintGLGrid(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_Simulation::processGet(), NIVissimConnectionCluster::recheckEdges(), NIVissimConnectionCluster::recomputeBoundary(), SUMORTree::removeAdditionalGLObject(), set(), GUIBaseVehicle::setFunctionalColor(), GNEPoly::simplifyShape(), BinaryFormatter::writeAttr(), NWWriter_OpenDrive::writeNetwork(), and GUIDanielPerspectiveChanger::zoom().
SUMOReal Boundary::xmin () const
Returns minimum x-coordinate.
Definition at line 112 of file Boundary.cpp.
References myXmin, and SUMOReal.
Referenced by add(), NIVissimConnectionCluster::add(), SUMORTree::addAdditionalGLObject(), NBHeightMapper::addTriangle(), GUISUMOAbstractView::applyGLTransform(), NIVissimConnectionCluster::around(), NIVissimConnection::buildNodeClusters(), GUIDanielPerspectiveChanger::changeCanvassLeft(), TraCIServer::collectObjectsInRange(), NBNetBuilder::compute(), NIVissimDisturbance::computeBounding(), NIVissimBoundedClusterObject::crosses(), GeomHelper::crossPoint(), GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), MSLane::fill(), NIVissimConnection::getBoundingBox(), NIVissimConnectionCluster::getPositionForEdge(), GUISUMOAbstractView::getPositionInformation(), TraCIServerAPI_Junction::getTree(), TraCIServerAPI_Polygon::getTree(), NBHeightMapper::getZ(), GUINet::initGUIStructures(), main(), GUISUMOAbstractView::makeSnapshot(), NBNetBuilder::moveToOrigin(), NIVissimConnectionCluster::NIVissimConnectionCluster(), NIVissimConnectionCluster::overlapsWith(), NIVissimConnectionCluster::NodeSubCluster::overlapsWith(), GUISUMOAbstractView::paintGLGrid(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_Simulation::processGet(), NIVissimConnectionCluster::recheckEdges(), NIVissimConnectionCluster::recomputeBoundary(), SUMORTree::removeAdditionalGLObject(), set(), GUIBaseVehicle::setFunctionalColor(), GNEPoly::simplifyShape(), BinaryFormatter::writeAttr(), NWWriter_OpenDrive::writeNetwork(), and GUIDanielPerspectiveChanger::zoom().
SUMOReal Boundary::ymax () const
Returns maximum y-coordinate.
Definition at line 130 of file Boundary.cpp.
References myYmax, and SUMOReal.
Referenced by add(), SUMORTree::addAdditionalGLObject(), NBHeightMapper::addTriangle(), GUIDanielPerspectiveChanger::changeCanvassLeft(), TraCIServer::collectObjectsInRange(), NBNetBuilder::compute(), GeomHelper::crossPoint(), GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), MSLane::fill(), TraCIServerAPI_Junction::getTree(), TraCIServerAPI_Polygon::getTree(), NBHeightMapper::getZ(), GUINet::initGUIStructures(), main(), GUISUMOAbstractView::makeSnapshot(), NBNetBuilder::moveToOrigin(), GUISUMOAbstractView::paintGLGrid(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_Simulation::processGet(), SUMORTree::removeAdditionalGLObject(), set(), GUIBaseVehicle::setFunctionalColor(), GNEPoly::simplifyShape(), BinaryFormatter::writeAttr(), NWWriter_OpenDrive::writeNetwork(), and GUIDanielPerspectiveChanger::zoom().
SUMOReal Boundary::ymin () const
Returns minimum y-coordinate.
Definition at line 124 of file Boundary.cpp.
References myYmin, and SUMOReal.
Referenced by add(), SUMORTree::addAdditionalGLObject(), NBHeightMapper::addTriangle(), GUISUMOAbstractView::applyGLTransform(), GUIDanielPerspectiveChanger::changeCanvassLeft(), TraCIServer::collectObjectsInRange(), NBNetBuilder::compute(), GeomHelper::crossPoint(), GUIViewTraffic::doPaintGL(), GNEViewNet::doPaintGL(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), MSLane::fill(), GUISUMOAbstractView::getPositionInformation(), TraCIServerAPI_Junction::getTree(), TraCIServerAPI_Polygon::getTree(), GNENet::GNENet(), GUINet::initGUIStructures(), main(), GUISUMOAbstractView::makeSnapshot(), NBNetBuilder::moveToOrigin(), GUISUMOAbstractView::paintGLGrid(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_Simulation::processGet(), SUMORTree::removeAdditionalGLObject(), set(), GUIBaseVehicle::setFunctionalColor(), GNEPoly::simplifyShape(), BinaryFormatter::writeAttr(), NWWriter_OpenDrive::writeNetwork(), and GUIDanielPerspectiveChanger::zoom().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const Boundary & b) friend
Output operator.
Definition at line 234 of file Boundary.cpp.
Field Documentation
bool Boundary::myWasInitialised private
Information whether the boundary was initialised.
Definition at line 132 of file Boundary.h.
Referenced by add(), and reset().
SUMOReal Boundary::myXmax private
Definition at line 129 of file Boundary.h.
Referenced by add(), around(), crosses(), getCenter(), getWidth(), grow(), growWidth(), moveby(), operator<<(), overlapsWith(), partialWithin(), reset(), set(), and xmax().
SUMOReal Boundary::myXmin private
The boundaries.
Definition at line 129 of file Boundary.h.
Referenced by add(), around(), crosses(), getCenter(), getWidth(), grow(), growWidth(), moveby(), operator<<(), overlapsWith(), partialWithin(), reset(), set(), and xmin().
SUMOReal Boundary::myYmax private
Definition at line 129 of file Boundary.h.
Referenced by add(), around(), crosses(), flipY(), getCenter(), getHeight(), grow(), growHeight(), moveby(), operator<<(), overlapsWith(), partialWithin(), reset(), set(), and ymax().
SUMOReal Boundary::myYmin private
Definition at line 129 of file Boundary.h.
Referenced by add(), around(), crosses(), flipY(), getCenter(), getHeight(), grow(), growHeight(), moveby(), operator<<(), overlapsWith(), partialWithin(), reset(), set(), and ymin().
The documentation for this class was generated from the following files:
Boundary.h
Boundary.cpp