SUMO - Simulation of Urban MObility: GUIEdgeControlBuilder Class Reference
GUIEdgeControlBuilder Class Reference
Derivation of NLEdgeControlBuilder which builds gui-edges.
#include <GUIEdgeControlBuilder.h>
Public Member Functions
virtual void addCrossingEdges (const std::vector< std::string > &)
add the crossingEdges in a crossing edge if present
virtual MSLane * addLane (const std::string &id, SUMOReal maxSpeed, SUMOReal length, const PositionVector &shape, SUMOReal width, SVCPermissions permissions, int index)
Builds and adds a lane.
virtual void addNeigh (const std::string id)
Adds a neighbor to the current lane.
void beginEdgeParsing (const std::string &id, const MSEdge::EdgeBasicFunction function, const std::string &streetName, const std::string &edgeType, int priority)
Begins building of an MSEdge.
MSEdgeControl * build ()
builds the MSEdgeControl-class which holds all edges
MSEdge * buildEdge (const std::string &id, const MSEdge::EdgeBasicFunction function, const std::string &streetName, const std::string &edgeType, const int priority)
Builds an edge instance (GUIEdge in this case)
virtual MSEdge * closeEdge ()
Closes the building of an edge; The edge is completely described by now and may not be opened again.
GUIEdgeControlBuilder ()
Constructor.
~GUIEdgeControlBuilder ()
Destructor.
Protected Attributes
MSEdge * myActiveEdge
pointer to the currently chosen edge
int myCurrentNumericalEdgeID
A running number for edge numbering.
int myCurrentNumericalLaneID
A running number for lane numbering.
MSEdgeVector myEdges
Temporary, internal storage for built edges.
std::vector< MSLane * > * myLaneStorage
pointer to a temporary lane storage
Private Member Functions
GUIEdgeControlBuilder (const GUIEdgeControlBuilder &s)
invalidated copy constructor
GUIEdgeControlBuilder & operator= (const GUIEdgeControlBuilder &s)
invalidated assignment operator
Detailed Description
Derivation of NLEdgeControlBuilder which builds gui-edges.
Instead of building pure microsim-objects (MSEdge and MSLane), this class builds GUIEdges and GUILanes.
See also
NLEdgeControlBuilder
Definition at line 60 of file GUIEdgeControlBuilder.h.
Constructor & Destructor Documentation
GUIEdgeControlBuilder::GUIEdgeControlBuilder ()
Constructor.
Parameters
[in] glObjectIDStorage Storage of gl-ids used to assign new ids to built edges
Definition at line 53 of file GUIEdgeControlBuilder.cpp.
GUIEdgeControlBuilder::~GUIEdgeControlBuilder ()
Destructor.
Definition at line 57 of file GUIEdgeControlBuilder.cpp.
GUIEdgeControlBuilder::GUIEdgeControlBuilder (const GUIEdgeControlBuilder & s) private
invalidated copy constructor
Member Function Documentation
void NLEdgeControlBuilder::addCrossingEdges (const std::vector< std::string > & crossingEdges) virtual inherited
add the crossingEdges in a crossing edge if present
Parameters
[in] the vector of crossed edges id
Definition at line 147 of file NLEdgeControlBuilder.cpp.
References NLEdgeControlBuilder::myActiveEdge, and MSEdge::setCrossingEdges().
Referenced by NLHandler::beginEdgeParsing().
MSLane * GUIEdgeControlBuilder::addLane (const std::string & id, SUMOReal maxSpeed, SUMOReal length, const PositionVector & shape, SUMOReal width, SVCPermissions permissions, int index) virtual
Builds and adds a lane.
Parameters
[in] id The lane's id
[in] maxSpeed The speed allowed on this lane
[in] length The lane's length
[in] shape The shape of the lane
[in] width The width of the lane
[in] permissions Encoding of vehicle classes that may drive on this lane
[in] index The index of this lane within its parent edge
See also
SUMOVehicleClass
MSLane
Reimplemented from NLEdgeControlBuilder.
Definition at line 61 of file GUIEdgeControlBuilder.cpp.
References NLEdgeControlBuilder::myActiveEdge, NLEdgeControlBuilder::myCurrentNumericalLaneID, and NLEdgeControlBuilder::myLaneStorage.
void NLEdgeControlBuilder::addNeigh (const std::string id) virtual inherited
Adds a neighbor to the current lane.
Parameters
[in] id The lane's id
See also
MSLane
Definition at line 95 of file NLEdgeControlBuilder.cpp.
References NLEdgeControlBuilder::myLaneStorage.
Referenced by NLHandler::myStartElement().
void NLEdgeControlBuilder::beginEdgeParsing (const std::string & id, const MSEdge::EdgeBasicFunction function, const std::string & streetName, const std::string & edgeType, int priority) inherited
Begins building of an MSEdge.
Builds an instance of MSEdge using "buildEdge". Stores it as the current edge in "myActiveEdge" and appends it to the list of built edges ("myEdges").
The given information is used to build the edge.
Parameters
[in] id The id of the edge
[in] function The function of the edge
[in] streetName The street name of the edge
Exceptions
InvalidArgument If an edge with the same name was already built
Definition at line 70 of file NLEdgeControlBuilder.cpp.
References NLEdgeControlBuilder::buildEdge(), MSEdge::dictionary(), NLEdgeControlBuilder::myActiveEdge, and NLEdgeControlBuilder::myEdges.
Referenced by NLHandler::beginEdgeParsing().
MSEdgeControl * NLEdgeControlBuilder::build () inherited
builds the MSEdgeControl-class which holds all edges
Definition at line 112 of file NLEdgeControlBuilder.cpp.
References deprecatedVehicleClassesSeen, Named::getID(), MSEdge::getIncomingEdges(), MSEdge::getNumSuccessors(), MSEdge::getSuccessors(), MSGlobals::gUsingInternalLanes, MSEdge::isInternal(), MSEdge::markAsRoundabout(), NLEdgeControlBuilder::myEdges, toString(), and WRITE_WARNING.
Referenced by NLBuilder::buildNet().
MSEdge * GUIEdgeControlBuilder::buildEdge (const std::string & id, const MSEdge::EdgeBasicFunction function, const std::string & streetName, const std::string & edgeType, const int priority) virtual
Builds an edge instance (GUIEdge in this case)
Builds an GUIEdge-instance using the given name and the current index "myCurrentNumericalEdgeID" Post-increments the index, returns the built edge.
Parameters
[in] id The id of the edge to build
Reimplemented from NLEdgeControlBuilder.
Definition at line 75 of file GUIEdgeControlBuilder.cpp.
References NLEdgeControlBuilder::myCurrentNumericalEdgeID.
MSEdge * NLEdgeControlBuilder::closeEdge () virtual inherited
Closes the building of an edge; The edge is completely described by now and may not be opened again.
Definition at line 101 of file NLEdgeControlBuilder.cpp.
References MSEdge::initialize(), NLEdgeControlBuilder::myActiveEdge, and NLEdgeControlBuilder::myLaneStorage.
Referenced by NLHandler::closeEdge().
GUIEdgeControlBuilder& GUIEdgeControlBuilder::operator= (const GUIEdgeControlBuilder & s) private
invalidated assignment operator
Field Documentation
MSEdge* NLEdgeControlBuilder::myActiveEdge protected inherited
pointer to the currently chosen edge
Definition at line 154 of file NLEdgeControlBuilder.h.
Referenced by NLEdgeControlBuilder::addCrossingEdges(), addLane(), NLEdgeControlBuilder::addLane(), NLEdgeControlBuilder::beginEdgeParsing(), NLEdgeControlBuilder::closeEdge(), and NLEdgeControlBuilder::NLEdgeControlBuilder().
int NLEdgeControlBuilder::myCurrentNumericalEdgeID protected inherited
A running number for edge numbering.
Definition at line 148 of file NLEdgeControlBuilder.h.
Referenced by buildEdge(), and NLEdgeControlBuilder::buildEdge().
int NLEdgeControlBuilder::myCurrentNumericalLaneID protected inherited
A running number for lane numbering.
Definition at line 145 of file NLEdgeControlBuilder.h.
Referenced by addLane(), and NLEdgeControlBuilder::addLane().
MSEdgeVector NLEdgeControlBuilder::myEdges protected inherited
Temporary, internal storage for built edges.
Definition at line 151 of file NLEdgeControlBuilder.h.
Referenced by NLEdgeControlBuilder::beginEdgeParsing(), and NLEdgeControlBuilder::build().
std::vector<MSLane*>* NLEdgeControlBuilder::myLaneStorage protected inherited
pointer to a temporary lane storage
Definition at line 157 of file NLEdgeControlBuilder.h.
Referenced by addLane(), NLEdgeControlBuilder::addLane(), NLEdgeControlBuilder::addNeigh(), NLEdgeControlBuilder::closeEdge(), NLEdgeControlBuilder::NLEdgeControlBuilder(), and NLEdgeControlBuilder::~NLEdgeControlBuilder().
The documentation for this class was generated from the following files:
GUIEdgeControlBuilder.h
GUIEdgeControlBuilder.cpp