SUMO - Simulation of Urban MObility: GUISettingsHandler Class Reference
GUISettingsHandler Class Reference
An XML-handler for visualisation schemes.
#include <GUISettingsHandler.h>
Public Member Functions
std::string addSettings (GUISUMOAbstractView *view=0) const
Adds the parsed settings to the global list of settings.
void applyViewport (GUISUMOAbstractView *view) const
Sets the viewport which has been parsed.
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::vector< SUMOTime > & getBreakpoints () const
Returns the parsed breakpoints.
const std::vector< GUISUMOAbstractView::Decal > & getDecals () const
Returns the parsed decals.
SUMOReal getDelay () const
Returns the parsed delay.
RandomDistributor< std::string > getEventDistribution (const std::string &id)
const std::string & getFileName () const
returns the current file name
SUMOReal getJamSoundTime ()
const std::string & getViewType () const
Returns the parsed view type.
GUISettingsHandler (const std::string &content, bool isFile=true)
Constructor.
bool hasDecals () const
Returns whether any decals have been parsed.
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void setSnapshots (GUISUMOAbstractView *view) const
Makes a snapshot if it has been parsed.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
~GUISettingsHandler ()
Destructor.
inherited from GenericSAXHandler
void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Static Public Member Functions
static std::vector< SUMOTime > loadBreakpoints (const std::string &file)
loads breakpoints from the specified file
Protected Member Functions
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
virtual void myEndElement (int element)
Callback method for a closing tag to implement by derived classes.
Private Member Functions
GUIVisualizationSizeSettings parseSizeSettings (const std::string &prefix, const SUMOSAXAttributes &attrs, GUIVisualizationSizeSettings defaults)
parse attributes for sizeSettings
GUIVisualizationTextSettings parseTextSettings (const std::string &prefix, const SUMOSAXAttributes &attrs, GUIVisualizationTextSettings defaults)
parse attributes for textSettings
Private Attributes
std::vector< SUMOTime > myBreakpoints
The parsed breakpoints.
int myCurrentColorer
The last color scheme category (edges or vehicles)
GUIScaleScheme * myCurrentScaleScheme
The current scaling scheme.
GUIColorScheme * myCurrentScheme
The current color scheme.
std::vector< GUISUMOAbstractView::Decal > myDecals
The decals list to fill.
SUMOReal myDelay
The delay loaded.
std::map< std::string, RandomDistributor< std::string > > myEventDistributions
The parsed event distributions.
SUMOReal myJamSoundTime
Position myLookAt
The point to look at, only needed for osg view.
Position myLookFrom
The viewport loaded, zoom is stored in z coordinate.
GUIVisualizationSettings mySettings
The settings to fill.
std::map< SUMOTime, std::string > mySnapshots
mappig of time steps to filenames for potential snapshots
std::string myViewType
The view type (osg, opengl, default) loaded.
Detailed Description
An XML-handler for visualisation schemes.
Definition at line 52 of file GUISettingsHandler.h.
Constructor & Destructor Documentation
GUISettingsHandler::GUISettingsHandler (const std::string & content, bool isFile = true)
Constructor.
Parameters
[in] file the file to parse
Definition at line 56 of file GUISettingsHandler.cpp.
References XMLSubSys::getSAXReader(), SUMOSAXReader::parseString(), XMLSubSys::runParser(), and GenericSAXHandler::setFileName().
GUISettingsHandler::~GUISettingsHandler ()
Destructor.
Definition at line 70 of file GUISettingsHandler.cpp.
Member Function Documentation
std::string GUISettingsHandler::addSettings (GUISUMOAbstractView * view = 0) const
Adds the parsed settings to the global list of settings.
Returns
the name of the parsed settings
Definition at line 340 of file GUISettingsHandler.cpp.
References GUICompleteSchemeStorage::add(), GUISUMOAbstractView::getColoringSchemesCombo(), gSchemeStorage, mySettings, GUIVisualizationSettings::name, and GUISUMOAbstractView::setColorScheme().
Referenced by GNEApplicationWindow::handleEvent_NetworkLoaded(), GUIApplicationWindow::handleEvent_SimulationLoaded(), GUICompleteSchemeStorage::init(), and GUIDialog_ViewSettings::loadSettings().
void GUISettingsHandler::applyViewport (GUISUMOAbstractView * view) const
Sets the viewport which has been parsed.
Parameters
[in] parent the view for which the viewport has to be set
Definition at line 354 of file GUISettingsHandler.cpp.
References GUISUMOAbstractView::getChanger(), myLookAt, myLookFrom, GUISUMOAbstractView::setViewportFromTo(), Position::x(), Position::y(), Position::z(), and GUIPerspectiveChanger::zoom2ZPos().
Referenced by GNEApplicationWindow::handleEvent_NetworkLoaded(), GUIApplicationWindow::handleEvent_SimulationLoaded(), GUIDialog_ViewSettings::loadSettings(), and GUIDialog_EditViewport::onCmdLoad().
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 192 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 175 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 211 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), MSRouteHandler::myStartElement(), and MSRouteHandler::parseWalkPos().
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 217 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::vector<SUMOTime>& GUISettingsHandler::getBreakpoints () const inline
Returns the parsed breakpoints.
Returns
the parsed breakpoints
Definition at line 119 of file GUISettingsHandler.h.
References loadBreakpoints(), and myBreakpoints.
Referenced by GUIApplicationWindow::handleEvent_SimulationLoaded().
const std::vector< GUISUMOAbstractView::Decal > & GUISettingsHandler::getDecals () const
Returns the parsed decals.
Returns
the parsed decals
Definition at line 378 of file GUISettingsHandler.cpp.
References myDecals, and SUMOReal.
Referenced by GNEApplicationWindow::handleEvent_NetworkLoaded(), GUIApplicationWindow::handleEvent_SimulationLoaded(), GUIDialog_ViewSettings::loadDecals(), and GUIDialog_ViewSettings::loadSettings().
SUMOReal GUISettingsHandler::getDelay () const
Returns the parsed delay.
Returns
the parsed delay
Definition at line 384 of file GUISettingsHandler.cpp.
References myDelay.
Referenced by GUIApplicationWindow::handleEvent_SimulationLoaded(), and GUIDialog_ViewSettings::loadSettings().
RandomDistributor< std::string > GUISettingsHandler::getEventDistribution (const std::string & id)
Definition at line 413 of file GUISettingsHandler.cpp.
References RandomDistributor< T >::add(), RandomDistributor< T >::getOverallProb(), and myEventDistributions.
Referenced by getViewType(), and GUIApplicationWindow::handleEvent_SimulationLoaded().
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), myStartElement(), MSStateHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
SUMOReal GUISettingsHandler::getJamSoundTime () inline
Definition at line 136 of file GUISettingsHandler.h.
References myJamSoundTime.
Referenced by GUIApplicationWindow::handleEvent_SimulationLoaded().
const std::string& GUISettingsHandler::getViewType () const inline
Returns the parsed view type.
Returns
the parsed view type
Definition at line 131 of file GUISettingsHandler.h.
References getEventDistribution(), and myViewType.
Referenced by GUIApplicationWindow::handleEvent_SimulationLoaded().
bool GUISettingsHandler::hasDecals () const
Returns whether any decals have been parsed.
Returns
whether decals have been parsed
Definition at line 372 of file GUISettingsHandler.cpp.
References myDecals.
Referenced by GUIDialog_ViewSettings::loadDecals(), and GUIDialog_ViewSettings::loadSettings().
std::vector< SUMOTime > GUISettingsHandler::loadBreakpoints (const std::string & file) static
loads breakpoints from the specified file
Definition at line 390 of file GUISettingsHandler.cpp.
References string2time(), and WRITE_ERROR.
Referenced by getBreakpoints(), myStartElement(), and GUIDialog_Breakpoints::onCmdLoad().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 227 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void GenericSAXHandler::myEndElement (int element) protected virtual inherited
Callback method for a closing tag to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The closed element, given as a int ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_OpenDrive, NIImporter_OpenStreetMap::RelationHandler, NIImporter_Vissim::NIVissimXMLHandler_Routenentscheidungsdefinition, NIImporter_Vissim::NIVissimXMLHandler_Geschwindigkeitsverteilungsdefinition, NIImporter_OpenStreetMap::EdgesHandler, PCLoaderOSM::EdgesHandler, NIImporter_Vissim::NIVissimXMLHandler_VWunschentscheidungsdefinition, NIImporter_OpenStreetMap::NodesHandler, NIImporter_Vissim::NIVissimXMLHandler_Fahrzeugklassendefinition, PCLoaderOSM::RelationsHandler, MSTriggeredRerouter, SAXWeightsHandler, PCLoaderOSM::NodesHandler, NLHandler, NIImporter_ITSUMO::Handler, MSLaneSpeedTrigger, NIImporter_SUMO, NIImporter_Vissim::NIVissimXMLHandler_Streckendefinition, NIXMLEdgesHandler, MSCalibrator, SUMORouteHandler, RORouteHandler, ODDistrictHandler, MSRouteHandler, RONetHandler, MSStateHandler, NIXMLTrafficLightsHandler, GUITriggeredRerouter, GNEPoly::GNEPolyHandler, and ROMARouteHandler.
Definition at line 231 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement(), NLHandler::networkVersion(), and SUMOSAXReader::parseNext().
void GUISettingsHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) virtual
Called on the opening of a tag.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 75 of file GUISettingsHandler.cpp.
References TplConvert::_2bool(), TplConvert::_2int(), TplConvert::_2SUMOReal(), GUIPropertyScheme< T >::addColor(), GUIVisualizationSettings::addMode, GUIVisualizationSettings::addName, GUIVisualizationSettings::addSize, GUISUMOAbstractView::Decal::altitude, GUIVisualizationSettings::antialiase, GUIVisualizationSettings::backgroundColor, GUISUMOAbstractView::Decal::centerX, GUISUMOAbstractView::Decal::centerY, GUISUMOAbstractView::Decal::centerZ, GUIPropertyScheme< T >::clear(), GUIVisualizationSettings::containerColorer, GUIVisualizationSettings::containerName, GUIVisualizationSettings::containerQuality, GUIVisualizationSettings::containerSize, GUICompleteSchemeStorage::contains(), GUIVisualizationSettings::cwaEdgeName, GUIVisualizationSettings::dither, GUIVisualizationSettings::drawCrossingsAndWalkingareas, GUIVisualizationSettings::drawJunctionShape, GUIVisualizationSettings::drawLinkJunctionIndex, GUIVisualizationSettings::drawLinkTLIndex, GUIVisualizationSettings::edgeColorer, GUIVisualizationSettings::edgeName, GUIVisualizationSettings::edgeScaler, GUISUMOAbstractView::Decal::filename, GUICompleteSchemeStorage::get(), SUMOSAXAttributes::get(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), GUIPropertySchemeStorage< T >::getSchemeByName(), SUMOSAXAttributes::getStringSecure(), GUIVisualizationSettings::gridXSize, GUIVisualizationSettings::gridYSize, gSchemeStorage, GUISUMOAbstractView::Decal::height, GUIVisualizationSettings::hideConnectors, GUISUMOAbstractView::Decal::initialised, GUIVisualizationSettings::internalEdgeName, GUIVisualizationSettings::internalJunctionName, FileHelpers::isAbsolute(), GUIPropertyScheme< T >::isFixed(), GUIVisualizationSettings::junctionColorer, GUIVisualizationSettings::junctionName, GUIVisualizationSettings::junctionSize, GUIVisualizationSettings::laneColorer, GUIVisualizationSettings::laneMinSize, GUIVisualizationSettings::laneScaler, GUIVisualizationSettings::laneShowBorders, GUIVisualizationSettings::laneWidthExaggeration, GUISUMOAbstractView::Decal::layer, loadBreakpoints(), myBreakpoints, myCurrentColorer, myCurrentScaleScheme, myCurrentScheme, myDecals, myDelay, myEventDistributions, myJamSoundTime, myLookAt, myLookFrom, mySettings, mySnapshots, myViewType, GUIVisualizationSettings::name, RGBColor::parseColorReporting(), parseSizeSettings(), parseTextSettings(), GUIVisualizationSettings::personColorer, GUIVisualizationSettings::personName, GUIVisualizationSettings::personQuality, GUIVisualizationSettings::personSize, GUIVisualizationSettings::poiName, GUIVisualizationSettings::poiSize, GUIVisualizationSettings::polyName, GUIVisualizationSettings::polySize, GUISUMOAbstractView::Decal::roll, GUISUMOAbstractView::Decal::rot, Position::set(), GUIPropertySchemeStorage< T >::setActive(), GUIPropertyScheme< T >::setColor(), GUIPropertyScheme< T >::setInterpolated(), GUIVisualizationSettings::showBlinker, GUIVisualizationSettings::showGrid, GUIVisualizationSettings::showLane2Lane, GUIVisualizationSettings::showLaneDirection, GUIVisualizationSettings::showLinkDecals, GUIVisualizationSettings::showRails, GUIVisualizationSettings::showSizeLegend, GUIVisualizationSettings::showSublanes, GUIVisualizationSettings::streetName, SUMO_ATTR_CENTER_X, SUMO_ATTR_CENTER_Y, SUMO_ATTR_CENTER_Z, SUMO_ATTR_COLOR, SUMO_ATTR_COMMAND, SUMO_ATTR_FILE, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_INTERPOLATED, SUMO_ATTR_LAYER, SUMO_ATTR_NAME, SUMO_ATTR_PROB, SUMO_ATTR_THRESHOLD, SUMO_ATTR_TIME, SUMO_ATTR_TYPE, SUMO_ATTR_VALUE, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_ATTR_ZOOM, SUMO_TAG_BREAKPOINTS_FILE, SUMO_TAG_COLORSCHEME, SUMO_TAG_DELAY, SUMO_TAG_ENTRY, SUMO_TAG_SCALINGSCHEME, SUMO_TAG_SNAPSHOT, SUMO_TAG_VIEWPORT, SUMO_TAG_VIEWSETTINGS, SUMO_TAG_VIEWSETTINGS_ADDITIONALS, SUMO_TAG_VIEWSETTINGS_BACKGROUND, SUMO_TAG_VIEWSETTINGS_CONTAINERS, SUMO_TAG_VIEWSETTINGS_DECAL, SUMO_TAG_VIEWSETTINGS_EDGES, SUMO_TAG_VIEWSETTINGS_EVENT, SUMO_TAG_VIEWSETTINGS_EVENT_JAM_TIME, SUMO_TAG_VIEWSETTINGS_JUNCTIONS, SUMO_TAG_VIEWSETTINGS_LEGEND, SUMO_TAG_VIEWSETTINGS_LIGHT, SUMO_TAG_VIEWSETTINGS_OPENGL, SUMO_TAG_VIEWSETTINGS_PERSONS, SUMO_TAG_VIEWSETTINGS_POIS, SUMO_TAG_VIEWSETTINGS_POLYS, SUMO_TAG_VIEWSETTINGS_SCHEME, SUMO_TAG_VIEWSETTINGS_VEHICLES, SUMOReal, GUISUMOAbstractView::Decal::tilt, toString(), GUIVisualizationSettings::vehicleColorer, GUIVisualizationSettings::vehicleName, GUIVisualizationSettings::vehicleQuality, GUIVisualizationSettings::vehicleSize, GUISUMOAbstractView::Decal::width, Position::x(), Position::y(), and Position::z().
GUIVisualizationSizeSettings GUISettingsHandler::parseSizeSettings (const std::string & prefix, const SUMOSAXAttributes & attrs, GUIVisualizationSizeSettings defaults) private
parse attributes for sizeSettings
Definition at line 329 of file GUISettingsHandler.cpp.
References TplConvert::_2bool(), TplConvert::_2SUMOReal(), GUIVisualizationSizeSettings::constantSize, GUIVisualizationSizeSettings::exaggeration, SUMOSAXAttributes::getStringSecure(), GUIVisualizationSizeSettings::minSize, and toString().
Referenced by myStartElement().
GUIVisualizationTextSettings GUISettingsHandler::parseTextSettings (const std::string & prefix, const SUMOSAXAttributes & attrs, GUIVisualizationTextSettings defaults) private
parse attributes for textSettings
Definition at line 317 of file GUISettingsHandler.cpp.
References TplConvert::_2bool(), TplConvert::_2SUMOReal(), GUIVisualizationTextSettings::color, SUMOSAXAttributes::getStringSecure(), RGBColor::parseColorReporting(), GUIVisualizationTextSettings::show, GUIVisualizationTextSettings::size, and toString().
Referenced by myStartElement().
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 167 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
void GUISettingsHandler::setSnapshots (GUISUMOAbstractView * view) const
Makes a snapshot if it has been parsed.
Parameters
[in] parent the view which needs to be shot
Todo:
Please describe why the snapshots are only set if no other existed before (see code)
Definition at line 364 of file GUISettingsHandler.cpp.
References mySnapshots, and GUISUMOAbstractView::setSnapshots().
Referenced by GNEApplicationWindow::handleEvent_NetworkLoaded(), and GUIApplicationWindow::handleEvent_SimulationLoaded().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 205 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
std::vector<SUMOTime> GUISettingsHandler::myBreakpoints private
The parsed breakpoints.
Definition at line 172 of file GUISettingsHandler.h.
Referenced by getBreakpoints(), and myStartElement().
int GUISettingsHandler::myCurrentColorer private
The last color scheme category (edges or vehicles)
Definition at line 163 of file GUISettingsHandler.h.
Referenced by myStartElement().
GUIScaleScheme* GUISettingsHandler::myCurrentScaleScheme private
The current scaling scheme.
Definition at line 169 of file GUISettingsHandler.h.
Referenced by myStartElement().
GUIColorScheme* GUISettingsHandler::myCurrentScheme private
The current color scheme.
Definition at line 166 of file GUISettingsHandler.h.
Referenced by myStartElement().
std::vector<GUISUMOAbstractView::Decal> GUISettingsHandler::myDecals private
The decals list to fill.
Definition at line 160 of file GUISettingsHandler.h.
Referenced by getDecals(), hasDecals(), and myStartElement().
SUMOReal GUISettingsHandler::myDelay private
The delay loaded.
Definition at line 148 of file GUISettingsHandler.h.
Referenced by getDelay(), and myStartElement().
std::map<std::string, RandomDistributor<std::string> > GUISettingsHandler::myEventDistributions private
The parsed event distributions.
Definition at line 175 of file GUISettingsHandler.h.
Referenced by getEventDistribution(), and myStartElement().
SUMOReal GUISettingsHandler::myJamSoundTime private
Definition at line 176 of file GUISettingsHandler.h.
Referenced by getJamSoundTime(), and myStartElement().
Position GUISettingsHandler::myLookAt private
The point to look at, only needed for osg view.
Definition at line 154 of file GUISettingsHandler.h.
Referenced by applyViewport(), and myStartElement().
Position GUISettingsHandler::myLookFrom private
The viewport loaded, zoom is stored in z coordinate.
Definition at line 151 of file GUISettingsHandler.h.
Referenced by applyViewport(), and myStartElement().
GUIVisualizationSettings GUISettingsHandler::mySettings private
The settings to fill.
Definition at line 142 of file GUISettingsHandler.h.
Referenced by addSettings(), and myStartElement().
std::map<SUMOTime, std::string> GUISettingsHandler::mySnapshots private
mappig of time steps to filenames for potential snapshots
Definition at line 157 of file GUISettingsHandler.h.
Referenced by myStartElement(), and setSnapshots().
std::string GUISettingsHandler::myViewType private
The view type (osg, opengl, default) loaded.
Definition at line 145 of file GUISettingsHandler.h.
Referenced by getViewType(), and myStartElement().
The documentation for this class was generated from the following files:
GUISettingsHandler.h
GUISettingsHandler.cpp