SUMO - Simulation of Urban MObility: MSVehicle Class Reference
MSVehicle Class Reference
Representation of a vehicle in the micro simulation.
#include <MSVehicle.h>
Data Structures
struct DriveProcessItem
class Influencer
Changes the wished vehicle speed / lanes.
struct LaneQ
A structure representing the best lanes for continuing the route.
class State
Container that holds the vehicles driving state (position+speed).
struct Stop
Definition of vehicle stop (position and duration)
class WaitingTimeCollector
Stores the waiting intervals over the previous seconds (memory is to be specified in ms.).
Public Types
enum ChangeRequest { REQUEST_NONE, REQUEST_LEFT, REQUEST_RIGHT, REQUEST_HOLD }
Requests set via TraCI.
typedef Named::NamedLikeComparatorIdLess< SUMOVehicle > ComparatorIdLess
Public Member Functions
void activateReminders (const MSMoveReminder::Notification reason)
"Activates" all current move reminder
void addReminder (MSMoveReminder *rem)
Adds a MoveReminder dynamically.
void addStops (const bool ignoreStopErrors)
Adds stops to the built vehicle.
bool addTraciBusOrContainerStop (const std::string &stopId, const SUMOTime duration, const SUMOTime until, const bool parking, const bool triggered, const bool containerTriggered, const bool isContainerStop, std::string &errorMsg)
bool addTraciStop (MSLane *const lane, const SUMOReal startPos, const SUMOReal endPos, const SUMOTime duration, const SUMOTime until, const bool parking, const bool triggered, const bool containerTriggered, std::string &errorMsg)
SUMOReal computeAngle () const
compute the current vehicle angle
bool congested () const
void enterLaneAtInsertion (MSLane *enteredLane, SUMOReal pos, SUMOReal speed, SUMOReal posLat, MSMoveReminder::Notification notification)
Update when the vehicle enters a new lane in the emit step.
void enterLaneAtLaneChange (MSLane *enteredLane)
Update when the vehicle enters a new lane in the laneChange step.
bool enterLaneAtMove (MSLane *enteredLane, bool onTeleporting=false)
Update when the vehicle enters a new lane in the move step.
bool executeMove ()
Executes planned vehicle movements with regards to right-of-way.
void fixPosition ()
repair errors in vehicle position after changing between internal edges
virtual SUMOReal getArrivalPos () const
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
PositionVector getBoundingBox () const
get bounding rectangle
PositionVector getBoundingPoly () const
get bounding polygon
const MSCFModel & getCarFollowModel () const
Returns the vehicle's car following model definition.
MSCFModel::VehicleVariables * getCarFollowVariables () const
Returns the vehicle's car following model variables.
SUMOReal getChosenSpeedFactor () const
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
const MSRouteIterator & getCurrentRouteEdge () const
Returns an iterator pointing to the current edge in this vehicles route.
SUMOTime getDepartDelay () const
Returns the depart delay.
SUMOReal getDepartPos () const
Returns this vehicle's real departure position.
SUMOTime getDeparture () const
Returns this vehicle's real departure time.
MSDevice * getDevice (const std::type_info &type) const
Returns a device of the given type if it exists or 0.
const std::vector< MSDevice * > & getDevices () const
Returns this vehicle's devices.
SUMOReal getDistanceToPosition (SUMOReal destPos, const MSEdge *destEdge) const
const MSEdge * getEdge () const
Returns the edge the vehicle is currently at.
const std::vector< MSLane * > & getFurtherLanes () const
const std::vector< SUMOReal > & getFurtherLanesPosLat () const
const std::string & getID () const
Returns the name of the vehicle.
SUMOReal getImpatience () const
Returns this vehicles impatience.
Influencer & getInfluencer ()
Returns the velocity/lane influencer.
const Influencer * getInfluencer () const
MSAbstractLaneChangeModel & getLaneChangeModel ()
const MSAbstractLaneChangeModel & getLaneChangeModel () const
int getLaneIndex () const
std::pair< const MSVehicle *const, SUMOReal > getLeader (SUMOReal dist=0) const
Returns the leader of the vehicle looking for a fixed distance.
SUMOReal getMaxSpeed () const
Returns the maximum speed.
Stop & getNextStop ()
int getNumberReroutes () const
Returns the number of new routes this vehicle got.
const SUMOVehicleParameter & getParameter () const
Returns the vehicle's parameter (including departure definition)
const MSRoute & getRoute () const
Returns the current route.
SUMOReal getSafeFollowSpeed (const std::pair< const MSVehicle *, SUMOReal > leaderInfo, const SUMOReal seen, const MSLane *const lane, SUMOReal distToCrossing) const
compute safe speed for following the given leader
SUMOReal getSpeedWithoutTraciInfluence () const
Returns the uninfluenced velocity.
SUMOReal getTimeGap () const
Returns the time gap in seconds to the leader of the vehicle looking for a fixed distance.
SUMOVehicleClass getVClass () const
Returns the vehicle's access class.
const MSVehicleType & getVehicleType () const
Returns the vehicle's type definition.
bool hasDeparted () const
Returns whether this vehicle has already departed.
bool hasInfluencer () const
bool hasValidRoute (std::string &msg, const MSRoute *route=0) const
Validates the current or given route.
int influenceChangeDecision (int state)
allow TraCI to influence a lane change decision
bool knowsEdgeTest (MSEdge &edge) const
void leaveLane (const MSMoveReminder::Notification reason)
Update of members if vehicle leaves a new lane in the lane change step or at arrival.
MSVehicle (SUMOVehicleParameter *pars, const MSRoute *route, const MSVehicleType *type, const SUMOReal speedFactor)
Constructor.
void onDepart ()
Called when the vehicle is inserted into the network.
void planMove (const SUMOTime t, const MSLeaderInfo &ahead, const SUMOReal lengthsInFront)
Compute safe velocities for the upcoming lanes based on positions and speeds from the last time step. Also registers ApproachingVehicleInformation for all links.
SUMOReal processNextStop (SUMOReal currentVelocity)
Processes stops, returns the velocity needed to reach the stop.
void removeReminder (MSMoveReminder *rem)
Removes a MoveReminder dynamically.
bool replaceRouteEdges (ConstMSEdgeVector &edges, bool onInit=false, bool check=false)
Replaces the current route by the given edges.
void replaceVehicleType (MSVehicleType *type)
Replaces the current vehicle type by the one given.
void reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > &router, const bool onInit=false, const bool withTaz=false)
Performs a rerouting using the given router.
bool resumeFromStopping ()
void setAngle (SUMOReal angle)
Set a custom vehicle angle in rad.
virtual void setArrivalPos (SUMOReal arrivalPos)
Sets this vehicle's desired arrivalPos for its current route.
void setChosenSpeedFactor (const SUMOReal factor)
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
void setTentativeLaneAndPosition (MSLane *lane, SUMOReal pos, SUMOReal posLat=0)
set tentative lane and position during insertion to ensure that all cfmodels work (some of them require veh->getLane() to return a valid lane) Once the vehicle is sucessfully inserted the lane is set again (see enterLaneAtInsertion)
void setVTDState (Position xyPos)
sets position outside the road network
const MSEdge * succEdge (int nSuccs) const
Returns the nSuccs'th successor of edge the vehicle is currently at.
bool unsafeLinkAhead (const MSLane *lane) const
whether the vehicle may safely move to the given lane with regard to upcoming links
SUMOReal updateFurtherLanes (std::vector< MSLane * > &furtherLanes, std::vector< SUMOReal > &furtherLanesPosLat, const std::vector< MSLane * > &passedLanes)
update a vector of further lanes and return the new backPos
virtual ~MSVehicle ()
Destructor.
insertion/removal
void onRemovalFromNet (const MSMoveReminder::Notification reason)
Called when the vehicle is removed from the network.
interaction with the route
bool hasArrived () const
Returns whether this vehicle has already arived (reached the arrivalPosition on its final edge)
bool replaceRoute (const MSRoute *route, bool onInit=false, int offset=0)
Replaces the current route by the given one.
bool willPass (const MSEdge *const edge) const
Returns whether the vehicle wil pass the given edge.
int getRoutePosition () const
void resetRoutePosition (int index)
const MSEdgeWeightsStorage & getWeightsStorage () const
Returns the vehicle's internal edge travel times/efforts container.
MSEdgeWeightsStorage & getWeightsStorage ()
state setter/getter
SUMOReal getPositionOnLane () const
Get the vehicle's position along the lane.
SUMOReal getPositionOnLane (const MSLane *lane) const
Get the vehicle's front position relative to the given lane.
SUMOReal getBackPositionOnLane (const MSLane *lane) const
Get the vehicle's position relative to the given lane.
SUMOReal getBackPositionOnLane () const
Get the vehicle's position relative to its current lane.
SUMOReal getLateralPositionOnLane () const
Get the vehicle's lateral position on the lane.
SUMOReal getRightSideOnLane () const
Get the vehicle's lateral position on the lane:
SUMOReal getLateralOverlap () const
return the amount by which the vehicle extends laterally outside it's primary lane
SUMOReal getRightSideOnEdge (const MSLane *lane=0) const
Get the vehicle's lateral position on the edge of the given lane (or its current edge if lane == 0)
SUMOReal getCenterOnEdge (const MSLane *lane=0) const
Get the vehicle's lateral position on the edge of the given lane (or its current edge if lane == 0)
SUMOReal getLatOffset (const MSLane *lane) const
Get the offset that that must be added to interpret myState.myPosLat for the given lane.
SUMOReal getSpeed () const
Returns the vehicle's current speed.
SUMOReal getAcceleration () const
Returns the vehicle's acceleration in m/s.
Other getter methods
SUMOReal getSlope () const
Returns the slope of the road at vehicle's position.
Position getPosition (const SUMOReal offset=0) const
Return current position (x/y, cartesian)
MSLane * getLane () const
Returns the lane the vehicle is on.
bool isOnRoad () const
Returns the information whether the vehicle is on a road (is simulated)
bool isFrontOnLane (const MSLane *lane) const
Returns the information whether the front of the vehicle is on the given lane.
const MSEdge * getRerouteOrigin () const
Returns the starting point for reroutes (usually the current edge)
SUMOTime getWaitingTime () const
Returns the SUMOTime waited (speed was lesser than 0.1m/s)
SUMOTime getAccumulatedWaitingTime (SUMOTime t=MSGlobals::gWaitingTimeMemory) const
Returns the SUMOTime waited (speed was lesser than 0.1m/s) within the last t millisecs.
SUMOReal getWaitingSeconds () const
Returns the number of seconds waited (speed was lesser than 0.1m/s)
SUMOReal getAccumulatedWaitingSeconds () const
Returns the number of seconds waited (speed was lesser than 0.1m/s) within the last millisecs.
SUMOReal getAngle () const
Returns the vehicle's direction in degrees.
strategical/tactical lane choosing methods
const std::vector< LaneQ > & getBestLanes () const
Returns the description of best lanes to use in order to continue the route.
void updateBestLanes (bool forceRebuild=false, const MSLane *startLane=0)
computes the best lanes to use in order to continue the route
const std::vector< MSLane * > & getBestLanesContinuation () const
Returns the subpart of best lanes that describes the vehicle's current lane and their successors.
const std::vector< MSLane * > & getBestLanesContinuation (const MSLane *const l) const
Returns the subpart of best lanes that describes the given lane and their successors.
int getBestLaneOffset () const
returns the current offset from the best lane
void adaptBestLanesOccupation (int laneIndex, SUMOReal density)
update occupation from MSLaneChanger
vehicle stops definitions and i/o
bool addStop (const SUMOVehicleParameter::Stop &stopPar, std::string &errorMsg, SUMOTime untilOffset=0)
Adds a stop.
bool hasStops () const
Returns whether the vehicle has to stop somewhere.
bool isStopped () const
Returns whether the vehicle is at a stop.
bool isParking () const
Returns whether the vehicle is parking.
bool isRemoteControlled () const
Returns the information whether the vehicle is fully controlled via TraCI.
SUMOReal nextStopDist () const
return the distance to the next stop or SUMORealMax if there is none.
bool isStoppedTriggered () const
Returns whether the vehicle is on a triggered stop.
bool isStoppedInRange (SUMOReal pos) const
return whether the given position is within range of the current stop
Emission retrieval
SUMOReal getCO2Emissions () const
Returns CO2 emission of the current state.
SUMOReal getCOEmissions () const
Returns CO emission of the current state.
SUMOReal getHCEmissions () const
Returns HC emission of the current state.
SUMOReal getNOxEmissions () const
Returns NOx emission of the current state.
SUMOReal getPMxEmissions () const
Returns PMx emission of the current state.
SUMOReal getFuelConsumption () const
Returns fuel consumption of the current state.
SUMOReal getElectricityConsumption () const
Returns electricity consumption of the current state.
SUMOReal getHarmonoise_NoiseEmissions () const
Returns noise emissions of the current state.
Interaction with persons
void addPerson (MSTransportable *person)
Adds a passenger.
Interaction with containers
void addContainer (MSTransportable *container)
Adds a container.
const std::vector< MSTransportable * > & getPersons () const
retrieve riding persons
const std::vector< MSTransportable * > & getContainers () const
retrieve riding containers
int getPersonNumber () const
Returns the number of persons.
int getContainerNumber () const
Returns the number of containers.
state io
void saveState (OutputDevice &out)
Saves the states of a vehicle.
void loadState (const SUMOSAXAttributes &attrs, const SUMOTime offset)
Loads the state of this vehicle from the given description.
Static Public Member Functions
static int nextLinkPriority (const std::vector< MSLane * > &conts)
get a numerical value for the priority of the upcoming link
static bool overlap (const MSVehicle *veh1, const MSVehicle *veh2)
Protected Types
typedef std::vector< DriveProcessItem > DriveItemVector
Container for used Links/visited Lanes during lookForward.
Protected Member Functions
void adaptToLeader (const std::pair< const MSVehicle *, SUMOReal > leaderInfo, const SUMOReal seen, DriveProcessItem *const lastLink, const MSLane *const lane, SUMOReal &v, SUMOReal &vLinkPass, SUMOReal distToCrossing=-1) const
void adaptToLeaders (const MSLeaderInfo &ahead, SUMOReal latOffset, const SUMOReal seen, DriveProcessItem *const lastLink, const MSLane *const lane, SUMOReal &v, SUMOReal &vLinkPass) const
void calculateArrivalParams ()
(Re-)Calculates the arrival position and lane from the vehicle parameters
void checkRewindLinkLanes (const SUMOReal lengthsInFront, DriveItemVector &lfLinks) const
virtual void drawOutsideNetwork (bool) const
register vehicle for drawing while outside the network
SUMOReal estimateLeaveSpeed (const MSLink *const link, const SUMOReal vLinkPass) const
estimate leaving speed when accelerating across a link
SUMOReal estimateSpeedAfterDistance (const SUMOReal dist, const SUMOReal v, const SUMOReal accel) const
const MSLane * getBackLane () const
const Position getBackPosition () const
SUMOReal getSpaceTillLastStanding (const MSLane *l, bool &foundStopped) const
const ConstMSEdgeVector getStopEdges () const
Returns the list of still pending stop edges.
void planMoveInternal (const SUMOTime t, MSLeaderInfo ahead, DriveItemVector &lfLinks, SUMOReal &myStopDist) const
void removeApproachingInformation (DriveItemVector &lfLinks) const
unregister approach from all upcoming links
void setBlinkerInformation ()
void setEmergencyBlueLight (SUMOTime currentTime)
sets the blue flashing light for emergency vehicles
void updateOccupancyAndCurrentBestLane (const MSLane *startLane)
updates LaneQ::nextOccupation and myCurrentLaneInBestLanes
Protected Attributes
SUMOReal myAcceleration
The current acceleration after dawdling in m/s.
bool myAmOnNet
Whether the vehicle is on the network (not parking, teleported, vaporized, or arrived)
bool myAmRegisteredAsWaitingForContainer
Whether this vehicle is registered as waiting for a container (for deadlock-recognition)
bool myAmRegisteredAsWaitingForPerson
Whether this vehicle is registered as waiting for a person (for deadlock-recognition)
SUMOReal myAngle
the angle (
int myArrivalLane
The destination lane where the vehicle stops.
SUMOReal myArrivalPos
The position on the destination lane where the vehicle stops.
std::vector< std::vector< LaneQ > > myBestLanes
Position myCachedPosition
SUMOReal myChosenSpeedFactor
A precomputed factor by which the driver wants to be faster than the speed limit.
MSDevice_Transportable * myContainerDevice
The containers this vehicle may have.
MSRouteIterator myCurrEdge
Iterator to current route-edge.
std::vector< LaneQ >::iterator myCurrentLaneInBestLanes
SUMOReal myDepartPos
The real depart position.
SUMOTime myDeparture
The real departure time.
std::vector< MSDevice * > myDevices
The devices this vehicle has.
std::vector< MSLane * > myFurtherLanes
The information into which lanes the vehicle laps into.
std::vector< SUMOReal > myFurtherLanesPosLat
bool myHaveToWaitOnNextLink
MSLane * myLane
The lane the vehicle is on.
MSAbstractLaneChangeModel * myLaneChangeModel
const MSEdge * myLastBestLanesEdge
const MSLane * myLastBestLanesInternalLane
DriveItemVector myLFLinkLanes
int myNumberReroutes
The number of reroutings.
const SUMOVehicleParameter * myParameter
This Vehicle's parameter.
MSDevice_Transportable * myPersonDevice
The passengers this vehicle may have.
const MSRoute * myRoute
This Vehicle's route.
int mySignals
State of things of the vehicle that can be on or off.
State myState
This Vehicles driving state (pos and speed)
SUMOReal myStopDist
distance to the next stop or -1 if there is none
std::list< Stop > myStops
The vehicle's list of stops.
const MSVehicleType * myType
This Vehicle's type.
SUMOTime myWaitingTime
The time the vehicle waits (is not faster than 0.1m/s) in seconds.
WaitingTimeCollector myWaitingTimeCollector
Static Protected Attributes
static std::vector< MSLane * > myEmptyLaneVector
static std::vector< MSTransportable * > myEmptyTransportableVector
static const SUMOTime NOT_YET_DEPARTED = SUMOTime_MAX
Private Member Functions
MSEdgeWeightsStorage & _getWeightsStorage () const
MSVehicle ()
invalidated default constructor
MSVehicle (const MSVehicle &)
invalidated copy constructor
MSVehicle & operator= (const MSVehicle &)
invalidated assignment operator
Private Attributes
MSCFModel::VehicleVariables * myCFVariables
The per vehicle variables of the car following model.
MSEdgeWeightsStorage * myEdgeWeights
Influencer * myInfluencer
An instance of a velocity/lane influencing instance; built in "getInfluencer".
Friends
class MSLaneChanger
the lane changer sets myLastLaneChangeOffset
class MSLaneChangerSublane
Move reminder structures
typedef std::vector< std::pair< MSMoveReminder *, SUMOReal > > MoveReminderCont
Definition of a move reminder container.
MoveReminderCont myMoveReminders
Current lane's move reminder.
Interaction with move reminders
void workOnMoveReminders (SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed)
Processes active move reminder.
void adaptLaneEntering2MoveReminder (const MSLane &enteredLane)
Adapts the vehicle's entering of a new lane.
Access to bool signals
enum Signalling {
VEH_SIGNAL_NONE = 0, VEH_SIGNAL_BLINKER_RIGHT = 1, VEH_SIGNAL_BLINKER_LEFT = 2, VEH_SIGNAL_BLINKER_EMERGENCY = 4,
VEH_SIGNAL_BRAKELIGHT = 8, VEH_SIGNAL_FRONTLIGHT = 16, VEH_SIGNAL_FOGLIGHT = 32, VEH_SIGNAL_HIGHBEAM = 64,
VEH_SIGNAL_BACKDRIVE = 128, VEH_SIGNAL_WIPER = 256, VEH_SIGNAL_DOOR_OPEN_LEFT = 512, VEH_SIGNAL_DOOR_OPEN_RIGHT = 1024,
VEH_SIGNAL_EMERGENCY_BLUE = 2048, VEH_SIGNAL_EMERGENCY_RED = 4096, VEH_SIGNAL_EMERGENCY_YELLOW = 8192
}
Some boolean values which describe the state of some vehicle parts.
enum LaneChangeMode { LC_NEVER = 0, LC_NOCONFLICT = 1, LC_ALWAYS = 2 }
modes for resolving conflicts between external control (traci) and vehicle control over lane changing. Each level of the lane-changing hierarchy (strategic, cooperative, speedGain, keepRight) can be controlled separately
enum TraciLaneChangePriority { LCP_ALWAYS = 0, LCP_NOOVERLAP = 1, LCP_URGENT = 2, LCP_OPPORTUNISTIC = 3 }
modes for prioritizing traci lane change requests
void switchOnSignal (int signal)
Switches the given signal on.
void switchOffSignal (int signal)
Switches the given signal off.
int getSignals () const
Returns the signals.
bool signalSet (int which) const
Returns whether the given signal is on.
Detailed Description
Representation of a vehicle in the micro simulation.
Definition at line 81 of file MSVehicle.h.
Member Typedef Documentation
typedef Named::NamedLikeComparatorIdLess<SUMOVehicle> SUMOVehicle::ComparatorIdLess inherited
Definition at line 68 of file SUMOVehicle.h.
typedef std::vector< DriveProcessItem > MSVehicle::DriveItemVector protected
Container for used Links/visited Lanes during lookForward.
Definition at line 1486 of file MSVehicle.h.
typedef std::vector< std::pair<MSMoveReminder*, SUMOReal> > MSBaseVehicle::MoveReminderCont protected inherited
Definition of a move reminder container.
Definition at line 403 of file MSBaseVehicle.h.
Member Enumeration Documentation
enum MSVehicle::ChangeRequest
Requests set via TraCI.
Enumerator
REQUEST_NONE
vehicle doesn't want to change
REQUEST_LEFT
vehicle want's to change to left lane
REQUEST_RIGHT
vehicle want's to change to right lane
REQUEST_HOLD
vehicle want's to keep the current lane
Definition at line 206 of file MSVehicle.h.
enum MSVehicle::LaneChangeMode
modes for resolving conflicts between external control (traci) and vehicle control over lane changing. Each level of the lane-changing hierarchy (strategic, cooperative, speedGain, keepRight) can be controlled separately
Enumerator
LC_NEVER
LC_NOCONFLICT
LC_ALWAYS
Definition at line 976 of file MSVehicle.h.
enum MSVehicle::Signalling
Some boolean values which describe the state of some vehicle parts.
Enumerator
VEH_SIGNAL_NONE
Everything is switched off.
VEH_SIGNAL_BLINKER_RIGHT
Right blinker lights are switched on.
VEH_SIGNAL_BLINKER_LEFT
Left blinker lights are switched on.
VEH_SIGNAL_BLINKER_EMERGENCY
Blinker lights on both sides are switched on.
VEH_SIGNAL_BRAKELIGHT
The brake lights are on.
VEH_SIGNAL_FRONTLIGHT
The front lights are on (no visualisation)
VEH_SIGNAL_FOGLIGHT
The fog lights are on (no visualisation)
VEH_SIGNAL_HIGHBEAM
The high beam lights are on (no visualisation)
VEH_SIGNAL_BACKDRIVE
The backwards driving lights are on (no visualisation)
VEH_SIGNAL_WIPER
The wipers are on.
VEH_SIGNAL_DOOR_OPEN_LEFT
One of the left doors is opened.
VEH_SIGNAL_DOOR_OPEN_RIGHT
One of the right doors is opened.
VEH_SIGNAL_EMERGENCY_BLUE
A blue emergency light is on.
VEH_SIGNAL_EMERGENCY_RED
A red emergency light is on.
VEH_SIGNAL_EMERGENCY_YELLOW
A yellow emergency light is on.
Definition at line 938 of file MSVehicle.h.
enum MSVehicle::TraciLaneChangePriority
modes for prioritizing traci lane change requests
Enumerator
LCP_ALWAYS
LCP_NOOVERLAP
LCP_URGENT
LCP_OPPORTUNISTIC
Definition at line 984 of file MSVehicle.h.
Constructor & Destructor Documentation
MSVehicle::MSVehicle (SUMOVehicleParameter * pars, const MSRoute * route, const MSVehicleType * type, const SUMOReal speedFactor)
Constructor.
Parameters
[in] pars The vehicle description
[in] route The vehicle's route
[in] type The vehicle's type
[in] speedFactor The factor for driven lane's speed limits
Exceptions
ProcessError If a value is wrong
Definition at line 523 of file MSVehicle.cpp.
References MSAbstractLaneChangeModel::build(), MSCFModel::createVehicleVariables(), DEPART_LANE_GIVEN, DEPART_SPEED_GIVEN, SUMOVehicleParameter::departLaneProcedure, SUMOVehicleParameter::departSpeed, SUMOVehicleParameter::departSpeedProcedure, MSEdge::EDGEFUNCTION_DISTRICT, MSVehicleType::getCarFollowModel(), MSVehicleType::getID(), MSVehicleType::getLaneChangeModel(), MSVehicleType::getMaxSpeed(), MSVehicleType::getVehicleClass(), SUMOVehicleParameter::id, myCFVariables, and myLaneChangeModel.
MSVehicle::~MSVehicle () virtual
Destructor.
Definition at line 568 of file MSVehicle.cpp.
References MSVehicleType::amVehicleSpecific(), MSAbstractLaneChangeModel::cleanupShadowLane(), myEdgeWeights, myFurtherLanes, myFurtherLanesPosLat, myInfluencer, myLaneChangeModel, myLFLinkLanes, MSBaseVehicle::myType, and removeApproachingInformation().
MSVehicle::MSVehicle () private
invalidated default constructor
MSVehicle::MSVehicle (const MSVehicle &) private
invalidated copy constructor
Member Function Documentation
MSEdgeWeightsStorage & MSVehicle::_getWeightsStorage () const private
Definition at line 696 of file MSVehicle.cpp.
References myEdgeWeights.
Referenced by getWeightsStorage().
void MSVehicle::activateReminders (const MSMoveReminder::Notification reason) virtual
"Activates" all current move reminder
For all move reminder stored in "myMoveReminders", their method "MSMoveReminder::notifyEnter" is called.
Parameters
[in] reason The reason for changing the reminders' states
See also
MSMoveReminder
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented from MSBaseVehicle.
Definition at line 2256 of file MSVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by congested(), enterLaneAtInsertion(), enterLaneAtLaneChange(), and enterLaneAtMove().
void MSVehicle::adaptBestLanesOccupation (int laneIndex, SUMOReal density)
update occupation from MSLaneChanger
Definition at line 2846 of file MSVehicle.cpp.
References myBestLanes.
Referenced by MSLaneChangerSublane::change(), and MSLaneChanger::change().
void MSVehicle::adaptLaneEntering2MoveReminder (const MSLane & enteredLane) protected
Adapts the vehicle's entering of a new lane.
All offsets already stored in "myOldLaneMoveReminderOffsets" are increased by the length that has been left. All still active move reminders from "myMoveReminders" are put into "myOldLaneMoveReminders" and the offset to the last lane is added to "myOldLaneMoveReminderOffsets" for each of these.
Move reminder from the given lane are set into "myMoveReminders".
"myLane" must still be the left lane!
Parameters
[in] enteredLane
See also
MSMoveReminder
MSLane::getMoveReminder
Definition at line 730 of file MSVehicle.cpp.
References MSBaseVehicle::addReminder(), MSLane::getLength(), MSLane::getMoveReminders(), myLane, MSBaseVehicle::myMoveReminders, and SUMOReal.
Referenced by enterLaneAtMove(), and hasInfluencer().
void MSVehicle::adaptToLeader (const std::pair< const MSVehicle *, SUMOReal > leaderInfo, const SUMOReal seen, DriveProcessItem *const lastLink, const MSLane *const lane, SUMOReal & v, SUMOReal & vLinkPass, SUMOReal distToCrossing = -1) const protected
Definition at line 1504 of file MSVehicle.cpp.
References MSVehicle::DriveProcessItem::adaptLeaveSpeed(), DEBUG_COND, Named::getID(), MSBaseVehicle::getID(), getSafeFollowSpeed(), MIN2(), myLane, SIMTIME, and SUMOReal.
Referenced by adaptToLeaders(), estimateSpeedAfterDistance(), and planMoveInternal().
void MSVehicle::adaptToLeaders (const MSLeaderInfo & ahead, SUMOReal latOffset, const SUMOReal seen, DriveProcessItem *const lastLink, const MSLane *const lane, SUMOReal & v, SUMOReal & vLinkPass) const protected
Definition at line 1469 of file MSVehicle.cpp.
References adaptToLeader(), DEBUG_COND, getBackPositionOnLane(), Named::getID(), MSBaseVehicle::getID(), getLane(), MSLane::getLength(), MSVehicleType::getMinGap(), getPositionOnLane(), MSLeaderInfo::getSubLanes(), MSBaseVehicle::getVehicleType(), myLane, MSVehicle::State::myPos, myState, SIMTIME, SUMOReal, and MSLeaderInfo::toString().
Referenced by estimateSpeedAfterDistance(), and planMoveInternal().
void MSVehicle::addContainer (MSTransportable * container) virtual
Adds a container.
Parameters
[in] container The container to add
Reimplemented from MSBaseVehicle.
Definition at line 2987 of file MSVehicle.cpp.
References MSDevice_Transportable::addTransportable(), MSDevice_Transportable::buildVehicleDevices(), MSTransportable::getID(), myContainerDevice, MSBaseVehicle::myDevices, MSBaseVehicle::myMoveReminders, and myStops.
Referenced by MSTransportableControl::loadAnyWaiting(), and nextStopDist().
void MSVehicle::addPerson (MSTransportable * person) virtual
Adds a passenger.
Parameters
[in] person The person to add
Reimplemented from MSBaseVehicle.
Definition at line 2965 of file MSVehicle.cpp.
References MSDevice_Transportable::addTransportable(), MSDevice_Transportable::buildVehicleDevices(), MSTransportable::getID(), MSBaseVehicle::myDevices, MSBaseVehicle::myMoveReminders, myPersonDevice, and myStops.
Referenced by MSTransportableControl::boardAnyWaiting(), and nextStopDist().
void MSBaseVehicle::addReminder (MSMoveReminder * rem) inherited
Adds a MoveReminder dynamically.
Parameters
[in] rem the reminder to add
See also
MSMoveReminder
Definition at line 312 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by adaptLaneEntering2MoveReminder(), MESegment::addReminders(), enterLaneAtInsertion(), enterLaneAtLaneChange(), and MSBaseVehicle::getDevices().
bool MSVehicle::addStop (const SUMOVehicleParameter::Stop & stopPar, std::string & errorMsg, SUMOTime untilOffset = 0) virtual
Adds a stop.
The stop is put into the sorted list.
Parameters
[in] stop The stop to add
Returns
Whether the stop could be added
Implements SUMOVehicle.
Definition at line 860 of file MSVehicle.cpp.
References MSLane::allowsVehicleClass(), SUMOVehicleParameter::Stop::awaitedContainers, MSVehicle::Stop::awaitedContainers, SUMOVehicleParameter::Stop::awaitedPersons, MSVehicle::Stop::awaitedPersons, SUMOVehicleParameter::Stop::busstop, MSVehicle::Stop::busstop, SUMOVehicleParameter::Stop::containerstop, MSVehicle::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, MSVehicle::Stop::containerTriggered, DEPART_POS_BASE, DEPART_POS_DEFAULT, DEPART_POS_GIVEN, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, MSLane::dictionary(), SUMOVehicleParameter::Stop::duration, MSVehicle::Stop::duration, MSVehicle::Stop::edge, MSRoute::end(), SUMOVehicleParameter::Stop::endPos, MSVehicle::Stop::endPos, MSNet::getBusStop(), getCarFollowModel(), MSNet::getContainerStop(), MSLane::getEdge(), Named::getID(), MSNet::getInstance(), MSVehicleType::getLength(), MSLane::getLength(), MSVehicleType::getVehicleClass(), MSBaseVehicle::getVehicleType(), MSBaseVehicle::hasDeparted(), SUMOVehicleParameter::id, SUMOVehicleParameter::Stop::index, SUMOVehicleParameter::Stop::lane, MSVehicle::Stop::lane, MIN2(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myParameter, MSVehicle::State::myPos, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, myState, myStops, MSBaseVehicle::myType, SUMOVehicleParameter::Stop::parking, MSVehicle::Stop::parking, POSITION_EPS, MSVehicle::Stop::reached, SUMOVehicleParameter::Stop::startPos, MSVehicle::Stop::startPos, STOP_INDEX_END, STOP_INDEX_FIT, SUMOReal, MSVehicle::Stop::timeToBoardNextPerson, MSVehicle::Stop::timeToLoadNextContainer, SUMOVehicleParameter::Stop::triggered, MSVehicle::Stop::triggered, SUMOVehicleParameter::Stop::until, and MSVehicle::Stop::until.
Referenced by addTraciBusOrContainerStop(), addTraciStop(), and replaceRoute().
void MSBaseVehicle::addStops (const bool ignoreStopErrors) inherited
Adds stops to the built vehicle.
This code needs to be separated from the MSBaseVehicle constructor since it is not allowed to call virtual functions from a constructor
Parameters
[in] ignoreStopErrors whether invalid stops trigger a warning only
Definition at line 431 of file MSBaseVehicle.cpp.
References SUMOVehicle::addStop(), OutputDevice::closeTag(), MSMoveReminder::getDescription(), OutputDevice::getDeviceByOption(), MSBaseVehicle::getID(), MSNet::getInstance(), MSRoute::getStops(), OptionsCont::getStringVector(), OptionsCont::isSet(), MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, OutputDevice::openTag(), STEPS2TIME, SUMOVehicleParameter::stops, SUMO_ATTR_ID, SUMO_ATTR_TIME, SUMOReal, toString(), WRITE_WARNING, and OutputDevice::writeAttr().
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), and MSBaseVehicle::setChosenSpeedFactor().
bool MSVehicle::addTraciBusOrContainerStop (const std::string & stopId, const SUMOTime duration, const SUMOTime until, const bool parking, const bool triggered, const bool containerTriggered, const bool isContainerStop, std::string & errorMsg)
schedule a new stop for the vehicle; each time a stop is reached, the vehicle will wait for the given duration before continuing on its route
Parameters
stopId bus or container stop id
duration waiting time duration
until time step at which the stop shall end
parking a flag indicating whether the traci stop is used for parking or not
triggered a flag indicating whether the traci stop is triggered or not
containerTriggered a flag indicating whether the traci stop is triggered by a container or not
isContainerStop a flag indicating whether the stop is a container stop
Definition at line 3355 of file MSVehicle.cpp.
References addStop(), SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, MSStoppingPlace::getBeginLanePosition(), MSNet::getBusStop(), MSNet::getContainerStop(), MSStoppingPlace::getEndLanePosition(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSStoppingPlace::getLane(), SUMOVehicleParameter::Stop::index, SUMOVehicleParameter::Stop::lane, myLane, myStops, SUMOVehicleParameter::Stop::parking, SUMOVehicleParameter::Stop::startPos, STOP_INDEX_FIT, SUMOVehicleParameter::Stop::triggered, SUMOVehicleParameter::Stop::until, and updateBestLanes().
Referenced by TraCIServerAPI_Vehicle::processSet(), and signalSet().
bool MSVehicle::addTraciStop (MSLane *const lane, const SUMOReal startPos, const SUMOReal endPos, const SUMOTime duration, const SUMOTime until, const bool parking, const bool triggered, const bool containerTriggered, std::string & errorMsg)
schedule a new stop for the vehicle; each time a stop is reached, the vehicle will wait for the given duration before continuing on its route
Parameters
lane lane on wich to stop
startPos start position on the given lane at wich to stop
endPos end position on the given lane at wich to stop
duration waiting time duration
until time step at which the stop shall end
parking a flag indicating whether the traci stop is used for parking or not
triggered a flag indicating whether the traci stop is triggered or not
containerTriggered a flag indicating whether the traci stop is triggered by a container or not
Definition at line 3322 of file MSVehicle.cpp.
References addStop(), SUMOVehicleParameter::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, Named::getID(), SUMOVehicleParameter::Stop::index, SUMOVehicleParameter::Stop::lane, myLane, myStops, SUMOVehicleParameter::Stop::parking, POSITION_EPS, SUMOVehicleParameter::Stop::startPos, STOP_INDEX_FIT, SUMOVehicleParameter::Stop::triggered, SUMOVehicleParameter::Stop::until, and updateBestLanes().
Referenced by TraCIServerAPI_Vehicle::processSet(), and signalSet().
void MSBaseVehicle::calculateArrivalParams () protected inherited
(Re-)Calculates the arrival position and lane from the vehicle parameters
Definition at line 361 of file MSBaseVehicle.cpp.
References ARRIVAL_LANE_GIVEN, ARRIVAL_POS_GIVEN, ARRIVAL_POS_RANDOM, ARRIVAL_SPEED_GIVEN, SUMOVehicleParameter::arrivalLane, SUMOVehicleParameter::arrivalLaneProcedure, SUMOVehicleParameter::arrivalPos, SUMOVehicleParameter::arrivalPosProcedure, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, Named::getID(), MSBaseVehicle::getID(), MSEdge::getLanes(), MSRoute::getLastEdge(), MSVehicleType::getVehicleClass(), MAX2(), MIN2(), MSBaseVehicle::myArrivalLane, MSBaseVehicle::myArrivalPos, MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, MSBaseVehicle::myType, RandHelper::rand(), SUMOReal, toString(), and WRITE_WARNING.
Referenced by MSBaseVehicle::MSBaseVehicle(), replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), and MSBaseVehicle::setChosenSpeedFactor().
void MSVehicle::checkRewindLinkLanes (const SUMOReal lengthsInFront, DriveItemVector & lfLinks) const protected
Definition at line 2048 of file MSVehicle.cpp.
References ACCEL2SPEED, MSVehicle::DriveProcessItem::availableSpace, bla, MSCFModel::brakeGap(), DEBUG_COND, MSEdge::EDGEFUNCTION_INTERNAL, gDebugSelectedVehicle, getBackPositionOnLane(), MSLane::getBruttoVehLenSum(), getCarFollowModel(), MSLane::getEdge(), MSCFModel::getHeadwayTime(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getImpatience(), MSLink::getLane(), getLaneChangeModel(), MSLane::getLastAnyVehicle(), getLateralPositionOnLane(), MSVehicle::DriveProcessItem::getLeaveSpeed(), MSVehicleType::getLength(), MSLane::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSLink::getParallelLink(), MSEdge::getPurpose(), MSVehicle::Influencer::getRespectJunctionPriority(), MSAbstractLaneChangeModel::getShadowLane(), getSpaceTillLastStanding(), getSpeed(), MSLane::getVehicleNumber(), MSBaseVehicle::getVehicleType(), getWaitingTime(), MSGlobals::gUsingInternalLanes, MSVehicle::DriveProcessItem::hadVehicle, MSLink::hasFoes(), MSLink::havePriority(), MSLink::isCont(), isFrontOnLane(), MSAbstractLaneChangeModel::isOpposite(), MSEdge::isRoundabout(), MSLink::keepClear(), LINKSTATE_ALLWAY_STOP, MAX2(), MSVehicle::DriveProcessItem::myArrivalSpeed, MSVehicle::DriveProcessItem::myArrivalTime, myHaveToWaitOnNextLink, myInfluencer, myLane, MSVehicle::DriveProcessItem::myLink, MSVehicle::State::mySpeed, myState, MSLink::opened(), RandHelper::rand(), MSLink::setApproaching(), MSAbstractLaneChangeModel::setShadowApproachingInformation(), signalSet(), SIMTIME, SUMOReal, UNUSED_PARAMETER, and VEH_SIGNAL_BRAKELIGHT.
Referenced by planMove().
SUMOReal MSVehicle::computeAngle () const
compute the current vehicle angle
Definition at line 808 of file MSVehicle.cpp.
References Position::angleTo2D(), DEBUG_COND, DEG2RAD, MSLane::geometryPositionAtOffset(), getBackPosition(), MSBaseVehicle::getID(), getLaneChangeModel(), getPosition(), getPositionOnLane(), MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), MSAbstractLaneChangeModel::isChangingLanes(), isParking(), myLane, MSVehicle::State::myPos, MSVehicle::State::myPosLat, myState, PositionVector::rotationAtOffset(), SIMTIME, and SUMOReal.
Referenced by MSLaneChanger::continueChange(), enterLaneAtInsertion(), enterLaneAtLaneChange(), executeMove(), and getAngle().
bool MSVehicle::congested () const inline
Returns true if vehicle's speed is below 60km/h. This is only relevant on highways. Overtaking on the right is allowed then.
Definition at line 542 of file MSVehicle.h.
References activateReminders(), enterLaneAtInsertion(), enterLaneAtLaneChange(), enterLaneAtMove(), getLaneChangeModel(), leaveLane(), MSVehicle::State::mySpeed, myState, MSVehicle::State::pos(), MSVehicle::State::posLat(), setTentativeLaneAndPosition(), MSVehicle::State::speed(), and SUMOReal.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::checkStrategicChange(), MSAbstractLaneChangeModel::congested(), MSLCM_JE2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), and MSLCM_SL2015::informLeader().
virtual void MSVehicle::drawOutsideNetwork (bool) const inline protected virtual
register vehicle for drawing while outside the network
Reimplemented in GUIVehicle.
Definition at line 1372 of file MSVehicle.h.
Referenced by MSVehicle::Influencer::postProcessVTD().
void MSVehicle::enterLaneAtInsertion (MSLane * enteredLane, SUMOReal pos, SUMOReal speed, SUMOReal posLat, MSMoveReminder::Notification notification)
Update when the vehicle enters a new lane in the emit step.
Parameters
[in] enteredLane The lane the vehicle enters
[in] pos The position the vehicle was inserted into the lane
[in] speed The speed with which the vehicle was inserted into the lane
[in] posLat The lateral position the vehicle was inserted into the lane
[in] notification The cause of insertion (i.e. departure, teleport, parking)
Definition at line 2371 of file MSVehicle.cpp.
References activateReminders(), MSBaseVehicle::addReminder(), computeAngle(), getLaneChangeModel(), MSVehicleType::getLength(), MSLane::getLogicalPredecessorLane(), MSLane::getMoveReminders(), MSBaseVehicle::getVehicleType(), MSGlobals::gLaneChangeDuration, MSGlobals::gLateralResolution, Position::INVALID, M_PI, myAmOnNet, myAngle, MSVehicle::State::myBackPos, myCachedPosition, MSBaseVehicle::myDeparture, myFurtherLanes, myFurtherLanesPosLat, myLane, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSVehicle::State::mySpeed, myState, MSBaseVehicle::myType, myWaitingTime, MSBaseVehicle::NOT_YET_DEPARTED, MSMoveReminder::NOTIFICATION_TELEPORT, MSBaseVehicle::onDepart(), SUMOReal, and MSAbstractLaneChangeModel::updateShadowLane().
Referenced by congested(), and MSLane::incorporateVehicle().
void MSVehicle::enterLaneAtLaneChange (MSLane * enteredLane)
Update when the vehicle enters a new lane in the laneChange step.
Parameters
[in] enteredLane The lane the vehicle enters
Definition at line 2321 of file MSVehicle.cpp.
References activateReminders(), MSBaseVehicle::addReminder(), computeAngle(), DEBUG_COND, MSBaseVehicle::getEdge(), MSVehicleType::getLength(), MSLane::getLogicalPredecessorLane(), MSLane::getMoveReminders(), MSBaseVehicle::getVehicleType(), Position::INVALID, MSAbstractLaneChangeModel::isChangingLanes(), myAmOnNet, myAngle, myCachedPosition, myFurtherLanes, myFurtherLanesPosLat, myLane, myLaneChangeModel, MSVehicle::State::myPos, MSVehicle::State::myPosLat, myState, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSAbstractLaneChangeModel::setNoShadowPartialOccupator(), SIMTIME, SUMOReal, toString(), and updateBestLanes().
Referenced by congested(), and MSAbstractLaneChangeModel::primaryLaneChanged().
bool MSVehicle::enterLaneAtMove (MSLane * enteredLane, bool onTeleporting = false)
Update when the vehicle enters a new lane in the move step.
Parameters
[in] enteredLane The lane the vehicle enters
[in] onTeleporting Whether the lane was entered while being teleported
Returns
Whether the vehicle's route has ended (due to vaporization, or because the destination was reached)
Definition at line 2288 of file MSVehicle.cpp.
References activateReminders(), adaptLaneEntering2MoveReminder(), MSEdge::EDGEFUNCTION_INTERNAL, MSLane::getEdge(), MSEdge::getPurpose(), hasArrived(), Position::INVALID, myAmOnNet, myCachedPosition, MSBaseVehicle::myCurrEdge, myLane, myLastBestLanesEdge, MSVehicle::State::myPos, myState, MSMoveReminder::NOTIFICATION_JUNCTION, and MSMoveReminder::NOTIFICATION_TELEPORT.
Referenced by MSVehicleTransfer::add(), MSVehicleTransfer::checkInsertions(), congested(), executeMove(), and TraCIServerAPI_Vehicle::processSet().
SUMOReal MSVehicle::estimateLeaveSpeed (const MSLink *const link, const SUMOReal vLinkPass) const inline protected
estimate leaving speed when accelerating across a link
Definition at line 1497 of file MSVehicle.h.
References estimateSpeedAfterDistance(), MSVehicleType::getCarFollowModel(), MSLink::getLength(), MSCFModel::getMaxAccel(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSLink::getViaLaneOrLane(), and MIN2().
Referenced by planMoveInternal().
SUMOReal MSVehicle::estimateSpeedAfterDistance (const SUMOReal dist, const SUMOReal v, const SUMOReal accel) const inline protected
Definition at line 1511 of file MSVehicle.h.
References adaptToLeader(), adaptToLeaders(), getBackLane(), getBackPosition(), MSBaseVehicle::getMaxSpeed(), MSBaseVehicle::getVehicleType(), MIN2(), and SUMOReal.
Referenced by estimateLeaveSpeed(), and planMoveInternal().
bool MSVehicle::executeMove ()
Executes planned vehicle movements with regards to right-of-way.
This method goes through all DriveProcessItems in myLFLinkLanes in order to find a speed that is safe for all upcoming links.
Using this speed the position is updated and the vehicle is moved to the next lane (myLane is updated) if the end of the current lane is reached (this may happen multiple times in this method)
The vehicle also sets the lanes it is in-lapping into and informs them about it.
Returns
Whether the vehicle has moved to the next edge
Definition at line 1559 of file MSVehicle.cpp.
References ACCEL2SPEED, bla, MSCFModel::brakeGap(), MSAbstractLaneChangeModel::changedToOpposite(), computeAngle(), DEBUG_COND, DELTA_T, DIST2SPEED, MSRoute::end(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), enterLaneAtMove(), gDebugSelectedVehicle, getBackLane(), MSVehicleType::getCarFollowModel(), getCarFollowModel(), MSLink::getDirection(), MSLane::getEdge(), MSVehicle::Influencer::getEmergencyBrakeRedLight(), MSCFModel::getHeadwayTime(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getImpatience(), MSNet::getInstance(), getLaneChangeModel(), getLateralPositionOnLane(), MSVehicleType::getLength(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSLane::getOpposite(), MSLane::getOppositePos(), MSLink::getParallelLink(), getPositionOnLane(), MSVehicle::Influencer::getRespectJunctionPriority(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), getSpeed(), MSLink::getState(), MSVehicleType::getVehicleClass(), MSNet::getVehicleControl(), MSBaseVehicle::getVehicleType(), MSLink::getViaLaneOrLane(), getWaitingTime(), MSLane::getWidth(), MSGlobals::gUsingInternalLanes, hasArrived(), MSVehicle::Influencer::implicitDeltaPosVTD(), MSVehicle::Influencer::implicitSpeedVTD(), MSVehicle::Influencer::influenceSpeed(), Position::INVALID, isRemoteControlled(), MSEdge::isRoundabout(), isStopped(), MSEdge::isVaporizing(), MSVehicle::Influencer::isVTDControlled(), leaveLane(), LINKDIR_LEFT, LINKDIR_RIGHT, LINKSTATE_EQUAL, LINKSTATE_TL_RED, LINKSTATE_TL_YELLOW_MAJOR, LINKSTATE_TL_YELLOW_MINOR, LINKSTATE_ZIPPER, max, MAX2(), MSCFModel::maxNextSpeed(), MIN2(), myAcceleration, myAngle, MSVehicle::State::myBackPos, myCachedPosition, MSBaseVehicle::myCurrEdge, myFurtherLanes, myFurtherLanesPosLat, myHaveToWaitOnNextLink, myInfluencer, myLane, myLFLinkLanes, MSVehicle::State::myPos, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, myState, MSBaseVehicle::myType, myWaitingTime, myWaitingTimeCollector, MSMoveReminder::NOTIFICATION_JUNCTION, MSMoveReminder::NOTIFICATION_VAPORIZED, NUMERICAL_EPS, MSLink::opened(), MSLink::passedJunction(), MSVehicle::WaitingTimeCollector::passTime(), POSITION_EPS, MSAbstractLaneChangeModel::prepareStep(), MSVehicleControl::registerEmergencyStop(), setBlinkerInformation(), setEmergencyBlueLight(), SIMTIME, SPEED2ACCEL, SPEED2DIST, SUMO_const_haltingSpeed, SUMOReal, SVC_EMERGENCY, switchOffSignal(), switchOnSignal(), time2string(), toString(), updateBestLanes(), updateFurtherLanes(), MSAbstractLaneChangeModel::updateShadowLane(), VEH_SIGNAL_BRAKELIGHT, workOnMoveReminders(), and WRITE_WARNING.
Referenced by MSLane::executeMovements().
void MSVehicle::fixPosition ()
repair errors in vehicle position after changing between internal edges
Definition at line 2854 of file MSVehicle.cpp.
References getLaneChangeModel(), MSGlobals::gLaneChangeDuration, MSVehicle::State::myPosLat, myState, and SUMOReal.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver().
SUMOReal MSVehicle::getAcceleration () const inline virtual
Returns the vehicle's acceleration in m/s.
Returns
The acceleration
Reimplemented from MSBaseVehicle.
Definition at line 418 of file MSVehicle.h.
References getPosition(), getSlope(), myAcceleration, and SUMOReal.
Referenced by GUIVehicle::getColorValue(), MSE2Collector::getEstimatedCurrentVehicleNumber(), and MSBatteryExport::write().
SUMOReal MSVehicle::getAccumulatedWaitingSeconds () const inline
Returns the number of seconds waited (speed was lesser than 0.1m/s) within the last millisecs.
Returns
The time the vehicle was standing within the last t millisecs
Definition at line 512 of file MSVehicle.h.
References getAccumulatedWaitingTime(), and STEPS2TIME.
Referenced by GUIVehicle::getColorValue(), and GUIVehicle::getParameterWindow().
SUMOTime MSVehicle::getAccumulatedWaitingTime (SUMOTime t = MSGlobals::gWaitingTimeMemory) const inline
Returns the SUMOTime waited (speed was lesser than 0.1m/s) within the last t millisecs.
Parameters
[in] t specifies the length of the interval over which the cumulated waiting time is to be summed up (defaults to and must not exceed MSGlobals::gWaitingTimeMemory)
Returns
The time the vehicle was standing within the last t millisecs
Definition at line 491 of file MSVehicle.h.
References MSVehicle::WaitingTimeCollector::cumulatedWaitingTime(), and myWaitingTimeCollector.
Referenced by getAccumulatedWaitingSeconds().
SUMOReal MSVehicle::getAngle () const inline virtual
Returns the vehicle's direction in degrees.
Returns
The vehicle's current angle
Implements SUMOVehicle.
Definition at line 520 of file MSVehicle.h.
References computeAngle(), myAngle, setAngle(), and SUMOReal.
Referenced by GUIVehicle::getAngle(), MSTransportable::Stage_Driving::getAngle(), and TraCIServerAPI_Vehicle::processGet().
virtual SUMOReal MSBaseVehicle::getArrivalPos () const inline virtual inherited
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
Returns
This vehicle's real arrivalPos
Implements SUMOVehicle.
Definition at line 250 of file MSBaseVehicle.h.
References MSBaseVehicle::myArrivalPos.
const MSLane * MSVehicle::getBackLane () const protected
Definition at line 1901 of file MSVehicle.cpp.
References myFurtherLanes, myLane, and SUMOReal.
Referenced by estimateSpeedAfterDistance(), and executeMove().
const Position MSVehicle::getBackPosition () const protected
Definition at line 836 of file MSVehicle.cpp.
References DEBUG_COND, MSLane::geometryPositionAtOffset(), getBackPositionOnLane(), Named::getID(), MSBaseVehicle::getID(), getLaneChangeModel(), MSVehicleType::getLength(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::isChangingLanes(), myFurtherLanes, myFurtherLanesPosLat, myLane, MSVehicle::State::myPos, MSVehicle::State::myPosLat, myState, MSBaseVehicle::myType, SUMOReal, and toString().
Referenced by computeAngle(), estimateSpeedAfterDistance(), getBoundingBox(), and getBoundingPoly().
SUMOReal MSVehicle::getBackPositionOnLane (const MSLane * lane) const virtual
Get the vehicle's position relative to the given lane.
Returns
The back position of the vehicle (in m from the given lane's begin)
Implements SUMOVehicle.
Definition at line 1962 of file MSVehicle.cpp.
References MSBaseVehicle::getID(), Named::getIDSecure(), getLaneChangeModel(), MSVehicleType::getLength(), MSAbstractLaneChangeModel::getShadowFurtherLanes(), MSVehicle::State::myBackPos, myFurtherLanes, myLane, MSVehicle::State::myPos, myState, MSBaseVehicle::myType, and SUMOReal.
Referenced by adaptToLeaders(), checkRewindLinkLanes(), MSLane::detectCollisionBetween(), MSE2Collector::detectorUpdate(), MSLane::freeInsertion(), MSLane::getCriticalLeader(), MSLane::getLeader(), getLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getOppositeFollower(), MSLaneChanger::getRealLeader(), MSLane::isInsertionSuccess(), MSLink::maybeOccupied(), MSLane::vehicle_position_sorter::operator()(), MSLane::vehicle_natural_position_sorter::operator()(), MSLane::safeInsertionSpeed(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), and MSLink::writeApproaching().
SUMOReal MSVehicle::getBackPositionOnLane () const inline
Get the vehicle's position relative to its current lane.
Returns
The back position of the vehicle (in m from the current lane's begin)
Definition at line 367 of file MSVehicle.h.
References myLane.
Referenced by getBackPosition(), and getPositionOnLane().
int MSVehicle::getBestLaneOffset () const
returns the current offset from the best lane
Definition at line 2836 of file MSVehicle.cpp.
References myBestLanes.
Referenced by MSLCM_JE2013::changed(), MSLCM_SL2015::changed(), MSLCM_LC2013::changed(), and GUIVehicle::getColorValue().
const std::vector< MSVehicle::LaneQ > & MSVehicle::getBestLanes () const
Returns the description of best lanes to use in order to continue the route.
Returns
The best lanes structure holding matching the current vehicle position and state ahead
Definition at line 2474 of file MSVehicle.cpp.
References myBestLanes.
Referenced by MSLane::appropriate(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLaneChangerSublane::checkChangeHelper(), MSEdge::getDepartLane(), TraCIServerAPI_Vehicle::processGet(), and MSLCM_SL2015::updateExpectedSublaneSpeeds().
const std::vector< MSLane * > & MSVehicle::getBestLanesContinuation () const
Returns the subpart of best lanes that describes the vehicle's current lane and their successors.
Returns
The best lane information for the vehicle's current lane
Todo:
Describe better
Definition at line 2808 of file MSVehicle.cpp.
References myBestLanes, and myEmptyLaneVector.
Referenced by MSLane::appropriate(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), GUIVehicle::drawRouteHelper(), MSLane::executeMovements(), MSLane::getCriticalLeader(), getLeader(), MSLaneChangerSublane::getLeaders(), MSLane::getOppositeLeader(), MSLaneChanger::getRealLeader(), MSLane::isInsertionSuccess(), planMoveInternal(), TraCIServerAPI_Vehicle::processGet(), setBlinkerInformation(), unsafeLinkAhead(), and updateBestLanes().
const std::vector< MSLane * > & MSVehicle::getBestLanesContinuation (const MSLane *const l) const
Returns the subpart of best lanes that describes the given lane and their successors.
Returns
The best lane information for the given lane
Todo:
Describe better
Definition at line 2817 of file MSVehicle.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSLane::getEdge(), MSLane::getLinkCont(), MSEdge::getPurpose(), myBestLanes, and myEmptyLaneVector.
PositionVector MSVehicle::getBoundingBox () const
get bounding rectangle
Definition at line 3272 of file MSVehicle.cpp.
References PositionVector::append(), getBackPosition(), getPosition(), MSVehicleType::getWidth(), PositionVector::move2side(), MSBaseVehicle::myType, POSITION_EPS, and PositionVector::reverse().
Referenced by MSLane::detectCollisions(), GUIVehicle::drawAction_drawPersonsAndContainers(), getBoundingPoly(), and signalSet().
PositionVector MSVehicle::getBoundingPoly () const
get bounding polygon
Definition at line 3285 of file MSVehicle.cpp.
References getBackPosition(), getBoundingBox(), MSVehicleType::getGuiShape(), getPosition(), MSVehicleType::getWidth(), PositionVector::move2side(), MSBaseVehicle::myType, PositionVector::scaleRelative(), SVS_PASSENGER, SVS_PASSENGER_HATCHBACK, SVS_PASSENGER_SEDAN, SVS_PASSENGER_VAN, and SVS_PASSENGER_WAGON.
Referenced by MSLane::detectCollisions(), GUIVehicle::drawAction_drawPersonsAndContainers(), and signalSet().
const MSCFModel& MSVehicle::getCarFollowModel () const inline
Returns the vehicle's car following model definition.
This is simply a wrapper around the vehicle type's car-following model retrieval for a shorter access.
Returns
The vehicle's car following model definition
Definition at line 700 of file MSVehicle.h.
References MSVehicleType::getCarFollowModel(), and MSBaseVehicle::myType.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSCriticalFollowerDistanceInfo::addFollower(), addStop(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), MSLane::checkFailure(), checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::computeOvertakingTime(), MSLink::couldBrakeForLeader(), executeMove(), MSLane::freeInsertion(), MSLane::getCriticalLeader(), MSLane::getFollower(), MSLane::getLeader(), getLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getMissingRearGap(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), getRerouteOrigin(), getSafeFollowSpeed(), GUIVehicle::getTypeParameterWindow(), MSLink::getZipperSpeed(), MSLCM_DK2008::informBlocker(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSLink::maybeOccupied(), MSLCM_DK2008::patchSpeed(), planMoveInternal(), processNextStop(), MSLane::safeInsertionSpeed(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), GUIVehicle::selectBlockingFoes(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), unsafeLinkAhead(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
MSCFModel::VehicleVariables* MSVehicle::getCarFollowVariables () const inline
Returns the vehicle's car following model variables.
Returns
The vehicle's car following model variables
Definition at line 709 of file MSVehicle.h.
References myCFVariables.
Referenced by MSCFModel_Kerner::_v(), MSCFModel_Wiedemann::_v(), MSCFModel_IDM::_v(), MSCFModel_SmartSK::_vsafe(), MSCFModel_SmartSK::followSpeed(), MSCFModel_PWag2009::followSpeed(), MSCFModel_Kerner::moveHelper(), MSCFModel_PWag2009::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_Wiedemann::moveHelper(), MSCFModel_IDM::moveHelper(), MSCFModel_SmartSK::stopSpeed(), and MSCFModel_SmartSK::updateMyHeadway().
SUMOReal MSVehicle::getCenterOnEdge (const MSLane * lane = 0) const
Get the vehicle's lateral position on the edge of the given lane (or its current edge if lane == 0)
Returns
The lateral position of the vehicle (in m distance between center of vehicle and ride side of edge
Definition at line 3125 of file MSVehicle.cpp.
References DEBUG_COND, MSLane::getCenterOnEdge(), MSLane::getEdge(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), getLaneChangeModel(), MSLane::getRightSideOnEdge(), MSAbstractLaneChangeModel::getShadowFurtherLanes(), MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat(), MSAbstractLaneChangeModel::getShadowLane(), MSLane::getWidth(), myFurtherLanes, myFurtherLanesPosLat, myLane, MSVehicle::State::myPosLat, myState, and SUMOReal.
Referenced by MSLCM_SL2015::checkBlocking(), MSLane::detectCollisionBetween(), getLateralPositionOnLane(), getRightSideOnEdge(), and MSLCM_SL2015::keepLatGap().
SUMOReal MSBaseVehicle::getChosenSpeedFactor () const inline virtual inherited
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
Returns
Speed limit factor
Implements SUMOVehicle.
Definition at line 340 of file MSBaseVehicle.h.
References MSBaseVehicle::myChosenSpeedFactor.
Referenced by GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), and TraCIServerAPI_Vehicle::processGet().
SUMOReal MSVehicle::getCO2Emissions () const
Returns CO2 emission of the current state.
Returns
The current CO2 emission
Definition at line 2917 of file MSVehicle.cpp.
References PollutantsInterface::CO2, PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), getSlope(), myAcceleration, myState, MSBaseVehicle::myType, MSVehicle::State::speed(), and SUMOReal.
Referenced by GUIVehicle::getColorValue(), GUIVehicle::getParameterWindow(), nextStopDist(), and TraCIServerAPI_Vehicle::processGet().
SUMOReal MSVehicle::getCOEmissions () const
Returns CO emission of the current state.
Returns
The current CO emission
Definition at line 2923 of file MSVehicle.cpp.
References PollutantsInterface::CO, PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), getSlope(), myAcceleration, myState, MSBaseVehicle::myType, MSVehicle::State::speed(), and SUMOReal.
Referenced by GUIVehicle::getColorValue(), GUIVehicle::getParameterWindow(), nextStopDist(), and TraCIServerAPI_Vehicle::processGet().
int MSVehicle::getContainerNumber () const
Returns the number of containers.
Returns
The number of contaiers on-board
Definition at line 3033 of file MSVehicle.cpp.
References SUMOVehicleParameter::containerNumber, myContainerDevice, MSBaseVehicle::myParameter, and MSDevice_Transportable::size().
Referenced by GUIVehicle::getParameterWindow(), MSTransportableControl::loadAnyWaiting(), nextStopDist(), processNextStop(), and MSXMLRawOut::writeVehicle().
const std::vector< MSTransportable * > & MSVehicle::getContainers () const
retrieve riding containers
Definition at line 3017 of file MSVehicle.cpp.
References MSDevice_Transportable::getTransportables(), myContainerDevice, and myEmptyTransportableVector.
Referenced by nextStopDist(), MSFCDExport::write(), and MSXMLRawOut::writeVehicle().
const MSRouteIterator& MSBaseVehicle::getCurrentRouteEdge () const inline virtual inherited
Returns an iterator pointing to the current edge in this vehicles route.
Returns
The current route pointer
Implements SUMOVehicle.
Definition at line 174 of file MSBaseVehicle.h.
References MSBaseVehicle::getAcceleration(), MSBaseVehicle::getSlope(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::onDepart(), MSBaseVehicle::replaceRouteEdges(), MSBaseVehicle::reroute(), and SUMOReal.
Referenced by TraCIServerAPI_Vehicle::vtdMap_matchingRoutePosition().
SUMOTime MSBaseVehicle::getDepartDelay () const inline virtual inherited
Returns the depart delay.
Implements SUMOVehicle.
Definition at line 234 of file MSBaseVehicle.h.
References SUMOVehicleParameter::depart, MSBaseVehicle::getDeparture(), and MSBaseVehicle::getParameter().
Referenced by GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIMEVehicle::getParameterWindow(), and GUIVehicle::getParameterWindow().
SUMOReal MSBaseVehicle::getDepartPos () const inline virtual inherited
Returns this vehicle's real departure position.
Returns
This vehicle's real departure position
Implements SUMOVehicle.
Definition at line 242 of file MSBaseVehicle.h.
References MSBaseVehicle::myDepartPos.
Referenced by TraCIServerAPI_Vehicle::processGet().
SUMOTime MSBaseVehicle::getDeparture () const inline virtual inherited
Returns this vehicle's real departure time.
Returns
This vehicle's real departure time
Implements SUMOVehicle.
Definition at line 229 of file MSBaseVehicle.h.
References MSBaseVehicle::myDeparture.
Referenced by MSBaseVehicle::getDepartDelay().
MSDevice * MSBaseVehicle::getDevice (const std::type_info & type) const virtual inherited
Returns a device of the given type if it exists or 0.
Implements SUMOVehicle.
Definition at line 409 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDevices.
Referenced by GUIBaseVehicle::drawOnPos(), MSBaseVehicle::setChosenSpeedFactor(), and MSBatteryExport::write().
const std::vector<MSDevice*>& MSBaseVehicle::getDevices () const inline virtual inherited
Returns this vehicle's devices.
Returns
This vehicle's devices
Implements SUMOVehicle.
Definition at line 283 of file MSBaseVehicle.h.
References MSBaseVehicle::activateReminders(), MSBaseVehicle::addContainer(), MSBaseVehicle::addPerson(), MSBaseVehicle::addReminder(), MSBaseVehicle::hasValidRoute(), MSBaseVehicle::myDevices, and MSBaseVehicle::removeReminder().
SUMOReal MSVehicle::getDistanceToPosition (SUMOReal destPos, const MSEdge * destEdge) const
Compute distance that will be covered, if the vehicle moves to a given position on its route, starting at its current position.
Parameters
destPos position on the destination edge that shall be reached
destEdge destination edge that shall be reached
Returns
distance from the vehicles current position to the destination position, or a near infinite real value if the destination position is not contained within the vehicles route or the vehicle is not active
Definition at line 2862 of file MSVehicle.cpp.
References MSRoute::getDistanceBetween(), MSLane::getEdge(), MSLane::getLength(), getPositionOnLane(), isOnRoad(), max, MSBaseVehicle::myCurrEdge, myLane, MSBaseVehicle::myRoute, and SUMOReal.
Referenced by MSVehicle::Influencer::implicitDeltaPosVTD(), MSVehicle::Influencer::implicitSpeedVTD(), and nextStopDist().
const MSEdge * MSBaseVehicle::getEdge () const virtual inherited
Returns the edge the vehicle is currently at.
Returns
The current edge in the vehicle's route
Implements SUMOVehicle.
Definition at line 133 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myCurrEdge.
Referenced by MSVehicleTransfer::add(), MELoop::changeSegment(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), TraCIServerAPI_Vehicle::commandDistanceRequest(), enterLaneAtLaneChange(), METriggeredCalibrator::execute(), MEVehicle::getAngle(), GUIMEVehicle::getParameterWindow(), MEVehicle::getPosition(), MEVehicle::getSlope(), MSBaseVehicle::getVClass(), TraCIServerAPI_Vehicle::processSet(), MESegment::receive(), MELoop::teleportVehicle(), and TraCIServerAPI_Vehicle::vtdMap().
SUMOReal MSVehicle::getElectricityConsumption () const
Returns electricity consumption of the current state.
Returns
The current electricity consumption
Definition at line 2953 of file MSVehicle.cpp.
References PollutantsInterface::compute(), PollutantsInterface::ELEC, MSVehicleType::getEmissionClass(), getSlope(), myAcceleration, myState, MSBaseVehicle::myType, MSVehicle::State::speed(), and SUMOReal.
Referenced by GUIVehicle::getColorValue(), GUIVehicle::getParameterWindow(), nextStopDist(), and TraCIServerAPI_Vehicle::processGet().
SUMOReal MSVehicle::getFuelConsumption () const
Returns fuel consumption of the current state.
Returns
The current fuel consumption
Definition at line 2947 of file MSVehicle.cpp.
References PollutantsInterface::compute(), PollutantsInterface::FUEL, MSVehicleType::getEmissionClass(), getSlope(), myAcceleration, myState, MSBaseVehicle::myType, MSVehicle::State::speed(), and SUMOReal.
Referenced by GUIVehicle::getColorValue(), GUIVehicle::getParameterWindow(), nextStopDist(), and TraCIServerAPI_Vehicle::processGet().
const std::vector<MSLane*>& MSVehicle::getFurtherLanes () const inline
Definition at line 600 of file MSVehicle.h.
References myFurtherLanes.
Referenced by MSAbstractLaneChangeModel::updateShadowLane().
const std::vector<SUMOReal>& MSVehicle::getFurtherLanesPosLat () const inline
Definition at line 604 of file MSVehicle.h.
References myFurtherLanesPosLat.
Referenced by MSAbstractLaneChangeModel::updateShadowLane().
SUMOReal MSVehicle::getHarmonoise_NoiseEmissions () const
Returns noise emissions of the current state.
Returns
The noise produced
Definition at line 2959 of file MSVehicle.cpp.
References HelpersHarmonoise::computeNoise(), MSVehicleType::getEmissionClass(), myAcceleration, myState, MSBaseVehicle::myType, and MSVehicle::State::speed().
Referenced by GUIVehicle::getColorValue(), GUIVehicle::getParameterWindow(), nextStopDist(), and TraCIServerAPI_Vehicle::processGet().
SUMOReal MSVehicle::getHCEmissions () const
Returns HC emission of the current state.
Returns
The current HC emission
Definition at line 2929 of file MSVehicle.cpp.
References PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), getSlope(), PollutantsInterface::HC, myAcceleration, myState, MSBaseVehicle::myType, MSVehicle::State::speed(), and SUMOReal.
Referenced by GUIVehicle::getColorValue(), GUIVehicle::getParameterWindow(), nextStopDist(), and TraCIServerAPI_Vehicle::processGet().
const std::string & MSBaseVehicle::getID () const virtual inherited
Returns the name of the vehicle.
Implements SUMOVehicle.
Definition at line 105 of file MSBaseVehicle.cpp.
References SUMOVehicleParameter::id, and MSBaseVehicle::myParameter.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), adaptToLeader(), adaptToLeaders(), MSVehicleTransfer::add(), MSBaseVehicle::addStops(), addTraciBusOrContainerStop(), MSBaseVehicle::calculateArrivalParams(), MSLaneChangerSublane::change(), MSLaneChanger::change(), MSLCM_SL2015::changed(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), MSLane::checkFailure(), MSVehicleTransfer::checkInsertions(), checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSAbstractLaneChangeModel::cleanupShadowLane(), computeAngle(), MSLaneChanger::continueChange(), MSLCM_SL2015::decideDirection(), GUIVehicle::drawOutsideNetwork(), MSCalibrator::execute(), executeMove(), MSLane::executeMovements(), getBackPosition(), getBackPositionOnLane(), getCenterOnEdge(), MSE2Collector::getCurrentVehicleIDs(), MSE2Collector::getEstimateQueueLength(), MSLane::getFirstVehicleInformation(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), MSLane::getLastVehicleInformation(), getLatOffset(), MSLane::getLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), MSLane::getPartialBehind(), MSAbstractLaneChangeModel::getShadowLane(), MSLane::handleCollisionBetween(), MSLCM_SL2015::inform(), MSLCM_JE2013::inform(), MSLCM_LC2013::inform(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MESegment::initialise(), MSPedestrianPushButton::isActiveForEdge(), MSLane::isInsertionSuccess(), leaveLane(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSLCM_JE2013::MSLCM_JE2013(), MSLCM_LC2013::MSLCM_LC2013(), MSCalibrator::VehicleRemover::notifyEnter(), MSLCM_DK2008::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSLCM_LC2013::patchSpeed(), planMove(), planMoveInternal(), MSAbstractLaneChangeModel::primaryLaneChanged(), processNextStop(), TraCIServerAPI_Vehicle::processSet(), MSBaseVehicle::replaceRouteEdges(), MSBaseVehicle::reroute(), MSLane::resetPartialOccupation(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSCalibrator::scheduleRemoval(), MSLane::setPartialOccupation(), TraCIServer::setVTDControlled(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), updateBestLanes(), MSLCM_SL2015::updateGaps(), MSAbstractLaneChangeModel::updateShadowLane(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), MSLink::writeApproaching(), and MSXMLRawOut::writeVehicle().
SUMOReal MSBaseVehicle::getImpatience () const virtual inherited
Returns this vehicles impatience.
Implements SUMOVehicle.
Definition at line 400 of file MSBaseVehicle.cpp.
References MSBaseVehicle::getVehicleType(), SUMOVehicle::getWaitingTime(), MSGlobals::gTimeToGridlock, MAX2(), MIN2(), and SUMOReal.
Referenced by checkRewindLinkLanes(), executeMove(), MSLane::getCriticalLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSBaseVehicle::getNumberReroutes(), GUIVehicle::getParameterWindow(), MSLane::isInsertionSuccess(), MESegment::isOpen(), and GUIVehicle::selectBlockingFoes().
MSVehicle::Influencer & MSVehicle::getInfluencer ()
Returns the velocity/lane influencer.
If no influencer was existing before, one is built, first
Returns
Reference to this vehicle's speed influencer
Definition at line 3448 of file MSVehicle.cpp.
References myInfluencer.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLane::detectCollisionBetween(), MSLane::executeMovements(), MSLane::handleCollisionBetween(), influenceChangeDecision(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), and TraCIServer::setVTDControlled().
const MSVehicle::Influencer * MSVehicle::getInfluencer () const
Definition at line 3457 of file MSVehicle.cpp.
References myInfluencer, and SUMOReal.
MSLane* MSVehicle::getLane () const inline virtual
Returns the lane the vehicle is on.
Returns
The vehicle's current lane
Implements SUMOVehicle.
Definition at line 447 of file MSVehicle.h.
References myLane.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), adaptToLeaders(), MSVehicleTransfer::add(), MSLaneChangerSublane::change(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlocking(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), MSVehicleTransfer::checkInsertions(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::computeOvertakingTime(), MSAbstractLaneChangeModel::congested(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSE2Collector::detectorUpdate(), MSVTypeProbe::execute(), MSLane::executeMovements(), MSCFModel_IDM::followSpeed(), GUIVehicle::getColorValue(), MSLane::getFollowersOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSAbstractLaneChangeModel::getShadowDirection(), MSVTKExport::getSpeed(), MSLink::getZipperSpeed(), MSLane::integrateNewVehicle(), MSCFModel_IDM::interactionGap(), MSCFModel::interactionGap(), MSJunction::isLeader(), MSLCM_SL2015::keepLatGap(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel::moveHelper(), MSCFModel_IDM::moveHelper(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSLCM_DK2008::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_LC2013::patchSpeed(), planMoveInternal(), MSVehicle::Influencer::postProcessVTD(), MSLCM_SL2015::prepareStep(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), MSVehicleTransfer::remove(), MSCalibrator::removePending(), MSLane::removeVehicle(), setBlinkerInformation(), MSLaneChangerSublane::startChangeSublane(), MSCFModel_IDM::stopSpeed(), MSLaneChangerSublane::updateChanger(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSAbstractLaneChangeModel::updateShadowLane(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSEmissionExport::write(), MSBatteryExport::write(), MSFCDExport::write(), MSQueueExport::writeLane(), and MSFullExport::writeVehicles().
MSAbstractLaneChangeModel & MSVehicle::getLaneChangeModel ()
Definition at line 2462 of file MSVehicle.cpp.
References myLaneChangeModel.
Referenced by MSVehicleTransfer::add(), MSLaneChangerSublane::change(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), checkRewindLinkLanes(), computeAngle(), congested(), MSLaneChanger::continueChange(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), enterLaneAtInsertion(), executeMove(), fixPosition(), getBackPosition(), getBackPositionOnLane(), getCenterOnEdge(), GUIVehicle::getLastLaneChangeOffset(), getLatOffset(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), GUIVehicle::getParameterWindow(), getPosition(), MSAbstractLaneChangeModel::MSLCMessager::informLeader(), MSAbstractLaneChangeModel::MSLCMessager::informNeighFollower(), MSAbstractLaneChangeModel::MSLCMessager::informNeighLeader(), isFrontOnLane(), MSCFModel_Daniel1::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel::moveHelper(), planMove(), planMoveInternal(), MSLaneChanger::registerUnchanged(), removeApproachingInformation(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), GUIVehicle::selectBlockingFoes(), setBlinkerInformation(), MSLaneChanger::startChange(), MSLaneChangerSublane::startChangeSublane(), updateBestLanes(), and MSLaneChangerSublane::updateChanger().
const MSAbstractLaneChangeModel & MSVehicle::getLaneChangeModel () const
Definition at line 2468 of file MSVehicle.cpp.
References myLaneChangeModel.
int MSVehicle::getLaneIndex () const
Definition at line 3096 of file MSVehicle.cpp.
References MSLane::getEdge(), MSEdge::getLanes(), and myLane.
Referenced by MSLane::appropriate(), influenceChangeDecision(), and nextStopDist().
SUMOReal MSVehicle::getLateralOverlap () const
return the amount by which the vehicle extends laterally outside it's primary lane
Definition at line 3200 of file MSVehicle.cpp.
References getLateralPositionOnLane(), MSBaseVehicle::getVehicleType(), MSLane::getWidth(), and myLane.
Referenced by getLateralPositionOnLane(), MSAbstractLaneChangeModel::getShadowLane(), and MSAbstractLaneChangeModel::updateShadowLane().
SUMOReal MSVehicle::getLateralPositionOnLane () const inline virtual
Get the vehicle's lateral position on the lane.
Returns
The lateral position of the vehicle (in m relative to the centerline of the lane)
Reimplemented from MSBaseVehicle.
Definition at line 375 of file MSVehicle.h.
References getCenterOnEdge(), getLateralOverlap(), getLatOffset(), getRightSideOnEdge(), getRightSideOnLane(), MSVehicle::State::myPosLat, myState, and SUMOReal.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSVehicleTransfer::checkInsertions(), checkRewindLinkLanes(), MSLaneChanger::continueChange(), executeMove(), MSLane::getCriticalLeader(), getLateralOverlap(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), GUIVehicle::getParameterWindow(), getPosition(), MSAbstractLaneChangeModel::getShadowLane(), MSLeaderInfo::getSubLanes(), MSLCM_SL2015::keepLatGap(), MSLane::loadState(), MSLane::vehicle_natural_position_sorter::operator()(), planMove(), GUIVehicle::selectBlockingFoes(), MSLaneChangerSublane::startChangeSublane(), MSAbstractLaneChangeModel::updateShadowLane(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), and MSXMLRawOut::writeVehicle().
SUMOReal MSVehicle::getLatOffset (const MSLane * lane) const
Get the offset that that must be added to interpret myState.myPosLat for the given lane.
Definition at line 3157 of file MSVehicle.cpp.
References DEBUG_COND, MSLane::getEdge(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), getLaneChangeModel(), MSLane::getRightSideOnEdge(), MSAbstractLaneChangeModel::getShadowFurtherLanes(), MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat(), myFurtherLanes, myFurtherLanesPosLat, myLane, MSVehicle::State::myPosLat, myState, SIMTIME, SUMOReal, and toString().
Referenced by MSLane::getFirstVehicleInformation(), MSLane::getFollowersOnConsecutive(), MSLane::getLastVehicleInformation(), and getLateralPositionOnLane().
std::pair< const MSVehicle *const, SUMOReal > MSVehicle::getLeader (SUMOReal dist = 0) const
Returns the leader of the vehicle looking for a fixed distance.
If the distance is not given it is calculated from the brake gap. The gap returned does not include the minGap.
Parameters
dist up to which distance to look for a leader
Returns
The leading vehicle together with the gap; (0, -1) if no leader was found.
Definition at line 2879 of file MSVehicle.cpp.
References MSCFModel::brakeGap(), getBackPositionOnLane(), getBestLanesContinuation(), getCarFollowModel(), MSLane::getLeaderOnConsecutive(), MSLane::getLength(), MSVehicleType::getMinGap(), getPositionOnLane(), getSpeed(), MSLane::getVehiclesSecure(), MSBaseVehicle::getVehicleType(), myLane, MSLane::releaseVehicles(), and SUMOReal.
Referenced by getTimeGap(), nextStopDist(), and TraCIServerAPI_Vehicle::processGet().
SUMOReal MSBaseVehicle::getMaxSpeed () const virtual inherited
Returns the maximum speed.
Returns
The vehicle's maximum speed
Implements SUMOVehicle.
Definition at line 117 of file MSBaseVehicle.cpp.
References MSVehicleType::getMaxSpeed(), and MSBaseVehicle::myType.
Referenced by MSCFModel_Wiedemann::_v(), MSVehicleTransfer::checkInsertions(), estimateSpeedAfterDistance(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), MSBaseVehicle::getVClass(), MSVehicle::Influencer::implicitDeltaPosVTD(), and MSVehicle::Influencer::implicitSpeedVTD().
MSVehicle::Stop & MSVehicle::getNextStop ()
returns the next imminent stop in the stop queue
Returns
the upcoming stop
Definition at line 3442 of file MSVehicle.cpp.
References myStops.
Referenced by TraCIServerAPI_Vehicle::processGet(), and signalSet().
SUMOReal MSVehicle::getNOxEmissions () const
Returns NOx emission of the current state.
Returns
The current NOx emission
Definition at line 2935 of file MSVehicle.cpp.
References PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), getSlope(), myAcceleration, myState, MSBaseVehicle::myType, PollutantsInterface::NO_X, MSVehicle::State::speed(), and SUMOReal.
Referenced by GUIVehicle::getColorValue(), GUIVehicle::getParameterWindow(), nextStopDist(), and TraCIServerAPI_Vehicle::processGet().
int MSBaseVehicle::getNumberReroutes () const inline virtual inherited
Returns the number of new routes this vehicle got.
Returns
the number of new routes this vehicle got
Implements SUMOVehicle.
Definition at line 272 of file MSBaseVehicle.h.
References MSBaseVehicle::getImpatience(), MSBaseVehicle::myNumberReroutes, and SUMOReal.
Referenced by GUIBaseVehicle::drawGLAdditional(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), and MSBaseVehicle::replaceRouteEdges().
const SUMOVehicleParameter & MSBaseVehicle::getParameter () const virtual inherited
Returns the vehicle's parameter (including departure definition)
Returns
The vehicle's parameter
Implements SUMOVehicle.
Definition at line 111 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myParameter, and SUMOReal.
Referenced by MSTransportableControl::boardAnyWaiting(), GUIBaseVehicle::drawOnPos(), MSBaseVehicle::getDepartDelay(), MSEdge::getDepartLane(), MSLane::getDepartSpeed(), GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), MSLane::insertVehicle(), MSLane::isInsertionSuccess(), MSTransportableControl::loadAnyWaiting(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), GUIBaseVehicle::setFunctionalColor(), and METriggeredCalibrator::tryEmit().
int MSVehicle::getPersonNumber () const
Returns the number of persons.
Returns
The number of passengers on-board
Definition at line 3027 of file MSVehicle.cpp.
References MSBaseVehicle::myParameter, myPersonDevice, SUMOVehicleParameter::personNumber, and MSDevice_Transportable::size().
Referenced by MSTransportableControl::boardAnyWaiting(), GUIVehicle::getParameterWindow(), nextStopDist(), TraCIServerAPI_Vehicle::processGet(), processNextStop(), and MSXMLRawOut::writeVehicle().
const std::vector< MSTransportable * > & MSVehicle::getPersons () const
retrieve riding persons
Definition at line 3007 of file MSVehicle.cpp.
References MSDevice_Transportable::getTransportables(), myEmptyTransportableVector, and myPersonDevice.
Referenced by nextStopDist(), MSFCDExport::write(), and MSXMLRawOut::writeVehicle().
SUMOReal MSVehicle::getPMxEmissions () const
Returns PMx emission of the current state.
Returns
The current PMx emission
Definition at line 2941 of file MSVehicle.cpp.
References PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), getSlope(), myAcceleration, myState, MSBaseVehicle::myType, PollutantsInterface::PM_X, MSVehicle::State::speed(), and SUMOReal.
Referenced by GUIVehicle::getColorValue(), GUIVehicle::getParameterWindow(), nextStopDist(), and TraCIServerAPI_Vehicle::processGet().
Position MSVehicle::getPosition (const SUMOReal offset = 0) const virtual
Return current position (x/y, cartesian)
If the vehicle's myLane is 0, Position::INVALID.
Parameters
[in] offset optional offset in longitudinal direction
Returns
The current position (in cartesian coordinates)
See also
myLane
Implements SUMOVehicle.
Definition at line 761 of file MSVehicle.cpp.
References MSLane::geometryPositionAtOffset(), MSLane::getEdge(), getLaneChangeModel(), MSEdge::getLanes(), getLateralPositionOnLane(), getPositionOnLane(), MSLane::interpolateLanePosToGeometryPos(), Position::INVALID, MSAbstractLaneChangeModel::isChangingLanes(), isParking(), isRemoteControlled(), PositionVector::move2side(), myCachedPosition, myLane, MSVehicle::State::myPos, MSVehicle::State::myPosLat, myState, PositionVector::positionAtOffset(), and SUMO_const_laneWidth.
Referenced by TraCIServerAPI_Vehicle::commandDistanceRequest(), computeAngle(), getAcceleration(), getBoundingBox(), getBoundingPoly(), TraCIServerAPI_Vehicle::getPosition(), GUIVehicle::getPosition(), MSVTKExport::getPositions(), MSVehicle::Influencer::implicitDeltaPosVTD(), MSVehicle::Influencer::implicitSpeedVTD(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Vehicle::vtdMap(), and MSBatteryExport::write().
SUMOReal MSVehicle::getPositionOnLane () const inline virtual
Get the vehicle's position along the lane.
Returns
The position of the vehicle (in m from the lane's begin)
Implements SUMOVehicle.
Definition at line 350 of file MSVehicle.h.
References getBackPositionOnLane(), MSVehicle::State::myPos, myState, and SUMOReal.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), adaptToLeaders(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), MSVehicleTransfer::checkInsertions(), MSLCM_SL2015::checkStrategicChange(), TraCIServerAPI_Vehicle::commandDistanceRequest(), computeAngle(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSE2Collector::detectorUpdate(), executeMove(), MSLane::executeMovements(), MSLane::freeInsertion(), MSLane::getBruttoOccupancy(), MSLaneChanger::getCloserFollower(), getDistanceToPosition(), MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSLane::getFirstAnyVehicle(), MSLane::getFirstVehicleInformation(), MSLane::getFollower(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MSLane::getLastVehicleInformation(), MSLane::getLeader(), getLeader(), MSLaneChangerSublane::getLeaders(), MSLane::getNettoOccupancy(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), GUIVehicle::getParameterWindow(), MSLane::getPartialBehind(), getPosition(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), getSlope(), MSVTKExport::getSpeed(), MSLane::lastInsertion(), MSLane::loadState(), MSLane::VehPosition::operator()(), MSLCM_JE2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSLCM_LC2013::patchSpeed(), planMove(), TraCIServerAPI_Vehicle::processGet(), MSCalibrator::remainingVehicleCapacity(), MSLane::safeInsertionSpeed(), GUIVehicle::selectBlockingFoes(), setBlinkerInformation(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), unsafeLinkAhead(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), and MSQueueExport::writeLane().
SUMOReal MSVehicle::getPositionOnLane (const MSLane * lane) const
Get the vehicle's front position relative to the given lane.
Returns
The front position of the vehicle (in m from the given lane's begin)
Definition at line 2016 of file MSVehicle.cpp.
References getBackPositionOnLane(), MSVehicleType::getLength(), and MSBaseVehicle::myType.
const MSEdge * MSVehicle::getRerouteOrigin () const virtual
Returns the starting point for reroutes (usually the current edge)
This differs from *myCurrEdge only if the vehicle is on an internal edge or very close to the junction
Returns
The rerouting start point
Reimplemented from MSBaseVehicle.
Definition at line 787 of file MSVehicle.cpp.
References MSCFModel::brakeGap(), MSRoute::end(), getCarFollowModel(), MSLane::getInternalFollower(), MSLane::getLength(), MSBaseVehicle::myCurrEdge, myLane, MSVehicle::State::myPos, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, and myState.
Referenced by isOnRoad(), and TraCIServerAPI_Vehicle::processSet().
SUMOReal MSVehicle::getRightSideOnEdge (const MSLane * lane = 0) const
Get the vehicle's lateral position on the edge of the given lane (or its current edge if lane == 0)
Returns
The lateral position of the vehicle (in m distance between right side of vehicle and ride side of edge
Definition at line 3119 of file MSVehicle.cpp.
References getCenterOnEdge(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), and SUMOReal.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSLCM_SL2015::checkBlockingVehicles(), and getLateralPositionOnLane().
SUMOReal MSVehicle::getRightSideOnLane () const
Get the vehicle's lateral position on the lane:
Returns
The lateral position of the vehicle (in m distance between right side of vehicle and ride side of the lane it is on
Definition at line 3113 of file MSVehicle.cpp.
References MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSLane::getWidth(), myLane, MSVehicle::State::myPosLat, myState, and SUMOReal.
Referenced by getLateralPositionOnLane().
const MSRoute& MSBaseVehicle::getRoute () const inline virtual inherited
Returns the current route.
Returns
The route the vehicle uses
Implements SUMOVehicle.
Definition at line 89 of file MSBaseVehicle.h.
References MSBaseVehicle::myRoute.
Referenced by TraCIServerAPI_Vehicle::commandDistanceRequest(), GUIBaseVehicle::drawRoute(), MSEdge::getDepartLane(), MSLane::isInsertionSuccess(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Vehicle::processGet(), GUIBaseVehicle::setFunctionalColor(), TraCIServerAPI_Vehicle::vtdMap(), and TraCIServerAPI_Vehicle::vtdMap_matchingRoutePosition().
int MSVehicle::getRoutePosition () const
Definition at line 669 of file MSVehicle.cpp.
References MSRoute::begin(), MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), TraCIServerAPI_Vehicle::processGet(), and TraCIServerAPI_Vehicle::vtdMap().
SUMOReal MSVehicle::getSafeFollowSpeed (const std::pair< const MSVehicle *, SUMOReal > leaderInfo, const SUMOReal seen, const MSLane *const lane, SUMOReal distToCrossing) const
compute safe speed for following the given leader
Definition at line 1538 of file MSVehicle.cpp.
References MSCFModel::followSpeed(), getCarFollowModel(), MSLane::getLength(), getSpeed(), MAX2(), POSITION_EPS, MSCFModel::stopSpeed(), and SUMOReal.
Referenced by adaptToLeader(), MSLane::getCriticalLeader(), and hasInfluencer().
int MSVehicle::getSignals () const inline
Returns the signals.
Returns
The signals' states
Definition at line 1011 of file MSVehicle.h.
References mySignals.
Referenced by TraCIServerAPI_Vehicle::processGet(), and MSFCDExport::write().
SUMOReal MSVehicle::getSlope () const virtual
Returns the slope of the road at vehicle's position.
Returns
The slope
Reimplemented from MSBaseVehicle.
Definition at line 750 of file MSVehicle.cpp.
References getPositionOnLane(), MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), myLane, PositionVector::slopeDegreeAtOffset(), and SUMOReal.
Referenced by getAcceleration(), getCO2Emissions(), getCOEmissions(), getElectricityConsumption(), getFuelConsumption(), getHCEmissions(), getNOxEmissions(), GUIVehicle::getParameterWindow(), getPMxEmissions(), MSCFModel_KraussPS::maxNextSpeed(), and TraCIServerAPI_Vehicle::processGet().
SUMOReal MSVehicle::getSpaceTillLastStanding (const MSLane * l, bool & foundStopped) const protected
Definition at line 2028 of file MSVehicle.cpp.
References MSLane::getLength(), MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), SUMO_const_haltingSpeed, and SUMOReal.
Referenced by checkRewindLinkLanes(), and hasInfluencer().
SUMOReal MSVehicle::getSpeed () const inline virtual
Returns the vehicle's current speed.
Returns
The vehicle's speed
Implements SUMOVehicle.
Definition at line 410 of file MSVehicle.h.
References MSVehicle::State::mySpeed, and myState.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSCFModel_Wiedemann::_v(), MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSCriticalFollowerDistanceInfo::addFollower(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), GUIApplicationWindow::checkGamingEvents(), checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::computeOvertakingTime(), MSLink::couldBrakeForLeader(), MSE2Collector::detectorUpdate(), executeMove(), MSLane::executeMovements(), MSLane::forceVehicleInsertion(), MSLane::freeInsertion(), GUIVehicle::getColorValue(), MSLane::getCriticalLeader(), MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSLane::getFollower(), MSLane::getLeader(), getLeader(), MSLaneChangerSublane::getLeaders(), MSLane::getMissingRearGap(), GUIVehicle::getParameterWindow(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), getSafeFollowSpeed(), MSVTKExport::getSpeed(), getTimeGap(), MSLink::getZipperSpeed(), MSLCM_DK2008::informBlocker(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), MSCFModel_IDM::interactionGap(), MSCFModel::interactionGap(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSLane::loadState(), MSLink::maybeOccupied(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_PWag2009::moveHelper(), MSCFModel_Wiedemann::moveHelper(), MSCFModel::moveHelper(), MSLCM_DK2008::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSLCM_LC2013::patchSpeed(), planMove(), planMoveInternal(), MSAbstractLaneChangeModel::predInteraction(), MSAbstractLaneChangeModel::primaryLaneChanged(), TraCIServerAPI_Vehicle::processGet(), processNextStop(), TraCIServerAPI_Vehicle::processSet(), MSLane::safeInsertionSpeed(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), unsafeLinkAhead(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), and MSQueueExport::writeLane().
SUMOReal MSVehicle::getSpeedWithoutTraciInfluence () const
Returns the uninfluenced velocity.
If no influencer exists (myInfluencer==0) the vehicle's current speed is returned. Otherwise the speed returned from myInfluencer->getOriginalSpeed().
Returns
The vehicle's velocity as it would without an influence
See also
Influencer::getOriginalSpeed
Definition at line 3463 of file MSVehicle.cpp.
References MSVehicle::Influencer::getOriginalSpeed(), myInfluencer, MSVehicle::State::mySpeed, and myState.
Referenced by TraCIServerAPI_Vehicle::processGet(), and signalSet().
const ConstMSEdgeVector MSVehicle::getStopEdges () const protected virtual
Returns the list of still pending stop edges.
Implements MSBaseVehicle.
Definition at line 1137 of file MSVehicle.cpp.
References myStops.
Referenced by hasInfluencer().
SUMOReal MSVehicle::getTimeGap () const
Returns the time gap in seconds to the leader of the vehicle looking for a fixed distance.
If the distance is too big -1 is returned. The gap returned takes the minGap into account.
Returns
The time gap in seconds; -1 if no leader was found or speed is 0.
Definition at line 2907 of file MSVehicle.cpp.
References getLeader(), getSpeed(), MSBaseVehicle::getVehicleType(), and SUMOReal.
Referenced by GUIVehicle::getColorValue(), GUIVehicle::getParameterWindow(), and nextStopDist().
SUMOVehicleClass MSBaseVehicle::getVClass () const inline virtual inherited
Returns the vehicle's access class.
Returns
The vehicle's access class
Implements SUMOVehicle.
Definition at line 105 of file MSBaseVehicle.h.
References MSBaseVehicle::getEdge(), MSBaseVehicle::getMaxSpeed(), MSVehicleType::getParameter(), MSBaseVehicle::myType, MSBaseVehicle::succEdge(), SUMOReal, and SUMOVTypeParameter::vehicleClass.
Referenced by MSPedestrianPushButton::isActiveForEdge(), and MSBaseVehicle::reroute().
const MSVehicleType& MSBaseVehicle::getVehicleType () const inline virtual inherited
Returns the vehicle's type definition.
Returns
The vehicle's type definition
Implements SUMOVehicle.
Definition at line 97 of file MSBaseVehicle.h.
References MSBaseVehicle::myType.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), adaptToLeaders(), addStop(), MSLane::basePos(), MSTransportableControl::boardAnyWaiting(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), MSLane::checkFailure(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), checkRewindLinkLanes(), MSLaneChanger::computeOvertakingTime(), MSLaneChanger::continueChange(), MSLane::detectCollisionBetween(), MSE2Collector::detectorUpdate(), GUIVehicle::drawAction_drawLinkItems(), GUIVehicle::drawAction_drawRailCarriages(), GUIVehicle::drawAction_drawVehicleBlinker(), GUIVehicle::drawAction_drawVehicleBrakeLight(), GUIEdge::drawMesoVehicles(), MSLane::enteredByLaneChange(), enterLaneAtInsertion(), enterLaneAtLaneChange(), MEVehicle::estimateLeaveSpeed(), estimateLeaveSpeed(), estimateSpeedAfterDistance(), executeMove(), MSLane::executeMovements(), MSLane::freeInsertion(), MEVehicle::getBackPositionOnLane(), MSLane::getBruttoOccupancy(), GUIBaseVehicle::getCenteringBoundary(), MSLane::getCriticalLeader(), MSEdge::getDepartLane(), MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), MSBaseVehicle::getImpatience(), getLateralOverlap(), MSLane::getLeader(), getLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getNettoOccupancy(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), getRightSideOnEdge(), getRightSideOnLane(), MSLeaderInfo::getSubLanes(), getTimeGap(), MSLink::getZipperSpeed(), MESegment::hasSpaceFor(), MSLane::incorporateVehicle(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLane::insertVehicle(), MSLane::integrateNewVehicle(), MSLane::isInsertionSuccess(), MESegment::isOpen(), MSLCM_SL2015::keepLatGap(), MSLane::lastInsertion(), MSLane::leftByLaneChange(), MSTransportableControl::loadAnyWaiting(), MESegment::loadState(), overlap(), MSLCM_DK2008::patchSpeed(), planMoveInternal(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Vehicle::processGet(), processNextStop(), TraCIServerAPI_Vehicle::processSet(), MESegment::receive(), MSLaneChanger::registerUnchanged(), MESegment::removeCar(), MSLane::removeVehicle(), MSLane::safeInsertionSpeed(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), GUIVehicle::selectBlockingFoes(), MESegment::send(), GUIBaseVehicle::setFunctionalColor(), setTentativeLaneAndPosition(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChanger::startChange(), MSLaneChangerSublane::startChangeSublane(), unsafeLinkAhead(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), updateFurtherLanes(), MSLCM_SL2015::updateGaps(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), and MSQueueExport::writeLane().
SUMOReal MSVehicle::getWaitingSeconds () const inline
Returns the number of seconds waited (speed was lesser than 0.1m/s)
The value is reset if the vehicle moves faster than 0.1m/s Intentional stopping does not count towards this time.
Returns
The time the vehicle is standing
Definition at line 502 of file MSVehicle.h.
References myWaitingTime, and STEPS2TIME.
Referenced by GUIVehicle::getColorValue(), GUIVehicle::getParameterWindow(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSPedestrianPushButton::isActiveForEdge(), TraCIServerAPI_Vehicle::processGet(), MSEmissionExport::write(), MSQueueExport::writeLane(), and MSFullExport::writeVehicles().
SUMOTime MSVehicle::getWaitingTime () const inline virtual
Returns the SUMOTime waited (speed was lesser than 0.1m/s)
The value is reset if the vehicle moves faster than 0.1m/s Intentional stopping does not count towards this time.
Returns
The time the vehicle is standing
Implements SUMOVehicle.
Definition at line 481 of file MSVehicle.h.
References myWaitingTime.
Referenced by checkRewindLinkLanes(), executeMove(), MSLane::executeMovements(), GUIVehicle::selectBlockingFoes(), and MSLink::writeApproaching().
const MSEdgeWeightsStorage & MSVehicle::getWeightsStorage () const
Returns the vehicle's internal edge travel times/efforts container.
If the vehicle does not have such a container, it is built.
Returns
The vehicle's knowledge about edge weights
Definition at line 684 of file MSVehicle.cpp.
References _getWeightsStorage().
Referenced by MSNet::getEffort(), MSNet::getTravelTime(), TraCIServerAPI_Vehicle::processGet(), and TraCIServerAPI_Vehicle::processSet().
MSEdgeWeightsStorage & MSVehicle::getWeightsStorage ()
Definition at line 690 of file MSVehicle.cpp.
References _getWeightsStorage().
bool MSVehicle::hasArrived () const virtual
Returns whether this vehicle has already arived (reached the arrivalPosition on its final edge)
Reimplemented from MSBaseVehicle.
Definition at line 601 of file MSVehicle.cpp.
References MSRoute::end(), isRemoteControlled(), MSBaseVehicle::myArrivalPos, MSBaseVehicle::myCurrEdge, MSVehicle::State::myPos, MSBaseVehicle::myRoute, myState, myStops, and POSITION_EPS.
Referenced by enterLaneAtMove(), executeMove(), and MSLane::executeMovements().
bool MSBaseVehicle::hasDeparted () const virtual inherited
Returns whether this vehicle has already departed.
Implements SUMOVehicle.
Definition at line 265 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDeparture, and MSBaseVehicle::NOT_YET_DEPARTED.
Referenced by addStop(), MSLane::forceVehicleInsertion(), MEVehicle::loadState(), loadState(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), and MSBaseVehicle::setArrivalPos().
bool MSVehicle::hasInfluencer () const inline
Definition at line 1301 of file MSVehicle.h.
References adaptLaneEntering2MoveReminder(), getSafeFollowSpeed(), getSpaceTillLastStanding(), getStopEdges(), influenceChangeDecision(), loadState(), myInfluencer, nextLinkPriority(), saveState(), setBlinkerInformation(), setEmergencyBlueLight(), setVTDState(), SUMOReal, and updateOccupancyAndCurrentBestLane().
Referenced by MSLane::detectCollisionBetween(), MSLane::executeMovements(), MSLane::handleCollisionBetween(), and influenceChangeDecision().
bool MSVehicle::hasStops () const inline
Returns whether the vehicle has to stop somewhere.
Returns
Whether the vehicle has to stop somewhere
Definition at line 771 of file MSVehicle.h.
References isParking(), isRemoteControlled(), isStopped(), and myStops.
bool MSBaseVehicle::hasValidRoute (std::string & msg, const MSRoute * route = 0) const virtual inherited
Validates the current or given route.
Parameters
[out] msg Description why the route is not valid (if it is the case)
[in] route The route to check (or 0 if the current route shall be checked)
Returns
Whether the vehicle's current route is valid
Implements SUMOVehicle.
Definition at line 284 of file MSBaseVehicle.cpp.
References MSRoute::begin(), MSRoute::end(), MSVehicleType::getVehicleClass(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myRoute, and MSBaseVehicle::myType.
Referenced by MSBaseVehicle::getDevices(), MESegment::initialise(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), and MSBaseVehicle::replaceRouteEdges().
int MSVehicle::influenceChangeDecision (int state)
allow TraCI to influence a lane change decision
Definition at line 3472 of file MSVehicle.cpp.
References MSLane::getEdge(), getInfluencer(), MSNet::getInstance(), getLaneIndex(), hasInfluencer(), MSVehicle::Influencer::influenceChangeDecision(), and myLane.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSAbstractLaneChangeModel::cancelRequest(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), MSLCM_SL2015::checkStrategicChange(), and hasInfluencer().
bool MSVehicle::isFrontOnLane (const MSLane * lane) const virtual
Returns the information whether the front of the vehicle is on the given lane.
Returns
Whether the vehicle's front is on that lane
Reimplemented from MSBaseVehicle.
Definition at line 2022 of file MSVehicle.cpp.
References getLaneChangeModel(), MSAbstractLaneChangeModel::getShadowLane(), myLane, and SUMOReal.
Referenced by checkRewindLinkLanes(), MSLane::detectCollisionBetween(), MSLane::getFirstVehicleInformation(), MSLane::getFollowersOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLane::getPartialBehind(), isOnRoad(), and MSLink::writeApproaching().
bool MSVehicle::isOnRoad () const inline virtual
Returns the information whether the vehicle is on a road (is simulated)
Returns
Whether the vehicle is simulated
Reimplemented from MSBaseVehicle.
Definition at line 455 of file MSVehicle.h.
References getRerouteOrigin(), isFrontOnLane(), and myAmOnNet.
Referenced by GUIApplicationWindow::checkGamingEvents(), TraCIServerAPI_Vehicle::commandDistanceRequest(), getDistanceToPosition(), MSVTKExport::getPositions(), MSVTKExport::getSpeed(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Vehicle::vtdMap(), MSBatteryExport::write(), and MSQueueExport::writeLane().
bool MSVehicle::isParking () const virtual
Returns whether the vehicle is parking.
Returns
whether the vehicle is parking
Implements SUMOVehicle.
Definition at line 994 of file MSVehicle.cpp.
References isStopped(), and myStops.
Referenced by MSVehicleTransfer::add(), computeAngle(), MSLane::executeMovements(), getPosition(), GUIVehicle::getStopInfo(), hasStops(), and TraCIServerAPI_Vehicle::processGet().
bool MSVehicle::isRemoteControlled () const virtual
Returns the information whether the vehicle is fully controlled via TraCI.
Returns
Whether the vehicle is remote-controlled
Reimplemented from MSBaseVehicle.
Definition at line 3492 of file MSVehicle.cpp.
References MSVehicle::Influencer::isVTDControlled(), and myInfluencer.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), executeMove(), getPosition(), hasArrived(), and hasStops().
bool MSVehicle::isStopped () const virtual
Returns whether the vehicle is at a stop.
Returns
Whether the vehicle has stopped
Implements SUMOVehicle.
Definition at line 988 of file MSVehicle.cpp.
References myStops.
Referenced by MSLaneChanger::changeOpposite(), executeMove(), MSLane::executeMovements(), GUIVehicle::getStopInfo(), hasStops(), isParking(), isStoppedInRange(), isStoppedTriggered(), TraCIServerAPI_Vehicle::processGet(), and resumeFromStopping().
bool MSVehicle::isStoppedInRange (SUMOReal pos) const
return whether the given position is within range of the current stop
Definition at line 1006 of file MSVehicle.cpp.
References isStopped(), myStops, and SUMOReal.
Referenced by MSVehicleControl::getWaitingVehicle(), and nextStopDist().
bool MSVehicle::isStoppedTriggered () const virtual
Returns whether the vehicle is on a triggered stop.
Returns
whether the vehicle is on a triggered stop
Implements SUMOVehicle.
Definition at line 1000 of file MSVehicle.cpp.
References isStopped(), and myStops.
Referenced by nextStopDist().
bool MSVehicle::knowsEdgeTest (MSEdge & edge) const
Referenced by nextStopDist().
void MSVehicle::leaveLane (const MSMoveReminder::Notification reason)
Update of members if vehicle leaves a new lane in the lane change step or at arrival.
Definition at line 2413 of file MSVehicle.cpp.
References DEBUG_COND, MSBaseVehicle::getID(), MSNet::getInstance(), myAmOnNet, MSBaseVehicle::myCurrEdge, myFurtherLanes, myFurtherLanesPosLat, MSBaseVehicle::myMoveReminders, MSVehicle::State::myPos, myState, myStops, MSMoveReminder::NOTIFICATION_JUNCTION, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSMoveReminder::NOTIFICATION_PARKING, MSMoveReminder::NOTIFICATION_TELEPORT, resumeFromStopping(), SIMTIME, time2string(), and WRITE_WARNING.
Referenced by MSVehicleTransfer::checkInsertions(), congested(), executeMove(), onRemovalFromNet(), MSAbstractLaneChangeModel::primaryLaneChanged(), and MSLane::removeVehicle().
void MSVehicle::loadState (const SUMOSAXAttributes & attrs, const SUMOTime offset) virtual
Loads the state of this vehicle from the given description.
Implements SUMOVehicle.
Definition at line 3514 of file MSVehicle.cpp.
References SUMOSAXAttributes::getFloat(), SUMOSAXAttributes::getString(), SUMOSAXAttributes::hasAttribute(), MSBaseVehicle::hasDeparted(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myDeparture, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSVehicle::State::mySpeed, myState, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_SPEED, and SUMO_ATTR_STATE.
Referenced by hasInfluencer().
int MSVehicle::nextLinkPriority (const std::vector< MSLane * > & conts) static
get a numerical value for the priority of the upcoming link
Definition at line 2775 of file MSVehicle.cpp.
References MSLinkContHelper::getConnectingLink(), and MSLink::havePriority().
Referenced by hasInfluencer(), and updateBestLanes().
SUMOReal MSVehicle::nextStopDist () const inline
return the distance to the next stop or SUMORealMax if there is none.
Definition at line 791 of file MSVehicle.h.
References addContainer(), addPerson(), getCO2Emissions(), getCOEmissions(), getContainerNumber(), getContainers(), getDistanceToPosition(), getElectricityConsumption(), getFuelConsumption(), getHarmonoise_NoiseEmissions(), getHCEmissions(), getLaneIndex(), getLeader(), getNOxEmissions(), getPersonNumber(), getPersons(), getPMxEmissions(), getTimeGap(), isStoppedInRange(), isStoppedTriggered(), knowsEdgeTest(), myStopDist, processNextStop(), and SUMOReal.
Referenced by MSLaneChanger::changeOpposite().
void MSBaseVehicle::onDepart () virtual inherited
Called when the vehicle is inserted into the network.
Sets optional information about departure time, informs the vehicle control about a further running vehicle.
Implements SUMOVehicle.
Definition at line 257 of file MSBaseVehicle.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), SUMOVehicle::getPositionOnLane(), MSNet::getVehicleControl(), MSBaseVehicle::myDepartPos, MSBaseVehicle::myDeparture, and MSVehicleControl::vehicleDeparted().
Referenced by enterLaneAtInsertion(), MSBaseVehicle::getCurrentRouteEdge(), and MESegment::receive().
void MSVehicle::onRemovalFromNet (const MSMoveReminder::Notification reason)
Called when the vehicle is removed from the network.
Moves along work reminders and informs all devices about quitting. Calls "leaveLane" then.
Parameters
[in] reason why the vehicle leaves (reached its destination, parking, teleport)
Definition at line 591 of file MSVehicle.cpp.
References MSVehicleTransfer::getInstance(), leaveLane(), myLFLinkLanes, MSVehicle::State::myPos, MSVehicle::State::mySpeed, myState, MSVehicleTransfer::remove(), removeApproachingInformation(), SPEED2DIST, and workOnMoveReminders().
Referenced by MSVehicleTransfer::add(), MSLane::detectCollisions(), MSLane::executeMovements(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Vehicle::processSet(), and MSCalibrator::removePending().
MSVehicle& MSVehicle::operator= (const MSVehicle &) private
invalidated assignment operator
static bool MSVehicle::overlap (const MSVehicle * veh1, const MSVehicle * veh2) inline static
Returns true if the two vehicles overlap.
Definition at line 532 of file MSVehicle.h.
References MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), MSVehicle::State::myPos, and myState.
void MSVehicle::planMove (const SUMOTime t, const MSLeaderInfo & ahead, const SUMOReal lengthsInFront)
Compute safe velocities for the upcoming lanes based on positions and speeds from the last time step. Also registers ApproachingVehicleInformation for all links.
This method goes through the best continuation lanes of the current lane and computes the safe velocities for passing/stopping at the next link as a DriveProcessItem
Afterwards it checks if any DriveProcessItem should be discared to avoid blocking a junction (checkRewindLinkLanes).
Finally the ApproachingVehicleInformation is registered for all links that shall be passed
Parameters
[in] t The current timeStep
[in] ahead The leaders (may be 0)
[in] lengthsInFront Sum of vehicle lengths in front of the vehicle
Definition at line 1147 of file MSVehicle.cpp.
References checkRewindLinkLanes(), DEBUG_COND, Named::getID(), MSBaseVehicle::getID(), getLaneChangeModel(), getLateralPositionOnLane(), getPositionOnLane(), getSpeed(), myLane, myLFLinkLanes, myStopDist, planMoveInternal(), MSAbstractLaneChangeModel::resetChanged(), and STEPS2TIME.
void MSVehicle::planMoveInternal (const SUMOTime t, MSLeaderInfo ahead, DriveItemVector & lfLinks, SUMOReal & myStopDist) const protected
Definition at line 1198 of file MSVehicle.cpp.
References MSVehicle::DriveProcessItem::adaptLeaveSpeed(), adaptToLeader(), adaptToLeaders(), ARRIVAL_SPEED_GIVEN, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, bla, MSCFModel::brakeGap(), MSVehicle::Stop::busstop, CRLL_LOOK_AHEAD, DEBUG_COND, DELTA_T, DIST_TO_STOPLINE_EXPECT_PRIORITY, MSEdge::EDGEFUNCTION_INTERNAL, MSRoute::end(), MSVehicle::Stop::endPos, estimateLeaveSpeed(), estimateSpeedAfterDistance(), MSCFModel::freeSpeed(), gDebugSelectedVehicle, getBestLanesContinuation(), getCarFollowModel(), MSLane::getEdge(), MSCFModel::getHeadwayTime(), MSBaseVehicle::getID(), MSNet::getInstance(), getLane(), getLaneChangeModel(), MSStoppingPlace::getLastFreePos(), MSLane::getLastVehicleInformation(), MSVehicleType::getLength(), MSLane::getLength(), MSLane::getLogicalPredecessorLane(), MSCFModel::getMaxAccel(), MSCFModel::getMaxDecel(), MSLane::getOpposite(), MSLane::getParallelLane(), MSEdge::getPurpose(), MSLane::getRightSideOnEdge(), MSAbstractLaneChangeModel::getShadowLane(), getSpeed(), MSCFModel::getSpeedAfterMaxDecel(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSGlobals::gUsingInternalLanes, MSVehicle::Influencer::influenceSpeed(), MSEdge::isInternal(), MSLane::isLinkEnd(), MSAbstractLaneChangeModel::isOpposite(), LINKDIR_LEFT, LINKDIR_RIGHT, LINKSTATE_TL_RED, LINKSTATE_TL_REDYELLOW, LINKSTATE_TL_YELLOW_MAJOR, LINKSTATE_TL_YELLOW_MINOR, max, MAX2(), MAX3(), MSCFModel::maxNextSpeed(), MIN2(), MSBaseVehicle::myArrivalPos, MSBaseVehicle::myCurrEdge, myInfluencer, myLane, MSBaseVehicle::myParameter, MSVehicle::State::myPos, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, myState, myStops, MSVehicle::DriveProcessItem::myVLinkWait, NUMERICAL_EPS, POSITION_EPS, removeApproachingInformation(), SIMTIME, SPEED2DIST, STEPS2TIME, MSCFModel::stopSpeed(), MSLane::succLinkSec(), SUMO_const_haltingSpeed, SUMOReal, TIME2STEPS, and toString().
Referenced by planMove().
SUMOReal MSVehicle::processNextStop (SUMOReal currentVelocity)
Processes stops, returns the velocity needed to reach the stop.
Returns
The velocity in dependance to the next/current stop
Todo:
Describe more detailed
See also
Stop
MSStoppingPlace
MSStoppingPlace
Definition at line 1012 of file MSVehicle.cpp.
References MSVehicleControl::addWaiting(), MSVehicle::Stop::awaitedContainers, MSVehicle::Stop::awaitedPersons, MSTransportableControl::boardAnyWaiting(), MSVehicle::Stop::busstop, MSVehicle::Stop::containerstop, MSVehicle::Stop::containerTriggered, DELTA_T, MSVehicle::Stop::duration, MSVehicle::Stop::edge, MSVehicle::Stop::endPos, MSStoppingPlace::enter(), MSStoppingPlace::getBeginLanePosition(), getCarFollowModel(), MSNet::getContainerControl(), getContainerNumber(), MSNet::getCurrentTimeStep(), MSLane::getEdge(), MSStoppingPlace::getEndLanePosition(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSStoppingPlace::getLastFreePos(), MSVehicleType::getLength(), MSVehicleType::getMinGap(), MSNet::getPersonControl(), getPersonNumber(), getSpeed(), MSDevice_Transportable::getTransportables(), MSNet::getVehicleControl(), MSBaseVehicle::getVehicleType(), MSNet::hasContainers(), MSNet::hasPersons(), MSNet::informVehicleStateListener(), MSVehicle::Stop::lane, MSTransportableControl::loadAnyWaiting(), MAX2(), myAmRegisteredAsWaitingForContainer, myAmRegisteredAsWaitingForPerson, myContainerDevice, MSBaseVehicle::myCurrEdge, myLane, myPersonDevice, myState, myStops, MSBaseVehicle::myType, NUMERICAL_EPS, MSVehicle::State::pos(), MSVehicle::Stop::reached, MSVehicleControl::registerOneWaitingForContainer(), MSVehicleControl::registerOneWaitingForPerson(), MSStoppingPlace::removeTransportable(), resumeFromStopping(), MSVehicle::Stop::startPos, STOPPING_PLACE_OFFSET, MSCFModel::stopSpeed(), SUMO_const_haltingSpeed, SUMOReal, MSVehicle::Stop::triggered, MSVehicleControl::unregisterOneWaitingForContainer(), MSVehicleControl::unregisterOneWaitingForPerson(), MSVehicle::Stop::until, MSNet::VEHICLE_STATE_STARTING_STOP, and WRITE_WARNING.
Referenced by MSVehicleTransfer::checkInsertions(), MSCFModel_Daniel1::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel::moveHelper(), and nextStopDist().
void MSVehicle::removeApproachingInformation (DriveItemVector & lfLinks) const protected
unregister approach from all upcoming links
Definition at line 3207 of file MSVehicle.cpp.
References getLaneChangeModel(), and MSAbstractLaneChangeModel::removeShadowApproachingInformation().
Referenced by onRemovalFromNet(), planMoveInternal(), and ~MSVehicle().
void MSBaseVehicle::removeReminder (MSMoveReminder * rem) inherited
Removes a MoveReminder dynamically.
Parameters
[in] rem the reminder to remove
See also
MSMoveReminder
Definition at line 323 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by MSBaseVehicle::getDevices().
bool MSVehicle::replaceRoute (const MSRoute * route, bool onInit = false, int offset = 0) virtual
Replaces the current route by the given one.
It is possible that the new route is not accepted, if it does not contain the vehicle's current edge.
Parameters
[in] route The new route to pass
Returns
Whether the new route was accepted
Implements SUMOVehicle.
Definition at line 610 of file MSVehicle.cpp.
References MSRoute::addReference(), addStop(), MSRoute::begin(), MSBaseVehicle::calculateArrivalParams(), MSRoute::contains(), MSLane::getEdge(), MSRoute::getEdges(), MSNet::getInstance(), MSLane::getOutgoingLanes(), MSRoute::getStops(), MSNet::informVehicleStateListener(), MSEdge::isInternal(), MSBaseVehicle::myCurrEdge, myLane, myLastBestLanesEdge, myLastBestLanesInternalLane, MSBaseVehicle::myNumberReroutes, MSBaseVehicle::myRoute, myStops, MSRoute::release(), updateBestLanes(), MSNet::VEHICLE_STATE_NEWROUTE, and WRITE_WARNING.
Referenced by TraCIServerAPI_Vehicle::processSet().
bool MSBaseVehicle::replaceRouteEdges (ConstMSEdgeVector & edges, bool onInit = false, bool check = false) virtual inherited
Replaces the current route by the given edges.
It is possible that the new route is not accepted, if a) it does not contain the vehicle's current edge, or b) something fails on insertion into the routes container (see in-line comments).
Parameters
[in] edges The new list of edges to pass
[in] onInit Whether the vehicle starts with this route
[in] check Whether the route should be checked for validity
Returns
Whether the new route was accepted
Implements SUMOVehicle.
Definition at line 186 of file MSBaseVehicle.cpp.
References MSRoute::addReference(), MSRoute::begin(), MSBaseVehicle::calculateArrivalParams(), RGBColor::DEFAULT_COLOR, MSRoute::dictionary(), MSGlobals::gCheckRoutes, MSRoute::getColor(), MSRoute::getEdges(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getNumberReroutes(), MSBaseVehicle::getRerouteOrigin(), MSRoute::getStops(), MSBaseVehicle::hasValidRoute(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myRoute, MSRoute::release(), SUMOVehicle::replaceRoute(), MSRoute::size(), SUMOReal, toString(), and WRITE_WARNING.
Referenced by MSBaseVehicle::getCurrentRouteEdge(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Vehicle::processSet(), and MSBaseVehicle::reroute().
void MSVehicle::replaceVehicleType (MSVehicleType * type)
Replaces the current vehicle type by the one given.
If the currently used vehicle type is marked as being used by this vehicle only, it is deleted, first. The new, given type is then assigned to "myType".
Parameters
[in] type The new vehicle type
See also
MSVehicle::myType
Definition at line 3088 of file MSVehicle.cpp.
References MSVehicleType::amVehicleSpecific(), and MSBaseVehicle::myType.
Referenced by TraCIServerAPI_Vehicle::processSet().
void MSBaseVehicle::reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > & router, const bool onInit = false, const bool withTaz = false) virtual inherited
Performs a rerouting using the given router.
Tries to find a new route between the current edge and the destination edge, first. Tries to replace the current route by the new one using replaceRoute.
Parameters
[in] t The time for which the route is computed
[in] router The router to use
See also
replaceRoute
Implements SUMOVehicle.
Definition at line 139 of file MSBaseVehicle.cpp.
References MSEdge::allowedLanes(), SUMOAbstractRouter< E, V >::compute(), MSEdge::dictionary(), MSEdge::EDGEFUNCTION_DISTRICT, SUMOVehicleParameter::fromTaz, Named::getID(), MSBaseVehicle::getID(), MSRoute::getLastEdge(), MSBaseVehicle::getRerouteOrigin(), MSBaseVehicle::getStopEdges(), MSBaseVehicle::getVClass(), MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, MSBaseVehicle::replaceRouteEdges(), SUMOVehicleParameter::toTaz, and SUMOVehicleParameter::via.
Referenced by MSBaseVehicle::getCurrentRouteEdge(), and TraCIServerAPI_Vehicle::processSet().
void MSVehicle::resetRoutePosition (int index)
Definition at line 675 of file MSVehicle.cpp.
References MSRoute::begin(), MSRoute::end(), MSBaseVehicle::myArrivalPos, MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by MSCalibrator::execute().
bool MSVehicle::resumeFromStopping ()
resumes a vehicle from stopping
Returns
true on success, the resuming fails if the vehicle wasn't parking in the first place
Definition at line 3405 of file MSVehicle.cpp.
References MSLane::getEdge(), MSNet::getInstance(), MSNet::getVehicleControl(), MSNet::informVehicleStateListener(), isStopped(), myAmRegisteredAsWaitingForContainer, myAmRegisteredAsWaitingForPerson, myLane, myStops, myWaitingTime, MSVehicleControl::removeWaiting(), MSVehicleControl::unregisterOneWaitingForContainer(), MSVehicleControl::unregisterOneWaitingForPerson(), updateBestLanes(), and MSNet::VEHICLE_STATE_ENDING_STOP.
Referenced by leaveLane(), processNextStop(), and signalSet().
void MSVehicle::saveState (OutputDevice & out) virtual
Saves the states of a vehicle.
Reimplemented from MSBaseVehicle.
Definition at line 3499 of file MSVehicle.cpp.
References MSRoute::begin(), OutputDevice::closeTag(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myDeparture, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, myState, MSBaseVehicle::saveState(), SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_SPEED, SUMO_ATTR_STATE, toString(), and OutputDevice::writeAttr().
Referenced by hasInfluencer().
void MSVehicle::setAngle (SUMOReal angle)
Set a custom vehicle angle in rad.
Definition at line 802 of file MSVehicle.cpp.
References myAngle, and SUMOReal.
Referenced by getAngle(), and MSVehicle::Influencer::postProcessVTD().
virtual void MSBaseVehicle::setArrivalPos (SUMOReal arrivalPos) inline virtual inherited
Sets this vehicle's desired arrivalPos for its current route.
Implements SUMOVehicle.
Definition at line 256 of file MSBaseVehicle.h.
References MSBaseVehicle::hasArrived(), MSBaseVehicle::hasDeparted(), and MSBaseVehicle::myArrivalPos.
void MSVehicle::setBlinkerInformation () protected
Definition at line 3040 of file MSVehicle.cpp.
References getBestLanesContinuation(), getLane(), getLaneChangeModel(), MSLane::getLength(), MSLane::getLinkCont(), MSAbstractLaneChangeModel::getOwnState(), getPositionOnLane(), MSLane::getVehicleMaxSpeed(), LCA_LEFT, LCA_RIGHT, LCA_SUBLANE, LINKDIR_LEFT, LINKDIR_PARTLEFT, LINKDIR_PARTRIGHT, LINKDIR_RIGHT, LINKDIR_TURN, MSLane::succLinkSec(), SUMOReal, switchOffSignal(), switchOnSignal(), VEH_SIGNAL_BLINKER_LEFT, and VEH_SIGNAL_BLINKER_RIGHT.
Referenced by executeMove(), and hasInfluencer().
void MSBaseVehicle::setChosenSpeedFactor (const SUMOReal factor) inline virtual inherited
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
Returns
Speed limit factor
Implements SUMOVehicle.
Definition at line 347 of file MSBaseVehicle.h.
References MSBaseVehicle::addStops(), MSBaseVehicle::calculateArrivalParams(), MSBaseVehicle::getDevice(), MSBaseVehicle::getStopEdges(), MSBaseVehicle::myChosenSpeedFactor, and MSBaseVehicle::saveState().
Referenced by TraCIServerAPI_Vehicle::processSet().
void MSVehicle::setEmergencyBlueLight (SUMOTime currentTime) protected
sets the blue flashing light for emergency vehicles
Definition at line 3076 of file MSVehicle.cpp.
References signalSet(), switchOffSignal(), switchOnSignal(), and VEH_SIGNAL_EMERGENCY_BLUE.
Referenced by executeMove(), and hasInfluencer().
void MSVehicle::setTentativeLaneAndPosition (MSLane * lane, SUMOReal pos, SUMOReal posLat = 0)
set tentative lane and position during insertion to ensure that all cfmodels work (some of them require veh->getLane() to return a valid lane) Once the vehicle is sucessfully inserted the lane is set again (see enterLaneAtInsertion)
Definition at line 3103 of file MSVehicle.cpp.
References MSVehicleType::getLength(), MSBaseVehicle::getVehicleType(), MSVehicle::State::myBackPos, myLane, MSVehicle::State::myPos, MSVehicle::State::myPosLat, myState, and SUMOReal.
Referenced by congested(), MSLane::isInsertionSuccess(), and TraCIServerAPI_Vehicle::processSet().
void MSVehicle::setVTDState (Position xyPos)
sets position outside the road network
Definition at line 3485 of file MSVehicle.cpp.
References myCachedPosition.
Referenced by hasInfluencer(), and MSVehicle::Influencer::postProcessVTD().
bool MSVehicle::signalSet (int which) const inline
Returns whether the given signal is on.
Parameters
[in] signal The signal to return the value of
Returns
Whether the given signal is on
Definition at line 1020 of file MSVehicle.h.
References addTraciBusOrContainerStop(), addTraciStop(), getBoundingBox(), getBoundingPoly(), getNextStop(), getSpeedWithoutTraciInfluence(), mySignals, resumeFromStopping(), SUMOReal, unsafeLinkAhead(), and updateFurtherLanes().
Referenced by checkRewindLinkLanes(), GUIVehicle::drawAction_drawVehicleBlinker(), GUIVehicle::drawAction_drawVehicleBlueLight(), GUIVehicle::drawAction_drawVehicleBrakeLight(), and setEmergencyBlueLight().
const MSEdge * MSBaseVehicle::succEdge (int nSuccs) const virtual inherited
Returns the nSuccs'th successor of edge the vehicle is currently at.
If the rest of the route (counted from the current edge) has less than nSuccs edges, 0 is returned.
Parameters
[in] nSuccs The number of edge to look forward
Returns
The nSuccs'th following edge in the vehicle's route
Implements SUMOVehicle.
Definition at line 123 of file MSBaseVehicle.cpp.
References MSRoute::begin(), MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by MSVehicleTransfer::add(), MSLane::appropriate(), MSVehicleTransfer::checkInsertions(), MESegment::getLink(), MSBaseVehicle::getVClass(), MSBaseVehicle::hasArrived(), MSPedestrianPushButton::isActiveForEdge(), MELoop::nextSegment(), TraCIServerAPI_Vehicle::processSet(), and MESegment::receive().
void MSVehicle::switchOffSignal (int signal) inline
Switches the given signal off.
Parameters
[in] signal The signal to mark as being switched off
Definition at line 1003 of file MSVehicle.h.
References mySignals.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver(), executeMove(), TraCIServerAPI_Vehicle::processSet(), setBlinkerInformation(), setEmergencyBlueLight(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
void MSVehicle::switchOnSignal (int signal) inline
Switches the given signal on.
Parameters
[in] signal The signal to mark as being switched on
Definition at line 995 of file MSVehicle.h.
References mySignals.
Referenced by executeMove(), TraCIServerAPI_Vehicle::processSet(), setBlinkerInformation(), setEmergencyBlueLight(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
bool MSVehicle::unsafeLinkAhead (const MSLane * lane) const
whether the vehicle may safely move to the given lane with regard to upcoming links
Definition at line 3219 of file MSVehicle.cpp.
References MSCFModel::brakeGap(), getBestLanesContinuation(), getCarFollowModel(), MSLane::getEdge(), MSVehicleType::getLength(), MSLane::getLength(), getPositionOnLane(), getSpeed(), MSBaseVehicle::getVehicleType(), MSEdge::isInternal(), MSLane::isLinkEnd(), LINKSTATE_ZIPPER, myLane, myLFLinkLanes, MSLane::succLinkSec(), SUMOReal, and MSLink::ZIPPER_ADAPT_DIST.
Referenced by MSLaneChanger::checkChange(), and signalSet().
void MSVehicle::updateBestLanes (bool forceRebuild = false, const MSLane * startLane = 0)
computes the best lanes to use in order to continue the route
The information is rebuilt if the vehicle is on a different edge than the one stored in "myLastBestLanesEdge" or "forceRebuild" is true.
Otherwise, only the density changes on the stored lanes are adapted to the container only.
A rebuild must be done if the vehicle leaves a stop; then, another lane may become the best one.
If no starting lane ("startLane") is given, the vehicle's current lane ("myLane") is used as start of bect lanes building.
Parameters
[in] forceRebuild Whether the best lanes container shall be rebuilt even if the vehicle's edge has not changed
[in] startLane The lane the process shall start at ("myLane" will be used if ==0)
Definition at line 2480 of file MSVehicle.cpp.
References abs, MSEdge::allowedLanes(), MSVehicle::LaneQ::allowsContinuation, MSLane::allowsVehicleClass(), ARRIVAL_LANE_GIVEN, SUMOVehicleParameter::arrivalLaneProcedure, MSVehicle::LaneQ::bestContinuations, MSVehicle::LaneQ::bestLaneOffset, bla, MSEdge::clear(), MSVehicle::LaneQ::currentLength, DEBUG_COND, MSEdge::EDGEFUNCTION_INTERNAL, MSRoute::end(), gDebugSelectedVehicle, getBestLanesContinuation(), MSLane::getEdge(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), MSLane::getInternalFollower(), getLaneChangeModel(), MSEdge::getLanes(), MSLane::getLength(), MSEdge::getLength(), MSLane::getLinkCont(), MSLane::getLogicalPredecessorLane(), MSEdge::getPurpose(), MSVehicleType::getVehicleClass(), MSVehicle::LaneQ::lane, MSVehicle::Stop::lane, MSVehicle::LaneQ::length, MAX2(), MIN2(), MSBaseVehicle::myArrivalLane, MSBaseVehicle::myArrivalPos, myBestLanes, MSBaseVehicle::myCurrEdge, myCurrentLaneInBestLanes, myLane, myLastBestLanesEdge, myLastBestLanesInternalLane, MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, myStops, MSBaseVehicle::myType, nextLinkPriority(), MSVehicle::LaneQ::nextOccupation, MSVehicle::LaneQ::occupation, POSITION_EPS, SIMTIME, MSVehicle::Stop::startPos, SUMOReal, toString(), and updateOccupancyAndCurrentBestLane().
Referenced by addTraciBusOrContainerStop(), addTraciStop(), MSLaneChangerSublane::change(), MSLaneChanger::change(), enterLaneAtLaneChange(), executeMove(), MSLane::forceVehicleInsertion(), MSEdge::getDepartLane(), MSLane::isInsertionSuccess(), MSLane::loadState(), MSVehicle::Influencer::postProcessVTD(), replaceRoute(), and resumeFromStopping().
SUMOReal MSVehicle::updateFurtherLanes (std::vector< MSLane * > & furtherLanes, std::vector< SUMOReal > & furtherLanesPosLat, const std::vector< MSLane * > & passedLanes)
update a vector of further lanes and return the new backPos
Definition at line 1911 of file MSVehicle.cpp.
References DEBUG_COND, MSVehicleType::getLength(), MSBaseVehicle::getVehicleType(), MSVehicle::State::myPos, MSVehicle::State::myPosLat, myState, SIMTIME, SUMOReal, and toString().
Referenced by executeMove(), signalSet(), and MSAbstractLaneChangeModel::updateShadowLane().
void MSVehicle::updateOccupancyAndCurrentBestLane (const MSLane * startLane) protected
updates LaneQ::nextOccupation and myCurrentLaneInBestLanes
Definition at line 2791 of file MSVehicle.cpp.
References myBestLanes, myCurrentLaneInBestLanes, and SUMOReal.
Referenced by hasInfluencer(), and updateBestLanes().
bool MSVehicle::willPass (const MSEdge *const edge) const
Returns whether the vehicle wil pass the given edge.
Parameters
[in] The edge to find in the vehicle's current route
Returns
Whether the given edge will be passed by the vehicle
Todo:
Move to MSRoute?
Definition at line 663 of file MSVehicle.cpp.
References MSRoute::end(), MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by TraCIServerAPI_Vehicle::processSet().
void MSVehicle::workOnMoveReminders (SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed)
Processes active move reminder.
This method goes through all active move reminder, both those for the current lane, stored in "myMoveReminders" and those of prior lanes stored in "myOldLaneMoveReminders" calling "MSMoveReminder::notifyMove".
When processing move reminder from "myOldLaneMoveReminders", the offsets (prior lane lengths) are used, which are stored in "myOldLaneMoveReminderOffsets".
Each move reminder which is no longer active is removed from the container.
Parameters
[in] oldPos The position the vehicle had before it has moved
[in] newPos The position the vehicle has after it has moved
[in] newSpeed The vehicle's speed within this move
See also
MSMoveReminder
Definition at line 706 of file MSVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by executeMove(), MSLane::executeMovements(), and onRemovalFromNet().
Friends And Related Function Documentation
friend class MSLaneChanger friend
the lane changer sets myLastLaneChangeOffset
Definition at line 85 of file MSVehicle.h.
friend class MSLaneChangerSublane friend
Definition at line 86 of file MSVehicle.h.
Field Documentation
SUMOReal MSVehicle::myAcceleration protected
The current acceleration after dawdling in m/s.
Definition at line 1404 of file MSVehicle.h.
Referenced by executeMove(), getAcceleration(), getCO2Emissions(), getCOEmissions(), getElectricityConsumption(), getFuelConsumption(), getHarmonoise_NoiseEmissions(), getHCEmissions(), getNOxEmissions(), and getPMxEmissions().
bool MSVehicle::myAmOnNet protected
Whether the vehicle is on the network (not parking, teleported, vaporized, or arrived)
Definition at line 1414 of file MSVehicle.h.
Referenced by enterLaneAtInsertion(), enterLaneAtLaneChange(), enterLaneAtMove(), isOnRoad(), and leaveLane().
bool MSVehicle::myAmRegisteredAsWaitingForContainer protected
Whether this vehicle is registered as waiting for a container (for deadlock-recognition)
Definition at line 1420 of file MSVehicle.h.
Referenced by processNextStop(), and resumeFromStopping().
bool MSVehicle::myAmRegisteredAsWaitingForPerson protected
Whether this vehicle is registered as waiting for a person (for deadlock-recognition)
Definition at line 1417 of file MSVehicle.h.
Referenced by processNextStop(), and resumeFromStopping().
SUMOReal MSVehicle::myAngle protected
the angle (
Todo:
consider moving this into myState)
Definition at line 1425 of file MSVehicle.h.
Referenced by MSLaneChanger::continueChange(), enterLaneAtInsertion(), enterLaneAtLaneChange(), executeMove(), getAngle(), and setAngle().
int MSBaseVehicle::myArrivalLane protected inherited
The destination lane where the vehicle stops.
Definition at line 422 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), and updateBestLanes().
SUMOReal MSBaseVehicle::myArrivalPos protected inherited
The position on the destination lane where the vehicle stops.
Definition at line 419 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), MSBaseVehicle::getArrivalPos(), MEVehicle::hasArrived(), hasArrived(), planMoveInternal(), resetRoutePosition(), MSBaseVehicle::setArrivalPos(), and updateBestLanes().
std::vector<std::vector<LaneQ> > MSVehicle::myBestLanes protected
Definition at line 1389 of file MSVehicle.h.
Referenced by adaptBestLanesOccupation(), GUIVehicle::drawBestLanes(), getBestLaneOffset(), getBestLanes(), getBestLanesContinuation(), updateBestLanes(), and updateOccupancyAndCurrentBestLane().
Position MSVehicle::myCachedPosition mutable protected
Definition at line 1430 of file MSVehicle.h.
Referenced by MSLaneChanger::continueChange(), enterLaneAtInsertion(), enterLaneAtLaneChange(), enterLaneAtMove(), executeMove(), getPosition(), setVTDState(), and MSLaneChangerSublane::startChangeSublane().
MSCFModel::VehicleVariables* MSVehicle::myCFVariables private
The per vehicle variables of the car following model.
Definition at line 1561 of file MSVehicle.h.
Referenced by getCarFollowVariables(), and MSVehicle().
SUMOReal MSBaseVehicle::myChosenSpeedFactor protected inherited
A precomputed factor by which the driver wants to be faster than the speed limit.
Definition at line 396 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getChosenSpeedFactor(), and MSBaseVehicle::setChosenSpeedFactor().
MSDevice_Transportable* MSVehicle::myContainerDevice protected
The containers this vehicle may have.
Definition at line 1401 of file MSVehicle.h.
Referenced by addContainer(), GUIVehicle::drawAction_drawPersonsAndContainers(), getContainerNumber(), getContainers(), and processNextStop().
MSRouteIterator MSBaseVehicle::myCurrEdge protected inherited
Iterator to current route-edge.
Definition at line 393 of file MSBaseVehicle.h.
Referenced by addStop(), enterLaneAtMove(), executeMove(), MSBaseVehicle::getCurrentRouteEdge(), getDistanceToPosition(), MSBaseVehicle::getEdge(), MSBaseVehicle::getRerouteOrigin(), getRerouteOrigin(), getRoutePosition(), MEVehicle::hasArrived(), hasArrived(), MSBaseVehicle::hasValidRoute(), leaveLane(), MEVehicle::loadState(), loadState(), MEVehicle::moveRoutePointer(), planMoveInternal(), MSVehicle::Influencer::postProcessVTD(), processNextStop(), replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), resetRoutePosition(), MEVehicle::saveState(), saveState(), MSBaseVehicle::succEdge(), updateBestLanes(), and willPass().
std::vector<LaneQ>::iterator MSVehicle::myCurrentLaneInBestLanes protected
Definition at line 1390 of file MSVehicle.h.
Referenced by updateBestLanes(), and updateOccupancyAndCurrentBestLane().
SUMOReal MSBaseVehicle::myDepartPos protected inherited
The real depart position.
Definition at line 416 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getDepartPos(), and MSBaseVehicle::onDepart().
SUMOTime MSBaseVehicle::myDeparture protected inherited
The real departure time.
Definition at line 413 of file MSBaseVehicle.h.
Referenced by enterLaneAtInsertion(), MSBaseVehicle::getDeparture(), MSBaseVehicle::hasDeparted(), MEVehicle::loadState(), loadState(), MSBaseVehicle::onDepart(), MEVehicle::saveState(), and saveState().
std::vector<MSDevice*> MSBaseVehicle::myDevices protected inherited
The devices this vehicle has.
Definition at line 410 of file MSBaseVehicle.h.
Referenced by addContainer(), addPerson(), MSBaseVehicle::getDevice(), MSBaseVehicle::getDevices(), GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIBaseVehicle::GUIBaseVehicle(), MSBaseVehicle::MSBaseVehicle(), and MSBaseVehicle::~MSBaseVehicle().
MSEdgeWeightsStorage* MSVehicle::myEdgeWeights mutable private
Definition at line 1558 of file MSVehicle.h.
Referenced by _getWeightsStorage(), and ~MSVehicle().
std::vector< MSLane * > MSVehicle::myEmptyLaneVector static protected
Definition at line 1391 of file MSVehicle.h.
Referenced by getBestLanesContinuation().
std::vector< MSTransportable * > MSVehicle::myEmptyTransportableVector static protected
Definition at line 1392 of file MSVehicle.h.
Referenced by getContainers(), and getPersons().
std::vector<MSLane*> MSVehicle::myFurtherLanes protected
The information into which lanes the vehicle laps into.
Definition at line 1407 of file MSVehicle.h.
Referenced by enterLaneAtInsertion(), enterLaneAtLaneChange(), executeMove(), getBackLane(), getBackPosition(), getBackPositionOnLane(), getCenterOnEdge(), getFurtherLanes(), getLatOffset(), GUIVehicle::getPreviousLane(), leaveLane(), and ~MSVehicle().
std::vector<SUMOReal> MSVehicle::myFurtherLanesPosLat protected
Definition at line 1408 of file MSVehicle.h.
Referenced by enterLaneAtInsertion(), enterLaneAtLaneChange(), executeMove(), getBackPosition(), getCenterOnEdge(), getFurtherLanesPosLat(), getLatOffset(), leaveLane(), and ~MSVehicle().
bool MSVehicle::myHaveToWaitOnNextLink protected
Definition at line 1422 of file MSVehicle.h.
Referenced by checkRewindLinkLanes(), and executeMove().
Influencer* MSVehicle::myInfluencer private
An instance of a velocity/lane influencing instance; built in "getInfluencer".
Definition at line 1565 of file MSVehicle.h.
Referenced by checkRewindLinkLanes(), executeMove(), getInfluencer(), getSpeedWithoutTraciInfluence(), hasInfluencer(), isRemoteControlled(), planMoveInternal(), and ~MSVehicle().
MSLane* MSVehicle::myLane protected
The lane the vehicle is on.
Definition at line 1382 of file MSVehicle.h.
Referenced by adaptLaneEntering2MoveReminder(), adaptToLeader(), adaptToLeaders(), addTraciBusOrContainerStop(), addTraciStop(), checkRewindLinkLanes(), computeAngle(), GUIVehicle::drawAction_drawRailCarriages(), enterLaneAtInsertion(), enterLaneAtLaneChange(), enterLaneAtMove(), executeMove(), getBackLane(), getBackPosition(), getBackPositionOnLane(), getCenterOnEdge(), getDistanceToPosition(), getLane(), getLaneIndex(), getLateralOverlap(), getLatOffset(), getLeader(), GUIVehicle::getParameterWindow(), getPosition(), getRerouteOrigin(), getRightSideOnLane(), getSlope(), influenceChangeDecision(), isFrontOnLane(), planMove(), planMoveInternal(), processNextStop(), replaceRoute(), resumeFromStopping(), GUIVehicle::selectBlockingFoes(), setTentativeLaneAndPosition(), unsafeLinkAhead(), and updateBestLanes().
MSAbstractLaneChangeModel* MSVehicle::myLaneChangeModel protected
Definition at line 1384 of file MSVehicle.h.
Referenced by enterLaneAtLaneChange(), getLaneChangeModel(), MSVehicle(), and ~MSVehicle().
const MSEdge* MSVehicle::myLastBestLanesEdge protected
Definition at line 1386 of file MSVehicle.h.
Referenced by enterLaneAtMove(), replaceRoute(), and updateBestLanes().
const MSLane* MSVehicle::myLastBestLanesInternalLane protected
Definition at line 1387 of file MSVehicle.h.
Referenced by replaceRoute(), and updateBestLanes().
DriveItemVector MSVehicle::myLFLinkLanes protected
Definition at line 1487 of file MSVehicle.h.
Referenced by GUIVehicle::drawAction_drawLinkItems(), executeMove(), onRemovalFromNet(), planMove(), GUIVehicle::selectBlockingFoes(), unsafeLinkAhead(), and ~MSVehicle().
MoveReminderCont MSBaseVehicle::myMoveReminders protected inherited
Current lane's move reminder.
Definition at line 406 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::activateReminders(), activateReminders(), adaptLaneEntering2MoveReminder(), addContainer(), addPerson(), MSBaseVehicle::addReminder(), GUIBaseVehicle::GUIBaseVehicle(), leaveLane(), MSBaseVehicle::MSBaseVehicle(), MSBaseVehicle::removeReminder(), MEVehicle::updateDetectorForWriting(), MEVehicle::updateDetectors(), and workOnMoveReminders().
int MSBaseVehicle::myNumberReroutes protected inherited
The number of reroutings.
Definition at line 425 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getNumberReroutes(), replaceRoute(), and MEVehicle::replaceRoute().
const SUMOVehicleParameter* MSBaseVehicle::myParameter protected inherited
This Vehicle's parameter.
Definition at line 384 of file MSBaseVehicle.h.
Referenced by addStop(), MSBaseVehicle::addStops(), MSBaseVehicle::calculateArrivalParams(), getContainerNumber(), MSBaseVehicle::getID(), MSBaseVehicle::getParameter(), GUIMEVehicle::getParameterWindow(), GUIVehicle::getParameterWindow(), getPersonNumber(), planMoveInternal(), MSBaseVehicle::reroute(), MSBaseVehicle::saveState(), updateBestLanes(), and MSBaseVehicle::~MSBaseVehicle().
MSDevice_Transportable* MSVehicle::myPersonDevice protected
The passengers this vehicle may have.
Definition at line 1398 of file MSVehicle.h.
Referenced by addPerson(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::getNumPassengers(), getPersonNumber(), getPersons(), and processNextStop().
const MSRoute* MSBaseVehicle::myRoute protected inherited
This Vehicle's route.
Definition at line 387 of file MSBaseVehicle.h.
Referenced by addStop(), MSBaseVehicle::addStops(), MSBaseVehicle::calculateArrivalParams(), GUIVehicle::drawRouteHelper(), executeMove(), getDistanceToPosition(), getRerouteOrigin(), MSBaseVehicle::getRoute(), getRoutePosition(), MEVehicle::hasArrived(), hasArrived(), MSBaseVehicle::hasValidRoute(), MEVehicle::moveRoutePointer(), MSBaseVehicle::MSBaseVehicle(), planMoveInternal(), replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), MSBaseVehicle::reroute(), resetRoutePosition(), MEVehicle::saveState(), MSBaseVehicle::saveState(), saveState(), MSBaseVehicle::succEdge(), updateBestLanes(), willPass(), and MSBaseVehicle::~MSBaseVehicle().
int MSVehicle::mySignals protected
State of things of the vehicle that can be on or off.
Definition at line 1411 of file MSVehicle.h.
Referenced by getSignals(), signalSet(), switchOffSignal(), and switchOnSignal().
State MSVehicle::myState protected
This Vehicles driving state (pos and speed)
Definition at line 1379 of file MSVehicle.h.
Referenced by adaptToLeaders(), addStop(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), checkRewindLinkLanes(), computeAngle(), congested(), MSLaneChanger::continueChange(), GUIVehicle::drawAction_drawRailCarriages(), enterLaneAtInsertion(), enterLaneAtLaneChange(), enterLaneAtMove(), executeMove(), fixPosition(), getBackPosition(), getBackPositionOnLane(), getCenterOnEdge(), getCO2Emissions(), getCOEmissions(), getElectricityConsumption(), getFuelConsumption(), getHarmonoise_NoiseEmissions(), getHCEmissions(), getLateralPositionOnLane(), getLatOffset(), getNOxEmissions(), getPMxEmissions(), getPosition(), getPositionOnLane(), getRerouteOrigin(), getRightSideOnLane(), getSpeed(), getSpeedWithoutTraciInfluence(), hasArrived(), leaveLane(), loadState(), onRemovalFromNet(), overlap(), planMoveInternal(), processNextStop(), saveState(), setTentativeLaneAndPosition(), MSLaneChangerSublane::startChangeSublane(), and updateFurtherLanes().
SUMOReal MSVehicle::myStopDist protected
distance to the next stop or -1 if there is none
Definition at line 1428 of file MSVehicle.h.
Referenced by nextStopDist(), and planMove().
std::list<Stop> MSVehicle::myStops protected
The vehicle's list of stops.
Definition at line 1395 of file MSVehicle.h.
Referenced by addContainer(), addPerson(), addStop(), addTraciBusOrContainerStop(), addTraciStop(), getNextStop(), getStopEdges(), GUIVehicle::getStopInfo(), hasArrived(), hasStops(), isParking(), isStopped(), isStoppedInRange(), isStoppedTriggered(), leaveLane(), planMoveInternal(), processNextStop(), replaceRoute(), resumeFromStopping(), and updateBestLanes().
const MSVehicleType* MSBaseVehicle::myType protected inherited
This Vehicle's type.
Definition at line 390 of file MSBaseVehicle.h.
Referenced by addStop(), MSBaseVehicle::calculateArrivalParams(), enterLaneAtInsertion(), executeMove(), getBackPosition(), getBackPositionOnLane(), getBoundingBox(), getBoundingPoly(), getCarFollowModel(), getCO2Emissions(), getCOEmissions(), getElectricityConsumption(), getFuelConsumption(), getHarmonoise_NoiseEmissions(), getHCEmissions(), MSBaseVehicle::getMaxSpeed(), getNOxEmissions(), getPMxEmissions(), getPositionOnLane(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), MSBaseVehicle::getVClass(), MSBaseVehicle::getVehicleType(), MSBaseVehicle::hasValidRoute(), processNextStop(), replaceVehicleType(), MSBaseVehicle::saveState(), updateBestLanes(), and ~MSVehicle().
SUMOTime MSVehicle::myWaitingTime protected
The time the vehicle waits (is not faster than 0.1m/s) in seconds.
Definition at line 1372 of file MSVehicle.h.
Referenced by enterLaneAtInsertion(), executeMove(), getWaitingSeconds(), getWaitingTime(), and resumeFromStopping().
WaitingTimeCollector MSVehicle::myWaitingTimeCollector protected
Definition at line 1376 of file MSVehicle.h.
Referenced by executeMove(), and getAccumulatedWaitingTime().
const SUMOTime MSBaseVehicle::NOT_YET_DEPARTED = SUMOTime_MAX static protected inherited
Definition at line 430 of file MSBaseVehicle.h.
Referenced by enterLaneAtInsertion(), and MSBaseVehicle::hasDeparted().
The documentation for this class was generated from the following files:
MSVehicle.h
MSVehicle.cpp