SUMO - Simulation of Urban MObility: GUIDetectorBuilder Class Reference
GUIDetectorBuilder Class Reference
Builds detectors for guisim.
#include <GUIDetectorBuilder.h>
Public Member Functions
MSDetectorFileOutput * buildMultiLaneE2Det (const std::string &id, DetectorUsage usage, MSLane *lane, SUMOReal pos, SUMOReal length, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold)
Builds an e2 detector that continues on preceeding lanes.
MSE2Collector * buildSingleLaneE2Det (const std::string &id, DetectorUsage usage, MSLane *lane, SUMOReal pos, SUMOReal length, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold)
Builds an e2 detector that lies on only one lane.
GUIDetectorBuilder (MSNet &net)
Constructor.
~GUIDetectorBuilder ()
Destructor.
Detector creating methods
Override NLDetectorBuilder methods.
virtual MSDetectorFileOutput * createInductLoop (const std::string &id, MSLane *lane, SUMOReal pos, bool splitByType, bool show=true)
Creates an instance of an e1 detector using the given values.
virtual MSDetectorFileOutput * createInstantInductLoop (const std::string &id, MSLane *lane, SUMOReal pos, const std::string &od)
Creates an instance of an e1 detector using the given values.
virtual MSE2Collector * createSingleLaneE2Detector (const std::string &id, DetectorUsage usage, MSLane *lane, SUMOReal pos, SUMOReal length, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold)
Creates an instance of an e2-detector (areal detector) using the given values.
virtual MSDetectorFileOutput * createMultiLaneE2Detector (const std::string &id, DetectorUsage usage, MSLane *lane, SUMOReal pos, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold)
Creates an instance of an e2ol-detector using the given values.
virtual MSDetectorFileOutput * createE3Detector (const std::string &id, const CrossSectionVector &entries, const CrossSectionVector &exits, SUMOReal haltingSpeedThreshold, SUMOTime haltingTimeThreshold)
Creates an instance of an e3 detector using the given values.
Value parsing and detector building methods
void buildInductLoop (const std::string &id, const std::string &lane, SUMOReal pos, SUMOTime splInterval, const std::string &device, bool friendlyPos, bool splitByType)
Builds an e1 detector and adds it to the net.
void buildInstantInductLoop (const std::string &id, const std::string &lane, SUMOReal pos, const std::string &device, bool friendlyPos)
Builds an instantenous induction and adds it to the net.
void buildE2Detector (const std::string &id, const std::string &lane, SUMOReal pos, SUMOReal length, bool cont, SUMOTime splInterval, const std::string &device, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold, bool friendlyPos)
Builds an e2 detector with a fixed interval and adds it to the net.
void buildE2Detector (const std::string &id, const std::string &lane, SUMOReal pos, SUMOReal length, bool cont, MSTLLogicControl::TLSLogicVariants &tlls, const std::string &device, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold, bool friendlyPos)
Builds an e2 detector connected to a lsa.
void buildE2Detector (const std::string &id, const std::string &lane, SUMOReal pos, SUMOReal length, bool cont, MSTLLogicControl::TLSLogicVariants &tlls, const std::string &tolane, const std::string &device, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold, bool friendlyPos)
Builds an e2 detector connected to a link's state.
void beginE3Detector (const std::string &id, const std::string &device, SUMOTime splInterval, SUMOReal haltingSpeedThreshold, SUMOTime haltingTimeThreshold)
Stores temporary the initial information about an e3 detector to build.
void addE3Entry (const std::string &lane, SUMOReal pos, bool friendlyPos)
Builds an entry point of an e3 detector.
void addE3Exit (const std::string &lane, SUMOReal pos, bool friendlyPos)
Builds an exit point of an e3 detector.
void endE3Detector ()
Builds of an e3 detector using collected values.
std::string getCurrentE3ID () const
Returns the id of the currently built e3 detector.
void buildVTypeProbe (const std::string &id, const std::string &vtype, SUMOTime frequency, const std::string &device)
Builds a vTypeProbe and adds it to the net.
void buildRouteProbe (const std::string &id, const std::string &edge, SUMOTime frequency, SUMOTime begin, const std::string &device)
Builds a routeProbe and adds it to the net.
Detector creating methods
Virtual, so they may be overwritten, for generating gui-versions of the detectors, for example.
void createEdgeLaneMeanData (const std::string &id, SUMOTime frequency, SUMOTime begin, SUMOTime end, const std::string &type, const bool useLanes, const bool withEmpty, const bool printDefaults, const bool withInternal, const bool trackVehicles, const SUMOReal maxTravelTime, const SUMOReal minSamples, const SUMOReal haltSpeed, const std::string &vTypes, const std::string &device)
Creates edge based mean data collector using the given specification.
Protected Member Functions
void convContE2PosLength (const std::string &id, MSLane *clane, SUMOReal &pos, SUMOReal &length, bool frinedly_pos)
Converts the length and the position information for an e2ol-detector.
void convUncontE2PosLength (const std::string &id, MSLane *clane, SUMOReal &pos, SUMOReal &length, bool frinedly_pos)
Converts the length and the position information for an e2 detector.
SUMOReal getPositionChecking (SUMOReal pos, MSLane *lane, bool friendlyPos, const std::string &detid)
Computes the position to use.
Value checking/adapting methods
MSEdge * getEdgeChecking (const std::string &edgeID, SumoXMLTag type, const std::string &detid)
Returns the named edge.
MSLane * getLaneChecking (const std::string &laneID, SumoXMLTag type, const std::string &detid)
Returns the named lane.
void checkSampleInterval (SUMOTime splInterval, SumoXMLTag type, const std::string &id)
Checks whether the given frequency (sample interval) is valid.
Protected Attributes
MSNet & myNet
The net to fill.
Detailed Description
Builds detectors for guisim.
This class overrides NLDetectorBuilder's detector creation methods in order to build guisim-classes instead of microsim-classes.
See also
NLDetectorBuilder
Definition at line 56 of file GUIDetectorBuilder.h.
Constructor & Destructor Documentation
GUIDetectorBuilder::GUIDetectorBuilder (MSNet & net)
Constructor.
Parameters
[in] net The network to which's detector control built detector shall be added
Definition at line 57 of file GUIDetectorBuilder.cpp.
GUIDetectorBuilder::~GUIDetectorBuilder ()
Destructor.
Definition at line 61 of file GUIDetectorBuilder.cpp.
Member Function Documentation
void NLDetectorBuilder::addE3Entry (const std::string & lane, SUMOReal pos, bool friendlyPos) inherited
Builds an entry point of an e3 detector.
If the lane is not known or the position information is not within the lane, an InvalidArgument is thrown. Otherwise a MSCrossSection is built using the obtained values and added to the list of entries of the e3 definition stored in "myE3Definition".
Parameters
[in] lane The id of the lane the entry shall be placed at
[in] pos The position on the lane the entry shall be placed at
[in] friendlyPos Whether the position information shall be used "friendly" (see user docs)
Exceptions
InvalidArgument If one of the values is invalid
Definition at line 273 of file NLDetectorBuilder.cpp.
References NLDetectorBuilder::getLaneChecking(), NLDetectorBuilder::getPositionChecking(), NLDetectorBuilder::myE3Definition, NLDetectorBuilder::E3DetectorDefinition::myEntries, NLDetectorBuilder::E3DetectorDefinition::myID, and SUMO_TAG_E3DETECTOR.
Referenced by NLHandler::addE3Entry().
void NLDetectorBuilder::addE3Exit (const std::string & lane, SUMOReal pos, bool friendlyPos) inherited
Builds an exit point of an e3 detector.
If the lane is not known or the position information is not within the lane, an InvalidArgument is thrown. Otherwise a MSCrossSection is built using the obtained values and added to the list of exits of the e3 definition stored in "myE3Definition".
Parameters
[in] lane The id of the lane the exit shall be placed at
[in] pos The position on the lane the exit shall be placed at
[in] friendlyPos Whether the position information shall be used "friendly" (see user docs)
Exceptions
InvalidArgument If one of the values is invalid
Definition at line 287 of file NLDetectorBuilder.cpp.
References NLDetectorBuilder::getLaneChecking(), NLDetectorBuilder::getPositionChecking(), NLDetectorBuilder::myE3Definition, NLDetectorBuilder::E3DetectorDefinition::myExits, NLDetectorBuilder::E3DetectorDefinition::myID, and SUMO_TAG_E3DETECTOR.
Referenced by NLHandler::addE3Exit().
void NLDetectorBuilder::beginE3Detector (const std::string & id, const std::string & device, SUMOTime splInterval, SUMOReal haltingSpeedThreshold, SUMOTime haltingTimeThreshold) inherited
Stores temporary the initial information about an e3 detector to build.
If the given sample interval is < 0, an InvalidArgument is thrown. Otherwise, the values are stored in a new instance of E3DetectorDefinition within "myE3Definition".
Parameters
[in] id The id the detector shall have
[in] device The output device the detector shall write into
[in] splInterval The aggregation time span the detector shall use
[in] haltingTimeThreshold Detector parameter: the time a vehicle's speed must be below haltingSpeedThreshold to be assigned as jammed
[in] haltingSpeedThreshold Detector parameter: the speed a vehicle's speed must be below to be assigned as jammed
Exceptions
InvalidArgument If one of the values is invalid
Definition at line 263 of file NLDetectorBuilder.cpp.
References NLDetectorBuilder::checkSampleInterval(), NLDetectorBuilder::myE3Definition, and SUMO_TAG_E3DETECTOR.
Referenced by NLHandler::beginE3Detector().
void NLDetectorBuilder::buildE2Detector (const std::string & id, const std::string & lane, SUMOReal pos, SUMOReal length, bool cont, SUMOTime splInterval, const std::string & device, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold, bool friendlyPos) inherited
Builds an e2 detector with a fixed interval and adds it to the net.
Checks the given values, first. If one of the values is invalid (lane is not known, sampling frequency<=0, position is larger than lane's length, length is too large, the id is already in use), an InvalidArgument is thrown.
Otherwise the e2 detector is built, either by calling "buildMultiLaneE2Det" if the detector shall continue on consecutive lanes, or by calling "buildSingleLaneE2Det" if it is a one-lane detector.
Parameters
[in] id The id the detector shall have
[in] lane The name of the lane the detector is placed at
[in] pos The definition of the position on the lane the detector shall be placed at
[in] length The definition of the length the detector shall have
[in] cont Whether the detector shall continue on predeceeding lanes
[in] splInterval The aggregation time span the detector shall use
[in] device The output device the detector shall write into
[in] haltingTimeThreshold Detector parameter: the time a vehicle's speed must be below haltingSpeedThreshold to be assigned as jammed
[in] haltingSpeedThreshold Detector parameter: the speed a vehicle's speed must be below to be assigned as jammed
[in] jamDistThreshold Detector parameter: the distance between two vehicles in order to not count them to one jam
[in] friendlyPos Whether the position information shall be used "friendly" (see user docs)
Exceptions
InvalidArgument If one of the values is invalid
Definition at line 133 of file NLDetectorBuilder.cpp.
References MSDetectorControl::add(), NLDetectorBuilder::buildMultiLaneE2Det(), NLDetectorBuilder::buildSingleLaneE2Det(), NLDetectorBuilder::checkSampleInterval(), NLDetectorBuilder::convContE2PosLength(), NLDetectorBuilder::convUncontE2PosLength(), DU_USER_DEFINED, MSNet::getDetectorControl(), NLDetectorBuilder::getLaneChecking(), NLDetectorBuilder::myNet, SUMO_TAG_E2DETECTOR, and SUMO_TAG_LANE_AREA_DETECTOR.
Referenced by NLHandler::addE2Detector().
void NLDetectorBuilder::buildE2Detector (const std::string & id, const std::string & lane, SUMOReal pos, SUMOReal length, bool cont, MSTLLogicControl::TLSLogicVariants & tlls, const std::string & device, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold, bool friendlyPos) inherited
Builds an e2 detector connected to a lsa.
Checks the given values, first. If one of the values is invalid (lane is not known, position is larger than lane's length, length is too large, the tls is not known, the id is already in use), an InvalidArgument is thrown.
Otherwise the e2 detector is built, either by calling "buildMultiLaneE2Det" if the detector shall continue on consecutive lanes, or by calling "buildSingleLaneE2Det" if it is a one-lane detector.
Parameters
[in] id The id the detector shall have
[in] lane The name of the lane the detector is placed at
[in] pos The definition of the position on the lane the detector shall be placed at
[in] length The definition of the length the detector shall have
[in] cont Whether the detector shall continue on predeceeding lanes
[in] tlls The tls the detector is assigned to
[in] device The output device the detector shall write into
[in] haltingTimeThreshold Detector parameter: the time a vehicle's speed must be below haltingSpeedThreshold to be assigned as jammed
[in] haltingSpeedThreshold Detector parameter: the speed a vehicle's speed must be below to be assigned as jammed
[in] jamDistThreshold Detector parameter: the distance between two vehicles in order to not count them to one jam
[in] friendlyPos Whether the position information shall be used "friendly" (see user docs)
Exceptions
InvalidArgument If one of the values is invalid
Definition at line 157 of file NLDetectorBuilder.cpp.
References MSDetectorControl::add(), NLDetectorBuilder::buildMultiLaneE2Det(), NLDetectorBuilder::buildSingleLaneE2Det(), NLDetectorBuilder::convContE2PosLength(), NLDetectorBuilder::convUncontE2PosLength(), DU_USER_DEFINED, MSTLLogicControl::TLSLogicVariants::getActive(), MSNet::getCurrentTimeStep(), MSNet::getDetectorControl(), OutputDevice::getDevice(), NLDetectorBuilder::getLaneChecking(), NLDetectorBuilder::myNet, SUMO_TAG_E2DETECTOR, and SUMO_TAG_LANE_AREA_DETECTOR.
void NLDetectorBuilder::buildE2Detector (const std::string & id, const std::string & lane, SUMOReal pos, SUMOReal length, bool cont, MSTLLogicControl::TLSLogicVariants & tlls, const std::string & tolane, const std::string & device, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold, bool friendlyPos) inherited
Builds an e2 detector connected to a link's state.
Checks the given values, first. If one of the values is invalid (lane is not known, position is larger than lane's length, length is too large, the tls or the destination lane is not known, the id is already in use), an InvalidArgument is thrown.
Otherwise the e2 detector is built, either by calling "buildMultiLaneE2Det" if the detector shall continue on consecutive lanes, or by calling "buildSingleLaneE2Det" if it is a one-lane detector.
Parameters
[in] id The id the detector shall have
[in] lane The name of the lane the detector is placed at
[in] pos The definition of the position on the lane the detector shall be placed at
[in] length The definition of the length the detector shall have
[in] cont Whether the detector shall continue on predeceeding lanes
[in] tlls The tls the detector is assigned to
[in] tolane The name of the lane to which the link to which the detector to build shall be assigned to points
[in] device The output device the detector shall write into
[in] haltingTimeThreshold Detector parameter: the time a vehicle's speed must be below haltingSpeedThreshold to be assigned as jammed
[in] haltingSpeedThreshold Detector parameter: the speed a vehicle's speed must be below to be assigned as jammed
[in] jamDistThreshold Detector parameter: the distance between two vehicles in order to not count them to one jam
[in] friendlyPos Whether the position information shall be used "friendly" (see user docs)
Exceptions
InvalidArgument If one of the values is invalid
Definition at line 186 of file NLDetectorBuilder.cpp.
References MSDetectorControl::add(), NLDetectorBuilder::buildMultiLaneE2Det(), NLDetectorBuilder::buildSingleLaneE2Det(), NLDetectorBuilder::convContE2PosLength(), NLDetectorBuilder::convUncontE2PosLength(), DU_USER_DEFINED, MSTLLogicControl::TLSLogicVariants::getActive(), MSLinkContHelper::getConnectingLink(), MSNet::getCurrentTimeStep(), MSNet::getDetectorControl(), OutputDevice::getDevice(), NLDetectorBuilder::getLaneChecking(), NLDetectorBuilder::myNet, SUMO_TAG_E2DETECTOR, and SUMO_TAG_LANE_AREA_DETECTOR.
void NLDetectorBuilder::buildInductLoop (const std::string & id, const std::string & lane, SUMOReal pos, SUMOTime splInterval, const std::string & device, bool friendlyPos, bool splitByType) inherited
Builds an e1 detector and adds it to the net.
Checks the given values, first. If one of the values is invalid (lane is not known, sampling frequency<=0, position is larger than lane's length, the id is already in use), an InvalidArgument is thrown.
Otherwise the e1 detector is built by calling "createInductLoop".
Internally, there is also a distinction whether a mesosim e1 detector shall be built.
Parameters
[in] id The id the detector shall have
[in] lane The name of the lane the detector is placed at
[in] pos The definition of the position on the lane the detector shall be placed at
[in] splInterval The aggregation time span the detector shall use
[in] device The output device the detector shall write into
[in] friendlyPos Whether the position information shall be used "friendly" (see user docs)
[in] splitByType Whether vehicle types shall be disaggregated
Exceptions
InvalidArgument If one of the values is invalid
Definition at line 102 of file NLDetectorBuilder.cpp.
References MSDetectorControl::add(), NLDetectorBuilder::checkSampleInterval(), NLDetectorBuilder::createInductLoop(), MSNet::getDetectorControl(), NLDetectorBuilder::getLaneChecking(), NLDetectorBuilder::getPositionChecking(), NLDetectorBuilder::myNet, SUMO_TAG_E1DETECTOR, and SUMO_TAG_INDUCTION_LOOP.
Referenced by NLHandler::addE1Detector().
void NLDetectorBuilder::buildInstantInductLoop (const std::string & id, const std::string & lane, SUMOReal pos, const std::string & device, bool friendlyPos) inherited
Builds an instantenous induction and adds it to the net.
Checks the given values, first. If one of the values is invalid (lane is not known, sampling frequency<=0, position is larger than lane's length, the id is already in use), an InvalidArgument is thrown.
Otherwise the e1 detector is built by calling "createInductLoop".
Parameters
[in] id The id the detector shall have
[in] lane The name of the lane the detector is placed at
[in] pos The definition of the position on the lane the detector shall be placed at
[in] device The output device the detector shall write into
[in] friendlyPos Whether the position information shall be used "friendly" (see user docs)
Exceptions
InvalidArgument If one of the values is invalid
Definition at line 118 of file NLDetectorBuilder.cpp.
References MSDetectorControl::add(), NLDetectorBuilder::createInstantInductLoop(), MSNet::getDetectorControl(), NLDetectorBuilder::getLaneChecking(), NLDetectorBuilder::getPositionChecking(), NLDetectorBuilder::myNet, and SUMO_TAG_INSTANT_INDUCTION_LOOP.
Referenced by NLHandler::addInstantE1Detector().
MSDetectorFileOutput * NLDetectorBuilder::buildMultiLaneE2Det (const std::string & id, DetectorUsage usage, MSLane * lane, SUMOReal pos, SUMOReal length, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold) inherited
Builds an e2 detector that continues on preceeding lanes.
Parameters
[in] id The id the detector shall have
[in] usage Information how the detector is used within the simulation
[in] lane The lane the detector is placed at
[in] pos The position on the lane the detector is placed at
[in] length The length the detector has
[in] haltingTimeThreshold Detector parameter: the time a vehicle's speed must be below haltingSpeedThreshold to be assigned as jammed
[in] haltingSpeedThreshold Detector parameter: the speed a vehicle's speed must be below to be assigned as jammed
[in] jamDistThreshold Detector parameter: the distance between two vehicles in order to not count them to one jam
Todo:
Check whether this method is really needful
Definition at line 367 of file NLDetectorBuilder.cpp.
References NLDetectorBuilder::createMultiLaneE2Detector().
Referenced by NLDetectorBuilder::buildE2Detector().
void NLDetectorBuilder::buildRouteProbe (const std::string & id, const std::string & edge, SUMOTime frequency, SUMOTime begin, const std::string & device) inherited
Builds a routeProbe and adds it to the net.
Checks the given values, first. If one of the values is invalid (sampling frequency<=0), an InvalidArgument is thrown.
Otherwise the routeProbe is built (directly).
Parameters
[in] id The id the detector shall have
[in] edge The name of the edge the detector shall observe
[in] frequency The reporting frequency
[in] begin The start of the first reporting interval
[in] device The output device the detector shall write into
Exceptions
InvalidArgument If one of the values is invalid
Definition at line 341 of file NLDetectorBuilder.cpp.
References MSDetectorControl::add(), NLDetectorBuilder::checkSampleInterval(), MSNet::getDetectorControl(), NLDetectorBuilder::getEdgeChecking(), NLDetectorBuilder::myNet, SUMO_TAG_ROUTEPROBE, and toString().
Referenced by NLHandler::addRouteProbeDetector().
MSE2Collector * NLDetectorBuilder::buildSingleLaneE2Det (const std::string & id, DetectorUsage usage, MSLane * lane, SUMOReal pos, SUMOReal length, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold) inherited
Builds an e2 detector that lies on only one lane.
Parameters
[in] id The id the detector shall have
[in] usage Information how the detector is used within the simulation
[in] lane The lane the detector is placed at
[in] pos The position on the lane the detector is placed at
[in] length The length the detector has
[in] haltingTimeThreshold Detector parameter: the time a vehicle's speed must be below haltingSpeedThreshold to be assigned as jammed
[in] haltingSpeedThreshold Detector parameter: the speed a vehicle's speed must be below to be assigned as jammed
[in] jamDistThreshold Detector parameter: the distance between two vehicles in order to not count them to one jam
Todo:
Check whether this method is really needful
Definition at line 354 of file NLDetectorBuilder.cpp.
References NLDetectorBuilder::createSingleLaneE2Detector().
Referenced by MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NLDetectorBuilder::buildE2Detector(), MSSOTLE2Sensors::buildSensorForLane(), and MSSOTLE2Sensors::buildSensorForOutLane().
void NLDetectorBuilder::buildVTypeProbe (const std::string & id, const std::string & vtype, SUMOTime frequency, const std::string & device) inherited
Builds a vTypeProbe and adds it to the net.
Checks the given values, first. If one of the values is invalid (sampling frequency<=0), an InvalidArgument is thrown.
Otherwise the vTypeProbe is built (directly).
Parameters
[in] id The id the detector shall have
[in] vtype The name of the vehicle type the detector shall observe
[in] frequency The reporting frequency
[in] device The output device the detector shall write into
Exceptions
InvalidArgument If one of the values is invalid
Definition at line 332 of file NLDetectorBuilder.cpp.
References NLDetectorBuilder::checkSampleInterval(), OutputDevice::getDevice(), and SUMO_TAG_VTYPEPROBE.
Referenced by NLHandler::addVTypeProbeDetector().
void NLDetectorBuilder::checkSampleInterval (SUMOTime splInterval, SumoXMLTag type, const std::string & id) protected inherited
Checks whether the given frequency (sample interval) is valid.
Parameters
[in] splInterval The sample interval
[in] type The type of the detector (for error message generation)
[in] id The id of the detector (for error message generation)
Exceptions
InvalidArgument If the given sample interval is invalid (<=0)
Todo:
Why is splInterval an int???
Definition at line 527 of file NLDetectorBuilder.cpp.
References toString().
Referenced by NLDetectorBuilder::beginE3Detector(), NLDetectorBuilder::buildE2Detector(), NLDetectorBuilder::buildInductLoop(), NLDetectorBuilder::buildRouteProbe(), and NLDetectorBuilder::buildVTypeProbe().
void NLDetectorBuilder::convContE2PosLength (const std::string & id, MSLane * clane, SUMOReal & pos, SUMOReal & length, bool frinedly_pos) protected inherited
Converts the length and the position information for an e2ol-detector.
Parameters
[in] id The id of the currently built detector (for error message generation)
[in] clane The lane the detector is placed at
[in,out] pos The position definition to convert
[in,out] length The length definition to convert
Exceptions
InvalidArgument If the defined position or the defined length is invalid
Definition at line 253 of file NLDetectorBuilder.cpp.
References NLDetectorBuilder::getPositionChecking().
Referenced by NLDetectorBuilder::buildE2Detector().
void NLDetectorBuilder::convUncontE2PosLength (const std::string & id, MSLane * clane, SUMOReal & pos, SUMOReal & length, bool frinedly_pos) protected inherited
Converts the length and the position information for an e2 detector.
Parameters
[in] id The id of the currently built detector (for error message generation)
[in] clane The lane the detector is placed at
[in,out] pos The position definition to convert
[in,out] length The length definition to convert
Exceptions
InvalidArgument If the defined position or the defined length is invalid
Definition at line 226 of file NLDetectorBuilder.cpp.
References Named::getID(), MSLane::getLength(), NLDetectorBuilder::getPositionChecking(), and SUMOReal.
Referenced by NLDetectorBuilder::buildE2Detector().
MSDetectorFileOutput * GUIDetectorBuilder::createE3Detector (const std::string & id, const CrossSectionVector & entries, const CrossSectionVector & exits, SUMOReal haltingSpeedThreshold, SUMOTime haltingTimeThreshold) virtual
Creates an instance of an e3 detector using the given values.
Simply calls the GUIE3Collector constructor.
Parameters
[in] id The id the detector shall have
[in] entries The list of this detector's entries
[in] exits The list of this detector's exits
[in] haltingSpeedThreshold Detector parameter: the speed a vehicle's speed must be below to be assigned as jammed
[in] haltingTimeThreshold Detector parameter: the time a vehicle's speed must be below haltingSpeedThreshold to be assigned as jammed
Reimplemented from NLDetectorBuilder.
Definition at line 106 of file GUIDetectorBuilder.cpp.
void NLDetectorBuilder::createEdgeLaneMeanData (const std::string & id, SUMOTime frequency, SUMOTime begin, SUMOTime end, const std::string & type, const bool useLanes, const bool withEmpty, const bool printDefaults, const bool withInternal, const bool trackVehicles, const SUMOReal maxTravelTime, const SUMOReal minSamples, const SUMOReal haltSpeed, const std::string & vTypes, const std::string & device) inherited
Creates edge based mean data collector using the given specification.
Parameters
[in] id The id the detector shall have
[in] frequency The aggregation interval the detector shall use
[in] begin dump begin time
[in] end dump end time
[in] type The type of values to be generated
[in] useLanes Information whether lane-based or edge-based dump shall be generated
[in] withEmpty Information whether empty lanes/edges shall be written
[in] withInternal Information whether internal lanes/edges shall be written
[in] trackVehicles Information whether information shall be collected per vehicle
[in] maxTravelTime the maximum travel time to output
[in] minSamples the minimum number of sample seconds before the values are valid
[in] haltSpeed the maximum speed to consider a vehicle waiting
[in] vTypes the set of vehicle types to consider
Exceptions
InvalidArgument If one of the values is invalid
Definition at line 450 of file NLDetectorBuilder.cpp.
References MSDetectorControl::add(), MSNet::getDetectorControl(), MSNet::getInstance(), StringTokenizer::hasNext(), StringTokenizer::next(), SUMOTime_MAX, and WRITE_WARNING.
Referenced by NLHandler::addEdgeLaneMeanData().
MSDetectorFileOutput * GUIDetectorBuilder::createInductLoop (const std::string & id, MSLane * lane, SUMOReal pos, bool splitByType, bool show = true) virtual
Creates an instance of an e1 detector using the given values.
Simply calls the GUIInductLoop constructor
Parameters
[in] id The id the detector shall have
[in] lane The lane the detector is placed at
[in] pos The position on the lane the detector is placed at
[in] splitByType Whether additional information split by vehicle classes shall be generated
[in] show Whether to show the detector in the gui if available
Reimplemented from NLDetectorBuilder.
Definition at line 65 of file GUIDetectorBuilder.cpp.
References NLDetectorBuilder::createInductLoop(), MSLane::getEdge(), MSGlobals::gMesoNet, and MSGlobals::gUseMesoSim.
MSDetectorFileOutput * GUIDetectorBuilder::createInstantInductLoop (const std::string & id, MSLane * lane, SUMOReal pos, const std::string & od) virtual
Creates an instance of an e1 detector using the given values.
Simply calls the MSInductLoop constructor
Parameters
[in] id The id the detector shall have
[in] lane The lane the detector is placed at
[in] pos The position on the lane the detector is placed at
[in] od The output device the loop shall use
Reimplemented from NLDetectorBuilder.
Definition at line 79 of file GUIDetectorBuilder.cpp.
References OutputDevice::getDevice().
MSDetectorFileOutput * GUIDetectorBuilder::createMultiLaneE2Detector (const std::string & id, DetectorUsage usage, MSLane * lane, SUMOReal pos, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold) virtual
Creates an instance of an e2ol-detector using the given values.
Simply calls the GUI_E2_ZS_CollectorOverLanes constructor. After this call, the detector must be initialised.
Parameters
[in] id The id the detector shall have
[in] lane The lane the detector is placed at
[in] pos The position on the lane the detector is placed at
[in] length The length the detector has
[in] haltingTimeThreshold Detector parameter: the time a vehicle's speed must be below haltingSpeedThreshold to be assigned as jammed
[in] haltingSpeedThreshold Detector parameter: the speed a vehicle's speed must be below to be assigned as jammed
[in] jamDistThreshold Detector parameter: the distance between two vehicles in order to not count them to one jam
Reimplemented from NLDetectorBuilder.
Definition at line 96 of file GUIDetectorBuilder.cpp.
MSE2Collector * GUIDetectorBuilder::createSingleLaneE2Detector (const std::string & id, DetectorUsage usage, MSLane * lane, SUMOReal pos, SUMOReal length, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold) virtual
Creates an instance of an e2-detector (areal detector) using the given values.
Simply calls the GUI_E2_ZS_Collector constructor
Parameters
[in] id The id the detector shall have
[in] lane The lane the detector is placed at
[in] pos The position on the lane the detector is placed at
[in] length The length the detector has
[in] haltingTimeThreshold Detector parameter: the time a vehicle's speed must be below haltingSpeedThreshold to be assigned as jammed
[in] haltingSpeedThreshold Detector parameter: the speed a vehicle's speed must be below to be assigned as jammed
[in] jamDistThreshold Detector parameter: the distance between two vehicles in order to not count them to one jam
Reimplemented from NLDetectorBuilder.
Definition at line 86 of file GUIDetectorBuilder.cpp.
void NLDetectorBuilder::endE3Detector () inherited
Builds of an e3 detector using collected values.
The parameter collected are used to build an e3 detector using "createE3Detector". The resulting detector is added to the net.
Parameters
[in] lane The id of the lane the exit shall be placed at
[in] pos The position on the lane the exit shall be placed at
Exceptions
InvalidArgument If one of the values is invalid
Definition at line 310 of file NLDetectorBuilder.cpp.
References MSDetectorControl::add(), NLDetectorBuilder::createE3Detector(), MSNet::getDetectorControl(), NLDetectorBuilder::E3DetectorDefinition::myDevice, NLDetectorBuilder::myE3Definition, NLDetectorBuilder::E3DetectorDefinition::myEntries, NLDetectorBuilder::E3DetectorDefinition::myExits, NLDetectorBuilder::E3DetectorDefinition::myHaltingSpeedThreshold, NLDetectorBuilder::E3DetectorDefinition::myHaltingTimeThreshold, NLDetectorBuilder::E3DetectorDefinition::myID, NLDetectorBuilder::myNet, NLDetectorBuilder::E3DetectorDefinition::mySampleInterval, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E3DETECTOR, SUMO_TAG_ENTRY_EXIT_DETECTOR, toString(), and WRITE_WARNING.
Referenced by NLHandler::endE3Detector().
std::string NLDetectorBuilder::getCurrentE3ID () const inherited
Returns the id of the currently built e3 detector.
This is used for error-message generation only. If no id is known, "<unknown>" is returned.
Returns
The id of the currently processed e3 detector
Definition at line 301 of file NLDetectorBuilder.cpp.
References NLDetectorBuilder::myE3Definition, and NLDetectorBuilder::E3DetectorDefinition::myID.
Referenced by NLHandler::addE3Entry(), and NLHandler::addE3Exit().
MSEdge * NLDetectorBuilder::getEdgeChecking (const std::string & edgeID, SumoXMLTag type, const std::string & detid) protected inherited
Returns the named edge.
Parameters
[in] edgeID The id of the lane
[in] type The type of the detector (for error message generation)
[in] detid The id of the currently built detector (for error message generation)
Exceptions
InvalidArgument If the named edge is not known
Definition at line 503 of file NLDetectorBuilder.cpp.
References MSEdge::dictionary(), and toString().
Referenced by NLDetectorBuilder::buildRouteProbe().
MSLane * NLDetectorBuilder::getLaneChecking (const std::string & laneID, SumoXMLTag type, const std::string & detid) protected inherited
Returns the named lane.
Parameters
[in] laneID The id of the lane
[in] type The type of the detector (for error message generation)
[in] detid The id of the currently built detector (for error message generation)
Exceptions
InvalidArgument If the named lane is not known
Definition at line 515 of file NLDetectorBuilder.cpp.
References MSLane::dictionary(), and toString().
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), NLDetectorBuilder::buildE2Detector(), NLDetectorBuilder::buildInductLoop(), and NLDetectorBuilder::buildInstantInductLoop().
SUMOReal NLDetectorBuilder::getPositionChecking (SUMOReal pos, MSLane * lane, bool friendlyPos, const std::string & detid) protected inherited
Computes the position to use.
At first, it is checked whether the given position is negative. If so, the position is added to the lane's length to obtain the position counted backwards.
If the resulting position is beyond or in front (<0) of the lane, it is either set to the according lane's boundary (.1 or length-.1) if friendlyPos is set, or, if friendlyPos is not set, an InvalidArgument is thrown.
Parameters
[in] pos Definition of the position on the lane
[in] lane The lane the position must be valid for
[in] friendlyPos Whether false positions shall be made acceptable
[in] detid The id of the currently built detector (for error message generation)
Exceptions
InvalidArgument If the defined position is invalid
Definition at line 424 of file NLDetectorBuilder.cpp.
References Named::getID(), MSLane::getLength(), and SUMOReal.
Referenced by NLDetectorBuilder::addE3Entry(), NLDetectorBuilder::addE3Exit(), NLDetectorBuilder::buildInductLoop(), NLDetectorBuilder::buildInstantInductLoop(), NLDetectorBuilder::convContE2PosLength(), and NLDetectorBuilder::convUncontE2PosLength().
Field Documentation
MSNet& NLDetectorBuilder::myNet protected inherited
The net to fill.
Definition at line 602 of file NLDetectorBuilder.h.
Referenced by NLDetectorBuilder::buildE2Detector(), NLDetectorBuilder::buildInductLoop(), NLDetectorBuilder::buildInstantInductLoop(), NLDetectorBuilder::buildRouteProbe(), and NLDetectorBuilder::endE3Detector().
The documentation for this class was generated from the following files:
GUIDetectorBuilder.h
GUIDetectorBuilder.cpp