SUMO - Simulation of Urban MObility: XMLSubSys Class Reference
XMLSubSys Class Reference
Utility methods for initialising, closing and using the XML-subsystem.
#include <XMLSubSys.h>
Static Public Member Functions
static void close ()
Closes the xml-subsystem.
static SUMOSAXReader * getSAXReader (SUMOSAXHandler &handler)
Builds a reader and assigns the handler to it.
static void init ()
Initialises the xml-subsystem.
static bool runParser (GenericSAXHandler &handler, const std::string &file, const bool isNet=false)
Runs the given handler on the given file; returns if everything's ok.
static void setHandler (GenericSAXHandler &handler)
Sets the given handler for the default reader.
static void setValidation (const std::string &validationScheme, const std::string &netValidationScheme)
Enables or disables validation.
Static Private Attributes
static XERCES_CPP_NAMESPACE::SAX2XMLReader::ValSchemes myNetValidationScheme = XERCES_CPP_NAMESPACE::SAX2XMLReader::Val_Auto
Information whether built reader/parser shall validate SUMO networks against schemata.
static int myNextFreeReader
Information whether the reader is parsing.
static std::vector< SUMOSAXReader * > myReaders
The XML Readers used for repeated parsing.
static XERCES_CPP_NAMESPACE::SAX2XMLReader::ValSchemes myValidationScheme = XERCES_CPP_NAMESPACE::SAX2XMLReader::Val_Auto
Information whether built reader/parser shall validate XML-documents against schemata.
Detailed Description
Utility methods for initialising, closing and using the XML-subsystem.
The Xerces-parsers need an initialisation and should also be closed.
As we use xerces for both the input files and the configuration we would have to check whether the system was initialised before. Instead, we call XMLSubSys::init(bool) once at the beginning of our application and XMLSubSys::close() at the end.
Closing and initialising the XML subsystem is necessary. Still, we never encountered any problems with it. Once, after some modifications, SUMO crashed when closing the XML sub system. The reason was a memory leak within the microsim-module. On initialisation, a SAX2XMLReader is built which can be used during later process. It is destroyed when the subsystem is closed.
In addition to initialisation and shutdown, this module allows to build SAXReaders and/or running a given handler on a given file without dealing with the reader at all.
Todo:
make schema checking optional
Definition at line 73 of file XMLSubSys.h.
Member Function Documentation
void XMLSubSys::close () static
Closes the xml-subsystem.
Deletes the built reader and calls XMLPlatformUtils::Terminate();
Definition at line 92 of file XMLSubSys.cpp.
References myReaders.
Referenced by SystemFrame::close().
SUMOSAXReader * XMLSubSys::getSAXReader (SUMOSAXHandler & handler) static
Builds a reader and assigns the handler to it.
Tries to build a SAX2XMLReader using "getSAXReader()". If this fails, 0 is returned. Otherwise, the given handler is assigned to the reader as the current DefaultHandler and ErrorHandler.
Parameters
[in] handler The handler to assign to the built reader
Returns
The built Xerces-SAX-reader, 0 if something failed
See also
getSAXReader()
Definition at line 102 of file XMLSubSys.cpp.
References myValidationScheme.
Referenced by GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), main(), and SUMORouteLoader::SUMORouteLoader().
void XMLSubSys::init () static
Initialises the xml-subsystem.
Calls XMLPlatformUtils::Initialize(). If this fails, the exception is caught and its content is reported using a ProcessError.
Exceptions
ProcessError If the initialisation fails
Definition at line 58 of file XMLSubSys.cpp.
References TplConvert::_2str(), and myNextFreeReader.
Referenced by main().
bool XMLSubSys::runParser (GenericSAXHandler & handler, const std::string & file, const bool isNet = false) static
Runs the given handler on the given file; returns if everything's ok.
Uses the reader built on init() which is stored in myReader to parse the given file.
All exceptions are catched and reported to the error-instance of the MsgHandler. Also, if the reader could not be built, this is reported.
The method returns true if everything went ok. This means, that the reader could be built, no exception was caught, and nothing was reported to the error-instance of the MsgHandler.
Parameters
[in] handler The handler to assign to the built reader
[in] file The file to run the parser at
[in] isNet whether a network gets loaded
Returns
true if the parsing was done without errors, false otherwise (error was printed)
Definition at line 114 of file XMLSubSys.cpp.
References MsgHandler::getErrorInstance(), GenericSAXHandler::getFileName(), myNetValidationScheme, myNextFreeReader, myReaders, myValidationScheme, GenericSAXHandler::setFileName(), MsgHandler::wasInformed(), and WRITE_ERROR.
Referenced by NIImporter_SUMO::_loadNetwork(), NLBuilder::build(), GUISettingsHandler::GUISettingsHandler(), AGActivityGen::importInfoCity(), NLBuilder::load(), NIImporter_OpenStreetMap::load(), ODDistrictCont::loadDistricts(), ShapeHandler::loadFiles(), PCLoaderOSM::loadIfSet(), PCLoaderXML::loadIfSet(), loadJTRDefinitions(), ODMatrix::loadMatrix(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_OpenDrive::loadNetwork(), ODMatrix::loadRoutes(), ROLoader::loadWeights(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), MSCalibrator::MSCalibrator(), MSLaneSpeedTrigger::MSLaneSpeedTrigger(), GNEApplicationWindow::onCmdOpenAdditionals(), GNEApplicationWindow::onCmdOpenShapes(), GUIApplicationWindow::onCmdOpenShapes(), NLTriggerBuilder::parseAndBuildRerouter(), readDetectors(), and GenericSAXHandler::startElement().
void XMLSubSys::setHandler (GenericSAXHandler & handler) static
Sets the given handler for the default reader.
Uses the reader built on init() which is stored in myReader.
Parameters
[in] handler The handler to assign to the built reader
Definition at line 108 of file XMLSubSys.cpp.
References myNextFreeReader, and myReaders.
Referenced by GenericSAXHandler::endElement(), and GenericSAXHandler::registerParent().
void XMLSubSys::setValidation (const std::string & validationScheme, const std::string & netValidationScheme) static
Enables or disables validation.
The setting is only valid for parsers created after the call. Existing parsers are not adapted.
Parameters
[in] validationScheme Whether validation of XML-documents against schemata shall be enabled
[in] netValidationScheme Whether validation of SUMO networks against schemata shall be enabled
Definition at line 69 of file XMLSubSys.cpp.
References myNetValidationScheme, and myValidationScheme.
Referenced by main(), GNELoadThread::run(), and GUILoadThread::run().
Field Documentation
XERCES_CPP_NAMESPACE::SAX2XMLReader::ValSchemes XMLSubSys::myNetValidationScheme = XERCES_CPP_NAMESPACE::SAX2XMLReader::Val_Auto static private
Information whether built reader/parser shall validate SUMO networks against schemata.
Definition at line 162 of file XMLSubSys.h.
Referenced by runParser(), and setValidation().
int XMLSubSys::myNextFreeReader static private
Information whether the reader is parsing.
Definition at line 156 of file XMLSubSys.h.
Referenced by init(), runParser(), and setHandler().
std::vector< SUMOSAXReader * > XMLSubSys::myReaders static private
The XML Readers used for repeated parsing.
Definition at line 153 of file XMLSubSys.h.
Referenced by close(), runParser(), and setHandler().
XERCES_CPP_NAMESPACE::SAX2XMLReader::ValSchemes XMLSubSys::myValidationScheme = XERCES_CPP_NAMESPACE::SAX2XMLReader::Val_Auto static private
Information whether built reader/parser shall validate XML-documents against schemata.
Definition at line 159 of file XMLSubSys.h.
Referenced by getSAXReader(), runParser(), and setValidation().
The documentation for this class was generated from the following files:
XMLSubSys.h
XMLSubSys.cpp