SUMO - Simulation of Urban MObility: OutputFormatter Class Reference
OutputFormatter Class Reference abstract
Abstract base class for output formatters.
#include <OutputFormatter.h>
Public Member Functions
virtual bool closeTag (std::ostream &into)=0
Closes the most recently opened tag.
virtual void openTag (std::ostream &into, const std::string &xmlElement)=0
Opens an XML tag.
virtual void openTag (std::ostream &into, const SumoXMLTag &xmlElement)=0
Opens an XML tag.
virtual void writePreformattedTag (std::ostream &into, const std::string &val)=0
virtual bool writeXMLHeader (std::ostream &into, const std::string &rootElement, const std::string &attrs="", const std::string &comment="")=0
Writes an XML header with optional configuration.
virtual ~OutputFormatter ()
Destructor.
Detailed Description
Abstract base class for output formatters.
OutputFormatter format XML like output into the output stream. There are only two implementation at the moment, "normal" XML and binary XML.
Definition at line 59 of file OutputFormatter.h.
Constructor & Destructor Documentation
virtual OutputFormatter::~OutputFormatter () inline virtual
Destructor.
Definition at line 62 of file OutputFormatter.h.
References closeTag(), openTag(), writePreformattedTag(), and writeXMLHeader().
Member Function Documentation
virtual bool OutputFormatter::closeTag (std::ostream & into) pure virtual
Closes the most recently opened tag.
Parameters
[in] into The output stream to use
Returns
Whether a further element existed in the stack and could be closed
Todo:
it is not verified that the topmost element was closed
Implemented in BinaryFormatter, and PlainXMLFormatter.
Referenced by OutputDevice::closeTag(), and ~OutputFormatter().
virtual void OutputFormatter::openTag (std::ostream & into, const std::string & xmlElement) pure virtual
Opens an XML tag.
An indentation, depending on the current xml-element-stack size, is written followed by the given xml element ("<" + xmlElement) The xml element is added to the stack, then.
Parameters
[in] into The output stream to use
[in] xmlElement Name of element to open
Returns
The OutputDevice for further processing
Implemented in BinaryFormatter, and PlainXMLFormatter.
Referenced by OutputDevice::openTag(), and ~OutputFormatter().
virtual void OutputFormatter::openTag (std::ostream & into, const SumoXMLTag & xmlElement) pure virtual
Opens an XML tag.
Helper method which finds the correct string before calling openTag.
Parameters
[in] into The output stream to use
[in] xmlElement Id of the element to open
Implemented in BinaryFormatter, and PlainXMLFormatter.
virtual void OutputFormatter::writePreformattedTag (std::ostream & into, const std::string & val) pure virtual
Implemented in BinaryFormatter, and PlainXMLFormatter.
Referenced by OutputDevice::writePreformattedTag(), and ~OutputFormatter().
virtual bool OutputFormatter::writeXMLHeader (std::ostream & into, const std::string & rootElement, const std::string & attrs = "", const std::string & comment = "") pure virtual
Writes an XML header with optional configuration.
If something has been written (myXMLStack is not empty), nothing is written and false returned.
Parameters
[in] into The output stream to use
[in] rootElement The root element to use
[in] attrs Additional attributes to save within the rootElement
[in] comment Additional comment (saved in front the rootElement)
Todo:
Check which parameter is used herein
Describe what is saved
Implemented in BinaryFormatter, and PlainXMLFormatter.
Referenced by OutputDevice::writeXMLHeader(), and ~OutputFormatter().
The documentation for this class was generated from the following file:
OutputFormatter.h