SUMO - Simulation of Urban MObility: MSSOTLE2Sensors.cpp File Reference
MSSOTLE2Sensors.cpp File Reference
#include <utils/common/TplConvert.h>
#include <microsim/output/MSDetectorControl.h>
#include <microsim/MSEdge.h>
#include <microsim/MSVehicleType.h>
#include "MSSOTLE2Sensors.h"
Functions
std::vector< std::string > & split (const std::string &s, char delim, std::vector< std::string > &elems)
std::string trim (std::string &str)
Detailed Description
Author
Gianfilippo Slager
Alessio Bonfietti
Federico Caselli
Date
2010-02-25
Version
Id
MSSOTLE2Sensors.cpp 21202 2016-07-19 13:40:35Z behrisch
Definition in file MSSOTLE2Sensors.cpp.
Function Documentation
std::vector<std::string>& split (const std::string & s, char delim, std::vector< std::string > & elems)
Definition at line 512 of file MSSOTLE2Sensors.cpp.
Referenced by NBEdge::buildInnerEdges(), ROEdge::getTravelTime(), and MSSOTLE2Sensors::setVehicleWeigths().
std::string trim (std::string & str)
Definition at line 506 of file MSSOTLE2Sensors.cpp.
Referenced by MSSOTLE2Sensors::setVehicleWeigths().