SUMO - Simulation of Urban MObility: NBContHelper Class Reference
NBContHelper Class Reference
#include <NBContHelper.h>
Data Structures
class edge_by_angle_to_nodeShapeCentroid_sorter
class edge_by_priority_sorter
class edge_opposite_direction_sorter
Class to sort edges by their angle in relation to the given edge.
class edge_similar_direction_sorter
class edge_with_destination_finder
class node_with_incoming_finder
class node_with_outgoing_finder
class opposite_finder
class relative_incoming_edge_sorter
class relative_outgoing_edge_sorter
class same_connection_edge_sorter
class straightness_sorter
Static Public Member Functions
static NBEdge * findConnectingEdge (const EdgeVector &edges, NBNode *from, NBNode *to)
static SUMOReal getMaxSpeed (const EdgeVector &edges)
static SUMOReal getMinSpeed (const EdgeVector &edges)
static SUMOReal maxSpeed (const EdgeVector &ev)
static void nextCCW (const EdgeVector &edges, EdgeVector::const_iterator &from)
static void nextCW (const EdgeVector &edges, EdgeVector::const_iterator &from)
static std::ostream & out (std::ostream &os, const std::vector< bool > &v)
Friends
std::ostream & operator<< (std::ostream &os, const EdgeVector &ev)
Detailed Description
NBContHelper Some static helper methods that traverse a sorted list of edges in both directions
Definition at line 56 of file NBContHelper.h.
Member Function Documentation
NBEdge * NBContHelper::findConnectingEdge (const EdgeVector & edges, NBNode * from, NBNode * to) static
Tries to return the first edge within the given container which connects both given nodes
Definition at line 79 of file NBContHelper.cpp.
References SUMOReal.
SUMOReal NBContHelper::getMaxSpeed (const EdgeVector & edges) static
Definition at line 267 of file NBContHelper.cpp.
References SUMOReal.
SUMOReal NBContHelper::getMinSpeed (const EdgeVector & edges) static
Definition at line 282 of file NBContHelper.cpp.
References SUMOReal.
SUMOReal NBContHelper::maxSpeed (const EdgeVector & ev) static
returns the maximum speed allowed on the edges
Definition at line 92 of file NBContHelper.cpp.
References max, and SUMOReal.
Referenced by NBTrafficLightDefinition::computeBrakingTime().
void NBContHelper::nextCCW (const EdgeVector & edges, EdgeVector::const_iterator & from) static
Moves the given iterator counter clockwise within the given container of edges sorted clockwise
Definition at line 60 of file NBContHelper.cpp.
Referenced by NBRequest::computeRightOutgoingLinkCrossings(), and NBNode::getDirection().
void NBContHelper::nextCW (const EdgeVector & edges, EdgeVector::const_iterator & from) static
Moves the given iterator clockwise within the given container of edges sorted clockwise
Definition at line 51 of file NBContHelper.cpp.
Referenced by NBRequest::computeLeftOutgoingLinkCrossings(), NBNode::edgesBetween(), NBNode::getDirection(), NBNode::getEdgesThatApproach(), NBRampsComputer::getOffRampEdges(), NBRampsComputer::getOnRampEdges(), NBEdgeCont::guessRoundabouts(), NBNode::isLeftMover(), NBNode::isSimpleContinuation(), and NBRequest::setBlocking().
std::ostream & NBContHelper::out (std::ostream & os, const std::vector< bool > & v) static
writes the vector of bools to the given stream
Definition at line 70 of file NBContHelper.cpp.
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const EdgeVector & ev) friend
Definition at line 253 of file NBContHelper.cpp.
Referenced by NBContHelper::same_connection_edge_sorter::getMinMaxRelAngles().
The documentation for this class was generated from the following files:
NBContHelper.h
NBContHelper.cpp