SUMO - Simulation of Urban MObility: bezier.cpp File Reference
bezier.cpp File Reference
#include <config.h>
#include <math.h>
#include <iostream>
#include <utils/common/StdDefs.h>
#include "PositionVector.h"
Functions
SUMOReal Basis (int n, int i, SUMOReal t)
void bezier (int npts, SUMOReal b[], int cpts, SUMOReal p[])
PositionVector bezier (const PositionVector &init, int numPoints)
SUMOReal factrl (int n)
SUMOReal Ni (int n, int i)
Detailed Description
Author
Daniel Krajzewicz
Michael Behrisch
Date
2003-11-19
Version
Id
bezier.cpp 21154 2016-07-12 14:23:01Z namdre
Definition in file bezier.cpp.
Function Documentation
SUMOReal Basis (int n, int i, SUMOReal t)
Definition at line 92 of file bezier.cpp.
References Ni(), and SUMOReal.
Referenced by bezier().
void bezier (int npts, SUMOReal b[], int cpts, SUMOReal p[])
Definition at line 101 of file bezier.cpp.
References Basis(), and SUMOReal.
Referenced by bezier(), NBNode::computeSmoothShape(), NWWriter_OpenDrive::writeGeomSmooth(), and NWWriter_OpenDrive::writeNetwork().
PositionVector bezier (const PositionVector & init, int numPoints)
Definition at line 138 of file bezier.cpp.
References bezier(), ISNAN(), SUMOReal, Position::x(), and Position::y().
SUMOReal factrl (int n)
Definition at line 62 of file bezier.cpp.
References SUMOReal.
Referenced by Ni().
SUMOReal Ni (int n, int i)
Definition at line 86 of file bezier.cpp.
References factrl().
Referenced by Basis().