SUMO - Simulation of Urban MObility: gl2psTestSimple.c File Reference
gl2psTestSimple.c File Reference
#include <GL/glut.h>
#include <string.h>
#include "gl2ps.h"
Functions
static void display (void)
static void keyboard (unsigned char key, int x, int y)
int main (int argc, char **argv)
Function Documentation
static void display (void) static
Definition at line 53 of file gl2psTestSimple.c.
References GL2PS_LINE_STIPPLE, gl2psDisable(), gl2psEnable(), and gl2psText().
Referenced by keyboard(), and main().
static void keyboard (unsigned char key, int x, int y) static
Definition at line 94 of file gl2psTestSimple.c.
References display(), GL2PS_DRAW_BACKGROUND, GL2PS_EPS, GL2PS_OVERFLOW, GL2PS_SIMPLE_SORT, GL2PS_USE_CURRENT_VIEWPORT, gl2psBeginPage(), and gl2psEndPage().
Referenced by main().
int main (int argc, char ** argv)
Definition at line 121 of file gl2psTestSimple.c.
References display(), and keyboard().