SUMO - Simulation of Urban MObility: GNERouteProbe Class Reference
GNERouteProbe Class Reference
#include <GNERouteProbe.h>
Public Member Functions
void decRef (const std::string &debugMsg="")
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawName (const Position &pos, const SUMOReal scale, const GUIVisualizationTextSettings &settings, const SUMOReal angle=0) const
draw name of item
const std::string & getAdditionalID () const
returns the ID of additional
GNEAdditionalSet * getAdditionalSetParent () const
get additionalSet parent, or NULL if don't belongs to an additionalSet
std::vector< SumoXMLAttr > getAttrs () const
get vector of attributes
int getBegin () const
get begin of RouteProbe
template<>
int getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
SUMOReal getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
bool getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::string getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< int > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< SUMOReal > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< bool > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< std::string > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
virtual std::string getDescription ()
how should this attribute carrier be called
GNEEdge * getEdge () const
get edge in which the RouteProbe is placed
std::string getFilename () const
get filename of RouteProbe
int getFrequency () const
get frequency of RouteProbe
const std::string getID () const
function to support debugging
virtual GNELane * getLane () const
get lane of additional, or NULL if additional isn't placed over a Lane
Position getPositionInView () const
Returns position of RouteProbe in view.
PositionVector getShape () const
Returns additional element's shape.
SumoXMLTag getTag () const
get Tag assigned to this object
GNEViewNet * getViewNet () const
Returns a pointer to GNEViewNet in which additional element is located.
GNERouteProbe (const std::string &id, GNEViewNet *viewNet, GNEEdge *edge, int frequency, const std::string &filename, int begin, bool blocked)
Constructor.
void incRef (const std::string &debugMsg="")
bool isAdditionalBlocked () const
Check if additional item is currently blocked (i.e. cannot be moved with mouse)
bool isAdditionalInspectionable () const
check if additional element is inspectionable (With GNEInspectorFrame)
bool isAdditionalMovable () const
check if additional element is movable
bool isAdditionalSelectable () const
check if additional element is selectable (With GNESelectorFrame)
bool isAdditionalSelected () const
void moveAdditional (SUMOReal, SUMOReal, GNEUndoList *)
change the position of the RouteProbe geometry
virtual void openAdditionalDialog ()
open Additional Dialog
template<>
int parse (const std::string &string)
template<>
SUMOReal parse (const std::string &string)
template<>
bool parse (const std::string &string)
void removeEdgeReference ()
remove reference to edge
virtual void removeLaneReference ()
if additional is placed over a lane, remove it reference
void setAdditionalID (const std::string &id)
set the ID of additional
void setBegin (int begin)
set begin of RouteProbe
void setBlocked (bool value)
Block or unblock additional element(i.e. cannot be moved with mouse)
void setFilename (std::string filename)
set filename of RouteProbe
void setFrequency (int frequency)
set frequency of RouteProbe
void setPositionInView (const Position &pos)
set new position in the view
bool unreferenced ()
void updateGeometry ()
update pre-computed geometry information
void writeAdditional (OutputDevice &device, const std::string &)
writte additional element into a xml file
~GNERouteProbe ()
Destructor.
inherited from GUIGlObject
Returns the name of the parent object
Returns
This object's parent id
const std::string & getParentName () const
Returns the name of the parent object (if any)
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
inherited from GNEAttributeCarrier
std::string getAttribute (SumoXMLAttr key) const
void setAttribute (SumoXMLAttr key, const std::string &value, GNEUndoList *undoList)
bool isValid (SumoXMLAttr key, const std::string &value)
inherited from GUIGlObject
Returns the name of the parent object
Returns
This object's parent id
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window (optional)
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static const std::vector< SumoXMLTag > & allowedAdditionalTags ()
get all editable tags for additionals
static const std::vector< std::pair< SumoXMLAttr, std::string > > & allowedAttributes (SumoXMLTag tag)
get all editable attributes for tag and their default values.
static const std::vector< SumoXMLTag > & allowedNetElementTags ()
get all editable tags for netElements
static const std::vector< SumoXMLTag > & allowedTags ()
get all editable for tag.
template<typename T >
static bool canParse (const std::string &string)
true if a number of type T can be parsed from string
static const std::vector< std::string > & discreteChoices (SumoXMLTag tag, SumoXMLAttr attr)
return a list of discrete choices for this attribute or an empty vector
static bool discreteCombinableChoices (SumoXMLTag tag, SumoXMLAttr attr)
return whether the given attribute allows for a combination of discrete values
template<typename T >
static T getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
return the default value of the attribute of an element
static std::string getDefinition (SumoXMLTag tag, SumoXMLAttr attr)
return definition of a certain SumoXMLAttr
static int getHigherNumberOfAttributes ()
return the number of attributes of the tag with the most highter number of attributes
static SumoXMLTag getParentType (SumoXMLTag tag)
get parent's tag of a certain additional element
static bool hasAttribute (SumoXMLTag tag, SumoXMLAttr attr)
check if a element with certain tag has a certain attribute
static bool hasParent (SumoXMLTag tag)
check if a element with certain tag has another additional element as parent
static bool isBool (SumoXMLAttr attr)
whether an attribute is of type bool
static bool isDiscrete (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is Discrete
static bool isFloat (SumoXMLAttr attr)
whether an attribute is numerical of type float
static bool isInt (SumoXMLAttr attr)
whether an attribute is numerical or type int
static bool isList (SumoXMLAttr attr)
whether an attribute is of type bool
static bool isNumerical (SumoXMLAttr attr)
whether an attribute is numerical (int or float)
template<typename T >
static bool isPositive (const std::string &string)
true if a positive number of type T can be parsed from string
static bool isString (SumoXMLAttr attr)
whether an attribute is of type string
static bool isUnique (SumoXMLAttr attr)
whether an attribute is unique (may not be edited for a multi-selection)
static bool isValidFileValue (const std::string &value)
true if value is a valid file value
static bool isValidID (const std::string &value)
true if value is a valid sumo ID
static bool isValidStringVector (const std::string &value)
true if value is a valid string vector
template<typename T >
static T parse (const std::string &string)
parses a number of type T from string
Static Public Attributes
static const std::string APPROVED = "approved"
feature has been approved but not changed (i.e. after being reguessed)
static const std::string GUESSED = "guessed"
feature has been reguessed (may still be unchanged be we can't tell (yet)
static const GUIGlID INVALID_ID = 0
static const std::string LOADED = "loaded"
feature is still unchanged after being loaded (implies approval)
static const std::string MODIFIED = "modified"
feature has been manually modified (implies approval)
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
GNEAdditionalDialog * myAdditionalDialog
pointer to additional dialog
GNEAdditionalSet * myAdditionalSetParent
pointer to additional set parent, if belong to set
RGBColor myBaseColor
base color (Default green)
RGBColor myBaseColorSelected
base color selected (Default blue)
int myBegin
begin of rerouter
bool myBlocked
boolean to check if additional element is blocked (i.e. cannot be moved with mouse)
GNEEdge * myEdge
edge of routeProbe
std::string myFilename
filename of RouteProbe
int myFrequency
Frequency of RouteProbe.
bool myInspectionable
boolean to check if additional element is inspectionable (With GNEInspectorFrame). By default true
bool myMovable
boolean to check if additional element is movable (with the mouse). By default true
Position myPosition
The position in which this additional element is located.
bool myRotationLefthand
rotation depending of the option "Lefthand"
Position myRouteProbeLogoOffset
route probe logo offset
bool mySelectable
boolean to check if additional element is selectable (With GNESelectorFrame). By default true
PositionVector myShape
The shape of the additional element.
GNEViewNet * myViewNet
The GNEViewNet this additional element belongs.
int numberOfLanes
number of lanes of edge (To improve efficiency)
computed only once (for performance) in updateGeometry()
The rotations of the shape parts
std::vector< SUMOReal > myShapeRotations
std::vector< SUMOReal > myShapeLengths
The lengths of the shape parts.
Private Member Functions
GNERouteProbe (const GNERouteProbe &)
Invalidated copy constructor.
GNERouteProbe & operator= (const GNERouteProbe &)
Invalidated assignment operator.
void setAttribute (SumoXMLAttr key, const std::string &value)
set attribute after validation
members and functions relative to block icon
set Rotation of block Icon
Note
must be called in updateGeometry() after setting of Shape, and use parameter "lane" if additional is placed over a lane
Position myBlockIconPosition
position of the block icon
Position myBlockIconOffset
The offSet of the block icon.
SUMOReal myBlockIconRotation
The rotation of the block icon.
void setBlockIconRotation (GNELane *lane=NULL)
void drawLockIcon (SUMOReal size=0.5) const
draw lock icon
Detailed Description
Definition at line 48 of file GNERouteProbe.h.
Constructor & Destructor Documentation
GNERouteProbe::GNERouteProbe (const std::string & id, GNEViewNet * viewNet, GNEEdge * edge, int frequency, const std::string & filename, int begin, bool blocked)
Constructor.
Parameters
[in] id The storage of gl-ids to get the one for this lane representation from
[in] viewNet pointer to GNEViewNet of this additional element belongs
[in] edge edge in which this routeProbe is placed
[in] frequency The frequency in which to report the distribution
[in] filename The file for generated output
[in] begin The time at which to start generating output
[in] blocked set initial blocking state of item
Definition at line 68 of file GNERouteProbe.cpp.
References GNEEdge::addAdditional(), GUISUMOAbstractView::centerTo(), GUIGlObject::getGlID(), myEdge, GNEAdditional::myMovable, GNEAdditional::myViewNet, and updateGeometry().
GNERouteProbe::~GNERouteProbe ()
Destructor.
Definition at line 85 of file GNERouteProbe.cpp.
References myEdge, and GNEEdge::removeAdditional().
GNERouteProbe::GNERouteProbe (const GNERouteProbe &) private
Invalidated copy constructor.
Member Function Documentation
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 258 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedAdditionalTags () static inherited
get all editable tags for additionals
Definition at line 391 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedAdditionalTags, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VAPORIZER, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::GNEAdditionalFrame(), GNEAdditionalFrame::onCmdSelectAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
const std::vector< std::pair< SumoXMLAttr, std::string > > & GNEAttributeCarrier::allowedAttributes (SumoXMLTag tag) static inherited
get all editable attributes for tag and their default values.
Definition at line 186 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, SUMO_ATTR_ALLOW, SUMO_ATTR_BEGIN, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CONT, SUMO_ATTR_CONTPOS, SUMO_ATTR_DISALLOW, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_END, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_LANE, SUMO_ATTR_LANES, SUMO_ATTR_LENGTH, SUMO_ATTR_LINES, SUMO_ATTR_NAME, SUMO_ATTR_NUMLANES, SUMO_ATTR_OFF, SUMO_ATTR_OUTPUT, SUMO_ATTR_PASS, SUMO_ATTR_POSITION, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_SHAPE, SUMO_ATTR_SPEED, SUMO_ATTR_SPLIT_VTYPE, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_STARTTIME, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_TYPE, SUMO_ATTR_UNCONTROLLED, SUMO_ATTR_WIDTH, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_POI, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VAPORIZER, SUMO_TAG_VSS, toString(), and WRITE_WARNING.
Referenced by GNEAttributeCarrier::getAttrs(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNEAttributeCarrier::hasAttribute(), GNESelectorFrame::onCmdSelMBString(), GNESelectorFrame::onCmdSelMBTag(), GNEAdditionalFrame::setParametersOfAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedNetElementTags () static inherited
get all editable tags for netElements
Definition at line 378 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedNetElementTags, SUMO_TAG_CONNECTION, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, and SUMO_TAG_LANE.
Referenced by GNEAttributeCarrier::~GNEAttributeCarrier().
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedTags () static inherited
get all editable for tag.
Definition at line 352 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedTags, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VAPORIZER, and SUMO_TAG_VSS.
Referenced by GNEAttributeCarrier::getHigherNumberOfAttributes(), GNESelectorFrame::GNESelectorFrame(), GNEAttributeCarrier::isBool(), GNESelectorFrame::onCmdSelMBString(), GNESelectorFrame::onCmdSelMBTag(), and GNEAttributeCarrier::~GNEAttributeCarrier().
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 187 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 196 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 177 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GNECrossing::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 237 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 206 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 249 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 219 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 228 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIBaseVehicle::getPopUpMenu().
template<typename T > static bool GNEAttributeCarrier::canParse (const std::string & string) inline static inherited
true if a number of type T can be parsed from string
Definition at line 168 of file GNEAttributeCarrier.h.
References GNEAttributeCarrier::parse().
void GNEReferenceCounter::decRef (const std::string & debugMsg = "") inline inherited
Definition at line 61 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), GNEReferenceCounter::myCount, toString(), and UNUSED_PARAMETER.
Referenced by GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GNEEdge::removeLane(), GNEInspectorFrame::setEdgeTemplate(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_Connection::~GNEChange_Connection(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_TLS::~GNEChange_TLS(), and GNEInspectorFrame::~GNEInspectorFrame().
const std::vector< std::string > & GNEAttributeCarrier::discreteChoices (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return a list of discrete choices for this attribute or an empty vector
Definition at line 548 of file GNEAttributeCarrier.cpp.
References StringBijection< T >::getStrings(), SUMOXMLDefinitions::LaneSpreadFunctions, GNEAttributeCarrier::myDiscreteChoices, NODETYPE_DEAD_END_DEPRECATED, SUMOXMLDefinitions::NodeTypes, SUMO_ATTR_ALLOW, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CONT, SUMO_ATTR_DISALLOW, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_OFF, SUMO_ATTR_PRIORITY, SUMO_ATTR_SPLIT_VTYPE, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_TYPE, SUMO_ATTR_UNCONTROLLED, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_REROUTER, SumoVehicleClassStrings, and toString().
Referenced by GNEInspectorFrame::AttrEditor::AttrEditor(), GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isDiscrete(), GNEInspectorFrame::AttrEditor::onCmdReset(), GNEInspectorFrame::AttrInput::onCmdSetAttribute(), GNEInspectorFrame::AttrInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::discreteCombinableChoices (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return whether the given attribute allows for a combination of discrete values
Definition at line 602 of file GNEAttributeCarrier.cpp.
References SUMO_ATTR_ALLOW, and SUMO_ATTR_DISALLOW.
Referenced by GNEInspectorFrame::AttrInput::onCmdSetAttribute(), GNEInspectorFrame::AttrInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
void GNERouteProbe::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GNEAdditional.
Definition at line 216 of file GNERouteProbe.cpp.
References GUIVisualizationSettings::addName, GUIVisualizationSettings::addSize, GNEAdditional::drawLockIcon(), GUIGlObject::drawName(), GUITexturesHelper::drawTexturedBox(), GNEAdditional::getCenteringBoundary(), GUIVisualizationSizeSettings::getExaggeration(), GUITextureSubSys::getGif(), GUIGlObject::getGlID(), GUIGlObject::getType(), GNETEXTURE_ROUTEPROBE, GNETEXTURE_ROUTEPROBESELECTED, GNEAdditional::isAdditionalSelected(), GNEAdditional::myShape, GNEAdditional::myShapeRotations, numberOfLanes, GUIVisualizationSettings::scale, and SUMOReal.
void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIBaseVehicle, GUIPerson, and GUIContainer.
Definition at line 156 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
void GNEAdditional::drawLockIcon (SUMOReal size = 0.5) const protected inherited
draw lock icon
Definition at line 327 of file GNEAdditional.cpp.
References GUITexturesHelper::drawTexturedBox(), GUITextureSubSys::getGif(), GUIGlObject::getType(), GNETEXTURE_EMPTY, GNETEXTURE_EMPTYSELECTED, GNETEXTURE_LOCK, GNETEXTURE_LOCKSELECTED, GNETEXTURE_NOTMOVING, GNETEXTURE_NOTMOVINGSELECTED, GNEAdditional::isAdditionalSelected(), GNEAdditional::myBlocked, GNEAdditional::myBlockIconOffset, GNEAdditional::myBlockIconPosition, GNEAdditional::myBlockIconRotation, GNEAdditional::myMovable, Position::x(), and Position::y().
Referenced by GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE3::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSignal::drawGL(), drawGL(), GNEChargingStation::drawGL(), and GNERerouter::drawGL().
void GUIGlObject::drawName (const Position & pos, const SUMOReal scale, const GUIVisualizationTextSettings & settings, const SUMOReal angle = 0) const inherited
draw name of item
Definition at line 286 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE3::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GUIPolygon::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), drawGL(), GNEEdge::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIEdge::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GNERerouter::drawGL(), and GUIBaseVehicle::drawOnPos().
const std::string & GNEAdditional::getAdditionalID () const inherited
returns the ID of additional
Definition at line 103 of file GNEAdditional.cpp.
References GUIGlObject::getMicrosimID().
Referenced by GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorE2::getAttribute(), GNEBusStop::getAttribute(), GNEContainerStop::getAttribute(), GNEDetectorE3::getAttribute(), GNEVaporizer::getAttribute(), GNEVariableSpeedSignal::getAttribute(), getAttribute(), GNEChargingStation::getAttribute(), GNECalibrator::getAttribute(), and GNERerouter::getAttribute().
GNEAdditionalSet * GNEAdditional::getAdditionalSetParent () const inherited
get additionalSet parent, or NULL if don't belongs to an additionalSet
Definition at line 151 of file GNEAdditional.cpp.
References GNEAdditional::myAdditionalSetParent.
Referenced by GNENet::deleteAdditional(), and GNENet::insertAdditional().
std::string GNERouteProbe::getAttribute (SumoXMLAttr key) const virtual
Implements GNEAdditional.
Definition at line 287 of file GNERouteProbe.cpp.
References GNEAdditional::getAdditionalID(), GNEAttributeCarrier::getID(), GUIGlObject::getType(), myBegin, myEdge, myFilename, myFrequency, SUMO_ATTR_BEGIN, SUMO_ATTR_EDGE, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, and toString().
Referenced by setAttribute().
std::vector< SumoXMLAttr > GNEAttributeCarrier::getAttrs () const inherited
get vector of attributes
Definition at line 107 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), and GNEAttributeCarrier::myTag.
Referenced by GNEAdditional::getParameterWindow(), GNEAdditional::getPopUpMenu(), GNEAttributeCarrier::isValid(), and GNEAttributeCarrier::~GNEAttributeCarrier().
int GNERouteProbe::getBegin () const
get begin of RouteProbe
Definition at line 186 of file GNERouteProbe.cpp.
References myBegin.
Boundary GNEAdditional::getCenteringBoundary () const virtual inherited
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
Implements GUIGlObject.
Definition at line 304 of file GNEAdditional.cpp.
References PositionVector::getBoxBoundary(), Boundary::grow(), and GNEAdditional::myShape.
Referenced by GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE3::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSignal::drawGL(), drawGL(), GNEChargingStation::drawGL(), GNECalibrator::drawGL(), and GNERerouter::drawGL().
template<typename T > static T GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return the default value of the attribute of an element
Note
It's advisable to check before with function hasDefaultValue if exits a default value
Referenced by GNEAdditionalFrame::additionalParameters::addAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
template<> int GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 752 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, TplConvert::_str2int(), SUMOReal, toString(), and WRITE_WARNING.
template<> SUMOReal GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 765 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, TplConvert::_str2SUMOReal(), toString(), and WRITE_WARNING.
template<> bool GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 778 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, TplConvert::_str2Bool(), toString(), and WRITE_WARNING.
template<> std::string GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 791 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, toString(), and WRITE_WARNING.
template<> std::vector<int> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 804 of file GNEAttributeCarrier.cpp.
References toString(), and WRITE_WARNING.
template<> std::vector<SUMOReal> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 814 of file GNEAttributeCarrier.cpp.
References toString(), and WRITE_WARNING.
template<> std::vector<bool> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 824 of file GNEAttributeCarrier.cpp.
References toString(), and WRITE_WARNING.
template<> std::vector<std::string> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 834 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, SUMOSAXAttributes::parseStringVector(), toString(), and WRITE_WARNING.
std::string GNEAttributeCarrier::getDefinition (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return definition of a certain SumoXMLAttr
Definition at line 608 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAttrDefinitions, SUMO_ATTR_ALLOW, SUMO_ATTR_BEGIN, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CONT, SUMO_ATTR_CONTPOS, SUMO_ATTR_DISALLOW, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_LANE, SUMO_ATTR_LANES, SUMO_ATTR_LENGTH, SUMO_ATTR_LINES, SUMO_ATTR_NAME, SUMO_ATTR_NUMLANES, SUMO_ATTR_OFF, SUMO_ATTR_OUTPUT, SUMO_ATTR_PASS, SUMO_ATTR_POSITION, SUMO_ATTR_PREFER, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_SHAPE, SUMO_ATTR_SPEED, SUMO_ATTR_SPLIT_VTYPE, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_TYPE, SUMO_ATTR_UNCONTROLLED, SUMO_ATTR_WIDTH, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_POI, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::additionalParameters::onCmdHelp(), and GNEAttributeCarrier::~GNEAttributeCarrier().
std::string GNEAttributeCarrier::getDescription () virtual inherited
how should this attribute carrier be called
Definition at line 95 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myTag, and toString().
Referenced by GNEChange_Attribute::redoName(), GNEAdditionalFrame::removeAdditional(), GNEChange_Attribute::undoName(), and GNEAttributeCarrier::~GNEAttributeCarrier().
GNEEdge * GNERouteProbe::getEdge () const virtual
get edge in which the RouteProbe is placed
Reimplemented from GNEAdditional.
Definition at line 163 of file GNERouteProbe.cpp.
References myEdge.
std::string GNERouteProbe::getFilename () const
get filename of RouteProbe
Definition at line 174 of file GNERouteProbe.cpp.
References myFilename.
int GNERouteProbe::getFrequency () const
get frequency of RouteProbe
Definition at line 180 of file GNERouteProbe.cpp.
References myFrequency.
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 111 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 123 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GUIVehicle::drawAction_drawPersonsAndContainers(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE3::drawGL(), GNEInternalLane::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), drawGL(), GNELane::drawGL(), GNEEdge::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), GUIEdge::drawGL(), GNEConnection::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GNERerouter::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GUIContainer::getColorValue(), GNEJunction::getColorValue(), GUIPerson::getColorValue(), GNELane::getColorValue(), GUILane::getColorValue(), GUIEdge::getIDs(), GNEEdge::getLaneGlIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNECalibrator::GNECalibrator(), GNERouteProbe(), GNEVaporizer::GNEVaporizer(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onLeftBtnPress(), GUISUMOAbstractView::removeAdditionalGLVisualisation(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUIVehicle::selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), and GUIGlObject::~GUIGlObject().
int GNEAttributeCarrier::getHigherNumberOfAttributes () static inherited
return the number of attributes of the tag with the most highter number of attributes
Definition at line 740 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), and GNEAttributeCarrier::allowedTags().
Referenced by GNEInspectorFrame::GNEInspectorFrame(), and GNEAttributeCarrier::~GNEAttributeCarrier().
const std::string GNEAttributeCarrier::getID () const virtual inherited
function to support debugging
Implements GNEReferenceCounter.
Definition at line 117 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::getAttribute(), and SUMO_ATTR_ID.
Referenced by GNEAdditionalFrame::addAdditional(), GNENet::addReversedEdge(), GNENet::deleteAdditional(), GNEAdditionalFrame::generateID(), GNEVaporizer::getAttribute(), getAttribute(), GNECalibrator::getAttribute(), GNEAdditionalHandler::getPosition(), GNENet::insertAdditional(), GNENet::reverseEdge(), GNEJunction::setLogicValid(), GNENet::updateAdditionalID(), GNEDetectorEntry::writeAdditional(), GNEDetectorExit::writeAdditional(), GNEChargingStation::writeAdditional(), GNEDetectorE1::writeAdditional(), GNEVaporizer::writeAdditional(), writeAdditional(), GNEDetectorE2::writeAdditional(), GNEContainerStop::writeAdditional(), GNEBusStop::writeAdditional(), GNEVariableSpeedSignal::writeAdditional(), GNEDetectorE3::writeAdditional(), GNECalibrator::writeAdditional(), GNERerouter::writeAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
GNELane * GNEAdditional::getLane () const virtual inherited
get lane of additional, or NULL if additional isn't placed over a Lane
Note
if additional is placed over a lane, this function has to be implemented in the children (See StoppingPlaces and Detectors)
Reimplemented in GNEDetector, and GNEStoppingPlace.
Definition at line 186 of file GNEAdditional.cpp.
Referenced by GNEViewNet::onLeftBtnPress(), and GNEViewNet::onMouseMove().
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 137 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNEPOI::getAttribute(), GNECrossing::getAttribute(), GNEJunction::getAttribute(), GNEPoly::getAttribute(), GNEEdge::getAttribute(), GNELane::getAttribute(), GNELane::getParentName(), GNENetElement::getParentName(), GNEDetectorE3::getParentName(), GNEVaporizer::getParentName(), GNEVariableSpeedSignal::getParentName(), getParentName(), GNEStoppingPlace::getParentName(), GNECalibrator::getParentName(), GNEDetector::getParentName(), GNEAdditional::getParentName(), GNERerouter::getParentName(), GNEAdditional::getPopUpMenu(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GNEEdge::moveGeometry(), GNEPoly::moveGeometry(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEViewNet::onCmdNodeShape(), GNEViewNet::onLeftBtnPress(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNENet::replaceJunctionByGeometry(), GNENet::retrieveAttributeCarriers(), GNEAdditional::setAdditionalID(), GNEEdge::setAttribute(), GNENet::splitEdge(), and GNEConnectorFrame::updateDescription().
GUIParameterTableWindow * GNEAdditional::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
complet with the rest of parameters
Implements GUIGlObject.
Definition at line 280 of file GNEAdditional.cpp.
References GUIParameterTableWindow::closeBuilding(), GNEAdditional::getAttribute(), GNEAttributeCarrier::getAttrs(), GNEAttributeCarrier::isUnique(), GUIParameterTableWindow::mkItem(), toString(), and UNUSED_PARAMETER.
const std::string & GNERouteProbe::getParentName () const virtual
Returns the name of the parent object (if any)
Returns
This object's parent id
Implements GNEAdditional.
Definition at line 210 of file GNERouteProbe.cpp.
References GUIGlObject::getMicrosimID(), and myEdge.
SumoXMLTag GNEAttributeCarrier::getParentType (SumoXMLTag tag) static inherited
get parent's tag of a certain additional element
Definition at line 123 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::hasParent(), GNEAttributeCarrier::myAllowedAdditionalWithParentTags, and SUMO_TAG_NOTHING.
Referenced by GNEAdditionalFrame::setParametersOfAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
GUIGLObjectPopupMenu * GNEAdditional::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 210 of file GNEAdditional.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), GUIGlObject::buildShowParamsPopupEntry(), GNEAttributeCarrier::getAttrs(), GNEEdge::getLanes(), GUIGlObject::getMicrosimID(), GNEViewNet::getNet(), GNEAdditional::getParentName(), GUISUMOAbstractView::getPositionInformation(), GNELane::getShape(), GNEAttributeCarrier::getTag(), MID_COPY_NAME, MID_COPY_TYPED_NAME, GNEAdditional::myPosition, GNEAdditional::myShape, GNEAdditional::myViewNet, PositionVector::nearest_offset_to_point2D(), GNENet::retrieveEdge(), GNENet::retrieveLane(), SUMO_ATTR_EDGE, SUMO_ATTR_LANE, SUMOReal, toString(), Position::x(), and Position::y().
Position GNERouteProbe::getPositionInView () const virtual
Returns position of RouteProbe in view.
Implements GNEAdditional.
Definition at line 131 of file GNERouteProbe.cpp.
References GNEEdge::getLanes(), myEdge, GNEAdditional::myPosition, Position::x(), and Position::y().
PositionVector GNEAdditional::getShape () const inherited
Returns additional element's shape.
Definition at line 115 of file GNEAdditional.cpp.
References GNEAdditional::myShape.
SumoXMLTag GNEAttributeCarrier::getTag () const inherited
get Tag assigned to this object
Definition at line 101 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myTag.
Referenced by GNENet::deleteAdditional(), GNESelectorFrame::getMatches(), GNEAdditional::getPopUpMenu(), GNENet::insertAdditional(), GNEDetectorExit::isValid(), GNEDetectorEntry::isValid(), GNEDetectorE1::isValid(), GNEDetectorE2::isValid(), GNEBusStop::isValid(), GNEContainerStop::isValid(), GNEDetectorE3::isValid(), GNEVaporizer::isValid(), GNEVariableSpeedSignal::isValid(), isValid(), GNEChargingStation::isValid(), GNECalibrator::isValid(), GNERerouter::isValid(), GNEViewNet::onLeftBtnPress(), GNENet::updateAdditionalID(), GNEDetectorEntry::writeAdditional(), GNEDetectorExit::writeAdditional(), GNEDetectorE1::writeAdditional(), GNEChargingStation::writeAdditional(), GNEVaporizer::writeAdditional(), writeAdditional(), GNEDetectorE2::writeAdditional(), GNEContainerStop::writeAdditional(), GNEBusStop::writeAdditional(), GNEVariableSpeedSignal::writeAdditional(), GNEDetectorE3::writeAdditional(), GNECalibrator::writeAdditional(), GNERerouter::writeAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 150 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEAdditionalSet::drawConnections(), GNEDetector::drawDetectorIcon(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE3::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), drawGL(), GNELane::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GNERerouter::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorE2::getAttribute(), GNEContainerStop::getAttribute(), GNEBusStop::getAttribute(), GNEDetectorE3::getAttribute(), GNEVaporizer::getAttribute(), GNEVariableSpeedSignal::getAttribute(), getAttribute(), GNEChargingStation::getAttribute(), GNECalibrator::getAttribute(), GNERerouter::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNEJunction::getColorValue(), GNELane::getColorValue(), GUILane::getColorValue(), GNEViewNet::getEdgeAtCursorPosition(), GNEViewNet::getEdgesAtCursorPosition(), GNEViewNet::getJunctionAtCursorPosition(), GNEViewNet::getLaneAtCurserPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEDetectorE1::isValid(), GNEDetectorE2::isValid(), GNEContainerStop::isValid(), GNEBusStop::isValid(), GNEDetectorE3::isValid(), GNEVaporizer::isValid(), GNEVariableSpeedSignal::isValid(), isValid(), GNEChargingStation::isValid(), GNECalibrator::isValid(), GNERerouter::isValid(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onDoubleClicked(), GNEViewNet::onLeftBtnPress(), LayeredRTree::selectLayer(), GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEDetectorE1::setAttribute(), GNEDetectorE2::setAttribute(), GNEBusStop::setAttribute(), GNEContainerStop::setAttribute(), GNEDetectorE3::setAttribute(), GNEVaporizer::setAttribute(), GNEVariableSpeedSignal::setAttribute(), setAttribute(), GNEChargingStation::setAttribute(), GNECalibrator::setAttribute(), GNERerouter::setAttribute(), GNEJunction::setColor(), and GUISelectedStorage::toggleSelection().
GUIParameterTableWindow * GUIGlObject::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own type parameter window (optional)
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Reimplemented in GUIVehicle, GUIBaseVehicle, and GUIMEVehicle.
Definition at line 129 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
Referenced by GUIGLObjectPopupMenu::onCmdShowTypePars().
GNEViewNet * GNEAdditional::getViewNet () const inherited
Returns a pointer to GNEViewNet in which additional element is located.
Definition at line 109 of file GNEAdditional.cpp.
References GNEAdditional::myViewNet.
Referenced by GNEStoppingPlace::changeLane(), GNEDetector::changeLane(), GNEDetectorExit::setAttribute(), GNEDetectorE1::setAttribute(), GNEDetectorEntry::setAttribute(), GNEBusStop::setAttribute(), GNEContainerStop::setAttribute(), GNEDetectorE2::setAttribute(), GNEDetectorE3::setAttribute(), GNEVaporizer::setAttribute(), GNEVariableSpeedSignal::setAttribute(), setAttribute(), GNEChargingStation::setAttribute(), GNECalibrator::setAttribute(), and GNERerouter::setAttribute().
bool GNEAttributeCarrier::hasAttribute (SumoXMLTag tag, SumoXMLAttr attr) static inherited
check if a element with certain tag has a certain attribute
Definition at line 536 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes().
Referenced by GNEAdditionalFrame::addAdditional(), GNEAdditionalFrame::setParametersOfAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::hasParent (SumoXMLTag tag) static inherited
check if a element with certain tag has another additional element as parent
Definition at line 525 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedAdditionalWithParentTags, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, and SUMO_TAG_E3DETECTOR.
Referenced by GNEAdditionalFrame::addAdditional(), GNEAttributeCarrier::getParentType(), GNEAdditionalFrame::setParametersOfAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
void GNEReferenceCounter::incRef (const std::string & debugMsg = "") inline inherited
Definition at line 73 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), GNEReferenceCounter::myCount, toString(), and UNUSED_PARAMETER.
Referenced by GNEEdge::addLane(), GNENet::registerEdge(), GNENet::registerJunction(), and GNEInspectorFrame::setEdgeTemplate().
bool GNEAdditional::isAdditionalBlocked () const inherited
Check if additional item is currently blocked (i.e. cannot be moved with mouse)
Definition at line 121 of file GNEAdditional.cpp.
References GNEAdditional::myBlocked.
Referenced by GNEInspectorFrame::inspect().
bool GNEAdditional::isAdditionalInspectionable () const inherited
check if additional element is inspectionable (With GNEInspectorFrame)
Definition at line 127 of file GNEAdditional.cpp.
References GNEAdditional::myInspectionable.
bool GNEAdditional::isAdditionalMovable () const inherited
check if additional element is movable
Definition at line 139 of file GNEAdditional.cpp.
References GNEAdditional::myMovable.
Referenced by GNEInspectorFrame::inspect().
bool GNEAdditional::isAdditionalSelectable () const inherited
check if additional element is selectable (With GNESelectorFrame)
Definition at line 133 of file GNEAdditional.cpp.
References GNEAdditional::mySelectable.
bool GNEAdditional::isAdditionalSelected () const inherited
Definition at line 145 of file GNEAdditional.cpp.
References GUIGlObject::getGlID(), GUIGlObject::getType(), gSelected, and GUISelectedStorage::isSelected().
Referenced by GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE3::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSignal::drawGL(), drawGL(), GNEChargingStation::drawGL(), GNERerouter::drawGL(), and GNEAdditional::drawLockIcon().
bool GNEAttributeCarrier::isBool (SumoXMLAttr attr) static inherited
whether an attribute is of type bool
Definition at line 460 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedTags(), and GNEAttributeCarrier::discreteChoices().
Referenced by GNEAdditionalFrame::additionalParameters::addAttribute(), GNEAdditionalFrame::additionalParameter::getValue(), GNEAttributeCarrier::isString(), GNEAdditionalFrame::additionalParameters::onCmdHelp(), GNEInspectorFrame::AttrInput::onCmdSetAttribute(), GNEInspectorFrame::AttrInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isDiscrete (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is Discrete
Definition at line 515 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::discreteChoices().
Referenced by GNEInspectorFrame::AttrInput::onCmdSetAttribute(), GNEInspectorFrame::AttrInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isFloat (SumoXMLAttr attr) static inherited
whether an attribute is numerical of type float
Definition at line 437 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNumericalFloatAttrs, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CONTPOS, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_LENGTH, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_SPEED, SUMO_ATTR_STARTPOS, and SUMO_ATTR_WIDTH.
Referenced by GNEAdditionalFrame::additionalParameters::addAttribute(), GNEAttributeCarrier::isNumerical(), GNEAttributeCarrier::isString(), GNEAdditionalFrame::additionalParameters::onCmdHelp(), GNEInspectorFrame::AttrInput::onCmdSetAttribute(), GNEInspectorFrame::AttrInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isInt (SumoXMLAttr attr) static inherited
whether an attribute is numerical or type int
Definition at line 419 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNumericalIntAttrs, SUMO_ATTR_BEGIN, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FROM_LANE, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_INDEX, SUMO_ATTR_NUMLANES, SUMO_ATTR_PRIORITY, and SUMO_ATTR_TO_LANE.
Referenced by GNEAdditionalFrame::additionalParameters::addAttribute(), GNEAttributeCarrier::isNumerical(), GNEAdditionalFrame::additionalParameters::onCmdHelp(), GNEInspectorFrame::AttrInput::onCmdSetAttribute(), GNEInspectorFrame::AttrInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isList (SumoXMLAttr attr) static inherited
whether an attribute is of type bool
Definition at line 481 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myListAttrs, SUMO_ATTR_EDGES, SUMO_ATTR_LANES, and SUMO_ATTR_LINES.
Referenced by GNEAdditionalFrame::additionalParameters::addAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isNumerical (SumoXMLAttr attr) static inherited
whether an attribute is numerical (int or float)
Definition at line 413 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isFloat(), and GNEAttributeCarrier::isInt().
Referenced by GNESelectorFrame::getMatches(), GNEAttributeCarrier::isString(), GNESelectorFrame::onCmdSelMBString(), and GNEAttributeCarrier::~GNEAttributeCarrier().
template<typename T > static bool GNEAttributeCarrier::isPositive (const std::string & string) inline static inherited
true if a positive number of type T can be parsed from string
Definition at line 187 of file GNEAttributeCarrier.h.
References GNEAttributeCarrier::isValidFileValue(), GNEAttributeCarrier::isValidID(), and GNEAttributeCarrier::isValidStringVector().
bool GNEAttributeCarrier::isString (SumoXMLAttr attr) static inherited
whether an attribute is of type string
Definition at line 475 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isFloat(), and GNEAttributeCarrier::isNumerical().
Referenced by GNEAdditionalFrame::additionalParameters::addAttribute(), GNEAdditionalFrame::additionalParameters::onCmdHelp(), GNEInspectorFrame::AttrInput::onCmdSetAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isUnique (SumoXMLAttr attr) static inherited
whether an attribute is unique (may not be edited for a multi-selection)
Note
unique attributes don't have a default value
Definition at line 493 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myUniqueAttrs, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_ENDPOS, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_SHAPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_TO, and SUMO_ATTR_TO_LANE.
Referenced by GNEAdditional::getParameterWindow(), GNEInspectorFrame::inspect(), GNEAdditionalFrame::setParametersOfAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNERouteProbe::isValid (SumoXMLAttr key, const std::string & value) virtual
Implements GNEAdditional.
Definition at line 326 of file GNERouteProbe.cpp.
References GNENet::getAdditional(), GNEViewNet::getNet(), GNEAttributeCarrier::getTag(), GUIGlObject::getType(), GNEAttributeCarrier::isValidFileValue(), GNEAdditional::myViewNet, GNENet::retrieveEdge(), SUMO_ATTR_BEGIN, SUMO_ATTR_EDGE, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, and toString().
bool GNEAttributeCarrier::isValidFileValue (const std::string & value) static inherited
true if value is a valid file value
Definition at line 139 of file GNEAttributeCarrier.cpp.
Referenced by GNEAttributeCarrier::isPositive(), GNEDetectorE1::isValid(), GNEDetectorE2::isValid(), GNEDetectorE3::isValid(), GNEVariableSpeedSignal::isValid(), isValid(), GNECalibrator::isValid(), GNERerouter::isValid(), and GNEAttributeCarrier::isValidStringVector().
bool GNEAttributeCarrier::isValidID (const std::string & value) static inherited
true if value is a valid sumo ID
Definition at line 133 of file GNEAttributeCarrier.cpp.
Referenced by GNEAttributeCarrier::isPositive(), GNEJunction::isValid(), and GNEEdge::isValid().
bool GNEAttributeCarrier::isValidStringVector (const std::string & value) static inherited
true if value is a valid string vector
Definition at line 147 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isValidFileValue().
Referenced by GNEAttributeCarrier::isPositive(), GNEContainerStop::isValid(), and GNEBusStop::isValid().
void GNERouteProbe::moveAdditional (SUMOReal , SUMOReal , GNEUndoList *) virtual
change the position of the RouteProbe geometry
Implements GNEAdditional.
Definition at line 141 of file GNERouteProbe.cpp.
void GNEAdditional::openAdditionalDialog () virtual inherited
open Additional Dialog
Note
: if additional needs an additional dialog, this function has to be implemented in childrens (see GNERerouter and GNEVariableSpeedSignal)
Reimplemented in GNERerouter, GNECalibrator, and GNEVariableSpeedSignal.
Definition at line 99 of file GNEAdditional.cpp.
Referenced by GNEViewNet::onDoubleClicked().
GNERouteProbe& GNERouteProbe::operator= (const GNERouteProbe &) private
Invalidated assignment operator.
template<> int GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 70 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2int(), and SUMOReal.
template<> SUMOReal GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 76 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2SUMOReal().
template<> bool GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 82 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2Bool().
template<typename T > static T GNEAttributeCarrier::parse (const std::string & string) static inherited
parses a number of type T from string
Referenced by GNEAttributeCarrier::canParse().
void GNERouteProbe::removeEdgeReference () virtual
remove reference to edge
Note
this function will be called automatically in destructor of GNEEdge
Reimplemented from GNEAdditional.
Definition at line 168 of file GNERouteProbe.cpp.
References myEdge.
void GNEAdditional::removeLaneReference () virtual inherited
if additional is placed over a lane, remove it reference
Note
if additional is placed over a lane, this function has to be implemented in the children (See StoppingPlaces and Detectors) AND called in lane destructor
Reimplemented in GNEDetector, and GNEStoppingPlace.
Definition at line 198 of file GNEAdditional.cpp.
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 264 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
void GNEAdditional::setAdditionalID (const std::string & id) inherited
set the ID of additional
Definition at line 157 of file GNEAdditional.cpp.
References GUIGlObject::getMicrosimID(), GNEViewNet::getNet(), GNEAdditional::myViewNet, GUIGlObject::setMicrosimID(), and GNENet::updateAdditionalID().
Referenced by GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEDetectorE1::setAttribute(), GNEBusStop::setAttribute(), GNEContainerStop::setAttribute(), GNEDetectorE2::setAttribute(), GNEDetectorE3::setAttribute(), GNEVaporizer::setAttribute(), GNEVariableSpeedSignal::setAttribute(), setAttribute(), GNEChargingStation::setAttribute(), GNECalibrator::setAttribute(), and GNERerouter::setAttribute().
void GNERouteProbe::setAttribute (SumoXMLAttr key, const std::string & value, GNEUndoList * undoList) virtual
Implements GNEAdditional.
Definition at line 306 of file GNERouteProbe.cpp.
References getAttribute(), GUIGlObject::getType(), GNEAttributeCarrier::GNEChange_Attribute, GNEUndoList::p_add(), SUMO_ATTR_BEGIN, SUMO_ATTR_EDGE, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, toString(), and updateGeometry().
void GNERouteProbe::setAttribute (SumoXMLAttr key, const std::string & value) private virtual
set attribute after validation
Implements GNEAdditional.
Definition at line 353 of file GNERouteProbe.cpp.
References GNEEdge::addAdditional(), GNEViewNet::getNet(), GUIGlObject::getType(), GNEAdditional::getViewNet(), myBegin, myEdge, myFilename, myFrequency, GNEAdditional::myViewNet, GNEEdge::removeAdditional(), GNENet::retrieveEdge(), GNEAdditional::setAdditionalID(), SUMO_ATTR_BEGIN, SUMO_ATTR_EDGE, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, toString(), and updateGeometry().
void GNERouteProbe::setBegin (int begin)
set begin of RouteProbe
Definition at line 204 of file GNERouteProbe.cpp.
References myBegin.
void GNEAdditional::setBlocked (bool value) inherited
Block or unblock additional element(i.e. cannot be moved with mouse)
Definition at line 168 of file GNEAdditional.cpp.
References GNEAdditional::myBlocked.
Referenced by GNEInspectorFrame::onCmdSetBlocking().
void GNEAdditional::setBlockIconRotation (GNELane * lane = NULL) protected inherited
Definition at line 312 of file GNEAdditional.cpp.
References GNELane::getPositionRelativeToParametricLenght(), GNELane::getShape(), PositionVector::length(), GNEAdditional::myBlockIconRotation, GNEAdditional::myPosition, GNEAdditional::myShape, PositionVector::rotationDegreeAtOffset(), and Position::x().
Referenced by GNEVariableSpeedSignal::updateGeometry(), GNEDetectorExit::updateGeometry(), GNEDetectorEntry::updateGeometry(), GNEDetectorE1::updateGeometry(), GNEDetectorE3::updateGeometry(), GNEVaporizer::updateGeometry(), updateGeometry(), GNEChargingStation::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEBusStop::updateGeometry(), GNEContainerStop::updateGeometry(), and GNERerouter::updateGeometry().
void GNERouteProbe::setFilename (std::string filename)
set filename of RouteProbe
Definition at line 192 of file GNERouteProbe.cpp.
References myFilename.
void GNERouteProbe::setFrequency (int frequency)
set frequency of RouteProbe
Definition at line 198 of file GNERouteProbe.cpp.
References myFrequency.
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 143 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNENet::renameJunction(), GNEAdditional::setAdditionalID(), GNELane::setIndex(), and GNEEdge::setMicrosimID().
void GNEAdditional::setPositionInView (const Position & pos) inherited
set new position in the view
Note
movement cannot be undo with GNEUndoRedo
Definition at line 174 of file GNEAdditional.cpp.
References GNEAdditional::myPosition.
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 273 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
bool GNEReferenceCounter::unreferenced () inline inherited
Definition at line 82 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), and GNEReferenceCounter::myCount.
Referenced by GNEEdge::removeLane(), GNEInspectorFrame::setEdgeTemplate(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_Connection::~GNEChange_Connection(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_TLS::~GNEChange_TLS(), and GNEInspectorFrame::~GNEInspectorFrame().
void GNERouteProbe::updateGeometry () virtual
update pre-computed geometry information
Note
: must be called when geometry changes (i.e. lane moved)
Implements GNEAdditional.
Definition at line 93 of file GNERouteProbe.cpp.
References GNEEdge::getLanes(), PositionVector::getLineCenter(), GNELane::getShape(), GNEAdditional::myBlockIconOffset, GNEAdditional::myBlockIconPosition, myEdge, GNEAdditional::myShape, GNEAdditional::myShapeLengths, GNEAdditional::myShapeRotations, numberOfLanes, PositionVector::positionAtOffset(), PositionVector::rotationDegreeAtOffset(), and GNEAdditional::setBlockIconRotation().
Referenced by GNERouteProbe(), and setAttribute().
void GNERouteProbe::writeAdditional (OutputDevice & device, const std::string &) virtual
writte additional element into a xml file
Parameters
[in] device device in which write parameters of additional element
Implements GNEAdditional.
Definition at line 147 of file GNERouteProbe.cpp.
References OutputDevice::closeTag(), GNEAttributeCarrier::getID(), GNEAttributeCarrier::getTag(), myBegin, myEdge, myFilename, myFrequency, OutputDevice::openTag(), SUMO_ATTR_BEGIN, SUMO_ATTR_EDGE, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, and OutputDevice::writeAttr().
Field Documentation
const std::string GNEAttributeCarrier::APPROVED = "approved" static inherited
feature has been approved but not changed (i.e. after being reguessed)
Definition at line 210 of file GNEAttributeCarrier.h.
const std::string GNEAttributeCarrier::GUESSED = "guessed" static inherited
feature has been reguessed (may still be unchanged be we can't tell (yet)
Definition at line 204 of file GNEAttributeCarrier.h.
Referenced by GNEEdge::setAttribute().
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 77 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
const std::string GNEAttributeCarrier::LOADED = "loaded" static inherited
feature is still unchanged after being loaded (implies approval)
Definition at line 201 of file GNEAttributeCarrier.h.
const std::string GNEAttributeCarrier::MODIFIED = "modified" static inherited
feature has been manually modified (implies approval)
Definition at line 207 of file GNEAttributeCarrier.h.
Referenced by GNEConnectorFrame::onCmdClearSelectedConnections(), and GNEEdge::setAttribute().
GNEAdditionalDialog* GNEAdditional::myAdditionalDialog protected inherited
pointer to additional dialog
Definition at line 240 of file GNEAdditional.h.
GNEAdditionalSet* GNEAdditional::myAdditionalSetParent protected inherited
pointer to additional set parent, if belong to set
Definition at line 229 of file GNEAdditional.h.
Referenced by GNEAdditional::getAdditionalSetParent(), GNEAdditional::GNEAdditional(), GNEDetectorExit::updateGeometry(), GNEDetectorEntry::updateGeometry(), and GNEAdditional::~GNEAdditional().
RGBColor GNEAdditional::myBaseColor protected inherited
base color (Default green)
Note
default color can be defined in the constructor of every additional
Definition at line 233 of file GNEAdditional.h.
Referenced by GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEChargingStation::drawGL(), GNEBusStop::GNEBusStop(), GNECalibrator::GNECalibrator(), GNEChargingStation::GNEChargingStation(), GNEContainerStop::GNEContainerStop(), GNEDetectorE1::GNEDetectorE1(), GNEDetectorE2::GNEDetectorE2(), GNEDetectorE3::GNEDetectorE3(), GNEDetectorEntry::GNEDetectorEntry(), GNEDetectorExit::GNEDetectorExit(), GNERerouter::GNERerouter(), and GNEVariableSpeedSignal::GNEVariableSpeedSignal().
RGBColor GNEAdditional::myBaseColorSelected protected inherited
base color selected (Default blue)
Note
default color can be defined in the constructor of every additional
Definition at line 237 of file GNEAdditional.h.
Referenced by GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEChargingStation::drawGL(), GNEBusStop::GNEBusStop(), GNECalibrator::GNECalibrator(), GNEChargingStation::GNEChargingStation(), GNEContainerStop::GNEContainerStop(), GNEDetectorE1::GNEDetectorE1(), GNEDetectorE2::GNEDetectorE2(), GNEDetectorE3::GNEDetectorE3(), GNEDetectorEntry::GNEDetectorEntry(), GNEDetectorExit::GNEDetectorExit(), GNERerouter::GNERerouter(), and GNEVariableSpeedSignal::GNEVariableSpeedSignal().
int GNERouteProbe::myBegin protected
begin of rerouter
Definition at line 151 of file GNERouteProbe.h.
Referenced by getAttribute(), getBegin(), setAttribute(), setBegin(), and writeAdditional().
bool GNEAdditional::myBlocked protected inherited
boolean to check if additional element is blocked (i.e. cannot be moved with mouse)
Definition at line 274 of file GNEAdditional.h.
Referenced by GNEAdditional::drawLockIcon(), GNEAdditional::isAdditionalBlocked(), GNEVariableSpeedSignal::moveAdditional(), GNEDetector::moveAdditional(), GNEDetectorE3::moveAdditional(), GNEStoppingPlace::moveAdditional(), GNERerouter::moveAdditional(), and GNEAdditional::setBlocked().
Position GNEAdditional::myBlockIconOffset protected inherited
The offSet of the block icon.
Definition at line 267 of file GNEAdditional.h.
Referenced by GNEAdditional::drawLockIcon(), GNEVariableSpeedSignal::updateGeometry(), GNEDetectorE1::updateGeometry(), GNEDetectorE3::updateGeometry(), GNEVaporizer::updateGeometry(), updateGeometry(), GNEDetectorE2::updateGeometry(), and GNERerouter::updateGeometry().
Position GNEAdditional::myBlockIconPosition protected inherited
position of the block icon
Definition at line 264 of file GNEAdditional.h.
Referenced by GNEAdditional::drawLockIcon(), GNEVariableSpeedSignal::updateGeometry(), GNEDetectorExit::updateGeometry(), GNEDetectorEntry::updateGeometry(), GNEDetectorE1::updateGeometry(), GNEDetectorE3::updateGeometry(), GNEVaporizer::updateGeometry(), updateGeometry(), GNEChargingStation::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEBusStop::updateGeometry(), GNEContainerStop::updateGeometry(), and GNERerouter::updateGeometry().
SUMOReal GNEAdditional::myBlockIconRotation protected inherited
The rotation of the block icon.
Definition at line 270 of file GNEAdditional.h.
Referenced by GNEDetector::drawDetectorIcon(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEChargingStation::drawGL(), GNEAdditional::drawLockIcon(), and GNEAdditional::setBlockIconRotation().
GNEEdge* GNERouteProbe::myEdge protected
edge of routeProbe
Definition at line 142 of file GNERouteProbe.h.
Referenced by getAttribute(), getEdge(), getParentName(), getPositionInView(), GNERouteProbe(), removeEdgeReference(), setAttribute(), updateGeometry(), writeAdditional(), and ~GNERouteProbe().
std::string GNERouteProbe::myFilename protected
filename of RouteProbe
Definition at line 148 of file GNERouteProbe.h.
Referenced by getAttribute(), getFilename(), setAttribute(), setFilename(), and writeAdditional().
int GNERouteProbe::myFrequency protected
Frequency of RouteProbe.
Definition at line 145 of file GNERouteProbe.h.
Referenced by getAttribute(), getFrequency(), setAttribute(), setFrequency(), and writeAdditional().
bool GNEAdditional::myInspectionable protected inherited
boolean to check if additional element is inspectionable (With GNEInspectorFrame). By default true
Definition at line 277 of file GNEAdditional.h.
Referenced by GNEAdditional::isAdditionalInspectionable().
bool GNEAdditional::myMovable protected inherited
boolean to check if additional element is movable (with the mouse). By default true
Definition at line 283 of file GNEAdditional.h.
Referenced by GNEAdditional::drawLockIcon(), GNECalibrator::GNECalibrator(), GNERouteProbe(), GNEVaporizer::GNEVaporizer(), and GNEAdditional::isAdditionalMovable().
Position GNEAdditional::myPosition protected inherited
The position in which this additional element is located.
Note
if this element belongs to a Lane, x() value will be the position over Lane
Definition at line 222 of file GNEAdditional.h.
Referenced by GNEAdditionalSet::drawConnections(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorE2::getAttribute(), GNEDetectorE3::getAttribute(), GNEVariableSpeedSignal::getAttribute(), GNECalibrator::getAttribute(), GNERerouter::getAttribute(), GNEAdditional::getPopUpMenu(), GNEVariableSpeedSignal::getPositionInView(), GNEDetectorExit::getPositionInView(), GNEDetectorEntry::getPositionInView(), GNEDetectorE1::getPositionInView(), GNEDetectorE3::getPositionInView(), GNEStoppingPlace::getPositionInView(), GNEVaporizer::getPositionInView(), getPositionInView(), GNEDetectorE2::getPositionInView(), GNECalibrator::getPositionInView(), GNERerouter::getPositionInView(), GNEDetector::getPositionOverLane(), GNEDetector::moveAdditional(), GNEDetectorEntry::setAttribute(), GNEDetectorE1::setAttribute(), GNEDetectorExit::setAttribute(), GNEDetectorE2::setAttribute(), GNEDetectorE3::setAttribute(), GNEVariableSpeedSignal::setAttribute(), GNECalibrator::setAttribute(), GNERerouter::setAttribute(), GNEAdditional::setBlockIconRotation(), GNEAdditional::setPositionInView(), GNEDetector::setPositionOverLane(), GNEAdditionalSet::updateConnections(), GNEVariableSpeedSignal::updateGeometry(), GNEDetectorEntry::updateGeometry(), GNEDetectorExit::updateGeometry(), GNEDetectorE1::updateGeometry(), GNEDetectorE3::updateGeometry(), GNEDetectorE2::updateGeometry(), GNECalibrator::updateGeometry(), GNERerouter::updateGeometry(), GNEDetectorExit::writeAdditional(), GNEDetectorEntry::writeAdditional(), GNEDetectorE1::writeAdditional(), GNEDetectorE2::writeAdditional(), GNEVariableSpeedSignal::writeAdditional(), GNEDetectorE3::writeAdditional(), GNECalibrator::writeAdditional(), and GNERerouter::writeAdditional().
bool GNEAdditional::myRotationLefthand protected inherited
rotation depending of the option "Lefthand"
Definition at line 252 of file GNEAdditional.h.
Referenced by GNEAdditional::GNEAdditional(), and GNEChargingStation::updateGeometry().
Position GNERouteProbe::myRouteProbeLogoOffset protected
route probe logo offset
Definition at line 154 of file GNERouteProbe.h.
bool GNEAdditional::mySelectable protected inherited
boolean to check if additional element is selectable (With GNESelectorFrame). By default true
Definition at line 280 of file GNEAdditional.h.
Referenced by GNEAdditional::isAdditionalSelectable().
PositionVector GNEAdditional::myShape protected inherited
The shape of the additional element.
Note
must be configured in updateGeometry()
Definition at line 226 of file GNEAdditional.h.
Referenced by GNEDetector::drawDetectorIcon(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE3::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSignal::drawGL(), drawGL(), GNEChargingStation::drawGL(), GNECalibrator::drawGL(), GNERerouter::drawGL(), GNEAdditional::getCenteringBoundary(), GNEAdditional::getPopUpMenu(), GNEAdditional::getShape(), GNEAdditional::setBlockIconRotation(), GNEVariableSpeedSignal::updateGeometry(), GNEDetectorEntry::updateGeometry(), GNEDetectorExit::updateGeometry(), GNEDetectorE1::updateGeometry(), GNEDetectorE3::updateGeometry(), GNEVaporizer::updateGeometry(), updateGeometry(), GNEChargingStation::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEContainerStop::updateGeometry(), GNEBusStop::updateGeometry(), GNECalibrator::updateGeometry(), and GNERerouter::updateGeometry().
std::vector<SUMOReal> GNEAdditional::myShapeLengths protected inherited
The lengths of the shape parts.
Definition at line 248 of file GNEAdditional.h.
Referenced by GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEChargingStation::drawGL(), GNEDetectorEntry::updateGeometry(), GNEDetectorExit::updateGeometry(), GNEDetectorE1::updateGeometry(), GNEVaporizer::updateGeometry(), GNEChargingStation::updateGeometry(), updateGeometry(), GNEDetectorE2::updateGeometry(), GNEBusStop::updateGeometry(), GNEContainerStop::updateGeometry(), and GNECalibrator::updateGeometry().
std::vector<SUMOReal> GNEAdditional::myShapeRotations protected inherited
Definition at line 245 of file GNEAdditional.h.
Referenced by GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEVaporizer::drawGL(), drawGL(), GNEChargingStation::drawGL(), GNECalibrator::drawGL(), GNEDetectorEntry::updateGeometry(), GNEDetectorExit::updateGeometry(), GNEDetectorE1::updateGeometry(), GNEVaporizer::updateGeometry(), GNEChargingStation::updateGeometry(), updateGeometry(), GNEDetectorE2::updateGeometry(), GNEBusStop::updateGeometry(), GNEContainerStop::updateGeometry(), and GNECalibrator::updateGeometry().
GNEViewNet* GNEAdditional::myViewNet protected inherited
The GNEViewNet this additional element belongs.
Definition at line 218 of file GNEAdditional.h.
Referenced by GNEDetectorE3::getParentName(), GNEVariableSpeedSignal::getParentName(), GNEAdditional::getParentName(), GNERerouter::getParentName(), GNEAdditional::getPopUpMenu(), GNEAdditional::getViewNet(), GNECalibrator::GNECalibrator(), GNERouteProbe(), GNEVaporizer::GNEVaporizer(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEDetectorE1::isValid(), GNEDetectorE2::isValid(), GNEBusStop::isValid(), GNEContainerStop::isValid(), GNEDetectorE3::isValid(), GNEVaporizer::isValid(), GNEVariableSpeedSignal::isValid(), isValid(), GNEChargingStation::isValid(), GNECalibrator::isValid(), GNERerouter::isValid(), GNEAdditional::setAdditionalID(), GNEDetectorExit::setAttribute(), GNEDetectorEntry::setAttribute(), GNEDetectorE1::setAttribute(), GNEContainerStop::setAttribute(), GNEBusStop::setAttribute(), GNEDetectorE2::setAttribute(), GNEVaporizer::setAttribute(), GNEVariableSpeedSignal::setAttribute(), setAttribute(), GNEChargingStation::setAttribute(), GNECalibrator::setAttribute(), and GNERerouter::setAttribute().
int GNERouteProbe::numberOfLanes protected
number of lanes of edge (To improve efficiency)
Definition at line 157 of file GNERouteProbe.h.
Referenced by drawGL(), and updateGeometry().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 76 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GNERouteProbe.h
GNERouteProbe.cpp