SUMO - Simulation of Urban MObility: MSAbstractLaneChangeModel Class Reference
MSAbstractLaneChangeModel Class Reference abstract
Interface for lane-change models.
#include <MSAbstractLaneChangeModel.h>
Data Structures
class MSLCMessager
A class responsible for exchanging messages between cars involved in lane-change interaction.
struct StateAndDist
Public Member Functions
bool alreadyChanged () const
reset the flag whether a vehicle already moved to false
virtual void changed ()=0
void changedToOpposite ()
called when a vehicle changes between lanes in opposite directions
void cleanupShadowLane ()
virtual bool debugVehicle () const
whether the current vehicles shall be debugged
virtual StateAndDist decideDirection (StateAndDist sd1, StateAndDist sd2) const
decide in which direction to move in case both directions are desirable
void endLaneChangeManeuver (const MSMoveReminder::Notification reason=MSMoveReminder::NOTIFICATION_LANE_CHANGE)
SUMOReal getAngleOffset () const
return the angle offset during a continuous change maneuver
int getLaneChangeDirection () const
return the direction of the current lane change maneuver
SUMOTime getLastLaneChangeOffset () const
SUMOReal getLateralSpeed () const
return the lateral speed of the current lane change maneuver
int getOwnState () const
int getShadowDirection () const
return the direction in which the current shadow lane lies
const std::vector< MSLane * > & getShadowFurtherLanes () const
const std::vector< SUMOReal > & getShadowFurtherLanesPosLat () const
MSLane * getShadowLane () const
Returns the lane the vehicles shadow is on during continuous/sublane lane change.
MSLane * getShadowLane (const MSLane *lane) const
return the shadow lane for the given lane
virtual void * inform (void *info, MSVehicle *sender)=0
bool isChangingLanes () const
return true if the vehicle currently performs a lane change maneuver
bool isOpposite () const
MSAbstractLaneChangeModel (MSVehicle &v, const LaneChangeModel model)
Constructor.
bool pastMidpoint () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
virtual SUMOReal patchSpeed (const SUMOReal min, const SUMOReal wanted, const SUMOReal max, const MSCFModel &cfModel)=0
Called to adapt the speed in order to allow a lane change.
virtual void prepareStep ()
void primaryLaneChanged (MSLane *source, MSLane *target, int direction)
called once when the vehicles primary lane changes
SUMOTime remainingTime () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
void removeShadowApproachingInformation () const
void resetChanged ()
reset the flag whether a vehicle already moved to false
virtual void saveBlockerLength (SUMOReal length)
reserve space at the end of the lane to avoid dead locks
void setNoShadowPartialOccupator (MSLane *lane)
virtual void setOwnState (int state)
void setShadowApproachingInformation (MSLink *link) const
set approach information for the shadow vehicle
void setShadowLane (MSLane *lane)
set the shadow lane
void setShadowPartialOccupator (MSLane *lane)
bool startLaneChangeManeuver (MSLane *source, MSLane *target, int direction)
start the lane change maneuver and return whether it continues
void unchanged ()
bool updateCompletion ()
virtual void updateExpectedSublaneSpeeds (const MSLeaderInfo &ahead, int sublaneOffset, int laneIndex)
update expected speeds for each sublane of the current edge
void updateShadowLane ()
virtual int wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > &leader, const std::pair< MSVehicle *, SUMOReal > &neighLead, const std::pair< MSVehicle *, SUMOReal > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked)
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
virtual int wantsChangeSublane (int laneOffset, const MSLeaderDistanceInfo &leaders, const MSLeaderDistanceInfo &followers, const MSLeaderDistanceInfo &blockers, const MSLeaderDistanceInfo &neighLeaders, const MSLeaderDistanceInfo &neighFollowers, const MSLeaderDistanceInfo &neighBlockers, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked, SUMOReal &latDist, int &blocked)
virtual ~MSAbstractLaneChangeModel ()
Destructor.
Static Public Member Functions
static MSAbstractLaneChangeModel * build (LaneChangeModel lcm, MSVehicle &vehicle)
Factory method for instantiating new lane changing models.
static void initGlobalOptions (const OptionsCont &oc)
init global model parameters
Protected Member Functions
bool cancelRequest (int state)
whether the influencer cancels the given request
virtual bool congested (const MSVehicle *const neighLeader)
void initLastLaneChangeOffset (int dir)
virtual bool predInteraction (const std::pair< MSVehicle *, SUMOReal > &leader)
Protected Attributes
bool myAlreadyChanged
whether the vehicle has already moved this step
const MSCFModel & myCarFollowModel
The vehicle's car following model.
SUMOReal myLaneChangeCompletion
progress of the lane change maneuver 0:started, 1:complete
int myLaneChangeDirection
direction of the lane change maneuver -1 means right, 1 means left
SUMOReal myLateralspeed
The lateral offset during a continuous LaneChangeManeuver.
const LaneChangeModel myModel
the type of this model
std::vector< MSLane * > myNoPartiallyOccupatedByShadow
int myOwnState
The current state of the vehicle.
std::vector< MSLane * > myPartiallyOccupatedByShadow
list of lanes where the shadow vehicle is partial occupator
std::vector< MSLane * > myShadowFurtherLanes
std::vector< SUMOReal > myShadowFurtherLanesPosLat
MSLane * myShadowLane
A lane that is partially occupied by the front of the vehicle but that is not the primary lane.
MSVehicle & myVehicle
The vehicle this lane-changer belongs to.
Static Protected Attributes
static bool myAllowOvertakingRight
whether overtaking on the right is permitted
static bool myLCOutput
whether to record lane-changing
Private Member Functions
MSAbstractLaneChangeModel & operator= (const MSAbstractLaneChangeModel &s)
Invalidated assignment operator.
Private Attributes
bool myAmOpposite
whether the vehicle is driving in the opposite direction
std::vector< MSLink * > myApproachedByShadow
links which are approached by the shadow vehicle
SUMOTime myLastLaneChangeOffset
Detailed Description
Interface for lane-change models.
Definition at line 51 of file MSAbstractLaneChangeModel.h.
Constructor & Destructor Documentation
MSAbstractLaneChangeModel::MSAbstractLaneChangeModel (MSVehicle & v, const LaneChangeModel model)
Constructor.
Parameters
[in] v The vehicle this lane-changer belongs to
[in] model The type of lane change model
Definition at line 88 of file MSAbstractLaneChangeModel.cpp.
Referenced by MSAbstractLaneChangeModel::StateAndDist::StateAndDist().
MSAbstractLaneChangeModel::~MSAbstractLaneChangeModel () virtual
Destructor.
Definition at line 103 of file MSAbstractLaneChangeModel.cpp.
Referenced by MSAbstractLaneChangeModel::StateAndDist::StateAndDist().
Member Function Documentation
bool MSAbstractLaneChangeModel::alreadyChanged () const inline
reset the flag whether a vehicle already moved to false
Definition at line 324 of file MSAbstractLaneChangeModel.h.
References myAlreadyChanged.
Referenced by MSLaneChanger::change().
MSAbstractLaneChangeModel * MSAbstractLaneChangeModel::build (LaneChangeModel lcm, MSVehicle & vehicle) static
Factory method for instantiating new lane changing models.
Parameters
[in] lcm The type of model to build
[in] vehicle The vehicle for which this model shall be built
Definition at line 63 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLateralResolution, LCM_DEFAULT, LCM_DK2008, LCM_JE2013, LCM_LC2013, LCM_SL2015, and toString().
Referenced by MSVehicle::MSVehicle(), and MSAbstractLaneChangeModel::StateAndDist::StateAndDist().
bool MSAbstractLaneChangeModel::cancelRequest (int state) protected
whether the influencer cancels the given request
Definition at line 244 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::influenceChangeDecision(), and myVehicle.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), and isOpposite().
virtual void MSAbstractLaneChangeModel::changed () pure virtual
Implemented in MSLCM_LC2013, MSLCM_JE2013, MSLCM_SL2015, and MSLCM_DK2008.
Referenced by decideDirection(), and primaryLaneChanged().
void MSAbstractLaneChangeModel::changedToOpposite ()
called when a vehicle changes between lanes in opposite directions
Definition at line 350 of file MSAbstractLaneChangeModel.cpp.
References myAlreadyChanged, and myAmOpposite.
Referenced by debugVehicle(), MSVehicle::executeMove(), and startLaneChangeManeuver().
void MSAbstractLaneChangeModel::cleanupShadowLane ()
Definition at line 224 of file MSAbstractLaneChangeModel.cpp.
References MSBaseVehicle::getID(), myNoPartiallyOccupatedByShadow, myShadowFurtherLanes, myShadowLane, myVehicle, MSLane::resetPartialOccupation(), and SIMTIME.
Referenced by endLaneChangeManeuver(), resetChanged(), and MSVehicle::~MSVehicle().
bool MSAbstractLaneChangeModel::congested (const MSVehicle *const neighLeader) protected virtual
Definition at line 108 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::congested(), MSVehicle::getLane(), MSLane::getSpeedLimit(), and myVehicle.
Referenced by isOpposite(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
virtual bool MSAbstractLaneChangeModel::debugVehicle () const inline virtual
whether the current vehicles shall be debugged
Reimplemented in MSLCM_JE2013, MSLCM_SL2015, and MSLCM_LC2013.
Definition at line 251 of file MSAbstractLaneChangeModel.h.
References changedToOpposite().
Referenced by MSLaneChangerSublane::change().
virtual StateAndDist MSAbstractLaneChangeModel::decideDirection (StateAndDist sd1, StateAndDist sd2) const inline virtual
decide in which direction to move in case both directions are desirable
Reimplemented in MSLCM_SL2015.
Definition at line 223 of file MSAbstractLaneChangeModel.h.
References changed(), inform(), max, min, myModel, patchSpeed(), SUMOReal, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::change().
void MSAbstractLaneChangeModel::endLaneChangeManeuver (const MSMoveReminder::Notification reason = MSMoveReminder::NOTIFICATION_LANE_CHANGE)
Definition at line 191 of file MSAbstractLaneChangeModel.cpp.
References cleanupShadowLane(), MSVehicle::fixPosition(), myLaneChangeCompletion, myNoPartiallyOccupatedByShadow, myVehicle, MSVehicle::switchOffSignal(), UNUSED_PARAMETER, MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSVehicleTransfer::add(), MSLaneChanger::continueChange(), MSVehicle::executeMove(), resetChanged(), and updateShadowLane().
SUMOReal MSAbstractLaneChangeModel::getAngleOffset () const
return the angle offset during a continuous change maneuver
Definition at line 321 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLaneChangeDuration, myLaneChangeCompletion, myLaneChangeDirection, pastMidpoint(), STEPS2TIME, and SUMOReal.
Referenced by getLaneChangeDirection().
int MSAbstractLaneChangeModel::getLaneChangeDirection () const inline
return the direction of the current lane change maneuver
Definition at line 308 of file MSAbstractLaneChangeModel.h.
References getAngleOffset(), getShadowDirection(), myLaneChangeDirection, and SUMOReal.
Referenced by MSLaneChanger::continueChange().
SUMOTime MSAbstractLaneChangeModel::getLastLaneChangeOffset () const inline
Definition at line 289 of file MSAbstractLaneChangeModel.h.
References myLastLaneChangeOffset.
SUMOReal MSAbstractLaneChangeModel::getLateralSpeed () const inline
return the lateral speed of the current lane change maneuver
Definition at line 319 of file MSAbstractLaneChangeModel.h.
References myLateralspeed.
Referenced by MSLaneChanger::continueChange().
int MSAbstractLaneChangeModel::getOwnState () const inline
Definition at line 148 of file MSAbstractLaneChangeModel.h.
References myOwnState.
Referenced by MSLaneChanger::change(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), and MSVehicle::setBlinkerInformation().
int MSAbstractLaneChangeModel::getShadowDirection () const
return the direction in which the current shadow lane lies
Definition at line 304 of file MSAbstractLaneChangeModel.cpp.
References MSLane::getEdge(), MSLane::getIndex(), MSVehicle::getLane(), isChangingLanes(), myLaneChangeDirection, myShadowLane, myVehicle, pastMidpoint(), and SUMOReal.
Referenced by MSLaneChanger::continueChange(), MSVehicle::executeMove(), getLaneChangeDirection(), and GUIVehicle::selectBlockingFoes().
const std::vector<MSLane*>& MSAbstractLaneChangeModel::getShadowFurtherLanes () const inline
Definition at line 281 of file MSAbstractLaneChangeModel.h.
References myShadowFurtherLanes.
Referenced by MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), and MSVehicle::getLatOffset().
const std::vector<SUMOReal>& MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat () const inline
Definition at line 285 of file MSAbstractLaneChangeModel.h.
References myShadowFurtherLanesPosLat.
Referenced by MSVehicle::getCenterOnEdge(), and MSVehicle::getLatOffset().
MSLane* MSAbstractLaneChangeModel::getShadowLane () const inline
Returns the lane the vehicles shadow is on during continuous/sublane lane change.
Returns
The vehicle's shadow lane
Definition at line 269 of file MSAbstractLaneChangeModel.h.
References myShadowLane.
Referenced by MSVehicle::checkRewindLinkLanes(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::executeMove(), MSVehicle::getBackPosition(), MSVehicle::getCenterOnEdge(), GUIVehicle::getParameterWindow(), MSVehicle::isFrontOnLane(), MSVehicle::planMoveInternal(), GUIVehicle::selectBlockingFoes(), MSLaneChangerSublane::startChangeSublane(), MSLaneChangerSublane::updateChanger(), and updateShadowLane().
MSLane * MSAbstractLaneChangeModel::getShadowLane (const MSLane * lane) const
return the shadow lane for the given lane
Definition at line 202 of file MSAbstractLaneChangeModel.cpp.
References MSBaseVehicle::getID(), MSVehicle::getLateralOverlap(), MSVehicle::getLateralPositionOnLane(), MSLane::getParallelLane(), isChangingLanes(), myLaneChangeCompletion, myNoPartiallyOccupatedByShadow, myVehicle, NUMERICAL_EPS, SIMTIME, and SUMOReal.
virtual void* MSAbstractLaneChangeModel::inform (void * info, MSVehicle * sender) pure virtual
Implemented in MSLCM_LC2013, MSLCM_JE2013, MSLCM_SL2015, and MSLCM_DK2008.
Referenced by decideDirection(), MSAbstractLaneChangeModel::MSLCMessager::informLeader(), MSAbstractLaneChangeModel::MSLCMessager::informNeighFollower(), and MSAbstractLaneChangeModel::MSLCMessager::informNeighLeader().
void MSAbstractLaneChangeModel::initGlobalOptions (const OptionsCont & oc) static
init global model parameters
Definition at line 56 of file MSAbstractLaneChangeModel.cpp.
References OptionsCont::getBool(), OptionsCont::isSet(), myAllowOvertakingRight, and myLCOutput.
Referenced by MSFrame::setMSGlobals(), and MSAbstractLaneChangeModel::StateAndDist::StateAndDist().
void MSAbstractLaneChangeModel::initLastLaneChangeOffset (int dir) protected
Definition at line 251 of file MSAbstractLaneChangeModel.cpp.
References myLastLaneChangeOffset.
Referenced by primaryLaneChanged().
bool MSAbstractLaneChangeModel::isChangingLanes () const inline
return true if the vehicle currently performs a lane change maneuver
Definition at line 303 of file MSAbstractLaneChangeModel.h.
References myLaneChangeCompletion, and NUMERICAL_EPS.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), MSVehicle::computeAngle(), MSLaneChanger::continueChange(), MSLane::detectCollisionBetween(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::getBackPosition(), MSVehicle::getPosition(), getShadowDirection(), getShadowLane(), and updateShadowLane().
bool MSAbstractLaneChangeModel::isOpposite () const inline
Definition at line 372 of file MSAbstractLaneChangeModel.h.
References cancelRequest(), congested(), myAmOpposite, and predInteraction().
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLaneChanger::changeOpposite(), MSVehicle::checkRewindLinkLanes(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), and MSVehicle::planMoveInternal().
MSAbstractLaneChangeModel& MSAbstractLaneChangeModel::operator= (const MSAbstractLaneChangeModel & s) private
Invalidated assignment operator.
bool MSAbstractLaneChangeModel::pastMidpoint () const inline
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 295 of file MSAbstractLaneChangeModel.h.
References myLaneChangeCompletion, and remainingTime().
Referenced by getAngleOffset(), getShadowDirection(), and updateCompletion().
virtual SUMOReal MSAbstractLaneChangeModel::patchSpeed (const SUMOReal min, const SUMOReal wanted, const SUMOReal max, const MSCFModel & cfModel) pure virtual
Called to adapt the speed in order to allow a lane change.
It is guaranteed that min<=wanted<=max, but the implementation needs to make sure that the return value is between min and max.
Parameters
min The minimum resulting speed
wanted The aspired speed of the car following model
max The maximum resulting speed
cfModel The model used
Returns
the new speed of the vehicle as proposed by the lane changer
Implemented in MSLCM_LC2013, MSLCM_JE2013, MSLCM_SL2015, and MSLCM_DK2008.
Referenced by decideDirection(), MSCFModel_Daniel1::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_SmartSK::moveHelper(), and MSCFModel::moveHelper().
bool MSAbstractLaneChangeModel::predInteraction (const std::pair< MSVehicle *, SUMOReal > & leader) protected virtual
Definition at line 128 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getSpeed(), MSCFModel::interactionGap(), myCarFollowModel, and myVehicle.
Referenced by isOpposite(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
virtual void MSAbstractLaneChangeModel::prepareStep () inline virtual
Reimplemented in MSLCM_LC2013, MSLCM_JE2013, MSLCM_SL2015, and MSLCM_DK2008.
Definition at line 156 of file MSAbstractLaneChangeModel.h.
Referenced by MSVehicle::executeMove().
void MSAbstractLaneChangeModel::primaryLaneChanged (MSLane * source, MSLane * target, int direction)
called once when the vehicles primary lane changes
Definition at line 160 of file MSAbstractLaneChangeModel.cpp.
References changed(), OutputDevice::closeTag(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtLaneChange(), OutputDevice::getDeviceByOption(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getSpeed(), initLastLaneChangeOffset(), LCA_LEFT, LCA_RIGHT, MSVehicle::leaveLane(), MSLane::leftByLaneChange(), myLCOutput, myOwnState, myVehicle, MSMoveReminder::NOTIFICATION_LANE_CHANGE, OutputDevice::openTag(), SUMO_ATTR_DIR, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_SPEED, SUMO_ATTR_TIME, SUMO_ATTR_TO, time2string(), toString(), and OutputDevice::writeAttr().
Referenced by MSLaneChanger::continueChange(), setNoShadowPartialOccupator(), and startLaneChangeManeuver().
SUMOTime MSAbstractLaneChangeModel::remainingTime () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 328 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLaneChangeDuration, and myLaneChangeCompletion.
Referenced by pastMidpoint().
void MSAbstractLaneChangeModel::removeShadowApproachingInformation () const
Definition at line 340 of file MSAbstractLaneChangeModel.cpp.
References myApproachedByShadow, and myVehicle.
Referenced by MSVehicle::removeApproachingInformation(), and setNoShadowPartialOccupator().
void MSAbstractLaneChangeModel::resetChanged () inline
reset the flag whether a vehicle already moved to false
Definition at line 329 of file MSAbstractLaneChangeModel.h.
References cleanupShadowLane(), endLaneChangeManeuver(), myAlreadyChanged, MSMoveReminder::NOTIFICATION_LANE_CHANGE, startLaneChangeManeuver(), updateCompletion(), and updateShadowLane().
Referenced by MSVehicle::planMove().
virtual void MSAbstractLaneChangeModel::saveBlockerLength (SUMOReal length) inline virtual
reserve space at the end of the lane to avoid dead locks
Reimplemented in MSLCM_SL2015, MSLCM_LC2013, and MSLCM_JE2013.
Definition at line 353 of file MSAbstractLaneChangeModel.h.
References UNUSED_PARAMETER.
Referenced by MSLCM_JE2013::saveBlockerLength(), and MSLCM_LC2013::saveBlockerLength().
void MSAbstractLaneChangeModel::setNoShadowPartialOccupator (MSLane * lane) inline
Definition at line 361 of file MSAbstractLaneChangeModel.h.
References myNoPartiallyOccupatedByShadow, primaryLaneChanged(), removeShadowApproachingInformation(), and setShadowApproachingInformation().
Referenced by MSVehicle::enterLaneAtLaneChange().
virtual void MSAbstractLaneChangeModel::setOwnState (int state) inline virtual
Reimplemented in MSLCM_SL2015.
Definition at line 152 of file MSAbstractLaneChangeModel.h.
References myOwnState.
Referenced by MSLaneChangerSublane::change(), and MSLaneChanger::change().
void MSAbstractLaneChangeModel::setShadowApproachingInformation (MSLink * link) const
set approach information for the shadow vehicle
Definition at line 334 of file MSAbstractLaneChangeModel.cpp.
References myApproachedByShadow.
Referenced by MSVehicle::checkRewindLinkLanes(), and setNoShadowPartialOccupator().
void MSAbstractLaneChangeModel::setShadowLane (MSLane * lane) inline
set the shadow lane
Definition at line 277 of file MSAbstractLaneChangeModel.h.
References myShadowLane.
void MSAbstractLaneChangeModel::setShadowPartialOccupator (MSLane * lane) inline
Definition at line 357 of file MSAbstractLaneChangeModel.h.
References myPartiallyOccupatedByShadow.
bool MSAbstractLaneChangeModel::startLaneChangeManeuver (MSLane * source, MSLane * target, int direction)
start the lane change maneuver and return whether it continues
Definition at line 141 of file MSAbstractLaneChangeModel.cpp.
References changedToOpposite(), DELTA_T, MSLane::getCenterOnEdge(), MSLane::getEdge(), MSGlobals::gLaneChangeDuration, myLaneChangeCompletion, myLaneChangeDirection, myLateralspeed, myVehicle, primaryLaneChanged(), SUMOReal, MSVehicle::switchOffSignal(), MSVehicle::switchOnSignal(), MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSLaneChanger::changeOpposite(), resetChanged(), MSLaneChanger::startChange(), and MSLaneChangerSublane::startChangeSublane().
void MSAbstractLaneChangeModel::unchanged () inline
Definition at line 258 of file MSAbstractLaneChangeModel.h.
References DELTA_T, and myLastLaneChangeOffset.
Referenced by MSLaneChanger::registerUnchanged().
bool MSAbstractLaneChangeModel::updateCompletion ()
Definition at line 183 of file MSAbstractLaneChangeModel.cpp.
References DELTA_T, MSGlobals::gLaneChangeDuration, myLaneChangeCompletion, pastMidpoint(), and SUMOReal.
Referenced by MSLaneChanger::continueChange(), and resetChanged().
virtual void MSAbstractLaneChangeModel::updateExpectedSublaneSpeeds (const MSLeaderInfo & ahead, int sublaneOffset, int laneIndex) inline virtual
update expected speeds for each sublane of the current edge
Reimplemented in MSLCM_SL2015.
Definition at line 215 of file MSAbstractLaneChangeModel.h.
References myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::change().
void MSAbstractLaneChangeModel::updateShadowLane ()
Definition at line 260 of file MSAbstractLaneChangeModel.cpp.
References endLaneChangeManeuver(), gDebugFlag4, MSVehicle::getFurtherLanes(), MSVehicle::getFurtherLanesPosLat(), MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getLateralOverlap(), MSVehicle::getLateralPositionOnLane(), getShadowLane(), isChangingLanes(), myShadowFurtherLanes, myShadowFurtherLanesPosLat, myShadowLane, myVehicle, NUMERICAL_EPS, MSLane::resetPartialOccupation(), MSLane::setPartialOccupation(), SIMTIME, time2string(), toString(), MSVehicle::updateFurtherLanes(), and WRITE_WARNING.
Referenced by MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), resetChanged(), and MSLaneChangerSublane::startChangeSublane().
virtual int MSAbstractLaneChangeModel::wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > & leader, const std::pair< MSVehicle *, SUMOReal > & neighLead, const std::pair< MSVehicle *, SUMOReal > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked) inline virtual
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
Reimplemented in MSLCM_LC2013, MSLCM_JE2013, and MSLCM_DK2008.
Definition at line 162 of file MSAbstractLaneChangeModel.h.
References myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChanger::checkChange().
virtual int MSAbstractLaneChangeModel::wantsChangeSublane (int laneOffset, const MSLeaderDistanceInfo & leaders, const MSLeaderDistanceInfo & followers, const MSLeaderDistanceInfo & blockers, const MSLeaderDistanceInfo & neighLeaders, const MSLeaderDistanceInfo & neighFollowers, const MSLeaderDistanceInfo & neighBlockers, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked, SUMOReal & latDist, int & blocked) inline virtual
Reimplemented in MSLCM_SL2015.
Definition at line 185 of file MSAbstractLaneChangeModel.h.
References myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::checkChangeSublane().
Field Documentation
bool MSAbstractLaneChangeModel::myAllowOvertakingRight static protected
whether overtaking on the right is permitted
Definition at line 430 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::checkStrategicChange(), MSLCM_JE2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), and initGlobalOptions().
bool MSAbstractLaneChangeModel::myAlreadyChanged protected
whether the vehicle has already moved this step
Definition at line 402 of file MSAbstractLaneChangeModel.h.
Referenced by alreadyChanged(), changedToOpposite(), and resetChanged().
bool MSAbstractLaneChangeModel::myAmOpposite private
whether the vehicle is driving in the opposite direction
Definition at line 445 of file MSAbstractLaneChangeModel.h.
Referenced by changedToOpposite(), and isOpposite().
std::vector<MSLink*> MSAbstractLaneChangeModel::myApproachedByShadow mutable private
links which are approached by the shadow vehicle
Definition at line 442 of file MSAbstractLaneChangeModel.h.
Referenced by removeShadowApproachingInformation(), and setShadowApproachingInformation().
const MSCFModel& MSAbstractLaneChangeModel::myCarFollowModel protected
The vehicle's car following model.
Definition at line 413 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::checkStrategicChange(), MSLCM_DK2008::informBlocker(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), predInteraction(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
SUMOReal MSAbstractLaneChangeModel::myLaneChangeCompletion protected
progress of the lane change maneuver 0:started, 1:complete
Definition at line 393 of file MSAbstractLaneChangeModel.h.
Referenced by endLaneChangeManeuver(), getAngleOffset(), getShadowLane(), isChangingLanes(), pastMidpoint(), remainingTime(), startLaneChangeManeuver(), and updateCompletion().
int MSAbstractLaneChangeModel::myLaneChangeDirection protected
direction of the lane change maneuver -1 means right, 1 means left
Definition at line 396 of file MSAbstractLaneChangeModel.h.
Referenced by getAngleOffset(), getLaneChangeDirection(), getShadowDirection(), and startLaneChangeManeuver().
SUMOTime MSAbstractLaneChangeModel::myLastLaneChangeOffset private
Definition at line 439 of file MSAbstractLaneChangeModel.h.
Referenced by getLastLaneChangeOffset(), initLastLaneChangeOffset(), and unchanged().
SUMOReal MSAbstractLaneChangeModel::myLateralspeed protected
The lateral offset during a continuous LaneChangeManeuver.
Definition at line 399 of file MSAbstractLaneChangeModel.h.
Referenced by getLateralSpeed(), and startLaneChangeManeuver().
bool MSAbstractLaneChangeModel::myLCOutput static protected
whether to record lane-changing
Definition at line 433 of file MSAbstractLaneChangeModel.h.
Referenced by initGlobalOptions(), and primaryLaneChanged().
const LaneChangeModel MSAbstractLaneChangeModel::myModel protected
the type of this model
Definition at line 416 of file MSAbstractLaneChangeModel.h.
Referenced by decideDirection(), updateExpectedSublaneSpeeds(), wantsChange(), and wantsChangeSublane().
std::vector<MSLane*> MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow protected
Definition at line 423 of file MSAbstractLaneChangeModel.h.
Referenced by cleanupShadowLane(), endLaneChangeManeuver(), getShadowLane(), and setNoShadowPartialOccupator().
int MSAbstractLaneChangeModel::myOwnState protected
The current state of the vehicle.
Definition at line 390 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLCM_DK2008::amBlockingFollower(), MSLCM_JE2013::amBlockingFollower(), MSLCM_LC2013::amBlockingFollower(), MSLCM_SL2015::amBlockingFollower(), MSLCM_DK2008::amBlockingFollowerNB(), MSLCM_JE2013::amBlockingFollowerNB(), MSLCM_LC2013::amBlockingFollowerNB(), MSLCM_SL2015::amBlockingFollowerNB(), MSLCM_DK2008::amBlockingFollowerPlusNB(), MSLCM_JE2013::amBlockingFollowerPlusNB(), MSLCM_LC2013::amBlockingFollowerPlusNB(), MSLCM_SL2015::amBlockingFollowerPlusNB(), MSLCM_DK2008::amBlockingLeader(), MSLCM_JE2013::amBlockingLeader(), MSLCM_LC2013::amBlockingLeader(), MSLCM_SL2015::amBlockingLeader(), MSLCM_DK2008::changed(), MSLCM_SL2015::changed(), MSLCM_JE2013::changed(), MSLCM_LC2013::changed(), getOwnState(), MSLCM_DK2008::inform(), MSLCM_SL2015::inform(), MSLCM_JE2013::inform(), MSLCM_LC2013::inform(), MSLCM_DK2008::patchSpeed(), MSLCM_DK2008::prepareStep(), MSLCM_JE2013::prepareStep(), MSLCM_SL2015::prepareStep(), MSLCM_LC2013::prepareStep(), primaryLaneChanged(), MSLCM_SL2015::setOwnState(), setOwnState(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
std::vector<MSLane*> MSAbstractLaneChangeModel::myPartiallyOccupatedByShadow protected
list of lanes where the shadow vehicle is partial occupator
Definition at line 419 of file MSAbstractLaneChangeModel.h.
Referenced by setShadowPartialOccupator().
std::vector<MSLane*> MSAbstractLaneChangeModel::myShadowFurtherLanes protected
Definition at line 409 of file MSAbstractLaneChangeModel.h.
Referenced by cleanupShadowLane(), getShadowFurtherLanes(), and updateShadowLane().
std::vector<SUMOReal> MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat protected
Definition at line 410 of file MSAbstractLaneChangeModel.h.
Referenced by getShadowFurtherLanesPosLat(), and updateShadowLane().
MSLane* MSAbstractLaneChangeModel::myShadowLane protected
A lane that is partially occupied by the front of the vehicle but that is not the primary lane.
Definition at line 405 of file MSAbstractLaneChangeModel.h.
Referenced by cleanupShadowLane(), getShadowDirection(), getShadowLane(), setShadowLane(), and updateShadowLane().
MSVehicle& MSAbstractLaneChangeModel::myVehicle protected
The vehicle this lane-changer belongs to.
Definition at line 387 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), cancelRequest(), MSLCM_JE2013::changed(), MSLCM_SL2015::changed(), MSLCM_LC2013::changed(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::checkStrategicChange(), cleanupShadowLane(), congested(), MSLCM_SL2015::decideDirection(), endLaneChangeManeuver(), getShadowDirection(), getShadowLane(), MSLCM_JE2013::inform(), MSLCM_SL2015::inform(), MSLCM_LC2013::inform(), MSLCM_DK2008::informBlocker(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), MSLCM_SL2015::keepLatGap(), MSLCM_SL2015::msg(), MSLCM_JE2013::MSLCM_JE2013(), MSLCM_LC2013::MSLCM_LC2013(), MSLCM_DK2008::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSLCM_LC2013::patchSpeed(), predInteraction(), MSLCM_SL2015::prepareStep(), primaryLaneChanged(), removeShadowApproachingInformation(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), startLaneChangeManeuver(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), updateShadowLane(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
The documentation for this class was generated from the following files:
MSAbstractLaneChangeModel.h
MSAbstractLaneChangeModel.cpp