SUMO - Simulation of Urban MObility: GUIPerspectiveChanger Class Reference
GUIPerspectiveChanger Class Reference abstract
#include <GUIPerspectiveChanger.h>
Public Types
enum MouseState { MOUSEBTN_NONE = 0, MOUSEBTN_LEFT = 1, MOUSEBTN_RIGHT = 2, MOUSEBTN_MIDDLE = 4 }
mouse states
Public Member Functions
virtual void centerTo (const Position &pos, SUMOReal radius, bool applyZoom=true)=0
Centers the view to the given position, setting it to a size that covers the radius. Used for: Centering of vehicles and junctions */.
virtual void changeCanvassLeft (int change)=0
FXint getMouseXPosition () const
Returns the last mouse x-position an event occured at.
FXint getMouseYPosition () const
Returns the last mouse y-position an event occured at.
virtual SUMOReal getRotation () const =0
Returns the rotation of the canvas stored in this changer.
Boundary getViewport (bool fixRatio=true)
get viewport
virtual SUMOReal getXPos () const =0
Returns the x-offset of the field to show stored in this changer.
virtual SUMOReal getYPos () const =0
Returns the y-offset of the field to show stored in this changer.
virtual SUMOReal getZoom () const =0
Returns the zoom factor computed stored in this changer.
virtual SUMOReal getZPos () const =0
Returns the camera height corresponding to the current zoom factor.
GUIPerspectiveChanger (GUISUMOAbstractView &callBack, const Boundary &viewPort)
Constructor.
virtual void setViewport (SUMOReal zoom, SUMOReal xPos, SUMOReal yPos)=0
Sets the viewport Used for: Adapting a new viewport.
void setViewport (const Boundary &viewPort)
set viewport
virtual void setViewportFrom (SUMOReal xPos, SUMOReal yPos, SUMOReal zPos)=0
Alternative method for setting the viewport.
virtual SUMOReal zoom2ZPos (SUMOReal zoom) const =0
Returns the camera height at which the given zoom level is reached.
virtual SUMOReal zPos2Zoom (SUMOReal zPos) const =0
Returns the zoom level that is achieved at a given camera height.
virtual ~GUIPerspectiveChanger ()
Destructor.
virtual void onLeftBtnPress (void *data)
mouse functions
virtual bool onLeftBtnRelease (void *data)
called when user releases left button
virtual void onRightBtnPress (void *data)
called when user press right button
virtual bool onRightBtnRelease (void *data)
called when user releases right button
virtual void onDoubleClicked (void *data)
called when user click two times
virtual void onMouseWheel (void *data)
called when user changes mouse wheel
virtual void onMouseMove (void *data)
called when user moves mouse
virtual long onKeyPress (void *data)
called when user press a key
virtual long onKeyRelease (void *data)
called when user releases a key
Protected Attributes
GUISUMOAbstractView & myCallback
The parent window (canvas to scale)
FXint myMouseXPosition
the current mouse position
FXint myMouseYPosition
Boundary myViewPort
the intended viewport
Private Member Functions
GUIPerspectiveChanger (const GUIPerspectiveChanger &)
Invalidated copy constructor.
GUIPerspectiveChanger & operator= (const GUIPerspectiveChanger &)
Invalidated assignment operator.
Boundary patchedViewPort ()
patched viewPort with the same aspect ratio as the canvas
Detailed Description
This is the interface for implementation of own classes that handle the interaction between the user and a display field. While most of our (IVF) interfaces allow zooming by choosing the rectangle to show, other types of interaction are possible and have been implemented. To differ between the behaviours, all types of interaction between the user and the canvas are send to this class: mouse moving, mouse button pressing and releasing.
Definition at line 60 of file GUIPerspectiveChanger.h.
Member Enumeration Documentation
enum GUIPerspectiveChanger::MouseState
mouse states
Enumerator
MOUSEBTN_NONE
MOUSEBTN_LEFT
MOUSEBTN_RIGHT
MOUSEBTN_MIDDLE
Definition at line 63 of file GUIPerspectiveChanger.h.
Constructor & Destructor Documentation
GUIPerspectiveChanger::GUIPerspectiveChanger (GUISUMOAbstractView & callBack, const Boundary & viewPort)
Constructor.
Definition at line 44 of file GUIPerspectiveChanger.cpp.
GUIPerspectiveChanger::~GUIPerspectiveChanger () virtual
Destructor.
Definition at line 50 of file GUIPerspectiveChanger.cpp.
GUIPerspectiveChanger::GUIPerspectiveChanger (const GUIPerspectiveChanger &) private
Invalidated copy constructor.
Member Function Documentation
virtual void GUIPerspectiveChanger::centerTo (const Position & pos, SUMOReal radius, bool applyZoom = true) pure virtual
Centers the view to the given position, setting it to a size that covers the radius. Used for: Centering of vehicles and junctions */.
Implemented in GUIDanielPerspectiveChanger.
Referenced by GUISUMOAbstractView::centerTo().
virtual void GUIPerspectiveChanger::changeCanvassLeft (int change) pure virtual
Implemented in GUIDanielPerspectiveChanger.
Referenced by GNEViewNet::updateModeSpecificControls().
FXint GUIPerspectiveChanger::getMouseXPosition () const
Returns the last mouse x-position an event occured at.
Definition at line 103 of file GUIPerspectiveChanger.cpp.
References myMouseXPosition.
FXint GUIPerspectiveChanger::getMouseYPosition () const
Returns the last mouse y-position an event occured at.
Definition at line 109 of file GUIPerspectiveChanger.cpp.
References myMouseYPosition.
virtual SUMOReal GUIPerspectiveChanger::getRotation () const pure virtual
Returns the rotation of the canvas stored in this changer.
Implemented in GUIDanielPerspectiveChanger.
Boundary GUIPerspectiveChanger::getViewport (bool fixRatio = true)
get viewport
Definition at line 115 of file GUIPerspectiveChanger.cpp.
References myViewPort, and patchedViewPort().
Referenced by GUISUMOAbstractView::applyGLTransform(), GUISUMOAbstractView::getObjectsInBoundary(), GUISUMOAbstractView::getPositionInformation(), GUISUMOAbstractView::getVisibleBoundary(), GUISUMOAbstractView::m2p(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::p2m(), and GUISUMOAbstractView::paintGL().
virtual SUMOReal GUIPerspectiveChanger::getXPos () const pure virtual
Returns the x-offset of the field to show stored in this changer.
Implemented in GUIDanielPerspectiveChanger.
Referenced by GUISUMOAbstractView::copyViewportTo(), GUISUMOAbstractView::getViewportEditor(), GUIDialog_EditViewport::onCmdLoad(), GUIApplicationWindow::onCmdNetedit(), GUISUMOAbstractView::onMouseMove(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_GUI::processSet(), GUISUMOAbstractView::showViewportEditor(), and GUISUMOAbstractView::~GUISUMOAbstractView().
virtual SUMOReal GUIPerspectiveChanger::getYPos () const pure virtual
Returns the y-offset of the field to show stored in this changer.
Implemented in GUIDanielPerspectiveChanger.
Referenced by GUISUMOAbstractView::copyViewportTo(), GUISUMOAbstractView::getViewportEditor(), GUIDialog_EditViewport::onCmdLoad(), GUIApplicationWindow::onCmdNetedit(), GUISUMOAbstractView::onMouseMove(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_GUI::processSet(), GUISUMOAbstractView::showViewportEditor(), and GUISUMOAbstractView::~GUISUMOAbstractView().
virtual SUMOReal GUIPerspectiveChanger::getZoom () const pure virtual
Returns the zoom factor computed stored in this changer.
Implemented in GUIDanielPerspectiveChanger.
Referenced by GUISUMOAbstractView::getViewportEditor(), GUIDialog_EditViewport::onCmdLoad(), GUISUMOAbstractView::onMouseMove(), and TraCIServerAPI_GUI::processGet().
virtual SUMOReal GUIPerspectiveChanger::getZPos () const pure virtual
Returns the camera height corresponding to the current zoom factor.
Implemented in GUIDanielPerspectiveChanger.
Referenced by GUISUMOAbstractView::copyViewportTo(), GUIApplicationWindow::onCmdNetedit(), TraCIServerAPI_GUI::processSet(), GUISUMOAbstractView::showViewportEditor(), and GUISUMOAbstractView::~GUISUMOAbstractView().
void GUIPerspectiveChanger::onDoubleClicked (void * data) virtual
called when user click two times
Definition at line 76 of file GUIPerspectiveChanger.cpp.
long GUIPerspectiveChanger::onKeyPress (void * data) virtual
called when user press a key
Reimplemented in GUIDanielPerspectiveChanger.
Definition at line 91 of file GUIPerspectiveChanger.cpp.
Referenced by GUISUMOAbstractView::onKeyPress().
long GUIPerspectiveChanger::onKeyRelease (void * data) virtual
called when user releases a key
Definition at line 97 of file GUIPerspectiveChanger.cpp.
Referenced by GUISUMOAbstractView::onKeyRelease().
void GUIPerspectiveChanger::onLeftBtnPress (void * data) virtual
mouse functions
called when user press left button
Reimplemented in GUIDanielPerspectiveChanger.
Definition at line 55 of file GUIPerspectiveChanger.cpp.
Referenced by GUISUMOAbstractView::onLeftBtnPress().
bool GUIPerspectiveChanger::onLeftBtnRelease (void * data) virtual
called when user releases left button
Reimplemented in GUIDanielPerspectiveChanger.
Definition at line 60 of file GUIPerspectiveChanger.cpp.
Referenced by GUISUMOAbstractView::onLeftBtnRelease().
void GUIPerspectiveChanger::onMouseMove (void * data) virtual
called when user moves mouse
Reimplemented in GUIDanielPerspectiveChanger.
Definition at line 86 of file GUIPerspectiveChanger.cpp.
Referenced by GUISUMOAbstractView::onMouseMove().
void GUIPerspectiveChanger::onMouseWheel (void * data) virtual
called when user changes mouse wheel
Reimplemented in GUIDanielPerspectiveChanger.
Definition at line 81 of file GUIPerspectiveChanger.cpp.
Referenced by GUISUMOAbstractView::onMouseWheel().
void GUIPerspectiveChanger::onRightBtnPress (void * data) virtual
called when user press right button
Reimplemented in GUIDanielPerspectiveChanger.
Definition at line 66 of file GUIPerspectiveChanger.cpp.
Referenced by GUISUMOAbstractView::onRightBtnPress().
bool GUIPerspectiveChanger::onRightBtnRelease (void * data) virtual
called when user releases right button
Reimplemented in GUIDanielPerspectiveChanger.
Definition at line 71 of file GUIPerspectiveChanger.cpp.
Referenced by GUISUMOAbstractView::onRightBtnRelease(), and GUISUMOAbstractView::openObjectDialog().
GUIPerspectiveChanger& GUIPerspectiveChanger::operator= (const GUIPerspectiveChanger &) private
Invalidated assignment operator.
Boundary GUIPerspectiveChanger::patchedViewPort () private
patched viewPort with the same aspect ratio as the canvas
Definition at line 131 of file GUIPerspectiveChanger.cpp.
References Boundary::getHeight(), Boundary::getWidth(), Boundary::growHeight(), Boundary::growWidth(), myCallback, myViewPort, and SUMOReal.
Referenced by getViewport().
virtual void GUIPerspectiveChanger::setViewport (SUMOReal zoom, SUMOReal xPos, SUMOReal yPos) pure virtual
Sets the viewport Used for: Adapting a new viewport.
Implemented in GUIDanielPerspectiveChanger.
Referenced by GUISUMOAbstractView::centerTo(), GUISUMOAbstractView::getObjectsInBoundary(), and GUISUMOAbstractView::recenterView().
void GUIPerspectiveChanger::setViewport (const Boundary & viewPort)
set viewport
Definition at line 125 of file GUIPerspectiveChanger.cpp.
References myViewPort.
virtual void GUIPerspectiveChanger::setViewportFrom (SUMOReal xPos, SUMOReal yPos, SUMOReal zPos) pure virtual
Alternative method for setting the viewport.
Implemented in GUIDanielPerspectiveChanger.
Referenced by GUISUMOAbstractView::setViewportFromTo().
virtual SUMOReal GUIPerspectiveChanger::zoom2ZPos (SUMOReal zoom) const pure virtual
Returns the camera height at which the given zoom level is reached.
Implemented in GUIDanielPerspectiveChanger.
Referenced by GUISettingsHandler::applyViewport(), GUIDialog_EditViewport::onCmdChanged(), TraCIServerAPI_GUI::processSet(), and GUIDialog_EditViewport::setValues().
virtual SUMOReal GUIPerspectiveChanger::zPos2Zoom (SUMOReal zPos) const pure virtual
Returns the zoom level that is achieved at a given camera height.
Implemented in GUIDanielPerspectiveChanger.
Referenced by GUIDialog_EditViewport::onCmdChanged(), and GUIDialog_EditViewport::setValues().
Field Documentation
GUISUMOAbstractView& GUIPerspectiveChanger::myCallback protected
The parent window (canvas to scale)
Definition at line 158 of file GUIPerspectiveChanger.h.
Referenced by GUIDanielPerspectiveChanger::changeCanvassLeft(), GUIDanielPerspectiveChanger::move(), GUIDanielPerspectiveChanger::onKeyPress(), GUIDanielPerspectiveChanger::onMouseMove(), GUIDanielPerspectiveChanger::onMouseWheel(), GUIDanielPerspectiveChanger::onRightBtnPress(), patchedViewPort(), GUIDanielPerspectiveChanger::setViewport(), and GUIDanielPerspectiveChanger::zoom().
FXint GUIPerspectiveChanger::myMouseXPosition protected
the current mouse position
Definition at line 161 of file GUIPerspectiveChanger.h.
Referenced by getMouseXPosition(), GUIDanielPerspectiveChanger::onLeftBtnPress(), GUIDanielPerspectiveChanger::onLeftBtnRelease(), GUIDanielPerspectiveChanger::onMouseMove(), GUIDanielPerspectiveChanger::onRightBtnPress(), and GUIDanielPerspectiveChanger::onRightBtnRelease().
FXint GUIPerspectiveChanger::myMouseYPosition protected
Definition at line 161 of file GUIPerspectiveChanger.h.
Referenced by getMouseYPosition(), GUIDanielPerspectiveChanger::onLeftBtnPress(), GUIDanielPerspectiveChanger::onLeftBtnRelease(), GUIDanielPerspectiveChanger::onMouseMove(), GUIDanielPerspectiveChanger::onRightBtnPress(), and GUIDanielPerspectiveChanger::onRightBtnRelease().
Boundary GUIPerspectiveChanger::myViewPort protected
the intended viewport
Definition at line 164 of file GUIPerspectiveChanger.h.
Referenced by GUIDanielPerspectiveChanger::centerTo(), GUIDanielPerspectiveChanger::changeCanvassLeft(), getViewport(), GUIDanielPerspectiveChanger::getXPos(), GUIDanielPerspectiveChanger::getYPos(), GUIDanielPerspectiveChanger::getZoom(), GUIDanielPerspectiveChanger::getZPos(), GUIDanielPerspectiveChanger::move(), GUIDanielPerspectiveChanger::onKeyPress(), patchedViewPort(), GUIDanielPerspectiveChanger::setViewport(), setViewport(), and GUIDanielPerspectiveChanger::zoom().
The documentation for this class was generated from the following files:
GUIPerspectiveChanger.h
GUIPerspectiveChanger.cpp