SUMO - Simulation of Urban MObility: GNERerouter::rerouterInterval Class Reference
GNERerouter::rerouterInterval Class Reference
#include <GNERerouter.h>
Public Member Functions
SUMOTime getBegin () const
get time begin
std::vector< closingReroute * > getClosingReroutes () const
get closing reroutes
std::vector< destProbReroute * > getDestProbReroutes () const
get destiny probability reroutes
SUMOTime getEnd () const
get time end
std::vector< routeProbReroute * > getRouteProbReroutes () const
get reoute probability reroutes
void insertClosingReroutes (closingReroute *cr)
insert a new closing reroute
void insertDestProbReroutes (destProbReroute *dpr)
insert destiny probability reroute
void insertRouteProbReroute (routeProbReroute *rpr)
insert route probability reroute
void removeClosingReroutes (closingReroute *cr)
remove a previously inserted closing reroute
void removeDestProbReroutes (destProbReroute *dpr)
remove a previously inserted destiny probability reroute
void removeRouteProbReroute (routeProbReroute *rpr)
remove a previously inserted route probability reroute
rerouterInterval (SUMOTime begin, SUMOTime end)
constructor
~rerouterInterval ()
destructor
Private Attributes
std::vector< closingReroute * > myClosingReroutes
vector with the closingReroutes
std::vector< destProbReroute * > myDestProbReroutes
vector with the destProbReroutes
std::vector< routeProbReroute * > myRouteProbReroutes
vector with the routeProbReroutes
Detailed Description
Definition at line 163 of file GNERerouter.h.
Constructor & Destructor Documentation
GNERerouter::rerouterInterval::rerouterInterval (SUMOTime begin, SUMOTime end)
constructor
Definition at line 229 of file GNERerouter.cpp.
GNERerouter::rerouterInterval::~rerouterInterval ()
destructor
Definition at line 234 of file GNERerouter.cpp.
Member Function Documentation
SUMOTime GNERerouter::rerouterInterval::getBegin () const
get time begin
Definition at line 320 of file GNERerouter.cpp.
std::vector< GNERerouter::closingReroute * > GNERerouter::rerouterInterval::getClosingReroutes () const
get closing reroutes
Definition at line 332 of file GNERerouter.cpp.
References myClosingReroutes.
std::vector< GNERerouter::destProbReroute * > GNERerouter::rerouterInterval::getDestProbReroutes () const
get destiny probability reroutes
Definition at line 338 of file GNERerouter.cpp.
References myDestProbReroutes.
SUMOTime GNERerouter::rerouterInterval::getEnd () const
get time end
Definition at line 326 of file GNERerouter.cpp.
std::vector< GNERerouter::routeProbReroute * > GNERerouter::rerouterInterval::getRouteProbReroutes () const
get reoute probability reroutes
Definition at line 344 of file GNERerouter.cpp.
References myRouteProbReroutes.
void GNERerouter::rerouterInterval::insertClosingReroutes (GNERerouter::closingReroute * cr)
insert a new closing reroute
Exceptions
ProcessError if closing reroute was already inserted
Definition at line 239 of file GNERerouter.cpp.
References GNERerouter::closingReroute::getClosedEdgeId(), and myClosingReroutes.
void GNERerouter::rerouterInterval::insertDestProbReroutes (GNERerouter::destProbReroute * dpr)
insert destiny probability reroute
Exceptions
ProcessError if destiny probability reroute was already inserted
Definition at line 266 of file GNERerouter.cpp.
References GNERerouter::destProbReroute::getNewDestinationId(), and myDestProbReroutes.
void GNERerouter::rerouterInterval::insertRouteProbReroute (GNERerouter::routeProbReroute * rpr)
insert route probability reroute
Exceptions
ProcessError if route probability reroute was already inserted
Definition at line 293 of file GNERerouter.cpp.
References GNERerouter::routeProbReroute::getNewRouteId(), and myRouteProbReroutes.
void GNERerouter::rerouterInterval::removeClosingReroutes (GNERerouter::closingReroute * cr)
remove a previously inserted closing reroute
Exceptions
ProcessError if closing reroute cannot be found in the container
Definition at line 252 of file GNERerouter.cpp.
References GNERerouter::closingReroute::getClosedEdgeId(), and myClosingReroutes.
void GNERerouter::rerouterInterval::removeDestProbReroutes (GNERerouter::destProbReroute * dpr)
remove a previously inserted destiny probability reroute
Exceptions
ProcessError if destiny probability reroute cannot be found in the container
Definition at line 279 of file GNERerouter.cpp.
References GNERerouter::destProbReroute::getNewDestinationId(), and myDestProbReroutes.
void GNERerouter::rerouterInterval::removeRouteProbReroute (GNERerouter::routeProbReroute * rpr)
remove a previously inserted route probability reroute
Exceptions
ProcessError if route probability reroute cannot be found in the container
Definition at line 306 of file GNERerouter.cpp.
References GNERerouter::routeProbReroute::getNewRouteId(), and myRouteProbReroutes.
Field Documentation
std::vector<closingReroute*> GNERerouter::rerouterInterval::myClosingReroutes private
vector with the closingReroutes
Definition at line 212 of file GNERerouter.h.
Referenced by getClosingReroutes(), insertClosingReroutes(), and removeClosingReroutes().
std::vector<destProbReroute*> GNERerouter::rerouterInterval::myDestProbReroutes private
vector with the destProbReroutes
Definition at line 215 of file GNERerouter.h.
Referenced by getDestProbReroutes(), insertDestProbReroutes(), and removeDestProbReroutes().
std::vector<routeProbReroute*> GNERerouter::rerouterInterval::myRouteProbReroutes private
vector with the routeProbReroutes
Definition at line 218 of file GNERerouter.h.
Referenced by getRouteProbReroutes(), insertRouteProbReroute(), and removeRouteProbReroute().
The documentation for this class was generated from the following files:
GNERerouter.h
GNERerouter.cpp