SUMO - Simulation of Urban MObility: GUITextureSubSys Class Reference
GUITextureSubSys Class Reference
#include <GUITextureSubSys.h>
Static Public Member Functions
static void close ()
close GUITextureSubSys
static GUIGlID getGif (GUITexture which)
returns a texture Gif previously defined in the enum GUITexture
static void init (FXApp *a)
Initiate GUITextureSubSys for textures.
static void reset ()
Reset textures.
Private Member Functions
GUITextureSubSys (FXApp *a)
constructor
~GUITextureSubSys ()
destructor
Private Attributes
FXApp * myApp
to Fox App
std::map< GUITexture, std::pair< bool, GUIGlID > > myTextures
vector with the Gifs
Static Private Attributes
static GUITextureSubSys * myInstance = 0
instance of GUITextureSubSys
Detailed Description
Definition at line 41 of file GUITextureSubSys.h.
Constructor & Destructor Documentation
GUITextureSubSys::GUITextureSubSys (FXApp * a) private
constructor
Note
is private because is called by the static function init(FXApp* a)
Definition at line 73 of file GUITextureSubSys.cpp.
References GNETEXTURE_E1, GNETEXTURE_E2, GNETEXTURE_E3, GNETEXTURE_E3SELECTED, GNETEXTURE_EMPTY, GNETEXTURE_EMPTYSELECTED, GNETEXTURE_ENTRY, GNETEXTURE_EXIT, GNETEXTURE_LOCK, GNETEXTURE_LOCKSELECTED, GNETEXTURE_NOTMOVING, GNETEXTURE_NOTMOVINGSELECTED, GNETEXTURE_REROUTER, GNETEXTURE_REROUTERSELECTED, GNETEXTURE_ROUTEPROBE, GNETEXTURE_ROUTEPROBESELECTED, GNETEXTURE_TLS, GNETEXTURE_VAPORIZER, GNETEXTURE_VAPORIZERSELECTED, GNETEXTURE_VARIABLESPEEDSIGNAL, GNETEXTURE_VARIABLESPEEDSIGNALSELECTED, and myTextures.
Referenced by init().
GUITextureSubSys::~GUITextureSubSys () private
destructor
Definition at line 100 of file GUITextureSubSys.cpp.
Member Function Documentation
void GUITextureSubSys::close () static
close GUITextureSubSys
Definition at line 202 of file GUITextureSubSys.cpp.
References myInstance.
Referenced by GNEApplicationWindow::~GNEApplicationWindow().
GUIGlID GUITextureSubSys::getGif (GUITexture which) static
returns a texture Gif previously defined in the enum GUITexture
Parameters
[in] GUITexture code of texture to use
Definition at line 112 of file GUITextureSubSys.cpp.
References GUITexturesHelper::add(), GNETexture_E1, GNETEXTURE_E1, GNETexture_E2, GNETEXTURE_E2, GNETexture_E3, GNETEXTURE_E3, GNETexture_E3Selected, GNETEXTURE_E3SELECTED, GNETexture_Empty, GNETEXTURE_EMPTY, GNETexture_EmptySelected, GNETEXTURE_EMPTYSELECTED, GNETexture_Entry, GNETEXTURE_ENTRY, GNETexture_Exit, GNETEXTURE_EXIT, GNETexture_Lock, GNETEXTURE_LOCK, GNETexture_LockSelected, GNETEXTURE_LOCKSELECTED, GNETexture_NotMoving, GNETEXTURE_NOTMOVING, GNETexture_NotMovingSelected, GNETEXTURE_NOTMOVINGSELECTED, GNETexture_Rerouter, GNETEXTURE_REROUTER, GNETexture_RerouterSelected, GNETEXTURE_REROUTERSELECTED, GNETexture_RouteProbe, GNETEXTURE_ROUTEPROBE, GNETexture_RouteProbeSelected, GNETEXTURE_ROUTEPROBESELECTED, GNETexture_TLS, GNETEXTURE_TLS, GNETexture_Vaporizer, GNETEXTURE_VAPORIZER, GNETexture_VaporizerSelected, GNETEXTURE_VAPORIZERSELECTED, GNETexture_VariableSpeedSignal, GNETEXTURE_VARIABLESPEEDSIGNAL, GNETexture_VariableSpeedSignalSelected, GNETEXTURE_VARIABLESPEEDSIGNALSELECTED, myApp, myInstance, and myTextures.
Referenced by GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEDetectorE3::drawGL(), GNEJunction::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSignal::drawGL(), GNERouteProbe::drawGL(), GNERerouter::drawGL(), and GNEAdditional::drawLockIcon().
void GUITextureSubSys::init (FXApp * a) static
Initiate GUITextureSubSys for textures.
Parameters
[in] a FOX Toolkit APP
Definition at line 105 of file GUITextureSubSys.cpp.
References GUITextureSubSys(), and myInstance.
Referenced by GNEApplicationWindow::GNEApplicationWindow().
void GUITextureSubSys::reset () static
Reset textures.
Note
Necessary to avoid problems with textures (ej: white empty)
Definition at line 193 of file GUITextureSubSys.cpp.
References myInstance, and myTextures.
Referenced by GNEApplicationWindow::closeAllWindows().
Field Documentation
FXApp* GUITextureSubSys::myApp private
to Fox App
Definition at line 67 of file GUITextureSubSys.h.
Referenced by getGif().
GUITextureSubSys * GUITextureSubSys::myInstance = 0 static private
instance of GUITextureSubSys
Definition at line 70 of file GUITextureSubSys.h.
Referenced by close(), getGif(), init(), and reset().
std::map<GUITexture, std::pair<bool, GUIGlID> > GUITextureSubSys::myTextures private
vector with the Gifs
Definition at line 73 of file GUITextureSubSys.h.
Referenced by getGif(), GUITextureSubSys(), and reset().
The documentation for this class was generated from the following files:
GUITextureSubSys.h
GUITextureSubSys.cpp