SUMO - Simulation of Urban MObility: CState Class Reference
CState Class Reference
#include <MSCModel_NonInteracting.h>
Public Member Functions
SUMOTime computeTranshipTime (const MSEdge *prev, const MSContainer::MSContainerStage_Tranship &stage, SUMOTime currentTime)
compute tranship time on edge and update state members
CState ()
SUMOReal getAngle (const MSContainer::MSContainerStage_Tranship &stage, SUMOTime now) const
return the direction in which the container heading to
SUMOReal getEdgePos (const MSContainer::MSContainerStage_Tranship &stage, SUMOTime now) const
return the offset from the start of the current edge measured in its natural direction
Position getPosition (const MSContainer::MSContainerStage_Tranship &stage, SUMOTime now) const
return the network coordinate of the container
SUMOReal getSpeed (const MSContainer::MSContainerStage_Tranship &stage) const
return the current speed of the container
~CState ()
Static Public Attributes
static const int BACKWARD
static const int FORWARD
static const SUMOReal LATERAL_OFFSET
the offset for computing container positions when being transhiped
static const int UNDEFINED_DIRECTION
Private Attributes
SUMOReal myCurrentBeginPos
Position myCurrentBeginPosition
SUMOTime myCurrentDuration
SUMOReal myCurrentEndPos
Position myCurrentEndPosition
SUMOTime myLastEntryTime
Detailed Description
Definition at line 99 of file MSCModel_NonInteracting.h.
Constructor & Destructor Documentation
CState::CState () inline
Definition at line 101 of file MSCModel_NonInteracting.h.
CState::~CState () inline
Definition at line 103 of file MSCModel_NonInteracting.h.
Member Function Documentation
SUMOTime CState::computeTranshipTime (const MSEdge * prev, const MSContainer::MSContainerStage_Tranship & stage, SUMOTime currentTime)
compute tranship time on edge and update state members
Definition at line 141 of file MSCModel_NonInteracting.cpp.
References MSContainer::MSContainerStage_Tranship::getArrivalPos(), MSContainer::MSContainerStage_Tranship::getDepartPos(), MSContainer::MSContainerStage_Tranship::getFromEdge(), MSTransportable::Stage::getLanePosition(), MSEdge::getLanes(), MSContainer::MSContainerStage_Tranship::getMaxSpeed(), MSContainer::MSContainerStage_Tranship::getToEdge(), MAX2(), and TIME2STEPS.
Referenced by MSCModel_NonInteracting::add(), and MSCModel_NonInteracting::MoveToNextEdge::execute().
SUMOReal CState::getAngle (const MSContainer::MSContainerStage_Tranship & stage, SUMOTime now) const
return the direction in which the container heading to
Definition at line 125 of file MSCModel_NonInteracting.cpp.
References MSContainer::MSContainerStage_Tranship::getEdge(), MSTransportable::Stage::getEdgeAngle(), M_PI, and SUMOReal.
Referenced by MSContainer::MSContainerStage_Tranship::getAngle().
SUMOReal CState::getEdgePos (const MSContainer::MSContainerStage_Tranship & stage, SUMOTime now) const
return the offset from the start of the current edge measured in its natural direction
Definition at line 111 of file MSCModel_NonInteracting.cpp.
Referenced by MSContainer::MSContainerStage_Tranship::getEdgePos().
Position CState::getPosition (const MSContainer::MSContainerStage_Tranship & stage, SUMOTime now) const
return the network coordinate of the container
Definition at line 117 of file MSCModel_NonInteracting.cpp.
References MSContainer::MSContainerStage_Tranship::getMaxSpeed(), MIN2(), PositionVector::positionAtOffset2D(), STEPS2TIME, and SUMOReal.
Referenced by MSContainer::MSContainerStage_Tranship::getPosition().
SUMOReal CState::getSpeed (const MSContainer::MSContainerStage_Tranship & stage) const
return the current speed of the container
Definition at line 135 of file MSCModel_NonInteracting.cpp.
References MSContainer::MSContainerStage_Tranship::getMaxSpeed().
Referenced by MSContainer::MSContainerStage_Tranship::getSpeed().
Field Documentation
const int CState::BACKWARD static
Definition at line 107 of file MSCModel_NonInteracting.h.
const int CState::FORWARD static
Definition at line 103 of file MSCModel_NonInteracting.h.
const SUMOReal CState::LATERAL_OFFSET static
the offset for computing container positions when being transhiped
Definition at line 111 of file MSCModel_NonInteracting.h.
SUMOReal CState::myCurrentBeginPos private
Definition at line 128 of file MSCModel_NonInteracting.h.
Position CState::myCurrentBeginPosition private
Definition at line 130 of file MSCModel_NonInteracting.h.
SUMOTime CState::myCurrentDuration private
Definition at line 127 of file MSCModel_NonInteracting.h.
SUMOReal CState::myCurrentEndPos private
Definition at line 129 of file MSCModel_NonInteracting.h.
Position CState::myCurrentEndPosition private
Definition at line 131 of file MSCModel_NonInteracting.h.
SUMOTime CState::myLastEntryTime private
Definition at line 126 of file MSCModel_NonInteracting.h.
const int CState::UNDEFINED_DIRECTION static
Definition at line 108 of file MSCModel_NonInteracting.h.
The documentation for this class was generated from the following files:
MSCModel_NonInteracting.h
MSCModel_NonInteracting.cpp