SUMO - Simulation of Urban MObility: GUIVehicle Class Reference
GUIVehicle Class Reference
A MSVehicle extended by some values for usage within the gui.
#include <GUIVehicle.h>
Public Types
enum ChangeRequest { REQUEST_NONE, REQUEST_LEFT, REQUEST_RIGHT, REQUEST_HOLD }
Requests set via TraCI.
typedef Named::NamedLikeComparatorIdLess< SUMOVehicle > ComparatorIdLess
Public Member Functions
void activateReminders (const MSMoveReminder::Notification reason)
"Activates" all current move reminder
void addReminder (MSMoveReminder *rem)
Adds a MoveReminder dynamically.
void addStops (const bool ignoreStopErrors)
Adds stops to the built vehicle.
bool addTraciBusOrContainerStop (const std::string &stopId, const SUMOTime duration, const SUMOTime until, const bool parking, const bool triggered, const bool containerTriggered, const bool isContainerStop, std::string &errorMsg)
bool addTraciStop (MSLane *const lane, const SUMOReal startPos, const SUMOReal endPos, const SUMOTime duration, const SUMOTime until, const bool parking, const bool triggered, const bool containerTriggered, std::string &errorMsg)
SUMOReal computeAngle () const
compute the current vehicle angle
bool congested () const
void drawAction_drawLinkItems (const GUIVisualizationSettings &s) const
void drawAction_drawPersonsAndContainers (const GUIVisualizationSettings &s) const
void drawAction_drawVehicleBlinker (SUMOReal length) const
void drawAction_drawVehicleBlueLight () const
void drawAction_drawVehicleBrakeLight (SUMOReal length, bool onlyOne=1) const
void drawBestLanes () const
Draws the vehicle's best lanes.
void drawName (const Position &pos, const SUMOReal scale, const GUIVisualizationTextSettings &settings, const SUMOReal angle=0) const
draw name of item
void drawRouteHelper (const MSRoute &r, SUMOReal exaggeration) const
Draws the route.
void enterLaneAtInsertion (MSLane *enteredLane, SUMOReal pos, SUMOReal speed, SUMOReal posLat, MSMoveReminder::Notification notification)
Update when the vehicle enters a new lane in the emit step.
void enterLaneAtLaneChange (MSLane *enteredLane)
Update when the vehicle enters a new lane in the laneChange step.
bool enterLaneAtMove (MSLane *enteredLane, bool onTeleporting=false)
Update when the vehicle enters a new lane in the move step.
bool executeMove ()
Executes planned vehicle movements with regards to right-of-way.
void fixPosition ()
repair errors in vehicle position after changing between internal edges
SUMOReal getAngle () const
Return current angle.
virtual SUMOReal getArrivalPos () const
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
PositionVector getBoundingBox () const
get bounding rectangle
PositionVector getBoundingPoly () const
get bounding polygon
const MSCFModel & getCarFollowModel () const
Returns the vehicle's car following model definition.
MSCFModel::VehicleVariables * getCarFollowVariables () const
Returns the vehicle's car following model variables.
SUMOReal getChosenSpeedFactor () const
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
SUMOReal getColorValue (int activeScheme) const
gets the color value according to the current scheme index
const MSRouteIterator & getCurrentRouteEdge () const
Returns an iterator pointing to the current edge in this vehicles route.
SUMOTime getDepartDelay () const
Returns the depart delay.
SUMOReal getDepartPos () const
Returns this vehicle's real departure position.
SUMOTime getDeparture () const
Returns this vehicle's real departure time.
MSDevice * getDevice (const std::type_info &type) const
Returns a device of the given type if it exists or 0.
const std::vector< MSDevice * > & getDevices () const
Returns this vehicle's devices.
SUMOReal getDistanceToPosition (SUMOReal destPos, const MSEdge *destEdge) const
const MSEdge * getEdge () const
Returns the edge the vehicle is currently at.
const std::vector< MSLane * > & getFurtherLanes () const
const std::vector< SUMOReal > & getFurtherLanesPosLat () const
const std::string & getID () const
Returns the name of the vehicle.
SUMOReal getImpatience () const
Returns this vehicles impatience.
Influencer & getInfluencer ()
Returns the velocity/lane influencer.
const Influencer * getInfluencer () const
MSAbstractLaneChangeModel & getLaneChangeModel ()
const MSAbstractLaneChangeModel & getLaneChangeModel () const
int getLaneIndex () const
SUMOReal getLastLaneChangeOffset () const
Returns the time since the last lane change in seconds.
std::pair< const MSVehicle *const, SUMOReal > getLeader (SUMOReal dist=0) const
Returns the leader of the vehicle looking for a fixed distance.
SUMOReal getMaxSpeed () const
Returns the maximum speed.
SUMOReal getNaviDegree () const
return the current angle in navigational degrees
Stop & getNextStop ()
int getNumberReroutes () const
Returns the number of new routes this vehicle got.
const SUMOVehicleParameter & getParameter () const
Returns the vehicle's parameter (including departure definition)
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Position getPosition (const SUMOReal offset=0) const
Return current position (x/y, cartesian)
const MSRoute & getRoute () const
Returns the current route.
SUMOReal getSafeFollowSpeed (const std::pair< const MSVehicle *, SUMOReal > leaderInfo, const SUMOReal seen, const MSLane *const lane, SUMOReal distToCrossing) const
compute safe speed for following the given leader
SUMOReal getSpeedWithoutTraciInfluence () const
Returns the uninfluenced velocity.
SUMOReal getTimeGap () const
Returns the time gap in seconds to the leader of the vehicle looking for a fixed distance.
GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window.
SUMOVehicleClass getVClass () const
Returns the vehicle's access class.
const MSVehicleType & getVehicleType () const
Returns the vehicle's type definition.
GUIVehicle (SUMOVehicleParameter *pars, const MSRoute *route, const MSVehicleType *type, const SUMOReal speedFactor)
Constructor.
bool hasDeparted () const
Returns whether this vehicle has already departed.
bool hasInfluencer () const
bool hasValidRoute (std::string &msg, const MSRoute *route=0) const
Validates the current or given route.
int influenceChangeDecision (int state)
allow TraCI to influence a lane change decision
bool knowsEdgeTest (MSEdge &edge) const
void leaveLane (const MSMoveReminder::Notification reason)
Update of members if vehicle leaves a new lane in the lane change step or at arrival.
void onDepart ()
Called when the vehicle is inserted into the network.
void planMove (const SUMOTime t, const MSLeaderInfo &ahead, const SUMOReal lengthsInFront)
Compute safe velocities for the upcoming lanes based on positions and speeds from the last time step. Also registers ApproachingVehicleInformation for all links.
SUMOReal processNextStop (SUMOReal currentVelocity)
Processes stops, returns the velocity needed to reach the stop.
void removeReminder (MSMoveReminder *rem)
Removes a MoveReminder dynamically.
bool replaceRouteEdges (ConstMSEdgeVector &edges, bool onInit=false, bool check=false)
Replaces the current route by the given edges.
void replaceVehicleType (MSVehicleType *type)
Replaces the current vehicle type by the one given.
void reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > &router, const bool onInit=false, const bool withTaz=false)
Performs a rerouting using the given router.
bool resumeFromStopping ()
void selectBlockingFoes () const
adds the blocking foes to the current selection
void setAngle (SUMOReal angle)
Set a custom vehicle angle in rad.
virtual void setArrivalPos (SUMOReal arrivalPos)
Sets this vehicle's desired arrivalPos for its current route.
void setChosenSpeedFactor (const SUMOReal factor)
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
void setTentativeLaneAndPosition (MSLane *lane, SUMOReal pos, SUMOReal posLat=0)
set tentative lane and position during insertion to ensure that all cfmodels work (some of them require veh->getLane() to return a valid lane) Once the vehicle is sucessfully inserted the lane is set again (see enterLaneAtInsertion)
void setVTDState (Position xyPos)
sets position outside the road network
const MSEdge * succEdge (int nSuccs) const
Returns the nSuccs'th successor of edge the vehicle is currently at.
bool unsafeLinkAhead (const MSLane *lane) const
whether the vehicle may safely move to the given lane with regard to upcoming links
SUMOReal updateFurtherLanes (std::vector< MSLane * > &furtherLanes, std::vector< SUMOReal > &furtherLanesPosLat, const std::vector< MSLane * > &passedLanes)
update a vector of further lanes and return the new backPos
~GUIVehicle ()
destructor
insertion/removal
void onRemovalFromNet (const MSMoveReminder::Notification reason)
Called when the vehicle is removed from the network.
interaction with the route
bool hasArrived () const
Returns whether this vehicle has already arived (reached the arrivalPosition on its final edge)
bool replaceRoute (const MSRoute *route, bool onInit=false, int offset=0)
Replaces the current route by the given one.
bool willPass (const MSEdge *const edge) const
Returns whether the vehicle wil pass the given edge.
int getRoutePosition () const
void resetRoutePosition (int index)
const MSEdgeWeightsStorage & getWeightsStorage () const
Returns the vehicle's internal edge travel times/efforts container.
MSEdgeWeightsStorage & getWeightsStorage ()
state setter/getter
SUMOReal getPositionOnLane () const
Get the vehicle's position along the lane.
SUMOReal getPositionOnLane (const MSLane *lane) const
Get the vehicle's front position relative to the given lane.
SUMOReal getBackPositionOnLane (const MSLane *lane) const
Get the vehicle's position relative to the given lane.
SUMOReal getBackPositionOnLane () const
Get the vehicle's position relative to its current lane.
SUMOReal getLateralPositionOnLane () const
Get the vehicle's lateral position on the lane.
SUMOReal getRightSideOnLane () const
Get the vehicle's lateral position on the lane:
SUMOReal getLateralOverlap () const
return the amount by which the vehicle extends laterally outside it's primary lane
SUMOReal getRightSideOnEdge (const MSLane *lane=0) const
Get the vehicle's lateral position on the edge of the given lane (or its current edge if lane == 0)
SUMOReal getCenterOnEdge (const MSLane *lane=0) const
Get the vehicle's lateral position on the edge of the given lane (or its current edge if lane == 0)
SUMOReal getLatOffset (const MSLane *lane) const
Get the offset that that must be added to interpret myState.myPosLat for the given lane.
SUMOReal getSpeed () const
Returns the vehicle's current speed.
SUMOReal getAcceleration () const
Returns the vehicle's acceleration in m/s.
Other getter methods
SUMOReal getSlope () const
Returns the slope of the road at vehicle's position.
MSLane * getLane () const
Returns the lane the vehicle is on.
bool isOnRoad () const
Returns the information whether the vehicle is on a road (is simulated)
bool isFrontOnLane (const MSLane *lane) const
Returns the information whether the front of the vehicle is on the given lane.
const MSEdge * getRerouteOrigin () const
Returns the starting point for reroutes (usually the current edge)
SUMOTime getWaitingTime () const
Returns the SUMOTime waited (speed was lesser than 0.1m/s)
SUMOTime getAccumulatedWaitingTime (SUMOTime t=MSGlobals::gWaitingTimeMemory) const
Returns the SUMOTime waited (speed was lesser than 0.1m/s) within the last t millisecs.
SUMOReal getWaitingSeconds () const
Returns the number of seconds waited (speed was lesser than 0.1m/s)
SUMOReal getAccumulatedWaitingSeconds () const
Returns the number of seconds waited (speed was lesser than 0.1m/s) within the last millisecs.
strategical/tactical lane choosing methods
const std::vector< LaneQ > & getBestLanes () const
Returns the description of best lanes to use in order to continue the route.
void updateBestLanes (bool forceRebuild=false, const MSLane *startLane=0)
computes the best lanes to use in order to continue the route
const std::vector< MSLane * > & getBestLanesContinuation () const
Returns the subpart of best lanes that describes the vehicle's current lane and their successors.
const std::vector< MSLane * > & getBestLanesContinuation (const MSLane *const l) const
Returns the subpart of best lanes that describes the given lane and their successors.
int getBestLaneOffset () const
returns the current offset from the best lane
void adaptBestLanesOccupation (int laneIndex, SUMOReal density)
update occupation from MSLaneChanger
vehicle stops definitions and i/o
bool addStop (const SUMOVehicleParameter::Stop &stopPar, std::string &errorMsg, SUMOTime untilOffset=0)
Adds a stop.
bool hasStops () const
Returns whether the vehicle has to stop somewhere.
bool isStopped () const
Returns whether the vehicle is at a stop.
bool isParking () const
Returns whether the vehicle is parking.
bool isRemoteControlled () const
Returns the information whether the vehicle is fully controlled via TraCI.
SUMOReal nextStopDist () const
return the distance to the next stop or SUMORealMax if there is none.
bool isStoppedTriggered () const
Returns whether the vehicle is on a triggered stop.
bool isStoppedInRange (SUMOReal pos) const
return whether the given position is within range of the current stop
Emission retrieval
SUMOReal getCO2Emissions () const
Returns CO2 emission of the current state.
SUMOReal getCOEmissions () const
Returns CO emission of the current state.
SUMOReal getHCEmissions () const
Returns HC emission of the current state.
SUMOReal getNOxEmissions () const
Returns NOx emission of the current state.
SUMOReal getPMxEmissions () const
Returns PMx emission of the current state.
SUMOReal getFuelConsumption () const
Returns fuel consumption of the current state.
SUMOReal getElectricityConsumption () const
Returns electricity consumption of the current state.
SUMOReal getHarmonoise_NoiseEmissions () const
Returns noise emissions of the current state.
Interaction with persons
void addPerson (MSTransportable *person)
Adds a passenger.
Interaction with containers
void addContainer (MSTransportable *container)
Adds a container.
const std::vector< MSTransportable * > & getPersons () const
retrieve riding persons
const std::vector< MSTransportable * > & getContainers () const
retrieve riding containers
int getPersonNumber () const
Returns the number of persons.
int getContainerNumber () const
Returns the number of containers.
state io
void saveState (OutputDevice &out)
Saves the states of a vehicle.
void loadState (const SUMOSAXAttributes &attrs, const SUMOTime offset)
Loads the state of this vehicle from the given description.
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawOnPos (const GUIVisualizationSettings &s, const Position &pos, const SUMOReal angle) const
Draws the object on the specified position with the specified angle.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additionally triggered visualisations.
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
virtual const std::string & getParentName () const
Returns the name of the parent object (if any)
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static int nextLinkPriority (const std::vector< MSLane * > &conts)
get a numerical value for the priority of the upcoming link
static bool overlap (const MSVehicle *veh1, const MSVehicle *veh2)
static bool setFunctionalColor (int activeScheme, const MSBaseVehicle *veh)
sets the color according to the current scheme index and some vehicle function
Static Public Attributes
static const GUIGlID INVALID_ID = 0
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Types
typedef std::vector< DriveProcessItem > DriveItemVector
Container for used Links/visited Lanes during lookForward.
Protected Member Functions
void adaptToLeader (const std::pair< const MSVehicle *, SUMOReal > leaderInfo, const SUMOReal seen, DriveProcessItem *const lastLink, const MSLane *const lane, SUMOReal &v, SUMOReal &vLinkPass, SUMOReal distToCrossing=-1) const
void adaptToLeaders (const MSLeaderInfo &ahead, SUMOReal latOffset, const SUMOReal seen, DriveProcessItem *const lastLink, const MSLane *const lane, SUMOReal &v, SUMOReal &vLinkPass) const
void calculateArrivalParams ()
(Re-)Calculates the arrival position and lane from the vehicle parameters
void checkRewindLinkLanes (const SUMOReal lengthsInFront, DriveItemVector &lfLinks) const
void drawOutsideNetwork (bool) const
register vehicle for drawing while outside the network
SUMOReal estimateLeaveSpeed (const MSLink *const link, const SUMOReal vLinkPass) const
estimate leaving speed when accelerating across a link
SUMOReal estimateSpeedAfterDistance (const SUMOReal dist, const SUMOReal v, const SUMOReal accel) const
const MSLane * getBackLane () const
const Position getBackPosition () const
const Position & getSeatPosition (int personIndex) const
returns the seat position for the person with the given index
SUMOReal getSpaceTillLastStanding (const MSLane *l, bool &foundStopped) const
const ConstMSEdgeVector getStopEdges () const
Returns the list of still pending stop edges.
void planMoveInternal (const SUMOTime t, MSLeaderInfo ahead, DriveItemVector &lfLinks, SUMOReal &myStopDist) const
void removeApproachingInformation (DriveItemVector &lfLinks) const
unregister approach from all upcoming links
void setBlinkerInformation ()
void setColor (const GUIVisualizationSettings &s) const
sets the color according to the currente settings
void setEmergencyBlueLight (SUMOTime currentTime)
sets the blue flashing light for emergency vehicles
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
void updateOccupancyAndCurrentBestLane (const MSLane *startLane)
updates LaneQ::nextOccupation and myCurrentLaneInBestLanes
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Static Protected Member Functions
static void drawLinkItem (const Position &pos, SUMOTime arrivalTime, SUMOTime leaveTime, SUMOReal exagerate)
Protected Attributes
SUMOReal myAcceleration
The current acceleration after dawdling in m/s.
bool myAmOnNet
Whether the vehicle is on the network (not parking, teleported, vaporized, or arrived)
bool myAmRegisteredAsWaitingForContainer
Whether this vehicle is registered as waiting for a container (for deadlock-recognition)
bool myAmRegisteredAsWaitingForPerson
Whether this vehicle is registered as waiting for a person (for deadlock-recognition)
SUMOReal myAngle
the angle (
int myArrivalLane
The destination lane where the vehicle stops.
SUMOReal myArrivalPos
The position on the destination lane where the vehicle stops.
std::vector< std::vector< LaneQ > > myBestLanes
Position myCachedPosition
SUMOReal myCarriageLength
Variable to set with the length of the last drawn carriage or the vehicle length.
SUMOReal myChosenSpeedFactor
A precomputed factor by which the driver wants to be faster than the speed limit.
MSDevice_Transportable * myContainerDevice
The containers this vehicle may have.
MSRouteIterator myCurrEdge
Iterator to current route-edge.
std::vector< LaneQ >::iterator myCurrentLaneInBestLanes
SUMOReal myDepartPos
The real depart position.
SUMOTime myDeparture
The real departure time.
std::vector< MSDevice * > myDevices
The devices this vehicle has.
std::vector< MSLane * > myFurtherLanes
The information into which lanes the vehicle laps into.
std::vector< SUMOReal > myFurtherLanesPosLat
bool myHaveToWaitOnNextLink
MSLane * myLane
The lane the vehicle is on.
MSAbstractLaneChangeModel * myLaneChangeModel
const MSEdge * myLastBestLanesEdge
const MSLane * myLastBestLanesInternalLane
DriveItemVector myLFLinkLanes
MFXMutex myLock
The mutex used to avoid concurrent updates of the vehicle buffer.
int myNumberReroutes
The number of reroutings.
const SUMOVehicleParameter * myParameter
This Vehicle's parameter.
MSDevice_Transportable * myPersonDevice
The passengers this vehicle may have.
const MSRoute * myRoute
This Vehicle's route.
PositionVector mySeatPositions
positions of seats in the vehicle (updated at every drawing step)
int mySignals
State of things of the vehicle that can be on or off.
State myState
This Vehicles driving state (pos and speed)
SUMOReal myStopDist
distance to the next stop or -1 if there is none
std::list< Stop > myStops
The vehicle's list of stops.
const MSVehicleType * myType
This Vehicle's type.
SUMOTime myWaitingTime
The time the vehicle waits (is not faster than 0.1m/s) in seconds.
WaitingTimeCollector myWaitingTimeCollector
Static Protected Attributes
static std::vector< MSLane * > myEmptyLaneVector
static std::vector< MSTransportable * > myEmptyTransportableVector
static const SUMOTime NOT_YET_DEPARTED = SUMOTime_MAX
Private Member Functions
void computeSeats (const Position &front, const Position &back, int &requiredSeats) const
add seats to mySeatPositions and update requiredSeats
bool drawAction_drawCarriageClass (const GUIVisualizationSettings &s, SUMOVehicleShape guiShape, bool asImage) const
draws the given guiShape if it has distinct carriages/modules and returns true if so
void drawAction_drawRailCarriages (const GUIVisualizationSettings &s, SUMOReal defaultLength, SUMOReal carriageGap, int firstPassengerCarriage, bool asImage) const
int getNumPassengers () const
return the number of passengers
MSLane * getPreviousLane (MSLane *current, int &furtherIndex) const
std::string getStopInfo () const
retrieve information about the current stop state
Additional visualisations
bool hasActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) const
Returns whether the named feature is enabled in the given view.
void addActiveAddVisualisation (GUISUMOAbstractView *const parent, int which)
Adds the named visualisation feature to the given view.
void removeActiveAddVisualisation (GUISUMOAbstractView *const parent, int which)
Adds the named visualisation feature to the given view.
void drawRoute (const GUIVisualizationSettings &s, int routeNo, SUMOReal darken) const
Chooses the route to draw and draws it, darkening it as given.
enum VisualisationFeatures {
VO_SHOW_BEST_LANES = 1, VO_SHOW_ROUTE = 2, VO_SHOW_ALL_ROUTES = 4, VO_TRACKED = 8,
VO_SHOW_LFLINKITEMS = 16
}
Additional visualisation feature ids.
std::map< GUISUMOAbstractView *, int > myAdditionalVisualizations
Enabled visualisations, per view.
drawing helper methods
void drawAction_drawVehicleAsBoxPlus () const
void drawAction_drawVehicleAsTrianglePlus () const
void drawAction_drawVehicleAsPoly (const GUIVisualizationSettings &s) const
bool drawAction_drawVehicleAsImage (const GUIVisualizationSettings &s, SUMOReal length=-1) const
static void drawPoly (double *poses, SUMOReal offset)
Move reminder structures
typedef std::vector< std::pair< MSMoveReminder *, SUMOReal > > MoveReminderCont
Definition of a move reminder container.
MoveReminderCont myMoveReminders
Current lane's move reminder.
Interaction with move reminders
void workOnMoveReminders (SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed)
Processes active move reminder.
void adaptLaneEntering2MoveReminder (const MSLane &enteredLane)
Adapts the vehicle's entering of a new lane.
Access to bool signals
void switchOnSignal (int signal)
Switches the given signal on.
void switchOffSignal (int signal)
Switches the given signal off.
int getSignals () const
Returns the signals.
bool signalSet (int which) const
Returns whether the given signal is on.
enum Signalling {
VEH_SIGNAL_NONE = 0, VEH_SIGNAL_BLINKER_RIGHT = 1, VEH_SIGNAL_BLINKER_LEFT = 2, VEH_SIGNAL_BLINKER_EMERGENCY = 4,
VEH_SIGNAL_BRAKELIGHT = 8, VEH_SIGNAL_FRONTLIGHT = 16, VEH_SIGNAL_FOGLIGHT = 32, VEH_SIGNAL_HIGHBEAM = 64,
VEH_SIGNAL_BACKDRIVE = 128, VEH_SIGNAL_WIPER = 256, VEH_SIGNAL_DOOR_OPEN_LEFT = 512, VEH_SIGNAL_DOOR_OPEN_RIGHT = 1024,
VEH_SIGNAL_EMERGENCY_BLUE = 2048, VEH_SIGNAL_EMERGENCY_RED = 4096, VEH_SIGNAL_EMERGENCY_YELLOW = 8192
}
Some boolean values which describe the state of some vehicle parts.
enum LaneChangeMode { LC_NEVER = 0, LC_NOCONFLICT = 1, LC_ALWAYS = 2 }
modes for resolving conflicts between external control (traci) and vehicle control over lane changing. Each level of the lane-changing hierarchy (strategic, cooperative, speedGain, keepRight) can be controlled separately
enum TraciLaneChangePriority { LCP_ALWAYS = 0, LCP_NOOVERLAP = 1, LCP_URGENT = 2, LCP_OPPORTUNISTIC = 3 }
modes for prioritizing traci lane change requests
Detailed Description
A MSVehicle extended by some values for usage within the gui.
A visualisable MSVehicle. Extended by the possibility to retrieve names of all available vehicles (static) and the possibility to retrieve the color of the vehicle which is available in different forms allowing an easier recognition of done actions such as lane changing.
Definition at line 61 of file GUIVehicle.h.
Member Typedef Documentation
typedef Named::NamedLikeComparatorIdLess<SUMOVehicle> SUMOVehicle::ComparatorIdLess inherited
Definition at line 68 of file SUMOVehicle.h.
typedef std::vector< DriveProcessItem > MSVehicle::DriveItemVector protected inherited
Container for used Links/visited Lanes during lookForward.
Definition at line 1486 of file MSVehicle.h.
typedef std::vector< std::pair<MSMoveReminder*, SUMOReal> > MSBaseVehicle::MoveReminderCont protected inherited
Definition of a move reminder container.
Definition at line 403 of file MSBaseVehicle.h.
Member Enumeration Documentation
enum MSVehicle::ChangeRequest inherited
Requests set via TraCI.
Enumerator
REQUEST_NONE
vehicle doesn't want to change
REQUEST_LEFT
vehicle want's to change to left lane
REQUEST_RIGHT
vehicle want's to change to right lane
REQUEST_HOLD
vehicle want's to keep the current lane
Definition at line 206 of file MSVehicle.h.
enum MSVehicle::LaneChangeMode inherited
modes for resolving conflicts between external control (traci) and vehicle control over lane changing. Each level of the lane-changing hierarchy (strategic, cooperative, speedGain, keepRight) can be controlled separately
Enumerator
LC_NEVER
LC_NOCONFLICT
LC_ALWAYS
Definition at line 976 of file MSVehicle.h.
enum MSVehicle::Signalling inherited
Some boolean values which describe the state of some vehicle parts.
Enumerator
VEH_SIGNAL_NONE
Everything is switched off.
VEH_SIGNAL_BLINKER_RIGHT
Right blinker lights are switched on.
VEH_SIGNAL_BLINKER_LEFT
Left blinker lights are switched on.
VEH_SIGNAL_BLINKER_EMERGENCY
Blinker lights on both sides are switched on.
VEH_SIGNAL_BRAKELIGHT
The brake lights are on.
VEH_SIGNAL_FRONTLIGHT
The front lights are on (no visualisation)
VEH_SIGNAL_FOGLIGHT
The fog lights are on (no visualisation)
VEH_SIGNAL_HIGHBEAM
The high beam lights are on (no visualisation)
VEH_SIGNAL_BACKDRIVE
The backwards driving lights are on (no visualisation)
VEH_SIGNAL_WIPER
The wipers are on.
VEH_SIGNAL_DOOR_OPEN_LEFT
One of the left doors is opened.
VEH_SIGNAL_DOOR_OPEN_RIGHT
One of the right doors is opened.
VEH_SIGNAL_EMERGENCY_BLUE
A blue emergency light is on.
VEH_SIGNAL_EMERGENCY_RED
A red emergency light is on.
VEH_SIGNAL_EMERGENCY_YELLOW
A yellow emergency light is on.
Definition at line 938 of file MSVehicle.h.
enum MSVehicle::TraciLaneChangePriority inherited
modes for prioritizing traci lane change requests
Enumerator
LCP_ALWAYS
LCP_NOOVERLAP
LCP_URGENT
LCP_OPPORTUNISTIC
Definition at line 984 of file MSVehicle.h.
enum GUIBaseVehicle::VisualisationFeatures inherited
Additional visualisation feature ids.
Enumerator
VO_SHOW_BEST_LANES
show vehicle's best lanes
VO_SHOW_ROUTE
show vehicle's current route
VO_SHOW_ALL_ROUTES
show all vehicle's routes
VO_TRACKED
track vehicle
VO_SHOW_LFLINKITEMS
LFLinkItems.
Definition at line 288 of file GUIBaseVehicle.h.
Constructor & Destructor Documentation
GUIVehicle::GUIVehicle (SUMOVehicleParameter * pars, const MSRoute * route, const MSVehicleType * type, const SUMOReal speedFactor)
Constructor.
Parameters
[in] pars The vehicle description
[in] route The vehicle's route
[in] type The vehicle's type
[in] speedFactor The factor for driven lane's speed limits
Exceptions
ProcessError If a value is wrong
Definition at line 88 of file GUIVehicle.cpp.
GUIVehicle::~GUIVehicle ()
destructor
Definition at line 98 of file GUIVehicle.cpp.
Member Function Documentation
void MSVehicle::activateReminders (const MSMoveReminder::Notification reason) virtual inherited
"Activates" all current move reminder
For all move reminder stored in "myMoveReminders", their method "MSMoveReminder::notifyEnter" is called.
Parameters
[in] reason The reason for changing the reminders' states
See also
MSMoveReminder
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented from MSBaseVehicle.
Definition at line 2256 of file MSVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by MSVehicle::congested(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), and MSVehicle::enterLaneAtMove().
void MSVehicle::adaptBestLanesOccupation (int laneIndex, SUMOReal density) inherited
update occupation from MSLaneChanger
Definition at line 2846 of file MSVehicle.cpp.
References MSVehicle::myBestLanes.
Referenced by MSLaneChangerSublane::change(), and MSLaneChanger::change().
void MSVehicle::adaptLaneEntering2MoveReminder (const MSLane & enteredLane) protected inherited
Adapts the vehicle's entering of a new lane.
All offsets already stored in "myOldLaneMoveReminderOffsets" are increased by the length that has been left. All still active move reminders from "myMoveReminders" are put into "myOldLaneMoveReminders" and the offset to the last lane is added to "myOldLaneMoveReminderOffsets" for each of these.
Move reminder from the given lane are set into "myMoveReminders".
"myLane" must still be the left lane!
Parameters
[in] enteredLane
See also
MSMoveReminder
MSLane::getMoveReminder
Definition at line 730 of file MSVehicle.cpp.
References MSBaseVehicle::addReminder(), MSLane::getLength(), MSLane::getMoveReminders(), MSVehicle::myLane, MSBaseVehicle::myMoveReminders, and SUMOReal.
Referenced by MSVehicle::enterLaneAtMove(), and MSVehicle::hasInfluencer().
void MSVehicle::adaptToLeader (const std::pair< const MSVehicle *, SUMOReal > leaderInfo, const SUMOReal seen, DriveProcessItem *const lastLink, const MSLane *const lane, SUMOReal & v, SUMOReal & vLinkPass, SUMOReal distToCrossing = -1) const protected inherited
Definition at line 1504 of file MSVehicle.cpp.
References MSVehicle::DriveProcessItem::adaptLeaveSpeed(), DEBUG_COND, Named::getID(), MSBaseVehicle::getID(), MSVehicle::getSafeFollowSpeed(), MIN2(), MSVehicle::myLane, SIMTIME, and SUMOReal.
Referenced by MSVehicle::adaptToLeaders(), MSVehicle::estimateSpeedAfterDistance(), and MSVehicle::planMoveInternal().
void MSVehicle::adaptToLeaders (const MSLeaderInfo & ahead, SUMOReal latOffset, const SUMOReal seen, DriveProcessItem *const lastLink, const MSLane *const lane, SUMOReal & v, SUMOReal & vLinkPass) const protected inherited
Definition at line 1469 of file MSVehicle.cpp.
References MSVehicle::adaptToLeader(), DEBUG_COND, MSVehicle::getBackPositionOnLane(), Named::getID(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSLane::getLength(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSLeaderInfo::getSubLanes(), MSBaseVehicle::getVehicleType(), MSVehicle::myLane, MSVehicle::State::myPos, MSVehicle::myState, SIMTIME, SUMOReal, and MSLeaderInfo::toString().
Referenced by MSVehicle::estimateSpeedAfterDistance(), and MSVehicle::planMoveInternal().
void GUIBaseVehicle::addActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) inherited
Adds the named visualisation feature to the given view.
Parameters
[in] parent The view for which the feature shall be enabled
[in] which The visualisation feature to enable
See also
GUISUMOAbstractView::addAdditionalGLVisualisation
Definition at line 1127 of file GUIBaseVehicle.cpp.
References GUISUMOAbstractView::addAdditionalGLVisualisation(), and GUIBaseVehicle::myAdditionalVisualizations.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), and GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack().
void MSVehicle::addContainer (MSTransportable * container) virtual inherited
Adds a container.
Parameters
[in] container The container to add
Reimplemented from MSBaseVehicle.
Definition at line 2987 of file MSVehicle.cpp.
References MSDevice_Transportable::addTransportable(), MSDevice_Transportable::buildVehicleDevices(), MSTransportable::getID(), MSVehicle::myContainerDevice, MSBaseVehicle::myDevices, MSBaseVehicle::myMoveReminders, and MSVehicle::myStops.
Referenced by MSTransportableControl::loadAnyWaiting(), and MSVehicle::nextStopDist().
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 258 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
void MSVehicle::addPerson (MSTransportable * person) virtual inherited
Adds a passenger.
Parameters
[in] person The person to add
Reimplemented from MSBaseVehicle.
Definition at line 2965 of file MSVehicle.cpp.
References MSDevice_Transportable::addTransportable(), MSDevice_Transportable::buildVehicleDevices(), MSTransportable::getID(), MSBaseVehicle::myDevices, MSBaseVehicle::myMoveReminders, MSVehicle::myPersonDevice, and MSVehicle::myStops.
Referenced by MSTransportableControl::boardAnyWaiting(), and MSVehicle::nextStopDist().
void MSBaseVehicle::addReminder (MSMoveReminder * rem) inherited
Adds a MoveReminder dynamically.
Parameters
[in] rem the reminder to add
See also
MSMoveReminder
Definition at line 312 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by MSVehicle::adaptLaneEntering2MoveReminder(), MESegment::addReminders(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), and MSBaseVehicle::getDevices().
bool MSVehicle::addStop (const SUMOVehicleParameter::Stop & stopPar, std::string & errorMsg, SUMOTime untilOffset = 0) virtual inherited
Adds a stop.
The stop is put into the sorted list.
Parameters
[in] stop The stop to add
Returns
Whether the stop could be added
Implements SUMOVehicle.
Definition at line 860 of file MSVehicle.cpp.
References MSLane::allowsVehicleClass(), SUMOVehicleParameter::Stop::awaitedContainers, MSVehicle::Stop::awaitedContainers, SUMOVehicleParameter::Stop::awaitedPersons, MSVehicle::Stop::awaitedPersons, SUMOVehicleParameter::Stop::busstop, MSVehicle::Stop::busstop, SUMOVehicleParameter::Stop::containerstop, MSVehicle::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, MSVehicle::Stop::containerTriggered, DEPART_POS_BASE, DEPART_POS_DEFAULT, DEPART_POS_GIVEN, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, MSLane::dictionary(), SUMOVehicleParameter::Stop::duration, MSVehicle::Stop::duration, MSVehicle::Stop::edge, MSRoute::end(), SUMOVehicleParameter::Stop::endPos, MSVehicle::Stop::endPos, MSNet::getBusStop(), MSVehicle::getCarFollowModel(), MSNet::getContainerStop(), MSLane::getEdge(), Named::getID(), MSNet::getInstance(), MSVehicleType::getLength(), MSLane::getLength(), MSVehicleType::getVehicleClass(), MSBaseVehicle::getVehicleType(), MSBaseVehicle::hasDeparted(), SUMOVehicleParameter::id, SUMOVehicleParameter::Stop::index, SUMOVehicleParameter::Stop::lane, MSVehicle::Stop::lane, MIN2(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myParameter, MSVehicle::State::myPos, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, MSVehicle::myState, MSVehicle::myStops, MSBaseVehicle::myType, SUMOVehicleParameter::Stop::parking, MSVehicle::Stop::parking, POSITION_EPS, MSVehicle::Stop::reached, SUMOVehicleParameter::Stop::startPos, MSVehicle::Stop::startPos, STOP_INDEX_END, STOP_INDEX_FIT, SUMOReal, MSVehicle::Stop::timeToBoardNextPerson, MSVehicle::Stop::timeToLoadNextContainer, SUMOVehicleParameter::Stop::triggered, MSVehicle::Stop::triggered, SUMOVehicleParameter::Stop::until, and MSVehicle::Stop::until.
Referenced by MSVehicle::addTraciBusOrContainerStop(), MSVehicle::addTraciStop(), and MSVehicle::replaceRoute().
void MSBaseVehicle::addStops (const bool ignoreStopErrors) inherited
Adds stops to the built vehicle.
This code needs to be separated from the MSBaseVehicle constructor since it is not allowed to call virtual functions from a constructor
Parameters
[in] ignoreStopErrors whether invalid stops trigger a warning only
Definition at line 431 of file MSBaseVehicle.cpp.
References SUMOVehicle::addStop(), OutputDevice::closeTag(), MSMoveReminder::getDescription(), OutputDevice::getDeviceByOption(), MSBaseVehicle::getID(), MSNet::getInstance(), MSRoute::getStops(), OptionsCont::getStringVector(), OptionsCont::isSet(), MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, OutputDevice::openTag(), STEPS2TIME, SUMOVehicleParameter::stops, SUMO_ATTR_ID, SUMO_ATTR_TIME, SUMOReal, toString(), WRITE_WARNING, and OutputDevice::writeAttr().
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), and MSBaseVehicle::setChosenSpeedFactor().
bool MSVehicle::addTraciBusOrContainerStop (const std::string & stopId, const SUMOTime duration, const SUMOTime until, const bool parking, const bool triggered, const bool containerTriggered, const bool isContainerStop, std::string & errorMsg) inherited
schedule a new stop for the vehicle; each time a stop is reached, the vehicle will wait for the given duration before continuing on its route
Parameters
stopId bus or container stop id
duration waiting time duration
until time step at which the stop shall end
parking a flag indicating whether the traci stop is used for parking or not
triggered a flag indicating whether the traci stop is triggered or not
containerTriggered a flag indicating whether the traci stop is triggered by a container or not
isContainerStop a flag indicating whether the stop is a container stop
Definition at line 3355 of file MSVehicle.cpp.
References MSVehicle::addStop(), SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, MSStoppingPlace::getBeginLanePosition(), MSNet::getBusStop(), MSNet::getContainerStop(), MSStoppingPlace::getEndLanePosition(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSStoppingPlace::getLane(), SUMOVehicleParameter::Stop::index, SUMOVehicleParameter::Stop::lane, MSVehicle::myLane, MSVehicle::myStops, SUMOVehicleParameter::Stop::parking, SUMOVehicleParameter::Stop::startPos, STOP_INDEX_FIT, SUMOVehicleParameter::Stop::triggered, SUMOVehicleParameter::Stop::until, and MSVehicle::updateBestLanes().
Referenced by TraCIServerAPI_Vehicle::processSet(), and MSVehicle::signalSet().
bool MSVehicle::addTraciStop (MSLane *const lane, const SUMOReal startPos, const SUMOReal endPos, const SUMOTime duration, const SUMOTime until, const bool parking, const bool triggered, const bool containerTriggered, std::string & errorMsg) inherited
schedule a new stop for the vehicle; each time a stop is reached, the vehicle will wait for the given duration before continuing on its route
Parameters
lane lane on wich to stop
startPos start position on the given lane at wich to stop
endPos end position on the given lane at wich to stop
duration waiting time duration
until time step at which the stop shall end
parking a flag indicating whether the traci stop is used for parking or not
triggered a flag indicating whether the traci stop is triggered or not
containerTriggered a flag indicating whether the traci stop is triggered by a container or not
Definition at line 3322 of file MSVehicle.cpp.
References MSVehicle::addStop(), SUMOVehicleParameter::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, Named::getID(), SUMOVehicleParameter::Stop::index, SUMOVehicleParameter::Stop::lane, MSVehicle::myLane, MSVehicle::myStops, SUMOVehicleParameter::Stop::parking, POSITION_EPS, SUMOVehicleParameter::Stop::startPos, STOP_INDEX_FIT, SUMOVehicleParameter::Stop::triggered, SUMOVehicleParameter::Stop::until, and MSVehicle::updateBestLanes().
Referenced by TraCIServerAPI_Vehicle::processSet(), and MSVehicle::signalSet().
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 187 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 196 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 177 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GNECrossing::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 237 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 206 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 249 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 219 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 228 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIBaseVehicle::getPopUpMenu().
void MSBaseVehicle::calculateArrivalParams () protected inherited
(Re-)Calculates the arrival position and lane from the vehicle parameters
Definition at line 361 of file MSBaseVehicle.cpp.
References ARRIVAL_LANE_GIVEN, ARRIVAL_POS_GIVEN, ARRIVAL_POS_RANDOM, ARRIVAL_SPEED_GIVEN, SUMOVehicleParameter::arrivalLane, SUMOVehicleParameter::arrivalLaneProcedure, SUMOVehicleParameter::arrivalPos, SUMOVehicleParameter::arrivalPosProcedure, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, Named::getID(), MSBaseVehicle::getID(), MSEdge::getLanes(), MSRoute::getLastEdge(), MSVehicleType::getVehicleClass(), MAX2(), MIN2(), MSBaseVehicle::myArrivalLane, MSBaseVehicle::myArrivalPos, MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, MSBaseVehicle::myType, RandHelper::rand(), SUMOReal, toString(), and WRITE_WARNING.
Referenced by MSBaseVehicle::MSBaseVehicle(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), and MSBaseVehicle::setChosenSpeedFactor().
void MSVehicle::checkRewindLinkLanes (const SUMOReal lengthsInFront, DriveItemVector & lfLinks) const protected inherited
Definition at line 2048 of file MSVehicle.cpp.
References ACCEL2SPEED, MSVehicle::DriveProcessItem::availableSpace, bla, MSCFModel::brakeGap(), DEBUG_COND, MSEdge::EDGEFUNCTION_INTERNAL, gDebugSelectedVehicle, MSVehicle::getBackPositionOnLane(), MSLane::getBruttoVehLenSum(), MSVehicle::getCarFollowModel(), MSLane::getEdge(), MSCFModel::getHeadwayTime(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getImpatience(), MSLink::getLane(), MSVehicle::getLaneChangeModel(), MSLane::getLastAnyVehicle(), MSVehicle::getLateralPositionOnLane(), MSVehicle::DriveProcessItem::getLeaveSpeed(), MSVehicleType::getLength(), MSLane::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSLink::getParallelLink(), MSEdge::getPurpose(), MSVehicle::Influencer::getRespectJunctionPriority(), MSAbstractLaneChangeModel::getShadowLane(), MSVehicle::getSpaceTillLastStanding(), MSVehicle::getSpeed(), MSLane::getVehicleNumber(), MSBaseVehicle::getVehicleType(), MSVehicle::getWaitingTime(), MSGlobals::gUsingInternalLanes, MSVehicle::DriveProcessItem::hadVehicle, MSLink::hasFoes(), MSLink::havePriority(), MSLink::isCont(), MSVehicle::isFrontOnLane(), MSAbstractLaneChangeModel::isOpposite(), MSEdge::isRoundabout(), MSLink::keepClear(), LINKSTATE_ALLWAY_STOP, MAX2(), MSVehicle::DriveProcessItem::myArrivalSpeed, MSVehicle::DriveProcessItem::myArrivalTime, MSVehicle::myHaveToWaitOnNextLink, MSVehicle::myInfluencer, MSVehicle::myLane, MSVehicle::DriveProcessItem::myLink, MSVehicle::State::mySpeed, MSVehicle::myState, MSLink::opened(), RandHelper::rand(), MSLink::setApproaching(), MSAbstractLaneChangeModel::setShadowApproachingInformation(), MSVehicle::signalSet(), SIMTIME, SUMOReal, UNUSED_PARAMETER, and MSVehicle::VEH_SIGNAL_BRAKELIGHT.
Referenced by MSVehicle::planMove().
SUMOReal MSVehicle::computeAngle () const inherited
compute the current vehicle angle
Definition at line 808 of file MSVehicle.cpp.
References Position::angleTo2D(), DEBUG_COND, DEG2RAD, MSLane::geometryPositionAtOffset(), MSVehicle::getBackPosition(), MSBaseVehicle::getID(), MSVehicle::getLaneChangeModel(), MSVehicle::getPosition(), MSVehicle::getPositionOnLane(), MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), MSAbstractLaneChangeModel::isChangingLanes(), MSVehicle::isParking(), MSVehicle::myLane, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSVehicle::myState, PositionVector::rotationAtOffset(), SIMTIME, and SUMOReal.
Referenced by MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::executeMove(), and MSVehicle::getAngle().
void GUIVehicle::computeSeats (const Position & front, const Position & back, int & requiredSeats) const private
add seats to mySeatPositions and update requiredSeats
Definition at line 599 of file GUIVehicle.cpp.
References Position::distanceTo2D(), GUIBaseVehicle::mySeatPositions, PositionVector::positionAtOffset2D(), and SUMOReal.
Referenced by drawAction_drawRailCarriages(), and getAngle().
bool MSVehicle::congested () const inline inherited
Returns true if vehicle's speed is below 60km/h. This is only relevant on highways. Overtaking on the right is allowed then.
Definition at line 542 of file MSVehicle.h.
References MSVehicle::activateReminders(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), MSVehicle::getLaneChangeModel(), MSVehicle::leaveLane(), MSVehicle::State::mySpeed, MSVehicle::myState, MSVehicle::State::pos(), MSVehicle::State::posLat(), MSVehicle::setTentativeLaneAndPosition(), MSVehicle::State::speed(), and SUMOReal.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::checkStrategicChange(), MSAbstractLaneChangeModel::congested(), MSLCM_JE2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), and MSLCM_SL2015::informLeader().
bool GUIVehicle::drawAction_drawCarriageClass (const GUIVisualizationSettings & s, SUMOVehicleShape guiShape, bool asImage) const private virtual
draws the given guiShape if it has distinct carriages/modules and returns true if so
Implements GUIBaseVehicle.
Definition at line 284 of file GUIVehicle.cpp.
References drawAction_drawRailCarriages(), SVS_BUS_FLEXIBLE, SVS_RAIL, SVS_RAIL_CAR, and SVS_RAIL_CARGO.
Referenced by getAngle().
void GUIVehicle::drawAction_drawLinkItems (const GUIVisualizationSettings & s) const virtual
Reimplemented from GUIBaseVehicle.
Definition at line 256 of file GUIVehicle.cpp.
References MSLink::ApproachingVehicleInformation::arrivalTime, GUIBaseVehicle::drawLinkItem(), MSVehicleType::getLength(), MSLane::getShape(), MSBaseVehicle::getVehicleType(), MSLink::getViaLaneOrLane(), MSLink::ApproachingVehicleInformation::leavingTime, MSVehicle::myLFLinkLanes, GUIVisualizationSettings::scale, GUIVisualizationTextSettings::size, UNUSED_PARAMETER, and GUIVisualizationSettings::vehicleName.
Referenced by getAngle().
void GUIVehicle::drawAction_drawPersonsAndContainers (const GUIVisualizationSettings & s) const virtual
Reimplemented from GUIBaseVehicle.
Definition at line 216 of file GUIVehicle.cpp.
References GUIContainer::drawGL(), GUIPerson::drawGL(), GLHelper::drawLine(), MSVehicle::getBoundingBox(), MSVehicle::getBoundingPoly(), GUIGlObject::getGlID(), GUIBaseVehicle::getSeatPosition(), MSDevice_Transportable::getTransportables(), GUIGlObject::getType(), MSVehicle::myContainerDevice, MSVehicle::myPersonDevice, GUIContainer::setPositionInVehicle(), and GUIPerson::setPositionInVehicle().
Referenced by getAngle().
void GUIVehicle::drawAction_drawRailCarriages (const GUIVisualizationSettings & s, SUMOReal defaultLength, SUMOReal carriageGap, int firstPassengerCarriage, bool asImage) const private
Definition at line 491 of file GUIVehicle.cpp.
References RGBColor::changedBrightness(), computeSeats(), Position::distanceTo2D(), GUIBaseVehicle::drawAction_drawVehicleAsImage(), MSLane::geometryPositionAtOffset(), GLHelper::getColor(), GUIVisualizationSizeSettings::getExaggeration(), MSVehicleType::getLength(), MSLane::getLength(), getNumPassengers(), getPreviousLane(), GUIGlObject::getType(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSVehicle::myLane, GUIBaseVehicle::mySeatPositions, MSVehicle::myState, PI, MSVehicle::State::pos(), GLHelper::setColor(), SUMOReal, GUIVisualizationSettings::vehicleSize, Position::x(), and Position::y().
Referenced by drawAction_drawCarriageClass(), and getAngle().
void GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus () const protected inherited
Definition at line 336 of file GUIBaseVehicle.cpp.
References MSVehicleType::getLength(), MSVehicleType::getWidth(), and GUIBaseVehicle::myVType.
Referenced by GUIMEVehicle::drawAction_drawCarriageClass(), GUIBaseVehicle::drawAction_drawVehicleAsTrianglePlus(), and GUIBaseVehicle::drawOnPos().
bool GUIBaseVehicle::drawAction_drawVehicleAsImage (const GUIVisualizationSettings & s, SUMOReal length = -1) const protected inherited
Definition at line 806 of file GUIBaseVehicle.cpp.
References GUITexturesHelper::drawTexturedBox(), GUIVisualizationSizeSettings::getExaggeration(), MSVehicleType::getImgFile(), MSVehicleType::getLength(), GUITexturesHelper::getTextureID(), MSVehicleType::getWidth(), GUIBaseVehicle::myVType, SUMOReal, and GUIVisualizationSettings::vehicleSize.
Referenced by drawAction_drawRailCarriages(), and GUIBaseVehicle::drawOnPos().
void GUIBaseVehicle::drawAction_drawVehicleAsPoly (const GUIVisualizationSettings & s) const protected inherited
Definition at line 385 of file GUIBaseVehicle.cpp.
References RGBColor::changedBrightness(), GUIBaseVehicle::drawAction_drawCarriageClass(), GLHelper::drawBoxLine(), GLHelper::drawFilledCircle(), GUIBaseVehicle::drawPoly(), GLHelper::getColor(), MSVehicleType::getGuiShape(), MSVehicleType::getLength(), MSVehicleType::getWidth(), RGBColor::GREY, GUIBaseVehicle::myVType, GLHelper::setColor(), SUMOReal, SVS_ANT, SVS_BICYCLE, SVS_BUS, SVS_BUS_COACH, SVS_BUS_FLEXIBLE, SVS_BUS_TROLLEY, SVS_DELIVERY, SVS_E_VEHICLE, SVS_EMERGENCY, SVS_MOPED, SVS_MOTORCYCLE, SVS_PASSENGER, SVS_PASSENGER_HATCHBACK, SVS_PASSENGER_SEDAN, SVS_PASSENGER_VAN, SVS_PASSENGER_WAGON, SVS_PEDESTRIAN, SVS_RAIL, SVS_RAIL_CAR, SVS_RAIL_CARGO, SVS_SHIP, SVS_TRUCK, SVS_TRUCK_1TRAILER, SVS_TRUCK_SEMITRAILER, SVS_UNKNOWN, and vehiclePoly_PassengerCarBody.
Referenced by GUIBaseVehicle::drawOnPos().
void GUIBaseVehicle::drawAction_drawVehicleAsTrianglePlus () const protected inherited
Definition at line 351 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus(), MSVehicleType::getLength(), MSVehicleType::getWidth(), GUIBaseVehicle::myVType, and SUMOReal.
Referenced by GUIBaseVehicle::drawOnPos().
void GUIVehicle::drawAction_drawVehicleBlinker (SUMOReal length) const virtual
Reimplemented from GUIBaseVehicle.
Definition at line 325 of file GUIVehicle.cpp.
References drawAction_drawBlinker(), MSBaseVehicle::getVehicleType(), MAX2(), MSVehicle::signalSet(), MSVehicle::VEH_SIGNAL_BLINKER_EMERGENCY, MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by getAngle().
void GUIVehicle::drawAction_drawVehicleBlueLight () const inline virtual
Reimplemented from GUIBaseVehicle.
Definition at line 365 of file GUIVehicle.cpp.
References GLHelper::drawFilledCircle(), MSVehicle::signalSet(), SUMOReal, and MSVehicle::VEH_SIGNAL_EMERGENCY_BLUE.
Referenced by getAngle().
void GUIVehicle::drawAction_drawVehicleBrakeLight (SUMOReal length, bool onlyOne = 1) const inline virtual
Reimplemented from GUIBaseVehicle.
Definition at line 344 of file GUIVehicle.cpp.
References GLHelper::drawFilledCircle(), MSBaseVehicle::getVehicleType(), MSVehicle::signalSet(), and MSVehicle::VEH_SIGNAL_BRAKELIGHT.
Referenced by getAngle().
void GUIVehicle::drawBestLanes () const virtual
Draws the vehicle's best lanes.
Reimplemented from GUIBaseVehicle.
Definition at line 426 of file GUIVehicle.cpp.
References abs, GLHelper::drawBoxLines(), GLHelper::drawLine(), MFXMutex::lock(), MAX2(), PositionVector::move2side(), MSVehicle::myBestLanes, GUIBaseVehicle::myLock, SUMOReal, and MFXMutex::unlock().
Referenced by getAngle().
void GUIBaseVehicle::drawGL (const GUIVisualizationSettings & s) const virtual inherited
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 983 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::drawOnPos(), GUIBaseVehicle::getAngle(), and GUIBaseVehicle::getPosition().
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUILane::drawGL(), and GUIBaseVehicle::drawGLAdditional().
void GUIBaseVehicle::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additionally triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented from GUIGlObject.
Definition at line 989 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::drawAction_drawLinkItems(), GUIBaseVehicle::drawBestLanes(), GUIBaseVehicle::drawGL(), GUIBaseVehicle::drawRoute(), GUIGlObject::getGlID(), MSBaseVehicle::getNumberReroutes(), GUIGlObject::getType(), GUIBaseVehicle::hasActiveAddVisualisation(), MSBaseVehicle::isOnRoad(), GUIBaseVehicle::myVehicle, SUMOReal, GUIBaseVehicle::VO_SHOW_ALL_ROUTES, GUIBaseVehicle::VO_SHOW_BEST_LANES, GUIBaseVehicle::VO_SHOW_LFLINKITEMS, and GUIBaseVehicle::VO_SHOW_ROUTE.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight().
void GUIBaseVehicle::drawLinkItem (const Position & pos, SUMOTime arrivalTime, SUMOTime leaveTime, SUMOReal exagerate) static protected inherited
Definition at line 1022 of file GUIBaseVehicle.cpp.
References GLHelper::drawFilledCircle(), GLHelper::drawText(), RGBColor::GREEN, STEPS2TIME, toString(), Position::x(), and Position::y().
Referenced by drawAction_drawLinkItems().
void GUIGlObject::drawName (const Position & pos, const SUMOReal scale, const GUIVisualizationTextSettings & settings, const SUMOReal angle = 0) const inherited
draw name of item
Definition at line 286 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE3::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GUIPolygon::drawGL(), GNEVariableSpeedSignal::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GNERouteProbe::drawGL(), GNEEdge::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIEdge::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GNERerouter::drawGL(), and GUIBaseVehicle::drawOnPos().
void GUIBaseVehicle::drawOnPos (const GUIVisualizationSettings & s, const Position & pos, const SUMOReal angle) const inherited
Draws the object on the specified position with the specified angle.
Parameters
[in] s The settings for the current view (may influence drawing)
[in] pos The position to draw the vehicle on
[in] angle The drawing angle of the vehicle
Definition at line 825 of file GUIBaseVehicle.cpp.
References GUIVisualizationTextSettings::color, GUIBaseVehicle::drawAction_drawCarriageClass(), GUIBaseVehicle::drawAction_drawPersonsAndContainers(), GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus(), GUIBaseVehicle::drawAction_drawVehicleAsImage(), GUIBaseVehicle::drawAction_drawVehicleAsPoly(), GUIBaseVehicle::drawAction_drawVehicleAsTrianglePlus(), GUIBaseVehicle::drawAction_drawVehicleBlinker(), GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::drawAction_drawVehicleBrakeLight(), GUIVisualizationSettings::drawLaneChangePreference, GUIVisualizationSettings::drawMinGap, GUIGlObject::drawName(), GLHelper::drawOutlineCircle(), GLHelper::drawText(), MSLane::geometryPositionAtOffset(), MSBaseVehicle::getDevice(), GUIVisualizationSizeSettings::getExaggeration(), GUIGlObject::getGlID(), MSVehicleType::getGuiShape(), SUMOVehicle::getLane(), MSVehicleType::getLength(), MSVehicleType::getMinGap(), MSBaseVehicle::getParameter(), SUMOVehicle::getPositionOnLane(), MSDevice_BTreceiver::getRange(), GUIGlObject::getType(), GLO_MAX, SUMOVehicleParameter::line, MIN2(), GUIBaseVehicle::myCarriageLength, GUIBaseVehicle::mySeatPositions, GUIBaseVehicle::myVehicle, GUIBaseVehicle::myVType, GUIVisualizationSettings::personName, PI, RAD2DEG, GUIVisualizationSettings::scale, GUIBaseVehicle::setColor(), GUIVisualizationTextSettings::show, GUIVisualizationSettings::showBlinker, GUIVisualizationSettings::showBTRange, GUIVisualizationTextSettings::size, SUMOReal, SVS_ANT, SVS_BICYCLE, SVS_EMERGENCY, SVS_MOPED, SVS_MOTORCYCLE, SVS_PEDESTRIAN, SVS_RAIL, SVS_RAIL_CARGO, SVS_SHIP, GUIVisualizationSettings::vehicleName, GUIVisualizationSettings::vehicleQuality, GUIVisualizationSettings::vehicleSize, Position::x(), and Position::y().
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::drawGL(), and GUIEdge::drawMesoVehicles().
void GUIVehicle::drawOutsideNetwork (bool add) const protected virtual
register vehicle for drawing while outside the network
Reimplemented from MSVehicle.
Definition at line 696 of file GUIVehicle.cpp.
References GUISUMOAbstractView::addAdditionalGLVisualisation(), GUIMainWindow::getActiveView(), MSBaseVehicle::getID(), GUIMainWindow::getInstance(), GUISUMOAbstractView::removeAdditionalGLVisualisation(), and SIMTIME.
Referenced by getAngle().
void GUIBaseVehicle::drawPoly (double * poses, SUMOReal offset) static protected inherited
Definition at line 369 of file GUIBaseVehicle.cpp.
Referenced by GUIBaseVehicle::drawAction_drawVehicleAsPoly().
void GUIBaseVehicle::drawRoute (const GUIVisualizationSettings & s, int routeNo, SUMOReal darken) const inherited
Chooses the route to draw and draws it, darkening it as given.
Parameters
[in] s The visualisation settings, needed to determine the vehicle's color
[in] routeNo The route to show (0: the current, >0: prior)
[in] darken The amount to darken the route by
Definition at line 1144 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::drawRouteHelper(), GUIVisualizationSizeSettings::getExaggeration(), MSBaseVehicle::getRoute(), MSDevice_Vehroutes::getRoute(), GUIBaseVehicle::myRoutes, GUIBaseVehicle::myVehicle, GUIBaseVehicle::setColor(), SUMOReal, and GUIVisualizationSettings::vehicleSize.
Referenced by GUIBaseVehicle::drawGLAdditional().
void GUIVehicle::drawRouteHelper (const MSRoute & r, SUMOReal exaggeration) const virtual
Draws the route.
Parameters
[in] r The route to draw
Implements GUIBaseVehicle.
Definition at line 461 of file GUIVehicle.cpp.
References MSRoute::begin(), GLHelper::drawBoxLines(), MSRoute::end(), MSVehicle::getBestLanesContinuation(), GUILane::getShape(), GUILane::getShapeLengths(), GUILane::getShapeRotations(), MSBaseVehicle::myRoute, and MSRoute::size().
Referenced by getAngle().
void MSVehicle::enterLaneAtInsertion (MSLane * enteredLane, SUMOReal pos, SUMOReal speed, SUMOReal posLat, MSMoveReminder::Notification notification) inherited
Update when the vehicle enters a new lane in the emit step.
Parameters
[in] enteredLane The lane the vehicle enters
[in] pos The position the vehicle was inserted into the lane
[in] speed The speed with which the vehicle was inserted into the lane
[in] posLat The lateral position the vehicle was inserted into the lane
[in] notification The cause of insertion (i.e. departure, teleport, parking)
Definition at line 2371 of file MSVehicle.cpp.
References MSVehicle::activateReminders(), MSBaseVehicle::addReminder(), MSVehicle::computeAngle(), MSVehicle::getLaneChangeModel(), MSVehicleType::getLength(), MSLane::getLogicalPredecessorLane(), MSLane::getMoveReminders(), MSBaseVehicle::getVehicleType(), MSGlobals::gLaneChangeDuration, MSGlobals::gLateralResolution, Position::INVALID, M_PI, MSVehicle::myAmOnNet, MSVehicle::myAngle, MSVehicle::State::myBackPos, MSVehicle::myCachedPosition, MSBaseVehicle::myDeparture, MSVehicle::myFurtherLanes, MSVehicle::myFurtherLanesPosLat, MSVehicle::myLane, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSVehicle::State::mySpeed, MSVehicle::myState, MSBaseVehicle::myType, MSVehicle::myWaitingTime, MSBaseVehicle::NOT_YET_DEPARTED, MSMoveReminder::NOTIFICATION_TELEPORT, MSBaseVehicle::onDepart(), SUMOReal, and MSAbstractLaneChangeModel::updateShadowLane().
Referenced by MSVehicle::congested(), and MSLane::incorporateVehicle().
void MSVehicle::enterLaneAtLaneChange (MSLane * enteredLane) inherited
Update when the vehicle enters a new lane in the laneChange step.
Parameters
[in] enteredLane The lane the vehicle enters
Definition at line 2321 of file MSVehicle.cpp.
References MSVehicle::activateReminders(), MSBaseVehicle::addReminder(), MSVehicle::computeAngle(), DEBUG_COND, MSBaseVehicle::getEdge(), MSVehicleType::getLength(), MSLane::getLogicalPredecessorLane(), MSLane::getMoveReminders(), MSBaseVehicle::getVehicleType(), Position::INVALID, MSAbstractLaneChangeModel::isChangingLanes(), MSVehicle::myAmOnNet, MSVehicle::myAngle, MSVehicle::myCachedPosition, MSVehicle::myFurtherLanes, MSVehicle::myFurtherLanesPosLat, MSVehicle::myLane, MSVehicle::myLaneChangeModel, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSVehicle::myState, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSAbstractLaneChangeModel::setNoShadowPartialOccupator(), SIMTIME, SUMOReal, toString(), and MSVehicle::updateBestLanes().
Referenced by MSVehicle::congested(), and MSAbstractLaneChangeModel::primaryLaneChanged().
bool MSVehicle::enterLaneAtMove (MSLane * enteredLane, bool onTeleporting = false) inherited
Update when the vehicle enters a new lane in the move step.
Parameters
[in] enteredLane The lane the vehicle enters
[in] onTeleporting Whether the lane was entered while being teleported
Returns
Whether the vehicle's route has ended (due to vaporization, or because the destination was reached)
Definition at line 2288 of file MSVehicle.cpp.
References MSVehicle::activateReminders(), MSVehicle::adaptLaneEntering2MoveReminder(), MSEdge::EDGEFUNCTION_INTERNAL, MSLane::getEdge(), MSEdge::getPurpose(), MSVehicle::hasArrived(), Position::INVALID, MSVehicle::myAmOnNet, MSVehicle::myCachedPosition, MSBaseVehicle::myCurrEdge, MSVehicle::myLane, MSVehicle::myLastBestLanesEdge, MSVehicle::State::myPos, MSVehicle::myState, MSMoveReminder::NOTIFICATION_JUNCTION, and MSMoveReminder::NOTIFICATION_TELEPORT.
Referenced by MSVehicleTransfer::add(), MSVehicleTransfer::checkInsertions(), MSVehicle::congested(), MSVehicle::executeMove(), and TraCIServerAPI_Vehicle::processSet().
SUMOReal MSVehicle::estimateLeaveSpeed (const MSLink *const link, const SUMOReal vLinkPass) const inline protected inherited
estimate leaving speed when accelerating across a link
Definition at line 1497 of file MSVehicle.h.
References MSVehicle::estimateSpeedAfterDistance(), MSVehicleType::getCarFollowModel(), MSLink::getLength(), MSCFModel::getMaxAccel(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSLink::getViaLaneOrLane(), and MIN2().
Referenced by MSVehicle::planMoveInternal().
SUMOReal MSVehicle::estimateSpeedAfterDistance (const SUMOReal dist, const SUMOReal v, const SUMOReal accel) const inline protected inherited
Definition at line 1511 of file MSVehicle.h.
References MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), MSVehicle::getBackLane(), MSVehicle::getBackPosition(), MSBaseVehicle::getMaxSpeed(), MSBaseVehicle::getVehicleType(), MIN2(), and SUMOReal.
Referenced by MSVehicle::estimateLeaveSpeed(), and MSVehicle::planMoveInternal().
bool MSVehicle::executeMove () inherited
Executes planned vehicle movements with regards to right-of-way.
This method goes through all DriveProcessItems in myLFLinkLanes in order to find a speed that is safe for all upcoming links.
Using this speed the position is updated and the vehicle is moved to the next lane (myLane is updated) if the end of the current lane is reached (this may happen multiple times in this method)
The vehicle also sets the lanes it is in-lapping into and informs them about it.
Returns
Whether the vehicle has moved to the next edge
Definition at line 1559 of file MSVehicle.cpp.
References ACCEL2SPEED, bla, MSCFModel::brakeGap(), MSAbstractLaneChangeModel::changedToOpposite(), MSVehicle::computeAngle(), DEBUG_COND, DELTA_T, DIST2SPEED, MSRoute::end(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSVehicle::enterLaneAtMove(), gDebugSelectedVehicle, MSVehicle::getBackLane(), MSVehicleType::getCarFollowModel(), MSVehicle::getCarFollowModel(), MSLink::getDirection(), MSLane::getEdge(), MSVehicle::Influencer::getEmergencyBrakeRedLight(), MSCFModel::getHeadwayTime(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getImpatience(), MSNet::getInstance(), MSVehicle::getLaneChangeModel(), MSVehicle::getLateralPositionOnLane(), MSVehicleType::getLength(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSLane::getOpposite(), MSLane::getOppositePos(), MSLink::getParallelLink(), MSVehicle::getPositionOnLane(), MSVehicle::Influencer::getRespectJunctionPriority(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), MSVehicle::getSpeed(), MSLink::getState(), MSVehicleType::getVehicleClass(), MSNet::getVehicleControl(), MSBaseVehicle::getVehicleType(), MSLink::getViaLaneOrLane(), MSVehicle::getWaitingTime(), MSLane::getWidth(), MSGlobals::gUsingInternalLanes, MSVehicle::hasArrived(), MSVehicle::Influencer::implicitDeltaPosVTD(), MSVehicle::Influencer::implicitSpeedVTD(), MSVehicle::Influencer::influenceSpeed(), Position::INVALID, MSVehicle::isRemoteControlled(), MSEdge::isRoundabout(), MSVehicle::isStopped(), MSEdge::isVaporizing(), MSVehicle::Influencer::isVTDControlled(), MSVehicle::leaveLane(), LINKDIR_LEFT, LINKDIR_RIGHT, LINKSTATE_EQUAL, LINKSTATE_TL_RED, LINKSTATE_TL_YELLOW_MAJOR, LINKSTATE_TL_YELLOW_MINOR, LINKSTATE_ZIPPER, max, MAX2(), MSCFModel::maxNextSpeed(), MIN2(), MSVehicle::myAcceleration, MSVehicle::myAngle, MSVehicle::State::myBackPos, MSVehicle::myCachedPosition, MSBaseVehicle::myCurrEdge, MSVehicle::myFurtherLanes, MSVehicle::myFurtherLanesPosLat, MSVehicle::myHaveToWaitOnNextLink, MSVehicle::myInfluencer, MSVehicle::myLane, MSVehicle::myLFLinkLanes, MSVehicle::State::myPos, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, MSVehicle::myState, MSBaseVehicle::myType, MSVehicle::myWaitingTime, MSVehicle::myWaitingTimeCollector, MSMoveReminder::NOTIFICATION_JUNCTION, MSMoveReminder::NOTIFICATION_VAPORIZED, NUMERICAL_EPS, MSLink::opened(), MSLink::passedJunction(), MSVehicle::WaitingTimeCollector::passTime(), POSITION_EPS, MSAbstractLaneChangeModel::prepareStep(), MSVehicleControl::registerEmergencyStop(), MSVehicle::setBlinkerInformation(), MSVehicle::setEmergencyBlueLight(), SIMTIME, SPEED2ACCEL, SPEED2DIST, SUMO_const_haltingSpeed, SUMOReal, SVC_EMERGENCY, MSVehicle::switchOffSignal(), MSVehicle::switchOnSignal(), time2string(), toString(), MSVehicle::updateBestLanes(), MSVehicle::updateFurtherLanes(), MSAbstractLaneChangeModel::updateShadowLane(), MSVehicle::VEH_SIGNAL_BRAKELIGHT, MSVehicle::workOnMoveReminders(), and WRITE_WARNING.
Referenced by MSLane::executeMovements().
void MSVehicle::fixPosition () inherited
repair errors in vehicle position after changing between internal edges
Definition at line 2854 of file MSVehicle.cpp.
References MSVehicle::getLaneChangeModel(), MSGlobals::gLaneChangeDuration, MSVehicle::State::myPosLat, MSVehicle::myState, and SUMOReal.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver().
SUMOReal MSVehicle::getAcceleration () const inline virtual inherited
Returns the vehicle's acceleration in m/s.
Returns
The acceleration
Reimplemented from MSBaseVehicle.
Definition at line 418 of file MSVehicle.h.
References MSVehicle::getPosition(), MSVehicle::getSlope(), MSVehicle::myAcceleration, and SUMOReal.
Referenced by getColorValue(), MSE2Collector::getEstimatedCurrentVehicleNumber(), and MSBatteryExport::write().
SUMOReal MSVehicle::getAccumulatedWaitingSeconds () const inline inherited
Returns the number of seconds waited (speed was lesser than 0.1m/s) within the last millisecs.
Returns
The time the vehicle was standing within the last t millisecs
Definition at line 512 of file MSVehicle.h.
References MSVehicle::getAccumulatedWaitingTime(), and STEPS2TIME.
Referenced by getColorValue(), and getParameterWindow().
SUMOTime MSVehicle::getAccumulatedWaitingTime (SUMOTime t = MSGlobals::gWaitingTimeMemory) const inline inherited
Returns the SUMOTime waited (speed was lesser than 0.1m/s) within the last t millisecs.
Parameters
[in] t specifies the length of the interval over which the cumulated waiting time is to be summed up (defaults to and must not exceed MSGlobals::gWaitingTimeMemory)
Returns
The time the vehicle was standing within the last t millisecs
Definition at line 491 of file MSVehicle.h.
References MSVehicle::WaitingTimeCollector::cumulatedWaitingTime(), and MSVehicle::myWaitingTimeCollector.
Referenced by MSVehicle::getAccumulatedWaitingSeconds().
SUMOReal GUIVehicle::getAngle () const inline virtual
Return current angle.
Note
implementation of abstract method does not work otherwise
Implements GUIBaseVehicle.
Definition at line 89 of file GUIVehicle.h.
References computeSeats(), drawAction_drawCarriageClass(), drawAction_drawLinkItems(), drawAction_drawPersonsAndContainers(), drawAction_drawRailCarriages(), drawAction_drawVehicleBlinker(), drawAction_drawVehicleBlueLight(), drawAction_drawVehicleBrakeLight(), drawBestLanes(), drawOutsideNetwork(), drawRouteHelper(), MSVehicle::getAngle(), getColorValue(), getLastLaneChangeOffset(), getNumPassengers(), getParameterWindow(), getPreviousLane(), getStopInfo(), getTypeParameterWindow(), selectBlockingFoes(), and SUMOReal.
virtual SUMOReal MSBaseVehicle::getArrivalPos () const inline virtual inherited
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
Returns
This vehicle's real arrivalPos
Implements SUMOVehicle.
Definition at line 250 of file MSBaseVehicle.h.
References MSBaseVehicle::myArrivalPos.
const MSLane * MSVehicle::getBackLane () const protected inherited
Definition at line 1901 of file MSVehicle.cpp.
References MSVehicle::myFurtherLanes, MSVehicle::myLane, and SUMOReal.
Referenced by MSVehicle::estimateSpeedAfterDistance(), and MSVehicle::executeMove().
const Position MSVehicle::getBackPosition () const protected inherited
Definition at line 836 of file MSVehicle.cpp.
References DEBUG_COND, MSLane::geometryPositionAtOffset(), MSVehicle::getBackPositionOnLane(), Named::getID(), MSBaseVehicle::getID(), MSVehicle::getLaneChangeModel(), MSVehicleType::getLength(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSVehicle::myFurtherLanes, MSVehicle::myFurtherLanesPosLat, MSVehicle::myLane, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSVehicle::myState, MSBaseVehicle::myType, SUMOReal, and toString().
Referenced by MSVehicle::computeAngle(), MSVehicle::estimateSpeedAfterDistance(), MSVehicle::getBoundingBox(), and MSVehicle::getBoundingPoly().
SUMOReal MSVehicle::getBackPositionOnLane (const MSLane * lane) const virtual inherited
Get the vehicle's position relative to the given lane.
Returns
The back position of the vehicle (in m from the given lane's begin)
Implements SUMOVehicle.
Definition at line 1962 of file MSVehicle.cpp.
References MSBaseVehicle::getID(), Named::getIDSecure(), MSVehicle::getLaneChangeModel(), MSVehicleType::getLength(), MSAbstractLaneChangeModel::getShadowFurtherLanes(), MSVehicle::State::myBackPos, MSVehicle::myFurtherLanes, MSVehicle::myLane, MSVehicle::State::myPos, MSVehicle::myState, MSBaseVehicle::myType, and SUMOReal.
Referenced by MSVehicle::adaptToLeaders(), MSVehicle::checkRewindLinkLanes(), MSLane::detectCollisionBetween(), MSE2Collector::detectorUpdate(), MSLane::freeInsertion(), MSLane::getCriticalLeader(), MSLane::getLeader(), MSVehicle::getLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getOppositeFollower(), MSLaneChanger::getRealLeader(), MSLane::isInsertionSuccess(), MSLink::maybeOccupied(), MSLane::vehicle_position_sorter::operator()(), MSLane::vehicle_natural_position_sorter::operator()(), MSLane::safeInsertionSpeed(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), and MSLink::writeApproaching().
SUMOReal MSVehicle::getBackPositionOnLane () const inline inherited
Get the vehicle's position relative to its current lane.
Returns
The back position of the vehicle (in m from the current lane's begin)
Definition at line 367 of file MSVehicle.h.
References MSVehicle::myLane.
Referenced by MSVehicle::getBackPosition(), and MSVehicle::getPositionOnLane().
int MSVehicle::getBestLaneOffset () const inherited
returns the current offset from the best lane
Definition at line 2836 of file MSVehicle.cpp.
References MSVehicle::myBestLanes.
Referenced by MSLCM_JE2013::changed(), MSLCM_SL2015::changed(), MSLCM_LC2013::changed(), and getColorValue().
const std::vector< MSVehicle::LaneQ > & MSVehicle::getBestLanes () const inherited
Returns the description of best lanes to use in order to continue the route.
Returns
The best lanes structure holding matching the current vehicle position and state ahead
Definition at line 2474 of file MSVehicle.cpp.
References MSVehicle::myBestLanes.
Referenced by MSLane::appropriate(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLaneChangerSublane::checkChangeHelper(), MSEdge::getDepartLane(), TraCIServerAPI_Vehicle::processGet(), and MSLCM_SL2015::updateExpectedSublaneSpeeds().
const std::vector< MSLane * > & MSVehicle::getBestLanesContinuation () const inherited
Returns the subpart of best lanes that describes the vehicle's current lane and their successors.
Returns
The best lane information for the vehicle's current lane
Todo:
Describe better
Definition at line 2808 of file MSVehicle.cpp.
References MSVehicle::myBestLanes, and MSVehicle::myEmptyLaneVector.
Referenced by MSLane::appropriate(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), drawRouteHelper(), MSLane::executeMovements(), MSLane::getCriticalLeader(), MSVehicle::getLeader(), MSLaneChangerSublane::getLeaders(), MSLane::getOppositeLeader(), MSLaneChanger::getRealLeader(), MSLane::isInsertionSuccess(), MSVehicle::planMoveInternal(), TraCIServerAPI_Vehicle::processGet(), MSVehicle::setBlinkerInformation(), MSVehicle::unsafeLinkAhead(), and MSVehicle::updateBestLanes().
const std::vector< MSLane * > & MSVehicle::getBestLanesContinuation (const MSLane *const l) const inherited
Returns the subpart of best lanes that describes the given lane and their successors.
Returns
The best lane information for the given lane
Todo:
Describe better
Definition at line 2817 of file MSVehicle.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSLane::getEdge(), MSLane::getLinkCont(), MSEdge::getPurpose(), MSVehicle::myBestLanes, and MSVehicle::myEmptyLaneVector.
PositionVector MSVehicle::getBoundingBox () const inherited
get bounding rectangle
Definition at line 3272 of file MSVehicle.cpp.
References PositionVector::append(), MSVehicle::getBackPosition(), MSVehicle::getPosition(), MSVehicleType::getWidth(), PositionVector::move2side(), MSBaseVehicle::myType, POSITION_EPS, and PositionVector::reverse().
Referenced by MSLane::detectCollisions(), drawAction_drawPersonsAndContainers(), MSVehicle::getBoundingPoly(), and MSVehicle::signalSet().
PositionVector MSVehicle::getBoundingPoly () const inherited
get bounding polygon
Definition at line 3285 of file MSVehicle.cpp.
References MSVehicle::getBackPosition(), MSVehicle::getBoundingBox(), MSVehicleType::getGuiShape(), MSVehicle::getPosition(), MSVehicleType::getWidth(), PositionVector::move2side(), MSBaseVehicle::myType, PositionVector::scaleRelative(), SVS_PASSENGER, SVS_PASSENGER_HATCHBACK, SVS_PASSENGER_SEDAN, SVS_PASSENGER_VAN, and SVS_PASSENGER_WAGON.
Referenced by MSLane::detectCollisions(), drawAction_drawPersonsAndContainers(), and MSVehicle::signalSet().
const MSCFModel& MSVehicle::getCarFollowModel () const inline inherited
Returns the vehicle's car following model definition.
This is simply a wrapper around the vehicle type's car-following model retrieval for a shorter access.
Returns
The vehicle's car following model definition
Definition at line 700 of file MSVehicle.h.
References MSVehicleType::getCarFollowModel(), and MSBaseVehicle::myType.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSCriticalFollowerDistanceInfo::addFollower(), MSVehicle::addStop(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), MSLane::checkFailure(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::computeOvertakingTime(), MSLink::couldBrakeForLeader(), MSVehicle::executeMove(), MSLane::freeInsertion(), MSLane::getCriticalLeader(), MSLane::getFollower(), MSLane::getLeader(), MSVehicle::getLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getMissingRearGap(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSVehicle::getRerouteOrigin(), MSVehicle::getSafeFollowSpeed(), getTypeParameterWindow(), MSLink::getZipperSpeed(), MSLCM_DK2008::informBlocker(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSLink::maybeOccupied(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSVehicle::processNextStop(), MSLane::safeInsertionSpeed(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), selectBlockingFoes(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSVehicle::unsafeLinkAhead(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
MSCFModel::VehicleVariables* MSVehicle::getCarFollowVariables () const inline inherited
Returns the vehicle's car following model variables.
Returns
The vehicle's car following model variables
Definition at line 709 of file MSVehicle.h.
References MSVehicle::myCFVariables.
Referenced by MSCFModel_Kerner::_v(), MSCFModel_Wiedemann::_v(), MSCFModel_IDM::_v(), MSCFModel_SmartSK::_vsafe(), MSCFModel_SmartSK::followSpeed(), MSCFModel_PWag2009::followSpeed(), MSCFModel_Kerner::moveHelper(), MSCFModel_PWag2009::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_Wiedemann::moveHelper(), MSCFModel_IDM::moveHelper(), MSCFModel_SmartSK::stopSpeed(), and MSCFModel_SmartSK::updateMyHeadway().
Boundary GUIBaseVehicle::getCenteringBoundary () const virtual inherited
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 327 of file GUIBaseVehicle.cpp.
References Boundary::add(), MSVehicleType::getLength(), GUIBaseVehicle::getPosition(), MSBaseVehicle::getVehicleType(), Boundary::grow(), and GUIBaseVehicle::myVehicle.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight().
SUMOReal MSVehicle::getCenterOnEdge (const MSLane * lane = 0) const inherited
Get the vehicle's lateral position on the edge of the given lane (or its current edge if lane == 0)
Returns
The lateral position of the vehicle (in m distance between center of vehicle and ride side of edge
Definition at line 3125 of file MSVehicle.cpp.
References DEBUG_COND, MSLane::getCenterOnEdge(), MSLane::getEdge(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), MSVehicle::getLaneChangeModel(), MSLane::getRightSideOnEdge(), MSAbstractLaneChangeModel::getShadowFurtherLanes(), MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat(), MSAbstractLaneChangeModel::getShadowLane(), MSLane::getWidth(), MSVehicle::myFurtherLanes, MSVehicle::myFurtherLanesPosLat, MSVehicle::myLane, MSVehicle::State::myPosLat, MSVehicle::myState, and SUMOReal.
Referenced by MSLCM_SL2015::checkBlocking(), MSLane::detectCollisionBetween(), MSVehicle::getLateralPositionOnLane(), MSVehicle::getRightSideOnEdge(), and MSLCM_SL2015::keepLatGap().
SUMOReal MSBaseVehicle::getChosenSpeedFactor () const inline virtual inherited
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
Returns
Speed limit factor
Implements SUMOVehicle.
Definition at line 340 of file MSBaseVehicle.h.
References MSBaseVehicle::myChosenSpeedFactor.
Referenced by GUIMEVehicle::getParameterWindow(), getParameterWindow(), and TraCIServerAPI_Vehicle::processGet().
SUMOReal MSVehicle::getCO2Emissions () const inherited
Returns CO2 emission of the current state.
Returns
The current CO2 emission
Definition at line 2917 of file MSVehicle.cpp.
References PollutantsInterface::CO2, PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), MSVehicle::getSlope(), MSVehicle::myAcceleration, MSVehicle::myState, MSBaseVehicle::myType, MSVehicle::State::speed(), and SUMOReal.
Referenced by getColorValue(), getParameterWindow(), MSVehicle::nextStopDist(), and TraCIServerAPI_Vehicle::processGet().
SUMOReal MSVehicle::getCOEmissions () const inherited
Returns CO emission of the current state.
Returns
The current CO emission
Definition at line 2923 of file MSVehicle.cpp.
References PollutantsInterface::CO, PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), MSVehicle::getSlope(), MSVehicle::myAcceleration, MSVehicle::myState, MSBaseVehicle::myType, MSVehicle::State::speed(), and SUMOReal.
Referenced by getColorValue(), getParameterWindow(), MSVehicle::nextStopDist(), and TraCIServerAPI_Vehicle::processGet().
SUMOReal GUIVehicle::getColorValue (int activeScheme) const virtual
gets the color value according to the current scheme index
Implements GUIBaseVehicle.
Definition at line 377 of file GUIVehicle.cpp.
References MSVehicle::getAcceleration(), MSVehicle::getAccumulatedWaitingSeconds(), MSVehicle::getBestLaneOffset(), MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSBaseVehicle::getDepartDelay(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), GUIGlObject::getGlID(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHCEmissions(), MSVehicle::getLane(), getLastLaneChangeOffset(), MSVehicle::getNOxEmissions(), MSBaseVehicle::getNumberReroutes(), MSVehicle::getPMxEmissions(), MSVehicle::getSpeed(), MSVehicle::getTimeGap(), MSLane::getVehicleMaxSpeed(), MSVehicle::getWaitingSeconds(), GLO_VEHICLE, gSelected, GUISelectedStorage::isSelected(), and STEPS2TIME.
Referenced by getAngle().
int MSVehicle::getContainerNumber () const inherited
Returns the number of containers.
Returns
The number of contaiers on-board
Definition at line 3033 of file MSVehicle.cpp.
References SUMOVehicleParameter::containerNumber, MSVehicle::myContainerDevice, MSBaseVehicle::myParameter, and MSDevice_Transportable::size().
Referenced by getParameterWindow(), MSTransportableControl::loadAnyWaiting(), MSVehicle::nextStopDist(), MSVehicle::processNextStop(), and MSXMLRawOut::writeVehicle().
const std::vector< MSTransportable * > & MSVehicle::getContainers () const inherited
retrieve riding containers
Definition at line 3017 of file MSVehicle.cpp.
References MSDevice_Transportable::getTransportables(), MSVehicle::myContainerDevice, and MSVehicle::myEmptyTransportableVector.
Referenced by MSVehicle::nextStopDist(), MSFCDExport::write(), and MSXMLRawOut::writeVehicle().
const MSRouteIterator& MSBaseVehicle::getCurrentRouteEdge () const inline virtual inherited
Returns an iterator pointing to the current edge in this vehicles route.
Returns
The current route pointer
Implements SUMOVehicle.
Definition at line 174 of file MSBaseVehicle.h.
References MSBaseVehicle::getAcceleration(), MSBaseVehicle::getSlope(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::onDepart(), MSBaseVehicle::replaceRouteEdges(), MSBaseVehicle::reroute(), and SUMOReal.
Referenced by TraCIServerAPI_Vehicle::vtdMap_matchingRoutePosition().
SUMOTime MSBaseVehicle::getDepartDelay () const inline virtual inherited
Returns the depart delay.
Implements SUMOVehicle.
Definition at line 234 of file MSBaseVehicle.h.
References SUMOVehicleParameter::depart, MSBaseVehicle::getDeparture(), and MSBaseVehicle::getParameter().
Referenced by GUIMEVehicle::getColorValue(), getColorValue(), GUIMEVehicle::getParameterWindow(), and getParameterWindow().
SUMOReal MSBaseVehicle::getDepartPos () const inline virtual inherited
Returns this vehicle's real departure position.
Returns
This vehicle's real departure position
Implements SUMOVehicle.
Definition at line 242 of file MSBaseVehicle.h.
References MSBaseVehicle::myDepartPos.
Referenced by TraCIServerAPI_Vehicle::processGet().
SUMOTime MSBaseVehicle::getDeparture () const inline virtual inherited
Returns this vehicle's real departure time.
Returns
This vehicle's real departure time
Implements SUMOVehicle.
Definition at line 229 of file MSBaseVehicle.h.
References MSBaseVehicle::myDeparture.
Referenced by MSBaseVehicle::getDepartDelay().
MSDevice * MSBaseVehicle::getDevice (const std::type_info & type) const virtual inherited
Returns a device of the given type if it exists or 0.
Implements SUMOVehicle.
Definition at line 409 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDevices.
Referenced by GUIBaseVehicle::drawOnPos(), MSBaseVehicle::setChosenSpeedFactor(), and MSBatteryExport::write().
const std::vector<MSDevice*>& MSBaseVehicle::getDevices () const inline virtual inherited
Returns this vehicle's devices.
Returns
This vehicle's devices
Implements SUMOVehicle.
Definition at line 283 of file MSBaseVehicle.h.
References MSBaseVehicle::activateReminders(), MSBaseVehicle::addContainer(), MSBaseVehicle::addPerson(), MSBaseVehicle::addReminder(), MSBaseVehicle::hasValidRoute(), MSBaseVehicle::myDevices, and MSBaseVehicle::removeReminder().
SUMOReal MSVehicle::getDistanceToPosition (SUMOReal destPos, const MSEdge * destEdge) const inherited
Compute distance that will be covered, if the vehicle moves to a given position on its route, starting at its current position.
Parameters
destPos position on the destination edge that shall be reached
destEdge destination edge that shall be reached
Returns
distance from the vehicles current position to the destination position, or a near infinite real value if the destination position is not contained within the vehicles route or the vehicle is not active
Definition at line 2862 of file MSVehicle.cpp.
References MSRoute::getDistanceBetween(), MSLane::getEdge(), MSLane::getLength(), MSVehicle::getPositionOnLane(), MSVehicle::isOnRoad(), max, MSBaseVehicle::myCurrEdge, MSVehicle::myLane, MSBaseVehicle::myRoute, and SUMOReal.
Referenced by MSVehicle::Influencer::implicitDeltaPosVTD(), MSVehicle::Influencer::implicitSpeedVTD(), and MSVehicle::nextStopDist().
const MSEdge * MSBaseVehicle::getEdge () const virtual inherited
Returns the edge the vehicle is currently at.
Returns
The current edge in the vehicle's route
Implements SUMOVehicle.
Definition at line 133 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myCurrEdge.
Referenced by MSVehicleTransfer::add(), MELoop::changeSegment(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), TraCIServerAPI_Vehicle::commandDistanceRequest(), MSVehicle::enterLaneAtLaneChange(), METriggeredCalibrator::execute(), MEVehicle::getAngle(), GUIMEVehicle::getParameterWindow(), MEVehicle::getPosition(), MEVehicle::getSlope(), MSBaseVehicle::getVClass(), TraCIServerAPI_Vehicle::processSet(), MESegment::receive(), MELoop::teleportVehicle(), and TraCIServerAPI_Vehicle::vtdMap().
SUMOReal MSVehicle::getElectricityConsumption () const inherited
Returns electricity consumption of the current state.
Returns
The current electricity consumption
Definition at line 2953 of file MSVehicle.cpp.
References PollutantsInterface::compute(), PollutantsInterface::ELEC, MSVehicleType::getEmissionClass(), MSVehicle::getSlope(), MSVehicle::myAcceleration, MSVehicle::myState, MSBaseVehicle::myType, MSVehicle::State::speed(), and SUMOReal.
Referenced by getColorValue(), getParameterWindow(), MSVehicle::nextStopDist(), and TraCIServerAPI_Vehicle::processGet().
SUMOReal MSVehicle::getFuelConsumption () const inherited
Returns fuel consumption of the current state.
Returns
The current fuel consumption
Definition at line 2947 of file MSVehicle.cpp.
References PollutantsInterface::compute(), PollutantsInterface::FUEL, MSVehicleType::getEmissionClass(), MSVehicle::getSlope(), MSVehicle::myAcceleration, MSVehicle::myState, MSBaseVehicle::myType, MSVehicle::State::speed(), and SUMOReal.
Referenced by getColorValue(), getParameterWindow(), MSVehicle::nextStopDist(), and TraCIServerAPI_Vehicle::processGet().
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 111 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
const std::vector<MSLane*>& MSVehicle::getFurtherLanes () const inline inherited
Definition at line 600 of file MSVehicle.h.
References MSVehicle::myFurtherLanes.
Referenced by MSAbstractLaneChangeModel::updateShadowLane().
const std::vector<SUMOReal>& MSVehicle::getFurtherLanesPosLat () const inline inherited
Definition at line 604 of file MSVehicle.h.
References MSVehicle::myFurtherLanesPosLat.
Referenced by MSAbstractLaneChangeModel::updateShadowLane().
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 123 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), drawAction_drawPersonsAndContainers(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE3::drawGL(), GNEInternalLane::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GNERouteProbe::drawGL(), GNELane::drawGL(), GNEEdge::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), GUIEdge::drawGL(), GNEConnection::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GNERerouter::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), GUIMEVehicle::getColorValue(), getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GUIContainer::getColorValue(), GNEJunction::getColorValue(), GUIPerson::getColorValue(), GNELane::getColorValue(), GUILane::getColorValue(), GUIEdge::getIDs(), GNEEdge::getLaneGlIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNECalibrator::GNECalibrator(), GNERouteProbe::GNERouteProbe(), GNEVaporizer::GNEVaporizer(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onLeftBtnPress(), GUISUMOAbstractView::removeAdditionalGLVisualisation(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), and GUIGlObject::~GUIGlObject().
SUMOReal MSVehicle::getHarmonoise_NoiseEmissions () const inherited
Returns noise emissions of the current state.
Returns
The noise produced
Definition at line 2959 of file MSVehicle.cpp.
References HelpersHarmonoise::computeNoise(), MSVehicleType::getEmissionClass(), MSVehicle::myAcceleration, MSVehicle::myState, MSBaseVehicle::myType, and MSVehicle::State::speed().
Referenced by getColorValue(), getParameterWindow(), MSVehicle::nextStopDist(), and TraCIServerAPI_Vehicle::processGet().
SUMOReal MSVehicle::getHCEmissions () const inherited
Returns HC emission of the current state.
Returns
The current HC emission
Definition at line 2929 of file MSVehicle.cpp.
References PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), MSVehicle::getSlope(), PollutantsInterface::HC, MSVehicle::myAcceleration, MSVehicle::myState, MSBaseVehicle::myType, MSVehicle::State::speed(), and SUMOReal.
Referenced by getColorValue(), getParameterWindow(), MSVehicle::nextStopDist(), and TraCIServerAPI_Vehicle::processGet().
const std::string & MSBaseVehicle::getID () const virtual inherited
Returns the name of the vehicle.
Implements SUMOVehicle.
Definition at line 105 of file MSBaseVehicle.cpp.
References SUMOVehicleParameter::id, and MSBaseVehicle::myParameter.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), MSVehicleTransfer::add(), MSBaseVehicle::addStops(), MSVehicle::addTraciBusOrContainerStop(), MSBaseVehicle::calculateArrivalParams(), MSLaneChangerSublane::change(), MSLaneChanger::change(), MSLCM_SL2015::changed(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), MSLane::checkFailure(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSAbstractLaneChangeModel::cleanupShadowLane(), MSVehicle::computeAngle(), MSLaneChanger::continueChange(), MSLCM_SL2015::decideDirection(), drawOutsideNetwork(), MSCalibrator::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSE2Collector::getCurrentVehicleIDs(), MSE2Collector::getEstimateQueueLength(), MSLane::getFirstVehicleInformation(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), GUIMEVehicle::getParameterWindow(), getParameterWindow(), MSLane::getPartialBehind(), MSAbstractLaneChangeModel::getShadowLane(), MSLane::handleCollisionBetween(), MSLCM_SL2015::inform(), MSLCM_JE2013::inform(), MSLCM_LC2013::inform(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MESegment::initialise(), MSPedestrianPushButton::isActiveForEdge(), MSLane::isInsertionSuccess(), MSVehicle::leaveLane(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSLCM_JE2013::MSLCM_JE2013(), MSLCM_LC2013::MSLCM_LC2013(), MSCalibrator::VehicleRemover::notifyEnter(), MSLCM_DK2008::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_LC2013::patchSpeed(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSAbstractLaneChangeModel::primaryLaneChanged(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), MSBaseVehicle::replaceRouteEdges(), MSBaseVehicle::reroute(), MSLane::resetPartialOccupation(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSCalibrator::scheduleRemoval(), MSLane::setPartialOccupation(), TraCIServer::setVTDControlled(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSVehicle::updateBestLanes(), MSLCM_SL2015::updateGaps(), MSAbstractLaneChangeModel::updateShadowLane(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), MSLink::writeApproaching(), and MSXMLRawOut::writeVehicle().
SUMOReal MSBaseVehicle::getImpatience () const virtual inherited
Returns this vehicles impatience.
Implements SUMOVehicle.
Definition at line 400 of file MSBaseVehicle.cpp.
References MSBaseVehicle::getVehicleType(), SUMOVehicle::getWaitingTime(), MSGlobals::gTimeToGridlock, MAX2(), MIN2(), and SUMOReal.
Referenced by MSVehicle::checkRewindLinkLanes(), MSVehicle::executeMove(), MSLane::getCriticalLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSBaseVehicle::getNumberReroutes(), getParameterWindow(), MSLane::isInsertionSuccess(), MESegment::isOpen(), and selectBlockingFoes().
MSVehicle::Influencer & MSVehicle::getInfluencer () inherited
Returns the velocity/lane influencer.
If no influencer was existing before, one is built, first
Returns
Reference to this vehicle's speed influencer
Definition at line 3448 of file MSVehicle.cpp.
References MSVehicle::myInfluencer.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLane::detectCollisionBetween(), MSLane::executeMovements(), MSLane::handleCollisionBetween(), MSVehicle::influenceChangeDecision(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), and TraCIServer::setVTDControlled().
const MSVehicle::Influencer * MSVehicle::getInfluencer () const inherited
Definition at line 3457 of file MSVehicle.cpp.
References MSVehicle::myInfluencer, and SUMOReal.
MSLane* MSVehicle::getLane () const inline virtual inherited
Returns the lane the vehicle is on.
Returns
The vehicle's current lane
Implements SUMOVehicle.
Definition at line 447 of file MSVehicle.h.
References MSVehicle::myLane.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSVehicle::adaptToLeaders(), MSVehicleTransfer::add(), MSLaneChangerSublane::change(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlocking(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), MSVehicleTransfer::checkInsertions(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::computeOvertakingTime(), MSAbstractLaneChangeModel::congested(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSE2Collector::detectorUpdate(), MSVTypeProbe::execute(), MSLane::executeMovements(), MSCFModel_IDM::followSpeed(), getColorValue(), MSLane::getFollowersOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSAbstractLaneChangeModel::getShadowDirection(), MSVTKExport::getSpeed(), MSLink::getZipperSpeed(), MSLane::integrateNewVehicle(), MSCFModel_IDM::interactionGap(), MSCFModel::interactionGap(), MSJunction::isLeader(), MSLCM_SL2015::keepLatGap(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel::moveHelper(), MSCFModel_IDM::moveHelper(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSLCM_DK2008::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSLCM_LC2013::patchSpeed(), MSVehicle::planMoveInternal(), MSVehicle::Influencer::postProcessVTD(), MSLCM_SL2015::prepareStep(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), MSVehicleTransfer::remove(), MSCalibrator::removePending(), MSLane::removeVehicle(), MSVehicle::setBlinkerInformation(), MSLaneChangerSublane::startChangeSublane(), MSCFModel_IDM::stopSpeed(), MSLaneChangerSublane::updateChanger(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSAbstractLaneChangeModel::updateShadowLane(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSQueueExport::writeLane(), and MSFullExport::writeVehicles().
MSAbstractLaneChangeModel & MSVehicle::getLaneChangeModel () inherited
Definition at line 2462 of file MSVehicle.cpp.
References MSVehicle::myLaneChangeModel.
Referenced by MSVehicleTransfer::add(), MSLaneChangerSublane::change(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), MSVehicle::checkRewindLinkLanes(), MSVehicle::computeAngle(), MSVehicle::congested(), MSLaneChanger::continueChange(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), MSVehicle::fixPosition(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), getLastLaneChangeOffset(), MSVehicle::getLatOffset(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), getParameterWindow(), MSVehicle::getPosition(), MSAbstractLaneChangeModel::MSLCMessager::informLeader(), MSAbstractLaneChangeModel::MSLCMessager::informNeighFollower(), MSAbstractLaneChangeModel::MSLCMessager::informNeighLeader(), MSVehicle::isFrontOnLane(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel::moveHelper(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSLaneChanger::registerUnchanged(), MSVehicle::removeApproachingInformation(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), selectBlockingFoes(), MSVehicle::setBlinkerInformation(), MSLaneChanger::startChange(), MSLaneChangerSublane::startChangeSublane(), MSVehicle::updateBestLanes(), and MSLaneChangerSublane::updateChanger().
const MSAbstractLaneChangeModel & MSVehicle::getLaneChangeModel () const inherited
Definition at line 2468 of file MSVehicle.cpp.
References MSVehicle::myLaneChangeModel.
int MSVehicle::getLaneIndex () const inherited
Definition at line 3096 of file MSVehicle.cpp.
References MSLane::getEdge(), MSEdge::getLanes(), and MSVehicle::myLane.
Referenced by MSLane::appropriate(), MSVehicle::influenceChangeDecision(), and MSVehicle::nextStopDist().
SUMOReal GUIVehicle::getLastLaneChangeOffset () const virtual
Returns the time since the last lane change in seconds.
See also
MSVehicle::myLastLaneChangeOffset
Returns
The time since the last lane change in seconds
Implements GUIBaseVehicle.
Definition at line 618 of file GUIVehicle.cpp.
References MSVehicle::getLaneChangeModel(), and STEPS2TIME.
Referenced by getAngle(), getColorValue(), and getParameterWindow().
SUMOReal MSVehicle::getLateralOverlap () const inherited
return the amount by which the vehicle extends laterally outside it's primary lane
Definition at line 3200 of file MSVehicle.cpp.
References MSVehicle::getLateralPositionOnLane(), MSBaseVehicle::getVehicleType(), MSLane::getWidth(), and MSVehicle::myLane.
Referenced by MSVehicle::getLateralPositionOnLane(), MSAbstractLaneChangeModel::getShadowLane(), and MSAbstractLaneChangeModel::updateShadowLane().
SUMOReal MSVehicle::getLateralPositionOnLane () const inline virtual inherited
Get the vehicle's lateral position on the lane.
Returns
The lateral position of the vehicle (in m relative to the centerline of the lane)
Reimplemented from MSBaseVehicle.
Definition at line 375 of file MSVehicle.h.
References MSVehicle::getCenterOnEdge(), MSVehicle::getLateralOverlap(), MSVehicle::getLatOffset(), MSVehicle::getRightSideOnEdge(), MSVehicle::getRightSideOnLane(), MSVehicle::State::myPosLat, MSVehicle::myState, and SUMOReal.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSLaneChanger::continueChange(), MSVehicle::executeMove(), MSLane::getCriticalLeader(), MSVehicle::getLateralOverlap(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), getParameterWindow(), MSVehicle::getPosition(), MSAbstractLaneChangeModel::getShadowLane(), MSLeaderInfo::getSubLanes(), MSLCM_SL2015::keepLatGap(), MSLane::loadState(), MSLane::vehicle_natural_position_sorter::operator()(), MSVehicle::planMove(), selectBlockingFoes(), MSLaneChangerSublane::startChangeSublane(), MSAbstractLaneChangeModel::updateShadowLane(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), and MSXMLRawOut::writeVehicle().
SUMOReal MSVehicle::getLatOffset (const MSLane * lane) const inherited
Get the offset that that must be added to interpret myState.myPosLat for the given lane.
Definition at line 3157 of file MSVehicle.cpp.
References DEBUG_COND, MSLane::getEdge(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), MSVehicle::getLaneChangeModel(), MSLane::getRightSideOnEdge(), MSAbstractLaneChangeModel::getShadowFurtherLanes(), MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat(), MSVehicle::myFurtherLanes, MSVehicle::myFurtherLanesPosLat, MSVehicle::myLane, MSVehicle::State::myPosLat, MSVehicle::myState, SIMTIME, SUMOReal, and toString().
Referenced by MSLane::getFirstVehicleInformation(), MSLane::getFollowersOnConsecutive(), MSLane::getLastVehicleInformation(), and MSVehicle::getLateralPositionOnLane().
std::pair< const MSVehicle *const, SUMOReal > MSVehicle::getLeader (SUMOReal dist = 0) const inherited
Returns the leader of the vehicle looking for a fixed distance.
If the distance is not given it is calculated from the brake gap. The gap returned does not include the minGap.
Parameters
dist up to which distance to look for a leader
Returns
The leading vehicle together with the gap; (0, -1) if no leader was found.
Definition at line 2879 of file MSVehicle.cpp.
References MSCFModel::brakeGap(), MSVehicle::getBackPositionOnLane(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSLane::getLeaderOnConsecutive(), MSLane::getLength(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSLane::getVehiclesSecure(), MSBaseVehicle::getVehicleType(), MSVehicle::myLane, MSLane::releaseVehicles(), and SUMOReal.
Referenced by MSVehicle::getTimeGap(), MSVehicle::nextStopDist(), and TraCIServerAPI_Vehicle::processGet().
SUMOReal MSBaseVehicle::getMaxSpeed () const virtual inherited
Returns the maximum speed.
Returns
The vehicle's maximum speed
Implements SUMOVehicle.
Definition at line 117 of file MSBaseVehicle.cpp.
References MSVehicleType::getMaxSpeed(), and MSBaseVehicle::myType.
Referenced by MSCFModel_Wiedemann::_v(), MSVehicleTransfer::checkInsertions(), MSVehicle::estimateSpeedAfterDistance(), GUIMEVehicle::getTypeParameterWindow(), getTypeParameterWindow(), MSBaseVehicle::getVClass(), MSVehicle::Influencer::implicitDeltaPosVTD(), and MSVehicle::Influencer::implicitSpeedVTD().
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 137 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNEPOI::getAttribute(), GNECrossing::getAttribute(), GNEJunction::getAttribute(), GNEPoly::getAttribute(), GNEEdge::getAttribute(), GNELane::getAttribute(), GNELane::getParentName(), GNENetElement::getParentName(), GNEDetectorE3::getParentName(), GNEVaporizer::getParentName(), GNEVariableSpeedSignal::getParentName(), GNERouteProbe::getParentName(), GNEStoppingPlace::getParentName(), GNECalibrator::getParentName(), GNEDetector::getParentName(), GNEAdditional::getParentName(), GNERerouter::getParentName(), GNEAdditional::getPopUpMenu(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GNEEdge::moveGeometry(), GNEPoly::moveGeometry(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEViewNet::onCmdNodeShape(), GNEViewNet::onLeftBtnPress(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNENet::replaceJunctionByGeometry(), GNENet::retrieveAttributeCarriers(), GNEAdditional::setAdditionalID(), GNEEdge::setAttribute(), GNENet::splitEdge(), and GNEConnectorFrame::updateDescription().
SUMOReal GUIBaseVehicle::getNaviDegree () const inline inherited
return the current angle in navigational degrees
Definition at line 93 of file GUIBaseVehicle.h.
References GUIBaseVehicle::drawAction_drawCarriageClass(), GUIBaseVehicle::drawRouteHelper(), GUIBaseVehicle::getAngle(), GUIBaseVehicle::getColorValue(), GUIBaseVehicle::getLastLaneChangeOffset(), GUIBaseVehicle::getParameterWindow(), GUIBaseVehicle::getStopInfo(), GUIBaseVehicle::getTypeParameterWindow(), GeomHelper::naviDegree(), GUIBaseVehicle::selectBlockingFoes(), and SUMOReal.
Referenced by GUIMEVehicle::getParameterWindow(), and getParameterWindow().
MSVehicle::Stop & MSVehicle::getNextStop () inherited
returns the next imminent stop in the stop queue
Returns
the upcoming stop
Definition at line 3442 of file MSVehicle.cpp.
References MSVehicle::myStops.
Referenced by TraCIServerAPI_Vehicle::processGet(), and MSVehicle::signalSet().
SUMOReal MSVehicle::getNOxEmissions () const inherited
Returns NOx emission of the current state.
Returns
The current NOx emission
Definition at line 2935 of file MSVehicle.cpp.
References PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), MSVehicle::getSlope(), MSVehicle::myAcceleration, MSVehicle::myState, MSBaseVehicle::myType, PollutantsInterface::NO_X, MSVehicle::State::speed(), and SUMOReal.
Referenced by getColorValue(), getParameterWindow(), MSVehicle::nextStopDist(), and TraCIServerAPI_Vehicle::processGet().
int MSBaseVehicle::getNumberReroutes () const inline virtual inherited
Returns the number of new routes this vehicle got.
Returns
the number of new routes this vehicle got
Implements SUMOVehicle.
Definition at line 272 of file MSBaseVehicle.h.
References MSBaseVehicle::getImpatience(), MSBaseVehicle::myNumberReroutes, and SUMOReal.
Referenced by GUIBaseVehicle::drawGLAdditional(), GUIMEVehicle::getColorValue(), getColorValue(), and MSBaseVehicle::replaceRouteEdges().
int GUIVehicle::getNumPassengers () const private
return the number of passengers
Definition at line 590 of file GUIVehicle.cpp.
References MSVehicle::myPersonDevice, and MSDevice_Transportable::size().
Referenced by drawAction_drawRailCarriages(), and getAngle().
const SUMOVehicleParameter & MSBaseVehicle::getParameter () const virtual inherited
Returns the vehicle's parameter (including departure definition)
Returns
The vehicle's parameter
Implements SUMOVehicle.
Definition at line 111 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myParameter, and SUMOReal.
Referenced by MSTransportableControl::boardAnyWaiting(), GUIBaseVehicle::drawOnPos(), MSBaseVehicle::getDepartDelay(), MSEdge::getDepartLane(), MSLane::getDepartSpeed(), GUIMEVehicle::getParameterWindow(), getParameterWindow(), MSLane::insertVehicle(), MSLane::isInsertionSuccess(), MSTransportableControl::loadAnyWaiting(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), GUIBaseVehicle::setFunctionalColor(), and METriggeredCalibrator::tryEmit().
GUIParameterTableWindow * GUIVehicle::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GUIBaseVehicle.
Definition at line 103 of file GUIVehicle.cpp.
References GUIParameterTableWindow::closeBuilding(), MSVehicle::getAccumulatedWaitingSeconds(), MSBaseVehicle::getChosenSpeedFactor(), MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getContainerNumber(), MSBaseVehicle::getDepartDelay(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHCEmissions(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getImpatience(), MSVehicle::getLaneChangeModel(), getLastLaneChangeOffset(), MSVehicle::getLateralPositionOnLane(), GUIBaseVehicle::getNaviDegree(), MSVehicle::getNOxEmissions(), MSBaseVehicle::getParameter(), MSVehicle::getPersonNumber(), MSVehicle::getPMxEmissions(), MSVehicle::getPositionOnLane(), MSAbstractLaneChangeModel::getShadowLane(), MSVehicle::getSlope(), MSVehicle::getSpeed(), getStopInfo(), MSVehicle::getTimeGap(), MSVehicle::getWaitingSeconds(), MSGlobals::gLaneChangeDuration, MSGlobals::gLateralResolution, MSGlobals::gWaitingTimeMemory, SUMOVehicleParameter::line, GUIParameterTableWindow::mkItem(), MSBaseVehicle::myDevices, MSVehicle::myLane, MSBaseVehicle::myParameter, time2string(), and toString().
Referenced by getAngle().
const std::string & GUIGlObject::getParentName () const virtual inherited
Returns the name of the parent object (if any)
Returns
This object's parent id
Reimplemented in GNERerouter, GNEAdditional, GNEAdditionalSet, GNEDetector, GNECalibrator, GNEStoppingPlace, GNERouteProbe, GNEVariableSpeedSignal, GNEVaporizer, GUILane, GNEDetectorE3, GNENetElement, and GNELane.
Definition at line 117 of file GUIGlObject.cpp.
References StringUtils::emptyString.
Referenced by GUIGLObjectPopupMenu::onCmdCopyEdgeName().
int MSVehicle::getPersonNumber () const inherited
Returns the number of persons.
Returns
The number of passengers on-board
Definition at line 3027 of file MSVehicle.cpp.
References MSBaseVehicle::myParameter, MSVehicle::myPersonDevice, SUMOVehicleParameter::personNumber, and MSDevice_Transportable::size().
Referenced by MSTransportableControl::boardAnyWaiting(), getParameterWindow(), MSVehicle::nextStopDist(), TraCIServerAPI_Vehicle::processGet(), MSVehicle::processNextStop(), and MSXMLRawOut::writeVehicle().
const std::vector< MSTransportable * > & MSVehicle::getPersons () const inherited
retrieve riding persons
Definition at line 3007 of file MSVehicle.cpp.
References MSDevice_Transportable::getTransportables(), MSVehicle::myEmptyTransportableVector, and MSVehicle::myPersonDevice.
Referenced by MSVehicle::nextStopDist(), MSFCDExport::write(), and MSXMLRawOut::writeVehicle().
SUMOReal MSVehicle::getPMxEmissions () const inherited
Returns PMx emission of the current state.
Returns
The current PMx emission
Definition at line 2941 of file MSVehicle.cpp.
References PollutantsInterface::compute(), MSVehicleType::getEmissionClass(), MSVehicle::getSlope(), MSVehicle::myAcceleration, MSVehicle::myState, MSBaseVehicle::myType, PollutantsInterface::PM_X, MSVehicle::State::speed(), and SUMOReal.
Referenced by getColorValue(), getParameterWindow(), MSVehicle::nextStopDist(), and TraCIServerAPI_Vehicle::processGet().
GUIGLObjectPopupMenu * GUIBaseVehicle::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 280 of file GUIBaseVehicle.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), GUIGlObject::buildShowParamsPopupEntry(), GUIGlObject::buildShowTypeParamsPopupEntry(), GUIGlObject::getGlID(), GUISUMOAbstractView::getTrackedID(), GUIBaseVehicle::hasActiveAddVisualisation(), MID_HIDE_ALLROUTES, MID_HIDE_BEST_LANES, MID_HIDE_CURRENTROUTE, MID_HIDE_LFLINKITEMS, MID_SHOW_ALLROUTES, MID_SHOW_BEST_LANES, MID_SHOW_CURRENTROUTE, MID_SHOW_FOES, MID_SHOW_LFLINKITEMS, MID_START_TRACK, MID_STOP_TRACK, GUIBaseVehicle::myAdditionalVisualizations, GUIBaseVehicle::VO_SHOW_ALL_ROUTES, GUIBaseVehicle::VO_SHOW_BEST_LANES, GUIBaseVehicle::VO_SHOW_LFLINKITEMS, and GUIBaseVehicle::VO_SHOW_ROUTE.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight().
Position GUIVehicle::getPosition (const SUMOReal offset = 0) const inline virtual
Return current position (x/y, cartesian)
Note
implementation of abstract method does not work otherwise
Implements GUIBaseVehicle.
Definition at line 81 of file GUIVehicle.h.
References MSVehicle::getPosition().
SUMOReal MSVehicle::getPositionOnLane () const inline virtual inherited
Get the vehicle's position along the lane.
Returns
The position of the vehicle (in m from the lane's begin)
Implements SUMOVehicle.
Definition at line 350 of file MSVehicle.h.
References MSVehicle::getBackPositionOnLane(), MSVehicle::State::myPos, MSVehicle::myState, and SUMOReal.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSVehicle::adaptToLeaders(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), MSVehicleTransfer::checkInsertions(), MSLCM_SL2015::checkStrategicChange(), TraCIServerAPI_Vehicle::commandDistanceRequest(), MSVehicle::computeAngle(), MSLane::detectCollisionBetween(), MSLane::detectCollisions(), MSE2Collector::detectorUpdate(), MSVehicle::executeMove(), MSLane::executeMovements(), MSLane::freeInsertion(), MSLane::getBruttoOccupancy(), MSLaneChanger::getCloserFollower(), MSVehicle::getDistanceToPosition(), MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSLane::getFirstAnyVehicle(), MSLane::getFirstVehicleInformation(), MSLane::getFollower(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MSLane::getLastVehicleInformation(), MSLane::getLeader(), MSVehicle::getLeader(), MSLaneChangerSublane::getLeaders(), MSLane::getNettoOccupancy(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), getParameterWindow(), MSLane::getPartialBehind(), MSVehicle::getPosition(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSVehicle::getSlope(), MSVTKExport::getSpeed(), MSLane::lastInsertion(), MSLane::loadState(), MSLane::VehPosition::operator()(), MSLCM_JE2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSLCM_LC2013::patchSpeed(), MSVehicle::planMove(), TraCIServerAPI_Vehicle::processGet(), MSCalibrator::remainingVehicleCapacity(), MSLane::safeInsertionSpeed(), selectBlockingFoes(), MSVehicle::setBlinkerInformation(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSVehicle::unsafeLinkAhead(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), and MSQueueExport::writeLane().
SUMOReal MSVehicle::getPositionOnLane (const MSLane * lane) const inherited
Get the vehicle's front position relative to the given lane.
Returns
The front position of the vehicle (in m from the given lane's begin)
Definition at line 2016 of file MSVehicle.cpp.
References MSVehicle::getBackPositionOnLane(), MSVehicleType::getLength(), and MSBaseVehicle::myType.
MSLane * GUIVehicle::getPreviousLane (MSLane * current, int & furtherIndex) const private
Definition at line 481 of file GUIVehicle.cpp.
References MSVehicle::myFurtherLanes.
Referenced by drawAction_drawRailCarriages(), and getAngle().
const MSEdge * MSVehicle::getRerouteOrigin () const virtual inherited
Returns the starting point for reroutes (usually the current edge)
This differs from *myCurrEdge only if the vehicle is on an internal edge or very close to the junction
Returns
The rerouting start point
Reimplemented from MSBaseVehicle.
Definition at line 787 of file MSVehicle.cpp.
References MSCFModel::brakeGap(), MSRoute::end(), MSVehicle::getCarFollowModel(), MSLane::getInternalFollower(), MSLane::getLength(), MSBaseVehicle::myCurrEdge, MSVehicle::myLane, MSVehicle::State::myPos, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, and MSVehicle::myState.
Referenced by MSVehicle::isOnRoad(), and TraCIServerAPI_Vehicle::processSet().
SUMOReal MSVehicle::getRightSideOnEdge (const MSLane * lane = 0) const inherited
Get the vehicle's lateral position on the edge of the given lane (or its current edge if lane == 0)
Returns
The lateral position of the vehicle (in m distance between right side of vehicle and ride side of edge
Definition at line 3119 of file MSVehicle.cpp.
References MSVehicle::getCenterOnEdge(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), and SUMOReal.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSLCM_SL2015::checkBlockingVehicles(), and MSVehicle::getLateralPositionOnLane().
SUMOReal MSVehicle::getRightSideOnLane () const inherited
Get the vehicle's lateral position on the lane:
Returns
The lateral position of the vehicle (in m distance between right side of vehicle and ride side of the lane it is on
Definition at line 3113 of file MSVehicle.cpp.
References MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSLane::getWidth(), MSVehicle::myLane, MSVehicle::State::myPosLat, MSVehicle::myState, and SUMOReal.
Referenced by MSVehicle::getLateralPositionOnLane().
const MSRoute& MSBaseVehicle::getRoute () const inline virtual inherited
Returns the current route.
Returns
The route the vehicle uses
Implements SUMOVehicle.
Definition at line 89 of file MSBaseVehicle.h.
References MSBaseVehicle::myRoute.
Referenced by TraCIServerAPI_Vehicle::commandDistanceRequest(), GUIBaseVehicle::drawRoute(), MSEdge::getDepartLane(), MSLane::isInsertionSuccess(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Vehicle::processGet(), GUIBaseVehicle::setFunctionalColor(), TraCIServerAPI_Vehicle::vtdMap(), and TraCIServerAPI_Vehicle::vtdMap_matchingRoutePosition().
int MSVehicle::getRoutePosition () const inherited
Definition at line 669 of file MSVehicle.cpp.
References MSRoute::begin(), MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), TraCIServerAPI_Vehicle::processGet(), and TraCIServerAPI_Vehicle::vtdMap().
SUMOReal MSVehicle::getSafeFollowSpeed (const std::pair< const MSVehicle *, SUMOReal > leaderInfo, const SUMOReal seen, const MSLane *const lane, SUMOReal distToCrossing) const inherited
compute safe speed for following the given leader
Definition at line 1538 of file MSVehicle.cpp.
References MSCFModel::followSpeed(), MSVehicle::getCarFollowModel(), MSLane::getLength(), MSVehicle::getSpeed(), MAX2(), POSITION_EPS, MSCFModel::stopSpeed(), and SUMOReal.
Referenced by MSVehicle::adaptToLeader(), MSLane::getCriticalLeader(), and MSVehicle::hasInfluencer().
const Position & GUIBaseVehicle::getSeatPosition (int personIndex) const protected inherited
returns the seat position for the person with the given index
if there are not enough seats in the vehicle people have to squeeze onto the last seat
Definition at line 1179 of file GUIBaseVehicle.cpp.
References MIN2(), and GUIBaseVehicle::mySeatPositions.
Referenced by drawAction_drawPersonsAndContainers().
int MSVehicle::getSignals () const inline inherited
Returns the signals.
Returns
The signals' states
Definition at line 1011 of file MSVehicle.h.
References MSVehicle::mySignals.
Referenced by TraCIServerAPI_Vehicle::processGet(), and MSFCDExport::write().
SUMOReal MSVehicle::getSlope () const virtual inherited
Returns the slope of the road at vehicle's position.
Returns
The slope
Reimplemented from MSBaseVehicle.
Definition at line 750 of file MSVehicle.cpp.
References MSVehicle::getPositionOnLane(), MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), MSVehicle::myLane, PositionVector::slopeDegreeAtOffset(), and SUMOReal.
Referenced by MSVehicle::getAcceleration(), MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), MSVehicle::getHCEmissions(), MSVehicle::getNOxEmissions(), getParameterWindow(), MSVehicle::getPMxEmissions(), MSCFModel_KraussPS::maxNextSpeed(), and TraCIServerAPI_Vehicle::processGet().
SUMOReal MSVehicle::getSpaceTillLastStanding (const MSLane * l, bool & foundStopped) const protected inherited
Definition at line 2028 of file MSVehicle.cpp.
References MSLane::getLength(), MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), SUMO_const_haltingSpeed, and SUMOReal.
Referenced by MSVehicle::checkRewindLinkLanes(), and MSVehicle::hasInfluencer().
SUMOReal MSVehicle::getSpeed () const inline virtual inherited
Returns the vehicle's current speed.
Returns
The vehicle's speed
Implements SUMOVehicle.
Definition at line 410 of file MSVehicle.h.
References MSVehicle::State::mySpeed, and MSVehicle::myState.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSCFModel_Wiedemann::_v(), MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSCriticalFollowerDistanceInfo::addFollower(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), GUIApplicationWindow::checkGamingEvents(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLaneChanger::computeOvertakingTime(), MSLink::couldBrakeForLeader(), MSE2Collector::detectorUpdate(), MSVehicle::executeMove(), MSLane::executeMovements(), MSLane::forceVehicleInsertion(), MSLane::freeInsertion(), getColorValue(), MSLane::getCriticalLeader(), MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSLane::getFollower(), MSLane::getLeader(), MSVehicle::getLeader(), MSLaneChangerSublane::getLeaders(), MSLane::getMissingRearGap(), getParameterWindow(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSVehicle::getSafeFollowSpeed(), MSVTKExport::getSpeed(), MSVehicle::getTimeGap(), MSLink::getZipperSpeed(), MSLCM_DK2008::informBlocker(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), MSCFModel_IDM::interactionGap(), MSCFModel::interactionGap(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSLane::loadState(), MSLink::maybeOccupied(), MSCFModel_Daniel1::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_PWag2009::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_Wiedemann::moveHelper(), MSCFModel::moveHelper(), MSLCM_DK2008::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSLCM_LC2013::patchSpeed(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSAbstractLaneChangeModel::predInteraction(), MSAbstractLaneChangeModel::primaryLaneChanged(), TraCIServerAPI_Vehicle::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), MSLane::safeInsertionSpeed(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSVehicle::unsafeLinkAhead(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), and MSQueueExport::writeLane().
SUMOReal MSVehicle::getSpeedWithoutTraciInfluence () const inherited
Returns the uninfluenced velocity.
If no influencer exists (myInfluencer==0) the vehicle's current speed is returned. Otherwise the speed returned from myInfluencer->getOriginalSpeed().
Returns
The vehicle's velocity as it would without an influence
See also
Influencer::getOriginalSpeed
Definition at line 3463 of file MSVehicle.cpp.
References MSVehicle::Influencer::getOriginalSpeed(), MSVehicle::myInfluencer, MSVehicle::State::mySpeed, and MSVehicle::myState.
Referenced by TraCIServerAPI_Vehicle::processGet(), and MSVehicle::signalSet().
const ConstMSEdgeVector MSVehicle::getStopEdges () const protected virtual inherited
Returns the list of still pending stop edges.
Implements MSBaseVehicle.
Definition at line 1137 of file MSVehicle.cpp.
References MSVehicle::myStops.
Referenced by MSVehicle::hasInfluencer().
std::string GUIVehicle::getStopInfo () const private virtual
retrieve information about the current stop state
Implements GUIBaseVehicle.
Definition at line 624 of file GUIVehicle.cpp.
References MSVehicle::isParking(), MSVehicle::isStopped(), MSVehicle::myStops, and time2string().
Referenced by getAngle(), and getParameterWindow().
SUMOReal MSVehicle::getTimeGap () const inherited
Returns the time gap in seconds to the leader of the vehicle looking for a fixed distance.
If the distance is too big -1 is returned. The gap returned takes the minGap into account.
Returns
The time gap in seconds; -1 if no leader was found or speed is 0.
Definition at line 2907 of file MSVehicle.cpp.
References MSVehicle::getLeader(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), and SUMOReal.
Referenced by getColorValue(), getParameterWindow(), and MSVehicle::nextStopDist().
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 150 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), drawAction_drawPersonsAndContainers(), drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEAdditionalSet::drawConnections(), GNEDetector::drawDetectorIcon(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE3::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GNELane::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GNERerouter::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorE2::getAttribute(), GNEContainerStop::getAttribute(), GNEBusStop::getAttribute(), GNEDetectorE3::getAttribute(), GNEVaporizer::getAttribute(), GNEVariableSpeedSignal::getAttribute(), GNERouteProbe::getAttribute(), GNEChargingStation::getAttribute(), GNECalibrator::getAttribute(), GNERerouter::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNEJunction::getColorValue(), GNELane::getColorValue(), GUILane::getColorValue(), GNEViewNet::getEdgeAtCursorPosition(), GNEViewNet::getEdgesAtCursorPosition(), GNEViewNet::getJunctionAtCursorPosition(), GNEViewNet::getLaneAtCurserPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEDetectorE1::isValid(), GNEDetectorE2::isValid(), GNEContainerStop::isValid(), GNEBusStop::isValid(), GNEDetectorE3::isValid(), GNEVaporizer::isValid(), GNEVariableSpeedSignal::isValid(), GNERouteProbe::isValid(), GNEChargingStation::isValid(), GNECalibrator::isValid(), GNERerouter::isValid(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onDoubleClicked(), GNEViewNet::onLeftBtnPress(), LayeredRTree::selectLayer(), GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEDetectorE1::setAttribute(), GNEDetectorE2::setAttribute(), GNEContainerStop::setAttribute(), GNEBusStop::setAttribute(), GNEDetectorE3::setAttribute(), GNEVaporizer::setAttribute(), GNEVariableSpeedSignal::setAttribute(), GNERouteProbe::setAttribute(), GNEChargingStation::setAttribute(), GNECalibrator::setAttribute(), GNERerouter::setAttribute(), GNEJunction::setColor(), and GUISelectedStorage::toggleSelection().
GUIParameterTableWindow * GUIVehicle::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own type parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Implements GUIBaseVehicle.
Definition at line 186 of file GUIVehicle.cpp.
References GUIParameterTableWindow::closeBuilding(), MSVehicle::getCarFollowModel(), MSVehicleType::getContainerCapacity(), MSVehicleType::getEmissionClass(), MSVehicleType::getID(), MSVehicleType::getLength(), Parameterised::getMap(), MSBaseVehicle::getMaxSpeed(), MSVehicleType::getMinGap(), PollutantsInterface::getName(), MSVehicleType::getParameter(), MSVehicleType::getPersonCapacity(), MSVehicleType::getVehicleClass(), MSVehicleType::getWidth(), GUIParameterTableWindow::mkItem(), MSBaseVehicle::myType, SumoVehicleClassStrings, and toString().
Referenced by getAngle().
SUMOVehicleClass MSBaseVehicle::getVClass () const inline virtual inherited
Returns the vehicle's access class.
Returns
The vehicle's access class
Implements SUMOVehicle.
Definition at line 105 of file MSBaseVehicle.h.
References MSBaseVehicle::getEdge(), MSBaseVehicle::getMaxSpeed(), MSVehicleType::getParameter(), MSBaseVehicle::myType, MSBaseVehicle::succEdge(), SUMOReal, and SUMOVTypeParameter::vehicleClass.
Referenced by MSPedestrianPushButton::isActiveForEdge(), and MSBaseVehicle::reroute().
const MSVehicleType& MSBaseVehicle::getVehicleType () const inline virtual inherited
Returns the vehicle's type definition.
Returns
The vehicle's type definition
Implements SUMOVehicle.
Definition at line 97 of file MSBaseVehicle.h.
References MSBaseVehicle::myType.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSVehicle::adaptToLeaders(), MSVehicle::addStop(), MSLane::basePos(), MSTransportableControl::boardAnyWaiting(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), MSLane::checkFailure(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSLaneChanger::computeOvertakingTime(), MSLaneChanger::continueChange(), MSLane::detectCollisionBetween(), MSE2Collector::detectorUpdate(), drawAction_drawLinkItems(), drawAction_drawRailCarriages(), drawAction_drawVehicleBlinker(), drawAction_drawVehicleBrakeLight(), GUIEdge::drawMesoVehicles(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MEVehicle::estimateLeaveSpeed(), MSVehicle::estimateLeaveSpeed(), MSVehicle::estimateSpeedAfterDistance(), MSVehicle::executeMove(), MSLane::executeMovements(), MSLane::freeInsertion(), MEVehicle::getBackPositionOnLane(), MSLane::getBruttoOccupancy(), GUIBaseVehicle::getCenteringBoundary(), MSLane::getCriticalLeader(), MSEdge::getDepartLane(), MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), MSBaseVehicle::getImpatience(), MSVehicle::getLateralOverlap(), MSLane::getLeader(), MSVehicle::getLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getNettoOccupancy(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSVehicle::getRightSideOnEdge(), MSVehicle::getRightSideOnLane(), MSLeaderInfo::getSubLanes(), MSVehicle::getTimeGap(), MSLink::getZipperSpeed(), MESegment::hasSpaceFor(), MSLane::incorporateVehicle(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLane::insertVehicle(), MSLane::integrateNewVehicle(), MSLane::isInsertionSuccess(), MESegment::isOpen(), MSLCM_SL2015::keepLatGap(), MSLane::lastInsertion(), MSLane::leftByLaneChange(), MSTransportableControl::loadAnyWaiting(), MESegment::loadState(), MSVehicle::overlap(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Vehicle::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), MESegment::receive(), MSLaneChanger::registerUnchanged(), MESegment::removeCar(), MSLane::removeVehicle(), MSLane::safeInsertionSpeed(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), selectBlockingFoes(), MESegment::send(), GUIBaseVehicle::setFunctionalColor(), MSVehicle::setTentativeLaneAndPosition(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChanger::startChange(), MSLaneChangerSublane::startChangeSublane(), MSVehicle::unsafeLinkAhead(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSVehicle::updateFurtherLanes(), MSLCM_SL2015::updateGaps(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), and MSQueueExport::writeLane().
SUMOReal MSVehicle::getWaitingSeconds () const inline inherited
Returns the number of seconds waited (speed was lesser than 0.1m/s)
The value is reset if the vehicle moves faster than 0.1m/s Intentional stopping does not count towards this time.
Returns
The time the vehicle is standing
Definition at line 502 of file MSVehicle.h.
References MSVehicle::myWaitingTime, and STEPS2TIME.
Referenced by getColorValue(), getParameterWindow(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSPedestrianPushButton::isActiveForEdge(), TraCIServerAPI_Vehicle::processGet(), MSEmissionExport::write(), MSQueueExport::writeLane(), and MSFullExport::writeVehicles().
SUMOTime MSVehicle::getWaitingTime () const inline virtual inherited
Returns the SUMOTime waited (speed was lesser than 0.1m/s)
The value is reset if the vehicle moves faster than 0.1m/s Intentional stopping does not count towards this time.
Returns
The time the vehicle is standing
Implements SUMOVehicle.
Definition at line 481 of file MSVehicle.h.
References MSVehicle::myWaitingTime.
Referenced by MSVehicle::checkRewindLinkLanes(), MSVehicle::executeMove(), MSLane::executeMovements(), selectBlockingFoes(), and MSLink::writeApproaching().
const MSEdgeWeightsStorage & MSVehicle::getWeightsStorage () const inherited
Returns the vehicle's internal edge travel times/efforts container.
If the vehicle does not have such a container, it is built.
Returns
The vehicle's knowledge about edge weights
Definition at line 684 of file MSVehicle.cpp.
References MSVehicle::_getWeightsStorage().
Referenced by MSNet::getEffort(), MSNet::getTravelTime(), TraCIServerAPI_Vehicle::processGet(), and TraCIServerAPI_Vehicle::processSet().
MSEdgeWeightsStorage & MSVehicle::getWeightsStorage () inherited
Definition at line 690 of file MSVehicle.cpp.
References MSVehicle::_getWeightsStorage().
bool GUIBaseVehicle::hasActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) const inherited
Returns whether the named feature is enabled in the given view.
Parameters
[in] parent The view for which the feature may be enabled
[in] which The visualisation feature
Returns
see comment
Definition at line 1121 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::myAdditionalVisualizations.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::drawGLAdditional(), and GUIBaseVehicle::getPopUpMenu().
bool MSVehicle::hasArrived () const virtual inherited
Returns whether this vehicle has already arived (reached the arrivalPosition on its final edge)
Reimplemented from MSBaseVehicle.
Definition at line 601 of file MSVehicle.cpp.
References MSRoute::end(), MSVehicle::isRemoteControlled(), MSBaseVehicle::myArrivalPos, MSBaseVehicle::myCurrEdge, MSVehicle::State::myPos, MSBaseVehicle::myRoute, MSVehicle::myState, MSVehicle::myStops, and POSITION_EPS.
Referenced by MSVehicle::enterLaneAtMove(), MSVehicle::executeMove(), and MSLane::executeMovements().
bool MSBaseVehicle::hasDeparted () const virtual inherited
Returns whether this vehicle has already departed.
Implements SUMOVehicle.
Definition at line 265 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDeparture, and MSBaseVehicle::NOT_YET_DEPARTED.
Referenced by MSVehicle::addStop(), MSLane::forceVehicleInsertion(), MEVehicle::loadState(), MSVehicle::loadState(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), and MSBaseVehicle::setArrivalPos().
bool MSVehicle::hasInfluencer () const inline inherited
Definition at line 1301 of file MSVehicle.h.
References MSVehicle::adaptLaneEntering2MoveReminder(), MSVehicle::getSafeFollowSpeed(), MSVehicle::getSpaceTillLastStanding(), MSVehicle::getStopEdges(), MSVehicle::influenceChangeDecision(), MSVehicle::loadState(), MSVehicle::myInfluencer, MSVehicle::nextLinkPriority(), MSVehicle::saveState(), MSVehicle::setBlinkerInformation(), MSVehicle::setEmergencyBlueLight(), MSVehicle::setVTDState(), SUMOReal, and MSVehicle::updateOccupancyAndCurrentBestLane().
Referenced by MSLane::detectCollisionBetween(), MSLane::executeMovements(), MSLane::handleCollisionBetween(), and MSVehicle::influenceChangeDecision().
bool MSVehicle::hasStops () const inline inherited
Returns whether the vehicle has to stop somewhere.
Returns
Whether the vehicle has to stop somewhere
Definition at line 771 of file MSVehicle.h.
References MSVehicle::isParking(), MSVehicle::isRemoteControlled(), MSVehicle::isStopped(), and MSVehicle::myStops.
bool MSBaseVehicle::hasValidRoute (std::string & msg, const MSRoute * route = 0) const virtual inherited
Validates the current or given route.
Parameters
[out] msg Description why the route is not valid (if it is the case)
[in] route The route to check (or 0 if the current route shall be checked)
Returns
Whether the vehicle's current route is valid
Implements SUMOVehicle.
Definition at line 284 of file MSBaseVehicle.cpp.
References MSRoute::begin(), MSRoute::end(), MSVehicleType::getVehicleClass(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myRoute, and MSBaseVehicle::myType.
Referenced by MSBaseVehicle::getDevices(), MESegment::initialise(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), and MSBaseVehicle::replaceRouteEdges().
int MSVehicle::influenceChangeDecision (int state) inherited
allow TraCI to influence a lane change decision
Definition at line 3472 of file MSVehicle.cpp.
References MSLane::getEdge(), MSVehicle::getInfluencer(), MSNet::getInstance(), MSVehicle::getLaneIndex(), MSVehicle::hasInfluencer(), MSVehicle::Influencer::influenceChangeDecision(), and MSVehicle::myLane.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSAbstractLaneChangeModel::cancelRequest(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), MSLCM_SL2015::checkStrategicChange(), and MSVehicle::hasInfluencer().
bool MSVehicle::isFrontOnLane (const MSLane * lane) const virtual inherited
Returns the information whether the front of the vehicle is on the given lane.
Returns
Whether the vehicle's front is on that lane
Reimplemented from MSBaseVehicle.
Definition at line 2022 of file MSVehicle.cpp.
References MSVehicle::getLaneChangeModel(), MSAbstractLaneChangeModel::getShadowLane(), MSVehicle::myLane, and SUMOReal.
Referenced by MSVehicle::checkRewindLinkLanes(), MSLane::detectCollisionBetween(), MSLane::getFirstVehicleInformation(), MSLane::getFollowersOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLane::getPartialBehind(), MSVehicle::isOnRoad(), and MSLink::writeApproaching().
bool MSVehicle::isOnRoad () const inline virtual inherited
Returns the information whether the vehicle is on a road (is simulated)
Returns
Whether the vehicle is simulated
Reimplemented from MSBaseVehicle.
Definition at line 455 of file MSVehicle.h.
References MSVehicle::getRerouteOrigin(), MSVehicle::isFrontOnLane(), and MSVehicle::myAmOnNet.
Referenced by GUIApplicationWindow::checkGamingEvents(), TraCIServerAPI_Vehicle::commandDistanceRequest(), MSVehicle::getDistanceToPosition(), MSVTKExport::getPositions(), MSVTKExport::getSpeed(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Vehicle::vtdMap(), MSBatteryExport::write(), and MSQueueExport::writeLane().
bool MSVehicle::isParking () const virtual inherited
Returns whether the vehicle is parking.
Returns
whether the vehicle is parking
Implements SUMOVehicle.
Definition at line 994 of file MSVehicle.cpp.
References MSVehicle::isStopped(), and MSVehicle::myStops.
Referenced by MSVehicleTransfer::add(), MSVehicle::computeAngle(), MSLane::executeMovements(), MSVehicle::getPosition(), getStopInfo(), MSVehicle::hasStops(), and TraCIServerAPI_Vehicle::processGet().
bool MSVehicle::isRemoteControlled () const virtual inherited
Returns the information whether the vehicle is fully controlled via TraCI.
Returns
Whether the vehicle is remote-controlled
Reimplemented from MSBaseVehicle.
Definition at line 3492 of file MSVehicle.cpp.
References MSVehicle::Influencer::isVTDControlled(), and MSVehicle::myInfluencer.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), MSVehicle::executeMove(), MSVehicle::getPosition(), MSVehicle::hasArrived(), and MSVehicle::hasStops().
bool MSVehicle::isStopped () const virtual inherited
Returns whether the vehicle is at a stop.
Returns
Whether the vehicle has stopped
Implements SUMOVehicle.
Definition at line 988 of file MSVehicle.cpp.
References MSVehicle::myStops.
Referenced by MSLaneChanger::changeOpposite(), MSVehicle::executeMove(), MSLane::executeMovements(), getStopInfo(), MSVehicle::hasStops(), MSVehicle::isParking(), MSVehicle::isStoppedInRange(), MSVehicle::isStoppedTriggered(), TraCIServerAPI_Vehicle::processGet(), and MSVehicle::resumeFromStopping().
bool MSVehicle::isStoppedInRange (SUMOReal pos) const inherited
return whether the given position is within range of the current stop
Definition at line 1006 of file MSVehicle.cpp.
References MSVehicle::isStopped(), MSVehicle::myStops, and SUMOReal.
Referenced by MSVehicleControl::getWaitingVehicle(), and MSVehicle::nextStopDist().
bool MSVehicle::isStoppedTriggered () const virtual inherited
Returns whether the vehicle is on a triggered stop.
Returns
whether the vehicle is on a triggered stop
Implements SUMOVehicle.
Definition at line 1000 of file MSVehicle.cpp.
References MSVehicle::isStopped(), and MSVehicle::myStops.
Referenced by MSVehicle::nextStopDist().
bool MSVehicle::knowsEdgeTest (MSEdge & edge) const inherited
Referenced by MSVehicle::nextStopDist().
void MSVehicle::leaveLane (const MSMoveReminder::Notification reason) inherited
Update of members if vehicle leaves a new lane in the lane change step or at arrival.
Definition at line 2413 of file MSVehicle.cpp.
References DEBUG_COND, MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::myAmOnNet, MSBaseVehicle::myCurrEdge, MSVehicle::myFurtherLanes, MSVehicle::myFurtherLanesPosLat, MSBaseVehicle::myMoveReminders, MSVehicle::State::myPos, MSVehicle::myState, MSVehicle::myStops, MSMoveReminder::NOTIFICATION_JUNCTION, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSMoveReminder::NOTIFICATION_PARKING, MSMoveReminder::NOTIFICATION_TELEPORT, MSVehicle::resumeFromStopping(), SIMTIME, time2string(), and WRITE_WARNING.
Referenced by MSVehicleTransfer::checkInsertions(), MSVehicle::congested(), MSVehicle::executeMove(), MSVehicle::onRemovalFromNet(), MSAbstractLaneChangeModel::primaryLaneChanged(), and MSLane::removeVehicle().
void MSVehicle::loadState (const SUMOSAXAttributes & attrs, const SUMOTime offset) virtual inherited
Loads the state of this vehicle from the given description.
Implements SUMOVehicle.
Definition at line 3514 of file MSVehicle.cpp.
References SUMOSAXAttributes::getFloat(), SUMOSAXAttributes::getString(), SUMOSAXAttributes::hasAttribute(), MSBaseVehicle::hasDeparted(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myDeparture, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSVehicle::State::mySpeed, MSVehicle::myState, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_SPEED, and SUMO_ATTR_STATE.
Referenced by MSVehicle::hasInfluencer().
int MSVehicle::nextLinkPriority (const std::vector< MSLane * > & conts) static inherited
get a numerical value for the priority of the upcoming link
Definition at line 2775 of file MSVehicle.cpp.
References MSLinkContHelper::getConnectingLink(), and MSLink::havePriority().
Referenced by MSVehicle::hasInfluencer(), and MSVehicle::updateBestLanes().
SUMOReal MSVehicle::nextStopDist () const inline inherited
return the distance to the next stop or SUMORealMax if there is none.
Definition at line 791 of file MSVehicle.h.
References MSVehicle::addContainer(), MSVehicle::addPerson(), MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getContainerNumber(), MSVehicle::getContainers(), MSVehicle::getDistanceToPosition(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHCEmissions(), MSVehicle::getLaneIndex(), MSVehicle::getLeader(), MSVehicle::getNOxEmissions(), MSVehicle::getPersonNumber(), MSVehicle::getPersons(), MSVehicle::getPMxEmissions(), MSVehicle::getTimeGap(), MSVehicle::isStoppedInRange(), MSVehicle::isStoppedTriggered(), MSVehicle::knowsEdgeTest(), MSVehicle::myStopDist, MSVehicle::processNextStop(), and SUMOReal.
Referenced by MSLaneChanger::changeOpposite().
void MSBaseVehicle::onDepart () virtual inherited
Called when the vehicle is inserted into the network.
Sets optional information about departure time, informs the vehicle control about a further running vehicle.
Implements SUMOVehicle.
Definition at line 257 of file MSBaseVehicle.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), SUMOVehicle::getPositionOnLane(), MSNet::getVehicleControl(), MSBaseVehicle::myDepartPos, MSBaseVehicle::myDeparture, and MSVehicleControl::vehicleDeparted().
Referenced by MSVehicle::enterLaneAtInsertion(), MSBaseVehicle::getCurrentRouteEdge(), and MESegment::receive().
void MSVehicle::onRemovalFromNet (const MSMoveReminder::Notification reason) inherited
Called when the vehicle is removed from the network.
Moves along work reminders and informs all devices about quitting. Calls "leaveLane" then.
Parameters
[in] reason why the vehicle leaves (reached its destination, parking, teleport)
Definition at line 591 of file MSVehicle.cpp.
References MSVehicleTransfer::getInstance(), MSVehicle::leaveLane(), MSVehicle::myLFLinkLanes, MSVehicle::State::myPos, MSVehicle::State::mySpeed, MSVehicle::myState, MSVehicleTransfer::remove(), MSVehicle::removeApproachingInformation(), SPEED2DIST, and MSVehicle::workOnMoveReminders().
Referenced by MSVehicleTransfer::add(), MSLane::detectCollisions(), MSLane::executeMovements(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Vehicle::processSet(), and MSCalibrator::removePending().
static bool MSVehicle::overlap (const MSVehicle * veh1, const MSVehicle * veh2) inline static inherited
Returns true if the two vehicles overlap.
Definition at line 532 of file MSVehicle.h.
References MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), MSVehicle::State::myPos, and MSVehicle::myState.
void MSVehicle::planMove (const SUMOTime t, const MSLeaderInfo & ahead, const SUMOReal lengthsInFront) inherited
Compute safe velocities for the upcoming lanes based on positions and speeds from the last time step. Also registers ApproachingVehicleInformation for all links.
This method goes through the best continuation lanes of the current lane and computes the safe velocities for passing/stopping at the next link as a DriveProcessItem
Afterwards it checks if any DriveProcessItem should be discared to avoid blocking a junction (checkRewindLinkLanes).
Finally the ApproachingVehicleInformation is registered for all links that shall be passed
Parameters
[in] t The current timeStep
[in] ahead The leaders (may be 0)
[in] lengthsInFront Sum of vehicle lengths in front of the vehicle
Definition at line 1147 of file MSVehicle.cpp.
References MSVehicle::checkRewindLinkLanes(), DEBUG_COND, Named::getID(), MSBaseVehicle::getID(), MSVehicle::getLaneChangeModel(), MSVehicle::getLateralPositionOnLane(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSVehicle::myLane, MSVehicle::myLFLinkLanes, MSVehicle::myStopDist, MSVehicle::planMoveInternal(), MSAbstractLaneChangeModel::resetChanged(), and STEPS2TIME.
void MSVehicle::planMoveInternal (const SUMOTime t, MSLeaderInfo ahead, DriveItemVector & lfLinks, SUMOReal & myStopDist) const protected inherited
Definition at line 1198 of file MSVehicle.cpp.
References MSVehicle::DriveProcessItem::adaptLeaveSpeed(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), ARRIVAL_SPEED_GIVEN, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, bla, MSCFModel::brakeGap(), MSVehicle::Stop::busstop, CRLL_LOOK_AHEAD, DEBUG_COND, DELTA_T, DIST_TO_STOPLINE_EXPECT_PRIORITY, MSEdge::EDGEFUNCTION_INTERNAL, MSRoute::end(), MSVehicle::Stop::endPos, MSVehicle::estimateLeaveSpeed(), MSVehicle::estimateSpeedAfterDistance(), MSCFModel::freeSpeed(), gDebugSelectedVehicle, MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSLane::getEdge(), MSCFModel::getHeadwayTime(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getLaneChangeModel(), MSStoppingPlace::getLastFreePos(), MSLane::getLastVehicleInformation(), MSVehicleType::getLength(), MSLane::getLength(), MSLane::getLogicalPredecessorLane(), MSCFModel::getMaxAccel(), MSCFModel::getMaxDecel(), MSLane::getOpposite(), MSLane::getParallelLane(), MSEdge::getPurpose(), MSLane::getRightSideOnEdge(), MSAbstractLaneChangeModel::getShadowLane(), MSVehicle::getSpeed(), MSCFModel::getSpeedAfterMaxDecel(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSGlobals::gUsingInternalLanes, MSVehicle::Influencer::influenceSpeed(), MSEdge::isInternal(), MSLane::isLinkEnd(), MSAbstractLaneChangeModel::isOpposite(), LINKDIR_LEFT, LINKDIR_RIGHT, LINKSTATE_TL_RED, LINKSTATE_TL_REDYELLOW, LINKSTATE_TL_YELLOW_MAJOR, LINKSTATE_TL_YELLOW_MINOR, max, MAX2(), MAX3(), MSCFModel::maxNextSpeed(), MIN2(), MSBaseVehicle::myArrivalPos, MSBaseVehicle::myCurrEdge, MSVehicle::myInfluencer, MSVehicle::myLane, MSBaseVehicle::myParameter, MSVehicle::State::myPos, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, MSVehicle::myState, MSVehicle::myStops, MSVehicle::DriveProcessItem::myVLinkWait, NUMERICAL_EPS, POSITION_EPS, MSVehicle::removeApproachingInformation(), SIMTIME, SPEED2DIST, STEPS2TIME, MSCFModel::stopSpeed(), MSLane::succLinkSec(), SUMO_const_haltingSpeed, SUMOReal, TIME2STEPS, and toString().
Referenced by MSVehicle::planMove().
SUMOReal MSVehicle::processNextStop (SUMOReal currentVelocity) inherited
Processes stops, returns the velocity needed to reach the stop.
Returns
The velocity in dependance to the next/current stop
Todo:
Describe more detailed
See also
Stop
MSStoppingPlace
MSStoppingPlace
Definition at line 1012 of file MSVehicle.cpp.
References MSVehicleControl::addWaiting(), MSVehicle::Stop::awaitedContainers, MSVehicle::Stop::awaitedPersons, MSTransportableControl::boardAnyWaiting(), MSVehicle::Stop::busstop, MSVehicle::Stop::containerstop, MSVehicle::Stop::containerTriggered, DELTA_T, MSVehicle::Stop::duration, MSVehicle::Stop::edge, MSVehicle::Stop::endPos, MSStoppingPlace::enter(), MSStoppingPlace::getBeginLanePosition(), MSVehicle::getCarFollowModel(), MSNet::getContainerControl(), MSVehicle::getContainerNumber(), MSNet::getCurrentTimeStep(), MSLane::getEdge(), MSStoppingPlace::getEndLanePosition(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSStoppingPlace::getLastFreePos(), MSVehicleType::getLength(), MSVehicleType::getMinGap(), MSNet::getPersonControl(), MSVehicle::getPersonNumber(), MSVehicle::getSpeed(), MSDevice_Transportable::getTransportables(), MSNet::getVehicleControl(), MSBaseVehicle::getVehicleType(), MSNet::hasContainers(), MSNet::hasPersons(), MSNet::informVehicleStateListener(), MSVehicle::Stop::lane, MSTransportableControl::loadAnyWaiting(), MAX2(), MSVehicle::myAmRegisteredAsWaitingForContainer, MSVehicle::myAmRegisteredAsWaitingForPerson, MSVehicle::myContainerDevice, MSBaseVehicle::myCurrEdge, MSVehicle::myLane, MSVehicle::myPersonDevice, MSVehicle::myState, MSVehicle::myStops, MSBaseVehicle::myType, NUMERICAL_EPS, MSVehicle::State::pos(), MSVehicle::Stop::reached, MSVehicleControl::registerOneWaitingForContainer(), MSVehicleControl::registerOneWaitingForPerson(), MSStoppingPlace::removeTransportable(), MSVehicle::resumeFromStopping(), MSVehicle::Stop::startPos, STOPPING_PLACE_OFFSET, MSCFModel::stopSpeed(), SUMO_const_haltingSpeed, SUMOReal, MSVehicle::Stop::triggered, MSVehicleControl::unregisterOneWaitingForContainer(), MSVehicleControl::unregisterOneWaitingForPerson(), MSVehicle::Stop::until, MSNet::VEHICLE_STATE_STARTING_STOP, and WRITE_WARNING.
Referenced by MSVehicleTransfer::checkInsertions(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel::moveHelper(), and MSVehicle::nextStopDist().
void GUIBaseVehicle::removeActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) inherited
Adds the named visualisation feature to the given view.
Parameters
[in] parent The view for which the feature shall be enabled
[in] which The visualisation feature to enable
See also
GUISUMOAbstractView::removeAdditionalGLVisualisation
Definition at line 1137 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::myAdditionalVisualizations, and GUISUMOAbstractView::removeAdditionalGLVisualisation().
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), and GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack().
void MSVehicle::removeApproachingInformation (DriveItemVector & lfLinks) const protected inherited
unregister approach from all upcoming links
Definition at line 3207 of file MSVehicle.cpp.
References MSVehicle::getLaneChangeModel(), and MSAbstractLaneChangeModel::removeShadowApproachingInformation().
Referenced by MSVehicle::onRemovalFromNet(), MSVehicle::planMoveInternal(), and MSVehicle::~MSVehicle().
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 264 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
void MSBaseVehicle::removeReminder (MSMoveReminder * rem) inherited
Removes a MoveReminder dynamically.
Parameters
[in] rem the reminder to remove
See also
MSMoveReminder
Definition at line 323 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by MSBaseVehicle::getDevices().
bool MSVehicle::replaceRoute (const MSRoute * route, bool onInit = false, int offset = 0) virtual inherited
Replaces the current route by the given one.
It is possible that the new route is not accepted, if it does not contain the vehicle's current edge.
Parameters
[in] route The new route to pass
Returns
Whether the new route was accepted
Implements SUMOVehicle.
Definition at line 610 of file MSVehicle.cpp.
References MSRoute::addReference(), MSVehicle::addStop(), MSRoute::begin(), MSBaseVehicle::calculateArrivalParams(), MSRoute::contains(), MSLane::getEdge(), MSRoute::getEdges(), MSNet::getInstance(), MSLane::getOutgoingLanes(), MSRoute::getStops(), MSNet::informVehicleStateListener(), MSEdge::isInternal(), MSBaseVehicle::myCurrEdge, MSVehicle::myLane, MSVehicle::myLastBestLanesEdge, MSVehicle::myLastBestLanesInternalLane, MSBaseVehicle::myNumberReroutes, MSBaseVehicle::myRoute, MSVehicle::myStops, MSRoute::release(), MSVehicle::updateBestLanes(), MSNet::VEHICLE_STATE_NEWROUTE, and WRITE_WARNING.
Referenced by TraCIServerAPI_Vehicle::processSet().
bool MSBaseVehicle::replaceRouteEdges (ConstMSEdgeVector & edges, bool onInit = false, bool check = false) virtual inherited
Replaces the current route by the given edges.
It is possible that the new route is not accepted, if a) it does not contain the vehicle's current edge, or b) something fails on insertion into the routes container (see in-line comments).
Parameters
[in] edges The new list of edges to pass
[in] onInit Whether the vehicle starts with this route
[in] check Whether the route should be checked for validity
Returns
Whether the new route was accepted
Implements SUMOVehicle.
Definition at line 186 of file MSBaseVehicle.cpp.
References MSRoute::addReference(), MSRoute::begin(), MSBaseVehicle::calculateArrivalParams(), RGBColor::DEFAULT_COLOR, MSRoute::dictionary(), MSGlobals::gCheckRoutes, MSRoute::getColor(), MSRoute::getEdges(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getNumberReroutes(), MSBaseVehicle::getRerouteOrigin(), MSRoute::getStops(), MSBaseVehicle::hasValidRoute(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myRoute, MSRoute::release(), SUMOVehicle::replaceRoute(), MSRoute::size(), SUMOReal, toString(), and WRITE_WARNING.
Referenced by MSBaseVehicle::getCurrentRouteEdge(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Vehicle::processSet(), and MSBaseVehicle::reroute().
void MSVehicle::replaceVehicleType (MSVehicleType * type) inherited
Replaces the current vehicle type by the one given.
If the currently used vehicle type is marked as being used by this vehicle only, it is deleted, first. The new, given type is then assigned to "myType".
Parameters
[in] type The new vehicle type
See also
MSVehicle::myType
Definition at line 3088 of file MSVehicle.cpp.
References MSVehicleType::amVehicleSpecific(), and MSBaseVehicle::myType.
Referenced by TraCIServerAPI_Vehicle::processSet().
void MSBaseVehicle::reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > & router, const bool onInit = false, const bool withTaz = false) virtual inherited
Performs a rerouting using the given router.
Tries to find a new route between the current edge and the destination edge, first. Tries to replace the current route by the new one using replaceRoute.
Parameters
[in] t The time for which the route is computed
[in] router The router to use
See also
replaceRoute
Implements SUMOVehicle.
Definition at line 139 of file MSBaseVehicle.cpp.
References MSEdge::allowedLanes(), SUMOAbstractRouter< E, V >::compute(), MSEdge::dictionary(), MSEdge::EDGEFUNCTION_DISTRICT, SUMOVehicleParameter::fromTaz, Named::getID(), MSBaseVehicle::getID(), MSRoute::getLastEdge(), MSBaseVehicle::getRerouteOrigin(), MSBaseVehicle::getStopEdges(), MSBaseVehicle::getVClass(), MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, MSBaseVehicle::replaceRouteEdges(), SUMOVehicleParameter::toTaz, and SUMOVehicleParameter::via.
Referenced by MSBaseVehicle::getCurrentRouteEdge(), and TraCIServerAPI_Vehicle::processSet().
void MSVehicle::resetRoutePosition (int index) inherited
Definition at line 675 of file MSVehicle.cpp.
References MSRoute::begin(), MSRoute::end(), MSBaseVehicle::myArrivalPos, MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by MSCalibrator::execute().
bool MSVehicle::resumeFromStopping () inherited
resumes a vehicle from stopping
Returns
true on success, the resuming fails if the vehicle wasn't parking in the first place
Definition at line 3405 of file MSVehicle.cpp.
References MSLane::getEdge(), MSNet::getInstance(), MSNet::getVehicleControl(), MSNet::informVehicleStateListener(), MSVehicle::isStopped(), MSVehicle::myAmRegisteredAsWaitingForContainer, MSVehicle::myAmRegisteredAsWaitingForPerson, MSVehicle::myLane, MSVehicle::myStops, MSVehicle::myWaitingTime, MSVehicleControl::removeWaiting(), MSVehicleControl::unregisterOneWaitingForContainer(), MSVehicleControl::unregisterOneWaitingForPerson(), MSVehicle::updateBestLanes(), and MSNet::VEHICLE_STATE_ENDING_STOP.
Referenced by MSVehicle::leaveLane(), MSVehicle::processNextStop(), and MSVehicle::signalSet().
void MSVehicle::saveState (OutputDevice & out) virtual inherited
Saves the states of a vehicle.
Reimplemented from MSBaseVehicle.
Definition at line 3499 of file MSVehicle.cpp.
References MSRoute::begin(), OutputDevice::closeTag(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myDeparture, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSBaseVehicle::myRoute, MSVehicle::State::mySpeed, MSVehicle::myState, MSBaseVehicle::saveState(), SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_SPEED, SUMO_ATTR_STATE, toString(), and OutputDevice::writeAttr().
Referenced by MSVehicle::hasInfluencer().
void GUIVehicle::selectBlockingFoes () const virtual
adds the blocking foes to the current selection
Implements GUIBaseVehicle.
Definition at line 645 of file GUIVehicle.cpp.
References MSVehicle::getCarFollowModel(), GUIGlObject::getGlID(), MSBaseVehicle::getImpatience(), MSVehicle::getLaneChangeModel(), MSVehicle::getLateralPositionOnLane(), MSVehicle::DriveProcessItem::getLeaveSpeed(), MSVehicleType::getLength(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSLink::getParallelLink(), MSVehicle::getPositionOnLane(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), MSBaseVehicle::getVehicleType(), MSLink::getViaLaneOrLane(), MSVehicle::getWaitingTime(), MSLane::getWidth(), gSelected, MSLink::isLeader(), MSVehicle::DriveProcessItem::myArrivalSpeed, MSVehicle::DriveProcessItem::myArrivalTime, MSVehicle::myLane, MSVehicle::myLFLinkLanes, MSVehicle::DriveProcessItem::myLink, MSLink::opened(), GUISelectedStorage::select(), and SUMOReal.
Referenced by getAngle().
void MSVehicle::setAngle (SUMOReal angle) inherited
Set a custom vehicle angle in rad.
Definition at line 802 of file MSVehicle.cpp.
References MSVehicle::myAngle, and SUMOReal.
Referenced by MSVehicle::getAngle(), and MSVehicle::Influencer::postProcessVTD().
virtual void MSBaseVehicle::setArrivalPos (SUMOReal arrivalPos) inline virtual inherited
Sets this vehicle's desired arrivalPos for its current route.
Implements SUMOVehicle.
Definition at line 256 of file MSBaseVehicle.h.
References MSBaseVehicle::hasArrived(), MSBaseVehicle::hasDeparted(), and MSBaseVehicle::myArrivalPos.
void MSVehicle::setBlinkerInformation () protected inherited
Definition at line 3040 of file MSVehicle.cpp.
References MSVehicle::getBestLanesContinuation(), MSVehicle::getLane(), MSVehicle::getLaneChangeModel(), MSLane::getLength(), MSLane::getLinkCont(), MSAbstractLaneChangeModel::getOwnState(), MSVehicle::getPositionOnLane(), MSLane::getVehicleMaxSpeed(), LCA_LEFT, LCA_RIGHT, LCA_SUBLANE, LINKDIR_LEFT, LINKDIR_PARTLEFT, LINKDIR_PARTRIGHT, LINKDIR_RIGHT, LINKDIR_TURN, MSLane::succLinkSec(), SUMOReal, MSVehicle::switchOffSignal(), MSVehicle::switchOnSignal(), MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSVehicle::executeMove(), and MSVehicle::hasInfluencer().
void MSBaseVehicle::setChosenSpeedFactor (const SUMOReal factor) inline virtual inherited
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
Returns
Speed limit factor
Implements SUMOVehicle.
Definition at line 347 of file MSBaseVehicle.h.
References MSBaseVehicle::addStops(), MSBaseVehicle::calculateArrivalParams(), MSBaseVehicle::getDevice(), MSBaseVehicle::getStopEdges(), MSBaseVehicle::myChosenSpeedFactor, and MSBaseVehicle::saveState().
Referenced by TraCIServerAPI_Vehicle::processSet().
void GUIBaseVehicle::setColor (const GUIVisualizationSettings & s) const protected inherited
sets the color according to the currente settings
Definition at line 1032 of file GUIBaseVehicle.cpp.
References GUIPropertySchemeStorage< T >::getActive(), GUIPropertyScheme< T >::getColor(), GUIBaseVehicle::getColorValue(), GUIPropertySchemeStorage< T >::getScheme(), GUIBaseVehicle::myVehicle, GLHelper::setColor(), GUIBaseVehicle::setFunctionalColor(), and GUIVisualizationSettings::vehicleColorer.
Referenced by GUIBaseVehicle::drawOnPos(), and GUIBaseVehicle::drawRoute().
void MSVehicle::setEmergencyBlueLight (SUMOTime currentTime) protected inherited
sets the blue flashing light for emergency vehicles
Definition at line 3076 of file MSVehicle.cpp.
References MSVehicle::signalSet(), MSVehicle::switchOffSignal(), MSVehicle::switchOnSignal(), and MSVehicle::VEH_SIGNAL_EMERGENCY_BLUE.
Referenced by MSVehicle::executeMove(), and MSVehicle::hasInfluencer().
bool GUIBaseVehicle::setFunctionalColor (int activeScheme, const MSBaseVehicle * veh) static inherited
sets the color according to the current scheme index and some vehicle function
Definition at line 1041 of file GUIBaseVehicle.cpp.
References SUMOVehicleParameter::color, RGBColor::DEFAULT_COLOR, Position::distanceTo(), RGBColor::fromHSV(), Boundary::getCenter(), MSRoute::getColor(), MSVehicleType::getColor(), MSRoute::getEdges(), MSNet::getInstance(), MSBaseVehicle::getParameter(), MSBaseVehicle::getRoute(), MSBaseVehicle::getVehicleType(), PI, GLHelper::setColor(), SUMOReal, VEHPARS_COLOR_SET, VTYPEPARS_COLOR_SET, MSVehicleType::wasSet(), SUMOVehicleParameter::wasSet(), Position::x(), Boundary::xmax(), Boundary::xmin(), Position::y(), Boundary::ymax(), and Boundary::ymin().
Referenced by GUIBaseVehicle::setColor().
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 143 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNENet::renameJunction(), GNEAdditional::setAdditionalID(), GNELane::setIndex(), and GNEEdge::setMicrosimID().
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 273 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
void MSVehicle::setTentativeLaneAndPosition (MSLane * lane, SUMOReal pos, SUMOReal posLat = 0) inherited
set tentative lane and position during insertion to ensure that all cfmodels work (some of them require veh->getLane() to return a valid lane) Once the vehicle is sucessfully inserted the lane is set again (see enterLaneAtInsertion)
Definition at line 3103 of file MSVehicle.cpp.
References MSVehicleType::getLength(), MSBaseVehicle::getVehicleType(), MSVehicle::State::myBackPos, MSVehicle::myLane, MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSVehicle::myState, and SUMOReal.
Referenced by MSVehicle::congested(), MSLane::isInsertionSuccess(), and TraCIServerAPI_Vehicle::processSet().
void MSVehicle::setVTDState (Position xyPos) inherited
sets position outside the road network
Definition at line 3485 of file MSVehicle.cpp.
References MSVehicle::myCachedPosition.
Referenced by MSVehicle::hasInfluencer(), and MSVehicle::Influencer::postProcessVTD().
bool MSVehicle::signalSet (int which) const inline inherited
Returns whether the given signal is on.
Parameters
[in] signal The signal to return the value of
Returns
Whether the given signal is on
Definition at line 1020 of file MSVehicle.h.
References MSVehicle::addTraciBusOrContainerStop(), MSVehicle::addTraciStop(), MSVehicle::getBoundingBox(), MSVehicle::getBoundingPoly(), MSVehicle::getNextStop(), MSVehicle::getSpeedWithoutTraciInfluence(), MSVehicle::mySignals, MSVehicle::resumeFromStopping(), SUMOReal, MSVehicle::unsafeLinkAhead(), and MSVehicle::updateFurtherLanes().
Referenced by MSVehicle::checkRewindLinkLanes(), drawAction_drawVehicleBlinker(), drawAction_drawVehicleBlueLight(), drawAction_drawVehicleBrakeLight(), and MSVehicle::setEmergencyBlueLight().
const MSEdge * MSBaseVehicle::succEdge (int nSuccs) const virtual inherited
Returns the nSuccs'th successor of edge the vehicle is currently at.
If the rest of the route (counted from the current edge) has less than nSuccs edges, 0 is returned.
Parameters
[in] nSuccs The number of edge to look forward
Returns
The nSuccs'th following edge in the vehicle's route
Implements SUMOVehicle.
Definition at line 123 of file MSBaseVehicle.cpp.
References MSRoute::begin(), MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by MSVehicleTransfer::add(), MSLane::appropriate(), MSVehicleTransfer::checkInsertions(), MESegment::getLink(), MSBaseVehicle::getVClass(), MSBaseVehicle::hasArrived(), MSPedestrianPushButton::isActiveForEdge(), MELoop::nextSegment(), TraCIServerAPI_Vehicle::processSet(), and MESegment::receive().
void MSVehicle::switchOffSignal (int signal) inline inherited
Switches the given signal off.
Parameters
[in] signal The signal to mark as being switched off
Definition at line 1003 of file MSVehicle.h.
References MSVehicle::mySignals.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSVehicle::executeMove(), TraCIServerAPI_Vehicle::processSet(), MSVehicle::setBlinkerInformation(), MSVehicle::setEmergencyBlueLight(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
void MSVehicle::switchOnSignal (int signal) inline inherited
Switches the given signal on.
Parameters
[in] signal The signal to mark as being switched on
Definition at line 995 of file MSVehicle.h.
References MSVehicle::mySignals.
Referenced by MSVehicle::executeMove(), TraCIServerAPI_Vehicle::processSet(), MSVehicle::setBlinkerInformation(), MSVehicle::setEmergencyBlueLight(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
bool MSVehicle::unsafeLinkAhead (const MSLane * lane) const inherited
whether the vehicle may safely move to the given lane with regard to upcoming links
Definition at line 3219 of file MSVehicle.cpp.
References MSCFModel::brakeGap(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSLane::getEdge(), MSVehicleType::getLength(), MSLane::getLength(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSEdge::isInternal(), MSLane::isLinkEnd(), LINKSTATE_ZIPPER, MSVehicle::myLane, MSVehicle::myLFLinkLanes, MSLane::succLinkSec(), SUMOReal, and MSLink::ZIPPER_ADAPT_DIST.
Referenced by MSLaneChanger::checkChange(), and MSVehicle::signalSet().
void MSVehicle::updateBestLanes (bool forceRebuild = false, const MSLane * startLane = 0) inherited
computes the best lanes to use in order to continue the route
The information is rebuilt if the vehicle is on a different edge than the one stored in "myLastBestLanesEdge" or "forceRebuild" is true.
Otherwise, only the density changes on the stored lanes are adapted to the container only.
A rebuild must be done if the vehicle leaves a stop; then, another lane may become the best one.
If no starting lane ("startLane") is given, the vehicle's current lane ("myLane") is used as start of bect lanes building.
Parameters
[in] forceRebuild Whether the best lanes container shall be rebuilt even if the vehicle's edge has not changed
[in] startLane The lane the process shall start at ("myLane" will be used if ==0)
Definition at line 2480 of file MSVehicle.cpp.
References abs, MSEdge::allowedLanes(), MSVehicle::LaneQ::allowsContinuation, MSLane::allowsVehicleClass(), ARRIVAL_LANE_GIVEN, SUMOVehicleParameter::arrivalLaneProcedure, MSVehicle::LaneQ::bestContinuations, MSVehicle::LaneQ::bestLaneOffset, bla, MSEdge::clear(), MSVehicle::LaneQ::currentLength, DEBUG_COND, MSEdge::EDGEFUNCTION_INTERNAL, MSRoute::end(), gDebugSelectedVehicle, MSVehicle::getBestLanesContinuation(), MSLane::getEdge(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), MSLane::getInternalFollower(), MSVehicle::getLaneChangeModel(), MSEdge::getLanes(), MSLane::getLength(), MSEdge::getLength(), MSLane::getLinkCont(), MSLane::getLogicalPredecessorLane(), MSEdge::getPurpose(), MSVehicleType::getVehicleClass(), MSVehicle::LaneQ::lane, MSVehicle::Stop::lane, MSVehicle::LaneQ::length, MAX2(), MIN2(), MSBaseVehicle::myArrivalLane, MSBaseVehicle::myArrivalPos, MSVehicle::myBestLanes, MSBaseVehicle::myCurrEdge, MSVehicle::myCurrentLaneInBestLanes, MSVehicle::myLane, MSVehicle::myLastBestLanesEdge, MSVehicle::myLastBestLanesInternalLane, MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, MSVehicle::myStops, MSBaseVehicle::myType, MSVehicle::nextLinkPriority(), MSVehicle::LaneQ::nextOccupation, MSVehicle::LaneQ::occupation, POSITION_EPS, SIMTIME, MSVehicle::Stop::startPos, SUMOReal, toString(), and MSVehicle::updateOccupancyAndCurrentBestLane().
Referenced by MSVehicle::addTraciBusOrContainerStop(), MSVehicle::addTraciStop(), MSLaneChangerSublane::change(), MSLaneChanger::change(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::executeMove(), MSLane::forceVehicleInsertion(), MSEdge::getDepartLane(), MSLane::isInsertionSuccess(), MSLane::loadState(), MSVehicle::Influencer::postProcessVTD(), MSVehicle::replaceRoute(), and MSVehicle::resumeFromStopping().
SUMOReal MSVehicle::updateFurtherLanes (std::vector< MSLane * > & furtherLanes, std::vector< SUMOReal > & furtherLanesPosLat, const std::vector< MSLane * > & passedLanes) inherited
update a vector of further lanes and return the new backPos
Definition at line 1911 of file MSVehicle.cpp.
References DEBUG_COND, MSVehicleType::getLength(), MSBaseVehicle::getVehicleType(), MSVehicle::State::myPos, MSVehicle::State::myPosLat, MSVehicle::myState, SIMTIME, SUMOReal, and toString().
Referenced by MSVehicle::executeMove(), MSVehicle::signalSet(), and MSAbstractLaneChangeModel::updateShadowLane().
void MSVehicle::updateOccupancyAndCurrentBestLane (const MSLane * startLane) protected inherited
updates LaneQ::nextOccupation and myCurrentLaneInBestLanes
Definition at line 2791 of file MSVehicle.cpp.
References MSVehicle::myBestLanes, MSVehicle::myCurrentLaneInBestLanes, and SUMOReal.
Referenced by MSVehicle::hasInfluencer(), and MSVehicle::updateBestLanes().
bool MSVehicle::willPass (const MSEdge *const edge) const inherited
Returns whether the vehicle wil pass the given edge.
Parameters
[in] The edge to find in the vehicle's current route
Returns
Whether the given edge will be passed by the vehicle
Todo:
Move to MSRoute?
Definition at line 663 of file MSVehicle.cpp.
References MSRoute::end(), MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by TraCIServerAPI_Vehicle::processSet().
void MSVehicle::workOnMoveReminders (SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed) inherited
Processes active move reminder.
This method goes through all active move reminder, both those for the current lane, stored in "myMoveReminders" and those of prior lanes stored in "myOldLaneMoveReminders" calling "MSMoveReminder::notifyMove".
When processing move reminder from "myOldLaneMoveReminders", the offsets (prior lane lengths) are used, which are stored in "myOldLaneMoveReminderOffsets".
Each move reminder which is no longer active is removed from the container.
Parameters
[in] oldPos The position the vehicle had before it has moved
[in] newPos The position the vehicle has after it has moved
[in] newSpeed The vehicle's speed within this move
See also
MSMoveReminder
Definition at line 706 of file MSVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by MSVehicle::executeMove(), MSLane::executeMovements(), and MSVehicle::onRemovalFromNet().
Field Documentation
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 77 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
SUMOReal MSVehicle::myAcceleration protected inherited
The current acceleration after dawdling in m/s.
Definition at line 1404 of file MSVehicle.h.
Referenced by MSVehicle::executeMove(), MSVehicle::getAcceleration(), MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHCEmissions(), MSVehicle::getNOxEmissions(), and MSVehicle::getPMxEmissions().
std::map<GUISUMOAbstractView*, int> GUIBaseVehicle::myAdditionalVisualizations inherited
Enabled visualisations, per view.
Definition at line 302 of file GUIBaseVehicle.h.
Referenced by GUIBaseVehicle::addActiveAddVisualisation(), GUIBaseVehicle::getPopUpMenu(), GUIBaseVehicle::hasActiveAddVisualisation(), GUIBaseVehicle::removeActiveAddVisualisation(), and GUIBaseVehicle::~GUIBaseVehicle().
bool MSVehicle::myAmOnNet protected inherited
Whether the vehicle is on the network (not parking, teleported, vaporized, or arrived)
Definition at line 1414 of file MSVehicle.h.
Referenced by MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), MSVehicle::isOnRoad(), and MSVehicle::leaveLane().
bool MSVehicle::myAmRegisteredAsWaitingForContainer protected inherited
Whether this vehicle is registered as waiting for a container (for deadlock-recognition)
Definition at line 1420 of file MSVehicle.h.
Referenced by MSVehicle::processNextStop(), and MSVehicle::resumeFromStopping().
bool MSVehicle::myAmRegisteredAsWaitingForPerson protected inherited
Whether this vehicle is registered as waiting for a person (for deadlock-recognition)
Definition at line 1417 of file MSVehicle.h.
Referenced by MSVehicle::processNextStop(), and MSVehicle::resumeFromStopping().
SUMOReal MSVehicle::myAngle protected inherited
the angle (
Todo:
consider moving this into myState)
Definition at line 1425 of file MSVehicle.h.
Referenced by MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::executeMove(), MSVehicle::getAngle(), and MSVehicle::setAngle().
int MSBaseVehicle::myArrivalLane protected inherited
The destination lane where the vehicle stops.
Definition at line 422 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), and MSVehicle::updateBestLanes().
SUMOReal MSBaseVehicle::myArrivalPos protected inherited
The position on the destination lane where the vehicle stops.
Definition at line 419 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), MSBaseVehicle::getArrivalPos(), MEVehicle::hasArrived(), MSVehicle::hasArrived(), MSVehicle::planMoveInternal(), MSVehicle::resetRoutePosition(), MSBaseVehicle::setArrivalPos(), and MSVehicle::updateBestLanes().
std::vector<std::vector<LaneQ> > MSVehicle::myBestLanes protected inherited
Definition at line 1389 of file MSVehicle.h.
Referenced by MSVehicle::adaptBestLanesOccupation(), drawBestLanes(), MSVehicle::getBestLaneOffset(), MSVehicle::getBestLanes(), MSVehicle::getBestLanesContinuation(), MSVehicle::updateBestLanes(), and MSVehicle::updateOccupancyAndCurrentBestLane().
Position MSVehicle::myCachedPosition mutable protected inherited
Definition at line 1430 of file MSVehicle.h.
Referenced by MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), MSVehicle::executeMove(), MSVehicle::getPosition(), MSVehicle::setVTDState(), and MSLaneChangerSublane::startChangeSublane().
SUMOReal GUIBaseVehicle::myCarriageLength mutable protected inherited
Variable to set with the length of the last drawn carriage or the vehicle length.
Definition at line 347 of file GUIBaseVehicle.h.
Referenced by GUIBaseVehicle::drawOnPos().
SUMOReal MSBaseVehicle::myChosenSpeedFactor protected inherited
A precomputed factor by which the driver wants to be faster than the speed limit.
Definition at line 396 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getChosenSpeedFactor(), and MSBaseVehicle::setChosenSpeedFactor().
MSDevice_Transportable* MSVehicle::myContainerDevice protected inherited
The containers this vehicle may have.
Definition at line 1401 of file MSVehicle.h.
Referenced by MSVehicle::addContainer(), drawAction_drawPersonsAndContainers(), MSVehicle::getContainerNumber(), MSVehicle::getContainers(), and MSVehicle::processNextStop().
MSRouteIterator MSBaseVehicle::myCurrEdge protected inherited
Iterator to current route-edge.
Definition at line 393 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSVehicle::enterLaneAtMove(), MSVehicle::executeMove(), MSBaseVehicle::getCurrentRouteEdge(), MSVehicle::getDistanceToPosition(), MSBaseVehicle::getEdge(), MSBaseVehicle::getRerouteOrigin(), MSVehicle::getRerouteOrigin(), MSVehicle::getRoutePosition(), MEVehicle::hasArrived(), MSVehicle::hasArrived(), MSBaseVehicle::hasValidRoute(), MSVehicle::leaveLane(), MEVehicle::loadState(), MSVehicle::loadState(), MEVehicle::moveRoutePointer(), MSVehicle::planMoveInternal(), MSVehicle::Influencer::postProcessVTD(), MSVehicle::processNextStop(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), MSVehicle::resetRoutePosition(), MEVehicle::saveState(), MSVehicle::saveState(), MSBaseVehicle::succEdge(), MSVehicle::updateBestLanes(), and MSVehicle::willPass().
std::vector<LaneQ>::iterator MSVehicle::myCurrentLaneInBestLanes protected inherited
Definition at line 1390 of file MSVehicle.h.
Referenced by MSVehicle::updateBestLanes(), and MSVehicle::updateOccupancyAndCurrentBestLane().
SUMOReal MSBaseVehicle::myDepartPos protected inherited
The real depart position.
Definition at line 416 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getDepartPos(), and MSBaseVehicle::onDepart().
SUMOTime MSBaseVehicle::myDeparture protected inherited
The real departure time.
Definition at line 413 of file MSBaseVehicle.h.
Referenced by MSVehicle::enterLaneAtInsertion(), MSBaseVehicle::getDeparture(), MSBaseVehicle::hasDeparted(), MEVehicle::loadState(), MSVehicle::loadState(), MSBaseVehicle::onDepart(), MEVehicle::saveState(), and MSVehicle::saveState().
std::vector<MSDevice*> MSBaseVehicle::myDevices protected inherited
The devices this vehicle has.
Definition at line 410 of file MSBaseVehicle.h.
Referenced by MSVehicle::addContainer(), MSVehicle::addPerson(), MSBaseVehicle::getDevice(), MSBaseVehicle::getDevices(), GUIMEVehicle::getParameterWindow(), getParameterWindow(), GUIBaseVehicle::GUIBaseVehicle(), MSBaseVehicle::MSBaseVehicle(), and MSBaseVehicle::~MSBaseVehicle().
std::vector< MSLane * > MSVehicle::myEmptyLaneVector static protected inherited
Definition at line 1391 of file MSVehicle.h.
Referenced by MSVehicle::getBestLanesContinuation().
std::vector< MSTransportable * > MSVehicle::myEmptyTransportableVector static protected inherited
Definition at line 1392 of file MSVehicle.h.
Referenced by MSVehicle::getContainers(), and MSVehicle::getPersons().
std::vector<MSLane*> MSVehicle::myFurtherLanes protected inherited
The information into which lanes the vehicle laps into.
Definition at line 1407 of file MSVehicle.h.
Referenced by MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::executeMove(), MSVehicle::getBackLane(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSVehicle::getFurtherLanes(), MSVehicle::getLatOffset(), getPreviousLane(), MSVehicle::leaveLane(), and MSVehicle::~MSVehicle().
std::vector<SUMOReal> MSVehicle::myFurtherLanesPosLat protected inherited
Definition at line 1408 of file MSVehicle.h.
Referenced by MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::executeMove(), MSVehicle::getBackPosition(), MSVehicle::getCenterOnEdge(), MSVehicle::getFurtherLanesPosLat(), MSVehicle::getLatOffset(), MSVehicle::leaveLane(), and MSVehicle::~MSVehicle().
bool MSVehicle::myHaveToWaitOnNextLink protected inherited
Definition at line 1422 of file MSVehicle.h.
Referenced by MSVehicle::checkRewindLinkLanes(), and MSVehicle::executeMove().
MSLane* MSVehicle::myLane protected inherited
The lane the vehicle is on.
Definition at line 1382 of file MSVehicle.h.
Referenced by MSVehicle::adaptLaneEntering2MoveReminder(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), MSVehicle::addTraciBusOrContainerStop(), MSVehicle::addTraciStop(), MSVehicle::checkRewindLinkLanes(), MSVehicle::computeAngle(), drawAction_drawRailCarriages(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), MSVehicle::executeMove(), MSVehicle::getBackLane(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSVehicle::getDistanceToPosition(), MSVehicle::getLane(), MSVehicle::getLaneIndex(), MSVehicle::getLateralOverlap(), MSVehicle::getLatOffset(), MSVehicle::getLeader(), getParameterWindow(), MSVehicle::getPosition(), MSVehicle::getRerouteOrigin(), MSVehicle::getRightSideOnLane(), MSVehicle::getSlope(), MSVehicle::influenceChangeDecision(), MSVehicle::isFrontOnLane(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSVehicle::processNextStop(), MSVehicle::replaceRoute(), MSVehicle::resumeFromStopping(), selectBlockingFoes(), MSVehicle::setTentativeLaneAndPosition(), MSVehicle::unsafeLinkAhead(), and MSVehicle::updateBestLanes().
MSAbstractLaneChangeModel* MSVehicle::myLaneChangeModel protected inherited
Definition at line 1384 of file MSVehicle.h.
Referenced by MSVehicle::enterLaneAtLaneChange(), MSVehicle::getLaneChangeModel(), MSVehicle::MSVehicle(), and MSVehicle::~MSVehicle().
const MSEdge* MSVehicle::myLastBestLanesEdge protected inherited
Definition at line 1386 of file MSVehicle.h.
Referenced by MSVehicle::enterLaneAtMove(), MSVehicle::replaceRoute(), and MSVehicle::updateBestLanes().
const MSLane* MSVehicle::myLastBestLanesInternalLane protected inherited
Definition at line 1387 of file MSVehicle.h.
Referenced by MSVehicle::replaceRoute(), and MSVehicle::updateBestLanes().
DriveItemVector MSVehicle::myLFLinkLanes protected inherited
Definition at line 1487 of file MSVehicle.h.
Referenced by drawAction_drawLinkItems(), MSVehicle::executeMove(), MSVehicle::onRemovalFromNet(), MSVehicle::planMove(), selectBlockingFoes(), MSVehicle::unsafeLinkAhead(), and MSVehicle::~MSVehicle().
MFXMutex GUIBaseVehicle::myLock mutable protected inherited
The mutex used to avoid concurrent updates of the vehicle buffer.
Definition at line 344 of file GUIBaseVehicle.h.
Referenced by drawBestLanes(), and GUIBaseVehicle::~GUIBaseVehicle().
MoveReminderCont MSBaseVehicle::myMoveReminders protected inherited
Current lane's move reminder.
Definition at line 406 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::activateReminders(), MSVehicle::activateReminders(), MSVehicle::adaptLaneEntering2MoveReminder(), MSVehicle::addContainer(), MSVehicle::addPerson(), MSBaseVehicle::addReminder(), GUIBaseVehicle::GUIBaseVehicle(), MSVehicle::leaveLane(), MSBaseVehicle::MSBaseVehicle(), MSBaseVehicle::removeReminder(), MEVehicle::updateDetectorForWriting(), MEVehicle::updateDetectors(), and MSVehicle::workOnMoveReminders().
int MSBaseVehicle::myNumberReroutes protected inherited
The number of reroutings.
Definition at line 425 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getNumberReroutes(), MSVehicle::replaceRoute(), and MEVehicle::replaceRoute().
const SUMOVehicleParameter* MSBaseVehicle::myParameter protected inherited
This Vehicle's parameter.
Definition at line 384 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSBaseVehicle::addStops(), MSBaseVehicle::calculateArrivalParams(), MSVehicle::getContainerNumber(), MSBaseVehicle::getID(), MSBaseVehicle::getParameter(), GUIMEVehicle::getParameterWindow(), getParameterWindow(), MSVehicle::getPersonNumber(), MSVehicle::planMoveInternal(), MSBaseVehicle::reroute(), MSBaseVehicle::saveState(), MSVehicle::updateBestLanes(), and MSBaseVehicle::~MSBaseVehicle().
MSDevice_Transportable* MSVehicle::myPersonDevice protected inherited
The passengers this vehicle may have.
Definition at line 1398 of file MSVehicle.h.
Referenced by MSVehicle::addPerson(), drawAction_drawPersonsAndContainers(), getNumPassengers(), MSVehicle::getPersonNumber(), MSVehicle::getPersons(), and MSVehicle::processNextStop().
const MSRoute* MSBaseVehicle::myRoute protected inherited
This Vehicle's route.
Definition at line 387 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSBaseVehicle::addStops(), MSBaseVehicle::calculateArrivalParams(), drawRouteHelper(), MSVehicle::executeMove(), MSVehicle::getDistanceToPosition(), MSVehicle::getRerouteOrigin(), MSBaseVehicle::getRoute(), MSVehicle::getRoutePosition(), MEVehicle::hasArrived(), MSVehicle::hasArrived(), MSBaseVehicle::hasValidRoute(), MEVehicle::moveRoutePointer(), MSBaseVehicle::MSBaseVehicle(), MSVehicle::planMoveInternal(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), MSBaseVehicle::reroute(), MSVehicle::resetRoutePosition(), MEVehicle::saveState(), MSBaseVehicle::saveState(), MSVehicle::saveState(), MSBaseVehicle::succEdge(), MSVehicle::updateBestLanes(), MSVehicle::willPass(), and MSBaseVehicle::~MSBaseVehicle().
PositionVector GUIBaseVehicle::mySeatPositions mutable protected inherited
positions of seats in the vehicle (updated at every drawing step)
Definition at line 350 of file GUIBaseVehicle.h.
Referenced by computeSeats(), drawAction_drawRailCarriages(), GUIBaseVehicle::drawOnPos(), GUIBaseVehicle::getSeatPosition(), and GUIBaseVehicle::GUIBaseVehicle().
int MSVehicle::mySignals protected inherited
State of things of the vehicle that can be on or off.
Definition at line 1411 of file MSVehicle.h.
Referenced by MSVehicle::getSignals(), MSVehicle::signalSet(), MSVehicle::switchOffSignal(), and MSVehicle::switchOnSignal().
State MSVehicle::myState protected inherited
This Vehicles driving state (pos and speed)
Definition at line 1379 of file MSVehicle.h.
Referenced by MSVehicle::adaptToLeaders(), MSVehicle::addStop(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSVehicle::checkRewindLinkLanes(), MSVehicle::computeAngle(), MSVehicle::congested(), MSLaneChanger::continueChange(), drawAction_drawRailCarriages(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), MSVehicle::executeMove(), MSVehicle::fixPosition(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHCEmissions(), MSVehicle::getLateralPositionOnLane(), MSVehicle::getLatOffset(), MSVehicle::getNOxEmissions(), MSVehicle::getPMxEmissions(), MSVehicle::getPosition(), MSVehicle::getPositionOnLane(), MSVehicle::getRerouteOrigin(), MSVehicle::getRightSideOnLane(), MSVehicle::getSpeed(), MSVehicle::getSpeedWithoutTraciInfluence(), MSVehicle::hasArrived(), MSVehicle::leaveLane(), MSVehicle::loadState(), MSVehicle::onRemovalFromNet(), MSVehicle::overlap(), MSVehicle::planMoveInternal(), MSVehicle::processNextStop(), MSVehicle::saveState(), MSVehicle::setTentativeLaneAndPosition(), MSLaneChangerSublane::startChangeSublane(), and MSVehicle::updateFurtherLanes().
SUMOReal MSVehicle::myStopDist protected inherited
distance to the next stop or -1 if there is none
Definition at line 1428 of file MSVehicle.h.
Referenced by MSVehicle::nextStopDist(), and MSVehicle::planMove().
std::list<Stop> MSVehicle::myStops protected inherited
The vehicle's list of stops.
Definition at line 1395 of file MSVehicle.h.
Referenced by MSVehicle::addContainer(), MSVehicle::addPerson(), MSVehicle::addStop(), MSVehicle::addTraciBusOrContainerStop(), MSVehicle::addTraciStop(), MSVehicle::getNextStop(), MSVehicle::getStopEdges(), getStopInfo(), MSVehicle::hasArrived(), MSVehicle::hasStops(), MSVehicle::isParking(), MSVehicle::isStopped(), MSVehicle::isStoppedInRange(), MSVehicle::isStoppedTriggered(), MSVehicle::leaveLane(), MSVehicle::planMoveInternal(), MSVehicle::processNextStop(), MSVehicle::replaceRoute(), MSVehicle::resumeFromStopping(), and MSVehicle::updateBestLanes().
const MSVehicleType* MSBaseVehicle::myType protected inherited
This Vehicle's type.
Definition at line 390 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSBaseVehicle::calculateArrivalParams(), MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getBoundingBox(), MSVehicle::getBoundingPoly(), MSVehicle::getCarFollowModel(), MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHCEmissions(), MSBaseVehicle::getMaxSpeed(), MSVehicle::getNOxEmissions(), MSVehicle::getPMxEmissions(), MSVehicle::getPositionOnLane(), GUIMEVehicle::getTypeParameterWindow(), getTypeParameterWindow(), MSBaseVehicle::getVClass(), MSBaseVehicle::getVehicleType(), MSBaseVehicle::hasValidRoute(), MSVehicle::processNextStop(), MSVehicle::replaceVehicleType(), MSBaseVehicle::saveState(), MSVehicle::updateBestLanes(), and MSVehicle::~MSVehicle().
SUMOTime MSVehicle::myWaitingTime protected inherited
The time the vehicle waits (is not faster than 0.1m/s) in seconds.
Definition at line 1372 of file MSVehicle.h.
Referenced by MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), MSVehicle::getWaitingSeconds(), MSVehicle::getWaitingTime(), and MSVehicle::resumeFromStopping().
WaitingTimeCollector MSVehicle::myWaitingTimeCollector protected inherited
Definition at line 1376 of file MSVehicle.h.
Referenced by MSVehicle::executeMove(), and MSVehicle::getAccumulatedWaitingTime().
const SUMOTime MSBaseVehicle::NOT_YET_DEPARTED = SUMOTime_MAX static protected inherited
Definition at line 430 of file MSBaseVehicle.h.
Referenced by MSVehicle::enterLaneAtInsertion(), and MSBaseVehicle::hasDeparted().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 76 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUIVehicle.h
GUIVehicle.cpp