SUMO - Simulation of Urban MObility: GNEInspectorFrame::AttrInput Class Reference
GNEInspectorFrame::AttrInput Class Reference
FOX-declaration.
#include <GNEInspectorFrame.h>
Public Member Functions
AttrInput (FXComposite *parent, GNEInspectorFrame *inspectorFrameParent)
FOX-declaration.
SumoXMLAttr getAttr () const
get current Attr
SumoXMLTag getTag () const
get current tag
void hiddeAttribute ()
show attribute
long onCmdOpenAttributeEditor (FXObject *, FXSelector, void *)
open model dialog for more comfortable attribute editing
long onCmdSetAttribute (FXObject *, FXSelector, void *)
try to set new attribute value
void showAttribute (SumoXMLTag tag, SumoXMLAttr attr, const std::string &value)
show attribute
Protected Member Functions
AttrInput ()
FOX needs this.
Private Member Functions
void hide ()
set hide as private function
void show ()
set show as private function
Private Attributes
SumoXMLAttr myAttr
current Attr
FXButton * myButtonCombinableChoices
pointer to buttonCombinableChoices
FXCheckButton * myCheckBox
pointer to checkBox
FXComboBox * myChoicesCombo
pointer to combo box choices
GNEInspectorFrame * myInspectorFrameParent
pointer to GNEInspectorFrame parent
FXLabel * myLabel
pointer to label
SumoXMLTag myTag
current tag
FXTextField * myTextFieldInt
textField to modify the value of int values
FXTextField * myTextFieldReal
textField to modify the value of real values
FXTextField * myTextFieldStrings
textField to modify the value of strings values
Detailed Description
FOX-declaration.
Definition at line 60 of file GNEInspectorFrame.h.
Constructor & Destructor Documentation
GNEInspectorFrame::AttrInput::AttrInput (FXComposite * parent, GNEInspectorFrame * inspectorFrameParent)
FOX-declaration.
constructor
Definition at line 327 of file GNEInspectorFrame.cpp.
References MID_GNE_OPEN_ATTRIBUTE_EDITOR, MID_GNE_SET_ATTRIBUTE, myButtonCombinableChoices, myCheckBox, myChoicesCombo, myLabel, myTextFieldInt, myTextFieldReal, and myTextFieldStrings.
GNEInspectorFrame::AttrInput::AttrInput () inline protected
FOX needs this.
Definition at line 88 of file GNEInspectorFrame.h.
Member Function Documentation
SumoXMLAttr GNEInspectorFrame::AttrInput::getAttr () const
get current Attr
Definition at line 440 of file GNEInspectorFrame.cpp.
References myAttr.
Referenced by GNEInspectorFrame::AttrEditor::AttrEditor(), and GNEInspectorFrame::AttrEditor::onCmdReset().
SumoXMLTag GNEInspectorFrame::AttrInput::getTag () const
get current tag
Definition at line 434 of file GNEInspectorFrame.cpp.
References myTag.
Referenced by GNEInspectorFrame::AttrEditor::AttrEditor(), and GNEInspectorFrame::AttrEditor::onCmdReset().
void GNEInspectorFrame::AttrInput::hiddeAttribute ()
show attribute
Definition at line 419 of file GNEInspectorFrame.cpp.
References hide(), myButtonCombinableChoices, myCheckBox, myChoicesCombo, myLabel, myTextFieldInt, myTextFieldReal, and myTextFieldStrings.
void GNEInspectorFrame::AttrInput::hide () private
set hide as private function
Definition at line 534 of file GNEInspectorFrame.cpp.
Referenced by hiddeAttribute().
long GNEInspectorFrame::AttrInput::onCmdOpenAttributeEditor (FXObject * , FXSelector , void *)
open model dialog for more comfortable attribute editing
Definition at line 446 of file GNEInspectorFrame.cpp.
References myTextFieldStrings.
long GNEInspectorFrame::AttrInput::onCmdSetAttribute (FXObject * , FXSelector , void *)
try to set new attribute value
Definition at line 454 of file GNEInspectorFrame.cpp.
References GNEAttributeCarrier::discreteChoices(), GNEAttributeCarrier::discreteCombinableChoices(), GNEInspectorFrame::getACs(), GNEViewNet::getUndoList(), GNEFrame::getViewNet(), GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isDiscrete(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isString(), myAttr, myCheckBox, myChoicesCombo, myInspectorFrameParent, myTag, myTextFieldInt, myTextFieldReal, myTextFieldStrings, GNEUndoList::p_begin(), and GNEUndoList::p_end().
Referenced by GNEInspectorFrame::AttrEditor::AttrEditor().
void GNEInspectorFrame::AttrInput::show () private
set show as private function
Definition at line 528 of file GNEInspectorFrame.cpp.
Referenced by showAttribute().
void GNEInspectorFrame::AttrInput::showAttribute (SumoXMLTag tag, SumoXMLAttr attr, const std::string & value)
show attribute
Definition at line 357 of file GNEInspectorFrame.cpp.
References GNEAttributeCarrier::discreteChoices(), GNEAttributeCarrier::discreteCombinableChoices(), GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isDiscrete(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), myAttr, myButtonCombinableChoices, myCheckBox, myChoicesCombo, myLabel, myTag, myTextFieldInt, myTextFieldReal, myTextFieldStrings, show(), and toString().
Field Documentation
SumoXMLAttr GNEInspectorFrame::AttrInput::myAttr private
current Attr
Definition at line 98 of file GNEInspectorFrame.h.
Referenced by getAttr(), onCmdSetAttribute(), and showAttribute().
FXButton* GNEInspectorFrame::AttrInput::myButtonCombinableChoices private
pointer to buttonCombinableChoices
Definition at line 119 of file GNEInspectorFrame.h.
Referenced by AttrInput(), hiddeAttribute(), and showAttribute().
FXCheckButton* GNEInspectorFrame::AttrInput::myCheckBox private
pointer to checkBox
Definition at line 116 of file GNEInspectorFrame.h.
Referenced by AttrInput(), hiddeAttribute(), onCmdSetAttribute(), and showAttribute().
FXComboBox* GNEInspectorFrame::AttrInput::myChoicesCombo private
pointer to combo box choices
Definition at line 113 of file GNEInspectorFrame.h.
Referenced by AttrInput(), hiddeAttribute(), onCmdSetAttribute(), and showAttribute().
GNEInspectorFrame* GNEInspectorFrame::AttrInput::myInspectorFrameParent private
pointer to GNEInspectorFrame parent
Definition at line 92 of file GNEInspectorFrame.h.
Referenced by onCmdSetAttribute().
FXLabel* GNEInspectorFrame::AttrInput::myLabel private
pointer to label
Definition at line 101 of file GNEInspectorFrame.h.
Referenced by AttrInput(), hiddeAttribute(), and showAttribute().
SumoXMLTag GNEInspectorFrame::AttrInput::myTag private
current tag
Definition at line 95 of file GNEInspectorFrame.h.
Referenced by getTag(), onCmdSetAttribute(), and showAttribute().
FXTextField* GNEInspectorFrame::AttrInput::myTextFieldInt private
textField to modify the value of int values
Definition at line 104 of file GNEInspectorFrame.h.
Referenced by AttrInput(), hiddeAttribute(), onCmdSetAttribute(), and showAttribute().
FXTextField* GNEInspectorFrame::AttrInput::myTextFieldReal private
textField to modify the value of real values
Definition at line 107 of file GNEInspectorFrame.h.
Referenced by AttrInput(), hiddeAttribute(), onCmdSetAttribute(), and showAttribute().
FXTextField* GNEInspectorFrame::AttrInput::myTextFieldStrings private
textField to modify the value of strings values
Definition at line 110 of file GNEInspectorFrame.h.
Referenced by AttrInput(), hiddeAttribute(), onCmdOpenAttributeEditor(), onCmdSetAttribute(), and showAttribute().
The documentation for this class was generated from the following files:
GNEInspectorFrame.h
GNEInspectorFrame.cpp