SUMO - Simulation of Urban MObility: GenericSAXHandler Class Reference
GenericSAXHandler Class Reference
A handler which converts occuring elements and attributes into enums.
#include <GenericSAXHandler.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
GenericSAXHandler (StringBijection< int >::Entry *tags, int terminatorTag, StringBijection< int >::Entry *attrs, int terminatorAttr, const std::string &file)
Constructor.
const std::string & getFileName () const
returns the current file name
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
virtual ~GenericSAXHandler ()
Destructor.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Protected Member Functions
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
virtual void myEndElement (int element)
Callback method for a closing tag to implement by derived classes.
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Callback method for an opening tag to implement by derived classes.
Private Member Functions
XMLCh * convert (const std::string &name) const
converts from c++-string into unicode
int convertTag (const std::string &tag) const
Converts a tag from its string into its numerical representation.
GenericSAXHandler (const GenericSAXHandler &s)
invalidated copy constructor
const GenericSAXHandler & operator= (const GenericSAXHandler &s)
invalidated assignment operator
Private Attributes
std::vector< std::string > myCharactersVector
A list of character strings obtained so far to build the complete characters string at the end.
std::string myFileName
The name of the currently parsed file.
GenericSAXHandler * myParentHandler
The handler to give control back to.
int myParentIndicator
The tag indicating that control should be given back.
Friends
class SUMOSAXReader
attributes parsing
typedef std::map< int, XMLCh * > AttrMap
AttrMap myPredefinedTags
std::map< int, std::string > myPredefinedTagsMML
the map from ids to their string representation
elements parsing
typedef std::map< std::string, int > TagMap
TagMap myTagMap
Detailed Description
A handler which converts occuring elements and attributes into enums.
Normally, when using a standard SAX-handler, we would have to compare the incoming XMLCh*-element names with the ones we can parse. The same applies to parsing the attributes. This was assumed to be very time consuming, that's why we derive our handlers from this class.
The idea behind this second handler layer was avoid repeated conversion from strings/whatever to XMLCh* and back again. The usage is quite straight forward, the only overhead is the need to define the enums - both elements and attributes within "SUMOXMLDefinitions". Still, it maybe helps to avoid typos.
This class implements the SAX-callback and offers a new set of callbacks which must be implemented by derived classes. Instead of XMLCh*-values, element names are supplied to the derived classes as enums (int).
Also, this class allows to retrieve attributes using enums (int) within the implemented "myStartElement" method.
Basically, GenericSAXHandler is not derived within SUMO directly, but via SUMOSAXHandler which knows all tags/attributes used by SUMO. It is still kept separate for an easier maintainability and later extensions.
Definition at line 75 of file GenericSAXHandler.h.
Member Typedef Documentation
typedef std::map<int, XMLCh*> GenericSAXHandler::AttrMap private
Definition at line 288 of file GenericSAXHandler.h.
typedef std::map<std::string, int> GenericSAXHandler::TagMap private
Definition at line 302 of file GenericSAXHandler.h.
Constructor & Destructor Documentation
GenericSAXHandler::GenericSAXHandler (StringBijection< int >::Entry * tags, int terminatorTag, StringBijection< int >::Entry * attrs, int terminatorAttr, const std::string & file)
Constructor.
This constructor gets the lists of known tag and attribute names with their enums (sumotags and sumoattrs in most cases). The end of the list is signaled by terminatorTag/terminatorAttr respectively.
The attribute names are converted into XMLCh* and stored within an internal container. This container is cleared within the destructor.
Parameters
[in] tags The list of known tags
[in] terminatorTag The tag which signales the end of tags (usually the last entry)
[in] attrs The list of known attributes
[in] terminatorAttr The attr which signales the end of attrs (usually the last entry)
[in] file The name of the processed file
Todo:
Why are both lists non-const and given as pointers?
Definition at line 52 of file GenericSAXHandler.cpp.
References convert(), myPredefinedTags, myPredefinedTagsMML, and myTagMap.
GenericSAXHandler::~GenericSAXHandler () virtual
Destructor.
Definition at line 72 of file GenericSAXHandler.cpp.
References myPredefinedTags.
GenericSAXHandler::GenericSAXHandler (const GenericSAXHandler & s) private
invalidated copy constructor
Member Function Documentation
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 192 of file GenericSAXHandler.cpp.
References getFileName().
Referenced by error(), fatalError(), and warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 175 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and myCharactersVector.
XMLCh * GenericSAXHandler::convert (const std::string & name) const private
converts from c++-string into unicode
Todo:
recheck encoding
Parameters
[in] name The string to convert
Returns
The string converted into a XMLCh-string
Definition at line 92 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler().
int GenericSAXHandler::convertTag (const std::string & tag) const private
Converts a tag from its string into its numerical representation.
Returns the enum-representation stored for the given tag. If the tag is not known, SUMO_TAG_NOTHING is returned.
Parameters
[in] tag The string to convert
Returns
The int-value that represents the string, SUMO_TAG_NOTHING if the named attribute is not known
Definition at line 182 of file GenericSAXHandler.cpp.
References myTagMap, and SUMO_TAG_NOTHING.
Referenced by endElement(), and startElement().
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), convertTag(), myCharacters(), myCharactersVector, myEndElement(), myParentHandler, myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception)
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 211 of file GenericSAXHandler.cpp.
References buildErrorMessage().
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), MSRouteHandler::myStartElement(), and MSRouteHandler::parseWalkPos().
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception)
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 217 of file GenericSAXHandler.cpp.
References buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const
returns the current file name
Returns
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), MSStateHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), startElement(), and SUMORouteLoader::SUMORouteLoader().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 227 of file GenericSAXHandler.cpp.
Referenced by endElement().
void GenericSAXHandler::myEndElement (int element) protected virtual
Callback method for a closing tag to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The closed element, given as a int ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_OpenDrive, NIImporter_OpenStreetMap::RelationHandler, NIImporter_Vissim::NIVissimXMLHandler_Routenentscheidungsdefinition, NIImporter_Vissim::NIVissimXMLHandler_Geschwindigkeitsverteilungsdefinition, NIImporter_OpenStreetMap::EdgesHandler, PCLoaderOSM::EdgesHandler, NIImporter_Vissim::NIVissimXMLHandler_VWunschentscheidungsdefinition, NIImporter_OpenStreetMap::NodesHandler, NIImporter_Vissim::NIVissimXMLHandler_Fahrzeugklassendefinition, PCLoaderOSM::RelationsHandler, MSTriggeredRerouter, SAXWeightsHandler, PCLoaderOSM::NodesHandler, NLHandler, NIImporter_ITSUMO::Handler, MSLaneSpeedTrigger, NIImporter_SUMO, NIImporter_Vissim::NIVissimXMLHandler_Streckendefinition, NIXMLEdgesHandler, MSCalibrator, SUMORouteHandler, RORouteHandler, ODDistrictHandler, MSRouteHandler, RONetHandler, MSStateHandler, NIXMLTrafficLightsHandler, GUITriggeredRerouter, GNEPoly::GNEPolyHandler, and ROMARouteHandler.
Definition at line 231 of file GenericSAXHandler.cpp.
Referenced by endElement(), NLHandler::networkVersion(), and SUMOSAXReader::parseNext().
void GenericSAXHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Callback method for an opening tag to implement by derived classes.
Called by "startElement" (see there).
Parameters
[in] element The element that contains the characters, given as a int
[in] attrs The SAX-attributes, wrapped as SUMOSAXAttributes ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_OpenDrive, NIImporter_Vissim::NIVissimXMLHandler_ConflictArea, NIImporter_OpenStreetMap::RelationHandler, NIImporter_Vissim::NIVissimXMLHandler_Routenentscheidungsdefinition, NIImporter_Vissim::NIVissimXMLHandler_Geschwindigkeitsverteilungsdefinition, NIImporter_OpenStreetMap::EdgesHandler, PCLoaderOSM::EdgesHandler, NIImporter_Vissim::NIVissimXMLHandler_VWunschentscheidungsdefinition, NIImporter_OpenStreetMap::NodesHandler, NIImporter_Vissim::NIVissimXMLHandler_Fahrzeugklassendefinition, PCLoaderOSM::RelationsHandler, NIImporter_Vissim::NIVissimXMLHandler_Parkplatzdefinition, MSTriggeredRerouter, SAXWeightsHandler, NIImporter_Vissim::NIVissimXMLHandler_Zuflussdefinition, PCLoaderOSM::NodesHandler, NIImporter_MATSim::EdgesHandler, NLHandler, NIImporter_Vissim::NIVissimXMLHandler_Streckendefinition, MSLaneSpeedTrigger, NIImporter_SUMO, NIImporter_MATSim::NodesHandler, NIImporter_ITSUMO::Handler, PCLoaderXML, NIXMLEdgesHandler, NIXMLNodesHandler, TrajectoriesHandler, MSCalibrator, PCNetProjectionLoader, ShapeHandler, SUMORouteHandler, RORouteHandler, ROJTRTurnDefLoader, ODDistrictHandler, MSRouteHandler, RONetHandler, NIXMLConnectionsHandler, NIXMLTypesHandler, ODAmitranHandler, MSStateHandler, NIXMLTrafficLightsHandler, PCTypeDefHandler, AGActivityGenHandler, GNEAdditionalHandler, GNEPoly::GNEPolyHandler, GUISettingsHandler, ROMARouteHandler, and RODFDetectorHandler.
Definition at line 223 of file GenericSAXHandler.cpp.
Referenced by SUMOSAXReader::parseNext(), and startElement().
const GenericSAXHandler& GenericSAXHandler::operator= (const GenericSAXHandler & s) private
invalidated assignment operator
Referenced by NIImporter_OpenDrive::same_position_finder::operator()().
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler)
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 167 of file GenericSAXHandler.cpp.
References myParentHandler, myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
void GenericSAXHandler::setFileName (const std::string & name)
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs)
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), convertTag(), FileHelpers::getConfigurationRelative(), getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), myCharactersVector, myPredefinedTags, myPredefinedTagsMML, myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception)
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 205 of file GenericSAXHandler.cpp.
References buildErrorMessage(), and WRITE_WARNING.
Friends And Related Function Documentation
friend class SUMOSAXReader friend
Definition at line 212 of file GenericSAXHandler.h.
Field Documentation
std::vector<std::string> GenericSAXHandler::myCharactersVector private
A list of character strings obtained so far to build the complete characters string at the end.
Definition at line 309 of file GenericSAXHandler.h.
Referenced by characters(), endElement(), and startElement().
std::string GenericSAXHandler::myFileName private
The name of the currently parsed file.
Definition at line 318 of file GenericSAXHandler.h.
Referenced by getFileName(), and setFileName().
GenericSAXHandler* GenericSAXHandler::myParentHandler private
The handler to give control back to.
Definition at line 312 of file GenericSAXHandler.h.
Referenced by endElement(), and registerParent().
int GenericSAXHandler::myParentIndicator private
The tag indicating that control should be given back.
Definition at line 315 of file GenericSAXHandler.h.
Referenced by endElement(), and registerParent().
AttrMap GenericSAXHandler::myPredefinedTags private
Definition at line 291 of file GenericSAXHandler.h.
Referenced by GenericSAXHandler(), startElement(), and ~GenericSAXHandler().
std::map<int, std::string> GenericSAXHandler::myPredefinedTagsMML private
the map from ids to their string representation
Definition at line 294 of file GenericSAXHandler.h.
Referenced by GenericSAXHandler(), SUMOSAXReader::parseNext(), and startElement().
TagMap GenericSAXHandler::myTagMap private
Definition at line 305 of file GenericSAXHandler.h.
Referenced by convertTag(), and GenericSAXHandler().
The documentation for this class was generated from the following files:
GenericSAXHandler.h
GenericSAXHandler.cpp