SUMO - Simulation of Urban MObility: NWWriter_Amitran Class Reference
NWWriter_Amitran Class Reference
Exporter writing networks using the Amitran format.
#include <NWWriter_Amitran.h>
Static Public Member Functions
static void writeNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Writes the network into a Amitran-file.
Detailed Description
Exporter writing networks using the Amitran format.
Definition at line 49 of file NWWriter_Amitran.h.
Member Function Documentation
void NWWriter_Amitran::writeNetwork (const OptionsCont & oc, NBNetBuilder & nb) static
Writes the network into a Amitran-file.
Parameters
[in] oc The options to use
[in] nb The network builder to fill
Definition at line 55 of file NWWriter_Amitran.cpp.
References NBNodeCont::begin(), NBEdgeCont::begin(), NBNodeCont::end(), NBEdgeCont::end(), OutputDevice::getDevice(), NBNetBuilder::getEdgeCont(), NBNetBuilder::getNodeCont(), NWWriter_DlrNavteq::getRoadClass(), NBEdgeCont::getRoundabouts(), OptionsCont::getString(), OptionsCont::isSet(), NODETYPE_ALLWAY_STOP, NODETYPE_DEAD_END, NODETYPE_DEAD_END_DEPRECATED, NODETYPE_DISTRICT, NODETYPE_INTERNAL, NODETYPE_NOJUNCTION, NODETYPE_PRIORITY, NODETYPE_PRIORITY_STOP, NODETYPE_RAIL_CROSSING, NODETYPE_RAIL_SIGNAL, NODETYPE_RIGHT_BEFORE_LEFT, NODETYPE_TRAFFIC_LIGHT, NODETYPE_TRAFFIC_LIGHT_NOJUNCTION, NODETYPE_TRAFFIC_LIGHT_RIGHT_ON_RED, NODETYPE_UNKNOWN, and NODETYPE_ZIPPER.
Referenced by NWFrame::writeNetwork().
The documentation for this class was generated from the following files:
NWWriter_Amitran.h
NWWriter_Amitran.cpp