SUMO - Simulation of Urban MObility: GNEAdditionalFrame Class Reference
GNEAdditionalFrame Class Reference
#include <GNEAdditionalFrame.h>
Data Structures
class additionalParameter
FOX-declaration.
class additionalParameterList
class additionalParameters
class additionalSet
class edgesSelector
class editorParameters
class lanesSelector
Public Member Functions
bool addAdditional (GNENetElement *netElement, GUISUMOAbstractView *parent)
add additional element
FXFont * getFrameHeaderFont () const
get font of the header's frame
FXLabel * getFrameHeaderLabel () const
get the label for the frame's header
GNEViewNet * getViewNet () const
get view net
GNEAdditionalFrame (FXComposite *parent, GNEViewNet *viewNet)
Constructor.
void hide ()
hidde additional frame
void removeAdditional (GNEAdditional *additional)
remove an additional element previously added
void show ()
show additional frame
~GNEAdditionalFrame ()
Destructor.
FOX-callbacks
Called when the user select another additional Type
long onCmdSelectAdditional (FXObject *, FXSelector, void *)
Static Public Member Functions
static std::string getIdsSelected (const FXList *list)
get list of selecte id's in string format
Protected Member Functions
GNEAdditionalFrame ()
FOX needs this.
Protected Attributes
FXVerticalFrame * myContentFrame
the panel to hold all member widgets
FXFont * myFrameHeaderFont
Font for the Header.
FXLabel * myFrameHeaderLabel
the label for the frame's header
GNEViewNet * myViewNet
the window to inform when the tls is modfied
Private Member Functions
std::string generateID (GNENetElement *netElement) const
generate a ID for an additiona element
SUMOReal setEndPosition (SUMOReal laneLenght, SUMOReal positionOfTheMouseOverLane, SUMOReal lenghtOfAdditional)
obtain the End position values of StoppingPlaces and E2 detector over the lane
void setParametersOfAdditional (SumoXMLTag actualAdditionalType)
set parameters depending of the new additionalType
SUMOReal setStartPosition (SUMOReal positionOfTheMouseOverLane, SUMOReal lenghtOfAdditional)
obtain the Start position values of StoppingPlaces and E2 detector over the lane
Private Attributes
SumoXMLTag myActualAdditionalType
actual additional type selected in the match Box
FXComboBox * myAdditionalMatchBox
combo box with the list of additional elements
GNEAdditionalFrame::additionalParameters * myAdditionalParameters
additional default parameters
GNEAdditionalFrame::additionalSet * myAdditionalSet
list of additional Set
GNEAdditionalFrame::edgesSelector * myEdgesSelector
list of edgesSelector
GNEAdditionalFrame::editorParameters * myEditorParameters
editor parameter
FXGroupBox * myGroupBoxForMyAdditionalMatchBox
groupBox for Match Box of additionals
GNEAdditionalFrame::lanesSelector * myLanesSelector
list of lanesSelector
Detailed Description
The Widget for setting default parameters of additional elements
Definition at line 50 of file GNEAdditionalFrame.h.
Constructor & Destructor Documentation
GNEAdditionalFrame::GNEAdditionalFrame (FXComposite * parent, GNEViewNet * viewNet)
Constructor.
parent FXFrame in which this GNEFrame is placed viewNet viewNet that uses this GNEFrame
Create list for edgesSelector
Create list for lanesSelector
Definition at line 122 of file GNEAdditionalFrame.cpp.
References GNEAttributeCarrier::allowedAdditionalTags(), MID_GNE_MODE_ADDITIONAL_ITEM, and toString().
GNEAdditionalFrame::~GNEAdditionalFrame ()
Destructor.
Definition at line 165 of file GNEAdditionalFrame.cpp.
References gSelected, and GUISelectedStorage::remove2Update().
GNEAdditionalFrame::GNEAdditionalFrame () inline protected
FOX needs this.
Definition at line 580 of file GNEAdditionalFrame.h.
References generateID(), setEndPosition(), setParametersOfAdditional(), setStartPosition(), and SUMOReal.
Member Function Documentation
bool GNEAdditionalFrame::addAdditional (GNENetElement * netElement, GUISUMOAbstractView * parent)
add additional element
Parameters
[in] netElement clicked netElement. if user dind't clicked over a GNENetElement in view, netElement will be NULL
[in] parent AbstractView to obtain the position of the mouse over the lane.
Returns
true if an additional (GNEAdditional or GNEAdditionalSet) was added, false in other case
Definition at line 171 of file GNEAdditionalFrame.cpp.
References GNEAdditionalHandler::buildAdditional(), generateID(), GNEAdditionalFrame::additionalParameters::getAttributes(), GNEAdditionalFrame::additionalSet::getCurrentlyTag(), GNEAttributeCarrier::getID(), GNEAdditionalFrame::additionalSet::getIdSelected(), GNEAdditionalFrame::edgesSelector::getIdsSelected(), GNEAdditionalFrame::lanesSelector::getIdsSelected(), GNEEdge::getLanes(), GNELane::getLaneShapeLenght(), GNEAdditionalFrame::editorParameters::getLenght(), GNEViewNet::getNet(), GUISUMOAbstractView::getPositionInformation(), GNELane::getShape(), GNE_ATTR_BLOCK_MOVEMENT, GNE_ATTR_PARENT, GNEAttributeCarrier::hasAttribute(), GNEAttributeCarrier::hasParent(), GNEAdditionalFrame::editorParameters::isBlockEnabled(), GNEAdditionalFrame::edgesSelector::isUseSelectedEdgesEnable(), GNEAdditionalFrame::lanesSelector::isUseSelectedLanesEnable(), joinToString(), myActualAdditionalType, myAdditionalParameters, myAdditionalSet, myEdgesSelector, myEditorParameters, myLanesSelector, GNEFrame::myViewNet, PositionVector::nearest_offset_to_point2D(), GNENet::retrieveEdges(), GNENet::retrieveLanes(), setEndPosition(), setStartPosition(), SUMO_ATTR_CROSSING, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_ID, SUMO_ATTR_JUNCTION, SUMO_ATTR_LANE, SUMO_ATTR_LANES, SUMO_ATTR_OUTPUT, SUMO_ATTR_POSITION, SUMO_ATTR_STARTPOS, SUMOReal, toString(), and WRITE_WARNING.
Referenced by GNEViewNet::onLeftBtnPress().
std::string GNEAdditionalFrame::generateID (GNENetElement * netElement) const private
generate a ID for an additiona element
Definition at line 426 of file GNEAdditionalFrame.cpp.
References GNENet::getAdditional(), GNEAttributeCarrier::getID(), GNEViewNet::getNet(), GNENet::getNumberOfAdditionals(), myActualAdditionalType, GNEFrame::myViewNet, SUMOReal, and toString().
Referenced by addAdditional(), and GNEAdditionalFrame().
FXFont * GNEFrame::getFrameHeaderFont () const inherited
get font of the header's frame
Definition at line 94 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderFont.
FXLabel * GNEFrame::getFrameHeaderLabel () const inherited
get the label for the frame's header
Definition at line 88 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by GNEInspectorFrame::inspect().
std::string GNEAdditionalFrame::getIdsSelected (const FXList * list) static
get list of selecte id's in string format
Definition at line 1069 of file GNEAdditionalFrame.cpp.
References text().
Referenced by GNEAdditionalFrame::edgesSelector::getIdsSelected(), and GNEAdditionalFrame::lanesSelector::getIdsSelected().
GNEViewNet * GNEFrame::getViewNet () const inherited
get view net
Definition at line 82 of file GNEFrame.cpp.
References GNEFrame::myViewNet.
Referenced by GNEInspectorFrame::AttrInput::onCmdSetAttribute().
void GNEAdditionalFrame::hide () virtual
hidde additional frame
Implements GNEFrame.
Definition at line 370 of file GNEAdditionalFrame.cpp.
References GNEViewNet::getViewParent(), GNEViewParent::hideFramesArea(), and GNEFrame::myViewNet.
Referenced by GNEAdditionalFrame::additionalParameters::hideAdditionalParameters(), GNEAdditionalFrame::additionalSet::hideList(), GNEAdditionalFrame::lanesSelector::hideList(), GNEAdditionalFrame::additionalParameter::hideParameter(), GNEAdditionalFrame::additionalParameterList::hideParameter(), and GNEViewNet::updateModeSpecificControls().
long GNEAdditionalFrame::onCmdSelectAdditional (FXObject * , FXSelector , void *)
Definition at line 344 of file GNEAdditionalFrame.cpp.
References GNEAttributeCarrier::allowedAdditionalTags(), myAdditionalMatchBox, setParametersOfAdditional(), and toString().
void GNEAdditionalFrame::removeAdditional (GNEAdditional * additional)
remove an additional element previously added
Parameters
[in] additional element to erase
Definition at line 336 of file GNEAdditionalFrame.cpp.
References GNEAttributeCarrier::getDescription(), GNEViewNet::getNet(), GNEViewNet::getUndoList(), GNEFrame::myViewNet, GNEUndoList::p_begin(), and GNEUndoList::p_end().
Referenced by GNEViewNet::onLeftBtnPress().
SUMOReal GNEAdditionalFrame::setEndPosition (SUMOReal laneLenght, SUMOReal positionOfTheMouseOverLane, SUMOReal lenghtOfAdditional) private
obtain the End position values of StoppingPlaces and E2 detector over the lane
Definition at line 474 of file GNEAdditionalFrame.cpp.
References GNEAdditionalFrame::editorParameters::getActualReferencePoint(), GNEAdditionalFrame::editorParameters::GNE_ADDITIONALREFERENCEPOINT_CENTER, GNEAdditionalFrame::editorParameters::GNE_ADDITIONALREFERENCEPOINT_LEFT, GNEAdditionalFrame::editorParameters::GNE_ADDITIONALREFERENCEPOINT_RIGHT, GNEAdditionalFrame::editorParameters::isForcePositionEnabled(), and myEditorParameters.
Referenced by addAdditional(), and GNEAdditionalFrame().
void GNEAdditionalFrame::setParametersOfAdditional (SumoXMLTag actualAdditionalType) private
set parameters depending of the new additionalType
Definition at line 379 of file GNEAdditionalFrame.cpp.
References GNEAdditionalFrame::additionalParameters::addAttribute(), GNEAttributeCarrier::allowedAttributes(), GNEAdditionalFrame::additionalParameters::clearAttributes(), GNEAdditionalFrame::additionalParameters::getNumberOfAddedAttributes(), GNEAttributeCarrier::getParentType(), GNEAttributeCarrier::hasAttribute(), GNEAttributeCarrier::hasParent(), GNEAdditionalFrame::additionalParameters::hideAdditionalParameters(), GNEAdditionalFrame::editorParameters::hideLengthField(), GNEAdditionalFrame::additionalSet::hideList(), GNEAdditionalFrame::edgesSelector::hideList(), GNEAdditionalFrame::lanesSelector::hideList(), GNEAdditionalFrame::editorParameters::hideReferencePoint(), GNEAttributeCarrier::isUnique(), myActualAdditionalType, myAdditionalParameters, myAdditionalSet, myEdgesSelector, myEditorParameters, myLanesSelector, GNEAdditionalFrame::additionalParameters::showAdditionalParameters(), GNEAdditionalFrame::editorParameters::showLengthField(), GNEAdditionalFrame::additionalSet::showList(), GNEAdditionalFrame::edgesSelector::showList(), GNEAdditionalFrame::lanesSelector::showList(), GNEAdditionalFrame::editorParameters::showReferencePoint(), SUMO_ATTR_EDGES, SUMO_ATTR_ENDPOS, and SUMO_ATTR_LANES.
Referenced by GNEAdditionalFrame(), and onCmdSelectAdditional().
SUMOReal GNEAdditionalFrame::setStartPosition (SUMOReal positionOfTheMouseOverLane, SUMOReal lenghtOfAdditional) private
obtain the Start position values of StoppingPlaces and E2 detector over the lane
Definition at line 445 of file GNEAdditionalFrame.cpp.
References GNEAdditionalFrame::editorParameters::getActualReferencePoint(), GNEAdditionalFrame::editorParameters::GNE_ADDITIONALREFERENCEPOINT_CENTER, GNEAdditionalFrame::editorParameters::GNE_ADDITIONALREFERENCEPOINT_LEFT, GNEAdditionalFrame::editorParameters::GNE_ADDITIONALREFERENCEPOINT_RIGHT, GNEAdditionalFrame::editorParameters::isForcePositionEnabled(), myEditorParameters, and SUMOReal.
Referenced by addAdditional(), and GNEAdditionalFrame().
void GNEAdditionalFrame::show () virtual
show additional frame
Implements GNEFrame.
Definition at line 357 of file GNEAdditionalFrame.cpp.
References GNEViewNet::getViewParent(), myEdgesSelector, myLanesSelector, GNEFrame::myViewNet, GNEViewParent::showFramesArea(), GNEAdditionalFrame::edgesSelector::updateUseSelectedEdges(), and GNEAdditionalFrame::lanesSelector::updateUseSelectedLanes().
Referenced by GNEAdditionalFrame::additionalParameters::showAdditionalParameters(), GNEAdditionalFrame::additionalSet::showList(), GNEAdditionalFrame::edgesSelector::showList(), GNEAdditionalFrame::lanesSelector::showList(), GNEAdditionalFrame::additionalParameterList::showListParameter(), GNEAdditionalFrame::additionalParameter::showParameter(), and GNEViewNet::updateModeSpecificControls().
Field Documentation
SumoXMLTag GNEAdditionalFrame::myActualAdditionalType private
actual additional type selected in the match Box
Definition at line 617 of file GNEAdditionalFrame.h.
Referenced by addAdditional(), generateID(), and setParametersOfAdditional().
FXComboBox* GNEAdditionalFrame::myAdditionalMatchBox private
combo box with the list of additional elements
Definition at line 599 of file GNEAdditionalFrame.h.
Referenced by onCmdSelectAdditional().
GNEAdditionalFrame::additionalParameters* GNEAdditionalFrame::myAdditionalParameters private
additional default parameters
Definition at line 602 of file GNEAdditionalFrame.h.
Referenced by addAdditional(), and setParametersOfAdditional().
GNEAdditionalFrame::additionalSet* GNEAdditionalFrame::myAdditionalSet private
list of additional Set
Definition at line 608 of file GNEAdditionalFrame.h.
Referenced by addAdditional(), and setParametersOfAdditional().
FXVerticalFrame* GNEFrame::myContentFrame protected inherited
the panel to hold all member widgets
Definition at line 94 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
GNEAdditionalFrame::edgesSelector* GNEAdditionalFrame::myEdgesSelector private
list of edgesSelector
Definition at line 611 of file GNEAdditionalFrame.h.
Referenced by addAdditional(), setParametersOfAdditional(), and show().
GNEAdditionalFrame::editorParameters* GNEAdditionalFrame::myEditorParameters private
editor parameter
Definition at line 605 of file GNEAdditionalFrame.h.
Referenced by addAdditional(), setEndPosition(), setParametersOfAdditional(), and setStartPosition().
FXFont* GNEFrame::myFrameHeaderFont protected inherited
Font for the Header.
Definition at line 88 of file GNEFrame.h.
Referenced by GNEFrame::getFrameHeaderFont(), GNEFrame::GNEFrame(), and GNEFrame::~GNEFrame().
FXLabel* GNEFrame::myFrameHeaderLabel protected inherited
the label for the frame's header
Definition at line 91 of file GNEFrame.h.
Referenced by GNEFrame::getFrameHeaderLabel(), GNEFrame::GNEFrame(), and GNESelectorFrame::selectionUpdated().
FXGroupBox* GNEAdditionalFrame::myGroupBoxForMyAdditionalMatchBox private
groupBox for Match Box of additionals
Definition at line 596 of file GNEAdditionalFrame.h.
GNEAdditionalFrame::lanesSelector* GNEAdditionalFrame::myLanesSelector private
list of lanesSelector
Definition at line 614 of file GNEAdditionalFrame.h.
Referenced by addAdditional(), setParametersOfAdditional(), and show().
GNEViewNet* GNEFrame::myViewNet protected inherited
the window to inform when the tls is modfied
Definition at line 85 of file GNEFrame.h.
Referenced by addAdditional(), GNEConnectorFrame::buildIinternalLanes(), GNETLSEditorFrame::buildIinternalLanes(), GNETLSEditorFrame::editJunction(), generateID(), GNESelectorFrame::getMatches(), GNEFrame::getViewNet(), GNETLSEditorFrame::handleChange(), GNESelectorFrame::handleIDs(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEConnectorFrame::hide(), GNETLSEditorFrame::hide(), GNESelectorFrame::hide(), GNEInspectorFrame::hide(), hide(), GNEConnectorFrame::initTargets(), GNEConnectorFrame::onCmdCancel(), GNETLSEditorFrame::onCmdCancel(), GNESelectorFrame::onCmdClear(), GNEConnectorFrame::onCmdClearSelectedConnections(), GNEInspectorFrame::onCmdCopyTemplate(), GNETLSEditorFrame::onCmdDefCreate(), GNETLSEditorFrame::onCmdDefDelete(), GNETLSEditorFrame::onCmdDefSwitch(), GNESelectorFrame::onCmdInvert(), GNESelectorFrame::onCmdLoad(), GNEConnectorFrame::onCmdOK(), GNETLSEditorFrame::onCmdOK(), GNETLSEditorFrame::onCmdPhaseSwitch(), GNEConnectorFrame::onCmdResetSelectedConnections(), GNESelectorFrame::onCmdScaleSelection(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEInspectorFrame::onCmdSetBlocking(), removeAdditional(), GNEConnectorFrame::show(), GNETLSEditorFrame::show(), GNESelectorFrame::show(), GNEInspectorFrame::show(), and show().
The documentation for this class was generated from the following files:
GNEAdditionalFrame.h
GNEAdditionalFrame.cpp