SUMO - Simulation of Urban MObility: NWWriter_DlrNavteq Class Reference
NWWriter_DlrNavteq Class Reference
Exporter writing networks using XML (native input) format.
#include <NWWriter_DlrNavteq.h>
Static Public Member Functions
static int getRoadClass (NBEdge *edge)
get the navteq road class
static void writeNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Writes the network into XML-files (nodes, edges, connections, traffic lights)
Static Private Member Functions
static std::string getAllowedTypes (SVCPermissions permissions)
build the ascii-bit-vector for column vehicle_type
static SUMOReal getGraphLength (NBEdge *edge)
get the length of the edge when measured up to the junction center
static int getNavteqLaneCode (const int numLanes)
get the lane number encoding
static int getSpeedCategory (int kph)
get the navteq speed class based on the speed in km/h
static int getSpeedCategoryUpperBound (int kph)
get the SPEED_LIMIT as defined by elmar (upper bound of speed category)
static int speedInKph (SUMOReal metersPerSecond)
get edge speed rounded to kmh
static void writeHeader (OutputDevice &device, const OptionsCont &oc)
write header comments (input paramters, date, etc...)
static void writeLinksUnsplitted (const OptionsCont &oc, NBEdgeCont &ec)
Writes the links_unsplitted file.
static void writeNodesUnsplitted (const OptionsCont &oc, NBNodeCont &nc, NBEdgeCont &ec)
Writes the nodes_unsplitted file.
static void writeTrafficSignals (const OptionsCont &oc, NBNodeCont &nc)
Writes the traffic_signals file.
Static Private Attributes
static const std::string UNDEFINED
magic value for undefined stuff
Detailed Description
Exporter writing networks using XML (native input) format.
Definition at line 61 of file NWWriter_DlrNavteq.h.
Member Function Documentation
std::string NWWriter_DlrNavteq::getAllowedTypes (SVCPermissions permissions) static private
build the ascii-bit-vector for column vehicle_type
Definition at line 215 of file NWWriter_DlrNavteq.cpp.
References SVCAll.
Referenced by writeLinksUnsplitted().
SUMOReal NWWriter_DlrNavteq::getGraphLength (NBEdge * edge) static private
get the length of the edge when measured up to the junction center
Definition at line 324 of file NWWriter_DlrNavteq.cpp.
References NBEdge::getFromNode(), NBEdge::getGeometry(), NBNode::getPosition(), NBEdge::getToNode(), PositionVector::length(), PositionVector::push_back_noDoublePos(), and PositionVector::push_front_noDoublePos().
Referenced by writeLinksUnsplitted().
int NWWriter_DlrNavteq::getNavteqLaneCode (const int numLanes) static private
get the lane number encoding
Definition at line 316 of file NWWriter_DlrNavteq.cpp.
References SUMOReal.
Referenced by writeLinksUnsplitted().
int NWWriter_DlrNavteq::getRoadClass (NBEdge * edge) static
get the navteq road class
Definition at line 237 of file NWWriter_DlrNavteq.cpp.
References NBEdge::getNumLanes(), NBEdge::getSpeed(), and speedInKph().
Referenced by writeLinksUnsplitted(), and NWWriter_Amitran::writeNetwork().
int NWWriter_DlrNavteq::getSpeedCategory (int kph) static private
get the navteq speed class based on the speed in km/h
Definition at line 262 of file NWWriter_DlrNavteq.cpp.
Referenced by writeLinksUnsplitted().
int NWWriter_DlrNavteq::getSpeedCategoryUpperBound (int kph) static private
get the SPEED_LIMIT as defined by elmar (upper bound of speed category)
Definition at line 289 of file NWWriter_DlrNavteq.cpp.
Referenced by writeLinksUnsplitted().
static int NWWriter_DlrNavteq::speedInKph (SUMOReal metersPerSecond) inline static private
get edge speed rounded to kmh
Definition at line 116 of file NWWriter_DlrNavteq.h.
Referenced by getRoadClass(), and writeLinksUnsplitted().
void NWWriter_DlrNavteq::writeHeader (OutputDevice & device, const OptionsCont & oc) static private
write header comments (input paramters, date, etc...)
Definition at line 74 of file NWWriter_DlrNavteq.cpp.
References OptionsCont::getFullName(), and OptionsCont::writeConfiguration().
Referenced by writeLinksUnsplitted(), writeNodesUnsplitted(), and writeTrafficSignals().
void NWWriter_DlrNavteq::writeLinksUnsplitted (const OptionsCont & oc, NBEdgeCont & ec) static private
Writes the links_unsplitted file.
Parameters
[in] oc The options to use
[in] ec The edge-container from which to read data
Definition at line 156 of file NWWriter_DlrNavteq.cpp.
References NBEdgeCont::begin(), NBEdgeCont::end(), getAllowedTypes(), OptionsCont::getBool(), OutputDevice::getDevice(), NBEdge::getFromNode(), NBEdge::getGeometry(), getGraphLength(), Named::getID(), getNavteqLaneCode(), NBEdge::getNumLanes(), NBEdge::getPermissions(), getRoadClass(), NBEdge::getSpeed(), getSpeedCategory(), getSpeedCategoryUpperBound(), OptionsCont::getString(), NBEdge::getToNode(), speedInKph(), toString(), UNDEFINED, and writeHeader().
Referenced by writeNetwork().
void NWWriter_DlrNavteq::writeNetwork (const OptionsCont & oc, NBNetBuilder & nb) static
Writes the network into XML-files (nodes, edges, connections, traffic lights)
Parameters
[in] oc The options to use
[in] nb The network builder from which to read data
Definition at line 63 of file NWWriter_DlrNavteq.cpp.
References NBNetBuilder::getEdgeCont(), NBNetBuilder::getNodeCont(), OptionsCont::isSet(), writeLinksUnsplitted(), writeNodesUnsplitted(), and writeTrafficSignals().
Referenced by NWFrame::writeNetwork().
void NWWriter_DlrNavteq::writeNodesUnsplitted (const OptionsCont & oc, NBNodeCont & nc, NBEdgeCont & ec) static private
Writes the nodes_unsplitted file.
Parameters
[in] oc The options to use
[in] nc The node-container from which to read data
[in] ec The edge-container from which to read data
Definition at line 93 of file NWWriter_DlrNavteq.cpp.
References NBNodeCont::begin(), NBEdgeCont::begin(), GeoConvHelper::cartesian2geo(), OutputDevice::close(), NBNodeCont::end(), NBEdgeCont::end(), NBEdgeCont::getAllNames(), NBNodeCont::getAllNames(), OptionsCont::getBool(), OutputDevice::getDevice(), GeoConvHelper::getFinal(), NBEdge::getGeometry(), Named::getID(), IDSupplier::getNext(), NBNode::getPosition(), OptionsCont::getString(), Position::mul(), NBNodeCont::retrieve(), OutputDevice::setPrecision(), SUMOReal, UNDEFINED, GeoConvHelper::usingGeoProjection(), WRITE_WARNING, writeHeader(), Position::x(), and Position::y().
Referenced by writeNetwork().
void NWWriter_DlrNavteq::writeTrafficSignals (const OptionsCont & oc, NBNodeCont & nc) static private
Writes the traffic_signals file.
Parameters
[in] oc The options to use
[in] nc The node-container from which to read data
Definition at line 333 of file NWWriter_DlrNavteq.cpp.
References NBNodeCont::begin(), GeoConvHelper::cartesian2geo(), NBNodeCont::end(), OutputDevice::getDevice(), GeoConvHelper::getFinal(), Named::getID(), NBNode::getIncomingEdges(), NBNode::getPosition(), OptionsCont::getString(), NBNode::isTLControlled(), Position::mul(), OutputDevice::setPrecision(), SUMOReal, GeoConvHelper::usingGeoProjection(), writeHeader(), Position::x(), and Position::y().
Referenced by writeNetwork().
Field Documentation
const std::string NWWriter_DlrNavteq::UNDEFINED static private
magic value for undefined stuff
Definition at line 113 of file NWWriter_DlrNavteq.h.
Referenced by writeLinksUnsplitted(), and writeNodesUnsplitted().
The documentation for this class was generated from the following files:
NWWriter_DlrNavteq.h
NWWriter_DlrNavteq.cpp