SUMO - Simulation of Urban MObility: SUMOVTypeParameter Class Reference
SUMOVTypeParameter Class Reference
Structure representing possible vehicle parameter.
#include <SUMOVTypeParameter.h>
Public Types
typedef std::map< SumoXMLAttr, SUMOReal > SubParams
sub-model parameters
Public Member Functions
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
void clearParameter ()
Clears the parameter map.
SUMOReal getCFParam (const SumoXMLAttr attr, const SUMOReal defaultValue) const
Returns the named value from the map, or the default if it is not contained there.
SUMOReal getLCParam (const SumoXMLAttr attr, const SUMOReal defaultValue) const
Returns the named value from the map, or the default if it is not contained there.
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
SUMOVTypeParameter (const std::string &vtid, const SUMOVehicleClass vc=SVC_IGNORING)
Constructor.
void validateCFParameter () const
Validates stored car-following parameter.
bool wasSet (int what) const
Returns whether the given parameter was set.
void write (OutputDevice &dev) const
Writes the vtype.
Static Public Member Functions
static const SUMOVTypeParameter & getDefault ()
return the default parameters, this is a function due to the http://www.parashift.com/c++-faq/static-init-order.html
static SUMOReal getDefaultAccel (const SUMOVehicleClass vc=SVC_IGNORING)
Returns the default acceleration for the given vehicle class This needs to be a function because the actual value is stored in the car following model.
static SUMOReal getDefaultDecel (const SUMOVehicleClass vc=SVC_IGNORING)
Returns the default deceleration for the given vehicle class This needs to be a function because the actual value is stored in the car following model.
static SUMOReal getDefaultImperfection (const SUMOVehicleClass vc=SVC_IGNORING)
Returns the default driver's imperfection (sigma or epsilon in Krauss' model) for the given vehicle class This needs to be a function because the actual value is stored in the car following model.
Data Fields
SUMOTime boardingDuration
The time a person needs to board the vehicle.
SumoXMLTag cfModel
The enum-representation of the car-following model to use.
SubParams cfParameter
Car-following parameter.
RGBColor color
The color.
int containerCapacity
The container capacity of the vehicle.
SUMOReal defaultProbability
The probability when being added to a distribution without an explicit probability.
SUMOEmissionClass emissionClass
The emission class of this vehicle.
std::string id
The vehicle type's id.
SUMOReal impatience
The vehicle's impatience (willingness to obstruct others)
LateralAlignment latAlignment
The vehicles desired lateral alignment.
LaneChangeModel lcModel
The lane-change model to use.
SubParams lcParameter
Lane-changing parameter.
SUMOReal length
The physical vehicle length.
SUMOTime loadingDuration
The time a container needs to get loaded on the vehicle.
SUMOReal maxSpeed
The vehicle type's maximum speed [m/s].
SUMOReal maxSpeedLat
The vehicle type's maximum lateral speed [m/s].
SUMOReal minGap
This class' free space in front of the vehicle itself.
SUMOReal minGapLat
The vehicle type's minimum lateral gap [m].
bool onlyReferenced
Information whether this is a type-stub, being only referenced but not defined (needed by routers)
int personCapacity
The person capacity of the vehicle.
bool saved
Information whether this type was already saved (needed by routers)
int setParameter
Information for the router which parameter were set.
SUMOReal speedDev
The standard deviation for speed variations.
SUMOReal speedFactor
The factor by which the maximum speed may deviate from the allowed max speed on the street.
SUMOVehicleClass vehicleClass
The vehicle's class.
Values for drawing this class' vehicles
SUMOReal width
This class' width.
SUMOReal height
This class' height.
SUMOVehicleShape shape
This class' shape.
std::string osgFile
3D model file for this class
std::string imgFile
Image file for this class.
Detailed Description
Structure representing possible vehicle parameter.
Definition at line 85 of file SUMOVTypeParameter.h.
Member Typedef Documentation
typedef std::map<SumoXMLAttr, SUMOReal> SUMOVTypeParameter::SubParams
sub-model parameters
Definition at line 186 of file SUMOVTypeParameter.h.
Constructor & Destructor Documentation
SUMOVTypeParameter::SUMOVTypeParameter (const std::string & vtid, const SUMOVehicleClass vc = SVC_IGNORING)
Constructor.
Initialises the structure with default values
Definition at line 51 of file SUMOVTypeParameter.cpp.
References containerCapacity, DEFAULT_PEDESTRIAN_SPEED, height, length, maxSpeed, minGap, osgFile, personCapacity, shape, SVC_BICYCLE, SVC_BUS, SVC_COACH, SVC_DELIVERY, SVC_E_VEHICLE, SVC_EMERGENCY, SVC_MOPED, SVC_MOTORCYCLE, SVC_PASSENGER, SVC_PEDESTRIAN, SVC_RAIL, SVC_RAIL_ELECTRIC, SVC_RAIL_URBAN, SVC_SHIP, SVC_TRAILER, SVC_TRAM, SVC_TRUCK, SVS_BICYCLE, SVS_BUS, SVS_BUS_COACH, SVS_DELIVERY, SVS_E_VEHICLE, SVS_MOPED, SVS_MOTORCYCLE, SVS_PASSENGER, SVS_PEDESTRIAN, SVS_RAIL, SVS_RAIL_CAR, SVS_SHIP, SVS_TRUCK, SVS_TRUCK_SEMITRAILER, and width.
Member Function Documentation
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 53 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NBTrafficLightDefinition::compute(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::EdgesHandler::myStartElement(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_TLS::processSet(), TraCIServerAPI_Polygon::processSet(), and TraCIServerAPI_Lane::processSet().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 59 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 67 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 91 of file Parameterised.cpp.
References Parameterised::myMap.
SUMOReal SUMOVTypeParameter::getCFParam (const SumoXMLAttr attr, const SUMOReal defaultValue) const
Returns the named value from the map, or the default if it is not contained there.
Parameters
[in] attr The corresponding xml attribute
[in] defaultValue The value to return if the given map does not contain the named variable
Returns
The named value from the map or the default if it does not exist there
Definition at line 308 of file SUMOVTypeParameter.cpp.
References cfParameter, and SUMOReal.
Referenced by MSVehicleType::build(), ROEdge::getEmissionEffort(), and wasSet().
const SUMOVTypeParameter & SUMOVTypeParameter::getDefault () static
return the default parameters, this is a function due to the http://www.parashift.com/c++-faq/static-init-order.html
Definition at line 413 of file SUMOVTypeParameter.cpp.
Referenced by MESegment::jamThresholdForSpeed(), and TraCIServerAPI_Lane::processGet().
SUMOReal SUMOVTypeParameter::getDefaultAccel (const SUMOVehicleClass vc = SVC_IGNORING) static
Returns the default acceleration for the given vehicle class This needs to be a function because the actual value is stored in the car following model.
Parameters
[in] vc the vehicle class
Returns
the acceleration in m/s^2
Definition at line 328 of file SUMOVTypeParameter.cpp.
References SUMOReal, SVC_BICYCLE, SVC_BUS, SVC_COACH, SVC_MOPED, SVC_MOTORCYCLE, SVC_PEDESTRIAN, SVC_RAIL, SVC_RAIL_ELECTRIC, SVC_RAIL_URBAN, SVC_SHIP, SVC_TRAILER, SVC_TRAM, and SVC_TRUCK.
Referenced by MSVehicleType::build(), and ROEdge::getEmissionEffort().
SUMOReal SUMOVTypeParameter::getDefaultDecel (const SUMOVehicleClass vc = SVC_IGNORING) static
Returns the default deceleration for the given vehicle class This needs to be a function because the actual value is stored in the car following model.
Parameters
[in] vc the vehicle class
Returns
the deceleration in m/s^2
Definition at line 363 of file SUMOVTypeParameter.cpp.
References SUMOReal, SVC_BICYCLE, SVC_BUS, SVC_COACH, SVC_MOPED, SVC_MOTORCYCLE, SVC_PEDESTRIAN, SVC_RAIL, SVC_RAIL_ELECTRIC, SVC_RAIL_URBAN, SVC_SHIP, SVC_TRAILER, SVC_TRAM, and SVC_TRUCK.
Referenced by MSVehicleType::build(), and TraCIServerAPI_Lane::processGet().
SUMOReal SUMOVTypeParameter::getDefaultImperfection (const SUMOVehicleClass vc = SVC_IGNORING) static
Returns the default driver's imperfection (sigma or epsilon in Krauss' model) for the given vehicle class This needs to be a function because the actual value is stored in the car following model.
Parameters
[in] vc the vehicle class
Returns
the imperfection as a value between 0 and 1
Definition at line 398 of file SUMOVTypeParameter.cpp.
References SVC_RAIL, SVC_RAIL_ELECTRIC, SVC_RAIL_URBAN, SVC_SHIP, and SVC_TRAM.
Referenced by MSVehicleType::build(), and ROEdge::getEmissionEffort().
SUMOReal SUMOVTypeParameter::getLCParam (const SumoXMLAttr attr, const SUMOReal defaultValue) const
Returns the named value from the map, or the default if it is not contained there.
Parameters
[in] attr The corresponding xml attribute
[in] defaultValue The value to return if the given map does not contain the named variable
Returns
The named value from the map or the default if it does not exist there
Definition at line 317 of file SUMOVTypeParameter.cpp.
References lcParameter, and SUMOReal.
Referenced by wasSet().
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 107 of file Parameterised.h.
References Parameterised::myMap.
Referenced by NBTrafficLightDefinition::compute(), MSDevice_Vehroutes::generateOutput(), GUIPerson::getParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), TraCIServerAPI_TLS::processGet(), ROVehicle::saveAsXML(), ROPerson::saveAsXML(), write(), PointOfInterest::writeXML(), and SUMO::Polygon::writeXML().
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 81 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), MSSOTLPolicyDesirability::readParameter(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), and TraCIServerAPI_Vehicle::vtdMap().
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 75 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), and MSDevice::equippedByDefaultAssignmentOptions().
void SUMOVTypeParameter::validateCFParameter () const
Validates stored car-following parameter.
Referenced by wasSet().
bool SUMOVTypeParameter::wasSet (int what) const inline
Returns whether the given parameter was set.
Parameters
[in] what The parameter which one asks for
Returns
Whether the given parameter was set
Definition at line 98 of file SUMOVTypeParameter.h.
References getCFParam(), getLCParam(), setParameter, SUMOReal, validateCFParameter(), and write().
Referenced by write().
void SUMOVTypeParameter::write (OutputDevice & dev) const
Writes the vtype.
Parameters
[in,out] dev The device to write into
Exceptions
IOError not yet implemented
Definition at line 198 of file SUMOVTypeParameter.cpp.
References boardingDuration, cfModel, cfParameter, OutputDevice::closeTag(), color, containerCapacity, defaultProbability, emissionClass, Parameterised::getMap(), PollutantsInterface::getName(), getVehicleShapeName(), height, imgFile, impatience, latAlignment, lcModel, lcParameter, length, loadingDuration, max, maxSpeed, maxSpeedLat, minGap, minGapLat, onlyReferenced, OutputDevice::openTag(), osgFile, personCapacity, shape, speedDev, speedFactor, SUMO_ATTR_BOARDING_DURATION, SUMO_ATTR_COLOR, SUMO_ATTR_CONTAINER_CAPACITY, SUMO_ATTR_EMISSIONCLASS, SUMO_ATTR_GUISHAPE, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_IMPATIENCE, SUMO_ATTR_KEY, SUMO_ATTR_LANE_CHANGE_MODEL, SUMO_ATTR_LATALIGNMENT, SUMO_ATTR_LENGTH, SUMO_ATTR_LOADING_DURATION, SUMO_ATTR_MAXSPEED, SUMO_ATTR_MAXSPEED_LAT, SUMO_ATTR_MINGAP, SUMO_ATTR_MINGAP_LAT, SUMO_ATTR_OSGFILE, SUMO_ATTR_PERSON_CAPACITY, SUMO_ATTR_PROB, SUMO_ATTR_SPEEDDEV, SUMO_ATTR_SPEEDFACTOR, SUMO_ATTR_VALUE, SUMO_ATTR_VCLASS, SUMO_ATTR_WIDTH, SUMO_TAG_PARAM, SUMO_TAG_VTYPE, SUMOReal, toString(), vehicleClass, VTYPEPARS_BOARDING_DURATION, VTYPEPARS_CAR_FOLLOW_MODEL, VTYPEPARS_COLOR_SET, VTYPEPARS_CONTAINER_CAPACITY, VTYPEPARS_EMISSIONCLASS_SET, VTYPEPARS_HEIGHT_SET, VTYPEPARS_IMGFILE_SET, VTYPEPARS_IMPATIENCE_SET, VTYPEPARS_LANE_CHANGE_MODEL_SET, VTYPEPARS_LATALIGNMENT_SET, VTYPEPARS_LENGTH_SET, VTYPEPARS_LOADING_DURATION, VTYPEPARS_MAXSPEED_LAT_SET, VTYPEPARS_MAXSPEED_SET, VTYPEPARS_MINGAP_LAT_SET, VTYPEPARS_MINGAP_SET, VTYPEPARS_OSGFILE_SET, VTYPEPARS_PERSON_CAPACITY, VTYPEPARS_PROBABILITY_SET, VTYPEPARS_SHAPE_SET, VTYPEPARS_SPEEDDEVIATION_SET, VTYPEPARS_SPEEDFACTOR_SET, VTYPEPARS_VEHICLECLASS_SET, VTYPEPARS_WIDTH_SET, wasSet(), width, and OutputDevice::writeAttr().
Referenced by ROVehicle::saveAsXML(), ROPerson::saveAsXML(), and wasSet().
Field Documentation
SUMOTime SUMOVTypeParameter::boardingDuration
The time a person needs to board the vehicle.
Definition at line 158 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getBoardingDuration(), and write().
SumoXMLTag SUMOVTypeParameter::cfModel
The enum-representation of the car-following model to use.
Definition at line 183 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::build(), SUMOVehicleParserHelper::parseVTypeEmbedded(), and write().
SubParams SUMOVTypeParameter::cfParameter
Car-following parameter.
Definition at line 188 of file SUMOVTypeParameter.h.
Referenced by getCFParam(), SUMOVehicleParserHelper::parseVTypeEmbedded(), and write().
RGBColor SUMOVTypeParameter::color
The color.
Definition at line 148 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getColor(), MSVehicleType::setColor(), and write().
int SUMOVTypeParameter::containerCapacity
The container capacity of the vehicle.
Definition at line 156 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getContainerCapacity(), SUMOVTypeParameter(), and write().
SUMOReal SUMOVTypeParameter::defaultProbability
The probability when being added to a distribution without an explicit probability.
Definition at line 140 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getDefaultProbability(), RORouteHandler::myEndElement(), MSVehicleType::setDefaultProbability(), and write().
SUMOEmissionClass SUMOVTypeParameter::emissionClass
The emission class of this vehicle.
Definition at line 146 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getEmissionClass(), ROEdge::getEmissionEffort(), ROEdge::getNoiseEffort(), MSVehicleType::setEmissionClass(), and write().
SUMOReal SUMOVTypeParameter::height
This class' height.
Definition at line 169 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getHeight(), SUMOVTypeParameter(), and write().
std::string SUMOVTypeParameter::id
The vehicle type's id.
Definition at line 131 of file SUMOVTypeParameter.h.
Referenced by RONet::addVehicleType(), SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::build(), RONet::checkFlows(), RORouteHandler::closeVehicle(), MSVehicleType::getID(), SUMOVehicleParserHelper::parseLCParams(), SUMOVehicleParserHelper::parseVTypeEmbedded(), and RONet::RONet().
std::string SUMOVTypeParameter::imgFile
Image file for this class.
Definition at line 178 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getImgFile(), and write().
SUMOReal SUMOVTypeParameter::impatience
The vehicle's impatience (willingness to obstruct others)
Definition at line 152 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getImpatience(), TraCIServerAPI_Lane::processGet(), MSVehicleType::setImpatience(), and write().
LateralAlignment SUMOVTypeParameter::latAlignment
The vehicles desired lateral alignment.
Definition at line 198 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getPreferredLateralAlignment(), and write().
LaneChangeModel SUMOVTypeParameter::lcModel
The lane-change model to use.
Definition at line 193 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getLaneChangeModel(), and write().
SubParams SUMOVTypeParameter::lcParameter
Lane-changing parameter.
Definition at line 190 of file SUMOVTypeParameter.h.
Referenced by getLCParam(), SUMOVehicleParserHelper::parseLCParams(), and write().
SUMOReal SUMOVTypeParameter::length
The physical vehicle length.
Definition at line 134 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MESegment::jamThresholdForSpeed(), TraCIServerAPI_Lane::processGet(), MSVehicleType::setLength(), SUMOVTypeParameter(), and write().
SUMOTime SUMOVTypeParameter::loadingDuration
The time a container needs to get loaded on the vehicle.
Definition at line 160 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getLoadingDuration(), and write().
SUMOReal SUMOVTypeParameter::maxSpeed
The vehicle type's maximum speed [m/s].
Definition at line 138 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), ROPerson::computeIntermodal(), ROEdge::getEffort(), ROEdge::getEmissionEffort(), RORoutable::getMaxSpeed(), MSVehicleType::getMaxSpeed(), ROEdge::getMinimumTravelTime(), ROEdge::getNoiseEffort(), ROEdge::getTravelTime(), MSVehicleType::setMaxSpeed(), SUMOVTypeParameter(), and write().
SUMOReal SUMOVTypeParameter::maxSpeedLat
The vehicle type's maximum lateral speed [m/s].
Definition at line 196 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getMaxSpeedLat(), and write().
SUMOReal SUMOVTypeParameter::minGap
This class' free space in front of the vehicle itself.
Definition at line 136 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getLengthWithGap(), MSVehicleType::getMinGap(), MESegment::jamThresholdForSpeed(), MSVehicleType::setMinGap(), SUMOVTypeParameter(), and write().
SUMOReal SUMOVTypeParameter::minGapLat
The vehicle type's minimum lateral gap [m].
Definition at line 200 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getMinGapLat(), and write().
bool SUMOVTypeParameter::onlyReferenced mutable
Information whether this is a type-stub, being only referenced but not defined (needed by routers)
Definition at line 210 of file SUMOVTypeParameter.h.
Referenced by RONet::RONet(), and write().
std::string SUMOVTypeParameter::osgFile
3D model file for this class
Definition at line 175 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getOSGFile(), SUMOVTypeParameter(), and write().
int SUMOVTypeParameter::personCapacity
The person capacity of the vehicle.
Definition at line 154 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getPersonCapacity(), SUMOVTypeParameter(), and write().
bool SUMOVTypeParameter::saved mutable
Information whether this type was already saved (needed by routers)
Definition at line 207 of file SUMOVTypeParameter.h.
Referenced by ROVehicle::saveAsXML(), and ROPerson::saveAsXML().
int SUMOVTypeParameter::setParameter
Information for the router which parameter were set.
Definition at line 203 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleControl::MSVehicleControl(), SUMOVehicleParserHelper::parseVTypeEmbedded(), RONet::RONet(), MSVehicleType::wasSet(), and wasSet().
SUMOVehicleShape SUMOVTypeParameter::shape
This class' shape.
Definition at line 172 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getGuiShape(), MSVehicleType::setShape(), SUMOVTypeParameter(), and write().
SUMOReal SUMOVTypeParameter::speedDev
The standard deviation for speed variations.
Definition at line 144 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::computeChosenSpeedDeviation(), MSVehicleType::getSpeedDeviation(), MSVehicleType::setSpeedDeviation(), and write().
SUMOReal SUMOVTypeParameter::speedFactor
The factor by which the maximum speed may deviate from the allowed max speed on the street.
Definition at line 142 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::computeChosenSpeedDeviation(), ROVehicle::getChosenSpeedFactor(), MSVehicleType::getSpeedFactor(), ROEdge::getTravelTime(), MSVehicleType::setSpeedFactor(), and write().
SUMOVehicleClass SUMOVTypeParameter::vehicleClass
The vehicle's class.
Definition at line 150 of file SUMOVTypeParameter.h.
Referenced by MSVehicleType::build(), ROEdge::getEmissionEffort(), MSBaseVehicle::getVClass(), RORoutable::getVClass(), MSVehicleType::getVehicleClass(), MSVehicleType::setVClass(), and write().
SUMOReal SUMOVTypeParameter::width
This class' width.
Definition at line 166 of file SUMOVTypeParameter.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), MSVehicleType::getWidth(), MSVehicleType::setWidth(), SUMOVTypeParameter(), and write().
The documentation for this class was generated from the following files:
SUMOVTypeParameter.h
SUMOVTypeParameter.cpp