SUMO - Simulation of Urban MObility: GUIE3Collector::MyWrapper Class Reference
GUIE3Collector::MyWrapper Class Reference
#include <GUIE3Collector.h>
Data Structures
struct SingleCrossingDefinition
Representation of a single crossing point.
Public Member Functions
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawName (const Position &pos, const SUMOReal scale, const GUIVisualizationTextSettings &settings, const SUMOReal angle=0) const
draw name of item
GUIE3Collector & getDetector ()
Returns the detector itself.
MyWrapper (GUIE3Collector &detector)
Constructor.
~MyWrapper ()
Destrutor.
inherited from GUIGlObject
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
virtual const std::string & getParentName () const
Returns the name of the parent object (if any)
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window (optional)
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static void clearDictionary ()
Clears the dictionary (the objects will not be deleted)
static GUIGlObject_AbstractAdd * get (const std::string &name)
Returns a named object.
static std::vector< GUIGlID > getIDList ()
Returns the list of gl-ids of all additional objects.
static const std::vector< GUIGlObject_AbstractAdd * > & getObjectList ()
Returns the list of all additional objects.
static void remove (GUIGlObject_AbstractAdd *o)
Removes an object.
Static Public Attributes
static const GUIGlID INVALID_ID = 0
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
SingleCrossingDefinition buildDefinition (const MSCrossSection &section)
Builds the description about the position of the entry/exit point.
void drawSingleCrossing (const Position &pos, SUMOReal rot, SUMOReal upscale) const
Draws a single entry/exit point.
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Static Protected Attributes
static std::vector< GUIGlObject_AbstractAdd * > myObjectList
The list of all addtional objects currently loaded.
static std::map< std::string, GUIGlObject_AbstractAdd * > myObjects
Map from names of loaded additional objects to the objects themselves.
Private Types
typedef std::vector< SingleCrossingDefinition > CrossingDefinitions
Definition of a list of cross (entry/exit-point) positions.
Private Attributes
Boundary myBoundary
The detector's boundary.
GUIE3Collector & myDetector
The wrapped detector.
CrossingDefinitions myEntryDefinitions
The list of entry positions.
CrossingDefinitions myExitDefinitions
The list of exit positions.
Detailed Description
A GUIE3Collector-visualiser
Definition at line 89 of file GUIE3Collector.h.
Member Typedef Documentation
typedef std::vector<SingleCrossingDefinition> GUIE3Collector::MyWrapper::CrossingDefinitions private
Definition of a list of cross (entry/exit-point) positions.
Definition at line 159 of file GUIE3Collector.h.
Constructor & Destructor Documentation
GUIE3Collector::MyWrapper::MyWrapper (GUIE3Collector & detector)
Constructor.
Definition at line 52 of file GUIE3Collector.cpp.
References Boundary::add(), buildDefinition(), GUIE3Collector::getEntries(), GUIE3Collector::getExits(), myBoundary, myEntryDefinitions, myExitDefinitions, and GUIE3Collector::MyWrapper::SingleCrossingDefinition::myFGPosition.
GUIE3Collector::MyWrapper::~MyWrapper ()
Destrutor.
Definition at line 71 of file GUIE3Collector.cpp.
Member Function Documentation
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 258 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 187 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
GUIE3Collector::MyWrapper::SingleCrossingDefinition GUIE3Collector::MyWrapper::buildDefinition (const MSCrossSection & section) protected
Builds the description about the position of the entry/exit point.
Definition at line 75 of file GUIE3Collector.cpp.
References MSLane::geometryPositionAtOffset(), MSLane::getShape(), GUIE3Collector::MyWrapper::SingleCrossingDefinition::myFGPosition, GUIE3Collector::MyWrapper::SingleCrossingDefinition::myFGRotation, MSCrossSection::myLane, MSCrossSection::myPosition, and PositionVector::rotationDegreeAtOffset().
Referenced by MyWrapper().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 196 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 177 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GNECrossing::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 237 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 206 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 249 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 219 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 228 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIBaseVehicle::getPopUpMenu().
void GUIGlObject_AbstractAdd::clearDictionary () static inherited
Clears the dictionary (the objects will not be deleted)
!! delete (*i).second;
Definition at line 66 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList, and GUIGlObject_AbstractAdd::myObjects.
Referenced by GUINet::~GUINet().
void GUIE3Collector::MyWrapper::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 103 of file GUIE3Collector.cpp.
References GUIVisualizationSettings::addName, GUIVisualizationSettings::addSize, GUIGlObject::drawName(), drawSingleCrossing(), getCenteringBoundary(), GUIVisualizationSizeSettings::getExaggeration(), GUIGlObject::getGlID(), GUIGlObject::getType(), myEntryDefinitions, myExitDefinitions, GUIVisualizationSettings::scale, and SUMOReal.
void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIBaseVehicle, GUIPerson, and GUIContainer.
Definition at line 156 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
void GUIGlObject::drawName (const Position & pos, const SUMOReal scale, const GUIVisualizationTextSettings & settings, const SUMOReal angle = 0) const inherited
draw name of item
Definition at line 286 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE3::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GUIPolygon::drawGL(), GNEVariableSpeedSignal::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GNERouteProbe::drawGL(), GNEEdge::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIEdge::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GNERerouter::drawGL(), and GUIBaseVehicle::drawOnPos().
void GUIE3Collector::MyWrapper::drawSingleCrossing (const Position & pos, SUMOReal rot, SUMOReal upscale) const protected
Draws a single entry/exit point.
Definition at line 125 of file GUIE3Collector.cpp.
References GLHelper::drawBoxLine(), GLHelper::drawTriangleAtEnd(), SUMOReal, Position::x(), and Position::y().
Referenced by drawGL().
GUIGlObject_AbstractAdd * GUIGlObject_AbstractAdd::get (const std::string & name) static inherited
Returns a named object.
Definition at line 77 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjects.
Boundary GUIE3Collector::MyWrapper::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 154 of file GUIE3Collector.cpp.
References Boundary::grow(), and myBoundary.
Referenced by drawGL().
GUIE3Collector & GUIE3Collector::MyWrapper::getDetector ()
Returns the detector itself.
Definition at line 162 of file GUIE3Collector.cpp.
References myDetector.
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 111 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 123 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GUIVehicle::drawAction_drawPersonsAndContainers(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE3::drawGL(), GNEInternalLane::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GNERouteProbe::drawGL(), GNELane::drawGL(), GNEEdge::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), GUIEdge::drawGL(), GNEConnection::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GNERerouter::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GUIContainer::getColorValue(), GNEJunction::getColorValue(), GUIPerson::getColorValue(), GNELane::getColorValue(), GUILane::getColorValue(), GUIEdge::getIDs(), GNEEdge::getLaneGlIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNECalibrator::GNECalibrator(), GNERouteProbe::GNERouteProbe(), GNEVaporizer::GNEVaporizer(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onLeftBtnPress(), GUISUMOAbstractView::removeAdditionalGLVisualisation(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUIVehicle::selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), and GUIGlObject::~GUIGlObject().
std::vector< GUIGlID > GUIGlObject_AbstractAdd::getIDList () static inherited
Returns the list of gl-ids of all additional objects.
Definition at line 100 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList.
Referenced by GUISUMOViewParent::onCmdLocate().
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 137 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNEPOI::getAttribute(), GNECrossing::getAttribute(), GNEJunction::getAttribute(), GNEPoly::getAttribute(), GNEEdge::getAttribute(), GNELane::getAttribute(), GNELane::getParentName(), GNENetElement::getParentName(), GNEDetectorE3::getParentName(), GNEVaporizer::getParentName(), GNEVariableSpeedSignal::getParentName(), GNERouteProbe::getParentName(), GNEStoppingPlace::getParentName(), GNECalibrator::getParentName(), GNEDetector::getParentName(), GNEAdditional::getParentName(), GNERerouter::getParentName(), GNEAdditional::getPopUpMenu(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GNEEdge::moveGeometry(), GNEPoly::moveGeometry(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEViewNet::onCmdNodeShape(), GNEViewNet::onLeftBtnPress(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNENet::replaceJunctionByGeometry(), GNENet::retrieveAttributeCarriers(), GNEAdditional::setAdditionalID(), GNEEdge::setAttribute(), GNENet::splitEdge(), and GNEConnectorFrame::updateDescription().
const std::vector< GUIGlObject_AbstractAdd * > & GUIGlObject_AbstractAdd::getObjectList () static inherited
Returns the list of all additional objects.
Definition at line 94 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject_AbstractAdd::myObjectList.
Referenced by GNEPOI::saveToFile().
GUIParameterTableWindow * GUIE3Collector::MyWrapper::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 84 of file GUIE3Collector.cpp.
References GUIParameterTableWindow::closeBuilding(), MSE3Collector::getCurrentHaltingNumber(), MSE3Collector::getCurrentMeanSpeed(), MSE3Collector::getVehiclesWithin(), GUIParameterTableWindow::mkItem(), and myDetector.
const std::string & GUIGlObject::getParentName () const virtual inherited
Returns the name of the parent object (if any)
Returns
This object's parent id
Reimplemented in GNERerouter, GNEAdditional, GNEAdditionalSet, GNEDetector, GNECalibrator, GNEStoppingPlace, GNERouteProbe, GNEVariableSpeedSignal, GNEVaporizer, GUILane, GNEDetectorE3, GNENetElement, and GNELane.
Definition at line 117 of file GUIGlObject.cpp.
References StringUtils::emptyString.
Referenced by GUIGLObjectPopupMenu::onCmdCopyEdgeName().
GUIGLObjectPopupMenu * GUIDetectorWrapper::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 59 of file GUIDetectorWrapper.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), and GUIGlObject::buildShowParamsPopupEntry().
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 150 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEAdditionalSet::drawConnections(), GNEDetector::drawDetectorIcon(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE3::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GNELane::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GNERerouter::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorE2::getAttribute(), GNEContainerStop::getAttribute(), GNEBusStop::getAttribute(), GNEDetectorE3::getAttribute(), GNEVaporizer::getAttribute(), GNEVariableSpeedSignal::getAttribute(), GNERouteProbe::getAttribute(), GNEChargingStation::getAttribute(), GNECalibrator::getAttribute(), GNERerouter::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNEJunction::getColorValue(), GNELane::getColorValue(), GUILane::getColorValue(), GNEViewNet::getEdgeAtCursorPosition(), GNEViewNet::getEdgesAtCursorPosition(), GNEViewNet::getJunctionAtCursorPosition(), GNEViewNet::getLaneAtCurserPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEDetectorE1::isValid(), GNEDetectorE2::isValid(), GNEContainerStop::isValid(), GNEBusStop::isValid(), GNEDetectorE3::isValid(), GNEVaporizer::isValid(), GNEVariableSpeedSignal::isValid(), GNERouteProbe::isValid(), GNEChargingStation::isValid(), GNECalibrator::isValid(), GNERerouter::isValid(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onDoubleClicked(), GNEViewNet::onLeftBtnPress(), LayeredRTree::selectLayer(), GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEDetectorE1::setAttribute(), GNEDetectorE2::setAttribute(), GNEContainerStop::setAttribute(), GNEBusStop::setAttribute(), GNEDetectorE3::setAttribute(), GNEVaporizer::setAttribute(), GNEVariableSpeedSignal::setAttribute(), GNERouteProbe::setAttribute(), GNEChargingStation::setAttribute(), GNECalibrator::setAttribute(), GNERerouter::setAttribute(), GNEJunction::setColor(), and GUISelectedStorage::toggleSelection().
GUIParameterTableWindow * GUIGlObject::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own type parameter window (optional)
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Reimplemented in GUIVehicle, GUIBaseVehicle, and GUIMEVehicle.
Definition at line 129 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
Referenced by GUIGLObjectPopupMenu::onCmdShowTypePars().
void GUIGlObject_AbstractAdd::remove (GUIGlObject_AbstractAdd * o) static inherited
Removes an object.
Definition at line 87 of file GUIGlObject_AbstractAdd.cpp.
References GUIGlObject::getFullName(), GUIGlObject_AbstractAdd::myObjectList, and GUIGlObject_AbstractAdd::myObjects.
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 264 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 143 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNENet::renameJunction(), GNEAdditional::setAdditionalID(), GNELane::setIndex(), and GNEEdge::setMicrosimID().
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 273 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
Field Documentation
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 77 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
Boundary GUIE3Collector::MyWrapper::myBoundary private
The detector's boundary.
Definition at line 156 of file GUIE3Collector.h.
Referenced by getCenteringBoundary(), and MyWrapper().
GUIE3Collector& GUIE3Collector::MyWrapper::myDetector private
The wrapped detector.
Definition at line 153 of file GUIE3Collector.h.
Referenced by getDetector(), and getParameterWindow().
CrossingDefinitions GUIE3Collector::MyWrapper::myEntryDefinitions private
The list of entry positions.
Definition at line 162 of file GUIE3Collector.h.
Referenced by drawGL(), and MyWrapper().
CrossingDefinitions GUIE3Collector::MyWrapper::myExitDefinitions private
The list of exit positions.
Definition at line 165 of file GUIE3Collector.h.
Referenced by drawGL(), and MyWrapper().
std::vector< GUIGlObject_AbstractAdd * > GUIGlObject_AbstractAdd::myObjectList static protected inherited
The list of all addtional objects currently loaded.
Definition at line 78 of file GUIGlObject_AbstractAdd.h.
Referenced by GUIGlObject_AbstractAdd::clearDictionary(), GUIGlObject_AbstractAdd::getIDList(), GUIGlObject_AbstractAdd::getObjectList(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), and GUIGlObject_AbstractAdd::remove().
std::map< std::string, GUIGlObject_AbstractAdd * > GUIGlObject_AbstractAdd::myObjects static protected inherited
Map from names of loaded additional objects to the objects themselves.
Definition at line 75 of file GUIGlObject_AbstractAdd.h.
Referenced by GUIGlObject_AbstractAdd::clearDictionary(), GUIGlObject_AbstractAdd::get(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), and GUIGlObject_AbstractAdd::remove().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 76 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUIE3Collector.h
GUIE3Collector.cpp