SUMO - Simulation of Urban MObility: MESegment Class Reference
MESegment Class Reference
A single mesoscopic segment (cell)
#include <MESegment.h>
Public Types
typedef std::vector< MEVehicle * > Queue
typedef std::vector< Queue > Queues
Public Member Functions
void addReminders (MEVehicle *veh) const
add this lanes MoveReminders to the given vehicle
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
bool free () const
return whether this segment is considered free as opposed to jammed
SUMOReal getBruttoOccupancy () const
Returns the occupany of the segment (the sum of the vehicle lengths + minGaps)
int getCarNumber () const
Returns the total number of cars on the segment.
const MSEdge & getEdge () const
Returns the edge this segment belongs to.
SUMOTime getEntryBlockTime () const
return the next time at which a vehicle my enter this segment
SUMOTime getEventTime () const
Returns the (planned) time at which the next vehicle leaves this segment.
SUMOReal getEventTimeSeconds () const
Like getEventTime but returns seconds (for visualization)
SUMOReal getFlow () const
returns flow based on headway
const std::string & getID () const
Returns the id.
int getIndex () const
Returns the running index of the segment in the edge (0 is the most upstream).
SUMOReal getLength () const
Returns the length of the segment in meters.
SUMOReal getLengthGeometryFactor () const
return precomputed geometrical length / myLength
MSLink * getLink (const MEVehicle *veh, bool tlsPenalty=false) const
Returns the link the given car will use when passing the next junction.
SUMOReal getMeanSpeed (bool useCache) const
Returns the average speed of vehicles on the segment in meters per second. If there is no vehicle on the segment it returns the maximum allowed speed.
SUMOReal getMeanSpeed () const
wrapper to satisfy the FunctionBinding signature
SUMOTime getMinimumHeadwayTime () const
return the minimum headway-time with which vehicles may enter or leave this segment
SUMOTime getNextInsertionTime (SUMOTime earliestEntry) const
return a time after earliestEntry at which a vehicle may be inserted at full speed
MESegment * getNextSegment () const
Returns the following segment on the same edge (0 if it is the last).
const Queue & getQueue (int index) const
Returns the cars in the queue with the given index for visualization.
SUMOReal getRelativeJamThreshold () const
Returns the relative occupany of the segment (percentage of road used)) at which the segment is considered jammed.
SUMOReal getRelativeOccupancy () const
Returns the relative occupany of the segment (percentage of road used))
SUMOTime getTLSPenalty (const MEVehicle *veh) const
Returns the penalty time for passing a tls-controlled link (if using gMesoTLSPenalty > 0)
std::vector< const MEVehicle * > getVehicles () const
returns all vehicles (for debugging)
bool hasSpaceFor (const MEVehicle *veh, SUMOTime entryTime, bool init=false) const
Returns whether the given vehicle would still fit into the segment.
bool initialise (MEVehicle *veh, SUMOTime time)
Inserts (emits) vehicle into the segment.
bool isOpen (const MEVehicle *veh) const
Returns whether the vehicle may use the next link.
MESegment (const std::string &id, const MSEdge &parent, MESegment *next, SUMOReal length, SUMOReal speed, int idx, SUMOTime tauff, SUMOTime taufj, SUMOTime taujf, SUMOTime taujj, SUMOReal jamThresh, bool multiQueue, bool junctionControl, SUMOReal lengthGeometryFactor)
constructor
int numQueues () const
return the number of queues
void receive (MEVehicle *veh, SUMOTime time, bool isDepart=false, bool afterTeleport=false)
Adds the vehicle to the segment, adapting its parameters.
int remainingVehicleCapacity (const SUMOReal vehLength) const
return the remaining physical space on this segment
MEVehicle * removeCar (MEVehicle *v, SUMOTime leaveTime, MESegment *next)
Removes the given car from the edge's que.
void send (MEVehicle *veh, MESegment *next, SUMOTime time)
Removes the vehicle from the segment, adapting its parameters.
void setEntryBlockTime (SUMOTime entryBlockTime)
set the next time at which a vehicle my enter this segment
void setID (const std::string &newID)
resets the id
void setSpeed (SUMOReal newSpeed, SUMOTime currentTime, SUMOReal jamThresh=DO_NOT_PATCH_JAM_THRESHOLD)
reset mySpeed and patch the speed of all vehicles in it. Also set/recompute myJamThreshold
bool vaporizeAnyCar (SUMOTime currentTime)
tries to remove any car from this segment
void writeVehicles (OutputDevice &of) const
Measure collection
void addDetector (MSMoveReminder *data)
Adds a data collector for a detector to this segment.
void removeDetector (MSMoveReminder *data)
Removes a data collector for a detector from this segment.
void prepareDetectorForWriting (MSMoveReminder &data)
Updates data of a detector for all vehicle queues.
State saving/loading
void saveState (OutputDevice &out)
Saves the state of this segment into the given stream.
void loadState (std::vector< std::string > &vehIDs, MSVehicleControl &vc, const SUMOTime blockTime, const int queIdx)
Loads the state of this segment with the given parameters.
Static Public Member Functions
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
static bool isInvalid (const MESegment *segment)
whether the given segment is 0 or encodes vaporization
Static Public Attributes
static const SUMOReal DO_NOT_PATCH_JAM_THRESHOLD
Protected Attributes
std::string myID
The name of the object.
Private Member Functions
SUMOTime getTimeHeadway (bool predecessorIsFree, SUMOReal leaderLength)
SUMOReal jamThresholdForSpeed (SUMOReal speed, SUMOReal jamThresh) const
compute jam threshold for the given speed and jam-threshold option
bool limitedControlOverride (const MSLink *link) const
whether the given link may be passed because the option meso-junction-control.limited is set
MESegment (const MESegment &)
Invalidated copy constructor.
MESegment (const std::string &id)
constructor for dummy segment
SUMOTime newArrival (const MEVehicle *const v, SUMOReal newSpeed, SUMOTime currentTime)
compute the new arrival time when switching speed
MESegment & operator= (const MESegment &)
Invalidated assignment operator.
bool overtake ()
void recomputeJamThreshold (SUMOReal jamThresh)
compute a value for myJamThreshold if jamThresh is negative, compute a value which allows free flow at mySpeed interpret jamThresh as the relative occupation at which jam starts
void setSpeedForQueue (SUMOReal newSpeed, SUMOTime currentTime, SUMOTime blockTime, const std::vector< MEVehicle * > &vehs)
void updateDetectorsOnLeave (MEVehicle *v, SUMOTime currentTime, MESegment *next)
Updates data of all detectors for a leaving vehicle.
Private Attributes
SUMOReal myA
slope and axis offset for the jam-jam headway function
SUMOReal myB
std::vector< SUMOTime > myBlockTimes
The block times.
const SUMOReal myCapacity
The number of lanes * the length.
Queues myCarQues
The car queues. Vehicles are inserted in the front and removed in the back.
std::vector< MSMoveReminder * > myDetectorData
The data collection for all kinds of detectors.
const MSEdge & myEdge
The microsim edge this segment belongs to.
SUMOTime myEntryBlockTime
std::map< const MSEdge *, std::vector< int > > myFollowerMap
The follower edge to que index mapping for multi queue segments.
const SUMOReal myHeadwayCapacity
The capacity of the segment in number of cars, used only in time headway calculation This parameter has only an effect if tau_jf != tau_jj, which is not(!) the case per default.
const int myIndex
Running number of the segment in the edge.
SUMOReal myJamThreshold
The space (in m) which needs to be occupied before the segment is considered jammed.
const bool myJunctionControl
Whether junction control is enabled.
SUMOTime myLastMeanSpeedUpdate
the time at which myMeanSpeed was last updated
const SUMOReal myLength
The segment's length.
const SUMOReal myLengthGeometryFactor
SUMOReal myMeanSpeed
the mean speed on this segment. Updated at event time or on demand
MESegment * myNextSegment
The next segment of this edge, 0 if this is the last segment of this edge.
SUMOReal myOccupancy
The occupied space (in m) on the segment.
const SUMOTime myTau_ff
The time headway parameters, see the Eissfeldt thesis.
const SUMOTime myTau_fj
const SUMOTime myTau_jf
const SUMOTime myTau_jj
SUMOReal myTau_length
Headway paramter for computing gross time headyway from net time heawdway, length and edge speed.
const bool myTLSPenalty
Whether tls penalty is enabled.
Static Private Attributes
static MSEdge myDummyParent
static MESegment myVaporizationTarget
Detailed Description
A single mesoscopic segment (cell)
Definition at line 57 of file MESegment.h.
Member Typedef Documentation
typedef std::vector<MEVehicle*> MESegment::Queue
Definition at line 87 of file MESegment.h.
typedef std::vector<Queue> MESegment::Queues
Definition at line 88 of file MESegment.h.
Constructor & Destructor Documentation
MESegment::MESegment (const std::string & id, const MSEdge & parent, MESegment * next, SUMOReal length, SUMOReal speed, int idx, SUMOTime tauff, SUMOTime taufj, SUMOTime taujf, SUMOTime taujj, SUMOReal jamThresh, bool multiQueue, bool junctionControl, SUMOReal lengthGeometryFactor)
constructor
Parameters
[in] id The id of this segment (currently: "<EDGEID>:<SEGMENTNO>")
[in] parent The edge this segment is located within
[in] next The following segment (belonging to the same edge)
[in] length The segment's length
[in] speed The speed allowed on this segment
[in] idx The running index of this segment within the segment's edge
[in] tauff The factor for free-free headway time
[in] taufj The factor for free-jam headway time
[in] taujf The factor for jam-free headway time
[in] taujj The factor for jam-jam headway time
[in] jamThresh percentage of occupied space before the segment is jammed
[in] multiQueue whether to install multiple queues on this segment
[in] junctionControl whether junction control is enabled on this segment
[in] the quotient of geometrical length / given length
Todo:
recheck the id; using a ':' as divider is not really nice
Definition at line 71 of file MESegment.cpp.
References MSEdge::allowedLanes(), MSEdge::getLanes(), MSEdge::getNumSuccessors(), MSEdge::getSuccessors(), myBlockTimes, myCarQues, myFollowerMap, and recomputeJamThreshold().
MESegment::MESegment (const MESegment &) private
Invalidated copy constructor.
MESegment::MESegment (const std::string & id) private
constructor for dummy segment
Definition at line 125 of file MESegment.cpp.
Member Function Documentation
void MESegment::addDetector (MSMoveReminder * data)
Adds a data collector for a detector to this segment.
Parameters
[in] data The data collector to add
Definition at line 194 of file MESegment.cpp.
References myCarQues, and myDetectorData.
Referenced by MSMeanData::init(), MEInductLoop::MEInductLoop(), METriggeredCalibrator::METriggeredCalibrator(), MSRouteProbe::MSRouteProbe(), and MSTriggeredRerouter::MSTriggeredRerouter().
void MESegment::addReminders (MEVehicle * veh) const
add this lanes MoveReminders to the given vehicle
Definition at line 471 of file MESegment.cpp.
References MSBaseVehicle::addReminder(), and myDetectorData.
Referenced by receive().
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
bool MESegment::free () const inline
return whether this segment is considered free as opposed to jammed
Definition at line 347 of file MESegment.h.
References myJamThreshold, myOccupancy, and myTLSPenalty.
Referenced by getMeanSpeed(), getTimeHeadway(), and send().
SUMOReal MESegment::getBruttoOccupancy () const inline
Returns the occupany of the segment (the sum of the vehicle lengths + minGaps)
Returns
the occupany of the segment in meters
Definition at line 174 of file MESegment.h.
References myOccupancy.
Referenced by METriggeredCalibrator::invalidJam().
int MESegment::getCarNumber () const
Returns the total number of cars on the segment.
Returns
the total number of cars on the segment
Definition at line 288 of file MESegment.cpp.
References myCarQues, and SUMOReal.
Referenced by getFlow(), GUIEdge::getParameterWindow(), getTimeHeadway(), and MSXMLRawOut::writeEdge().
const MSEdge& MESegment::getEdge () const inline
Returns the edge this segment belongs to.
Returns
the edge this segment belongs to
Definition at line 272 of file MESegment.h.
References DO_NOT_PATCH_JAM_THRESHOLD, getEventTime(), myEdge, setSpeed(), and SUMOReal.
Referenced by MELoop::changeSegment(), METriggeredCalibrator::execute(), GUIMEVehicle::getColorValue(), GUIEdge::getParameterWindow(), METriggeredCalibrator::invalidJam(), MSStateHandler::myStartElement(), GUIMEInductLoop::MyWrapper::MyWrapper(), MEVehicle::saveState(), MEVehicle::setEventTime(), MELoop::teleportVehicle(), and MEInductLoop::writeXMLOutput().
SUMOTime MESegment::getEntryBlockTime () const inline
return the next time at which a vehicle my enter this segment
Definition at line 361 of file MESegment.h.
References myEntryBlockTime.
Referenced by MELoop::checkCar().
SUMOTime MESegment::getEventTime () const
Returns the (planned) time at which the next vehicle leaves this segment.
Returns
The time the vehicle thinks it leaves
Definition at line 616 of file MESegment.cpp.
References myCarQues, and SUMOTime_MAX.
Referenced by MELoop::checkCar(), getEdge(), and getEventTimeSeconds().
SUMOReal MESegment::getEventTimeSeconds () const inline
Like getEventTime but returns seconds (for visualization)
Definition at line 289 of file MESegment.h.
References getEventTime(), getFlow(), getVehicles(), loadState(), saveState(), STEPS2TIME, and SUMOReal.
Referenced by GUIEdge::getParameterWindow().
SUMOReal MESegment::getFlow () const
returns flow based on headway
Note
: returns magic number 10000 when headway cannot be computed
Definition at line 673 of file MESegment.cpp.
References getCarNumber(), getMeanSpeed(), and myLength.
Referenced by getEventTimeSeconds(), and GUIEdge::getParameterWindow().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciBusOrContainerStop(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNEConnectorFrame::buildIinternalLanes(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), NLDetectorBuilder::convUncontE2PosLength(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSVehicle::getBackPosition(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), GNEEdge::getDest(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), MSE2Collector::getEstimateQueueLength(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), GNEEdge::getSource(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_BTsender::notifyMove(), MSE2Collector::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_SL2015::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_LC2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_ArealDetector::processGet(), TraCIServerAPI_Lane::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), MSBaseVehicle::reroute(), MSLane::resetPartialOccupation(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), MSLane::saveState(), MSDevice_Battery::setAirDragCoefficient(), NBNodeCont::setAsTLControlled(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), MSDevice_Battery::setConstantPowerIntake(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), MSDevice_Battery::setFrontSurfaceArea(), MSDevice_Battery::setInternalMomentOfInertia(), GNEJunction::setLogicValid(), MSDevice_Battery::setMass(), MSDevice_Battery::setMaximumBatteryCapacity(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSDevice_Battery::setPropulsionEfficiency(), MSDevice_Battery::setRadialDragCoefficient(), MSDevice_Battery::setRecuperationEfficiency(), MSLink::setRequestInformation(), MSDevice_Battery::setRollDragCoefficient(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), operator<<(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
int MESegment::getIndex () const inline
Returns the running index of the segment in the edge (0 is the most upstream).
Returns
the running index of the segment in the edge
Definition at line 150 of file MESegment.h.
References myIndex.
Referenced by MELoop::changeSegment(), GUIEdge::getParameterWindow(), MEVehicle::getPositionOnLane(), MEVehicle::loadState(), MEVehicle::saveState(), MELoop::teleportVehicle(), MEVehicle::updateDetectorForWriting(), and MEVehicle::updateDetectors().
SUMOReal MESegment::getLength () const inline
Returns the length of the segment in meters.
Returns
the length of the segment
Definition at line 166 of file MESegment.h.
References myLength.
Referenced by MEVehicle::getAverageSpeed(), MEVehicle::getConservativeSpeed(), GUIEdge::getParameterWindow(), MEVehicle::getPositionOnLane(), MELoop::getSegmentForEdge(), MELoop::setApproaching(), MEVehicle::updateDetectorForWriting(), and MEVehicle::updateDetectors().
SUMOReal MESegment::getLengthGeometryFactor () const inline
return precomputed geometrical length / myLength
Definition at line 381 of file MESegment.h.
References getTimeHeadway(), getTLSPenalty(), jamThresholdForSpeed(), limitedControlOverride(), myLengthGeometryFactor, newArrival(), overtake(), recomputeJamThreshold(), setSpeedForQueue(), SUMOReal, and updateDetectorsOnLeave().
MSLink * MESegment::getLink (const MEVehicle * veh, bool tlsPenalty = false) const
Returns the link the given car will use when passing the next junction.
This returns non-zero values only for the last segment and only if junction control is enabled.
Parameters
[in] veh The vehicle in question
[in] tlsPenalty Whether the link should be returned for computing tlsPenalty
Returns
The link to use or 0 without junction control
Definition at line 387 of file MESegment.cpp.
References MSEdge::getLanes(), MSLane::getLinkCont(), MEVehicle::getQueIndex(), myEdge, myJunctionControl, and MSBaseVehicle::succEdge().
Referenced by MELoop::checkCar(), getMeanSpeed(), getTLSPenalty(), isOpen(), loadState(), receive(), MEVehicle::replaceRoute(), send(), and setSpeedForQueue().
SUMOReal MESegment::getMeanSpeed (bool useCache) const
Returns the average speed of vehicles on the segment in meters per second. If there is no vehicle on the segment it returns the maximum allowed speed.
Parameters
[in] useCache whether to use a cached value if available
Note
this value is cached in myMeanSpeed. Since caching only takes place once every simstep there is a potential for side-influences (i.e. GUI calls to this method, ...) For that reason the simulation logic doesn't use the cache. This shouldn't matter much for speed since it is only used during initializsation of vehicles onto the segment.
Returns
the average speed on the segment
Definition at line 298 of file MESegment.cpp.
References free(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSEdge::getSpeedLimit(), myCarQues, myEdge, myLastMeanSpeedUpdate, myMeanSpeed, myTau_ff, myTau_jf, and SUMOReal.
Referenced by METriggeredCalibrator::invalidJam().
SUMOReal MESegment::getMeanSpeed () const inline
wrapper to satisfy the FunctionBinding signature
Definition at line 207 of file MESegment.h.
References getLink(), isOpen(), receive(), removeCar(), send(), vaporizeAnyCar(), and writeVehicles().
Referenced by getFlow(), GUIEdge::getParameterWindow(), getRelativeJamThreshold(), and hasSpaceFor().
SUMOTime MESegment::getMinimumHeadwayTime () const inline
return the minimum headway-time with which vehicles may enter or leave this segment
Definition at line 371 of file MESegment.h.
References myTau_ff.
Referenced by METriggeredCalibrator::maximumInflow().
SUMOTime MESegment::getNextInsertionTime (SUMOTime earliestEntry) const
return a time after earliestEntry at which a vehicle may be inserted at full speed
Definition at line 372 of file MESegment.cpp.
References MSEdge::getSpeedLimit(), MAX2(), MAX3(), myBlockTimes, myCarQues, myEdge, myEntryBlockTime, myLength, and TIME2STEPS.
Referenced by METriggeredCalibrator::execute(), and isInvalid().
MESegment* MESegment::getNextSegment () const inline
Returns the following segment on the same edge (0 if it is the last).
Returns
the following segment on the same edge (0 if it is the last)
Definition at line 158 of file MESegment.h.
References myNextSegment.
Referenced by METriggeredCalibrator::execute(), MELoop::getSegmentForEdge(), MSMeanData::init(), MSEdge::insertVehicle(), MEVehicle::loadState(), MSRouteProbe::MSRouteProbe(), MSStateHandler::myStartElement(), MELoop::nextSegment(), MSLaneSpeedTrigger::processCommand(), MSMeanData::resetOnly(), MELoop::teleportVehicle(), MSXMLRawOut::writeEdge(), MSMeanData::writeEdge(), and MELoop::~MELoop().
const Queue& MESegment::getQueue (int index) const inline
Returns the cars in the queue with the given index for visualization.
Returns
the Queue (XXX not thread-safe!)
Definition at line 141 of file MESegment.h.
References myCarQues.
SUMOReal MESegment::getRelativeJamThreshold () const inline
Returns the relative occupany of the segment (percentage of road used)) at which the segment is considered jammed.
Returns
the jam treshold of the segment in percent
Definition at line 190 of file MESegment.h.
References getMeanSpeed(), myCapacity, myJamThreshold, and SUMOReal.
Referenced by GUIEdge::getParameterWindow().
SUMOReal MESegment::getRelativeOccupancy () const inline
Returns the relative occupany of the segment (percentage of road used))
Returns
the occupany of the segment in percent
Definition at line 182 of file MESegment.h.
References myCapacity, and myOccupancy.
Referenced by GUIEdge::getParameterWindow().
SUMOTime MESegment::getTimeHeadway (bool predecessorIsFree, SUMOReal leaderLength) private
Definition at line 356 of file MESegment.cpp.
References free(), getCarNumber(), myA, myB, myTau_ff, myTau_fj, myTau_jf, myTau_length, and TIME2STEPS.
Referenced by getLengthGeometryFactor(), and send().
SUMOTime MESegment::getTLSPenalty (const MEVehicle * veh) const
Returns the penalty time for passing a tls-controlled link (if using gMesoTLSPenalty > 0)
Parameters
[in] veh The vehicle in question
Returns
The time penalty
Definition at line 679 of file MESegment.cpp.
References getLink(), MSLink::getMesoTLSPenalty(), MSLink::isTLSControlled(), and myTLSPenalty.
Referenced by MEVehicle::getCurrentTLSPenaltySeconds(), getLengthGeometryFactor(), and receive().
std::vector< const MEVehicle * > MESegment::getVehicles () const
returns all vehicles (for debugging)
Definition at line 663 of file MESegment.cpp.
References myCarQues, and SUMOReal.
Referenced by getEventTimeSeconds().
bool MESegment::hasSpaceFor (const MEVehicle * veh, SUMOTime entryTime, bool init = false) const
Returns whether the given vehicle would still fit into the segment.
Parameters
[in] veh The vehicle to check space for
[in] entryTime The time at which the vehicle wants to enter
[in] init whether the check is done at insertion time
Returns
true if the vehicle may be added to this segment, false otherwise
Definition at line 250 of file MESegment.cpp.
References MSVehicleType::getLengthWithGap(), getMeanSpeed(), MSBaseVehicle::getVehicleType(), jamThresholdForSpeed(), myCapacity, myEntryBlockTime, myOccupancy, and SUMOReal.
Referenced by MELoop::changeSegment(), MELoop::checkCar(), initialise(), MSEdge::insertVehicle(), and MELoop::teleportVehicle().
bool MESegment::initialise (MEVehicle * veh, SUMOTime time)
Inserts (emits) vehicle into the segment.
Parameters
[in] veh The vehicle to emit
[in] time The emission time
Returns
Whether the emission was successful
Definition at line 273 of file MESegment.cpp.
References MSGlobals::gCheckRoutes, MSBaseVehicle::getID(), hasSpaceFor(), MSBaseVehicle::hasValidRoute(), and receive().
Referenced by MSEdge::insertVehicle(), and METriggeredCalibrator::tryEmit().
static bool MESegment::isInvalid (const MESegment * segment) inline static
whether the given segment is 0 or encodes vaporization
Definition at line 338 of file MESegment.h.
References getNextInsertionTime(), and myVaporizationTarget.
Referenced by MELoop::changeSegment(), and send().
bool MESegment::isOpen (const MEVehicle * veh) const
Returns whether the vehicle may use the next link.
In case of disabled junction control it returns always true.
Parameters
[in] veh The vehicle in question
Returns
Whether it may pass to the next segment
Definition at line 418 of file MESegment.cpp.
References MEVehicle::estimateLeaveSpeed(), MSVehicleType::getCarFollowModel(), MEVehicle::getEventTime(), MSBaseVehicle::getImpatience(), MSVehicleType::getLengthWithGap(), getLink(), MSCFModel::getMaxDecel(), MEVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MEVehicle::getWaitingTime(), MSLink::havePriority(), limitedControlOverride(), myTLSPenalty, and MSLink::opened().
Referenced by getMeanSpeed(), and MEVehicle::mayProceed().
SUMOReal MESegment::jamThresholdForSpeed (SUMOReal speed, SUMOReal jamThresh) const private
compute jam threshold for the given speed and jam-threshold option
Definition at line 180 of file MESegment.cpp.
References SUMOVTypeParameter::getDefault(), SUMOVTypeParameter::length, max, SUMOVTypeParameter::minGap, myLength, myTau_ff, myTau_length, STEPS2TIME, and SUMOReal.
Referenced by getLengthGeometryFactor(), hasSpaceFor(), and recomputeJamThreshold().
bool MESegment::limitedControlOverride (const MSLink * link) const private
whether the given link may be passed because the option meso-junction-control.limited is set
Definition at line 434 of file MESegment.cpp.
References MSLane::getEdge(), MSLink::getLane(), MELoop::getSegmentForEdge(), MSGlobals::gMesoLimitedJunctionControl, MSGlobals::gMesoNet, myJamThreshold, and myOccupancy.
Referenced by getLengthGeometryFactor(), and isOpen().
void MESegment::loadState (std::vector< std::string > & vehIDs, MSVehicleControl & vc, const SUMOTime blockTime, const int queIdx)
Loads the state of this segment with the given parameters.
This method is called for every internal que the segment has. Every vehicle is retrieved from the given MSVehicleControl and added to this segment. Then, the internal queues that store vehicles dependant to their next edge are filled the same way. Then, the departure of last vehicles onto the next edge are restored.
Parameters
[in] vehIDs The vehicle ids for the current que
[in] vc The vehicle control to retrieve references vehicles from
[in] blockTime The time the last vehicle left the que
[in] queIdx The index of the current que
Todo:
What about throwing an IOError?
What about throwing an error if something else fails (a vehicle can not be referenced)?
Definition at line 643 of file MESegment.cpp.
References MELoop::addLeaderCar(), MSVehicleType::getLengthWithGap(), getLink(), MEVehicle::getSegment(), MSVehicleControl::getVehicle(), MSBaseVehicle::getVehicleType(), MSGlobals::gMesoNet, MIN2(), myBlockTimes, myCapacity, myCarQues, and myOccupancy.
Referenced by getEventTimeSeconds(), and MSStateHandler::myStartElement().
SUMOTime MESegment::newArrival (const MEVehicle *const v, SUMOReal newSpeed, SUMOTime currentTime) private
compute the new arrival time when switching speed
Definition at line 595 of file MESegment.cpp.
References MEVehicle::getLastEntryTime(), MEVehicle::getSpeed(), MAX2(), MIN2(), myLength, STEPS2TIME, SUMOReal, and TIME2STEPS.
Referenced by getLengthGeometryFactor(), and setSpeedForQueue().
int MESegment::numQueues () const inline
return the number of queues
Definition at line 135 of file MESegment.h.
References myCarQues.
MESegment& MESegment::operator= (const MESegment &) private
Invalidated assignment operator.
bool MESegment::overtake () private
Definition at line 465 of file MESegment.cpp.
References MSGlobals::gMesoOvertaking, myCapacity, myLength, myOccupancy, and RandHelper::rand().
Referenced by getLengthGeometryFactor(), and receive().
void MESegment::prepareDetectorForWriting (MSMoveReminder & data)
Updates data of a detector for all vehicle queues.
Parameters
[in] data The detector data to update
Definition at line 236 of file MESegment.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), MAX2(), myCarQues, and myTau_ff.
Referenced by METriggeredCalibrator::execute(), MSMeanData::init(), MSMeanData::resetOnly(), MSMeanData::writeEdge(), and MEInductLoop::writeXMLOutput().
void MESegment::receive (MEVehicle * veh, SUMOTime time, bool isDepart = false, bool afterTeleport = false)
Adds the vehicle to the segment, adapting its parameters.
Parameters
[in] veh The vehicle in question
[in] time the leave time
[in] isDepart whether the vehicle just departed
Todo:
Isn't always time == veh->getEventTime?
Definition at line 478 of file MESegment.cpp.
References MSBaseVehicle::activateReminders(), MELoop::addLeaderCar(), addReminders(), MSBaseVehicle::getEdge(), MEVehicle::getEventTime(), MSNet::getInstance(), MSVehicleType::getLengthWithGap(), getLink(), MEVehicle::getSpeed(), MEVehicle::getStoptime(), getTLSPenalty(), MSNet::getVehicleControl(), MSEdge::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSGlobals::gMesoNet, MEVehicle::hasArrived(), MSEdge::lock(), MAX2(), MESO_MIN_SPEED, MIN2(), MEVehicle::moveRoutePointer(), myBlockTimes, myCapacity, myCarQues, myEdge, myEntryBlockTime, myFollowerMap, myIndex, myLength, myOccupancy, myTau_ff, MSMoveReminder::NOTIFICATION_DEPARTED, MSMoveReminder::NOTIFICATION_JUNCTION, MSMoveReminder::NOTIFICATION_SEGMENT, MSBaseVehicle::onDepart(), overtake(), MELoop::removeLeaderCar(), MSVehicleControl::scheduleVehicleRemoval(), MEVehicle::setBlockTime(), MEVehicle::setEventTime(), MEVehicle::setLastEntryTime(), MEVehicle::setSegment(), MSBaseVehicle::succEdge(), SUMOReal, SUMOTime_MAX, TIME2STEPS, MSEdge::unlock(), and updateDetectorsOnLeave().
Referenced by MELoop::changeSegment(), getMeanSpeed(), and initialise().
void MESegment::recomputeJamThreshold (SUMOReal jamThresh) private
compute a value for myJamThreshold if jamThresh is negative, compute a value which allows free flow at mySpeed interpret jamThresh as the relative occupation at which jam starts
Definition at line 137 of file MESegment.cpp.
References DO_NOT_PATCH_JAM_THRESHOLD, MSEdge::getSpeedLimit(), jamThresholdForSpeed(), myA, myB, myCapacity, myEdge, myHeadwayCapacity, myJamThreshold, myTau_jf, myTau_jj, STEPS2TIME, and SUMOReal.
Referenced by getLengthGeometryFactor(), MESegment(), and setSpeed().
int MESegment::remainingVehicleCapacity (const SUMOReal vehLength) const inline
return the remaining physical space on this segment
Definition at line 352 of file MESegment.h.
References myCapacity, and myOccupancy.
Referenced by METriggeredCalibrator::remainingVehicleCapacity().
MEVehicle * MESegment::removeCar (MEVehicle * v, SUMOTime leaveTime, MESegment * next)
Removes the given car from the edge's que.
Parameters
[in] v The vehicle to remove
[in] leaveTime The time at which the vehicle is leaving the que
[in] next The next segment for this vehicle
Returns
The next first vehicle to add to the net's que
Definition at line 334 of file MESegment.cpp.
References MSVehicleType::getLengthWithGap(), MEVehicle::getQueIndex(), MSBaseVehicle::getVehicleType(), MSEdge::lock(), MAX2(), myCarQues, myEdge, myOccupancy, SUMOReal, MSEdge::unlock(), and updateDetectorsOnLeave().
Referenced by getMeanSpeed(), and send().
void MESegment::removeDetector (MSMoveReminder * data)
Removes a data collector for a detector from this segment.
Parameters
[in] data The data collector to remove
Definition at line 205 of file MESegment.cpp.
References myCarQues, and myDetectorData.
Referenced by METriggeredCalibrator::~METriggeredCalibrator().
void MESegment::saveState (OutputDevice & out)
Saves the state of this segment into the given stream.
Some internal values which must be restored are saved as well as ids of the vehicles stored in internal queues and the last departures of connected edges.
Parameters
Definition at line 631 of file MESegment.cpp.
References OutputDevice::closeTag(), myBlockTimes, myCarQues, OutputDevice::openTag(), SUMO_ATTR_TIME, SUMO_ATTR_VALUE, SUMO_TAG_SEGMENT, SUMO_TAG_VIEWSETTINGS_VEHICLES, and OutputDevice::writeAttr().
Referenced by getEventTimeSeconds().
void MESegment::send (MEVehicle * veh, MESegment * next, SUMOTime time)
Removes the vehicle from the segment, adapting its parameters.
Parameters
[in] veh The vehicle in question
[in] next The subsequent segment for delay calculation
[in] time the leave time
Todo:
Isn't always time == veh->getEventTime?
Definition at line 447 of file MESegment.cpp.
References MELoop::addLeaderCar(), free(), MEVehicle::getEventTime(), MSVehicleType::getLengthWithGap(), getLink(), MEVehicle::getQueIndex(), getTimeHeadway(), MSBaseVehicle::getVehicleType(), MSGlobals::gMesoNet, isInvalid(), MAX2(), myBlockTimes, removeCar(), and MEVehicle::setEventTime().
Referenced by MELoop::changeSegment(), getMeanSpeed(), and MELoop::teleportVehicle().
void MESegment::setEntryBlockTime (SUMOTime entryBlockTime) inline
set the next time at which a vehicle my enter this segment
Definition at line 366 of file MESegment.h.
References myEntryBlockTime.
Referenced by MELoop::teleportVehicle().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
void MESegment::setSpeed (SUMOReal newSpeed, SUMOTime currentTime, SUMOReal jamThresh = DO_NOT_PATCH_JAM_THRESHOLD)
reset mySpeed and patch the speed of all vehicles in it. Also set/recompute myJamThreshold
Parameters
[in] jamThresh follows the semantic of option meso-jam-threshold
Definition at line 604 of file MESegment.cpp.
References myBlockTimes, myCarQues, recomputeJamThreshold(), and setSpeedForQueue().
Referenced by METriggeredCalibrator::execute(), getEdge(), and MSLaneSpeedTrigger::processCommand().
void MESegment::setSpeedForQueue (SUMOReal newSpeed, SUMOTime currentTime, SUMOTime blockTime, const std::vector< MEVehicle * > & vehs) private
Definition at line 576 of file MESegment.cpp.
References MELoop::addLeaderCar(), MEVehicle::getEventTime(), getLink(), MSGlobals::gMesoNet, MAX2(), myTau_ff, newArrival(), MELoop::removeLeaderCar(), MEVehicle::setEventTime(), and MEVehicle::updateDetectors().
Referenced by getLengthGeometryFactor(), and setSpeed().
void MESegment::updateDetectorsOnLeave (MEVehicle * v, SUMOTime currentTime, MESegment * next) private
Updates data of all detectors for a leaving vehicle.
Parameters
[in] v The vehicle to update values for
[in] currentTime The leave time of the vehicle
[in] next The next segment on this vehicles route
Definition at line 220 of file MESegment.cpp.
References myNextSegment, myVaporizationTarget, MSMoveReminder::NOTIFICATION_ARRIVED, MSMoveReminder::NOTIFICATION_JUNCTION, MSMoveReminder::NOTIFICATION_SEGMENT, MSMoveReminder::NOTIFICATION_VAPORIZED, and MEVehicle::updateDetectors().
Referenced by getLengthGeometryFactor(), receive(), and removeCar().
bool MESegment::vaporizeAnyCar (SUMOTime currentTime)
tries to remove any car from this segment
Parameters
[in] currentTime the current time
Returns
Whether vaporization was successful
Note
: cars removed via this method do NOT count as arrivals
Definition at line 558 of file MESegment.cpp.
References MELoop::changeSegment(), MSGlobals::gMesoNet, myCarQues, myVaporizationTarget, and MELoop::removeLeaderCar().
Referenced by METriggeredCalibrator::execute(), and getMeanSpeed().
void MESegment::writeVehicles (OutputDevice & of) const
Definition at line 324 of file MESegment.cpp.
References myCarQues, and MSXMLRawOut::writeVehicle().
Referenced by getMeanSpeed(), and MSXMLRawOut::writeEdge().
Field Documentation
const SUMOReal MESegment::DO_NOT_PATCH_JAM_THRESHOLD static
Definition at line 375 of file MESegment.h.
Referenced by getEdge(), and recomputeJamThreshold().
SUMOReal MESegment::myA private
slope and axis offset for the jam-jam headway function
Definition at line 443 of file MESegment.h.
Referenced by getTimeHeadway(), and recomputeJamThreshold().
SUMOReal MESegment::myB private
Definition at line 443 of file MESegment.h.
Referenced by getTimeHeadway(), and recomputeJamThreshold().
std::vector<SUMOTime> MESegment::myBlockTimes private
The block times.
Definition at line 474 of file MESegment.h.
Referenced by getNextInsertionTime(), loadState(), MESegment(), receive(), saveState(), send(), and setSpeed().
const SUMOReal MESegment::myCapacity private
The number of lanes * the length.
Definition at line 450 of file MESegment.h.
Referenced by getRelativeJamThreshold(), getRelativeOccupancy(), hasSpaceFor(), loadState(), overtake(), receive(), recomputeJamThreshold(), and remainingVehicleCapacity().
Queues MESegment::myCarQues private
The car queues. Vehicles are inserted in the front and removed in the back.
Definition at line 468 of file MESegment.h.
Referenced by addDetector(), getCarNumber(), getEventTime(), getMeanSpeed(), getNextInsertionTime(), getQueue(), getVehicles(), loadState(), MESegment(), numQueues(), prepareDetectorForWriting(), receive(), removeCar(), removeDetector(), saveState(), setSpeed(), vaporizeAnyCar(), and writeVehicles().
std::vector<MSMoveReminder*> MESegment::myDetectorData private
The data collection for all kinds of detectors.
Definition at line 465 of file MESegment.h.
Referenced by addDetector(), addReminders(), and removeDetector().
MSEdge MESegment::myDummyParent static private
Definition at line 486 of file MESegment.h.
const MSEdge& MESegment::myEdge private
The microsim edge this segment belongs to.
Definition at line 426 of file MESegment.h.
Referenced by getEdge(), getLink(), getMeanSpeed(), getNextInsertionTime(), receive(), recomputeJamThreshold(), and removeCar().
SUMOTime MESegment::myEntryBlockTime private
Definition at line 479 of file MESegment.h.
Referenced by getEntryBlockTime(), getNextInsertionTime(), hasSpaceFor(), receive(), and setEntryBlockTime().
std::map<const MSEdge*, std::vector<int> > MESegment::myFollowerMap private
The follower edge to que index mapping for multi queue segments.
Definition at line 471 of file MESegment.h.
Referenced by MESegment(), and receive().
const SUMOReal MESegment::myHeadwayCapacity private
The capacity of the segment in number of cars, used only in time headway calculation This parameter has only an effect if tau_jf != tau_jj, which is not(!) the case per default.
Definition at line 447 of file MESegment.h.
Referenced by recomputeJamThreshold().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
const int MESegment::myIndex private
Running number of the segment in the edge.
Definition at line 435 of file MESegment.h.
Referenced by getIndex(), and receive().
SUMOReal MESegment::myJamThreshold private
The space (in m) which needs to be occupied before the segment is considered jammed.
Definition at line 462 of file MESegment.h.
Referenced by free(), getRelativeJamThreshold(), limitedControlOverride(), and recomputeJamThreshold().
const bool MESegment::myJunctionControl private
Whether junction control is enabled.
Definition at line 456 of file MESegment.h.
Referenced by getLink().
SUMOTime MESegment::myLastMeanSpeedUpdate mutable private
the time at which myMeanSpeed was last updated
Definition at line 493 of file MESegment.h.
Referenced by getMeanSpeed().
const SUMOReal MESegment::myLength private
The segment's length.
Definition at line 432 of file MESegment.h.
Referenced by getFlow(), getLength(), getNextInsertionTime(), jamThresholdForSpeed(), newArrival(), overtake(), and receive().
const SUMOReal MESegment::myLengthGeometryFactor private
Definition at line 482 of file MESegment.h.
Referenced by getLengthGeometryFactor().
SUMOReal MESegment::myMeanSpeed mutable private
the mean speed on this segment. Updated at event time or on demand
Definition at line 490 of file MESegment.h.
Referenced by getMeanSpeed().
MESegment* MESegment::myNextSegment private
The next segment of this edge, 0 if this is the last segment of this edge.
Definition at line 429 of file MESegment.h.
Referenced by getNextSegment(), and updateDetectorsOnLeave().
SUMOReal MESegment::myOccupancy private
The occupied space (in m) on the segment.
Definition at line 453 of file MESegment.h.
Referenced by free(), getBruttoOccupancy(), getRelativeOccupancy(), hasSpaceFor(), limitedControlOverride(), loadState(), overtake(), receive(), remainingVehicleCapacity(), and removeCar().
const SUMOTime MESegment::myTau_ff private
The time headway parameters, see the Eissfeldt thesis.
Definition at line 438 of file MESegment.h.
Referenced by getMeanSpeed(), getMinimumHeadwayTime(), getTimeHeadway(), jamThresholdForSpeed(), prepareDetectorForWriting(), receive(), and setSpeedForQueue().
const SUMOTime MESegment::myTau_fj private
Definition at line 438 of file MESegment.h.
Referenced by getTimeHeadway().
const SUMOTime MESegment::myTau_jf private
Definition at line 438 of file MESegment.h.
Referenced by getMeanSpeed(), getTimeHeadway(), and recomputeJamThreshold().
const SUMOTime MESegment::myTau_jj private
Definition at line 438 of file MESegment.h.
Referenced by recomputeJamThreshold().
SUMOReal MESegment::myTau_length private
Headway paramter for computing gross time headyway from net time heawdway, length and edge speed.
Definition at line 440 of file MESegment.h.
Referenced by getTimeHeadway(), and jamThresholdForSpeed().
const bool MESegment::myTLSPenalty private
Whether tls penalty is enabled.
Definition at line 459 of file MESegment.h.
Referenced by free(), getTLSPenalty(), and isOpen().
MESegment MESegment::myVaporizationTarget static private
Definition at line 487 of file MESegment.h.
Referenced by isInvalid(), updateDetectorsOnLeave(), and vaporizeAnyCar().
The documentation for this class was generated from the following files:
MESegment.h
MESegment.cpp