SUMO - Simulation of Urban MObility: GNEAdditionalFrame::lanesSelector Class Reference
GNEAdditionalFrame::lanesSelector Class Reference
#include <GNEAdditionalFrame.h>
Public Member Functions
std::string getIdsSelected () const
get list of selecte id's in string format
void hideList ()
hide lanesSelector
bool isUseSelectedLanesEnable () const
get status of checkBox UseSelectedLanes
lanesSelector (FXComposite *parent, GNEViewNet *viewNet)
FOX-declaration.
void showList (std::string search="")
Show list of lanesSelector.
void updateUseSelectedLanes ()
~lanesSelector ()
destructor
FOX-callbacks
called when user trigger checkBox of useSelectedLanes
long onCmdUseSelectedLanes (FXObject *, FXSelector, void *)
long onCmdTypeInSearchBox (FXObject *, FXSelector, void *)
called when user type in search box
long onCmdSelectLane (FXObject *, FXSelector, void *)
called when user select a lane of the list
long onCmdClearSelection (FXObject *, FXSelector, void *)
called when clear selection button is pressed
long onCmdInvertSelection (FXObject *, FXSelector, void *)
called when invert selection button is pressed
long onCmdHelp (FXObject *, FXSelector, void *)
Called when help button is pressed.
Protected Member Functions
lanesSelector ()
FOX needs this.
Private Attributes
FXButton * clearLanesSelection
button for clear selection
FXButton * helpLanes
button for help
FXButton * invertLanesSelection
button for invert selection
FXTextField * myLanesSearch
text field for search lane IDs
FXList * myList
List of lanesSelector.
FXMenuCheck * myUseSelectedLanes
CheckBox for selected lanes.
GNEViewNet * myViewNet
viewNet associated to GNEAdditionalFrame
Detailed Description
Definition at line 468 of file GNEAdditionalFrame.h.
Constructor & Destructor Documentation
GNEAdditionalFrame::lanesSelector::lanesSelector (FXComposite * parent, GNEViewNet * viewNet)
FOX-declaration.
constructor
Definition at line 1321 of file GNEAdditionalFrame.cpp.
References clearLanesSelection, helpLanes, hideList(), invertLanesSelection, MID_GNE_CLEARLANESELECTION, MID_GNE_INVERTLANESELECTION, MID_GNE_SEARCHLANE, MID_GNE_SELECTLANE, MID_GNE_USESELECTEDLANES, MID_HELP, myLanesSearch, myList, and myUseSelectedLanes.
GNEAdditionalFrame::lanesSelector::~lanesSelector ()
destructor
Definition at line 1350 of file GNEAdditionalFrame.cpp.
GNEAdditionalFrame::lanesSelector::lanesSelector () inline protected
FOX needs this.
Definition at line 517 of file GNEAdditionalFrame.h.
Member Function Documentation
std::string GNEAdditionalFrame::lanesSelector::getIdsSelected () const
get list of selecte id's in string format
Definition at line 1354 of file GNEAdditionalFrame.cpp.
References GNEAdditionalFrame::getIdsSelected(), and myList.
Referenced by GNEAdditionalFrame::addAdditional().
void GNEAdditionalFrame::lanesSelector::hideList ()
hide lanesSelector
Definition at line 1376 of file GNEAdditionalFrame.cpp.
References GNEAdditionalFrame::hide().
Referenced by lanesSelector(), and GNEAdditionalFrame::setParametersOfAdditional().
bool GNEAdditionalFrame::lanesSelector::isUseSelectedLanesEnable () const
get status of checkBox UseSelectedLanes
Definition at line 1393 of file GNEAdditionalFrame.cpp.
References myUseSelectedLanes.
Referenced by GNEAdditionalFrame::addAdditional().
long GNEAdditionalFrame::lanesSelector::onCmdClearSelection (FXObject * , FXSelector , void *)
called when clear selection button is pressed
Definition at line 1440 of file GNEAdditionalFrame.cpp.
References myList.
long GNEAdditionalFrame::lanesSelector::onCmdHelp (FXObject * , FXSelector , void *)
Called when help button is pressed.
Definition at line 1464 of file GNEAdditionalFrame.cpp.
long GNEAdditionalFrame::lanesSelector::onCmdInvertSelection (FXObject * , FXSelector , void *)
called when invert selection button is pressed
Definition at line 1451 of file GNEAdditionalFrame.cpp.
References myList.
long GNEAdditionalFrame::lanesSelector::onCmdSelectLane (FXObject * , FXSelector , void *)
called when user select a lane of the list
Definition at line 1434 of file GNEAdditionalFrame.cpp.
long GNEAdditionalFrame::lanesSelector::onCmdTypeInSearchBox (FXObject * , FXSelector , void *)
called when user type in search box
Definition at line 1426 of file GNEAdditionalFrame.cpp.
References myLanesSearch, and showList().
long GNEAdditionalFrame::lanesSelector::onCmdUseSelectedLanes (FXObject * , FXSelector , void *)
Definition at line 1403 of file GNEAdditionalFrame.cpp.
References clearLanesSelection, helpLanes, invertLanesSelection, myLanesSearch, myList, and myUseSelectedLanes.
void GNEAdditionalFrame::lanesSelector::showList (std::string search = "")
Show list of lanesSelector.
Definition at line 1360 of file GNEAdditionalFrame.cpp.
References GNEViewNet::getNet(), myList, myUseSelectedLanes, myViewNet, GNENet::retrieveLanes(), and GNEAdditionalFrame::show().
Referenced by onCmdTypeInSearchBox(), and GNEAdditionalFrame::setParametersOfAdditional().
void GNEAdditionalFrame::lanesSelector::updateUseSelectedLanes ()
Definition at line 1382 of file GNEAdditionalFrame.cpp.
References GNEViewNet::getNet(), myUseSelectedLanes, myViewNet, and GNENet::retrieveLanes().
Referenced by GNEAdditionalFrame::show().
Field Documentation
FXButton* GNEAdditionalFrame::lanesSelector::clearLanesSelection private
button for clear selection
Definition at line 533 of file GNEAdditionalFrame.h.
Referenced by lanesSelector(), and onCmdUseSelectedLanes().
FXButton* GNEAdditionalFrame::lanesSelector::helpLanes private
button for help
Definition at line 530 of file GNEAdditionalFrame.h.
Referenced by lanesSelector(), and onCmdUseSelectedLanes().
FXButton* GNEAdditionalFrame::lanesSelector::invertLanesSelection private
button for invert selection
Definition at line 536 of file GNEAdditionalFrame.h.
Referenced by lanesSelector(), and onCmdUseSelectedLanes().
FXTextField* GNEAdditionalFrame::lanesSelector::myLanesSearch private
text field for search lane IDs
Definition at line 527 of file GNEAdditionalFrame.h.
Referenced by lanesSelector(), onCmdTypeInSearchBox(), and onCmdUseSelectedLanes().
FXList* GNEAdditionalFrame::lanesSelector::myList private
List of lanesSelector.
Definition at line 524 of file GNEAdditionalFrame.h.
Referenced by getIdsSelected(), lanesSelector(), onCmdClearSelection(), onCmdInvertSelection(), onCmdUseSelectedLanes(), and showList().
FXMenuCheck* GNEAdditionalFrame::lanesSelector::myUseSelectedLanes private
CheckBox for selected lanes.
Definition at line 521 of file GNEAdditionalFrame.h.
Referenced by isUseSelectedLanesEnable(), lanesSelector(), onCmdUseSelectedLanes(), showList(), and updateUseSelectedLanes().
GNEViewNet* GNEAdditionalFrame::lanesSelector::myViewNet private
viewNet associated to GNEAdditionalFrame
Definition at line 539 of file GNEAdditionalFrame.h.
Referenced by showList(), and updateUseSelectedLanes().
The documentation for this class was generated from the following files:
GNEAdditionalFrame.h
GNEAdditionalFrame.cpp