SUMO - Simulation of Urban MObility: MSE2Collector Class Reference
MSE2Collector Class Reference
An areal (along a single lane) detector.
#include <MSE2Collector.h>
Data Structures
class by_vehicle_position_sorter
A class used to sort known vehicles by their position.
struct JamInfo
Internal representation of a jam.
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED
}
Definition of a vehicle state.
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
void detectorUpdate (const SUMOTime step)
Computes the detector values in each time step.
const std::string & getDescription () const
SUMOReal getEndPos () const
Returns the end position of the detector.
int getEstimatedCurrentVehicleNumber (SUMOReal speedThreshold) const
Returns an estimate of the number of vehicles currently on the detector.
SUMOReal getEstimateQueueLength () const
Returns an estimate of the lenght of the queue of vehicles currently stopped on the detector.
const std::string & getID () const
Returns the id.
const MSLane * getLane () const
Returns the lane the reminder works on.
int getPassedVeh ()
Returns the number of vehicles passed over the sensor.
SUMOReal getStartPos () const
Returns the begin position of the detector.
virtual DetectorUsage getUsageType () const
Returns the detector's usage type.
MSE2Collector (const std::string &id, DetectorUsage usage, MSLane *const lane, SUMOReal startPos, SUMOReal detLength, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold)
Constructor.
virtual void notifyMoveInternal (SUMOVehicle &veh, SUMOReal timeOnLane, SUMOReal speed)
Internal notification about the vehicle moves.
void reset ()
Resets all values.
void setDescription (const std::string &description)
void setID (const std::string &newID)
resets the id
void subtractPassedVeh (int passed)
Subtract the number of vehicles indicated from passed from the sensor count.
virtual ~MSE2Collector ()
Destructor.
Methods inherited from MSMoveReminder
bool notifyMove (SUMOVehicle &veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed)
Adds/removes vehicles from the list of vehicles to regard.
bool notifyLeave (SUMOVehicle &veh, SUMOReal lastPos, MSMoveReminder::Notification reason)
Removes a known vehicle due to its lane-change.
bool notifyEnter (SUMOVehicle &veh, MSMoveReminder::Notification reason)
Adds the vehicle to known vehicles if not beyond the dector.
Methods inherited from MSDetectorFileOutput.
void writeXMLOutput (OutputDevice &dev, SUMOTime startTime, SUMOTime stopTime)
Writes collected values into the given stream.
void writeXMLDetectorProlog (OutputDevice &dev) const
Opens the XML-output using "detector" as root element.
Methods returning current values
int getCurrentVehicleNumber () const
Returns the number of vehicles currently on the detector.
SUMOReal getCurrentOccupancy () const
Returns the curent detector occupancy.
SUMOReal getCurrentMeanSpeed () const
Returns the mean vehicle speed of vehicles currently on the detector.
SUMOReal getCurrentMeanLength () const
Returns the mean vehicle length of vehicles currently on the detector.
int getCurrentJamNumber () const
Returns the current number of jams.
int getCurrentMaxJamLengthInVehicles () const
Returns the length in vehicles of the currently largest jam.
SUMOReal getCurrentMaxJamLengthInMeters () const
Returns the length in meters of the currently largest jam.
int getCurrentJamLengthInVehicles () const
Returns the length of all jams in vehicles.
SUMOReal getCurrentJamLengthInMeters () const
Returns the length of all jams in meters.
int getCurrentStartedHalts () const
Returns the length of all jams in meters.
int getCurrentHaltingNumber () const
Returns the number of current haltings within the area.
std::vector< std::string > getCurrentVehicleIDs () const
Returns the IDs of the vehicles within the area.
const std::list< SUMOVehicle * > & getCurrentVehicles () const
Returns the vehicles within the area.
Interface methods, to be derived by subclasses
void updateDetector (SUMOVehicle &veh, SUMOReal entryPos, SUMOReal leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp)
Virtual methods to implement by derived classes
virtual GUIDetectorWrapper * buildDetectorGUIRepresentation ()
Builds the graphical representation.
Static Public Member Functions
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
Protected Member Functions
void removeFromVehicleUpdateValues (SUMOVehicle &veh)
Protected Attributes
std::string myDescription
a description of this moveReminder
std::string myID
The name of the object.
MSLane *const myLane
Lane on which the reminder works.
Private Member Functions
MSE2Collector (const MSE2Collector &)
Invalidated copy constructor.
MSE2Collector & operator= (const MSE2Collector &)
Invalidated assignment operator.
Private Attributes
std::map< const SUMOVehicle *, SUMOTime > myHaltingVehicleDurations
Storage for halting durations of known vehicles (for halting vehicles)
std::map< const SUMOVehicle *, SUMOTime > myIntervalHaltingVehicleDurations
Storage for halting durations of known vehicles (current interval)
std::list< SUMOVehicle * > myKnownVehicles
List of known vehicles.
std::vector< SUMOTime > myPastIntervalStandingDurations
Halting durations of ended halts for the current interval [s].
std::vector< SUMOTime > myPastStandingDurations
Halting durations of ended halts [s].
DetectorUsage myUsage
Information about how this detector is used.
Detector parameter
SUMOReal myJamHaltingSpeedThreshold
A vehicle must driver slower than this to be counted as a part of a jam.
SUMOTime myJamHaltingTimeThreshold
A vehicle must be that long beyond myJamHaltingSpeedThreshold to be counted as a part of a jam.
SUMOReal myJamDistanceThreshold
Two standing vehicles must be closer than this to be counted into the same jam.
SUMOReal myStartPos
The position the detector starts at.
SUMOReal myEndPos
The position the detector ends at.
Values generated for aggregated file output
SUMOReal mySpeedSum
The sum of collected vehicle speeds [m/s].
SUMOReal myStartedHalts
The number of started halts [#].
SUMOReal myJamLengthInMetersSum
The sum of jam lengths [m].
int myJamLengthInVehiclesSum
The sum of jam lengths [#veh].
int myVehicleSamples
The number of collected samples [#].
int myTimeSamples
The current aggregation duration [#steps].
SUMOReal myOccupancySum
The sum of occupancies [%].
SUMOReal myMaxOccupancy
The maximum occupancy [%].
int myMeanMaxJamInVehicles
The mean jam length [#veh].
SUMOReal myMeanMaxJamInMeters
The mean jam length [m].
int myMaxJamInVehicles
The max jam length [#veh].
SUMOReal myMaxJamInMeters
The max jam length [m].
int myMeanVehicleNumber
The mean number of vehicles [#veh].
int myMaxVehicleNumber
The max number of vehicles [#veh].
Values generated describing the current state
SUMOReal myCurrentOccupancy
The current occupancy.
SUMOReal myCurrentMeanSpeed
The current mean speed.
SUMOReal myCurrentMeanLength
The current mean length.
int myCurrentJamNo
The current jam number.
SUMOReal myCurrentMaxJamLengthInMeters
the current maximum jam length in meters
int myCurrentMaxJamLengthInVehicles
The current maximum jam length in vehicles.
SUMOReal myCurrentJamLengthInMeters
The overall jam length in meters.
int myCurrentJamLengthInVehicles
The overall jam length in vehicles.
int myCurrentStartedHalts
The number of started halts in the last step.
int myCurrentHaltingsNumber
The number of halted vehicles [#].
int myPassedVeh
The number of vehicles passed on the sensor.
Detailed Description
An areal (along a single lane) detector.
This detector traces vehicles which are at a part of a single lane. A vehicle that enters the detector is stored and the stored vehicles' speeds are used within each timestep to compute the detector values. As soon as the vehicle leaves the detector, it is no longer tracked.
Determining entering and leaving vehicles is done via the MSMoveReminder interface. The values are computed by an event-callback (at the end of a time step).
Jams are determined as following: A vehicle must at least drive haltingTimeThreshold at a speed lesser than haltingSpeedThreshold to be a "halting" vehicle. Two or more vehicles are "in jam" if they are halting and their distance is lesser than jamDistThreshold.
See also
Named
MSMoveReminder
MSDetectorFileOutput
Command
Definition at line 83 of file MSE2Collector.h.
Member Enumeration Documentation
enum MSMoveReminder::Notification inherited
Definition of a vehicle state.
Enumerator
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network)
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only)
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only)
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted)
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
Definition at line 95 of file MSMoveReminder.h.
Constructor & Destructor Documentation
MSE2Collector::MSE2Collector (const std::string & id, DetectorUsage usage, MSLane *const lane, SUMOReal startPos, SUMOReal detLength, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold)
Constructor.
Parameters
[in] id The detector's unique id.
[in] usage Information how the detector is used
[in] lane The lane to place the detector at
[in] startPos Begin position of the detector
[in] detLength Length of the detector
[in] haltingTimeThreshold The time a vehicle's speed must be below haltingSpeedThreshold to be assigned as jammed
[in] haltingSpeedThreshold The speed a vehicle's speed must be below to be assigned as jammed
[in] jamDistThreshold The distance between two vehicles in order to not count them to one jam
Todo:
The lane should not be given as a pointer
Definition at line 52 of file MSE2Collector.cpp.
References myEndPos, MSMoveReminder::myLane, myStartPos, and reset().
MSE2Collector::~MSE2Collector () virtual
Destructor.
Definition at line 77 of file MSE2Collector.cpp.
References myKnownVehicles.
MSE2Collector::MSE2Collector (const MSE2Collector &) private
Invalidated copy constructor.
Member Function Documentation
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
virtual GUIDetectorWrapper* MSDetectorFileOutput::buildDetectorGUIRepresentation () inline virtual inherited
Builds the graphical representation.
Meant to be overridden by graphical versions of the detectors
Returns
A wrapper for the detector which performs the user I/O within the GUI
Reimplemented in GUI_E2_ZS_Collector, GUIInductLoop, GUIE3Collector, GUI_E2_ZS_CollectorOverLanes, GUIInstantInductLoop, and GUIMEInductLoop.
Definition at line 123 of file MSDetectorFileOutput.h.
References MSDetectorFileOutput::MSDetectorFileOutput(), and MSDetectorFileOutput::operator=().
void MSE2Collector::detectorUpdate (const SUMOTime step) virtual
Computes the detector values in each time step.
This method should be called at the end of a simulation step, when all vehicles have moved. The current values are computed and summed up with the previous.
Parameters
[in] currentTime The current simulation time
Reimplemented from MSDetectorFileOutput.
Definition at line 196 of file MSE2Collector.cpp.
References DELTA_T, MSE2Collector::JamInfo::firstStandingVehicle, MSVehicle::getBackPositionOnLane(), MSMoveReminder::getLane(), MSVehicle::getLane(), MSVehicleType::getLength(), MSLane::getLength(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSE2Collector::JamInfo::lastStandingVehicle, MAX2(), myCurrentHaltingsNumber, myCurrentJamLengthInMeters, myCurrentJamLengthInVehicles, myCurrentJamNo, myCurrentMaxJamLengthInMeters, myCurrentMaxJamLengthInVehicles, myCurrentMeanLength, myCurrentMeanSpeed, myCurrentOccupancy, myCurrentStartedHalts, myEndPos, myHaltingVehicleDurations, myIntervalHaltingVehicleDurations, myJamDistanceThreshold, myJamHaltingSpeedThreshold, myJamHaltingTimeThreshold, myJamLengthInMetersSum, myJamLengthInVehiclesSum, myKnownVehicles, MSMoveReminder::myLane, myMaxJamInMeters, myMaxJamInVehicles, myMaxOccupancy, myMaxVehicleNumber, myMeanMaxJamInMeters, myMeanMaxJamInVehicles, myMeanVehicleNumber, myOccupancySum, myPastIntervalStandingDurations, myPastStandingDurations, mySpeedSum, myStartedHalts, myStartPos, myTimeSamples, myVehicleSamples, and SUMOReal.
Referenced by getUsageType().
int MSE2Collector::getCurrentHaltingNumber () const
Returns the number of current haltings within the area.
If no vehicle is within the area, 0 is returned.
Returns
The mean number of haltings within the area
Definition at line 582 of file MSE2Collector.cpp.
References myCurrentHaltingsNumber.
Referenced by getEndPos(), and TraCIServerAPI_ArealDetector::processGet().
SUMOReal MSE2Collector::getCurrentJamLengthInMeters () const
Returns the length of all jams in meters.
Definition at line 559 of file MSE2Collector.cpp.
References myCurrentJamLengthInMeters.
Referenced by getEndPos(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), and TraCIServerAPI_ArealDetector::processGet().
int MSE2Collector::getCurrentJamLengthInVehicles () const
Returns the length of all jams in vehicles.
Definition at line 553 of file MSE2Collector.cpp.
References myCurrentJamLengthInVehicles, and SUMOReal.
Referenced by getEndPos(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), and TraCIServerAPI_ArealDetector::processGet().
int MSE2Collector::getCurrentJamNumber () const
Returns the current number of jams.
Definition at line 535 of file MSE2Collector.cpp.
References myCurrentJamNo.
Referenced by getEndPos(), and GUI_E2_ZS_Collector::MyWrapper::getParameterWindow().
SUMOReal MSE2Collector::getCurrentMaxJamLengthInMeters () const
Returns the length in meters of the currently largest jam.
Definition at line 547 of file MSE2Collector.cpp.
References myCurrentMaxJamLengthInMeters.
Referenced by getEndPos(), and GUI_E2_ZS_Collector::MyWrapper::getParameterWindow().
int MSE2Collector::getCurrentMaxJamLengthInVehicles () const
Returns the length in vehicles of the currently largest jam.
Definition at line 541 of file MSE2Collector.cpp.
References myCurrentMaxJamLengthInVehicles, and SUMOReal.
Referenced by getEndPos(), and GUI_E2_ZS_Collector::MyWrapper::getParameterWindow().
SUMOReal MSE2Collector::getCurrentMeanLength () const
Returns the mean vehicle length of vehicles currently on the detector.
Definition at line 529 of file MSE2Collector.cpp.
References myCurrentMeanLength.
Referenced by getEndPos(), and GUI_E2_ZS_Collector::MyWrapper::getParameterWindow().
SUMOReal MSE2Collector::getCurrentMeanSpeed () const
Returns the mean vehicle speed of vehicles currently on the detector.
Definition at line 523 of file MSE2Collector.cpp.
References myCurrentMeanSpeed, and SUMOReal.
Referenced by getEndPos(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), MSSOTLE2Sensors::meanVehiclesSpeed(), and TraCIServerAPI_ArealDetector::processGet().
SUMOReal MSE2Collector::getCurrentOccupancy () const
Returns the curent detector occupancy.
Definition at line 517 of file MSE2Collector.cpp.
References myCurrentOccupancy, and SUMOReal.
Referenced by getEndPos(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), and TraCIServerAPI_ArealDetector::processGet().
int MSE2Collector::getCurrentStartedHalts () const
Returns the length of all jams in meters.
Definition at line 565 of file MSE2Collector.cpp.
References myCurrentStartedHalts.
Referenced by getEndPos(), and GUI_E2_ZS_Collector::MyWrapper::getParameterWindow().
std::vector< std::string > MSE2Collector::getCurrentVehicleIDs () const
Returns the IDs of the vehicles within the area.
Returns
The IDs of the vehicles that have passed the entry, but not yet an exit point
Definition at line 588 of file MSE2Collector.cpp.
References MSBaseVehicle::getID(), and myKnownVehicles.
Referenced by getEndPos(), and TraCIServerAPI_ArealDetector::processGet().
int MSE2Collector::getCurrentVehicleNumber () const
Returns the number of vehicles currently on the detector.
Definition at line 438 of file MSE2Collector.cpp.
References myKnownVehicles.
Referenced by MSSOTLE2Sensors::count(), getEndPos(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), MSSOTLE2Sensors::meanVehiclesSpeed(), and TraCIServerAPI_ArealDetector::processGet().
const std::list< SUMOVehicle * > & MSE2Collector::getCurrentVehicles () const
Returns the vehicles within the area.
Returns
The vehicles that have passed the entry, but not yet an exit point
Definition at line 598 of file MSE2Collector.cpp.
References myKnownVehicles.
Referenced by MSSOTLE2Sensors::count(), and getEndPos().
const std::string& MSMoveReminder::getDescription () const inline inherited
Definition at line 213 of file MSMoveReminder.h.
References MSMoveReminder::myDescription, and MSMoveReminder::removeFromVehicleUpdateValues().
Referenced by MSBaseVehicle::addStops().
SUMOReal MSE2Collector::getEndPos () const inline
Returns the end position of the detector.
Returns
The detector's end position
Definition at line 220 of file MSE2Collector.h.
References getCurrentHaltingNumber(), getCurrentJamLengthInMeters(), getCurrentJamLengthInVehicles(), getCurrentJamNumber(), getCurrentMaxJamLengthInMeters(), getCurrentMaxJamLengthInVehicles(), getCurrentMeanLength(), getCurrentMeanSpeed(), getCurrentOccupancy(), getCurrentStartedHalts(), getCurrentVehicleIDs(), getCurrentVehicleNumber(), getCurrentVehicles(), getEstimatedCurrentVehicleNumber(), getEstimateQueueLength(), myEndPos, reset(), and SUMOReal.
Referenced by GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), and TraCIServerAPI_ArealDetector::processGet().
int MSE2Collector::getEstimatedCurrentVehicleNumber (SUMOReal speedThreshold) const
Returns an estimate of the number of vehicles currently on the detector.
Definition at line 443 of file MSE2Collector.cpp.
References MSVehicle::getAcceleration(), MSLane::getLength(), MSVehicleType::getLengthWithGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSLane::getSpeedLimit(), MSBaseVehicle::getVehicleType(), myKnownVehicles, MSMoveReminder::myLane, and SUMOReal.
Referenced by getEndPos().
SUMOReal MSE2Collector::getEstimateQueueLength () const
Returns an estimate of the lenght of the queue of vehicles currently stopped on the detector.
Definition at line 471 of file MSE2Collector.cpp.
References DBG, Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSLane::getLength(), MSVehicleType::getLengthWithGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), myKnownVehicles, MSMoveReminder::myLane, SUMOReal, time2string(), and WRITE_MESSAGE.
Referenced by getEndPos().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciBusOrContainerStop(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNEConnectorFrame::buildIinternalLanes(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), NLDetectorBuilder::convUncontE2PosLength(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSVehicle::getBackPosition(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), GNEEdge::getDest(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), getEstimateQueueLength(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), GNEEdge::getSource(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_BTsender::notifyMove(), notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_SL2015::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_LC2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_ArealDetector::processGet(), TraCIServerAPI_Lane::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), MSBaseVehicle::reroute(), MSLane::resetPartialOccupation(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), MSLane::saveState(), MSDevice_Battery::setAirDragCoefficient(), NBNodeCont::setAsTLControlled(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), MSDevice_Battery::setConstantPowerIntake(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), MSDevice_Battery::setFrontSurfaceArea(), MSDevice_Battery::setInternalMomentOfInertia(), GNEJunction::setLogicValid(), MSDevice_Battery::setMass(), MSDevice_Battery::setMaximumBatteryCapacity(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSDevice_Battery::setPropulsionEfficiency(), MSDevice_Battery::setRadialDragCoefficient(), MSDevice_Battery::setRecuperationEfficiency(), MSLink::setRequestInformation(), MSDevice_Battery::setRollDragCoefficient(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), writeXMLOutput(), and RONet::~RONet().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), operator<<(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
const MSLane* MSMoveReminder::getLane () const inline inherited
Returns the lane the reminder works on.
Returns
The lane the reminder works on.
Definition at line 89 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by MSDevice_Tripinfo::computeLengthAndDuration(), detectorUpdate(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_InductionLoop::getTree(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_ArealDetector::processGet(), and MSMeanData::writeEdge().
int MSE2Collector::getPassedVeh () inline
Returns the number of vehicles passed over the sensor.
Returns
number of cars passed over the sensor
Definition at line 296 of file MSE2Collector.h.
References myPassedVeh.
Referenced by MSSOTLE2Sensors::getPassedVeh().
SUMOReal MSE2Collector::getStartPos () const inline
Returns the begin position of the detector.
Returns
The detector's begin position
Definition at line 211 of file MSE2Collector.h.
References myStartPos.
Referenced by GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), and TraCIServerAPI_ArealDetector::processGet().
virtual DetectorUsage MSE2Collector::getUsageType () const inline virtual
Returns the detector's usage type.
See also
DetectorUsage
Returns
How the detector is used.
Definition at line 112 of file MSE2Collector.h.
References detectorUpdate(), myUsage, notifyEnter(), notifyLeave(), notifyMove(), SUMOReal, writeXMLDetectorProlog(), and writeXMLOutput().
Referenced by GUI_E2_ZS_Collector::MyWrapper::drawGL().
bool MSE2Collector::notifyEnter (SUMOVehicle & veh, MSMoveReminder::Notification reason) virtual
Adds the vehicle to known vehicles if not beyond the dector.
If the vehicles is within the detector are, it is added to the list of known vehicles. The method returns true as long as the vehicle is not beyond the detector.
Parameters
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns
False, if vehicle passed the detector entirely, else true.
See also
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented from MSMoveReminder.
Definition at line 132 of file MSE2Collector.cpp.
References DBG, SUMOVehicle::getBackPositionOnLane(), Named::getID(), MSVehicleType::getID(), MSNet::getInstance(), MSVehicleType::getLength(), SUMOVehicle::getPositionOnLane(), SUMOVehicle::getVehicleType(), SUMOVehicle::isOnRoad(), myEndPos, myKnownVehicles, MSMoveReminder::myLane, myPassedVeh, myStartPos, MSMoveReminder::NOTIFICATION_JUNCTION, time2string(), and WRITE_MESSAGE.
Referenced by getUsageType().
bool MSE2Collector::notifyLeave (SUMOVehicle & veh, SUMOReal lastPos, MSMoveReminder::Notification reason) virtual
Removes a known vehicle due to its lane-change.
If the reported vehicle is known, it is removed from the list of vehicles to regard (myKnownVehicles).
Parameters
[in] veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] isArrival whether the vehicle arrived at its destination
[in] isLaneChange whether the vehicle changed from the lane
See also
MSMoveReminder::notifyLeave
Reimplemented from MSMoveReminder.
Definition at line 119 of file MSE2Collector.cpp.
References MSVehicleType::getLength(), SUMOVehicle::getVehicleType(), myEndPos, myKnownVehicles, myStartPos, and MSMoveReminder::NOTIFICATION_JUNCTION.
Referenced by getUsageType().
bool MSE2Collector::notifyMove (SUMOVehicle & veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed) virtual
Adds/removes vehicles from the list of vehicles to regard.
As soon as the reported vehicle enters the detector area (position>myStartPos) it is added to the list of vehicles to regard (myKnownVehicles). It is removed from this list if it leaves the detector (position<lengt>myEndPos). The method returns true as long as the vehicle is not beyond the detector.
Parameters
[in] veh The vehicle in question.
[in] oldPos Position before the move-micro-timestep.
[in] newPos Position after the move-micro-timestep.
[in] newSpeed Unused here.
Returns
False, if vehicle passed the detector entierly, else true.
See also
MSMoveReminder
MSMoveReminder::notifyMove
Reimplemented from MSMoveReminder.
Definition at line 83 of file MSE2Collector.cpp.
References DBG, Named::getID(), MSVehicleType::getID(), MSNet::getInstance(), MSVehicleType::getLength(), SUMOVehicle::getVehicleType(), myEndPos, myKnownVehicles, MSMoveReminder::myLane, myPassedVeh, myStartPos, time2string(), and WRITE_MESSAGE.
Referenced by getUsageType().
virtual void MSMoveReminder::notifyMoveInternal (SUMOVehicle & veh, SUMOReal timeOnLane, SUMOReal speed) inline virtual inherited
Internal notification about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] timeOnLane time the vehicle spent on the lane.
[in] speed Moving speed.
Reimplemented in MSMeanData::MeanDataValueTracker, MSDevice_Tripinfo, MSMeanData_Net::MSLaneMeanDataValues, MSMeanData_Harmonoise::MSLaneMeanDataValues, MSMeanData_Amitran::MSLaneMeanDataValues, and MSMeanData_Emissions::MSLaneMeanDataValues.
Definition at line 201 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
Referenced by MSMeanData::MeanDataValues::notifyMove(), and MSMoveReminder::updateDetector().
MSE2Collector& MSE2Collector::operator= (const MSE2Collector &) private
Invalidated assignment operator.
Referenced by MSE2Collector::by_vehicle_position_sorter::by_vehicle_position_sorter().
void MSMoveReminder::removeFromVehicleUpdateValues (SUMOVehicle & veh) protected inherited
Definition at line 94 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues.
Referenced by MSMoveReminder::getDescription(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), and MSMoveReminder::updateDetector().
void MSE2Collector::reset () virtual
Resets all values.
This method is called on initialisation and as soon as the values were written. Values for the next interval may be collected, then. The list of known vehicles stays untouched.
Reimplemented from MSDetectorFileOutput.
Definition at line 170 of file MSE2Collector.cpp.
References myIntervalHaltingVehicleDurations, myJamLengthInMetersSum, myJamLengthInVehiclesSum, myMaxJamInMeters, myMaxJamInVehicles, myMaxOccupancy, myMaxVehicleNumber, myMeanMaxJamInMeters, myMeanMaxJamInVehicles, myMeanVehicleNumber, myOccupancySum, myPassedVeh, myPastIntervalStandingDurations, myPastStandingDurations, mySpeedSum, myStartedHalts, myTimeSamples, and myVehicleSamples.
Referenced by getEndPos(), MSE2Collector(), and writeXMLOutput().
void MSMoveReminder::setDescription (const std::string & description) inline inherited
Definition at line 209 of file MSMoveReminder.h.
References MSMoveReminder::myDescription.
Referenced by MSMeanData::init(), MEInductLoop::MEInductLoop(), METriggeredCalibrator::METriggeredCalibrator(), and MSCalibrator::MSCalibrator().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
void MSE2Collector::subtractPassedVeh (int passed) inline
Subtract the number of vehicles indicated from passed from the sensor count.
Parameters
[in] passed - int that indicates the number of vehicles to subtract
Definition at line 304 of file MSE2Collector.h.
References myPassedVeh.
void MSMoveReminder::updateDetector (SUMOVehicle & veh, SUMOReal entryPos, SUMOReal leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp) inherited
Definition at line 51 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues, MSMoveReminder::notifyMoveInternal(), MSMoveReminder::removeFromVehicleUpdateValues(), STEPS2TIME, and SUMOReal.
Referenced by MSMoveReminder::notifyLeave(), and MEVehicle::updateDetectorForWriting().
void MSE2Collector::writeXMLDetectorProlog (OutputDevice & dev) const virtual
Opens the XML-output using "detector" as root element.
Parameters
[in] dev The output device to write the root into
See also
MSDetectorFileOutput::writeXMLDetectorProlog
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSDetectorFileOutput.
Definition at line 432 of file MSE2Collector.cpp.
References OutputDevice::writeXMLHeader().
Referenced by getUsageType().
void MSE2Collector::writeXMLOutput (OutputDevice & dev, SUMOTime startTime, SUMOTime stopTime) virtual
Writes collected values into the given stream.
Parameters
[in] dev The output device to write the data into
[in] startTime First time step the data were gathered
[in] stopTime Last time step the data were gathered
See also
MSDetectorFileOutput::writeXMLOutput
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSDetectorFileOutput.
Definition at line 368 of file MSE2Collector.cpp.
References Named::getID(), MAX2(), myHaltingVehicleDurations, myIntervalHaltingVehicleDurations, myJamLengthInMetersSum, myJamLengthInVehiclesSum, myMaxJamInMeters, myMaxJamInVehicles, myMaxOccupancy, myMaxVehicleNumber, myMeanMaxJamInMeters, myMeanMaxJamInVehicles, myMeanVehicleNumber, myOccupancySum, myPastIntervalStandingDurations, myPastStandingDurations, mySpeedSum, myStartedHalts, myTimeSamples, myVehicleSamples, reset(), STEPS2TIME, SUMOReal, and time2string().
Referenced by getUsageType().
Field Documentation
int MSE2Collector::myCurrentHaltingsNumber private
The number of halted vehicles [#].
Definition at line 458 of file MSE2Collector.h.
Referenced by detectorUpdate(), and getCurrentHaltingNumber().
SUMOReal MSE2Collector::myCurrentJamLengthInMeters private
The overall jam length in meters.
Definition at line 452 of file MSE2Collector.h.
Referenced by detectorUpdate(), and getCurrentJamLengthInMeters().
int MSE2Collector::myCurrentJamLengthInVehicles private
The overall jam length in vehicles.
Definition at line 454 of file MSE2Collector.h.
Referenced by detectorUpdate(), and getCurrentJamLengthInVehicles().
int MSE2Collector::myCurrentJamNo private
The current jam number.
Definition at line 446 of file MSE2Collector.h.
Referenced by detectorUpdate(), and getCurrentJamNumber().
SUMOReal MSE2Collector::myCurrentMaxJamLengthInMeters private
the current maximum jam length in meters
Definition at line 448 of file MSE2Collector.h.
Referenced by detectorUpdate(), and getCurrentMaxJamLengthInMeters().
int MSE2Collector::myCurrentMaxJamLengthInVehicles private
The current maximum jam length in vehicles.
Definition at line 450 of file MSE2Collector.h.
Referenced by detectorUpdate(), and getCurrentMaxJamLengthInVehicles().
SUMOReal MSE2Collector::myCurrentMeanLength private
The current mean length.
Definition at line 444 of file MSE2Collector.h.
Referenced by detectorUpdate(), and getCurrentMeanLength().
SUMOReal MSE2Collector::myCurrentMeanSpeed private
The current mean speed.
Definition at line 442 of file MSE2Collector.h.
Referenced by detectorUpdate(), and getCurrentMeanSpeed().
SUMOReal MSE2Collector::myCurrentOccupancy private
The current occupancy.
Definition at line 440 of file MSE2Collector.h.
Referenced by detectorUpdate(), and getCurrentOccupancy().
int MSE2Collector::myCurrentStartedHalts private
The number of started halts in the last step.
Definition at line 456 of file MSE2Collector.h.
Referenced by detectorUpdate(), and getCurrentStartedHalts().
std::string MSMoveReminder::myDescription protected inherited
a description of this moveReminder
Definition at line 225 of file MSMoveReminder.h.
Referenced by MSMoveReminder::getDescription(), and MSMoveReminder::setDescription().
SUMOReal MSE2Collector::myEndPos private
The position the detector ends at.
Definition at line 380 of file MSE2Collector.h.
Referenced by detectorUpdate(), getEndPos(), MSE2Collector(), notifyEnter(), notifyLeave(), and notifyMove().
std::map<const SUMOVehicle*, SUMOTime> MSE2Collector::myHaltingVehicleDurations private
Storage for halting durations of known vehicles (for halting vehicles)
Definition at line 390 of file MSE2Collector.h.
Referenced by detectorUpdate(), and writeXMLOutput().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
std::map<const SUMOVehicle*, SUMOTime> MSE2Collector::myIntervalHaltingVehicleDurations private
Storage for halting durations of known vehicles (current interval)
Definition at line 393 of file MSE2Collector.h.
Referenced by detectorUpdate(), reset(), and writeXMLOutput().
SUMOReal MSE2Collector::myJamDistanceThreshold private
Two standing vehicles must be closer than this to be counted into the same jam.
Definition at line 376 of file MSE2Collector.h.
Referenced by detectorUpdate().
SUMOReal MSE2Collector::myJamHaltingSpeedThreshold private
A vehicle must driver slower than this to be counted as a part of a jam.
Definition at line 372 of file MSE2Collector.h.
Referenced by detectorUpdate().
SUMOTime MSE2Collector::myJamHaltingTimeThreshold private
A vehicle must be that long beyond myJamHaltingSpeedThreshold to be counted as a part of a jam.
Definition at line 374 of file MSE2Collector.h.
Referenced by detectorUpdate().
SUMOReal MSE2Collector::myJamLengthInMetersSum private
The sum of jam lengths [m].
Definition at line 410 of file MSE2Collector.h.
Referenced by detectorUpdate(), reset(), and writeXMLOutput().
int MSE2Collector::myJamLengthInVehiclesSum private
The sum of jam lengths [#veh].
Definition at line 412 of file MSE2Collector.h.
Referenced by detectorUpdate(), reset(), and writeXMLOutput().
std::list<SUMOVehicle*> MSE2Collector::myKnownVehicles private
List of known vehicles.
Definition at line 387 of file MSE2Collector.h.
Referenced by detectorUpdate(), getCurrentVehicleIDs(), getCurrentVehicleNumber(), getCurrentVehicles(), getEstimatedCurrentVehicleNumber(), getEstimateQueueLength(), notifyEnter(), notifyLeave(), notifyMove(), and ~MSE2Collector().
MSLane* const MSMoveReminder::myLane protected inherited
Lane on which the reminder works.
Definition at line 223 of file MSMoveReminder.h.
Referenced by detectorUpdate(), getEstimatedCurrentVehicleNumber(), getEstimateQueueLength(), MSMoveReminder::getLane(), MSE2Collector(), MSMoveReminder::MSMoveReminder(), notifyEnter(), notifyMove(), MSE2Collector::by_vehicle_position_sorter::operator()(), and MSMeanData::MeanDataValueTracker::reset().
SUMOReal MSE2Collector::myMaxJamInMeters private
The max jam length [m].
Definition at line 428 of file MSE2Collector.h.
Referenced by detectorUpdate(), reset(), and writeXMLOutput().
int MSE2Collector::myMaxJamInVehicles private
The max jam length [#veh].
Definition at line 426 of file MSE2Collector.h.
Referenced by detectorUpdate(), reset(), and writeXMLOutput().
SUMOReal MSE2Collector::myMaxOccupancy private
The maximum occupancy [%].
Definition at line 420 of file MSE2Collector.h.
Referenced by detectorUpdate(), reset(), and writeXMLOutput().
int MSE2Collector::myMaxVehicleNumber private
The max number of vehicles [#veh].
Definition at line 432 of file MSE2Collector.h.
Referenced by detectorUpdate(), reset(), and writeXMLOutput().
SUMOReal MSE2Collector::myMeanMaxJamInMeters private
The mean jam length [m].
Definition at line 424 of file MSE2Collector.h.
Referenced by detectorUpdate(), reset(), and writeXMLOutput().
int MSE2Collector::myMeanMaxJamInVehicles private
The mean jam length [#veh].
Definition at line 422 of file MSE2Collector.h.
Referenced by detectorUpdate(), reset(), and writeXMLOutput().
int MSE2Collector::myMeanVehicleNumber private
The mean number of vehicles [#veh].
Definition at line 430 of file MSE2Collector.h.
Referenced by detectorUpdate(), reset(), and writeXMLOutput().
SUMOReal MSE2Collector::myOccupancySum private
The sum of occupancies [%].
Definition at line 418 of file MSE2Collector.h.
Referenced by detectorUpdate(), reset(), and writeXMLOutput().
int MSE2Collector::myPassedVeh private
The number of vehicles passed on the sensor.
Definition at line 460 of file MSE2Collector.h.
Referenced by getPassedVeh(), notifyEnter(), notifyMove(), reset(), and subtractPassedVeh().
std::vector<SUMOTime> MSE2Collector::myPastIntervalStandingDurations private
Halting durations of ended halts for the current interval [s].
Definition at line 399 of file MSE2Collector.h.
Referenced by detectorUpdate(), reset(), and writeXMLOutput().
std::vector<SUMOTime> MSE2Collector::myPastStandingDurations private
Halting durations of ended halts [s].
Definition at line 396 of file MSE2Collector.h.
Referenced by detectorUpdate(), reset(), and writeXMLOutput().
SUMOReal MSE2Collector::mySpeedSum private
The sum of collected vehicle speeds [m/s].
Definition at line 406 of file MSE2Collector.h.
Referenced by detectorUpdate(), reset(), and writeXMLOutput().
SUMOReal MSE2Collector::myStartedHalts private
The number of started halts [#].
Definition at line 408 of file MSE2Collector.h.
Referenced by detectorUpdate(), reset(), and writeXMLOutput().
SUMOReal MSE2Collector::myStartPos private
The position the detector starts at.
Definition at line 378 of file MSE2Collector.h.
Referenced by detectorUpdate(), getStartPos(), MSE2Collector(), notifyEnter(), notifyLeave(), and notifyMove().
int MSE2Collector::myTimeSamples private
The current aggregation duration [#steps].
Definition at line 416 of file MSE2Collector.h.
Referenced by detectorUpdate(), reset(), and writeXMLOutput().
DetectorUsage MSE2Collector::myUsage private
Information about how this detector is used.
Definition at line 384 of file MSE2Collector.h.
Referenced by getUsageType().
int MSE2Collector::myVehicleSamples private
The number of collected samples [#].
Definition at line 414 of file MSE2Collector.h.
Referenced by detectorUpdate(), reset(), and writeXMLOutput().
The documentation for this class was generated from the following files:
MSE2Collector.h
MSE2Collector.cpp