SUMO - Simulation of Urban MObility: od2trips_main.cpp File Reference
od2trips_main.cpp File Reference
#include <config.h>
#include <version.h>
#include <iostream>
#include <algorithm>
#include <math.h>
#include <cstdlib>
#include <string>
#include <xercesc/parsers/SAXParser.hpp>
#include <xercesc/sax2/SAX2XMLReader.hpp>
#include <utils/options/Option.h>
#include <utils/options/OptionsCont.h>
#include <utils/options/OptionsIO.h>
#include <utils/common/MsgHandler.h>
#include <utils/common/UtilExceptions.h>
#include <utils/common/SystemFrame.h>
#include <utils/common/RandHelper.h>
#include <utils/common/ToString.h>
#include <utils/xml/XMLSubSys.h>
#include <utils/common/StringUtils.h>
#include <od/ODDistrictCont.h>
#include <od/ODDistrictHandler.h>
#include <od/ODMatrix.h>
#include <utils/common/TplConvert.h>
#include <utils/common/SUMOTime.h>
#include <utils/common/StringTokenizer.h>
#include <utils/common/FileHelpers.h>
#include <utils/vehicle/SUMOVehicleParameter.h>
#include <utils/importio/LineReader.h>
#include <utils/iodevices/OutputDevice.h>
Functions
bool checkOptions ()
void fillOptions ()
int main (int argc, char **argv)
Detailed Description
Author
Daniel Krajzewicz
Jakob Erdmann
Michael Behrisch
Laura Bieker
Yun-Pang Floetteroed
Date
Thu, 12 September 2002
Version
Id
od2trips_main.cpp 20834 2016-06-01 07:22:25Z behrisch
Definition in file od2trips_main.cpp.
Function Documentation
bool checkOptions ()
Definition at line 183 of file od2trips_main.cpp.
References SUMOVehicleParameter::arrivalLane, SUMOVehicleParameter::arrivalLaneProcedure, SUMOVehicleParameter::arrivalPos, SUMOVehicleParameter::arrivalPosProcedure, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, SUMOVehicleParameter::departLane, SUMOVehicleParameter::departLaneProcedure, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, SUMOVehicleParameter::departSpeed, SUMOVehicleParameter::departSpeedProcedure, OptionsCont::getOptions(), OptionsCont::getString(), OptionsCont::isSet(), SUMOVehicleParameter::parseArrivalLane(), SUMOVehicleParameter::parseArrivalPos(), SUMOVehicleParameter::parseArrivalSpeed(), SUMOVehicleParameter::parseDepartLane(), SUMOVehicleParameter::parseDepartPos(), SUMOVehicleParameter::parseDepartSpeed(), and WRITE_ERROR.
Referenced by main().
void fillOptions ()
Definition at line 76 of file od2trips_main.cpp.
References OptionsCont::addCallExample(), SystemFrame::addConfigurationOptions(), OptionsCont::addDescription(), OptionsCont::addOptionSubTopic(), SystemFrame::addReportOptions(), OptionsCont::addSynonyme(), OptionsCont::doRegister(), OptionsCont::getOptions(), RandHelper::insertRandOptions(), and SUMOTIME_MAXSTRING.
Referenced by main().
int main (int argc, char ** argv)
Definition at line 235 of file od2trips_main.cpp.
References ODMatrix::applyCurve(), checkOptions(), SystemFrame::close(), OutputDevice::createDeviceByOption(), fillOptions(), OptionsCont::getBool(), OutputDevice::getDeviceByOption(), MsgHandler::getErrorInstance(), ODMatrix::getNumDiscarded(), ODMatrix::getNumLoaded(), ODMatrix::getNumWritten(), OptionsIO::getOptions(), OptionsCont::getOptions(), OptionsCont::getString(), OptionsCont::getStringVector(), MsgHandler::inform(), XMLSubSys::init(), MsgHandler::initOutputOptions(), RandHelper::initRandGlobal(), OptionsCont::isSet(), ODDistrictCont::loadDistricts(), ODMatrix::loadMatrix(), ODMatrix::parseTimeLine(), OptionsCont::processMetaOptions(), OptionsCont::setApplicationDescription(), OptionsCont::setApplicationName(), OptionsIO::setArgs(), XMLSubSys::setValidation(), NamedObjectCont< T >::size(), string2time(), toString(), VERSION_STRING, ODMatrix::write(), WRITE_ERROR, WRITE_MESSAGE, and ODMatrix::writeFlows().