SUMO - Simulation of Urban MObility: SAXWeightsHandler Class Reference
SAXWeightsHandler Class Reference
An XML-handler for network weights.
#include <SAXWeightsHandler.h>
Data Structures
class EdgeFloatTimeLineRetriever
Interface for a class which obtains read weights for named edges.
class ToRetrieveDefinition
Complete definition about what shall be retrieved and where to store it.
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
SAXWeightsHandler (const std::vector< ToRetrieveDefinition * > &defs, const std::string &file)
Constructor.
SAXWeightsHandler (ToRetrieveDefinition *def, const std::string &file)
Constructor.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
~SAXWeightsHandler ()
Destructor.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Protected Member Functions
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
inherited from GenericSAXHandler
void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
void myEndElement (int elemente)
Called when a closing tag occurs.
Private Member Functions
SAXWeightsHandler & operator= (const SAXWeightsHandler &src)
we made the assignment operator invalid
SAXWeightsHandler (const SAXWeightsHandler &src)
we made the copy constructor invalid
void tryParse (const SUMOSAXAttributes &attrs, bool isEdge)
Parses the efforts of a lane for the previously read times.
Private Attributes
std::string myCurrentEdgeID
the edge which is currently being processed
SUMOReal myCurrentTimeBeg
the begin of the time period that is currently processed
SUMOReal myCurrentTimeEnd
the end of the time period that is currently processed
std::vector< ToRetrieveDefinition * > myDefinitions
List of definitions what shall be read and whereto stored while parsing the file.
Detailed Description
An XML-handler for network weights.
As network weights are used both in the simulation and the routers, a base class for loading them was built. Instances of this class should be supplied with at least one definition about what shall be retrieved (ToRetrieveDefinition, defined as inner class) which also contains the information about the retriever (EdgeFloatTimeLineRetriever, defined as inner class).
The ToRetrieveDefinition names the attribute which the SAXWeightsHandler shall parse and reporte. Within the parsed xml-file these attributes may be embedded in "lane" or "edge" elements, one for each edge or for each lane (see below). These elements should be embedded in interval-tags which specify the time the weight is valid at. The boolean "edgeBased" tells SAXWeightsHandler whether the weights are supplied on edge- or on lane-basis (whether it shall parse the "edge" or the "lane" elements).
Examples for files the SAXWeightsHandler can handle are the edgedump and the lanedump generated by the simulation.
The EdgeFloatTimeLineRetriever to which read values will be reported should have the method "addEdgeWeight" implemented. It wil be supplied with the current edge name, the interval the weight is valid for and the value.
Definition at line 76 of file SAXWeightsHandler.h.
Constructor & Destructor Documentation
SAXWeightsHandler::SAXWeightsHandler (const std::vector< ToRetrieveDefinition * > & defs, const std::string & file)
Constructor.
Gets a list of retriever definitions. Please note that the retrievers are not deleted!
Definition at line 66 of file SAXWeightsHandler.cpp.
SAXWeightsHandler::SAXWeightsHandler (ToRetrieveDefinition * def, const std::string & file)
Constructor.
Gets a single definition. Please note that the retrievers are not deleted!
Definition at line 72 of file SAXWeightsHandler.cpp.
References myDefinitions.
SAXWeightsHandler::~SAXWeightsHandler ()
Destructor.
Definition at line 80 of file SAXWeightsHandler.cpp.
References myDefinitions.
SAXWeightsHandler::SAXWeightsHandler (const SAXWeightsHandler & src) private
we made the copy constructor invalid
Member Function Documentation
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 192 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 175 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 211 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), MSRouteHandler::myStartElement(), and MSRouteHandler::parseWalkPos().
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 217 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), MSStateHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 227 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void SAXWeightsHandler::myEndElement (int elemente) protected virtual
Called when a closing tag occurs.
Parameters
[in] element ID of the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myEndElement
Reimplemented from GenericSAXHandler.
Definition at line 153 of file SAXWeightsHandler.cpp.
References myCurrentEdgeID, myCurrentTimeBeg, myCurrentTimeEnd, myDefinitions, SUMO_TAG_EDGE, and SUMOReal.
void SAXWeightsHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 88 of file SAXWeightsHandler.cpp.
References SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), myCurrentEdgeID, myCurrentTimeBeg, myCurrentTimeEnd, SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_TAG_EDGE, SUMO_TAG_INTERVAL, SUMO_TAG_LANE, SUMOReal, and tryParse().
SAXWeightsHandler& SAXWeightsHandler::operator= (const SAXWeightsHandler & src) private
we made the assignment operator invalid
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 167 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void SAXWeightsHandler::tryParse (const SUMOSAXAttributes & attrs, bool isEdge) private
Parses the efforts of a lane for the previously read times.
Definition at line 114 of file SAXWeightsHandler.cpp.
References SUMOSAXAttributes::getFloat(), SUMOSAXAttributes::hasAttribute(), myCurrentEdgeID, myCurrentTimeBeg, myDefinitions, toString(), and WRITE_ERROR.
Referenced by myStartElement().
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 205 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
std::string SAXWeightsHandler::myCurrentEdgeID private
the edge which is currently being processed
Definition at line 209 of file SAXWeightsHandler.h.
Referenced by myEndElement(), myStartElement(), and tryParse().
SUMOReal SAXWeightsHandler::myCurrentTimeBeg private
the begin of the time period that is currently processed
Definition at line 203 of file SAXWeightsHandler.h.
Referenced by myEndElement(), myStartElement(), and tryParse().
SUMOReal SAXWeightsHandler::myCurrentTimeEnd private
the end of the time period that is currently processed
Definition at line 206 of file SAXWeightsHandler.h.
Referenced by myEndElement(), and myStartElement().
std::vector<ToRetrieveDefinition*> SAXWeightsHandler::myDefinitions private
List of definitions what shall be read and whereto stored while parsing the file.
Definition at line 200 of file SAXWeightsHandler.h.
Referenced by myEndElement(), SAXWeightsHandler(), tryParse(), and ~SAXWeightsHandler().
The documentation for this class was generated from the following files:
SAXWeightsHandler.h
SAXWeightsHandler.cpp