SUMO - Simulation of Urban MObility: FX Namespace Reference
FX Namespace Reference
Data Structures
class FXRealSpinDial
Spinner control.
class FXRealSpinDialBtn
class FXRealSpinDialDial
class FXRealSpinDialText
Enumerations
enum {
SPINDIAL_CYCLIC = SPIN_CYCLIC, SPINDIAL_NOTEXT = SPIN_NOTEXT, SPINDIAL_NOMAX = SPIN_NOMAX, SPINDIAL_NOMIN = SPIN_NOMIN,
SPINDIAL_LOG = 0x00200000, SPINDIAL_NODIAL = 0x00400000, SPINDIAL_NOBUTTONS = 0x00800000, SPINDIAL_NORMAL = SPINDIAL_NOBUTTONS
}
enum { SPINDIAL_INC_NORMAL = 0, SPINDIAL_INC_FINE = -1, SPINDIAL_INC_COARSE = 1 }
Functions
FXDEFMAP (FXRealSpinDialDial) FXSpinDialMap[]
FXDEFMAP (FXRealSpinDialBtn) FXSpinDialBtnMap[]
FXDEFMAP (FXRealSpinDialText) FXSpinDialTextMap[]
FXDEFMAP (FXRealSpinDial) FXRealSpinDialMap[]
Enumeration Type Documentation
anonymous enum
Enumerator
SPINDIAL_CYCLIC
SPINDIAL_NOTEXT
SPINDIAL_NOMAX
SPINDIAL_NOMIN
SPINDIAL_LOG
SPINDIAL_NODIAL
SPINDIAL_NOBUTTONS
SPINDIAL_NORMAL
Definition at line 46 of file FXRealSpinDial.h.
anonymous enum
Enumerator
SPINDIAL_INC_NORMAL
SPINDIAL_INC_FINE
SPINDIAL_INC_COARSE
Definition at line 57 of file FXRealSpinDial.h.
Function Documentation
FX::FXDEFMAP (FXRealSpinDialDial)
Referenced by FX::FXRealSpinDialBtn::FXRealSpinDialBtn(), FX::FXRealSpinDialDial::FXRealSpinDialDial(), and FX::FXRealSpinDialText::onCmdSetRealValue().
FX::FXDEFMAP (FXRealSpinDialBtn)
FX::FXDEFMAP (FXRealSpinDialText)
FX::FXDEFMAP (FXRealSpinDial)