SUMO - Simulation of Urban MObility: DijkstraRouterTT< E, V, PF > Class Template Reference
DijkstraRouterTT< E, V, PF > Class Template Reference
Computes the shortest path through a network using the Dijkstra algorithm.
#include <DijkstraRouterTT.h>
Data Structures
struct EdgeInfo
class EdgeInfoByTTComparator
Public Types
typedef SUMOReal(* Operation) (const E *const, const V *const, SUMOReal)
Public Member Functions
void buildPathFrom (const EdgeInfo *rbegin, std::vector< const E * > &edges)
Builds the path from marked edges.
virtual SUMOAbstractRouter< E, V > * clone ()
virtual bool compute (const E *from, const E *to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > &into)
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
DijkstraRouterTT (const std::vector< E * > &edges, bool unbuildIsWarning, Operation operation)
Constructor.
DijkstraRouterTT (const std::vector< EdgeInfo > &edgeInfos, bool unbuildIsWarning, Operation operation)
void endQuery (int visits)
const EdgeInfo & getEdgeInfo (int index) const
SUMOReal getEffort (const E *const e, const V *const v, SUMOReal t) const
void init ()
SUMOReal recomputeCosts (const std::vector< const E * > &edges, const V *const v, SUMOTime msTime) const
void setBulkMode (const bool mode)
void startQuery ()
virtual ~DijkstraRouterTT ()
Destructor.
Protected Attributes
bool myBulkMode
whether we are currently operating several route queries in a bulk
Operation myOperation
The object's operation to perform.
Private Attributes
EdgeInfoByTTComparator myComparator
std::vector< EdgeInfo > myEdgeInfos
The container of edge information.
MsgHandler *const myErrorMsgHandler
the handler for routing errors
std::vector< EdgeInfo * > myFound
list of visited Edges (for resetting)
std::vector< EdgeInfo * > myFrontierList
A container for reusage of the min edge heap.
Detailed Description
template<class E, class V, class PF>
class DijkstraRouterTT< E, V, PF >
Computes the shortest path through a network using the Dijkstra algorithm.
The template parameters are:
Parameters
E The edge class to use (MSEdge/ROEdge)
V The vehicle class to use (MSVehicle/ROVehicle)
PF The prohibition function to use (prohibited_withPermissions/noProhibitions)
EC The class to retrieve the effort for an edge from
The router is edge-based. It must know the number of edges for internal reasons and whether a missing connection between two given edges (unbuild route) shall be reported as an error or as a warning.
Definition at line 71 of file DijkstraRouterTT.h.
Member Typedef Documentation
template<class E, class V, class PF> typedef SUMOReal(* DijkstraRouterTT< E, V, PF >::Operation) (const E *const, const V *const, SUMOReal)
Definition at line 74 of file DijkstraRouterTT.h.
Constructor & Destructor Documentation
template<class E, class V, class PF> DijkstraRouterTT< E, V, PF >::DijkstraRouterTT (const std::vector< E * > & edges, bool unbuildIsWarning, Operation operation) inline
Constructor.
Definition at line 121 of file DijkstraRouterTT.h.
template<class E, class V, class PF> DijkstraRouterTT< E, V, PF >::DijkstraRouterTT (const std::vector< EdgeInfo > & edgeInfos, bool unbuildIsWarning, Operation operation) inline
Definition at line 129 of file DijkstraRouterTT.h.
template<class E, class V, class PF> virtual DijkstraRouterTT< E, V, PF >::~DijkstraRouterTT () inline virtual
Destructor.
Definition at line 138 of file DijkstraRouterTT.h.
Member Function Documentation
template<class E, class V, class PF> void DijkstraRouterTT< E, V, PF >::buildPathFrom (const EdgeInfo * rbegin, std::vector< const E * > & edges) inline
Builds the path from marked edges.
Definition at line 266 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> virtual SUMOAbstractRouter<E, V>* DijkstraRouterTT< E, V, PF >::clone () inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 140 of file DijkstraRouterTT.h.
template<class E, class V, class PF> virtual bool DijkstraRouterTT< E, V, PF >::compute (const E * from, const E * to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > & into) inline virtual
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Implements SUMOAbstractRouter< E, V >.
Definition at line 159 of file DijkstraRouterTT.h.
template<class E, class V> void SUMOAbstractRouter< E, V >::endQuery (int visits) inline inherited
Definition at line 96 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and CHRouter< E, V, PF >::compute().
template<class E, class V, class PF> const EdgeInfo& DijkstraRouterTT< E, V, PF >::getEdgeInfo (int index) const inline
Definition at line 275 of file DijkstraRouterTT.h.
template<class E, class V> SUMOReal SUMOAbstractRouter< E, V >::getEffort (const E *const e, const V *const v, SUMOReal t) const inline inherited
Definition at line 87 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), CHRouterWrapper< E, V, PF >::recomputeCosts(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), CHRouter< E, V, PF >::recomputeCosts(), and CHRouter< E, V, PF >::synchronize().
template<class E, class V, class PF> void DijkstraRouterTT< E, V, PF >::init () inline
Definition at line 144 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> SUMOReal DijkstraRouterTT< E, V, PF >::recomputeCosts (const std::vector< const E * > & edges, const V *const v, SUMOTime msTime) const inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 252 of file DijkstraRouterTT.h.
template<class E, class V> void SUMOAbstractRouter< E, V >::setBulkMode (const bool mode) inline inherited
Definition at line 101 of file SUMOAbstractRouter.h.
Referenced by ROMAAssignments::incremental().
template<class E, class V> void SUMOAbstractRouter< E, V >::startQuery () inline inherited
Definition at line 91 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and CHRouter< E, V, PF >::compute().
Field Documentation
template<class E, class V> bool SUMOAbstractRouter< E, V >::myBulkMode protected inherited
whether we are currently operating several route queries in a bulk
Definition at line 110 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::setBulkMode().
template<class E, class V, class PF> EdgeInfoByTTComparator DijkstraRouterTT< E, V, PF >::myComparator private
Definition at line 288 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> std::vector<EdgeInfo> DijkstraRouterTT< E, V, PF >::myEdgeInfos private
The container of edge information.
Definition at line 281 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::DijkstraRouterTT(), and DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::getEdgeInfo().
template<class E, class V, class PF> MsgHandler* const DijkstraRouterTT< E, V, PF >::myErrorMsgHandler private
the handler for routing errors
Definition at line 291 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), and DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> std::vector<EdgeInfo*> DijkstraRouterTT< E, V, PF >::myFound private
list of visited Edges (for resetting)
Definition at line 286 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::init().
template<class E, class V, class PF> std::vector<EdgeInfo*> DijkstraRouterTT< E, V, PF >::myFrontierList private
A container for reusage of the min edge heap.
Definition at line 284 of file DijkstraRouterTT.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::init().
template<class E, class V> Operation SUMOAbstractRouter< E, V >::myOperation protected inherited
The object's operation to perform.
Definition at line 107 of file SUMOAbstractRouter.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), CHRouter< E, V, PF >::clone(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::getEffort().
The documentation for this class was generated from the following file:
DijkstraRouterTT.h