SUMO - Simulation of Urban MObility: GNERerouter::destProbReroute Class Reference
GNERerouter::destProbReroute Class Reference
#include <GNERerouter.h>
Public Member Functions
destProbReroute (std::string newDestinationId, SUMOReal probability)
constructor
std::string getNewDestinationId () const
id of new edge destination
SUMOReal getProbability () const
get probability
void setProbability (SUMOReal probability)
set probability
~destProbReroute ()
destructor
Private Attributes
std::string myNewDestinationId
id of new edge destination
SUMOReal myProbability
probability with which a vehicle will use the given edge as destination
Detailed Description
Definition at line 103 of file GNERerouter.h.
Constructor & Destructor Documentation
GNERerouter::destProbReroute::destProbReroute (std::string newDestinationId, SUMOReal probability)
constructor
Definition at line 159 of file GNERerouter.cpp.
GNERerouter::destProbReroute::~destProbReroute ()
destructor
Definition at line 165 of file GNERerouter.cpp.
Member Function Documentation
std::string GNERerouter::destProbReroute::getNewDestinationId () const
id of new edge destination
Definition at line 170 of file GNERerouter.cpp.
References myNewDestinationId, and SUMOReal.
Referenced by GNERerouter::rerouterInterval::insertDestProbReroutes(), and GNERerouter::rerouterInterval::removeDestProbReroutes().
SUMOReal GNERerouter::destProbReroute::getProbability () const
get probability
Definition at line 176 of file GNERerouter.cpp.
References myProbability.
void GNERerouter::destProbReroute::setProbability (SUMOReal probability)
set probability
Exceptions
InvalidArgument if probability isn't valid
Definition at line 182 of file GNERerouter.cpp.
References myProbability, and toString().
Field Documentation
std::string GNERerouter::destProbReroute::myNewDestinationId private
id of new edge destination
Definition at line 123 of file GNERerouter.h.
Referenced by getNewDestinationId().
SUMOReal GNERerouter::destProbReroute::myProbability private
probability with which a vehicle will use the given edge as destination
Definition at line 126 of file GNERerouter.h.
Referenced by getProbability(), and setProbability().
The documentation for this class was generated from the following files:
GNERerouter.h
GNERerouter.cpp