SUMO - Simulation of Urban MObility: MSEdge::transportable_by_position_sorter Class Reference
MSEdge::transportable_by_position_sorter Class Reference
Sorts transportables by their positions.
#include <MSEdge.h>
Public Member Functions
int operator() (const MSTransportable *const c1, const MSTransportable *const c2) const
comparing operator
transportable_by_position_sorter (SUMOTime timestep)
constructor
Private Attributes
SUMOTime myTime
Detailed Description
Sorts transportables by their positions.
Definition at line 727 of file MSEdge.h.
Constructor & Destructor Documentation
MSEdge::transportable_by_position_sorter::transportable_by_position_sorter (SUMOTime timestep) inline explicit
constructor
Definition at line 730 of file MSEdge.h.
References MSEdge::by_id_sorter::operator()().
Member Function Documentation
int MSEdge::transportable_by_position_sorter::operator() (const MSTransportable *const c1, const MSTransportable *const c2) const
comparing operator
Definition at line 803 of file MSEdge.cpp.
References MSTransportable::getCurrentStage(), MSTransportable::Stage::getEdgePos(), MSTransportable::getID(), and SUMOReal.
Field Documentation
SUMOTime MSEdge::transportable_by_position_sorter::myTime private
Definition at line 735 of file MSEdge.h.
The documentation for this class was generated from the following files:
MSEdge.h
MSEdge.cpp