SUMO - Simulation of Urban MObility: CHRouterWrapper< E, V, PF > Class Template Reference
CHRouterWrapper< E, V, PF > Class Template Reference
Computes the shortest path through a contracted network.
#include <CHRouterWrapper.h>
Public Types
typedef SUMOReal(* Operation) (const E *const, const V *const, SUMOReal)
Type of the function that is used to retrieve the edge effort.
Public Member Functions
CHRouterWrapper (const std::vector< E * > &edges, bool ignoreErrors, Operation operation, SUMOTime begin, SUMOTime weightPeriod)
Constructor.
virtual SUMOAbstractRouter< E, V > * clone ()
bool compute (const E *from, const E *to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > &into)
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
void endQuery (int visits)
SUMOReal getEffort (const E *const e, const V *const v, SUMOReal t) const
SUMOReal recomputeCosts (const std::vector< const E * > &edges, const V *const v, SUMOTime msTime) const
void setBulkMode (const bool mode)
void startQuery ()
~CHRouterWrapper ()
Protected Attributes
bool myBulkMode
whether we are currently operating several route queries in a bulk
Operation myOperation
The object's operation to perform.
Private Types
typedef CHRouter< E, V, noProhibitions< E, V > > CHRouterType
typedef std::map< std::pair< const SUMOVehicleClass, const SUMOReal >, CHRouterType * > RouterMap
Private Attributes
SUMOTime myBegin
const std::vector< E * > & myEdges
all edges with numerical ids
bool myIgnoreErrors
RouterMap myRouters
SUMOTime myWeightPeriod
Detailed Description
template<class E, class V, class PF>
class CHRouterWrapper< E, V, PF >
Computes the shortest path through a contracted network.
The template parameters are:
Parameters
E The edge class to use (MSEdge/ROEdge)
V The vehicle class to use (MSVehicle/ROVehicle)
PF The prohibition function to use (prohibited_withPermissions/noProhibitions)
The router is edge-based. It must know the number of edges for internal reasons and whether a missing connection between two given edges (unbuild route) shall be reported as an error or as a warning.
Definition at line 68 of file CHRouterWrapper.h.
Member Typedef Documentation
template<class E, class V, class PF> typedef CHRouter<E, V, noProhibitions<E, V> > CHRouterWrapper< E, V, PF >::CHRouterType private
Definition at line 124 of file CHRouterWrapper.h.
template<class E, class V, class PF> typedef SUMOReal(* CHRouterWrapper< E, V, PF >::Operation) (const E *const, const V *const, SUMOReal)
Type of the function that is used to retrieve the edge effort.
Definition at line 72 of file CHRouterWrapper.h.
template<class E, class V, class PF> typedef std::map<std::pair<const SUMOVehicleClass, const SUMOReal>, CHRouterType*> CHRouterWrapper< E, V, PF >::RouterMap private
Definition at line 125 of file CHRouterWrapper.h.
Constructor & Destructor Documentation
template<class E, class V, class PF> CHRouterWrapper< E, V, PF >::CHRouterWrapper (const std::vector< E * > & edges, bool ignoreErrors, Operation operation, SUMOTime begin, SUMOTime weightPeriod) inline
Constructor.
Definition at line 76 of file CHRouterWrapper.h.
template<class E, class V, class PF> CHRouterWrapper< E, V, PF >::~CHRouterWrapper () inline
Definition at line 84 of file CHRouterWrapper.h.
References CHRouterWrapper< E, V, PF >::myRouters.
Member Function Documentation
template<class E, class V, class PF> virtual SUMOAbstractRouter<E, V>* CHRouterWrapper< E, V, PF >::clone () inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 91 of file CHRouterWrapper.h.
References CHRouterWrapper< E, V, PF >::myBegin, CHRouterWrapper< E, V, PF >::myEdges, CHRouterWrapper< E, V, PF >::myIgnoreErrors, SUMOAbstractRouter< E, V >::myOperation, and CHRouterWrapper< E, V, PF >::myWeightPeriod.
template<class E, class V, class PF> bool CHRouterWrapper< E, V, PF >::compute (const E * from, const E * to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > & into) inline virtual
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Implements SUMOAbstractRouter< E, V >.
Definition at line 95 of file CHRouterWrapper.h.
References CHRouterWrapper< E, V, PF >::myEdges, CHRouterWrapper< E, V, PF >::myIgnoreErrors, CHRouterWrapper< E, V, PF >::myRouters, and CHRouterWrapper< E, V, PF >::myWeightPeriod.
template<class E, class V> void SUMOAbstractRouter< E, V >::endQuery (int visits) inline inherited
Definition at line 96 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and CHRouter< E, V, PF >::compute().
template<class E, class V> SUMOReal SUMOAbstractRouter< E, V >::getEffort (const E *const e, const V *const v, SUMOReal t) const inline inherited
Definition at line 87 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), CHRouterWrapper< E, V, PF >::recomputeCosts(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), CHRouter< E, V, PF >::recomputeCosts(), and CHRouter< E, V, PF >::synchronize().
template<class E, class V, class PF> SUMOReal CHRouterWrapper< E, V, PF >::recomputeCosts (const std::vector< const E * > & edges, const V *const v, SUMOTime msTime) const inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 108 of file CHRouterWrapper.h.
References SUMOAbstractRouter< E, V >::getEffort(), STEPS2TIME, SUMOReal, and WRITE_WARNING.
template<class E, class V> void SUMOAbstractRouter< E, V >::setBulkMode (const bool mode) inline inherited
Definition at line 101 of file SUMOAbstractRouter.h.
Referenced by ROMAAssignments::incremental().
template<class E, class V> void SUMOAbstractRouter< E, V >::startQuery () inline inherited
Definition at line 91 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and CHRouter< E, V, PF >::compute().
Field Documentation
template<class E, class V, class PF> SUMOTime CHRouterWrapper< E, V, PF >::myBegin private
Definition at line 134 of file CHRouterWrapper.h.
Referenced by CHRouterWrapper< E, V, PF >::clone().
template<class E, class V> bool SUMOAbstractRouter< E, V >::myBulkMode protected inherited
whether we are currently operating several route queries in a bulk
Definition at line 110 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::setBulkMode().
template<class E, class V, class PF> const std::vector<E*>& CHRouterWrapper< E, V, PF >::myEdges private
all edges with numerical ids
Definition at line 130 of file CHRouterWrapper.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), and CHRouterWrapper< E, V, PF >::compute().
template<class E, class V, class PF> bool CHRouterWrapper< E, V, PF >::myIgnoreErrors private
Definition at line 132 of file CHRouterWrapper.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), and CHRouterWrapper< E, V, PF >::compute().
template<class E, class V> Operation SUMOAbstractRouter< E, V >::myOperation protected inherited
The object's operation to perform.
Definition at line 107 of file SUMOAbstractRouter.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), CHRouter< E, V, PF >::clone(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::getEffort().
template<class E, class V, class PF> RouterMap CHRouterWrapper< E, V, PF >::myRouters private
Definition at line 127 of file CHRouterWrapper.h.
Referenced by CHRouterWrapper< E, V, PF >::compute(), and CHRouterWrapper< E, V, PF >::~CHRouterWrapper().
template<class E, class V, class PF> SUMOTime CHRouterWrapper< E, V, PF >::myWeightPeriod private
Definition at line 135 of file CHRouterWrapper.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), and CHRouterWrapper< E, V, PF >::compute().
The documentation for this class was generated from the following file:
CHRouterWrapper.h