SUMO - Simulation of Urban MObility: ROFrame Class Reference
ROFrame Class Reference
Sets and checks options for routing.
#include <ROFrame.h>
Static Public Member Functions
static bool checkOptions (OptionsCont &oc)
Checks whether options are valid.
static void fillOptions (OptionsCont &oc, bool forDuarouter)
Inserts options used by routing applications into the OptionsCont-singleton.
Detailed Description
Sets and checks options for routing.
Normally, these methods are called from another frame (ROJTRFrame, RODUAFrame)...
Definition at line 50 of file ROFrame.h.
Member Function Documentation
bool ROFrame::checkOptions (OptionsCont & oc) static
Checks whether options are valid.
To be valid,
an output file must be given
max-alternatives must not be lower than 2
Parameters
[in] oc The options container to fill
Returns
Whether all needed options are set
Todo:
Why is the container given? Everywhere else not...
probably, more things should be checked...
Definition at line 192 of file ROFrame.cpp.
References OptionsCont::getInt(), OptionsCont::isSet(), and WRITE_ERROR.
Referenced by ROJTRFrame::checkOptions(), and RODUAFrame::checkOptions().
void ROFrame::fillOptions (OptionsCont & oc, bool forDuarouter) static
Inserts options used by routing applications into the OptionsCont-singleton.
Parameters
[in] oc The options container to fill
[in] forDuarouter whether duarouter-specific options shall be added
Todo:
Why is the container given? Everywhere else not...
Definition at line 54 of file ROFrame.cpp.
References OptionsCont::addDescription(), OptionsCont::addSynonyme(), OptionsCont::doRegister(), and SUMOTIME_MAXSTRING.
Referenced by ROJTRFrame::fillOptions(), and RODUAFrame::fillOptions().
The documentation for this class was generated from the following files:
ROFrame.h
ROFrame.cpp