SUMO - Simulation of Urban MObility: PedestrianState Class Reference
PedestrianState Class Reference abstract
abstract base class for managing callbacks to retrieve various state information from the model
#include <MSPModel.h>
Public Member Functions
virtual SUMOReal getAngle (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const =0
return the direction in which the person faces in degrees
virtual SUMOReal getEdgePos (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const =0
return the offset from the start of the current edge measured in its natural direction
virtual const MSEdge * getNextEdge (const MSPerson::MSPersonStage_Walking &stage) const =0
return the list of internal edges if the pedestrian is on an intersection
virtual Position getPosition (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const =0
return the network coordinate of the person
virtual SUMOReal getSpeed (const MSPerson::MSPersonStage_Walking &stage) const =0
return the current speed of the person
virtual SUMOTime getWaitingTime (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const =0
return the time the person spent standing
virtual ~PedestrianState ()
Detailed Description
abstract base class for managing callbacks to retrieve various state information from the model
Definition at line 93 of file MSPModel.h.
Constructor & Destructor Documentation
virtual PedestrianState::~PedestrianState () inline virtual
Definition at line 95 of file MSPModel.h.
References SUMOReal.
Member Function Documentation
virtual SUMOReal PedestrianState::getAngle (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const pure virtual
return the direction in which the person faces in degrees
Implemented in MSPModel_Striping::PState, and MSPModel_NonInteracting::PState.
Referenced by MSPerson::MSPersonStage_Walking::getAngle().
virtual SUMOReal PedestrianState::getEdgePos (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const pure virtual
return the offset from the start of the current edge measured in its natural direction
Implemented in MSPModel_Striping::PState, and MSPModel_NonInteracting::PState.
Referenced by MSPerson::MSPersonStage_Walking::getEdgePos().
virtual const MSEdge* PedestrianState::getNextEdge (const MSPerson::MSPersonStage_Walking & stage) const pure virtual
return the list of internal edges if the pedestrian is on an intersection
Implemented in MSPModel_Striping::PState, and MSPModel_NonInteracting::PState.
Referenced by MSPerson::getNextEdgePtr().
virtual Position PedestrianState::getPosition (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const pure virtual
return the network coordinate of the person
Implemented in MSPModel_Striping::PState, and MSPModel_NonInteracting::PState.
Referenced by MSPerson::MSPersonStage_Walking::getPosition().
virtual SUMOReal PedestrianState::getSpeed (const MSPerson::MSPersonStage_Walking & stage) const pure virtual
return the current speed of the person
Implemented in MSPModel_Striping::PState, and MSPModel_NonInteracting::PState.
Referenced by MSPerson::MSPersonStage_Walking::getSpeed().
virtual SUMOTime PedestrianState::getWaitingTime (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const pure virtual
return the time the person spent standing
Implemented in MSPModel_Striping::PState, and MSPModel_NonInteracting::PState.
Referenced by MSPerson::MSPersonStage_Walking::getWaitingTime().
The documentation for this class was generated from the following file:
MSPModel.h