SUMO - Simulation of Urban MObility: LogitCalculator< R, E, V > Class Template Reference
LogitCalculator< R, E, V > Class Template Reference
Cost calculation with c-logit or logit method.
#include <LogitCalculator.h>
Public Member Functions
void calculateProbabilities (std::vector< R * > alternatives, const V *const veh, const SUMOTime time)
calculate the probabilities in the logit model
int getMaxRouteNumber () const
bool keepRoutes () const
LogitCalculator (const SUMOReal beta, const SUMOReal gamma, const SUMOReal theta)
Constructor.
void setCosts (R *route, const SUMOReal costs, const bool) const
bool skipRouteCalculation () const
virtual ~LogitCalculator ()
Destructor.
Static Public Member Functions
static void cleanup ()
static RouteCostCalculator< R, E, V > & getCalculator ()
Private Member Functions
SUMOReal getBetaForCLogit (const std::vector< R * > alternatives) const
calculate the scaling factor in the logit model
SUMOReal getThetaForCLogit (const std::vector< R * > alternatives) const
calculate the scaling factor in the logit model
LogitCalculator & operator= (const LogitCalculator &s)
invalidated assignment operator
Private Attributes
const SUMOReal myBeta
logit beta - value
std::map< const R *, SUMOReal > myCommonalities
The route commonality factors for c-logit.
const SUMOReal myGamma
logit gamma - value
const SUMOReal myTheta
logit theta - value
Detailed Description
template<class R, class E, class V>
class LogitCalculator< R, E, V >
Cost calculation with c-logit or logit method.
Definition at line 47 of file LogitCalculator.h.
Constructor & Destructor Documentation
template<class R , class E , class V > LogitCalculator< R, E, V >::LogitCalculator (const SUMOReal beta, const SUMOReal gamma, const SUMOReal theta) inline
Constructor.
Definition at line 50 of file LogitCalculator.h.
template<class R , class E , class V > virtual LogitCalculator< R, E, V >::~LogitCalculator () inline virtual
Destructor.
Definition at line 54 of file LogitCalculator.h.
Member Function Documentation
template<class R , class E , class V > void LogitCalculator< R, E, V >::calculateProbabilities (std::vector< R * > alternatives, const V *const veh, const SUMOTime time) inline virtual
calculate the probabilities in the logit model
Implements RouteCostCalculator< R, E, V >.
Definition at line 61 of file LogitCalculator.h.
References LogitCalculator< R, E, V >::getBetaForCLogit(), LogitCalculator< R, E, V >::getThetaForCLogit(), LogitCalculator< R, E, V >::myBeta, LogitCalculator< R, E, V >::myCommonalities, LogitCalculator< R, E, V >::myGamma, LogitCalculator< R, E, V >::myTheta, STEPS2TIME, and SUMOReal.
template<class R, class E, class V> static void RouteCostCalculator< R, E, V >::cleanup () inline static inherited
Definition at line 55 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::calculateProbabilities(), RouteCostCalculator< R, E, V >::myInstance, RouteCostCalculator< R, E, V >::setCosts(), and SUMOReal.
Referenced by RONet::cleanup().
template<class R , class E , class V > SUMOReal LogitCalculator< R, E, V >::getBetaForCLogit (const std::vector< R * > alternatives) const inline private
calculate the scaling factor in the logit model
Definition at line 105 of file LogitCalculator.h.
References max, min, and SUMOReal.
Referenced by LogitCalculator< R, E, V >::calculateProbabilities().
template<class R , class E , class V > RouteCostCalculator< R, E, V > & RouteCostCalculator< R, E, V >::getCalculator () static inherited
Definition at line 115 of file RouteCostCalculator.h.
References OptionsCont::getFloat(), OptionsCont::getOptions(), OptionsCont::getString(), and RouteCostCalculator< R, E, V >::myInstance.
Referenced by RORouteDef::addAlternative(), and ROMAAssignments::sue().
template<class R, class E, class V> int RouteCostCalculator< R, E, V >::getMaxRouteNumber () const inline inherited
Definition at line 65 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::myMaxRouteNumber.
template<class R , class E , class V > SUMOReal LogitCalculator< R, E, V >::getThetaForCLogit (const std::vector< R * > alternatives) const inline private
calculate the scaling factor in the logit model
Definition at line 117 of file LogitCalculator.h.
References max, min, and SUMOReal.
Referenced by LogitCalculator< R, E, V >::calculateProbabilities().
template<class R, class E, class V> bool RouteCostCalculator< R, E, V >::keepRoutes () const inline inherited
Definition at line 69 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::myKeepRoutes.
Referenced by RORouteDef::addAlternative().
template<class R , class E , class V > LogitCalculator& LogitCalculator< R, E, V >::operator= (const LogitCalculator< R, E, V > & s) private
invalidated assignment operator
template<class R , class E , class V > void LogitCalculator< R, E, V >::setCosts (R * route, const SUMOReal costs, const bool) const inline virtual
Implements RouteCostCalculator< R, E, V >.
Definition at line 56 of file LogitCalculator.h.
template<class R, class E, class V> bool RouteCostCalculator< R, E, V >::skipRouteCalculation () const inline inherited
Definition at line 73 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::mySkipRouteCalculation.
Field Documentation
template<class R , class E , class V > const SUMOReal LogitCalculator< R, E, V >::myBeta private
logit beta - value
Definition at line 144 of file LogitCalculator.h.
Referenced by LogitCalculator< R, E, V >::calculateProbabilities().
template<class R , class E , class V > std::map<const R*, SUMOReal> LogitCalculator< R, E, V >::myCommonalities private
The route commonality factors for c-logit.
Definition at line 153 of file LogitCalculator.h.
Referenced by LogitCalculator< R, E, V >::calculateProbabilities().
template<class R , class E , class V > const SUMOReal LogitCalculator< R, E, V >::myGamma private
logit gamma - value
Definition at line 147 of file LogitCalculator.h.
Referenced by LogitCalculator< R, E, V >::calculateProbabilities().
template<class R , class E , class V > const SUMOReal LogitCalculator< R, E, V >::myTheta private
logit theta - value
Definition at line 150 of file LogitCalculator.h.
Referenced by LogitCalculator< R, E, V >::calculateProbabilities().
The documentation for this class was generated from the following file:
LogitCalculator.h