SUMO - Simulation of Urban MObility: ShapeHandler Class Reference
ShapeHandler Class Reference abstract
The XML-Handler for network loading.
#include <ShapeHandler.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
ShapeHandler (const std::string &file, ShapeContainer &sc)
Constructor.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
virtual ~ShapeHandler ()
Destructor.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Static Public Member Functions
static bool loadFiles (const std::vector< std::string > &files, ShapeHandler &sh)
loads all of the given files
Protected Member Functions
void addPOI (const SUMOSAXAttributes &attrs, const bool ignorePruning, const bool useProcessing)
adds a POI
void addPoly (const SUMOSAXAttributes &attrs, const bool ignorePruning, const bool useProcessing)
adds a polygon
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual Position getLanePos (const std::string &poiID, const std::string &laneID, SUMOReal lanePos)=0
get position for a given laneID
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
virtual void myEndElement (int element)
Callback method for a closing tag to implement by derived classes.
void setDefaults (const std::string &prefix, const RGBColor &color, const SUMOReal layer, const bool fill=false)
inherited from GenericSAXHandler
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
Protected Attributes
ShapeContainer & myShapeContainer
Private Member Functions
ShapeHandler & operator= (const ShapeHandler &s)
ShapeHandler (const ShapeHandler &s)
Private Attributes
RGBColor myDefaultColor
The default color to use.
bool myDefaultFill
Information whether polygons should be filled.
SUMOReal myDefaultLayer
The default layer to use.
std::string myPrefix
The prefix to use.
Detailed Description
The XML-Handler for network loading.
The SAX2-handler responsible for parsing networks and routes to load. This is an extension of the MSRouteHandler as routes and vehicles may also be loaded from network descriptions.
Definition at line 56 of file ShapeHandler.h.
Constructor & Destructor Documentation
ShapeHandler::ShapeHandler (const std::string & file, ShapeContainer & sc)
Constructor.
Parameters
[in] file Name of the parsed file
[in,out] net The network to fill
[in] detBuilder The detector builder to use
[in] triggerBuilder The trigger builder to use
[in] edgeBuilder The builder of edges to use
[in] junctionBuilder The builder of junctions to use
Definition at line 55 of file ShapeHandler.cpp.
ShapeHandler::~ShapeHandler () virtual
Destructor.
Definition at line 60 of file ShapeHandler.cpp.
ShapeHandler::ShapeHandler (const ShapeHandler & s) private
invalid copy constructor
Member Function Documentation
void ShapeHandler::addPOI (const SUMOSAXAttributes & attrs, const bool ignorePruning, const bool useProcessing) protected
adds a POI
Definition at line 87 of file ShapeHandler.cpp.
References ShapeContainer::addPOI(), Shape::DEFAULT_ANGLE, Shape::DEFAULT_IMG_FILE, Shape::DEFAULT_IMG_HEIGHT, Shape::DEFAULT_IMG_WIDTH, SUMOSAXAttributes::get(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), GeoConvHelper::getFinal(), getLanePos(), SUMOSAXAttributes::getOpt(), GeoConvHelper::getProcessing(), SUMOSAXAttributes::hasAttribute(), FileHelpers::isAbsolute(), myDefaultColor, myDefaultLayer, myPrefix, myShapeContainer, Position::set(), SUMO_ATTR_ANGLE, SUMO_ATTR_COLOR, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_LANE, SUMO_ATTR_LAT, SUMO_ATTR_LAYER, SUMO_ATTR_LON, SUMO_ATTR_POSITION, SUMO_ATTR_TYPE, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMOReal, GeoConvHelper::usingGeoProjection(), WRITE_ERROR, GeoConvHelper::x2cartesian(), and GeoConvHelper::x2cartesian_const().
Referenced by myStartElement(), and PCLoaderXML::myStartElement().
void ShapeHandler::addPoly (const SUMOSAXAttributes & attrs, const bool ignorePruning, const bool useProcessing) protected
adds a polygon
Definition at line 152 of file ShapeHandler.cpp.
References ShapeContainer::addPolygon(), Shape::DEFAULT_ANGLE, Shape::DEFAULT_IMG_FILE, Shape::DEFAULT_TYPE, SUMOSAXAttributes::get(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), GeoConvHelper::getFinal(), SUMOSAXAttributes::getOpt(), GeoConvHelper::getProcessing(), SUMOSAXAttributes::hasAttribute(), FileHelpers::isAbsolute(), myDefaultColor, myDefaultFill, myDefaultLayer, myPrefix, myShapeContainer, SUMO_ATTR_ANGLE, SUMO_ATTR_COLOR, SUMO_ATTR_FILL, SUMO_ATTR_GEO, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_LAYER, SUMO_ATTR_SHAPE, SUMO_ATTR_TYPE, SUMOReal, WRITE_ERROR, WRITE_WARNING, GeoConvHelper::x2cartesian(), and GeoConvHelper::x2cartesian_const().
Referenced by myStartElement(), and PCLoaderXML::myStartElement().
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 192 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 175 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 211 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), MSRouteHandler::myStartElement(), and MSRouteHandler::parseWalkPos().
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 217 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), addPOI(), addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), MSStateHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
virtual Position ShapeHandler::getLanePos (const std::string & poiID, const std::string & laneID, SUMOReal lanePos) protected pure virtual
get position for a given laneID
Implemented in GNEApplicationWindow::GNEShapeHandler, PCLoaderXML, and NLShapeHandler.
Referenced by addPOI().
bool ShapeHandler::loadFiles (const std::vector< std::string > & files, ShapeHandler & sh) static
loads all of the given files
Definition at line 191 of file ShapeHandler.cpp.
References XMLSubSys::runParser(), and WRITE_MESSAGE.
Referenced by NLBuilder::build().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 227 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void GenericSAXHandler::myEndElement (int element) protected virtual inherited
Callback method for a closing tag to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The closed element, given as a int ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_OpenDrive, NIImporter_OpenStreetMap::RelationHandler, NIImporter_Vissim::NIVissimXMLHandler_Routenentscheidungsdefinition, NIImporter_Vissim::NIVissimXMLHandler_Geschwindigkeitsverteilungsdefinition, NIImporter_OpenStreetMap::EdgesHandler, PCLoaderOSM::EdgesHandler, NIImporter_Vissim::NIVissimXMLHandler_VWunschentscheidungsdefinition, NIImporter_OpenStreetMap::NodesHandler, NIImporter_Vissim::NIVissimXMLHandler_Fahrzeugklassendefinition, PCLoaderOSM::RelationsHandler, MSTriggeredRerouter, SAXWeightsHandler, PCLoaderOSM::NodesHandler, NLHandler, NIImporter_ITSUMO::Handler, MSLaneSpeedTrigger, NIImporter_SUMO, NIImporter_Vissim::NIVissimXMLHandler_Streckendefinition, NIXMLEdgesHandler, MSCalibrator, SUMORouteHandler, RORouteHandler, ODDistrictHandler, MSRouteHandler, RONetHandler, MSStateHandler, NIXMLTrafficLightsHandler, GUITriggeredRerouter, GNEPoly::GNEPolyHandler, and ROMARouteHandler.
Definition at line 231 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement(), NLHandler::networkVersion(), and SUMOSAXReader::parseNext().
void ShapeHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Todo:
Refactor/describe
Reimplemented from GenericSAXHandler.
Reimplemented in PCLoaderXML.
Definition at line 64 of file ShapeHandler.cpp.
References addPOI(), addPoly(), Shape::DEFAULT_LAYER, GLO_POI, myDefaultLayer, SUMO_TAG_POI, SUMO_TAG_POLY, SUMOReal, and WRITE_ERROR.
Referenced by NLHandler::networkVersion().
ShapeHandler& ShapeHandler::operator= (const ShapeHandler & s) private
invalid assignment operator
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 167 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
void ShapeHandler::setDefaults (const std::string & prefix, const RGBColor & color, const SUMOReal layer, const bool fill = false) protected
Definition at line 203 of file ShapeHandler.cpp.
References myDefaultColor, myDefaultFill, myDefaultLayer, and myPrefix.
Referenced by PCLoaderXML::myStartElement().
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 205 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
RGBColor ShapeHandler::myDefaultColor private
The default color to use.
Definition at line 116 of file ShapeHandler.h.
Referenced by addPOI(), addPoly(), and setDefaults().
bool ShapeHandler::myDefaultFill private
Information whether polygons should be filled.
Definition at line 120 of file ShapeHandler.h.
Referenced by addPoly(), and setDefaults().
SUMOReal ShapeHandler::myDefaultLayer private
The default layer to use.
Definition at line 118 of file ShapeHandler.h.
Referenced by addPOI(), addPoly(), myStartElement(), and setDefaults().
std::string ShapeHandler::myPrefix private
The prefix to use.
Definition at line 114 of file ShapeHandler.h.
Referenced by addPOI(), addPoly(), and setDefaults().
ShapeContainer& ShapeHandler::myShapeContainer protected
Definition at line 110 of file ShapeHandler.h.
Referenced by addPOI(), addPoly(), and PCLoaderXML::getLanePos().
The documentation for this class was generated from the following files:
ShapeHandler.h
ShapeHandler.cpp