SUMO - Simulation of Urban MObility: NBDistrict Class Reference
NBDistrict Class Reference
A class representing a single district.
#include <NBDistrict.h>
Public Member Functions
void addShape (const PositionVector &p)
Sets the shape of this district.
bool addSink (NBEdge *const sink, SUMOReal weight)
Adds a sink.
bool addSource (NBEdge *const source, SUMOReal weight)
Adds a source.
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
const std::string & getID () const
Returns the id.
const Position & getPosition () const
Returns the position of this district's center.
const PositionVector & getShape () const
Returns the shape.
const std::vector< NBEdge * > & getSinkEdges () const
Returns the sinks.
const std::vector< SUMOReal > & getSinkWeights () const
Returns the weights of the sinks.
const std::vector< NBEdge * > & getSourceEdges () const
Returns the sources.
const std::vector< SUMOReal > & getSourceWeights () const
Returns the weights of the sources.
NBDistrict (const std::string &id, const Position &pos)
Constructor with id, and position.
NBDistrict (const std::string &id)
Constructor without position.
void removeFromSinksAndSources (NBEdge *const e)
Removes the given edge from the lists of sources and sinks.
void replaceIncoming (const EdgeVector &which, NBEdge *const by)
Replaces incoming edges from the vector (sinks) by the given edge.
void replaceOutgoing (const EdgeVector &which, NBEdge *const by)
Replaces outgoing edges from the vector (source) by the given edge.
void setCenter (const Position &pos)
Sets the center coordinates.
void setID (const std::string &newID)
resets the id
~NBDistrict ()
Destructor.
Applying offset
void reshiftPosition (SUMOReal xoff, SUMOReal yoff)
Applies an offset to the district.
void mirrorX ()
mirror coordinates along the x-axis
Static Public Member Functions
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
Protected Attributes
std::string myID
The name of the object.
Private Types
typedef std::vector< SUMOReal > WeightsCont
Definition of a vector of connection weights.
Private Member Functions
NBDistrict (const NBDistrict &s)
NBDistrict & operator= (const NBDistrict &s)
Private Attributes
Position myPosition
The position of the district.
PositionVector myShape
The shape of the dsitrict.
EdgeVector mySinks
The sinks (connection from network to district)
WeightsCont mySinkWeights
The weights of the sinks.
EdgeVector mySources
The sources (connection from district to network)
WeightsCont mySourceWeights
The weights of the sources.
Detailed Description
A class representing a single district.
A "district" is an area within the network which may be referenced by O/D-matrices. It stems from importing VISUM-networks. Work with VISUM- -networks also made it necessary that a district knows the edges at which new vehicles shall approach the simulated network (sources) and those to use when leaving the network (sinks). These connections to the network are weighted.
Later work on VISUM required also parsing the shape of a district. This information is used by some external tools only, it is even not shown within the GUI.
Todo:
Recheck whether this can be somehow joined with ODDistrict
Definition at line 72 of file NBDistrict.h.
Member Typedef Documentation
typedef std::vector<SUMOReal> NBDistrict::WeightsCont private
Definition of a vector of connection weights.
Definition at line 247 of file NBDistrict.h.
Constructor & Destructor Documentation
NBDistrict::NBDistrict (const std::string & id, const Position & pos)
Constructor with id, and position.
Parameters
[in] id The id of the district
[in] pos The position of the district
Definition at line 53 of file NBDistrict.cpp.
NBDistrict::NBDistrict (const std::string & id)
Constructor without position.
The position must be computed later
Parameters
[in] id The id of the district
Definition at line 58 of file NBDistrict.cpp.
NBDistrict::~NBDistrict ()
Destructor.
Definition at line 62 of file NBDistrict.cpp.
NBDistrict::NBDistrict (const NBDistrict & s) private
invalid copy constructor
Member Function Documentation
void NBDistrict::addShape (const PositionVector & p)
Sets the shape of this district.
Parameters
[in] p The new shape
Definition at line 195 of file NBDistrict.cpp.
References myShape.
Referenced by getPosition().
bool NBDistrict::addSink (NBEdge *const sink, SUMOReal weight)
Adds a sink.
It is checked whether the edge has already been added as a sink. false is returned in this case. Otherwise, the sink is pushed into the list of sink and the weight into the list of sink weights. both lists stay sorted this way. true is returned.
Parameters
[in] sink An edge that shall be used as sink
[in] weight The weight of the sink
Returns
Whether the sink could be added (was not added before)
Todo:
Consider using only one list for sinks/weights
Definition at line 94 of file NBDistrict.cpp.
References Named::getID(), mySinks, and mySinkWeights.
Referenced by NBDistrictCont::addSink(), and NIVissimDistrictConnection::dict_BuildDistricts().
bool NBDistrict::addSource (NBEdge *const source, SUMOReal weight)
Adds a source.
It is checked whether the edge has already been added as a source. false is returned in this case. Otherwise, the source is pushed into the list of sources and the weight into the list of source weights. both lists stay sorted this way. true is returned.
Parameters
[in] source An edge that shall be used as source
[in] weight The weight of the source
Returns
Whether the source could be added (was not added before)
Todo:
Consider using only one list for sources/weights
Definition at line 81 of file NBDistrict.cpp.
References Named::getID(), mySources, and mySourceWeights.
Referenced by NBDistrictCont::addSource(), and NIVissimDistrictConnection::dict_BuildDistricts().
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), addSink(), addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciBusOrContainerStop(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNEConnectorFrame::buildIinternalLanes(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), NLDetectorBuilder::convUncontE2PosLength(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSVehicle::getBackPosition(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), GNEEdge::getDest(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), MSE2Collector::getEstimateQueueLength(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), GNEEdge::getSource(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSE2Collector::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_SL2015::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_LC2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_ArealDetector::processGet(), TraCIServerAPI_Lane::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), MSBaseVehicle::reroute(), MSLane::resetPartialOccupation(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), MSLane::saveState(), MSDevice_Battery::setAirDragCoefficient(), NBNodeCont::setAsTLControlled(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), MSDevice_Battery::setConstantPowerIntake(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), MSDevice_Battery::setFrontSurfaceArea(), MSDevice_Battery::setInternalMomentOfInertia(), GNEJunction::setLogicValid(), MSDevice_Battery::setMass(), MSDevice_Battery::setMaximumBatteryCapacity(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSDevice_Battery::setPropulsionEfficiency(), MSDevice_Battery::setRadialDragCoefficient(), MSDevice_Battery::setRecuperationEfficiency(), MSLink::setRequestInformation(), MSDevice_Battery::setRollDragCoefficient(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), operator<<(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
const Position& NBDistrict::getPosition () const inline
Returns the position of this district's center.
Returns
The position of this district's center
Todo:
Recheck when this information is set/needed
Definition at line 130 of file NBDistrict.h.
References addShape(), myPosition, removeFromSinksAndSources(), replaceIncoming(), replaceOutgoing(), and setCenter().
Referenced by NIImporter_VISUM::buildDistrictNode().
const PositionVector& NBDistrict::getShape () const inline
Returns the shape.
Returns
The district's shape
Definition at line 222 of file NBDistrict.h.
References mirrorX(), myShape, reshiftPosition(), and SUMOReal.
Referenced by NWWriter_SUMO::writeDistrict().
const std::vector<NBEdge*>& NBDistrict::getSinkEdges () const inline
Returns the sinks.
Returns
The sink edges
Definition at line 214 of file NBDistrict.h.
References mySinks.
Referenced by NWWriter_SUMO::writeDistrict().
const std::vector<SUMOReal>& NBDistrict::getSinkWeights () const inline
Returns the weights of the sinks.
Returns
The sink weights
Definition at line 206 of file NBDistrict.h.
References mySinkWeights.
Referenced by NWWriter_SUMO::writeDistrict().
const std::vector<NBEdge*>& NBDistrict::getSourceEdges () const inline
Returns the sources.
Returns
The source edges
Definition at line 198 of file NBDistrict.h.
References mySources.
Referenced by NWWriter_SUMO::writeDistrict().
const std::vector<SUMOReal>& NBDistrict::getSourceWeights () const inline
Returns the weights of the sources.
Returns
The source weights
Definition at line 190 of file NBDistrict.h.
References mySourceWeights.
Referenced by NWWriter_SUMO::writeDistrict().
void NBDistrict::mirrorX ()
mirror coordinates along the x-axis
Definition at line 74 of file NBDistrict.cpp.
References PositionVector::mirrorX(), Position::mul(), myPosition, and myShape.
Referenced by getShape().
NBDistrict& NBDistrict::operator= (const NBDistrict & s) private
invalid assignment operator
void NBDistrict::removeFromSinksAndSources (NBEdge *const e)
Removes the given edge from the lists of sources and sinks.
The according weights are removed, too.
Parameters
[in] e The edge to remove from sinks/sources
Definition at line 177 of file NBDistrict.cpp.
References mySinks, mySinkWeights, mySources, and mySourceWeights.
Referenced by getPosition().
void NBDistrict::replaceIncoming (const EdgeVector & which, NBEdge *const by)
Replaces incoming edges from the vector (sinks) by the given edge.
When an edge is split/joined/removed/etc., it may get necessary to replace prior edges by new ones. This method replaces all occurences of the edges from "which" within incoming edges (sinks) by the given edge.
The new sink edge's weight is the sum of the weights of the replaced edges.
Parameters
[in] which List of edges to replace
[in] by The replacement
Definition at line 113 of file NBDistrict.cpp.
References mySinks, mySinkWeights, and SUMOReal.
Referenced by getPosition(), and NBNode::replaceIncoming().
void NBDistrict::replaceOutgoing (const EdgeVector & which, NBEdge *const by)
Replaces outgoing edges from the vector (source) by the given edge.
When an edge is split/joined/removed/etc., it may get necessary to replace prior edges by new ones. This method replaces all occurences of the edges from "which" within outgoing edges (sources) by the given edge.
The new source edge's weight is the sum of the weights of the replaced edges.
Parameters
[in] which List of edges to replace
[in] by The replacement
Definition at line 145 of file NBDistrict.cpp.
References mySources, mySourceWeights, and SUMOReal.
Referenced by getPosition(), and NBNode::replaceOutgoing().
void NBDistrict::reshiftPosition (SUMOReal xoff, SUMOReal yoff)
Applies an offset to the district.
Parameters
[in] xoff The x-offset to apply
[in] yoff The y-offset to apply
Definition at line 67 of file NBDistrict.cpp.
References Position::add(), PositionVector::add(), myPosition, and myShape.
Referenced by getShape().
void NBDistrict::setCenter (const Position & pos)
Sets the center coordinates.
Parameters
[in] pos The new center to assign
Todo:
Recheck when this information is set/needed
Definition at line 107 of file NBDistrict.cpp.
References myPosition.
Referenced by getPosition().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
Field Documentation
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
Position NBDistrict::myPosition private
The position of the district.
Definition at line 262 of file NBDistrict.h.
Referenced by getPosition(), mirrorX(), reshiftPosition(), and setCenter().
PositionVector NBDistrict::myShape private
The shape of the dsitrict.
Definition at line 265 of file NBDistrict.h.
Referenced by addShape(), getShape(), mirrorX(), and reshiftPosition().
EdgeVector NBDistrict::mySinks private
The sinks (connection from network to district)
Definition at line 256 of file NBDistrict.h.
Referenced by addSink(), getSinkEdges(), removeFromSinksAndSources(), and replaceIncoming().
WeightsCont NBDistrict::mySinkWeights private
The weights of the sinks.
Definition at line 259 of file NBDistrict.h.
Referenced by addSink(), getSinkWeights(), removeFromSinksAndSources(), and replaceIncoming().
EdgeVector NBDistrict::mySources private
The sources (connection from district to network)
Definition at line 250 of file NBDistrict.h.
Referenced by addSource(), getSourceEdges(), removeFromSinksAndSources(), and replaceOutgoing().
WeightsCont NBDistrict::mySourceWeights private
The weights of the sources.
Definition at line 253 of file NBDistrict.h.
Referenced by addSource(), getSourceWeights(), removeFromSinksAndSources(), and replaceOutgoing().
The documentation for this class was generated from the following files:
NBDistrict.h
NBDistrict.cpp