SUMO - Simulation of Urban MObility: RONetHandler Class Reference
RONetHandler Class Reference
The handler that parses a SUMO-network for its usage in a router.
#include <RONetHandler.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
RONetHandler (RONet &net, ROAbstractEdgeBuilder &eb)
Constructor.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
virtual ~RONetHandler ()
Destructor.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Protected Types
typedef std::map< std::string, std::pair< std::string, std::string > > JunctionGraph
temporary data for building the junction graph after network parsing is finished
Protected Member Functions
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
inherited from GenericSAXHandler
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
virtual void myEndElement (int element)
Called when a closing tag occurs.
called from myStartElement
void parseEdge (const SUMOSAXAttributes &attrs)
Parses and builds an edge.
virtual void parseLane (const SUMOSAXAttributes &attrs)
Parses and builds a lane.
void parseJunction (const SUMOSAXAttributes &attrs)
Parses a junction's position.
void parseConnection (const SUMOSAXAttributes &attrs)
void parseStoppingPlace (const SUMOSAXAttributes &attrs, const SumoXMLTag element)
void parseAccess (const SUMOSAXAttributes &attrs)
void parseDistrict (const SUMOSAXAttributes &attrs)
void parseDistrictEdge (const SUMOSAXAttributes &attrs, bool isSource)
Protected Attributes
ROEdge * myCurrentEdge
The currently built edge.
std::string myCurrentName
The name of the edge/node that is currently processed.
SUMOVehicleParameter::Stop * myCurrentStoppingPlace
The currently built stopping place.
std::string myCurrentTypeID
The id of the currently processed edge type.
ROAbstractEdgeBuilder & myEdgeBuilder
The object used to build of edges of the desired type.
JunctionGraph myJunctionGraph
RONet & myNet
The net to store the information into.
bool myProcess
An indicator whether the next edge shall be read (internal edges are not read by now)
Private Member Functions
RONetHandler & operator= (const RONetHandler &src)
Invalidated assignment operator.
RONetHandler (const RONetHandler &src)
Invalidated copy constructor.
Detailed Description
The handler that parses a SUMO-network for its usage in a router.
SAX2-Handler for SUMO-network loading. As this class is used for both the dua- and the jtrrouter, a reference to the edge builder is given.
Definition at line 60 of file RONetHandler.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<std::string, std::string> > RONetHandler::JunctionGraph protected
temporary data for building the junction graph after network parsing is finished
Definition at line 209 of file RONetHandler.h.
Constructor & Destructor Documentation
RONetHandler::RONetHandler (RONet & net, ROAbstractEdgeBuilder & eb)
Constructor.
Parameters
[in] net The network instance to fill
[in] eb The abstract edge builder to use
Definition at line 59 of file RONetHandler.cpp.
RONetHandler::~RONetHandler () virtual
Destructor.
Definition at line 67 of file RONetHandler.cpp.
RONetHandler::RONetHandler (const RONetHandler & src) private
Invalidated copy constructor.
Member Function Documentation
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 192 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 175 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 211 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), MSRouteHandler::myStartElement(), and MSRouteHandler::parseWalkPos().
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 217 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), MSStateHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 227 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void RONetHandler::myEndElement (int element) protected virtual
Called when a closing tag occurs.
Parameters
[in] element ID of the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myEndElement
Reimplemented from GenericSAXHandler.
Definition at line 129 of file RONetHandler.cpp.
References RONode::addIncoming(), RONode::addOutgoing(), RONet::getEdge(), RONet::getNode(), myJunctionGraph, myNet, and SUMO_TAG_NET.
void RONetHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 71 of file RONetHandler.cpp.
References RONet::addRestriction(), SUMOSAXAttributes::get(), getVehicleClassID(), myCurrentTypeID, myNet, myProcess, parseAccess(), parseConnection(), parseDistrict(), parseDistrictEdge(), parseEdge(), parseJunction(), parseLane(), parseStoppingPlace(), SUMO_ATTR_ID, SUMO_ATTR_SPEED, SUMO_ATTR_VCLASS, SUMO_TAG_ACCESS, SUMO_TAG_BUS_STOP, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_RESTRICTION, SUMO_TAG_TAZ, SUMO_TAG_TAZSINK, SUMO_TAG_TAZSOURCE, SUMO_TAG_TRAIN_STOP, SUMO_TAG_TYPE, and SUMOReal.
RONetHandler& RONetHandler::operator= (const RONetHandler & src) private
Invalidated assignment operator.
void RONetHandler::parseAccess (const SUMOSAXAttributes & attrs) protected
Parses an access point to a train stop Called on the occurence of an "access" element
Parameters
[in] attrs The attributes to parse
Definition at line 349 of file RONetHandler.cpp.
References SUMOVehicleParameter::Stop::accessPos, SUMOSAXAttributes::get(), RONet::getEdgeForLaneID(), SUMOSAXAttributes::getOpt(), myCurrentStoppingPlace, myNet, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, and SUMOReal.
Referenced by myStartElement().
void RONetHandler::parseConnection (const SUMOSAXAttributes & attrs) protected
Parses a connection Called on the occurence of a "connection" element
Parameters
[in] attrs The attributes (of the "connection"-element) to parse
Definition at line 289 of file RONetHandler.cpp.
References ROEdge::ET_INTERNAL, SUMOSAXAttributes::get(), RONet::getEdge(), ROEdge::getLanes(), myNet, SUMO_ATTR_DIR, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, and toString().
Referenced by myStartElement().
void RONetHandler::parseDistrict (const SUMOSAXAttributes & attrs) protected
Parses a district and creates a pseudo edge for it
Called on the occurence of a "district" element, this method retrieves the id of the district and creates a district type edge with this id.
Parameters
[in] attrs The attributes (of the "district"-element) to parse
Exceptions
ProcessError If an edge given in district is not known
Definition at line 365 of file RONetHandler.cpp.
References RONet::addDistrict(), RONet::addDistrictEdge(), ROAbstractEdgeBuilder::buildEdge(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getStringVector(), SUMOSAXAttributes::hasAttribute(), myCurrentEdge, myCurrentName, myEdgeBuilder, myNet, SUMO_ATTR_EDGES, and SUMO_ATTR_ID.
Referenced by myStartElement().
void RONetHandler::parseDistrictEdge (const SUMOSAXAttributes & attrs, bool isSource) protected
Parses a district edge and connects it to the district
Called on the occurence of a "dsource" or "dsink" element, this method retrieves the id of the approachable edge. If this edge is known and valid, the approaching edge is informed about it (by calling "ROEdge::addFollower").
Parameters
[in] attrs The attributes to parse
[in] isSource whether a "dsource or a "dsink" was given
Todo:
No exception?
Definition at line 384 of file RONetHandler.cpp.
References RONet::addDistrictEdge(), SUMOSAXAttributes::get(), myCurrentName, myNet, and SUMO_ATTR_ID.
Referenced by myStartElement().
void RONetHandler::parseEdge (const SUMOSAXAttributes & attrs) protected
Parses and builds an edge.
Parses attributes from an "edge"-element (id, from/to-nodes, function, etc.). If the given nodes are not yet known, they are added to the network. Uses the internal edge builder to build the edge and adds the edge to the network.
Parameters
[in] attrs The attributes (of the "edge"-element) to parse
Todo:
The edge is "built" first, then the nodes are added; should be done while constructing, probably a legacy issue
No exception?
Definition at line 150 of file RONetHandler.cpp.
References RONet::addEdge(), RONet::addNode(), ROAbstractEdgeBuilder::buildEdge(), EDGEFUNC_CONNECTOR, EDGEFUNC_CROSSING, EDGEFUNC_INTERNAL, EDGEFUNC_NORMAL, EDGEFUNC_SINK, EDGEFUNC_SOURCE, EDGEFUNC_WALKINGAREA, ROEdge::ET_CROSSING, ROEdge::ET_INTERNAL, ROEdge::ET_NORMAL, ROEdge::ET_SINK, ROEdge::ET_SOURCE, ROEdge::ET_WALKINGAREA, SUMOSAXAttributes::get(), SUMOSAXAttributes::getEdgeFunc(), RONet::getNode(), SUMOSAXAttributes::getOpt(), RONet::getRestrictions(), myCurrentEdge, myCurrentName, myEdgeBuilder, myJunctionGraph, myNet, myProcess, ROEdge::setFunc(), ROEdge::setRestrictions(), SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_PRIORITY, SUMO_ATTR_TO, SUMO_ATTR_TYPE, toString(), and WRITE_ERROR.
Referenced by myStartElement().
void RONetHandler::parseJunction (const SUMOSAXAttributes & attrs) protected
Parses a junction's position.
Parses the position of the junction. Sets it to the junction.
Parameters
[in] attrs The attributes (of the "lane"-element) to parse
Todo:
In fact, the junction should be built given its position.
No exception?
Definition at line 265 of file RONetHandler.cpp.
References RONet::addNode(), SUMOSAXAttributes::get(), RONet::getNode(), myNet, RONode::setPosition(), SUMO_ATTR_ID, SUMO_ATTR_X, SUMO_ATTR_Y, and SUMOReal.
Referenced by myStartElement().
void RONetHandler::parseLane (const SUMOSAXAttributes & attrs) protected virtual
Parses and builds a lane.
Parses attributes from an "lane"-element (speed, length, vehicle classes, etc.). Builds a ROLane using these attributes (if they are valid) and adds it to the edge.
Parameters
[in] attrs The attributes (of the "lane"-element) to parse
Todo:
No exception?
Definition at line 232 of file RONetHandler.cpp.
References ROEdge::addLane(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), myCurrentEdge, myNet, parseVehicleClasses(), RONet::setPermissionsFound(), SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_ID, SUMO_ATTR_LENGTH, SUMO_ATTR_SPEED, SUMOReal, and SVCAll.
Referenced by myStartElement().
void RONetHandler::parseStoppingPlace (const SUMOSAXAttributes & attrs, const SumoXMLTag element) protected
Parses a stopping place Called on the occurence of a "busStop", "trainStop" or "containerStop" element
Parameters
[in] attrs The attributes to parse
[in] element which kind of stop is to be parsed
Definition at line 319 of file RONetHandler.cpp.
References RONet::addBusStop(), RONet::addContainerStop(), SUMORouteHandler::checkStopPos(), SUMOVehicleParameter::Stop::endPos, SUMOSAXAttributes::get(), RONet::getEdgeForLaneID(), ROEdge::getLength(), SUMOSAXAttributes::getOpt(), SUMOVehicleParameter::Stop::lane, myCurrentStoppingPlace, myNet, POSITION_EPS, SUMOVehicleParameter::Stop::startPos, SUMO_ATTR_ENDPOS, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_STARTPOS, SUMO_TAG_CONTAINER_STOP, SUMOReal, and toString().
Referenced by myStartElement().
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 167 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 205 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
ROEdge* RONetHandler::myCurrentEdge protected
The currently built edge.
Definition at line 197 of file RONetHandler.h.
Referenced by parseDistrict(), parseEdge(), and parseLane().
std::string RONetHandler::myCurrentName protected
The name of the edge/node that is currently processed.
Definition at line 191 of file RONetHandler.h.
Referenced by parseDistrict(), parseDistrictEdge(), and parseEdge().
SUMOVehicleParameter::Stop* RONetHandler::myCurrentStoppingPlace protected
The currently built stopping place.
Definition at line 200 of file RONetHandler.h.
Referenced by parseAccess(), and parseStoppingPlace().
std::string RONetHandler::myCurrentTypeID protected
The id of the currently processed edge type.
Definition at line 194 of file RONetHandler.h.
Referenced by myStartElement().
ROAbstractEdgeBuilder& RONetHandler::myEdgeBuilder protected
The object used to build of edges of the desired type.
Definition at line 206 of file RONetHandler.h.
Referenced by parseDistrict(), and parseEdge().
JunctionGraph RONetHandler::myJunctionGraph protected
Definition at line 210 of file RONetHandler.h.
Referenced by myEndElement(), and parseEdge().
RONet& RONetHandler::myNet protected
The net to store the information into.
Definition at line 188 of file RONetHandler.h.
Referenced by myEndElement(), myStartElement(), parseAccess(), parseConnection(), parseDistrict(), parseDistrictEdge(), parseEdge(), parseJunction(), parseLane(), and parseStoppingPlace().
bool RONetHandler::myProcess protected
An indicator whether the next edge shall be read (internal edges are not read by now)
Definition at line 203 of file RONetHandler.h.
Referenced by myStartElement(), and parseEdge().
The documentation for this class was generated from the following files:
RONetHandler.h
RONetHandler.cpp