SUMO - Simulation of Urban MObility: Bresenham Class Reference
Bresenham Class Reference
#include <Bresenham.h>
Data Structures
class BresenhamCallBack
Static Public Member Functions
static void compute (BresenhamCallBack *callBack, const int val1, const int val2)
Detailed Description
The class' only static method "execute" obtains a callback object and performs the computation of the n:m - relationship
Definition at line 42 of file Bresenham.h.
Member Function Documentation
void Bresenham::compute (BresenhamCallBack * callBack, const int val1, const int val2) static
compute the bresenham - interpolation between both values the higher number is increased by one for each step while the smaller is increased by smaller/higher. In each step, the callback is executed.
Definition at line 45 of file Bresenham.cpp.
References Bresenham::BresenhamCallBack::execute(), MAX2(), and MIN2().
Referenced by NBNode::computeLanes2Lanes(), NBEdge::divideSelectedLanesOnEdges(), and Bresenham::BresenhamCallBack::~BresenhamCallBack().
The documentation for this class was generated from the following files:
Bresenham.h
Bresenham.cpp