SUMO - Simulation of Urban MObility: LineHandler Class Reference
LineHandler Class Reference abstract
Interface definition for a class which retrieves lines from a LineHandler.
#include <LineHandler.h>
Public Member Functions
LineHandler ()
constructor
virtual bool report (const std::string &result)=0
Method that obatins a line read by the LineReader.
virtual ~LineHandler ()
(virtual) destructor
Detailed Description
Interface definition for a class which retrieves lines from a LineHandler.
The LineHandler is an interface for a class which retrieves information from a file linewise. The lines are suppoted to this class using the "report"-method. The LineHandler is used together with the LineReader which reads the lines from a file.
See also
LineReader
Definition at line 52 of file LineHandler.h.
Constructor & Destructor Documentation
LineHandler::LineHandler () inline
constructor
Definition at line 55 of file LineHandler.h.
virtual LineHandler::~LineHandler () inline virtual
(virtual) destructor
Definition at line 59 of file LineHandler.h.
References report().
Member Function Documentation
virtual bool LineHandler::report (const std::string & result) pure virtual
Method that obatins a line read by the LineReader.
Real interface method, used by a LineReader, which retrieves lines from a file
Parameters
[in] result The read line
Returns
Whether the caller shall continue with reading
Implemented in NIImporter_DlrNavteq::NamesHandler, NIImporter_DlrNavteq::TrafficlightsHandler, NIImporter_DlrNavteq::EdgesHandler, and NIImporter_DlrNavteq::NodesHandler.
Referenced by LineReader::readLine(), and ~LineHandler().
The documentation for this class was generated from the following file:
LineHandler.h