SUMO - Simulation of Urban MObility: TraCIServerAPI_Junction Class Reference
TraCIServerAPI_Junction Class Reference
APIs for getting/setting junction values via TraCI.
#include <TraCIServerAPI_Junction.h>
Static Public Member Functions
static bool getPosition (const std::string &id, Position &p)
Returns the named junction's position.
static NamedRTree * getTree ()
Returns a tree filled with junction instances.
static bool processGet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a get value command (Command 0xa9: Get Junction Variable)
Private Member Functions
TraCIServerAPI_Junction & operator= (const TraCIServerAPI_Junction &s)
invalidated assignment operator
TraCIServerAPI_Junction (const TraCIServerAPI_Junction &s)
invalidated copy constructor
Detailed Description
APIs for getting/setting junction values via TraCI.
Definition at line 48 of file TraCIServerAPI_Junction.h.
Constructor & Destructor Documentation
TraCIServerAPI_Junction::TraCIServerAPI_Junction (const TraCIServerAPI_Junction & s) private
invalidated copy constructor
Member Function Documentation
bool TraCIServerAPI_Junction::getPosition (const std::string & id, Position & p) static
Returns the named junction's position.
Parameters
[in] id The id of the searched junction
[out] p The position, if the junction is known
Returns
Whether the junction is known (and on road)
Definition at line 110 of file TraCIServerAPI_Junction.cpp.
References NamedObjectCont< T >::get(), MSNet::getInstance(), MSNet::getJunctionControl(), and MSJunction::getPosition().
Referenced by TraCIServer::findObjectShape().
NamedRTree * TraCIServerAPI_Junction::getTree () static
Returns a tree filled with junction instances.
Returns
The rtree of junctions
Definition at line 121 of file TraCIServerAPI_Junction.cpp.
References MSNet::getInstance(), MSNet::getJunctionControl(), NamedObjectCont< T >::getMyMap(), NamedRTree::Insert(), Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by TraCIServer::collectObjectsInRange().
TraCIServerAPI_Junction& TraCIServerAPI_Junction::operator= (const TraCIServerAPI_Junction & s) private
invalidated assignment operator
bool TraCIServerAPI_Junction::processGet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a get value command (Command 0xa9: Get Junction Variable)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 53 of file TraCIServerAPI_Junction.cpp.
References CMD_GET_JUNCTION_VARIABLE, NamedObjectCont< T >::get(), MSNet::getInstance(), MSNet::getJunctionControl(), MSJunction::getPosition(), MSJunction::getShape(), ID_COUNT, ID_LIST, NamedObjectCont< T >::insertIDs(), MIN2(), POSITION_2D, tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), RESPONSE_GET_JUNCTION_VARIABLE, RTYPE_OK, toHex(), TYPE_INTEGER, TYPE_POLYGON, TYPE_STRINGLIST, VAR_POSITION, VAR_SHAPE, tcpip::Storage::writeDouble(), TraCIServer::writeErrorStatusCmd(), tcpip::Storage::writeInt(), TraCIServer::writeResponseWithLength(), TraCIServer::writeStatusCmd(), tcpip::Storage::writeString(), tcpip::Storage::writeStringList(), tcpip::Storage::writeUnsignedByte(), Position::x(), and Position::y().
Referenced by TraCIServer::TraCIServer().
The documentation for this class was generated from the following files:
TraCIServerAPI_Junction.h
TraCIServerAPI_Junction.cpp