SUMO - Simulation of Urban MObility: ROVehicle Class Reference
ROVehicle Class Reference
A vehicle as used by router.
#include <ROVehicle.h>
Public Member Functions
void computeRoute (const RORouterProvider &provider, const bool removeLoops, MsgHandler *errorHandler)
SUMOReal getChosenSpeedFactor () const
Returns an upper bound for the speed factor of this vehicle.
SUMOTime getDepart () const
Returns the time the vehicle starts at, -1 for triggered vehicles.
const ROEdge * getDepartEdge () const
Returns the first edge the vehicle takes.
SUMOTime getDepartureTime () const
Returns the time the vehicle starts at, 0 for triggered vehicles.
const std::string & getID () const
Returns the id of the vehicle.
SUMOReal getMaxSpeed () const
Returns the vehicle's maximum speed.
const SUMOVehicleParameter & getParameter () const
Returns the definition of the vehicle parameter.
RORouteDef * getRouteDefinition () const
Returns the definition of the route the vehicle takes.
bool getRoutingSuccess () const
const ConstROEdgeVector & getStopEdges () const
const SUMOVTypeParameter * getType () const
Returns the type of the vehicle.
SUMOVehicleClass getVClass () const
ROVehicle (const SUMOVehicleParameter &pars, RORouteDef *route, const SUMOVTypeParameter *type, const RONet *net, MsgHandler *errorHandler=0)
Constructor.
void saveAsXML (OutputDevice &os, OutputDevice *const typeos, bool asAlternatives, OptionsCont &options) const
Saves the complete vehicle description.
void write (OutputDevice &os, OutputDevice *const altos, OutputDevice *const typeos, OptionsCont &options) const
Saves the routable including the vehicle type (if it was not saved before).
virtual ~ROVehicle ()
Destructor.
Protected Attributes
SUMOVehicleParameter myParameter
The vehicle's parameter.
bool myRoutingSuccess
Whether the last routing was successful.
const SUMOVTypeParameter *const myType
The type of the vehicle.
Private Member Functions
void addStop (const SUMOVehicleParameter::Stop &stopPar, const RONet *net, MsgHandler *errorHandler)
Adds a stop to this vehicle.
ROVehicle & operator= (const ROVehicle &src)
Invalidated assignment operator.
ROVehicle (const ROVehicle &src)
Invalidated copy constructor.
Private Attributes
RORouteDef *const myRoute
The route the vehicle takes.
ConstROEdgeVector myStopEdges
The edges where the vehicle stops.
Detailed Description
A vehicle as used by router.
Definition at line 60 of file ROVehicle.h.
Constructor & Destructor Documentation
ROVehicle::ROVehicle (const SUMOVehicleParameter & pars, RORouteDef * route, const SUMOVTypeParameter * type, const RONet * net, MsgHandler * errorHandler = 0)
Constructor.
Parameters
[in] pars Parameter of this vehicle
[in] route The definition of the route the vehicle shall use
[in] type The type of the vehicle
Definition at line 56 of file ROVehicle.cpp.
References addStop(), RONet::getEdge(), RORouteDef::getFirstRoute(), RORoute::getStops(), RORoutable::myParameter, myStopEdges, SUMOVehicleParameter::stops, and SUMOVehicleParameter::via.
ROVehicle::~ROVehicle () virtual
Destructor.
Definition at line 125 of file ROVehicle.cpp.
ROVehicle::ROVehicle (const ROVehicle & src) private
Invalidated copy constructor.
Member Function Documentation
void ROVehicle::addStop (const SUMOVehicleParameter::Stop & stopPar, const RONet * net, MsgHandler * errorHandler) private
Adds a stop to this vehicle.
Parameters
[in] stopPar the stop paramters
[in] net pointer to the network, used for edge retrieval
Definition at line 82 of file ROVehicle.cpp.
References SUMOVehicleParameter::Stop::endPos, RONet::getEdgeForLaneID(), RORoute::getEdgeVector(), RORouteDef::getFirstRoute(), Named::getID(), RORoutable::getID(), SUMOVehicleParameter::Stop::index, MsgHandler::inform(), SUMOVehicleParameter::Stop::lane, RORoutable::myParameter, myRoute, myStopEdges, ROEdge::prohibits(), STOP_INDEX_END, STOP_INDEX_FIT, and SUMOVehicleParameter::stops.
Referenced by getChosenSpeedFactor(), and ROVehicle().
void ROVehicle::computeRoute (const RORouterProvider & provider, const bool removeLoops, MsgHandler * errorHandler) virtual
Implements RORoutable.
Definition at line 135 of file ROVehicle.cpp.
References RORouteDef::addAlternative(), RORouteDef::buildCurrentRoute(), getDepartureTime(), RORoutable::getID(), getRouteDefinition(), RouterProvider< E, L, N, V >::getVehicleRouter(), MsgHandler::inform(), RORoutable::myRoutingSuccess, RORoute::recheckForLoops(), and RORoute::size().
Referenced by getParameter().
SUMOReal ROVehicle::getChosenSpeedFactor () const inline
Returns an upper bound for the speed factor of this vehicle.
Returns
the maximum speed factor
Definition at line 124 of file ROVehicle.h.
References addStop(), RORoutable::getType(), saveAsXML(), SUMOVTypeParameter::speedFactor, and SUMOReal.
Referenced by ROEdge::getMinimumTravelTime().
SUMOTime RORoutable::getDepart () const inline inherited
Returns the time the vehicle starts at, -1 for triggered vehicles.
Returns
The vehicle's depart time
Definition at line 101 of file RORoutable.h.
References SUMOVehicleParameter::depart, and RORoutable::myParameter.
Referenced by RONet::addPerson(), RONet::addVehicle(), and ROVehicleByDepartureComperator::operator()().
const ROEdge * ROVehicle::getDepartEdge () const virtual
Returns the first edge the vehicle takes.
Returns
The vehicle's departure edge
Implements RORoutable.
Definition at line 129 of file ROVehicle.cpp.
References RORoute::getFirst(), RORouteDef::getFirstRoute(), and myRoute.
Referenced by getParameter().
SUMOTime ROVehicle::getDepartureTime () const inline
Returns the time the vehicle starts at, 0 for triggered vehicles.
Returns
The vehicle's depart time
Definition at line 111 of file ROVehicle.h.
References SUMOVehicleParameter::depart, MAX2(), and RORoutable::myParameter.
Referenced by RORouteDef::addAlternative(), computeRoute(), and RORoute::writeXMLDefinition().
const std::string& RORoutable::getID () const inline inherited
Returns the id of the vehicle.
Returns
The id of the vehicle
Definition at line 92 of file RORoutable.h.
References SUMOVehicleParameter::id, and RORoutable::myParameter.
Referenced by RORouteDef::addAlternative(), RONet::addPerson(), addStop(), ROPerson::addTrip(), ROPerson::computeIntermodal(), computeRoute(), RONet::createBulkRouteRequests(), ROVehicleByDepartureComperator::operator()(), RORouteDef::preComputeCurrentRoute(), and RORouteDef::repairCurrentRoute().
SUMOReal RORoutable::getMaxSpeed () const inline inherited
Returns the vehicle's maximum speed.
Definition at line 112 of file RORoutable.h.
References RORoutable::computeRoute(), RORoutable::getDepartEdge(), SUMOVTypeParameter::maxSpeed, and RORoutable::myType.
Referenced by RONet::createBulkRouteRequests().
const SUMOVehicleParameter& ROVehicle::getParameter () const inline
Returns the definition of the vehicle parameter.
Returns
The vehicle's parameter
Definition at line 92 of file ROVehicle.h.
References computeRoute(), getDepartEdge(), and RORoutable::myParameter.
Referenced by RONet::adaptIntermodalRouter().
RORouteDef* ROVehicle::getRouteDefinition () const inline
Returns the definition of the route the vehicle takes.
Returns
The vehicle's route definition
Todo:
Why not return a reference?
Definition at line 83 of file ROVehicle.h.
References myRoute.
Referenced by ROPerson::computeIntermodal(), computeRoute(), RONet::saveAndRemoveRoutesUntil(), and RONet::~RONet().
bool RORoutable::getRoutingSuccess () const inline inherited
Definition at line 144 of file RORoutable.h.
References RORoutable::myRoutingSuccess, and RORoutable::saveAsXML().
Referenced by RONet::saveAndRemoveRoutesUntil().
const ConstROEdgeVector& ROVehicle::getStopEdges () const inline
Definition at line 116 of file ROVehicle.h.
References myStopEdges.
Referenced by RORouteDef::repairCurrentRoute().
const SUMOVTypeParameter* RORoutable::getType () const inline inherited
Returns the type of the vehicle.
Returns
The vehicle's type
Todo:
Why not return a reference?
Definition at line 83 of file RORoutable.h.
References RORoutable::myType.
Referenced by getChosenSpeedFactor(), ROEdge::getEffort(), ROEdge::getEmissionEffort(), ROEdge::getMinimumTravelTime(), ROEdge::getNoiseEffort(), ROEdge::getTravelTime(), and RORoutable::getVClass().
SUMOVehicleClass RORoutable::getVClass () const inline inherited
Definition at line 106 of file RORoutable.h.
References RORoutable::getType(), SVC_IGNORING, and SUMOVTypeParameter::vehicleClass.
Referenced by RONet::createBulkRouteRequests(), ROEdge::isConnectedTo(), and ROEdge::prohibits().
ROVehicle& ROVehicle::operator= (const ROVehicle & src) private
Invalidated assignment operator.
void ROVehicle::saveAsXML (OutputDevice & os, OutputDevice *const typeos, bool asAlternatives, OptionsCont & options) const virtual
Saves the complete vehicle description.
Saves the vehicle itself including the route and stops.
Parameters
[in] os The routes or alternatives output device to store the vehicle's description into
[in] typeos The types - output device to store types into
[in] asAlternatives Whether the route shall be saved as route alternatives
[in] options to find out about defaults and whether exit times for the edges shall be written
Exceptions
IOError If something fails (not yet implemented)
Implements RORoutable.
Definition at line 171 of file ROVehicle.cpp.
References OutputDevice::closeTag(), OptionsCont::getBool(), Parameterised::getMap(), RORoutable::myParameter, myRoute, RORoutable::myType, OutputDevice::openTag(), SUMOVTypeParameter::saved, SUMOVehicleParameter::stops, SUMO_ATTR_KEY, SUMO_ATTR_VALUE, SUMO_TAG_PARAM, SUMOVTypeParameter::write(), SUMOVehicleParameter::write(), OutputDevice::writeAttr(), and RORouteDef::writeXMLDefinition().
Referenced by getChosenSpeedFactor().
void RORoutable::write (OutputDevice & os, OutputDevice *const altos, OutputDevice *const typeos, OptionsCont & options) const inline inherited
Saves the routable including the vehicle type (if it was not saved before).
Parameters
[in] os The routes - output device to store the vehicle's description into
[in] altos The route alternatives - output device to store the vehicle's description into
[in] typeos The types - output device to store the vehicle types into
Exceptions
IOError If something fails (not yet implemented)
Definition at line 131 of file RORoutable.h.
References RORoutable::saveAsXML().
Referenced by RONet::saveAndRemoveRoutesUntil().
Field Documentation
SUMOVehicleParameter RORoutable::myParameter protected inherited
The vehicle's parameter.
Definition at line 165 of file RORoutable.h.
Referenced by addStop(), RORoutable::getDepart(), getDepartureTime(), RORoutable::getID(), getParameter(), ROVehicle(), saveAsXML(), and ROPerson::saveAsXML().
RORouteDef* const ROVehicle::myRoute private
The route the vehicle takes.
Definition at line 153 of file ROVehicle.h.
Referenced by addStop(), getDepartEdge(), getRouteDefinition(), and saveAsXML().
bool RORoutable::myRoutingSuccess protected inherited
Whether the last routing was successful.
Definition at line 171 of file RORoutable.h.
Referenced by ROPerson::computeIntermodal(), computeRoute(), ROPerson::computeRoute(), and RORoutable::getRoutingSuccess().
ConstROEdgeVector ROVehicle::myStopEdges private
The edges where the vehicle stops.
Definition at line 156 of file ROVehicle.h.
Referenced by addStop(), getStopEdges(), and ROVehicle().
const SUMOVTypeParameter* const RORoutable::myType protected inherited
The type of the vehicle.
Definition at line 168 of file RORoutable.h.
Referenced by ROPerson::computeIntermodal(), RORoutable::getMaxSpeed(), RORoutable::getType(), saveAsXML(), and ROPerson::saveAsXML().
The documentation for this class was generated from the following files:
ROVehicle.h
ROVehicle.cpp