SUMO - Simulation of Urban MObility: MSSOTLSensors Class Reference
MSSOTLSensors Class Reference abstract
#include <MSSOTLSensors.h>
Public Member Functions
virtual void buildOutSensors (MSTrafficLightLogic::LaneVectorVector controlledLanes, NLDetectorBuilder &nb)=0
This function member has to be extended to properly build sensors for the output lanes Sensors has to be constrained on lane dimension Built sensors has to be collected and associated properly to theirs MSLane for retrieval using MSSOTLSensors::countVehicles(std::string) See extension classes for further specifications on sensor building.
virtual void buildSensors (MSTrafficLightLogic::LaneVectorVector controlledLanes, NLDetectorBuilder &nb)=0
This function member has to be extended to properly build sensors for the input lanes Sensors has to be constrained on lane dimension Built sensors has to be collected and associated properly to theirs MSLane for retrieval using MSSOTLSensors::countVehicles(std::string) See extension classes for further specifications on sensor building.
virtual int countVehicles (MSLane *lane)=0
virtual int countVehicles (std::string laneId)=0
virtual SUMOReal getMaxSpeed (std::string laneId)=0
virtual SUMOReal meanVehiclesSpeed (MSLane *lane)=0
virtual SUMOReal meanVehiclesSpeed (std::string laneId)=0
MSSOTLSensors (std::string tlLogicID, const MSTrafficLightLogic::Phases *phases)
virtual void stepChanged (int newStep)
virtual ~MSSOTLSensors ()
Protected Member Functions
virtual void buildSensorForLane (MSLane *lane, NLDetectorBuilder &nb)=0
This function member has to be extended to properly build a sensor for a specific input lane Sensors has to be constrained on lane dimension Built sensors has to be collected and associated properly to the respective MSLane for retrieval using MSSOTLSensors::countVehicles(std::string) See extension classes for further specifications on sensor building.
virtual void buildSensorForOutLane (MSLane *lane, NLDetectorBuilder &nb)=0
This function member has to be extended to properly build a sensor for a specific output lane Sensors has to be constrained on lane dimension Built sensors has to be collected and associated properly to the respective MSLane for retrieval using MSSOTLSensors::countVehicles(std::string) See extension classes for further specifications on sensor building.
Protected Attributes
int currentStep
const MSTrafficLightLogic::Phases * myPhases
std::string tlLogicID
Detailed Description
Definition at line 40 of file MSSOTLSensors.h.
Constructor & Destructor Documentation
MSSOTLSensors::MSSOTLSensors (std::string tlLogicID, const MSTrafficLightLogic::Phases * phases)
Definition at line 22 of file MSSOTLSensors.cpp.
References myPhases, and tlLogicID.
MSSOTLSensors::~MSSOTLSensors () virtual
Definition at line 28 of file MSSOTLSensors.cpp.
Member Function Documentation
virtual void MSSOTLSensors::buildOutSensors (MSTrafficLightLogic::LaneVectorVector controlledLanes, NLDetectorBuilder & nb) pure virtual
This function member has to be extended to properly build sensors for the output lanes Sensors has to be constrained on lane dimension Built sensors has to be collected and associated properly to theirs MSLane for retrieval using MSSOTLSensors::countVehicles(std::string) See extension classes for further specifications on sensor building.
Implemented in MSSOTLE2Sensors.
virtual void MSSOTLSensors::buildSensorForLane (MSLane * lane, NLDetectorBuilder & nb) protected pure virtual
This function member has to be extended to properly build a sensor for a specific input lane Sensors has to be constrained on lane dimension Built sensors has to be collected and associated properly to the respective MSLane for retrieval using MSSOTLSensors::countVehicles(std::string) See extension classes for further specifications on sensor building.
Implemented in MSSOTLE2Sensors.
virtual void MSSOTLSensors::buildSensorForOutLane (MSLane * lane, NLDetectorBuilder & nb) protected pure virtual
This function member has to be extended to properly build a sensor for a specific output lane Sensors has to be constrained on lane dimension Built sensors has to be collected and associated properly to the respective MSLane for retrieval using MSSOTLSensors::countVehicles(std::string) See extension classes for further specifications on sensor building.
Implemented in MSSOTLE2Sensors.
virtual void MSSOTLSensors::buildSensors (MSTrafficLightLogic::LaneVectorVector controlledLanes, NLDetectorBuilder & nb) pure virtual
This function member has to be extended to properly build sensors for the input lanes Sensors has to be constrained on lane dimension Built sensors has to be collected and associated properly to theirs MSLane for retrieval using MSSOTLSensors::countVehicles(std::string) See extension classes for further specifications on sensor building.
Implemented in MSSOTLE2Sensors.
virtual int MSSOTLSensors::countVehicles (MSLane * lane) pure virtual
Implemented in MSSOTLE2Sensors.
Referenced by MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLTrafficLightLogic::countVehicles(), and MSSwarmTrafficLightLogic::updatePheromoneLevels().
virtual int MSSOTLSensors::countVehicles (std::string laneId) pure virtual
Implemented in MSSOTLE2Sensors.
virtual SUMOReal MSSOTLSensors::getMaxSpeed (std::string laneId) pure virtual
Implemented in MSSOTLE2Sensors.
Referenced by MSSwarmTrafficLightLogic::updatePheromoneLevels().
virtual SUMOReal MSSOTLSensors::meanVehiclesSpeed (MSLane * lane) pure virtual
Implemented in MSSOTLE2Sensors.
Referenced by MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), and MSSwarmTrafficLightLogic::updatePheromoneLevels().
virtual SUMOReal MSSOTLSensors::meanVehiclesSpeed (std::string laneId) pure virtual
Implemented in MSSOTLE2Sensors.
virtual void MSSOTLSensors::stepChanged (int newStep) inline virtual
Definition at line 135 of file MSSOTLSensors.h.
Referenced by MSSOTLTrafficLightLogic::init(), and MSSOTLTrafficLightLogic::trySwitch().
Field Documentation
int MSSOTLSensors::currentStep protected
Definition at line 44 of file MSSOTLSensors.h.
const MSTrafficLightLogic::Phases* MSSOTLSensors::myPhases protected
Definition at line 42 of file MSSOTLSensors.h.
Referenced by MSSOTLSensors().
std::string MSSOTLSensors::tlLogicID protected
Definition at line 43 of file MSSOTLSensors.h.
Referenced by MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), and MSSOTLSensors().
The documentation for this class was generated from the following files:
MSSOTLSensors.h
MSSOTLSensors.cpp