SUMO - Simulation of Urban MObility: bezier.h File Reference
bezier.h File Reference
#include <config.h>
#include "PositionVector.h"
Functions
void bezier (int npts, SUMOReal b[], int cpts, SUMOReal p[])
PositionVector bezier (const PositionVector &init, int numPoints)
Detailed Description
Author
Daniel Krajzewicz
Michael Behrisch
Date
2003-11-19
Version
Id
bezier.h 21154 2016-07-12 14:23:01Z namdre
Definition in file bezier.h.
Function Documentation
void bezier (int npts, SUMOReal b[], int cpts, SUMOReal p[])
Definition at line 101 of file bezier.cpp.
References Basis(), and SUMOReal.
Referenced by bezier(), NBNode::computeSmoothShape(), NWWriter_OpenDrive::writeGeomSmooth(), and NWWriter_OpenDrive::writeNetwork().
PositionVector bezier (const PositionVector & init, int numPoints)
Definition at line 138 of file bezier.cpp.
References bezier(), ISNAN(), SUMOReal, Position::x(), and Position::y().