SUMO - Simulation of Urban MObility: ROJTREdgeBuilder Class Reference
ROJTREdgeBuilder Class Reference
Interface for building instances of jtrrouter-edges.
#include <ROJTREdgeBuilder.h>
Public Member Functions
ROJTREdgeBuilder ()
Constructor.
~ROJTREdgeBuilder ()
Destructor.
Methods inherited from ROAbstractEdgeBuilder
ROEdge * buildEdge (const std::string &name, RONode *from, RONode *to, const int priority)
Builds an edge with the given name.
Protected Member Functions
int getNextIndex ()
Returns the index of the edge to built.
Detailed Description
Interface for building instances of jtrrouter-edges.
This ROAbstractEdgeBuilder implementation builds edges for the jtrrouter (instances of ROJTREdge).
See also
ROJTREdge
Definition at line 56 of file ROJTREdgeBuilder.h.
Constructor & Destructor Documentation
ROJTREdgeBuilder::ROJTREdgeBuilder ()
Constructor.
Definition at line 44 of file ROJTREdgeBuilder.cpp.
ROJTREdgeBuilder::~ROJTREdgeBuilder ()
Destructor.
Definition at line 47 of file ROJTREdgeBuilder.cpp.
Member Function Documentation
ROEdge * ROJTREdgeBuilder::buildEdge (const std::string & name, RONode * from, RONode * to, const int priority) virtual
Builds an edge with the given name.
This implementation builds a ROJTREdge.
Parameters
[in] name The name of the edge
[in] from The node the edge begins at
[in] to The node the edge ends at
[in] priority The edge priority (road class)
Returns
A proper instance of the named edge
See also
ROJTREdge
Implements ROAbstractEdgeBuilder.
Definition at line 51 of file ROJTREdgeBuilder.cpp.
References ROAbstractEdgeBuilder::getNextIndex().
int ROAbstractEdgeBuilder::getNextIndex () inline protected inherited
Returns the index of the edge to built.
Returns
Next valid edge index
Definition at line 90 of file ROAbstractEdgeBuilder.h.
References ROAbstractEdgeBuilder::myCurrentIndex.
Referenced by AGStreet::Builder::buildEdge(), buildEdge(), RODFEdgeBuilder::buildEdge(), ROMAEdgeBuilder::buildEdge(), and RODUAEdgeBuilder::buildEdge().
The documentation for this class was generated from the following files:
ROJTREdgeBuilder.h
ROJTREdgeBuilder.cpp