SUMO - Simulation of Urban MObility: RandomDistributor< T > Class Template Reference
RandomDistributor< T > Class Template Reference
Represents a generic random distribution.
#include <RandomDistributor.h>
Public Member Functions
bool add (SUMOReal prob, T val, bool checkDuplicates=true)
Adds a value with an assigned probability to the distribution.
void clear ()
Clears the distribution.
T get (MTRand *which=0) const
Draw a sample of the distribution.
SUMOReal getOverallProb () const
Return the sum of the probabilites assigned to the members.
const std::vector< SUMOReal > & getProbs () const
Returns the probabilities assigned to the members of the distribution.
const std::vector< T > & getVals () const
Returns the members of the distribution.
RandomDistributor ()
Constructor for an empty distribution.
~RandomDistributor ()
Destructor.
Private Attributes
SUMOReal myProb
the total probability
std::vector< SUMOReal > myProbs
the corresponding probabilities (acts as a ring buffer if myMaximumSize is reached)
std::vector< T > myVals
the members (acts as a ring buffer if myMaximumSize is reached)
Detailed Description
template<class T>
class RandomDistributor< T >
Represents a generic random distribution.
This class allows to create random distributions by assigning arbitrary (non-negative) probabilities to its elements. The random number generator used is specified in RandHelper.
See also
RandHelper
Definition at line 56 of file RandomDistributor.h.
Constructor & Destructor Documentation
template<class T> RandomDistributor< T >::RandomDistributor () inline
Constructor for an empty distribution.
Parameters
[in] maximumSize The maximum size to maintain older entrys will be removed when adding more than the maximumSize
Definition at line 62 of file RandomDistributor.h.
template<class T> RandomDistributor< T >::~RandomDistributor () inline
Destructor.
Definition at line 67 of file RandomDistributor.h.
Member Function Documentation
template<class T> bool RandomDistributor< T >::add (SUMOReal prob, T val, bool checkDuplicates = true) inline
Adds a value with an assigned probability to the distribution.
If the value is already member of the distribution and checkDuplicates is true (the default) the given probability is added to the current. The probability has to be non-negative but values larger than one are allowed (and scaled accordingly when an element is drawn).
Parameters
[in] prob The probability assigned to the value
[in] val The value to add to the distribution
Returns
true if a new value was added, false if just the probability of an existing one was updated
Definition at line 80 of file RandomDistributor.h.
Referenced by GUIEdge::addRerouter(), ODDistrict::addSink(), ODDistrict::addSource(), ROJTREdge::chooseNext(), MSRouteHandler::closeRoute(), GUISettingsHandler::getEventDistribution(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), MSStateHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), MSRouteHandler::openRouteDistribution(), MSRouteHandler::openVehicleTypeDistribution(), and RORouteHandler::openVehicleTypeDistribution().
template<class T> void RandomDistributor< T >::clear () inline
Clears the distribution.
Definition at line 128 of file RandomDistributor.h.
Referenced by MSTriggeredRerouter::myEndElement().
template<class T> T RandomDistributor< T >::get (MTRand * which = 0) const inline
Draw a sample of the distribution.
A random sample is drawn according to the assigned probabilities.
Parameters
[in] which The random number generator to use; the static one will be used if 0 is passed
Returns
the drawn member
Definition at line 103 of file RandomDistributor.h.
Referenced by GUIApplicationWindow::checkGamingEvents(), ROJTREdge::chooseNext(), ODDistrict::getRandomSink(), ODDistrict::getRandomSource(), MSTriggeredRerouter::notifyEnter(), and RODFDetector::writeEmitterDefinition().
template<class T> SUMOReal RandomDistributor< T >::getOverallProb () const inline
Return the sum of the probabilites assigned to the members.
This should be zero if and only if the distribution is empty.
Returns
the total probability
Definition at line 123 of file RandomDistributor.h.
Referenced by GUIApplicationWindow::checkGamingEvents(), ROJTREdge::chooseNext(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::closeVehicleTypeDistribution(), RORouteHandler::closeVehicleTypeDistribution(), GUISettingsHandler::getEventDistribution(), MSTriggeredRerouter::notifyEnter(), and RODFDetector::writeEmitterDefinition().
template<class T> const std::vector<SUMOReal>& RandomDistributor< T >::getProbs () const inline
Returns the probabilities assigned to the members of the distribution.
See getVals for the corresponding members.
Returns
the probabilities assigned to the distribution
See also
RandomDistributor::getVals
Definition at line 152 of file RandomDistributor.h.
Referenced by MSDevice_Vehroutes::generateOutput(), and MSRouteHandler::openRoute().
template<class T> const std::vector<T>& RandomDistributor< T >::getVals () const inline
Returns the members of the distribution.
See getProbs for the corresponding probabilities.
Returns
the members of the distribution
See also
RandomDistributor::getProbs
Definition at line 141 of file RandomDistributor.h.
Referenced by MSInsertionControl::add(), MSDevice_Vehroutes::generateOutput(), ODDistrict::sinkNumber(), and ODDistrict::sourceNumber().
Field Documentation
template<class T> SUMOReal RandomDistributor< T >::myProb private
the total probability
Definition at line 158 of file RandomDistributor.h.
Referenced by RandomDistributor< SUMOVTypeParameter * >::add(), RandomDistributor< SUMOVTypeParameter * >::clear(), RandomDistributor< SUMOVTypeParameter * >::get(), and RandomDistributor< SUMOVTypeParameter * >::getOverallProb().
template<class T> std::vector<SUMOReal> RandomDistributor< T >::myProbs private
the corresponding probabilities (acts as a ring buffer if myMaximumSize is reached)
Definition at line 162 of file RandomDistributor.h.
Referenced by RandomDistributor< SUMOVTypeParameter * >::add(), RandomDistributor< SUMOVTypeParameter * >::clear(), RandomDistributor< SUMOVTypeParameter * >::get(), and RandomDistributor< SUMOVTypeParameter * >::getProbs().
template<class T> std::vector<T> RandomDistributor< T >::myVals private
the members (acts as a ring buffer if myMaximumSize is reached)
Definition at line 160 of file RandomDistributor.h.
Referenced by RandomDistributor< SUMOVTypeParameter * >::add(), RandomDistributor< SUMOVTypeParameter * >::clear(), RandomDistributor< SUMOVTypeParameter * >::get(), and RandomDistributor< SUMOVTypeParameter * >::getVals().
The documentation for this class was generated from the following file:
RandomDistributor.h