SUMO - Simulation of Urban MObility: MSVehicleContainer Class Reference
MSVehicleContainer Class Reference
#include <MSVehicleContainer.h>
Data Structures
class DepartFinder
Searches for the VehicleDepartureVector with the wished depart.
class VehicleDepartureVectorSortCrit
Sort-criterion for vehicle departure lists.
Public Types
typedef std::pair< SUMOTime, VehicleVector > VehicleDepartureVector
typedef std::vector< SUMOVehicle * > VehicleVector
definition of a list of vehicles which have the same departure time
Public Member Functions
void add (SUMOVehicle *veh)
Adds a single vehicle.
void add (SUMOTime time, const VehicleVector &cont)
Adds a container with vehicles departing at the given time.
bool anyWaitingBefore (SUMOTime time) const
Returns the information whether any vehicles want to depart before the given time.
bool isEmpty () const
Returns the information whether the container is empty.
MSVehicleContainer (int capacity=10)
Constructor.
void pop ()
Removes the uppermost vehicle vector.
void remove (SUMOVehicle *veh)
Removes a single vehicle.
void showArray () const
Prints the container (the departure times)
int size () const
Returns the size of the container.
const VehicleVector & top ()
Returns the uppermost vehicle vector.
SUMOTime topTime () const
Returns the time the uppermost vehicle vector is assigned to.
~MSVehicleContainer ()
Destructor.
Private Types
typedef std::vector< VehicleDepartureVector > VehicleHeap
Definition of the heap type.
Private Member Functions
void addReplacing (const VehicleDepartureVector &cont)
Replaces the existing single departure time vector by the one given.
bool isFull () const
void percolateDown (int hole)
Moves the elements down.
Private Attributes
VehicleHeap array
The vehicle vector heap.
int currentSize
Number of elements in heap.
Friends
std::ostream & operator<< (std::ostream &strm, MSVehicleContainer &cont)
Prints the contents of the container.
Detailed Description
A storage for vehicles, mainly used by the vehicle/route loading structures and the insertion control. Stores vehicles in a heap of vehiclevector/departure- pairs.
Definition at line 54 of file MSVehicleContainer.h.
Member Typedef Documentation
typedef std::pair<SUMOTime, VehicleVector> MSVehicleContainer::VehicleDepartureVector
definition of a structure storing the departure time and a list of vehicles leaving at this time
Definition at line 61 of file MSVehicleContainer.h.
typedef std::vector<VehicleDepartureVector> MSVehicleContainer::VehicleHeap private
Definition of the heap type.
Definition at line 138 of file MSVehicleContainer.h.
typedef std::vector<SUMOVehicle*> MSVehicleContainer::VehicleVector
definition of a list of vehicles which have the same departure time
Definition at line 57 of file MSVehicleContainer.h.
Constructor & Destructor Documentation
MSVehicleContainer::MSVehicleContainer (int capacity = 10)
Constructor.
Definition at line 76 of file MSVehicleContainer.cpp.
MSVehicleContainer::~MSVehicleContainer ()
Destructor.
Definition at line 80 of file MSVehicleContainer.cpp.
Member Function Documentation
void MSVehicleContainer::add (SUMOVehicle * veh)
Adds a single vehicle.
Definition at line 86 of file MSVehicleContainer.cpp.
References addReplacing(), array, currentSize, SUMOVehicleParameter::depart, and SUMOVehicle::getParameter().
Referenced by MSInsertionControl::add().
void MSVehicleContainer::add (SUMOTime time, const VehicleVector & cont)
Adds a container with vehicles departing at the given time.
Definition at line 117 of file MSVehicleContainer.cpp.
References addReplacing(), array, and currentSize.
void MSVehicleContainer::addReplacing (const VehicleDepartureVector & cont) private
Replaces the existing single departure time vector by the one given.
Definition at line 135 of file MSVehicleContainer.cpp.
References array, currentSize, and isFull().
Referenced by add().
bool MSVehicleContainer::anyWaitingBefore (SUMOTime time) const
Returns the information whether any vehicles want to depart before the given time.
Definition at line 157 of file MSVehicleContainer.cpp.
References isEmpty(), and topTime().
Referenced by MSInsertionControl::checkCandidates().
bool MSVehicleContainer::isEmpty () const
Returns the information whether the container is empty.
Definition at line 197 of file MSVehicleContainer.cpp.
References currentSize.
Referenced by anyWaitingBefore(), operator<<(), pop(), top(), and topTime().
bool MSVehicleContainer::isFull () const private
Returns the information whether the container must be extended
Definition at line 203 of file MSVehicleContainer.cpp.
References array, and currentSize.
Referenced by addReplacing().
void MSVehicleContainer::percolateDown (int hole) private
Moves the elements down.
Definition at line 209 of file MSVehicleContainer.cpp.
References array, and currentSize.
Referenced by pop().
void MSVehicleContainer::pop ()
Removes the uppermost vehicle vector.
!!Underflow();
Definition at line 183 of file MSVehicleContainer.cpp.
References array, currentSize, isEmpty(), and percolateDown().
Referenced by MSInsertionControl::checkCandidates(), and operator<<().
void MSVehicleContainer::remove (SUMOVehicle * veh)
Removes a single vehicle.
Definition at line 104 of file MSVehicleContainer.cpp.
References array, currentSize, SUMOVehicleParameter::depart, and SUMOVehicle::getParameter().
Referenced by MSInsertionControl::alreadyDeparted().
void MSVehicleContainer::showArray () const
Prints the container (the departure times)
Definition at line 238 of file MSVehicleContainer.cpp.
References array, and currentSize.
int MSVehicleContainer::size () const
Returns the size of the container.
Definition at line 232 of file MSVehicleContainer.cpp.
References currentSize.
const MSVehicleContainer::VehicleVector & MSVehicleContainer::top ()
Returns the uppermost vehicle vector.
!!Underflow();
Definition at line 163 of file MSVehicleContainer.cpp.
References array, and isEmpty().
Referenced by MSInsertionControl::checkCandidates(), and operator<<().
SUMOTime MSVehicleContainer::topTime () const
Returns the time the uppermost vehicle vector is assigned to.
!!Underflow();
Definition at line 173 of file MSVehicleContainer.cpp.
References array, and isEmpty().
Referenced by anyWaitingBefore().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & strm, MSVehicleContainer & cont) friend
Prints the contents of the container.
Definition at line 249 of file MSVehicleContainer.cpp.
Field Documentation
VehicleHeap MSVehicleContainer::array private
The vehicle vector heap.
Definition at line 141 of file MSVehicleContainer.h.
Referenced by add(), addReplacing(), isFull(), percolateDown(), pop(), remove(), showArray(), top(), and topTime().
int MSVehicleContainer::currentSize private
Number of elements in heap.
Definition at line 135 of file MSVehicleContainer.h.
Referenced by add(), addReplacing(), isEmpty(), isFull(), percolateDown(), pop(), remove(), showArray(), and size().
The documentation for this class was generated from the following files:
MSVehicleContainer.h
MSVehicleContainer.cpp