SUMO - Simulation of Urban MObility: SUMOAbstractRouter< E, V > Class Template Reference
SUMOAbstractRouter< E, V > Class Template Reference abstract
#include <SUMOAbstractRouter.h>
Public Types
typedef SUMOReal(* Operation) (const E *const, const V *const, SUMOReal)
Type of the function that is used to retrieve the edge effort.
Public Member Functions
virtual SUMOAbstractRouter * clone ()=0
virtual bool compute (const E *from, const E *to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > &into)=0
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
void endQuery (int visits)
SUMOReal getEffort (const E *const e, const V *const v, SUMOReal t) const
virtual SUMOReal recomputeCosts (const std::vector< const E * > &edges, const V *const v, SUMOTime msTime) const =0
void setBulkMode (const bool mode)
void startQuery ()
SUMOAbstractRouter (Operation operation, const std::string &type)
Constructor.
virtual ~SUMOAbstractRouter ()
Destructor.
Protected Attributes
bool myBulkMode
whether we are currently operating several route queries in a bulk
Operation myOperation
The object's operation to perform.
Private Member Functions
SUMOAbstractRouter & operator= (const SUMOAbstractRouter &s)
Invalidated assignment operator.
Private Attributes
long long int myNumQueries
long long int myQueryStartTime
the time spent querying in milliseconds
long long int myQueryTimeSum
long long int myQueryVisits
counters for performance logging
const std::string myType
the type of this router
Detailed Description
template<class E, class V>
class SUMOAbstractRouter< E, V >
The interface for routing the vehicles over the network.
Definition at line 53 of file SUMOAbstractRouter.h.
Member Typedef Documentation
template<class E, class V> typedef SUMOReal(* SUMOAbstractRouter< E, V >::Operation) (const E *const, const V *const, SUMOReal)
Type of the function that is used to retrieve the edge effort.
Definition at line 56 of file SUMOAbstractRouter.h.
Constructor & Destructor Documentation
template<class E, class V> SUMOAbstractRouter< E, V >::SUMOAbstractRouter (Operation operation, const std::string & type) inline
Constructor.
Definition at line 59 of file SUMOAbstractRouter.h.
template<class E, class V> virtual SUMOAbstractRouter< E, V >::~SUMOAbstractRouter () inline virtual
Destructor.
Definition at line 70 of file SUMOAbstractRouter.h.
Member Function Documentation
template<class E, class V> virtual SUMOAbstractRouter* SUMOAbstractRouter< E, V >::clone () pure virtual
Implemented in CHRouter< E, V, PF >, AStarRouter< E, V, PF >, AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >, DijkstraRouterTT< E, V, PF >, DijkstraRouterTT< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >, DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >, DijkstraRouterEffort< E, V, PF >, DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >, CHRouterWrapper< E, V, PF >, IntermodalRouter< E, L, N, V, INTERNALROUTER >, IntermodalRouter< E, L, N, V >, PedestrianRouter< E, L, N, V, INTERNALROUTER >, PedestrianRouter< E, L, N, V, DijkstraRouterTT< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >, and ROJTRRouter.
Referenced by SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::~SUMOAbstractRouter().
template<class E, class V> virtual bool SUMOAbstractRouter< E, V >::compute (const E * from, const E * to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > & into) pure virtual
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Implemented in IntermodalRouter< E, L, N, V, INTERNALROUTER >, IntermodalRouter< E, L, N, V >, AStarRouter< E, V, PF >, AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >, DijkstraRouterEffort< E, V, PF >, DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >, DijkstraRouterTT< E, V, PF >, DijkstraRouterTT< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >, DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >, PedestrianRouter< E, L, N, V, INTERNALROUTER >, PedestrianRouter< E, L, N, V, DijkstraRouterTT< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >, and CHRouterWrapper< E, V, PF >.
Referenced by TraCIServerAPI_Simulation::commandDistanceRequest(), ROMAAssignments::getKPaths(), ROMAAssignments::incremental(), MSTriggeredRerouter::notifyEnter(), TraCIServerAPI_Vehicle::processSet(), RORouteDef::repairCurrentRoute(), MSBaseVehicle::reroute(), ROMAAssignments::sue(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::~SUMOAbstractRouter().
template<class E, class V> void SUMOAbstractRouter< E, V >::endQuery (int visits) inline
Definition at line 96 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and CHRouter< E, V, PF >::compute().
template<class E, class V> SUMOReal SUMOAbstractRouter< E, V >::getEffort (const E *const e, const V *const v, SUMOReal t) const inline
Definition at line 87 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), CHRouterWrapper< E, V, PF >::recomputeCosts(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), CHRouter< E, V, PF >::recomputeCosts(), and CHRouter< E, V, PF >::synchronize().
template<class E, class V> SUMOAbstractRouter& SUMOAbstractRouter< E, V >::operator= (const SUMOAbstractRouter< E, V > & s) private
Invalidated assignment operator.
template<class E, class V> virtual SUMOReal SUMOAbstractRouter< E, V >::recomputeCosts (const std::vector< const E * > & edges, const V *const v, SUMOTime msTime) const pure virtual
Implemented in CHRouter< E, V, PF >, IntermodalRouter< E, L, N, V, INTERNALROUTER >, IntermodalRouter< E, L, N, V >, AStarRouter< E, V, PF >, AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >, DijkstraRouterTT< E, V, PF >, DijkstraRouterTT< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >, DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >, DijkstraRouterEffort< E, V, PF >, DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >, PedestrianRouter< E, L, N, V, INTERNALROUTER >, PedestrianRouter< E, L, N, V, DijkstraRouterTT< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >, and CHRouterWrapper< E, V, PF >.
Referenced by RORouteDef::addAlternative(), computeRoutes(), ROMAAssignments::sue(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::~SUMOAbstractRouter().
template<class E, class V> void SUMOAbstractRouter< E, V >::setBulkMode (const bool mode) inline
Definition at line 101 of file SUMOAbstractRouter.h.
Referenced by ROMAAssignments::incremental().
template<class E, class V> void SUMOAbstractRouter< E, V >::startQuery () inline
Definition at line 91 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and CHRouter< E, V, PF >::compute().
Field Documentation
template<class E, class V> bool SUMOAbstractRouter< E, V >::myBulkMode protected
whether we are currently operating several route queries in a bulk
Definition at line 110 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::setBulkMode().
template<class E, class V> long long int SUMOAbstractRouter< E, V >::myNumQueries private
Definition at line 118 of file SUMOAbstractRouter.h.
Referenced by SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::startQuery(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::~SUMOAbstractRouter().
template<class E, class V> Operation SUMOAbstractRouter< E, V >::myOperation protected
The object's operation to perform.
Definition at line 107 of file SUMOAbstractRouter.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), CHRouter< E, V, PF >::clone(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::getEffort().
template<class E, class V> long long int SUMOAbstractRouter< E, V >::myQueryStartTime private
the time spent querying in milliseconds
Definition at line 120 of file SUMOAbstractRouter.h.
Referenced by SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::endQuery(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::startQuery().
template<class E, class V> long long int SUMOAbstractRouter< E, V >::myQueryTimeSum private
Definition at line 121 of file SUMOAbstractRouter.h.
Referenced by SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::endQuery(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::~SUMOAbstractRouter().
template<class E, class V> long long int SUMOAbstractRouter< E, V >::myQueryVisits private
counters for performance logging
Definition at line 117 of file SUMOAbstractRouter.h.
Referenced by SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::endQuery(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::~SUMOAbstractRouter().
template<class E, class V> const std::string SUMOAbstractRouter< E, V >::myType private
the type of this router
Definition at line 114 of file SUMOAbstractRouter.h.
Referenced by SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::~SUMOAbstractRouter().
The documentation for this class was generated from the following file:
SUMOAbstractRouter.h