SUMO - Simulation of Urban MObility: GUIParameterTableItemInterface Class Reference
GUIParameterTableItemInterface Class Reference abstract
Interface to a single line in a parameter window.
#include <GUIParameterTableItem.h>
Public Member Functions
virtual ~GUIParameterTableItemInterface ()
Destructor.
Methods to be implemented by derived classes
virtual bool dynamic () const =0
Returns the information whether the value changes over simulation time.
virtual void update ()=0
Forces an update of the value.
virtual ValueSource< SUMOReal > * getSUMORealSourceCopy () const =0
Returns a SUMOReal-typed copy of the value-source.
virtual const std::string & getName () const =0
Returns the name of the value.
Detailed Description
Interface to a single line in a parameter window.
Because a single line in a parameter window may display different kinds of information (different value types, dynamic or static information), an interface is needed in order to allow a common access to the functions of a line - basically the possibility to open a tracker (GUIParameterTracker) for the stored, dynamic value.
The implementation is done by GUIParameterTableItem.
See also
GUIParameterTracker
GUIParameterTableItem
Definition at line 64 of file GUIParameterTableItem.h.
Constructor & Destructor Documentation
virtual GUIParameterTableItemInterface::~GUIParameterTableItemInterface () inline virtual
Destructor.
Definition at line 67 of file GUIParameterTableItem.h.
References dynamic(), getName(), getSUMORealSourceCopy(), and update().
Member Function Documentation
virtual bool GUIParameterTableItemInterface::dynamic () const pure virtual
Returns the information whether the value changes over simulation time.
Returns
Whether the value changes over simulation time
Implemented in GUIParameterTableItem< T >.
Referenced by GUIParameterTableWindow::onRightButtonPress(), GUIParameterTableItem< T >::update(), and ~GUIParameterTableItemInterface().
virtual const std::string& GUIParameterTableItemInterface::getName () const pure virtual
Returns the name of the value.
Returns
The name of the value
Implemented in GUIParameterTableItem< T >.
Referenced by GUIParameterTableWindow::onRightButtonPress(), and ~GUIParameterTableItemInterface().
virtual ValueSource<SUMOReal>* GUIParameterTableItemInterface::getSUMORealSourceCopy () const pure virtual
Returns a SUMOReal-typed copy of the value-source.
Returns
A SUMOReal-typed copy of the value-source
Implemented in GUIParameterTableItem< T >.
Referenced by GUIParameterTableWindow::onRightButtonPress(), and ~GUIParameterTableItemInterface().
virtual void GUIParameterTableItemInterface::update () pure virtual
Forces an update of the value.
Implemented in GUIParameterTableItem< T >.
Referenced by ~GUIParameterTableItemInterface().
The documentation for this class was generated from the following file:
GUIParameterTableItem.h