SUMO - Simulation of Urban MObility: points.h File Reference
points.h File Reference
#include <iostream>
#include <cmath>
#include <cassert>
Data Structures
class Point2D< coord_type >
Functions
template<class point_type1 , class point_type2 >
double euc_distance (Point2D< point_type1 > pt1, Point2D< point_type2 > pt2)
template<class mul_type , class point_type >
Point2D< point_type > operator* (mul_type val, const Point2D< point_type > pt)
template<class point_type , class mul_type >
Point2D< point_type > operator* (const Point2D< point_type > pt, mul_type val)
template<class point1_type , class point2_type >
Point2D< double > operator+ (const Point2D< point1_type > &pt1, const Point2D< point2_type > &pt2)
template<class point1_type , class point2_type >
Point2D< point1_type > operator- (Point2D< point1_type > pt1, Point2D< point2_type > pt2)
template<class point_type , class div_type >
Point2D< point_type > operator/ (const Point2D< point_type > pt, div_type val)
Function Documentation
template<class point_type1 , class point_type2 > double euc_distance (Point2D< point_type1 > pt1, Point2D< point_type2 > pt2)
Definition at line 245 of file points.h.
References Point2D< coord_type >::getX(), and Point2D< coord_type >::getY().
Referenced by BiArc::compute_biarc_params(), EulerSpiral::compute_error(), and EulerSpiral::compute_es_params().
template<class mul_type , class point_type > Point2D<point_type> operator* (mul_type val, const Point2D< point_type > pt) inline
Definition at line 180 of file points.h.
References Point2D< coord_type >::getX(), and Point2D< coord_type >::getY().
Referenced by MSLane::AnyVehicleIterator::operator->().
template<class point_type , class mul_type > Point2D<point_type> operator* (const Point2D< point_type > pt, mul_type val) inline
Definition at line 187 of file points.h.
template<class point1_type , class point2_type > Point2D<double> operator+ (const Point2D< point1_type > & pt1, const Point2D< point2_type > & pt2) inline
Definition at line 215 of file points.h.
References Point2D< coord_type >::getX(), and Point2D< coord_type >::getY().
template<class point1_type , class point2_type > Point2D<point1_type> operator- (Point2D< point1_type > pt1, Point2D< point2_type > pt2) inline
Definition at line 228 of file points.h.
References Point2D< coord_type >::getX(), and Point2D< coord_type >::getY().
template<class point_type , class div_type > Point2D<point_type> operator/ (const Point2D< point_type > pt, div_type val) inline
Definition at line 198 of file points.h.
References Point2D< coord_type >::getX(), and Point2D< coord_type >::getY().