SUMO - Simulation of Urban MObility: TraCIServerAPI_POI Class Reference
TraCIServerAPI_POI Class Reference
APIs for getting/setting POI values via TraCI.
#include <TraCIServerAPI_POI.h>
Static Public Member Functions
static bool getPosition (const std::string &id, Position &p)
Returns the named PoI's position.
static NamedRTree * getTree ()
Returns a tree filled with PoI instances.
static bool processGet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a get value command (Command 0xa7: Get PoI Variable)
static bool processSet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a set value command (Command 0xc7: Change PoI State)
Private Member Functions
TraCIServerAPI_POI & operator= (const TraCIServerAPI_POI &s)
invalidated assignment operator
TraCIServerAPI_POI (const TraCIServerAPI_POI &s)
invalidated copy constructor
Static Private Member Functions
static PointOfInterest * getPoI (const std::string &id)
Returns the named PoI.
Detailed Description
APIs for getting/setting POI values via TraCI.
Definition at line 48 of file TraCIServerAPI_POI.h.
Constructor & Destructor Documentation
TraCIServerAPI_POI::TraCIServerAPI_POI (const TraCIServerAPI_POI & s) private
invalidated copy constructor
Member Function Documentation
PointOfInterest * TraCIServerAPI_POI::getPoI (const std::string & id) static private
Returns the named PoI.
Parameters
[in] id The id of the searched PoI
Returns
The named PoI, or 0 if it is not known
Definition at line 244 of file TraCIServerAPI_POI.cpp.
References NamedObjectCont< T >::get(), MSNet::getInstance(), ShapeContainer::getPOIs(), and MSNet::getShapeContainer().
Referenced by getPosition(), processGet(), and processSet().
bool TraCIServerAPI_POI::getPosition (const std::string & id, Position & p) static
Returns the named PoI's position.
Parameters
[in] id The id of the searched PoI
[out] p The position, if the PoI is known
Returns
Whether the PoI is known (and on road)
Definition at line 233 of file TraCIServerAPI_POI.cpp.
References getPoI().
Referenced by TraCIServer::findObjectShape().
NamedRTree * TraCIServerAPI_POI::getTree () static
Returns a tree filled with PoI instances.
Returns
The rtree of PoIs
Definition at line 250 of file TraCIServerAPI_POI.cpp.
References MSNet::getInstance(), NamedObjectCont< T >::getMyMap(), ShapeContainer::getPOIs(), MSNet::getShapeContainer(), and NamedRTree::Insert().
Referenced by TraCIServer::collectObjectsInRange().
TraCIServerAPI_POI& TraCIServerAPI_POI::operator= (const TraCIServerAPI_POI & s) private
invalidated assignment operator
bool TraCIServerAPI_POI::processGet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a get value command (Command 0xa7: Get PoI Variable)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 51 of file TraCIServerAPI_POI.cpp.
References RGBColor::alpha(), RGBColor::blue(), CMD_GET_POI_VARIABLE, Shape::getColor(), MSNet::getInstance(), Parameterised::getParameter(), getPoI(), ShapeContainer::getPOIs(), MSNet::getShapeContainer(), Shape::getType(), RGBColor::green(), ID_COUNT, ID_LIST, NamedObjectCont< T >::insertIDs(), POSITION_2D, tcpip::Storage::readString(), TraCIServer::readTypeCheckingString(), tcpip::Storage::readUnsignedByte(), RGBColor::red(), RESPONSE_GET_POI_VARIABLE, RTYPE_OK, toHex(), TYPE_COLOR, TYPE_INTEGER, TYPE_STRING, TYPE_STRINGLIST, VAR_COLOR, VAR_PARAMETER, VAR_POSITION, VAR_TYPE, tcpip::Storage::writeDouble(), TraCIServer::writeErrorStatusCmd(), tcpip::Storage::writeInt(), TraCIServer::writeResponseWithLength(), TraCIServer::writeStatusCmd(), tcpip::Storage::writeString(), tcpip::Storage::writeStringList(), tcpip::Storage::writeUnsignedByte(), Position::x(), and Position::y().
Referenced by TraCIServer::TraCIServer().
bool TraCIServerAPI_POI::processSet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a set value command (Command 0xc7: Change PoI State)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 121 of file TraCIServerAPI_POI.cpp.
References ADD, Parameterised::addParameter(), ShapeContainer::addPOI(), CMD_SET_POI_VARIABLE, Shape::DEFAULT_ANGLE, Shape::DEFAULT_IMG_FILE, Shape::DEFAULT_IMG_HEIGHT, Shape::DEFAULT_IMG_WIDTH, MSNet::getInstance(), getPoI(), MSNet::getShapeContainer(), ShapeContainer::movePOI(), tcpip::Storage::readInt(), tcpip::Storage::readString(), TraCIServer::readTypeCheckingColor(), TraCIServer::readTypeCheckingInt(), TraCIServer::readTypeCheckingPosition2D(), TraCIServer::readTypeCheckingString(), tcpip::Storage::readUnsignedByte(), REMOVE, ShapeContainer::removePOI(), RTYPE_OK, Shape::setColor(), Shape::setType(), SUMOReal, toHex(), TYPE_COMPOUND, VAR_COLOR, VAR_PARAMETER, VAR_POSITION, VAR_TYPE, TraCIServer::writeErrorStatusCmd(), and TraCIServer::writeStatusCmd().
Referenced by TraCIServer::TraCIServer().
The documentation for this class was generated from the following files:
TraCIServerAPI_POI.h
TraCIServerAPI_POI.cpp