SUMO - Simulation of Urban MObility: NIImporter_DlrNavteq::NamesHandler Class Reference
NIImporter_DlrNavteq::NamesHandler Class Reference
Importer of street names in DLRNavteq's (aka elmar) format.
#include <NIImporter_DlrNavteq.h>
Public Member Functions
NamesHandler (const std::string &file, std::map< std::string, std::string > &streetNames)
Constructor.
bool report (const std::string &result)
Parsing method.
~NamesHandler ()
Destructor.
Protected Attributes
std::map< std::string, std::string > & myStreetNames
The container for storing read names.
Private Member Functions
NamesHandler (const NamesHandler &)
Invalidated copy constructor.
NamesHandler & operator= (const NamesHandler &)
Invalidated assignment operator.
Detailed Description
Importer of street names in DLRNavteq's (aka elmar) format.
Being a LineHandler, this class retrieves each line from a LineReader and parses these information assuming they contain name definitions in DLRNavteq's format.
Definition at line 312 of file NIImporter_DlrNavteq.h.
Constructor & Destructor Documentation
NIImporter_DlrNavteq::NamesHandler::NamesHandler (const std::string & file, std::map< std::string, std::string > & streetNames)
Constructor.
Parameters
[in] file The name of the parsed file
Definition at line 452 of file NIImporter_DlrNavteq.cpp.
References UNUSED_PARAMETER.
NIImporter_DlrNavteq::NamesHandler::~NamesHandler ()
Destructor.
Definition at line 459 of file NIImporter_DlrNavteq.cpp.
NIImporter_DlrNavteq::NamesHandler::NamesHandler (const NamesHandler &) private
Invalidated copy constructor.
Member Function Documentation
NamesHandler& NIImporter_DlrNavteq::NamesHandler::operator= (const NamesHandler &) private
Invalidated assignment operator.
bool NIImporter_DlrNavteq::NamesHandler::report (const std::string & result) virtual
Parsing method.
Implementation of the LineHandler-interface called by a LineReader; interprets the retrieved information and stores the streetNames
Parameters
[in] result The read line
Returns
Whether the parsing shall continue
Exceptions
ProcessError if something fails
See also
LineHandler::report
Implements LineHandler.
Definition at line 463 of file NIImporter_DlrNavteq.cpp.
References StringTokenizer::getVector(), joinToString(), myStreetNames, StringTokenizer::next(), StringTokenizer::size(), and StringTokenizer::WHITECHARS.
Field Documentation
std::map<std::string, std::string>& NIImporter_DlrNavteq::NamesHandler::myStreetNames protected
The container for storing read names.
Definition at line 339 of file NIImporter_DlrNavteq.h.
Referenced by report().
The documentation for this class was generated from the following files:
NIImporter_DlrNavteq.h
NIImporter_DlrNavteq.cpp