SUMO - Simulation of Urban MObility: ROJTRRouter Class Reference
ROJTRRouter Class Reference abstract
Computes routes using junction turning percentages.
#include <ROJTRRouter.h>
Public Types
typedef SUMOReal(* Operation) (const ROEdge *const, const ROVehicle *const, SUMOReal)
Type of the function that is used to retrieve the edge effort.
Public Member Functions
virtual SUMOAbstractRouter< ROEdge, ROVehicle > * clone ()
virtual bool compute (const ROEdge *from, const ROEdge *to, const ROVehicle *const vehicle, SUMOTime msTime, std::vector< const ROEdge * > &into)=0
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
void endQuery (int visits)
SUMOReal getEffort (const ROEdge *const e, const ROVehicle *const v, SUMOReal t) const
virtual SUMOReal recomputeCosts (const std::vector< const ROEdge * > &edges, const ROVehicle *const v, SUMOTime msTime) const =0
ROJTRRouter (bool unbuildIsWarningOnly, bool acceptAllDestinations, int maxEdges, bool ignoreClasses, bool allowLoops)
Constructor.
void setBulkMode (const bool mode)
void startQuery ()
~ROJTRRouter ()
Destructor.
Implementatios of SUMOAbstractRouter
bool compute (const ROEdge *from, const ROEdge *to, const ROVehicle *const vehicle, SUMOTime time, ConstROEdgeVector &into)
Computes a route.
SUMOReal recomputeCosts (const ConstROEdgeVector &edges, const ROVehicle *const v, SUMOTime time) const
Recomputes the costs of a route.
Protected Attributes
bool myBulkMode
whether we are currently operating several route queries in a bulk
Operation myOperation
The object's operation to perform.
Private Attributes
const bool myAcceptAllDestination
Whether all edges may be used as route end.
const bool myAllowLoops
Whether a vehicle may reuse a road.
const bool myIgnoreClasses
Whether vehicle class information shall be ignored.
const int myMaxEdges
The maximum number of edges a route may have.
const bool myUnbuildIsWarningOnly
Whether unbuildable routes shall be reported as warniings, not errors.
Detailed Description
Computes routes using junction turning percentages.
Definition at line 53 of file ROJTRRouter.h.
Member Typedef Documentation
typedef SUMOReal(* SUMOAbstractRouter< ROEdge , ROVehicle >::Operation) (const ROEdge *const, const ROVehicle *const, SUMOReal) inherited
Type of the function that is used to retrieve the edge effort.
Definition at line 56 of file SUMOAbstractRouter.h.
Constructor & Destructor Documentation
ROJTRRouter::ROJTRRouter (bool unbuildIsWarningOnly, bool acceptAllDestinations, int maxEdges, bool ignoreClasses, bool allowLoops)
Constructor.
Parameters
[in] unbuildIsWarningOnly Whether not closed routes shall not yield in an error
[in] acceptAllDestinations If false, only sinks will be used as final edges
[in] maxEdges The maximum number of edges a route may have
[in] ignoreClasses Whether routing shall be done without regarding vehicle classes
[in] allowLoops Whether a vehicle may reuse a road
Definition at line 46 of file ROJTRRouter.cpp.
Referenced by clone().
ROJTRRouter::~ROJTRRouter ()
Destructor.
Definition at line 55 of file ROJTRRouter.cpp.
Member Function Documentation
virtual SUMOAbstractRouter<ROEdge, ROVehicle>* ROJTRRouter::clone () inline virtual
Implements SUMOAbstractRouter< ROEdge, ROVehicle >.
Definition at line 70 of file ROJTRRouter.h.
References compute(), myAcceptAllDestination, myAllowLoops, myIgnoreClasses, myMaxEdges, myUnbuildIsWarningOnly, recomputeCosts(), ROJTRRouter(), and SUMOReal.
virtual bool SUMOAbstractRouter< ROEdge , ROVehicle >::compute (const ROEdge * from, const ROEdge * to, const ROVehicle *const vehicle, SUMOTime msTime, std::vector< const ROEdge * > & into) pure virtual inherited
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
bool ROJTRRouter::compute (const ROEdge * from, const ROEdge * to, const ROVehicle *const vehicle, SUMOTime time, ConstROEdgeVector & into)
Computes a route.
The description how routes are computed is given in the user documentation
Parameters
[in] from The edge the vehicle starts at
[in] to The destination edge - invalid here
[in] vehicle The vehicle to compute the route for
[in] time The departure time of the vehicle
Definition at line 59 of file ROJTRRouter.cpp.
References ROJTREdge::chooseNext(), ROEdge::ET_SINK, MsgHandler::getErrorInstance(), ROEdge::getFunc(), Named::getID(), ROEdge::getTravelTime(), MsgHandler::getWarningInstance(), MsgHandler::inform(), myAcceptAllDestination, myAllowLoops, myIgnoreClasses, myMaxEdges, myUnbuildIsWarningOnly, ROEdge::prohibits(), STEPS2TIME, and SUMOReal.
Referenced by clone().
void SUMOAbstractRouter< ROEdge , ROVehicle >::endQuery (int visits) inline inherited
Definition at line 96 of file SUMOAbstractRouter.h.
SUMOReal SUMOAbstractRouter< ROEdge , ROVehicle >::getEffort (const ROEdge *const e, const ROVehicle *const v, SUMOReal t) const inline inherited
Definition at line 87 of file SUMOAbstractRouter.h.
virtual SUMOReal SUMOAbstractRouter< ROEdge , ROVehicle >::recomputeCosts (const std::vector< const ROEdge * > & edges, const ROVehicle *const v, SUMOTime msTime) const pure virtual inherited
SUMOReal ROJTRRouter::recomputeCosts (const ConstROEdgeVector & edges, const ROVehicle *const v, SUMOTime time) const
Recomputes the costs of a route.
Parameters
[in] edges The route
[in] v The vehicle that belongs to the route
[in] time The departure time of the vehicle
Returns
The route costs
Definition at line 96 of file ROJTRRouter.cpp.
References SUMOReal.
Referenced by clone().
void SUMOAbstractRouter< ROEdge , ROVehicle >::setBulkMode (const bool mode) inline inherited
Definition at line 101 of file SUMOAbstractRouter.h.
void SUMOAbstractRouter< ROEdge , ROVehicle >::startQuery () inline inherited
Definition at line 91 of file SUMOAbstractRouter.h.
Field Documentation
const bool ROJTRRouter::myAcceptAllDestination private
Whether all edges may be used as route end.
Definition at line 105 of file ROJTRRouter.h.
Referenced by clone(), and compute().
const bool ROJTRRouter::myAllowLoops private
Whether a vehicle may reuse a road.
Definition at line 114 of file ROJTRRouter.h.
Referenced by clone(), and compute().
bool SUMOAbstractRouter< ROEdge , ROVehicle >::myBulkMode protected inherited
whether we are currently operating several route queries in a bulk
Definition at line 110 of file SUMOAbstractRouter.h.
const bool ROJTRRouter::myIgnoreClasses private
Whether vehicle class information shall be ignored.
Definition at line 111 of file ROJTRRouter.h.
Referenced by clone(), and compute().
const int ROJTRRouter::myMaxEdges private
The maximum number of edges a route may have.
Definition at line 108 of file ROJTRRouter.h.
Referenced by clone(), and compute().
Operation SUMOAbstractRouter< ROEdge , ROVehicle >::myOperation protected inherited
The object's operation to perform.
Definition at line 107 of file SUMOAbstractRouter.h.
const bool ROJTRRouter::myUnbuildIsWarningOnly private
Whether unbuildable routes shall be reported as warniings, not errors.
Definition at line 102 of file ROJTRRouter.h.
Referenced by clone(), and compute().
The documentation for this class was generated from the following files:
ROJTRRouter.h
ROJTRRouter.cpp