SUMO - Simulation of Urban MObility: PCLoaderOSM Class Reference
PCLoaderOSM Class Reference
A reader of pois and polygons stored in OSM-format.
#include <PCLoaderOSM.h>
Data Structures
class EdgesHandler
A class which extracts OSM-edges from a parsed OSM-file.
class NodesHandler
A class which extracts OSM-nodes from a parsed OSM-file.
struct PCOSMEdge
An internal definition of a loaded edge.
struct PCOSMNode
An internal representation of an OSM-node.
struct PCOSMRelation
An internal definition of a loaded relation.
class RelationsHandler
A class which extracts relevant way-ids from relations in a parsed OSM-file.
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Static Public Member Functions
static void loadIfSet (OptionsCont &oc, PCPolyContainer &toFill, PCTypeMap &tm)
Loads pois/polygons assumed to be stored as OSM-XML.
Protected Types
typedef std::map< long long int, PCOSMEdge * > EdgeMap
typedef std::vector< PCOSMRelation * > Relations
typedef std::map< long long int, PCOSMRelation * > RelationsMap
Protected Member Functions
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
virtual void myEndElement (int element)
Callback method for a closing tag to implement by derived classes.
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Callback method for an opening tag to implement by derived classes.
Static Protected Member Functions
static int addPOI (const PCOSMNode *node, const Position &pos, const PCTypeMap::TypeDef &def, const std::string &fullType, int index, PCPolyContainer &toFill, bool ignorePruning, bool withAttributes)
try add the POI and return the next index on success
static int addPolygon (const PCOSMEdge *edge, const PositionVector &vec, const PCTypeMap::TypeDef &def, const std::string &fullType, int index, bool useName, PCPolyContainer &toFill, bool ignorePruning, bool withAttributes)
try add the polygon and return the next index on success
Static Protected Attributes
static const std::set< std::string > MyKeysToInclude
Static Private Member Functions
static std::set< std::string > initMyKeysToInclude ()
Detailed Description
A reader of pois and polygons stored in OSM-format.
Reads pois stored as XML definition as given by the OpenStreetMap-API.
Definition at line 57 of file PCLoaderOSM.h.
Member Typedef Documentation
typedef std::map<long long int, PCOSMEdge*> PCLoaderOSM::EdgeMap protected
Definition at line 119 of file PCLoaderOSM.h.
typedef std::vector<PCOSMRelation*> PCLoaderOSM::Relations protected
Definition at line 117 of file PCLoaderOSM.h.
typedef std::map<long long int, PCOSMRelation*> PCLoaderOSM::RelationsMap protected
Definition at line 118 of file PCLoaderOSM.h.
Member Function Documentation
int PCLoaderOSM::addPOI (const PCOSMNode * node, const Position & pos, const PCTypeMap::TypeDef & def, const std::string & fullType, int index, PCPolyContainer & toFill, bool ignorePruning, bool withAttributes) static protected
try add the POI and return the next index on success
Definition at line 263 of file PCLoaderOSM.cpp.
References PCPolyContainer::add(), Parameterised::addParameter(), PCTypeMap::TypeDef::color, PCTypeMap::TypeDef::discard, StringUtils::escapeXML(), OptionsCont::getOptions(), PCTypeMap::TypeDef::id, PCLoaderOSM::PCOSMNode::id, PCTypeMap::TypeDef::layer, PCLoaderOSM::PCOSMNode::myAttributes, PCTypeMap::TypeDef::prefix, SUMOReal, and toString().
Referenced by loadIfSet().
int PCLoaderOSM::addPolygon (const PCOSMEdge * edge, const PositionVector & vec, const PCTypeMap::TypeDef & def, const std::string & fullType, int index, bool useName, PCPolyContainer & toFill, bool ignorePruning, bool withAttributes) static protected
try add the polygon and return the next index on success
Definition at line 240 of file PCLoaderOSM.cpp.
References PCPolyContainer::add(), Parameterised::addParameter(), PCTypeMap::TypeDef::allowFill, PCTypeMap::TypeDef::color, PCTypeMap::TypeDef::discard, StringUtils::escapeXML(), OptionsCont::getOptions(), PCTypeMap::TypeDef::id, PCLoaderOSM::PCOSMEdge::id, PCTypeMap::TypeDef::layer, PCLoaderOSM::PCOSMEdge::myAttributes, PCLoaderOSM::PCOSMEdge::name, PCTypeMap::TypeDef::prefix, SUMOReal, and toString().
Referenced by loadIfSet().
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 192 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 175 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 211 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), MSRouteHandler::myStartElement(), and MSRouteHandler::parseWalkPos().
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 217 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), MSStateHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
std::set< std::string > PCLoaderOSM::initMyKeysToInclude () static private
Definition at line 69 of file PCLoaderOSM.cpp.
void PCLoaderOSM::loadIfSet (OptionsCont & oc, PCPolyContainer & toFill, PCTypeMap & tm) static
Loads pois/polygons assumed to be stored as OSM-XML.
If the option "osm-files" is set within the given options container, an instance of PCLoaderOSM is built and used as a handler for the files given in this option.
Parameters
[in] oc The options container to get further options from
[in] toFill The poly/pois container to add loaded polys/pois to
[in] tm The type map to use for setting values of loaded polys/pois
Exceptions
ProcessError if something fails
Definition at line 98 of file PCLoaderOSM.cpp.
References addPOI(), addPolygon(), PCTypeMap::TypeDef::discard, PCTypeMap::get(), OptionsCont::getBool(), PCTypeMap::getDefault(), MsgHandler::getErrorInstance(), OptionsCont::getOptions(), GeoConvHelper::getProcessing(), OptionsCont::getStringVector(), MsgHandler::getWarningInstance(), PCTypeMap::has(), PCLoaderOSM::PCOSMNode::id, PCLoaderOSM::PCOSMEdge::id, OptionsCont::isInStringVector(), FileHelpers::isReadable(), OptionsCont::isSet(), PCLoaderOSM::PCOSMNode::lat, PCLoaderOSM::PCOSMNode::lon, PCLoaderOSM::PCOSMNode::myAttributes, PCLoaderOSM::PCOSMEdge::myAttributes, PCLoaderOSM::PCOSMEdge::myCurrentNodes, MyKeysToInclude, PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, PositionVector::push_back_noDoublePos(), XMLSubSys::runParser(), toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by main().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 227 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void GenericSAXHandler::myEndElement (int element) protected virtual inherited
Callback method for a closing tag to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The closed element, given as a int ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_OpenDrive, NIImporter_OpenStreetMap::RelationHandler, NIImporter_Vissim::NIVissimXMLHandler_Routenentscheidungsdefinition, NIImporter_Vissim::NIVissimXMLHandler_Geschwindigkeitsverteilungsdefinition, NIImporter_OpenStreetMap::EdgesHandler, PCLoaderOSM::EdgesHandler, NIImporter_Vissim::NIVissimXMLHandler_VWunschentscheidungsdefinition, NIImporter_OpenStreetMap::NodesHandler, NIImporter_Vissim::NIVissimXMLHandler_Fahrzeugklassendefinition, PCLoaderOSM::RelationsHandler, MSTriggeredRerouter, SAXWeightsHandler, PCLoaderOSM::NodesHandler, NLHandler, NIImporter_ITSUMO::Handler, MSLaneSpeedTrigger, NIImporter_SUMO, NIImporter_Vissim::NIVissimXMLHandler_Streckendefinition, NIXMLEdgesHandler, MSCalibrator, SUMORouteHandler, RORouteHandler, ODDistrictHandler, MSRouteHandler, RONetHandler, MSStateHandler, NIXMLTrafficLightsHandler, GUITriggeredRerouter, GNEPoly::GNEPolyHandler, and ROMARouteHandler.
Definition at line 231 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement(), NLHandler::networkVersion(), and SUMOSAXReader::parseNext().
void GenericSAXHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual inherited
Callback method for an opening tag to implement by derived classes.
Called by "startElement" (see there).
Parameters
[in] element The element that contains the characters, given as a int
[in] attrs The SAX-attributes, wrapped as SUMOSAXAttributes ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_OpenDrive, NIImporter_Vissim::NIVissimXMLHandler_ConflictArea, NIImporter_OpenStreetMap::RelationHandler, NIImporter_Vissim::NIVissimXMLHandler_Routenentscheidungsdefinition, NIImporter_Vissim::NIVissimXMLHandler_Geschwindigkeitsverteilungsdefinition, NIImporter_OpenStreetMap::EdgesHandler, PCLoaderOSM::EdgesHandler, NIImporter_Vissim::NIVissimXMLHandler_VWunschentscheidungsdefinition, NIImporter_OpenStreetMap::NodesHandler, NIImporter_Vissim::NIVissimXMLHandler_Fahrzeugklassendefinition, PCLoaderOSM::RelationsHandler, NIImporter_Vissim::NIVissimXMLHandler_Parkplatzdefinition, MSTriggeredRerouter, SAXWeightsHandler, NIImporter_Vissim::NIVissimXMLHandler_Zuflussdefinition, PCLoaderOSM::NodesHandler, NIImporter_MATSim::EdgesHandler, NLHandler, NIImporter_Vissim::NIVissimXMLHandler_Streckendefinition, MSLaneSpeedTrigger, NIImporter_SUMO, NIImporter_MATSim::NodesHandler, NIImporter_ITSUMO::Handler, PCLoaderXML, NIXMLEdgesHandler, NIXMLNodesHandler, TrajectoriesHandler, MSCalibrator, PCNetProjectionLoader, ShapeHandler, SUMORouteHandler, RORouteHandler, ROJTRTurnDefLoader, ODDistrictHandler, MSRouteHandler, RONetHandler, NIXMLConnectionsHandler, NIXMLTypesHandler, ODAmitranHandler, MSStateHandler, NIXMLTrafficLightsHandler, PCTypeDefHandler, AGActivityGenHandler, GNEAdditionalHandler, GNEPoly::GNEPolyHandler, GUISettingsHandler, ROMARouteHandler, and RODFDetectorHandler.
Definition at line 223 of file GenericSAXHandler.cpp.
Referenced by SUMOSAXReader::parseNext(), and GenericSAXHandler::startElement().
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 167 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 205 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
const std::set< std::string > PCLoaderOSM::MyKeysToInclude static protected
Definition at line 132 of file PCLoaderOSM.h.
Referenced by loadIfSet(), PCLoaderOSM::RelationsHandler::myStartElement(), and PCLoaderOSM::EdgesHandler::myStartElement().
The documentation for this class was generated from the following files:
PCLoaderOSM.h
PCLoaderOSM.cpp