SUMO - Simulation of Urban MObility: ROMAFrame Class Reference
ROMAFrame Class Reference
Sets and checks options for dua-routing.
#include <ROMAFrame.h>
Static Public Member Functions
static bool checkOptions ()
Checks set options from the OptionsCont-singleton for being valid for usage within duarouter.
static void fillOptions ()
Inserts options used by duarouter into the OptionsCont-singleton.
Static Protected Member Functions
static void addAssignmentOptions ()
Inserts dua options used by duarouter into the OptionsCont-singleton.
static void addImportOptions ()
Inserts import options used by duarouter into the OptionsCont-singleton.
Detailed Description
Sets and checks options for dua-routing.
Definition at line 43 of file ROMAFrame.h.
Member Function Documentation
void ROMAFrame::addAssignmentOptions () static protected
Inserts dua options used by duarouter into the OptionsCont-singleton.
Definition at line 209 of file ROMAFrame.cpp.
References OptionsCont::addDescription(), OptionsCont::addSynonyme(), OptionsCont::doRegister(), OptionsCont::getOptions(), and SUMOReal.
Referenced by fillOptions().
void ROMAFrame::addImportOptions () static protected
Inserts import options used by duarouter into the OptionsCont-singleton.
Definition at line 79 of file ROMAFrame.cpp.
References OptionsCont::addDescription(), OptionsCont::addSynonyme(), OptionsCont::doRegister(), OptionsCont::getOptions(), and SUMOTIME_MAXSTRING.
Referenced by fillOptions().
bool ROMAFrame::checkOptions () static
Checks set options from the OptionsCont-singleton for being valid for usage within duarouter.
Currently, this is done via a call to "ROFrame::checkOptions".
Returns
Whether all needed options are set
Todo:
probably, more things should be checked...
Definition at line 296 of file ROMAFrame.cpp.
References OptionsCont::getOptions(), OptionsCont::getString(), OptionsCont::isSet(), and WRITE_ERROR.
Referenced by main().
void ROMAFrame::fillOptions () static
Inserts options used by duarouter into the OptionsCont-singleton.
As duarouter shares several options with other routing appplications, the insertion of these is done via a call to ROFrame::fillOptions.
duarouter-specific options are added afterwards via calls to "addImportOptions" and "addDUAOptions".
Definition at line 57 of file ROMAFrame.cpp.
References addAssignmentOptions(), OptionsCont::addCallExample(), SystemFrame::addConfigurationOptions(), addImportOptions(), OptionsCont::addOptionSubTopic(), SystemFrame::addReportOptions(), OptionsCont::getOptions(), and RandHelper::insertRandOptions().
Referenced by main().
The documentation for this class was generated from the following files:
ROMAFrame.h
ROMAFrame.cpp