SUMO - Simulation of Urban MObility: MSSOTLPolicy Class Reference
MSSOTLPolicy Class Reference abstract
Class for a low-level policy.
#include <MSSOTLPolicy.h>
Public Member Functions
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
virtual bool canRelease (SUMOTime elapsed, bool thresholdPassed, bool pushButtonPressed, const MSPhaseDefinition *stage, int vehicleCount)=0
void clearParameter ()
Clears the parameter map.
SUMOReal computeDesirability (SUMOReal vehInMeasure, SUMOReal vehOutMeasure, SUMOReal vehInDispersionMeasure, SUMOReal vehOutDispersionMeasure)
Computes the desirability of this policy, necessary when used in combination with an high level policy.
SUMOReal computeDesirability (SUMOReal vehInMeasure, SUMOReal vehOutMeasure)
virtual int decideNextPhase (SUMOTime elapsed, const MSPhaseDefinition *stage, int currentPhaseIndex, int phaseMaxCTS, bool thresholdPassed, bool pushButtonPressed, int vehicleCount)
MSSOTLPolicyDesirability * getDesirabilityAlgorithm ()
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
std::string getName ()
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
virtual SUMOReal getThetaSensitivity ()
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
MSSOTLPolicy (std::string name, const std::map< std::string, std::string > &parameters)
Simple constructor.
MSSOTLPolicy (std::string name, MSSOTLPolicyDesirability *desirabilityAlgorithm)
Constructor when the policy is a low-level policy used by an high level policy.
MSSOTLPolicy (std::string name, MSSOTLPolicyDesirability *desirabilityAlgorithm, const std::map< std::string, std::string > &parameters)
Constructor when the policy is a low-level policy used by an high level policy.
virtual void setThetaSensitivity (SUMOReal val)
virtual ~MSSOTLPolicy ()
Protected Member Functions
virtual void init ()
Private Attributes
MSSOTLPolicyDesirability * myDesirabilityAlgorithm
A pointer to the policy desirability object.'s an optional component related to the computeDesirability() method and it's necessary only when the policy is used in combination with an high level policy.
std::string myName
The name of the policy.
SUMOReal theta_sensitivity
The sensitivity of this policy.
Detailed Description
Class for a low-level policy.
Definition at line 72 of file MSSOTLPolicy.h.
Constructor & Destructor Documentation
MSSOTLPolicy::MSSOTLPolicy (std::string name, const std::map< std::string, std::string > & parameters)
Simple constructor.
Parameters
[in] name The name of the policy
[in] parameters Parameters defined for the policy
Definition at line 82 of file MSSOTLPolicy.cpp.
References theta_sensitivity.
MSSOTLPolicy::MSSOTLPolicy (std::string name, MSSOTLPolicyDesirability * desirabilityAlgorithm)
Constructor when the policy is a low-level policy used by an high level policy.
Parameters
[in] name The name of the policy
[in] desirabilityAlgorithm The desirability algorithm to be used for this policy
Definition at line 88 of file MSSOTLPolicy.cpp.
References theta_sensitivity.
MSSOTLPolicy::MSSOTLPolicy (std::string name, MSSOTLPolicyDesirability * desirabilityAlgorithm, const std::map< std::string, std::string > & parameters)
Constructor when the policy is a low-level policy used by an high level policy.
Parameters
[in] name The name of the policy
[in] desirabilityAlgorithm The desirability algorithm to be used for this policy
[in] parameters Parameters defined for the policy
Definition at line 95 of file MSSOTLPolicy.cpp.
References TplConvert::_2SUMOReal(), Parameterised::getParameter(), and theta_sensitivity.
MSSOTLPolicy::~MSSOTLPolicy (void) virtual
Definition at line 103 of file MSSOTLPolicy.cpp.
Member Function Documentation
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 53 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NBTrafficLightDefinition::compute(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::EdgesHandler::myStartElement(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_TLS::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_Polygon::processSet(), and TraCIServerAPI_Lane::processSet().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 59 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 67 of file Parameterised.cpp.
References Parameterised::myMap.
virtual bool MSSOTLPolicy::canRelease (SUMOTime elapsed, bool thresholdPassed, bool pushButtonPressed, const MSPhaseDefinition * stage, int vehicleCount) pure virtual
Implemented in MSSOTLCongestionPolicy, MSSOTLPlatoonPolicy, MSSOTLMarchingPolicy, MSSOTLPhasePolicy, and MSSOTLRequestPolicy.
Referenced by MSDeterministicHiLevelTrafficLightLogic::canRelease(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSSwarmTrafficLightLogic::canRelease(), and decideNextPhase().
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 91 of file Parameterised.cpp.
References Parameterised::myMap.
SUMOReal MSSOTLPolicy::computeDesirability (SUMOReal vehInMeasure, SUMOReal vehOutMeasure, SUMOReal vehInDispersionMeasure, SUMOReal vehOutDispersionMeasure)
Computes the desirability of this policy, necessary when used in combination with an high level policy.
Definition at line 106 of file MSSOTLPolicy.cpp.
References MSSOTLPolicyDesirability::computeDesirability(), DBG, getName(), myDesirabilityAlgorithm, and WRITE_MESSAGE.
SUMOReal MSSOTLPolicy::computeDesirability (SUMOReal vehInMeasure, SUMOReal vehOutMeasure)
Definition at line 115 of file MSSOTLPolicy.cpp.
References MSSOTLPolicyDesirability::computeDesirability(), DBG, getName(), myDesirabilityAlgorithm, and WRITE_MESSAGE.
int MSSOTLPolicy::decideNextPhase (SUMOTime elapsed, const MSPhaseDefinition * stage, int currentPhaseIndex, int phaseMaxCTS, bool thresholdPassed, bool pushButtonPressed, int vehicleCount) virtual
Reimplemented in MSSOTLCongestionPolicy.
Definition at line 124 of file MSSOTLPolicy.cpp.
References canRelease(), DBG, MSPhaseDefinition::isCommit(), MSPhaseDefinition::isDecisional(), MSPhaseDefinition::isTransient(), time2string(), and WRITE_MESSAGE.
Referenced by MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), and MSSwarmTrafficLightLogic::decideNextPhase().
MSSOTLPolicyDesirability* MSSOTLPolicy::getDesirabilityAlgorithm () inline
Definition at line 128 of file MSSOTLPolicy.h.
References SUMOReal.
Referenced by MSSOTLCongestionPolicy::MSSOTLCongestionPolicy(), MSSOTLMarchingPolicy::MSSOTLMarchingPolicy(), MSSOTLPhasePolicy::MSSOTLPhasePolicy(), MSSOTLPlatoonPolicy::MSSOTLPlatoonPolicy(), MSSOTLRequestPolicy::MSSOTLRequestPolicy(), and MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic().
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 107 of file Parameterised.h.
References Parameterised::myMap.
Referenced by NBTrafficLightDefinition::compute(), MSDevice_Vehroutes::generateOutput(), GUIPerson::getParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), TraCIServerAPI_TLS::processGet(), ROVehicle::saveAsXML(), ROPerson::saveAsXML(), SUMOVTypeParameter::write(), PointOfInterest::writeXML(), and SUMO::Polygon::writeXML().
std::string MSSOTLPolicy::getName () inline
Definition at line 125 of file MSSOTLPolicy.h.
Referenced by MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), computeDesirability(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), and MSSwarmTrafficLightLogic::updateSensitivities().
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 81 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), MSSOTLPolicyDesirability::readParameter(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), and TraCIServerAPI_Vehicle::vtdMap().
virtual SUMOReal MSSOTLPolicy::getThetaSensitivity () inline virtual
Definition at line 119 of file MSSOTLPolicy.h.
Referenced by MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), and MSSwarmTrafficLightLogic::updateSensitivities().
virtual void MSSOTLPolicy::init () inline protected virtual
Reimplemented in MSSOTLPlatoonPolicy, MSSOTLMarchingPolicy, and MSSOTLPhasePolicy.
Definition at line 90 of file MSSOTLPolicy.h.
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 75 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), and MSDevice::equippedByDefaultAssignmentOptions().
virtual void MSSOTLPolicy::setThetaSensitivity (SUMOReal val) inline virtual
Definition at line 122 of file MSSOTLPolicy.h.
Referenced by MSSwarmTrafficLightLogic::updateSensitivities().
Field Documentation
MSSOTLPolicyDesirability* MSSOTLPolicy::myDesirabilityAlgorithm private
A pointer to the policy desirability object.'s an optional component related to the computeDesirability() method and it's necessary only when the policy is used in combination with an high level policy.
Definition at line 87 of file MSSOTLPolicy.h.
Referenced by computeDesirability().
std::string MSSOTLPolicy::myName private
The name of the policy.
Definition at line 82 of file MSSOTLPolicy.h.
SUMOReal MSSOTLPolicy::theta_sensitivity private
The sensitivity of this policy.
Definition at line 78 of file MSSOTLPolicy.h.
Referenced by MSSOTLPolicy().
The documentation for this class was generated from the following files:
MSSOTLPolicy.h
MSSOTLPolicy.cpp