SUMO - Simulation of Urban MObility: GNEAdditionalFrame::additionalParameters Class Reference
GNEAdditionalFrame::additionalParameters Class Reference
#include <GNEAdditionalFrame.h>
Public Member Functions
void addAttribute (SumoXMLTag additional, SumoXMLAttr attribute)
add attribute
additionalParameters (FXComposite *parent, FXObject *tgt)
FOX-declaration.
void clearAttributes ()
clear attributes
std::map< SumoXMLAttr, std::string > getAttributes () const
get attributes
int getNumberOfAddedAttributes () const
get number of added attributes
void hideAdditionalParameters ()
hide group box
void showAdditionalParameters ()
show group box
~additionalParameters ()
destructor
FOX-callbacks
Called when help button is pressed
long onCmdHelp (FXObject *, FXSelector, void *)
Protected Member Functions
additionalParameters ()
FOX needs this.
Private Attributes
FXButton * helpAdditional
button for help
int maxNumberOfListParameters
max number of parameters (Defined in constructor)
int maxNumberOfParameters
max number of parameters (Defined in constructor)
SumoXMLTag myAdditional
current additional
int myIndexParameter
Index for myVectorOfAdditionalParameter.
int myIndexParameterList
index for myIndexParameterList
std::vector< additionalParameter * > myVectorOfAdditionalParameter
vector with the additional parameters
std::vector< additionalParameterList * > myVectorOfAdditionalParameterList
vector with the additional parameters of type list
Detailed Description
Definition at line 180 of file GNEAdditionalFrame.h.
Constructor & Destructor Documentation
GNEAdditionalFrame::additionalParameters::additionalParameters (FXComposite * parent, FXObject * tgt)
FOX-declaration.
constructor
Definition at line 726 of file GNEAdditionalFrame.cpp.
References helpAdditional, maxNumberOfListParameters, maxNumberOfParameters, MID_HELP, myVectorOfAdditionalParameter, and myVectorOfAdditionalParameterList.
GNEAdditionalFrame::additionalParameters::~additionalParameters ()
destructor
Definition at line 748 of file GNEAdditionalFrame.cpp.
GNEAdditionalFrame::additionalParameters::additionalParameters () inline protected
FOX needs this.
Definition at line 217 of file GNEAdditionalFrame.h.
Member Function Documentation
void GNEAdditionalFrame::additionalParameters::addAttribute (SumoXMLTag additional, SumoXMLAttr attribute)
add attribute
Definition at line 771 of file GNEAdditionalFrame.cpp.
References GNEAttributeCarrier::getDefaultValue(), GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isList(), GNEAttributeCarrier::isString(), maxNumberOfListParameters, maxNumberOfParameters, myAdditional, myIndexParameter, myIndexParameterList, myVectorOfAdditionalParameter, myVectorOfAdditionalParameterList, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by GNEAdditionalFrame::setParametersOfAdditional().
void GNEAdditionalFrame::additionalParameters::clearAttributes ()
clear attributes
Definition at line 753 of file GNEAdditionalFrame.cpp.
References maxNumberOfListParameters, maxNumberOfParameters, myIndexParameter, myIndexParameterList, myVectorOfAdditionalParameter, and myVectorOfAdditionalParameterList.
Referenced by GNEAdditionalFrame::setParametersOfAdditional().
std::map< SumoXMLAttr, std::string > GNEAdditionalFrame::additionalParameters::getAttributes () const
get attributes
Definition at line 830 of file GNEAdditionalFrame.cpp.
References myIndexParameter, myIndexParameterList, myVectorOfAdditionalParameter, and myVectorOfAdditionalParameterList.
Referenced by GNEAdditionalFrame::addAdditional().
int GNEAdditionalFrame::additionalParameters::getNumberOfAddedAttributes () const
get number of added attributes
Definition at line 845 of file GNEAdditionalFrame.cpp.
References myIndexParameter, and myIndexParameterList.
Referenced by GNEAdditionalFrame::setParametersOfAdditional().
void GNEAdditionalFrame::additionalParameters::hideAdditionalParameters ()
hide group box
Definition at line 824 of file GNEAdditionalFrame.cpp.
References GNEAdditionalFrame::hide().
Referenced by GNEAdditionalFrame::setParametersOfAdditional().
long GNEAdditionalFrame::additionalParameters::onCmdHelp (FXObject * , FXSelector , void *)
Definition at line 851 of file GNEAdditionalFrame.cpp.
References GNEAttributeCarrier::getDefinition(), GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isFloat(), GNEAttributeCarrier::isInt(), GNEAttributeCarrier::isString(), MID_TABLE, myAdditional, myIndexParameter, myIndexParameterList, myVectorOfAdditionalParameter, myVectorOfAdditionalParameterList, and toString().
void GNEAdditionalFrame::additionalParameters::showAdditionalParameters ()
show group box
Definition at line 817 of file GNEAdditionalFrame.cpp.
References GNEAdditionalFrame::show().
Referenced by GNEAdditionalFrame::setParametersOfAdditional().
Field Documentation
FXButton* GNEAdditionalFrame::additionalParameters::helpAdditional private
button for help
Definition at line 242 of file GNEAdditionalFrame.h.
Referenced by additionalParameters().
int GNEAdditionalFrame::additionalParameters::maxNumberOfListParameters private
max number of parameters (Defined in constructor)
Definition at line 239 of file GNEAdditionalFrame.h.
Referenced by addAttribute(), additionalParameters(), and clearAttributes().
int GNEAdditionalFrame::additionalParameters::maxNumberOfParameters private
max number of parameters (Defined in constructor)
Definition at line 236 of file GNEAdditionalFrame.h.
Referenced by addAttribute(), additionalParameters(), and clearAttributes().
SumoXMLTag GNEAdditionalFrame::additionalParameters::myAdditional private
current additional
Definition at line 221 of file GNEAdditionalFrame.h.
Referenced by addAttribute(), and onCmdHelp().
int GNEAdditionalFrame::additionalParameters::myIndexParameter private
Index for myVectorOfAdditionalParameter.
Definition at line 227 of file GNEAdditionalFrame.h.
Referenced by addAttribute(), clearAttributes(), getAttributes(), getNumberOfAddedAttributes(), and onCmdHelp().
int GNEAdditionalFrame::additionalParameters::myIndexParameterList private
index for myIndexParameterList
Definition at line 233 of file GNEAdditionalFrame.h.
Referenced by addAttribute(), clearAttributes(), getAttributes(), getNumberOfAddedAttributes(), and onCmdHelp().
std::vector<additionalParameter*> GNEAdditionalFrame::additionalParameters::myVectorOfAdditionalParameter private
vector with the additional parameters
Definition at line 224 of file GNEAdditionalFrame.h.
Referenced by addAttribute(), additionalParameters(), clearAttributes(), getAttributes(), and onCmdHelp().
std::vector<additionalParameterList*> GNEAdditionalFrame::additionalParameters::myVectorOfAdditionalParameterList private
vector with the additional parameters of type list
Definition at line 230 of file GNEAdditionalFrame.h.
Referenced by addAttribute(), additionalParameters(), clearAttributes(), getAttributes(), and onCmdHelp().
The documentation for this class was generated from the following files:
GNEAdditionalFrame.h
GNEAdditionalFrame.cpp