SUMO - Simulation of Urban MObility: FXThreadMessageRetriever Class Reference
FXThreadMessageRetriever Class Reference
#include <FXThreadMessageRetriever.h>
Public Types
enum {
ID_NONE = 0, ID_DELETE = 6, ID_DISABLE, ID_ENABLE,
ID_SETVALUE = 17, ID_SETINTVALUE, ID_SETREALVALUE, ID_SETSTRINGVALUE,
ID_SETINTRANGE, ID_SETREALRANGE, ID_GETINTVALUE, ID_GETREALVALUE,
ID_GETSTRINGVALUE, ID_XML, ID_META, ID_COMMENT,
ID_DOCUMENT, ID_TAG, ID_CONTENT, ID_LAST
}
Public Member Functions
virtual void create ()
create resource
virtual void destroy ()
destroy resource
virtual void detach ()
detach resource
virtual void disable ()
disable us
virtual void enable ()
enable us
FXThreadMessageRetriever ()
FXApp * getApp ()
application pointer
FXSelector getSelector ()
get the message
FXObject * getTarget ()
get the target
void * getUserData ()
get user data
FXuint getUserDataLen ()
get user daat length
FXbool isEnabled ()
are we enabled?
virtual FXbool isReadonly ()
are we modifiable
virtual void load (FXStream &store)
load object from stream
long onCmdDisable (FXObject *, FXSelector, void *)
long onCmdEnable (FXObject *, FXSelector, void *)
long onUpdate (FXObject *, FXSelector, void *)
virtual void save (FXStream &store) const
save object to stream
virtual void setReadonly (FXbool mode=TRUE)
set modifiable mode
void setSelector (FXSelector sel)
set the selector
void setTarget (FXObject *tgt)
set the target
void setUserData (void *d)
set user data
void setUserDataLen (FXuint len)
set the user data length
~FXThreadMessageRetriever ()
Protected Types
enum {
FLAG_ENABLED = 0x00000002, FLAG_UPDATE = 0x00000004, FLAG_FOCUSED = 0x00000010, FLAG_DIRTY = 0x00000020,
FLAG_RECALC = 0x00000040, FLAG_DEFAULT = 0x00000200, FLAG_INITIAL = 0x00000400, FLAG_ACTIVE = 0x00001000,
FLAG_CHANGED = 0x00010000, FLAG_READONLY = 0x10000000
}
flags defined are the same as those defined in FXWindow, etc.
Protected Attributes
void * data
FXuint datalen
FXuint flags
FXSelector message
FXuint options
FXObject * target
Detailed Description
Definition at line 35 of file FXThreadMessageRetriever.h.
Member Enumeration Documentation
anonymous enum protected inherited
flags defined are the same as those defined in FXWindow, etc.
Enumerator
FLAG_ENABLED
FLAG_UPDATE
FLAG_FOCUSED
FLAG_DIRTY
FLAG_RECALC
FLAG_DEFAULT
FLAG_INITIAL
FLAG_ACTIVE
FLAG_CHANGED
FLAG_READONLY
Definition at line 68 of file FXBaseObject.h.
anonymous enum inherited
Enumerator
ID_NONE
ID_DELETE
ID_DISABLE
ID_ENABLE
ID_SETVALUE
ID_SETINTVALUE
ID_SETREALVALUE
ID_SETSTRINGVALUE
ID_SETINTRANGE
ID_SETREALRANGE
ID_GETINTVALUE
ID_GETREALVALUE
ID_GETSTRINGVALUE
ID_XML
ID_META
ID_COMMENT
ID_DOCUMENT
ID_TAG
ID_CONTENT
ID_LAST
Definition at line 93 of file FXBaseObject.h.
Constructor & Destructor Documentation
FXThreadMessageRetriever::FXThreadMessageRetriever () inline
Definition at line 37 of file FXThreadMessageRetriever.h.
FXThreadMessageRetriever::~FXThreadMessageRetriever () inline
Definition at line 38 of file FXThreadMessageRetriever.h.
Member Function Documentation
virtual void FXEX::FXBaseObject::create () inline virtual inherited
create resource
Definition at line 195 of file FXBaseObject.h.
virtual void FXEX::FXBaseObject::destroy () inline virtual inherited
destroy resource
Definition at line 201 of file FXBaseObject.h.
References load().
virtual void FXEX::FXBaseObject::detach () inline virtual inherited
detach resource
Definition at line 198 of file FXBaseObject.h.
virtual void FXEX::FXBaseObject::disable () inline virtual inherited
disable us
Definition at line 182 of file FXBaseObject.h.
Referenced by FXEX::FXBaseObject::onCmdDisable().
virtual void FXEX::FXBaseObject::enable () inline virtual inherited
enable us
Definition at line 177 of file FXBaseObject.h.
Referenced by FXEX::FXBaseObject::onCmdEnable().
FXApp * FXEX::FXBaseObject::getApp () inherited
application pointer
Definition at line 126 of file FXBaseObject.cpp.
References FXEX::FXBaseObject::app.
FXSelector FXEX::FXBaseObject::getSelector () inline inherited
get the message
Definition at line 142 of file FXBaseObject.h.
FXObject* FXEX::FXBaseObject::getTarget () inline inherited
get the target
Definition at line 132 of file FXBaseObject.h.
void* FXEX::FXBaseObject::getUserData () inline inherited
get user data
Definition at line 152 of file FXBaseObject.h.
FXuint FXEX::FXBaseObject::getUserDataLen () inline inherited
get user daat length
Definition at line 162 of file FXBaseObject.h.
FXbool FXEX::FXBaseObject::isEnabled () inline inherited
are we enabled?
Definition at line 172 of file FXBaseObject.h.
virtual FXbool FXEX::FXBaseObject::isReadonly () inline virtual inherited
are we modifiable
Definition at line 187 of file FXBaseObject.h.
void FXEX::FXBaseObject::load (FXStream & store) virtual inherited
load object from stream
Definition at line 114 of file FXBaseObject.cpp.
References FXEX::FXBaseObject::app, FXEX::FXBaseObject::data, FXEX::FXBaseObject::datalen, FXEX::FXBaseObject::flags, load(), FXEX::FXBaseObject::message, FXEX::FXBaseObject::options, and FXEX::FXBaseObject::target.
long FXEX::FXBaseObject::onCmdDisable (FXObject * , FXSelector , void *) inherited
Definition at line 149 of file FXBaseObject.cpp.
References FXEX::FXBaseObject::disable().
long FXEX::FXBaseObject::onCmdEnable (FXObject * , FXSelector , void *) inherited
Definition at line 143 of file FXBaseObject.cpp.
References FXEX::FXBaseObject::enable().
long FXEX::FXBaseObject::onUpdate (FXObject * sender, FXSelector , void *) inherited
Definition at line 155 of file FXBaseObject.cpp.
References FXEX::FXBaseObject::FLAG_ENABLED, and FXEX::FXBaseObject::flags.
void FXEX::FXBaseObject::save (FXStream & store) const virtual inherited
save object to stream
Definition at line 102 of file FXBaseObject.cpp.
References FXEX::FXBaseObject::app, FXEX::FXBaseObject::data, FXEX::FXBaseObject::datalen, FXEX::FXBaseObject::flags, FXEX::FXBaseObject::message, FXEX::FXBaseObject::options, and FXEX::FXBaseObject::target.
void FXEX::FXBaseObject::setReadonly (FXbool mode = TRUE) virtual inherited
set modifiable mode
Definition at line 134 of file FXBaseObject.cpp.
References FXEX::FXBaseObject::FLAG_READONLY, and FXEX::FXBaseObject::flags.
void FXEX::FXBaseObject::setSelector (FXSelector sel) inline inherited
set the selector
Definition at line 147 of file FXBaseObject.h.
Referenced by GNEApplicationWindow::dependentBuild(), and GUIApplicationWindow::dependentBuild().
void FXEX::FXBaseObject::setTarget (FXObject * tgt) inline inherited
set the target
Definition at line 137 of file FXBaseObject.h.
Referenced by GNEApplicationWindow::dependentBuild(), and GUIApplicationWindow::dependentBuild().
void FXEX::FXBaseObject::setUserData (void * d) inline inherited
set user data
Definition at line 157 of file FXBaseObject.h.
void FXEX::FXBaseObject::setUserDataLen (FXuint len) inline inherited
set the user data length
Definition at line 167 of file FXBaseObject.h.
Field Documentation
void* FXEX::FXBaseObject::data protected inherited
Definition at line 87 of file FXBaseObject.h.
Referenced by FXEX::FXBaseObject::FXBaseObject(), FXEX::FXBaseObject::load(), FXEX::FXBaseObject::save(), and FXEX::FXBaseObject::~FXBaseObject().
FXuint FXEX::FXBaseObject::datalen protected inherited
Definition at line 88 of file FXBaseObject.h.
Referenced by FXEX::FXBaseObject::load(), and FXEX::FXBaseObject::save().
FXuint FXEX::FXBaseObject::flags protected inherited
Definition at line 89 of file FXBaseObject.h.
Referenced by FXEX::FXBaseObject::FXBaseObject(), FXEX::FXBaseObject::load(), FXEX::FXBaseObject::onUpdate(), FXEX::FXBaseObject::save(), and FXEX::FXBaseObject::setReadonly().
FXSelector FXEX::FXBaseObject::message protected inherited
Definition at line 86 of file FXBaseObject.h.
Referenced by FXEX::FXBaseObject::FXBaseObject(), FXEX::FXBaseObject::load(), and FXEX::FXBaseObject::save().
FXuint FXEX::FXBaseObject::options protected inherited
Definition at line 90 of file FXBaseObject.h.
Referenced by FXEX::FXBaseObject::load(), and FXEX::FXBaseObject::save().
FXObject* FXEX::FXBaseObject::target protected inherited
Definition at line 85 of file FXBaseObject.h.
Referenced by FXEX::FXBaseObject::FXBaseObject(), FXEX::FXBaseObject::load(), FXEX::FXBaseObject::save(), and FXEX::FXBaseObject::~FXBaseObject().
The documentation for this class was generated from the following file:
FXThreadMessageRetriever.h