SUMO - Simulation of Urban MObility: PHEMlightdll::CEPHandler Class Reference
PHEMlightdll::CEPHandler Class Reference
#include <CEPHandler.h>
Public Member Functions
CEPHandler ()
CEPHandler ()
bool GetCEP (const std::vector< std::string > &DataPath, Helpers *Helper)
bool GetCEP (string DataPath, Helpers Helper)
const std::map< std::string, CEP * > & getCEPS () const
bool GetFleetCEP (string DataPath, string AggClass, Helpers Helper)
bool ReadFleetShares (string DataPath, Helpers Helper)
Properties
Dictionary< string, CEP > CEPS [get]
Dictionary< string, Dictionary< string, double > > FleetShares [get]
Private Member Functions
bool Load (const std::vector< std::string > &DataPath, Helpers *Helper)
bool Load (string DataPath, Helpers Helper)
bool ReadEmissionData (bool readFC, const std::vector< std::string > &DataPath, const std::string &emissionClass, Helpers *Helper, std::vector< std::string > &header, std::vector< std::vector< double > > &matrix, std::vector< double > &idlingValues)
bool ReadEmissionData (bool readFC, string DataPath, string emissionClass, Helpers Helper, out List< string > header, out List< List< double >> matrix, out List< double > idlingValues)
std::string ReadLine (std::ifstream &s)
string ReadLine (StreamReader s)
bool ReadVehicleFile (const std::vector< std::string > &DataPath, const std::string &emissionClass, Helpers *Helper, double &vehicleMass, double &vehicleLoading, double &vehicleMassRot, double &crossArea, double &cWValue, double &f0, double &f1, double &f2, double &f3, double &f4, double &axleRatio, double &auxPower, double &ratedPower, double &engineIdlingSpeed, double &engineRatedSpeed, double &effectiveWheelDiameter, std::vector< double > &transmissionGearRatios, std::string &vehicleMassType, std::string &vehicleFuelType, double &pNormV0, double &pNormP0, double &pNormV1, double &pNormP1, std::vector< std::vector< double > > &matrixSpeedInertiaTable, std::vector< std::vector< double > > &normedDragTable)
bool ReadVehicleFile (string DataPath, string emissionClass, Helpers Helper, out double vehicleMass, out double vehicleLoading, out double vehicleMassRot, out double crossArea, out double cWValue, out double f0, out double f1, out double f2, out double f3, out double f4, out double axleRatio, out double auxPower, out double ratedPower, out double engineIdlingSpeed, out double engineRatedSpeed, out double effectiveWheelDiameter, out List< double > transmissionGearRatios, out string vehicleMassType, out string vehicleFuelType, out double pNormV0, out double pNormP0, out double pNormV1, out double pNormP1, out List< List< double >> matrixSpeedInertiaTable, out List< List< double >> normedDragTable)
std::vector< std::string > split (const std::string &s, char delim)
List< string > split (string s, char delim)
double todouble (const std::string &s)
double todouble (string s)
std::vector< double > todoubleList (const std::vector< std::string > &s)
List< double > todoubleList (List< string > s)
Private Attributes
std::map< std::string, CEP * > _ceps
Dictionary< string, CEP > _ceps
Dictionary< string, Dictionary< string, double > > _fleetShares
Detailed Description
Definition at line 15 of file CEPHandler.h.
Constructor & Destructor Documentation
PHEMlightdll::CEPHandler::CEPHandler ()
Definition at line 11 of file CEPHandler.cpp.
References _ceps.
PHEMlightdll.CEPHandler.CEPHandler () inline
Definition at line 19 of file CEPHandler.cs.
References _ceps.
Member Function Documentation
bool PHEMlightdll::CEPHandler::GetCEP (const std::vector< std::string > & DataPath, Helpers * Helper)
Definition at line 19 of file CEPHandler.cpp.
References getCEPS(), PHEMlightdll::Helpers::getgClass(), and Load().
Referenced by PHEMlightdll.Start::CALC_Array(), PHEMlightdll.Start::CALC_Single(), and HelpersPHEMlight::getClassByName().
bool PHEMlightdll.CEPHandler.GetCEP (string DataPath, Helpers Helper) inline
Definition at line 58 of file CEPHandler.cs.
References CEPS, PHEMlightdll::Helpers.gClass, and Load().
const std::map< std::string, CEP * > & PHEMlightdll::CEPHandler::getCEPS () const
Definition at line 15 of file CEPHandler.cpp.
References _ceps.
Referenced by GetCEP(), and HelpersPHEMlight::getClassByName().
bool PHEMlightdll.CEPHandler.GetFleetCEP (string DataPath, string AggClass, Helpers Helper) inline
Definition at line 73 of file CEPHandler.cs.
References PHEMlightdll::CEP.AddRangeCeps(), PHEMlightdll::Constants.AGGREGATED_VEHICLECLASSES, CEPS, PHEMlightdll::Helpers.ErrMsg, FleetShares, PHEMlightdll::Helpers.gClass, Load(), and PHEMlightdll::Helpers.setclass().
Referenced by PHEMlightdll.Start.CALC_Array(), and PHEMlightdll.Start.CALC_Single().
bool PHEMlightdll::CEPHandler::Load (const std::vector< std::string > & DataPath, Helpers * Helper) private
Definition at line 28 of file CEPHandler.cpp.
References _ceps, PHEMlightdll::Helpers::getgClass(), PHEMlightdll::Constants::HeavyVehicle, ReadEmissionData(), and ReadVehicleFile().
Referenced by GetCEP(), and GetFleetCEP().
bool PHEMlightdll.CEPHandler.Load (string DataPath, Helpers Helper) inline private
Definition at line 122 of file CEPHandler.cs.
References PHEMlightdll::Helpers.gClass, PHEMlightdll::Constants.HeavyVehicle, ReadEmissionData(), and ReadVehicleFile().
bool PHEMlightdll::CEPHandler::ReadEmissionData (bool readFC, const std::vector< std::string > & DataPath, const std::string & emissionClass, Helpers * Helper, std::vector< std::string > & header, std::vector< std::vector< double > > & matrix, std::vector< double > & idlingValues) private
Definition at line 275 of file CEPHandler.cpp.
References ReadLine(), PHEMlightdll::Helpers::setErrMsg(), split(), and todoubleList().
Referenced by Load().
bool PHEMlightdll.CEPHandler.ReadEmissionData (bool readFC, string DataPath, string emissionClass, Helpers Helper, out List< string > header, out List< List< double >> matrix, out List< double > idlingValues) inline private
Definition at line 431 of file CEPHandler.cs.
References PHEMlightdll::Helpers.ErrMsg, ReadLine(), split(), and todoubleList().
bool PHEMlightdll.CEPHandler.ReadFleetShares (string DataPath, Helpers Helper) inline
Definition at line 493 of file CEPHandler.cs.
References PHEMlightdll::Helpers.CommentPrefix, PHEMlightdll::Helpers.ErrMsg, FleetShares, ReadLine(), split(), and todouble().
Referenced by PHEMlightdll.Start.CALC_Array(), and PHEMlightdll.Start.CALC_Single().
std::string PHEMlightdll::CEPHandler::ReadLine (std::ifstream & s) private
Definition at line 353 of file CEPHandler.cpp.
Referenced by ReadEmissionData(), ReadFleetShares(), and ReadVehicleFile().
string PHEMlightdll.CEPHandler.ReadLine (StreamReader s) inline private
Definition at line 552 of file CEPHandler.cs.
bool PHEMlightdll::CEPHandler::ReadVehicleFile (const std::vector< std::string > & DataPath, const std::string & emissionClass, Helpers * Helper, double & vehicleMass, double & vehicleLoading, double & vehicleMassRot, double & crossArea, double & cWValue, double & f0, double & f1, double & f2, double & f3, double & f4, double & axleRatio, double & auxPower, double & ratedPower, double & engineIdlingSpeed, double & engineRatedSpeed, double & effectiveWheelDiameter, std::vector< double > & transmissionGearRatios, std::string & vehicleMassType, std::string & vehicleFuelType, double & pNormV0, double & pNormP0, double & pNormV1, double & pNormP1, std::vector< std::vector< double > > & matrixSpeedInertiaTable, std::vector< std::vector< double > > & normedDragTable) private
Definition at line 85 of file CEPHandler.cpp.
References PHEMlightdll::Helpers::getCommentPrefix(), ReadLine(), PHEMlightdll::Helpers::setErrMsg(), split(), todouble(), and todoubleList().
Referenced by Load().
bool PHEMlightdll.CEPHandler.ReadVehicleFile (string DataPath, string emissionClass, Helpers Helper, out double vehicleMass, out double vehicleLoading, out double vehicleMassRot, out double crossArea, out double cWValue, out double f0, out double f1, out double f2, out double f3, out double f4, out double axleRatio, out double auxPower, out double ratedPower, out double engineIdlingSpeed, out double engineRatedSpeed, out double effectiveWheelDiameter, out List< double > transmissionGearRatios, out string vehicleMassType, out string vehicleFuelType, out double pNormV0, out double pNormP0, out double pNormV1, out double pNormP1, out List< List< double >> matrixSpeedInertiaTable, out List< List< double >> normedDragTable) inline private
Definition at line 234 of file CEPHandler.cs.
References PHEMlightdll::Helpers.CommentPrefix, PHEMlightdll::Helpers.ErrMsg, ReadLine(), split(), todouble(), and todoubleList().
std::vector< std::string > PHEMlightdll::CEPHandler::split (const std::string & s, char delim) private
Definition at line 328 of file CEPHandler.cpp.
Referenced by ReadEmissionData(), ReadFleetShares(), and ReadVehicleFile().
List<string> PHEMlightdll.CEPHandler.split (string s, char delim) inline private
Definition at line 534 of file CEPHandler.cs.
double PHEMlightdll::CEPHandler::todouble (const std::string & s) private
Definition at line 338 of file CEPHandler.cpp.
Referenced by ReadFleetShares(), ReadVehicleFile(), and todoubleList().
double PHEMlightdll.CEPHandler.todouble (string s) inline private
Definition at line 540 of file CEPHandler.cs.
std::vector< double > PHEMlightdll::CEPHandler::todoubleList (const std::vector< std::string > & s) private
Definition at line 345 of file CEPHandler.cpp.
References todouble().
Referenced by ReadEmissionData(), and ReadVehicleFile().
List<double> PHEMlightdll.CEPHandler.todoubleList (List< string > s) inline private
Definition at line 546 of file CEPHandler.cs.
References todouble().
Field Documentation
std::map<std::string, CEP*> PHEMlightdll::CEPHandler::_ceps private
Definition at line 28 of file CEPHandler.h.
Referenced by CEPHandler(), getCEPS(), and Load().
Dictionary<string, CEP> PHEMlightdll.CEPHandler._ceps private
Definition at line 30 of file CEPHandler.cs.
Dictionary<string, Dictionary<string, double> > PHEMlightdll.CEPHandler._fleetShares private
Definition at line 42 of file CEPHandler.cs.
Property Documentation
Dictionary<string, CEP> PHEMlightdll.CEPHandler.CEPS get
Definition at line 32 of file CEPHandler.cs.
Referenced by PHEMlightdll.Start.CALC_Array(), PHEMlightdll.Start.CALC_Single(), GetCEP(), and GetFleetCEP().
Dictionary<string, Dictionary<string, double> > PHEMlightdll.CEPHandler.FleetShares get
Definition at line 44 of file CEPHandler.cs.
Referenced by GetFleetCEP(), and ReadFleetShares().
The documentation for this class was generated from the following files:
CEPHandler.h
CEPHandler.cs
CEPHandler.cpp