SUMO - Simulation of Urban MObility: NWFrame Class Reference
NWFrame Class Reference
Sets and checks options for netwrite; saves the network.
#include <NWFrame.h>
Static Public Member Functions
static bool checkOptions ()
Checks set options from the OptionsCont-singleton for being valid.
static void fillOptions (bool forNetgen)
Inserts options used by the network writer.
static void writeNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Writes the network stored in the given net builder.
static void writePositionLong (const Position &pos, OutputDevice &dev)
Writes the given position to device in long format (one attribute per dimension)
Static Public Attributes
static const std::string MAJOR_VERSION = "version=\"0.27\""
The version number for written files.
Detailed Description
Sets and checks options for netwrite; saves the network.
Definition at line 52 of file NWFrame.h.
Member Function Documentation
bool NWFrame::checkOptions () static
Checks set options from the OptionsCont-singleton for being valid.
Returns
Whether needed options are set and have proper values
Definition at line 111 of file NWFrame.cpp.
References OptionsCont::getBool(), FileHelpers::getConfigurationRelative(), OptionsCont::getOptions(), OptionsCont::getString(), OptionsCont::isSet(), OptionsCont::setDefault(), and WRITE_ERROR.
Referenced by checkOptions(), and GNELoadThread::run().
void NWFrame::fillOptions (bool forNetgen) static
Inserts options used by the network writer.
Definition at line 63 of file NWFrame.cpp.
References OptionsCont::addDescription(), OptionsCont::addSynonyme(), OptionsCont::doRegister(), and OptionsCont::getOptions().
Referenced by fillOptions(), and GNELoadThread::fillOptions().
void NWFrame::writeNetwork (const OptionsCont & oc, NBNetBuilder & nb) static
Writes the network stored in the given net builder.
Definition at line 137 of file NWFrame.cpp.
References SysUtils::getCurrentMillis(), PROGRESS_BEGIN_MESSAGE, PROGRESS_TIME_MESSAGE, NWWriter_Amitran::writeNetwork(), NWWriter_OpenDrive::writeNetwork(), NWWriter_MATSim::writeNetwork(), NWWriter_DlrNavteq::writeNetwork(), NWWriter_XML::writeNetwork(), and NWWriter_SUMO::writeNetwork().
Referenced by main(), and GNENet::save().
void NWFrame::writePositionLong (const Position & pos, OutputDevice & dev) static
Writes the given position to device in long format (one attribute per dimension)
Definition at line 151 of file NWFrame.cpp.
References SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_ATTR_Z, OutputDevice::writeAttr(), Position::x(), Position::y(), and Position::z().
Referenced by NWWriter_SUMO::writeInternalNodes(), NWWriter_SUMO::writeJunction(), and NWWriter_XML::writeNodes().
Field Documentation
const std::string NWFrame::MAJOR_VERSION = "version=\"0.27\"" static
The version number for written files.
Definition at line 69 of file NWFrame.h.
Referenced by NWWriter_XML::writeEdgesAndConnections(), NWWriter_XML::writeJoinedJunctions(), NWWriter_SUMO::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_XML::writeTrafficLights(), and NWWriter_XML::writeTypes().
The documentation for this class was generated from the following files:
NWFrame.h
NWFrame.cpp