SUMO - Simulation of Urban MObility: EulerSpiralLookupTable Class Reference
EulerSpiralLookupTable Class Reference
#include <euler.h>
Public Member Functions
double dt ()
EulerSpiralLookupTable ()
double gamma (double start_angle, double end_angle)
double k0 (double start_angle, double end_angle)
double k1 (double start_angle, double end_angle)
double L (double start_angle, double end_angle)
double theta (int N)
~EulerSpiralLookupTable ()
Static Public Member Functions
static EulerSpiralLookupTable * get_globalEulerSpiralLookupTable ()
Private Attributes
double _dt
double * _theta
double ** ES_gamma
double ** ES_k0
double ** ES_k1
double ** ES_L
Detailed Description
Definition at line 111 of file euler.h.
Constructor & Destructor Documentation
EulerSpiralLookupTable::EulerSpiralLookupTable ()
Definition at line 29 of file euler.cpp.
Referenced by get_globalEulerSpiralLookupTable().
EulerSpiralLookupTable::~EulerSpiralLookupTable ()
Definition at line 33 of file euler.cpp.
Member Function Documentation
double EulerSpiralLookupTable::dt ()
Definition at line 38 of file euler.cpp.
References _dt.
double EulerSpiralLookupTable::gamma (double start_angle, double end_angle)
Definition at line 114 of file euler.cpp.
References _dt, _theta, ES_gamma, and M_PI.
Referenced by EulerSpiral::compute_error().
EulerSpiralLookupTable * EulerSpiralLookupTable::get_globalEulerSpiralLookupTable () static
Definition at line 21 of file euler.cpp.
References EulerSpiralLookupTable(), and globalEulerSpiralLookupTable.
double EulerSpiralLookupTable::k0 (double start_angle, double end_angle)
Definition at line 48 of file euler.cpp.
References _dt, _theta, ES_k0, and M_PI.
Referenced by EulerSpiral::compute_end_pt(), and EulerSpiral::compute_es_params().
double EulerSpiralLookupTable::k1 (double start_angle, double end_angle)
Definition at line 80 of file euler.cpp.
References _dt, _theta, ES_k1, and M_PI.
double EulerSpiralLookupTable::L (double start_angle, double end_angle)
Definition at line 148 of file euler.cpp.
References _dt, _theta, ES_L, and M_PI.
Referenced by EulerSpiral::compute_error(), and EulerSpiral::compute_es_params().
double EulerSpiralLookupTable::theta (int N)
Definition at line 43 of file euler.cpp.
References _theta.
Referenced by EulerSpiral::compute_end_pt().
Field Documentation
double EulerSpiralLookupTable::_dt private
Definition at line 117 of file euler.h.
Referenced by dt(), gamma(), k0(), k1(), and L().
double* EulerSpiralLookupTable::_theta private
Definition at line 116 of file euler.h.
Referenced by gamma(), k0(), k1(), L(), and theta().
double** EulerSpiralLookupTable::ES_gamma private
Definition at line 122 of file euler.h.
Referenced by gamma().
double** EulerSpiralLookupTable::ES_k0 private
Definition at line 120 of file euler.h.
Referenced by k0().
double** EulerSpiralLookupTable::ES_k1 private
Definition at line 121 of file euler.h.
Referenced by k1().
double** EulerSpiralLookupTable::ES_L private
Definition at line 123 of file euler.h.
Referenced by L().
The documentation for this class was generated from the following files:
euler.h
euler.cpp