SUMO - Simulation of Urban MObility: NIImporter_DlrNavteq Class Reference
NIImporter_DlrNavteq Class Reference
Importer for networks stored in Elmar's format.
#include <NIImporter_DlrNavteq.h>
Data Structures
class EdgesHandler
Importer of edges stored in unsplit elmar format.
class NamesHandler
Importer of street names in DLRNavteq's (aka elmar) format.
class NodesHandler
Importer of nodes stored in unsplit elmar format.
class TrafficlightsHandler
Importer of traffic lights stored in DLRNavteq's (aka elmar) format.
Static Public Member Functions
static void loadNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Loads content of the optionally given dlr-navteq (aka Elmar-fomat) folder.
Static Public Attributes
static const int GEO_SCALE = 5
scaling factor for geo coordinates (DLRNavteq format uses this to increase floating point precisions)
Detailed Description
Importer for networks stored in Elmar's format.
Definition at line 62 of file NIImporter_DlrNavteq.h.
Member Function Documentation
void NIImporter_DlrNavteq::loadNetwork (const OptionsCont & oc, NBNetBuilder & nb) static
Loads content of the optionally given dlr-navteq (aka Elmar-fomat) folder.
If the option "dlr-navteq-prefix" is set, the file(s) stored therein is read and the network definition stored therein is stored within the given network builder.
If the option "dlr-navteq-prefix" is not set, this method simply returns.
Parameters
[in] oc The options to use
[in] nb The network builder to fill
Definition at line 74 of file NIImporter_DlrNavteq.cpp.
References OptionsCont::getBool(), NBNetBuilder::getEdgeCont(), NBNetBuilder::getNodeCont(), OptionsCont::getString(), NBNetBuilder::getTLLogicCont(), OptionsCont::isSet(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, LineReader::readAll(), NBEdgeCont::recheckLaneSpread(), LineReader::setFile(), and WRITE_WARNING.
Referenced by NILoader::load().
Field Documentation
const int NIImporter_DlrNavteq::GEO_SCALE = 5 static
scaling factor for geo coordinates (DLRNavteq format uses this to increase floating point precisions)
Definition at line 78 of file NIImporter_DlrNavteq.h.
Referenced by NIFrame::checkOptions().
The documentation for this class was generated from the following files:
NIImporter_DlrNavteq.h
NIImporter_DlrNavteq.cpp