SUMO - Simulation of Urban MObility: PCLoaderXML Class Reference
PCLoaderXML Class Reference
A reader for polygons and pois stored in XML-format.
#include <PCLoaderXML.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
Position getLanePos (const std::string &poiID, const std::string &laneID, SUMOReal lanePos)
get position for a given laneID
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Static Public Member Functions
static bool loadFiles (const std::vector< std::string > &files, ShapeHandler &sh)
loads all of the given files
static void loadIfSet (OptionsCont &oc, PCPolyContainer &toFill, PCTypeMap &tm)
Loads pois/polygons assumed to be stored as XML.
Protected Member Functions
void addPOI (const SUMOSAXAttributes &attrs, const bool ignorePruning, const bool useProcessing)
adds a POI
void addPoly (const SUMOSAXAttributes &attrs, const bool ignorePruning, const bool useProcessing)
adds a polygon
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
virtual void myEndElement (int element)
Callback method for a closing tag to implement by derived classes.
PCLoaderXML (PCPolyContainer &toFill, PCTypeMap &tm, OptionsCont &oc)
Constructor.
void setDefaults (const std::string &prefix, const RGBColor &color, const SUMOReal layer, const bool fill=false)
~PCLoaderXML ()
Destructor.
inherited from GenericSAXHandler
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
Protected Attributes
ShapeContainer & myShapeContainer
Private Attributes
OptionsCont & myOptions
Settings to use.
PCTypeMap & myTypeMap
The type map to use.
Detailed Description
A reader for polygons and pois stored in XML-format.
Reads pois stored as XML definition. The definitions must match the format POLYCONVERT generates.
Definition at line 58 of file PCLoaderXML.h.
Constructor & Destructor Documentation
PCLoaderXML::PCLoaderXML (PCPolyContainer & toFill, PCTypeMap & tm, OptionsCont & oc) protected
Constructor.
Parameters
[in] toFill The poly/pois container to add loaded polys/pois to
[in] tm The type map to use for setting values of loaded polys/pois
[in] oc The options container to get further options from
Definition at line 90 of file PCLoaderXML.cpp.
PCLoaderXML::~PCLoaderXML () protected
Destructor.
Definition at line 96 of file PCLoaderXML.cpp.
Member Function Documentation
void ShapeHandler::addPOI (const SUMOSAXAttributes & attrs, const bool ignorePruning, const bool useProcessing) protected inherited
adds a POI
Definition at line 87 of file ShapeHandler.cpp.
References ShapeContainer::addPOI(), Shape::DEFAULT_ANGLE, Shape::DEFAULT_IMG_FILE, Shape::DEFAULT_IMG_HEIGHT, Shape::DEFAULT_IMG_WIDTH, SUMOSAXAttributes::get(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), GeoConvHelper::getFinal(), ShapeHandler::getLanePos(), SUMOSAXAttributes::getOpt(), GeoConvHelper::getProcessing(), SUMOSAXAttributes::hasAttribute(), FileHelpers::isAbsolute(), ShapeHandler::myDefaultColor, ShapeHandler::myDefaultLayer, ShapeHandler::myPrefix, ShapeHandler::myShapeContainer, Position::set(), SUMO_ATTR_ANGLE, SUMO_ATTR_COLOR, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_LANE, SUMO_ATTR_LAT, SUMO_ATTR_LAYER, SUMO_ATTR_LON, SUMO_ATTR_POSITION, SUMO_ATTR_TYPE, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMOReal, GeoConvHelper::usingGeoProjection(), WRITE_ERROR, GeoConvHelper::x2cartesian(), and GeoConvHelper::x2cartesian_const().
Referenced by ShapeHandler::myStartElement(), and myStartElement().
void ShapeHandler::addPoly (const SUMOSAXAttributes & attrs, const bool ignorePruning, const bool useProcessing) protected inherited
adds a polygon
Definition at line 152 of file ShapeHandler.cpp.
References ShapeContainer::addPolygon(), Shape::DEFAULT_ANGLE, Shape::DEFAULT_IMG_FILE, Shape::DEFAULT_TYPE, SUMOSAXAttributes::get(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), GeoConvHelper::getFinal(), SUMOSAXAttributes::getOpt(), GeoConvHelper::getProcessing(), SUMOSAXAttributes::hasAttribute(), FileHelpers::isAbsolute(), ShapeHandler::myDefaultColor, ShapeHandler::myDefaultFill, ShapeHandler::myDefaultLayer, ShapeHandler::myPrefix, ShapeHandler::myShapeContainer, SUMO_ATTR_ANGLE, SUMO_ATTR_COLOR, SUMO_ATTR_FILL, SUMO_ATTR_GEO, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_LAYER, SUMO_ATTR_SHAPE, SUMO_ATTR_TYPE, SUMOReal, WRITE_ERROR, WRITE_WARNING, GeoConvHelper::x2cartesian(), and GeoConvHelper::x2cartesian_const().
Referenced by ShapeHandler::myStartElement(), and myStartElement().
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 192 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 175 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 211 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), MSRouteHandler::myStartElement(), and MSRouteHandler::parseWalkPos().
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 217 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), MSStateHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
Position PCLoaderXML::getLanePos (const std::string & poiID, const std::string & laneID, SUMOReal lanePos) virtual
get position for a given laneID
Implements ShapeHandler.
Definition at line 134 of file PCLoaderXML.cpp.
References Position::INVALID, and ShapeHandler::myShapeContainer.
bool ShapeHandler::loadFiles (const std::vector< std::string > & files, ShapeHandler & sh) static inherited
loads all of the given files
Definition at line 191 of file ShapeHandler.cpp.
References XMLSubSys::runParser(), and WRITE_MESSAGE.
Referenced by NLBuilder::build().
void PCLoaderXML::loadIfSet (OptionsCont & oc, PCPolyContainer & toFill, PCTypeMap & tm) static
Loads pois/polygons assumed to be stored as XML.
If the option "xml" is set within the given options container, an instance of PCLoaderXML is built and used as a handler for the files given in this option.
Parameters
[in] oc The options container to get further options from
[in] toFill The poly/pois container to add loaded polys/pois to
[in] tm The type map to use for setting values of loaded polys/pois
Exceptions
ProcessError if something fails
Definition at line 65 of file PCLoaderXML.cpp.
References OptionsCont::getStringVector(), FileHelpers::isReadable(), OptionsCont::isSet(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, and XMLSubSys::runParser().
Referenced by main().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 227 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void GenericSAXHandler::myEndElement (int element) protected virtual inherited
Callback method for a closing tag to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The closed element, given as a int ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_OpenDrive, NIImporter_OpenStreetMap::RelationHandler, NIImporter_Vissim::NIVissimXMLHandler_Routenentscheidungsdefinition, NIImporter_Vissim::NIVissimXMLHandler_Geschwindigkeitsverteilungsdefinition, NIImporter_OpenStreetMap::EdgesHandler, PCLoaderOSM::EdgesHandler, NIImporter_Vissim::NIVissimXMLHandler_VWunschentscheidungsdefinition, NIImporter_OpenStreetMap::NodesHandler, NIImporter_Vissim::NIVissimXMLHandler_Fahrzeugklassendefinition, PCLoaderOSM::RelationsHandler, MSTriggeredRerouter, SAXWeightsHandler, PCLoaderOSM::NodesHandler, NLHandler, NIImporter_ITSUMO::Handler, MSLaneSpeedTrigger, NIImporter_SUMO, NIImporter_Vissim::NIVissimXMLHandler_Streckendefinition, NIXMLEdgesHandler, MSCalibrator, SUMORouteHandler, RORouteHandler, ODDistrictHandler, MSRouteHandler, RONetHandler, MSStateHandler, NIXMLTrafficLightsHandler, GUITriggeredRerouter, GNEPoly::GNEPolyHandler, and ROMARouteHandler.
Definition at line 231 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement(), NLHandler::networkVersion(), and SUMOSAXReader::parseNext().
void PCLoaderXML::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from ShapeHandler.
Definition at line 100 of file PCLoaderXML.cpp.
References ShapeHandler::addPOI(), ShapeHandler::addPoly(), PCTypeMap::TypeDef::allowFill, PCTypeMap::TypeDef::color, PCTypeMap::TypeDef::discard, SUMOSAXAttributes::get(), PCTypeMap::get(), OptionsCont::getBool(), OptionsCont::getFloat(), SUMOSAXAttributes::getOpt(), OptionsCont::getString(), PCTypeMap::has(), OptionsCont::isInStringVector(), PCTypeMap::TypeDef::layer, myOptions, myTypeMap, RGBColor::parseColor(), PCTypeMap::TypeDef::prefix, ShapeHandler::setDefaults(), SUMO_ATTR_ID, SUMO_ATTR_TYPE, SUMO_TAG_POI, and SUMO_TAG_POLY.
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 167 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
void ShapeHandler::setDefaults (const std::string & prefix, const RGBColor & color, const SUMOReal layer, const bool fill = false) protected inherited
Definition at line 203 of file ShapeHandler.cpp.
References ShapeHandler::myDefaultColor, ShapeHandler::myDefaultFill, ShapeHandler::myDefaultLayer, and ShapeHandler::myPrefix.
Referenced by myStartElement().
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 205 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
OptionsCont& PCLoaderXML::myOptions private
Settings to use.
Definition at line 111 of file PCLoaderXML.h.
Referenced by myStartElement().
ShapeContainer& ShapeHandler::myShapeContainer protected inherited
Definition at line 110 of file ShapeHandler.h.
Referenced by ShapeHandler::addPOI(), ShapeHandler::addPoly(), and getLanePos().
PCTypeMap& PCLoaderXML::myTypeMap private
The type map to use.
Definition at line 108 of file PCLoaderXML.h.
Referenced by myStartElement().
The documentation for this class was generated from the following files:
PCLoaderXML.h
PCLoaderXML.cpp