SUMO - Simulation of Urban MObility: MSLCM_LC2013 Class Reference
MSLCM_LC2013 Class Reference
A lane change model developed by D. Krajzewicz, J. Erdmann et al. between 2004 and 2013.
#include <MSLCM_LC2013.h>
Public Types
enum MyLCAEnum {
LCA_AMBLOCKINGLEADER = 1 << 16, LCA_AMBLOCKINGFOLLOWER = 1 << 17, LCA_MRIGHT = 1 << 18, LCA_MLEFT = 1 << 19,
LCA_AMBLOCKINGFOLLOWER_DONTBRAKE = 1 << 21, LCA_CHANGE_TO_HELP = 1 << 23, LCA_AMBACKBLOCKER = 1 << 26, LCA_AMBACKBLOCKER_STANDING = 1 << 27
}
Public Member Functions
SUMOReal _patchSpeed (const SUMOReal min, const SUMOReal wanted, const SUMOReal max, const MSCFModel &cfModel)
bool alreadyChanged () const
reset the flag whether a vehicle already moved to false
void changed ()
void changedToOpposite ()
called when a vehicle changes between lanes in opposite directions
void cleanupShadowLane ()
bool debugVehicle () const
whether the current vehicles shall be debugged
virtual StateAndDist decideDirection (StateAndDist sd1, StateAndDist sd2) const
decide in which direction to move in case both directions are desirable
void endLaneChangeManeuver (const MSMoveReminder::Notification reason=MSMoveReminder::NOTIFICATION_LANE_CHANGE)
SUMOReal getAngleOffset () const
return the angle offset during a continuous change maneuver
int getLaneChangeDirection () const
return the direction of the current lane change maneuver
SUMOTime getLastLaneChangeOffset () const
SUMOReal getLateralSpeed () const
return the lateral speed of the current lane change maneuver
int getOwnState () const
int getShadowDirection () const
return the direction in which the current shadow lane lies
const std::vector< MSLane * > & getShadowFurtherLanes () const
const std::vector< SUMOReal > & getShadowFurtherLanesPosLat () const
MSLane * getShadowLane () const
Returns the lane the vehicles shadow is on during continuous/sublane lane change.
MSLane * getShadowLane (const MSLane *lane) const
return the shadow lane for the given lane
void * inform (void *info, MSVehicle *sender)
bool isChangingLanes () const
return true if the vehicle currently performs a lane change maneuver
bool isOpposite () const
MSLCM_LC2013 (MSVehicle &v)
bool pastMidpoint () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
SUMOReal patchSpeed (const SUMOReal min, const SUMOReal wanted, const SUMOReal max, const MSCFModel &cfModel)
Called to adapt the speed in order to allow a lane change.
void prepareStep ()
void primaryLaneChanged (MSLane *source, MSLane *target, int direction)
called once when the vehicles primary lane changes
SUMOTime remainingTime () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
void removeShadowApproachingInformation () const
void resetChanged ()
reset the flag whether a vehicle already moved to false
void setNoShadowPartialOccupator (MSLane *lane)
virtual void setOwnState (int state)
void setShadowApproachingInformation (MSLink *link) const
set approach information for the shadow vehicle
void setShadowLane (MSLane *lane)
set the shadow lane
void setShadowPartialOccupator (MSLane *lane)
bool startLaneChangeManeuver (MSLane *source, MSLane *target, int direction)
start the lane change maneuver and return whether it continues
void unchanged ()
bool updateCompletion ()
virtual void updateExpectedSublaneSpeeds (const MSLeaderInfo &ahead, int sublaneOffset, int laneIndex)
update expected speeds for each sublane of the current edge
void updateShadowLane ()
int wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > &leader, const std::pair< MSVehicle *, SUMOReal > &neighLead, const std::pair< MSVehicle *, SUMOReal > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked)
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
virtual int wantsChangeSublane (int laneOffset, const MSLeaderDistanceInfo &leaders, const MSLeaderDistanceInfo &followers, const MSLeaderDistanceInfo &blockers, const MSLeaderDistanceInfo &neighLeaders, const MSLeaderDistanceInfo &neighFollowers, const MSLeaderDistanceInfo &neighBlockers, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked, SUMOReal &latDist, int &blocked)
virtual ~MSLCM_LC2013 ()
Static Public Member Functions
static MSAbstractLaneChangeModel * build (LaneChangeModel lcm, MSVehicle &vehicle)
Factory method for instantiating new lane changing models.
static void initGlobalOptions (const OptionsCont &oc)
init global model parameters
Protected Types
typedef std::pair< SUMOReal, int > Info
information regarding save velocity (unused) and state flags of the ego vehicle
Protected Member Functions
int _wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > &leader, const std::pair< MSVehicle *, SUMOReal > &neighLead, const std::pair< MSVehicle *, SUMOReal > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked)
helper function for doing the actual work
bool amBlockingFollower ()
bool amBlockingFollowerNB ()
bool amBlockingFollowerPlusNB ()
bool amBlockingLeader ()
bool cancelRequest (int state)
whether the influencer cancels the given request
virtual bool congested (const MSVehicle *const neighLeader)
bool currentDistAllows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist)
bool currentDistDisallows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist)
void informFollower (MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, int dir, const std::pair< MSVehicle *, SUMOReal > &neighFollow, SUMOReal remainingSeconds, SUMOReal plannedSpeed)
decide whether we will try cut in before the follower or allow to be overtaken
SUMOReal informLeader (MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, int dir, const std::pair< MSVehicle *, SUMOReal > &neighLead, SUMOReal remainingSeconds)
void initLastLaneChangeOffset (int dir)
virtual bool predInteraction (const std::pair< MSVehicle *, SUMOReal > &leader)
void saveBlockerLength (MSVehicle *blocker, int lcaCounter)
save space for vehicles which need to counter-lane-change
void saveBlockerLength (SUMOReal length)
reserve space at the end of the lane to avoid dead locks
int slowDownForBlocked (MSVehicle **blocked, int state)
compute useful slowdowns for blocked vehicles
Protected Attributes
bool myAlreadyChanged
whether the vehicle has already moved this step
const MSCFModel & myCarFollowModel
The vehicle's car following model.
bool myDontBrake
SUMOReal myKeepRightProbability
SUMOReal myLaneChangeCompletion
progress of the lane change maneuver 0:started, 1:complete
int myLaneChangeDirection
direction of the lane change maneuver -1 means right, 1 means left
SUMOReal myLateralspeed
The lateral offset during a continuous LaneChangeManeuver.
SUMOReal myLeadingBlockerLength
SUMOReal myLeftSpace
SUMOReal myLookAheadSpeed
const LaneChangeModel myModel
the type of this model
std::vector< MSLane * > myNoPartiallyOccupatedByShadow
int myOwnState
The current state of the vehicle.
std::vector< MSLane * > myPartiallyOccupatedByShadow
list of lanes where the shadow vehicle is partial occupator
std::vector< MSLane * > myShadowFurtherLanes
std::vector< SUMOReal > myShadowFurtherLanesPosLat
MSLane * myShadowLane
A lane that is partially occupied by the front of the vehicle but that is not the primary lane.
SUMOReal mySpeedGainProbability
a value for tracking the probability that a change to the offset with the same sign is beneficial
MSVehicle & myVehicle
The vehicle this lane-changer belongs to.
std::vector< SUMOReal > myVSafes
user configurable model parameters
const SUMOReal myStrategicParam
const SUMOReal myCooperativeParam
const SUMOReal mySpeedGainParam
const SUMOReal myKeepRightParam
derived parameters
const SUMOReal myChangeProbThresholdRight
const SUMOReal myChangeProbThresholdLeft
Static Protected Attributes
static bool myAllowOvertakingRight
whether overtaking on the right is permitted
static bool myLCOutput
whether to record lane-changing
Detailed Description
A lane change model developed by D. Krajzewicz, J. Erdmann et al. between 2004 and 2013.
Definition at line 49 of file MSLCM_LC2013.h.
Member Typedef Documentation
typedef std::pair<SUMOReal, int> MSLCM_LC2013::Info protected
information regarding save velocity (unused) and state flags of the ego vehicle
Definition at line 173 of file MSLCM_LC2013.h.
Member Enumeration Documentation
enum MSLCM_LC2013::MyLCAEnum
Enumerator
LCA_AMBLOCKINGLEADER
LCA_AMBLOCKINGFOLLOWER
LCA_MRIGHT
LCA_MLEFT
LCA_AMBLOCKINGFOLLOWER_DONTBRAKE
LCA_CHANGE_TO_HELP
LCA_AMBACKBLOCKER
LCA_AMBACKBLOCKER_STANDING
Definition at line 52 of file MSLCM_LC2013.h.
Constructor & Destructor Documentation
MSLCM_LC2013::MSLCM_LC2013 (MSVehicle & v)
Definition at line 94 of file MSLCM_LC2013.cpp.
References DEBUG_COND, MSBaseVehicle::getID(), myCooperativeParam, myKeepRightParam, mySpeedGainParam, myStrategicParam, MSAbstractLaneChangeModel::myVehicle, and SIMTIME.
MSLCM_LC2013::~MSLCM_LC2013 () virtual
Definition at line 120 of file MSLCM_LC2013.cpp.
References changed().
Member Function Documentation
SUMOReal MSLCM_LC2013::_patchSpeed (const SUMOReal min, const SUMOReal wanted, const SUMOReal max, const MSCFModel & cfModel)
helper function which contains the actual logic
Definition at line 207 of file MSLCM_LC2013.cpp.
References changed(), DEBUG_COND, MSLane::getEdge(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSEdge::getLanes(), MSVehicleType::getMinGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, LCA_AMBLOCKINGLEADER, LCA_BLOCKED, LCA_BLOCKED_BY_FOLLOWER, LCA_BLOCKED_BY_LEADER, LCA_COOPERATIVE, LCA_STRATEGIC, LCA_WANTS_LANECHANGE, MAX2(), MIN2(), myCooperativeParam, myDontBrake, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, myVSafes, NUMERICAL_EPS, SIMTIME, MSCFModel::stopSpeed(), SUMOReal, and toString().
Referenced by patchSpeed().
int MSLCM_LC2013::_wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > & leader, const std::pair< MSVehicle *, SUMOReal > & neighLead, const std::pair< MSVehicle *, SUMOReal > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked) protected
helper function for doing the actual work
we urgently need to change lanes to follow our route
Definition at line 646 of file MSLCM_LC2013.cpp.
References abs, amBlockingFollowerPlusNB(), MSVehicle::LaneQ::bestContinuations, MSVehicle::LaneQ::bestLaneOffset, MSCFModel::brakeGap(), MSAbstractLaneChangeModel::cancelRequest(), MSVehicle::Influencer::changeRequestRemainingSeconds(), MSVehicle::congested(), currentDistAllows(), currentDistDisallows(), DEBUG_COND, DELTA_T, MSEdge::EDGEFUNCTION_INTERNAL, MSCFModel::followSpeed(), MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), MSLane::getEdge(), MSBaseVehicle::getID(), Named::getIDSecure(), MSVehicle::getInfluencer(), MSNet::getInstance(), MSVehicle::getLane(), MSLane::getLength(), MSVehicleType::getLengthWithGap(), MSLane::getLinkCont(), MSCFModel::getMaxDecel(), MSVehicleType::getMaxSpeed(), MSVehicle::getPositionOnLane(), MSEdge::getPurpose(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSLane::getSpeedLimit(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSVehicle::influenceChangeDecision(), informFollower(), informLeader(), MSAbstractLaneChangeModel::isOpposite(), JAM_FACTOR, KEEP_RIGHT_ACCEPTANCE, KEEP_RIGHT_TIME, LCA_COOPERATIVE, LCA_KEEPRIGHT, LCA_LEFT, LCA_MLEFT, LCA_MRIGHT, LCA_RIGHT, LCA_SPEEDGAIN, LCA_STAY, LCA_STRATEGIC, LCA_TRACI, LCA_URGENT, MSVehicle::LaneQ::length, LOOK_AHEAD_MIN_SPEED, LOOK_AHEAD_SPEED_MEMORY, LOOK_FORWARD_LEFT, LOOK_FORWARD_RIGHT, MAX2(), MIN2(), MSAbstractLaneChangeModel::myAllowOvertakingRight, MSAbstractLaneChangeModel::myCarFollowModel, myChangeProbThresholdLeft, myChangeProbThresholdRight, myCooperativeParam, myKeepRightParam, myKeepRightProbability, myLeadingBlockerLength, myLeftSpace, myLookAheadSpeed, MSAbstractLaneChangeModel::myOwnState, mySpeedGainProbability, myStrategicParam, MSAbstractLaneChangeModel::myVehicle, myVSafes, NUMERICAL_EPS, MSVehicle::LaneQ::occupation, RELGAIN_NORMALIZATION_MIN_SPEED, ROUNDABOUT_DIST_BONUS, saveBlockerLength(), SIMTIME, slowDownForBlocked(), STEPS2TIME, SUMO_const_haltingSpeed, SUMOReal, toString(), TS, and URGENCY.
Referenced by wantsChange().
bool MSAbstractLaneChangeModel::alreadyChanged () const inline inherited
reset the flag whether a vehicle already moved to false
Definition at line 324 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myAlreadyChanged.
Referenced by MSLaneChanger::change().
bool MSLCM_LC2013::amBlockingFollower () inline protected
Definition at line 156 of file MSLCM_LC2013.h.
References LCA_AMBLOCKINGFOLLOWER, and MSAbstractLaneChangeModel::myOwnState.
bool MSLCM_LC2013::amBlockingFollowerNB () inline protected
Definition at line 159 of file MSLCM_LC2013.h.
References LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, and MSAbstractLaneChangeModel::myOwnState.
bool MSLCM_LC2013::amBlockingFollowerPlusNB () inline protected
Definition at line 162 of file MSLCM_LC2013.h.
References LCA_AMBLOCKINGFOLLOWER, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, and MSAbstractLaneChangeModel::myOwnState.
Referenced by _wantsChange().
bool MSLCM_LC2013::amBlockingLeader () inline protected
Definition at line 153 of file MSLCM_LC2013.h.
References LCA_AMBLOCKINGLEADER, and MSAbstractLaneChangeModel::myOwnState.
MSAbstractLaneChangeModel * MSAbstractLaneChangeModel::build (LaneChangeModel lcm, MSVehicle & vehicle) static inherited
Factory method for instantiating new lane changing models.
Parameters
[in] lcm The type of model to build
[in] vehicle The vehicle for which this model shall be built
Definition at line 63 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLateralResolution, LCM_DEFAULT, LCM_DK2008, LCM_JE2013, LCM_LC2013, LCM_SL2015, and toString().
Referenced by MSVehicle::MSVehicle(), and MSAbstractLaneChangeModel::StateAndDist::StateAndDist().
bool MSAbstractLaneChangeModel::cancelRequest (int state) protected inherited
whether the influencer cancels the given request
Definition at line 244 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::influenceChangeDecision(), and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSLCM_JE2013::_wantsChange(), _wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), and MSAbstractLaneChangeModel::isOpposite().
void MSLCM_LC2013::changed () virtual
Implements MSAbstractLaneChangeModel.
Definition at line 629 of file MSLCM_LC2013.cpp.
References MSVehicle::getBestLaneOffset(), LOOK_AHEAD_MIN_SPEED, myDontBrake, myKeepRightProbability, myLeadingBlockerLength, myLeftSpace, myLookAheadSpeed, MSAbstractLaneChangeModel::myOwnState, mySpeedGainProbability, MSAbstractLaneChangeModel::myVehicle, and myVSafes.
Referenced by _patchSpeed(), and ~MSLCM_LC2013().
void MSAbstractLaneChangeModel::changedToOpposite () inherited
called when a vehicle changes between lanes in opposite directions
Definition at line 350 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myAlreadyChanged, and MSAbstractLaneChangeModel::myAmOpposite.
Referenced by MSAbstractLaneChangeModel::debugVehicle(), MSVehicle::executeMove(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
void MSAbstractLaneChangeModel::cleanupShadowLane () inherited
Definition at line 224 of file MSAbstractLaneChangeModel.cpp.
References MSBaseVehicle::getID(), MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::myShadowFurtherLanes, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, MSLane::resetPartialOccupation(), and SIMTIME.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::resetChanged(), and MSVehicle::~MSVehicle().
bool MSAbstractLaneChangeModel::congested (const MSVehicle *const neighLeader) protected virtual inherited
Definition at line 108 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::congested(), MSVehicle::getLane(), MSLane::getSpeedLimit(), and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSAbstractLaneChangeModel::isOpposite(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
bool MSLCM_LC2013::currentDistAllows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist) inline protected
Definition at line 168 of file MSLCM_LC2013.h.
References abs.
Referenced by _wantsChange().
bool MSLCM_LC2013::currentDistDisallows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist) inline protected
Definition at line 165 of file MSLCM_LC2013.h.
References abs.
Referenced by _wantsChange().
bool MSLCM_LC2013::debugVehicle () const virtual
whether the current vehicles shall be debugged
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 126 of file MSLCM_LC2013.cpp.
References DEBUG_COND.
virtual StateAndDist MSAbstractLaneChangeModel::decideDirection (StateAndDist sd1, StateAndDist sd2) const inline virtual inherited
decide in which direction to move in case both directions are desirable
Reimplemented in MSLCM_SL2015.
Definition at line 223 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::changed(), MSAbstractLaneChangeModel::inform(), max, min, MSAbstractLaneChangeModel::myModel, MSAbstractLaneChangeModel::patchSpeed(), SUMOReal, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::change().
void MSAbstractLaneChangeModel::endLaneChangeManeuver (const MSMoveReminder::Notification reason = MSMoveReminder::NOTIFICATION_LANE_CHANGE) inherited
Definition at line 191 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::cleanupShadowLane(), MSVehicle::fixPosition(), MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::myVehicle, MSVehicle::switchOffSignal(), UNUSED_PARAMETER, MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSVehicleTransfer::add(), MSLaneChanger::continueChange(), MSVehicle::executeMove(), MSAbstractLaneChangeModel::resetChanged(), and MSAbstractLaneChangeModel::updateShadowLane().
SUMOReal MSAbstractLaneChangeModel::getAngleOffset () const inherited
return the angle offset during a continuous change maneuver
Definition at line 321 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::pastMidpoint(), STEPS2TIME, and SUMOReal.
Referenced by MSAbstractLaneChangeModel::getLaneChangeDirection().
int MSAbstractLaneChangeModel::getLaneChangeDirection () const inline inherited
return the direction of the current lane change maneuver
Definition at line 308 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::myLaneChangeDirection, and SUMOReal.
Referenced by MSLaneChanger::continueChange().
SUMOTime MSAbstractLaneChangeModel::getLastLaneChangeOffset () const inline inherited
Definition at line 289 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLastLaneChangeOffset.
SUMOReal MSAbstractLaneChangeModel::getLateralSpeed () const inline inherited
return the lateral speed of the current lane change maneuver
Definition at line 319 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLateralspeed.
Referenced by MSLaneChanger::continueChange().
int MSAbstractLaneChangeModel::getOwnState () const inline inherited
Definition at line 148 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myOwnState.
Referenced by MSLaneChanger::change(), MSLCM_JE2013::saveBlockerLength(), saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), and MSVehicle::setBlinkerInformation().
int MSAbstractLaneChangeModel::getShadowDirection () const inherited
return the direction in which the current shadow lane lies
Definition at line 304 of file MSAbstractLaneChangeModel.cpp.
References MSLane::getEdge(), MSLane::getIndex(), MSVehicle::getLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, MSAbstractLaneChangeModel::pastMidpoint(), and SUMOReal.
Referenced by MSLaneChanger::continueChange(), MSVehicle::executeMove(), MSAbstractLaneChangeModel::getLaneChangeDirection(), and GUIVehicle::selectBlockingFoes().
const std::vector<MSLane*>& MSAbstractLaneChangeModel::getShadowFurtherLanes () const inline inherited
Definition at line 281 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowFurtherLanes.
Referenced by MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), and MSVehicle::getLatOffset().
const std::vector<SUMOReal>& MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat () const inline inherited
Definition at line 285 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat.
Referenced by MSVehicle::getCenterOnEdge(), and MSVehicle::getLatOffset().
MSLane* MSAbstractLaneChangeModel::getShadowLane () const inline inherited
Returns the lane the vehicles shadow is on during continuous/sublane lane change.
Returns
The vehicle's shadow lane
Definition at line 269 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowLane.
Referenced by MSVehicle::checkRewindLinkLanes(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::executeMove(), MSVehicle::getBackPosition(), MSVehicle::getCenterOnEdge(), GUIVehicle::getParameterWindow(), MSVehicle::isFrontOnLane(), MSVehicle::planMoveInternal(), GUIVehicle::selectBlockingFoes(), MSLaneChangerSublane::startChangeSublane(), MSLaneChangerSublane::updateChanger(), and MSAbstractLaneChangeModel::updateShadowLane().
MSLane * MSAbstractLaneChangeModel::getShadowLane (const MSLane * lane) const inherited
return the shadow lane for the given lane
Definition at line 202 of file MSAbstractLaneChangeModel.cpp.
References MSBaseVehicle::getID(), MSVehicle::getLateralOverlap(), MSVehicle::getLateralPositionOnLane(), MSLane::getParallelLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, SIMTIME, and SUMOReal.
void * MSLCM_LC2013::inform (void * info, MSVehicle * sender) virtual
Implements MSAbstractLaneChangeModel.
Definition at line 324 of file MSLCM_LC2013.cpp.
References DEBUG_COND, MSBaseVehicle::getID(), MSNet::getInstance(), MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, myVSafes, STEPS2TIME, SUMOReal, and UNUSED_PARAMETER.
void MSLCM_LC2013::informFollower (MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, int dir, const std::pair< MSVehicle *, SUMOReal > & neighFollow, SUMOReal remainingSeconds, SUMOReal plannedSpeed) protected
decide whether we will try cut in before the follower or allow to be overtaken
Definition at line 470 of file MSLCM_LC2013.cpp.
References ACCEL2SPEED, CUT_IN_LEFT_SPEED_THRESHOLD, DEBUG_COND, MSCFModel::followSpeed(), MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSVehicle::getWaitingSeconds(), HELP_DECEL_FACTOR, HELP_OVERTAKE, MSAbstractLaneChangeModel::MSLCMessager::informNeighFollower(), LCA_AMBLOCKINGFOLLOWER, LCA_BLOCKED_BY_FOLLOWER, LCA_MLEFT, LCA_MRIGHT, LCA_RIGHT_IMPATIENCE, MAX2(), MSAbstractLaneChangeModel::myVehicle, myVSafes, POSITION_EPS, SPEED2DIST, STEPS2TIME, and SUMOReal.
Referenced by _wantsChange().
SUMOReal MSLCM_LC2013::informLeader (MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, int dir, const std::pair< MSVehicle *, SUMOReal > & neighLead, SUMOReal remainingSeconds) protected
Definition at line 345 of file MSLCM_LC2013.cpp.
References ACCEL2SPEED, MSVehicle::congested(), DEBUG_COND, MSCFModel::followSpeed(), MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), HELP_OVERTAKE, MSAbstractLaneChangeModel::MSLCMessager::informNeighLeader(), LCA_AMBLOCKINGLEADER, LCA_BLOCKED_BY_LEADER, LCA_MLEFT, MAX2(), MIN2(), MIN_FALLBEHIND, MSAbstractLaneChangeModel::myAllowOvertakingRight, MSAbstractLaneChangeModel::myCarFollowModel, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myVehicle, myVSafes, SPEED2DIST, STEPS2TIME, MSCFModel::stopSpeed(), and SUMOReal.
Referenced by _wantsChange().
void MSAbstractLaneChangeModel::initGlobalOptions (const OptionsCont & oc) static inherited
init global model parameters
Definition at line 56 of file MSAbstractLaneChangeModel.cpp.
References OptionsCont::getBool(), OptionsCont::isSet(), MSAbstractLaneChangeModel::myAllowOvertakingRight, and MSAbstractLaneChangeModel::myLCOutput.
Referenced by MSFrame::setMSGlobals(), and MSAbstractLaneChangeModel::StateAndDist::StateAndDist().
void MSAbstractLaneChangeModel::initLastLaneChangeOffset (int dir) protected inherited
Definition at line 251 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myLastLaneChangeOffset.
Referenced by MSAbstractLaneChangeModel::primaryLaneChanged().
bool MSAbstractLaneChangeModel::isChangingLanes () const inline inherited
return true if the vehicle currently performs a lane change maneuver
Definition at line 303 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeCompletion, and NUMERICAL_EPS.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), MSVehicle::computeAngle(), MSLaneChanger::continueChange(), MSLane::detectCollisionBetween(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::getBackPosition(), MSVehicle::getPosition(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), and MSAbstractLaneChangeModel::updateShadowLane().
bool MSAbstractLaneChangeModel::isOpposite () const inline inherited
Definition at line 372 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::cancelRequest(), MSAbstractLaneChangeModel::congested(), MSAbstractLaneChangeModel::myAmOpposite, and MSAbstractLaneChangeModel::predInteraction().
Referenced by MSLCM_JE2013::_wantsChange(), _wantsChange(), MSLaneChanger::changeOpposite(), MSVehicle::checkRewindLinkLanes(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), and MSVehicle::planMoveInternal().
bool MSAbstractLaneChangeModel::pastMidpoint () const inline inherited
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 295 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeCompletion, and MSAbstractLaneChangeModel::remainingTime().
Referenced by MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getShadowDirection(), and MSAbstractLaneChangeModel::updateCompletion().
SUMOReal MSLCM_LC2013::patchSpeed (const SUMOReal min, const SUMOReal wanted, const SUMOReal max, const MSCFModel & cfModel) virtual
Called to adapt the speed in order to allow a lane change.
Parameters
min The minimum resulting speed
wanted The aspired speed of the car following model
max The maximum resulting speed
cfModel The model used
Returns
the new speed of the vehicle as proposed by the lane changer
Implements MSAbstractLaneChangeModel.
Definition at line 185 of file MSLCM_LC2013.cpp.
References _patchSpeed(), DEBUG_COND, Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSAbstractLaneChangeModel::myVehicle, STEPS2TIME, SUMOReal, and toString().
bool MSAbstractLaneChangeModel::predInteraction (const std::pair< MSVehicle *, SUMOReal > & leader) protected virtual inherited
Definition at line 128 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getSpeed(), MSCFModel::interactionGap(), MSAbstractLaneChangeModel::myCarFollowModel, and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSAbstractLaneChangeModel::isOpposite(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
void MSLCM_LC2013::prepareStep () virtual
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 615 of file MSLCM_LC2013.cpp.
References LCA_STRATEGIC, LCA_WANTS_LANECHANGE, myDontBrake, myKeepRightProbability, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, mySpeedGainProbability, and myVSafes.
void MSAbstractLaneChangeModel::primaryLaneChanged (MSLane * source, MSLane * target, int direction) inherited
called once when the vehicles primary lane changes
Definition at line 160 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changed(), OutputDevice::closeTag(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtLaneChange(), OutputDevice::getDeviceByOption(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getSpeed(), MSAbstractLaneChangeModel::initLastLaneChangeOffset(), LCA_LEFT, LCA_RIGHT, MSVehicle::leaveLane(), MSLane::leftByLaneChange(), MSAbstractLaneChangeModel::myLCOutput, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, MSMoveReminder::NOTIFICATION_LANE_CHANGE, OutputDevice::openTag(), SUMO_ATTR_DIR, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_SPEED, SUMO_ATTR_TIME, SUMO_ATTR_TO, time2string(), toString(), and OutputDevice::writeAttr().
Referenced by MSLaneChanger::continueChange(), MSAbstractLaneChangeModel::setNoShadowPartialOccupator(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
SUMOTime MSAbstractLaneChangeModel::remainingTime () const inherited
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 328 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLaneChangeDuration, and MSAbstractLaneChangeModel::myLaneChangeCompletion.
Referenced by MSAbstractLaneChangeModel::pastMidpoint().
void MSAbstractLaneChangeModel::removeShadowApproachingInformation () const inherited
Definition at line 340 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myApproachedByShadow, and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSVehicle::removeApproachingInformation(), and MSAbstractLaneChangeModel::setNoShadowPartialOccupator().
void MSAbstractLaneChangeModel::resetChanged () inline inherited
reset the flag whether a vehicle already moved to false
Definition at line 329 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::myAlreadyChanged, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSAbstractLaneChangeModel::startLaneChangeManeuver(), MSAbstractLaneChangeModel::updateCompletion(), and MSAbstractLaneChangeModel::updateShadowLane().
Referenced by MSVehicle::planMove().
void MSLCM_LC2013::saveBlockerLength (MSVehicle * blocker, int lcaCounter) protected
save space for vehicles which need to counter-lane-change
Definition at line 1228 of file MSLCM_LC2013.cpp.
References MSCFModel::brakeGap(), DEBUG_COND, MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInstance(), MSVehicle::getLaneChangeModel(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSAbstractLaneChangeModel::getOwnState(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MAX2(), myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myVehicle, MSAbstractLaneChangeModel::saveBlockerLength(), STEPS2TIME, SUMOReal, and toString().
Referenced by _wantsChange().
void MSLCM_LC2013::saveBlockerLength (SUMOReal length) inline protected virtual
reserve space at the end of the lane to avoid dead locks
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 149 of file MSLCM_LC2013.h.
References MAX2(), and myLeadingBlockerLength.
void MSAbstractLaneChangeModel::setNoShadowPartialOccupator (MSLane * lane) inline inherited
Definition at line 361 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::primaryLaneChanged(), MSAbstractLaneChangeModel::removeShadowApproachingInformation(), and MSAbstractLaneChangeModel::setShadowApproachingInformation().
Referenced by MSVehicle::enterLaneAtLaneChange().
virtual void MSAbstractLaneChangeModel::setOwnState (int state) inline virtual inherited
Reimplemented in MSLCM_SL2015.
Definition at line 152 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myOwnState.
Referenced by MSLaneChangerSublane::change(), and MSLaneChanger::change().
void MSAbstractLaneChangeModel::setShadowApproachingInformation (MSLink * link) const inherited
set approach information for the shadow vehicle
Definition at line 334 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myApproachedByShadow.
Referenced by MSVehicle::checkRewindLinkLanes(), and MSAbstractLaneChangeModel::setNoShadowPartialOccupator().
void MSAbstractLaneChangeModel::setShadowLane (MSLane * lane) inline inherited
set the shadow lane
Definition at line 277 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowLane.
void MSAbstractLaneChangeModel::setShadowPartialOccupator (MSLane * lane) inline inherited
Definition at line 357 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myPartiallyOccupatedByShadow.
int MSLCM_LC2013::slowDownForBlocked (MSVehicle ** blocked, int state) protected
compute useful slowdowns for blocked vehicles
Definition at line 1195 of file MSLCM_LC2013.cpp.
References ACCEL2SPEED, DEBUG_COND, MSCFModel::followSpeed(), MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInstance(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), LCA_AMBACKBLOCKER, LCA_AMBACKBLOCKER_STANDING, MSAbstractLaneChangeModel::myCarFollowModel, MSAbstractLaneChangeModel::myVehicle, myVSafes, POSITION_EPS, STEPS2TIME, SUMO_const_haltingSpeed, and SUMOReal.
Referenced by _wantsChange().
bool MSAbstractLaneChangeModel::startLaneChangeManeuver (MSLane * source, MSLane * target, int direction) inherited
start the lane change maneuver and return whether it continues
Definition at line 141 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changedToOpposite(), DELTA_T, MSLane::getCenterOnEdge(), MSLane::getEdge(), MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::myLateralspeed, MSAbstractLaneChangeModel::myVehicle, MSAbstractLaneChangeModel::primaryLaneChanged(), SUMOReal, MSVehicle::switchOffSignal(), MSVehicle::switchOnSignal(), MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSLaneChanger::changeOpposite(), MSAbstractLaneChangeModel::resetChanged(), MSLaneChanger::startChange(), and MSLaneChangerSublane::startChangeSublane().
void MSAbstractLaneChangeModel::unchanged () inline inherited
Definition at line 258 of file MSAbstractLaneChangeModel.h.
References DELTA_T, and MSAbstractLaneChangeModel::myLastLaneChangeOffset.
Referenced by MSLaneChanger::registerUnchanged().
bool MSAbstractLaneChangeModel::updateCompletion () inherited
Definition at line 183 of file MSAbstractLaneChangeModel.cpp.
References DELTA_T, MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::pastMidpoint(), and SUMOReal.
Referenced by MSLaneChanger::continueChange(), and MSAbstractLaneChangeModel::resetChanged().
virtual void MSAbstractLaneChangeModel::updateExpectedSublaneSpeeds (const MSLeaderInfo & ahead, int sublaneOffset, int laneIndex) inline virtual inherited
update expected speeds for each sublane of the current edge
Reimplemented in MSLCM_SL2015.
Definition at line 215 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::change().
void MSAbstractLaneChangeModel::updateShadowLane () inherited
Definition at line 260 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::endLaneChangeManeuver(), gDebugFlag4, MSVehicle::getFurtherLanes(), MSVehicle::getFurtherLanesPosLat(), MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getLateralOverlap(), MSVehicle::getLateralPositionOnLane(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::myShadowFurtherLanes, MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, MSLane::resetPartialOccupation(), MSLane::setPartialOccupation(), SIMTIME, time2string(), toString(), MSVehicle::updateFurtherLanes(), and WRITE_WARNING.
Referenced by MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), MSAbstractLaneChangeModel::resetChanged(), and MSLaneChangerSublane::startChangeSublane().
int MSLCM_LC2013::wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > & leader, const std::pair< MSVehicle *, SUMOReal > & neighLead, const std::pair< MSVehicle *, SUMOReal > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked) virtual
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 132 of file MSLCM_LC2013.cpp.
References _wantsChange(), DEBUG_COND, Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getLateralPositionOnLane(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), LCA_BLOCKED, LCA_CHANGE_TO_HELP, LCA_COOPERATIVE, LCA_KEEPRIGHT, LCA_OVERLAPPING, LCA_SPEEDGAIN, LCA_STRATEGIC, LCA_TRACI, LCA_URGENT, LCA_WANTS_LANECHANGE, MSAbstractLaneChangeModel::myVehicle, STEPS2TIME, and SUMOReal.
virtual int MSAbstractLaneChangeModel::wantsChangeSublane (int laneOffset, const MSLeaderDistanceInfo & leaders, const MSLeaderDistanceInfo & followers, const MSLeaderDistanceInfo & blockers, const MSLeaderDistanceInfo & neighLeaders, const MSLeaderDistanceInfo & neighFollowers, const MSLeaderDistanceInfo & neighBlockers, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked, SUMOReal & latDist, int & blocked) inline virtual inherited
Reimplemented in MSLCM_SL2015.
Definition at line 185 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::checkChangeSublane().
Field Documentation
bool MSAbstractLaneChangeModel::myAllowOvertakingRight static protected inherited
whether overtaking on the right is permitted
Definition at line 430 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_JE2013::_wantsChange(), _wantsChange(), MSLCM_SL2015::checkStrategicChange(), MSLCM_JE2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), informLeader(), MSLCM_SL2015::informLeader(), and MSAbstractLaneChangeModel::initGlobalOptions().
bool MSAbstractLaneChangeModel::myAlreadyChanged protected inherited
whether the vehicle has already moved this step
Definition at line 402 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::alreadyChanged(), MSAbstractLaneChangeModel::changedToOpposite(), and MSAbstractLaneChangeModel::resetChanged().
const MSCFModel& MSAbstractLaneChangeModel::myCarFollowModel protected inherited
The vehicle's car following model.
Definition at line 413 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_JE2013::_wantsChange(), _wantsChange(), MSLCM_SL2015::checkStrategicChange(), MSLCM_DK2008::informBlocker(), MSLCM_JE2013::informLeader(), informLeader(), MSLCM_SL2015::informLeader(), MSAbstractLaneChangeModel::predInteraction(), MSLCM_JE2013::slowDownForBlocked(), slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
const SUMOReal MSLCM_LC2013::myChangeProbThresholdLeft protected
Definition at line 207 of file MSLCM_LC2013.h.
Referenced by _wantsChange().
const SUMOReal MSLCM_LC2013::myChangeProbThresholdRight protected
Definition at line 206 of file MSLCM_LC2013.h.
Referenced by _wantsChange().
const SUMOReal MSLCM_LC2013::myCooperativeParam protected
Definition at line 198 of file MSLCM_LC2013.h.
Referenced by _patchSpeed(), _wantsChange(), and MSLCM_LC2013().
bool MSLCM_LC2013::myDontBrake protected
Definition at line 193 of file MSLCM_LC2013.h.
Referenced by _patchSpeed(), changed(), and prepareStep().
const SUMOReal MSLCM_LC2013::myKeepRightParam protected
Definition at line 200 of file MSLCM_LC2013.h.
Referenced by _wantsChange(), and MSLCM_LC2013().
SUMOReal MSLCM_LC2013::myKeepRightProbability protected
Definition at line 183 of file MSLCM_LC2013.h.
Referenced by _wantsChange(), changed(), and prepareStep().
SUMOReal MSAbstractLaneChangeModel::myLaneChangeCompletion protected inherited
progress of the lane change maneuver 0:started, 1:complete
Definition at line 393 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::pastMidpoint(), MSAbstractLaneChangeModel::remainingTime(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), and MSAbstractLaneChangeModel::updateCompletion().
int MSAbstractLaneChangeModel::myLaneChangeDirection protected inherited
direction of the lane change maneuver -1 means right, 1 means left
Definition at line 396 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getLaneChangeDirection(), MSAbstractLaneChangeModel::getShadowDirection(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
SUMOReal MSAbstractLaneChangeModel::myLateralspeed protected inherited
The lateral offset during a continuous LaneChangeManeuver.
Definition at line 399 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getLateralSpeed(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
bool MSAbstractLaneChangeModel::myLCOutput static protected inherited
whether to record lane-changing
Definition at line 433 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::initGlobalOptions(), and MSAbstractLaneChangeModel::primaryLaneChanged().
SUMOReal MSLCM_LC2013::myLeadingBlockerLength protected
Definition at line 185 of file MSLCM_LC2013.h.
Referenced by _patchSpeed(), _wantsChange(), changed(), informLeader(), prepareStep(), and saveBlockerLength().
SUMOReal MSLCM_LC2013::myLeftSpace protected
Definition at line 186 of file MSLCM_LC2013.h.
Referenced by _patchSpeed(), _wantsChange(), changed(), informLeader(), prepareStep(), and saveBlockerLength().
SUMOReal MSLCM_LC2013::myLookAheadSpeed protected
Definition at line 190 of file MSLCM_LC2013.h.
Referenced by _wantsChange(), and changed().
const LaneChangeModel MSAbstractLaneChangeModel::myModel protected inherited
the type of this model
Definition at line 416 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::decideDirection(), MSAbstractLaneChangeModel::updateExpectedSublaneSpeeds(), MSAbstractLaneChangeModel::wantsChange(), and MSAbstractLaneChangeModel::wantsChangeSublane().
std::vector<MSLane*> MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow protected inherited
Definition at line 423 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getShadowLane(), and MSAbstractLaneChangeModel::setNoShadowPartialOccupator().
int MSAbstractLaneChangeModel::myOwnState protected inherited
The current state of the vehicle.
Definition at line 390 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), _patchSpeed(), MSLCM_JE2013::_wantsChange(), _wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLCM_DK2008::amBlockingFollower(), MSLCM_JE2013::amBlockingFollower(), amBlockingFollower(), MSLCM_SL2015::amBlockingFollower(), MSLCM_DK2008::amBlockingFollowerNB(), MSLCM_JE2013::amBlockingFollowerNB(), amBlockingFollowerNB(), MSLCM_SL2015::amBlockingFollowerNB(), MSLCM_DK2008::amBlockingFollowerPlusNB(), MSLCM_JE2013::amBlockingFollowerPlusNB(), amBlockingFollowerPlusNB(), MSLCM_SL2015::amBlockingFollowerPlusNB(), MSLCM_DK2008::amBlockingLeader(), MSLCM_JE2013::amBlockingLeader(), amBlockingLeader(), MSLCM_SL2015::amBlockingLeader(), MSLCM_DK2008::changed(), MSLCM_SL2015::changed(), MSLCM_JE2013::changed(), changed(), MSAbstractLaneChangeModel::getOwnState(), MSLCM_DK2008::inform(), MSLCM_JE2013::inform(), MSLCM_SL2015::inform(), inform(), MSLCM_DK2008::patchSpeed(), MSLCM_DK2008::prepareStep(), MSLCM_SL2015::prepareStep(), MSLCM_JE2013::prepareStep(), prepareStep(), MSAbstractLaneChangeModel::primaryLaneChanged(), MSLCM_SL2015::setOwnState(), MSAbstractLaneChangeModel::setOwnState(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
std::vector<MSLane*> MSAbstractLaneChangeModel::myPartiallyOccupatedByShadow protected inherited
list of lanes where the shadow vehicle is partial occupator
Definition at line 419 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::setShadowPartialOccupator().
std::vector<MSLane*> MSAbstractLaneChangeModel::myShadowFurtherLanes protected inherited
Definition at line 409 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::getShadowFurtherLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
std::vector<SUMOReal> MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat protected inherited
Definition at line 410 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat(), and MSAbstractLaneChangeModel::updateShadowLane().
MSLane* MSAbstractLaneChangeModel::myShadowLane protected inherited
A lane that is partially occupied by the front of the vehicle but that is not the primary lane.
Definition at line 405 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::setShadowLane(), and MSAbstractLaneChangeModel::updateShadowLane().
const SUMOReal MSLCM_LC2013::mySpeedGainParam protected
Definition at line 199 of file MSLCM_LC2013.h.
Referenced by MSLCM_LC2013().
SUMOReal MSLCM_LC2013::mySpeedGainProbability protected
a value for tracking the probability that a change to the offset with the same sign is beneficial
Definition at line 179 of file MSLCM_LC2013.h.
Referenced by _wantsChange(), changed(), and prepareStep().
const SUMOReal MSLCM_LC2013::myStrategicParam protected
Definition at line 197 of file MSLCM_LC2013.h.
Referenced by _wantsChange(), and MSLCM_LC2013().
MSVehicle& MSAbstractLaneChangeModel::myVehicle protected inherited
The vehicle this lane-changer belongs to.
Definition at line 387 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), _patchSpeed(), MSLCM_JE2013::_wantsChange(), _wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSAbstractLaneChangeModel::cancelRequest(), MSLCM_JE2013::changed(), MSLCM_SL2015::changed(), changed(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::checkStrategicChange(), MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::congested(), MSLCM_SL2015::decideDirection(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), MSLCM_JE2013::inform(), MSLCM_SL2015::inform(), inform(), MSLCM_DK2008::informBlocker(), MSLCM_JE2013::informFollower(), informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), informLeader(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), MSLCM_SL2015::keepLatGap(), MSLCM_SL2015::msg(), MSLCM_JE2013::MSLCM_JE2013(), MSLCM_LC2013(), MSLCM_DK2008::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), patchSpeed(), MSAbstractLaneChangeModel::predInteraction(), MSLCM_SL2015::prepareStep(), MSAbstractLaneChangeModel::primaryLaneChanged(), MSAbstractLaneChangeModel::removeShadowApproachingInformation(), MSLCM_JE2013::saveBlockerLength(), saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), MSAbstractLaneChangeModel::updateShadowLane(), MSLCM_JE2013::wantsChange(), wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
std::vector<SUMOReal> MSLCM_LC2013::myVSafes protected
Definition at line 192 of file MSLCM_LC2013.h.
Referenced by _patchSpeed(), _wantsChange(), changed(), inform(), informFollower(), informLeader(), prepareStep(), and slowDownForBlocked().
The documentation for this class was generated from the following files:
MSLCM_LC2013.h
MSLCM_LC2013.cpp