SUMO - Simulation of Urban MObility: NBConnection.cpp File Reference
NBConnection.cpp File Reference
#include <config.h>
#include <sstream>
#include <iostream>
#include <cassert>
#include "NBEdgeCont.h"
#include "NBEdge.h"
#include "NBConnection.h"
Functions
bool operator< (const NBConnection &c1, const NBConnection &c2)
std::ostream & operator<< (std::ostream &os, const NBConnection &c)
Detailed Description
Author
Daniel Krajzewicz
Jakob Erdmann
Michael Behrisch
Date
Sept 2002
Version
Id
NBConnection.cpp 21182 2016-07-18 06:46:01Z behrisch
Definition in file NBConnection.cpp.
Function Documentation
bool operator< (const NBConnection & c1, const NBConnection & c2)
Definition at line 173 of file NBConnection.cpp.
References NBConnection::myFromID, NBConnection::myFromLane, NBConnection::myToID, and NBConnection::myToLane.
std::ostream& operator<< (std::ostream & os, const NBConnection & c)
Definition at line 259 of file NBConnection.cpp.
References NBConnection::getFrom(), NBConnection::getFromLane(), Named::getIDSecure(), NBConnection::getTLIndex(), NBConnection::getTo(), and NBConnection::getToLane().