SUMO - Simulation of Urban MObility: NBDistribution Class Reference
NBDistribution Class Reference
The base class for statistical distribution descriptions.
#include <NBDistribution.h>
Static Public Member Functions
static void clear ()
static bool dictionary (const std::string &type, const std::string &id, Distribution *d)
static Distribution * dictionary (const std::string &type, const std::string &id)
Private Types
typedef std::map< std::string, Distribution * > DistDict
typedef std::map< std::string, DistDict > TypedDistDict
Static Private Attributes
static TypedDistDict myDict
Detailed Description
The base class for statistical distribution descriptions.
Definition at line 46 of file NBDistribution.h.
Member Typedef Documentation
typedef std::map<std::string, Distribution*> NBDistribution::DistDict private
Definition at line 54 of file NBDistribution.h.
typedef std::map<std::string, DistDict> NBDistribution::TypedDistDict private
Definition at line 55 of file NBDistribution.h.
Member Function Documentation
void NBDistribution::clear () static
Definition at line 81 of file NBDistribution.cpp.
References myDict.
Referenced by main().
bool NBDistribution::dictionary (const std::string & type, const std::string & id, Distribution * d) static
Definition at line 46 of file NBDistribution.cpp.
References myDict.
Referenced by NIVissimDistrictConnection::getRealSpeed(), NIVissimEdge::getRealSpeed(), NIImporter_Vissim::NIVissimXMLHandler_Geschwindigkeitsverteilungsdefinition::myEndElement(), NIVissimSingleTypeParser_Geschwindigkeitsverteilungsdefinition::parse(), NIVissimSingleTypeParser_Zeitenverteilungsdefinition::parse(), and NIVissimSingleTypeParser_Laengenverteilungsdefinition::parse().
Distribution * NBDistribution::dictionary (const std::string & type, const std::string & id) static
Definition at line 65 of file NBDistribution.cpp.
References myDict.
Field Documentation
NBDistribution::TypedDistDict NBDistribution::myDict static private
Definition at line 56 of file NBDistribution.h.
Referenced by clear(), and dictionary().
The documentation for this class was generated from the following files:
NBDistribution.h
NBDistribution.cpp