SUMO - Simulation of Urban MObility: NBContHelper::straightness_sorter Class Reference
NBContHelper::straightness_sorter Class Reference
#include <NBContHelper.h>
Public Member Functions
int operator() (NBEdge *e1, NBEdge *e2) const
comparing operation
straightness_sorter (NBEdge *e)
constructor
Private Attributes
SUMOReal myReferenceAngle
Position myReferencePos
Detailed Description
straightness_sorter Class to sort edges according to how straight thei are in relation to the reference edge
Definition at line 104 of file NBContHelper.h.
Constructor & Destructor Documentation
NBContHelper::straightness_sorter::straightness_sorter (NBEdge * e) inline explicit
constructor
Definition at line 107 of file NBContHelper.h.
References NBContHelper::relative_outgoing_edge_sorter::operator()().
Member Function Documentation
int NBContHelper::straightness_sorter::operator() (NBEdge * e1, NBEdge * e2) const
comparing operation
Definition at line 182 of file NBContHelper.cpp.
References NBEdge::ANGLE_LOOKAHEAD, NBEdge::getGeometry(), NBEdge::getLaneShape(), NBEdge::getLength(), NBEdge::getShapeStartAngle(), GeomHelper::legacyDegree(), MAX2(), NBHelpers::normRelAngle(), PositionVector::positionAtOffset2D(), and SUMOReal.
Field Documentation
SUMOReal NBContHelper::straightness_sorter::myReferenceAngle private
Definition at line 118 of file NBContHelper.h.
Position NBContHelper::straightness_sorter::myReferencePos private
Definition at line 117 of file NBContHelper.h.
The documentation for this class was generated from the following files:
NBContHelper.h
NBContHelper.cpp