SUMO - Simulation of Urban MObility: SUMOSAXReader Class Reference
SUMOSAXReader Class Reference
SAX-reader encapsulation containing binary reader.
#include <SUMOSAXReader.h>
Data Structures
class LocalSchemaResolver
Public Member Functions
void parse (std::string systemID)
bool parseFirst (std::string systemID)
bool parseNext ()
void parseString (std::string content)
void setHandler (GenericSAXHandler &handler)
Sets the given handler as content and error handler for the reader.
void setValidation (const XERCES_CPP_NAMESPACE::SAX2XMLReader::ValSchemes validationScheme)
SUMOSAXReader (GenericSAXHandler &handler, const XERCES_CPP_NAMESPACE::SAX2XMLReader::ValSchemes validationScheme)
Constructor.
~SUMOSAXReader ()
Destructor.
Private Member Functions
XERCES_CPP_NAMESPACE::SAX2XMLReader * getSAXReader ()
Builds a reader.
const SUMOSAXReader & operator= (const SUMOSAXReader &s)
invalidated assignment operator
SUMOSAXReader (const SUMOSAXReader &s)
invalidated copy constructor
Private Attributes
BinaryInputDevice * myBinaryInput
GenericSAXHandler * myHandler
LocalSchemaResolver mySchemaResolver
XERCES_CPP_NAMESPACE::XMLPScanToken myToken
XERCES_CPP_NAMESPACE::SAX2XMLReader::ValSchemes myValidationScheme
Information whether built reader/parser shall validate XML-documents against schemata.
XERCES_CPP_NAMESPACE::SAX2XMLReader * myXMLReader
Detailed Description
SAX-reader encapsulation containing binary reader.
This class generates on demand either a SAX2XMLReader or parses the SUMO binary xml. The interface is inspired by but not identical to SAX2XMLReader.
Definition at line 58 of file SUMOSAXReader.h.
Constructor & Destructor Documentation
SUMOSAXReader::SUMOSAXReader (GenericSAXHandler & handler, const XERCES_CPP_NAMESPACE::SAX2XMLReader::ValSchemes validationScheme)
Constructor.
Parameters
[in] file The name of the processed file
Definition at line 56 of file SUMOSAXReader.cpp.
SUMOSAXReader::~SUMOSAXReader ()
Destructor.
Definition at line 61 of file SUMOSAXReader.cpp.
References myBinaryInput, and myXMLReader.
SUMOSAXReader::SUMOSAXReader (const SUMOSAXReader & s) private
invalidated copy constructor
Member Function Documentation
XERCES_CPP_NAMESPACE::SAX2XMLReader * SUMOSAXReader::getSAXReader () private
Builds a reader.
Tries to build a SAX2XMLReader using XMLReaderFactory::createXMLReader. If this fails, 0 is returned. Otherwise the validation is set matching the value of "myEnableValidation". If validation is not wanted, a WFXMLScanner is used (see http://www.ibm.com/developerworks/library/x-xercesperf.html).
Returns
The built Xerces-SAX-reader, 0 if something failed
Definition at line 196 of file SUMOSAXReader.cpp.
References myHandler, mySchemaResolver, and myValidationScheme.
Referenced by parse(), parseFirst(), and parseString().
const SUMOSAXReader& SUMOSAXReader::operator= (const SUMOSAXReader & s) private
invalidated assignment operator
void SUMOSAXReader::parse (std::string systemID)
Definition at line 96 of file SUMOSAXReader.cpp.
References getSAXReader(), myXMLReader, parseFirst(), and parseNext().
bool SUMOSAXReader::parseFirst (std::string systemID)
Definition at line 121 of file SUMOSAXReader.cpp.
References getSAXReader(), myBinaryInput, myToken, myValidationScheme, myXMLReader, and parseNext().
Referenced by PCNetProjectionLoader::load(), parse(), and SUMORouteLoader::SUMORouteLoader().
bool SUMOSAXReader::parseNext ()
Definition at line 161 of file SUMOSAXReader.cpp.
References BinaryFormatter::BF_XML_TAG_END, BinaryFormatter::BF_XML_TAG_START, myBinaryInput, GenericSAXHandler::myEndElement(), myHandler, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), myToken, myXMLReader, BinaryInputDevice::peek(), and toString().
Referenced by PCNetProjectionLoader::load(), SUMORouteLoader::loadUntil(), parse(), and parseFirst().
void SUMOSAXReader::parseString (std::string content)
Definition at line 111 of file SUMOSAXReader.cpp.
References getSAXReader(), and myXMLReader.
Referenced by GUISettingsHandler::GUISettingsHandler(), NILoader::loadXMLType(), and main().
void SUMOSAXReader::setHandler (GenericSAXHandler & handler)
Sets the given handler as content and error handler for the reader.
Parameters
[in] handler The handler to assign to the reader
Definition at line 68 of file SUMOSAXReader.cpp.
References myHandler, and myXMLReader.
void SUMOSAXReader::setValidation (const XERCES_CPP_NAMESPACE::SAX2XMLReader::ValSchemes validationScheme)
Definition at line 78 of file SUMOSAXReader.cpp.
References mySchemaResolver, myValidationScheme, and myXMLReader.
Field Documentation
BinaryInputDevice* SUMOSAXReader::myBinaryInput private
Definition at line 117 of file SUMOSAXReader.h.
Referenced by parseFirst(), parseNext(), and ~SUMOSAXReader().
GenericSAXHandler* SUMOSAXReader::myHandler private
Definition at line 108 of file SUMOSAXReader.h.
Referenced by getSAXReader(), parseNext(), and setHandler().
LocalSchemaResolver SUMOSAXReader::mySchemaResolver private
Definition at line 119 of file SUMOSAXReader.h.
Referenced by getSAXReader(), and setValidation().
XERCES_CPP_NAMESPACE::XMLPScanToken SUMOSAXReader::myToken private
Definition at line 113 of file SUMOSAXReader.h.
Referenced by parseFirst(), and parseNext().
XERCES_CPP_NAMESPACE::SAX2XMLReader::ValSchemes SUMOSAXReader::myValidationScheme private
Information whether built reader/parser shall validate XML-documents against schemata.
Definition at line 111 of file SUMOSAXReader.h.
Referenced by getSAXReader(), parseFirst(), and setValidation().
XERCES_CPP_NAMESPACE::SAX2XMLReader* SUMOSAXReader::myXMLReader private
Definition at line 115 of file SUMOSAXReader.h.
Referenced by parse(), parseFirst(), parseNext(), parseString(), setHandler(), setValidation(), and ~SUMOSAXReader().
The documentation for this class was generated from the following files:
SUMOSAXReader.h
SUMOSAXReader.cpp