SUMO - Simulation of Urban MObility: NIImporter_DlrNavteq::TrafficlightsHandler Class Reference
NIImporter_DlrNavteq::TrafficlightsHandler Class Reference
Importer of traffic lights stored in DLRNavteq's (aka elmar) format.
#include <NIImporter_DlrNavteq.h>
Public Member Functions
bool report (const std::string &result)
Parsing method.
TrafficlightsHandler (NBNodeCont &nc, NBTrafficLightLogicCont &tlc, NBEdgeCont &ne, const std::string &file)
Constructor.
~TrafficlightsHandler ()
Destructor.
Protected Attributes
NBEdgeCont & myEdgeCont
The edge container to get the referenced edges from.
NBNodeCont & myNodeCont
The node container to get the referenced nodes from.
NBTrafficLightLogicCont & myTLLogicCont
The traffic lights container to add built tls to.
Private Member Functions
TrafficlightsHandler & operator= (const TrafficlightsHandler &)
Invalidated assignment operator.
TrafficlightsHandler (const TrafficlightsHandler &)
Invalidated copy constructor.
Detailed Description
Importer of traffic lights stored in DLRNavteq's (aka elmar) format.
Being a LineHandler, this class retrieves each line from a LineReader and parses these information assuming they contain traffic light definitions in DLRNavteq's format.
Definition at line 256 of file NIImporter_DlrNavteq.h.
Constructor & Destructor Documentation
NIImporter_DlrNavteq::TrafficlightsHandler::TrafficlightsHandler (NBNodeCont & nc, NBTrafficLightLogicCont & tlc, NBEdgeCont & ne, const std::string & file)
Constructor.
Parameters
[in] nc The node control to retrieve nodes from
Definition at line 404 of file NIImporter_DlrNavteq.cpp.
References UNUSED_PARAMETER.
NIImporter_DlrNavteq::TrafficlightsHandler::~TrafficlightsHandler ()
Destructor.
Definition at line 415 of file NIImporter_DlrNavteq.cpp.
NIImporter_DlrNavteq::TrafficlightsHandler::TrafficlightsHandler (const TrafficlightsHandler &) private
Invalidated copy constructor.
Member Function Documentation
TrafficlightsHandler& NIImporter_DlrNavteq::TrafficlightsHandler::operator= (const TrafficlightsHandler &) private
Invalidated assignment operator.
bool NIImporter_DlrNavteq::TrafficlightsHandler::report (const std::string & result) virtual
Parsing method.
Implementation of the LineHandler-interface called by a LineReader; interprets the retrieved information and alters the nodes.
Parameters
[in] result The read line
Returns
Whether the parsing shall continue
Exceptions
ProcessError if something fails
See also
LineHandler::report
Implements LineHandler.
Definition at line 419 of file NIImporter_DlrNavteq.cpp.
References StringBijection< T >::get(), StringTokenizer::get(), Named::getID(), OptionsCont::getOptions(), NBNode::getPosition(), NBEdge::getToNode(), NBNode::getType(), NBTrafficLightLogicCont::insert(), myEdgeCont, myTLLogicCont, NODETYPE_TRAFFIC_LIGHT, NBNode::reinit(), NBEdgeCont::retrieve(), SUMOXMLDefinitions::TrafficLightTypes, StringTokenizer::WHITECHARS, and WRITE_WARNING.
Field Documentation
NBEdgeCont& NIImporter_DlrNavteq::TrafficlightsHandler::myEdgeCont protected
The edge container to get the referenced edges from.
Definition at line 291 of file NIImporter_DlrNavteq.h.
Referenced by report().
NBNodeCont& NIImporter_DlrNavteq::TrafficlightsHandler::myNodeCont protected
The node container to get the referenced nodes from.
Definition at line 285 of file NIImporter_DlrNavteq.h.
NBTrafficLightLogicCont& NIImporter_DlrNavteq::TrafficlightsHandler::myTLLogicCont protected
The traffic lights container to add built tls to.
Definition at line 288 of file NIImporter_DlrNavteq.h.
Referenced by report().
The documentation for this class was generated from the following files:
NIImporter_DlrNavteq.h
NIImporter_DlrNavteq.cpp