SUMO - Simulation of Urban MObility: METriggeredCalibrator Class Reference
METriggeredCalibrator Class Reference
Calibrates the flow on a segment to a specified one.
#include <METriggeredCalibrator.h>
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
SUMOTime execute (SUMOTime currentTime)
const std::string & getFileName () const
returns the current file name
SUMOTime getFirstDepart () const
returns the first departure time that was ever read
const std::string & getID () const
Returns the id.
SUMOTime getLastDepart () const
Returns the last loaded depart time.
METriggeredCalibrator (const std::string &id, const MSEdge *const edge, const SUMOReal pos, const std::string &aXMLFilename, const std::string &outputFilename, const SUMOTime freq, const SUMOReal length, const MSRouteProbe *probe)
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void setID (const std::string &newID)
resets the id
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
virtual ~METriggeredCalibrator ()
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Static Public Member Functions
static bool checkStopPos (SUMOReal &startPos, SUMOReal &endPos, const SUMOReal laneLength, const SUMOReal minLength, const bool friendlyPos)
check start and end position of a stop
static void cleanup ()
cleanup remaining data structures
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
static MTRand * getParsingRNG ()
Protected Member Functions
void addParam (const SUMOSAXAttributes &attrs)
assign arbitrary vehicle parameters
void addStop (const SUMOSAXAttributes &attrs)
Processing of a stop.
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
bool checkLastDepart ()
Checks whether the route file is sorted by departure time if needed.
int clearedInJam () const
void closeContainer ()
Ends the processing of a container.
void closeFlow ()
Ends the processing of a flow.
void closePerson ()
Ends the processing of a person.
void closeRoute (const bool mayBeDisconnected=false)
void closeRouteDistribution ()
void closeVehicle ()
Ends the processing of a vehicle.
void closeVehicleTypeDistribution ()
void init ()
int inserted () const
bool invalidJam () const
returns whether the segment is jammed although it should not be
bool invalidJam (int laneIndex) const
bool isActive () const
bool isCurrentStateActive (SUMOTime time)
int maximumInflow () const
returns the maximum number of vehicles that could enter from upstream until the calibrator is activated again
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
void openRoute (const SUMOSAXAttributes &attrs)
void openRouteDistribution (const SUMOSAXAttributes &attrs)
void openVehicleTypeDistribution (const SUMOSAXAttributes &attrs)
void parseFromViaTo (std::string element, const SUMOSAXAttributes &attrs)
Called for parsing from and to and the corresponding taz attributes.
bool parseStop (SUMOVehicleParameter::Stop &stop, const SUMOSAXAttributes &attrs, std::string errorSuffix, MsgHandler *const errorOutput)
parses attributes common to all stops
SUMOReal parseWalkPos (SumoXMLAttr attr, const std::string &id, const MSEdge *edge, const std::string &val)
void parseWalkPositions (const SUMOSAXAttributes &attrs, const std::string &personID, const MSEdge *fromEdge, const MSEdge *&toEdge, SUMOReal &departPos, SUMOReal &arrivalPos, MSStoppingPlace *&bs, bool &ok)
@ brief parse depart- and arrival positions of a walk
int passed () const
void registerLastDepart ()
save last depart (only to be used if vehicle is not discarded)
int remainingVehicleCapacity () const
returns the number of vehicles (of the current type) that still fit onto the segment
int remainingVehicleCapacity (int laneIndex) const
int removed () const
bool removePending ()
remove any vehicles which are scheduled for removal. return true if removals took place
void reset ()
reset collected vehicle data
bool scheduleRemoval (MSVehicle *veh)
try to schedule the givne vehicle for removal. return true if it isn't already scheduled
int totalWished () const
number of vehicles expected to pass this interval
bool tryEmit (MESegment *s, MEVehicle *vehicle)
bool tryEmit (MSLane *lane, MSVehicle *vehicle)
void updateMeanData ()
do nothing
void writeXMLOutput ()
inherited from GenericSAXHandler
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
virtual void myEndElement (int element)
Called on the closing of a tag;.
Protected Attributes
MSTransportable::MSTransportablePlan * myActiveContainerPlan
The plan of the current container.
MSTransportable::MSTransportablePlan * myActivePlan
The plan of the current person.
ConstMSEdgeVector myActiveRoute
The current route.
const RGBColor * myActiveRouteColor
The currently parsed route's color.
std::string myActiveRouteID
The id of the current route.
SUMOReal myActiveRouteProbability
The probability of the current route.
std::string myActiveRouteRefID
The id of the route the current route references to.
std::vector< SUMOVehicleParameter::Stop > myActiveRouteStops
List of the stops on the parsed route.
bool myAddVehiclesDirectly
Information whether vehicles shall be directly added to the network or kept within the buffer.
bool myAmActive
whether the calibrator was active when last checking
SUMOTime myBeginDefault
The default value for flow begins.
int myClearedInJam
The number of vehicles that were removed when clearin a jam.
SUMOReal myCurrentCosts
The currently parsed route costs.
RandomDistributor< const MSRoute * > * myCurrentRouteDistribution
The currently parsed distribution of routes (probability->route)
std::string myCurrentRouteDistributionID
The id of the currently parsed route distribution.
std::vector< AspiredState >::const_iterator myCurrentStateInterval
Iterator pointing to the current interval.
SUMOVTypeParameter * myCurrentVType
The currently parsed vehicle type.
RandomDistributor< MSVehicleType * > * myCurrentVTypeDistribution
The currently parsed distribution of vehicle types (probability->vehicle type)
std::string myCurrentVTypeDistributionID
The id of the currently parsed vehicle type distribution.
SUMOReal myDefaultSpeed
The default (maximum) speed on the segment.
bool myDidInit
The information whether init was called.
bool myDidSpeedAdaption
The information whether speed was adapted in the current interval.
const MSEdge *const myEdge
the edge on which this calibrator lies
MSMeanData_Net::MSLaneMeanDataValues myEdgeMeanData
accumlated data for the whole edge
SUMOTime myEndDefault
The default value for flow ends.
SUMOTime myFirstDepart
the first read departure time
SUMOTime myFrequency
The frequeny with which to check for calibration.
bool myHaveWarnedAboutClearingJam
The default (maximum) speed on the segment.
std::string myID
The name of the object.
IDSupplier myIdSupplier
generates numerical ids
int myInserted
The number of vehicles that were inserted in the current interval.
int myInsertStopEdgesAt
where stop edges can be inserted into the current route (-1 means no insertion)
std::vector< AspiredState > myIntervals
List of adaptation intervals.
std::vector< MSMeanData_Net::MSLaneMeanDataValues * > myLaneMeanData
data collector for the calibrator
SUMOTime myLastDepart
The insertion time of the vehicle read last.
OutputDevice * myOutput
The device for xml statistics.
const SUMOReal myPos
the position on the edge where this calibrator lies
const MSRouteProbe *const myProbe
the route probe to retrieve routes from
int myRemoved
The number of vehicles that were removed in the current interval.
bool mySpeedIsDefault
The information whether the speed adaption has been reset.
std::set< std::string > myToRemove
set of vehicle ids to remove
SUMOVehicleParameter * myVehicleParameter
Parameter of the current vehicle, trip, person, container or flow.
std::vector< VehicleRemover * > myVehicleRemovers
Static Protected Attributes
static std::vector< MSMoveReminder * > LeftoverReminders
static std::vector< SUMOVehicleParameter * > LeftoverVehicleParameters
static MTRand myParsingRNG
A random number generator used to choose from vtype/route distributions and computing the speed factors.
Private Attributes
MESegment * mySegment
mesoscopic edge segment the calibrator lies on
Detailed Description
Calibrates the flow on a segment to a specified one.
Definition at line 46 of file METriggeredCalibrator.h.
Constructor & Destructor Documentation
METriggeredCalibrator::METriggeredCalibrator (const std::string & id, const MSEdge *const edge, const SUMOReal pos, const std::string & aXMLFilename, const std::string & outputFilename, const SUMOTime freq, const SUMOReal length, const MSRouteProbe * probe)
constructor
Definition at line 62 of file METriggeredCalibrator.cpp.
References MESegment::addDetector(), Named::getID(), MSCalibrator::myEdgeMeanData, mySegment, and MSMoveReminder::setDescription().
METriggeredCalibrator::~METriggeredCalibrator () virtual
destructor
Definition at line 75 of file METriggeredCalibrator.cpp.
References MSCalibrator::myCurrentStateInterval, MSCalibrator::myEdgeMeanData, MSCalibrator::myIntervals, mySegment, MESegment::removeDetector(), and MSCalibrator::writeXMLOutput().
Member Function Documentation
void SUMORouteHandler::addParam (const SUMOSAXAttributes & attrs) protected inherited
assign arbitrary vehicle parameters
Definition at line 249 of file SUMORouteHandler.cpp.
References Parameterised::addParameter(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getString(), SUMOSAXAttributes::hasAttribute(), SUMORouteHandler::myCurrentVType, SUMORouteHandler::myVehicleParameter, SUMO_ATTR_KEY, and SUMO_ATTR_VALUE.
Referenced by SUMORouteHandler::getFirstDepart(), and SUMORouteHandler::myStartElement().
void MSRouteHandler::addStop (const SUMOSAXAttributes & attrs) protected virtual inherited
Processing of a stop.
Implements SUMORouteHandler.
Definition at line 900 of file MSRouteHandler.cpp.
References SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, SUMORouteHandler::checkStopPos(), SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::depart, SUMOVehicleParameter::departPos, MSLane::dictionary(), SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, MSStoppingPlace::getBeginLanePosition(), MSNet::getBusStop(), MSNet::getChargingStation(), MSNet::getContainerStop(), MSLane::getEdge(), MSStoppingPlace::getEndLanePosition(), MsgHandler::getErrorInstance(), Named::getID(), MSNet::getInstance(), MSStoppingPlace::getLane(), MSEdge::getLanes(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, SUMOVehicleParameter::Stop::lane, MAX2(), MSRouteHandler::myActiveContainerPlan, MSRouteHandler::myActivePlan, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteStops, SUMORouteHandler::myInsertStopEdgesAt, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::parseStop(), POSITION_EPS, SUMOVehicleParameter::Stop::startPos, SUMOVehicleParameter::stops, SUMO_ATTR_ACTTYPE, SUMO_ATTR_ENDPOS, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_STARTPOS, SUMOReal, SUMOVehicleParameter::Stop::until, WRITE_ERROR, and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG().
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 192 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 175 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
bool SUMORouteHandler::checkLastDepart () protected inherited
Checks whether the route file is sorted by departure time if needed.
Definition at line 78 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, SUMOVehicleParameter::id, SUMORouteHandler::myLastDepart, SUMORouteHandler::myVehicleParameter, and WRITE_WARNING.
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeVehicle(), and SUMORouteHandler::getFirstDepart().
bool SUMORouteHandler::checkStopPos (SUMOReal & startPos, SUMOReal & endPos, const SUMOReal laneLength, const SUMOReal minLength, const bool friendlyPos) static inherited
check start and end position of a stop
Definition at line 211 of file SUMORouteHandler.cpp.
Referenced by NLTriggerBuilder::addAccess(), MSRouteHandler::addStop(), RORouteHandler::addStop(), NLTriggerBuilder::parseAndBuildChargingStation(), NLTriggerBuilder::parseAndBuildStoppingPlace(), and RONetHandler::parseStoppingPlace().
void MSCalibrator::cleanup () static inherited
cleanup remaining data structures
Definition at line 457 of file MSCalibrator.cpp.
References MSCalibrator::LeftoverReminders, and MSCalibrator::LeftoverVehicleParameters.
Referenced by MSNet::clearAll().
int MSCalibrator::clearedInJam () const inline protected inherited
Definition at line 182 of file MSCalibrator.h.
References MSCalibrator::myClearedInJam, MSCalibrator::remainingVehicleCapacity(), MSCalibrator::reset(), and MSCalibrator::updateMeanData().
Referenced by GUICalibrator::getParameterWindow().
void MSRouteHandler::closeContainer () protected virtual inherited
Ends the processing of a container.
Implements SUMORouteHandler.
Definition at line 831 of file MSRouteHandler.cpp.
References MSTransportableControl::buildContainer(), SUMORouteHandler::checkLastDepart(), GenericSAXHandler::error(), MSNet::getContainerControl(), MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOVehicleParameter::id, MSRouteHandler::myActiveContainerPlan, MSRouteHandler::myAddVehiclesDirectly, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), and SUMOVehicleParameter::vtypeid.
Referenced by MSRouteHandler::getParsingRNG().
void MSRouteHandler::closeFlow () protected virtual inherited
Ends the processing of a flow.
Implements SUMORouteHandler.
Definition at line 858 of file MSRouteHandler.cpp.
References SUMORouteHandler::checkLastDepart(), MSRouteHandler::closeRoute(), SUMOVehicleParameter::depart, MSRoute::dictionary(), MSNet::getInstance(), OptionsCont::getOptions(), SUMOVehicleParameter::id, SUMORouteHandler::myActiveRouteID, MSRouteHandler::myAddVehiclesDirectly, SUMORouteHandler::myInsertStopEdgesAt, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), SUMOVehicleParameter::repetitionNumber, SUMOVehicleParameter::repetitionOffset, SUMOVehicleParameter::repetitionProbability, SUMOVehicleParameter::repetitionsDone, SUMOVehicleParameter::routeid, SUMOVehicleParameter::setParameter, string2time(), VEHPARS_FORCE_REROUTE, and SUMOVehicleParameter::vtypeid.
Referenced by MSRouteHandler::getParsingRNG().
void MSRouteHandler::closePerson () protected virtual inherited
Ends the processing of a person.
Implements SUMORouteHandler.
Definition at line 797 of file MSRouteHandler.cpp.
References MSTransportableControl::buildPerson(), SUMORouteHandler::checkLastDepart(), MSRouteHandler::deleteActivePlans(), GenericSAXHandler::error(), MSNet::getInstance(), MSNet::getPersonControl(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOVehicleParameter::id, MSRouteHandler::myActivePlan, MSRouteHandler::myAddVehiclesDirectly, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), and SUMOVehicleParameter::vtypeid.
Referenced by MSRouteHandler::getParsingRNG().
void MSRouteHandler::closeRoute (const bool mayBeDisconnected = false) protected virtual inherited
closes (ends) the building of a route. Afterwards no edges may be added to it; this method may throw exceptions when a) the route is empty or b) another route with the same id already exists
Implements SUMORouteHandler.
Definition at line 533 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), MSRoute::addReference(), MSRoute::dictionary(), MSEdge::EDGEFUNCTION_DISTRICT, MSNet::getInstance(), MSGlobals::gStateLoaded, SUMOVehicleParameter::id, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteColor, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteProbability, SUMORouteHandler::myActiveRouteRefID, SUMORouteHandler::myActiveRouteStops, SUMORouteHandler::myCurrentCosts, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMOVehicleParameter::repetitionNumber, and MSRoute::setCosts().
Referenced by MSRouteHandler::closeFlow(), MSRouteHandler::getParsingRNG(), and MSRouteHandler::myEndElement().
void MSRouteHandler::closeRouteDistribution () protected virtual inherited
closes (ends) the building of a distribution
Implements SUMORouteHandler.
Definition at line 650 of file MSRouteHandler.cpp.
References MSRoute::dictionary(), RandomDistributor< T >::getOverallProb(), MSGlobals::gStateLoaded, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myCurrentRouteDistributionID, MSRouteHandler::myParsingRNG, and SUMORouteHandler::myVehicleParameter.
Referenced by MSRouteHandler::getParsingRNG().
void MSRouteHandler::closeVehicle () protected virtual inherited
Ends the processing of a vehicle.
Implements SUMORouteHandler.
Definition at line 672 of file MSRouteHandler.cpp.
References MSInsertionControl::add(), MSRoute::addReference(), MSVehicleControl::addVehicle(), MSVehicleControl::addWaiting(), MSRoute::begin(), MSVehicleControl::buildVehicle(), SUMORouteHandler::checkLastDepart(), DEFAULT_VTYPE_ID, MSVehicleControl::deleteVehicle(), SUMOVehicleParameter::depart, DEPART_CONTAINER_TRIGGERED, DEPART_GIVEN, DEPART_TRIGGERED, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departProcedure, MSRoute::dictionary(), MSGlobals::gCheckRoutes, MSRoute::getEdges(), MSNet::getInsertionControl(), MSNet::getInstance(), MSEdge::getLanes(), OptionsCont::getOptions(), SUMOVehicle::getParameter(), MSVehicleControl::getQuota(), SUMOVehicle::getRoute(), MSVehicleControl::getVehicle(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), MSGlobals::gStateLoaded, MSGlobals::gUseMesoSim, SUMOVehicleParameter::id, SUMORouteHandler::myActiveRouteID, MSRouteHandler::myAddVehiclesDirectly, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), MSVehicleControl::registerOneWaitingForContainer(), MSVehicleControl::registerOneWaitingForPerson(), MSRoute::release(), SUMOVehicleParameter::routeid, string2time(), toString(), SUMOVehicleParameter::vtypeid, and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG(), and MSRouteHandler::myEndElement().
void MSRouteHandler::closeVehicleTypeDistribution () protected virtual inherited
closes (ends) the building of a distribution
Implements SUMORouteHandler.
Definition at line 434 of file MSRouteHandler.cpp.
References MSNet::getInstance(), RandomDistributor< T >::getOverallProb(), MSGlobals::gStateLoaded, MSRouteHandler::myCurrentVTypeDistribution, and MSRouteHandler::myCurrentVTypeDistributionID.
Referenced by MSRouteHandler::getParsingRNG().
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 211 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), MSRouteHandler::myStartElement(), and MSRouteHandler::parseWalkPos().
SUMOTime METriggeredCalibrator::execute (SUMOTime currentTime) virtual
the implementation of the MSTrigger / Command interface. Calibrating takes place here.
Reimplemented from MSCalibrator.
Definition at line 97 of file METriggeredCalibrator.cpp.
References MSVehicleControl::buildVehicle(), MSRoute::contains(), MSVehicleControl::deleteVehicle(), DELTA_T, SUMOVehicleParameter::depart, MSRoute::dictionary(), MSBaseVehicle::getEdge(), MESegment::getEdge(), OptionsCont::getFloat(), Named::getID(), MSNet::getInstance(), MESegment::getNextInsertionTime(), MESegment::getNextSegment(), OptionsCont::getOptions(), MSRouteProbe::getRoute(), MELoop::getSegmentForEdge(), MSEdge::getSpeedLimit(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), MSGlobals::gMesoNet, SUMOVehicleParameter::id, invalidJam(), MSCalibrator::isCurrentStateActive(), MAX2(), maximumInflow(), MEVehicle::moveRoutePointer(), MSCalibrator::myClearedInJam, MSCalibrator::myCurrentStateInterval, MSCalibrator::myDefaultSpeed, MSCalibrator::myDidSpeedAdaption, MSCalibrator::myEdge, MSCalibrator::myEdgeMeanData, MSCalibrator::myFrequency, MSCalibrator::myHaveWarnedAboutClearingJam, Named::myID, MSCalibrator::myInserted, MSCalibrator::myIntervals, MSCalibrator::myProbe, MSCalibrator::myRemoved, mySegment, MSCalibrator::mySpeedIsDefault, passed(), MESegment::prepareDetectorForWriting(), remainingVehicleCapacity(), MSMeanData_Net::MSLaneMeanDataValues::reset(), SUMOVehicleParameter::routeid, MEVehicle::setEventTime(), MSEdge::setMaxSpeed(), MEVehicle::setSegment(), MESegment::setSpeed(), STEPS2TIME, SUMOReal, TIME2STEPS, time2string(), toString(), tryEmit(), MESegment::vaporizeAnyCar(), SUMOVehicleParameter::vtypeid, WRITE_WARNING, and MSCalibrator::writeXMLOutput().
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 217 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), MSStateHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
SUMOTime SUMORouteHandler::getFirstDepart () const inline inherited
returns the first departure time that was ever read
Definition at line 74 of file SUMORouteHandler.h.
References SUMORouteHandler::addParam(), SUMORouteHandler::addStop(), SUMORouteHandler::checkLastDepart(), SUMORouteHandler::closeContainer(), SUMORouteHandler::closeFlow(), SUMORouteHandler::closePerson(), SUMORouteHandler::closeRoute(), SUMORouteHandler::closeRouteDistribution(), SUMORouteHandler::closeVehicle(), SUMORouteHandler::closeVehicleTypeDistribution(), SUMORouteHandler::myEndElement(), SUMORouteHandler::myFirstDepart, SUMORouteHandler::myStartElement(), SUMORouteHandler::openRoute(), SUMORouteHandler::openRouteDistribution(), SUMORouteHandler::openVehicleTypeDistribution(), SUMORouteHandler::parseStop(), and SUMORouteHandler::registerLastDepart().
Referenced by SUMORouteLoader::getFirstDepart().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciBusOrContainerStop(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNEConnectorFrame::buildIinternalLanes(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), NLDetectorBuilder::convUncontE2PosLength(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSVehicle::getBackPosition(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), GNEEdge::getDest(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), MSE2Collector::getEstimateQueueLength(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), GNEEdge::getSource(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSE2Collector::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_SL2015::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_LC2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_ArealDetector::processGet(), TraCIServerAPI_Lane::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), MSBaseVehicle::reroute(), MSLane::resetPartialOccupation(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), MSLane::saveState(), MSDevice_Battery::setAirDragCoefficient(), NBNodeCont::setAsTLControlled(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), MSDevice_Battery::setConstantPowerIntake(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), MSDevice_Battery::setFrontSurfaceArea(), MSDevice_Battery::setInternalMomentOfInertia(), GNEJunction::setLogicValid(), MSDevice_Battery::setMass(), MSDevice_Battery::setMaximumBatteryCapacity(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSDevice_Battery::setPropulsionEfficiency(), MSDevice_Battery::setRadialDragCoefficient(), MSDevice_Battery::setRecuperationEfficiency(), MSLink::setRequestInformation(), MSDevice_Battery::setRollDragCoefficient(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), operator<<(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
SUMOTime SUMORouteHandler::getLastDepart () const inherited
Returns the last loaded depart time.
Definition at line 72 of file SUMORouteHandler.cpp.
References SUMORouteHandler::myLastDepart.
Referenced by SUMORouteLoader::loadUntil().
static MTRand* MSRouteHandler::getParsingRNG () inline static inherited
Definition at line 70 of file MSRouteHandler.h.
References MSRouteHandler::addStop(), MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::closeVehicle(), MSRouteHandler::closeVehicleTypeDistribution(), MSRouteHandler::myEndElement(), MSRouteHandler::myParsingRNG, MSRouteHandler::myStartElement(), MSRouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), MSRouteHandler::openVehicleTypeDistribution(), MSRouteHandler::parseFromViaTo(), MSRouteHandler::parseWalkPos(), MSRouteHandler::parseWalkPositions(), and SUMOReal.
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MSVehicleControl::computeRandomDepartOffset(), MSInsertionControl::determineCandidates(), main(), and GUILoadThread::run().
void MSCalibrator::init () protected inherited
Definition at line 111 of file MSCalibrator.cpp.
References MSEventControl::ADAPT_AFTER_EXECUTION, MSEventControl::addEvent(), MSNet::getEndOfTimestepEvents(), MSNet::getInstance(), MSCalibrator::myCurrentStateInterval, MSCalibrator::myDidInit, Named::myID, MSCalibrator::myIntervals, SUMOTime_MAX, and WRITE_WARNING.
Referenced by MSCalibrator::MSCalibrator(), and MSCalibrator::myEndElement().
int MSCalibrator::inserted () const inline protected inherited
Definition at line 176 of file MSCalibrator.h.
References MSCalibrator::myInserted.
Referenced by GUICalibrator::getParameterWindow().
bool METriggeredCalibrator::invalidJam () const protected
returns whether the segment is jammed although it should not be
Definition at line 236 of file METriggeredCalibrator.cpp.
References MESegment::getBruttoOccupancy(), MESegment::getEdge(), MESegment::getMeanSpeed(), MSEdge::getSpeedLimit(), maximumInflow(), mySegment, and remainingVehicleCapacity().
Referenced by execute(), and passed().
bool MSCalibrator::invalidJam (int laneIndex) const protected inherited
Definition at line 409 of file MSCalibrator.cpp.
References MSEdge::getLanes(), MSEdge::getSpeedLimit(), MSCalibrator::myEdge, and MSCalibrator::remainingVehicleCapacity().
Referenced by MSCalibrator::execute(), and MSCalibrator::passed().
bool MSCalibrator::isActive () const inline protected inherited
Definition at line 136 of file MSCalibrator.h.
References MSCalibrator::myAmActive.
Referenced by GUICalibrator::drawGL(), and GUICalibrator::getParameterWindow().
bool MSCalibrator::isCurrentStateActive (SUMOTime time) protected inherited
Definition at line 237 of file MSCalibrator.cpp.
References MSCalibrator::myCurrentStateInterval, and MSCalibrator::myIntervals.
Referenced by execute(), and MSCalibrator::execute().
int METriggeredCalibrator::maximumInflow () const inline protected
returns the maximum number of vehicles that could enter from upstream until the calibrator is activated again
Definition at line 86 of file METriggeredCalibrator.h.
References MESegment::getMinimumHeadwayTime(), MSCalibrator::myFrequency, mySegment, and SUMOReal.
Referenced by execute(), and invalidJam().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 227 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void MSCalibrator::myEndElement (int element) protected virtual inherited
Called on the closing of a tag;.
Parameters
[in] element ID of the currently closed element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myEndElement
Reimplemented from MSRouteHandler.
Definition at line 192 of file MSCalibrator.cpp.
References MSCalibrator::init(), MSCalibrator::myDidInit, MSRouteHandler::myEndElement(), SUMO_TAG_CALIBRATOR, and SUMO_TAG_FLOW.
void MSCalibrator::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual inherited
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from MSRouteHandler.
Definition at line 139 of file MSCalibrator.cpp.
References MSCalibrator::AspiredState::begin, DEFAULT_VTYPE_ID, DEPART_LANE_ALLOWED_FREE, DEPART_LANE_DEFAULT, DEPART_SPEED_DEFAULT, DEPART_SPEED_MAX, SUMOVehicleParameter::departLaneProcedure, SUMOVehicleParameter::departSpeedProcedure, MSCalibrator::AspiredState::end, MSNet::getInstance(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getSUMOTimeReporting(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), MSCalibrator::LeftoverVehicleParameters, Named::myID, MSCalibrator::myIntervals, MSRouteHandler::myStartElement(), SUMOVehicleParserHelper::parseVehicleAttributes(), MSCalibrator::AspiredState::q, SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_ATTR_SPEED, SUMO_ATTR_VEHSPERHOUR, SUMO_TAG_FLOW, SUMOReal, MSCalibrator::AspiredState::v, MSCalibrator::AspiredState::vehicleParameter, SUMOVehicleParameter::vtypeid, and WRITE_ERROR.
void MSRouteHandler::openRoute (const SUMOSAXAttributes & attrs) protected virtual inherited
opens a route for reading
Implements SUMORouteHandler.
Definition at line 454 of file MSRouteHandler.cpp.
References DEFAULT_VEH_PROB, MSRoute::dictionary(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), RandomDistributor< T >::getProbs(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteColor, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteProbability, SUMORouteHandler::myActiveRouteRefID, SUMORouteHandler::myCurrentCosts, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myCurrentRouteDistributionID, SUMORouteHandler::myInsertStopEdgesAt, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, MSEdge::parseEdgesList(), SUMO_ATTR_COLOR, SUMO_ATTR_COST, SUMO_ATTR_EDGES, SUMO_ATTR_ID, SUMO_ATTR_PROB, SUMO_ATTR_REFID, SUMOReal, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG().
void MSRouteHandler::openRouteDistribution (const SUMOSAXAttributes & attrs) protected virtual inherited
opens a route distribution for reading
Implements SUMORouteHandler.
Definition at line 603 of file MSRouteHandler.cpp.
References TplConvert::_2SUMORealSec(), RandomDistributor< T >::add(), MSRoute::addReference(), MSRoute::dictionary(), SUMOSAXAttributes::get(), SUMOSAXAttributes::hasAttribute(), StringTokenizer::hasNext(), SUMOVehicleParameter::id, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myCurrentRouteDistributionID, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, StringTokenizer::next(), SUMO_ATTR_ID, SUMO_ATTR_PROBS, SUMO_ATTR_ROUTES, SUMOReal, toString(), and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG().
void MSRouteHandler::openVehicleTypeDistribution (const SUMOSAXAttributes & attrs) protected virtual inherited
opens a type distribution for reading
Implements SUMORouteHandler.
Definition at line 412 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), SUMOSAXAttributes::get(), MSVehicleType::getDefaultProbability(), MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOSAXAttributes::hasAttribute(), MSRouteHandler::myCurrentVTypeDistribution, MSRouteHandler::myCurrentVTypeDistributionID, MSRouteHandler::myParsingRNG, SUMO_ATTR_ID, and SUMO_ATTR_VTYPES.
Referenced by MSRouteHandler::getParsingRNG().
void MSRouteHandler::parseFromViaTo (std::string element, const SUMOSAXAttributes & attrs) protected inherited
Called for parsing from and to and the corresponding taz attributes.
Parameters
[in] element description of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
Definition at line 110 of file MSRouteHandler.cpp.
References MSEdge::dictionary(), SUMOVehicleParameter::fromTaz, OptionsCont::getBool(), MSEdge::getNumPredecessors(), MSEdge::getNumSuccessors(), SUMOSAXAttributes::getOpt(), OptionsCont::getOptions(), StringTokenizer::getVector(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myInsertStopEdgesAt, SUMORouteHandler::myVehicleParameter, MSEdge::parseEdgesList(), SUMOVehicleParameter::routeid, SUMO_ATTR_FROM, SUMO_ATTR_ROUTE, SUMO_ATTR_TO, SUMO_ATTR_VIA, SUMOVehicleParameter::toTaz, VEHPARS_FROM_TAZ_SET, VEHPARS_TO_TAZ_SET, SUMOVehicleParameter::via, SUMOVehicleParameter::wasSet(), and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG(), and MSRouteHandler::myStartElement().
bool SUMORouteHandler::parseStop (SUMOVehicleParameter::Stop & stop, const SUMOSAXAttributes & attrs, std::string errorSuffix, MsgHandler *const errorOutput) protected inherited
parses attributes common to all stops
Definition at line 263 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::Stop::awaitedContainers, SUMOVehicleParameter::Stop::awaitedPersons, SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::Stop::index, MsgHandler::inform(), SUMOVehicleParameter::Stop::lane, SUMOVehicleParameter::Stop::parking, SUMOSAXAttributes::parseStringSet(), SUMOVehicleParameter::Stop::setParameter, STOP_CONTAINER_TRIGGER_SET, STOP_END_SET, STOP_EXPECTED_CONTAINERS_SET, STOP_EXPECTED_SET, STOP_INDEX_END, STOP_INDEX_FIT, STOP_PARKING_SET, STOP_START_SET, STOP_TRIGGER_SET, SUMO_ATTR_BUS_STOP, SUMO_ATTR_CHARGING_STATION, SUMO_ATTR_CONTAINER_STOP, SUMO_ATTR_CONTAINER_TRIGGERED, SUMO_ATTR_DURATION, SUMO_ATTR_ENDPOS, SUMO_ATTR_EXPECTED, SUMO_ATTR_EXPECTED_CONTAINERS, SUMO_ATTR_INDEX, SUMO_ATTR_PARKING, SUMO_ATTR_STARTPOS, SUMO_ATTR_TRIGGERED, SUMO_ATTR_UNTIL, SUMOVehicleParameter::Stop::triggered, and SUMOVehicleParameter::Stop::until.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), and SUMORouteHandler::getFirstDepart().
SUMOReal MSRouteHandler::parseWalkPos (SumoXMLAttr attr, const std::string & id, const MSEdge * edge, const std::string & val) protected inherited
Definition at line 1085 of file MSRouteHandler.cpp.
References ARRIVAL_POS_MAX, ARRIVAL_POS_RANDOM, GenericSAXHandler::error(), MSEdge::getLength(), SUMOVehicleParameter::interpretEdgePos(), MSRouteHandler::myParsingRNG, SUMOVehicleParameter::parseArrivalPos(), MTRand::rand(), SUMO_TAG_WALK, SUMOReal, and toString().
Referenced by MSRouteHandler::getParsingRNG(), and MSRouteHandler::parseWalkPositions().
void MSRouteHandler::parseWalkPositions (const SUMOSAXAttributes & attrs, const std::string & personID, const MSEdge * fromEdge, const MSEdge *& toEdge, SUMOReal & departPos, SUMOReal & arrivalPos, MSStoppingPlace *& bs, bool & ok) protected inherited
@ brief parse depart- and arrival positions of a walk
Definition at line 1039 of file MSRouteHandler.cpp.
References SUMOSAXAttributes::get(), MSStoppingPlace::getBeginLanePosition(), MSNet::getBusStop(), MSLane::getEdge(), MSStoppingPlace::getEndLanePosition(), Named::getID(), MSNet::getInstance(), MSStoppingPlace::getLane(), SUMOSAXAttributes::getOpt(), MSStoppingPlace::hasAccess(), SUMOSAXAttributes::hasAttribute(), NUMERICAL_EPS, MSRouteHandler::parseWalkPos(), SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_BUS_STOP, SUMO_ATTR_DEPARTPOS, SUMOReal, toString(), and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG(), and MSRouteHandler::myStartElement().
int METriggeredCalibrator::passed () const inline protected virtual
Reimplemented from MSCalibrator.
Definition at line 68 of file METriggeredCalibrator.h.
References invalidJam(), MSCalibrator::myEdgeMeanData, MSMeanData_Net::MSLaneMeanDataValues::nVehDeparted, MSMeanData_Net::MSLaneMeanDataValues::nVehEntered, MSMeanData_Net::MSLaneMeanDataValues::nVehVaporized, remainingVehicleCapacity(), and reset().
Referenced by execute().
void SUMORouteHandler::registerLastDepart () protected inherited
save last depart (only to be used if vehicle is not discarded)
Definition at line 90 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, SUMOVehicleParameter::line, SUMORouteHandler::myFirstDepart, SUMORouteHandler::myLastDepart, and SUMORouteHandler::myVehicleParameter.
Referenced by MSRouteHandler::closeContainer(), RORouteHandler::closeContainer(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closePerson(), RORouteHandler::closePerson(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), and SUMORouteHandler::getFirstDepart().
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 167 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
int METriggeredCalibrator::remainingVehicleCapacity () const protected
returns the number of vehicles (of the current type) that still fit onto the segment
Definition at line 247 of file METriggeredCalibrator.cpp.
References MSNet::getInstance(), MSVehicleType::getLengthWithGap(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), MSCalibrator::myCurrentStateInterval, mySegment, MESegment::remainingVehicleCapacity(), and SUMOVehicleParameter::vtypeid.
Referenced by execute(), invalidJam(), and passed().
int MSCalibrator::remainingVehicleCapacity (int laneIndex) const protected inherited
Definition at line 432 of file MSCalibrator.cpp.
References MSVehicleType::getCarFollowModel(), MSCFModel::getHeadwayTime(), MSNet::getInstance(), MSEdge::getLanes(), MSEdge::getLength(), MSVehicleType::getLengthWithGap(), MSVehicle::getPositionOnLane(), MSEdge::getSpeedLimit(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), MAX2(), MSCalibrator::myCurrentStateInterval, MSCalibrator::myEdge, SUMOReal, and SUMOVehicleParameter::vtypeid.
Referenced by MSCalibrator::clearedInJam(), and MSCalibrator::invalidJam().
int MSCalibrator::removed () const inline protected inherited
Definition at line 179 of file MSCalibrator.h.
References MSCalibrator::myRemoved.
Referenced by GUICalibrator::getParameterWindow().
bool MSCalibrator::removePending () protected inherited
remove any vehicles which are scheduled for removal. return true if removals took place
Definition at line 258 of file MSCalibrator.cpp.
References Named::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicleControl::getVehicle(), MSNet::getVehicleControl(), MSCalibrator::myToRemove, MSMoveReminder::NOTIFICATION_VAPORIZED, MSVehicle::onRemovalFromNet(), MSLane::removeVehicle(), MSVehicleControl::scheduleVehicleRemoval(), and WRITE_WARNING.
Referenced by MSCalibrator::execute(), and MSCalibrator::scheduleRemoval().
void METriggeredCalibrator::reset () protected virtual
reset collected vehicle data
Reimplemented from MSCalibrator.
Definition at line 255 of file METriggeredCalibrator.cpp.
References MSCalibrator::myEdgeMeanData, and MSMeanData_Net::MSLaneMeanDataValues::reset().
Referenced by passed().
bool MSCalibrator::scheduleRemoval (MSVehicle * veh) inline protected inherited
try to schedule the givne vehicle for removal. return true if it isn't already scheduled
Definition at line 200 of file MSCalibrator.h.
References MSBaseVehicle::getID(), MSCalibrator::myToRemove, and MSCalibrator::removePending().
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
int MSCalibrator::totalWished () const protected inherited
number of vehicles expected to pass this interval
Definition at line 247 of file MSCalibrator.cpp.
References MSCalibrator::myCurrentStateInterval, MSCalibrator::myIntervals, STEPS2TIME, and SUMOReal.
Referenced by MSCalibrator::execute(), GUICalibrator::getParameterWindow(), and MSCalibrator::passed().
bool METriggeredCalibrator::tryEmit (MESegment * s, MEVehicle * vehicle) protected
Definition at line 85 of file METriggeredCalibrator.cpp.
References MSVehicleControl::addVehicle(), SUMOVehicleParameter::depart, Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSBaseVehicle::getParameter(), MSNet::getVehicleControl(), and MESegment::initialise().
Referenced by execute().
bool MSCalibrator::tryEmit (MSLane * lane, MSVehicle * vehicle) protected inherited
void METriggeredCalibrator::updateMeanData () inline protected virtual
do nothing
Reimplemented from MSCalibrator.
Definition at line 83 of file METriggeredCalibrator.h.
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 205 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
void MSCalibrator::writeXMLOutput () protected inherited
Definition at line 204 of file MSCalibrator.cpp.
References MSMeanData::MeanDataValues::getSamples(), MSCalibrator::myClearedInJam, MSCalibrator::myCurrentStateInterval, MSCalibrator::myDidSpeedAdaption, MSCalibrator::myEdgeMeanData, MSCalibrator::myHaveWarnedAboutClearingJam, Named::myID, MSCalibrator::myInserted, MSCalibrator::myOutput, MSCalibrator::myRemoved, MSMeanData_Net::MSLaneMeanDataValues::nVehDeparted, MSMeanData_Net::MSLaneMeanDataValues::nVehEntered, MSMeanData_Net::MSLaneMeanDataValues::nVehVaporized, MSCalibrator::passed(), MSCalibrator::reset(), STEPS2TIME, SUMOReal, time2string(), toString(), MSMeanData::MeanDataValues::travelledDistance, and MSCalibrator::updateMeanData().
Referenced by execute(), MSCalibrator::execute(), ~METriggeredCalibrator(), and MSCalibrator::~MSCalibrator().
Field Documentation
std::vector< MSMoveReminder * > MSCalibrator::LeftoverReminders static protected inherited
Definition at line 260 of file MSCalibrator.h.
Referenced by MSCalibrator::cleanup(), and MSCalibrator::MSCalibrator().
std::vector< SUMOVehicleParameter * > MSCalibrator::LeftoverVehicleParameters static protected inherited
Definition at line 261 of file MSCalibrator.h.
Referenced by MSCalibrator::cleanup(), and MSCalibrator::myStartElement().
MSTransportable::MSTransportablePlan* MSRouteHandler::myActiveContainerPlan protected inherited
The plan of the current container.
Definition at line 160 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addStop(), MSRouteHandler::closeContainer(), MSRouteHandler::deleteActivePlans(), and MSRouteHandler::myStartElement().
MSTransportable::MSTransportablePlan* MSRouteHandler::myActivePlan protected inherited
The plan of the current person.
Definition at line 157 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addStop(), MSRouteHandler::closePerson(), MSRouteHandler::deleteActivePlans(), and MSRouteHandler::myStartElement().
ConstMSEdgeVector MSRouteHandler::myActiveRoute protected inherited
The current route.
Definition at line 154 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addStop(), MSRouteHandler::closeRoute(), MSRouteHandler::MSRouteHandler(), MSRouteHandler::myStartElement(), MSRouteHandler::openRoute(), and MSRouteHandler::parseFromViaTo().
const RGBColor* SUMORouteHandler::myActiveRouteColor protected inherited
The currently parsed route's color.
Definition at line 169 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
std::string SUMORouteHandler::myActiveRouteID protected inherited
The id of the current route.
Definition at line 160 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::closeVehicle(), MSRouteHandler::myStartElement(), SUMORouteHandler::myStartElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::parseFromViaTo(), and RORouteHandler::parseFromViaTo().
SUMOReal SUMORouteHandler::myActiveRouteProbability protected inherited
The probability of the current route.
Definition at line 166 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), RORouteHandler::myStartElement(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
std::string SUMORouteHandler::myActiveRouteRefID protected inherited
The id of the route the current route references to.
Definition at line 163 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
std::vector<SUMOVehicleParameter::Stop> SUMORouteHandler::myActiveRouteStops protected inherited
List of the stops on the parsed route.
Definition at line 175 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::closeRoute(), and RORouteHandler::closeRoute().
bool MSRouteHandler::myAddVehiclesDirectly protected inherited
Information whether vehicles shall be directly added to the network or kept within the buffer.
Definition at line 163 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), and MSRouteHandler::closeVehicle().
bool MSCalibrator::myAmActive protected inherited
whether the calibrator was active when last checking
Definition at line 256 of file MSCalibrator.h.
Referenced by MSCalibrator::execute(), and MSCalibrator::isActive().
SUMOTime SUMORouteHandler::myBeginDefault protected inherited
The default value for flow begins.
Definition at line 184 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myEndElement(), and SUMORouteHandler::myStartElement().
int MSCalibrator::myClearedInJam protected inherited
The number of vehicles that were removed when clearin a jam.
Definition at line 243 of file MSCalibrator.h.
Referenced by MSCalibrator::clearedInJam(), execute(), MSCalibrator::execute(), MSCalibrator::passed(), and MSCalibrator::writeXMLOutput().
SUMOReal SUMORouteHandler::myCurrentCosts protected inherited
The currently parsed route costs.
Definition at line 172 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
RandomDistributor<const MSRoute*>* MSRouteHandler::myCurrentRouteDistribution protected inherited
The currently parsed distribution of routes (probability->route)
Definition at line 172 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::openRoute(), and MSRouteHandler::openRouteDistribution().
std::string MSRouteHandler::myCurrentRouteDistributionID protected inherited
The id of the currently parsed route distribution.
Definition at line 175 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeRouteDistribution(), MSRouteHandler::openRoute(), and MSRouteHandler::openRouteDistribution().
std::vector<AspiredState>::const_iterator MSCalibrator::myCurrentStateInterval protected inherited
Iterator pointing to the current interval.
Definition at line 223 of file MSCalibrator.h.
Referenced by GUICalibrator::drawGL(), execute(), MSCalibrator::execute(), GUICalibrator::getParameterWindow(), MSCalibrator::init(), MSCalibrator::isCurrentStateActive(), remainingVehicleCapacity(), MSCalibrator::remainingVehicleCapacity(), MSCalibrator::totalWished(), MSCalibrator::writeXMLOutput(), ~METriggeredCalibrator(), and MSCalibrator::~MSCalibrator().
SUMOVTypeParameter* SUMORouteHandler::myCurrentVType protected inherited
The currently parsed vehicle type.
Definition at line 178 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::addParam(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), SUMORouteHandler::myEndElement(), MSRouteHandler::myStartElement(), RORouteHandler::myStartElement(), SUMORouteHandler::myStartElement(), and SUMORouteHandler::~SUMORouteHandler().
RandomDistributor<MSVehicleType*>* MSRouteHandler::myCurrentVTypeDistribution protected inherited
The currently parsed distribution of vehicle types (probability->vehicle type)
Definition at line 166 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeVehicleTypeDistribution(), MSRouteHandler::myEndElement(), and MSRouteHandler::openVehicleTypeDistribution().
std::string MSRouteHandler::myCurrentVTypeDistributionID protected inherited
The id of the currently parsed vehicle type distribution.
Definition at line 169 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeVehicleTypeDistribution(), and MSRouteHandler::openVehicleTypeDistribution().
SUMOReal MSCalibrator::myDefaultSpeed protected inherited
The default (maximum) speed on the segment.
Definition at line 251 of file MSCalibrator.h.
Referenced by execute(), MSCalibrator::execute(), and GUICalibrator::getParameterWindow().
bool MSCalibrator::myDidInit protected inherited
The information whether init was called.
Definition at line 249 of file MSCalibrator.h.
Referenced by MSCalibrator::init(), MSCalibrator::MSCalibrator(), and MSCalibrator::myEndElement().
bool MSCalibrator::myDidSpeedAdaption protected inherited
The information whether speed was adapted in the current interval.
Definition at line 247 of file MSCalibrator.h.
Referenced by execute(), MSCalibrator::execute(), and MSCalibrator::writeXMLOutput().
const MSEdge* const MSCalibrator::myEdge protected inherited
the edge on which this calibrator lies
Definition at line 211 of file MSCalibrator.h.
Referenced by execute(), MSCalibrator::execute(), MSCalibrator::invalidJam(), MSCalibrator::MSCalibrator(), and MSCalibrator::remainingVehicleCapacity().
MSMeanData_Net::MSLaneMeanDataValues MSCalibrator::myEdgeMeanData protected inherited
accumlated data for the whole edge
Definition at line 219 of file MSCalibrator.h.
Referenced by execute(), MSCalibrator::execute(), METriggeredCalibrator(), passed(), MSCalibrator::passed(), reset(), MSCalibrator::reset(), MSCalibrator::updateMeanData(), MSCalibrator::writeXMLOutput(), and ~METriggeredCalibrator().
SUMOTime SUMORouteHandler::myEndDefault protected inherited
The default value for flow ends.
Definition at line 187 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myEndElement(), and SUMORouteHandler::myStartElement().
SUMOTime SUMORouteHandler::myFirstDepart protected inherited
the first read departure time
Definition at line 190 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::getFirstDepart(), and SUMORouteHandler::registerLastDepart().
SUMOTime MSCalibrator::myFrequency protected inherited
The frequeny with which to check for calibration.
Definition at line 237 of file MSCalibrator.h.
Referenced by execute(), MSCalibrator::execute(), and maximumInflow().
bool MSCalibrator::myHaveWarnedAboutClearingJam protected inherited
The default (maximum) speed on the segment.
Definition at line 253 of file MSCalibrator.h.
Referenced by execute(), and MSCalibrator::writeXMLOutput().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), execute(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
IDSupplier SUMORouteHandler::myIdSupplier protected inherited
generates numerical ids
Definition at line 181 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myStartElement().
int MSCalibrator::myInserted protected inherited
The number of vehicles that were inserted in the current interval.
Definition at line 241 of file MSCalibrator.h.
Referenced by execute(), MSCalibrator::execute(), MSCalibrator::inserted(), and MSCalibrator::writeXMLOutput().
int SUMORouteHandler::myInsertStopEdgesAt protected inherited
where stop edges can be inserted into the current route (-1 means no insertion)
Definition at line 193 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::parseFromViaTo(), and RORouteHandler::parseFromViaTo().
std::vector<AspiredState> MSCalibrator::myIntervals protected inherited
List of adaptation intervals.
Definition at line 221 of file MSCalibrator.h.
Referenced by execute(), MSCalibrator::execute(), GUICalibrator::getParameterWindow(), MSCalibrator::init(), MSCalibrator::isCurrentStateActive(), MSCalibrator::myStartElement(), MSCalibrator::totalWished(), ~METriggeredCalibrator(), and MSCalibrator::~MSCalibrator().
std::vector<MSMeanData_Net::MSLaneMeanDataValues*> MSCalibrator::myLaneMeanData protected inherited
data collector for the calibrator
Definition at line 217 of file MSCalibrator.h.
Referenced by MSCalibrator::MSCalibrator(), MSCalibrator::reset(), and MSCalibrator::updateMeanData().
SUMOTime SUMORouteHandler::myLastDepart protected inherited
The insertion time of the vehicle read last.
Definition at line 157 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::checkLastDepart(), SUMORouteHandler::getLastDepart(), and SUMORouteHandler::registerLastDepart().
OutputDevice* MSCalibrator::myOutput protected inherited
The device for xml statistics.
Definition at line 234 of file MSCalibrator.h.
Referenced by MSCalibrator::MSCalibrator(), and MSCalibrator::writeXMLOutput().
MTRand MSRouteHandler::myParsingRNG static protected inherited
A random number generator used to choose from vtype/route distributions and computing the speed factors.
Definition at line 178 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::closeVehicle(), MSRouteHandler::getParsingRNG(), MSRouteHandler::myStartElement(), MSRouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), MSRouteHandler::openVehicleTypeDistribution(), and MSRouteHandler::parseWalkPos().
const SUMOReal MSCalibrator::myPos protected inherited
the position on the edge where this calibrator lies
Definition at line 213 of file MSCalibrator.h.
const MSRouteProbe* const MSCalibrator::myProbe protected inherited
the route probe to retrieve routes from
Definition at line 215 of file MSCalibrator.h.
Referenced by execute(), and MSCalibrator::execute().
int MSCalibrator::myRemoved protected inherited
The number of vehicles that were removed in the current interval.
Definition at line 239 of file MSCalibrator.h.
Referenced by execute(), MSCalibrator::passed(), MSCalibrator::removed(), and MSCalibrator::writeXMLOutput().
MESegment* METriggeredCalibrator::mySegment private
mesoscopic edge segment the calibrator lies on
Definition at line 92 of file METriggeredCalibrator.h.
Referenced by execute(), invalidJam(), maximumInflow(), METriggeredCalibrator(), remainingVehicleCapacity(), and ~METriggeredCalibrator().
bool MSCalibrator::mySpeedIsDefault protected inherited
The information whether the speed adaption has been reset.
Definition at line 245 of file MSCalibrator.h.
Referenced by execute(), and MSCalibrator::execute().
std::set<std::string> MSCalibrator::myToRemove protected inherited
set of vehicle ids to remove
Note
: we avoid keeping vehicle points because someone else might invalidate it before look at it again (i.e. another calibrator)
Definition at line 231 of file MSCalibrator.h.
Referenced by MSCalibrator::removePending(), and MSCalibrator::scheduleRemoval().
SUMOVehicleParameter* SUMORouteHandler::myVehicleParameter protected inherited
Parameter of the current vehicle, trip, person, container or flow.
Definition at line 154 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::addParam(), RORouteHandler::addPersonTrip(), MSRouteHandler::addStop(), RORouteHandler::addStop(), SUMORouteHandler::checkLastDepart(), MSRouteHandler::closeContainer(), RORouteHandler::closeContainer(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closePerson(), RORouteHandler::closePerson(), MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), SUMORouteHandler::myEndElement(), MSRouteHandler::myStartElement(), RORouteHandler::myStartElement(), SUMORouteHandler::myStartElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), RORouteHandler::openRouteDistribution(), MSRouteHandler::parseFromViaTo(), RORouteHandler::parseFromViaTo(), and SUMORouteHandler::registerLastDepart().
std::vector<VehicleRemover*> MSCalibrator::myVehicleRemovers protected inherited
Definition at line 225 of file MSCalibrator.h.
Referenced by MSCalibrator::MSCalibrator(), and MSCalibrator::~MSCalibrator().
The documentation for this class was generated from the following files:
METriggeredCalibrator.h
METriggeredCalibrator.cpp