SUMO - Simulation of Urban MObility: TraCIServerAPI_Simulation Class Reference
TraCIServerAPI_Simulation Class Reference
APIs for getting/setting simulation values via TraCI.
#include <TraCIServerAPI_Simulation.h>
Static Public Member Functions
static bool commandDistanceRequest (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage, int commandId)
static bool commandPositionConversion (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage, int commandId)
static std::pair< MSLane *, SUMOReal > convertCartesianToRoadMap (Position pos)
static const MSLane * getLaneChecking (std::string roadID, int laneIndex, SUMOReal pos)
static bool processGet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a get value command (Command 0xab: Get Simulation Variable)
static bool processSet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a set value command (Command 0xcb: Set Simulation Variable)
static void writeVehicleStateIDs (TraCIServer &server, tcpip::Storage &outputStorage, MSNet::VehicleState state)
static void writeVehicleStateNumber (TraCIServer &server, tcpip::Storage &outputStorage, MSNet::VehicleState state)
Private Member Functions
TraCIServerAPI_Simulation & operator= (const TraCIServerAPI_Simulation &s)
invalidated assignment operator
TraCIServerAPI_Simulation (const TraCIServerAPI_Simulation &s)
invalidated copy constructor
Detailed Description
APIs for getting/setting simulation values via TraCI.
Definition at line 51 of file TraCIServerAPI_Simulation.h.
Constructor & Destructor Documentation
TraCIServerAPI_Simulation::TraCIServerAPI_Simulation (const TraCIServerAPI_Simulation & s) private
invalidated copy constructor
Member Function Documentation
bool TraCIServerAPI_Simulation::commandDistanceRequest (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage, int commandId) static
Definition at line 401 of file TraCIServerAPI_Simulation.cpp.
References SUMOAbstractRouter< E, V >::compute(), convertCartesianToRoadMap(), Position::distanceTo(), MSNet::getCurrentTimeStep(), MSRoute::getDistanceBetween(), MSNet::getInstance(), getLaneChecking(), MSNet::getRouterTT(), POSITION_2D, POSITION_3D, POSITION_ROADMAP, tcpip::Storage::readDouble(), tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), REQUEST_DRIVINGDIST, RTYPE_ERR, Position::set(), SUMOReal, TYPE_DOUBLE, tcpip::Storage::writeDouble(), TraCIServer::writeStatusCmd(), and tcpip::Storage::writeUnsignedByte().
Referenced by processGet().
bool TraCIServerAPI_Simulation::commandPositionConversion (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage, int commandId) static
Definition at line 308 of file TraCIServerAPI_Simulation.cpp.
References GeoConvHelper::cartesian2geo(), convertCartesianToRoadMap(), GeoConvHelper::getFinal(), getLaneChecking(), MSLane::getShape(), POSITION_2D, POSITION_3D, POSITION_LON_LAT, POSITION_LON_LAT_ALT, POSITION_ROADMAP, PositionVector::positionAtOffset(), tcpip::Storage::readDouble(), tcpip::Storage::readString(), TraCIServer::readTypeCheckingUnsignedByte(), tcpip::Storage::readUnsignedByte(), RTYPE_ERR, Position::set(), SUMOReal, tcpip::Storage::writeDouble(), TraCIServer::writeStatusCmd(), tcpip::Storage::writeString(), tcpip::Storage::writeUnsignedByte(), Position::x(), GeoConvHelper::x2cartesian_const(), Position::y(), and Position::z().
Referenced by processGet().
std::pair< MSLane *, SUMOReal > TraCIServerAPI_Simulation::convertCartesianToRoadMap (Position pos) static
Converts a cartesian position to the closest road map position
Parameters
pos cartesian position that is to be converted
Returns
the closest road map position to the cartesian position
Definition at line 268 of file TraCIServerAPI_Simulation.cpp.
References MSEdge::dictionary(), MSNet::getEdgeControl(), MSEdgeControl::getEdgeNames(), MSNet::getInstance(), max, and SUMOReal.
Referenced by TraCIServerAPI_Vehicle::commandDistanceRequest(), commandDistanceRequest(), and commandPositionConversion().
const MSLane * TraCIServerAPI_Simulation::getLaneChecking (std::string roadID, int laneIndex, SUMOReal pos) static
Converts a road map position to a cartesian position
Parameters
pos road map position that is to be convertes
Returns
closest 2D position
Definition at line 291 of file TraCIServerAPI_Simulation.cpp.
References MSEdge::dictionary(), MSEdge::getLanes(), and MSLane::getLength().
Referenced by TraCIServerAPI_Vehicle::commandDistanceRequest(), commandDistanceRequest(), and commandPositionConversion().
TraCIServerAPI_Simulation& TraCIServerAPI_Simulation::operator= (const TraCIServerAPI_Simulation & s) private
invalidated assignment operator
bool TraCIServerAPI_Simulation::processGet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a get value command (Command 0xab: Get Simulation Variable)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 57 of file TraCIServerAPI_Simulation.cpp.
References CMD_GET_SIM_VARIABLE, commandDistanceRequest(), commandPositionConversion(), DELTA_T, DISTANCE_REQUEST, MSNet::getBusStop(), GeoConvHelper::getConvBoundary(), GeoConvHelper::getFinal(), MSNet::getInstance(), MSStoppingPlace::getTransportableNumber(), TraCIServer::getVehicleStateChanges(), POSITION_CONVERSION, tcpip::Storage::readInt(), tcpip::Storage::readString(), TraCIServer::readTypeCheckingString(), tcpip::Storage::readUnsignedByte(), RESPONSE_GET_SIM_VARIABLE, RTYPE_OK, toHex(), TYPE_BOUNDINGBOX, TYPE_COMPOUND, TYPE_INTEGER, TYPE_STRINGLIST, VAR_ARRIVED_VEHICLES_IDS, VAR_ARRIVED_VEHICLES_NUMBER, VAR_BUS_STOP_WAITING, VAR_DELTA_T, VAR_DEPARTED_VEHICLES_IDS, VAR_DEPARTED_VEHICLES_NUMBER, VAR_LOADED_VEHICLES_IDS, VAR_LOADED_VEHICLES_NUMBER, VAR_MIN_EXPECTED_VEHICLES, VAR_NET_BOUNDING_BOX, VAR_PARKING_ENDING_VEHICLES_IDS, VAR_PARKING_ENDING_VEHICLES_NUMBER, VAR_PARKING_STARTING_VEHICLES_IDS, VAR_PARKING_STARTING_VEHICLES_NUMBER, VAR_STOP_ENDING_VEHICLES_IDS, VAR_STOP_ENDING_VEHICLES_NUMBER, VAR_STOP_STARTING_VEHICLES_IDS, VAR_STOP_STARTING_VEHICLES_NUMBER, VAR_TELEPORT_ENDING_VEHICLES_IDS, VAR_TELEPORT_ENDING_VEHICLES_NUMBER, VAR_TELEPORT_STARTING_VEHICLES_IDS, VAR_TELEPORT_STARTING_VEHICLES_NUMBER, VAR_TIME_STEP, MSNet::VEHICLE_STATE_ARRIVED, MSNet::VEHICLE_STATE_BUILT, MSNet::VEHICLE_STATE_DEPARTED, MSNet::VEHICLE_STATE_ENDING_PARKING, MSNet::VEHICLE_STATE_ENDING_STOP, MSNet::VEHICLE_STATE_ENDING_TELEPORT, MSNet::VEHICLE_STATE_STARTING_PARKING, MSNet::VEHICLE_STATE_STARTING_STOP, MSNet::VEHICLE_STATE_STARTING_TELEPORT, tcpip::Storage::writeDouble(), TraCIServer::writeErrorStatusCmd(), tcpip::Storage::writeInt(), TraCIServer::writeResponseWithLength(), TraCIServer::writeStatusCmd(), tcpip::Storage::writeString(), tcpip::Storage::writeStringList(), tcpip::Storage::writeUnsignedByte(), writeVehicleStateIDs(), writeVehicleStateNumber(), Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by TraCIServer::TraCIServer().
bool TraCIServerAPI_Simulation::processSet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a set value command (Command 0xcb: Set Simulation Variable)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 212 of file TraCIServerAPI_Simulation.cpp.
References MSInsertionControl::clearPendingVehicles(), CMD_CLEAR_PENDING_VEHICLES, CMD_SAVE_SIMSTATE, CMD_SET_SIM_VARIABLE, MSNet::getInsertionControl(), MSNet::getInstance(), tcpip::Storage::readString(), TraCIServer::readTypeCheckingString(), tcpip::Storage::readUnsignedByte(), RTYPE_OK, MSStateHandler::saveState(), toHex(), TraCIServer::writeErrorStatusCmd(), and TraCIServer::writeStatusCmd().
Referenced by TraCIServer::TraCIServer().
void TraCIServerAPI_Simulation::writeVehicleStateIDs (TraCIServer & server, tcpip::Storage & outputStorage, MSNet::VehicleState state) static
Definition at line 260 of file TraCIServerAPI_Simulation.cpp.
References TraCIServer::getVehicleStateChanges(), TYPE_STRINGLIST, tcpip::Storage::writeStringList(), and tcpip::Storage::writeUnsignedByte().
Referenced by processGet().
void TraCIServerAPI_Simulation::writeVehicleStateNumber (TraCIServer & server, tcpip::Storage & outputStorage, MSNet::VehicleState state) static
Definition at line 252 of file TraCIServerAPI_Simulation.cpp.
References TraCIServer::getVehicleStateChanges(), TYPE_INTEGER, tcpip::Storage::writeInt(), and tcpip::Storage::writeUnsignedByte().
Referenced by processGet().
The documentation for this class was generated from the following files:
TraCIServerAPI_Simulation.h
TraCIServerAPI_Simulation.cpp