SUMO - Simulation of Urban MObility: GUIMEVehicle Class Reference
GUIMEVehicle Class Reference
A MSVehicle extended by some values for usage within the gui.
#include <GUIMEVehicle.h>
Public Types
typedef Named::NamedLikeComparatorIdLess< SUMOVehicle > ComparatorIdLess
Public Member Functions
virtual void activateReminders (const MSMoveReminder::Notification reason)
"Activates" all current move reminder
virtual void addContainer (MSTransportable *container)
Adds a container to this vehicle.
virtual void addPerson (MSTransportable *person)
Adds a person to this vehicle.
void addReminder (MSMoveReminder *rem)
Adds a MoveReminder dynamically.
bool addStop (const SUMOVehicleParameter::Stop &stopPar, std::string &errorMsg, SUMOTime untilOffset=0)
Adds a stop.
void addStops (const bool ignoreStopErrors)
Adds stops to the built vehicle.
bool drawAction_drawCarriageClass (const GUIVisualizationSettings &s, SUMOVehicleShape guiShape, bool asImage) const
draws the given guiShape if it has distinc carriages/modules and eturns true if so
virtual void drawAction_drawLinkItems (const GUIVisualizationSettings &) const
virtual void drawAction_drawPersonsAndContainers (const GUIVisualizationSettings &) const
virtual void drawAction_drawVehicleBlinker (SUMOReal) const
virtual void drawAction_drawVehicleBlueLight () const
virtual void drawAction_drawVehicleBrakeLight (SUMOReal length, bool onlyOne=false) const
virtual void drawBestLanes () const
Draws the vehicle's best lanes.
void drawName (const Position &pos, const SUMOReal scale, const GUIVisualizationTextSettings &settings, const SUMOReal angle=0) const
draw name of item
void drawRouteHelper (const MSRoute &r, SUMOReal exaggeration) const
Draws the route.
SUMOReal estimateLeaveSpeed (const MSLink *link) const
Returns the vehicle's estimated speed after driving accross the link.
virtual SUMOReal getAcceleration () const
Returns the vehicle's acceleration.
SUMOReal getAngle () const
Return current angle.
virtual SUMOReal getArrivalPos () const
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
SUMOReal getAverageSpeed () const
Returns the vehicle's estimated average speed on the segment assuming no further delays.
SUMOReal getBackPositionOnLane (const MSLane *lane) const
Get the vehicle's position relative to the given lane.
SUMOTime getBlockTime () const
Returns the time at which the vehicle was blocked.
SUMOReal getBlockTimeSeconds () const
Returns the time at which the vehicle was blocked on the current segment.
SUMOReal getChosenSpeedFactor () const
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
SUMOReal getColorValue (int activeScheme) const
gets the color value according to the current scheme index
SUMOReal getConservativeSpeed (SUMOTime &earliestArrival) const
Returns the vehicle's estimated speed taking into account delays.
const MSRouteIterator & getCurrentRouteEdge () const
Returns an iterator pointing to the current edge in this vehicles route.
SUMOReal getCurrentTLSPenaltySeconds () const
Returns the delay that is accrued due to option –meso-tls-penalty.
SUMOTime getDepartDelay () const
Returns the depart delay.
SUMOReal getDepartPos () const
Returns this vehicle's real departure position.
SUMOTime getDeparture () const
Returns this vehicle's real departure time.
MSDevice * getDevice (const std::type_info &type) const
Returns a device of the given type if it exists or 0.
const std::vector< MSDevice * > & getDevices () const
Returns this vehicle's devices.
const MSEdge * getEdge () const
Returns the edge the vehicle is currently at.
SUMOTime getEventTime () const
Returns the (planned) time at which the vehicle leaves his current cell.
SUMOReal getEventTimeSeconds () const
Returns the earliest leave time for the current segment.
const std::string & getID () const
Returns the name of the vehicle.
SUMOReal getImpatience () const
Returns this vehicles impatience.
MSLane * getLane () const
Returns the lane the vehicle is on.
SUMOTime getLastEntryTime () const
Returns the time the vehicle entered the current segment.
SUMOReal getLastEntryTimeSeconds () const
Returns the entry time for the current segment.
SUMOReal getLastLaneChangeOffset () const
Returns the time since the last lane change in seconds.
virtual SUMOReal getLateralPositionOnLane () const
Get the vehicle's lateral position on the lane.
SUMOReal getMaxSpeed () const
Returns the maximum speed.
SUMOReal getNaviDegree () const
return the current angle in navigational degrees
int getNumberReroutes () const
Returns the number of new routes this vehicle got.
const SUMOVehicleParameter & getParameter () const
Returns the vehicle's parameter (including departure definition)
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Position getPosition (const SUMOReal offset=0) const
Return current position (x/y, cartesian)
SUMOReal getPositionOnLane () const
Get the vehicle's position along the lane.
int getQueIndex () const
Returns the index of the que the vehicle is in.
virtual const MSEdge * getRerouteOrigin () const
Returns the starting point for reroutes (usually the current edge)
const MSRoute & getRoute () const
Returns the current route.
MESegment * getSegment () const
Returns the current segment the vehicle is on.
SUMOReal getSlope () const
Returns the slope of the road at vehicle's position.
SUMOReal getSpeed () const
Returns the vehicle's estimated speed assuming no delays.
const ConstMSEdgeVector getStopEdges () const
Returns the list of still pending stop edges.
std::string getStopInfo () const
retrieve information about the current stop state
SUMOTime getStoptime (const MESegment *const seg) const
Returns how long to stop at the given segment.
GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window.
SUMOVehicleClass getVClass () const
Returns the vehicle's access class.
const MSVehicleType & getVehicleType () const
Returns the vehicle's type definition.
SUMOReal getWaitingSeconds () const
Returns the number of seconds waited (speed was lesser than 0.1m/s)
SUMOTime getWaitingTime () const
Returns the duration for which the vehicle was blocked.
GUIMEVehicle (SUMOVehicleParameter *pars, const MSRoute *route, const MSVehicleType *type, const SUMOReal speedFactor)
Constructor.
bool hasArrived () const
Returns whether this vehicle has already arived (reached the arrivalPosition on its final edge)
bool hasDeparted () const
Returns whether this vehicle has already departed.
bool hasValidRoute (std::string &msg, const MSRoute *route=0) const
Validates the current or given route.
virtual bool isFrontOnLane (const MSLane *) const
Returns the information whether the front of the vehhicle is on the given lane.
bool isOnRoad () const
Returns the information whether the vehicle is on a road (is simulated)
bool isParking () const
Returns whether the vehicle is parking.
virtual bool isRemoteControlled () const
Returns the information whether the vehicle is fully controlled via TraCI.
bool isStopped () const
Returns whether the vehicle is at a stop.
bool isStoppedTriggered () const
Returns whether the vehicle is on a triggered stop.
bool mayProceed () const
Returns whether the vehicle is allowed to pass the next junction.
bool moveRoutePointer ()
Update when the vehicle enters a new edge in the move step.
void onDepart ()
Called when the vehicle is inserted into the network.
void removeReminder (MSMoveReminder *rem)
Removes a MoveReminder dynamically.
bool replaceRoute (const MSRoute *route, bool onInit=false, int offset=0)
Replaces the current route by the given one.
bool replaceRouteEdges (ConstMSEdgeVector &edges, bool onInit=false, bool check=false)
Replaces the current route by the given edges.
void reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > &router, const bool onInit=false, const bool withTaz=false)
Performs a rerouting using the given router.
void selectBlockingFoes () const
adds the blocking foes to the current selection
virtual void setArrivalPos (SUMOReal arrivalPos)
Sets this vehicle's desired arrivalPos for its current route.
void setBlockTime (const SUMOTime t)
Sets the time at which the vehicle was blocked.
void setChosenSpeedFactor (const SUMOReal factor)
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
void setEventTime (SUMOTime t, bool hasDelay=true)
Sets the (planned) time at which the vehicle leaves his current cell.
void setLastEntryTime (SUMOTime t)
Sets the entry time for the current segment.
virtual void setSegment (MESegment *s, int idx=0)
Sets the current segment the vehicle is at together with its que.
const MSEdge * succEdge (int nSuccs) const
Returns the nSuccs'th successor of edge the vehicle is currently at.
void updateDetectorForWriting (MSMoveReminder *rem, SUMOTime currentTime, SUMOTime exitTime)
Updates a single vehicle detector if present.
void updateDetectors (SUMOTime currentTime, const bool isLeave, const MSMoveReminder::Notification reason=MSMoveReminder::NOTIFICATION_JUNCTION)
Updates all vehicle detectors.
~GUIMEVehicle ()
destructor
state io
void saveState (OutputDevice &out)
Saves the states of a vehicle.
void loadState (const SUMOSAXAttributes &attrs, const SUMOTime offset)
Loads the state of this vehicle from the given description.
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawOnPos (const GUIVisualizationSettings &s, const Position &pos, const SUMOReal angle) const
Draws the object on the specified position with the specified angle.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additionally triggered visualisations.
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
virtual const std::string & getParentName () const
Returns the name of the parent object (if any)
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static bool setFunctionalColor (int activeScheme, const MSBaseVehicle *veh)
sets the color according to the current scheme index and some vehicle function
Static Public Attributes
static const GUIGlID INVALID_ID = 0
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
void calculateArrivalParams ()
(Re-)Calculates the arrival position and lane from the vehicle parameters
const Position & getSeatPosition (int personIndex) const
returns the seat position for the person with the given index
void setColor (const GUIVisualizationSettings &s) const
sets the color according to the currente settings
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Static Protected Member Functions
static void drawLinkItem (const Position &pos, SUMOTime arrivalTime, SUMOTime leaveTime, SUMOReal exagerate)
Protected Attributes
int myArrivalLane
The destination lane where the vehicle stops.
SUMOReal myArrivalPos
The position on the destination lane where the vehicle stops.
SUMOTime myBlockTime
The time at which the vehicle was blocked on its current segment.
SUMOReal myCarriageLength
Variable to set with the length of the last drawn carriage or the vehicle length.
SUMOReal myChosenSpeedFactor
A precomputed factor by which the driver wants to be faster than the speed limit.
MSRouteIterator myCurrEdge
Iterator to current route-edge.
SUMOReal myDepartPos
The real depart position.
SUMOTime myDeparture
The real departure time.
std::vector< MSDevice * > myDevices
The devices this vehicle has.
SUMOTime myEventTime
The (planned) time of leaving the segment (cell)
SUMOTime myLastEntryTime
The time the vehicle entered its current segment.
MFXMutex myLock
The mutex used to avoid concurrent updates of the vehicle buffer.
int myNumberReroutes
The number of reroutings.
const SUMOVehicleParameter * myParameter
This Vehicle's parameter.
int myQueIndex
Index of the que the vehicle is in (important for multiqueue extension)
const MSRoute * myRoute
This Vehicle's route.
PositionVector mySeatPositions
positions of seats in the vehicle (updated at every drawing step)
MESegment * mySegment
The segment the vehicle is at.
std::map< const MESegment *const, SUMOTime > myStops
where to stop
const MSVehicleType * myType
This Vehicle's type.
Static Protected Attributes
static const SUMOTime NOT_YET_DEPARTED = SUMOTime_MAX
Additional visualisations
bool hasActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) const
Returns whether the named feature is enabled in the given view.
void addActiveAddVisualisation (GUISUMOAbstractView *const parent, int which)
Adds the named visualisation feature to the given view.
void removeActiveAddVisualisation (GUISUMOAbstractView *const parent, int which)
Adds the named visualisation feature to the given view.
void drawRoute (const GUIVisualizationSettings &s, int routeNo, SUMOReal darken) const
Chooses the route to draw and draws it, darkening it as given.
enum VisualisationFeatures {
VO_SHOW_BEST_LANES = 1, VO_SHOW_ROUTE = 2, VO_SHOW_ALL_ROUTES = 4, VO_TRACKED = 8,
VO_SHOW_LFLINKITEMS = 16
}
Additional visualisation feature ids.
std::map< GUISUMOAbstractView *, int > myAdditionalVisualizations
Enabled visualisations, per view.
drawing helper methods
void drawAction_drawVehicleAsBoxPlus () const
void drawAction_drawVehicleAsTrianglePlus () const
void drawAction_drawVehicleAsPoly (const GUIVisualizationSettings &s) const
bool drawAction_drawVehicleAsImage (const GUIVisualizationSettings &s, SUMOReal length=-1) const
static void drawPoly (double *poses, SUMOReal offset)
Move reminder structures
MoveReminderCont myMoveReminders
Current lane's move reminder.
typedef std::vector< std::pair< MSMoveReminder *, SUMOReal > > MoveReminderCont
Definition of a move reminder container.
Detailed Description
A MSVehicle extended by some values for usage within the gui.
A visualisable MSVehicle. Extended by the possibility to retrieve names of all available vehicles (static) and the possibility to retrieve the color of the vehicle which is available in different forms allowing an easier recognition of done actions such as lane changing.
Definition at line 61 of file GUIMEVehicle.h.
Member Typedef Documentation
typedef Named::NamedLikeComparatorIdLess<SUMOVehicle> SUMOVehicle::ComparatorIdLess inherited
Definition at line 68 of file SUMOVehicle.h.
typedef std::vector< std::pair<MSMoveReminder*, SUMOReal> > MSBaseVehicle::MoveReminderCont protected inherited
Definition of a move reminder container.
Definition at line 403 of file MSBaseVehicle.h.
Member Enumeration Documentation
enum GUIBaseVehicle::VisualisationFeatures inherited
Additional visualisation feature ids.
Enumerator
VO_SHOW_BEST_LANES
show vehicle's best lanes
VO_SHOW_ROUTE
show vehicle's current route
VO_SHOW_ALL_ROUTES
show all vehicle's routes
VO_TRACKED
track vehicle
VO_SHOW_LFLINKITEMS
LFLinkItems.
Definition at line 288 of file GUIBaseVehicle.h.
Constructor & Destructor Documentation
GUIMEVehicle::GUIMEVehicle (SUMOVehicleParameter * pars, const MSRoute * route, const MSVehicleType * type, const SUMOReal speedFactor)
Constructor.
Parameters
[in] pars The vehicle description
[in] route The vehicle's route
[in] type The vehicle's type
[in] speedFactor The factor for driven lane's speed limits
Exceptions
ProcessError If a value is wrong
Definition at line 54 of file GUIMEVehicle.cpp.
GUIMEVehicle::~GUIMEVehicle ()
destructor
Definition at line 64 of file GUIMEVehicle.cpp.
Member Function Documentation
void MSBaseVehicle::activateReminders (const MSMoveReminder::Notification reason) virtual inherited
"Activates" all current move reminder
For all move reminder stored in "myMoveReminders", their method "MSMoveReminder::notifyEnter" is called.
Parameters
[in] reason The reason for changing the reminders' states
See also
MSMoveReminder
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented in MSVehicle.
Definition at line 339 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by MSBaseVehicle::getDevices(), MESegment::receive(), and MELoop::teleportVehicle().
void GUIBaseVehicle::addActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) inherited
Adds the named visualisation feature to the given view.
Parameters
[in] parent The view for which the feature shall be enabled
[in] which The visualisation feature to enable
See also
GUISUMOAbstractView::addAdditionalGLVisualisation
Definition at line 1127 of file GUIBaseVehicle.cpp.
References GUISUMOAbstractView::addAdditionalGLVisualisation(), and GUIBaseVehicle::myAdditionalVisualizations.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), and GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack().
void MSBaseVehicle::addContainer (MSTransportable * container) virtual inherited
Adds a container to this vehicle.
The default implementation does nothing since containers are not supported by default
Parameters
[in] container The container to add
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 280 of file MSBaseVehicle.cpp.
Referenced by MSBaseVehicle::getDevices().
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 258 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
void MSBaseVehicle::addPerson (MSTransportable * person) virtual inherited
Adds a person to this vehicle.
The default implementation does nothing since persons are not supported by default
Parameters
[in] person The person to add
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 276 of file MSBaseVehicle.cpp.
Referenced by MSBaseVehicle::getDevices().
void MSBaseVehicle::addReminder (MSMoveReminder * rem) inherited
Adds a MoveReminder dynamically.
Parameters
[in] rem the reminder to add
See also
MSMoveReminder
Definition at line 312 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by MSVehicle::adaptLaneEntering2MoveReminder(), MESegment::addReminders(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), and MSBaseVehicle::getDevices().
bool MEVehicle::addStop (const SUMOVehicleParameter::Stop & stopPar, std::string & errorMsg, SUMOTime untilOffset = 0) virtual inherited
Adds a stop.
The stop is put into the sorted list.
Parameters
[in] stop The stop to add
Returns
Whether the stop could be added
Implements SUMOVehicle.
Definition at line 220 of file MEVehicle.cpp.
References MSEdge::dictionary(), SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, MELoop::getSegmentForEdge(), MSGlobals::gMesoNet, SUMOVehicleParameter::Stop::lane, and MEVehicle::myStops.
Referenced by MEVehicle::getLane().
void MSBaseVehicle::addStops (const bool ignoreStopErrors) inherited
Adds stops to the built vehicle.
This code needs to be separated from the MSBaseVehicle constructor since it is not allowed to call virtual functions from a constructor
Parameters
[in] ignoreStopErrors whether invalid stops trigger a warning only
Definition at line 431 of file MSBaseVehicle.cpp.
References SUMOVehicle::addStop(), OutputDevice::closeTag(), MSMoveReminder::getDescription(), OutputDevice::getDeviceByOption(), MSBaseVehicle::getID(), MSNet::getInstance(), MSRoute::getStops(), OptionsCont::getStringVector(), OptionsCont::isSet(), MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, OutputDevice::openTag(), STEPS2TIME, SUMOVehicleParameter::stops, SUMO_ATTR_ID, SUMO_ATTR_TIME, SUMOReal, toString(), WRITE_WARNING, and OutputDevice::writeAttr().
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), and MSBaseVehicle::setChosenSpeedFactor().
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 187 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 196 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 177 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GNECrossing::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 237 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 206 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 249 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 219 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 228 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIBaseVehicle::getPopUpMenu().
void MSBaseVehicle::calculateArrivalParams () protected inherited
(Re-)Calculates the arrival position and lane from the vehicle parameters
Definition at line 361 of file MSBaseVehicle.cpp.
References ARRIVAL_LANE_GIVEN, ARRIVAL_POS_GIVEN, ARRIVAL_POS_RANDOM, ARRIVAL_SPEED_GIVEN, SUMOVehicleParameter::arrivalLane, SUMOVehicleParameter::arrivalLaneProcedure, SUMOVehicleParameter::arrivalPos, SUMOVehicleParameter::arrivalPosProcedure, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, Named::getID(), MSBaseVehicle::getID(), MSEdge::getLanes(), MSRoute::getLastEdge(), MSVehicleType::getVehicleClass(), MAX2(), MIN2(), MSBaseVehicle::myArrivalLane, MSBaseVehicle::myArrivalPos, MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, MSBaseVehicle::myType, RandHelper::rand(), SUMOReal, toString(), and WRITE_WARNING.
Referenced by MSBaseVehicle::MSBaseVehicle(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), and MSBaseVehicle::setChosenSpeedFactor().
bool GUIMEVehicle::drawAction_drawCarriageClass (const GUIVisualizationSettings & s, SUMOVehicleShape guiShape, bool asImage) const virtual
draws the given guiShape if it has distinc carriages/modules and eturns true if so
Implements GUIBaseVehicle.
Definition at line 171 of file GUIMEVehicle.cpp.
References GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus(), and SUMOReal.
Referenced by getAngle().
virtual void GUIBaseVehicle::drawAction_drawLinkItems (const GUIVisualizationSettings &) const inline virtual inherited
Reimplemented in GUIVehicle.
Definition at line 142 of file GUIBaseVehicle.h.
Referenced by GUIBaseVehicle::drawGLAdditional().
virtual void GUIBaseVehicle::drawAction_drawPersonsAndContainers (const GUIVisualizationSettings &) const inline virtual inherited
Reimplemented in GUIVehicle.
Definition at line 143 of file GUIBaseVehicle.h.
Referenced by GUIBaseVehicle::drawOnPos().
void GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus () const protected inherited
Definition at line 336 of file GUIBaseVehicle.cpp.
References MSVehicleType::getLength(), MSVehicleType::getWidth(), and GUIBaseVehicle::myVType.
Referenced by drawAction_drawCarriageClass(), GUIBaseVehicle::drawAction_drawVehicleAsTrianglePlus(), and GUIBaseVehicle::drawOnPos().
bool GUIBaseVehicle::drawAction_drawVehicleAsImage (const GUIVisualizationSettings & s, SUMOReal length = -1) const protected inherited
Definition at line 806 of file GUIBaseVehicle.cpp.
References GUITexturesHelper::drawTexturedBox(), GUIVisualizationSizeSettings::getExaggeration(), MSVehicleType::getImgFile(), MSVehicleType::getLength(), GUITexturesHelper::getTextureID(), MSVehicleType::getWidth(), GUIBaseVehicle::myVType, SUMOReal, and GUIVisualizationSettings::vehicleSize.
Referenced by GUIVehicle::drawAction_drawRailCarriages(), and GUIBaseVehicle::drawOnPos().
void GUIBaseVehicle::drawAction_drawVehicleAsPoly (const GUIVisualizationSettings & s) const protected inherited
Definition at line 385 of file GUIBaseVehicle.cpp.
References RGBColor::changedBrightness(), GUIBaseVehicle::drawAction_drawCarriageClass(), GLHelper::drawBoxLine(), GLHelper::drawFilledCircle(), GUIBaseVehicle::drawPoly(), GLHelper::getColor(), MSVehicleType::getGuiShape(), MSVehicleType::getLength(), MSVehicleType::getWidth(), RGBColor::GREY, GUIBaseVehicle::myVType, GLHelper::setColor(), SUMOReal, SVS_ANT, SVS_BICYCLE, SVS_BUS, SVS_BUS_COACH, SVS_BUS_FLEXIBLE, SVS_BUS_TROLLEY, SVS_DELIVERY, SVS_E_VEHICLE, SVS_EMERGENCY, SVS_MOPED, SVS_MOTORCYCLE, SVS_PASSENGER, SVS_PASSENGER_HATCHBACK, SVS_PASSENGER_SEDAN, SVS_PASSENGER_VAN, SVS_PASSENGER_WAGON, SVS_PEDESTRIAN, SVS_RAIL, SVS_RAIL_CAR, SVS_RAIL_CARGO, SVS_SHIP, SVS_TRUCK, SVS_TRUCK_1TRAILER, SVS_TRUCK_SEMITRAILER, SVS_UNKNOWN, and vehiclePoly_PassengerCarBody.
Referenced by GUIBaseVehicle::drawOnPos().
void GUIBaseVehicle::drawAction_drawVehicleAsTrianglePlus () const protected inherited
Definition at line 351 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus(), MSVehicleType::getLength(), MSVehicleType::getWidth(), GUIBaseVehicle::myVType, and SUMOReal.
Referenced by GUIBaseVehicle::drawOnPos().
virtual void GUIBaseVehicle::drawAction_drawVehicleBlinker (SUMOReal) const inline virtual inherited
Reimplemented in GUIVehicle.
Definition at line 137 of file GUIBaseVehicle.h.
Referenced by GUIBaseVehicle::drawOnPos().
virtual void GUIBaseVehicle::drawAction_drawVehicleBlueLight () const inline virtual inherited
Reimplemented in GUIVehicle.
Definition at line 146 of file GUIBaseVehicle.h.
References GUIBaseVehicle::addActiveAddVisualisation(), GUIBaseVehicle::drawGL(), GUIBaseVehicle::drawGLAdditional(), GUIBaseVehicle::drawOnPos(), GUIBaseVehicle::getCenteringBoundary(), GUIBaseVehicle::getPopUpMenu(), GUIBaseVehicle::hasActiveAddVisualisation(), GUIBaseVehicle::removeActiveAddVisualisation(), and SUMOReal.
Referenced by GUIBaseVehicle::drawOnPos().
virtual void GUIBaseVehicle::drawAction_drawVehicleBrakeLight (SUMOReal length, bool onlyOne = false) const inline virtual inherited
Reimplemented in GUIVehicle.
Definition at line 138 of file GUIBaseVehicle.h.
References UNUSED_PARAMETER.
Referenced by GUIBaseVehicle::drawOnPos().
virtual void GUIBaseVehicle::drawBestLanes () const inline virtual inherited
Draws the vehicle's best lanes.
Reimplemented in GUIVehicle.
Definition at line 145 of file GUIBaseVehicle.h.
Referenced by GUIBaseVehicle::drawGLAdditional().
void GUIBaseVehicle::drawGL (const GUIVisualizationSettings & s) const virtual inherited
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 983 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::drawOnPos(), GUIBaseVehicle::getAngle(), and GUIBaseVehicle::getPosition().
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUILane::drawGL(), and GUIBaseVehicle::drawGLAdditional().
void GUIBaseVehicle::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additionally triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented from GUIGlObject.
Definition at line 989 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::drawAction_drawLinkItems(), GUIBaseVehicle::drawBestLanes(), GUIBaseVehicle::drawGL(), GUIBaseVehicle::drawRoute(), GUIGlObject::getGlID(), MSBaseVehicle::getNumberReroutes(), GUIGlObject::getType(), GUIBaseVehicle::hasActiveAddVisualisation(), MSBaseVehicle::isOnRoad(), GUIBaseVehicle::myVehicle, SUMOReal, GUIBaseVehicle::VO_SHOW_ALL_ROUTES, GUIBaseVehicle::VO_SHOW_BEST_LANES, GUIBaseVehicle::VO_SHOW_LFLINKITEMS, and GUIBaseVehicle::VO_SHOW_ROUTE.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight().
void GUIBaseVehicle::drawLinkItem (const Position & pos, SUMOTime arrivalTime, SUMOTime leaveTime, SUMOReal exagerate) static protected inherited
Definition at line 1022 of file GUIBaseVehicle.cpp.
References GLHelper::drawFilledCircle(), GLHelper::drawText(), RGBColor::GREEN, STEPS2TIME, toString(), Position::x(), and Position::y().
Referenced by GUIVehicle::drawAction_drawLinkItems().
void GUIGlObject::drawName (const Position & pos, const SUMOReal scale, const GUIVisualizationTextSettings & settings, const SUMOReal angle = 0) const inherited
draw name of item
Definition at line 286 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE3::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GUIPolygon::drawGL(), GNEVariableSpeedSignal::drawGL(), GUILaneSpeedTrigger::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GNERouteProbe::drawGL(), GNEEdge::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIEdge::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GNERerouter::drawGL(), and GUIBaseVehicle::drawOnPos().
void GUIBaseVehicle::drawOnPos (const GUIVisualizationSettings & s, const Position & pos, const SUMOReal angle) const inherited
Draws the object on the specified position with the specified angle.
Parameters
[in] s The settings for the current view (may influence drawing)
[in] pos The position to draw the vehicle on
[in] angle The drawing angle of the vehicle
Definition at line 825 of file GUIBaseVehicle.cpp.
References GUIVisualizationTextSettings::color, GUIBaseVehicle::drawAction_drawCarriageClass(), GUIBaseVehicle::drawAction_drawPersonsAndContainers(), GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus(), GUIBaseVehicle::drawAction_drawVehicleAsImage(), GUIBaseVehicle::drawAction_drawVehicleAsPoly(), GUIBaseVehicle::drawAction_drawVehicleAsTrianglePlus(), GUIBaseVehicle::drawAction_drawVehicleBlinker(), GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::drawAction_drawVehicleBrakeLight(), GUIVisualizationSettings::drawLaneChangePreference, GUIVisualizationSettings::drawMinGap, GUIGlObject::drawName(), GLHelper::drawOutlineCircle(), GLHelper::drawText(), MSLane::geometryPositionAtOffset(), MSBaseVehicle::getDevice(), GUIVisualizationSizeSettings::getExaggeration(), GUIGlObject::getGlID(), MSVehicleType::getGuiShape(), SUMOVehicle::getLane(), MSVehicleType::getLength(), MSVehicleType::getMinGap(), MSBaseVehicle::getParameter(), SUMOVehicle::getPositionOnLane(), MSDevice_BTreceiver::getRange(), GUIGlObject::getType(), GLO_MAX, SUMOVehicleParameter::line, MIN2(), GUIBaseVehicle::myCarriageLength, GUIBaseVehicle::mySeatPositions, GUIBaseVehicle::myVehicle, GUIBaseVehicle::myVType, GUIVisualizationSettings::personName, PI, RAD2DEG, GUIVisualizationSettings::scale, GUIBaseVehicle::setColor(), GUIVisualizationTextSettings::show, GUIVisualizationSettings::showBlinker, GUIVisualizationSettings::showBTRange, GUIVisualizationTextSettings::size, SUMOReal, SVS_ANT, SVS_BICYCLE, SVS_EMERGENCY, SVS_MOPED, SVS_MOTORCYCLE, SVS_PEDESTRIAN, SVS_RAIL, SVS_RAIL_CARGO, SVS_SHIP, GUIVisualizationSettings::vehicleName, GUIVisualizationSettings::vehicleQuality, GUIVisualizationSettings::vehicleSize, Position::x(), and Position::y().
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::drawGL(), and GUIEdge::drawMesoVehicles().
void GUIBaseVehicle::drawPoly (double * poses, SUMOReal offset) static protected inherited
Definition at line 369 of file GUIBaseVehicle.cpp.
Referenced by GUIBaseVehicle::drawAction_drawVehicleAsPoly().
void GUIBaseVehicle::drawRoute (const GUIVisualizationSettings & s, int routeNo, SUMOReal darken) const inherited
Chooses the route to draw and draws it, darkening it as given.
Parameters
[in] s The visualisation settings, needed to determine the vehicle's color
[in] routeNo The route to show (0: the current, >0: prior)
[in] darken The amount to darken the route by
Definition at line 1144 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::drawRouteHelper(), GUIVisualizationSizeSettings::getExaggeration(), MSBaseVehicle::getRoute(), MSDevice_Vehroutes::getRoute(), GUIBaseVehicle::myRoutes, GUIBaseVehicle::myVehicle, GUIBaseVehicle::setColor(), SUMOReal, and GUIVisualizationSettings::vehicleSize.
Referenced by GUIBaseVehicle::drawGLAdditional().
void GUIMEVehicle::drawRouteHelper (const MSRoute & r, SUMOReal exaggeration) const virtual
Draws the route.
Parameters
[in] r The route to draw
Implements GUIBaseVehicle.
Definition at line 224 of file GUIMEVehicle.cpp.
References MSRoute::begin(), GLHelper::drawBoxLines(), MSRoute::end(), GUILane::getShape(), GUILane::getShapeLengths(), GUILane::getShapeRotations(), and SUMOReal.
Referenced by getAngle().
SUMOReal MEVehicle::estimateLeaveSpeed (const MSLink * link) const inherited
Returns the vehicle's estimated speed after driving accross the link.
See also
MSVehicle.cpp::estimateLeaveSpeed
Definition at line 129 of file MEVehicle.cpp.
References MSVehicleType::getCarFollowModel(), MSLink::getLength(), MSCFModel::getMaxAccel(), MEVehicle::getSpeed(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSLink::getViaLaneOrLane(), MIN2(), and SUMOReal.
Referenced by MEVehicle::getLane(), and MESegment::isOpen().
SUMOReal MSBaseVehicle::getAcceleration () const virtual inherited
Returns the vehicle's acceleration.
This default implementation returns always 0.
Returns
The acceleration
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 245 of file MSBaseVehicle.cpp.
References SUMOReal.
Referenced by MSBaseVehicle::getCurrentRouteEdge().
SUMOReal GUIMEVehicle::getAngle () const inline virtual
Return current angle.
Note
implementation of abstract method does not work otherwise
Implements GUIBaseVehicle.
Definition at line 90 of file GUIMEVehicle.h.
References drawAction_drawCarriageClass(), drawRouteHelper(), MEVehicle::getAngle(), getColorValue(), getLastLaneChangeOffset(), getParameterWindow(), getStopInfo(), getTypeParameterWindow(), selectBlockingFoes(), and SUMOReal.
virtual SUMOReal MSBaseVehicle::getArrivalPos () const inline virtual inherited
Returns this vehicle's desired arrivalPos for its current route (may change on reroute)
Returns
This vehicle's real arrivalPos
Implements SUMOVehicle.
Definition at line 250 of file MSBaseVehicle.h.
References MSBaseVehicle::myArrivalPos.
SUMOReal MEVehicle::getAverageSpeed () const inherited
Returns the vehicle's estimated average speed on the segment assuming no further delays.
Returns
The vehicle's estimated average speed
Note
This is only an upper bound. The speed will be lower if the preceeding vehicle is delayed
Definition at line 123 of file MEVehicle.cpp.
References MESegment::getLength(), MEVehicle::myEventTime, MEVehicle::myLastEntryTime, MEVehicle::mySegment, STEPS2TIME, and SUMOReal.
Referenced by MEVehicle::getLane(), and MEVehicle::getSpeed().
SUMOReal MEVehicle::getBackPositionOnLane (const MSLane * lane) const virtual inherited
Get the vehicle's position relative to the given lane.
Returns
The back position of the vehicle (in m from the given lane's begin)
Implements SUMOVehicle.
Definition at line 78 of file MEVehicle.cpp.
References MSVehicleType::getLength(), MEVehicle::getPositionOnLane(), MSBaseVehicle::getVehicleType(), and SUMOReal.
SUMOTime MEVehicle::getBlockTime () const inline inherited
Returns the time at which the vehicle was blocked.
Returns
The blocking time
Definition at line 254 of file MEVehicle.h.
References MEVehicle::myBlockTime.
Referenced by MELoop::checkCar(), and MEVehicle::getBlockTimeSeconds().
SUMOReal MEVehicle::getBlockTimeSeconds () const inline inherited
Returns the time at which the vehicle was blocked on the current segment.
Definition at line 287 of file MEVehicle.h.
References MEVehicle::getBlockTime(), MEVehicle::getCurrentTLSPenaltySeconds(), MEVehicle::loadState(), MEVehicle::mayProceed(), MSMoveReminder::NOTIFICATION_JUNCTION, MEVehicle::replaceRoute(), MEVehicle::saveState(), STEPS2TIME, SUMOReal, MEVehicle::updateDetectorForWriting(), and MEVehicle::updateDetectors().
Referenced by getParameterWindow().
Boundary GUIBaseVehicle::getCenteringBoundary () const virtual inherited
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 327 of file GUIBaseVehicle.cpp.
References Boundary::add(), MSVehicleType::getLength(), GUIBaseVehicle::getPosition(), MSBaseVehicle::getVehicleType(), Boundary::grow(), and GUIBaseVehicle::myVehicle.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight().
SUMOReal MSBaseVehicle::getChosenSpeedFactor () const inline virtual inherited
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
Returns
Speed limit factor
Implements SUMOVehicle.
Definition at line 340 of file MSBaseVehicle.h.
References MSBaseVehicle::myChosenSpeedFactor.
Referenced by getParameterWindow(), GUIVehicle::getParameterWindow(), and TraCIServerAPI_Vehicle::processGet().
SUMOReal GUIMEVehicle::getColorValue (int activeScheme) const virtual
gets the color value according to the current scheme index
Implements GUIBaseVehicle.
Definition at line 178 of file GUIMEVehicle.cpp.
References MSBaseVehicle::getDepartDelay(), MESegment::getEdge(), GUIGlObject::getGlID(), MSBaseVehicle::getNumberReroutes(), MEVehicle::getSegment(), MEVehicle::getSpeed(), MSEdge::getVehicleMaxSpeed(), MEVehicle::getWaitingSeconds(), GLO_VEHICLE, gSelected, GUISelectedStorage::isSelected(), and STEPS2TIME.
Referenced by getAngle().
SUMOReal MEVehicle::getConservativeSpeed (SUMOTime & earliestArrival) const inherited
Returns the vehicle's estimated speed taking into account delays.
Returns
The vehicle's estimated speed
Parameters
[in,out] earliestArrival A lower bound on leaveTime, modified to contain new lower bound on leave Time
Note
This is only an upper bound. The speed may be even lower if there are further delays downstream
Definition at line 138 of file MEVehicle.cpp.
References DELTA_T, MESegment::getLength(), MAX2(), MEVehicle::myEventTime, MEVehicle::myLastEntryTime, MEVehicle::mySegment, and STEPS2TIME.
Referenced by MEVehicle::getLane().
const MSRouteIterator& MSBaseVehicle::getCurrentRouteEdge () const inline virtual inherited
Returns an iterator pointing to the current edge in this vehicles route.
Returns
The current route pointer
Implements SUMOVehicle.
Definition at line 174 of file MSBaseVehicle.h.
References MSBaseVehicle::getAcceleration(), MSBaseVehicle::getSlope(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::onDepart(), MSBaseVehicle::replaceRouteEdges(), MSBaseVehicle::reroute(), and SUMOReal.
Referenced by TraCIServerAPI_Vehicle::vtdMap_matchingRoutePosition().
SUMOReal MEVehicle::getCurrentTLSPenaltySeconds () const inherited
Returns the delay that is accrued due to option –meso-tls-penalty.
Definition at line 267 of file MEVehicle.cpp.
References MESegment::getTLSPenalty(), MEVehicle::mySegment, and STEPS2TIME.
Referenced by MEVehicle::getBlockTimeSeconds(), and getParameterWindow().
SUMOTime MSBaseVehicle::getDepartDelay () const inline virtual inherited
Returns the depart delay.
Implements SUMOVehicle.
Definition at line 234 of file MSBaseVehicle.h.
References SUMOVehicleParameter::depart, MSBaseVehicle::getDeparture(), and MSBaseVehicle::getParameter().
Referenced by getColorValue(), GUIVehicle::getColorValue(), getParameterWindow(), and GUIVehicle::getParameterWindow().
SUMOReal MSBaseVehicle::getDepartPos () const inline virtual inherited
Returns this vehicle's real departure position.
Returns
This vehicle's real departure position
Implements SUMOVehicle.
Definition at line 242 of file MSBaseVehicle.h.
References MSBaseVehicle::myDepartPos.
Referenced by TraCIServerAPI_Vehicle::processGet().
SUMOTime MSBaseVehicle::getDeparture () const inline virtual inherited
Returns this vehicle's real departure time.
Returns
This vehicle's real departure time
Implements SUMOVehicle.
Definition at line 229 of file MSBaseVehicle.h.
References MSBaseVehicle::myDeparture.
Referenced by MSBaseVehicle::getDepartDelay().
MSDevice * MSBaseVehicle::getDevice (const std::type_info & type) const virtual inherited
Returns a device of the given type if it exists or 0.
Implements SUMOVehicle.
Definition at line 409 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDevices.
Referenced by GUIBaseVehicle::drawOnPos(), MSBaseVehicle::setChosenSpeedFactor(), and MSBatteryExport::write().
const std::vector<MSDevice*>& MSBaseVehicle::getDevices () const inline virtual inherited
Returns this vehicle's devices.
Returns
This vehicle's devices
Implements SUMOVehicle.
Definition at line 283 of file MSBaseVehicle.h.
References MSBaseVehicle::activateReminders(), MSBaseVehicle::addContainer(), MSBaseVehicle::addPerson(), MSBaseVehicle::addReminder(), MSBaseVehicle::hasValidRoute(), MSBaseVehicle::myDevices, and MSBaseVehicle::removeReminder().
const MSEdge * MSBaseVehicle::getEdge () const virtual inherited
Returns the edge the vehicle is currently at.
Returns
The current edge in the vehicle's route
Implements SUMOVehicle.
Definition at line 133 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myCurrEdge.
Referenced by MSVehicleTransfer::add(), MELoop::changeSegment(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), TraCIServerAPI_Vehicle::commandDistanceRequest(), MSVehicle::enterLaneAtLaneChange(), METriggeredCalibrator::execute(), MEVehicle::getAngle(), getParameterWindow(), MEVehicle::getPosition(), MEVehicle::getSlope(), MSBaseVehicle::getVClass(), TraCIServerAPI_Vehicle::processSet(), MESegment::receive(), MELoop::teleportVehicle(), and TraCIServerAPI_Vehicle::vtdMap().
SUMOTime MEVehicle::getEventTime () const inline inherited
Returns the (planned) time at which the vehicle leaves his current cell.
Returns
The time the vehicle thinks he leaves his cell at
Definition at line 195 of file MEVehicle.h.
References MEVehicle::myEventTime.
Referenced by MELoop::addLeaderCar(), MELoop::checkCar(), MEVehicle::getEventTimeSeconds(), MESegment::isOpen(), MESegment::receive(), MELoop::removeLeaderCar(), MESegment::send(), MELoop::setApproaching(), MESegment::setSpeedForQueue(), MELoop::teleportVehicle(), and MEVehicle::updateDetectors().
SUMOReal MEVehicle::getEventTimeSeconds () const inline inherited
Returns the earliest leave time for the current segment.
Definition at line 277 of file MEVehicle.h.
References MEVehicle::getEventTime(), and STEPS2TIME.
Referenced by getParameterWindow().
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 111 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 123 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GUIVehicle::drawAction_drawPersonsAndContainers(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE3::drawGL(), GNEInternalLane::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GNERouteProbe::drawGL(), GNELane::drawGL(), GNEEdge::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), GUIEdge::drawGL(), GNEConnection::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GNERerouter::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GUIContainer::getColorValue(), GNEJunction::getColorValue(), GUIPerson::getColorValue(), GNELane::getColorValue(), GUILane::getColorValue(), GUIEdge::getIDs(), GNEEdge::getLaneGlIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNECalibrator::GNECalibrator(), GNERouteProbe::GNERouteProbe(), GNEVaporizer::GNEVaporizer(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onLeftBtnPress(), GUISUMOAbstractView::removeAdditionalGLVisualisation(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUIVehicle::selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), and GUIGlObject::~GUIGlObject().
const std::string & MSBaseVehicle::getID () const virtual inherited
Returns the name of the vehicle.
Implements SUMOVehicle.
Definition at line 105 of file MSBaseVehicle.cpp.
References SUMOVehicleParameter::id, and MSBaseVehicle::myParameter.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), MSVehicleTransfer::add(), MSBaseVehicle::addStops(), MSVehicle::addTraciBusOrContainerStop(), MSBaseVehicle::calculateArrivalParams(), MSLaneChangerSublane::change(), MSLaneChanger::change(), MSLCM_SL2015::changed(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSLaneChanger::checkChange(), MSLaneChangerSublane::checkChangeSublane(), MSLane::checkFailure(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSAbstractLaneChangeModel::cleanupShadowLane(), MSVehicle::computeAngle(), MSLaneChanger::continueChange(), MSLCM_SL2015::decideDirection(), GUIVehicle::drawOutsideNetwork(), MSCalibrator::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSE2Collector::getCurrentVehicleIDs(), MSE2Collector::getEstimateQueueLength(), MSLane::getFirstVehicleInformation(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), getParameterWindow(), GUIVehicle::getParameterWindow(), MSLane::getPartialBehind(), MSAbstractLaneChangeModel::getShadowLane(), MSLane::handleCollisionBetween(), MSLCM_SL2015::inform(), MSLCM_JE2013::inform(), MSLCM_LC2013::inform(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MESegment::initialise(), MSPedestrianPushButton::isActiveForEdge(), MSLane::isInsertionSuccess(), MSVehicle::leaveLane(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSLCM_JE2013::MSLCM_JE2013(), MSLCM_LC2013::MSLCM_LC2013(), MSCalibrator::VehicleRemover::notifyEnter(), MSLCM_DK2008::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSLCM_LC2013::patchSpeed(), MSVehicle::planMove(), MSVehicle::planMoveInternal(), MSAbstractLaneChangeModel::primaryLaneChanged(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), MSBaseVehicle::replaceRouteEdges(), MSBaseVehicle::reroute(), MSLane::resetPartialOccupation(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSCalibrator::scheduleRemoval(), MSLane::setPartialOccupation(), TraCIServer::setVTDControlled(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSVehicle::updateBestLanes(), MSLCM_SL2015::updateGaps(), MSAbstractLaneChangeModel::updateShadowLane(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), MSLink::writeApproaching(), and MSXMLRawOut::writeVehicle().
SUMOReal MSBaseVehicle::getImpatience () const virtual inherited
Returns this vehicles impatience.
Implements SUMOVehicle.
Definition at line 400 of file MSBaseVehicle.cpp.
References MSBaseVehicle::getVehicleType(), SUMOVehicle::getWaitingTime(), MSGlobals::gTimeToGridlock, MAX2(), MIN2(), and SUMOReal.
Referenced by MSVehicle::checkRewindLinkLanes(), MSVehicle::executeMove(), MSLane::getCriticalLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSBaseVehicle::getNumberReroutes(), GUIVehicle::getParameterWindow(), MSLane::isInsertionSuccess(), MESegment::isOpen(), and GUIVehicle::selectBlockingFoes().
MSLane* MEVehicle::getLane () const inline virtual inherited
Returns the lane the vehicle is on.
Returns
The vehicle's current lane
Implements SUMOVehicle.
Definition at line 91 of file MEVehicle.h.
References MEVehicle::addStop(), MEVehicle::estimateLeaveSpeed(), MEVehicle::getAverageSpeed(), MEVehicle::getConservativeSpeed(), MEVehicle::getPosition(), MEVehicle::getSpeed(), MEVehicle::getStopEdges(), MEVehicle::getStoptime(), MEVehicle::hasArrived(), MEVehicle::isOnRoad(), MEVehicle::isParking(), MEVehicle::isStopped(), MEVehicle::isStoppedTriggered(), MEVehicle::moveRoutePointer(), and SUMOReal.
SUMOTime MEVehicle::getLastEntryTime () const inline inherited
Returns the time the vehicle entered the current segment.
Returns
The entry time
Definition at line 237 of file MEVehicle.h.
References MEVehicle::myLastEntryTime.
Referenced by MEVehicle::getLastEntryTimeSeconds(), MESegment::newArrival(), MEVehicle::updateDetectorForWriting(), and MEVehicle::updateDetectors().
SUMOReal MEVehicle::getLastEntryTimeSeconds () const inline inherited
Returns the entry time for the current segment.
Definition at line 282 of file MEVehicle.h.
References MEVehicle::getLastEntryTime(), and STEPS2TIME.
Referenced by getParameterWindow().
SUMOReal GUIMEVehicle::getLastLaneChangeOffset () const virtual
Returns the time since the last lane change in seconds.
See also
MSVehicle::myLastLaneChangeOffset
Returns
The time since the last lane change in seconds
Implements GUIBaseVehicle.
Definition at line 235 of file GUIMEVehicle.cpp.
Referenced by getAngle().
virtual SUMOReal MSBaseVehicle::getLateralPositionOnLane () const inline virtual inherited
Get the vehicle's lateral position on the lane.
Returns
The lateral position of the vehicle (in m relative to the centerline of the lane)
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 157 of file MSBaseVehicle.h.
SUMOReal MSBaseVehicle::getMaxSpeed () const virtual inherited
Returns the maximum speed.
Returns
The vehicle's maximum speed
Implements SUMOVehicle.
Definition at line 117 of file MSBaseVehicle.cpp.
References MSVehicleType::getMaxSpeed(), and MSBaseVehicle::myType.
Referenced by MSCFModel_Wiedemann::_v(), MSVehicleTransfer::checkInsertions(), MSVehicle::estimateSpeedAfterDistance(), getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), MSBaseVehicle::getVClass(), MSVehicle::Influencer::implicitDeltaPosVTD(), and MSVehicle::Influencer::implicitSpeedVTD().
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 137 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNEPOI::getAttribute(), GNECrossing::getAttribute(), GNEJunction::getAttribute(), GNEPoly::getAttribute(), GNEEdge::getAttribute(), GNELane::getAttribute(), GNELane::getParentName(), GNENetElement::getParentName(), GNEDetectorE3::getParentName(), GNEVaporizer::getParentName(), GNEVariableSpeedSignal::getParentName(), GNERouteProbe::getParentName(), GNEStoppingPlace::getParentName(), GNECalibrator::getParentName(), GNEDetector::getParentName(), GNEAdditional::getParentName(), GNERerouter::getParentName(), GNEAdditional::getPopUpMenu(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GNEEdge::moveGeometry(), GNEPoly::moveGeometry(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEViewNet::onCmdNodeShape(), GNEViewNet::onLeftBtnPress(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNENet::replaceJunctionByGeometry(), GNENet::retrieveAttributeCarriers(), GNEAdditional::setAdditionalID(), GNEEdge::setAttribute(), GNENet::splitEdge(), and GNEConnectorFrame::updateDescription().
SUMOReal GUIBaseVehicle::getNaviDegree () const inline inherited
return the current angle in navigational degrees
Definition at line 93 of file GUIBaseVehicle.h.
References GUIBaseVehicle::drawAction_drawCarriageClass(), GUIBaseVehicle::drawRouteHelper(), GUIBaseVehicle::getAngle(), GUIBaseVehicle::getColorValue(), GUIBaseVehicle::getLastLaneChangeOffset(), GUIBaseVehicle::getParameterWindow(), GUIBaseVehicle::getStopInfo(), GUIBaseVehicle::getTypeParameterWindow(), GeomHelper::naviDegree(), GUIBaseVehicle::selectBlockingFoes(), and SUMOReal.
Referenced by getParameterWindow(), and GUIVehicle::getParameterWindow().
int MSBaseVehicle::getNumberReroutes () const inline virtual inherited
Returns the number of new routes this vehicle got.
Returns
the number of new routes this vehicle got
Implements SUMOVehicle.
Definition at line 272 of file MSBaseVehicle.h.
References MSBaseVehicle::getImpatience(), MSBaseVehicle::myNumberReroutes, and SUMOReal.
Referenced by GUIBaseVehicle::drawGLAdditional(), getColorValue(), GUIVehicle::getColorValue(), and MSBaseVehicle::replaceRouteEdges().
const SUMOVehicleParameter & MSBaseVehicle::getParameter () const virtual inherited
Returns the vehicle's parameter (including departure definition)
Returns
The vehicle's parameter
Implements SUMOVehicle.
Definition at line 111 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myParameter, and SUMOReal.
Referenced by MSTransportableControl::boardAnyWaiting(), GUIBaseVehicle::drawOnPos(), MSBaseVehicle::getDepartDelay(), MSEdge::getDepartLane(), MSLane::getDepartSpeed(), getParameterWindow(), GUIVehicle::getParameterWindow(), MSLane::insertVehicle(), MSLane::isInsertionSuccess(), MSTransportableControl::loadAnyWaiting(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), GUIBaseVehicle::setFunctionalColor(), and METriggeredCalibrator::tryEmit().
GUIParameterTableWindow * GUIMEVehicle::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GUIBaseVehicle.
Definition at line 68 of file GUIMEVehicle.cpp.
References GUIParameterTableWindow::closeBuilding(), MEVehicle::getBlockTimeSeconds(), MSBaseVehicle::getChosenSpeedFactor(), MEVehicle::getCurrentTLSPenaltySeconds(), MSBaseVehicle::getDepartDelay(), MSBaseVehicle::getEdge(), MEVehicle::getEventTimeSeconds(), MSBaseVehicle::getID(), MEVehicle::getLastEntryTimeSeconds(), GUIBaseVehicle::getNaviDegree(), MSBaseVehicle::getParameter(), MEVehicle::getPositionOnLane(), MEVehicle::getSegment(), MEVehicle::getSpeed(), MEVehicle::getWaitingSeconds(), SUMOVehicleParameter::line, GUIParameterTableWindow::mkItem(), MSBaseVehicle::myDevices, MSBaseVehicle::myParameter, time2string(), and toString().
Referenced by getAngle().
const std::string & GUIGlObject::getParentName () const virtual inherited
Returns the name of the parent object (if any)
Returns
This object's parent id
Reimplemented in GNERerouter, GNEAdditional, GNEAdditionalSet, GNEDetector, GNECalibrator, GNEStoppingPlace, GNERouteProbe, GNEVariableSpeedSignal, GNEVaporizer, GUILane, GNEDetectorE3, GNENetElement, and GNELane.
Definition at line 117 of file GUIGlObject.cpp.
References StringUtils::emptyString.
Referenced by GUIGLObjectPopupMenu::onCmdCopyEdgeName().
GUIGLObjectPopupMenu * GUIBaseVehicle::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 280 of file GUIBaseVehicle.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), GUIGlObject::buildShowParamsPopupEntry(), GUIGlObject::buildShowTypeParamsPopupEntry(), GUIGlObject::getGlID(), GUISUMOAbstractView::getTrackedID(), GUIBaseVehicle::hasActiveAddVisualisation(), MID_HIDE_ALLROUTES, MID_HIDE_BEST_LANES, MID_HIDE_CURRENTROUTE, MID_HIDE_LFLINKITEMS, MID_SHOW_ALLROUTES, MID_SHOW_BEST_LANES, MID_SHOW_CURRENTROUTE, MID_SHOW_FOES, MID_SHOW_LFLINKITEMS, MID_START_TRACK, MID_STOP_TRACK, GUIBaseVehicle::myAdditionalVisualizations, GUIBaseVehicle::VO_SHOW_ALL_ROUTES, GUIBaseVehicle::VO_SHOW_BEST_LANES, GUIBaseVehicle::VO_SHOW_LFLINKITEMS, and GUIBaseVehicle::VO_SHOW_ROUTE.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight().
Position GUIMEVehicle::getPosition (const SUMOReal offset = 0) const inline virtual
Return current position (x/y, cartesian)
Note
implementation of abstract method does not work otherwise
Implements GUIBaseVehicle.
Definition at line 82 of file GUIMEVehicle.h.
References MEVehicle::getPosition().
SUMOReal MEVehicle::getPositionOnLane () const virtual inherited
Get the vehicle's position along the lane.
Returns
The position of the vehicle (in m from the lane's begin)
Implements SUMOVehicle.
Definition at line 84 of file MEVehicle.cpp.
References MESegment::getIndex(), MESegment::getLength(), MEVehicle::mySegment, and SUMOReal.
Referenced by MEVehicle::getAngle(), MEVehicle::getBackPositionOnLane(), getParameterWindow(), MEVehicle::getPosition(), MEVehicle::getSlope(), and MEVehicle::hasArrived().
int MEVehicle::getQueIndex () const inline inherited
Returns the index of the que the vehicle is in.
Returns
The que index
Definition at line 221 of file MEVehicle.h.
References MEVehicle::myQueIndex.
Referenced by MESegment::getLink(), MESegment::removeCar(), MEVehicle::saveState(), and MESegment::send().
virtual const MSEdge* MSBaseVehicle::getRerouteOrigin () const inline virtual inherited
Returns the starting point for reroutes (usually the current edge)
This differs from *myCurrEdge only if the vehicle is on an internal edge
Returns
The rerouting start point
Reimplemented in MSVehicle.
Definition at line 166 of file MSBaseVehicle.h.
References MSBaseVehicle::myCurrEdge.
Referenced by MSBaseVehicle::replaceRouteEdges(), and MSBaseVehicle::reroute().
const MSRoute& MSBaseVehicle::getRoute () const inline virtual inherited
Returns the current route.
Returns
The route the vehicle uses
Implements SUMOVehicle.
Definition at line 89 of file MSBaseVehicle.h.
References MSBaseVehicle::myRoute.
Referenced by TraCIServerAPI_Vehicle::commandDistanceRequest(), GUIBaseVehicle::drawRoute(), MSEdge::getDepartLane(), MSLane::isInsertionSuccess(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Vehicle::processGet(), GUIBaseVehicle::setFunctionalColor(), TraCIServerAPI_Vehicle::vtdMap(), and TraCIServerAPI_Vehicle::vtdMap_matchingRoutePosition().
const Position & GUIBaseVehicle::getSeatPosition (int personIndex) const protected inherited
returns the seat position for the person with the given index
if there are not enough seats in the vehicle people have to squeeze onto the last seat
Definition at line 1179 of file GUIBaseVehicle.cpp.
References MIN2(), and GUIBaseVehicle::mySeatPositions.
Referenced by GUIVehicle::drawAction_drawPersonsAndContainers().
MESegment* MEVehicle::getSegment () const inline inherited
Returns the current segment the vehicle is on.
Returns
The segment the vehicle is on
Definition at line 213 of file MEVehicle.h.
References MEVehicle::mySegment.
Referenced by MELoop::changeSegment(), MELoop::checkCar(), getColorValue(), getParameterWindow(), MEVehicle::isOnRoad(), MESegment::loadState(), MELoop::setApproaching(), and MELoop::teleportVehicle().
SUMOReal MEVehicle::getSlope () const virtual inherited
Returns the slope of the road at vehicle's position.
Returns
The slope
Reimplemented from MSBaseVehicle.
Definition at line 99 of file MEVehicle.cpp.
References MSBaseVehicle::getEdge(), MSEdge::getLanes(), MEVehicle::getPositionOnLane(), MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), and PositionVector::slopeDegreeAtOffset().
SUMOReal MEVehicle::getSpeed () const virtual inherited
Returns the vehicle's estimated speed assuming no delays.
Returns
The vehicle's estimated speed
Note
This is only an upper bound. The speed will be lower if the preceeding vehicle is delayed
Implements SUMOVehicle.
Definition at line 113 of file MEVehicle.cpp.
References MEVehicle::getAverageSpeed(), MEVehicle::getWaitingTime(), and SUMOReal.
Referenced by MEVehicle::estimateLeaveSpeed(), getColorValue(), MEVehicle::getLane(), getParameterWindow(), MESegment::isOpen(), MESegment::newArrival(), MESegment::receive(), and MELoop::setApproaching().
const ConstMSEdgeVector MEVehicle::getStopEdges () const virtual inherited
Returns the list of still pending stop edges.
Implements MSBaseVehicle.
Definition at line 251 of file MEVehicle.cpp.
References MEVehicle::myStops.
Referenced by MEVehicle::getLane().
std::string GUIMEVehicle::getStopInfo () const virtual
retrieve information about the current stop state
Implements GUIBaseVehicle.
Definition at line 242 of file GUIMEVehicle.cpp.
References MEVehicle::isParking(), and MEVehicle::isStopped().
Referenced by getAngle().
SUMOTime MEVehicle::getStoptime (const MESegment *const seg) const inherited
Returns how long to stop at the given segment.
Parameters
[in] seg The segment in question
Returns
stop time for the segment
Definition at line 242 of file MEVehicle.cpp.
References MEVehicle::myStops.
Referenced by MEVehicle::getLane(), and MESegment::receive().
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 150 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEAdditionalSet::drawConnections(), GNEDetector::drawDetectorIcon(), GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE3::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GNELane::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GNERerouter::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorE2::getAttribute(), GNEContainerStop::getAttribute(), GNEBusStop::getAttribute(), GNEDetectorE3::getAttribute(), GNEVaporizer::getAttribute(), GNEVariableSpeedSignal::getAttribute(), GNERouteProbe::getAttribute(), GNEChargingStation::getAttribute(), GNECalibrator::getAttribute(), GNERerouter::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNEJunction::getColorValue(), GNELane::getColorValue(), GUILane::getColorValue(), GNEViewNet::getEdgeAtCursorPosition(), GNEViewNet::getEdgesAtCursorPosition(), GNEViewNet::getJunctionAtCursorPosition(), GNEViewNet::getLaneAtCurserPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEDetectorE1::isValid(), GNEDetectorE2::isValid(), GNEContainerStop::isValid(), GNEBusStop::isValid(), GNEDetectorE3::isValid(), GNEVaporizer::isValid(), GNEVariableSpeedSignal::isValid(), GNERouteProbe::isValid(), GNEChargingStation::isValid(), GNECalibrator::isValid(), GNERerouter::isValid(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onDoubleClicked(), GNEViewNet::onLeftBtnPress(), LayeredRTree::selectLayer(), GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEDetectorE1::setAttribute(), GNEDetectorE2::setAttribute(), GNEContainerStop::setAttribute(), GNEBusStop::setAttribute(), GNEDetectorE3::setAttribute(), GNEVaporizer::setAttribute(), GNEVariableSpeedSignal::setAttribute(), GNERouteProbe::setAttribute(), GNEChargingStation::setAttribute(), GNECalibrator::setAttribute(), GNERerouter::setAttribute(), GNEJunction::setColor(), and GUISelectedStorage::toggleSelection().
GUIParameterTableWindow * GUIMEVehicle::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own type parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Implements GUIBaseVehicle.
Definition at line 144 of file GUIMEVehicle.cpp.
References GUIParameterTableWindow::closeBuilding(), MSVehicleType::getContainerCapacity(), MSVehicleType::getEmissionClass(), MSVehicleType::getID(), MSVehicleType::getLength(), Parameterised::getMap(), MSBaseVehicle::getMaxSpeed(), MSVehicleType::getMinGap(), PollutantsInterface::getName(), MSVehicleType::getParameter(), MSVehicleType::getPersonCapacity(), MSVehicleType::getVehicleClass(), GUIParameterTableWindow::mkItem(), MSBaseVehicle::myType, SumoVehicleClassStrings, and toString().
Referenced by getAngle().
SUMOVehicleClass MSBaseVehicle::getVClass () const inline virtual inherited
Returns the vehicle's access class.
Returns
The vehicle's access class
Implements SUMOVehicle.
Definition at line 105 of file MSBaseVehicle.h.
References MSBaseVehicle::getEdge(), MSBaseVehicle::getMaxSpeed(), MSVehicleType::getParameter(), MSBaseVehicle::myType, MSBaseVehicle::succEdge(), SUMOReal, and SUMOVTypeParameter::vehicleClass.
Referenced by MSPedestrianPushButton::isActiveForEdge(), and MSBaseVehicle::reroute().
const MSVehicleType& MSBaseVehicle::getVehicleType () const inline virtual inherited
Returns the vehicle's type definition.
Returns
The vehicle's type definition
Implements SUMOVehicle.
Definition at line 97 of file MSBaseVehicle.h.
References MSBaseVehicle::myType.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSVehicle::adaptToLeaders(), MSVehicle::addStop(), MSLane::basePos(), MSTransportableControl::boardAnyWaiting(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), MSLane::checkFailure(), GUIApplicationWindow::checkGamingEvents(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSLaneChanger::computeOvertakingTime(), MSLaneChanger::continueChange(), MSLane::detectCollisionBetween(), MSE2Collector::detectorUpdate(), GUIVehicle::drawAction_drawLinkItems(), GUIVehicle::drawAction_drawRailCarriages(), GUIVehicle::drawAction_drawVehicleBlinker(), GUIVehicle::drawAction_drawVehicleBrakeLight(), GUIEdge::drawMesoVehicles(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MEVehicle::estimateLeaveSpeed(), MSVehicle::estimateLeaveSpeed(), MSVehicle::estimateSpeedAfterDistance(), MSVehicle::executeMove(), MSLane::executeMovements(), MSLane::freeInsertion(), MEVehicle::getBackPositionOnLane(), MSLane::getBruttoOccupancy(), GUIBaseVehicle::getCenteringBoundary(), MSLane::getCriticalLeader(), MSEdge::getDepartLane(), MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSLane::getFollower(), MSLane::getFollowersOnConsecutive(), MSBaseVehicle::getImpatience(), MSVehicle::getLateralOverlap(), MSLane::getLeader(), MSVehicle::getLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getNettoOccupancy(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLaneChanger::getRealFollower(), MSLaneChanger::getRealLeader(), MSVehicle::getRightSideOnEdge(), MSVehicle::getRightSideOnLane(), MSLeaderInfo::getSubLanes(), MSVehicle::getTimeGap(), MSLink::getZipperSpeed(), MESegment::hasSpaceFor(), MSLane::incorporateVehicle(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLane::insertVehicle(), MSLane::integrateNewVehicle(), MSLane::isInsertionSuccess(), MESegment::isOpen(), MSLCM_SL2015::keepLatGap(), MSLane::lastInsertion(), MSLane::leftByLaneChange(), MSTransportableControl::loadAnyWaiting(), MESegment::loadState(), MSVehicle::overlap(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Vehicle::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), MESegment::receive(), MSLaneChanger::registerUnchanged(), MESegment::removeCar(), MSLane::removeVehicle(), MSLane::safeInsertionSpeed(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), GUIVehicle::selectBlockingFoes(), MESegment::send(), GUIBaseVehicle::setFunctionalColor(), MSVehicle::setTentativeLaneAndPosition(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChanger::startChange(), MSLaneChangerSublane::startChangeSublane(), MSVehicle::unsafeLinkAhead(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSVehicle::updateFurtherLanes(), MSLCM_SL2015::updateGaps(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSBatteryExport::write(), and MSQueueExport::writeLane().
SUMOReal MEVehicle::getWaitingSeconds () const inline inherited
Returns the number of seconds waited (speed was lesser than 0.1m/s)
The value is reset if the vehicle moves faster than 0.1m/s Intentional stopping does not count towards this time.
Returns
The time the vehicle is standing
Definition at line 271 of file MEVehicle.h.
References MEVehicle::getWaitingTime(), and STEPS2TIME.
Referenced by getColorValue(), and getParameterWindow().
SUMOTime MEVehicle::getWaitingTime () const inline virtual inherited
Returns the duration for which the vehicle was blocked.
Implements SUMOVehicle.
Definition at line 260 of file MEVehicle.h.
References MAX2(), MEVehicle::myBlockTime, and MEVehicle::myEventTime.
Referenced by MELoop::checkCar(), MEVehicle::getSpeed(), MEVehicle::getWaitingSeconds(), MESegment::isOpen(), and MELoop::setApproaching().
bool GUIBaseVehicle::hasActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) const inherited
Returns whether the named feature is enabled in the given view.
Parameters
[in] parent The view for which the feature may be enabled
[in] which The visualisation feature
Returns
see comment
Definition at line 1121 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::myAdditionalVisualizations.
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::drawGLAdditional(), and GUIBaseVehicle::getPopUpMenu().
bool MEVehicle::hasArrived () const virtual inherited
Returns whether this vehicle has already arived (reached the arrivalPosition on its final edge)
Reimplemented from MSBaseVehicle.
Definition at line 159 of file MEVehicle.cpp.
References MSRoute::end(), MEVehicle::getPositionOnLane(), MSBaseVehicle::myArrivalPos, MSBaseVehicle::myCurrEdge, MEVehicle::myEventTime, MSBaseVehicle::myRoute, MEVehicle::mySegment, POSITION_EPS, and SUMOTime_MIN.
Referenced by MEVehicle::getLane(), MEVehicle::moveRoutePointer(), and MESegment::receive().
bool MSBaseVehicle::hasDeparted () const virtual inherited
Returns whether this vehicle has already departed.
Implements SUMOVehicle.
Definition at line 265 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myDeparture, and MSBaseVehicle::NOT_YET_DEPARTED.
Referenced by MSVehicle::addStop(), MSLane::forceVehicleInsertion(), MEVehicle::loadState(), MSVehicle::loadState(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), and MSBaseVehicle::setArrivalPos().
bool MSBaseVehicle::hasValidRoute (std::string & msg, const MSRoute * route = 0) const virtual inherited
Validates the current or given route.
Parameters
[out] msg Description why the route is not valid (if it is the case)
[in] route The route to check (or 0 if the current route shall be checked)
Returns
Whether the vehicle's current route is valid
Implements SUMOVehicle.
Definition at line 284 of file MSBaseVehicle.cpp.
References MSRoute::begin(), MSRoute::end(), MSVehicleType::getVehicleClass(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myRoute, and MSBaseVehicle::myType.
Referenced by MSBaseVehicle::getDevices(), MESegment::initialise(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), and MSBaseVehicle::replaceRouteEdges().
virtual bool MSBaseVehicle::isFrontOnLane (const MSLane *) const inline virtual inherited
Returns the information whether the front of the vehhicle is on the given lane.
Returns
Whether the vehicle's front is on that lane
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 149 of file MSBaseVehicle.h.
bool MEVehicle::isOnRoad () const virtual inherited
Returns the information whether the vehicle is on a road (is simulated)
Returns
Whether the vehicle is simulated
Reimplemented from MSBaseVehicle.
Definition at line 168 of file MEVehicle.cpp.
References MEVehicle::getSegment().
Referenced by MEVehicle::getLane().
bool MEVehicle::isParking () const virtual inherited
Returns whether the vehicle is parking.
Returns
whether the vehicle is parking
Implements SUMOVehicle.
Definition at line 174 of file MEVehicle.cpp.
Referenced by MEVehicle::getLane(), and getStopInfo().
virtual bool MSBaseVehicle::isRemoteControlled () const inline virtual inherited
Returns the information whether the vehicle is fully controlled via TraCI.
Returns
Whether the vehicle is remote-controlled
Implements SUMOVehicle.
Reimplemented in MSVehicle.
Definition at line 142 of file MSBaseVehicle.h.
bool MEVehicle::isStopped () const virtual inherited
Returns whether the vehicle is at a stop.
Returns
Whether it has stopped
Implements SUMOVehicle.
Definition at line 230 of file MEVehicle.cpp.
References MEVehicle::mySegment, and MEVehicle::myStops.
Referenced by MELoop::checkCar(), MEVehicle::getLane(), and getStopInfo().
bool MEVehicle::isStoppedTriggered () const virtual inherited
Returns whether the vehicle is on a triggered stop.
Returns
whether the vehicle is on a triggered stop
Implements SUMOVehicle.
Definition at line 236 of file MEVehicle.cpp.
Referenced by MEVehicle::getLane().
void MEVehicle::loadState (const SUMOSAXAttributes & attrs, const SUMOTime offset) virtual inherited
Loads the state of this vehicle from the given description.
Implements SUMOVehicle.
Definition at line 346 of file MEVehicle.cpp.
References MELoop::addLeaderCar(), MESegment::getIndex(), MESegment::getNextSegment(), MELoop::getSegmentForEdge(), SUMOSAXAttributes::getString(), MSGlobals::gMesoNet, SUMOSAXAttributes::hasAttribute(), MSBaseVehicle::hasDeparted(), MEVehicle::myBlockTime, MSBaseVehicle::myCurrEdge, MSBaseVehicle::myDeparture, MEVehicle::myEventTime, MEVehicle::myLastEntryTime, MEVehicle::setSegment(), SUMO_ATTR_POSITION, SUMO_ATTR_STATE, SUMOTime_MAX, and SUMOTime_MIN.
Referenced by MEVehicle::getBlockTimeSeconds().
bool MEVehicle::mayProceed () const inherited
Returns whether the vehicle is allowed to pass the next junction.
Returns
true iff the vehicle may drive over the next junction
Definition at line 261 of file MEVehicle.cpp.
References MESegment::isOpen(), MEVehicle::mySegment, and SUMOReal.
Referenced by MELoop::changeSegment(), MELoop::checkCar(), and MEVehicle::getBlockTimeSeconds().
bool MEVehicle::moveRoutePointer () inherited
Update when the vehicle enters a new edge in the move step.
Returns
Whether the vehicle's route has ended (due to vaporization, or because the destination was reached)
Definition at line 145 of file MEVehicle.cpp.
References MSRoute::end(), MEVehicle::hasArrived(), MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by METriggeredCalibrator::execute(), MEVehicle::getLane(), MESegment::receive(), and MELoop::teleportVehicle().
void MSBaseVehicle::onDepart () virtual inherited
Called when the vehicle is inserted into the network.
Sets optional information about departure time, informs the vehicle control about a further running vehicle.
Implements SUMOVehicle.
Definition at line 257 of file MSBaseVehicle.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), SUMOVehicle::getPositionOnLane(), MSNet::getVehicleControl(), MSBaseVehicle::myDepartPos, MSBaseVehicle::myDeparture, and MSVehicleControl::vehicleDeparted().
Referenced by MSVehicle::enterLaneAtInsertion(), MSBaseVehicle::getCurrentRouteEdge(), and MESegment::receive().
void GUIBaseVehicle::removeActiveAddVisualisation (GUISUMOAbstractView *const parent, int which) inherited
Adds the named visualisation feature to the given view.
Parameters
[in] parent The view for which the feature shall be enabled
[in] which The visualisation feature to enable
See also
GUISUMOAbstractView::removeAdditionalGLVisualisation
Definition at line 1137 of file GUIBaseVehicle.cpp.
References GUIBaseVehicle::myAdditionalVisualizations, and GUISUMOAbstractView::removeAdditionalGLVisualisation().
Referenced by GUIBaseVehicle::drawAction_drawVehicleBlueLight(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), and GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack().
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 264 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
void MSBaseVehicle::removeReminder (MSMoveReminder * rem) inherited
Removes a MoveReminder dynamically.
Parameters
[in] rem the reminder to remove
See also
MSMoveReminder
Definition at line 323 of file MSBaseVehicle.cpp.
References MSBaseVehicle::myMoveReminders.
Referenced by MSBaseVehicle::getDevices().
bool MEVehicle::replaceRoute (const MSRoute * route, bool onInit = false, int offset = 0) virtual inherited
Replaces the current route by the given one.
Implements SUMOVehicle.
Definition at line 180 of file MEVehicle.cpp.
References MSRoute::addReference(), MSRoute::begin(), MSBaseVehicle::calculateArrivalParams(), MSRoute::contains(), MSRoute::getEdges(), MSNet::getInstance(), MESegment::getLink(), MSNet::informVehicleStateListener(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myNumberReroutes, MSBaseVehicle::myRoute, MEVehicle::mySegment, MSRoute::release(), MSLink::removeApproaching(), MELoop::setApproaching(), and MSNet::VEHICLE_STATE_NEWROUTE.
Referenced by MEVehicle::getBlockTimeSeconds().
bool MSBaseVehicle::replaceRouteEdges (ConstMSEdgeVector & edges, bool onInit = false, bool check = false) virtual inherited
Replaces the current route by the given edges.
It is possible that the new route is not accepted, if a) it does not contain the vehicle's current edge, or b) something fails on insertion into the routes container (see in-line comments).
Parameters
[in] edges The new list of edges to pass
[in] onInit Whether the vehicle starts with this route
[in] check Whether the route should be checked for validity
Returns
Whether the new route was accepted
Implements SUMOVehicle.
Definition at line 186 of file MSBaseVehicle.cpp.
References MSRoute::addReference(), MSRoute::begin(), MSBaseVehicle::calculateArrivalParams(), RGBColor::DEFAULT_COLOR, MSRoute::dictionary(), MSGlobals::gCheckRoutes, MSRoute::getColor(), MSRoute::getEdges(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getNumberReroutes(), MSBaseVehicle::getRerouteOrigin(), MSRoute::getStops(), MSBaseVehicle::hasValidRoute(), MSBaseVehicle::myCurrEdge, MSBaseVehicle::myRoute, MSRoute::release(), SUMOVehicle::replaceRoute(), MSRoute::size(), SUMOReal, toString(), and WRITE_WARNING.
Referenced by MSBaseVehicle::getCurrentRouteEdge(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Vehicle::processSet(), and MSBaseVehicle::reroute().
void MSBaseVehicle::reroute (SUMOTime t, SUMOAbstractRouter< MSEdge, SUMOVehicle > & router, const bool onInit = false, const bool withTaz = false) virtual inherited
Performs a rerouting using the given router.
Tries to find a new route between the current edge and the destination edge, first. Tries to replace the current route by the new one using replaceRoute.
Parameters
[in] t The time for which the route is computed
[in] router The router to use
See also
replaceRoute
Implements SUMOVehicle.
Definition at line 139 of file MSBaseVehicle.cpp.
References MSEdge::allowedLanes(), SUMOAbstractRouter< E, V >::compute(), MSEdge::dictionary(), MSEdge::EDGEFUNCTION_DISTRICT, SUMOVehicleParameter::fromTaz, Named::getID(), MSBaseVehicle::getID(), MSRoute::getLastEdge(), MSBaseVehicle::getRerouteOrigin(), MSBaseVehicle::getStopEdges(), MSBaseVehicle::getVClass(), MSBaseVehicle::myParameter, MSBaseVehicle::myRoute, MSBaseVehicle::replaceRouteEdges(), SUMOVehicleParameter::toTaz, and SUMOVehicleParameter::via.
Referenced by MSBaseVehicle::getCurrentRouteEdge(), and TraCIServerAPI_Vehicle::processSet().
void MEVehicle::saveState (OutputDevice & out) virtual inherited
Saves the states of a vehicle.
Reimplemented from MSBaseVehicle.
Definition at line 329 of file MEVehicle.cpp.
References MSRoute::begin(), OutputDevice::closeTag(), MESegment::getEdge(), MESegment::getIndex(), MEVehicle::getQueIndex(), MEVehicle::myBlockTime, MSBaseVehicle::myCurrEdge, MSBaseVehicle::myDeparture, MEVehicle::myEventTime, MEVehicle::myLastEntryTime, MSBaseVehicle::myRoute, MEVehicle::mySegment, MSBaseVehicle::saveState(), SUMO_ATTR_STATE, toString(), and OutputDevice::writeAttr().
Referenced by MEVehicle::getBlockTimeSeconds().
void GUIMEVehicle::selectBlockingFoes () const virtual
adds the blocking foes to the current selection
Implements GUIBaseVehicle.
Definition at line 256 of file GUIMEVehicle.cpp.
Referenced by getAngle().
virtual void MSBaseVehicle::setArrivalPos (SUMOReal arrivalPos) inline virtual inherited
Sets this vehicle's desired arrivalPos for its current route.
Implements SUMOVehicle.
Definition at line 256 of file MSBaseVehicle.h.
References MSBaseVehicle::hasArrived(), MSBaseVehicle::hasDeparted(), and MSBaseVehicle::myArrivalPos.
void MEVehicle::setBlockTime (const SUMOTime t) inline inherited
Sets the time at which the vehicle was blocked.
Parameters
[in] t The blocking time
Definition at line 245 of file MEVehicle.h.
References MEVehicle::myBlockTime, and MEVehicle::myLastEntryTime.
Referenced by MELoop::checkCar(), and MESegment::receive().
void MSBaseVehicle::setChosenSpeedFactor (const SUMOReal factor) inline virtual inherited
Returns the precomputed factor by which the driver wants to be faster than the speed limit.
Returns
Speed limit factor
Implements SUMOVehicle.
Definition at line 347 of file MSBaseVehicle.h.
References MSBaseVehicle::addStops(), MSBaseVehicle::calculateArrivalParams(), MSBaseVehicle::getDevice(), MSBaseVehicle::getStopEdges(), MSBaseVehicle::myChosenSpeedFactor, and MSBaseVehicle::saveState().
Referenced by TraCIServerAPI_Vehicle::processSet().
void GUIBaseVehicle::setColor (const GUIVisualizationSettings & s) const protected inherited
sets the color according to the currente settings
Definition at line 1032 of file GUIBaseVehicle.cpp.
References GUIPropertySchemeStorage< T >::getActive(), GUIPropertyScheme< T >::getColor(), GUIBaseVehicle::getColorValue(), GUIPropertySchemeStorage< T >::getScheme(), GUIBaseVehicle::myVehicle, GLHelper::setColor(), GUIBaseVehicle::setFunctionalColor(), and GUIVisualizationSettings::vehicleColorer.
Referenced by GUIBaseVehicle::drawOnPos(), and GUIBaseVehicle::drawRoute().
void MEVehicle::setEventTime (SUMOTime t, bool hasDelay = true) inline inherited
Sets the (planned) time at which the vehicle leaves his current cell.
Parameters
[in] t The leaving time
Definition at line 183 of file MEVehicle.h.
References MESegment::getEdge(), MSEdge::markDelayed(), MEVehicle::myEventTime, MEVehicle::myLastEntryTime, and MEVehicle::mySegment.
Referenced by MELoop::checkCar(), METriggeredCalibrator::execute(), MESegment::receive(), MESegment::send(), MESegment::setSpeedForQueue(), and MELoop::teleportVehicle().
bool GUIBaseVehicle::setFunctionalColor (int activeScheme, const MSBaseVehicle * veh) static inherited
sets the color according to the current scheme index and some vehicle function
Definition at line 1041 of file GUIBaseVehicle.cpp.
References SUMOVehicleParameter::color, RGBColor::DEFAULT_COLOR, Position::distanceTo(), RGBColor::fromHSV(), Boundary::getCenter(), MSRoute::getColor(), MSVehicleType::getColor(), MSRoute::getEdges(), MSNet::getInstance(), MSBaseVehicle::getParameter(), MSBaseVehicle::getRoute(), MSBaseVehicle::getVehicleType(), PI, GLHelper::setColor(), SUMOReal, VEHPARS_COLOR_SET, VTYPEPARS_COLOR_SET, MSVehicleType::wasSet(), SUMOVehicleParameter::wasSet(), Position::x(), Boundary::xmax(), Boundary::xmin(), Position::y(), Boundary::ymax(), and Boundary::ymin().
Referenced by GUIBaseVehicle::setColor().
void MEVehicle::setLastEntryTime (SUMOTime t) inline inherited
Sets the entry time for the current segment.
Parameters
[in] t The entry time
Definition at line 229 of file MEVehicle.h.
References MEVehicle::myLastEntryTime.
Referenced by MESegment::receive().
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 143 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNENet::renameJunction(), GNEAdditional::setAdditionalID(), GNELane::setIndex(), and GNEEdge::setMicrosimID().
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 273 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
virtual void MEVehicle::setSegment (MESegment * s, int idx = 0) inline virtual inherited
Sets the current segment the vehicle is at together with its que.
Parameters
[in] s The current segment
[in] q The current que
Definition at line 204 of file MEVehicle.h.
References MEVehicle::myQueIndex, and MEVehicle::mySegment.
Referenced by MELoop::changeSegment(), METriggeredCalibrator::execute(), MEVehicle::loadState(), MESegment::receive(), and MELoop::teleportVehicle().
const MSEdge * MSBaseVehicle::succEdge (int nSuccs) const virtual inherited
Returns the nSuccs'th successor of edge the vehicle is currently at.
If the rest of the route (counted from the current edge) has less than nSuccs edges, 0 is returned.
Parameters
[in] nSuccs The number of edge to look forward
Returns
The nSuccs'th following edge in the vehicle's route
Implements SUMOVehicle.
Definition at line 123 of file MSBaseVehicle.cpp.
References MSRoute::begin(), MSBaseVehicle::myCurrEdge, and MSBaseVehicle::myRoute.
Referenced by MSVehicleTransfer::add(), MSLane::appropriate(), MSVehicleTransfer::checkInsertions(), MESegment::getLink(), MSBaseVehicle::getVClass(), MSBaseVehicle::hasArrived(), MSPedestrianPushButton::isActiveForEdge(), MELoop::nextSegment(), TraCIServerAPI_Vehicle::processSet(), and MESegment::receive().
void MEVehicle::updateDetectorForWriting (MSMoveReminder * rem, SUMOTime currentTime, SUMOTime exitTime) inherited
Updates a single vehicle detector if present.
Definition at line 277 of file MEVehicle.cpp.
References MESegment::getIndex(), MEVehicle::getLastEntryTime(), MESegment::getLength(), MSBaseVehicle::myMoveReminders, MEVehicle::mySegment, and MSMoveReminder::updateDetector().
Referenced by MEVehicle::getBlockTimeSeconds().
void MEVehicle::updateDetectors (SUMOTime currentTime, const bool isLeave, const MSMoveReminder::Notification reason = MSMoveReminder::NOTIFICATION_JUNCTION) inherited
Updates all vehicle detectors.
Definition at line 295 of file MEVehicle.cpp.
References MEVehicle::getEventTime(), MESegment::getIndex(), MEVehicle::getLastEntryTime(), MESegment::getLength(), MSBaseVehicle::myMoveReminders, MEVehicle::mySegment, and MSMoveReminder::NOTIFICATION_SEGMENT.
Referenced by MEVehicle::getBlockTimeSeconds(), MESegment::setSpeedForQueue(), and MESegment::updateDetectorsOnLeave().
Field Documentation
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 77 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
std::map<GUISUMOAbstractView*, int> GUIBaseVehicle::myAdditionalVisualizations inherited
Enabled visualisations, per view.
Definition at line 302 of file GUIBaseVehicle.h.
Referenced by GUIBaseVehicle::addActiveAddVisualisation(), GUIBaseVehicle::getPopUpMenu(), GUIBaseVehicle::hasActiveAddVisualisation(), GUIBaseVehicle::removeActiveAddVisualisation(), and GUIBaseVehicle::~GUIBaseVehicle().
int MSBaseVehicle::myArrivalLane protected inherited
The destination lane where the vehicle stops.
Definition at line 422 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), and MSVehicle::updateBestLanes().
SUMOReal MSBaseVehicle::myArrivalPos protected inherited
The position on the destination lane where the vehicle stops.
Definition at line 419 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::calculateArrivalParams(), MSBaseVehicle::getArrivalPos(), MEVehicle::hasArrived(), MSVehicle::hasArrived(), MSVehicle::planMoveInternal(), MSVehicle::resetRoutePosition(), MSBaseVehicle::setArrivalPos(), and MSVehicle::updateBestLanes().
SUMOTime MEVehicle::myBlockTime protected inherited
The time at which the vehicle was blocked on its current segment.
Definition at line 338 of file MEVehicle.h.
Referenced by MEVehicle::getBlockTime(), MEVehicle::getWaitingTime(), MEVehicle::loadState(), MEVehicle::saveState(), and MEVehicle::setBlockTime().
SUMOReal GUIBaseVehicle::myCarriageLength mutable protected inherited
Variable to set with the length of the last drawn carriage or the vehicle length.
Definition at line 347 of file GUIBaseVehicle.h.
Referenced by GUIBaseVehicle::drawOnPos().
SUMOReal MSBaseVehicle::myChosenSpeedFactor protected inherited
A precomputed factor by which the driver wants to be faster than the speed limit.
Definition at line 396 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getChosenSpeedFactor(), and MSBaseVehicle::setChosenSpeedFactor().
MSRouteIterator MSBaseVehicle::myCurrEdge protected inherited
Iterator to current route-edge.
Definition at line 393 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSVehicle::enterLaneAtMove(), MSVehicle::executeMove(), MSBaseVehicle::getCurrentRouteEdge(), MSVehicle::getDistanceToPosition(), MSBaseVehicle::getEdge(), MSBaseVehicle::getRerouteOrigin(), MSVehicle::getRerouteOrigin(), MSVehicle::getRoutePosition(), MEVehicle::hasArrived(), MSVehicle::hasArrived(), MSBaseVehicle::hasValidRoute(), MSVehicle::leaveLane(), MEVehicle::loadState(), MSVehicle::loadState(), MEVehicle::moveRoutePointer(), MSVehicle::planMoveInternal(), MSVehicle::Influencer::postProcessVTD(), MSVehicle::processNextStop(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), MSVehicle::resetRoutePosition(), MEVehicle::saveState(), MSVehicle::saveState(), MSBaseVehicle::succEdge(), MSVehicle::updateBestLanes(), and MSVehicle::willPass().
SUMOReal MSBaseVehicle::myDepartPos protected inherited
The real depart position.
Definition at line 416 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getDepartPos(), and MSBaseVehicle::onDepart().
SUMOTime MSBaseVehicle::myDeparture protected inherited
The real departure time.
Definition at line 413 of file MSBaseVehicle.h.
Referenced by MSVehicle::enterLaneAtInsertion(), MSBaseVehicle::getDeparture(), MSBaseVehicle::hasDeparted(), MEVehicle::loadState(), MSVehicle::loadState(), MSBaseVehicle::onDepart(), MEVehicle::saveState(), and MSVehicle::saveState().
std::vector<MSDevice*> MSBaseVehicle::myDevices protected inherited
The devices this vehicle has.
Definition at line 410 of file MSBaseVehicle.h.
Referenced by MSVehicle::addContainer(), MSVehicle::addPerson(), MSBaseVehicle::getDevice(), MSBaseVehicle::getDevices(), getParameterWindow(), GUIVehicle::getParameterWindow(), GUIBaseVehicle::GUIBaseVehicle(), MSBaseVehicle::MSBaseVehicle(), and MSBaseVehicle::~MSBaseVehicle().
SUMOTime MEVehicle::myEventTime protected inherited
The (planned) time of leaving the segment (cell)
Definition at line 332 of file MEVehicle.h.
Referenced by MEVehicle::getAverageSpeed(), MEVehicle::getConservativeSpeed(), MEVehicle::getEventTime(), MEVehicle::getWaitingTime(), MEVehicle::hasArrived(), MEVehicle::loadState(), MEVehicle::saveState(), and MEVehicle::setEventTime().
SUMOTime MEVehicle::myLastEntryTime protected inherited
The time the vehicle entered its current segment.
Definition at line 335 of file MEVehicle.h.
Referenced by MEVehicle::getAverageSpeed(), MEVehicle::getConservativeSpeed(), MEVehicle::getLastEntryTime(), MEVehicle::loadState(), MEVehicle::saveState(), MEVehicle::setBlockTime(), MEVehicle::setEventTime(), and MEVehicle::setLastEntryTime().
MFXMutex GUIBaseVehicle::myLock mutable protected inherited
The mutex used to avoid concurrent updates of the vehicle buffer.
Definition at line 344 of file GUIBaseVehicle.h.
Referenced by GUIVehicle::drawBestLanes(), and GUIBaseVehicle::~GUIBaseVehicle().
MoveReminderCont MSBaseVehicle::myMoveReminders protected inherited
Current lane's move reminder.
Definition at line 406 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::activateReminders(), MSVehicle::activateReminders(), MSVehicle::adaptLaneEntering2MoveReminder(), MSVehicle::addContainer(), MSVehicle::addPerson(), MSBaseVehicle::addReminder(), GUIBaseVehicle::GUIBaseVehicle(), MSVehicle::leaveLane(), MSBaseVehicle::MSBaseVehicle(), MSBaseVehicle::removeReminder(), MEVehicle::updateDetectorForWriting(), MEVehicle::updateDetectors(), and MSVehicle::workOnMoveReminders().
int MSBaseVehicle::myNumberReroutes protected inherited
The number of reroutings.
Definition at line 425 of file MSBaseVehicle.h.
Referenced by MSBaseVehicle::getNumberReroutes(), MSVehicle::replaceRoute(), and MEVehicle::replaceRoute().
const SUMOVehicleParameter* MSBaseVehicle::myParameter protected inherited
This Vehicle's parameter.
Definition at line 384 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSBaseVehicle::addStops(), MSBaseVehicle::calculateArrivalParams(), MSVehicle::getContainerNumber(), MSBaseVehicle::getID(), MSBaseVehicle::getParameter(), getParameterWindow(), GUIVehicle::getParameterWindow(), MSVehicle::getPersonNumber(), MSVehicle::planMoveInternal(), MSBaseVehicle::reroute(), MSBaseVehicle::saveState(), MSVehicle::updateBestLanes(), and MSBaseVehicle::~MSBaseVehicle().
int MEVehicle::myQueIndex protected inherited
Index of the que the vehicle is in (important for multiqueue extension)
Definition at line 329 of file MEVehicle.h.
Referenced by MEVehicle::getQueIndex(), and MEVehicle::setSegment().
const MSRoute* MSBaseVehicle::myRoute protected inherited
This Vehicle's route.
Definition at line 387 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSBaseVehicle::addStops(), MSBaseVehicle::calculateArrivalParams(), GUIVehicle::drawRouteHelper(), MSVehicle::executeMove(), MSVehicle::getDistanceToPosition(), MSVehicle::getRerouteOrigin(), MSBaseVehicle::getRoute(), MSVehicle::getRoutePosition(), MEVehicle::hasArrived(), MSVehicle::hasArrived(), MSBaseVehicle::hasValidRoute(), MEVehicle::moveRoutePointer(), MSBaseVehicle::MSBaseVehicle(), MSVehicle::planMoveInternal(), MSVehicle::replaceRoute(), MEVehicle::replaceRoute(), MSBaseVehicle::replaceRouteEdges(), MSBaseVehicle::reroute(), MSVehicle::resetRoutePosition(), MEVehicle::saveState(), MSBaseVehicle::saveState(), MSVehicle::saveState(), MSBaseVehicle::succEdge(), MSVehicle::updateBestLanes(), MSVehicle::willPass(), and MSBaseVehicle::~MSBaseVehicle().
PositionVector GUIBaseVehicle::mySeatPositions mutable protected inherited
positions of seats in the vehicle (updated at every drawing step)
Definition at line 350 of file GUIBaseVehicle.h.
Referenced by GUIVehicle::computeSeats(), GUIVehicle::drawAction_drawRailCarriages(), GUIBaseVehicle::drawOnPos(), GUIBaseVehicle::getSeatPosition(), and GUIBaseVehicle::GUIBaseVehicle().
MESegment* MEVehicle::mySegment protected inherited
The segment the vehicle is at.
Definition at line 326 of file MEVehicle.h.
Referenced by MEVehicle::getAverageSpeed(), MEVehicle::getConservativeSpeed(), MEVehicle::getCurrentTLSPenaltySeconds(), MEVehicle::getPositionOnLane(), MEVehicle::getSegment(), MEVehicle::hasArrived(), MEVehicle::isStopped(), MEVehicle::mayProceed(), MEVehicle::replaceRoute(), MEVehicle::saveState(), MEVehicle::setEventTime(), MEVehicle::setSegment(), MEVehicle::updateDetectorForWriting(), and MEVehicle::updateDetectors().
std::map<const MESegment* const, SUMOTime> MEVehicle::myStops protected inherited
where to stop
Definition at line 341 of file MEVehicle.h.
Referenced by MEVehicle::addStop(), MEVehicle::getStopEdges(), MEVehicle::getStoptime(), and MEVehicle::isStopped().
const MSVehicleType* MSBaseVehicle::myType protected inherited
This Vehicle's type.
Definition at line 390 of file MSBaseVehicle.h.
Referenced by MSVehicle::addStop(), MSBaseVehicle::calculateArrivalParams(), MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), MSVehicle::getBackPosition(), MSVehicle::getBackPositionOnLane(), MSVehicle::getBoundingBox(), MSVehicle::getBoundingPoly(), MSVehicle::getCarFollowModel(), MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHCEmissions(), MSBaseVehicle::getMaxSpeed(), MSVehicle::getNOxEmissions(), MSVehicle::getPMxEmissions(), MSVehicle::getPositionOnLane(), getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), MSBaseVehicle::getVClass(), MSBaseVehicle::getVehicleType(), MSBaseVehicle::hasValidRoute(), MSVehicle::processNextStop(), MSVehicle::replaceVehicleType(), MSBaseVehicle::saveState(), MSVehicle::updateBestLanes(), and MSVehicle::~MSVehicle().
const SUMOTime MSBaseVehicle::NOT_YET_DEPARTED = SUMOTime_MAX static protected inherited
Definition at line 430 of file MSBaseVehicle.h.
Referenced by MSVehicle::enterLaneAtInsertion(), and MSBaseVehicle::hasDeparted().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 76 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUIMEVehicle.h
GUIMEVehicle.cpp