SUMO - Simulation of Urban MObility: PCLoaderOSM::EdgesHandler Class Reference
PCLoaderOSM::EdgesHandler Class Reference
A class which extracts OSM-edges from a parsed OSM-file.
#include <PCLoaderOSM.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
EdgesHandler (const std::map< long long int, PCOSMNode * > &osmNodes, EdgeMap &toFill, const RelationsMap &additionalWays, bool withAttributes, MsgHandler &errorHandler)
Constructor.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
~EdgesHandler ()
Destructor.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Protected Member Functions
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
inherited from GenericSAXHandler
void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
void myEndElement (int element)
Called when a closing tag occurs.
Private Member Functions
EdgesHandler (const EdgesHandler &s)
Invalidated copy constructor.
EdgesHandler & operator= (const EdgesHandler &s)
Invalidated assignment operator.
Private Attributes
const RelationsMap & myAdditionalWays
additional ways which are reference by relations
PCOSMEdge * myCurrentEdge
The currently built edge.
EdgeMap & myEdgeMap
A map of built edges.
MsgHandler & myErrorHandler
The handler to report errors to (will be the WarningsHandler if –ignore-errors was set)
bool myKeep
whether the last edge (way) should be kept because it had a key from the inclusion list
const std::map< long long int, PCOSMNode * > & myOSMNodes
The previously parsed nodes.
std::vector< int > myParentElements
Current path in order to know to what occuring values belong.
bool myWithAttributes
Whether all attributes shall be stored.
Detailed Description
A class which extracts OSM-edges from a parsed OSM-file.
Definition at line 293 of file PCLoaderOSM.h.
Constructor & Destructor Documentation
PCLoaderOSM::EdgesHandler::EdgesHandler (const std::map< long long int, PCOSMNode * > & osmNodes, EdgeMap & toFill, const RelationsMap & additionalWays, bool withAttributes, MsgHandler & errorHandler)
Constructor.
Parameters
[in] osmNodes The previously parsed (osm-)nodes
[in] toFill The edges container to fill with read edges
[in] withAttributes Whether all attributes shall be stored
[in] additionalWays Additional ways which were identified as polygons to import
[in] errorHandler The handler to report errors to (WarningHandler for ignoring errors)
Definition at line 439 of file PCLoaderOSM.cpp.
PCLoaderOSM::EdgesHandler::~EdgesHandler ()
Destructor.
Definition at line 452 of file PCLoaderOSM.cpp.
PCLoaderOSM::EdgesHandler::EdgesHandler (const EdgesHandler & s) private
Invalidated copy constructor.
Member Function Documentation
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 192 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 175 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 211 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), MSRouteHandler::myStartElement(), and MSRouteHandler::parseWalkPos().
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 217 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), MSStateHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 227 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void PCLoaderOSM::EdgesHandler::myEndElement (int element) protected virtual
Called when a closing tag occurs.
Parameters
[in] element ID of the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myEndElement
Reimplemented from GenericSAXHandler.
Definition at line 507 of file PCLoaderOSM.cpp.
References PCLoaderOSM::PCOSMEdge::id, myAdditionalWays, PCLoaderOSM::PCOSMEdge::myAttributes, myCurrentEdge, myEdgeMap, myKeep, myParentElements, and SUMO_TAG_WAY.
void PCLoaderOSM::EdgesHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Definition at line 457 of file PCLoaderOSM.cpp.
References SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), PCLoaderOSM::PCOSMEdge::id, MsgHandler::inform(), myAdditionalWays, PCLoaderOSM::PCOSMEdge::myAttributes, myCurrentEdge, PCLoaderOSM::PCOSMEdge::myCurrentNodes, myErrorHandler, PCLoaderOSM::PCOSMEdge::myIsClosed, myKeep, PCLoaderOSM::MyKeysToInclude, myOSMNodes, myParentElements, PCLoaderOSM::PCOSMEdge::name, SUMO_ATTR_ID, SUMO_ATTR_K, SUMO_ATTR_REF, SUMO_ATTR_V, SUMO_TAG_ND, SUMO_TAG_TAG, SUMO_TAG_WAY, toString(), and WRITE_WARNING.
EdgesHandler& PCLoaderOSM::EdgesHandler::operator= (const EdgesHandler & s) private
Invalidated assignment operator.
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 167 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 205 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
const RelationsMap& PCLoaderOSM::EdgesHandler::myAdditionalWays private
additional ways which are reference by relations
Definition at line 352 of file PCLoaderOSM.h.
Referenced by myEndElement(), and myStartElement().
PCOSMEdge* PCLoaderOSM::EdgesHandler::myCurrentEdge private
The currently built edge.
Definition at line 355 of file PCLoaderOSM.h.
Referenced by myEndElement(), and myStartElement().
EdgeMap& PCLoaderOSM::EdgesHandler::myEdgeMap private
A map of built edges.
Definition at line 349 of file PCLoaderOSM.h.
Referenced by myEndElement().
MsgHandler& PCLoaderOSM::EdgesHandler::myErrorHandler private
The handler to report errors to (will be the WarningsHandler if –ignore-errors was set)
Definition at line 343 of file PCLoaderOSM.h.
Referenced by myStartElement().
bool PCLoaderOSM::EdgesHandler::myKeep private
whether the last edge (way) should be kept because it had a key from the inclusion list
Definition at line 361 of file PCLoaderOSM.h.
Referenced by myEndElement(), and myStartElement().
const std::map<long long int, PCOSMNode*>& PCLoaderOSM::EdgesHandler::myOSMNodes private
The previously parsed nodes.
Definition at line 346 of file PCLoaderOSM.h.
Referenced by myStartElement().
std::vector<int> PCLoaderOSM::EdgesHandler::myParentElements private
Current path in order to know to what occuring values belong.
Definition at line 358 of file PCLoaderOSM.h.
Referenced by myEndElement(), and myStartElement().
bool PCLoaderOSM::EdgesHandler::myWithAttributes private
Whether all attributes shall be stored.
Definition at line 340 of file PCLoaderOSM.h.
The documentation for this class was generated from the following files:
PCLoaderOSM.h
PCLoaderOSM.cpp