SUMO - Simulation of Urban MObility: TraCIServerAPI_MeMeDetector Class Reference
TraCIServerAPI_MeMeDetector Class Reference
APIs for getting/setting multi-entry/multi-exit detector values via TraCI.
#include <TraCIServerAPI_MeMeDetector.h>
Static Public Member Functions
static bool processGet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a get value command (Command 0xa1: Get MeMeDetector Variable)
Private Member Functions
TraCIServerAPI_MeMeDetector & operator= (const TraCIServerAPI_MeMeDetector &s)
invalidated assignment operator
TraCIServerAPI_MeMeDetector (const TraCIServerAPI_MeMeDetector &s)
invalidated copy constructor
Detailed Description
APIs for getting/setting multi-entry/multi-exit detector values via TraCI.
Definition at line 48 of file TraCIServerAPI_MeMeDetector.h.
Constructor & Destructor Documentation
TraCIServerAPI_MeMeDetector::TraCIServerAPI_MeMeDetector (const TraCIServerAPI_MeMeDetector & s) private
invalidated copy constructor
Member Function Documentation
TraCIServerAPI_MeMeDetector& TraCIServerAPI_MeMeDetector::operator= (const TraCIServerAPI_MeMeDetector & s) private
invalidated assignment operator
bool TraCIServerAPI_MeMeDetector::processGet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a get value command (Command 0xa1: Get MeMeDetector Variable)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 47 of file TraCIServerAPI_MeMeDetector.cpp.
References CMD_GET_MULTI_ENTRY_EXIT_DETECTOR_VARIABLE, NamedObjectCont< T >::get(), MSE3Collector::getCurrentHaltingNumber(), MSE3Collector::getCurrentMeanSpeed(), MSE3Collector::getCurrentVehicleIDs(), MSNet::getDetectorControl(), MSNet::getInstance(), MSDetectorControl::getTypedDetectors(), MSE3Collector::getVehiclesWithin(), ID_COUNT, ID_LIST, NamedObjectCont< T >::insertIDs(), LAST_STEP_MEAN_SPEED, LAST_STEP_VEHICLE_HALTING_NUMBER, LAST_STEP_VEHICLE_ID_LIST, LAST_STEP_VEHICLE_NUMBER, tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), RESPONSE_GET_MULTI_ENTRY_EXIT_DETECTOR_VARIABLE, RTYPE_OK, SUMO_TAG_ENTRY_EXIT_DETECTOR, toHex(), TYPE_DOUBLE, TYPE_INTEGER, TYPE_STRINGLIST, tcpip::Storage::writeDouble(), TraCIServer::writeErrorStatusCmd(), tcpip::Storage::writeInt(), TraCIServer::writeResponseWithLength(), TraCIServer::writeStatusCmd(), tcpip::Storage::writeString(), tcpip::Storage::writeStringList(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCIServer::TraCIServer().
The documentation for this class was generated from the following files:
TraCIServerAPI_MeMeDetector.h
TraCIServerAPI_MeMeDetector.cpp