SUMO - Simulation of Urban MObility: DijkstraRouterEffort< E, V, PF > Class Template Reference
DijkstraRouterEffort< E, V, PF > Class Template Reference
Computes the shortest path through a network using the Dijkstra algorithm.
#include <DijkstraRouterEffort.h>
Data Structures
struct EdgeInfo
class EdgeInfoByEffortComparator
Public Types
typedef SUMOReal(* Operation) (const E *const, const V *const, SUMOReal)
Public Member Functions
void buildPathFrom (const EdgeInfo *rbegin, std::vector< const E * > &edges)
Builds the path from marked edges.
virtual SUMOAbstractRouter< E, V > * clone ()
virtual bool compute (const E *from, const E *to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > &into)
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
DijkstraRouterEffort (const std::vector< E * > &edges, bool unbuildIsWarning, Operation effortOperation, Operation ttOperation)
Constructor.
DijkstraRouterEffort (const std::vector< EdgeInfo > &edgeInfos, bool unbuildIsWarning, Operation effortOperation, Operation ttOperation)
void endQuery (int visits)
SUMOReal getEffort (const E *const e, const V *const v, SUMOReal t) const
SUMOReal getTravelTime (const E *const e, const V *const v, SUMOReal t) const
void init ()
SUMOReal recomputeCosts (const std::vector< const E * > &edges, const V *const v, SUMOTime msTime) const
void setBulkMode (const bool mode)
void startQuery ()
virtual ~DijkstraRouterEffort ()
Destructor.
Protected Attributes
bool myBulkMode
whether we are currently operating several route queries in a bulk
Operation myOperation
The object's operation to perform.
Private Attributes
EdgeInfoByEffortComparator myComparator
std::vector< EdgeInfo > myEdgeInfos
The container of edge information.
MsgHandler *const myErrorMsgHandler
the handler for routing errors
std::vector< EdgeInfo * > myFound
list of visited Edges (for resetting)
std::vector< EdgeInfo * > myFrontierList
A container for reusage of the min edge heap.
Operation myTTOperation
The object's operation to perform for travel times.
Detailed Description
template<class E, class V, class PF>
class DijkstraRouterEffort< E, V, PF >
Computes the shortest path through a network using the Dijkstra algorithm.
The template parameters are:
Parameters
E The edge class to use (MSEdge/ROEdge)
V The vehicle class to use (MSVehicle/ROVehicle)
PF The prohibition function to use (prohibited_withPermissions/noProhibitions)
EC The class to retrieve the effort for an edge from
The router is edge-based. It must know the number of edges for internal reasons and whether a missing connection between two given edges (unbuild route) shall be reported as an error or as a warning.
Definition at line 66 of file DijkstraRouterEffort.h.
Member Typedef Documentation
template<class E, class V, class PF> typedef SUMOReal(* DijkstraRouterEffort< E, V, PF >::Operation) (const E *const, const V *const, SUMOReal)
Definition at line 69 of file DijkstraRouterEffort.h.
Constructor & Destructor Documentation
template<class E, class V, class PF> DijkstraRouterEffort< E, V, PF >::DijkstraRouterEffort (const std::vector< E * > & edges, bool unbuildIsWarning, Operation effortOperation, Operation ttOperation) inline
Constructor.
Definition at line 120 of file DijkstraRouterEffort.h.
template<class E, class V, class PF> DijkstraRouterEffort< E, V, PF >::DijkstraRouterEffort (const std::vector< EdgeInfo > & edgeInfos, bool unbuildIsWarning, Operation effortOperation, Operation ttOperation) inline
Definition at line 128 of file DijkstraRouterEffort.h.
template<class E, class V, class PF> virtual DijkstraRouterEffort< E, V, PF >::~DijkstraRouterEffort () inline virtual
Destructor.
Definition at line 137 of file DijkstraRouterEffort.h.
Member Function Documentation
template<class E, class V, class PF> void DijkstraRouterEffort< E, V, PF >::buildPathFrom (const EdgeInfo * rbegin, std::vector< const E * > & edges) inline
Builds the path from marked edges.
Definition at line 257 of file DijkstraRouterEffort.h.
Referenced by DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> virtual SUMOAbstractRouter<E, V>* DijkstraRouterEffort< E, V, PF >::clone () inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 139 of file DijkstraRouterEffort.h.
template<class E, class V, class PF> virtual bool DijkstraRouterEffort< E, V, PF >::compute (const E * from, const E * to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > & into) inline virtual
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Implements SUMOAbstractRouter< E, V >.
Definition at line 162 of file DijkstraRouterEffort.h.
template<class E, class V> void SUMOAbstractRouter< E, V >::endQuery (int visits) inline inherited
Definition at line 96 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and CHRouter< E, V, PF >::compute().
template<class E, class V> SUMOReal SUMOAbstractRouter< E, V >::getEffort (const E *const e, const V *const v, SUMOReal t) const inline inherited
Definition at line 87 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), CHRouterWrapper< E, V, PF >::recomputeCosts(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), CHRouter< E, V, PF >::recomputeCosts(), and CHRouter< E, V, PF >::synchronize().
template<class E, class V, class PF> SUMOReal DijkstraRouterEffort< E, V, PF >::getTravelTime (const E *const e, const V *const v, SUMOReal t) const inline
Definition at line 143 of file DijkstraRouterEffort.h.
Referenced by DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts().
template<class E, class V, class PF> void DijkstraRouterEffort< E, V, PF >::init () inline
Definition at line 147 of file DijkstraRouterEffort.h.
Referenced by DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> SUMOReal DijkstraRouterEffort< E, V, PF >::recomputeCosts (const std::vector< const E * > & edges, const V *const v, SUMOTime msTime) const inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 242 of file DijkstraRouterEffort.h.
template<class E, class V> void SUMOAbstractRouter< E, V >::setBulkMode (const bool mode) inline inherited
Definition at line 101 of file SUMOAbstractRouter.h.
Referenced by ROMAAssignments::incremental().
template<class E, class V> void SUMOAbstractRouter< E, V >::startQuery () inline inherited
Definition at line 91 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and CHRouter< E, V, PF >::compute().
Field Documentation
template<class E, class V> bool SUMOAbstractRouter< E, V >::myBulkMode protected inherited
whether we are currently operating several route queries in a bulk
Definition at line 110 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::setBulkMode().
template<class E, class V, class PF> EdgeInfoByEffortComparator DijkstraRouterEffort< E, V, PF >::myComparator private
Definition at line 278 of file DijkstraRouterEffort.h.
Referenced by DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> std::vector<EdgeInfo> DijkstraRouterEffort< E, V, PF >::myEdgeInfos private
The container of edge information.
Definition at line 271 of file DijkstraRouterEffort.h.
Referenced by DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::DijkstraRouterEffort().
template<class E, class V, class PF> MsgHandler* const DijkstraRouterEffort< E, V, PF >::myErrorMsgHandler private
the handler for routing errors
Definition at line 281 of file DijkstraRouterEffort.h.
Referenced by DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), and DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute().
template<class E, class V, class PF> std::vector<EdgeInfo*> DijkstraRouterEffort< E, V, PF >::myFound private
list of visited Edges (for resetting)
Definition at line 276 of file DijkstraRouterEffort.h.
Referenced by DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::init().
template<class E, class V, class PF> std::vector<EdgeInfo*> DijkstraRouterEffort< E, V, PF >::myFrontierList private
A container for reusage of the min edge heap.
Definition at line 274 of file DijkstraRouterEffort.h.
Referenced by DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::init().
template<class E, class V> Operation SUMOAbstractRouter< E, V >::myOperation protected inherited
The object's operation to perform.
Definition at line 107 of file SUMOAbstractRouter.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), CHRouter< E, V, PF >::clone(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::getEffort().
template<class E, class V, class PF> Operation DijkstraRouterEffort< E, V, PF >::myTTOperation private
The object's operation to perform for travel times.
Definition at line 268 of file DijkstraRouterEffort.h.
Referenced by DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), and DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::getTravelTime().
The documentation for this class was generated from the following file:
DijkstraRouterEffort.h