SUMO - Simulation of Urban MObility: MSContainer Class Reference
MSContainer Class Reference
#include <MSContainer.h>
Data Structures
class MSContainerStage_Driving
class MSContainerStage_Tranship
Public Types
typedef std::vector< MSTransportable::Stage * > MSTransportablePlan
the structure holding the plan of a transportable
enum StageType { DRIVING = 0, WAITING = 1, MOVING_WITHOUT_VEHICLE = 2, WAITING_FOR_DEPART = 3 }
Public Member Functions
virtual SUMOReal getAngle () const
return the current angle of the transportable
MSTransportable::Stage * getCurrentStage () const
Return the current stage.
std::string getCurrentStageDescription () const
Returns the current stage description as a string.
StageType getCurrentStageType () const
the current stage type of the transportable
SUMOTime getDesiredDepart () const
Returns the desired departure time.
const MSEdge & getDestination () const
Returns the current destination.
const MSEdge * getEdge () const
Returns the current edge.
virtual SUMOReal getEdgePos () const
Return the position on the edge.
const MSEdge * getFromEdge () const
Returns the departure edge.
const std::string & getID () const
returns the id of the transportable
const MSEdge & getNextDestination () const
Returns the destination after the current destination.
const SUMOVehicleParameter & getParameter () const
virtual Position getPosition () const
Return the Network coordinate of the transportable.
virtual SUMOReal getSpeed () const
the current speed of the transportable
SUMOVehicle * getVehicle () const
The vehicle associated with this transportable.
const MSVehicleType & getVehicleType () const
virtual SUMOReal getWaitingSeconds () const
the time this transportable spent waiting in seconds
bool isWaiting4Vehicle () const
Whether the transportable waits for a vehicle.
bool isWaitingFor (const std::string &line) const
Whether the transportable waits for a vehicle of the line specified.
MSContainer (const SUMOVehicleParameter *pars, const MSVehicleType *vtype, MSTransportablePlan *plan)
constructor
virtual bool proceed (MSNet *net, SUMOTime time)
virtual void routeOutput (OutputDevice &os) const
Called on writing vehroute output.
void setDeparted (SUMOTime now)
logs depart time of the current stage
virtual void tripInfoOutput (OutputDevice &os) const
Called on writing tripinfo output.
virtual ~MSContainer ()
destructor
Protected Attributes
const SUMOVehicleParameter * myParameter
the plan of the transportable
MSTransportablePlan * myPlan
the plan of the transportable
MSTransportablePlan::iterator myStep
the iterator over the route
const MSVehicleType * myVType
This transportable's type. (mainly used for drawing related information Note sure if it is really necessary.
bool myWriteEvents
Whether events shall be written.
Static Protected Attributes
static const SUMOReal ROADSIDE_OFFSET
the offset for computing positions when standing at an edge
Private Member Functions
MSContainer (const MSContainer &)
Invalidated copy constructor.
MSContainer & operator= (const MSContainer &)
Invalidated assignment operator.
Detailed Description
The class holds a simulated container together with its movement stages
Definition at line 68 of file MSContainer.h.
Member Typedef Documentation
typedef std::vector<MSTransportable::Stage*> MSTransportable::MSTransportablePlan inherited
the structure holding the plan of a transportable
Definition at line 359 of file MSTransportable.h.
Member Enumeration Documentation
enum MSTransportable::StageType inherited
Enumerator
DRIVING
WAITING
MOVING_WITHOUT_VEHICLE
WAITING_FOR_DEPART
Definition at line 60 of file MSTransportable.h.
Constructor & Destructor Documentation
MSContainer::MSContainer (const SUMOVehicleParameter * pars, const MSVehicleType * vtype, MSTransportablePlan * plan)
constructor
Definition at line 235 of file MSContainer.cpp.
MSContainer::~MSContainer () virtual
destructor
Definition at line 240 of file MSContainer.cpp.
MSContainer::MSContainer (const MSContainer &) private
Invalidated copy constructor.
Member Function Documentation
SUMOReal MSTransportable::getAngle () const virtual inherited
return the current angle of the transportable
Reimplemented in GUIContainer.
Definition at line 364 of file MSTransportable.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), and SUMOReal.
Referenced by GUIPerson::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsPoly(), GUIPerson::drawAction_drawAsTriangle(), GUIContainer::getAngle(), GUIPerson::getNaviDegree(), TraCIServerAPI_Person::processGet(), GUIPerson::setFunctionalColor(), MSFCDExport::writeTransportable(), and MSXMLRawOut::writeTransportable().
MSTransportable::Stage* MSTransportable::getCurrentStage () const inline inherited
Return the current stage.
Definition at line 434 of file MSTransportable.h.
References MSTransportable::myStep, MSTransportable::Stage::routeOutput(), and MSTransportable::Stage::tripInfoOutput().
Referenced by GUIPerson::drawAction_drawWalkingareaPath(), GUIPerson::drawGLAdditional(), and MSEdge::transportable_by_position_sorter::operator()().
std::string MSTransportable::getCurrentStageDescription () const inline inherited
Returns the current stage description as a string.
Definition at line 429 of file MSTransportable.h.
Referenced by GUIContainer::getParameterWindow(), GUIPerson::getParameterWindow(), and MSXMLRawOut::writeTransportable().
StageType MSTransportable::getCurrentStageType () const inline inherited
the current stage type of the transportable
Definition at line 424 of file MSTransportable.h.
Referenced by MSPModel_Striping::add(), GUIContainer::drawGL(), GUIPerson::drawGL(), GUIPerson::drawGLAdditional(), GUIContainer::getColorValue(), GUIPerson::getColorValue(), MSPerson::getNextEdgePtr(), and GUIContainer::getPosition().
SUMOTime MSTransportable::getDesiredDepart () const inherited
Returns the desired departure time.
Definition at line 344 of file MSTransportable.cpp.
References SUMOVehicleParameter::depart, and MSTransportable::myParameter.
Referenced by MSTransportable::getVehicleType(), routeOutput(), MSPerson::routeOutput(), tripInfoOutput(), and MSPerson::tripInfoOutput().
const MSEdge& MSTransportable::getDestination () const inline inherited
Returns the current destination.
Definition at line 389 of file MSTransportable.h.
Referenced by GUIContainer::getParameterWindow(), GUIPerson::getParameterWindow(), MSDevice_Transportable::notifyLeave(), and MSDevice_Transportable::notifyMove().
const MSEdge* MSTransportable::getEdge () const inline inherited
Returns the current edge.
Definition at line 399 of file MSTransportable.h.
Referenced by MSPModel_Striping::add(), GUIContainer::getParameterWindow(), GUIPerson::getParameterWindow(), GUIContainer::getPosition(), and TraCIServerAPI_Person::processGet().
SUMOReal MSTransportable::getEdgePos () const virtual inherited
Return the position on the edge.
Reimplemented in GUIPerson, and GUIContainer.
Definition at line 354 of file MSTransportable.cpp.
References MSNet::getCurrentTimeStep(), and MSNet::getInstance().
Referenced by GUIContainer::getEdgePos(), GUIPerson::getEdgePos(), TraCIServerAPI_Person::processGet(), MSFCDExport::writeTransportable(), and MSXMLRawOut::writeTransportable().
const MSEdge* MSTransportable::getFromEdge () const inline inherited
Returns the departure edge.
Definition at line 404 of file MSTransportable.h.
References MSTransportable::Stage::getAngle(), MSTransportable::Stage::getEdgePos(), MSTransportable::Stage::getPosition(), MSTransportable::Stage::getSpeed(), MSTransportable::getWaitingSeconds(), and SUMOReal.
Referenced by GUIContainer::getParameterWindow(), and GUIPerson::getParameterWindow().
const std::string & MSTransportable::getID () const inherited
returns the id of the transportable
Definition at line 339 of file MSTransportable.cpp.
References SUMOVehicleParameter::id, and MSTransportable::myParameter.
Referenced by MSTransportableControl::abortWaiting(), MSVehicle::addContainer(), MSVehicle::addPerson(), MSPerson::MSPersonStage_Walking::beginEventOutput(), MSContainer::MSContainerStage_Tranship::beginEventOutput(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), MSPerson::MSPersonStage_Walking::endEventOutput(), MSContainer::MSContainerStage_Tranship::endEventOutput(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSTransportableControl::erase(), MSPModel_Striping::MovePedestrians::execute(), MSPModel_Striping::getNeighboringObstacles(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextLaneObstacles(), GUIContainer::getParameterWindow(), GUIPerson::getParameterWindow(), MSPedestrianPushButton::isActiveForEdge(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), MSPModel_Striping::PState::moveToNextLane(), MSDevice_Transportable::notifyLeave(), MSPModel_Striping::by_xpos_sorter::operator()(), MSEdge::transportable_by_position_sorter::operator()(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSPModel_Striping::PState::PState(), MSContainer::MSContainerStage_Driving::routeOutput(), MSTransportable::Stage_Waiting::routeOutput(), MSPerson::MSPersonStage_Driving::routeOutput(), routeOutput(), MSPerson::routeOutput(), tripInfoOutput(), MSPerson::tripInfoOutput(), MSPModel_Striping::PState::walk(), MSFCDExport::writeTransportable(), and MSXMLRawOut::writeTransportable().
const MSEdge& MSTransportable::getNextDestination () const inline inherited
Returns the destination after the current destination.
Definition at line 394 of file MSTransportable.h.
References MSTransportable::myStep.
const SUMOVehicleParameter& MSTransportable::getParameter () const inline inherited
Definition at line 374 of file MSTransportable.h.
References MSTransportable::myParameter.
Referenced by MSTransportableControl::add(), GUIPerson::getParameterWindow(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Person::processSet(), GUIContainer::setFunctionalColor(), and GUIPerson::setFunctionalColor().
Position MSTransportable::getPosition () const virtual inherited
Return the Network coordinate of the transportable.
Reimplemented in GUIPerson, and GUIContainer.
Definition at line 359 of file MSTransportable.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), and SUMOReal.
Referenced by TraCIServerAPI_Person::getPosition(), GUIContainer::getPosition(), GUIPerson::getPosition(), TraCIServerAPI_Person::processGet(), and MSFCDExport::writeTransportable().
SUMOReal MSTransportable::getSpeed () const virtual inherited
the current speed of the transportable
Reimplemented in GUIPerson, and GUIContainer.
Definition at line 374 of file MSTransportable.cpp.
Referenced by GUIContainer::getSpeed(), GUIPerson::getSpeed(), TraCIServerAPI_Person::processGet(), and MSFCDExport::writeTransportable().
SUMOVehicle* MSTransportable::getVehicle () const inline inherited
The vehicle associated with this transportable.
Definition at line 463 of file MSTransportable.h.
const MSVehicleType& MSTransportable::getVehicleType () const inline inherited
Definition at line 378 of file MSTransportable.h.
References MSTransportable::getDesiredDepart(), MSTransportable::myVType, and MSTransportable::Stage::setDeparted().
Referenced by MSStoppingPlace::addTransportable(), GUIContainer::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsImage(), GUIContainer::drawAction_drawAsPoly(), GUIPerson::drawAction_drawAsPoly(), GUIPerson::drawAction_drawAsTriangle(), GUIPerson::getCenteringBoundary(), MSPModel_Striping::PState::getImpatience(), MSPModel_Striping::PState::getLength(), MSPModel_Striping::PState::getMinGap(), MSPModel_Striping::getNextLaneObstacles(), MSPModel_Striping::PState::otherStripe(), TraCIServerAPI_Person::processGet(), MSStoppingPlace::removeTransportable(), GUIContainer::setFunctionalColor(), and GUIPerson::setFunctionalColor().
SUMOReal MSTransportable::getWaitingSeconds () const virtual inherited
the time this transportable spent waiting in seconds
Reimplemented in GUIPerson, and GUIContainer.
Definition at line 369 of file MSTransportable.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), STEPS2TIME, and SUMOReal.
Referenced by MSTransportable::getFromEdge(), GUIContainer::getWaitingSeconds(), GUIPerson::getWaitingSeconds(), MSPedestrianPushButton::isActiveForEdge(), and TraCIServerAPI_Person::processGet().
bool MSTransportable::isWaiting4Vehicle () const inline inherited
Whether the transportable waits for a vehicle.
Definition at line 458 of file MSTransportable.h.
Referenced by GUIContainer::drawGL(), GUIPerson::drawGL(), GUIContainer::getColorValue(), and GUIPerson::getColorValue().
bool MSTransportable::isWaitingFor (const std::string & line) const inline inherited
Whether the transportable waits for a vehicle of the line specified.
Definition at line 453 of file MSTransportable.h.
MSContainer& MSContainer::operator= (const MSContainer &) private
Invalidated assignment operator.
bool MSContainer::proceed (MSNet * net, SUMOTime time) virtual
Implements MSTransportable.
Definition at line 245 of file MSContainer.cpp.
References MSTransportable::Stage::getEdge(), MSTransportable::myPlan, MSTransportable::myStep, MSEdge::removeContainer(), and MSTransportable::Stage::setArrived().
void MSContainer::routeOutput (OutputDevice & os) const virtual
Called on writing vehroute output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable.
Definition at line 270 of file MSContainer.cpp.
References OutputDevice::closeTag(), MSTransportable::getDesiredDepart(), MSTransportable::getID(), MSNet::getInstance(), OutputDevice::lf(), MSTransportable::myPlan, MSTransportable::myStep, OutputDevice::openTag(), SUMO_ATTR_DEPART, SUMO_ATTR_ID, SUMO_TAG_CONTAINER, time2string(), and OutputDevice::writeAttr().
void MSTransportable::setDeparted (SUMOTime now) inherited
logs depart time of the current stage
Definition at line 349 of file MSTransportable.cpp.
References SUMOReal.
void MSContainer::tripInfoOutput (OutputDevice & os) const virtual
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implements MSTransportable.
Definition at line 260 of file MSContainer.cpp.
References OutputDevice::closeTag(), MSTransportable::getDesiredDepart(), MSTransportable::getID(), MSTransportable::myPlan, OutputDevice::openTag(), time2string(), and OutputDevice::writeAttr().
Field Documentation
const SUMOVehicleParameter* MSTransportable::myParameter protected inherited
the plan of the transportable
Definition at line 472 of file MSTransportable.h.
Referenced by MSTransportable::getDesiredDepart(), MSTransportable::getID(), MSTransportable::getParameter(), and MSTransportable::~MSTransportable().
MSTransportablePlan* MSTransportable::myPlan protected inherited
the plan of the transportable
Definition at line 482 of file MSTransportable.h.
Referenced by MSTransportable::MSTransportable(), proceed(), MSPerson::proceed(), routeOutput(), MSPerson::routeOutput(), tripInfoOutput(), MSPerson::tripInfoOutput(), and MSTransportable::~MSTransportable().
MSTransportablePlan::iterator MSTransportable::myStep protected inherited
the iterator over the route
Definition at line 485 of file MSTransportable.h.
Referenced by MSTransportable::getCurrentStage(), MSTransportable::getNextDestination(), MSTransportable::MSTransportable(), proceed(), MSPerson::proceed(), routeOutput(), and MSPerson::routeOutput().
const MSVehicleType* MSTransportable::myVType protected inherited
This transportable's type. (mainly used for drawing related information Note sure if it is really necessary.
Definition at line 476 of file MSTransportable.h.
Referenced by GUIPerson::getParameterWindow(), and MSTransportable::getVehicleType().
bool MSTransportable::myWriteEvents protected inherited
Whether events shall be written.
Definition at line 479 of file MSTransportable.h.
const SUMOReal MSTransportable::ROADSIDE_OFFSET static protected inherited
the offset for computing positions when standing at an edge
Definition at line 469 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Waiting::getPosition(), and MSTransportable::Stage_Driving::getPosition().
The documentation for this class was generated from the following files:
MSContainer.h
MSContainer.cpp