SUMO - Simulation of Urban MObility: PHEMlightdll.PHEMLight Class Reference
PHEMlightdll.PHEMLight Class Reference
Static Public Member Functions
static VehicleResult CreateVehicleStateData (Helpers Helper, CEP currCep, double time, double inputSpeed, double inputAcc, double Gradient=0)
Detailed Description
Definition at line 415 of file Start.cs.
Member Function Documentation
static VehicleResult PHEMlightdll.PHEMLight.CreateVehicleStateData (Helpers Helper, CEP currCep, double time, double inputSpeed, double inputAcc, double Gradient = 0) inline static
Definition at line 418 of file Start.cs.
References PHEMlightdll::CEP.CalcEngPower(), PHEMlightdll::CEP.CalcPower(), PHEMlightdll::CEP.DrivingPower, PHEMlightdll::CEP.GetCO2Emission(), PHEMlightdll::CEP.GetDecelCoast(), PHEMlightdll::CEP.GetEmission(), PHEMlightdll.Start.Helper, PHEMlightdll::CEP.RatedPower, PHEMlightdll::Constants.strBEV, and PHEMlightdll::Helpers.tClass.
Referenced by PHEMlightdll.Start.CALC_Array(), and PHEMlightdll.Start.CALC_Single().
The documentation for this class was generated from the following file:
Start.cs