SUMO - Simulation of Urban MObility: MSDevice_Battery Class Reference
MSDevice_Battery Class Reference
Battery device for electric vehicles.
#include <MSDevice_Battery.h>
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED
}
Definition of a vehicle state.
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
void generateOutput () const
Called on writing tripinfo output.
SUMOReal getActualBatteryCapacity () const
Get the actual vehicle's Battery Capacity in kWh.
SUMOReal getAirDragCoefficient () const
Get vehicle's drag coefficient.
SUMOReal getChargingStartTime () const
Get charging start time.
std::string getChargingStationID () const
Get current Charging Station ID.
SUMOReal getConstantPowerIntake () const
Get vehicles's constant power intake.
SUMOReal getConsum () const
Get consum.
const std::string & getDescription () const
SUMOReal getEnergyCharged () const
Get charged energy.
SUMOReal getFrontSurfaceArea () const
Get vehicle's front surface Area.
SUMOVehicle & getHolder () const
Returns the vehicle that holds this device.
const std::string & getID () const
Returns the id.
SUMOReal getInternalMomentOfInertia () const
Get vehicles's internal moment of inertia.
const MSLane * getLane () const
Returns the lane the reminder works on.
SUMOReal getLastAngle () const
Get vehicles's last angle.
SUMOReal getLastEnergy () const
Get vehicles's last Energy.
SUMOReal getMass () const
Get vehicle's mass.
SUMOReal getMaximumBatteryCapacity () const
Get the total vehicle's Battery Capacity in kWh.
SUMOReal getMaximumPower () const
Get the maximum power when accelerating.
SUMOReal getPropEnergy (SUMOVehicle &veh)
get propulsion energy
SUMOReal getPropulsionEfficiency () const
Get vehicles's Propulsion efficiency.
SUMOReal getRadialDragCoefficient () const
Get vehicles's radial friction coefficient.
SUMOReal getRecuperationEfficiency () const
Get vehicles's Recuparation efficiency.
SUMOReal getRollDragCoefficient () const
Get vehicles's roll friction coefficient.
int getVehicleStopped () const
Get number of timestep that vehicle is stopped.
void increaseChargingStartTime ()
Increase Charging Start time.
void increaseVehicleStoppedTimer ()
Increase myVehicleStopped.
bool isChargingInTransit () const
Get true if Vehicle it's charging, false if not.
bool isChargingStopped () const
Get true if Vehicle is charging, false if not.
virtual void notifyMoveInternal (SUMOVehicle &veh, SUMOReal timeOnLane, SUMOReal speed)
Internal notification about the vehicle moves.
void resetChargingStartTime ()
Reset charging start time.
void resetVehicleStoppedTimer ()
Reset myVehicleStopped.
void setActualBatteryCapacity (const SUMOReal actualBatteryCapacity)
Set actual vehicle's Battery Capacity in kWh.
void setAirDragCoefficient (const SUMOReal new_C_Veh)
Set vehicle's drag coefficient.
void setConstantPowerIntake (const SUMOReal constantPowerIntake)
Set vehicle's constant power intake.
void setDescription (const std::string &description)
void setFrontSurfaceArea (const SUMOReal frontSurfaceArea)
Set vehicle's front surface Area.
void setID (const std::string &newID)
resets the id
void setInternalMomentOfInertia (const SUMOReal internalMomentOfInertia)
Set vehicle's internal moment of inertia.
void setLastAngle (const SUMOReal lastAngle)
Set vehicle's last Angle.
void setLastEnergy (const SUMOReal lastEnergy)
Set vehicle's last Energy.
void setMass (const SUMOReal mass)
Set vehicle's myMass.
void setMaximumBatteryCapacity (const SUMOReal maximumBatteryCapacity)
Set total vehicle's Battery Capacity in kWh.
void setPowerMax (const SUMOReal new_Pmax)
Set maximum power when accelerating.
void setPropulsionEfficiency (const SUMOReal propulsionEfficiency)
Set vehicle's Propulsion efficiency.
void setRadialDragCoefficient (const SUMOReal radialDragCoefficient)
Set vehicle's radial friction coefficient.
void setRecuperationEfficiency (const SUMOReal recuperationEfficiency)
Set vehicle's Recuparation efficiency.
void setRollDragCoefficient (const SUMOReal rollDragCoefficient)
Set vehicle's roll friction coefficient.
~MSDevice_Battery ()
Destructor.
Methods called on vehicle movement / state change, overwriting MSDevice
bool notifyMove (SUMOVehicle &veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed)
Checks for waiting steps when the vehicle moves.
bool notifyEnter (SUMOVehicle &veh, MSMoveReminder::Notification reason)
Saves departure info on insertion.
Interface methods, to be derived by subclasses
virtual bool notifyLeave (SUMOVehicle &veh, SUMOReal lastPos, Notification reason)
Called if the vehicle leaves the reminder's lane.
void updateDetector (SUMOVehicle &veh, SUMOReal entryPos, SUMOReal leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp)
Static Public Member Functions
static void buildVehicleDevices (SUMOVehicle &v, std::vector< MSDevice * > &into)
Build devices for the given vehicle, if needed.
static bool checkOptions (OptionsCont &oc)
check device-specific options
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
static void insertOptions (OptionsCont &oc)
Inserts MSDevice_Example-options.
Protected Member Functions
void removeFromVehicleUpdateValues (SUMOVehicle &veh)
Static Protected Member Functions
Helper methods for device assignment
static void insertDefaultAssignmentOptions (const std::string &deviceName, const std::string &optionsTopic, OptionsCont &oc)
Adds common command options that allow to assign devices to vehicles.
static bool equippedByDefaultAssignmentOptions (const OptionsCont &oc, const std::string &deviceName, SUMOVehicle &v)
Determines whether a vehicle should get a certain device.
Protected Attributes
MSChargingStation * myActChargingStation
Parameter, Pointer to current charging station in which vehicle is placed by default is NULL.
SUMOReal myActualBatteryCapacity
Parameter, The actual vehicles's Battery Capacity in kWh [myActualBatteryCapacity <= myMaximumBatteryCapacity].
SUMOReal myAirDragCoefficient
Parameter, Vehicle's drag coefficient [myAirDragCoefficient >=0].
bool myChargingInTransit
Parameter, Flag: Vehicles it's charging in transit by default is false.
SUMOReal myChargingStartTime
Parameter, Moment, wich the vehicle has beging to charging none.
bool myChargingStopped
Parameter, Flag: Vehicles it's charging stopped by default is false.
SUMOReal myConstantPowerIntake
Parameter, Vehicle's constant power intake [myConstantPowerIntake >= 0].
SUMOReal myConsum
Parameter, Vehicle consum during a time step by default is 0.
std::string myDescription
a description of this moveReminder
SUMOReal myEnergyCharged
Parameter, Energy charged in each timestep.
SUMOReal myFrontSurfaceArea
Parameter, Vehicle's front surface Area [myFrontSurfaceArea >= 0].
SUMOVehicle & myHolder
The vehicle that stores the device.
std::string myID
The name of the object.
SUMOReal myInternalMomentOfInertia
Parameter, Vehicle's internal moment of inertia [myInternalMomentOfInertia >= 0].
MSLane *const myLane
Lane on which the reminder works.
SUMOReal myLastAngle
Parameter, Vehicle's last angle none.
SUMOReal myLastEnergy
Parameter, Vehicle's last energy none.
SUMOReal myMass
Parameter, Vehicle's myMass [myMass >= 0].
SUMOReal myMaximumBatteryCapacity
Parameter, The total vehicles's Battery Capacity in kWh [myMaximumBatteryCapacity >= 0].
SUMOReal myPowerMax
Parameter, The Maximum Power when accelerating [myPowerMax >= 0].
SUMOReal myPropulsionEfficiency
Parameter, Vehicle's propulsion efficiency [1 >= myPropulsionEfficiency >= 0].
SUMOReal myRadialDragCoefficient
Parameter, Vehicle's radial friction coefficient [myRadialDragCoefficient >=0].
SUMOReal myRecuperationEfficiency
Parameter, Vehicle's recuparation efficiency [1 >= myRecuperationEfficiency >= 0].
SUMOReal myRollDragCoefficient
Parameter, Vehicle's roll friction coefficient [myRollDragCoefficient >= 0].
int myVehicleStopped
Parameter, How many timestep the vehicle is stopped.
Private Member Functions
MSDevice_Battery (SUMOVehicle &holder, const std::string &id, const SUMOReal actualBatteryCapacity, const SUMOReal maximumBatteryCapacity, const SUMOReal powerMax, const SUMOReal mass, const SUMOReal frontSurfaceArea, const SUMOReal airDragCoefficient, const SUMOReal internalMomentOfInertia, const SUMOReal radialDragCoefficient, const SUMOReal rollDragCoefficient, const SUMOReal constantPowerIntake, const SUMOReal propulsionEfficiency, const SUMOReal recuperationEfficiency, const SUMOReal lastAngle, const SUMOReal lastEnergy)
Constructor.
MSDevice_Battery (const MSDevice_Battery &)
Invalidated copy constructor.
MSDevice_Battery & operator= (const MSDevice_Battery &)
Invalidated assignment operator.
Detailed Description
Battery device for electric vehicles.
Definition at line 54 of file MSDevice_Battery.h.
Member Enumeration Documentation
enum MSMoveReminder::Notification inherited
Definition of a vehicle state.
Enumerator
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network)
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only)
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only)
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted)
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
Definition at line 95 of file MSMoveReminder.h.
Constructor & Destructor Documentation
MSDevice_Battery::~MSDevice_Battery ()
Destructor.
Definition at line 349 of file MSDevice_Battery.cpp.
MSDevice_Battery::MSDevice_Battery (SUMOVehicle & holder, const std::string & id, const SUMOReal actualBatteryCapacity, const SUMOReal maximumBatteryCapacity, const SUMOReal powerMax, const SUMOReal mass, const SUMOReal frontSurfaceArea, const SUMOReal airDragCoefficient, const SUMOReal internalMomentOfInertia, const SUMOReal radialDragCoefficient, const SUMOReal rollDragCoefficient, const SUMOReal constantPowerIntake, const SUMOReal propulsionEfficiency, const SUMOReal recuperationEfficiency, const SUMOReal lastAngle, const SUMOReal lastEnergy) private
Constructor.
Parameters
[in] holder The vehicle that holds this device
[in] id The ID of the device
[in] period The period with which a new route shall be searched
[in] preInsertionPeriod The route search period before insertion
Definition at line 251 of file MSDevice_Battery.cpp.
References TplConvert::_2str(), Named::getID(), myActualBatteryCapacity, myAirDragCoefficient, myConstantPowerIntake, myFrontSurfaceArea, myInternalMomentOfInertia, myMass, myMaximumBatteryCapacity, myPowerMax, myPropulsionEfficiency, myRadialDragCoefficient, myRecuperationEfficiency, myRollDragCoefficient, and WRITE_WARNING.
Referenced by buildVehicleDevices().
MSDevice_Battery::MSDevice_Battery (const MSDevice_Battery &) private
Invalidated copy constructor.
Member Function Documentation
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
void MSDevice_Battery::buildVehicleDevices (SUMOVehicle & v, std::vector< MSDevice * > & into) static
Build devices for the given vehicle, if needed.
The options are read and evaluated whether a example-device shall be built for the given vehicle.
The built device is stored in the given vector.
Parameters
[in] v The vehicle for which a device may be built
Definition at line 61 of file MSDevice_Battery.cpp.
References TplConvert::_2SUMOReal(), MSDevice::equippedByDefaultAssignmentOptions(), SUMOVehicle::getID(), OptionsCont::getOptions(), Parameterised::getParameter(), SUMOVehicle::getParameter(), MSVehicleType::getParameter(), SUMOVehicle::getVehicleType(), MSDevice_Battery(), and SUMOReal.
Referenced by MSDevice::buildVehicleDevices().
bool MSDevice::checkOptions (OptionsCont & oc) static inherited
check device-specific options
Parameters
Definition at line 73 of file MSDevice.cpp.
References MSDevice_Routing::checkOptions().
Referenced by MSFrame::checkOptions().
bool MSDevice::equippedByDefaultAssignmentOptions (const OptionsCont & oc, const std::string & deviceName, SUMOVehicle & v) static protected inherited
Determines whether a vehicle should get a certain device.
Parameters
[in] oc The options container to get the information about assignment from
[in] deviceName The name of the device type
[in] v The vehicle to determine whether it shall be equipped or not
Definition at line 108 of file MSDevice.cpp.
References TplConvert::_2bool(), OptionsCont::exists(), OptionsCont::getBool(), OptionsCont::getFloat(), SUMOVehicle::getID(), MSNet::getInstance(), OptionsCont::getOptions(), Parameterised::getParameter(), SUMOVehicle::getParameter(), MSVehicleType::getParameter(), MSVehicleControl::getQuota(), OptionsCont::getStringVector(), MSNet::getVehicleControl(), SUMOVehicle::getVehicleType(), OptionsCont::isSet(), Parameterised::knowsParameter(), MSDevice::myExplicitIDs, and RandHelper::rand().
Referenced by buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice_BTreceiver::buildVehicleDevices(), MSDevice_BTsender::buildVehicleDevices(), MSDevice_Emissions::buildVehicleDevices(), MSDevice_Routing::buildVehicleDevices(), and MSDevice::generateOutput().
void MSDevice_Battery::generateOutput () const virtual
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
See also
MSDevice::generateOutput
Reimplemented from MSDevice.
Definition at line 243 of file MSDevice_Battery.cpp.
SUMOReal MSDevice_Battery::getActualBatteryCapacity () const
Get the actual vehicle's Battery Capacity in kWh.
Definition at line 512 of file MSDevice_Battery.cpp.
References myActualBatteryCapacity, and SUMOReal.
Referenced by notifyMove(), and MSBatteryExport::write().
SUMOReal MSDevice_Battery::getAirDragCoefficient () const
Get vehicle's drag coefficient.
Definition at line 542 of file MSDevice_Battery.cpp.
References myAirDragCoefficient, and SUMOReal.
Referenced by getPropEnergy().
SUMOReal MSDevice_Battery::getChargingStartTime () const
Get charging start time.
Definition at line 614 of file MSDevice_Battery.cpp.
References myChargingStartTime.
Referenced by notifyMove().
std::string MSDevice_Battery::getChargingStationID () const
Get current Charging Station ID.
Definition at line 620 of file MSDevice_Battery.cpp.
References Named::getID(), myActChargingStation, and SUMOReal.
Referenced by MSBatteryExport::write().
SUMOReal MSDevice_Battery::getConstantPowerIntake () const
Get vehicles's constant power intake.
Definition at line 566 of file MSDevice_Battery.cpp.
References myConstantPowerIntake, and SUMOReal.
Referenced by getPropEnergy().
SUMOReal MSDevice_Battery::getConsum () const
Get consum.
Definition at line 596 of file MSDevice_Battery.cpp.
References myConsum.
Referenced by MSBatteryExport::write().
const std::string& MSMoveReminder::getDescription () const inline inherited
Definition at line 213 of file MSMoveReminder.h.
References MSMoveReminder::myDescription, and MSMoveReminder::removeFromVehicleUpdateValues().
Referenced by MSBaseVehicle::addStops().
SUMOReal MSDevice_Battery::getEnergyCharged () const
Get charged energy.
Definition at line 630 of file MSDevice_Battery.cpp.
References myEnergyCharged.
Referenced by MSBatteryExport::write().
SUMOReal MSDevice_Battery::getFrontSurfaceArea () const
Get vehicle's front surface Area.
Definition at line 536 of file MSDevice_Battery.cpp.
References myFrontSurfaceArea, and SUMOReal.
Referenced by getPropEnergy().
SUMOVehicle& MSDevice::getHolder () const inline inherited
Returns the vehicle that holds this device.
Returns
The vehicle that holds this device
Definition at line 110 of file MSDevice.h.
References MSDevice::myHolder.
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciBusOrContainerStop(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNEConnectorFrame::buildIinternalLanes(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), NLDetectorBuilder::convUncontE2PosLength(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSVehicle::getBackPosition(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), GNEEdge::getDest(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), MSE2Collector::getEstimateQueueLength(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), GNEEdge::getSource(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSE2Collector::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_SL2015::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_LC2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_ArealDetector::processGet(), TraCIServerAPI_Lane::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), MSBaseVehicle::reroute(), MSLane::resetPartialOccupation(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), MSLane::saveState(), setAirDragCoefficient(), NBNodeCont::setAsTLControlled(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), setConstantPowerIntake(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), setFrontSurfaceArea(), setInternalMomentOfInertia(), GNEJunction::setLogicValid(), setMass(), setMaximumBatteryCapacity(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), setPowerMax(), setPropulsionEfficiency(), setRadialDragCoefficient(), setRecuperationEfficiency(), MSLink::setRequestInformation(), setRollDragCoefficient(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), operator<<(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
SUMOReal MSDevice_Battery::getInternalMomentOfInertia () const
Get vehicles's internal moment of inertia.
Definition at line 548 of file MSDevice_Battery.cpp.
References myInternalMomentOfInertia, and SUMOReal.
Referenced by getPropEnergy(), and notifyEnter().
const MSLane* MSMoveReminder::getLane () const inline inherited
Returns the lane the reminder works on.
Returns
The lane the reminder works on.
Definition at line 89 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by MSDevice_Tripinfo::computeLengthAndDuration(), MSE2Collector::detectorUpdate(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_InductionLoop::getTree(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_ArealDetector::processGet(), and MSMeanData::writeEdge().
SUMOReal MSDevice_Battery::getLastAngle () const
Get vehicles's last angle.
Definition at line 584 of file MSDevice_Battery.cpp.
References myLastAngle, and SUMOReal.
Referenced by getPropEnergy().
SUMOReal MSDevice_Battery::getLastEnergy () const
Get vehicles's last Energy.
Definition at line 590 of file MSDevice_Battery.cpp.
References myLastEnergy, and SUMOReal.
Referenced by getPropEnergy().
SUMOReal MSDevice_Battery::getMass () const
Get vehicle's mass.
Definition at line 530 of file MSDevice_Battery.cpp.
References myMass, and SUMOReal.
Referenced by getPropEnergy(), and notifyEnter().
SUMOReal MSDevice_Battery::getMaximumBatteryCapacity () const
Get the total vehicle's Battery Capacity in kWh.
Definition at line 518 of file MSDevice_Battery.cpp.
References myMaximumBatteryCapacity, and SUMOReal.
Referenced by notifyMove(), and MSBatteryExport::write().
SUMOReal MSDevice_Battery::getMaximumPower () const
Get the maximum power when accelerating.
Definition at line 524 of file MSDevice_Battery.cpp.
References myPowerMax, and SUMOReal.
SUMOReal MSDevice_Battery::getPropEnergy (SUMOVehicle & veh)
get propulsion energy
Definition at line 640 of file MSDevice_Battery.cpp.
References GeomHelper::angleDiff(), getAirDragCoefficient(), SUMOVehicle::getAngle(), getConstantPowerIntake(), getFrontSurfaceArea(), getInternalMomentOfInertia(), SUMOVehicle::getLane(), getLastAngle(), getLastEnergy(), MSLane::getLength(), getMass(), SUMOVehicle::getPositionOnLane(), getPropulsionEfficiency(), getRadialDragCoefficient(), getRecuperationEfficiency(), getRollDragCoefficient(), MSLane::getShape(), SUMOVehicle::getSpeed(), setLastEnergy(), SPEED2DIST, and SUMOReal.
Referenced by notifyMove().
SUMOReal MSDevice_Battery::getPropulsionEfficiency () const
Get vehicles's Propulsion efficiency.
Definition at line 572 of file MSDevice_Battery.cpp.
References myPropulsionEfficiency, and SUMOReal.
Referenced by getPropEnergy().
SUMOReal MSDevice_Battery::getRadialDragCoefficient () const
Get vehicles's radial friction coefficient.
Definition at line 554 of file MSDevice_Battery.cpp.
References myRadialDragCoefficient, and SUMOReal.
Referenced by getPropEnergy().
SUMOReal MSDevice_Battery::getRecuperationEfficiency () const
Get vehicles's Recuparation efficiency.
Definition at line 578 of file MSDevice_Battery.cpp.
References myRecuperationEfficiency, and SUMOReal.
Referenced by getPropEnergy().
SUMOReal MSDevice_Battery::getRollDragCoefficient () const
Get vehicles's roll friction coefficient.
Definition at line 560 of file MSDevice_Battery.cpp.
References myRollDragCoefficient, and SUMOReal.
Referenced by getPropEnergy().
int MSDevice_Battery::getVehicleStopped () const
Get number of timestep that vehicle is stopped.
Definition at line 635 of file MSDevice_Battery.cpp.
References myVehicleStopped.
Referenced by MSBatteryExport::write().
void MSDevice_Battery::increaseChargingStartTime ()
Increase Charging Start time.
Definition at line 494 of file MSDevice_Battery.cpp.
References myChargingStartTime.
Referenced by notifyMove().
void MSDevice_Battery::increaseVehicleStoppedTimer ()
Increase myVehicleStopped.
Definition at line 506 of file MSDevice_Battery.cpp.
References myVehicleStopped, and SUMOReal.
Referenced by notifyMove().
void MSDevice::insertDefaultAssignmentOptions (const std::string & deviceName, const std::string & optionsTopic, OptionsCont & oc) static protected inherited
Adds common command options that allow to assign devices to vehicles.
Parameters
[in] deviceName The name of the device type
[in] optionsTopic The options topic into which the options shall be added
!! describe
!! describe
!! describe
Definition at line 94 of file MSDevice.cpp.
References OptionsCont::addDescription(), OptionsCont::addSynonyme(), and OptionsCont::doRegister().
Referenced by MSDevice::generateOutput(), insertOptions(), MSDevice_Example::insertOptions(), MSDevice_BTreceiver::insertOptions(), MSDevice_BTsender::insertOptions(), MSDevice_Emissions::insertOptions(), and MSDevice_Routing::insertOptions().
void MSDevice_Battery::insertOptions (OptionsCont & oc) static
Inserts MSDevice_Example-options.
Parameters
Definition at line 55 of file MSDevice_Battery.cpp.
References MSDevice::insertDefaultAssignmentOptions().
Referenced by MSDevice::insertOptions().
bool MSDevice_Battery::isChargingInTransit () const
Get true if Vehicle it's charging, false if not.
Definition at line 608 of file MSDevice_Battery.cpp.
References myChargingInTransit, and SUMOReal.
Referenced by MSBatteryExport::write().
bool MSDevice_Battery::isChargingStopped () const
Get true if Vehicle is charging, false if not.
Definition at line 602 of file MSDevice_Battery.cpp.
References myChargingStopped.
Referenced by MSBatteryExport::write().
bool MSDevice_Battery::notifyEnter (SUMOVehicle & veh, MSMoveReminder::Notification reason) virtual
Saves departure info on insertion.
Parameters
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
Returns
Always true
See also
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented from MSMoveReminder.
Definition at line 231 of file MSDevice_Battery.cpp.
References PositionVector::beginEndAngle(), getInternalMomentOfInertia(), SUMOVehicle::getLane(), getMass(), MSLane::getShape(), SUMOVehicle::getSpeed(), MSMoveReminder::NOTIFICATION_DEPARTED, setLastAngle(), and setLastEnergy().
virtual bool MSMoveReminder::notifyLeave (SUMOVehicle & veh, SUMOReal lastPos, Notification reason) inline virtual inherited
Called if the vehicle leaves the reminder's lane.
Informs if vehicle leaves reminder lane (due to lane change, removal from the network, or leaving to the next lane). The default is to do nothing.
Parameters
[in] veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] reason how the vehicle leaves the lane
See also
Notification
Returns
True if the reminder wants to receive further info.
Reimplemented in MSMeanData::MeanDataValueTracker, MSE3Collector::MSE3LeaveReminder, MSInductLoop, MSE2Collector, MSTriggeredRerouter, MSDevice_BTsender, MSDevice_BTreceiver, MSMeanData::MeanDataValues, MSDevice_Tripinfo, MSDevice_Example, MSInstantInductLoop, MSDevice_Vehroutes, MSE3Collector::MSE3EntryReminder, MSMeanData_Net::MSLaneMeanDataValues, and MSDevice_Transportable.
Definition at line 175 of file MSMoveReminder.h.
References SUMOReal, UNUSED_PARAMETER, and MSMoveReminder::updateDetector().
bool MSDevice_Battery::notifyMove (SUMOVehicle & veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed) virtual
Checks for waiting steps when the vehicle moves.
Parameters
[in] veh Vehicle that asks this reminder.
[in] oldPos Position before move.
[in] newPos Position after move with newSpeed.
[in] newSpeed Moving speed.
Returns
True (always).
Reimplemented from MSMoveReminder.
Definition at line 118 of file MSDevice_Battery.cpp.
References getActualBatteryCapacity(), SUMOVehicle::getAngle(), MSChargingStation::getChargeDelay(), MSChargingStation::getChargeInTransit(), MSChargingStation::getChargingPower(), getChargingStartTime(), MSNet::getChargingStation(), MSNet::getChargingStationID(), MSChargingStation::getEfficency(), SUMOVehicle::getID(), MSNet::getInstance(), SUMOVehicle::getLane(), getMaximumBatteryCapacity(), SUMOVehicle::getPositionOnLane(), getPropEnergy(), SUMOVehicle::getSpeed(), increaseChargingStartTime(), increaseVehicleStoppedTimer(), myActChargingStation, myChargingInTransit, myChargingStopped, myConsum, myEnergyCharged, resetChargingStartTime(), resetVehicleStoppedTimer(), setActualBatteryCapacity(), MSChargingStation::setChargingVehicle(), setLastAngle(), SUMO_const_haltingSpeed, and WRITE_WARNING.
virtual void MSMoveReminder::notifyMoveInternal (SUMOVehicle & veh, SUMOReal timeOnLane, SUMOReal speed) inline virtual inherited
Internal notification about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] timeOnLane time the vehicle spent on the lane.
[in] speed Moving speed.
Reimplemented in MSMeanData::MeanDataValueTracker, MSDevice_Tripinfo, MSMeanData_Net::MSLaneMeanDataValues, MSMeanData_Harmonoise::MSLaneMeanDataValues, MSMeanData_Amitran::MSLaneMeanDataValues, and MSMeanData_Emissions::MSLaneMeanDataValues.
Definition at line 201 of file MSMoveReminder.h.
References UNUSED_PARAMETER.
Referenced by MSMeanData::MeanDataValues::notifyMove(), and MSMoveReminder::updateDetector().
MSDevice_Battery& MSDevice_Battery::operator= (const MSDevice_Battery &) private
Invalidated assignment operator.
void MSMoveReminder::removeFromVehicleUpdateValues (SUMOVehicle & veh) protected inherited
Definition at line 94 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues.
Referenced by MSMoveReminder::getDescription(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), and MSMoveReminder::updateDetector().
void MSDevice_Battery::resetChargingStartTime ()
Reset charging start time.
Definition at line 488 of file MSDevice_Battery.cpp.
References myChargingStartTime.
Referenced by notifyMove().
void MSDevice_Battery::resetVehicleStoppedTimer ()
Reset myVehicleStopped.
Definition at line 500 of file MSDevice_Battery.cpp.
References myVehicleStopped.
Referenced by notifyMove().
void MSDevice_Battery::setActualBatteryCapacity (const SUMOReal actualBatteryCapacity)
Set actual vehicle's Battery Capacity in kWh.
Definition at line 354 of file MSDevice_Battery.cpp.
References myActualBatteryCapacity, and myMaximumBatteryCapacity.
Referenced by notifyMove().
void MSDevice_Battery::setAirDragCoefficient (const SUMOReal new_C_Veh)
Set vehicle's drag coefficient.
Definition at line 406 of file MSDevice_Battery.cpp.
References TplConvert::_2str(), Named::getID(), myAirDragCoefficient, and WRITE_WARNING.
void MSDevice_Battery::setConstantPowerIntake (const SUMOReal constantPowerIntake)
Set vehicle's constant power intake.
Definition at line 446 of file MSDevice_Battery.cpp.
References TplConvert::_2str(), Named::getID(), myConstantPowerIntake, and WRITE_WARNING.
void MSMoveReminder::setDescription (const std::string & description) inline inherited
Definition at line 209 of file MSMoveReminder.h.
References MSMoveReminder::myDescription.
Referenced by MSMeanData::init(), MEInductLoop::MEInductLoop(), METriggeredCalibrator::METriggeredCalibrator(), and MSCalibrator::MSCalibrator().
void MSDevice_Battery::setFrontSurfaceArea (const SUMOReal frontSurfaceArea)
Set vehicle's front surface Area.
Definition at line 396 of file MSDevice_Battery.cpp.
References TplConvert::_2str(), Named::getID(), myFrontSurfaceArea, and WRITE_WARNING.
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
void MSDevice_Battery::setInternalMomentOfInertia (const SUMOReal internalMomentOfInertia)
Set vehicle's internal moment of inertia.
Definition at line 416 of file MSDevice_Battery.cpp.
References TplConvert::_2str(), Named::getID(), myInternalMomentOfInertia, and WRITE_WARNING.
void MSDevice_Battery::setLastAngle (const SUMOReal lastAngle)
Set vehicle's last Angle.
Definition at line 476 of file MSDevice_Battery.cpp.
References myLastAngle.
Referenced by notifyEnter(), and notifyMove().
void MSDevice_Battery::setLastEnergy (const SUMOReal lastEnergy)
Set vehicle's last Energy.
Definition at line 482 of file MSDevice_Battery.cpp.
References myLastEnergy.
Referenced by getPropEnergy(), and notifyEnter().
void MSDevice_Battery::setMass (const SUMOReal mass)
Set vehicle's myMass.
Definition at line 376 of file MSDevice_Battery.cpp.
References TplConvert::_2str(), Named::getID(), myMass, and WRITE_WARNING.
void MSDevice_Battery::setMaximumBatteryCapacity (const SUMOReal maximumBatteryCapacity)
Set total vehicle's Battery Capacity in kWh.
Definition at line 366 of file MSDevice_Battery.cpp.
References TplConvert::_2str(), Named::getID(), myMaximumBatteryCapacity, and WRITE_WARNING.
void MSDevice_Battery::setPowerMax (const SUMOReal new_Pmax)
Set maximum power when accelerating.
Definition at line 386 of file MSDevice_Battery.cpp.
References TplConvert::_2str(), Named::getID(), myPowerMax, and WRITE_WARNING.
void MSDevice_Battery::setPropulsionEfficiency (const SUMOReal propulsionEfficiency)
Set vehicle's Propulsion efficiency.
Definition at line 456 of file MSDevice_Battery.cpp.
References TplConvert::_2str(), Named::getID(), myPropulsionEfficiency, and WRITE_WARNING.
void MSDevice_Battery::setRadialDragCoefficient (const SUMOReal radialDragCoefficient)
Set vehicle's radial friction coefficient.
Definition at line 426 of file MSDevice_Battery.cpp.
References TplConvert::_2str(), Named::getID(), myRadialDragCoefficient, and WRITE_WARNING.
void MSDevice_Battery::setRecuperationEfficiency (const SUMOReal recuperationEfficiency)
Set vehicle's Recuparation efficiency.
Definition at line 466 of file MSDevice_Battery.cpp.
References TplConvert::_2str(), Named::getID(), myRecuperationEfficiency, and WRITE_WARNING.
void MSDevice_Battery::setRollDragCoefficient (const SUMOReal rollDragCoefficient)
Set vehicle's roll friction coefficient.
Definition at line 436 of file MSDevice_Battery.cpp.
References TplConvert::_2str(), Named::getID(), myRollDragCoefficient, and WRITE_WARNING.
void MSMoveReminder::updateDetector (SUMOVehicle & veh, SUMOReal entryPos, SUMOReal leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp) inherited
Definition at line 51 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues, MSMoveReminder::notifyMoveInternal(), MSMoveReminder::removeFromVehicleUpdateValues(), STEPS2TIME, and SUMOReal.
Referenced by MSMoveReminder::notifyLeave(), and MEVehicle::updateDetectorForWriting().
Field Documentation
MSChargingStation* MSDevice_Battery::myActChargingStation protected
Parameter, Pointer to current charging station in which vehicle is placed by default is NULL.
Definition at line 315 of file MSDevice_Battery.h.
Referenced by getChargingStationID(), and notifyMove().
SUMOReal MSDevice_Battery::myActualBatteryCapacity protected
Parameter, The actual vehicles's Battery Capacity in kWh [myActualBatteryCapacity <= myMaximumBatteryCapacity].
Definition at line 243 of file MSDevice_Battery.h.
Referenced by getActualBatteryCapacity(), MSDevice_Battery(), and setActualBatteryCapacity().
SUMOReal MSDevice_Battery::myAirDragCoefficient protected
Parameter, Vehicle's drag coefficient [myAirDragCoefficient >=0].
Definition at line 263 of file MSDevice_Battery.h.
Referenced by getAirDragCoefficient(), MSDevice_Battery(), and setAirDragCoefficient().
bool MSDevice_Battery::myChargingInTransit protected
Parameter, Flag: Vehicles it's charging in transit by default is false.
Definition at line 303 of file MSDevice_Battery.h.
Referenced by isChargingInTransit(), and notifyMove().
SUMOReal MSDevice_Battery::myChargingStartTime protected
Parameter, Moment, wich the vehicle has beging to charging none.
Definition at line 307 of file MSDevice_Battery.h.
Referenced by getChargingStartTime(), increaseChargingStartTime(), and resetChargingStartTime().
bool MSDevice_Battery::myChargingStopped protected
Parameter, Flag: Vehicles it's charging stopped by default is false.
Definition at line 299 of file MSDevice_Battery.h.
Referenced by isChargingStopped(), and notifyMove().
SUMOReal MSDevice_Battery::myConstantPowerIntake protected
Parameter, Vehicle's constant power intake [myConstantPowerIntake >= 0].
Definition at line 279 of file MSDevice_Battery.h.
Referenced by getConstantPowerIntake(), MSDevice_Battery(), and setConstantPowerIntake().
SUMOReal MSDevice_Battery::myConsum protected
Parameter, Vehicle consum during a time step by default is 0.
Definition at line 311 of file MSDevice_Battery.h.
Referenced by getConsum(), and notifyMove().
std::string MSMoveReminder::myDescription protected inherited
a description of this moveReminder
Definition at line 225 of file MSMoveReminder.h.
Referenced by MSMoveReminder::getDescription(), and MSMoveReminder::setDescription().
SUMOReal MSDevice_Battery::myEnergyCharged protected
Parameter, Energy charged in each timestep.
Definition at line 318 of file MSDevice_Battery.h.
Referenced by getEnergyCharged(), and notifyMove().
SUMOReal MSDevice_Battery::myFrontSurfaceArea protected
Parameter, Vehicle's front surface Area [myFrontSurfaceArea >= 0].
Definition at line 259 of file MSDevice_Battery.h.
Referenced by getFrontSurfaceArea(), MSDevice_Battery(), and setFrontSurfaceArea().
SUMOVehicle& MSDevice::myHolder protected inherited
The vehicle that stores the device.
Definition at line 158 of file MSDevice.h.
Referenced by MSDevice_Vehroutes::addRoute(), MSDevice_Tripinfo::computeLengthAndDuration(), MSDevice_Vehroutes::generateOutput(), MSDevice_Tripinfo::generateOutput(), MSDevice_Tripinfo::generateOutputForUnfinished(), MSDevice::getHolder(), MSDevice_Vehroutes::notifyEnter(), MSDevice_Tripinfo::notifyLeave(), MSDevice_Routing::preInsertionReroute(), MSDevice_Routing::reroute(), MSDevice_Tripinfo::updateStatistics(), MSDevice_Vehroutes::writeXMLRoute(), and MSDevice_Vehroutes::~MSDevice_Vehroutes().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
SUMOReal MSDevice_Battery::myInternalMomentOfInertia protected
Parameter, Vehicle's internal moment of inertia [myInternalMomentOfInertia >= 0].
Definition at line 267 of file MSDevice_Battery.h.
Referenced by getInternalMomentOfInertia(), MSDevice_Battery(), and setInternalMomentOfInertia().
MSLane* const MSMoveReminder::myLane protected inherited
Lane on which the reminder works.
Definition at line 223 of file MSMoveReminder.h.
Referenced by MSE2Collector::detectorUpdate(), MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSMoveReminder::getLane(), MSE2Collector::MSE2Collector(), MSMoveReminder::MSMoveReminder(), MSE2Collector::notifyEnter(), MSE2Collector::notifyMove(), MSE2Collector::by_vehicle_position_sorter::operator()(), and MSMeanData::MeanDataValueTracker::reset().
SUMOReal MSDevice_Battery::myLastAngle protected
Parameter, Vehicle's last angle none.
Definition at line 291 of file MSDevice_Battery.h.
Referenced by getLastAngle(), and setLastAngle().
SUMOReal MSDevice_Battery::myLastEnergy protected
Parameter, Vehicle's last energy none.
Definition at line 295 of file MSDevice_Battery.h.
Referenced by getLastEnergy(), and setLastEnergy().
SUMOReal MSDevice_Battery::myMass protected
Parameter, Vehicle's myMass [myMass >= 0].
Definition at line 255 of file MSDevice_Battery.h.
Referenced by getMass(), MSDevice_Battery(), and setMass().
SUMOReal MSDevice_Battery::myMaximumBatteryCapacity protected
Parameter, The total vehicles's Battery Capacity in kWh [myMaximumBatteryCapacity >= 0].
Definition at line 247 of file MSDevice_Battery.h.
Referenced by getMaximumBatteryCapacity(), MSDevice_Battery(), setActualBatteryCapacity(), and setMaximumBatteryCapacity().
SUMOReal MSDevice_Battery::myPowerMax protected
Parameter, The Maximum Power when accelerating [myPowerMax >= 0].
Definition at line 251 of file MSDevice_Battery.h.
Referenced by getMaximumPower(), MSDevice_Battery(), and setPowerMax().
SUMOReal MSDevice_Battery::myPropulsionEfficiency protected
Parameter, Vehicle's propulsion efficiency [1 >= myPropulsionEfficiency >= 0].
Definition at line 283 of file MSDevice_Battery.h.
Referenced by getPropulsionEfficiency(), MSDevice_Battery(), and setPropulsionEfficiency().
SUMOReal MSDevice_Battery::myRadialDragCoefficient protected
Parameter, Vehicle's radial friction coefficient [myRadialDragCoefficient >=0].
Definition at line 271 of file MSDevice_Battery.h.
Referenced by getRadialDragCoefficient(), MSDevice_Battery(), and setRadialDragCoefficient().
SUMOReal MSDevice_Battery::myRecuperationEfficiency protected
Parameter, Vehicle's recuparation efficiency [1 >= myRecuperationEfficiency >= 0].
Definition at line 287 of file MSDevice_Battery.h.
Referenced by getRecuperationEfficiency(), MSDevice_Battery(), and setRecuperationEfficiency().
SUMOReal MSDevice_Battery::myRollDragCoefficient protected
Parameter, Vehicle's roll friction coefficient [myRollDragCoefficient >= 0].
Definition at line 275 of file MSDevice_Battery.h.
Referenced by getRollDragCoefficient(), MSDevice_Battery(), and setRollDragCoefficient().
int MSDevice_Battery::myVehicleStopped protected
Parameter, How many timestep the vehicle is stopped.
Definition at line 321 of file MSDevice_Battery.h.
Referenced by getVehicleStopped(), increaseVehicleStoppedTimer(), and resetVehicleStoppedTimer().
The documentation for this class was generated from the following files:
MSDevice_Battery.h
MSDevice_Battery.cpp