SUMO - Simulation of Urban MObility: GNEViewNet Class Reference
GNEViewNet Class Reference
#include <GNEViewNet.h>
Public Member Functions
void abortOperation (bool clearSelection=true)
abort current edition operation
void addDecals (const std::vector< Decal > &decals)
add decals
bool autoSelectNodes ()
whether to autoselect nodes or to lanes
virtual void buildViewToolBars (GUIGlChildWindow &)
builds the view toolbars
virtual void centerTo (GUIGlID id, bool applyZoom, SUMOReal zoomDist=20)
centers to the chosen artifact
void centerTo (const Boundary &bound)
centers to the chosen artifact
bool changeAllPhases () const
change all phases
virtual void copyViewportTo (GUISUMOAbstractView *view)
copy the viewport to the given view
void destroyPopup ()
destoys the popup
GUIPerspectiveChanger & getChanger () const
get changer
FXComboBox & getColoringSchemesCombo ()
get coloring schemes combo
EditMode getCurrentEditMode () const
get the current edit mode
SUMOReal getDelay () const
Returns the delay of the parent application.
SUMOReal getGridHeight () const
get grid Height
SUMOReal getGridWidth () const
get grid width
GNENet * getNet () const
get the net object
Position getPositionInformation () const
Returns the cursor's x/y position within the network.
virtual GUIGlID getTrackedID () const
get tracked id
GNEUndoList * getUndoList () const
get the undoList object
GNEViewParent * getViewParent () const
get the net object
GUIDialog_EditViewport * getViewportEditor ()
get the viewport and create it on first access
Boundary getVisibleBoundary () const
get visible boundary
GUIVisualizationSettings * getVisualisationSettings () const
get visualitation settings
GUIVisualizationSettings * getVisualisationSettings ()
get visualisation settings
GNEViewNet (FXComposite *tmpParent, FXComposite *actualParent, GUIMainWindow &app, GNEViewParent *viewParent, GNENet *net, GNEUndoList *undoList, FXGLVisual *glVis, FXGLCanvas *share, FXToolBar *toolBar)
FOX-declaration.
void hotkeyDel ()
handle del keypress
void hotkeyEnter ()
handle enter keypress
bool isInEditMode ()
returns true, if the edit button was pressed
SUMOReal m2p (SUMOReal meter) const
meter-to-pixels conversion method
FXbool makeCurrent ()
A reimplementation due to some internal reasons.
void markPopupPosition ()
store the position where a popup-menu was requested
long onCmdAddReversedEdge (FXObject *, FXSelector, void *)
add reversed edge
long onCmdChangeMode (FXObject *, FXSelector, void *)
sets edit mode via combo box
long onCmdDeleteGeometry (FXObject *, FXSelector, void *)
delete the closes geometry point
long onCmdDuplicateLane (FXObject *, FXSelector, void *)
duplicate selected lane
long onCmdNodeReplace (FXObject *, FXSelector, void *)
replace node by geometry
long onCmdNodeShape (FXObject *, FXSelector, void *)
input custom node shape
long onCmdResetEdgeEndpoint (FXObject *, FXSelector, void *)
restore geometry endpoint to node position
long onCmdReverseEdge (FXObject *, FXSelector, void *)
reverse edge
long onCmdSetEdgeEndpoint (FXObject *, FXSelector, void *)
set non-default geometry endpoint
long onCmdSimplifyShape (FXObject *, FXSelector, void *)
simply shape of current polygon
long onCmdSplitEdge (FXObject *, FXSelector, void *)
split edge at cursor position
long onCmdSplitEdgeBidi (FXObject *, FXSelector, void *)
split edge at cursor position
long onCmdStraightenEdges (FXObject *, FXSelector, void *)
makes selected edges straight
virtual void onGamingClick (Position)
on gaming click
virtual void openObjectDialog ()
SUMOReal p2m (SUMOReal pixel) const
pixels-to-meters conversion method
virtual void recenterView ()
recenters the view
void remove (GUIDialog_EditViewport *)
remove viewport
void remove (GUIDialog_ViewSettings *)
remove view settings
bool selectEdges ()
whether inspection, selection and inversion should apply to edges or to lanes
bool setColorScheme (const std::string &name)
set color schieme
void setDelay (SUMOReal delay)
Sets the delay of the parent application.
void setEditModeFromHotkey (FXushort selid)
sets edit mode (from hotkey)
void setSelectionScaling (SUMOReal selectionScale)
set selection scaling
void setStatusBarText (const std::string &text)
set staturBar text
virtual void setViewportFromTo (const Position &lookFrom, const Position &lookAt)
applies the given viewport settings
void setWindowCursorPosition (FXint x, FXint y)
Returns the information whether rotation is allowd.
bool showLockIcon () const
check if lock icon should be visible
void showToolTips (bool val)
show tool tips
virtual void showViewportEditor ()
show viewport editor
void showViewschemeEditor ()
show viewsscheme editor
virtual void startTrack (int)
star track
virtual void stopTrack ()
stop track
void updateControls ()
update control contents after undo/redo or recompute
void updateToolTip ()
A method that updates the tooltip.
virtual ~GNEViewNet ()
destructor
long onLeftBtnPress (FXObject *, FXSelector, void *)
overloaded handlers
long onLeftBtnRelease (FXObject *, FXSelector, void *)
called when user releases mouse's left button
long onDoubleClicked (FXObject *, FXSelector, void *)
called when user press mouse's left button two times
long onMouseMove (FXObject *, FXSelector, void *)
called when user moves mouse
virtual long onConfigure (FXObject *, FXSelector, void *)
mouse functions
virtual long onPaint (FXObject *, FXSelector, void *)
virtual long onMiddleBtnPress (FXObject *, FXSelector, void *)
virtual long onMiddleBtnRelease (FXObject *, FXSelector, void *)
virtual long onRightBtnPress (FXObject *, FXSelector, void *)
virtual long onRightBtnRelease (FXObject *, FXSelector, void *)
virtual long onMouseWheel (FXObject *, FXSelector, void *)
virtual long onMouseLeft (FXObject *, FXSelector, void *)
virtual long onKeyPress (FXObject *o, FXSelector sel, void *data)
keyboard functions
virtual long onKeyRelease (FXObject *o, FXSelector sel, void *data)
Dealing with snapshots
void setSnapshots (std::map< SUMOTime, std::string > snaps)
Sets the snapshot time to file map.
std::string makeSnapshot (const std::string &destFile)
Takes a snapshots and writes it into the given file.
virtual void saveFrame (const std::string &destFile, FXColor *buf)
Adds a frame to a video snapshot which will be initialized if neccessary.
virtual void endSnapshot ()
Ends a video snapshot.
virtual void checkSnapshots ()
Checks whether it is time for a snapshot.
virtual SUMOTime getCurrentTimeStep () const
get the current simulation time
Additional visualisations
bool addAdditionalGLVisualisation (const GUIGlObject *const which)
Adds an object to call its additional visualisation method.
bool removeAdditionalGLVisualisation (const GUIGlObject *const which)
Removes an object from the list of objects that show additional things.
bool isAdditionalGLVisualisationEnabled (GUIGlObject *const which) const
Check if an object is added in the additional GL visualitation.
Protected Member Functions
void applyGLTransform (bool fixRatio=true)
applies gl-transformations to fit the Boundary given by myChanger onto the canvas. If fixRatio is true, this boundary will be enlarged to prevent anisotropic stretching. (this should be set to false when doing selections)
FXImage * checkGDALImage (Decal &d)
check whether we can read image data or position with gdal
void displayLegend ()
a line with ticks, and the length information.
void doInit ()
called after some features are already initialized
int doPaintGL (int mode, const Boundary &bound)
do paintGL
void drawDecals ()
Draws the stored decals.
GUIGlID getObjectAtPosition (Position pos)
returns the id of the object at position using GL_SELECT
std::vector< GUIGlID > getObjectsAtPosition (Position pos, SUMOReal radius)
returns the ids of the object at position within the given (rectangular) radius using GL_SELECT
std::vector< GUIGlID > getObjectsInBoundary (const Boundary &bound)
returns the ids of all objects in the given boundary
GUIGlID getObjectUnderCursor ()
returns the id of the object under the cursor using GL_SELECT
GNEViewNet ()
FOX needs this.
void paintGL ()
performs the painting of the simulation
void paintGLGrid ()
paints a grid
void showToolTipFor (const GUIGlID id)
invokes the tooltip for the given object
void updatePositionInformation () const
update position information
Protected Attributes
std::map< const GUIGlObject *, int > myAdditionallyDrawn
List of objects for which GUIGlObject::drawGLAdditional is called.
bool myAmInitialised
Internal information whether doInit() was called.
GUIMainWindow * myApp
The application.
GUIPerspectiveChanger * myChanger
The perspective changer.
SUMORTree * myGrid
The visualization speed-up.
bool myInEditMode
Information whether too-tip informations shall be generated.
int myMouseHotspotX
Offset to the mouse-hotspot from the mouse position.
int myMouseHotspotY
GUIGlChildWindow * myParent
The parent window.
MFXMutex myPolyDrawLock
poly draw lock
GUIGLObjectPopupMenu * myPopup
The current popup-menu.
std::map< SUMOTime, std::string > mySnapshots
Snapshots.
bool myUseToolTips
use tool tips
GUIDialog_EditViewport * myViewportChooser
viewport chooser
GUIDialog_ViewSettings * myVisualizationChanger
Visualization changer.
GUIVisualizationSettings * myVisualizationSettings
visualization settings
FXint myWindowCursorPositionX
Position of the cursor relative to the window.
FXint myWindowCursorPositionY
Optionally shown decals
The list of decals to show
std::vector< Decal > myDecals
MFXMutex myDecalsLock
The mutex to use before accessing the decals list in order to avoid thread conficts.
Private Member Functions
void buildEditModeControls ()
adds controls for setting the edit mode
void deleteSelectedEdges ()
delete all currently selected edges
void deleteSelectedJunctions ()
delete all currently selected junctions
GNEEdge * getEdgeAtCursorPosition (Position &pos)
try to retrieve an edge at the given position
std::set< GNEEdge * > getEdgesAtCursorPosition (Position &pos)
try to retrieve multiple edges at the given position
GNEJunction * getJunctionAtCursorPosition (Position &pos)
try to retrieve a junction at the given position
GNELane * getLaneAtCurserPosition (Position &pos)
try to retrieve a lane at the given position
GNEViewNet (const GNEViewNet &)
Invalidated copy constructor.
bool mergeJunctions (GNEJunction *moved)
try to merge moved junction with another junction in that spot return true if merging did take place
GNEViewNet & operator= (const GNEViewNet &)
Invalidated assignment operator.
void removeCurrentPoly ()
remove the currently edited polygon
void setEditMode (EditMode mode)
set edit mode
void updateModeSpecificControls ()
updates mode specific controls
Private Attributes
FXMenuCheck * myChangeAllPhases
menu check to set change all phases
GNEPoly * myCurrentPoly
current polygon
EditMode myEditMode
the current edit mode
FXMenuCheck * myExtendToEdgeNodes
menu check to extend to edge nodes
GNENet * myNet
we are not responsible for deletion
Position myPopupSpot
Poput spot.
EditMode myPreviousEditMode
the previous edit mode used for toggling
FXMenuCheck * mySelectEdges
menu check to select only edges
GNEUndoList * myUndoList
a reference to the undolist maintained in the application
GNEViewParent * myViewParent
view parent
the state-variables of the create-edge state-machine
GNEJunction * myCreateEdgeSource
source junction for new edge 0 if no edge source is selected an existing (or newly created) junction otherwise
FXMenuCheck * myChainCreateEdge
whether the endpoint for a created edge should be set as the new source
FXMenuCheck * myAutoCreateOppositeEdge
the state-variables of the move state-machine
GNEJunction * myJunctionToMove
the Junction to be moved.
GNEEdge * myEdgeToMove
the edge of which geometry is being moved
GNEPoly * myPolyToMove
the poly of which geometry is being moved
GNEAdditional * myAdditionalToMove
the stoppingPlace element which shape is being moved
Position myAdditionalFirstPosition
variable to save the firstposition of the additional before move
Position myMoveSrc
position from which to move edge geometry
bool myMoveSelection
whether a selection is being moved
FXMenuCheck * myWarnAboutMerge
whether we should warn about merging junctions
state-variables of inspect-mode and select-mode
bool myAmInRectSelect
whether we have started rectangle-selection
Position mySelCorner1
firstcorner of the rectangle-selection
Position mySelCorner2
second corner of the rectangle-selection
toolbar related stuff
a reference to the toolbar in myParent
FXToolBar * myToolbar
FXComboBox * myEditModesCombo
combo box for selecting the edit mode
StringBijection< EditMode > myEditModeNames
since we cannot switch on strings we map the mode names to an enum
StringBijection< EditMode > myEditAdditionalModeNames
Detailed Description
Microsocopic view at the simulation
Definition at line 86 of file GNEViewNet.h.
Constructor & Destructor Documentation
GNEViewNet::GNEViewNet (FXComposite * tmpParent, FXComposite * actualParent, GUIMainWindow & app, GNEViewParent * viewParent, GNENet * net, GNEUndoList * undoList, FXGLVisual * glVis, FXGLCanvas * share, FXToolBar * toolBar)
FOX-declaration.
Definition at line 106 of file GNEViewNet.cpp.
References GUIPropertyScheme< T >::addColor(), GUIPropertySchemeStorage< T >::addScheme(), RGBColor::BLACK, RGBColor::BLUE, RGBColor::CYAN, RGBColor::GREEN, RGBColor::GREY, RGBColor::MAGENTA, RGBColor::ORANGE, RGBColor::RED, GUIPropertyScheme< T >::setAllowsNegativeValues(), SUMOReal, SVC_BICYCLE, SVC_BUS, SVC_DELIVERY, SVC_MOPED, SVC_NON_ROAD, SVC_PASSENGER, SVC_PEDESTRIAN, SVC_SHIP, SVC_TAXI, SVCAll, and RGBColor::YELLOW.
GNEViewNet::~GNEViewNet () virtual
destructor
Definition at line 243 of file GNEViewNet.cpp.
GNEViewNet::GNEViewNet () inline protected
FOX needs this.
Definition at line 220 of file GNEViewNet.h.
References doInit(), and doPaintGL().
GNEViewNet::GNEViewNet (const GNEViewNet &) private
Invalidated copy constructor.
Member Function Documentation
void GNEViewNet::abortOperation (bool clearSelection = true)
abort current edition operation
Definition at line 740 of file GNEViewNet.cpp.
References GUISelectedStorage::clear(), GNEViewParent::getConnectorFrame(), GNEViewParent::getTLSEditorFrame(), GNE_MODE_CONNECT, GNE_MODE_MOVE, GNE_MODE_SELECT, GNE_MODE_TLS, gSelected, myAmInRectSelect, myCreateEdgeSource, myEditMode, myUndoList, myViewParent, GNEConnectorFrame::onCmdCancel(), GNETLSEditorFrame::onCmdCancel(), GNEUndoList::p_abort(), removeCurrentPoly(), and GNEJunction::unMarkAsCreateEdgeSource().
Referenced by GNEApplicationWindow::onCmdAbort(), and setEditMode().
bool GUISUMOAbstractView::addAdditionalGLVisualisation (const GUIGlObject *const which) inherited
Adds an object to call its additional visualisation method.
Parameters
[in] which The object to add
Returns
Always true
See also
GUIGlObject::drawGLAdditional
Definition at line 1198 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myAdditionallyDrawn.
Referenced by GUIBaseVehicle::addActiveAddVisualisation(), GUIPerson::addActiveAddVisualisation(), GUIVehicle::drawOutsideNetwork(), and GUISUMOAbstractView::endSnapshot().
void GUISUMOAbstractView::addDecals (const std::vector< Decal > & decals) inherited
add decals
Definition at line 185 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myDecals.
Referenced by GNEApplicationWindow::handleEvent_NetworkLoaded(), and GUIApplicationWindow::handleEvent_SimulationLoaded().
void GUISUMOAbstractView::applyGLTransform (bool fixRatio = true) protected inherited
applies gl-transformations to fit the Boundary given by myChanger onto the canvas. If fixRatio is true, this boundary will be enlarged to prevent anisotropic stretching. (this should be set to false when doing selections)
Definition at line 1239 of file GUISUMOAbstractView.cpp.
References Boundary::getHeight(), GUIPerspectiveChanger::getViewport(), Boundary::getWidth(), GLO_MAX, GUISUMOAbstractView::myChanger, SUMOReal, Boundary::xmin(), and Boundary::ymin().
Referenced by GUISUMOAbstractView::getObjectsInBoundary(), GUISUMOAbstractView::makeSnapshot(), and GUISUMOAbstractView::paintGL().
bool GNEViewNet::autoSelectNodes ()
whether to autoselect nodes or to lanes
Definition at line 313 of file GNEViewNet.cpp.
References myExtendToEdgeNodes.
Referenced by GNESelectorFrame::handleIDs().
void GNEViewNet::buildEditModeControls () private
adds controls for setting the edit mode
Definition at line 1161 of file GNEViewNet.cpp.
References StringBijection< T >::getStrings(), GNE_MODE_ADDITIONAL, GNE_MODE_CONNECT, GNE_MODE_CREATE_EDGE, GNE_MODE_DELETE, GNE_MODE_INSPECT, GNE_MODE_MOVE, GNE_MODE_SELECT, GNE_MODE_TLS, StringBijection< T >::insert(), MID_GNE_MODE_CHANGE, myAutoCreateOppositeEdge, myChainCreateEdge, myChangeAllPhases, myEditModeNames, myEditModesCombo, myExtendToEdgeNodes, mySelectEdges, myToolbar, myWarnAboutMerge, and StringBijection< T >::size().
void GNEViewNet::buildViewToolBars (GUIGlChildWindow & cw) virtual
builds the view toolbars
Reimplemented from GUISUMOAbstractView.
Definition at line 251 of file GNEViewNet.cpp.
References GUIIconSubSys::getIcon(), GUIGlChildWindow::getLocatorPopup(), ICON_LOCATEEDGE, ICON_LOCATEJUNCTION, ICON_LOCATETLS, MID_LOCATEEDGE, MID_LOCATEJUNCTION, and MID_LOCATETLS.
Referenced by GNEViewParent::GNEViewParent().
void GUISUMOAbstractView::centerTo (GUIGlID id, bool applyZoom, SUMOReal zoomDist = 20) virtual inherited
centers to the chosen artifact
Parameters
[in] id The id of the artifact to center to
[in] applyZoom Whether to zoom in
[in] zoomDist The distance in m to use for the zoom, values < 0 means: use the centeringBoundary
Note
caller is responsible for calling update
Definition at line 533 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::centerTo(), Boundary::getCenter(), GUIGlObject::getCenteringBoundary(), GUIGlObjectStorage::getObjectBlocking(), GUIGlObjectStorage::gIDStorage, GUISUMOAbstractView::myChanger, GUIPerspectiveChanger::setViewport(), GUIGlObjectStorage::unblockObject(), and GUISUMOAbstractView::updatePositionInformation().
Referenced by GUISUMOAbstractView::buildViewToolBars(), GNECalibrator::GNECalibrator(), GNERouteProbe::GNERouteProbe(), GNEVaporizer::GNEVaporizer(), GUIGLObjectPopupMenu::onCmdCenter(), GUISUMOAbstractView::paintGL(), TraCIServerAPI_GUI::processSet(), and GUIGlChildWindow::setView().
void GUISUMOAbstractView::centerTo (const Boundary & bound) inherited
centers to the chosen artifact
Definition at line 550 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myChanger, and GUIPerspectiveChanger::setViewport().
bool GNEViewNet::changeAllPhases () const
change all phases
Definition at line 325 of file GNEViewNet.cpp.
References myChangeAllPhases.
Referenced by GNETLSEditorFrame::handleChange().
FXImage * GUISUMOAbstractView::checkGDALImage (Decal & d) protected inherited
check whether we can read image data or position with gdal
Definition at line 1080 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::Decal::centerX, GUISUMOAbstractView::Decal::centerY, GUISUMOAbstractView::Decal::filename, GUISUMOAbstractView::getGridHeight(), GUISUMOAbstractView::getGridWidth(), GeoConvHelper::getProcessing(), GUISUMOAbstractView::Decal::height, GUISUMOAbstractView::Decal::width, WRITE_MESSAGE, WRITE_WARNING, Position::x(), GeoConvHelper::x2cartesian(), and Position::y().
Referenced by GUISUMOAbstractView::drawDecals().
void GUISUMOAbstractView::checkSnapshots () virtual inherited
Checks whether it is time for a snapshot.
Reimplemented in GUIViewTraffic.
Definition at line 942 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::getCurrentTimeStep(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::mySnapshots, and WRITE_WARNING.
Referenced by GUIViewTraffic::checkSnapshots(), GUISUMOAbstractView::endSnapshot(), GUISUMOAbstractView::onConfigure(), and GUISUMOViewParent::onSimStep().
void GUISUMOAbstractView::copyViewportTo (GUISUMOAbstractView * view) virtual inherited
copy the viewport to the given view
Definition at line 1003 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::getXPos(), GUIPerspectiveChanger::getYPos(), GUIPerspectiveChanger::getZPos(), GUISUMOAbstractView::myChanger, and GUISUMOAbstractView::setViewportFromTo().
Referenced by GUISUMOAbstractView::buildViewToolBars(), and GUIApplicationWindow::openNewView().
void GNEViewNet::deleteSelectedEdges () private
delete all currently selected edges
Definition at line 1293 of file GNEViewNet.cpp.
References GNENet::deleteEdge(), GNENet::deleteLane(), myNet, mySelectEdges, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::retrieveEdges(), and GNENet::retrieveLanes().
Referenced by hotkeyDel().
void GNEViewNet::deleteSelectedJunctions () private
delete all currently selected junctions
Definition at line 1282 of file GNEViewNet.cpp.
References GNENet::deleteJunction(), myNet, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), and GNENet::retrieveJunctions().
Referenced by hotkeyDel().
void GUISUMOAbstractView::destroyPopup () inherited
destoys the popup
Definition at line 609 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myPopup.
Referenced by GUISUMOAbstractView::endSnapshot(), GNEInternalLane::onDefault(), GUISUMOAbstractView::onLeftBtnPress(), GUISUMOAbstractView::onLeftBtnRelease(), GUISUMOAbstractView::onRightBtnPress(), and GUISUMOAbstractView::onRightBtnRelease().
void GUISUMOAbstractView::displayLegend () protected inherited
a line with ticks, and the length information.
Definition at line 446 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::m2p(), pfDrawString(), pfSetPosition(), pfSetScaleXY(), SUMOReal, and text().
Referenced by GUISUMOAbstractView::makeSnapshot(), and GUISUMOAbstractView::paintGL().
void GNEViewNet::doInit () protected virtual
called after some features are already initialized
Reimplemented from GUISUMOAbstractView.
Definition at line 247 of file GNEViewNet.cpp.
Referenced by GNEViewNet().
int GNEViewNet::doPaintGL (int mode, const Boundary & bound) protected virtual
do paintGL
Reimplemented from GUISUMOAbstractView.
Definition at line 331 of file GNEViewNet.cpp.
References GUISUMOAbstractView::drawDecals(), GUIVisualizationSettings::editMode, GLO_ADDITIONAL, GLO_MAX, GUISUMOAbstractView::m2p(), GUISUMOAbstractView::myAdditionallyDrawn, myAmInRectSelect, myEditMode, GUISUMOAbstractView::myGrid, mySelCorner1, mySelCorner2, GUISUMOAbstractView::myUseToolTips, GUISUMOAbstractView::myVisualizationSettings, GUISUMOAbstractView::paintGLGrid(), GUIVisualizationSettings::scale, SUMORTree::Search(), GNENet::selectionColor, GLHelper::setColor(), GUIVisualizationSettings::showGrid, SUMO_const_laneWidth, SUMOReal, Position::x(), Boundary::xmax(), Boundary::xmin(), Position::y(), Boundary::ymax(), and Boundary::ymin().
Referenced by GNEViewNet().
void GUISUMOAbstractView::drawDecals () protected inherited
Draws the stored decals.
Definition at line 1159 of file GUISUMOAbstractView.cpp.
References GUITexturesHelper::add(), GUISUMOAbstractView::Decal::centerX, GUISUMOAbstractView::Decal::centerY, GUISUMOAbstractView::checkGDALImage(), GUITexturesHelper::drawTexturedBox(), GUISUMOAbstractView::Decal::filename, GUITexturesHelper::getMaxTextureSize(), GUISUMOAbstractView::Decal::glID, GUISUMOAbstractView::Decal::height, GUISUMOAbstractView::Decal::image, GUISUMOAbstractView::Decal::initialised, GUISUMOAbstractView::Decal::layer, MFXImageHelper::loadImage(), MFXMutex::lock(), GUISUMOAbstractView::myDecals, GUISUMOAbstractView::myDecalsLock, GUISUMOAbstractView::Decal::rot, MFXImageHelper::scalePower2(), GUISUMOAbstractView::Decal::skip2D, SUMOReal, MFXMutex::unlock(), GUISUMOAbstractView::Decal::width, and WRITE_ERROR.
Referenced by GUIViewTraffic::doPaintGL(), doPaintGL(), and GUISUMOAbstractView::makeSnapshot().
virtual void GUISUMOAbstractView::endSnapshot () inline virtual inherited
Ends a video snapshot.
Reimplemented in GUIViewTraffic.
Definition at line 187 of file GUISUMOAbstractView.h.
References GUISUMOAbstractView::addAdditionalGLVisualisation(), GUISUMOAbstractView::checkSnapshots(), GUISUMOAbstractView::destroyPopup(), GUISUMOAbstractView::getCurrentTimeStep(), GUISUMOAbstractView::getGridHeight(), GUISUMOAbstractView::getGridWidth(), GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::getViewportEditor(), GUISUMOAbstractView::getVisualisationSettings(), GUISUMOAbstractView::isAdditionalGLVisualisationEnabled(), GUISUMOAbstractView::onGamingClick(), GUISUMOAbstractView::removeAdditionalGLVisualisation(), GUISUMOAbstractView::setColorScheme(), GUISUMOAbstractView::showToolTips(), GUISUMOAbstractView::showViewportEditor(), GUISUMOAbstractView::showViewschemeEditor(), GUISUMOAbstractView::startTrack(), GUISUMOAbstractView::stopTrack(), and SUMOReal.
Referenced by GUISUMOViewParent::onCmdMakeSnapshot().
GUIPerspectiveChanger & GUISUMOAbstractView::getChanger () const inherited
get changer
Definition at line 160 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myChanger.
Referenced by GUISettingsHandler::applyViewport(), GUISUMOAbstractView::buildViewToolBars(), GUIDialog_EditViewport::onCmdChanged(), GUIDialog_EditViewport::onCmdLoad(), GUIApplicationWindow::onCmdNetedit(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_GUI::processSet(), and GUIDialog_EditViewport::setValues().
FXComboBox & GUISUMOAbstractView::getColoringSchemesCombo () inherited
get coloring schemes combo
Definition at line 1074 of file GUISUMOAbstractView.cpp.
References GUIGlChildWindow::getColoringSchemesCombo(), and GUISUMOAbstractView::myParent.
Referenced by GUISettingsHandler::addSettings(), GUIDialog_ViewSettings::onCmdColorChange(), and GUIDialog_ViewSettings::onCmdSaveSetting().
EditMode GNEViewNet::getCurrentEditMode () const
get the current edit mode
Definition at line 857 of file GNEViewNet.cpp.
References myEditMode.
SUMOTime GUISUMOAbstractView::getCurrentTimeStep () const virtual inherited
get the current simulation time
Reimplemented in GUIViewTraffic.
Definition at line 954 of file GUISUMOAbstractView.cpp.
Referenced by GUISUMOAbstractView::checkSnapshots(), and GUISUMOAbstractView::endSnapshot().
SUMOReal GUISUMOAbstractView::getDelay () const inherited
Returns the delay of the parent application.
Definition at line 1257 of file GUISUMOAbstractView.cpp.
References GUIMainWindow::getDelay(), and GUISUMOAbstractView::myApp.
Referenced by GUIDialog_ViewSettings::onCmdExportSetting().
GNEEdge * GNEViewNet::getEdgeAtCursorPosition (Position & pos) private
try to retrieve an edge at the given position
Definition at line 892 of file GNEViewNet.cpp.
References GUISUMOAbstractView::getObjectAtPosition(), GUIGlObjectStorage::getObjectBlocking(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GLO_EDGE, GLO_LANE, GUISUMOAbstractView::makeCurrent(), myPopupSpot, and GUIGlObjectStorage::unblockObject().
Referenced by onCmdAddReversedEdge(), onCmdResetEdgeEndpoint(), onCmdReverseEdge(), onCmdSetEdgeEndpoint(), onCmdSplitEdge(), and onCmdStraightenEdges().
std::set< GNEEdge * > GNEViewNet::getEdgesAtCursorPosition (Position & pos) private
try to retrieve multiple edges at the given position
Definition at line 933 of file GNEViewNet.cpp.
References GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getObjectsAtPosition(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GLO_EDGE, GLO_LANE, GUISUMOAbstractView::makeCurrent(), myPopupSpot, and GUIGlObjectStorage::unblockObject().
Referenced by onCmdSplitEdgeBidi().
SUMOReal GUISUMOAbstractView::getGridHeight () const inherited
get grid Height
Definition at line 1047 of file GUISUMOAbstractView.cpp.
References Boundary::getHeight(), and GUISUMOAbstractView::myGrid.
Referenced by GUISUMOAbstractView::checkGDALImage(), GUISUMOAbstractView::endSnapshot(), and GUIDialog_ViewSettings::onCmdEditTable().
SUMOReal GUISUMOAbstractView::getGridWidth () const inherited
get grid width
Definition at line 1041 of file GUISUMOAbstractView.cpp.
References Boundary::getWidth(), GUISUMOAbstractView::myGrid, and SUMOReal.
Referenced by GUISUMOAbstractView::checkGDALImage(), GUISUMOAbstractView::endSnapshot(), and GUIDialog_ViewSettings::onCmdEditTable().
GNEJunction * GNEViewNet::getJunctionAtCursorPosition (Position & pos) private
try to retrieve a junction at the given position
Definition at line 869 of file GNEViewNet.cpp.
References GUISUMOAbstractView::getObjectAtPosition(), GUIGlObjectStorage::getObjectBlocking(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GLO_JUNCTION, GUISUMOAbstractView::makeCurrent(), myPopupSpot, and GUIGlObjectStorage::unblockObject().
Referenced by onCmdNodeReplace(), and onCmdNodeShape().
GNELane * GNEViewNet::getLaneAtCurserPosition (Position & pos) private
try to retrieve a lane at the given position
Definition at line 916 of file GNEViewNet.cpp.
References GUISUMOAbstractView::getObjectAtPosition(), GUIGlObjectStorage::getObjectBlocking(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GLO_LANE, GUISUMOAbstractView::makeCurrent(), myPopupSpot, and GUIGlObjectStorage::unblockObject().
Referenced by onCmdDuplicateLane().
GNENet * GNEViewNet::getNet () const
get the net object
Definition at line 845 of file GNEViewNet.cpp.
References myNet.
Referenced by GNEAdditionalFrame::addAdditional(), GNEAdditionalHandler::buildAdditional(), GNEAdditionalHandler::buildBusStop(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildChargingStation(), GNEAdditionalHandler::buildContainerStop(), GNEAdditionalHandler::buildDetectorE1(), GNEAdditionalHandler::buildDetectorE2(), GNEAdditionalHandler::buildDetectorE3(), GNEAdditionalHandler::buildDetectorEntry(), GNEAdditionalHandler::buildDetectorExit(), GNEConnectorFrame::buildIinternalLanes(), GNETLSEditorFrame::buildIinternalLanes(), GNEAdditionalHandler::buildRerouter(), GNEAdditionalHandler::buildRouteProbe(), GNEAdditionalHandler::buildVaporizer(), GNEAdditionalHandler::buildVariableSpeedSignal(), GNEAdditionalFrame::generateID(), GNESelectorFrame::getMatches(), GNEDetectorE3::getParentName(), GNEVariableSpeedSignal::getParentName(), GNEAdditional::getParentName(), GNERerouter::getParentName(), GNEAdditional::getPopUpMenu(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEConnectorFrame::initTargets(), GNEDetectorExit::isValid(), GNEDetectorEntry::isValid(), GNEDetectorE1::isValid(), GNEDetectorE2::isValid(), GNEBusStop::isValid(), GNEContainerStop::isValid(), GNEDetectorE3::isValid(), GNEVaporizer::isValid(), GNEVariableSpeedSignal::isValid(), GNERouteProbe::isValid(), GNEChargingStation::isValid(), GNECalibrator::isValid(), GNERerouter::isValid(), GNETLSEditorFrame::onCmdDefSwitch(), GNESelectorFrame::onCmdInvert(), GNEViewParent::onCmdLocate(), GNETLSEditorFrame::onCmdOK(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEAdditionalHandler::parseAndBuildBusStop(), GNEAdditionalHandler::parseAndBuildCalibrator(), GNEAdditionalHandler::parseAndBuildChargingStation(), GNEAdditionalHandler::parseAndBuildContainerStop(), GNEAdditionalHandler::parseAndBuildDetectorE1(), GNEAdditionalHandler::parseAndBuildDetectorE2(), GNEAdditionalHandler::parseAndBuildDetectorEntry(), GNEAdditionalHandler::parseAndBuildDetectorExit(), GNEAdditionalHandler::parseAndBuildRerouter(), GNEAdditionalHandler::parseAndBuildRouteProbe(), GNEAdditionalHandler::parseAndBuildVaporizer(), GNEAdditionalHandler::parseAndBuildVariableSpeedSignal(), GNEAdditionalHandler::parseCalibratorFlow(), GNEAdditionalHandler::parseVariableSpeedSignalStep(), GNEAdditionalFrame::removeAdditional(), GNEAdditional::setAdditionalID(), GNEDetectorExit::setAttribute(), GNEDetectorEntry::setAttribute(), GNEDetectorE1::setAttribute(), GNEBusStop::setAttribute(), GNEContainerStop::setAttribute(), GNEDetectorE2::setAttribute(), GNEVaporizer::setAttribute(), GNEVariableSpeedSignal::setAttribute(), GNERouteProbe::setAttribute(), GNEChargingStation::setAttribute(), GNECalibrator::setAttribute(), GNERerouter::setAttribute(), GNEAdditionalFrame::additionalSet::showList(), GNEAdditionalFrame::edgesSelector::showList(), GNEAdditionalFrame::lanesSelector::showList(), GNEAdditionalFrame::edgesSelector::updateUseSelectedEdges(), and GNEAdditionalFrame::lanesSelector::updateUseSelectedLanes().
GUIGlID GUISUMOAbstractView::getObjectAtPosition (Position pos) protected inherited
returns the id of the object at position using GL_SELECT
Definition at line 288 of file GUISUMOAbstractView.cpp.
References Boundary::add(), GUIGlObject::getGlID(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getObjectsInBoundary(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GLO_LANE, GLO_POI, GLO_POLYGON, Boundary::grow(), max, SUMOReal, GUIGlObjectStorage::unblockObject(), and GUIVisualizationSettings::UseMesoSim.
Referenced by getEdgeAtCursorPosition(), getJunctionAtCursorPosition(), getLaneAtCurserPosition(), and GUISUMOAbstractView::getObjectUnderCursor().
std::vector< GUIGlID > GUISUMOAbstractView::getObjectsAtPosition (Position pos, SUMOReal radius) protected inherited
returns the ids of the object at position within the given (rectangular) radius using GL_SELECT
Definition at line 333 of file GUISUMOAbstractView.cpp.
References Boundary::add(), GUIGlObject::getGlID(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getObjectsInBoundary(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, Boundary::grow(), and GUIGlObjectStorage::unblockObject().
Referenced by getEdgesAtCursorPosition().
std::vector< GUIGlID > GUISUMOAbstractView::getObjectsInBoundary (const Boundary & bound) protected inherited
returns the ids of all objects in the given boundary
Definition at line 361 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::applyGLTransform(), GUISUMOAbstractView::doPaintGL(), GUIVisualizationSettings::drawForSelecting, GUIPerspectiveChanger::getViewport(), GUISUMOAbstractView::myApp, GUISUMOAbstractView::myChanger, GUISUMOAbstractView::myVisualizationSettings, GUIMainWindow::setStatusBarText(), GUIPerspectiveChanger::setViewport(), and toString().
Referenced by GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), mergeJunctions(), and onLeftBtnRelease().
GUIGlID GUISUMOAbstractView::getObjectUnderCursor () protected inherited
returns the id of the object under the cursor using GL_SELECT
Definition at line 282 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::getObjectAtPosition(), and GUISUMOAbstractView::getPositionInformation().
Referenced by GUIViewTraffic::getLaneUnderCursor(), onDoubleClicked(), onLeftBtnPress(), GUISUMOAbstractView::onLeftBtnPress(), GUISUMOAbstractView::openObjectDialog(), and GUISUMOAbstractView::paintGL().
Position GUISUMOAbstractView::getPositionInformation () const inherited
Returns the cursor's x/y position within the network.
Definition at line 175 of file GUISUMOAbstractView.cpp.
References Boundary::getHeight(), GUIPerspectiveChanger::getViewport(), Boundary::getWidth(), GUISUMOAbstractView::myChanger, GUISUMOAbstractView::myWindowCursorPositionX, GUISUMOAbstractView::myWindowCursorPositionY, SUMOReal, Boundary::xmin(), and Boundary::ymin().
Referenced by GNEAdditionalFrame::addAdditional(), GUISUMOAbstractView::getObjectUnderCursor(), GUIEdge::getParameterWindow(), GNELane::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNEAdditional::getPopUpMenu(), GUILane::getPopUpMenu(), markPopupPosition(), GUIDanielPerspectiveChanger::onKeyPress(), onLeftBtnPress(), GUISUMOAbstractView::onLeftBtnRelease(), onMouseMove(), GUIDanielPerspectiveChanger::onMouseWheel(), GUIDanielPerspectiveChanger::onRightBtnPress(), GUISUMOAbstractView::showToolTipFor(), and GUISUMOAbstractView::updatePositionInformation().
GUIGlID GUISUMOAbstractView::getTrackedID () const virtual inherited
get tracked id
Reimplemented in GUIViewTraffic.
Definition at line 1063 of file GUISUMOAbstractView.cpp.
References GUIGlObject::INVALID_ID.
Referenced by GUISUMOAbstractView::endSnapshot(), GUIPerson::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUISUMOAbstractView::paintGL(), and GUISUMOAbstractView::removeAdditionalGLVisualisation().
GNEUndoList * GNEViewNet::getUndoList () const
get the undoList object
Definition at line 851 of file GNEViewNet.cpp.
References myUndoList.
Referenced by GNEAdditionalHandler::buildBusStop(), GNEAdditionalHandler::buildCalibrator(), GNEAdditionalHandler::buildChargingStation(), GNEAdditionalHandler::buildContainerStop(), GNEAdditionalHandler::buildDetectorE1(), GNEAdditionalHandler::buildDetectorE2(), GNEAdditionalHandler::buildDetectorE3(), GNEAdditionalHandler::buildDetectorEntry(), GNEAdditionalHandler::buildDetectorExit(), GNEAdditionalHandler::buildRerouter(), GNEAdditionalHandler::buildRouteProbe(), GNEAdditionalHandler::buildVaporizer(), GNEAdditionalHandler::buildVariableSpeedSignal(), GNETLSEditorFrame::editJunction(), GNESelectorFrame::handleIDs(), GNEConnectorFrame::handleLaneClick(), GNEConnectorFrame::onCmdCancel(), GNETLSEditorFrame::onCmdCancel(), GNESelectorFrame::onCmdClear(), GNEConnectorFrame::onCmdClearSelectedConnections(), GNEInspectorFrame::onCmdCopyTemplate(), GNETLSEditorFrame::onCmdDefCreate(), GNETLSEditorFrame::onCmdDefDelete(), GNEConnectorFrame::onCmdOK(), GNETLSEditorFrame::onCmdOK(), GNEConnectorFrame::onCmdResetSelectedConnections(), GNEInspectorFrame::AttrInput::onCmdSetAttribute(), and GNEAdditionalFrame::removeAdditional().
GNEViewParent * GNEViewNet::getViewParent () const
get the net object
Definition at line 839 of file GNEViewNet.cpp.
References myViewParent.
Referenced by GNEConnectorFrame::hide(), GNETLSEditorFrame::hide(), GNESelectorFrame::hide(), GNEInspectorFrame::hide(), GNEAdditionalFrame::hide(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEConnectorFrame::show(), GNETLSEditorFrame::show(), GNESelectorFrame::show(), GNEInspectorFrame::show(), and GNEAdditionalFrame::show().
GUIDialog_EditViewport * GUISUMOAbstractView::getViewportEditor () inherited
get the viewport and create it on first access
Definition at line 975 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::getXPos(), GUIPerspectiveChanger::getYPos(), GUIPerspectiveChanger::getZoom(), GUISUMOAbstractView::myChanger, GUISUMOAbstractView::myViewportChooser, and GUIDialog_EditViewport::setValues().
Referenced by GUISUMOAbstractView::endSnapshot(), GUIDialog_ViewSettings::onCmdExportSetting(), and GUISUMOAbstractView::showViewportEditor().
Boundary GUISUMOAbstractView::getVisibleBoundary () const inherited
get visible boundary
Definition at line 223 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::getViewport(), and GUISUMOAbstractView::myChanger.
Referenced by GUISUMOAbstractView::buildViewToolBars(), and TraCIServerAPI_GUI::processGet().
GUIVisualizationSettings * GUISUMOAbstractView::getVisualisationSettings () const inherited
get visualitation settings
Definition at line 1023 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myVisualizationSettings.
Referenced by GUISUMOAbstractView::endSnapshot(), GNEJunction::getPopUpMenu(), GNELane::getPopUpMenu(), GUIApplicationWindow::onCmdEditChosen(), and TraCIServerAPI_GUI::processGet().
GUIVisualizationSettings * GUISUMOAbstractView::getVisualisationSettings () inherited
get visualisation settings
Definition at line 191 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myVisualizationSettings.
void GNEViewNet::hotkeyDel ()
handle del keypress
Definition at line 762 of file GNEViewNet.cpp.
References deleteSelectedEdges(), deleteSelectedJunctions(), GNE_MODE_CONNECT, GNE_MODE_TLS, myEditMode, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), and setStatusBarText().
Referenced by GNEApplicationWindow::onCmdDel().
void GNEViewNet::hotkeyEnter ()
handle enter keypress
Definition at line 775 of file GNEViewNet.cpp.
References GNEViewParent::getConnectorFrame(), GNEPoly::getEditedJunction(), SUMO::Polygon::getShape(), GNEViewParent::getTLSEditorFrame(), GNE_MODE_CONNECT, GNE_MODE_MOVE, GNE_MODE_TLS, myCurrentPoly, myEditMode, myUndoList, myViewParent, GNEConnectorFrame::onCmdOK(), GNETLSEditorFrame::onCmdOK(), removeCurrentPoly(), GNEJunction::setAttribute(), SUMO_ATTR_SHAPE, and toString().
Referenced by GNEApplicationWindow::onCmdEnter().
bool GUISUMOAbstractView::isAdditionalGLVisualisationEnabled (GUIGlObject *const which) const inherited
Check if an object is added in the additional GL visualitation.
Parameters
[in] which The object to check
See also
GUIGlObject::drawGLAdditional
Definition at line 1229 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myAdditionallyDrawn.
Referenced by GUISUMOAbstractView::endSnapshot().
bool GUISUMOAbstractView::isInEditMode () inherited
returns true, if the edit button was pressed
Definition at line 154 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myInEditMode.
Referenced by GUISUMOAbstractView::buildViewToolBars().
SUMOReal GUISUMOAbstractView::m2p (SUMOReal meter) const inherited
meter-to-pixels conversion method
Definition at line 515 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::getViewport(), Boundary::getWidth(), GUISUMOAbstractView::myChanger, and SUMOReal.
Referenced by GUISUMOAbstractView::buildViewToolBars(), GUISUMOAbstractView::displayLegend(), GUIViewTraffic::doPaintGL(), doPaintGL(), and GUISUMOAbstractView::makeSnapshot().
FXbool GUISUMOAbstractView::makeCurrent () inherited
A reimplementation due to some internal reasons.
Definition at line 571 of file GUISUMOAbstractView.cpp.
Referenced by GUISUMOAbstractView::buildViewToolBars(), getEdgeAtCursorPosition(), getEdgesAtCursorPosition(), getJunctionAtCursorPosition(), getLaneAtCurserPosition(), GUIViewTraffic::getLaneUnderCursor(), GUISUMOAbstractView::makeSnapshot(), mergeJunctions(), GUISUMOAbstractView::onConfigure(), onDoubleClicked(), onLeftBtnPress(), GUISUMOAbstractView::onLeftBtnPress(), onLeftBtnRelease(), GUISUMOAbstractView::onPaint(), and GUISUMOAbstractView::openObjectDialog().
std::string GUISUMOAbstractView::makeSnapshot (const std::string & destFile) inherited
Takes a snapshots and writes it into the given file.
The format to use is determined from the extension. If compiled with ffmpeg and a video format is requested it will instantiate a video encoder.
Parameters
[in] destFile The name of the file to write the snapshot into
Returns
The error message, if an error occcured; "" otherwise
Definition at line 780 of file GUISUMOAbstractView.cpp.
References RGBColor::alpha(), GUIVisualizationSettings::antialiase, GUISUMOAbstractView::applyGLTransform(), GUIVisualizationSettings::backgroundColor, RGBColor::blue(), GUISUMOAbstractView::displayLegend(), GUIVisualizationSettings::dither, GUISUMOAbstractView::doPaintGL(), GUISUMOAbstractView::drawDecals(), GUIPerspectiveChanger::getViewport(), GL2PS_DRAW_BACKGROUND, GL2PS_EPS, GL2PS_OVERFLOW, GL2PS_PDF, GL2PS_PGF, GL2PS_PS, GL2PS_SIMPLE_SORT, GL2PS_SVG, GL2PS_TEX, GL2PS_USE_CURRENT_VIEWPORT, gl2psBeginPage(), gl2psEndPage(), RGBColor::green(), GUISUMOAbstractView::m2p(), GUISUMOAbstractView::makeCurrent(), GUISUMOAbstractView::myChanger, GUISUMOAbstractView::myGrid, GUISUMOAbstractView::myUseToolTips, GUISUMOAbstractView::myVisualizationSettings, GUISUMOAbstractView::paintGLGrid(), RGBColor::red(), GUISUMOAbstractView::saveFrame(), MFXImageHelper::saveImage(), GUIVisualizationSettings::scale, SUMORTree::Search(), GUIVisualizationSettings::showGrid, GUIVisualizationSettings::showSizeLegend, FXSingleEventThread::sleep(), SUMO_const_laneWidth, Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by GUISUMOAbstractView::buildViewToolBars(), GUIViewTraffic::checkSnapshots(), GUISUMOAbstractView::checkSnapshots(), GUIApplicationWindow::handleEvent_Screenshot(), GUISUMOViewParent::onCmdMakeSnapshot(), and GNEViewParent::onCmdMakeSnapshot().
void GNEViewNet::markPopupPosition ()
store the position where a popup-menu was requested
Definition at line 833 of file GNEViewNet.cpp.
References GUISUMOAbstractView::getPositionInformation(), and myPopupSpot.
bool GNEViewNet::mergeJunctions (GNEJunction * moved) private
try to merge moved junction with another junction in that spot return true if merging did take place
Definition at line 1312 of file GNEViewNet.cpp.
References Boundary::add(), GUIGlObject::getGlID(), GUIGlObject::getMicrosimID(), GNEJunction::getNBNode(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getObjectsInBoundary(), NBNode::getPosition(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GLO_JUNCTION, Boundary::grow(), GUISUMOAbstractView::makeCurrent(), GNENet::mergeJunctions(), myNet, myUndoList, myWarnAboutMerge, toString(), and GUIGlObjectStorage::unblockObject().
Referenced by onLeftBtnRelease().
long GNEViewNet::onCmdAddReversedEdge (FXObject * , FXSelector , void *)
add reversed edge
Definition at line 989 of file GNEViewNet.cpp.
References GNENet::addReversedEdge(), getEdgeAtCursorPosition(), myNet, myPopupSpot, and myUndoList.
long GNEViewNet::onCmdChangeMode (FXObject * , FXSelector , void * data)
sets edit mode via combo box
Definition at line 791 of file GNEViewNet.cpp.
References StringBijection< T >::get(), myEditModeNames, and setEditMode().
long GNEViewNet::onCmdDeleteGeometry (FXObject * , FXSelector , void *)
delete the closes geometry point
Definition at line 1050 of file GNEViewNet.cpp.
References GNEPoly::deleteGeometryNear(), myCurrentPoly, and myPopupSpot.
long GNEViewNet::onCmdDuplicateLane (FXObject * , FXSelector , void *)
duplicate selected lane
Definition at line 1060 of file GNEViewNet.cpp.
References GNENet::duplicateLane(), GUIGlObject::getGlID(), getLaneAtCurserPosition(), GLO_LANE, gSelected, GUISelectedStorage::isSelected(), myNet, myPopupSpot, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), and GNENet::retrieveLanes().
long GNEViewNet::onCmdNodeReplace (FXObject * , FXSelector , void *)
replace node by geometry
Definition at line 1124 of file GNEViewNet.cpp.
References getJunctionAtCursorPosition(), myNet, myPopupSpot, myUndoList, and GNENet::replaceJunctionByGeometry().
long GNEViewNet::onCmdNodeShape (FXObject * , FXSelector , void *)
input custom node shape
Definition at line 1081 of file GNEViewNet.cpp.
References SUMORTree::addAdditionalGLObject(), PositionVector::closePolygon(), NBNode::computeNodeShape(), getJunctionAtCursorPosition(), GUIGlObject::getMicrosimID(), GNEJunction::getNBNode(), SUMO::Polygon::getShape(), NBNode::getShape(), GNENet::getVisualisationSpeedUp(), GLO_POLYGON, RGBColor::GREEN, MID_GNE_MODE_MOVE, myCurrentPoly, myNet, myPopupSpot, myUndoList, SUMORTree::removeAdditionalGLObject(), removeCurrentPoly(), GNEJunction::setAttribute(), setEditModeFromHotkey(), GUIPolygon::setLineWidth(), SUMO_ATTR_SHAPE, and toString().
long GNEViewNet::onCmdResetEdgeEndpoint (FXObject * , FXSelector , void *)
restore geometry endpoint to node position
Definition at line 1009 of file GNEViewNet.cpp.
References getEdgeAtCursorPosition(), myPopupSpot, myUndoList, and GNEEdge::resetEndpoint().
long GNEViewNet::onCmdReverseEdge (FXObject * , FXSelector , void *)
reverse edge
Definition at line 979 of file GNEViewNet.cpp.
References getEdgeAtCursorPosition(), myNet, myPopupSpot, myUndoList, and GNENet::reverseEdge().
long GNEViewNet::onCmdSetEdgeEndpoint (FXObject * , FXSelector , void *)
set non-default geometry endpoint
Definition at line 999 of file GNEViewNet.cpp.
References getEdgeAtCursorPosition(), myPopupSpot, myUndoList, and GNEEdge::setEndpoint().
long GNEViewNet::onCmdSimplifyShape (FXObject * , FXSelector , void *)
simply shape of current polygon
Definition at line 1040 of file GNEViewNet.cpp.
References myCurrentPoly, and GNEPoly::simplifyShape().
long GNEViewNet::onCmdSplitEdge (FXObject * , FXSelector , void *)
split edge at cursor position
Definition at line 959 of file GNEViewNet.cpp.
References getEdgeAtCursorPosition(), GNEEdge::getSplitPos(), myNet, myPopupSpot, myUndoList, and GNENet::splitEdge().
long GNEViewNet::onCmdSplitEdgeBidi (FXObject * , FXSelector , void *)
split edge at cursor position
Definition at line 969 of file GNEViewNet.cpp.
References getEdgesAtCursorPosition(), myNet, myPopupSpot, myUndoList, and GNENet::splitEdgesBidi().
long GNEViewNet::onCmdStraightenEdges (FXObject * , FXSelector , void *)
makes selected edges straight
Definition at line 1019 of file GNEViewNet.cpp.
References getEdgeAtCursorPosition(), GUIGlObject::getGlID(), GLO_EDGE, gSelected, GUISelectedStorage::isSelected(), myNet, myPopupSpot, myUndoList, GNEUndoList::p_begin(), GNEUndoList::p_end(), GNENet::retrieveEdges(), GNEEdge::setAttribute(), and SUMO_ATTR_SHAPE.
long GUISUMOAbstractView::onConfigure (FXObject * , FXSelector , void *) virtual inherited
mouse functions
Definition at line 578 of file GUISUMOAbstractView.cpp.
References RGBColor::alpha(), GUIVisualizationSettings::backgroundColor, RGBColor::blue(), GUISUMOAbstractView::checkSnapshots(), GUISUMOAbstractView::doInit(), RGBColor::green(), GUISUMOAbstractView::makeCurrent(), GUISUMOAbstractView::myAmInitialised, GUISUMOAbstractView::myVisualizationSettings, and RGBColor::red().
Referenced by GUISUMOAbstractView::buildViewToolBars().
long GNEViewNet::onDoubleClicked (FXObject * , FXSelector , void *) virtual
called when user press mouse's left button two times
Reimplemented from GUISUMOAbstractView.
Definition at line 685 of file GNEViewNet.cpp.
References GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getObjectUnderCursor(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GLO_ADDITIONAL, GNE_MODE_ADDITIONAL, GNE_MODE_INSPECT, GUISUMOAbstractView::makeCurrent(), myEditMode, GNEAdditional::openAdditionalDialog(), and GUIGlObjectStorage::unblockObject().
void GUISUMOAbstractView::onGamingClick (Position) virtual inherited
on gaming click
Reimplemented in GUIViewTraffic.
Definition at line 1069 of file GUISUMOAbstractView.cpp.
Referenced by GUISUMOAbstractView::endSnapshot(), and GUISUMOAbstractView::onLeftBtnRelease().
long GUISUMOAbstractView::onKeyPress (FXObject * o, FXSelector sel, void * data) virtual inherited
keyboard functions
Definition at line 759 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myChanger, and GUIPerspectiveChanger::onKeyPress().
Referenced by GUISUMOAbstractView::buildViewToolBars(), GUISUMOViewParent::onKeyPress(), and GNEViewParent::onKeyPress().
long GUISUMOAbstractView::onKeyRelease (FXObject * o, FXSelector sel, void * data) virtual inherited
Definition at line 766 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myChanger, and GUIPerspectiveChanger::onKeyRelease().
Referenced by GUISUMOAbstractView::buildViewToolBars(), GUISUMOViewParent::onKeyRelease(), and GNEViewParent::onKeyRelease().
long GNEViewNet::onLeftBtnPress (FXObject * obj, FXSelector sel, void * data) virtual
overloaded handlers
called when user press mouse's left button
Reimplemented from GUISUMOAbstractView.
Definition at line 390 of file GNEViewNet.cpp.
References GNEAdditionalFrame::addAdditional(), GNENet::createEdge(), GNENet::createJunction(), GNENet::deleteGeometryOrEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GNETLSEditorFrame::editJunction(), GNEViewParent::getAdditionalFrame(), GNEViewParent::getConnectorFrame(), GNEInspectorFrame::getEdgeTemplate(), GUIGlObject::getGlID(), Named::getID(), GNEViewParent::getInspectorFrame(), GNEAdditional::getLane(), GUIGlObject::getMicrosimID(), GNEEdge::getNBEdge(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getObjectUnderCursor(), GNELane::getParentEdge(), GUISUMOAbstractView::getPositionInformation(), GNEAdditional::getPositionInView(), GUISelectedStorage::getSelected(), GNELane::getShape(), GNENet::getShapeContainer(), GNEAttributeCarrier::getTag(), GNEViewParent::getTLSEditorFrame(), GUIGlObject::getType(), GUIGlObjectStorage::gIDStorage, GLO_ADDITIONAL, GLO_CROSSING, GLO_EDGE, GLO_JUNCTION, GLO_LANE, GLO_POI, GLO_POLYGON, GNE_MODE_ADDITIONAL, GNE_MODE_CONNECT, GNE_MODE_CREATE_EDGE, GNE_MODE_DELETE, GNE_MODE_INSPECT, GNE_MODE_MOVE, GNE_MODE_SELECT, GNE_MODE_TLS, gSelected, GNEConnectorFrame::handleLaneClick(), GNEUndoList::hasCommandGroup(), GNEInspectorFrame::inspect(), GUISelectedStorage::isSelected(), GUISUMOAbstractView::makeCurrent(), GNEJunction::markAsCreateEdgeSource(), myAdditionalFirstPosition, myAdditionalToMove, myAmInRectSelect, myAutoCreateOppositeEdge, myChainCreateEdge, myCreateEdgeSource, myEdgeToMove, myEditMode, myJunctionToMove, myMoveSelection, myMoveSrc, myNet, myPolyToMove, mySelCorner1, mySelCorner2, mySelectEdges, myUndoList, myViewParent, PositionVector::nearest_offset_to_point2D(), GUISUMOAbstractView::onLeftBtnPress(), GNEUndoList::p_begin(), GNEUndoList::p_end(), GNEAdditionalFrame::removeAdditional(), ShapeContainer::removePOI(), GNENet::retrieveAttributeCarriers(), selectEdges(), Position::set(), setStatusBarText(), GUISelectedStorage::toggleSelection(), toString(), GUIGlObjectStorage::unblockObject(), and GNEJunction::unMarkAsCreateEdgeSource().
long GNEViewNet::onLeftBtnRelease (FXObject * obj, FXSelector sel, void * data) virtual
called when user releases mouse's left button
Reimplemented from GUISUMOAbstractView.
Definition at line 644 of file GNEViewNet.cpp.
References Boundary::add(), GNENet::finishMoveSelection(), GNEEdge::getAttribute(), GUISUMOAbstractView::getObjectsInBoundary(), GNEViewParent::getSelectorFrame(), GNESelectorFrame::handleIDs(), GUISUMOAbstractView::makeCurrent(), mergeJunctions(), myAdditionalToMove, myAmInRectSelect, myEdgeToMove, myJunctionToMove, myMoveSelection, myNet, myPolyToMove, mySelCorner1, mySelCorner2, myUndoList, myViewParent, GUISUMOAbstractView::onLeftBtnRelease(), GNEUndoList::p_end(), GNEJunction::registerMove(), selectEdges(), GNEEdge::setAttribute(), and SUMO_ATTR_SHAPE.
long GUISUMOAbstractView::onMiddleBtnPress (FXObject * , FXSelector , void *) virtual inherited
Definition at line 659 of file GUISUMOAbstractView.cpp.
Referenced by GUISUMOAbstractView::buildViewToolBars().
long GUISUMOAbstractView::onMiddleBtnRelease (FXObject * , FXSelector , void *) virtual inherited
Definition at line 665 of file GUISUMOAbstractView.cpp.
Referenced by GUISUMOAbstractView::buildViewToolBars().
long GUISUMOAbstractView::onMouseLeft (FXObject * , FXSelector , void *) virtual inherited
Definition at line 721 of file GUISUMOAbstractView.cpp.
Referenced by GUISUMOAbstractView::buildViewToolBars().
long GNEViewNet::onMouseMove (FXObject * obj, FXSelector sel, void * data) virtual
called when user moves mouse
Reimplemented from GUISUMOAbstractView.
Definition at line 708 of file GNEViewNet.cpp.
References GNEAdditional::getLane(), GUISUMOAbstractView::getPositionInformation(), GNELane::getShape(), GNEJunction::move(), GNEAdditional::moveAdditional(), GNEEdge::moveGeometry(), GNEPoly::moveGeometry(), GNENet::moveSelection(), myAdditionalFirstPosition, myAdditionalToMove, myAmInRectSelect, myEdgeToMove, myJunctionToMove, myMoveSelection, myMoveSrc, myNet, myPolyToMove, mySelCorner2, myUndoList, PositionVector::nearest_offset_to_point2D(), GUISUMOAbstractView::onMouseMove(), Position::set(), SUMOReal, and Position::x().
long GUISUMOAbstractView::onMouseWheel (FXObject * , FXSelector , void * data) virtual inherited
Definition at line 698 of file GUISUMOAbstractView.cpp.
References GUIMainWindow::isGaming(), GUISUMOAbstractView::myApp, GUISUMOAbstractView::myChanger, GUIPerspectiveChanger::onMouseWheel(), and GUISUMOAbstractView::updatePositionInformation().
Referenced by GUISUMOAbstractView::buildViewToolBars().
long GUISUMOAbstractView::onPaint (FXObject * , FXSelector , void *) virtual inherited
Definition at line 596 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::makeCurrent(), GUISUMOAbstractView::myAmInitialised, and GUISUMOAbstractView::paintGL().
Referenced by GUISUMOAbstractView::buildViewToolBars(), and updateModeSpecificControls().
long GUISUMOAbstractView::onRightBtnPress (FXObject * , FXSelector , void * data) virtual inherited
Definition at line 671 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::destroyPopup(), GUISUMOAbstractView::myChanger, and GUIPerspectiveChanger::onRightBtnPress().
Referenced by GUISUMOAbstractView::buildViewToolBars().
long GUISUMOAbstractView::onRightBtnRelease (FXObject * o, FXSelector sel, void * data) virtual inherited
Definition at line 680 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::destroyPopup(), GUIMainWindow::isGaming(), GUISUMOAbstractView::myApp, GUISUMOAbstractView::myChanger, GUISUMOAbstractView::onMouseMove(), GUIPerspectiveChanger::onRightBtnRelease(), and GUISUMOAbstractView::openObjectDialog().
Referenced by GUISUMOAbstractView::buildViewToolBars().
void GUISUMOAbstractView::openObjectDialog () virtual inherited
Definition at line 727 of file GUISUMOAbstractView.cpp.
References GUIGlObjectStorage::getNetObject(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getObjectUnderCursor(), GUIGlObject::getPopUpMenu(), GUIGlObjectStorage::gIDStorage, GUISUMOAbstractView::makeCurrent(), GUISUMOAbstractView::myAmInitialised, GUISUMOAbstractView::myApp, GUISUMOAbstractView::myChanger, GUISUMOAbstractView::myPopup, GUIPerspectiveChanger::onRightBtnRelease(), and GUIGlObjectStorage::unblockObject().
Referenced by GUISUMOAbstractView::buildViewToolBars(), and GUISUMOAbstractView::onRightBtnRelease().
GNEViewNet& GNEViewNet::operator= (const GNEViewNet &) private
Invalidated assignment operator.
SUMOReal GUISUMOAbstractView::p2m (SUMOReal pixel) const inherited
pixels-to-meters conversion method
Definition at line 521 of file GUISUMOAbstractView.cpp.
References GUIPerspectiveChanger::getViewport(), Boundary::getWidth(), and GUISUMOAbstractView::myChanger.
Referenced by GUISUMOAbstractView::buildViewToolBars(), GUIDanielPerspectiveChanger::changeCanvassLeft(), GUIDanielPerspectiveChanger::move(), and GUISUMOAbstractView::showToolTipFor().
void GUISUMOAbstractView::paintGL () protected inherited
performs the painting of the simulation
Definition at line 229 of file GUISUMOAbstractView.cpp.
References RGBColor::alpha(), GUIVisualizationSettings::antialiase, GUISUMOAbstractView::applyGLTransform(), GUIVisualizationSettings::backgroundColor, RGBColor::blue(), GUISUMOAbstractView::centerTo(), GUISUMOAbstractView::displayLegend(), GUIVisualizationSettings::dither, GUISUMOAbstractView::doPaintGL(), GUISUMOAbstractView::getObjectUnderCursor(), GUISUMOAbstractView::getTrackedID(), GUIPerspectiveChanger::getViewport(), RGBColor::green(), GUIGlObject::INVALID_ID, GUISUMOAbstractView::myChanger, GUISUMOAbstractView::myUseToolTips, GUISUMOAbstractView::myVisualizationSettings, RGBColor::red(), GUIVisualizationSettings::showSizeLegend, and GUISUMOAbstractView::showToolTipFor().
Referenced by GUISUMOAbstractView::onPaint().
void GUISUMOAbstractView::paintGLGrid () protected inherited
paints a grid
Definition at line 414 of file GUISUMOAbstractView.cpp.
References GUIVisualizationSettings::gridXSize, GUIVisualizationSettings::gridYSize, GUISUMOAbstractView::myGrid, GUISUMOAbstractView::myVisualizationSettings, SUMOReal, Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by GUIViewTraffic::doPaintGL(), doPaintGL(), and GUISUMOAbstractView::makeSnapshot().
void GUISUMOAbstractView::recenterView () virtual inherited
recenters the view
Definition at line 527 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myChanger, GUISUMOAbstractView::myGrid, and GUIPerspectiveChanger::setViewport().
Referenced by GUISUMOAbstractView::buildViewToolBars(), GUIGlChildWindow::onCmdRecenterView(), GUIDanielPerspectiveChanger::onKeyPress(), and GUICompleteSchemeStorage::setViewport().
void GUISUMOAbstractView::remove (GUIDialog_EditViewport *) inherited
remove viewport
Definition at line 1029 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myViewportChooser.
Referenced by GUIDialog_ViewSettings::~GUIDialog_ViewSettings().
void GUISUMOAbstractView::remove (GUIDialog_ViewSettings *) inherited
remove view settings
Definition at line 1035 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myVisualizationChanger, and SUMOReal.
bool GUISUMOAbstractView::removeAdditionalGLVisualisation (const GUIGlObject *const which) inherited
Removes an object from the list of objects that show additional things.
Parameters
[in] which The object to remoe
Returns
True if the object was known, false otherwise
See also
GUIGlObject::drawGLAdditional
Definition at line 1210 of file GUISUMOAbstractView.cpp.
References GUIGlObject::getGlID(), GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::myAdditionallyDrawn, and GUISUMOAbstractView::stopTrack().
Referenced by GUIVehicle::drawOutsideNetwork(), GUISUMOAbstractView::endSnapshot(), GUIBaseVehicle::removeActiveAddVisualisation(), and GUIPerson::removeActiveAddVisualisation().
void GNEViewNet::removeCurrentPoly () private
remove the currently edited polygon
Definition at line 1114 of file GNEViewNet.cpp.
References GNENet::getVisualisationSpeedUp(), myCurrentPoly, myNet, and SUMORTree::removeAdditionalGLObject().
Referenced by abortOperation(), hotkeyEnter(), and onCmdNodeShape().
void GUISUMOAbstractView::saveFrame (const std::string & destFile, FXColor * buf) virtual inherited
Adds a frame to a video snapshot which will be initialized if neccessary.
Reimplemented in GUIViewTraffic.
Definition at line 935 of file GUISUMOAbstractView.cpp.
References UNUSED_PARAMETER.
Referenced by GUISUMOAbstractView::buildViewToolBars(), and GUISUMOAbstractView::makeSnapshot().
bool GNEViewNet::selectEdges ()
whether inspection, selection and inversion should apply to edges or to lanes
Definition at line 307 of file GNEViewNet.cpp.
References mySelectEdges.
Referenced by GNESelectorFrame::onCmdInvert(), onLeftBtnPress(), and onLeftBtnRelease().
bool GNEViewNet::setColorScheme (const std::string & name) virtual
set color schieme
Reimplemented from GUISUMOAbstractView.
Definition at line 285 of file GNEViewNet.cpp.
References GUICompleteSchemeStorage::contains(), GUICompleteSchemeStorage::get(), GUIDialog_ViewSettings::getCurrentScheme(), gSchemeStorage, GUISUMOAbstractView::myVisualizationChanger, GUISUMOAbstractView::myVisualizationSettings, and GUIDialog_ViewSettings::setCurrentScheme().
void GUISUMOAbstractView::setDelay (SUMOReal delay) inherited
Sets the delay of the parent application.
Definition at line 1263 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myApp, and GUIMainWindow::setDelay().
Referenced by GUIDialog_ViewSettings::loadSettings().
void GNEViewNet::setEditMode (EditMode mode) private
set edit mode
Definition at line 1138 of file GNEViewNet.cpp.
References abortOperation(), GNENet::computeEverything(), GNE_MODE_CONNECT, GNE_MODE_TLS, GUISUMOAbstractView::myApp, myEditMode, myNet, myPreviousEditMode, setStatusBarText(), and updateModeSpecificControls().
Referenced by onCmdChangeMode(), and setEditModeFromHotkey().
void GNEViewNet::setEditModeFromHotkey (FXushort selid)
sets edit mode (from hotkey)
Parameters
[in] selid An id MID_GNE_MODE_<foo> as defined in GUIAppEnum
Definition at line 798 of file GNEViewNet.cpp.
References StringBijection< T >::getString(), GNE_MODE_ADDITIONAL, GNE_MODE_CONNECT, GNE_MODE_CREATE_EDGE, GNE_MODE_DELETE, GNE_MODE_INSPECT, GNE_MODE_MOVE, GNE_MODE_SELECT, GNE_MODE_TLS, MID_GNE_MODE_ADDITIONAL, MID_GNE_MODE_CONNECT, MID_GNE_MODE_CREATE_EDGE, MID_GNE_MODE_DELETE, MID_GNE_MODE_INSPECT, MID_GNE_MODE_MOVE, MID_GNE_MODE_SELECT, MID_GNE_MODE_TLS, myEditMode, myEditModeNames, myEditModesCombo, and setEditMode().
Referenced by GNEApplicationWindow::handleEvent_NetworkLoaded(), onCmdNodeShape(), and GNEApplicationWindow::onCmdSetMode().
void GNEViewNet::setSelectionScaling (SUMOReal selectionScale)
set selection scaling
Definition at line 319 of file GNEViewNet.cpp.
References GUISUMOAbstractView::myVisualizationSettings, and GUIVisualizationSettings::selectionScale.
Referenced by GNESelectorFrame::onCmdScaleSelection().
void GUISUMOAbstractView::setSnapshots (std::map< SUMOTime, std::string > snaps) inherited
Sets the snapshot time to file map.
Parameters
[in] snaps The snapshots to take at certain times
Definition at line 774 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::mySnapshots.
Referenced by GUISUMOAbstractView::buildViewToolBars(), and GUISettingsHandler::setSnapshots().
void GNEViewNet::setStatusBarText (const std::string & text)
set staturBar text
Definition at line 301 of file GNEViewNet.cpp.
References GUISUMOAbstractView::myApp, and GUIMainWindow::setStatusBarText().
Referenced by GNETLSEditorFrame::editJunction(), GNEConnectorFrame::handleLaneClick(), hotkeyDel(), GNEConnectorFrame::onCmdCancel(), GNETLSEditorFrame::onCmdDefSwitch(), GNEConnectorFrame::onCmdOK(), onLeftBtnPress(), and setEditMode().
void GUISUMOAbstractView::setViewportFromTo (const Position & lookFrom, const Position & lookAt) virtual inherited
applies the given viewport settings
Definition at line 996 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myChanger, GUIPerspectiveChanger::setViewportFrom(), Position::x(), Position::y(), and Position::z().
Referenced by GUISettingsHandler::applyViewport(), GUISUMOAbstractView::buildViewToolBars(), GUISUMOAbstractView::copyViewportTo(), GNEApplicationWindow::handleEvent_NetworkLoaded(), GUIDialog_EditViewport::onCmdCancel(), GUIDialog_EditViewport::onCmdChanged(), GUIDialog_EditViewport::onCmdOk(), TraCIServerAPI_GUI::processSet(), and GUICompleteSchemeStorage::setViewport().
void GUISUMOAbstractView::setWindowCursorPosition (FXint x, FXint y) inherited
Returns the information whether rotation is allowd.
Note
disabled Returns the gl-id of the object under the given coordinates
Definition at line 564 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myMouseHotspotX, GUISUMOAbstractView::myMouseHotspotY, GUISUMOAbstractView::myWindowCursorPositionX, and GUISUMOAbstractView::myWindowCursorPositionY.
Referenced by GUISUMOAbstractView::buildViewToolBars(), and GUIDanielPerspectiveChanger::onMouseMove().
bool GNEViewNet::showLockIcon () const
check if lock icon should be visible
Definition at line 863 of file GNEViewNet.cpp.
References GNE_MODE_ADDITIONAL, GNE_MODE_INSPECT, GNE_MODE_MOVE, and myEditMode.
void GUISUMOAbstractView::showToolTipFor (const GUIGlID id) protected inherited
invokes the tooltip for the given object
Definition at line 400 of file GUISUMOAbstractView.cpp.
References Position::add(), RGBColor::BLACK, GLHelper::drawTextBox(), GUIGlObject::getFullName(), GUIGlObjectStorage::getObjectBlocking(), GUISUMOAbstractView::getPositionInformation(), GUIGlObjectStorage::gIDStorage, GLO_MAX, GUISUMOAbstractView::p2m(), and GUIGlObjectStorage::unblockObject().
Referenced by GUISUMOAbstractView::paintGL().
void GUISUMOAbstractView::showToolTips (bool val) inherited
show tool tips
Definition at line 1011 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myUseToolTips.
Referenced by GUISUMOAbstractView::endSnapshot(), and GUIGlChildWindow::onCmdShowToolTips().
void GUISUMOAbstractView::showViewportEditor () virtual inherited
show viewport editor
Definition at line 987 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::getViewportEditor(), GUIPerspectiveChanger::getXPos(), GUIPerspectiveChanger::getYPos(), GUIPerspectiveChanger::getZPos(), Position::INVALID, GUISUMOAbstractView::myChanger, GUISUMOAbstractView::myViewportChooser, and GUIDialog_EditViewport::setOldValues().
Referenced by GUISUMOAbstractView::endSnapshot(), and GUIGlChildWindow::onCmdEditViewport().
void GUISUMOAbstractView::showViewschemeEditor () inherited
show viewsscheme editor
Definition at line 960 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myDecals, GUISUMOAbstractView::myDecalsLock, GUISUMOAbstractView::myVisualizationChanger, GUISUMOAbstractView::myVisualizationSettings, and GUIDialog_ViewSettings::setCurrent().
Referenced by GUISUMOAbstractView::endSnapshot(), GUIGlChildWindow::onCmdEditViewScheme(), and GUIDanielPerspectiveChanger::onKeyPress().
void GUISUMOAbstractView::startTrack (int) virtual inherited
star track
Reimplemented in GUIViewTraffic.
Definition at line 1053 of file GUISUMOAbstractView.cpp.
Referenced by GUISUMOAbstractView::endSnapshot(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), and TraCIServerAPI_GUI::processSet().
void GUISUMOAbstractView::stopTrack () virtual inherited
stop track
Reimplemented in GUIViewTraffic.
Definition at line 1058 of file GUISUMOAbstractView.cpp.
Referenced by GUISUMOAbstractView::endSnapshot(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), TraCIServerAPI_GUI::processSet(), and GUISUMOAbstractView::removeAdditionalGLVisualisation().
void GNEViewNet::updateControls ()
update control contents after undo/redo or recompute
Definition at line 1360 of file GNEViewNet.cpp.
References GNEViewParent::getInspectorFrame(), GNE_MODE_INSPECT, myEditMode, and myViewParent.
Referenced by GNEApplicationWindow::updateControls().
void GNEViewNet::updateModeSpecificControls () private
updates mode specific controls
Definition at line 1200 of file GNEViewNet.cpp.
References GUIPerspectiveChanger::changeCanvassLeft(), GNEViewParent::getAdditionalFrame(), GNEViewParent::getConnectorFrame(), GNEViewParent::getInspectorFrame(), GNEViewParent::getSelectorFrame(), GNEViewParent::getTLSEditorFrame(), GNE_MODE_ADDITIONAL, GNE_MODE_CONNECT, GNE_MODE_CREATE_EDGE, GNE_MODE_DELETE, GNE_MODE_INSPECT, GNE_MODE_MOVE, GNE_MODE_SELECT, GNE_MODE_TLS, GNEConnectorFrame::hide(), GNETLSEditorFrame::hide(), GNESelectorFrame::hide(), GNEInspectorFrame::hide(), GNEAdditionalFrame::hide(), myAutoCreateOppositeEdge, myChainCreateEdge, myChangeAllPhases, GUISUMOAbstractView::myChanger, myEditMode, myExtendToEdgeNodes, mySelectEdges, myToolbar, myViewParent, myWarnAboutMerge, GUISUMOAbstractView::onPaint(), GNEConnectorFrame::show(), GNETLSEditorFrame::show(), GNESelectorFrame::show(), GNEInspectorFrame::show(), and GNEAdditionalFrame::show().
Referenced by setEditMode().
void GUISUMOAbstractView::updatePositionInformation () const protected inherited
update position information
Definition at line 197 of file GUISUMOAbstractView.cpp.
References GeoConvHelper::cartesian2geo(), GEO_OUTPUT_ACCURACY, GUIMainWindow::getCartesianLabel(), GeoConvHelper::getFinal(), GUIMainWindow::getGeoLabel(), GUISUMOAbstractView::getPositionInformation(), GUISUMOAbstractView::myApp, text(), toString(), Position::x(), and Position::y().
Referenced by GUISUMOAbstractView::centerTo(), GUISUMOAbstractView::onMouseMove(), and GUISUMOAbstractView::onMouseWheel().
void GUISUMOAbstractView::updateToolTip () inherited
A method that updates the tooltip.
Definition at line 166 of file GUISUMOAbstractView.cpp.
References GUISUMOAbstractView::myUseToolTips.
Referenced by GUISUMOAbstractView::buildViewToolBars(), GUIDanielPerspectiveChanger::onKeyPress(), GUIDanielPerspectiveChanger::onMouseMove(), and GUIDanielPerspectiveChanger::onMouseWheel().
Field Documentation
Position GNEViewNet::myAdditionalFirstPosition private
variable to save the firstposition of the additional before move
Definition at line 275 of file GNEViewNet.h.
Referenced by onLeftBtnPress(), and onMouseMove().
std::map<const GUIGlObject*, int> GUISUMOAbstractView::myAdditionallyDrawn protected inherited
List of objects for which GUIGlObject::drawGLAdditional is called.
Definition at line 426 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::addAdditionalGLVisualisation(), GUIViewTraffic::doPaintGL(), doPaintGL(), GUISUMOAbstractView::isAdditionalGLVisualisationEnabled(), and GUISUMOAbstractView::removeAdditionalGLVisualisation().
GNEAdditional* GNEViewNet::myAdditionalToMove private
the stoppingPlace element which shape is being moved
Definition at line 272 of file GNEViewNet.h.
Referenced by onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
bool GUISUMOAbstractView::myAmInitialised protected inherited
Internal information whether doInit() was called.
Definition at line 399 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::onConfigure(), GUISUMOAbstractView::onPaint(), and GUISUMOAbstractView::openObjectDialog().
bool GNEViewNet::myAmInRectSelect private
whether we have started rectangle-selection
Definition at line 290 of file GNEViewNet.h.
Referenced by abortOperation(), doPaintGL(), onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
GUIMainWindow* GUISUMOAbstractView::myApp protected inherited
The application.
Definition at line 372 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::getDelay(), GUISUMOAbstractView::getObjectsInBoundary(), GUISUMOAbstractView::onLeftBtnRelease(), GUISUMOAbstractView::onMouseWheel(), GUISUMOAbstractView::onRightBtnRelease(), GUISUMOAbstractView::openObjectDialog(), GUIViewTraffic::saveFrame(), GUIViewTraffic::setColorScheme(), GUISUMOAbstractView::setDelay(), setEditMode(), setStatusBarText(), and GUISUMOAbstractView::updatePositionInformation().
FXMenuCheck* GNEViewNet::myAutoCreateOppositeEdge private
Definition at line 257 of file GNEViewNet.h.
Referenced by buildEditModeControls(), onLeftBtnPress(), and updateModeSpecificControls().
FXMenuCheck* GNEViewNet::myChainCreateEdge private
whether the endpoint for a created edge should be set as the new source
Definition at line 256 of file GNEViewNet.h.
Referenced by buildEditModeControls(), onLeftBtnPress(), and updateModeSpecificControls().
FXMenuCheck* GNEViewNet::myChangeAllPhases private
menu check to set change all phases
Definition at line 248 of file GNEViewNet.h.
Referenced by buildEditModeControls(), changeAllPhases(), and updateModeSpecificControls().
GUIPerspectiveChanger* GUISUMOAbstractView::myChanger protected inherited
The perspective changer.
Definition at line 381 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::applyGLTransform(), GUISUMOAbstractView::centerTo(), GUISUMOAbstractView::copyViewportTo(), GUISUMOAbstractView::getChanger(), GUISUMOAbstractView::getObjectsInBoundary(), GUISUMOAbstractView::getPositionInformation(), GUISUMOAbstractView::getViewportEditor(), GUISUMOAbstractView::getVisibleBoundary(), GUISUMOAbstractView::m2p(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::onKeyPress(), GUISUMOAbstractView::onKeyRelease(), GUISUMOAbstractView::onLeftBtnPress(), GUISUMOAbstractView::onLeftBtnRelease(), GUISUMOAbstractView::onMouseMove(), GUISUMOAbstractView::onMouseWheel(), GUISUMOAbstractView::onRightBtnPress(), GUISUMOAbstractView::onRightBtnRelease(), GUISUMOAbstractView::openObjectDialog(), GUISUMOAbstractView::p2m(), GUISUMOAbstractView::paintGL(), GUISUMOAbstractView::recenterView(), GUISUMOAbstractView::setViewportFromTo(), GUISUMOAbstractView::showViewportEditor(), updateModeSpecificControls(), and GUISUMOAbstractView::~GUISUMOAbstractView().
GNEJunction* GNEViewNet::myCreateEdgeSource private
source junction for new edge 0 if no edge source is selected an existing (or newly created) junction otherwise
Definition at line 253 of file GNEViewNet.h.
Referenced by abortOperation(), and onLeftBtnPress().
GNEPoly* GNEViewNet::myCurrentPoly private
current polygon
Definition at line 319 of file GNEViewNet.h.
Referenced by hotkeyEnter(), onCmdDeleteGeometry(), onCmdNodeShape(), onCmdSimplifyShape(), and removeCurrentPoly().
std::vector<Decal> GUISUMOAbstractView::myDecals protected inherited
Definition at line 413 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::addDecals(), GUISUMOAbstractView::drawDecals(), GUISUMOAbstractView::showViewschemeEditor(), and GUISUMOAbstractView::~GUISUMOAbstractView().
MFXMutex GUISUMOAbstractView::myDecalsLock protected inherited
The mutex to use before accessing the decals list in order to avoid thread conficts.
Definition at line 416 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::drawDecals(), and GUISUMOAbstractView::showViewschemeEditor().
GNEEdge* GNEViewNet::myEdgeToMove private
the edge of which geometry is being moved
Definition at line 266 of file GNEViewNet.h.
Referenced by onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
StringBijection<EditMode> GNEViewNet::myEditAdditionalModeNames private
Definition at line 309 of file GNEViewNet.h.
EditMode GNEViewNet::myEditMode private
the current edit mode
Definition at line 236 of file GNEViewNet.h.
Referenced by abortOperation(), doPaintGL(), getCurrentEditMode(), hotkeyDel(), hotkeyEnter(), onDoubleClicked(), onLeftBtnPress(), setEditMode(), setEditModeFromHotkey(), showLockIcon(), updateControls(), and updateModeSpecificControls().
StringBijection<EditMode> GNEViewNet::myEditModeNames private
since we cannot switch on strings we map the mode names to an enum
Definition at line 308 of file GNEViewNet.h.
Referenced by buildEditModeControls(), onCmdChangeMode(), and setEditModeFromHotkey().
FXComboBox* GNEViewNet::myEditModesCombo private
combo box for selecting the edit mode
Definition at line 305 of file GNEViewNet.h.
Referenced by buildEditModeControls(), and setEditModeFromHotkey().
FXMenuCheck* GNEViewNet::myExtendToEdgeNodes private
menu check to extend to edge nodes
Definition at line 245 of file GNEViewNet.h.
Referenced by autoSelectNodes(), buildEditModeControls(), and updateModeSpecificControls().
SUMORTree* GUISUMOAbstractView::myGrid protected inherited
The visualization speed-up.
Definition at line 378 of file GUISUMOAbstractView.h.
Referenced by GUIViewTraffic::doPaintGL(), doPaintGL(), GUISUMOAbstractView::getGridHeight(), GUISUMOAbstractView::getGridWidth(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::paintGLGrid(), and GUISUMOAbstractView::recenterView().
bool GUISUMOAbstractView::myInEditMode protected inherited
Information whether too-tip informations shall be generated.
Definition at line 384 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::isInEditMode().
GNEJunction* GNEViewNet::myJunctionToMove private
the Junction to be moved.
Definition at line 263 of file GNEViewNet.h.
Referenced by onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
int GUISUMOAbstractView::myMouseHotspotX protected inherited
Offset to the mouse-hotspot from the mouse position.
Definition at line 387 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::setWindowCursorPosition().
int GUISUMOAbstractView::myMouseHotspotY protected inherited
Definition at line 387 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::setWindowCursorPosition().
bool GNEViewNet::myMoveSelection private
whether a selection is being moved
Definition at line 281 of file GNEViewNet.h.
Referenced by onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
Position GNEViewNet::myMoveSrc private
position from which to move edge geometry
Definition at line 278 of file GNEViewNet.h.
Referenced by onLeftBtnPress(), and onMouseMove().
GNENet* GNEViewNet::myNet private
we are not responsible for deletion
Definition at line 233 of file GNEViewNet.h.
Referenced by deleteSelectedEdges(), deleteSelectedJunctions(), getNet(), mergeJunctions(), onCmdAddReversedEdge(), onCmdDuplicateLane(), onCmdNodeReplace(), onCmdNodeShape(), onCmdReverseEdge(), onCmdSplitEdge(), onCmdSplitEdgeBidi(), onCmdStraightenEdges(), onLeftBtnPress(), onLeftBtnRelease(), onMouseMove(), removeCurrentPoly(), and setEditMode().
GUIGlChildWindow* GUISUMOAbstractView::myParent protected inherited
The parent window.
Definition at line 375 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::getColoringSchemesCombo().
MFXMutex GUISUMOAbstractView::myPolyDrawLock mutable protected inherited
poly draw lock
Definition at line 423 of file GUISUMOAbstractView.h.
GNEPoly* GNEViewNet::myPolyToMove private
the poly of which geometry is being moved
Definition at line 269 of file GNEViewNet.h.
Referenced by onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
GUIGLObjectPopupMenu* GUISUMOAbstractView::myPopup protected inherited
The current popup-menu.
Definition at line 390 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::destroyPopup(), GUISUMOAbstractView::openObjectDialog(), and GUISUMOAbstractView::~GUISUMOAbstractView().
Position GNEViewNet::myPopupSpot private
Poput spot.
Definition at line 316 of file GNEViewNet.h.
Referenced by getEdgeAtCursorPosition(), getEdgesAtCursorPosition(), getJunctionAtCursorPosition(), getLaneAtCurserPosition(), markPopupPosition(), onCmdAddReversedEdge(), onCmdDeleteGeometry(), onCmdDuplicateLane(), onCmdNodeReplace(), onCmdNodeShape(), onCmdResetEdgeEndpoint(), onCmdReverseEdge(), onCmdSetEdgeEndpoint(), onCmdSplitEdge(), onCmdSplitEdgeBidi(), and onCmdStraightenEdges().
EditMode GNEViewNet::myPreviousEditMode private
the previous edit mode used for toggling
Definition at line 239 of file GNEViewNet.h.
Referenced by setEditMode().
Position GNEViewNet::mySelCorner1 private
firstcorner of the rectangle-selection
Definition at line 293 of file GNEViewNet.h.
Referenced by doPaintGL(), onLeftBtnPress(), and onLeftBtnRelease().
Position GNEViewNet::mySelCorner2 private
second corner of the rectangle-selection
Definition at line 296 of file GNEViewNet.h.
Referenced by doPaintGL(), onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
FXMenuCheck* GNEViewNet::mySelectEdges private
menu check to select only edges
Definition at line 242 of file GNEViewNet.h.
Referenced by buildEditModeControls(), deleteSelectedEdges(), onLeftBtnPress(), selectEdges(), and updateModeSpecificControls().
std::map<SUMOTime, std::string> GUISUMOAbstractView::mySnapshots protected inherited
Snapshots.
Definition at line 420 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::checkSnapshots(), and GUISUMOAbstractView::setSnapshots().
FXToolBar* GNEViewNet::myToolbar private
Definition at line 302 of file GNEViewNet.h.
Referenced by buildEditModeControls(), and updateModeSpecificControls().
GNEUndoList* GNEViewNet::myUndoList private
a reference to the undolist maintained in the application
Definition at line 313 of file GNEViewNet.h.
Referenced by abortOperation(), deleteSelectedEdges(), deleteSelectedJunctions(), getUndoList(), hotkeyDel(), hotkeyEnter(), mergeJunctions(), onCmdAddReversedEdge(), onCmdDuplicateLane(), onCmdNodeReplace(), onCmdNodeShape(), onCmdResetEdgeEndpoint(), onCmdReverseEdge(), onCmdSetEdgeEndpoint(), onCmdSplitEdge(), onCmdSplitEdgeBidi(), onCmdStraightenEdges(), onLeftBtnPress(), onLeftBtnRelease(), and onMouseMove().
bool GUISUMOAbstractView::myUseToolTips protected inherited
use tool tips
Definition at line 396 of file GUISUMOAbstractView.h.
Referenced by GUIViewTraffic::doPaintGL(), doPaintGL(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::paintGL(), GUISUMOAbstractView::showToolTips(), and GUISUMOAbstractView::updateToolTip().
GNEViewParent* GNEViewNet::myViewParent private
view parent
Definition at line 230 of file GNEViewNet.h.
Referenced by abortOperation(), getViewParent(), hotkeyEnter(), onLeftBtnPress(), onLeftBtnRelease(), updateControls(), and updateModeSpecificControls().
GUIDialog_EditViewport* GUISUMOAbstractView::myViewportChooser protected inherited
viewport chooser
Definition at line 402 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::getViewportEditor(), GUISUMOAbstractView::onMouseMove(), GUISUMOAbstractView::remove(), GUISUMOAbstractView::showViewportEditor(), and GUISUMOAbstractView::~GUISUMOAbstractView().
GUIDialog_ViewSettings* GUISUMOAbstractView::myVisualizationChanger protected inherited
Visualization changer.
Definition at line 408 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::remove(), GUIViewTraffic::setColorScheme(), setColorScheme(), GUISUMOAbstractView::showViewschemeEditor(), and GUISUMOAbstractView::~GUISUMOAbstractView().
GUIVisualizationSettings* GUISUMOAbstractView::myVisualizationSettings protected inherited
visualization settings
Definition at line 393 of file GUISUMOAbstractView.h.
Referenced by GUIViewTraffic::buildViewToolBars(), GUIViewTraffic::doPaintGL(), doPaintGL(), GUISUMOAbstractView::getObjectsInBoundary(), GUISUMOAbstractView::getVisualisationSettings(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::onConfigure(), GUISUMOAbstractView::paintGL(), GUISUMOAbstractView::paintGLGrid(), GUIViewTraffic::setColorScheme(), setColorScheme(), setSelectionScaling(), GUISUMOAbstractView::showViewschemeEditor(), and GUISUMOAbstractView::~GUISUMOAbstractView().
FXMenuCheck* GNEViewNet::myWarnAboutMerge private
whether we should warn about merging junctions
Definition at line 284 of file GNEViewNet.h.
Referenced by buildEditModeControls(), mergeJunctions(), and updateModeSpecificControls().
FXint GUISUMOAbstractView::myWindowCursorPositionX protected inherited
Position of the cursor relative to the window.
Definition at line 405 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::getPositionInformation(), and GUISUMOAbstractView::setWindowCursorPosition().
FXint GUISUMOAbstractView::myWindowCursorPositionY protected inherited
Definition at line 405 of file GUISUMOAbstractView.h.
Referenced by GUISUMOAbstractView::getPositionInformation(), and GUISUMOAbstractView::setWindowCursorPosition().
The documentation for this class was generated from the following files:
GNEViewNet.h
GNEViewNet.cpp