SUMO - Simulation of Urban MObility: PCLoaderArcView Class Reference
PCLoaderArcView Class Reference
A reader of pois and polygons from shape files.
#include <PCLoaderArcView.h>
Static Public Member Functions
static void loadIfSet (OptionsCont &oc, PCPolyContainer &toFill, PCTypeMap &tm)
Loads pois/polygons assumed to be stored as shape files-files.
Static Protected Member Functions
static void load (const std::string &file, OptionsCont &oc, PCPolyContainer &toFill, PCTypeMap &tm)
Parses pois/polys stored within the given file.
Private Member Functions
PCLoaderArcView & operator= (const PCLoaderArcView &)
Invalidated assignment operator.
PCLoaderArcView (const PCLoaderArcView &)
Invalidated copy constructor.
Detailed Description
A reader of pois and polygons from shape files.
The current importer works only if SUMO was compiled with GDAL-support. If not, an error message is generated.
Todo:
reinsert import via shapelib
Definition at line 58 of file PCLoaderArcView.h.
Constructor & Destructor Documentation
PCLoaderArcView::PCLoaderArcView (const PCLoaderArcView &) private
Invalidated copy constructor.
Member Function Documentation
void PCLoaderArcView::load (const std::string & file, OptionsCont & oc, PCPolyContainer & toFill, PCTypeMap & tm) static protected
Parses pois/polys stored within the given file.
Parameters
[in] oc The options container to get further options from
[in] toFill The poly/pois container to add loaded polys/pois to
[in] tm The type map to use for setting values of loaded polys/pois
Exceptions
ProcessError if something fails
Definition at line 74 of file PCLoaderArcView.cpp.
References PCPolyContainer::add(), OptionsCont::getBool(), OptionsCont::getFloat(), GeoConvHelper::getProcessing(), OptionsCont::getString(), OptionsCont::isSet(), StringUtils::latin1_to_utf8(), RGBColor::parseColor(), PROGRESS_DONE_MESSAGE, StringUtils::prune(), PositionVector::push_back_noDoublePos(), SUMOReal, toString(), WRITE_ERROR, WRITE_WARNING, and GeoConvHelper::x2cartesian().
Referenced by loadIfSet().
void PCLoaderArcView::loadIfSet (OptionsCont & oc, PCPolyContainer & toFill, PCTypeMap & tm) static
Loads pois/polygons assumed to be stored as shape files-files.
If the option "shape-files" is set within the given options container, the files stored herein are parsed using "load", assuming this option contains file paths to files containing pois and polygons stored as shape-files.
Parameters
[in] oc The options container to get further options from
[in] toFill The poly/pois container to add loaded polys/pois to
[in] tm The type map to use for setting values of loaded polys/pois
Exceptions
ProcessError if something fails
Definition at line 57 of file PCLoaderArcView.cpp.
References OptionsCont::getStringVector(), OptionsCont::isSet(), load(), PROGRESS_BEGIN_MESSAGE, and PROGRESS_DONE_MESSAGE.
Referenced by main().
PCLoaderArcView& PCLoaderArcView::operator= (const PCLoaderArcView &) private
Invalidated assignment operator.
The documentation for this class was generated from the following files:
PCLoaderArcView.h
PCLoaderArcView.cpp