SUMO - Simulation of Urban MObility: NBConnection Class Reference
NBConnection Class Reference
#include <NBConnection.h>
Public Member Functions
bool check (const NBEdgeCont &ec)
checks whether the edges are still valid
NBEdge * getFrom () const
returns the from-edge (start of the connection)
int getFromLane () const
returns the from-lane
std::string getID () const
returns the id of the connection (!!! not really pretty)
int getTLIndex () const
NBEdge * getTo () const
returns the to-edge (end of the connection)
int getToLane () const
returns the to-lane
NBConnection (NBEdge *from, NBEdge *to)
Constructor.
NBConnection (NBEdge *from, int fromLane, NBEdge *to, int toLane, int tlIndex=InvalidTlIndex)
Constructor.
NBConnection (const std::string &fromID, NBEdge *from, const std::string &toID, NBEdge *to)
Constructor.
NBConnection (const NBConnection &c)
Constructor.
bool operator!= (const NBConnection &c) const
Comparison operator.
bool operator== (const NBConnection &c) const
Comparison operator.
bool replaceFrom (NBEdge *which, NBEdge *by)
replaces the from-edge by the one given
bool replaceFrom (NBEdge *which, int whichLane, NBEdge *by, int byLane)
replaces the from-edge by the one given
bool replaceTo (NBEdge *which, NBEdge *by)
replaces the to-edge by the one given
bool replaceTo (NBEdge *which, int whichLane, NBEdge *by, int byLane)
replaces the to-edge by the one given
void setTLIndex (int tlIndex)
void shiftLaneIndex (NBEdge *edge, int offset)
patches lane indices refering to the given edge
virtual ~NBConnection ()
Destructor.
Static Public Attributes
static const NBConnection InvalidConnection
static const int InvalidTlIndex = -1
Private Member Functions
NBEdge * checkFrom (const NBEdgeCont &ec)
Checks whether the from-edge is still valid.
NBEdge * checkTo (const NBEdgeCont &ec)
Checks whether the to-edge is still valid.
Private Attributes
NBEdge * myFrom
The from- and the to-edges.
std::string myFromID
The names of both edges, needed for verification of validity.
int myFromLane
The lanes; may be -1 if no certain lane was specified.
int myTlIndex
NBEdge * myTo
std::string myToID
int myToLane
Friends
bool operator< (const NBConnection &c1, const NBConnection &c2)
Compares both connections in order to allow sorting.
std::ostream & operator<< (std::ostream &os, const NBConnection &c)
Output operator.
Detailed Description
Definition at line 51 of file NBConnection.h.
Constructor & Destructor Documentation
NBConnection::NBConnection (NBEdge * from, NBEdge * to)
Constructor.
Definition at line 54 of file NBConnection.cpp.
NBConnection::NBConnection (NBEdge * from, int fromLane, NBEdge * to, int toLane, int tlIndex = InvalidTlIndex)
Constructor.
Definition at line 71 of file NBConnection.cpp.
References Named::getID(), myFromID, and myToID.
NBConnection::NBConnection (const std::string & fromID, NBEdge * from, const std::string & toID, NBEdge * to)
Constructor.
Definition at line 62 of file NBConnection.cpp.
NBConnection::NBConnection (const NBConnection & c)
Constructor.
Definition at line 88 of file NBConnection.cpp.
NBConnection::~NBConnection () virtual
Destructor.
Definition at line 85 of file NBConnection.cpp.
Member Function Documentation
bool NBConnection::check (const NBEdgeCont & ec)
checks whether the edges are still valid
Definition at line 197 of file NBConnection.cpp.
References checkFrom(), checkTo(), myFrom, and myTo.
Referenced by NIVissimDisturbance::addToNode(), NBLoadedTLDef::buildPhaseState(), NBLoadedTLDef::mustBrake(), and NBRequest::NBRequest().
NBEdge * NBConnection::checkFrom (const NBEdgeCont & ec) private
Checks whether the from-edge is still valid.
Definition at line 205 of file NBConnection.cpp.
References myFrom, myFromID, myToID, NBEdgeCont::retrieve(), and NBEdgeCont::retrievePossiblySplit().
Referenced by check().
NBEdge * NBConnection::checkTo (const NBEdgeCont & ec) private
Checks whether the to-edge is still valid.
Definition at line 217 of file NBConnection.cpp.
References myFromID, myTo, myToID, NBEdgeCont::retrieve(), and NBEdgeCont::retrievePossiblySplit().
Referenced by check().
NBEdge * NBConnection::getFrom () const
returns the from-edge (start of the connection)
Definition at line 97 of file NBConnection.cpp.
References myFrom.
Referenced by NBLoadedTLDef::SignalGroup::addConnection(), NBNode::addSortedLinkFoes(), NBLoadedTLDef::addToSignalGroup(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), NBLoadedTLDef::collectNodes(), GNETLSEditorFrame::handleMultiChange(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBTrafficLightDefinition::mustBrake(), NBLoadedTLDef::mustBrake(), NBLoadedTLDef::myCompute(), NIXMLConnectionsHandler::myStartElement(), NBRequest::NBRequest(), NBLoadedSUMOTLDef::connection_equal::operator()(), operator<<(), NWWriter_SUMO::prohibitionConnection(), NBNode::remapRemoved(), NBLoadedSUMOTLDef::removeConnection(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), and NBLoadedTLDef::setTLControllingInformation().
int NBConnection::getFromLane () const
returns the from-lane
Definition at line 237 of file NBConnection.cpp.
References myFromLane.
Referenced by NBLoadedTLDef::SignalGroup::addConnection(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), GNETLSEditorFrame::handleMultiChange(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBLoadedTLDef::myCompute(), NBLoadedSUMOTLDef::connection_equal::operator()(), operator<<(), NBLoadedSUMOTLDef::removeConnection(), and NBEdge::setControllingTLInformation().
std::string NBConnection::getID () const
returns the id of the connection (!!! not really pretty)
Definition at line 229 of file NBConnection.cpp.
References myFromID, myFromLane, myToID, and myToLane.
Referenced by setTLIndex().
int NBConnection::getTLIndex () const inline
Definition at line 101 of file NBConnection.h.
References myTlIndex.
Referenced by NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), GNETLSEditorFrame::handleMultiChange(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBLoadedTLDef::myCompute(), operator<<(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), NBLoadedSUMOTLDef::removeConnection(), NBEdge::setControllingTLInformation(), NBLoadedSUMOTLDef::setTLControllingInformation(), and NBLoadedTLDef::setTLControllingInformation().
NBEdge * NBConnection::getTo () const
returns the to-edge (end of the connection)
Definition at line 103 of file NBConnection.cpp.
References myTo.
Referenced by NBNode::addSortedLinkFoes(), NBLoadedTLDef::addToSignalGroup(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBTrafficLightDefinition::mustBrake(), NBLoadedTLDef::myCompute(), NBRequest::NBRequest(), NBLoadedSUMOTLDef::connection_equal::operator()(), operator<<(), NWWriter_SUMO::prohibitionConnection(), NBNode::remapRemoved(), NBLoadedSUMOTLDef::removeConnection(), and NBEdge::setControllingTLInformation().
int NBConnection::getToLane () const
returns the to-lane
Definition at line 243 of file NBConnection.cpp.
References myToLane.
Referenced by NBLoadedTLDef::collectLinks(), NBLoadedSUMOTLDef::connection_equal::operator()(), operator<<(), NBLoadedSUMOTLDef::removeConnection(), and NBEdge::setControllingTLInformation().
bool NBConnection::operator!= (const NBConnection & c) const inline
Comparison operator.
Definition at line 120 of file NBConnection.h.
References operator<<.
bool NBConnection::operator== (const NBConnection & c) const
Comparison operator.
Definition at line 188 of file NBConnection.cpp.
References myFrom, myFromID, myFromLane, myTlIndex, myTo, myToID, and myToLane.
Referenced by setTLIndex().
bool NBConnection::replaceFrom (NBEdge * which, NBEdge * by)
replaces the from-edge by the one given
Definition at line 109 of file NBConnection.cpp.
References Named::getID(), myFrom, and myFromID.
Referenced by NBLoadedTLDef::SignalGroup::remapIncoming(), and NBNode::replaceInConnectionProhibitions().
bool NBConnection::replaceFrom (NBEdge * which, int whichLane, NBEdge * by, int byLane)
replaces the from-edge by the one given
Definition at line 124 of file NBConnection.cpp.
References Named::getID(), myFrom, myFromID, and myFromLane.
bool NBConnection::replaceTo (NBEdge * which, NBEdge * by)
replaces the to-edge by the one given
Definition at line 141 of file NBConnection.cpp.
References Named::getID(), myTo, and myToID.
Referenced by NBLoadedTLDef::SignalGroup::remapOutgoing(), and NBNode::replaceInConnectionProhibitions().
bool NBConnection::replaceTo (NBEdge * which, int whichLane, NBEdge * by, int byLane)
replaces the to-edge by the one given
Definition at line 156 of file NBConnection.cpp.
References Named::getID(), myFromLane, myTo, myToID, and myToLane.
void NBConnection::setTLIndex (int tlIndex) inline
Definition at line 106 of file NBConnection.h.
References getID(), myTlIndex, operator<, and operator==().
Referenced by NBLoadedTLDef::collectLinks(), and NBLoadedSUMOTLDef::removeConnection().
void NBConnection::shiftLaneIndex (NBEdge * edge, int offset)
patches lane indices refering to the given edge
Definition at line 249 of file NBConnection.cpp.
References myFrom, myFromLane, myTo, and myToLane.
Friends And Related Function Documentation
bool operator< (const NBConnection & c1, const NBConnection & c2) friend
Compares both connections in order to allow sorting.
Definition at line 173 of file NBConnection.cpp.
Referenced by setTLIndex().
std::ostream& operator<< (std::ostream & os, const NBConnection & c) friend
Output operator.
Definition at line 259 of file NBConnection.cpp.
Referenced by operator!=().
Field Documentation
const NBConnection NBConnection::InvalidConnection static
Definition at line 128 of file NBConnection.h.
Referenced by NIVissimDisturbance::getConnection(), GNEConnectorFrame::handleLaneClick(), GNEJunction::invalidateTLS(), NIXMLConnectionsHandler::myStartElement(), and NIXMLConnectionsHandler::parseConnection().
const int NBConnection::InvalidTlIndex = -1 static
Definition at line 127 of file NBConnection.h.
Referenced by NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), NBLoadedSUMOTLDef::initNeedsContRelation(), NBLoadedTLDef::myCompute(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), and NBLoadedTLDef::setTLControllingInformation().
NBEdge* NBConnection::myFrom private
The from- and the to-edges.
Definition at line 139 of file NBConnection.h.
Referenced by check(), checkFrom(), getFrom(), operator==(), replaceFrom(), and shiftLaneIndex().
std::string NBConnection::myFromID private
The names of both edges, needed for verification of validity.
Definition at line 142 of file NBConnection.h.
Referenced by checkFrom(), checkTo(), getID(), NBConnection(), operator<(), operator==(), and replaceFrom().
int NBConnection::myFromLane private
The lanes; may be -1 if no certain lane was specified.
Definition at line 145 of file NBConnection.h.
Referenced by getFromLane(), getID(), operator<(), operator==(), replaceFrom(), replaceTo(), and shiftLaneIndex().
int NBConnection::myTlIndex private
Definition at line 148 of file NBConnection.h.
Referenced by getTLIndex(), operator==(), and setTLIndex().
NBEdge * NBConnection::myTo private
Definition at line 139 of file NBConnection.h.
Referenced by check(), checkTo(), getTo(), operator==(), replaceTo(), and shiftLaneIndex().
std::string NBConnection::myToID private
Definition at line 142 of file NBConnection.h.
Referenced by checkFrom(), checkTo(), getID(), NBConnection(), operator<(), operator==(), and replaceTo().
int NBConnection::myToLane private
Definition at line 145 of file NBConnection.h.
Referenced by getID(), getToLane(), operator<(), operator==(), replaceTo(), and shiftLaneIndex().
The documentation for this class was generated from the following files:
NBConnection.h
NBConnection.cpp