SUMO - Simulation of Urban MObility: MSMeanData::MeanDataValueTracker Class Reference
MSMeanData::MeanDataValueTracker Class Reference
Data structure for mean (aggregated) edge/lane values for tracked vehicles.
#include <MSMeanData.h>
Data Structures
class TrackerEntry
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED
}
Definition of a vehicle state.
Public Member Functions
void addTo (MSMeanData::MeanDataValues &val) const
Add the values of this to the given one and store them there.
void clearFirst ()
const std::string & getDescription () const
const MSLane * getLane () const
Returns the lane the reminder works on.
int getNumReady () const
SUMOReal getSamples () const
Returns the number of collected sample seconds.
bool isEmpty () const
Returns whether any data was collected.
MeanDataValueTracker (MSLane *const lane, const SUMOReal length, const std::set< std::string > *const vTypes=0, const MSMeanData *const parent=0)
Constructor.
bool notifyMove (SUMOVehicle &veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed)
Checks whether the reminder still has to be notified about the vehicle moves.
void reset (bool afterWrite)
Resets values so they may be used for the next interval.
void setDescription (const std::string &description)
virtual void update ()
Called if a per timestep update is needed. Default does nothing.
bool vehicleApplies (const SUMOVehicle &veh) const
Tests whether the vehicles type is to be regarded.
void write (OutputDevice &dev, const SUMOTime period, const SUMOReal numLanes, const SUMOReal defaultTravelTime, const int numVehicles=-1) const
Writes output values into the given stream.
virtual ~MeanDataValueTracker ()
Destructor.
Methods inherited from MSMoveReminder
void notifyMoveInternal (SUMOVehicle &veh, SUMOReal timeOnLane, SUMOReal speed)
Internal notification about the vehicle moves.
bool notifyLeave (SUMOVehicle &veh, SUMOReal lastPos, MSMoveReminder::Notification reason)
Called if the vehicle leaves the reminder's lane.
bool notifyEnter (SUMOVehicle &veh, MSMoveReminder::Notification reason)
Computes current values and adds them to their sums.
Interface methods, to be derived by subclasses
void updateDetector (SUMOVehicle &veh, SUMOReal entryPos, SUMOReal leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp)
Protected Member Functions
void removeFromVehicleUpdateValues (SUMOVehicle &veh)
Protected Attributes
std::string myDescription
a description of this moveReminder
MSLane *const myLane
Lane on which the reminder works.
const SUMOReal myLaneLength
The length of the lane / edge the data collector is on.
const std::set< std::string > *const myVehicleTypes
The vehicle types to look for (0 or empty means all)
Private Attributes
std::list< TrackerEntry * > myCurrentData
The currently active meandata "intervals".
const MSMeanData * myParent
The meandata parent.
std::map< SUMOVehicle *, TrackerEntry * > myTrackedData
The map of vehicles to data entries.
Collected values
The number of sampled vehicle movements (in s)
SUMOReal sampleSeconds
SUMOReal travelledDistance
The sum of the distances the vehicles travelled.
Detailed Description
Data structure for mean (aggregated) edge/lane values for tracked vehicles.
Definition at line 195 of file MSMeanData.h.
Member Enumeration Documentation
enum MSMoveReminder::Notification inherited
Definition of a vehicle state.
Enumerator
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network)
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only)
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only)
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted)
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
Definition at line 95 of file MSMoveReminder.h.
Constructor & Destructor Documentation
MSMeanData::MeanDataValueTracker::MeanDataValueTracker (MSLane *const lane, const SUMOReal length, const std::set< std::string > *const vTypes = 0, const MSMeanData *const parent = 0)
Constructor.
Definition at line 146 of file MSMeanData.cpp.
References MSMeanData::createValues(), and myCurrentData.
MSMeanData::MeanDataValueTracker::~MeanDataValueTracker () virtual
Destructor.
Definition at line 155 of file MSMeanData.cpp.
References myCurrentData.
Member Function Documentation
void MSMeanData::MeanDataValueTracker::addTo (MSMeanData::MeanDataValues & val) const virtual
Add the values of this to the given one and store them there.
Parameters
[in] val The meandata to add to
Implements MSMeanData::MeanDataValues.
Definition at line 184 of file MSMeanData.cpp.
References myCurrentData.
void MSMeanData::MeanDataValueTracker::clearFirst ()
const std::string& MSMoveReminder::getDescription () const inline inherited
Definition at line 213 of file MSMoveReminder.h.
References MSMoveReminder::myDescription, and MSMoveReminder::removeFromVehicleUpdateValues().
Referenced by MSBaseVehicle::addStops().
const MSLane* MSMoveReminder::getLane () const inline inherited
Returns the lane the reminder works on.
Returns
The lane the reminder works on.
Definition at line 89 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by MSDevice_Tripinfo::computeLengthAndDuration(), MSE2Collector::detectorUpdate(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_InductionLoop::getTree(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_ArealDetector::processGet(), and MSMeanData::writeEdge().
int MSMeanData::MeanDataValueTracker::getNumReady () const
Definition at line 242 of file MSMeanData.cpp.
References myCurrentData, and SUMOReal.
SUMOReal MSMeanData::MeanDataValueTracker::getSamples () const virtual
Returns the number of collected sample seconds.
Returns
the number of collected sample seconds
Reimplemented from MSMeanData::MeanDataValues.
Definition at line 256 of file MSMeanData.cpp.
References myCurrentData.
bool MSMeanData::MeanDataValueTracker::isEmpty () const virtual
Returns whether any data was collected.
Returns
whether no data was collected
Reimplemented from MSMeanData::MeanDataValues.
Definition at line 224 of file MSMeanData.cpp.
References myCurrentData.
bool MSMeanData::MeanDataValueTracker::notifyEnter (SUMOVehicle & veh, MSMoveReminder::Notification reason) virtual
Computes current values and adds them to their sums.
The fraction of time the vehicle is on the lane is computed and used as a weight for the vehicle's current values. The "emitted" field is incremented, additionally.
Parameters
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
See also
MSMoveReminder::notifyEnter
Returns
Always true
Reimplemented from MSMeanData::MeanDataValues.
Definition at line 205 of file MSMeanData.cpp.
References myCurrentData, myTrackedData, MSMoveReminder::NOTIFICATION_SEGMENT, and MSMeanData::MeanDataValues::vehicleApplies().
bool MSMeanData::MeanDataValueTracker::notifyLeave (SUMOVehicle & veh, SUMOReal lastPos, MSMoveReminder::Notification reason) virtual
Called if the vehicle leaves the reminder's lane.
Parameters
veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] isArrival whether the vehicle arrived at its destination
[in] isLaneChange whether the vehicle changed from the lane
See also
MSMoveReminder
MSMoveReminder::notifyLeave
Reimplemented from MSMeanData::MeanDataValues.
Definition at line 196 of file MSMeanData.cpp.
References myParent, myTrackedData, and MSMoveReminder::NOTIFICATION_SEGMENT.
bool MSMeanData::MeanDataValues::notifyMove (SUMOVehicle & veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed) virtual inherited
Checks whether the reminder still has to be notified about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] oldPos Position before move.
[in] newPos Position after move with newSpeed.
[in] newSpeed Moving speed.
Returns
True if vehicle hasn't passed the reminder completely.
Reimplemented from MSMoveReminder.
Definition at line 83 of file MSMeanData.cpp.
References Named::getID(), SUMOVehicle::getID(), MSMoveReminder::getLane(), MSVehicleType::getLength(), SUMOVehicle::getVehicleType(), SUMOVehicle::hasArrived(), MSMeanData::MeanDataValues::myLaneLength, MSMoveReminder::notifyMoveInternal(), SUMOReal, TS, and WRITE_ERROR.
void MSMeanData::MeanDataValueTracker::notifyMoveInternal (SUMOVehicle & veh, SUMOReal timeOnLane, SUMOReal speed) virtual
Internal notification about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] timeOnLane time the vehicle spent on the lane.
[in] speed Moving speed.
Reimplemented from MSMoveReminder.
Definition at line 190 of file MSMeanData.cpp.
References myTrackedData.
void MSMoveReminder::removeFromVehicleUpdateValues (SUMOVehicle & veh) protected inherited
Definition at line 94 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues.
Referenced by MSMoveReminder::getDescription(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), and MSMoveReminder::updateDetector().
void MSMeanData::MeanDataValueTracker::reset (bool afterWrite) virtual
Resets values so they may be used for the next interval.
Implements MSMeanData::MeanDataValues.
Definition at line 172 of file MSMeanData.cpp.
References MSMeanData::createValues(), myCurrentData, MSMoveReminder::myLane, MSMeanData::MeanDataValues::myLaneLength, and myParent.
void MSMoveReminder::setDescription (const std::string & description) inline inherited
Definition at line 209 of file MSMoveReminder.h.
References MSMoveReminder::myDescription.
Referenced by MSMeanData::init(), MEInductLoop::MEInductLoop(), METriggeredCalibrator::METriggeredCalibrator(), and MSCalibrator::MSCalibrator().
void MSMeanData::MeanDataValues::update () virtual inherited
Called if a per timestep update is needed. Default does nothing.
Reimplemented in MSMeanData_Harmonoise::MSLaneMeanDataValues.
Definition at line 133 of file MSMeanData.cpp.
References SUMOReal.
void MSMoveReminder::updateDetector (SUMOVehicle & veh, SUMOReal entryPos, SUMOReal leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp) inherited
Definition at line 51 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues, MSMoveReminder::notifyMoveInternal(), MSMoveReminder::removeFromVehicleUpdateValues(), STEPS2TIME, and SUMOReal.
Referenced by MSMoveReminder::notifyLeave(), and MEVehicle::updateDetectorForWriting().
bool MSMeanData::MeanDataValues::vehicleApplies (const SUMOVehicle & veh) const inherited
Tests whether the vehicles type is to be regarded.
Parameters
[in] veh The regarded vehicle
Returns
whether the type of the vehicle is in the set of regarded types
Definition at line 120 of file MSMeanData.cpp.
References MSVehicleType::getID(), SUMOVehicle::getVehicleType(), and MSMeanData::MeanDataValues::myVehicleTypes.
Referenced by MSMeanData::MeanDataValues::notifyEnter(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyEnter(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), notifyEnter(), and MSMeanData_Net::MSLaneMeanDataValues::notifyLeave().
void MSMeanData::MeanDataValueTracker::write (OutputDevice & dev, const SUMOTime period, const SUMOReal numLanes, const SUMOReal defaultTravelTime, const int numVehicles = -1) const virtual
Writes output values into the given stream.
Parameters
[in] dev The output device to write the data into
[in] period Length of the period the data were gathered
[in] numLanes The total number of lanes for which the data was collected
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSMeanData::MeanDataValues.
Definition at line 230 of file MSMeanData.cpp.
References myCurrentData.
Field Documentation
std::list<TrackerEntry*> MSMeanData::MeanDataValueTracker::myCurrentData private
The currently active meandata "intervals".
Definition at line 302 of file MSMeanData.h.
Referenced by addTo(), getNumReady(), getSamples(), isEmpty(), MeanDataValueTracker(), notifyEnter(), reset(), write(), and ~MeanDataValueTracker().
std::string MSMoveReminder::myDescription protected inherited
a description of this moveReminder
Definition at line 225 of file MSMoveReminder.h.
Referenced by MSMoveReminder::getDescription(), and MSMoveReminder::setDescription().
MSLane* const MSMoveReminder::myLane protected inherited
Lane on which the reminder works.
Definition at line 223 of file MSMoveReminder.h.
Referenced by MSE2Collector::detectorUpdate(), MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSMoveReminder::getLane(), MSE2Collector::MSE2Collector(), MSMoveReminder::MSMoveReminder(), MSE2Collector::notifyEnter(), MSE2Collector::notifyMove(), MSE2Collector::by_vehicle_position_sorter::operator()(), and reset().
const SUMOReal MSMeanData::MeanDataValues::myLaneLength protected inherited
The length of the lane / edge the data collector is on.
Definition at line 173 of file MSMeanData.h.
Referenced by MSMeanData::MeanDataValues::notifyMove(), reset(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSMeanData_Harmonoise::MSLaneMeanDataValues::write(), MSMeanData_Amitran::MSLaneMeanDataValues::write(), and MSMeanData_Net::MSLaneMeanDataValues::write().
const MSMeanData* MSMeanData::MeanDataValueTracker::myParent private
The meandata parent.
Definition at line 305 of file MSMeanData.h.
Referenced by notifyLeave(), and reset().
std::map<SUMOVehicle*, TrackerEntry*> MSMeanData::MeanDataValueTracker::myTrackedData private
The map of vehicles to data entries.
Definition at line 299 of file MSMeanData.h.
Referenced by notifyEnter(), notifyLeave(), and notifyMoveInternal().
const std::set<std::string>* const MSMeanData::MeanDataValues::myVehicleTypes protected inherited
The vehicle types to look for (0 or empty means all)
Definition at line 186 of file MSMeanData.h.
Referenced by MSMeanData::MeanDataValues::vehicleApplies(), and MSMeanData_Amitran::MSLaneMeanDataValues::write().
SUMOReal MSMeanData::MeanDataValues::sampleSeconds protected inherited
Definition at line 178 of file MSMeanData.h.
Referenced by MSMeanData_Harmonoise::MSLaneMeanDataValues::addTo(), MSMeanData_Emissions::MSLaneMeanDataValues::addTo(), MSMeanData_Amitran::MSLaneMeanDataValues::addTo(), MSMeanData_Net::MSLaneMeanDataValues::addTo(), MSMeanData::MeanDataValues::getSamples(), MSMeanData_Amitran::MSLaneMeanDataValues::isEmpty(), MSMeanData_Net::MSLaneMeanDataValues::isEmpty(), MSMeanData::MeanDataValues::isEmpty(), MSMeanData_Emissions::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::reset(), MSMeanData_Emissions::MSLaneMeanDataValues::reset(), MSMeanData_Net::MSLaneMeanDataValues::reset(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSMeanData_Harmonoise::MSLaneMeanDataValues::write(), MSMeanData_Amitran::MSLaneMeanDataValues::write(), and MSMeanData_Net::MSLaneMeanDataValues::write().
SUMOReal MSMeanData::MeanDataValues::travelledDistance inherited
The sum of the distances the vehicles travelled.
Definition at line 181 of file MSMeanData.h.
Referenced by MSMeanData_Harmonoise::MSLaneMeanDataValues::addTo(), MSMeanData_Emissions::MSLaneMeanDataValues::addTo(), MSMeanData_Amitran::MSLaneMeanDataValues::addTo(), MSMeanData_Net::MSLaneMeanDataValues::addTo(), MSMeanData_Emissions::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::reset(), MSMeanData_Emissions::MSLaneMeanDataValues::reset(), MSMeanData_Net::MSLaneMeanDataValues::reset(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSMeanData_Amitran::MSLaneMeanDataValues::write(), MSMeanData_Harmonoise::MSLaneMeanDataValues::write(), MSMeanData_Net::MSLaneMeanDataValues::write(), and MSCalibrator::writeXMLOutput().
The documentation for this class was generated from the following files:
MSMeanData.h
MSMeanData.cpp