SUMO - Simulation of Urban MObility: MSRouteHandler Class Reference
MSRouteHandler Class Reference
Parser and container for routes during their loading.
#include <MSRouteHandler.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
SUMOTime getFirstDepart () const
returns the first departure time that was ever read
SUMOTime getLastDepart () const
Returns the last loaded depart time.
MSRouteHandler (const std::string &file, bool addVehiclesDirectly)
standard constructor
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
virtual ~MSRouteHandler ()
standard destructor
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Static Public Member Functions
static bool checkStopPos (SUMOReal &startPos, SUMOReal &endPos, const SUMOReal laneLength, const SUMOReal minLength, const bool friendlyPos)
check start and end position of a stop
static MTRand * getParsingRNG ()
Protected Member Functions
void addParam (const SUMOSAXAttributes &attrs)
assign arbitrary vehicle parameters
void addStop (const SUMOSAXAttributes &attrs)
Processing of a stop.
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
bool checkLastDepart ()
Checks whether the route file is sorted by departure time if needed.
void closeContainer ()
Ends the processing of a container.
void closeFlow ()
Ends the processing of a flow.
void closePerson ()
Ends the processing of a person.
void closeRoute (const bool mayBeDisconnected=false)
void closeRouteDistribution ()
void closeVehicle ()
Ends the processing of a vehicle.
void closeVehicleTypeDistribution ()
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
void openRoute (const SUMOSAXAttributes &attrs)
void openRouteDistribution (const SUMOSAXAttributes &attrs)
void openVehicleTypeDistribution (const SUMOSAXAttributes &attrs)
void parseFromViaTo (std::string element, const SUMOSAXAttributes &attrs)
Called for parsing from and to and the corresponding taz attributes.
bool parseStop (SUMOVehicleParameter::Stop &stop, const SUMOSAXAttributes &attrs, std::string errorSuffix, MsgHandler *const errorOutput)
parses attributes common to all stops
SUMOReal parseWalkPos (SumoXMLAttr attr, const std::string &id, const MSEdge *edge, const std::string &val)
void parseWalkPositions (const SUMOSAXAttributes &attrs, const std::string &personID, const MSEdge *fromEdge, const MSEdge *&toEdge, SUMOReal &departPos, SUMOReal &arrivalPos, MSStoppingPlace *&bs, bool &ok)
@ brief parse depart- and arrival positions of a walk
void registerLastDepart ()
save last depart (only to be used if vehicle is not discarded)
inherited from GenericSAXHandler
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
virtual void myEndElement (int element)
Called when a closing tag occurs.
Protected Attributes
MSTransportable::MSTransportablePlan * myActiveContainerPlan
The plan of the current container.
MSTransportable::MSTransportablePlan * myActivePlan
The plan of the current person.
ConstMSEdgeVector myActiveRoute
The current route.
const RGBColor * myActiveRouteColor
The currently parsed route's color.
std::string myActiveRouteID
The id of the current route.
SUMOReal myActiveRouteProbability
The probability of the current route.
std::string myActiveRouteRefID
The id of the route the current route references to.
std::vector< SUMOVehicleParameter::Stop > myActiveRouteStops
List of the stops on the parsed route.
bool myAddVehiclesDirectly
Information whether vehicles shall be directly added to the network or kept within the buffer.
SUMOTime myBeginDefault
The default value for flow begins.
SUMOReal myCurrentCosts
The currently parsed route costs.
RandomDistributor< const MSRoute * > * myCurrentRouteDistribution
The currently parsed distribution of routes (probability->route)
std::string myCurrentRouteDistributionID
The id of the currently parsed route distribution.
SUMOVTypeParameter * myCurrentVType
The currently parsed vehicle type.
RandomDistributor< MSVehicleType * > * myCurrentVTypeDistribution
The currently parsed distribution of vehicle types (probability->vehicle type)
std::string myCurrentVTypeDistributionID
The id of the currently parsed vehicle type distribution.
SUMOTime myEndDefault
The default value for flow ends.
SUMOTime myFirstDepart
the first read departure time
IDSupplier myIdSupplier
generates numerical ids
int myInsertStopEdgesAt
where stop edges can be inserted into the current route (-1 means no insertion)
SUMOTime myLastDepart
The insertion time of the vehicle read last.
SUMOVehicleParameter * myVehicleParameter
Parameter of the current vehicle, trip, person, container or flow.
Static Protected Attributes
static MTRand myParsingRNG
A random number generator used to choose from vtype/route distributions and computing the speed factors.
Private Member Functions
void deleteActivePlans ()
delete already created MSTransportablePlans if error occurs before handing over responsibility to a MSTransportable.
MSRouteHandler (const MSRouteHandler &s)
Invalidated copy constructor.
MSRouteHandler & operator= (const MSRouteHandler &s)
Invalidated assignment operator.
Detailed Description
Parser and container for routes during their loading.
MSRouteHandler is the container for routes while they are build until their transfering to the MSNet::RouteDict The result of the operations are single MSNet::Route-instances
Definition at line 61 of file MSRouteHandler.h.
Constructor & Destructor Documentation
MSRouteHandler::MSRouteHandler (const std::string & file, bool addVehiclesDirectly)
standard constructor
Definition at line 74 of file MSRouteHandler.cpp.
References myActiveRoute.
MSRouteHandler::~MSRouteHandler () virtual
standard destructor
Definition at line 86 of file MSRouteHandler.cpp.
MSRouteHandler::MSRouteHandler (const MSRouteHandler & s) private
Invalidated copy constructor.
Member Function Documentation
void SUMORouteHandler::addParam (const SUMOSAXAttributes & attrs) protected inherited
assign arbitrary vehicle parameters
Definition at line 249 of file SUMORouteHandler.cpp.
References Parameterised::addParameter(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getString(), SUMOSAXAttributes::hasAttribute(), SUMORouteHandler::myCurrentVType, SUMORouteHandler::myVehicleParameter, SUMO_ATTR_KEY, and SUMO_ATTR_VALUE.
Referenced by SUMORouteHandler::getFirstDepart(), and SUMORouteHandler::myStartElement().
void MSRouteHandler::addStop (const SUMOSAXAttributes & attrs) protected virtual
Processing of a stop.
Implements SUMORouteHandler.
Definition at line 900 of file MSRouteHandler.cpp.
References SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, SUMORouteHandler::checkStopPos(), SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::depart, SUMOVehicleParameter::departPos, MSLane::dictionary(), SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, MSStoppingPlace::getBeginLanePosition(), MSNet::getBusStop(), MSNet::getChargingStation(), MSNet::getContainerStop(), MSLane::getEdge(), MSStoppingPlace::getEndLanePosition(), MsgHandler::getErrorInstance(), Named::getID(), MSNet::getInstance(), MSStoppingPlace::getLane(), MSEdge::getLanes(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, SUMOVehicleParameter::Stop::lane, MAX2(), myActiveContainerPlan, myActivePlan, myActiveRoute, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteStops, SUMORouteHandler::myInsertStopEdgesAt, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::parseStop(), POSITION_EPS, SUMOVehicleParameter::Stop::startPos, SUMOVehicleParameter::stops, SUMO_ATTR_ACTTYPE, SUMO_ATTR_ENDPOS, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_STARTPOS, SUMOReal, SUMOVehicleParameter::Stop::until, WRITE_ERROR, and WRITE_WARNING.
Referenced by getParsingRNG().
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 192 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 175 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
bool SUMORouteHandler::checkLastDepart () protected inherited
Checks whether the route file is sorted by departure time if needed.
Definition at line 78 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, SUMOVehicleParameter::id, SUMORouteHandler::myLastDepart, SUMORouteHandler::myVehicleParameter, and WRITE_WARNING.
Referenced by closeContainer(), closeFlow(), closePerson(), closeVehicle(), and SUMORouteHandler::getFirstDepart().
bool SUMORouteHandler::checkStopPos (SUMOReal & startPos, SUMOReal & endPos, const SUMOReal laneLength, const SUMOReal minLength, const bool friendlyPos) static inherited
check start and end position of a stop
Definition at line 211 of file SUMORouteHandler.cpp.
Referenced by NLTriggerBuilder::addAccess(), addStop(), RORouteHandler::addStop(), NLTriggerBuilder::parseAndBuildChargingStation(), NLTriggerBuilder::parseAndBuildStoppingPlace(), and RONetHandler::parseStoppingPlace().
void MSRouteHandler::closeContainer () protected virtual
Ends the processing of a container.
Implements SUMORouteHandler.
Definition at line 831 of file MSRouteHandler.cpp.
References MSTransportableControl::buildContainer(), SUMORouteHandler::checkLastDepart(), GenericSAXHandler::error(), MSNet::getContainerControl(), MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOVehicleParameter::id, myActiveContainerPlan, myAddVehiclesDirectly, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), and SUMOVehicleParameter::vtypeid.
Referenced by getParsingRNG().
void MSRouteHandler::closeFlow () protected virtual
Ends the processing of a flow.
Implements SUMORouteHandler.
Definition at line 858 of file MSRouteHandler.cpp.
References SUMORouteHandler::checkLastDepart(), closeRoute(), SUMOVehicleParameter::depart, MSRoute::dictionary(), MSNet::getInstance(), OptionsCont::getOptions(), SUMOVehicleParameter::id, SUMORouteHandler::myActiveRouteID, myAddVehiclesDirectly, SUMORouteHandler::myInsertStopEdgesAt, myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), SUMOVehicleParameter::repetitionNumber, SUMOVehicleParameter::repetitionOffset, SUMOVehicleParameter::repetitionProbability, SUMOVehicleParameter::repetitionsDone, SUMOVehicleParameter::routeid, SUMOVehicleParameter::setParameter, string2time(), VEHPARS_FORCE_REROUTE, and SUMOVehicleParameter::vtypeid.
Referenced by getParsingRNG().
void MSRouteHandler::closePerson () protected virtual
Ends the processing of a person.
Implements SUMORouteHandler.
Definition at line 797 of file MSRouteHandler.cpp.
References MSTransportableControl::buildPerson(), SUMORouteHandler::checkLastDepart(), deleteActivePlans(), GenericSAXHandler::error(), MSNet::getInstance(), MSNet::getPersonControl(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOVehicleParameter::id, myActivePlan, myAddVehiclesDirectly, myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), and SUMOVehicleParameter::vtypeid.
Referenced by getParsingRNG().
void MSRouteHandler::closeRoute (const bool mayBeDisconnected = false) protected virtual
closes (ends) the building of a route. Afterwards no edges may be added to it; this method may throw exceptions when a) the route is empty or b) another route with the same id already exists
Implements SUMORouteHandler.
Definition at line 533 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), MSRoute::addReference(), MSRoute::dictionary(), MSEdge::EDGEFUNCTION_DISTRICT, MSNet::getInstance(), MSGlobals::gStateLoaded, SUMOVehicleParameter::id, myActiveRoute, SUMORouteHandler::myActiveRouteColor, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteProbability, SUMORouteHandler::myActiveRouteRefID, SUMORouteHandler::myActiveRouteStops, SUMORouteHandler::myCurrentCosts, myCurrentRouteDistribution, myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMOVehicleParameter::repetitionNumber, and MSRoute::setCosts().
Referenced by closeFlow(), getParsingRNG(), and myEndElement().
void MSRouteHandler::closeRouteDistribution () protected virtual
closes (ends) the building of a distribution
Implements SUMORouteHandler.
Definition at line 650 of file MSRouteHandler.cpp.
References MSRoute::dictionary(), RandomDistributor< T >::getOverallProb(), MSGlobals::gStateLoaded, myCurrentRouteDistribution, myCurrentRouteDistributionID, myParsingRNG, and SUMORouteHandler::myVehicleParameter.
Referenced by getParsingRNG().
void MSRouteHandler::closeVehicle () protected virtual
Ends the processing of a vehicle.
Implements SUMORouteHandler.
Definition at line 672 of file MSRouteHandler.cpp.
References MSInsertionControl::add(), MSRoute::addReference(), MSVehicleControl::addVehicle(), MSVehicleControl::addWaiting(), MSRoute::begin(), MSVehicleControl::buildVehicle(), SUMORouteHandler::checkLastDepart(), DEFAULT_VTYPE_ID, MSVehicleControl::deleteVehicle(), SUMOVehicleParameter::depart, DEPART_CONTAINER_TRIGGERED, DEPART_GIVEN, DEPART_TRIGGERED, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departProcedure, MSRoute::dictionary(), MSGlobals::gCheckRoutes, MSRoute::getEdges(), MSNet::getInsertionControl(), MSNet::getInstance(), MSEdge::getLanes(), OptionsCont::getOptions(), SUMOVehicle::getParameter(), MSVehicleControl::getQuota(), SUMOVehicle::getRoute(), MSVehicleControl::getVehicle(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), MSGlobals::gStateLoaded, MSGlobals::gUseMesoSim, SUMOVehicleParameter::id, SUMORouteHandler::myActiveRouteID, myAddVehiclesDirectly, myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), MSVehicleControl::registerOneWaitingForContainer(), MSVehicleControl::registerOneWaitingForPerson(), MSRoute::release(), SUMOVehicleParameter::routeid, string2time(), toString(), SUMOVehicleParameter::vtypeid, and WRITE_WARNING.
Referenced by getParsingRNG(), and myEndElement().
void MSRouteHandler::closeVehicleTypeDistribution () protected virtual
closes (ends) the building of a distribution
Implements SUMORouteHandler.
Definition at line 434 of file MSRouteHandler.cpp.
References MSNet::getInstance(), RandomDistributor< T >::getOverallProb(), MSGlobals::gStateLoaded, myCurrentVTypeDistribution, and myCurrentVTypeDistributionID.
Referenced by getParsingRNG().
void MSRouteHandler::deleteActivePlans () private
delete already created MSTransportablePlans if error occurs before handing over responsibility to a MSTransportable.
Definition at line 90 of file MSRouteHandler.cpp.
References myActiveContainerPlan, and myActivePlan.
Referenced by closePerson(), and myStartElement().
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 211 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by closeContainer(), closePerson(), NIImporter_OpenDrive::geomFromSpiral(), myStartElement(), and parseWalkPos().
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 217 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), MSStateHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
SUMOTime SUMORouteHandler::getFirstDepart () const inline inherited
returns the first departure time that was ever read
Definition at line 74 of file SUMORouteHandler.h.
References SUMORouteHandler::addParam(), SUMORouteHandler::addStop(), SUMORouteHandler::checkLastDepart(), SUMORouteHandler::closeContainer(), SUMORouteHandler::closeFlow(), SUMORouteHandler::closePerson(), SUMORouteHandler::closeRoute(), SUMORouteHandler::closeRouteDistribution(), SUMORouteHandler::closeVehicle(), SUMORouteHandler::closeVehicleTypeDistribution(), SUMORouteHandler::myEndElement(), SUMORouteHandler::myFirstDepart, SUMORouteHandler::myStartElement(), SUMORouteHandler::openRoute(), SUMORouteHandler::openRouteDistribution(), SUMORouteHandler::openVehicleTypeDistribution(), SUMORouteHandler::parseStop(), and SUMORouteHandler::registerLastDepart().
Referenced by SUMORouteLoader::getFirstDepart().
SUMOTime SUMORouteHandler::getLastDepart () const inherited
Returns the last loaded depart time.
Definition at line 72 of file SUMORouteHandler.cpp.
References SUMORouteHandler::myLastDepart.
Referenced by SUMORouteLoader::loadUntil().
static MTRand* MSRouteHandler::getParsingRNG () inline static
Definition at line 70 of file MSRouteHandler.h.
References addStop(), closeContainer(), closeFlow(), closePerson(), closeRoute(), closeRouteDistribution(), closeVehicle(), closeVehicleTypeDistribution(), myEndElement(), myParsingRNG, myStartElement(), openRoute(), openRouteDistribution(), openVehicleTypeDistribution(), parseFromViaTo(), parseWalkPos(), parseWalkPositions(), and SUMOReal.
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MSVehicleControl::computeRandomDepartOffset(), MSInsertionControl::determineCandidates(), main(), and GUILoadThread::run().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 227 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void MSRouteHandler::myEndElement (int element) protected virtual
Called when a closing tag occurs.
Parameters
[in] element ID of the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myEndElement
Reimplemented from SUMORouteHandler.
Reimplemented in NLHandler, and MSCalibrator.
Definition at line 498 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), MSVehicleType::build(), closeRoute(), closeVehicle(), MSVehicleType::getDefaultProbability(), MSVehicleType::getID(), MSNet::getInstance(), MSGlobals::gStateLoaded, SUMORouteHandler::myCurrentVType, myCurrentVTypeDistribution, SUMORouteHandler::myEndElement(), SUMORouteHandler::myInsertStopEdgesAt, SUMORouteHandler::myVehicleParameter, SUMOVehicleParameter::setParameter, SUMO_TAG_TRIP, SUMO_TAG_VTYPE, and VEHPARS_FORCE_REROUTE.
Referenced by getParsingRNG(), MSCalibrator::myEndElement(), and NLHandler::myEndElement().
void MSRouteHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from SUMORouteHandler.
Reimplemented in NLHandler, and MSCalibrator.
Definition at line 159 of file MSRouteHandler.cpp.
References PedestrianRouter< E, L, N, V, INTERNALROUTER >::compute(), DEFAULT_CONTAINER_TRANSHIP_SPEED, DEFAULT_PEDESTRIAN_SPEED, deleteActivePlans(), SUMOVehicleParameter::depart, SUMOVehicleParameter::departPos, MSEdge::dictionary(), GenericSAXHandler::error(), MSGlobals::gCheckRoutes, SUMOSAXAttributes::get(), MSNet::getBusStop(), MSNet::getContainerStop(), MSNet::getInstance(), MSVehicleType::getMaxSpeed(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), MSNet::getPedestrianRouter(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, myActiveContainerPlan, myActivePlan, myActiveRoute, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myCurrentVType, myParsingRNG, SUMORouteHandler::myStartElement(), SUMORouteHandler::myVehicleParameter, NUMERICAL_EPS, MSEdge::parseEdgesList(), parseFromViaTo(), SUMOVehicleParserHelper::parseVTypeEmbedded(), parseWalkPositions(), SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_BUS_STOP, SUMO_ATTR_CONTAINER_STOP, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DURATION, SUMO_ATTR_EDGES, SUMO_ATTR_FROM, SUMO_ATTR_LINES, SUMO_ATTR_SPEED, SUMO_ATTR_TO, SUMO_TAG_CONTAINER, SUMO_TAG_FLOW, SUMO_TAG_PARAM, SUMO_TAG_PERSON, SUMO_TAG_RIDE, SUMO_TAG_TRANSHIP, SUMO_TAG_TRANSPORT, SUMO_TAG_TRIP, SUMO_TAG_VTYPE, SUMO_TAG_WALK, SUMOReal, SUMOVehicleParameter::vtypeid, VTYPEPARS_MAXSPEED_SET, MSVehicleType::wasSet(), and WRITE_ERROR.
Referenced by getParsingRNG(), MSCalibrator::myStartElement(), and NLHandler::myStartElement().
void MSRouteHandler::openRoute (const SUMOSAXAttributes & attrs) protected virtual
opens a route for reading
Implements SUMORouteHandler.
Definition at line 454 of file MSRouteHandler.cpp.
References DEFAULT_VEH_PROB, MSRoute::dictionary(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), RandomDistributor< T >::getProbs(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, myActiveRoute, SUMORouteHandler::myActiveRouteColor, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteProbability, SUMORouteHandler::myActiveRouteRefID, SUMORouteHandler::myCurrentCosts, myCurrentRouteDistribution, myCurrentRouteDistributionID, SUMORouteHandler::myInsertStopEdgesAt, myParsingRNG, SUMORouteHandler::myVehicleParameter, MSEdge::parseEdgesList(), SUMO_ATTR_COLOR, SUMO_ATTR_COST, SUMO_ATTR_EDGES, SUMO_ATTR_ID, SUMO_ATTR_PROB, SUMO_ATTR_REFID, SUMOReal, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by getParsingRNG().
void MSRouteHandler::openRouteDistribution (const SUMOSAXAttributes & attrs) protected virtual
opens a route distribution for reading
Implements SUMORouteHandler.
Definition at line 603 of file MSRouteHandler.cpp.
References TplConvert::_2SUMORealSec(), RandomDistributor< T >::add(), MSRoute::addReference(), MSRoute::dictionary(), SUMOSAXAttributes::get(), SUMOSAXAttributes::hasAttribute(), StringTokenizer::hasNext(), SUMOVehicleParameter::id, myCurrentRouteDistribution, myCurrentRouteDistributionID, myParsingRNG, SUMORouteHandler::myVehicleParameter, StringTokenizer::next(), SUMO_ATTR_ID, SUMO_ATTR_PROBS, SUMO_ATTR_ROUTES, SUMOReal, toString(), and WRITE_WARNING.
Referenced by getParsingRNG().
void MSRouteHandler::openVehicleTypeDistribution (const SUMOSAXAttributes & attrs) protected virtual
opens a type distribution for reading
Implements SUMORouteHandler.
Definition at line 412 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), SUMOSAXAttributes::get(), MSVehicleType::getDefaultProbability(), MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOSAXAttributes::hasAttribute(), myCurrentVTypeDistribution, myCurrentVTypeDistributionID, myParsingRNG, SUMO_ATTR_ID, and SUMO_ATTR_VTYPES.
Referenced by getParsingRNG().
MSRouteHandler& MSRouteHandler::operator= (const MSRouteHandler & s) private
Invalidated assignment operator.
void MSRouteHandler::parseFromViaTo (std::string element, const SUMOSAXAttributes & attrs) protected
Called for parsing from and to and the corresponding taz attributes.
Parameters
[in] element description of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
Definition at line 110 of file MSRouteHandler.cpp.
References MSEdge::dictionary(), SUMOVehicleParameter::fromTaz, OptionsCont::getBool(), MSEdge::getNumPredecessors(), MSEdge::getNumSuccessors(), SUMOSAXAttributes::getOpt(), OptionsCont::getOptions(), StringTokenizer::getVector(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, myActiveRoute, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myInsertStopEdgesAt, SUMORouteHandler::myVehicleParameter, MSEdge::parseEdgesList(), SUMOVehicleParameter::routeid, SUMO_ATTR_FROM, SUMO_ATTR_ROUTE, SUMO_ATTR_TO, SUMO_ATTR_VIA, SUMOVehicleParameter::toTaz, VEHPARS_FROM_TAZ_SET, VEHPARS_TO_TAZ_SET, SUMOVehicleParameter::via, SUMOVehicleParameter::wasSet(), and WRITE_WARNING.
Referenced by getParsingRNG(), and myStartElement().
bool SUMORouteHandler::parseStop (SUMOVehicleParameter::Stop & stop, const SUMOSAXAttributes & attrs, std::string errorSuffix, MsgHandler *const errorOutput) protected inherited
parses attributes common to all stops
Definition at line 263 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::Stop::awaitedContainers, SUMOVehicleParameter::Stop::awaitedPersons, SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::Stop::index, MsgHandler::inform(), SUMOVehicleParameter::Stop::lane, SUMOVehicleParameter::Stop::parking, SUMOSAXAttributes::parseStringSet(), SUMOVehicleParameter::Stop::setParameter, STOP_CONTAINER_TRIGGER_SET, STOP_END_SET, STOP_EXPECTED_CONTAINERS_SET, STOP_EXPECTED_SET, STOP_INDEX_END, STOP_INDEX_FIT, STOP_PARKING_SET, STOP_START_SET, STOP_TRIGGER_SET, SUMO_ATTR_BUS_STOP, SUMO_ATTR_CHARGING_STATION, SUMO_ATTR_CONTAINER_STOP, SUMO_ATTR_CONTAINER_TRIGGERED, SUMO_ATTR_DURATION, SUMO_ATTR_ENDPOS, SUMO_ATTR_EXPECTED, SUMO_ATTR_EXPECTED_CONTAINERS, SUMO_ATTR_INDEX, SUMO_ATTR_PARKING, SUMO_ATTR_STARTPOS, SUMO_ATTR_TRIGGERED, SUMO_ATTR_UNTIL, SUMOVehicleParameter::Stop::triggered, and SUMOVehicleParameter::Stop::until.
Referenced by addStop(), RORouteHandler::addStop(), and SUMORouteHandler::getFirstDepart().
SUMOReal MSRouteHandler::parseWalkPos (SumoXMLAttr attr, const std::string & id, const MSEdge * edge, const std::string & val) protected
Definition at line 1085 of file MSRouteHandler.cpp.
References ARRIVAL_POS_MAX, ARRIVAL_POS_RANDOM, GenericSAXHandler::error(), MSEdge::getLength(), SUMOVehicleParameter::interpretEdgePos(), myParsingRNG, SUMOVehicleParameter::parseArrivalPos(), MTRand::rand(), SUMO_TAG_WALK, SUMOReal, and toString().
Referenced by getParsingRNG(), and parseWalkPositions().
void MSRouteHandler::parseWalkPositions (const SUMOSAXAttributes & attrs, const std::string & personID, const MSEdge * fromEdge, const MSEdge *& toEdge, SUMOReal & departPos, SUMOReal & arrivalPos, MSStoppingPlace *& bs, bool & ok) protected
@ brief parse depart- and arrival positions of a walk
Definition at line 1039 of file MSRouteHandler.cpp.
References SUMOSAXAttributes::get(), MSStoppingPlace::getBeginLanePosition(), MSNet::getBusStop(), MSLane::getEdge(), MSStoppingPlace::getEndLanePosition(), Named::getID(), MSNet::getInstance(), MSStoppingPlace::getLane(), SUMOSAXAttributes::getOpt(), MSStoppingPlace::hasAccess(), SUMOSAXAttributes::hasAttribute(), NUMERICAL_EPS, parseWalkPos(), SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_BUS_STOP, SUMO_ATTR_DEPARTPOS, SUMOReal, toString(), and WRITE_WARNING.
Referenced by getParsingRNG(), and myStartElement().
void SUMORouteHandler::registerLastDepart () protected inherited
save last depart (only to be used if vehicle is not discarded)
Definition at line 90 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, SUMOVehicleParameter::line, SUMORouteHandler::myFirstDepart, SUMORouteHandler::myLastDepart, and SUMORouteHandler::myVehicleParameter.
Referenced by closeContainer(), RORouteHandler::closeContainer(), closeFlow(), RORouteHandler::closeFlow(), closePerson(), RORouteHandler::closePerson(), closeVehicle(), RORouteHandler::closeVehicle(), and SUMORouteHandler::getFirstDepart().
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 167 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 205 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
MSTransportable::MSTransportablePlan* MSRouteHandler::myActiveContainerPlan protected
The plan of the current container.
Definition at line 160 of file MSRouteHandler.h.
Referenced by addStop(), closeContainer(), deleteActivePlans(), and myStartElement().
MSTransportable::MSTransportablePlan* MSRouteHandler::myActivePlan protected
The plan of the current person.
Definition at line 157 of file MSRouteHandler.h.
Referenced by addStop(), closePerson(), deleteActivePlans(), and myStartElement().
ConstMSEdgeVector MSRouteHandler::myActiveRoute protected
The current route.
Definition at line 154 of file MSRouteHandler.h.
Referenced by addStop(), closeRoute(), MSRouteHandler(), myStartElement(), openRoute(), and parseFromViaTo().
const RGBColor* SUMORouteHandler::myActiveRouteColor protected inherited
The currently parsed route's color.
Definition at line 169 of file SUMORouteHandler.h.
Referenced by closeRoute(), RORouteHandler::closeRoute(), openRoute(), and RORouteHandler::openRoute().
std::string SUMORouteHandler::myActiveRouteID protected inherited
The id of the current route.
Definition at line 160 of file SUMORouteHandler.h.
Referenced by addStop(), RORouteHandler::addStop(), closeFlow(), RORouteHandler::closeFlow(), closeRoute(), RORouteHandler::closeRoute(), closeVehicle(), myStartElement(), SUMORouteHandler::myStartElement(), openRoute(), RORouteHandler::openRoute(), parseFromViaTo(), and RORouteHandler::parseFromViaTo().
SUMOReal SUMORouteHandler::myActiveRouteProbability protected inherited
The probability of the current route.
Definition at line 166 of file SUMORouteHandler.h.
Referenced by closeRoute(), RORouteHandler::closeRoute(), RORouteHandler::myStartElement(), openRoute(), and RORouteHandler::openRoute().
std::string SUMORouteHandler::myActiveRouteRefID protected inherited
The id of the route the current route references to.
Definition at line 163 of file SUMORouteHandler.h.
Referenced by closeRoute(), RORouteHandler::closeRoute(), openRoute(), and RORouteHandler::openRoute().
std::vector<SUMOVehicleParameter::Stop> SUMORouteHandler::myActiveRouteStops protected inherited
List of the stops on the parsed route.
Definition at line 175 of file SUMORouteHandler.h.
Referenced by addStop(), RORouteHandler::addStop(), closeRoute(), and RORouteHandler::closeRoute().
bool MSRouteHandler::myAddVehiclesDirectly protected
Information whether vehicles shall be directly added to the network or kept within the buffer.
Definition at line 163 of file MSRouteHandler.h.
Referenced by closeContainer(), closeFlow(), closePerson(), and closeVehicle().
SUMOTime SUMORouteHandler::myBeginDefault protected inherited
The default value for flow begins.
Definition at line 184 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myEndElement(), and SUMORouteHandler::myStartElement().
SUMOReal SUMORouteHandler::myCurrentCosts protected inherited
The currently parsed route costs.
Definition at line 172 of file SUMORouteHandler.h.
Referenced by closeRoute(), RORouteHandler::closeRoute(), openRoute(), and RORouteHandler::openRoute().
RandomDistributor<const MSRoute*>* MSRouteHandler::myCurrentRouteDistribution protected
The currently parsed distribution of routes (probability->route)
Definition at line 172 of file MSRouteHandler.h.
Referenced by closeRoute(), closeRouteDistribution(), openRoute(), and openRouteDistribution().
std::string MSRouteHandler::myCurrentRouteDistributionID protected
The id of the currently parsed route distribution.
Definition at line 175 of file MSRouteHandler.h.
Referenced by closeRouteDistribution(), openRoute(), and openRouteDistribution().
SUMOVTypeParameter* SUMORouteHandler::myCurrentVType protected inherited
The currently parsed vehicle type.
Definition at line 178 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::addParam(), myEndElement(), RORouteHandler::myEndElement(), SUMORouteHandler::myEndElement(), myStartElement(), RORouteHandler::myStartElement(), SUMORouteHandler::myStartElement(), and SUMORouteHandler::~SUMORouteHandler().
RandomDistributor<MSVehicleType*>* MSRouteHandler::myCurrentVTypeDistribution protected
The currently parsed distribution of vehicle types (probability->vehicle type)
Definition at line 166 of file MSRouteHandler.h.
Referenced by closeVehicleTypeDistribution(), myEndElement(), and openVehicleTypeDistribution().
std::string MSRouteHandler::myCurrentVTypeDistributionID protected
The id of the currently parsed vehicle type distribution.
Definition at line 169 of file MSRouteHandler.h.
Referenced by closeVehicleTypeDistribution(), and openVehicleTypeDistribution().
SUMOTime SUMORouteHandler::myEndDefault protected inherited
The default value for flow ends.
Definition at line 187 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myEndElement(), and SUMORouteHandler::myStartElement().
SUMOTime SUMORouteHandler::myFirstDepart protected inherited
the first read departure time
Definition at line 190 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::getFirstDepart(), and SUMORouteHandler::registerLastDepart().
IDSupplier SUMORouteHandler::myIdSupplier protected inherited
generates numerical ids
Definition at line 181 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myStartElement().
int SUMORouteHandler::myInsertStopEdgesAt protected inherited
where stop edges can be inserted into the current route (-1 means no insertion)
Definition at line 193 of file SUMORouteHandler.h.
Referenced by addStop(), RORouteHandler::addStop(), closeFlow(), RORouteHandler::closeFlow(), myEndElement(), RORouteHandler::myEndElement(), openRoute(), RORouteHandler::openRoute(), parseFromViaTo(), and RORouteHandler::parseFromViaTo().
SUMOTime SUMORouteHandler::myLastDepart protected inherited
The insertion time of the vehicle read last.
Definition at line 157 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::checkLastDepart(), SUMORouteHandler::getLastDepart(), and SUMORouteHandler::registerLastDepart().
MTRand MSRouteHandler::myParsingRNG static protected
A random number generator used to choose from vtype/route distributions and computing the speed factors.
Definition at line 178 of file MSRouteHandler.h.
Referenced by closeFlow(), closePerson(), closeRoute(), closeRouteDistribution(), closeVehicle(), getParsingRNG(), myStartElement(), openRoute(), openRouteDistribution(), openVehicleTypeDistribution(), and parseWalkPos().
SUMOVehicleParameter* SUMORouteHandler::myVehicleParameter protected inherited
Parameter of the current vehicle, trip, person, container or flow.
Definition at line 154 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::addParam(), RORouteHandler::addPersonTrip(), addStop(), RORouteHandler::addStop(), SUMORouteHandler::checkLastDepart(), closeContainer(), RORouteHandler::closeContainer(), closeFlow(), RORouteHandler::closeFlow(), closePerson(), RORouteHandler::closePerson(), closeRoute(), RORouteHandler::closeRoute(), closeRouteDistribution(), closeVehicle(), RORouteHandler::closeVehicle(), myEndElement(), RORouteHandler::myEndElement(), SUMORouteHandler::myEndElement(), myStartElement(), RORouteHandler::myStartElement(), SUMORouteHandler::myStartElement(), openRoute(), RORouteHandler::openRoute(), openRouteDistribution(), RORouteHandler::openRouteDistribution(), parseFromViaTo(), RORouteHandler::parseFromViaTo(), and SUMORouteHandler::registerLastDepart().
The documentation for this class was generated from the following files:
MSRouteHandler.h
MSRouteHandler.cpp