SUMO - Simulation of Urban MObility: NIVissimSingleTypeParser_Knotendefinition Class Reference
NIVissimSingleTypeParser_Knotendefinition Class Reference
#include <NIVissimSingleTypeParser_Knotendefinition.h>
Public Member Functions
NIVissimSingleTypeParser_Knotendefinition (NIImporter_Vissim &parent)
Constructor.
bool parse (std::istream &from)
Parses the data type from the given stream.
~NIVissimSingleTypeParser_Knotendefinition ()
Destructor.
Protected Member Functions
Position getPosition (std::istream &from)
returns the 2d-position saved as next within the stream
std::string myRead (std::istream &from)
reads from the stream and returns the lower case version of the read value
std::string overrideOptionalLabel (std::istream &from, const std::string &tag="")
overrides the optional label definition; returns the next tag as done by readEndSecure
std::vector< int > parseAssignedVehicleTypes (std::istream &from, const std::string &next)
parses a listof vehicle types assigned to the current data field One should remeber, that -1 means "all" vehicle types
std::string readEndSecure (std::istream &from, const std::string &excl="")
as myRead, but returns "DATAEND" when the current field has ended
std::string readEndSecure (std::istream &from, const std::vector< std::string > &excl)
NIVissimExtendedEdgePoint readExtEdgePointDef (std::istream &from)
std::string readName (std::istream &from)
Reads the structures name We cannot use the "<<" operator, as names may contain more than one word which are joined using '"'.
void readUntil (std::istream &from, const std::string &name)
Reads from the stream until the keywor occurs.
bool skipOverreading (std::istream &from, const std::string &name="")
Overreads the named parameter (if) given and skips the rest until "DATAEND".
Detailed Description
Definition at line 44 of file NIVissimSingleTypeParser_Knotendefinition.h.
Constructor & Destructor Documentation
NIVissimSingleTypeParser_Knotendefinition::NIVissimSingleTypeParser_Knotendefinition (NIImporter_Vissim & parent)
Constructor.
Definition at line 52 of file NIVissimSingleTypeParser_Knotendefinition.cpp.
NIVissimSingleTypeParser_Knotendefinition::~NIVissimSingleTypeParser_Knotendefinition ()
Destructor.
Definition at line 56 of file NIVissimSingleTypeParser_Knotendefinition.cpp.
Member Function Documentation
Position NIImporter_Vissim::VissimSingleTypeParser::getPosition (std::istream & from) protected inherited
returns the 2d-position saved as next within the stream
Definition at line 780 of file NIImporter_Vissim.cpp.
References SUMOReal.
Referenced by parse(), and NIVissimSingleTypeParser_Streckendefinition::parse().
std::string NIImporter_Vissim::VissimSingleTypeParser::myRead (std::istream & from) protected inherited
reads from the stream and returns the lower case version of the read value
Definition at line 702 of file NIImporter_Vissim.cpp.
References StringUtils::to_lower_case().
Referenced by NIImporter_Vissim::VissimSingleTypeParser::overrideOptionalLabel(), NIVissimSingleTypeParser_Auswertungsdefinition::parse(), NIVissimSingleTypeParser_Parkplatzdefinition::parse(), NIVissimSingleTypeParser_Zusammensetzungsdefinition::parse(), NIVissimSingleTypeParser_Reisezeitmessungsdefinition::parse(), NIVissimSingleTypeParser_Detektordefinition::parse(), NIVissimSingleTypeParser_Signalgeberdefinition::parse(), NIVissimSingleTypeParser_Haltestellendefinition::parse(), NIVissimSingleTypeParser_Zuflussdefinition::parse(), NIVissimSingleTypeParser_Signalgruppendefinition::parse(), parse(), NIVissimSingleTypeParser_Langsamfahrbereichdefinition::parse(), NIVissimSingleTypeParser_Streckendefinition::parse(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parse(), NIVissimSingleTypeParser_VWunschentscheidungsdefinition::parse(), NIVissimSingleTypeParser_Verlustzeitmessungsdefinition::parse(), NIVissimSingleTypeParser_Querschnittsmessungsdefinition::parse(), NIVissimSingleTypeParser_Verkehrszusammensetzungsdefinition::parse(), NIVissimSingleTypeParser_Fensterdefinition::parse(), NIVissimSingleTypeParser_Routenentscheidungsdefinition::parse(), NIVissimSingleTypeParser_Verbindungsdefinition::parse(), NIVissimSingleTypeParser_Fahrzeugklassendefinition::parse(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parse(), NIVissimSingleTypeParser_Fahrzeugtypdefinition::parse(), NIVissimSingleTypeParser_Signalgruppendefinition::parseFixedTime(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parseNumbered(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parsePositionDescribed(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parseRestActuated(), NIVissimSingleTypeParser_Signalgruppendefinition::parseVAS(), NIImporter_Vissim::VissimSingleTypeParser::readEndSecure(), NIImporter_Vissim::VissimSingleTypeParser::readUntil(), and NIImporter_Vissim::VissimSingleTypeParser::skipOverreading().
std::string NIImporter_Vissim::VissimSingleTypeParser::overrideOptionalLabel (std::istream & from, const std::string & tag = "") protected inherited
overrides the optional label definition; returns the next tag as done by readEndSecure
Definition at line 759 of file NIImporter_Vissim.cpp.
References NIImporter_Vissim::VissimSingleTypeParser::myRead().
Referenced by parse(), NIVissimSingleTypeParser_Zuflussdefinition::parse(), NIVissimSingleTypeParser_Streckendefinition::parse(), NIVissimSingleTypeParser_Signalgeberdefinition::parse(), NIVissimSingleTypeParser_VWunschentscheidungsdefinition::parse(), and NIVissimSingleTypeParser_Verbindungsdefinition::parse().
bool NIVissimSingleTypeParser_Knotendefinition::parse (std::istream & from) virtual
Parses the data type from the given stream.
Implements NIImporter_Vissim::VissimSingleTypeParser.
Definition at line 60 of file NIVissimSingleTypeParser_Knotendefinition.cpp.
References TplConvert::_2int(), PositionVector::closePolygon(), NIVissimNodeDef_Poly::dictionary(), NIVissimNodeDef_Edges::dictionary(), NIImporter_Vissim::VissimSingleTypeParser::getPosition(), NIImporter_Vissim::VissimSingleTypeParser::myRead(), NIImporter_Vissim::VissimSingleTypeParser::overrideOptionalLabel(), NIImporter_Vissim::VissimSingleTypeParser::readEndSecure(), NIImporter_Vissim::VissimSingleTypeParser::readName(), and SUMOReal.
std::vector< int > NIImporter_Vissim::VissimSingleTypeParser::parseAssignedVehicleTypes (std::istream & from, const std::string & next) protected inherited
parses a listof vehicle types assigned to the current data field One should remeber, that -1 means "all" vehicle types
Definition at line 789 of file NIImporter_Vissim.cpp.
References TplConvert::_2int(), and NIImporter_Vissim::VissimSingleTypeParser::readEndSecure().
Referenced by NIVissimSingleTypeParser_Signalgeberdefinition::parse().
std::string NIImporter_Vissim::VissimSingleTypeParser::readEndSecure (std::istream & from, const std::string & excl = "") protected inherited
as myRead, but returns "DATAEND" when the current field has ended
Definition at line 711 of file NIImporter_Vissim.cpp.
References NIImporter_Vissim::admitContinue(), NIImporter_Vissim::VissimSingleTypeParser::myRead(), NIImporter_Vissim::VissimSingleTypeParser::myVissimParent, and StringUtils::to_lower_case().
Referenced by NIVissimSingleTypeParser_Auswertungsdefinition::parse(), NIVissimSingleTypeParser_Zusammensetzungsdefinition::parse(), NIVissimSingleTypeParser_Haltestellendefinition::parse(), NIVissimSingleTypeParser_Zeitenverteilungsdefinition::parse(), NIVissimSingleTypeParser_DynUml::parse(), NIVissimSingleTypeParser_Verkehrszusammensetzungsdefinition::parse(), NIVissimSingleTypeParser_Zuflussdefinition::parse(), parse(), NIVissimSingleTypeParser_Streckendefinition::parse(), NIVissimSingleTypeParser_Laengenverteilungsdefinition::parse(), NIVissimSingleTypeParser_Querschnittsmessungsdefinition::parse(), NIVissimSingleTypeParser_Kantensperrung::parse(), NIVissimSingleTypeParser_Geschwindigkeitsverteilungsdefinition::parse(), NIVissimSingleTypeParser_VWunschentscheidungsdefinition::parse(), NIVissimSingleTypeParser_Routenentscheidungsdefinition::parse(), NIVissimSingleTypeParser_Detektordefinition::parse(), NIVissimSingleTypeParser_Reisezeitmessungsdefinition::parse(), NIVissimSingleTypeParser_Verlustzeitmessungsdefinition::parse(), NIVissimSingleTypeParser_Stopschilddefinition::parse(), NIVissimSingleTypeParser_Fahrzeugklassendefinition::parse(), NIVissimSingleTypeParser_Fahrzeugtypdefinition::parse(), NIVissimSingleTypeParser_Verbindungsdefinition::parse(), NIImporter_Vissim::VissimSingleTypeParser::parseAssignedVehicleTypes(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parseFixedTime(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parseNumbered(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parsePos(), NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parsePositionDescribed(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parseRestActuated(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parseVAS(), NIImporter_Vissim::VissimSingleTypeParser::readExtEdgePointDef(), and NIImporter_Vissim::VissimSingleTypeParser::skipOverreading().
std::string NIImporter_Vissim::VissimSingleTypeParser::readEndSecure (std::istream & from, const std::vector< std::string > & excl) protected inherited
Definition at line 729 of file NIImporter_Vissim.cpp.
References NIImporter_Vissim::admitContinue(), NIImporter_Vissim::VissimSingleTypeParser::myRead(), NIImporter_Vissim::VissimSingleTypeParser::myVissimParent, and StringUtils::to_lower_case().
NIVissimExtendedEdgePoint NIImporter_Vissim::VissimSingleTypeParser::readExtEdgePointDef (std::istream & from) protected inherited
Definition at line 806 of file NIImporter_Vissim.cpp.
References TplConvert::_2int(), NIImporter_Vissim::VissimSingleTypeParser::readEndSecure(), and SUMOReal.
Referenced by NIVissimSingleTypeParser_Verbindungsdefinition::parse().
std::string NIImporter_Vissim::VissimSingleTypeParser::readName (std::istream & from) protected inherited
Reads the structures name We cannot use the "<<" operator, as names may contain more than one word which are joined using '"'.
Definition at line 829 of file NIImporter_Vissim.cpp.
References StringUtils::convertUmlaute().
Referenced by NIVissimSingleTypeParser_Geschwindigkeitsverteilungsdefinition::parse(), NIVissimSingleTypeParser_Zuflussdefinition::parse(), NIVissimSingleTypeParser_Signalgeberdefinition::parse(), NIVissimSingleTypeParser_Parkplatzdefinition::parse(), NIVissimSingleTypeParser_Verkehrszusammensetzungsdefinition::parse(), parse(), NIVissimSingleTypeParser_VWunschentscheidungsdefinition::parse(), NIVissimSingleTypeParser_Kennungszeile::parse(), NIVissimSingleTypeParser_Signalgruppendefinition::parse(), NIVissimSingleTypeParser_Streckendefinition::parse(), NIVissimSingleTypeParser_Verbindungsdefinition::parse(), NIVissimSingleTypeParser_Lichtsignalanlagendefinition::parse(), NIVissimSingleTypeParser_Fahrzeugklassendefinition::parse(), NIVissimSingleTypeParser_Fahrzeugtypdefinition::parse(), and NIVissimSingleTypeParser_Querverkehrsstoerungsdefinition::parseNumbered().
void NIImporter_Vissim::VissimSingleTypeParser::readUntil (std::istream & from, const std::string & name) protected inherited
Reads from the stream until the keywor occurs.
Definition at line 845 of file NIImporter_Vissim.cpp.
References NIImporter_Vissim::VissimSingleTypeParser::myRead().
Referenced by NIVissimSingleTypeParser_DynUml::parse(), NIVissimSingleTypeParser_Fahrverhaltendefinition::parse(), NIVissimSingleTypeParser_Fensterdefinition::parse(), NIVissimSingleTypeParser_Langsamfahrbereichdefinition::parse(), NIVissimSingleTypeParser_Parkplatzdefinition::parse(), NIVissimSingleTypeParser_Stopschilddefinition::parse(), and NIVissimSingleTypeParser_Streckentypdefinition::parse().
bool NIImporter_Vissim::VissimSingleTypeParser::skipOverreading (std::istream & from, const std::string & name = "") protected inherited
Overreads the named parameter (if) given and skips the rest until "DATAEND".
Definition at line 854 of file NIImporter_Vissim.cpp.
References NIImporter_Vissim::VissimSingleTypeParser::myRead(), and NIImporter_Vissim::VissimSingleTypeParser::readEndSecure().
Referenced by NIVissimSingleTypeParser_Messungsdefinition::parse(), NIVissimSingleTypeParser_Richtungsentscheidungsdefinition::parse(), and NIVissimSingleTypeParser_Stauzaehlerdefinition::parse().
The documentation for this class was generated from the following files:
NIVissimSingleTypeParser_Knotendefinition.h
NIVissimSingleTypeParser_Knotendefinition.cpp