SUMO - Simulation of Urban MObility: NIImporter_Vissim Class Reference
NIImporter_Vissim Class Reference
Importer for networks stored in Vissim format.
#include <NIImporter_Vissim.h>
Data Structures
class NIVissimXMLHandler_ConflictArea
class NIVissimXMLHandler_Fahrzeugklassendefinition
class NIVissimXMLHandler_Geschwindigkeitsverteilungsdefinition
class NIVissimXMLHandler_Parkplatzdefinition
class NIVissimXMLHandler_Routenentscheidungsdefinition
A class which extracts VISSIM-Routes from a parsed VISSIM-file.
class NIVissimXMLHandler_Streckendefinition
class NIVissimXMLHandler_VWunschentscheidungsdefinition
class NIVissimXMLHandler_Zuflussdefinition
class VissimSingleTypeParser
Public Types
typedef std::map< std::string, RGBColor > ColorMap
definition of a map from color names to color definitions
Static Public Member Functions
static void loadNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Loads network definition from the assigned option and stores it in the given network builder.
Protected Member Functions
bool admitContinue (const std::string &tag)
void load (const OptionsCont &options)
loads the vissim file
void loadXML (const OptionsCont &options, NBNetBuilder &nb)
NIImporter_Vissim (NBNetBuilder &nb, const std::string &file)
constructor
~NIImporter_Vissim ()
destructor
Private Types
typedef std::map< std::string, std::list< std::string > > nodeMap
typedef std::map< std::string, NIVissimElement > ToElemIDMap
Definition of a map from element names to their numerical representation.
typedef std::map< NIVissimElement, VissimSingleTypeParser * > ToParserMap
Definition of a map from an element's numerical id to his parser.
enum VissimXMLAttr {
VISSIM_ATTR_NOTHING = 0, VISSIM_ATTR_NO, VISSIM_ATTR_NAME, VISSIM_ATTR_X,
VISSIM_ATTR_Y, VISSIM_ATTR_ZOFFSET, VISSIM_ATTR_ZUSCHLAG1, VISSIM_ATTR_ZUSCHLAG2,
VISSIM_ATTR_WIDTH, VISSIM_ATTR_LINKBEHAVETYPE, VISSIM_ATTR_LANE, VISSIM_ATTR_POS,
VISSIM_ATTR_LINK, VISSIM_ATTR_INTLINK, VISSIM_ATTR_PERCENTAGE, VISSIM_ATTR_DISTRICT,
VISSIM_ATTR_COLOR, VISSIM_ATTR_KEY, VISSIM_ATTR_FX, VISSIM_ATTR_DESTLINK,
VISSIM_ATTR_DESTPOS, VISSIM_ATTR_LINK1, VISSIM_ATTR_LINK2, VISSIM_ATTR_STATUS
}
Numbers representing VISSIM-XML - attributes.
enum VissimXMLTag {
VISSIM_TAG_NOTHING = 0, VISSIM_TAG_NETWORK, VISSIM_TAG_LANES, VISSIM_TAG_LANE,
VISSIM_TAG_LINK, VISSIM_TAG_LINKS, VISSIM_TAG_POINTS3D, VISSIM_TAG_POINT3D,
VISSIM_TAG_FROM, VISSIM_TAG_TO, VISSIM_TAG_VEHICLE_INPUT, VISSIM_TAG_PARKINGLOT,
VISSIM_TAG_VEHICLE_CLASS, VISSIM_TAG_INTOBJECTREF, VISSIM_TAG_SPEED_DECISION, VISSIM_TAG_SPEED_DIST,
VISSIM_TAG_DATAPOINT, VISSIM_TAG_DECISION_STATIC, VISSIM_TAG_ROUTE_STATIC, VISSIM_TAG_CA
}
Numbers representing VISSIM-XML - element names.
Private Member Functions
void buildParsers ()
adds id-to-parser - relationships of elements to parse into myParsers
void insertKnownElements ()
adds name-to-id - relationships of known elements into myKnownElements
NIImporter_Vissim (const NIImporter_Vissim &)
Invalidated copy constructor.
NIImporter_Vissim & operator= (const NIImporter_Vissim &)
Invalidated assignment operator.
void postLoadBuild (SUMOReal offset)
bool readContents (std::istream &strm)
Private Attributes
nodeMap elementData
ColorMap myColorMap
a map from color names to color definitions
bool myInputIsLegacyFormat
ToElemIDMap myKnownElements
Map from element names to their numerical representation.
std::string myLastSecure
NBNetBuilder & myNetBuilder
ToParserMap myParsers
Parsers by element id.
Static Private Attributes
static StringBijection< int >::Entry vissimAttrs []
The names of VISSIM-XML attributes (for passing to GenericSAXHandler)
static StringBijection< int >::Entry vissimTags []
The names of VISSIM-XML elements (for passing to GenericSAXHandler)
Detailed Description
Importer for networks stored in Vissim format.
Definition at line 66 of file NIImporter_Vissim.h.
Member Typedef Documentation
typedef std::map<std::string, RGBColor> NIImporter_Vissim::ColorMap
definition of a map from color names to color definitions
Definition at line 557 of file NIImporter_Vissim.h.
typedef std::map<std::string, std::list<std::string> > NIImporter_Vissim::nodeMap private
Definition at line 85 of file NIImporter_Vissim.h.
typedef std::map<std::string, NIVissimElement> NIImporter_Vissim::ToElemIDMap private
Definition of a map from element names to their numerical representation.
Definition at line 572 of file NIImporter_Vissim.h.
typedef std::map<NIVissimElement, VissimSingleTypeParser*> NIImporter_Vissim::ToParserMap private
Definition of a map from an element's numerical id to his parser.
Definition at line 578 of file NIImporter_Vissim.h.
Member Enumeration Documentation
enum NIImporter_Vissim::VissimXMLAttr private
Numbers representing VISSIM-XML - attributes.
See also
GenericSAXHandler
Enumerator
VISSIM_ATTR_NOTHING
VISSIM_ATTR_NO
VISSIM_ATTR_NAME
VISSIM_ATTR_X
VISSIM_ATTR_Y
VISSIM_ATTR_ZOFFSET
VISSIM_ATTR_ZUSCHLAG1
VISSIM_ATTR_ZUSCHLAG2
VISSIM_ATTR_WIDTH
VISSIM_ATTR_LINKBEHAVETYPE
VISSIM_ATTR_LANE
VISSIM_ATTR_POS
VISSIM_ATTR_LINK
VISSIM_ATTR_INTLINK
VISSIM_ATTR_PERCENTAGE
VISSIM_ATTR_DISTRICT
VISSIM_ATTR_COLOR
VISSIM_ATTR_KEY
VISSIM_ATTR_FX
VISSIM_ATTR_DESTLINK
VISSIM_ATTR_DESTPOS
VISSIM_ATTR_LINK1
VISSIM_ATTR_LINK2
VISSIM_ATTR_STATUS
Definition at line 635 of file NIImporter_Vissim.h.
enum NIImporter_Vissim::VissimXMLTag private
Numbers representing VISSIM-XML - element names.
See also
GenericSAXHandler
Enumerator
VISSIM_TAG_NOTHING
VISSIM_TAG_NETWORK
VISSIM_TAG_LANES
VISSIM_TAG_LANE
VISSIM_TAG_LINK
VISSIM_TAG_LINKS
VISSIM_TAG_POINTS3D
VISSIM_TAG_POINT3D
VISSIM_TAG_FROM
VISSIM_TAG_TO
VISSIM_TAG_VEHICLE_INPUT
VISSIM_TAG_PARKINGLOT
VISSIM_TAG_VEHICLE_CLASS
VISSIM_TAG_INTOBJECTREF
VISSIM_TAG_SPEED_DECISION
VISSIM_TAG_SPEED_DIST
VISSIM_TAG_DATAPOINT
VISSIM_TAG_DECISION_STATIC
VISSIM_TAG_ROUTE_STATIC
VISSIM_TAG_CA
Definition at line 606 of file NIImporter_Vissim.h.
Constructor & Destructor Documentation
NIImporter_Vissim::NIImporter_Vissim (NBNetBuilder & nb, const std::string & file) protected
constructor
Definition at line 871 of file NIImporter_Vissim.cpp.
References RGBColor::BLACK, buildParsers(), RGBColor::CYAN, RGBColor::GREEN, RGBColor::GREY, insertKnownElements(), RGBColor::MAGENTA, myColorMap, RGBColor::RED, UNUSED_PARAMETER, RGBColor::WHITE, and RGBColor::YELLOW.
NIImporter_Vissim::~NIImporter_Vissim () protected
destructor
Definition at line 891 of file NIImporter_Vissim.cpp.
References NIVissimSource::clearDict(), NIVissimTrafficDescription::clearDict(), NIVissimVehicleType::clearDict(), NIVissimClosures::clearDict(), NIVissimVehTypeClass::clearDict(), NIVissimNodeDef::clearDict(), NIVissimAbstractEdge::clearDict(), NIVissimTL::clearDict(), NIVissimDisturbance::clearDict(), NIVissimNodeCluster::clearDict(), NIVissimConflictArea::clearDict(), NIVissimDistrictConnection::clearDict(), NIVissimTL::NIVissimTLSignal::clearDict(), NIVissimConnectionCluster::clearDict(), NIVissimTL::NIVissimTLSignalGroup::clearDict(), and myParsers.
NIImporter_Vissim::NIImporter_Vissim (const NIImporter_Vissim &) private
Invalidated copy constructor.
Member Function Documentation
bool NIImporter_Vissim::admitContinue (const std::string & tag) protected
Definition at line 1001 of file NIImporter_Vissim.cpp.
References myKnownElements, and myLastSecure.
Referenced by NIImporter_Vissim::VissimSingleTypeParser::readEndSecure().
void NIImporter_Vissim::buildParsers () private
adds id-to-parser - relationships of elements to parse into myParsers
Definition at line 1179 of file NIImporter_Vissim.cpp.
References myColorMap, myParsers, VE_Auswertungsdefinition, VE_Baujahrverteilungsdefinition, VE_Detektorendefinition, VE_DynUml, VE_Einheitendefinition, VE_Emission, VE_Fahrtverlaufdateien, VE_Fahrverhaltendefinition, VE_Fahrzeugklassendefinition, VE_Fahrzeugtypdefinition, VE_Fensterdefinition, VE_Gefahrenwarnsystemdefinition, VE_Gelbverhaltendefinition, VE_Geschwindigkeitsverteilungsdefinition, VE_Haltestellendefinition, VE_Kantensperrung, VE_Kennungszeile, VE_Knotendefinition, VE_Laengenverteilungsdefinition, VE_Langsamfahrbereichdefinition, VE_Laufleistungsverteilungsdefinition, VE_Leistungsverteilungsdefinition, VE_Lichtsignalanlagendefinition, VE_Liniendefinition, VE_Linksverkehr, VE_LSAKopplungdefinition, VE_Massenverteilungsdefinition, VE_Maxbeschleunigungskurvedefinition, VE_Maxverzoegerungskurvedefinition, VE_Messungsdefinition, VE_Netzobjektdefinition, VE_Parkplatzdefinition, VE_Querschnittsmessungsdefinition, VE_Querverkehrsstoerungsdefinition, VE_Rautedefinition, VE_Reisezeitmessungsdefinition, VE_Richtungsentscheidungsdefinition, VE_Richtungspfeildefinition, VE_Routenentscheidungsdefinition, VE_Signalgeberdefinition, VE_Signalgruppendefinition, VE_Simdauer, VE_SimRate, VE_Startuhrzeit, VE_Startzufallszahl, VE_Stauparameterdefinition, VE_Stauzaehlerdefinition, VE_Stopschilddefinition, VE_Streckendefinition, VE_Streckentypdefinition, VE_TEAPACdefinition, VE_Verbindungsdefinition, VE_Verkehrszusammensetzungsdefinition, VE_Verlustzeitmessungsdefinition, VE_VWunschentscheidungsdefinition, VE_Wunschbeschleunigungskurvedefinition, VE_Wunschverzoegerungskurvedefinition, VE_Zeitenverteilungsdefinition, VE_Zeitschrittfaktor, and VE_Zuflussdefinition.
Referenced by NIImporter_Vissim().
void NIImporter_Vissim::insertKnownElements () private
adds name-to-id - relationships of known elements into myKnownElements
Definition at line 1107 of file NIImporter_Vissim.cpp.
References myKnownElements, VE_Auswertungsdefinition, VE_Baujahrverteilungsdefinition, VE_Detektorendefinition, VE_DUMMY, VE_DynUml, VE_Einheitendefinition, VE_Emission, VE_Fahrtverlaufdateien, VE_Fahrverhaltendefinition, VE_Fahrzeugklassendefinition, VE_Fahrzeugtypdefinition, VE_Fensterdefinition, VE_Gefahrenwarnsystemdefinition, VE_Gelbverhaltendefinition, VE_Geschwindigkeitsverteilungsdefinition, VE_Haltestellendefinition, VE_Kantensperrung, VE_Kennungszeile, VE_Knotendefinition, VE_Laengenverteilungsdefinition, VE_Langsamfahrbereichdefinition, VE_Laufleistungsverteilungsdefinition, VE_Leistungsverteilungsdefinition, VE_Lichtsignalanlagendefinition, VE_Liniendefinition, VE_Linksverkehr, VE_LSAKopplungdefinition, VE_Massenverteilungsdefinition, VE_Maxbeschleunigungskurvedefinition, VE_Maxverzoegerungskurvedefinition, VE_Messungsdefinition, VE_Netzobjektdefinition, VE_Parkplatzdefinition, VE_Querschnittsmessungsdefinition, VE_Querverkehrsstoerungsdefinition, VE_Rautedefinition, VE_Reisezeitmessungsdefinition, VE_Richtungsentscheidungsdefinition, VE_Richtungspfeildefinition, VE_Routenentscheidungsdefinition, VE_Signalgeberdefinition, VE_Signalgruppendefinition, VE_Simdauer, VE_SimRate, VE_Startuhrzeit, VE_Startzufallszahl, VE_Stauparameterdefinition, VE_Stauzaehlerdefinition, VE_Stopschilddefinition, VE_Streckendefinition, VE_Streckentypdefinition, VE_TEAPACdefinition, VE_Verbindungsdefinition, VE_Verkehrszusammensetzungsdefinition, VE_Verlustzeitmessungsdefinition, VE_VWunschentscheidungsdefinition, VE_Wunschbeschleunigungskurvedefinition, VE_Wunschverzoegerungskurvedefinition, VE_Zeitenverteilungsdefinition, VE_Zeitschrittfaktor, and VE_Zuflussdefinition.
Referenced by NIImporter_Vissim().
void NIImporter_Vissim::load (const OptionsCont & options) protected
loads the vissim file
Definition at line 917 of file NIImporter_Vissim.cpp.
References OptionsCont::getFloat(), OptionsCont::getString(), postLoadBuild(), readContents(), and WRITE_ERROR.
void NIImporter_Vissim::loadNetwork (const OptionsCont & oc, NBNetBuilder & nb) static
Loads network definition from the assigned option and stores it in the given network builder.
If the option "vissim-file" is set, the file stored therein is read and the network definition stored therein is stored within the given network builder.
If the option "vissim-file" is not set, this method simply returns.
Parameters
[in] oc The options to use
[in] nb The network builder to fill
Definition at line 203 of file NIImporter_Vissim.cpp.
References OptionsCont::getString(), OptionsCont::isSet(), and loadXML().
Referenced by NILoader::load().
void NIImporter_Vissim::loadXML (const OptionsCont & options, NBNetBuilder & nb) protected
Definition at line 932 of file NIImporter_Vissim.cpp.
References elementData, OptionsCont::getFloat(), OptionsCont::getString(), FileHelpers::isReadable(), postLoadBuild(), PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, XMLSubSys::runParser(), GenericSAXHandler::setFileName(), and WRITE_ERROR.
Referenced by loadNetwork().
NIImporter_Vissim& NIImporter_Vissim::operator= (const NIImporter_Vissim &) private
Invalidated assignment operator.
void NIImporter_Vissim::postLoadBuild (SUMOReal offset) private
Definition at line 1054 of file NIImporter_Vissim.cpp.
References NIVissimEdge::buildConnectionClusters(), NIVissimNodeCluster::buildNBNodes(), NIVissimConnectionCluster::buildNodeClusters(), NIVissimBoundedClusterObject::closeLoading(), NIVissimNodeCluster::dict_addDisturbances(), NIVissimConnection::dict_assignToEdges(), NIVissimDistrictConnection::dict_BuildDistrictConnections(), NIVissimDistrictConnection::dict_BuildDistrictNodes(), NIVissimDistrictConnection::dict_BuildDistricts(), NIVissimConnection::dict_buildNBEdgeConnections(), NIVissimEdge::dict_buildNBEdges(), NIVissimDistrictConnection::dict_CheckEdgeEnds(), NIVissimEdge::dict_checkEdges2Join(), NIVissimEdge::dict_propagateSpeeds(), NIVissimDisturbance::dict_SetDisturbances(), NIVissimTL::dict_SetSignals(), OptionsCont::getBool(), NBNetBuilder::getDistrictCont(), NBNetBuilder::getEdgeCont(), NIVissimNodeDef::getMaxID(), NBNetBuilder::getNodeCont(), OptionsCont::getOptions(), NBNetBuilder::getTLLogicCont(), NIVissimConnectionCluster::joinBySameEdges(), myNetBuilder, NIVissimEdge::reportUnsetSpeeds(), NIVissimNodeCluster::setCurrentVirtID(), and NIVissimConflictArea::setPriorityRegulation().
Referenced by load(), and loadXML().
bool NIImporter_Vissim::readContents (std::istream & strm) private
Definition at line 1012 of file NIImporter_Vissim.cpp.
References myKnownElements, myLastSecure, myParsers, NIImporter_Vissim::VissimSingleTypeParser::parse(), and StringUtils::to_lower_case().
Referenced by load().
Field Documentation
nodeMap NIImporter_Vissim::elementData private
Definition at line 86 of file NIImporter_Vissim.h.
Referenced by loadXML().
ColorMap NIImporter_Vissim::myColorMap private
a map from color names to color definitions
Definition at line 584 of file NIImporter_Vissim.h.
Referenced by buildParsers(), and NIImporter_Vissim().
bool NIImporter_Vissim::myInputIsLegacyFormat private
Definition at line 590 of file NIImporter_Vissim.h.
ToElemIDMap NIImporter_Vissim::myKnownElements private
Map from element names to their numerical representation.
Definition at line 575 of file NIImporter_Vissim.h.
Referenced by admitContinue(), insertKnownElements(), and readContents().
std::string NIImporter_Vissim::myLastSecure private
Definition at line 586 of file NIImporter_Vissim.h.
Referenced by admitContinue(), and readContents().
NBNetBuilder& NIImporter_Vissim::myNetBuilder private
Definition at line 588 of file NIImporter_Vissim.h.
Referenced by postLoadBuild().
ToParserMap NIImporter_Vissim::myParsers private
Parsers by element id.
Definition at line 581 of file NIImporter_Vissim.h.
Referenced by buildParsers(), readContents(), and ~NIImporter_Vissim().
StringBijection< int >::Entry NIImporter_Vissim::vissimAttrs static private
Initial value:
= {
    { "no",             NIImporter_Vissim::VISSIM_ATTR_NO },
    { "name",           NIImporter_Vissim::VISSIM_ATTR_NAME },
    { "x",              NIImporter_Vissim::VISSIM_ATTR_X },
    { "y",              NIImporter_Vissim::VISSIM_ATTR_Y },
    { "zOffset",        NIImporter_Vissim::VISSIM_ATTR_ZOFFSET },
    { "surch1",         NIImporter_Vissim::VISSIM_ATTR_ZUSCHLAG1 },
    { "surch2",         NIImporter_Vissim::VISSIM_ATTR_ZUSCHLAG2 },
    { "width",          NIImporter_Vissim::VISSIM_ATTR_WIDTH },
    { "linkBehavType",  NIImporter_Vissim::VISSIM_ATTR_LINKBEHAVETYPE},
    { "lane",           NIImporter_Vissim::VISSIM_ATTR_LANE },
    { "pos",            NIImporter_Vissim::VISSIM_ATTR_POS },
    { "link",           NIImporter_Vissim::VISSIM_ATTR_LINK },
    { "intLink",        NIImporter_Vissim::VISSIM_ATTR_INTLINK },
    { "relFlow",        NIImporter_Vissim::VISSIM_ATTR_PERCENTAGE },
    { "zone",           NIImporter_Vissim::VISSIM_ATTR_DISTRICT },
    { "color",          NIImporter_Vissim::VISSIM_ATTR_COLOR },
    { "key",            NIImporter_Vissim::VISSIM_ATTR_KEY },
    { "fx",             NIImporter_Vissim::VISSIM_ATTR_FX },
    { "destLink",       NIImporter_Vissim::VISSIM_ATTR_DESTLINK },
    { "destPos",        NIImporter_Vissim::VISSIM_ATTR_DESTPOS },
    { "link1",          NIImporter_Vissim::VISSIM_ATTR_LINK1 },
    { "link2",          NIImporter_Vissim::VISSIM_ATTR_LINK2 },
    { "status",         NIImporter_Vissim::VISSIM_ATTR_STATUS },
    { "",               NIImporter_Vissim::VISSIM_ATTR_NOTHING }
}
The names of VISSIM-XML attributes (for passing to GenericSAXHandler)
Definition at line 666 of file NIImporter_Vissim.h.
StringBijection< int >::Entry NIImporter_Vissim::vissimTags static private
The names of VISSIM-XML elements (for passing to GenericSAXHandler)
Definition at line 663 of file NIImporter_Vissim.h.
The documentation for this class was generated from the following files:
NIImporter_Vissim.h
NIImporter_Vissim.cpp