SUMO - Simulation of Urban MObility: emissionsMap_main.cpp File Reference
emissionsMap_main.cpp File Reference
#include <config.h>
#include <utils/common/TplConvert.h>
#include <iostream>
#include <string>
#include <ctime>
#include <utils/common/MsgHandler.h>
#include <utils/options/Option.h>
#include <utils/options/OptionsCont.h>
#include <utils/options/OptionsIO.h>
#include <utils/common/UtilExceptions.h>
#include <utils/emissions/PollutantsInterface.h>
#include <utils/common/SystemFrame.h>
#include <utils/common/ToString.h>
#include <utils/xml/XMLSubSys.h>
#include <utils/common/FileHelpers.h>
#include <utils/iodevices/OutputDevice.h>
Functions
int main (int argc, char **argv)
void single (const std::string &of, const std::string &className, SUMOEmissionClass c, SUMOReal vMin, SUMOReal vMax, SUMOReal vStep, SUMOReal aMin, SUMOReal aMax, SUMOReal aStep, SUMOReal sMin, SUMOReal sMax, SUMOReal sStep, bool verbose)
Detailed Description
Author
Daniel Krajzewicz
Michael Behrisch
Date
Wed, 21.08.2013
Version
Id
emissionsMap_main.cpp 20279 2016-03-22 13:55:22Z behrisch
Definition in file emissionsMap_main.cpp.
Function Documentation
int main (int argc, char ** argv)
Definition at line 94 of file emissionsMap_main.cpp.
References SystemFrame::addConfigurationOptions(), OptionsCont::addDescription(), OptionsCont::addOptionSubTopic(), SystemFrame::addReportOptions(), OptionsCont::addSynonyme(), SystemFrame::close(), OptionsCont::doRegister(), PollutantsInterface::getAllClasses(), OptionsCont::getBool(), PollutantsInterface::getClassByName(), MsgHandler::getErrorInstance(), OptionsCont::getFloat(), PollutantsInterface::getName(), OptionsIO::getOptions(), OptionsCont::getOptions(), OptionsCont::getString(), MsgHandler::inform(), XMLSubSys::init(), OptionsCont::isSet(), OptionsCont::processMetaOptions(), OptionsCont::set(), OptionsCont::setApplicationDescription(), OptionsCont::setApplicationName(), OptionsIO::setArgs(), single(), SUMOReal, and VERSION_STRING.
void single (const std::string & of, const std::string & className, SUMOEmissionClass c, SUMOReal vMin, SUMOReal vMax, SUMOReal vStep, SUMOReal aMin, SUMOReal aMax, SUMOReal aStep, SUMOReal sMin, SUMOReal sMax, SUMOReal sStep, bool verbose)
Definition at line 65 of file emissionsMap_main.cpp.
References PollutantsInterface::Emissions::CO, PollutantsInterface::Emissions::CO2, PollutantsInterface::computeAll(), PollutantsInterface::Emissions::electricity, PollutantsInterface::Emissions::fuel, PollutantsInterface::Emissions::HC, PollutantsInterface::Emissions::NOx, PollutantsInterface::Emissions::PMx, SUMOReal, and WRITE_MESSAGE.
Referenced by main().