SUMO - Simulation of Urban MObility: PHEMlightdll::Helpers Class Reference
PHEMlightdll::Helpers Class Reference
#include <Helpers.h>
Public Member Functions
const std::string & getCommentPrefix () const
const std::string & geteClass () const
const std::string & getErrMsg () const
const std::string & getgClass () const
const std::string & getPHEMDataV () const
const std::string & getsClass () const
const std::string & gettClass () const
const std::string & getvClass () const
bool setclass (const std::string &VEH)
bool setclass (string VEH)
void setCommentPrefix (const std::string &value)
void seteClass (const std::string &value)
void setErrMsg (const std::string &value)
void setgClass (const std::string &value)
void setPHEMDataV (const std::string &value)
void setsClass (const std::string &value)
void settClass (const std::string &value)
void setvClass (const std::string &value)
Properties
string CommentPrefix [get, set]
string eClass [get, set]
string ErrMsg [get, set]
string gClass [get, set]
string PHEMDataV [get, set]
string sClass [get, set]
string tClass [get, set]
string vClass [get, set]
Private Member Functions
bool geteclass (const std::string &VEH)
bool geteclass (string VEH)
bool getsclass (const std::string &VEH)
bool getsclass (string VEH)
bool gettclass (const std::string &VEH)
bool gettclass (string VEH)
bool getvclass (const std::string &VEH)
bool getvclass (string VEH)
Private Attributes
std::string _Class
string _Class
std::string _commentPrefix
string _commentPrefix
std::string _eClass
string _eClass
std::string _ErrMsg
string _ErrMsg
std::string _PHEMDataV
string _PHEMDataV
std::string _sClass
string _sClass
std::string _tClass
string _tClass
std::string _vClass
string _vClass
Detailed Description
Definition at line 8 of file Helpers.h.
Member Function Documentation
const std::string & PHEMlightdll::Helpers::getCommentPrefix () const
Definition at line 55 of file Helpers.cpp.
References _commentPrefix.
Referenced by PHEMlightdll::CEPHandler::ReadVehicleFile().
const std::string & PHEMlightdll::Helpers::geteClass () const
Definition at line 15 of file Helpers.cpp.
References _eClass.
Referenced by setclass().
bool PHEMlightdll::Helpers::geteclass (const std::string & VEH) private
Definition at line 193 of file Helpers.cpp.
References _eClass, _ErrMsg, PHEMlightdll::Constants::strBEV, and PHEMlightdll::Constants::strEU.
Referenced by setclass().
bool PHEMlightdll.Helpers.geteclass (string VEH) inline private
Definition at line 222 of file Helpers.cs.
References PHEMlightdll::Constants.strBEV, and PHEMlightdll::Constants.strEU.
const std::string & PHEMlightdll::Helpers::getErrMsg () const
Definition at line 47 of file Helpers.cpp.
References _ErrMsg.
Referenced by HelpersPHEMlight::getClassByName().
const std::string & PHEMlightdll::Helpers::getgClass () const
Definition at line 39 of file Helpers.cpp.
References _Class.
Referenced by PHEMlightdll::CEPHandler::GetCEP(), HelpersPHEMlight::getClassByName(), and PHEMlightdll::CEPHandler::Load().
const std::string & PHEMlightdll::Helpers::getPHEMDataV () const
Definition at line 63 of file Helpers.cpp.
References _PHEMDataV.
const std::string & PHEMlightdll::Helpers::getsClass () const
Definition at line 31 of file Helpers.cpp.
References _sClass.
Referenced by setclass().
bool PHEMlightdll::Helpers::getsclass (const std::string & VEH) private
Definition at line 153 of file Helpers.cpp.
References _ErrMsg, _sClass, PHEMlightdll::Constants::strLKW, PHEMlightdll::Constants::strLNF, PHEMlightdll::Constants::strSI, PHEMlightdll::Constants::strSII, and PHEMlightdll::Constants::strSIII.
Referenced by setclass().
bool PHEMlightdll.Helpers.getsclass (string VEH) inline private
Definition at line 170 of file Helpers.cs.
References PHEMlightdll::Constants.strLKW, PHEMlightdll::Constants.strLNF, PHEMlightdll::Constants.strSI, PHEMlightdll::Constants.strSII, and PHEMlightdll::Constants.strSIII.
const std::string & PHEMlightdll::Helpers::gettClass () const
Definition at line 23 of file Helpers.cpp.
References _tClass.
Referenced by setclass().
bool PHEMlightdll::Helpers::gettclass (const std::string & VEH) private
Definition at line 118 of file Helpers.cpp.
References _ErrMsg, _tClass, PHEMlightdll::Constants::strBEV, PHEMlightdll::Constants::strCNG, PHEMlightdll::Constants::strDiesel, PHEMlightdll::Constants::strGasoline, and PHEMlightdll::Constants::strHybrid.
Referenced by setclass().
bool PHEMlightdll.Helpers.gettclass (string VEH) inline private
Definition at line 125 of file Helpers.cs.
References PHEMlightdll::Constants.strBEV, PHEMlightdll::Constants.strCNG, PHEMlightdll::Constants.strDiesel, PHEMlightdll::Constants.strGasoline, and PHEMlightdll::Constants.strHybrid.
const std::string & PHEMlightdll::Helpers::getvClass () const
Definition at line 7 of file Helpers.cpp.
References _vClass.
bool PHEMlightdll::Helpers::getvclass (const std::string & VEH) private
Definition at line 71 of file Helpers.cpp.
References _ErrMsg, _vClass, PHEMlightdll::Constants::DRIVE_TRAIN_EFFICIENCY_All, PHEMlightdll::Constants::DRIVE_TRAIN_EFFICIENCY_CB, PHEMlightdll::Constants::setDRIVE_TRAIN_EFFICIENCY(), PHEMlightdll::Constants::strKKR, PHEMlightdll::Constants::strLB, PHEMlightdll::Constants::strLKW, PHEMlightdll::Constants::strLNF, PHEMlightdll::Constants::strLSZ, PHEMlightdll::Constants::strMR2, PHEMlightdll::Constants::strMR4, PHEMlightdll::Constants::strPKW, and PHEMlightdll::Constants::strRB.
Referenced by setclass().
bool PHEMlightdll.Helpers.getvclass (string VEH) inline private
Definition at line 67 of file Helpers.cs.
References PHEMlightdll::Constants.DRIVE_TRAIN_EFFICIENCY, PHEMlightdll::Constants.DRIVE_TRAIN_EFFICIENCY_All, PHEMlightdll::Constants.DRIVE_TRAIN_EFFICIENCY_CB, PHEMlightdll::Constants.strKKR, PHEMlightdll::Constants.strLB, PHEMlightdll::Constants.strLKW, PHEMlightdll::Constants.strLNF, PHEMlightdll::Constants.strLSZ, PHEMlightdll::Constants.strMR2, PHEMlightdll::Constants.strMR4, PHEMlightdll::Constants.strPKW, and PHEMlightdll::Constants.strRB.
bool PHEMlightdll::Helpers::setclass (const std::string & VEH)
Definition at line 217 of file Helpers.cpp.
References _Class, _eClass, _sClass, _vClass, geteClass(), geteclass(), getsClass(), getsclass(), gettClass(), gettclass(), and getvclass().
Referenced by PHEMlightdll.Start::CALC_Array(), PHEMlightdll.Start::CALC_Single(), HelpersPHEMlight::getClassByName(), and PHEMlightdll::CEPHandler::GetFleetCEP().
bool PHEMlightdll.Helpers.setclass (string VEH) inline
Definition at line 253 of file Helpers.cs.
References _vClass, eClass, geteclass(), getsclass(), gettclass(), getvclass(), sClass, and tClass.
void PHEMlightdll::Helpers::setCommentPrefix (const std::string & value)
Definition at line 59 of file Helpers.cpp.
References _commentPrefix.
Referenced by HelpersPHEMlight::getClassByName().
void PHEMlightdll::Helpers::seteClass (const std::string & value)
Definition at line 19 of file Helpers.cpp.
References _eClass.
void PHEMlightdll::Helpers::setErrMsg (const std::string & value)
Definition at line 51 of file Helpers.cpp.
References _ErrMsg.
Referenced by PHEMlightdll::CEP::GetCO2Emission(), PHEMlightdll::CEP::GetEmission(), PHEMlightdll::CEPHandler::ReadEmissionData(), and PHEMlightdll::CEPHandler::ReadVehicleFile().
void PHEMlightdll::Helpers::setgClass (const std::string & value)
Definition at line 43 of file Helpers.cpp.
References _Class.
void PHEMlightdll::Helpers::setPHEMDataV (const std::string & value)
Definition at line 67 of file Helpers.cpp.
References _PHEMDataV.
Referenced by HelpersPHEMlight::getClassByName().
void PHEMlightdll::Helpers::setsClass (const std::string & value)
Definition at line 35 of file Helpers.cpp.
References _sClass.
void PHEMlightdll::Helpers::settClass (const std::string & value)
Definition at line 27 of file Helpers.cpp.
References _tClass.
void PHEMlightdll::Helpers::setvClass (const std::string & value)
Definition at line 11 of file Helpers.cpp.
References _vClass.
Field Documentation
std::string PHEMlightdll::Helpers::_Class private
Definition at line 33 of file Helpers.h.
Referenced by getgClass(), setclass(), and setgClass().
string PHEMlightdll.Helpers._Class private
Definition at line 39 of file Helpers.cs.
std::string PHEMlightdll::Helpers::_commentPrefix private
Definition at line 43 of file Helpers.h.
Referenced by getCommentPrefix(), and setCommentPrefix().
string PHEMlightdll.Helpers._commentPrefix private
Definition at line 51 of file Helpers.cs.
std::string PHEMlightdll::Helpers::_eClass private
Definition at line 18 of file Helpers.h.
Referenced by geteClass(), geteclass(), setclass(), and seteClass().
string PHEMlightdll.Helpers._eClass private
Definition at line 21 of file Helpers.cs.
std::string PHEMlightdll::Helpers::_ErrMsg private
Definition at line 38 of file Helpers.h.
Referenced by geteclass(), getErrMsg(), getsclass(), gettclass(), getvclass(), and setErrMsg().
string PHEMlightdll.Helpers._ErrMsg private
Definition at line 45 of file Helpers.cs.
std::string PHEMlightdll::Helpers::_PHEMDataV private
Definition at line 48 of file Helpers.h.
Referenced by getPHEMDataV(), and setPHEMDataV().
string PHEMlightdll.Helpers._PHEMDataV private
Definition at line 57 of file Helpers.cs.
std::string PHEMlightdll::Helpers::_sClass private
Definition at line 28 of file Helpers.h.
Referenced by getsClass(), getsclass(), setclass(), and setsClass().
string PHEMlightdll.Helpers._sClass private
Definition at line 33 of file Helpers.cs.
std::string PHEMlightdll::Helpers::_tClass private
Definition at line 23 of file Helpers.h.
Referenced by gettClass(), gettclass(), and settClass().
string PHEMlightdll.Helpers._tClass private
Definition at line 27 of file Helpers.cs.
std::string PHEMlightdll::Helpers::_vClass private
Definition at line 13 of file Helpers.h.
Referenced by getvClass(), getvclass(), setclass(), and setvClass().
string PHEMlightdll.Helpers._vClass private
Definition at line 15 of file Helpers.cs.
Property Documentation
string PHEMlightdll.Helpers.CommentPrefix get set
Definition at line 53 of file Helpers.cs.
Referenced by PHEMlightdll.Start.CALC_Array(), PHEMlightdll.Start.CALC_Single(), PHEMlightdll::CEPHandler.ReadFleetShares(), and PHEMlightdll::CEPHandler.ReadVehicleFile().
string PHEMlightdll.Helpers.eClass get set
Definition at line 23 of file Helpers.cs.
Referenced by setclass().
string PHEMlightdll.Helpers.ErrMsg get set
Definition at line 47 of file Helpers.cs.
Referenced by PHEMlightdll.Start.CALC_Array(), PHEMlightdll::CEP.GetCO2Emission(), PHEMlightdll::CEP.GetEmission(), PHEMlightdll::CEPHandler.GetFleetCEP(), PHEMlightdll::CEP.GetNormedEmission(), PHEMlightdll::CEPHandler.ReadEmissionData(), PHEMlightdll::CEPHandler.ReadFleetShares(), and PHEMlightdll::CEPHandler.ReadVehicleFile().
string PHEMlightdll.Helpers.gClass get set
Definition at line 41 of file Helpers.cs.
Referenced by PHEMlightdll.Start.CALC_Array(), PHEMlightdll.Start.CALC_Single(), PHEMlightdll::CEPHandler.GetCEP(), PHEMlightdll::CEPHandler.GetFleetCEP(), and PHEMlightdll::CEPHandler.Load().
string PHEMlightdll.Helpers.PHEMDataV get set
Definition at line 59 of file Helpers.cs.
Referenced by PHEMlightdll.Start.CALC_Array(), and PHEMlightdll.Start.CALC_Single().
string PHEMlightdll.Helpers.sClass get set
Definition at line 35 of file Helpers.cs.
Referenced by setclass().
string PHEMlightdll.Helpers.tClass get set
Definition at line 29 of file Helpers.cs.
Referenced by PHEMlightdll.PHEMLight.CreateVehicleStateData(), PHEMlightdll::CEP.GetEmission(), and setclass().
string PHEMlightdll.Helpers.vClass get set
Definition at line 17 of file Helpers.cs.
The documentation for this class was generated from the following files:
Helpers.h
Helpers.cs
Helpers.cpp