SUMO - Simulation of Urban MObility: MSPModel_NonInteracting::PState Class Reference
MSPModel_NonInteracting::PState Class Reference
abstract base class for managing callbacks to retrieve various state information from the model
Public Member Functions
SUMOTime computeWalkingTime (const MSEdge *prev, const MSPerson::MSPersonStage_Walking &stage, SUMOTime currentTime)
compute walking time on edge and update state members
PState ()
SUMOReal getEdgePos (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const
abstract methods inherited from PedestrianState
Position getPosition (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const
return the network coordinate of the person
SUMOReal getAngle (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const
return the direction in which the person faces in degrees
SUMOTime getWaitingTime (const MSPerson::MSPersonStage_Walking &stage, SUMOTime now) const
return the time the person spent standing
SUMOReal getSpeed (const MSPerson::MSPersonStage_Walking &stage) const
return the current speed of the person
const MSEdge * getNextEdge (const MSPerson::MSPersonStage_Walking &stage) const
return the list of internal edges if the pedestrian is on an intersection
Private Attributes
SUMOReal myCurrentBeginPos
SUMOTime myCurrentDuration
SUMOReal myCurrentEndPos
SUMOTime myLastEntryTime
Detailed Description
abstract base class for managing callbacks to retrieve various state information from the model
Definition at line 86 of file MSPModel_NonInteracting.h.
Constructor & Destructor Documentation
MSPModel_NonInteracting::PState::PState () inline
Definition at line 88 of file MSPModel_NonInteracting.h.
References SUMOReal.
Member Function Documentation
SUMOTime MSPModel_NonInteracting::PState::computeWalkingTime (const MSEdge * prev, const MSPerson::MSPersonStage_Walking & stage, SUMOTime currentTime)
compute walking time on edge and update state members
Definition at line 111 of file MSPModel_NonInteracting.cpp.
References MSPModel::BACKWARD, MSPModel::FORWARD, MSPerson::MSPersonStage_Walking::getArrivalPos(), MSPerson::MSPersonStage_Walking::getDepartPos(), MSPerson::MSPersonStage_Walking::getEdge(), MSEdge::getFromJunction(), MSEdge::getLength(), MSPerson::MSPersonStage_Walking::getMaxSpeed(), MSPerson::MSPersonStage_Walking::getNextRouteEdge(), MSEdge::getToJunction(), MAX2(), SUMOReal, TIME2STEPS, and MSPModel::UNDEFINED_DIRECTION.
Referenced by MSPModel_NonInteracting::add(), and MSPModel_NonInteracting::MoveToNextEdge::execute().
SUMOReal MSPModel_NonInteracting::PState::getAngle (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const virtual
return the direction in which the person faces in degrees
Implements PedestrianState.
Definition at line 155 of file MSPModel_NonInteracting.cpp.
References MSPerson::MSPersonStage_Walking::getEdge(), MSTransportable::Stage::getEdgeAngle(), M_PI, and SUMOReal.
SUMOReal MSPModel_NonInteracting::PState::getEdgePos (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const virtual
abstract methods inherited from PedestrianState
Implements PedestrianState.
Definition at line 140 of file MSPModel_NonInteracting.cpp.
const MSEdge * MSPModel_NonInteracting::PState::getNextEdge (const MSPerson::MSPersonStage_Walking & stage) const virtual
return the list of internal edges if the pedestrian is on an intersection
Implements PedestrianState.
Definition at line 178 of file MSPModel_NonInteracting.cpp.
References MSPerson::MSPersonStage_Walking::getNextRouteEdge().
Position MSPModel_NonInteracting::PState::getPosition (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const virtual
return the network coordinate of the person
Implements PedestrianState.
Definition at line 147 of file MSPModel_NonInteracting.cpp.
References MSLane::allowsVehicleClass(), MSPerson::MSPersonStage_Walking::getEdge(), MSTransportable::Stage::getLanePosition(), MSPModel::SIDEWALK_OFFSET, SUMOReal, and SVC_PEDESTRIAN.
SUMOReal MSPModel_NonInteracting::PState::getSpeed (const MSPerson::MSPersonStage_Walking & stage) const virtual
return the current speed of the person
Implements PedestrianState.
Definition at line 172 of file MSPModel_NonInteracting.cpp.
References MSPerson::MSPersonStage_Walking::getMaxSpeed().
SUMOTime MSPModel_NonInteracting::PState::getWaitingTime (const MSPerson::MSPersonStage_Walking & stage, SUMOTime now) const virtual
return the time the person spent standing
Implements PedestrianState.
Definition at line 166 of file MSPModel_NonInteracting.cpp.
References SUMOReal.
Field Documentation
SUMOReal MSPModel_NonInteracting::PState::myCurrentBeginPos private
Definition at line 107 of file MSPModel_NonInteracting.h.
SUMOTime MSPModel_NonInteracting::PState::myCurrentDuration private
Definition at line 106 of file MSPModel_NonInteracting.h.
SUMOReal MSPModel_NonInteracting::PState::myCurrentEndPos private
Definition at line 108 of file MSPModel_NonInteracting.h.
SUMOTime MSPModel_NonInteracting::PState::myLastEntryTime private
Definition at line 105 of file MSPModel_NonInteracting.h.
The documentation for this class was generated from the following files:
MSPModel_NonInteracting.h
MSPModel_NonInteracting.cpp