SUMO - Simulation of Urban MObility: OptionsCont Class Reference
OptionsCont Class Reference
A storage for options typed value containers)
#include <OptionsCont.h>
Data Structures
class abbreviation_finder
A class to find abbreviated option names (length=1)
Public Member Functions
void clear ()
Removes all information from the container.
const std::string & getFullName () const
const std::vector< std::string > & getSubTopics () const
return the list of subtopics
std::vector< std::string > getSubTopicsEntries (const std::string &subtopic) const
return the list of entries for the given subtopic
std::string getTypeName (const std::string name)
return the type name for the given option
OptionsCont ()
Constructor.
bool processMetaOptions (bool missingOptions)
Checks for help and configuration output, returns whether we should exit.
void resetWritable ()
Resets all options to be writeable.
~OptionsCont ()
Destructor.
Methods setting and getting information about the appplication and currently set options
void setApplicationName (const std::string &appName, const std::string &fullName)
Sets the application name.
void setApplicationDescription (const std::string &appDesc)
Sets the application description.
void addCallExample (const std::string &example, const std::string &desc)
Add a call example.
void setAdditionalHelpMessage (const std::string &add)
Sets an additional message to be printed at the begin of the help screen.
void addCopyrightNotice (const std::string &copyrightLine)
Adds a copyright notice to the help output.
void clearCopyrightNotices ()
Removes all copyright information.
void addOptionSubTopic (const std::string &topic)
Adds an option subtopic.
void printHelp (std::ostream &os)
Prints the help.
void writeConfiguration (std::ostream &os, bool filled, bool complete, bool addComments) const
Writes the configuration.
void writeSchema (std::ostream &os, bool addComments)
Writes the xml schema for the configuration.
void writeXMLHeader (std::ostream &os)
Writes a standard XML header, including the configuration.
Methods for registering options
void doRegister (const std::string &name, Option *v)
Adds an option under the given name.
void doRegister (const std::string &name, char abbr, Option *v)
Adds an option under the given name and the given abbreviation.
void addSynonyme (const std::string &name1, const std::string &name2, bool isDeprecated=false)
Adds a synonyme for an options name (any order)
void addXMLDefault (const std::string &name, const std::string &xmlRoot="")
Adds an XML root element to handle by default. The special root "" denotes the default handler.
void addDescription (const std::string &name, const std::string &subtopic, const std::string &description)
Adds a description for an option.
Methods for retrieving information about options
bool exists (const std::string &name) const
Returns the information whether the named option is known.
bool isSet (const std::string &name, bool failOnNonExistant=true) const
Returns the information whether the named option is set.
void unSet (const std::string &name, bool failOnNonExistant=true) const
Marks the option as unset.
bool isDefault (const std::string &name) const
Returns the information whether the named option has still the default value.
bool isBool (const std::string &name) const
Returns the information whether the option is a boolean option.
bool isUsableFileList (const std::string &name) const
Checks whether the named option is usable as a file list (with at least a single file)
bool checkDependingSuboptions (const std::string &name, const std::string &prefix) const
Checks whether an option is set, which has options with a prefix depending on it.
void relocateFiles (const std::string &configuration) const
Modifies file name options according to the configuration path.
std::vector< std::string > getSynonymes (const std::string &name) const
Returns the synonymes of an option name.
bool isWriteable (const std::string &name)
Returns the information whether the named option may be set.
Methods for retrieving values from options
std::string getString (const std::string &name) const
Returns the string-value of the named option (only for Option_String)
SUMOReal getFloat (const std::string &name) const
Returns the SUMOReal-value of the named option (only for Option_Float)
int getInt (const std::string &name) const
Returns the int-value of the named option (only for Option_Integer)
bool getBool (const std::string &name) const
Returns the boolean-value of the named option (only for Option_Bool)
const IntVector & getIntVector (const std::string &name) const
Returns the list of integer-value of the named option (only for Option_IntVector)
std::vector< std::string > getStringVector (const std::string &name) const
Returns the list of string-vector-value of the named option (only for Option_String)
bool isInStringVector (const std::string &optionName, const std::string &itemName)
Returns the named option is a list of string values containing the specified item.
Methods for setting values into options
bool set (const std::string &name, const std::string &value)
Sets the given value for the named option.
bool setDefault (const std::string &name, const std::string &value)
Sets the given value for the named option as new default value.
bool setByRootElement (const std::string &name, const std::string &value)
Sets the given value for the option which can handle the given XML root.
Static Public Member Functions
static OptionsCont & getOptions ()
Retrieves the options.
Private Types
typedef std::vector< Option * > ItemAddressContType
typedef std::map< std::string, Option * > KnownContType
Private Member Functions
std::string convertChar (char abbr) const
Converts an abbreviation into a name.
Option * getSecure (const std::string &name) const
Returns the named option.
OptionsCont & operator= (const OptionsCont &s)
OptionsCont (const OptionsCont &s)
void reportDoubleSetting (const std::string &arg) const
Reports an error that the option has already been set.
void splitLines (std::ostream &os, std::string what, int offset, int nextOffset)
Writes the given string 'formatted'.
Private Attributes
std::string myAdditionalMessage
ItemAddressContType myAddresses
std::string myAppDescription
std::string myAppName
some information on the application
std::vector< std::pair< std::string, std::string > > myCallExamples
list of call examples
std::vector< std::string > myCopyrightNotices
std::map< std::string, bool > myDeprecatedSynonymes
A map from deprecated options to a bool indicating whether we warned about deprecation.
std::string myFullName
bool myHaveInformedAboutDeprecatedDivider
Information whether a warning a deprecated divider.
std::map< std::string, std::vector< std::string > > mySubTopicEntries
A map from subtopic to option.
std::vector< std::string > mySubTopics
lists of option subtopics and copyright notices
KnownContType myValues
std::map< std::string, std::string > myXMLDefaults
A map from XML root element to option.
Static Private Attributes
static OptionsCont myOptions
The static options container used.
Friends
std::ostream & operator<< (std::ostream &os, const OptionsCont &oc)
Output operator.
Detailed Description
A storage for options typed value containers)
This container stores options (typed value containers) by their names. In the case of command line tools, this container is the main interface between a user's definitions about what to do (command line options, configuration files) and the application.
At the begin, the application should initialise the container. Because the OptionsCont is also responsible for printing the help screen, one should name and describe the application, first. This means that the first usage of this container should look similar to this:
OptionsCont &oc = OptionsCont::getOptions();
// give some application descriptions
oc.setApplicationDescription(<ONE_LINE_DESCRIPTION>);
oc.setApplicationName(<APPLICATION_NAME>, "SUMO <APPLICATION_NAME> Version " + (string)VERSION_STRING);
See also
setApplicationDescription
setApplicationName
Then, you may also add some example calls using addCallExample.
See also
addCallExample
In the next step, option subtopics are registered. This is needed for the help screen and for writing the templates/saving configurations. A subtopic is added using addOptionSubTopic(<SUBTOPIC_NAME>).
See also
addOptionSubTopic
After this, you may add options to the container. This is done using doRegister. This method requires a long name for the option and the value container. The value container must be an instance of one of the classes derived from "Option". Do not use Option itself! This is a base class which is meant to supply a default behaviour, but this default behaviour throws exceptions only!
See also
Option
doRegister
addSynonyme
Once stored inside this container, options will not be visible to the world and are deleted by the container. Only values and stati of the options may be returned. While accessing the options, the programmer must assure that he asks for the right value (only Option_Bool is able to return a boolean value, other option types will throw exceptions). Further, options added to the container must not be deleted outside this container (the container becomes the owner).
For being printed in the help screen, a description together with the subtopic the option belongs to must be given to OptionsCont. This is done using addDescription(<OPTION_NAME>, <SUBTOPIC>, <DESCRIPTION>).
See also
addDescription
http://sumo.dlr.de/wiki/index.php/OptionsSubSystem
Definition at line 99 of file OptionsCont.h.
Member Typedef Documentation
typedef std::vector<Option*> OptionsCont::ItemAddressContType private
definition of the type that stores the addresses of used options
Definition at line 711 of file OptionsCont.h.
typedef std::map<std::string, Option*> OptionsCont::KnownContType private
definition of the type that realises the access to options
Definition at line 714 of file OptionsCont.h.
Constructor & Destructor Documentation
OptionsCont::OptionsCont ()
Constructor.
Definition at line 74 of file OptionsCont.cpp.
References myCopyrightNotices.
Referenced by OptionsCont::abbreviation_finder::operator()().
OptionsCont::~OptionsCont ()
Destructor.
Definition at line 80 of file OptionsCont.cpp.
References clear().
OptionsCont::OptionsCont (const OptionsCont & s) private
invalid copy constructor
Member Function Documentation
void OptionsCont::addCallExample (const std::string & example, const std::string & desc)
Add a call example.
Parameters
[in] example A call example (without the app name)
[in] desc A verbose description
Definition at line 503 of file OptionsCont.cpp.
References myCallExamples.
Referenced by RODFFrame::fillOptions(), AGFrame::fillOptions(), ROJTRFrame::fillOptions(), RODUAFrame::fillOptions(), ROMAFrame::fillOptions(), fillOptions(), MSFrame::fillOptions(), and GNELoadThread::fillOptions().
void OptionsCont::addCopyrightNotice (const std::string & copyrightLine)
Adds a copyright notice to the help output.
Parameters
[in] copyrightLine The line to put out as a copyright notice
Definition at line 515 of file OptionsCont.cpp.
References myCopyrightNotices.
Referenced by main().
void OptionsCont::addDescription (const std::string & name, const std::string & subtopic, const std::string & description)
Adds a description for an option.
Tries to retrieve the named option and to set the given description. Adds the name to the list of option names to be located in the named subtopic.
Throws an InvalidArgument if the option is not known or already has a description set.
Parameters
[in] name The option's name
[in] subtopic The subtopic to locate the description within
[in] description The description
Exceptions
InvalidArgument If none of the synonymes or both synonymes with different options were registered before
Definition at line 477 of file OptionsCont.cpp.
References getSecure(), mySubTopicEntries, mySubTopics, and Option::setDescription().
Referenced by ROMAFrame::addAssignmentOptions(), SystemFrame::addConfigurationOptions(), RODUAFrame::addDUAOptions(), RODUAFrame::addImportOptions(), ROMAFrame::addImportOptions(), GeoConvHelper::addProjectionOptions(), SystemFrame::addReportOptions(), NGFrame::fillOptions(), RODFFrame::fillOptions(), AGFrame::fillOptions(), NIFrame::fillOptions(), ROJTRFrame::fillOptions(), NWFrame::fillOptions(), ROFrame::fillOptions(), NBFrame::fillOptions(), MSFrame::fillOptions(), fillOptions(), GNELoadThread::fillOptions(), MSDevice::insertDefaultAssignmentOptions(), MSDevice_Example::insertOptions(), MSDevice_BTreceiver::insertOptions(), MSDevice_Routing::insertOptions(), RandHelper::insertRandOptions(), and main().
void OptionsCont::addOptionSubTopic (const std::string & topic)
Adds an option subtopic.
Sub-topics are used to join several options into one thematic field. They are used on writing the help screen and the configuration. They have no further meaning besides making the outputs better readable.
Parameters
[in] topic The options sub topic
Definition at line 527 of file OptionsCont.cpp.
References mySubTopicEntries, and mySubTopics.
Referenced by SystemFrame::addConfigurationOptions(), GeoConvHelper::addProjectionOptions(), SystemFrame::addReportOptions(), RODFFrame::fillOptions(), AGFrame::fillOptions(), ROJTRFrame::fillOptions(), RODUAFrame::fillOptions(), ROMAFrame::fillOptions(), fillOptions(), MSFrame::fillOptions(), GNELoadThread::fillOptions(), MSDevice_Example::insertOptions(), RandHelper::insertRandOptions(), and main().
void OptionsCont::addSynonyme (const std::string & name1, const std::string & name2, bool isDeprecated = false)
Adds a synonyme for an options name (any order)
Tries to find one of the synonymes. If both are known and the option differs for both, an InvalidArgument exception is thrown. If none is known, also.
If one of the synonymes is known and the other not, the option from the known one is made accessible by the other.
In the case both synonymes are known and have the same option assigned, nothing is done.
Parameters
[in] name1 The first synonyme
[in] name2 The second synonyme
[in] isDeprecated whether the synonyme is considered deprecated
Exceptions
InvalidArgument If none of the synonymes or both synonymes with different options were registered before
Definition at line 107 of file OptionsCont.cpp.
References doRegister(), myDeprecatedSynonymes, and myValues.
Referenced by ROMAFrame::addAssignmentOptions(), SystemFrame::addConfigurationOptions(), RODUAFrame::addDUAOptions(), RODUAFrame::addImportOptions(), ROMAFrame::addImportOptions(), GeoConvHelper::addProjectionOptions(), SystemFrame::addReportOptions(), NGFrame::fillOptions(), RODFFrame::fillOptions(), AGFrame::fillOptions(), NIFrame::fillOptions(), ROJTRFrame::fillOptions(), NWFrame::fillOptions(), ROFrame::fillOptions(), NBFrame::fillOptions(), MSFrame::fillOptions(), fillOptions(), MSDevice::insertDefaultAssignmentOptions(), MSDevice_Routing::insertOptions(), RandHelper::insertRandOptions(), and main().
void OptionsCont::addXMLDefault (const std::string & name, const std::string & xmlRoot = "")
Adds an XML root element to handle by default. The special root "" denotes the default handler.
Parameters
[in] name The option name
[in] xmlRoot The name of the xml root element to handle
Definition at line 135 of file OptionsCont.cpp.
References myXMLDefaults.
Referenced by SystemFrame::addConfigurationOptions(), NIFrame::fillOptions(), and MSFrame::fillOptions().
bool OptionsCont::checkDependingSuboptions (const std::string & name, const std::string & prefix) const
Checks whether an option is set, which has options with a prefix depending on it.
The method returns true, if the named option is set or no option dependoing on it is set. Throws an InvalidArgument exception if the option is not known.
Parameters
[in] name The name of the option to check
[in] prefix The prefix of depending options
Returns
Whether the dependencies are fulfilled
Exceptions
InvalidArgument If the option does not exist
Definition at line 393 of file OptionsCont.cpp.
References getSecure(), getSynonymes(), Option::isSet(), myValues, and WRITE_ERROR.
Referenced by NIFrame::checkOptions().
void OptionsCont::clear ()
Removes all information from the container.
Definition at line 464 of file OptionsCont.cpp.
References myAddresses, mySubTopicEntries, mySubTopics, and myValues.
Referenced by SystemFrame::close(), GNELoadThread::fillOptions(), GNELoadThread::run(), GUILoadThread::run(), and ~OptionsCont().
void OptionsCont::clearCopyrightNotices ()
Removes all copyright information.
Definition at line 521 of file OptionsCont.cpp.
References myCopyrightNotices.
std::string OptionsCont::convertChar (char abbr) const private
Converts an abbreviation into a name.
Build and returns the string which consists of the given character only.
Parameters
[in] abbr The abbreviation to convert into a string
Returns
The abbreviation converted into a string
Definition at line 432 of file OptionsCont.cpp.
Referenced by doRegister(), and getFullName().
void OptionsCont::doRegister (const std::string & name, Option * v)
Adds an option under the given name.
Parameters
[in] name The (long) name of the option
[in] v The option (typed value storage)
Exceptions
InvalidArgument If the name is already used
Definition at line 86 of file OptionsCont.cpp.
References myAddresses, and myValues.
Referenced by ROMAFrame::addAssignmentOptions(), SystemFrame::addConfigurationOptions(), RODUAFrame::addDUAOptions(), RODUAFrame::addImportOptions(), ROMAFrame::addImportOptions(), GeoConvHelper::addProjectionOptions(), SystemFrame::addReportOptions(), addSynonyme(), doRegister(), NGFrame::fillOptions(), RODFFrame::fillOptions(), AGFrame::fillOptions(), NIFrame::fillOptions(), ROJTRFrame::fillOptions(), NWFrame::fillOptions(), ROFrame::fillOptions(), NBFrame::fillOptions(), MSFrame::fillOptions(), fillOptions(), GNELoadThread::fillOptions(), MSDevice::insertDefaultAssignmentOptions(), MSDevice_Example::insertOptions(), MSDevice_BTreceiver::insertOptions(), MSDevice_Routing::insertOptions(), RandHelper::insertRandOptions(), and main().
void OptionsCont::doRegister (const std::string & name, char abbr, Option * v)
Adds an option under the given name and the given abbreviation.
Adds the option under both names using void doRegister(const std::string &name, Option *v);
Parameters
[in] name The (long) name of the option
[in] abbr The (short) name of the option
[in] v The option (typed value storage)
Exceptions
InvalidArgument If one of the names is already used
Definition at line 100 of file OptionsCont.cpp.
References convertChar(), and doRegister().
bool OptionsCont::exists (const std::string & name) const
Returns the information whether the named option is known.
Returns
true if an option has been added before under the given name, false otherwise
Definition at line 141 of file OptionsCont.cpp.
References myValues.
Referenced by NBEdgeCont::applyOptions(), NBNetBuilder::compute(), NIImporter_OpenDrive::computeShapes(), MSDevice::equippedByDefaultAssignmentOptions(), NBNodeCont::guessTLs(), GeoConvHelper::init(), NBEdgeCont::insert(), OptionsIO::loadConfiguration(), NIImporter_OpenDrive::loadNetwork(), ROLoader::openTypedRoutes(), processMetaOptions(), NWWriter_XML::writeEdgesAndConnections(), and NWWriter_XML::writeNodes().
bool OptionsCont::getBool (const std::string & name) const
Returns the boolean-value of the named option (only for Option_Bool)
This method returns the boolean-value of an existing boolean-option. If the named option does not exist or is not a boolean-option, an InvalidArgument is thrown.
Parameters
[in] name The name of the option to return the boolean-value of
Returns
The boolean-value of the named, existing boolean-option
Exceptions
InvalidArgument If the option does not exist or is not a boolean-option
Definition at line 234 of file OptionsCont.cpp.
References Option::getBool(), and getSecure().
Referenced by NIImporter_SUMO::_loadNetwork(), NIXMLEdgesHandler::addEdge(), NIXMLNodesHandler::addNode(), NIXMLEdgesHandler::addSplit(), NBEdgeCont::applyOptions(), NLBuilder::build(), MSEdge::buildLaneChanger(), buildNetwork(), MELoop::buildSegmentsFor(), MSDevice_Routing::buildVehicleDevices(), NGFrame::checkOptions(), NIFrame::checkOptions(), NWFrame::checkOptions(), RODUAFrame::checkOptions(), NBFrame::checkOptions(), MSFrame::checkOptions(), RORouteHandler::closeFlow(), NBTrafficLightDefinition::collectEdges(), NBNetBuilder::compute(), computeAllPairs(), NBNode::computeLogic(), NBRampsComputer::computeRamps(), computeRoutes(), RODFDetector::computeSplitProbabilities(), NBOwnTLDef::correctConflicting(), SUMOVehicleParameter::defaultOptionOverrides(), GNELane::drawArrows(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), MSDevice::equippedByDefaultAssignmentOptions(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), NBRequest::getResponseString(), GNEAdditional::GNEAdditional(), NBNodeCont::guessTLs(), MSDevice_Vehroutes::init(), GeoConvHelper::init(), MSLane::initCollisionOptions(), MSAbstractLaneChangeModel::initGlobalOptions(), NBLoadedSUMOTLDef::initNeedsContRelation(), initNet(), MsgHandler::initOutputOptions(), RandHelper::initRandGlobal(), GNEDialog_Wizard::InputBool::InputBool(), NBEdgeCont::insert(), NILoader::load(), PCLoaderVisum::load(), PCLoaderArcView::load(), NIImporter_ArcView::load(), NIImporter_OpenStreetMap::load(), PCLoaderOSM::loadIfSet(), loadJTRDefinitions(), NIImporter_ArcView::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_DlrNavteq::loadNetwork(), NIImporter_OpenDrive::loadNetwork(), NIImporter_VISUM::loadNetwork(), PCLoaderDlrNavteq::loadPOIFile(), PCLoaderDlrNavteq::loadPolyFile(), main(), MSPModel_Striping::PState::moveToNextLane(), MSNet::MSNet(), NBLoadedTLDef::myCompute(), PCTypeDefHandler::myStartElement(), PCLoaderXML::myStartElement(), ROLoader::openRoutes(), ROLoader::openTypedRoutes(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Turns(), MSRouteHandler::parseFromViaTo(), RORouteHandler::parseFromViaTo(), NIXMLConnectionsHandler::parseLaneBound(), PCTypeMap::PCTypeMap(), NIImporter_Vissim::postLoadBuild(), RORouteDef::preComputeCurrentRoute(), processMetaOptions(), readDetectors(), RORouteDef::repairCurrentRoute(), RODFNet::RODFNet(), RouteCostCalculator< R, E, V >::RouteCostCalculator(), GNELoadThread::run(), GUILoadThread::run(), RONet::saveAndRemoveRoutesUntil(), ROVehicle::saveAsXML(), MSFrame::setMSGlobals(), startComputation(), GNEContainerStop::updateGeometry(), GNEBusStop::updateGeometry(), MSFCDExport::write(), NWWriter_SUMO::writeConnection(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_SUMO::writeNetwork(), NWWriter_XML::writeNodes(), and NWWriter_DlrNavteq::writeNodesUnsplitted().
SUMOReal OptionsCont::getFloat (const std::string & name) const
Returns the SUMOReal-value of the named option (only for Option_Float)
This method returns the SUMOReal-value of an existing SUMOReal-option. If the named option does not exist or is not a SUMOReal-option, an InvalidArgument is thrown.
Parameters
[in] name The name of the option to return the SUMOReal-value of
Returns
The SUMOReal-value of the named, existing SUMOReal-option
Exceptions
InvalidArgument If the option does not exist or is not a SUMOReal-option
Definition at line 220 of file OptionsCont.cpp.
References Option::getFloat(), and getSecure().
Referenced by NBEdgeCont::applyOptions(), NBNetBuilder::applyOptions(), NIVissimEdge::buildNBEdge(), buildNetwork(), MELoop::buildSegmentsFor(), MSDevice_Example::buildVehicleDevices(), MSDevice_BTreceiver::buildVehicleDevices(), MSDevice_Routing::buildVehicleDevices(), NBNode::checkCrossing(), MSFrame::checkOptions(), NBNetBuilder::compute(), NBTrafficLightDefinition::compute(), NBNodeShapeComputer::computeNodeShapeDefault(), NBRampsComputer::computeRamps(), computeRoutes(), RODFNet::computeRoutesFor(), NIImporter_OpenDrive::computeShapes(), MSDevice::equippedByDefaultAssignmentOptions(), METriggeredCalibrator::execute(), RouteCostCalculator< R, E, V >::getCalculator(), NIVissimDistrictConnection::getRealSpeed(), NBNodeCont::guessTLs(), GeoConvHelper::init(), GNEDialog_Wizard::InputFloat::InputFloat(), PCLoaderVisum::load(), PCLoaderArcView::load(), NIImporter_OpenStreetMap::load(), NIImporter_Vissim::load(), ODMatrix::loadMatrix(), NIImporter_MATSim::loadNetwork(), NIImporter_VISUM::loadNetwork(), PCLoaderDlrNavteq::loadPOIFile(), PCLoaderDlrNavteq::loadPolyFile(), NIImporter_Vissim::loadXML(), main(), MSPModel_Striping::MSPModel_Striping(), MSVehicleControl::MSVehicleControl(), PCTypeDefHandler::myStartElement(), PCNetProjectionLoader::myStartElement(), PCLoaderXML::myStartElement(), PCTypeMap::PCTypeMap(), PCPolyContainer::save(), MSFrame::setMSGlobals(), startComputation(), NGNet::toNB(), NBNetBuilder::transformCoordinates(), and NWWriter_MATSim::writeNetwork().
const std::string& OptionsCont::getFullName () const inline
Definition at line 656 of file OptionsCont.h.
References convertChar(), getSecure(), myFullName, reportDoubleSetting(), and splitLines().
Referenced by NWWriter_DlrNavteq::writeHeader().
int OptionsCont::getInt (const std::string & name) const
Returns the int-value of the named option (only for Option_Integer)
This method returns the int-value of an existing int-option. If the named option does not exist or is not a int-option, an InvalidArgument is thrown.
Parameters
[in] name The name of the option to return the int-value of
Returns
The int-value of the named, existing int-option
Exceptions
InvalidArgument If the option does not exist or is not a int-option
Definition at line 227 of file OptionsCont.cpp.
References Option::getInt(), and getSecure().
Referenced by NBNetBuilder::applyOptions(), NBEdge::buildInnerEdges(), buildNetwork(), MSDevice_BTreceiver::buildVehicleDevices(), MSDevice_Routing::buildVehicleDevices(), NBFrame::checkOptions(), ROFrame::checkOptions(), MSDevice_Routing::checkOptions(), NBTrafficLightDefinition::compute(), NBOwnTLDef::computeLogicAndConts(), NBNodeShapeComputer::computeNodeShapeDefault(), computeRoutes(), GeoConvHelper::init(), RandHelper::initRandGlobal(), GNEDialog_Wizard::InputInt::InputInt(), main(), MSNet::MSNet(), MSDevice_Routing::reroute(), RouteCostCalculator< R, E, V >::RouteCostCalculator(), RONet::saveAndRemoveRoutesUntil(), startComputation(), NWWriter_SUMO::writeNetwork(), and MSNet::writeOutput().
const IntVector & OptionsCont::getIntVector (const std::string & name) const
Returns the list of integer-value of the named option (only for Option_IntVector)
This method returns the int-vector-value of an existing int-vector-option. If the named option does not exist or is not a int-vector-option, an InvalidArgument is thrown.
Parameters
[in] name The name of the option to return the int-vector-value of
Returns
The int-vector-value of the named, existing int-vector-option
Exceptions
InvalidArgument If the option does not exist or is not a int-vector-option
Definition at line 241 of file OptionsCont.cpp.
References Option::getIntVector(), and getSecure().
Referenced by NLBuilder::buildNet().
OptionsCont & OptionsCont::getOptions () static
Retrieves the options.
Definition at line 69 of file OptionsCont.cpp.
References myOptions.
Referenced by MSDevice_Routing::adaptEdgeEfforts(), ODMatrix::add(), MSDetectorControl::add(), ROMAFrame::addAssignmentOptions(), MSDetectorControl::addDetectorAndInterval(), RODUAFrame::addDUAOptions(), NIImporter_SUMO::addEdge(), NLHandler::addEdgeLaneMeanData(), ROLoader::EdgeFloatTimeLineRetriever_EdgeWeight::addEdgeWeight(), ROLoader::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight(), RODUAFrame::addImportOptions(), ROMAFrame::addImportOptions(), NIXMLEdgesHandler::addLane(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NIXMLEdgesHandler::addSplit(), NBNodeCont::analyzeCluster(), NLBuilder::build(), NIVisumTL::build(), NBNode::buildCrossingsAndWalkingAreas(), NBEdge::buildInnerEdges(), MSEdge::buildLaneChanger(), NIVissimEdge::buildNBEdge(), NGNode::buildNBNode(), buildNetwork(), NLTriggerBuilder::buildVaporizer(), MSDevice_Tripinfo::buildVehicleDevices(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice_BTreceiver::buildVehicleDevices(), MSDevice_BTsender::buildVehicleDevices(), MSDevice_Vehroutes::buildVehicleDevices(), MSDevice_Emissions::buildVehicleDevices(), MSDevice_Routing::buildVehicleDevices(), OptionsParser::check(), NBNode::checkCrossing(), NGFrame::checkOptions(), NIFrame::checkOptions(), ROJTRFrame::checkOptions(), NWFrame::checkOptions(), RODUAFrame::checkOptions(), ROMAFrame::checkOptions(), NBFrame::checkOptions(), MSFrame::checkOptions(), checkOptions(), SystemFrame::close(), MSEdge::closeBuilding(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSNet::closeSimulation(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectEdges(), GNENet::computeEverything(), GNENet::computeJunction(), NBOwnTLDef::computeLogicAndConts(), NBNodeShapeComputer::computeNodeShapeDefault(), computeRoutes(), RODFNet::computeRoutesFor(), NIImporter_OpenDrive::computeShapes(), RODFDetector::computeSplitProbabilities(), NBOwnTLDef::correctConflicting(), OutputDevice::createDeviceByOption(), GNELane::drawArrows(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), MSDevice::equippedByDefaultAssignmentOptions(), MSTransportableControl::erase(), METriggeredCalibrator::execute(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), NGFrame::fillOptions(), RODFFrame::fillOptions(), AGFrame::fillOptions(), NIFrame::fillOptions(), ROJTRFrame::fillOptions(), RODUAFrame::fillOptions(), ROMAFrame::fillOptions(), NWFrame::fillOptions(), NBFrame::fillOptions(), MSFrame::fillOptions(), fillOptions(), MSDevice_Emissions::generateOutput(), MSDevice_Example::generateOutput(), MSDevice_Tripinfo::generateOutput(), MSDevice_Tripinfo::generateOutputForUnfinished(), RouteCostCalculator< R, E, V >::getCalculator(), HelpersPHEMlight::getClassByName(), OutputDevice::getDevice(), OutputDevice::getDeviceByOption(), NBEdge::getFinalLength(), MSPModel::getModel(), OptionsIO::getOptions(), GUINet::getParameterWindow(), NIVissimDistrictConnection::getRealSpeed(), NBRequest::getResponseString(), MSNet::getRouterTT(), GNEAdditional::GNEAdditional(), GNEChange_TLS::GNEChange_TLS(), GNEDialog_Wizard::GNEDialog_Wizard(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), MSDevice_Vehroutes::init(), GUIRunThread::init(), MSPhaseDefinition::init(), NBLoadedSUMOTLDef::initNeedsContRelation(), GNELoadThread::initOptions(), MsgHandler::initOutputOptions(), RandHelper::initRandGlobal(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), GNEDialog_Wizard::InputBool::InputBool(), GNEDialog_Wizard::InputFloat::InputFloat(), GNEDialog_Wizard::InputInt::InputInt(), GNEDialog_Wizard::InputString::InputString(), NBEdgeCont::insert(), NIImporter_OpenStreetMap::insertNodeChecking(), MSDevice_Emissions::insertOptions(), RandHelper::insertRandOptions(), PHEMCEPHandler::Load(), NLBuilder::load(), OptionsIO::loadConfiguration(), PCLoaderOSM::loadIfSet(), loadNet(), NIImporter_OpenDrive::loadNetwork(), PCLoaderDlrNavteq::loadPOIFile(), main(), GUIRunThread::makeStep(), MSPModel_Striping::PState::moveToNextLane(), MSNet::MSNet(), MSVehicleControl::MSVehicleControl(), NBLoadedTLDef::myCompute(), SUMORouteHandler::myEndElement(), PCNetProjectionLoader::myStartElement(), GUIApplicationWindow::onCmdNetedit(), GNEApplicationWindow::onCmdNewNetwork(), GNEApplicationWindow::onCmdOpenForeign(), GNEApplicationWindow::onCmdReload(), GNEApplicationWindow::onCmdSaveAsNetwork(), GNEApplicationWindow::onCmdSaveAsPlainXML(), GNEApplicationWindow::onCmdSaveJoined(), GNEApplicationWindow::onCmdSaveNetwork(), GNEDialog_Wizard::InputString::onCmdSetOption(), GNEDialog_Wizard::InputBool::onCmdSetOption(), GNEDialog_Wizard::InputInt::onCmdSetOption(), GNEDialog_Wizard::InputFloat::onCmdSetOption(), GNEApplicationWindow::onUpdReload(), GNEApplicationWindow::onUpdSaveNetwork(), TraCIServer::openSocket(), NIImporter_VISUM::parse_Connectors(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Edges(), NIImporter_VISUM::parse_Turns(), MSRouteHandler::parseFromViaTo(), RORouteHandler::parseFromViaTo(), NIXMLConnectionsHandler::parseLaneBound(), NIImporter_Vissim::postLoadBuild(), RORouteDef::preComputeCurrentRoute(), TraCIServer::processCommandsUntilSimStep(), ROLoader::processRoutes(), NIXMLNodesHandler::processTrafficLightDefinitions(), NBNodeCont::removeIsolatedRoads(), NBNodeCont::removeUnwishedNodes(), RORouteDef::repairCurrentRoute(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), MSDevice_Routing::reroute(), RODFNet::RODFNet(), ROMARouteHandler::ROMARouteHandler(), RouteCostCalculator< R, E, V >::RouteCostCalculator(), GNELoadThread::run(), GUILoadThread::run(), PCPolyContainer::save(), MSVehicleControl::scheduleVehicleRemoval(), GNEEdge::setAttribute(), NLHandler::setLocation(), MSNet::simulate(), MSNet::simulationState(), GUILane::splitAtSegments(), NGNet::toNB(), NBNetBuilder::transformCoordinates(), GNEContainerStop::updateGeometry(), GNEBusStop::updateGeometry(), MSFCDExport::write(), NWWriter_SUMO::writeConnection(), ODMatrix::writeDefaultAttrs(), RODFDetector::writeEmitterDefinition(), PlainXMLFormatter::writeHeader(), NWWriter_SUMO::writeJunction(), NBRequest::writeLaneResponse(), MSNet::writeOutput(), and PlainXMLFormatter::writeXMLHeader().
Option * OptionsCont::getSecure (const std::string & name) const private
Returns the named option.
If the named option does not exist, an InvalidArgument is thrown.
Parameters
[in] name The name of the option to return
Returns
The named option
Definition at line 185 of file OptionsCont.cpp.
References myDeprecatedSynonymes, mySubTopicEntries, myValues, and WRITE_WARNING.
Referenced by addDescription(), checkDependingSuboptions(), getBool(), getFloat(), getFullName(), getInt(), getIntVector(), getString(), getStringVector(), getSynonymes(), getTypeName(), isBool(), isUsableFileList(), isWriteable(), printHelp(), set(), setDefault(), writeConfiguration(), and writeSchema().
std::string OptionsCont::getString (const std::string & name) const
Returns the string-value of the named option (only for Option_String)
This method returns the string-value of an existing string-option. If the named option does not exist or is not a string-option, an InvalidArgument is thrown.
Parameters
[in] name The name of the option to return the string-value of
Returns
The string-value of the named, existing string-option
Exceptions
InvalidArgument If the option does not exist or is not a string-option
Definition at line 213 of file OptionsCont.cpp.
References getSecure(), Option::getString(), and SUMOReal.
Referenced by NBEdgeCont::applyOptions(), NLBuilder::build(), NGNode::buildNBNode(), NLBuilder::buildNet(), NLBuilder::buildRouteLoaderControl(), MELoop::buildSegmentsFor(), MSDevice_Routing::buildVehicleDevices(), NGFrame::checkOptions(), NIFrame::checkOptions(), ROJTRFrame::checkOptions(), NWFrame::checkOptions(), RODUAFrame::checkOptions(), ROMAFrame::checkOptions(), NBFrame::checkOptions(), MSFrame::checkOptions(), checkOptions(), MSNet::closeBuilding(), NBNetBuilder::compute(), computeAllPairs(), computeRoutes(), RouteCostCalculator< R, E, V >::getCalculator(), OutputDevice::getDevice(), OutputDevice::getDeviceByOption(), MSPModel::getModel(), MSNet::getRouterTT(), GeoConvHelper::init(), MSLane::initCollisionOptions(), initNet(), GNELoadThread::initOptions(), MsgHandler::initOutputOptions(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), GNEDialog_Wizard::InputString::InputString(), PHEMCEPHandler::Load(), PCLoaderVisum::load(), PCLoaderArcView::load(), NIImporter_ArcView::load(), NIImporter_Vissim::load(), OptionsIO::loadConfiguration(), ODMatrix::loadMatrix(), loadNet(), ROLoader::loadNet(), NIImporter_ArcView::loadNetwork(), NIImporter_DlrNavteq::loadNetwork(), NIImporter_Vissim::loadNetwork(), NIImporter_VISUM::loadNetwork(), PCLoaderDlrNavteq::loadPOIFile(), PCLoaderDlrNavteq::loadPolyFile(), NIImporter_Vissim::loadXML(), main(), MSNet::MSNet(), MSPModel_Striping::MSPModel_Striping(), MSVehicleControl::MSVehicleControl(), PCTypeDefHandler::myStartElement(), PCLoaderXML::myStartElement(), GUIApplicationWindow::onCmdNetedit(), GNEApplicationWindow::onCmdSaveAsPlainXML(), GNEApplicationWindow::onCmdSaveJoined(), GNEApplicationWindow::onUpdSaveNetwork(), RONet::openOutput(), ROLoader::openRoutes(), PCTypeMap::PCTypeMap(), processMetaOptions(), NIXMLNodesHandler::processTrafficLightDefinitions(), readDetectorFlows(), NBNodeCont::removeUnwishedNodes(), MSDevice_Routing::reroute(), GNELoadThread::run(), GUILoadThread::run(), MSFrame::setMSGlobals(), startComputation(), SUMOVehicleParameter::write(), ODMatrix::writeDefaultAttrs(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), NWWriter_XML::writeJoinedJunctions(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_Amitran::writeNetwork(), NWWriter_OpenDrive::writeNetwork(), NWWriter_MATSim::writeNetwork(), NWWriter_SUMO::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), MSNet::writeOutput(), NWWriter_XML::writeStreetSigns(), NWWriter_XML::writeTrafficLights(), NWWriter_DlrNavteq::writeTrafficSignals(), and NWWriter_XML::writeTypes().
std::vector< std::string > OptionsCont::getStringVector (const std::string & name) const
Returns the list of string-vector-value of the named option (only for Option_String)
This method returns the string-vector-value of an existing string-option. If the named option does not exist or is not a string-option, an InvalidArgument is thrown.
The string-value is determined, first. If the legacy-divider ';' is found within the string, a warning is generated. The retrieved string is splitted at ',' and ';'.
Parameters
[in] name The name of the option to return the string-vector-value of
Returns
The string-vector-value of the named, existing string-option
Exceptions
InvalidArgument If the option does not exist or is not a string-option
Todo:
Is it possible to retrieve a const-reference of the string?
See also
getString()
Definition at line 882 of file OptionsCont.cpp.
References getSecure(), Option::getString(), StringTokenizer::getVector(), myHaveInformedAboutDeprecatedDivider, StringUtils::prune(), and WRITE_WARNING.
Referenced by NIImporter_SUMO::_loadNetwork(), MSBaseVehicle::addStops(), NBTrafficLightLogicCont::applyOptions(), NBEdgeCont::applyOptions(), NLBuilder::build(), NLBuilder::buildNet(), NLBuilder::buildRouteLoaderControl(), NBNetBuilder::compute(), NBRampsComputer::computeRamps(), computeRoutes(), MSDevice::equippedByDefaultAssignmentOptions(), getTurningDefaults(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), isInStringVector(), isUsableFileList(), NILoader::load(), NLBuilder::load(), NIImporter_OpenStreetMap::load(), PCLoaderVisum::loadIfSet(), PCLoaderOSM::loadIfSet(), PCLoaderXML::loadIfSet(), PCLoaderArcView::loadIfSet(), NBHeightMapper::loadIfSet(), loadJTRDefinitions(), ODMatrix::loadMatrix(), ROLoader::loadNet(), NIImporter_RobocupRescue::loadNetwork(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_OpenDrive::loadNetwork(), PCLoaderDlrNavteq::loadPOIFiles(), PCLoaderDlrNavteq::loadPolyFiles(), ODMatrix::loadRoutes(), ROLoader::loadWeights(), NILoader::loadXML(), main(), ROLoader::openTypedRoutes(), readDetectorFlows(), readDetectors(), NBNodeCont::removeUnwishedNodes(), RODFNet::RODFNet(), ROMARouteHandler::ROMARouteHandler(), and GUILoadThread::run().
const std::vector<std::string>& OptionsCont::getSubTopics () const inline
return the list of subtopics
Definition at line 635 of file OptionsCont.h.
References mySubTopics.
Referenced by GNEDialog_Wizard::GNEDialog_Wizard().
std::vector<std::string> OptionsCont::getSubTopicsEntries (const std::string & subtopic) const inline
return the list of entries for the given subtopic
Definition at line 641 of file OptionsCont.h.
References mySubTopicEntries.
Referenced by GNEDialog_Wizard::GNEDialog_Wizard().
std::vector< std::string > OptionsCont::getSynonymes (const std::string & name) const
Returns the synonymes of an option name.
The named option is extracted, first. An InvalidArgument is thrown if it does not exist. Otherwise, other names for the named option are searched and returned (the original name is not in the list).
Parameters
[in] name The name of the option to return synonymes of
Returns
List of existing synonymes
Exceptions
InvalidArgument If the named option does not exist
Definition at line 289 of file OptionsCont.cpp.
References getSecure(), and myValues.
Referenced by checkDependingSuboptions(), operator<<(), printHelp(), reportDoubleSetting(), and writeConfiguration().
std::string OptionsCont::getTypeName (const std::string name) inline
return the type name for the given option
Definition at line 651 of file OptionsCont.h.
References getSecure(), and Option::getTypeName().
Referenced by GNEDialog_Wizard::GNEDialog_Wizard().
bool OptionsCont::isBool (const std::string & name) const
Returns the information whether the option is a boolean option.
The option is retrieved from the container, first, what may cause an InvalidArgument exception if it is not known. Otherwise, this option's isBool-method is called.
Parameters
[in] name The name of the option to check
Returns
Whether the existing named option is a bool option
Exceptions
InvalidArgument If the option does not exist
Definition at line 442 of file OptionsCont.cpp.
References getSecure(), and Option::isBool().
Referenced by OptionsParser::check().
bool OptionsCont::isDefault (const std::string & name) const
Returns the information whether the named option has still the default value.
The named option is tried to be retrieved from the container. If it does not exist, an InvalidArgument is thrown. If it could be retrieved, the information whether the option still has the default value is returned.
An option "is default" if no value has been set from the command line / the configuration file.
Returns
true if the option still has the default value
Exceptions
InvalidArgument If the named option is not known
Definition at line 175 of file OptionsCont.cpp.
References myValues.
Referenced by NIImporter_SUMO::_loadNetwork(), NIImporter_SUMO::addEdge(), NIXMLEdgesHandler::addEdge(), NLBuilder::build(), buildNetwork(), NIFrame::checkOptions(), NBFrame::checkOptions(), MSFrame::checkOptions(), MSDevice_Routing::checkOptions(), NBNetBuilder::compute(), GeoConvHelper::init(), main(), ROLoader::processRoutes(), GUILoadThread::run(), and NWWriter_SUMO::writeNetwork().
bool OptionsCont::isInStringVector (const std::string & optionName, const std::string & itemName)
Returns the named option is a list of string values containing the specified item.
If the named option is not set, false is returned. Otherwise, the string-vector of this option is retrieved using getStringVector what may throw an InvalidArgument exception if the named option is not a string option or not existing at all.
The given itemName is searched in the obtained string-vector and the method returns whether it is stored in the list or not.
Parameters
[in] optionName The name of the option to evaluate entries of
[in] itemName The item to be searched for in the entries of the named option
Returns
Whether the named item is set in the named string-option
Exceptions
InvalidArgument If the option does not exist or is not a string-option
See also
getStringVector()
Todo:
Try to optimize - at each call, the vector is rebuilt
Definition at line 899 of file OptionsCont.cpp.
References getStringVector(), and isSet().
Referenced by NBNode::computeLogic(), PCLoaderOSM::loadIfSet(), and PCLoaderXML::myStartElement().
bool OptionsCont::isSet (const std::string & name, bool failOnNonExistant = true) const
Returns the information whether the named option is set.
The named option is tried to be retrieved from the container. If it does not exist, an InvalidArgument is thrown. If it could be retrieved, the information whether the option has a value stored is returned.
An option "is set" if a default value was supplied or a value has been set from the command line / the configuration file.
Parameters
[in] name The name of the option to check
[in] failOnNonExistant Whether asking for an unregistered option should trigger an exception
Returns
true if the option has a valid value, false otherwise
Exceptions
InvalidArgument If the named option is not known
Definition at line 147 of file OptionsCont.cpp.
References myValues.
Referenced by MSBaseVehicle::addStops(), NBTrafficLightLogicCont::applyOptions(), NBEdgeCont::applyOptions(), NLBuilder::build(), NGNode::buildNBNode(), NLBuilder::buildNet(), NLBuilder::buildRouteLoaderControl(), MSDevice_Vehroutes::buildVehicleDevices(), MSDevice_Routing::buildVehicleDevices(), NGFrame::checkOptions(), NIFrame::checkOptions(), ROJTRFrame::checkOptions(), NWFrame::checkOptions(), RODUAFrame::checkOptions(), ROMAFrame::checkOptions(), NBFrame::checkOptions(), ROFrame::checkOptions(), MSFrame::checkOptions(), checkOptions(), NBNetBuilder::compute(), NBTrafficLightDefinition::compute(), NBRampsComputer::computeRamps(), computeRoutes(), NIImporter_OpenDrive::computeShapes(), SUMOVehicleParameter::defaultOptionOverrides(), MSDevice::equippedByDefaultAssignmentOptions(), MSDevice_BTreceiver::BTreceiverUpdate::execute(), NBNodeCont::guessTLs(), MSAbstractLaneChangeModel::initGlobalOptions(), initNet(), GNELoadThread::initOptions(), MsgHandler::initOutputOptions(), isInStringVector(), NILoader::load(), PCLoaderArcView::load(), NIImporter_ArcView::load(), NIImporter_OpenStreetMap::load(), OptionsIO::loadConfiguration(), PCLoaderVisum::loadIfSet(), PCLoaderOSM::loadIfSet(), PCLoaderXML::loadIfSet(), PCLoaderArcView::loadIfSet(), NBHeightMapper::loadIfSet(), PCLoaderDlrNavteq::loadIfSet(), loadJTRDefinitions(), ROLoader::loadNet(), NIImporter_RobocupRescue::loadNetwork(), NIImporter_ArcView::loadNetwork(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_DlrNavteq::loadNetwork(), NIImporter_OpenDrive::loadNetwork(), NIImporter_Vissim::loadNetwork(), NIImporter_VISUM::loadNetwork(), main(), MSVehicleControl::MSVehicleControl(), GNEApplicationWindow::onCmdSaveAsPlainXML(), GNEApplicationWindow::onCmdSaveJoined(), GNEApplicationWindow::onUpdSaveNetwork(), RONet::openOutput(), ROLoader::openTypedRoutes(), NIImporter_VISUM::parse_Turns(), processMetaOptions(), readDetectorFlows(), readDetectors(), NBNodeCont::removeUnwishedNodes(), MSDevice_Routing::reroute(), GUILoadThread::run(), MSFrame::setMSGlobals(), startComputation(), SUMOVehicleParameter::write(), ODMatrix::writeDefaultAttrs(), RODFDetector::writeEmitterDefinition(), NWWriter_Amitran::writeNetwork(), NWWriter_OpenDrive::writeNetwork(), NWWriter_DlrNavteq::writeNetwork(), NWWriter_MATSim::writeNetwork(), NWWriter_XML::writeNetwork(), NWWriter_SUMO::writeNetwork(), and MSNet::writeOutput().
bool OptionsCont::isUsableFileList (const std::string & name) const
Checks whether the named option is usable as a file list (with at least a single file)
The method returns true, if the named option is set with entries containing names of accessable files.
Throw an InvalidArgument exception if the option is not known. If the option is not set, false is returned. Also, if the list is empty (conatins delimiters only) or if one of the named files (obtained using getStringVector) does not exist, false is returned. Additionally, an error is sent to MsgHandler in both cases.
In the case two delimiters were placed in the option value directly after each other, a warning is generated.
Parameters
[in] name The name of the option to check
Returns
Whether the option contains names of files which can be accessed (for reading)
Exceptions
InvalidArgument If the option does not exist or is not a string-option
Definition at line 364 of file OptionsCont.cpp.
References getSecure(), getStringVector(), FileHelpers::isReadable(), Option::isSet(), WRITE_ERROR, and WRITE_WARNING.
Referenced by NIImporter_SUMO::_loadNetwork(), NLBuilder::build(), MSFrame::checkOptions(), NIImporter_OpenDrive::loadNetwork(), ROLoader::loadWeights(), and ROLoader::openTypedRoutes().
bool OptionsCont::isWriteable (const std::string & name)
Returns the information whether the named option may be set.
An option is writable after initialisation, but as soon as it gets set, it is no longer writeable. This method returns whether the named option is writeable. If the named option is not known, an InvalidArgument is thrown.
Parameters
[in] name The name of the option to check
Returns
Whether the value can be set
Exceptions
InvalidArgument If the option does not exist
Definition at line 457 of file OptionsCont.cpp.
References getSecure(), and Option::isWriteable().
Referenced by NIFrame::checkOptions(), and OptionsLoader::setSecure().
OptionsCont& OptionsCont::operator= (const OptionsCont & s) private
invalid assignment operator
Referenced by OptionsCont::abbreviation_finder::operator()().
void OptionsCont::printHelp (std::ostream & os)
Prints the help.
Parameters
[in] os The stream to write the help into
Definition at line 669 of file OptionsCont.cpp.
References Option::getDescription(), getSecure(), getSynonymes(), Option::getTypeName(), Option::isBool(), myAdditionalMessage, myAppDescription, myAppName, myCallExamples, mySubTopicEntries, mySubTopics, and splitLines().
Referenced by processMetaOptions().
bool OptionsCont::processMetaOptions (bool missingOptions)
Checks for help and configuration output, returns whether we should exit.
Returns false if no error was detected and the application may be executed (at least from this point of view). If missingOptions is true, the user is informed that they should be supplied (returns true). Otherwise it is checked whether help shall be printed what is done if so, returning true. Also, it is checked whether the set options shall be printed and the configuration template or the current configuration shall be written.
This method throws a ProcessError if the configuration should be saved, but the file is not accessable. An error message is supplied.
Parameters
[in] missingOptions Whether no options have been given
Returns
Whether the application shall stop
Exceptions
ProcessError If the configuration file could not be saved
Definition at line 565 of file OptionsCont.cpp.
References exists(), getBool(), getString(), HAVE_ENABLED, isSet(), myCopyrightNotices, myFullName, printHelp(), WRITE_MESSAGE, writeConfiguration(), and writeSchema().
Referenced by main().
void OptionsCont::relocateFiles (const std::string & configuration) const
Modifies file name options according to the configuration path.
If the configuration path given is a relative one all filenames inside are adapted such that they refer to the correct location.
Parameters
[in] configuration The path to the configuration file
Definition at line 336 of file OptionsCont.cpp.
References FileHelpers::getConfigurationRelative(), FileHelpers::isAbsolute(), myAddresses, StringTokenizer::next(), and StringUtils::urlDecode().
Referenced by OptionsIO::loadConfiguration().
void OptionsCont::reportDoubleSetting (const std::string & arg) const private
Reports an error that the option has already been set.
Using the given option name, an error string is generated and reported to MsgHandler-error instance.
Parameters
[in] name The name of the option that was already set
Definition at line 416 of file OptionsCont.cpp.
References getSynonymes(), and WRITE_ERROR.
Referenced by getFullName(), and set().
void OptionsCont::resetWritable ()
Resets all options to be writeable.
An option is writable after initialisation, but as soon as it gets set, it is no longer writeable. This method resets the writable-flag of all known options.
Definition at line 449 of file OptionsCont.cpp.
References myAddresses.
Referenced by OptionsIO::getOptions(), main(), GNEApplicationWindow::onCmdSaveAsNetwork(), GNEApplicationWindow::onCmdSaveAsPlainXML(), GNEApplicationWindow::onCmdSaveJoined(), GNEDialog_Wizard::InputString::onCmdSetOption(), GNEDialog_Wizard::InputBool::onCmdSetOption(), GNEDialog_Wizard::InputInt::onCmdSetOption(), GNEDialog_Wizard::InputFloat::onCmdSetOption(), GUILoadThread::run(), and GNEEdge::setAttribute().
bool OptionsCont::set (const std::string & name, const std::string & value)
Sets the given value for the named option.
The option is retrieved from the container, first, what yields in a InvalidArgument exception for not known options.
If the option is not writable (was set before), an error is generated using reportDoubleSetting, and false is returned. Otherwise, the option is told to set the given value using Option::set. Possible problems herein are caught and reported to the error-handler, yielding in returning false.
If the new value could be set, true is returned.
Parameters
[in] name The name of the option to set
[in] value The value to set
Returns
Whether the value could be set
Exceptions
InvalidArgument If the option does not exist
See also
reportDoubleSetting
Option::set(const std::string &)
Definition at line 248 of file OptionsCont.cpp.
References getSecure(), Option::isWriteable(), reportDoubleSetting(), Option::set(), and WRITE_ERROR.
Referenced by NIImporter_SUMO::_loadNetwork(), NIImporter_SUMO::addEdge(), NIXMLEdgesHandler::addEdge(), NLBuilder::build(), OptionsParser::check(), NIFrame::checkOptions(), RODUAFrame::checkOptions(), NBFrame::checkOptions(), MSFrame::checkOptions(), NBNetBuilder::compute(), GNELoadThread::initOptions(), main(), GNEApplicationWindow::onCmdOpenForeign(), GNEApplicationWindow::onCmdSaveAsNetwork(), GNEApplicationWindow::onCmdSaveAsPlainXML(), GNEApplicationWindow::onCmdSaveJoined(), GNEDialog_Wizard::InputString::onCmdSetOption(), GNEDialog_Wizard::InputBool::onCmdSetOption(), GNEDialog_Wizard::InputInt::onCmdSetOption(), GNEDialog_Wizard::InputFloat::onCmdSetOption(), OptionsParser::processNonBooleanSingleSwitch(), GUILoadThread::run(), GNEEdge::setAttribute(), GNELoadThread::setDefaultOptions(), and OptionsLoader::setSecure().
void OptionsCont::setAdditionalHelpMessage (const std::string & add)
Sets an additional message to be printed at the begin of the help screen.
Parameters
[in] example Some additional information about how to use the application
Definition at line 509 of file OptionsCont.cpp.
References myAdditionalMessage.
Referenced by fillOptions().
void OptionsCont::setApplicationDescription (const std::string & appDesc)
Sets the application description.
Parameters
[in] appDesc A description of the application
Definition at line 497 of file OptionsCont.cpp.
References myAppDescription.
Referenced by main().
void OptionsCont::setApplicationName (const std::string & appName, const std::string & fullName)
Sets the application name.
Parameters
[in] name The name of the excutable
[in] v The name of the executable with version information
Definition at line 489 of file OptionsCont.cpp.
References myAppName, and myFullName.
Referenced by main().
bool OptionsCont::setByRootElement (const std::string & name, const std::string & value)
Sets the given value for the option which can handle the given XML root.
The option is retrieved from the container, which yields in an InvalidArgument exception if no option is registered for the XML root. Then it uses the standard set method.
Parameters
[in] root The name of the XML root element to look for
[in] value The value to set
Returns
Whether the value could be set
Exceptions
InvalidArgument If the root element was not registered or the value could not be set
See also
OptionsCont::set(const std::string &, const std::string &)
Definition at line 277 of file OptionsCont.cpp.
References myXMLDefaults.
bool OptionsCont::setDefault (const std::string & name, const std::string & value)
Sets the given value for the named option as new default value.
The option is retrieved from the container, first, what yields in a InvalidArgument exception for not known options.
If the option is not writable (was set before), an error is generated using reportDoubleSetting, and false is returned. Otherwise, the option is told to set the given value using Option::set. Possible problems herein are caught and reported to the error-handler, yielding in returning false.
If the new value could be set, true is returned.
Parameters
[in] name The name of the option to set
[in] value The value to set
Returns
Whether the value could be set
Exceptions
InvalidArgument If the option does not exist
See also
reportDoubleSetting
Option::set(const std::string &)
Definition at line 267 of file OptionsCont.cpp.
References getSecure(), and Option::resetDefault().
Referenced by NIFrame::checkOptions(), NWFrame::checkOptions(), and main().
void OptionsCont::splitLines (std::ostream & os, std::string what, int offset, int nextOffset) private
Writes the given string 'formatted'.
The given string is split so that no word-wrapping occurs at line ends. The text is wrapped at ';' or ' '.
Parameters
[in] os The stream to write the text into
[in] what The text to write
[in] offset ?
[in] nextOffset ?
Todo:
Describe parameter
Definition at line 534 of file OptionsCont.cpp.
Referenced by getFullName(), and printHelp().
void OptionsCont::unSet (const std::string & name, bool failOnNonExistant = true) const
Marks the option as unset.
Parameters
[in] name The name of the option to check
[in] failOnNonExistant Whether asking for an unregistered option should trigger an exception
Definition at line 161 of file OptionsCont.cpp.
References myValues.
Referenced by NIImporter_OpenDrive::loadNetwork(), GNEApplicationWindow::onCmdSaveAsPlainXML(), and GNEApplicationWindow::onCmdSaveJoined().
void OptionsCont::writeConfiguration (std::ostream & os, bool filled, bool complete, bool addComments) const
Writes the configuration.
The configuration is written as XML into the given stream, allowing to reload it on a next run.
Parameters
[in] os The stream to write the configuration into
[in] filled Whether only set (and not default) options shall be written
[in] complete Whether all options shall be written
[in] addComments Whether comments (option descriptions) shall be written
Definition at line 760 of file OptionsCont.cpp.
References SUMOSAXAttributes::ENCODING, StringUtils::escapeXML(), Option::getDescription(), getSecure(), getSynonymes(), Option::getTypeName(), Option::getValueString(), Option::isDefault(), Option::isSet(), myAppName, mySubTopicEntries, and mySubTopics.
Referenced by processMetaOptions(), NWWriter_DlrNavteq::writeHeader(), and writeXMLHeader().
void OptionsCont::writeSchema (std::ostream & os, bool addComments)
Writes the xml schema for the configuration.
The schema for the configuration is written as XML into the given stream, allowing to validate the configuration against.
Parameters
[in] os The stream to write the schema into
[in] addComments Whether comments (option descriptions) shall be written
Definition at line 823 of file OptionsCont.cpp.
References SUMOSAXAttributes::ENCODING, getSecure(), Option::getTypeName(), mySubTopicEntries, and mySubTopics.
Referenced by processMetaOptions().
void OptionsCont::writeXMLHeader (std::ostream & os)
Writes a standard XML header, including the configuration.
The header consists of the xml-declaration with encoding as defined by SUMOSAXAttributes::ENCODING, followed by a note which contains the current date and time and the application configuration (set values).
Parameters
[in] os The stream to write the header into
Definition at line 868 of file OptionsCont.cpp.
References SUMOSAXAttributes::ENCODING, myFullName, and writeConfiguration().
Referenced by PlainXMLFormatter::writeHeader(), and PlainXMLFormatter::writeXMLHeader().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const OptionsCont & oc) friend
Output operator.
Generates the output used when current option values shall be printed.
Parameters
[in] os The stream to write into
[in] oc The options to print
Returns
The stream to write into
Definition at line 302 of file OptionsCont.cpp.
Field Documentation
std::string OptionsCont::myAdditionalMessage private
Definition at line 723 of file OptionsCont.h.
Referenced by printHelp(), and setAdditionalHelpMessage().
ItemAddressContType OptionsCont::myAddresses private
storage for option-addresses
Definition at line 717 of file OptionsCont.h.
Referenced by clear(), doRegister(), relocateFiles(), and resetWritable().
std::string OptionsCont::myAppDescription private
Definition at line 723 of file OptionsCont.h.
Referenced by printHelp(), and setApplicationDescription().
std::string OptionsCont::myAppName private
some information on the application
Definition at line 723 of file OptionsCont.h.
Referenced by printHelp(), setApplicationName(), and writeConfiguration().
std::vector< std::pair<std::string, std::string> > OptionsCont::myCallExamples private
list of call examples
Definition at line 726 of file OptionsCont.h.
Referenced by addCallExample(), and printHelp().
std::vector<std::string> OptionsCont::myCopyrightNotices private
Definition at line 729 of file OptionsCont.h.
Referenced by addCopyrightNotice(), clearCopyrightNotices(), OptionsCont(), and processMetaOptions().
std::map<std::string, bool> OptionsCont::myDeprecatedSynonymes mutable private
A map from deprecated options to a bool indicating whether we warned about deprecation.
Definition at line 738 of file OptionsCont.h.
Referenced by addSynonyme(), and getSecure().
std::string OptionsCont::myFullName private
Definition at line 723 of file OptionsCont.h.
Referenced by getFullName(), processMetaOptions(), setApplicationName(), and writeXMLHeader().
bool OptionsCont::myHaveInformedAboutDeprecatedDivider mutable private
Information whether a warning a deprecated divider.
Definition at line 741 of file OptionsCont.h.
Referenced by getStringVector().
OptionsCont OptionsCont::myOptions static private
The static options container used.
Definition at line 708 of file OptionsCont.h.
Referenced by getOptions().
std::map<std::string, std::vector<std::string> > OptionsCont::mySubTopicEntries private
A map from subtopic to option.
Definition at line 732 of file OptionsCont.h.
Referenced by addDescription(), addOptionSubTopic(), clear(), getSecure(), getSubTopicsEntries(), printHelp(), writeConfiguration(), and writeSchema().
std::vector<std::string> OptionsCont::mySubTopics private
lists of option subtopics and copyright notices
Definition at line 729 of file OptionsCont.h.
Referenced by addDescription(), addOptionSubTopic(), clear(), getSubTopics(), printHelp(), writeConfiguration(), and writeSchema().
KnownContType OptionsCont::myValues private
access map of options
Definition at line 720 of file OptionsCont.h.
Referenced by addSynonyme(), checkDependingSuboptions(), clear(), doRegister(), exists(), getSecure(), getSynonymes(), isDefault(), isSet(), operator<<(), and unSet().
std::map<std::string, std::string> OptionsCont::myXMLDefaults private
A map from XML root element to option.
Definition at line 735 of file OptionsCont.h.
Referenced by addXMLDefault(), and setByRootElement().
The documentation for this class was generated from the following files:
OptionsCont.h
OptionsCont.cpp