SUMO - Simulation of Urban MObility: NLJunctionControlBuilder Class Reference
NLJunctionControlBuilder Class Reference
Builder of microsim-junctions and tls.
#include <NLJunctionControlBuilder.h>
Public Member Functions
void addLogicItem (int request, const std::string &response, const std::string &foes, bool cont)
Adds a logic item.
void addParam (const std::string &key, const std::string &value)
Adds a parameter.
void addPhase (SUMOTime duration, const std::string &state, SUMOTime min, SUMOTime max)
Adds a phase to the currently built traffic lights logic.
void addPhase (SUMOTime duration, const std::string &state, SUMOTime minDuration, SUMOTime maxDuration, bool transient_notdecisional, bool commit) throw ()
Adds a phase to the currently built traffic lights logic.
void addPhase (SUMOTime duration, const std::string &state, SUMOTime minDuration, SUMOTime maxDuration, bool transient_notdecisional, bool commit, MSPhaseDefinition::LaneIdVector &targetLanes) throw ()
Adds a phase to the currently built traffic lights logic.
MSJunctionControl * build () const
Builds the MSJunctionControl which holds all of the simulations junctions.
MSTLLogicControl * buildTLLogics ()
Returns the built tls-logic control.
void closeJunction (const std::string &basePath)
Closes (ends) the processing of the current junction.
void closeJunctionLogic ()
Ends the building of a junction logic (row-logic)
virtual void closeTrafficLightLogic (const std::string &basePath)
Ends the building of a traffic lights logic.
const std::string & getActiveKey () const
Returns the active key.
const std::string & getActiveSubKey () const
Returns the active sub key.
int getNumberOfLoadedPhases () const
return the number of phases loaded so far (for error reporting)
MSTLLogicControl::TLSLogicVariants & getTLLogic (const std::string &id) const
Returns a previously build tls logic.
MSTLLogicControl & getTLLogicControlToUse () const
Returns the used tls control.
void initJunctionLogic (const std::string &id)
Initialises a junction logic.
void initTrafficLightLogic (const std::string &id, const std::string &programID, TrafficLightType type, SUMOTime offset)
Begins the reading of a traffic lights logic.
NLJunctionControlBuilder (MSNet &net, NLDetectorBuilder &db)
Constructor.
void openJunction (const std::string &id, const std::string &key, const SumoXMLNodeType type, SUMOReal x, SUMOReal y, const PositionVector &shape, const std::vector< MSLane * > &incomingLanes, const std::vector< MSLane * > &internalLanes)
Begins the processing of the named junction.
void postLoadInitialization ()
initialize junctions after all connections have been loaded
MSJunction * retrieve (const std::string id)
try to retrieve junction by id
virtual ~NLJunctionControlBuilder ()
Destructor.
Protected Types
typedef std::map< std::string, std::string > StringParameterMap
Definition of a parameter map (key->value)
Protected Member Functions
MSJunctionLogic * getJunctionLogicSecure ()
Returns the current junction logic.
Factory methods, virtual so that other versions of the structures can be built
virtual MSJunction * buildNoLogicJunction ()
Builds a junction that does not use a logic.
virtual MSJunction * buildLogicJunction ()
Builds a junction with a logic.
Protected Attributes
SUMOTime myAbsDuration
The absolute duration of a tls-control loop.
std::bitset< SUMO_MAX_CONNECTIONS > myActiveConts
The description about which lanes have an internal follower.
MSBitsetLogic::Foes myActiveFoes
The description about which lanes disallow other passing the junction simultaneously.
std::string myActiveID
The id of the currently chosen junction.
LaneVector myActiveIncomingLanes
The list of the incoming lanes of the currently chosen junction.
std::string myActiveKey
The key of the currently chosen junction.
MSBitsetLogic::Logic myActiveLogic
The right-of-way-logic of the currently chosen bitset-logic.
MSSimpleTrafficLightLogic::Phases myActivePhases
The current phase definitions for a simple traffic light.
std::string myActiveProgram
StringParameterMap myAdditionalParameter
Parameter map (key->value)
bool myCurrentHasError
Information whether the current logic had an error.
NLDetectorBuilder & myDetectorBuilder
The detector builder to use.
MSJunctionControl * myJunctions
The junctions controls.
MSTLLogicControl * myLogicControl
The tls control to use (0 if net's tls control shall be used)
std::map< std::string, MSJunctionLogic * > myLogics
Map of loaded junction logics.
std::vector< MSTrafficLightLogic * > myLogics2PostLoadInit
The container for information which junctions shall be initialised using which values.
TrafficLightType myLogicType
The current logic type.
MSNet & myNet
The net to use.
SUMOTime myOffset
The switch offset within the tls.
Position myPosition
The position of the junction.
int myRequestItemNumber
Counter for the inserted items.
int myRequestSize
The size of the request.
PositionVector myShape
The shape of the current junction.
SumoXMLNodeType myType
The type of the currently chosen junction.
Private Types
typedef std::vector< MSLane * > LaneVector
Definition of a lane vector.
Private Member Functions
NLJunctionControlBuilder (const NLJunctionControlBuilder &s)
invalidated copy operator
NLJunctionControlBuilder & operator= (const NLJunctionControlBuilder &s)
invalidated assignment operator
Private Attributes
bool myNetIsLoaded
whether the network has been loaded
Static Private Attributes
static const int NO_REQUEST_SIZE = -1
Detailed Description
Builder of microsim-junctions and tls.
NLJunctionControlBuilder is a factory for MSJunction, MSJunctionLogic, WAUT, and MSTRafficLightLogic-instances.
Todo:
Refactor this class - it's too large
Resort method by one of the topics.
Definition at line 70 of file NLJunctionControlBuilder.h.
Member Typedef Documentation
typedef std::vector<MSLane*> NLJunctionControlBuilder::LaneVector private
Definition of a lane vector.
Definition at line 73 of file NLJunctionControlBuilder.h.
typedef std::map<std::string, std::string> NLJunctionControlBuilder::StringParameterMap protected
Definition of a parameter map (key->value)
Definition at line 418 of file NLJunctionControlBuilder.h.
Constructor & Destructor Documentation
NLJunctionControlBuilder::NLJunctionControlBuilder (MSNet & net, NLDetectorBuilder & db)
Constructor.
Stores default values for extended tls reading them from the given options. Builds a MSTLLogicControl instance for myLogicControl.
Parameters
[in] net The network to fill
[in] db The detector builder to use
Definition at line 82 of file NLJunctionControlBuilder.cpp.
References myJunctions, and myLogicControl.
NLJunctionControlBuilder::~NLJunctionControlBuilder () virtual
Destructor.
Deletes previously allocated "myLogicControl" and "myJunctions" if they were not previously returned (this may happen if an error occured).
Definition at line 93 of file NLJunctionControlBuilder.cpp.
References myJunctions, and myLogicControl.
NLJunctionControlBuilder::NLJunctionControlBuilder (const NLJunctionControlBuilder & s) private
invalidated copy operator
Member Function Documentation
void NLJunctionControlBuilder::addLogicItem (int request, const std::string & response, const std::string & foes, bool cont)
Adds a logic item.
Adds a logic item to the current processed logic. Throws an InvalidArgument if the current request size (myRequestSize) is 0 or lower.
Parameters
[in] request The request (~link) index
[in] response The response (list of higher priorised links)
[in] foes List of foes to the request
[in] cont Whether the request is followed by an internal end
Todo:
Recheck "cont"; is the description correct?
Definition at line 366 of file NLJunctionControlBuilder.cpp.
References myActiveConts, myActiveFoes, myActiveKey, myActiveLogic, myCurrentHasError, myRequestItemNumber, myRequestSize, NO_REQUEST_SIZE, SUMO_MAX_CONNECTIONS, and toString().
Referenced by NLHandler::addRequest().
void NLJunctionControlBuilder::addParam (const std::string & key, const std::string & value)
Adds a parameter.
Parameters
[in] key The key of the parameter
[in] value The value of the parameter
Todo:
Where are these parameter used? Describe!
Can a parameter be overwritten?
Definition at line 485 of file NLJunctionControlBuilder.cpp.
References myAdditionalParameter.
Referenced by NLHandler::addParam().
void NLJunctionControlBuilder::addPhase (SUMOTime duration, const std::string & state, SUMOTime min, SUMOTime max)
Adds a phase to the currently built traffic lights logic.
Parameters
[in] duration The duration of the phase
[in] state The state of the tls
[in] min The minimum duration of the phase
[in] max The maximum duration of the phase
Todo:
min/max is used only by one junction type. Recheck
min/max: maybe only one type of a phase definition should be built
Definition at line 439 of file NLJunctionControlBuilder.cpp.
References myAbsDuration, and myActivePhases.
Referenced by NLHandler::addPhase().
void NLJunctionControlBuilder::addPhase (SUMOTime duration, const std::string & state, SUMOTime minDuration, SUMOTime maxDuration, bool transient_notdecisional, bool commit) throw ()
Adds a phase to the currently built traffic lights logic.
Parameters
[in] duration The duration of the phase
[in] state The state of the tls
[in] minDuration The minimum duration of the phase
[in] maxDuration The maximum duration of the phase
[in] transient_notdecisional Specifies if this is a transient phase (true) or a decisional one (false)
[in] commit Specifies if this is a commit phase
Definition at line 422 of file NLJunctionControlBuilder.cpp.
References myAbsDuration, and myActivePhases.
void NLJunctionControlBuilder::addPhase (SUMOTime duration, const std::string & state, SUMOTime minDuration, SUMOTime maxDuration, bool transient_notdecisional, bool commit, MSPhaseDefinition::LaneIdVector & targetLanes) throw ()
Adds a phase to the currently built traffic lights logic.
Parameters
[in] duration The duration of the phase
[in] state The state of the tls
[in] minDuration The minimum duration of the phase
[in] maxDuration The maximum duration of the phase
[in] transient_notdecisional Specifies if this is a transient phase (true) or a decisional one (false)
[in] commit Specifies if this is a commit phase
[in] targetLanes A reference to the vector containing targeted sensor lanes for this phase, given by lane id
Definition at line 430 of file NLJunctionControlBuilder.cpp.
References myAbsDuration, and myActivePhases.
MSJunctionControl * NLJunctionControlBuilder::build () const
Builds the MSJunctionControl which holds all of the simulations junctions.
Returns the previously built junction control ("myJunctions"). "myJunctions" is set to 0, so that it will not be destroyed by the destructor.
Returns
The built junction control
Definition at line 172 of file NLJunctionControlBuilder.cpp.
References myJunctions.
Referenced by NLBuilder::buildNet().
MSJunction * NLJunctionControlBuilder::buildLogicJunction () protected virtual
Builds a junction with a logic.
Builds a MSRightOfWayJunction. Throws an exception if the logic was not built (see getJunctionLogicSecure).
Returns
The built junction
Exceptions
InvalidArgument If the logic of the junction was not built before
Definition at line 190 of file NLJunctionControlBuilder.cpp.
References getJunctionLogicSecure(), HAVE_INTERNAL_LANES, myActiveID, myActiveIncomingLanes, myPosition, myShape, and myType.
Referenced by closeJunction(), and getNumberOfLoadedPhases().
MSJunction * NLJunctionControlBuilder::buildNoLogicJunction () protected virtual
Builds a junction that does not use a logic.
Builds a MSNoLogicJunction
Returns
The built junction
Definition at line 180 of file NLJunctionControlBuilder.cpp.
References HAVE_INTERNAL_LANES, myActiveID, myActiveIncomingLanes, myPosition, myShape, and myType.
Referenced by closeJunction(), and getNumberOfLoadedPhases().
MSTLLogicControl * NLJunctionControlBuilder::buildTLLogics ()
Returns the built tls-logic control.
Returns the junction control ("myLogicControl") built using MSTLLogicControl::closeNetworkReading. "myLogicControl" is set to 0, so that it will not be destroyed by the destructor.
Returns
The built tls-logic control
Exceptions
ProcessError If the traffic lights were not correct
See also
MSTLLogicControl::closeNetworkReading
Definition at line 473 of file NLJunctionControlBuilder.cpp.
References MSTLLogicControl::closeNetworkReading(), myLogicControl, and postLoadInitialization().
Referenced by NLBuilder::buildNet().
void NLJunctionControlBuilder::closeJunction (const std::string & basePath)
Closes (ends) the processing of the current junction.
This method throws an InvalidArgument when a junction with the same id as the current was already added or if the junction type stored in "myType" is invalid. It throws a ProcessError if the container to store the junction in was not built before.
Exceptions
InvalidArgument If the current id is already used or the junction type was invalid
ProcessError If the container to store the junction in was not built before
Todo:
Throwing ProcessError would get unneeded if the container would be built by default (see prepare)
The type of the junctions shoould probably be checked when supprted (in openJunction)
Definition at line 122 of file NLJunctionControlBuilder.cpp.
References NamedObjectCont< T >::add(), buildLogicJunction(), buildNoLogicJunction(), closeTrafficLightLogic(), MSGlobals::gUsingInternalLanes, myActiveID, myActiveKey, myActiveProgram, myJunctions, myLogicType, myOffset, myType, NODETYPE_ALLWAY_STOP, NODETYPE_DEAD_END, NODETYPE_DEAD_END_DEPRECATED, NODETYPE_DISTRICT, NODETYPE_INTERNAL, NODETYPE_NOJUNCTION, NODETYPE_PRIORITY, NODETYPE_PRIORITY_STOP, NODETYPE_RAIL_CROSSING, NODETYPE_RAIL_SIGNAL, NODETYPE_RIGHT_BEFORE_LEFT, NODETYPE_TRAFFIC_LIGHT, NODETYPE_TRAFFIC_LIGHT_NOJUNCTION, NODETYPE_TRAFFIC_LIGHT_RIGHT_ON_RED, NODETYPE_ZIPPER, and TLTYPE_RAIL.
Referenced by NLHandler::myEndElement().
void NLJunctionControlBuilder::closeJunctionLogic ()
Ends the building of a junction logic (row-logic)
Rechecks values for the request and builds a MSJunctionLogic using these values. Throws and InvalidArgument if the values are invalid (error message is included). Tries to add the built logic to the internal container "myLogics". If another logic with the same id exists, an InvalidArgument is thrown.
Exceptions
InvalidArgument If the logic's values are false or another logic with the same id was built before
Definition at line 449 of file NLJunctionControlBuilder.cpp.
References myActiveConts, myActiveFoes, myActiveKey, myActiveLogic, myCurrentHasError, myLogics, myRequestItemNumber, myRequestSize, and NO_REQUEST_SIZE.
Referenced by NLHandler::myEndElement().
void NLJunctionControlBuilder::closeTrafficLightLogic (const std::string & basePath) virtual
Ends the building of a traffic lights logic.
Builds the correct type of a MSTrafficLightLogic using the stored information. Tries to add it to the used tls control. Throws an InvalidArgument if this is not possible (another tls logic with the same name exists).
Exceptions
InvalidArgument If another tls logic with the same name as the currently built was loaded before
Definition at line 228 of file NLJunctionControlBuilder.cpp.
References MSTrafficLightLogic::changeStepAndDuration(), DELTA_T, MSTLLogicControl::get(), MSNet::getCurrentTimeStep(), MSTrafficLightLogic::getDefaultCycleTime(), MSTrafficLightLogic::getPhases(), getTLLogicControlToUse(), MSTrafficLightLogic::init(), myAbsDuration, myActiveKey, myActivePhases, myActiveProgram, myAdditionalParameter, myDetectorBuilder, myLogics2PostLoadInit, myLogicType, myNet, myNetIsLoaded, myOffset, myType, NODETYPE_RAIL_CROSSING, NODETYPE_RAIL_SIGNAL, TLTYPE_ACTUATED, TLTYPE_HILVL_DETERMINISTIC, TLTYPE_INVALID, TLTYPE_RAIL, TLTYPE_SOTL_MARCHING, TLTYPE_SOTL_PHASE, TLTYPE_SOTL_PLATOON, TLTYPE_SOTL_REQUEST, TLTYPE_SOTL_WAVE, TLTYPE_STATIC, TLTYPE_SWARM_BASED, toString(), and WRITE_ERROR.
Referenced by closeJunction(), and NLHandler::myEndElement().
const std::string & NLJunctionControlBuilder::getActiveKey () const
Returns the active key.
Returns
The active key
Definition at line 501 of file NLJunctionControlBuilder.cpp.
References myActiveKey.
Referenced by NLHandler::addPhase().
const std::string & NLJunctionControlBuilder::getActiveSubKey () const
Returns the active sub key.
Returns
The active sub key
Definition at line 507 of file NLJunctionControlBuilder.cpp.
References myActiveProgram.
Referenced by NLHandler::addPhase().
MSJunctionLogic * NLJunctionControlBuilder::getJunctionLogicSecure () protected
Returns the current junction logic.
"Current" means the one with "myActiveID". If it is not built yet (not within "myLogics") an InvalidArgument is thrown.
Returns
The current tls logic
Exceptions
InvalidArgument If the logic was not built before
Todo:
Where is this used?
Definition at line 212 of file NLJunctionControlBuilder.cpp.
References myActiveID, and myLogics.
Referenced by buildLogicJunction(), and getNumberOfLoadedPhases().
int NLJunctionControlBuilder::getNumberOfLoadedPhases () const inline
return the number of phases loaded so far (for error reporting)
Definition at line 294 of file NLJunctionControlBuilder.h.
References buildLogicJunction(), buildNoLogicJunction(), getJunctionLogicSecure(), and myActivePhases.
Referenced by NLHandler::addPhase().
MSTLLogicControl::TLSLogicVariants & NLJunctionControlBuilder::getTLLogic (const std::string & id) const
Returns a previously build tls logic.
Parameters
[in] id The ID of the tls logic to return
Returns
The named logic
Exceptions
InvalidArgument If the named tls logic was not built before
Definition at line 222 of file NLJunctionControlBuilder.cpp.
References MSTLLogicControl::get(), and getTLLogicControlToUse().
Referenced by NLHandler::addConnection(), and NLHandler::addE2Detector().
MSTLLogicControl & NLJunctionControlBuilder::getTLLogicControlToUse () const
Returns the used tls control.
This may be either the internal one ("myLogicControl"), or, if the network has been already loaded and we are loading additional tls programs, the net's logic control.
Returns
The tls control to use
Definition at line 492 of file NLJunctionControlBuilder.cpp.
References MSNet::getTLSControl(), myLogicControl, and myNet.
Referenced by NLHandler::addWAUTJunction(), NLHandler::addWAUTSwitch(), closeTrafficLightLogic(), NLHandler::closeWAUT(), getTLLogic(), NLHandler::initTrafficLightLogic(), and NLHandler::openWAUT().
void NLJunctionControlBuilder::initJunctionLogic (const std::string & id)
Initialises a junction logic.
Parameters
[in] id The id of the row-logic
Definition at line 353 of file NLJunctionControlBuilder.cpp.
References myActiveConts, myActiveFoes, myActiveKey, myActiveLogic, myActiveProgram, myCurrentHasError, myRequestItemNumber, myRequestSize, and NO_REQUEST_SIZE.
Referenced by NLHandler::initJunctionLogic().
void NLJunctionControlBuilder::initTrafficLightLogic (const std::string & id, const std::string & programID, TrafficLightType type, SUMOTime offset)
Begins the reading of a traffic lights logic.
Parameters
[in] id The id of the tls
[in] programID The id of the currently loaded program
[in] type The type of the tls
[in] offset The offset to start with
Todo:
Why is the type not verified?
Recheck, describe usage of detectorOffset (where does the information come from?)
Definition at line 408 of file NLJunctionControlBuilder.cpp.
References myAbsDuration, myActiveKey, myActivePhases, myActiveProgram, myAdditionalParameter, myLogicType, myOffset, myRequestSize, and NO_REQUEST_SIZE.
Referenced by NLHandler::initTrafficLightLogic().
void NLJunctionControlBuilder::openJunction (const std::string & id, const std::string & key, const SumoXMLNodeType type, SUMOReal x, SUMOReal y, const PositionVector & shape, const std::vector< MSLane * > & incomingLanes, const std::vector< MSLane * > & internalLanes)
Begins the processing of the named junction.
Parameters
[in] id The ID of the junction
[in] key unused?!
[in] type The type of the junction
[in] x x-position of the junction
[in] y y-position of the junction
[in] shape The shape of the junction
[in] incomingLanes List of lanes which end at this intersection
[in] internalLanes List of internal lanes across this intersection
Exceptions
InvalidArgument If the junction type is not known
Todo:
Check why "key" is given
Definition at line 100 of file NLJunctionControlBuilder.cpp.
References myActiveID, myActiveIncomingLanes, myActiveKey, myPosition, myShape, myType, Position::set(), and UNUSED_PARAMETER.
Referenced by NLHandler::openJunction().
NLJunctionControlBuilder& NLJunctionControlBuilder::operator= (const NLJunctionControlBuilder & s) private
invalidated assignment operator
void NLJunctionControlBuilder::postLoadInitialization ()
initialize junctions after all connections have been loaded
Definition at line 513 of file NLJunctionControlBuilder.cpp.
References myDetectorBuilder, myLogics2PostLoadInit, and myNetIsLoaded.
Referenced by buildTLLogics().
MSJunction * NLJunctionControlBuilder::retrieve (const std::string id)
try to retrieve junction by id
Definition at line 523 of file NLJunctionControlBuilder.cpp.
References NamedObjectCont< T >::get(), and myJunctions.
Referenced by NLHandler::myEndElement().
Field Documentation
SUMOTime NLJunctionControlBuilder::myAbsDuration protected
The absolute duration of a tls-control loop.
Definition at line 403 of file NLJunctionControlBuilder.h.
Referenced by addPhase(), closeTrafficLightLogic(), and initTrafficLightLogic().
std::bitset<SUMO_MAX_CONNECTIONS> NLJunctionControlBuilder::myActiveConts protected
The description about which lanes have an internal follower.
Definition at line 368 of file NLJunctionControlBuilder.h.
Referenced by addLogicItem(), closeJunctionLogic(), and initJunctionLogic().
MSBitsetLogic::Foes NLJunctionControlBuilder::myActiveFoes protected
The description about which lanes disallow other passing the junction simultaneously.
Definition at line 365 of file NLJunctionControlBuilder.h.
Referenced by addLogicItem(), closeJunctionLogic(), and initJunctionLogic().
std::string NLJunctionControlBuilder::myActiveID protected
The id of the currently chosen junction.
Definition at line 391 of file NLJunctionControlBuilder.h.
Referenced by buildLogicJunction(), buildNoLogicJunction(), closeJunction(), getJunctionLogicSecure(), and openJunction().
LaneVector NLJunctionControlBuilder::myActiveIncomingLanes protected
The list of the incoming lanes of the currently chosen junction.
Definition at line 383 of file NLJunctionControlBuilder.h.
Referenced by buildLogicJunction(), buildNoLogicJunction(), and openJunction().
std::string NLJunctionControlBuilder::myActiveKey protected
The key of the currently chosen junction.
Definition at line 394 of file NLJunctionControlBuilder.h.
Referenced by addLogicItem(), closeJunction(), closeJunctionLogic(), closeTrafficLightLogic(), getActiveKey(), initJunctionLogic(), initTrafficLightLogic(), and openJunction().
MSBitsetLogic::Logic NLJunctionControlBuilder::myActiveLogic protected
The right-of-way-logic of the currently chosen bitset-logic.
Definition at line 362 of file NLJunctionControlBuilder.h.
Referenced by addLogicItem(), closeJunctionLogic(), and initJunctionLogic().
MSSimpleTrafficLightLogic::Phases NLJunctionControlBuilder::myActivePhases protected
The current phase definitions for a simple traffic light.
Definition at line 371 of file NLJunctionControlBuilder.h.
Referenced by addPhase(), closeTrafficLightLogic(), getNumberOfLoadedPhases(), and initTrafficLightLogic().
std::string NLJunctionControlBuilder::myActiveProgram protected
Definition at line 394 of file NLJunctionControlBuilder.h.
Referenced by closeJunction(), closeTrafficLightLogic(), getActiveSubKey(), initJunctionLogic(), and initTrafficLightLogic().
StringParameterMap NLJunctionControlBuilder::myAdditionalParameter protected
Parameter map (key->value)
Definition at line 421 of file NLJunctionControlBuilder.h.
Referenced by addParam(), closeTrafficLightLogic(), and initTrafficLightLogic().
bool NLJunctionControlBuilder::myCurrentHasError protected
Information whether the current logic had an error.
Definition at line 428 of file NLJunctionControlBuilder.h.
Referenced by addLogicItem(), closeJunctionLogic(), and initJunctionLogic().
NLDetectorBuilder& NLJunctionControlBuilder::myDetectorBuilder protected
The detector builder to use.
Definition at line 353 of file NLJunctionControlBuilder.h.
Referenced by closeTrafficLightLogic(), and postLoadInitialization().
MSJunctionControl* NLJunctionControlBuilder::myJunctions mutable protected
The junctions controls.
Definition at line 380 of file NLJunctionControlBuilder.h.
Referenced by build(), closeJunction(), NLJunctionControlBuilder(), retrieve(), and ~NLJunctionControlBuilder().
MSTLLogicControl* NLJunctionControlBuilder::myLogicControl mutable protected
The tls control to use (0 if net's tls control shall be used)
Definition at line 414 of file NLJunctionControlBuilder.h.
Referenced by buildTLLogics(), getTLLogicControlToUse(), NLJunctionControlBuilder(), and ~NLJunctionControlBuilder().
std::map<std::string, MSJunctionLogic*> NLJunctionControlBuilder::myLogics protected
Map of loaded junction logics.
Definition at line 425 of file NLJunctionControlBuilder.h.
Referenced by closeJunctionLogic(), and getJunctionLogicSecure().
std::vector<MSTrafficLightLogic*> NLJunctionControlBuilder::myLogics2PostLoadInit protected
The container for information which junctions shall be initialised using which values.
Definition at line 410 of file NLJunctionControlBuilder.h.
Referenced by closeTrafficLightLogic(), and postLoadInitialization().
TrafficLightType NLJunctionControlBuilder::myLogicType protected
The current logic type.
Definition at line 359 of file NLJunctionControlBuilder.h.
Referenced by closeJunction(), closeTrafficLightLogic(), and initTrafficLightLogic().
MSNet& NLJunctionControlBuilder::myNet protected
The net to use.
Definition at line 350 of file NLJunctionControlBuilder.h.
Referenced by closeTrafficLightLogic(), and getTLLogicControlToUse().
bool NLJunctionControlBuilder::myNetIsLoaded private
whether the network has been loaded
Definition at line 441 of file NLJunctionControlBuilder.h.
Referenced by closeTrafficLightLogic(), and postLoadInitialization().
SUMOTime NLJunctionControlBuilder::myOffset protected
The switch offset within the tls.
Definition at line 356 of file NLJunctionControlBuilder.h.
Referenced by closeJunction(), closeTrafficLightLogic(), and initTrafficLightLogic().
Position NLJunctionControlBuilder::myPosition protected
The position of the junction.
Definition at line 400 of file NLJunctionControlBuilder.h.
Referenced by buildLogicJunction(), buildNoLogicJunction(), and openJunction().
int NLJunctionControlBuilder::myRequestItemNumber protected
Counter for the inserted items.
Definition at line 377 of file NLJunctionControlBuilder.h.
Referenced by addLogicItem(), closeJunctionLogic(), and initJunctionLogic().
int NLJunctionControlBuilder::myRequestSize protected
The size of the request.
Definition at line 374 of file NLJunctionControlBuilder.h.
Referenced by addLogicItem(), closeJunctionLogic(), initJunctionLogic(), and initTrafficLightLogic().
PositionVector NLJunctionControlBuilder::myShape protected
The shape of the current junction.
Definition at line 406 of file NLJunctionControlBuilder.h.
Referenced by buildLogicJunction(), buildNoLogicJunction(), and openJunction().
SumoXMLNodeType NLJunctionControlBuilder::myType protected
The type of the currently chosen junction.
Definition at line 397 of file NLJunctionControlBuilder.h.
Referenced by buildLogicJunction(), buildNoLogicJunction(), closeJunction(), closeTrafficLightLogic(), and openJunction().
const int NLJunctionControlBuilder::NO_REQUEST_SIZE = -1 static private
Definition at line 438 of file NLJunctionControlBuilder.h.
Referenced by addLogicItem(), closeJunctionLogic(), initJunctionLogic(), and initTrafficLightLogic().
The documentation for this class was generated from the following files:
NLJunctionControlBuilder.h
NLJunctionControlBuilder.cpp