SUMO - Simulation of Urban MObility: NBContHelper::relative_outgoing_edge_sorter Class Reference
NBContHelper::relative_outgoing_edge_sorter Class Reference
#include <NBContHelper.h>
Public Member Functions
int operator() (NBEdge *e1, NBEdge *e2) const
comparing operation
relative_outgoing_edge_sorter (NBEdge *e)
constructor
Private Attributes
NBEdge * myEdge
the edge to compute the relative angle of
Detailed Description
relative_outgoing_edge_sorter Class to sort edges by their angle in relation to the node the edge using this class is incoming into. This is normally done to sort edges outgoing from the node the using edge is incoming in by their angle in relation to the using edge's angle (this angle is the reference angle).
Definition at line 84 of file NBContHelper.h.
Constructor & Destructor Documentation
NBContHelper::relative_outgoing_edge_sorter::relative_outgoing_edge_sorter (NBEdge * e) inline explicit
constructor
Definition at line 87 of file NBContHelper.h.
References operator()().
Member Function Documentation
int NBContHelper::relative_outgoing_edge_sorter::operator() (NBEdge * e1, NBEdge * e2) const
comparing operation
Definition at line 151 of file NBContHelper.cpp.
References NBEdge::ANGLE_LOOKAHEAD, Position::angleTo2D(), NBEdge::getFromNode(), NBEdge::getGeometry(), NBEdge::getLength(), NBNode::getPosition(), NBEdge::getStartAngle(), GeomHelper::legacyDegree(), MAX2(), NBHelpers::normRelAngle(), PositionVector::positionAtOffset2D(), and SUMOReal.
Referenced by NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::edge_by_angle_to_nodeShapeCentroid_sorter(), NBContHelper::relative_incoming_edge_sorter::relative_incoming_edge_sorter(), relative_outgoing_edge_sorter(), and NBContHelper::straightness_sorter::straightness_sorter().
Field Documentation
NBEdge* NBContHelper::relative_outgoing_edge_sorter::myEdge private
the edge to compute the relative angle of
Definition at line 95 of file NBContHelper.h.
The documentation for this class was generated from the following files:
NBContHelper.h
NBContHelper.cpp