SUMO - Simulation of Urban MObility: GNELane Class Reference
GNELane Class Reference
This lane is powered by an underlying GNEEdge and basically knows how to draw itself.
#include <GNELane.h>
Public Types
typedef std::vector< GNEAdditionalSet * > AdditionalSetVector
Definition of the additionalSets vector.
typedef std::vector< GNEAdditional * > AdditionalVector
FOX-declaration.
Public Member Functions
void addAdditional (GNEAdditional *additional)
bool addAdditionalSet (GNEAdditionalSet *additionalSet)
add GNEAdditionalSet to this lane
void decRef (const std::string &debugMsg="")
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawName (const Position &pos, const SUMOReal scale, const GUIVisualizationTextSettings &settings, const SUMOReal angle=0) const
draw name of item
const std::vector< GNEAdditional * > & getAdditionals () const
method to obtain a list of additional elements associated to this lane
const std::vector< GNEAdditionalSet * > & getAdditionalSets ()
return list of additionalSets associated with this lane
std::vector< SumoXMLAttr > getAttrs () const
get vector of attributes
Boundary getBoundary () const
returns the boundry (including lanes)
template<>
int getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
SUMOReal getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
bool getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::string getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< int > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< SUMOReal > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< bool > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
template<>
std::vector< std::string > getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
virtual std::string getDescription ()
how should this attribute carrier be called
const std::string getID () const
function to support debugging
int getIndex () const
returns the index of the lane
SUMOReal getLaneParametricLenght () const
returns the parameteric length of the lane
SUMOReal getLaneShapeLenght () const
returns the length of the lane's shape
GNENet * getNet () const
Returns the NetElement's geometry.
SUMOReal getPositionRelativeToParametricLenght (SUMOReal position) const
SUMOReal getPositionRelativeToShapeLenght (SUMOReal position) const
const PositionVector & getShape () const
returns the shape of the lane
const std::vector< SUMOReal > & getShapeLengths () const
returns the vector with the shape lengths
const std::vector< SUMOReal > & getShapeRotations () const
returns the vector with the shape rotations
SUMOReal getSpeed () const
returns the current speed of lane
SumoXMLTag getTag () const
get Tag assigned to this object
GNELane (GNEEdge &edge, const int index)
Constructor.
void incRef (const std::string &debugMsg="")
template<>
int parse (const std::string &string)
template<>
SUMOReal parse (const std::string &string)
template<>
bool parse (const std::string &string)
bool removeAdditional (GNEAdditional *additional)
bool removeAdditionalSet (GNEAdditionalSet *additionalSet)
remove GNEAdditionalSet from this lane
void setIndex (int index)
void setSpecialColor (const RGBColor *Color2)
bool unreferenced ()
void updateGeometry ()
update pre-computed geometry information
~GNELane ()
Destructor.
inherited from GUIGlObject
const std::string & getParentName () const
Returns the name of the parent object (if any)
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
long onDefault (FXObject *, FXSelector, void *)
multiplexes message to two targets
GNEEdge & getParentEdge ()
Returns underlying parent edge.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
inherited from GNEAttributeCarrier
std::string getAttribute (SumoXMLAttr key) const
void setAttribute (SumoXMLAttr key, const std::string &value, GNEUndoList *undoList)
bool isValid (SumoXMLAttr key, const std::string &value)
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window (optional)
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static const std::vector< SumoXMLTag > & allowedAdditionalTags ()
get all editable tags for additionals
static const std::vector< std::pair< SumoXMLAttr, std::string > > & allowedAttributes (SumoXMLTag tag)
get all editable attributes for tag and their default values.
static const std::vector< SumoXMLTag > & allowedNetElementTags ()
get all editable tags for netElements
static const std::vector< SumoXMLTag > & allowedTags ()
get all editable for tag.
template<typename T >
static bool canParse (const std::string &string)
true if a number of type T can be parsed from string
static const std::vector< std::string > & discreteChoices (SumoXMLTag tag, SumoXMLAttr attr)
return a list of discrete choices for this attribute or an empty vector
static bool discreteCombinableChoices (SumoXMLTag tag, SumoXMLAttr attr)
return whether the given attribute allows for a combination of discrete values
template<typename T >
static T getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr)
return the default value of the attribute of an element
static std::string getDefinition (SumoXMLTag tag, SumoXMLAttr attr)
return definition of a certain SumoXMLAttr
static int getHigherNumberOfAttributes ()
return the number of attributes of the tag with the most highter number of attributes
static SumoXMLTag getParentType (SumoXMLTag tag)
get parent's tag of a certain additional element
static bool hasAttribute (SumoXMLTag tag, SumoXMLAttr attr)
check if a element with certain tag has a certain attribute
static bool hasParent (SumoXMLTag tag)
check if a element with certain tag has another additional element as parent
static bool isBool (SumoXMLAttr attr)
whether an attribute is of type bool
static bool isDiscrete (SumoXMLTag tag, SumoXMLAttr attr)
whether an attribute is Discrete
static bool isFloat (SumoXMLAttr attr)
whether an attribute is numerical of type float
static bool isInt (SumoXMLAttr attr)
whether an attribute is numerical or type int
static bool isList (SumoXMLAttr attr)
whether an attribute is of type bool
static bool isNumerical (SumoXMLAttr attr)
whether an attribute is numerical (int or float)
template<typename T >
static bool isPositive (const std::string &string)
true if a positive number of type T can be parsed from string
static bool isString (SumoXMLAttr attr)
whether an attribute is of type string
static bool isUnique (SumoXMLAttr attr)
whether an attribute is unique (may not be edited for a multi-selection)
static bool isValidFileValue (const std::string &value)
true if value is a valid file value
static bool isValidID (const std::string &value)
true if value is a valid sumo ID
static bool isValidStringVector (const std::string &value)
true if value is a valid string vector
template<typename T >
static T parse (const std::string &string)
parses a number of type T from string
Static Public Attributes
static const std::string APPROVED = "approved"
feature has been approved but not changed (i.e. after being reguessed)
static const std::string GUESSED = "guessed"
feature has been reguessed (may still be unchanged be we can't tell (yet)
static const GUIGlID INVALID_ID = 0
static const std::string LOADED = "loaded"
feature is still unchanged after being loaded (implies approval)
static const std::string MODIFIED = "modified"
feature has been manually modified (implies approval)
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
GNELane ()
FOX needs this.
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
AdditionalVector myAdditionals
list with the additonals vinculated with this lane
AdditionalSetVector myAdditionalSets
list with the additonalSets vinculated with this lane
int myIndex
The index of this lane.
GNENet * myNet
the net to inform about updates
GNEEdge & myParentEdge
The Edge that to which this lane belongs.
std::vector< RGBColor > myShapeColors
The color of the shape parts (cached)
const RGBColor * mySpecialColor
optional special color
GNETLSEditorFrame * myTLSEditor
the tls-editor for setting multiple links in TLS-mode
computed only once (for performance) in updateGeometry()
The rotations of the shape parts
std::vector< SUMOReal > myShapeRotations
std::vector< SUMOReal > myShapeLengths
The lengths of the shape parts.
Private Member Functions
void drawArrows () const
draw arrows
bool drawAsRailway (const GUIVisualizationSettings &s) const
whether to draw this lane as a railway
bool drawAsWaterway (const GUIVisualizationSettings &s) const
whether to draw this lane as a waterways
void drawCrossties (SUMOReal length, SUMOReal spacing, SUMOReal halfWidth) const
draw crossties for railroads
void drawDirectionIndicators () const
direction indicators for lanes
void drawLane2LaneConnections () const
draw lane to lane connections
void drawLinkNo () const
draw link Number
void drawLinkRules () const
draw link rules
void drawMarkings (const bool &selectedEdge, SUMOReal scale) const
draw lane markings
void drawTLSLinkNo () const
draw TLS Link Number
SUMOReal getColorValue (int activeScheme) const
return value for lane coloring according to the given scheme
GNELane (const GNELane &)
Invalidated copy constructor.
GNELane & operator= (const GNELane &)
Invalidated assignment operator.
void setAttribute (SumoXMLAttr key, const std::string &value)
set attribute after validation
bool setFunctionalColor (int activeScheme) const
sets the color according to the current scheme index and some lane function
bool setMultiColor (const GUIColorer &c) const
sets multiple colors according to the current scheme index and some lane function
Detailed Description
This lane is powered by an underlying GNEEdge and basically knows how to draw itself.
Definition at line 54 of file GNELane.h.
Member Typedef Documentation
typedef std::vector<GNEAdditionalSet*> GNELane::AdditionalSetVector
Definition of the additionalSets vector.
Definition at line 63 of file GNELane.h.
typedef std::vector<GNEAdditional*> GNELane::AdditionalVector
FOX-declaration.
Definition of the additionals vector
Definition at line 60 of file GNELane.h.
Constructor & Destructor Documentation
GNELane::GNELane (GNEEdge & edge, const int index)
Constructor.
Parameters
[in] idStorage The storage of gl-ids to get the one for this lane representation from
[in] the edge this lane belongs to
[in] the index of this lane
Definition at line 77 of file GNELane.cpp.
GNELane::~GNELane ()
Destructor.
Definition at line 95 of file GNELane.cpp.
References myAdditionals.
GNELane::GNELane () protected
FOX needs this.
Definition at line 86 of file GNELane.cpp.
GNELane::GNELane (const GNELane &) private
Invalidated copy constructor.
Member Function Documentation
void GNELane::addAdditional (GNEAdditional * additional)
Definition at line 542 of file GNELane.cpp.
References myAdditionals.
Referenced by GNEStoppingPlace::changeLane(), GNEDetector::changeLane(), GNEDetector::GNEDetector(), and GNEStoppingPlace::GNEStoppingPlace().
bool GNELane::addAdditionalSet (GNEAdditionalSet * additionalSet)
add GNEAdditionalSet to this lane
Definition at line 567 of file GNELane.cpp.
References myAdditionalSets.
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 258 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedAdditionalTags () static inherited
get all editable tags for additionals
Definition at line 391 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedAdditionalTags, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VAPORIZER, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::GNEAdditionalFrame(), GNEAdditionalFrame::onCmdSelectAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
const std::vector< std::pair< SumoXMLAttr, std::string > > & GNEAttributeCarrier::allowedAttributes (SumoXMLTag tag) static inherited
get all editable attributes for tag and their default values.
Definition at line 186 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, SUMO_ATTR_ALLOW, SUMO_ATTR_BEGIN, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CONT, SUMO_ATTR_CONTPOS, SUMO_ATTR_DISALLOW, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_END, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_LANE, SUMO_ATTR_LANES, SUMO_ATTR_LENGTH, SUMO_ATTR_LINES, SUMO_ATTR_NAME, SUMO_ATTR_NUMLANES, SUMO_ATTR_OFF, SUMO_ATTR_OUTPUT, SUMO_ATTR_PASS, SUMO_ATTR_POSITION, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_SHAPE, SUMO_ATTR_SPEED, SUMO_ATTR_SPLIT_VTYPE, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_STARTTIME, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_TYPE, SUMO_ATTR_UNCONTROLLED, SUMO_ATTR_WIDTH, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_POI, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VAPORIZER, SUMO_TAG_VSS, toString(), and WRITE_WARNING.
Referenced by GNEAttributeCarrier::getAttrs(), GNEAttributeCarrier::getHigherNumberOfAttributes(), GNEAttributeCarrier::hasAttribute(), GNESelectorFrame::onCmdSelMBString(), GNESelectorFrame::onCmdSelMBTag(), GNEAdditionalFrame::setParametersOfAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedNetElementTags () static inherited
get all editable tags for netElements
Definition at line 378 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedNetElementTags, SUMO_TAG_CONNECTION, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, and SUMO_TAG_LANE.
Referenced by GNEAttributeCarrier::~GNEAttributeCarrier().
const std::vector< SumoXMLTag > & GNEAttributeCarrier::allowedTags () static inherited
get all editable for tag.
Definition at line 352 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedTags, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, SUMO_TAG_VAPORIZER, and SUMO_TAG_VSS.
Referenced by GNEAttributeCarrier::getHigherNumberOfAttributes(), GNESelectorFrame::GNESelectorFrame(), GNEAttributeCarrier::isBool(), GNESelectorFrame::onCmdSelMBString(), GNESelectorFrame::onCmdSelMBTag(), and GNEAttributeCarrier::~GNEAttributeCarrier().
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 187 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 196 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 177 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GNECrossing::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 237 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 206 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 249 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 219 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 228 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIBaseVehicle::getPopUpMenu().
template<typename T > static bool GNEAttributeCarrier::canParse (const std::string & string) inline static inherited
true if a number of type T can be parsed from string
Definition at line 168 of file GNEAttributeCarrier.h.
References GNEAttributeCarrier::parse().
void GNEReferenceCounter::decRef (const std::string & debugMsg = "") inline inherited
Definition at line 61 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), GNEReferenceCounter::myCount, toString(), and UNUSED_PARAMETER.
Referenced by GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GNEEdge::removeLane(), GNEInspectorFrame::setEdgeTemplate(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_Connection::~GNEChange_Connection(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_TLS::~GNEChange_TLS(), and GNEInspectorFrame::~GNEInspectorFrame().
const std::vector< std::string > & GNEAttributeCarrier::discreteChoices (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return a list of discrete choices for this attribute or an empty vector
Definition at line 548 of file GNEAttributeCarrier.cpp.
References StringBijection< T >::getStrings(), SUMOXMLDefinitions::LaneSpreadFunctions, GNEAttributeCarrier::myDiscreteChoices, NODETYPE_DEAD_END_DEPRECATED, SUMOXMLDefinitions::NodeTypes, SUMO_ATTR_ALLOW, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CONT, SUMO_ATTR_DISALLOW, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_OFF, SUMO_ATTR_PRIORITY, SUMO_ATTR_SPLIT_VTYPE, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_TYPE, SUMO_ATTR_UNCONTROLLED, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CROSSING, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_REROUTER, SumoVehicleClassStrings, and toString().
Referenced by GNEInspectorFrame::AttrEditor::AttrEditor(), GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isDiscrete(), GNEInspectorFrame::AttrEditor::onCmdReset(), GNEInspectorFrame::AttrInput::onCmdSetAttribute(), GNEInspectorFrame::AttrInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::discreteCombinableChoices (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return whether the given attribute allows for a combination of discrete values
Definition at line 602 of file GNEAttributeCarrier.cpp.
References SUMO_ATTR_ALLOW, and SUMO_ATTR_DISALLOW.
Referenced by GNEInspectorFrame::AttrInput::onCmdSetAttribute(), GNEInspectorFrame::AttrInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
void GNELane::drawArrows () const private
draw arrows
Definition at line 119 of file GNELane.cpp.
References GLHelper::drawBoxLine(), GLHelper::drawOutlineCircle(), GLHelper::drawTriangleAtEnd(), OptionsCont::getBool(), NBNode::getDirection(), GNEEdge::getNBEdge(), OptionsCont::getOptions(), getShape(), GLO_JUNCTION, LINKDIR_LEFT, LINKDIR_NODIR, LINKDIR_PARTLEFT, LINKDIR_PARTRIGHT, LINKDIR_RIGHT, LINKDIR_STRAIGHT, LINKDIR_TURN, LINKDIR_TURN_LEFTHAND, NBEdge::myConnections, myIndex, myParentEdge, NBEdge::myTo, PI, SUMOReal, Position::x(), and Position::y().
Referenced by drawGL().
bool GNELane::drawAsRailway (const GUIVisualizationSettings & s) const private
whether to draw this lane as a railway
Definition at line 793 of file GNELane.cpp.
References GNEEdge::getNBEdge(), NBEdge::getPermissions(), isRailway(), myIndex, myParentEdge, and GUIVisualizationSettings::showRails.
Referenced by drawGL().
bool GNELane::drawAsWaterway (const GUIVisualizationSettings & s) const private
whether to draw this lane as a waterways
Definition at line 799 of file GNELane.cpp.
References GNEEdge::getNBEdge(), NBEdge::getPermissions(), isWaterway(), myIndex, myParentEdge, and GUIVisualizationSettings::showRails.
void GNELane::drawCrossties (SUMOReal length, SUMOReal spacing, SUMOReal halfWidth) const private
draw crossties for railroads
Todo:
: XXX This duplicates the code of GUILane::drawCrossties and needs to be
Definition at line 805 of file GNELane.cpp.
References getShape(), myShapeLengths, myShapeRotations, and SUMOReal.
Referenced by drawGL().
void GNELane::drawDirectionIndicators () const private
direction indicators for lanes
Definition at line 829 of file GNELane.cpp.
References NBEdge::getLaneWidth(), GNEEdge::getNBEdge(), getShape(), GLO_JUNCTION, MIN2(), myIndex, myParentEdge, myShapeLengths, myShapeRotations, and SUMOReal.
Referenced by drawGL().
void GNELane::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GNENetElement.
Definition at line 239 of file GNELane.cpp.
References drawArrows(), drawAsRailway(), GLHelper::drawBoxLines(), drawCrossties(), drawDirectionIndicators(), GLHelper::drawLine(), drawMarkings(), GUIPropertySchemeStorage< T >::getActive(), GUIPropertyScheme< T >::getColor(), GLHelper::getColor(), getColorValue(), GNEEdge::getDest(), GUIGlObject::getGlID(), NBEdge::getLaneWidth(), GNEEdge::getNBEdge(), GUIPropertySchemeStorage< T >::getScheme(), getShape(), GUIGlObject::getType(), gSelected, GNEJunction::isLogicValid(), GUISelectedStorage::isSelected(), GUIVisualizationSettings::laneColorer, GUIVisualizationSettings::laneMinSize, GUIVisualizationSettings::laneWidthExaggeration, myIndex, myParentEdge, myShapeColors, myShapeLengths, myShapeRotations, mySpecialColor, GUIVisualizationSettings::scale, GNENet::selectedLaneColor, GNENet::selectionColor, GUIVisualizationSettings::selectionScale, GLHelper::setColor(), setFunctionalColor(), setMultiColor(), GUIVisualizationSettings::showLaneDirection, and SUMOReal.
void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIBaseVehicle, GUIPerson, and GUIContainer.
Definition at line 156 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
void GNELane::drawLane2LaneConnections () const private
draw lane to lane connections
Definition at line 189 of file GNELane.cpp.
References GLHelper::drawTriangleAtEnd(), NBEdge::getConnectionsFromLane(), NBNode::getLinkState(), GNEEdge::getNBEdge(), getShape(), NBEdge::getToNode(), GLO_JUNCTION, LINKSTATE_ALLWAY_STOP, LINKSTATE_EQUAL, LINKSTATE_MAJOR, LINKSTATE_MINOR, LINKSTATE_STOP, LINKSTATE_TL_OFF_BLINKING, LINKSTATE_TL_OFF_NOSIGNAL, LINKSTATE_ZIPPER, myIndex, myParentEdge, SUMOReal, toString(), Position::x(), and Position::y().
void GNELane::drawLinkNo () const private
draw link Number
Definition at line 104 of file GNELane.cpp.
void GNELane::drawLinkRules () const private
draw link rules
Definition at line 114 of file GNELane.cpp.
void GNELane::drawMarkings (const bool & selectedEdge, SUMOReal scale) const private
draw lane markings
Definition at line 326 of file GNELane.cpp.
References GLHelper::drawBoxLines(), NBEdge::getLaneWidth(), GNEEdge::getNBEdge(), NBEdge::getPermissions(), getShape(), getShapeLengths(), getShapeRotations(), GLO_EDGE, MIN2(), myIndex, myParentEdge, myShapeLengths, myShapeRotations, GNENet::selectionColor, GLHelper::setColor(), SUMO_const_laneOffset, and SUMOReal.
Referenced by drawGL().
void GUIGlObject::drawName (const Position & pos, const SUMOReal scale, const GUIVisualizationTextSettings & settings, const SUMOReal angle = 0) const inherited
draw name of item
Definition at line 286 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE3::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GUIPolygon::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GNERouteProbe::drawGL(), GNEEdge::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIEdge::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GNERerouter::drawGL(), and GUIBaseVehicle::drawOnPos().
void GNELane::drawTLSLinkNo () const private
draw TLS Link Number
Definition at line 109 of file GNELane.cpp.
const std::vector< GNEAdditional * > & GNELane::getAdditionals () const
method to obtain a list of additional elements associated to this lane
Returns
set with all additional elements
Definition at line 561 of file GNELane.cpp.
References myAdditionals.
const std::vector< GNEAdditionalSet * > & GNELane::getAdditionalSets ()
return list of additionalSets associated with this lane
Definition at line 595 of file GNELane.cpp.
References myAdditionalSets.
std::string GNELane::getAttribute (SumoXMLAttr key) const virtual
Implements GNENetElement.
Definition at line 601 of file GNELane.cpp.
References NBEdge::Lane::endOffset, NBEdge::getLaneSpeed(), NBEdge::getLaneStruct(), GUIGlObject::getMicrosimID(), GNEEdge::getNBEdge(), NBEdge::getPermissions(), getVehicleClassNames(), myIndex, myParentEdge, SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_SPEED, SUMO_ATTR_WIDTH, toString(), and NBEdge::Lane::width.
Referenced by GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorE2::getAttribute(), GNEBusStop::getAttribute(), GNEContainerStop::getAttribute(), and GNEChargingStation::getAttribute().
std::vector< SumoXMLAttr > GNEAttributeCarrier::getAttrs () const inherited
get vector of attributes
Definition at line 107 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), and GNEAttributeCarrier::myTag.
Referenced by GNEAdditional::getParameterWindow(), GNEAdditional::getPopUpMenu(), GNEAttributeCarrier::isValid(), and GNEAttributeCarrier::~GNEAttributeCarrier().
Boundary GNELane::getBoundary () const
returns the boundry (including lanes)
Definition at line 442 of file GNELane.cpp.
References PositionVector::getBoxBoundary(), NBEdge::getLaneStruct(), GNEEdge::getNBEdge(), myIndex, myParentEdge, and NBEdge::Lane::shape.
Boundary GNELane::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GNENetElement.
Definition at line 448 of file GNELane.cpp.
References PositionVector::getBoxBoundary(), getShape(), and Boundary::grow().
SUMOReal GNELane::getColorValue (int activeScheme) const private
return value for lane coloring according to the given scheme
Definition at line 741 of file GNELane.cpp.
References GUIGlObject::getGlID(), NBEdge::getLaneSpeed(), NBEdge::getLength(), NBEdge::getLoadedLength(), GNEEdge::getNBEdge(), NBEdge::getNumLanes(), NBEdge::getPermissions(), NBEdge::getPriority(), getShape(), GUIGlObject::getType(), GLO_EDGE, gSelected, isRailway(), GUISelectedStorage::isSelected(), myIndex, myParentEdge, SUMOReal, SVC_BICYCLE, SVC_PASSENGER, SVC_PEDESTRIAN, and SVC_SHIP.
Referenced by drawGL().
template<typename T > static T GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return the default value of the attribute of an element
Note
It's advisable to check before with function hasDefaultValue if exits a default value
Referenced by GNEAdditionalFrame::additionalParameters::addAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
template<> int GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 752 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, TplConvert::_str2int(), SUMOReal, toString(), and WRITE_WARNING.
template<> SUMOReal GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 765 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, TplConvert::_str2SUMOReal(), toString(), and WRITE_WARNING.
template<> bool GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 778 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, TplConvert::_str2Bool(), toString(), and WRITE_WARNING.
template<> std::string GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 791 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, toString(), and WRITE_WARNING.
template<> std::vector<int> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 804 of file GNEAttributeCarrier.cpp.
References toString(), and WRITE_WARNING.
template<> std::vector<SUMOReal> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 814 of file GNEAttributeCarrier.cpp.
References toString(), and WRITE_WARNING.
template<> std::vector<bool> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 824 of file GNEAttributeCarrier.cpp.
References toString(), and WRITE_WARNING.
template<> std::vector<std::string> GNEAttributeCarrier::getDefaultValue (SumoXMLTag tag, SumoXMLAttr attr) inherited
Definition at line 834 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::_allowedAttributes, SUMOSAXAttributes::parseStringVector(), toString(), and WRITE_WARNING.
std::string GNEAttributeCarrier::getDefinition (SumoXMLTag tag, SumoXMLAttr attr) static inherited
return definition of a certain SumoXMLAttr
Definition at line 608 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAttrDefinitions, SUMO_ATTR_ALLOW, SUMO_ATTR_BEGIN, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_CHARGEINTRANSIT, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CONT, SUMO_ATTR_CONTPOS, SUMO_ATTR_DISALLOW, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_LANE, SUMO_ATTR_LANES, SUMO_ATTR_LENGTH, SUMO_ATTR_LINES, SUMO_ATTR_NAME, SUMO_ATTR_NUMLANES, SUMO_ATTR_OFF, SUMO_ATTR_OUTPUT, SUMO_ATTR_PASS, SUMO_ATTR_POSITION, SUMO_ATTR_PREFER, SUMO_ATTR_PRIORITY, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_SHAPE, SUMO_ATTR_SPEED, SUMO_ATTR_SPLIT_VTYPE, SUMO_ATTR_SPREADTYPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_TYPE, SUMO_ATTR_UNCONTROLLED, SUMO_ATTR_WIDTH, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_CROSSING, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_POI, SUMO_TAG_REROUTER, SUMO_TAG_ROUTEPROBE, and SUMO_TAG_VSS.
Referenced by GNEAdditionalFrame::additionalParameters::onCmdHelp(), and GNEAttributeCarrier::~GNEAttributeCarrier().
std::string GNEAttributeCarrier::getDescription () virtual inherited
how should this attribute carrier be called
Definition at line 95 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myTag, and toString().
Referenced by GNEChange_Attribute::redoName(), GNEAdditionalFrame::removeAdditional(), GNEChange_Attribute::undoName(), and GNEAttributeCarrier::~GNEAttributeCarrier().
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 111 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 123 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GUIVehicle::drawAction_drawPersonsAndContainers(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE3::drawGL(), GNEInternalLane::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GNERouteProbe::drawGL(), drawGL(), GNEEdge::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), GUIEdge::drawGL(), GNEConnection::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GNERerouter::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GUIContainer::getColorValue(), GNEJunction::getColorValue(), GUIPerson::getColorValue(), getColorValue(), GUILane::getColorValue(), GUIEdge::getIDs(), GNEEdge::getLaneGlIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNECalibrator::GNECalibrator(), GNERouteProbe::GNERouteProbe(), GNEVaporizer::GNEVaporizer(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onLeftBtnPress(), GUISUMOAbstractView::removeAdditionalGLVisualisation(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUIVehicle::selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), and GUIGlObject::~GUIGlObject().
int GNEAttributeCarrier::getHigherNumberOfAttributes () static inherited
return the number of attributes of the tag with the most highter number of attributes
Definition at line 740 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes(), and GNEAttributeCarrier::allowedTags().
Referenced by GNEInspectorFrame::GNEInspectorFrame(), and GNEAttributeCarrier::~GNEAttributeCarrier().
const std::string GNEAttributeCarrier::getID () const virtual inherited
function to support debugging
Implements GNEReferenceCounter.
Definition at line 117 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::getAttribute(), and SUMO_ATTR_ID.
Referenced by GNEAdditionalFrame::addAdditional(), GNENet::addReversedEdge(), GNENet::deleteAdditional(), GNEAdditionalFrame::generateID(), GNEVaporizer::getAttribute(), GNERouteProbe::getAttribute(), GNECalibrator::getAttribute(), GNEAdditionalHandler::getPosition(), GNENet::insertAdditional(), GNENet::reverseEdge(), GNEJunction::setLogicValid(), GNENet::updateAdditionalID(), GNEDetectorEntry::writeAdditional(), GNEDetectorExit::writeAdditional(), GNEDetectorE1::writeAdditional(), GNEChargingStation::writeAdditional(), GNEVaporizer::writeAdditional(), GNERouteProbe::writeAdditional(), GNEDetectorE2::writeAdditional(), GNEContainerStop::writeAdditional(), GNEVariableSpeedSignal::writeAdditional(), GNEBusStop::writeAdditional(), GNEDetectorE3::writeAdditional(), GNECalibrator::writeAdditional(), GNERerouter::writeAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
int GNELane::getIndex () const
returns the index of the lane
Definition at line 500 of file GNELane.cpp.
References myIndex.
Referenced by GNEEdge::addLane(), GNENet::deleteLane(), GNENet::duplicateLane(), GNEConnectorFrame::getLaneStatus(), GNEConnectorFrame::getTLLLinkNumber(), GNEConnectorFrame::handleLaneClick(), GNEConnectorFrame::initTargets(), and GNEEdge::removeLane().
SUMOReal GNELane::getLaneParametricLenght () const
returns the parameteric length of the lane
Note
is the same as their Edge parent
Definition at line 518 of file GNELane.cpp.
References NBEdge::getLoadedLength(), GNEEdge::getNBEdge(), myParentEdge, and SUMOReal.
Referenced by getPositionRelativeToParametricLenght(), getPositionRelativeToShapeLenght(), GNEDetectorExit::isValid(), GNEDetectorEntry::isValid(), GNEDetectorE1::isValid(), and GNEDetectorE2::isValid().
SUMOReal GNELane::getLaneShapeLenght () const
returns the length of the lane's shape
Definition at line 524 of file GNELane.cpp.
References getShape(), PositionVector::length(), and SUMOReal.
Referenced by GNEAdditionalFrame::addAdditional(), GNEAdditionalHandler::getPosition(), getPositionRelativeToParametricLenght(), getPositionRelativeToShapeLenght(), GNEStoppingPlace::moveAdditional(), GNEDetector::moveAdditional(), GNEAdditionalHandler::parseAndBuildBusStop(), GNEAdditionalHandler::parseAndBuildChargingStation(), GNEAdditionalHandler::parseAndBuildContainerStop(), GNEStoppingPlace::setEndPosition(), and GNEDetector::setPositionOverLane().
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 137 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNEPOI::getAttribute(), GNECrossing::getAttribute(), GNEJunction::getAttribute(), GNEPoly::getAttribute(), GNEEdge::getAttribute(), getAttribute(), getParentName(), GNENetElement::getParentName(), GNEDetectorE3::getParentName(), GNEVaporizer::getParentName(), GNEVariableSpeedSignal::getParentName(), GNERouteProbe::getParentName(), GNEStoppingPlace::getParentName(), GNECalibrator::getParentName(), GNEDetector::getParentName(), GNEAdditional::getParentName(), GNERerouter::getParentName(), GNEAdditional::getPopUpMenu(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GNEEdge::moveGeometry(), GNEPoly::moveGeometry(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEViewNet::onCmdNodeShape(), GNEViewNet::onLeftBtnPress(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNENet::replaceJunctionByGeometry(), GNENet::retrieveAttributeCarriers(), GNEAdditional::setAdditionalID(), GNEEdge::setAttribute(), GNENet::splitEdge(), and GNEConnectorFrame::updateDescription().
GNENet * GNENetElement::getNet () const inherited
Returns the NetElement's geometry.
get Net in which this element is placed
Definition at line 70 of file GNENetElement.cpp.
References GNENetElement::myNet.
GUIParameterTableWindow * GNELane::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GNENetElement.
Definition at line 431 of file GNELane.cpp.
References GUIParameterTableWindow::closeBuilding(), NBEdge::getLength(), GNEEdge::getNBEdge(), GUIParameterTableWindow::mkItem(), and myParentEdge.
GNEEdge & GNELane::getParentEdge ()
Returns underlying parent edge.
Definition at line 870 of file GNELane.cpp.
References myParentEdge.
Referenced by GNEAdditionalHandler::buildAdditional(), GNENet::deleteLane(), GNENet::duplicateLane(), GNEConnectorFrame::getLaneStatus(), GNEConnectorFrame::getTLLLinkNumber(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEConnectorFrame::initTargets(), GNEViewNet::onLeftBtnPress(), GNEAdditionalHandler::parseAndBuildCalibrator(), and GNECalibrator::setAttribute().
const std::string & GNELane::getParentName () const virtual
Returns the name of the parent object (if any)
Returns
This object's parent id
Reimplemented from GNENetElement.
Definition at line 855 of file GNELane.cpp.
References GUIGlObject::getMicrosimID(), and myParentEdge.
SumoXMLTag GNEAttributeCarrier::getParentType (SumoXMLTag tag) static inherited
get parent's tag of a certain additional element
Definition at line 123 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::hasParent(), GNEAttributeCarrier::myAllowedAdditionalWithParentTags, and SUMO_TAG_NOTHING.
Referenced by GNEAdditionalFrame::setParametersOfAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
GUIGLObjectPopupMenu * GNELane::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GNENetElement.
Definition at line 371 of file GNELane.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), GNEInternalLane::colorForLinksState(), GNETLSEditorFrame::controlsEdge(), GUIVisualizationSettings::editMode, StringBijection< T >::get(), MFXUtils::getFXColor(), GUIGlObject::getGlID(), GUISUMOAbstractView::getPositionInformation(), getPositionRelativeToShapeLenght(), getShape(), StringBijection< T >::getStrings(), GUISUMOAbstractView::getVisualisationSettings(), GLO_LANE, GNE_MODE_CONNECT, GNE_MODE_CREATE_EDGE, GNE_MODE_TLS, gSelected, GUISelectedStorage::isSelected(), GNEInternalLane::LinkStateNames, MID_COPY_EDGE_NAME, MID_GNE_ADD_REVERSE_EDGE, MID_GNE_DUPLICATE_LANE, MID_GNE_RESET_EDGE_ENDPOINT, MID_GNE_REVERSE_EDGE, MID_GNE_SET_EDGE_ENDPOINT, MID_GNE_SPLIT_EDGE, MID_GNE_SPLIT_EDGE_BIDI, MID_GNE_STRAIGHTEN, myParentEdge, myTLSEditor, PositionVector::nearest_offset_to_point2D(), PositionVector::positionAtOffset2D(), SUMOReal, toString(), and Position::z().
SUMOReal GNELane::getPositionRelativeToParametricLenght (SUMOReal position) const
Definition at line 530 of file GNELane.cpp.
References getLaneParametricLenght(), getLaneShapeLenght(), and SUMOReal.
Referenced by GNEDetectorEntry::getPositionInView(), GNEDetectorExit::getPositionInView(), GNEDetectorE1::getPositionInView(), GNEStoppingPlace::getPositionInView(), GNEDetectorE2::getPositionInView(), GNEAdditional::setBlockIconRotation(), GNEDetectorEntry::updateGeometry(), GNEDetectorExit::updateGeometry(), GNEDetectorE1::updateGeometry(), GNEChargingStation::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEContainerStop::updateGeometry(), and GNEBusStop::updateGeometry().
SUMOReal GNELane::getPositionRelativeToShapeLenght (SUMOReal position) const
Definition at line 536 of file GNELane.cpp.
References getLaneParametricLenght(), and getLaneShapeLenght().
Referenced by getPopUpMenu().
const PositionVector & GNELane::getShape () const
returns the shape of the lane
Definition at line 456 of file GNELane.cpp.
References NBEdge::getLaneShape(), GNEEdge::getNBEdge(), myIndex, and myParentEdge.
Referenced by GNEAdditionalFrame::addAdditional(), drawArrows(), drawCrossties(), drawDirectionIndicators(), drawGL(), GNEEdge::drawGL(), drawLane2LaneConnections(), drawMarkings(), getCenteringBoundary(), getColorValue(), getLaneShapeLenght(), getPopUpMenu(), GNEAdditional::getPopUpMenu(), GNEDetectorEntry::getPositionInView(), GNEDetectorExit::getPositionInView(), GNEDetectorE1::getPositionInView(), GNEStoppingPlace::getPositionInView(), GNEDetectorE2::getPositionInView(), GNEViewNet::onLeftBtnPress(), GNEViewNet::onMouseMove(), GNEAdditional::setBlockIconRotation(), setFunctionalColor(), setMultiColor(), GNEDetectorEntry::updateGeometry(), GNEDetectorExit::updateGeometry(), GNEDetectorE1::updateGeometry(), GNEVaporizer::updateGeometry(), GNERouteProbe::updateGeometry(), GNEChargingStation::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEBusStop::updateGeometry(), GNEContainerStop::updateGeometry(), and updateGeometry().
const std::vector< SUMOReal > & GNELane::getShapeLengths () const
returns the vector with the shape lengths
Definition at line 468 of file GNELane.cpp.
References myShapeLengths.
Referenced by drawMarkings().
const std::vector< SUMOReal > & GNELane::getShapeRotations () const
returns the vector with the shape rotations
Definition at line 462 of file GNELane.cpp.
References myShapeRotations.
Referenced by drawMarkings().
SUMOReal GNELane::getSpeed () const
returns the current speed of lane
Definition at line 512 of file GNELane.cpp.
References NBEdge::getLaneSpeed(), GNEEdge::getNBEdge(), myIndex, myParentEdge, and SUMOReal.
SumoXMLTag GNEAttributeCarrier::getTag () const inherited
get Tag assigned to this object
Definition at line 101 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myTag.
Referenced by GNENet::deleteAdditional(), GNESelectorFrame::getMatches(), GNEAdditional::getPopUpMenu(), GNENet::insertAdditional(), GNEDetectorExit::isValid(), GNEDetectorEntry::isValid(), GNEDetectorE1::isValid(), GNEDetectorE2::isValid(), GNEBusStop::isValid(), GNEContainerStop::isValid(), GNEDetectorE3::isValid(), GNEVaporizer::isValid(), GNEVariableSpeedSignal::isValid(), GNERouteProbe::isValid(), GNEChargingStation::isValid(), GNECalibrator::isValid(), GNERerouter::isValid(), GNEViewNet::onLeftBtnPress(), GNENet::updateAdditionalID(), GNEDetectorEntry::writeAdditional(), GNEDetectorExit::writeAdditional(), GNEDetectorE1::writeAdditional(), GNEChargingStation::writeAdditional(), GNEVaporizer::writeAdditional(), GNERouteProbe::writeAdditional(), GNEDetectorE2::writeAdditional(), GNEContainerStop::writeAdditional(), GNEVariableSpeedSignal::writeAdditional(), GNEBusStop::writeAdditional(), GNEDetectorE3::writeAdditional(), GNECalibrator::writeAdditional(), GNERerouter::writeAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 150 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEAdditionalSet::drawConnections(), GNEDetector::drawDetectorIcon(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE3::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GNERerouter::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorE2::getAttribute(), GNEContainerStop::getAttribute(), GNEBusStop::getAttribute(), GNEDetectorE3::getAttribute(), GNEVaporizer::getAttribute(), GNEVariableSpeedSignal::getAttribute(), GNERouteProbe::getAttribute(), GNEChargingStation::getAttribute(), GNECalibrator::getAttribute(), GNERerouter::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNEJunction::getColorValue(), getColorValue(), GUILane::getColorValue(), GNEViewNet::getEdgeAtCursorPosition(), GNEViewNet::getEdgesAtCursorPosition(), GNEViewNet::getJunctionAtCursorPosition(), GNEViewNet::getLaneAtCurserPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), GUILane::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEDetectorE1::isValid(), GNEDetectorE2::isValid(), GNEContainerStop::isValid(), GNEBusStop::isValid(), GNEDetectorE3::isValid(), GNEVaporizer::isValid(), GNEVariableSpeedSignal::isValid(), GNERouteProbe::isValid(), GNEChargingStation::isValid(), GNECalibrator::isValid(), GNERerouter::isValid(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onDoubleClicked(), GNEViewNet::onLeftBtnPress(), LayeredRTree::selectLayer(), GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEDetectorE1::setAttribute(), GNEDetectorE2::setAttribute(), GNEBusStop::setAttribute(), GNEContainerStop::setAttribute(), GNEDetectorE3::setAttribute(), GNEVaporizer::setAttribute(), GNEVariableSpeedSignal::setAttribute(), GNERouteProbe::setAttribute(), GNEChargingStation::setAttribute(), GNECalibrator::setAttribute(), GNERerouter::setAttribute(), GNEJunction::setColor(), and GUISelectedStorage::toggleSelection().
GUIParameterTableWindow * GUIGlObject::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own type parameter window (optional)
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Reimplemented in GUIVehicle, GUIBaseVehicle, and GUIMEVehicle.
Definition at line 129 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
Referenced by GUIGLObjectPopupMenu::onCmdShowTypePars().
bool GNEAttributeCarrier::hasAttribute (SumoXMLTag tag, SumoXMLAttr attr) static inherited
check if a element with certain tag has a certain attribute
Definition at line 536 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedAttributes().
Referenced by GNEAdditionalFrame::addAdditional(), GNEAdditionalFrame::setParametersOfAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::hasParent (SumoXMLTag tag) static inherited
check if a element with certain tag has another additional element as parent
Definition at line 525 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myAllowedAdditionalWithParentTags, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, and SUMO_TAG_E3DETECTOR.
Referenced by GNEAdditionalFrame::addAdditional(), GNEAttributeCarrier::getParentType(), GNEAdditionalFrame::setParametersOfAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
void GNEReferenceCounter::incRef (const std::string & debugMsg = "") inline inherited
Definition at line 73 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), GNEReferenceCounter::myCount, toString(), and UNUSED_PARAMETER.
Referenced by GNEEdge::addLane(), GNENet::registerEdge(), GNENet::registerJunction(), and GNEInspectorFrame::setEdgeTemplate().
bool GNEAttributeCarrier::isBool (SumoXMLAttr attr) static inherited
whether an attribute is of type bool
Definition at line 460 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::allowedTags(), and GNEAttributeCarrier::discreteChoices().
Referenced by GNEAdditionalFrame::additionalParameters::addAttribute(), GNEAdditionalFrame::additionalParameter::getValue(), GNEAttributeCarrier::isString(), GNEAdditionalFrame::additionalParameters::onCmdHelp(), GNEInspectorFrame::AttrInput::onCmdSetAttribute(), GNEInspectorFrame::AttrInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isDiscrete (SumoXMLTag tag, SumoXMLAttr attr) static inherited
whether an attribute is Discrete
Definition at line 515 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::discreteChoices().
Referenced by GNEInspectorFrame::AttrInput::onCmdSetAttribute(), GNEInspectorFrame::AttrInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isFloat (SumoXMLAttr attr) static inherited
whether an attribute is numerical of type float
Definition at line 437 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNumericalFloatAttrs, SUMO_ATTR_CHARGINGPOWER, SUMO_ATTR_CONTPOS, SUMO_ATTR_EFFICIENCY, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ENDPOS, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_LENGTH, SUMO_ATTR_PROB, SUMO_ATTR_RADIUS, SUMO_ATTR_SPEED, SUMO_ATTR_STARTPOS, and SUMO_ATTR_WIDTH.
Referenced by GNEAdditionalFrame::additionalParameters::addAttribute(), GNEAttributeCarrier::isNumerical(), GNEAttributeCarrier::isString(), GNEAdditionalFrame::additionalParameters::onCmdHelp(), GNEInspectorFrame::AttrInput::onCmdSetAttribute(), GNEInspectorFrame::AttrInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isInt (SumoXMLAttr attr) static inherited
whether an attribute is numerical or type int
Definition at line 419 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myNumericalIntAttrs, SUMO_ATTR_BEGIN, SUMO_ATTR_CHARGEDELAY, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FROM_LANE, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_INDEX, SUMO_ATTR_NUMLANES, SUMO_ATTR_PRIORITY, and SUMO_ATTR_TO_LANE.
Referenced by GNEAdditionalFrame::additionalParameters::addAttribute(), GNEAttributeCarrier::isNumerical(), GNEAdditionalFrame::additionalParameters::onCmdHelp(), GNEInspectorFrame::AttrInput::onCmdSetAttribute(), GNEInspectorFrame::AttrInput::showAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isList (SumoXMLAttr attr) static inherited
whether an attribute is of type bool
Definition at line 481 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myListAttrs, SUMO_ATTR_EDGES, SUMO_ATTR_LANES, and SUMO_ATTR_LINES.
Referenced by GNEAdditionalFrame::additionalParameters::addAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isNumerical (SumoXMLAttr attr) static inherited
whether an attribute is numerical (int or float)
Definition at line 413 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isFloat(), and GNEAttributeCarrier::isInt().
Referenced by GNESelectorFrame::getMatches(), GNEAttributeCarrier::isString(), GNESelectorFrame::onCmdSelMBString(), and GNEAttributeCarrier::~GNEAttributeCarrier().
template<typename T > static bool GNEAttributeCarrier::isPositive (const std::string & string) inline static inherited
true if a positive number of type T can be parsed from string
Definition at line 187 of file GNEAttributeCarrier.h.
References GNEAttributeCarrier::isValidFileValue(), GNEAttributeCarrier::isValidID(), and GNEAttributeCarrier::isValidStringVector().
bool GNEAttributeCarrier::isString (SumoXMLAttr attr) static inherited
whether an attribute is of type string
Definition at line 475 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isBool(), GNEAttributeCarrier::isFloat(), and GNEAttributeCarrier::isNumerical().
Referenced by GNEAdditionalFrame::additionalParameters::addAttribute(), GNEAdditionalFrame::additionalParameters::onCmdHelp(), GNEInspectorFrame::AttrInput::onCmdSetAttribute(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNEAttributeCarrier::isUnique (SumoXMLAttr attr) static inherited
whether an attribute is unique (may not be edited for a multi-selection)
Note
unique attributes don't have a default value
Definition at line 493 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::myUniqueAttrs, SUMO_ATTR_EDGE, SUMO_ATTR_EDGES, SUMO_ATTR_ENDPOS, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_ROUTEPROBE, SUMO_ATTR_SHAPE, SUMO_ATTR_STARTPOS, SUMO_ATTR_TO, and SUMO_ATTR_TO_LANE.
Referenced by GNEAdditional::getParameterWindow(), GNEInspectorFrame::inspect(), GNEAdditionalFrame::setParametersOfAdditional(), and GNEAttributeCarrier::~GNEAttributeCarrier().
bool GNELane::isValid (SumoXMLAttr key, const std::string & value) virtual
Implements GNENetElement.
Definition at line 647 of file GNELane.cpp.
References canParseVehicleClasses(), myIndex, SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_SPEED, SUMO_ATTR_WIDTH, toString(), and NBEdge::UNSPECIFIED_WIDTH.
bool GNEAttributeCarrier::isValidFileValue (const std::string & value) static inherited
true if value is a valid file value
Definition at line 139 of file GNEAttributeCarrier.cpp.
Referenced by GNEAttributeCarrier::isPositive(), GNEDetectorE1::isValid(), GNEDetectorE2::isValid(), GNEDetectorE3::isValid(), GNEVariableSpeedSignal::isValid(), GNERouteProbe::isValid(), GNECalibrator::isValid(), GNERerouter::isValid(), and GNEAttributeCarrier::isValidStringVector().
bool GNEAttributeCarrier::isValidID (const std::string & value) static inherited
true if value is a valid sumo ID
Definition at line 133 of file GNEAttributeCarrier.cpp.
Referenced by GNEAttributeCarrier::isPositive(), GNEJunction::isValid(), and GNEEdge::isValid().
bool GNEAttributeCarrier::isValidStringVector (const std::string & value) static inherited
true if value is a valid string vector
Definition at line 147 of file GNEAttributeCarrier.cpp.
References GNEAttributeCarrier::isValidFileValue().
Referenced by GNEAttributeCarrier::isPositive(), GNEBusStop::isValid(), and GNEContainerStop::isValid().
long GNELane::onDefault (FXObject * obj, FXSelector sel, void * data)
multiplexes message to two targets
Definition at line 861 of file GNELane.cpp.
References GNETLSEditorFrame::handleMultiChange(), and myTLSEditor.
GNELane& GNELane::operator= (const GNELane &) private
Invalidated assignment operator.
template<> int GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 70 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2int(), and SUMOReal.
template<> SUMOReal GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 76 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2SUMOReal().
template<> bool GNEAttributeCarrier::parse (const std::string & string) inherited
Definition at line 82 of file GNEAttributeCarrier.cpp.
References TplConvert::_str2Bool().
template<typename T > static T GNEAttributeCarrier::parse (const std::string & string) static inherited
parses a number of type T from string
Referenced by GNEAttributeCarrier::canParse().
bool GNELane::removeAdditional (GNEAdditional * additional)
Definition at line 548 of file GNELane.cpp.
References myAdditionals.
Referenced by GNEStoppingPlace::changeLane(), GNEDetector::changeLane(), GNEDetector::~GNEDetector(), and GNEStoppingPlace::~GNEStoppingPlace().
bool GNELane::removeAdditionalSet (GNEAdditionalSet * additionalSet)
remove GNEAdditionalSet from this lane
Definition at line 581 of file GNELane.cpp.
References myAdditionalSets.
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 264 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
void GNELane::setAttribute (SumoXMLAttr key, const std::string & value, GNEUndoList * undoList) virtual
Implements GNENetElement.
Definition at line 627 of file GNELane.cpp.
References GNEAttributeCarrier::GNEChange_Attribute, GNEUndoList::p_add(), SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_SPEED, SUMO_ATTR_WIDTH, and toString().
void GNELane::setAttribute (SumoXMLAttr key, const std::string & value) private virtual
set attribute after validation
Implements GNENetElement.
Definition at line 678 of file GNELane.cpp.
References GNEEdge::getNBEdge(), myIndex, myParentEdge, parseVehicleClasses(), NBEdge::setEndOffset(), NBEdge::setLaneWidth(), NBEdge::setPermissions(), NBEdge::setSpeed(), SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_ENDOFFSET, SUMO_ATTR_ID, SUMO_ATTR_SPEED, SUMO_ATTR_WIDTH, and toString().
bool GNELane::setFunctionalColor (int activeScheme) const private
sets the color according to the current scheme index and some lane function
Definition at line 705 of file GNELane.cpp.
References RGBColor::fromHSV(), getShape(), GeomHelper::naviDegree(), GLHelper::setColor(), and SUMOReal.
Referenced by drawGL().
void GNELane::setIndex (int index)
Definition at line 505 of file GNELane.cpp.
References NBEdge::getLaneID(), GNEEdge::getNBEdge(), myIndex, myParentEdge, GUIGlObject::setMicrosimID(), and SUMOReal.
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 143 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNENet::renameJunction(), GNEAdditional::setAdditionalID(), setIndex(), and GNEEdge::setMicrosimID().
bool GNELane::setMultiColor (const GUIColorer & c) const private
sets multiple colors according to the current scheme index and some lane function
Definition at line 719 of file GNELane.cpp.
References GUIPropertySchemeStorage< T >::getActive(), GUIPropertyScheme< T >::getColor(), GUIPropertySchemeStorage< T >::getScheme(), getShape(), MAX2(), myShapeColors, POSITION_EPS, and SUMOReal.
Referenced by drawGL().
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 273 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
void GNELane::setSpecialColor (const RGBColor * Color2)
Definition at line 669 of file GNELane.cpp.
References mySpecialColor.
Referenced by GNEConnectorFrame::cleanup(), and GNEConnectorFrame::handleLaneClick().
bool GNEReferenceCounter::unreferenced () inline inherited
Definition at line 82 of file GNEReferenceCounter.h.
References GNEReferenceCounter::getID(), and GNEReferenceCounter::myCount.
Referenced by GNEEdge::removeLane(), GNEInspectorFrame::setEdgeTemplate(), GNEChange_Additional::~GNEChange_Additional(), GNEChange_Attribute::~GNEChange_Attribute(), GNEChange_Connection::~GNEChange_Connection(), GNEChange_Edge::~GNEChange_Edge(), GNEChange_Junction::~GNEChange_Junction(), GNEChange_Lane::~GNEChange_Lane(), GNEChange_TLS::~GNEChange_TLS(), and GNEInspectorFrame::~GNEInspectorFrame().
void GNELane::updateGeometry () virtual
update pre-computed geometry information
Implements GNENetElement.
Definition at line 473 of file GNELane.cpp.
References Position::distanceTo2D(), getShape(), myAdditionals, myAdditionalSets, myShapeLengths, myShapeRotations, PI, SUMOReal, Position::x(), and Position::y().
Field Documentation
const std::string GNEAttributeCarrier::APPROVED = "approved" static inherited
feature has been approved but not changed (i.e. after being reguessed)
Definition at line 210 of file GNEAttributeCarrier.h.
const std::string GNEAttributeCarrier::GUESSED = "guessed" static inherited
feature has been reguessed (may still be unchanged be we can't tell (yet)
Definition at line 204 of file GNEAttributeCarrier.h.
Referenced by GNEEdge::setAttribute().
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 77 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
const std::string GNEAttributeCarrier::LOADED = "loaded" static inherited
feature is still unchanged after being loaded (implies approval)
Definition at line 201 of file GNEAttributeCarrier.h.
const std::string GNEAttributeCarrier::MODIFIED = "modified" static inherited
feature has been manually modified (implies approval)
Definition at line 207 of file GNEAttributeCarrier.h.
Referenced by GNEConnectorFrame::onCmdClearSelectedConnections(), and GNEEdge::setAttribute().
AdditionalVector GNELane::myAdditionals protected
list with the additonals vinculated with this lane
Definition at line 239 of file GNELane.h.
Referenced by addAdditional(), getAdditionals(), removeAdditional(), updateGeometry(), and ~GNELane().
AdditionalSetVector GNELane::myAdditionalSets protected
list with the additonalSets vinculated with this lane
Definition at line 242 of file GNELane.h.
Referenced by addAdditionalSet(), getAdditionalSets(), removeAdditionalSet(), and updateGeometry().
int GNELane::myIndex protected
The index of this lane.
Definition at line 227 of file GNELane.h.
Referenced by drawArrows(), drawAsRailway(), drawAsWaterway(), drawDirectionIndicators(), drawGL(), drawLane2LaneConnections(), drawMarkings(), getAttribute(), getBoundary(), getColorValue(), getIndex(), getShape(), getSpeed(), isValid(), setAttribute(), and setIndex().
GNENet* GNENetElement::myNet protected inherited
the net to inform about updates
Definition at line 141 of file GNENetElement.h.
Referenced by GNEEdge::addConnection(), GNEEdge::addLane(), GNEJunction::addTrafficLight(), GNEEdge::getDest(), GNENetElement::getNet(), GNENetElement::getParentName(), GNEEdge::getSource(), GNEJunction::invalidateShape(), GNEJunction::invalidateTLS(), GNEJunction::isValid(), GNEEdge::isValid(), GNEJunction::move(), GNEEdge::removeConnection(), GNEEdge::removeLane(), GNEJunction::removeTrafficLight(), GNEEdge::setAttribute(), GNEJunction::setAttribute(), GNEEdge::setGeometry(), GNEJunction::setLogicValid(), and GNEJunction::updateCrossingAttributes().
GNEEdge& GNELane::myParentEdge protected
The Edge that to which this lane belongs.
Definition at line 224 of file GNELane.h.
Referenced by drawArrows(), drawAsRailway(), drawAsWaterway(), drawDirectionIndicators(), drawGL(), drawLane2LaneConnections(), drawMarkings(), getAttribute(), getBoundary(), getColorValue(), getLaneParametricLenght(), getParameterWindow(), getParentEdge(), getParentName(), getPopUpMenu(), getShape(), getSpeed(), setAttribute(), and setIndex().
std::vector<RGBColor> GNELane::myShapeColors mutable protected
The color of the shape parts (cached)
Definition at line 248 of file GNELane.h.
Referenced by drawGL(), and setMultiColor().
std::vector<SUMOReal> GNELane::myShapeLengths protected
The lengths of the shape parts.
Definition at line 235 of file GNELane.h.
Referenced by drawCrossties(), drawDirectionIndicators(), drawGL(), drawMarkings(), getShapeLengths(), and updateGeometry().
std::vector<SUMOReal> GNELane::myShapeRotations protected
Definition at line 232 of file GNELane.h.
Referenced by drawCrossties(), drawDirectionIndicators(), drawGL(), drawMarkings(), getShapeRotations(), and updateGeometry().
const RGBColor* GNELane::mySpecialColor protected
optional special color
Definition at line 245 of file GNELane.h.
Referenced by drawGL(), and setSpecialColor().
GNETLSEditorFrame* GNELane::myTLSEditor protected
the tls-editor for setting multiple links in TLS-mode
Definition at line 251 of file GNELane.h.
Referenced by getPopUpMenu(), and onDefault().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 76 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GNELane.h
GNELane.cpp