SUMO - Simulation of Urban MObility: CHRouter< E, V, PF > Class Template Reference
CHRouter< E, V, PF > Class Template Reference abstract
Computes the shortest path through a contracted network.
#include <CHRouter.h>
Data Structures
class CHConnection
Forward/backward connection with associated FORWARD cost.
class CHInfo
class CHInfoComparator
class Connection
Forward/backward connection with associated forward/backward cost.
struct EdgeInfo
struct Shortcut
class Unidirectional
Public Types
typedef std::pair< const CHConnection *, const CHConnection * > CHConnectionPair
typedef std::vector< CHConnectionPair > CHConnectionPairs
typedef std::vector< CHConnection > CHConnections
typedef std::pair< const E *, const E * > ConstEdgePair
contraction related members
typedef std::pair< E *, E * > EdgePair
typedef std::set< const E * > EdgeSet
A set of (found) Edges.
typedef std::pair< const EdgeInfo *, const EdgeInfo * > Meeting
A meeting point of the two search scopes.
typedef SUMOReal(* Operation) (const E *const, const V *const, SUMOReal)
Type of the function that is used to retrieve the edge effort.
typedef std::vector< const E * > Result
The found route (used as output parameter)
typedef std::vector< Shortcut > Shortcuts
typedef std::map< ConstEdgePair, const E * > ShortcutVia
Public Member Functions
void buildPathFromMeeting (Meeting meeting, Result &into)
normal routing methods
CHRouter (const std::vector< E * > &edges, bool unbuildIsWarning, Operation operation, const SUMOVehicleClass svc, SUMOTime weightPeriod, bool validatePermissions)
Constructor.
virtual SUMOAbstractRouter< E, V > * clone ()
virtual bool compute (const E *from, const E *to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > &into)=0
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
virtual bool compute (const E *from, const E *to, const V *const vehicle, SUMOTime msTime, Result &into)
Builds the route between the given edges using the minimum traveltime in the contracted graph.
void endQuery (int visits)
SUMOReal getEffort (const E *const e, const V *const v, SUMOReal t) const
SUMOReal recomputeCosts (const std::vector< const E * > &edges, const V *const v, SUMOTime msTime) const
void setBulkMode (const bool mode)
void startQuery ()
virtual ~CHRouter ()
Destructor.
Protected Attributes
bool myBulkMode
whether we are currently operating several route queries in a bulk
Operation myOperation
The object's operation to perform.
Private Member Functions
void buildContractionHierarchy (SUMOTime time, const V *const vehicle)
void debugPrintQueue (std::vector< CHInfo * > &queue)
void disconnect (CHConnections &connections, CHInfo *other)
remove all connections to/from the given edge (assume it exists only once)
CHInfo * getCHInfo (const E *const edge)
const E * getVia (const E *forwardFrom, const E *forwardTo)
void synchronize (CHInfo &info, SUMOReal time, const V *const vehicle)
copy connections from the original net (modified destructively during contraction)
bool tryUpdateFront (std::vector< CHInfo * > &queue)
tries to update the priority of the first edge
Private Attributes
Unidirectional myBackwardSearch
std::vector< CHInfo > myCHInfos
static vector for lookup
CHInfoComparator myCmp
Comparator for contraction priority.
const std::vector< E * > & myEdges
all edges with numerical ids
MsgHandler *const myErrorMsgHandler
the handler for routing errors
Unidirectional myForwardSearch
the unidirectional search queues
ShortcutVia myShortcuts
map from (forward) shortcut to via-Edge
SPTree< CHInfo, CHConnection > * mySPTree
the shortest path tree to use when searching for shortcuts
SUMOVehicleClass mySVC
the permissions for which the hierarchy was constructed
int myUpdateCount
counters for performance logging
SUMOTime myValidUntil
the validity duration of the current hierarchy (exclusive)
const SUMOTime myWeightPeriod
the validity duration of one weight interval
Detailed Description
template<class E, class V, class PF>
class CHRouter< E, V, PF >
Computes the shortest path through a contracted network.
The template parameters are:
Parameters
E The edge class to use (MSEdge/ROEdge)
V The vehicle class to use (MSVehicle/ROVehicle)
PF The prohibition function to use (prohibited_withPermissions/noProhibitions)
The router is edge-based. It must know the number of edges for internal reasons and whether a missing connection between two given edges (unbuild route) shall be reported as an error or as a warning.
Definition at line 74 of file CHRouter.h.
Member Typedef Documentation
template<class E, class V, class PF> typedef std::pair<const CHConnection*, const CHConnection*> CHRouter< E, V, PF >::CHConnectionPair
Definition at line 312 of file CHRouter.h.
template<class E, class V, class PF> typedef std::vector<CHConnectionPair> CHRouter< E, V, PF >::CHConnectionPairs
Definition at line 313 of file CHRouter.h.
template<class E, class V, class PF> typedef std::vector<CHConnection> CHRouter< E, V, PF >::CHConnections
Definition at line 311 of file CHRouter.h.
template<class E, class V, class PF> typedef std::pair<const E*, const E*> CHRouter< E, V, PF >::ConstEdgePair
contraction related members
Definition at line 450 of file CHRouter.h.
template<class E, class V, class PF> typedef std::pair<E*, E*> CHRouter< E, V, PF >::EdgePair
Definition at line 451 of file CHRouter.h.
template<class E, class V, class PF> typedef std::set<const E*> CHRouter< E, V, PF >::EdgeSet
A set of (found) Edges.
Definition at line 86 of file CHRouter.h.
template<class E, class V, class PF> typedef std::pair<const EdgeInfo*, const EdgeInfo*> CHRouter< E, V, PF >::Meeting
A meeting point of the two search scopes.
Definition at line 83 of file CHRouter.h.
template<class E, class V, class PF> typedef SUMOReal(* CHRouter< E, V, PF >::Operation) (const E *const, const V *const, SUMOReal)
Type of the function that is used to retrieve the edge effort.
Definition at line 80 of file CHRouter.h.
template<class E, class V, class PF> typedef std::vector<const E*> CHRouter< E, V, PF >::Result
The found route (used as output parameter)
Definition at line 89 of file CHRouter.h.
template<class E, class V, class PF> typedef std::vector<Shortcut> CHRouter< E, V, PF >::Shortcuts
Definition at line 462 of file CHRouter.h.
template<class E, class V, class PF> typedef std::map<ConstEdgePair, const E*> CHRouter< E, V, PF >::ShortcutVia
Definition at line 463 of file CHRouter.h.
Constructor & Destructor Documentation
template<class E, class V, class PF> CHRouter< E, V, PF >::CHRouter (const std::vector< E * > & edges, bool unbuildIsWarning, Operation operation, const SUMOVehicleClass svc, SUMOTime weightPeriod, bool validatePermissions) inline
Constructor.
Parameters
[in] validatePermissions Whether a multi-permission hierarchy shall be built If set to false, the net is pruned in synchronize() and the hierarchy is tailored to the vClass of the defaultVehicle
Note
: defaultVehicle is not transient and must be kept after constructor finishes
Definition at line 321 of file CHRouter.h.
References CHRouter< E, V, PF >::myCHInfos.
template<class E, class V, class PF> virtual CHRouter< E, V, PF >::~CHRouter () inline virtual
Destructor.
Definition at line 341 of file CHRouter.h.
References CHRouter< E, V, PF >::mySPTree.
Member Function Documentation
template<class E, class V, class PF> void CHRouter< E, V, PF >::buildContractionHierarchy (SUMOTime time, const V *const vehicle) inline private
Definition at line 702 of file CHRouter.h.
References CHRouter< E, V, PF >::CHInfo::approaching, CHRouter< E, V, PF >::Connection::Connection(), CHRouter< E, V, PF >::CHConnection::cost, CHRouter< E, V, PF >::disconnect(), CHRouter< E, V, PF >::CHInfo::edge, MsgHandler::endProcessMsg(), CHRouter< E, V, PF >::CHInfo::followers, CHRouter< E, V, PF >::getCHInfo(), SysUtils::getCurrentMillis(), CHRouter< E, V, PF >::Unidirectional::getEdgeInfo(), MsgHandler::getMessageInstance(), max, CHRouter< E, V, PF >::myBackwardSearch, CHRouter< E, V, PF >::myCHInfos, CHRouter< E, V, PF >::myCmp, CHRouter< E, V, PF >::myForwardSearch, CHRouter< E, V, PF >::myShortcuts, CHRouter< E, V, PF >::mySPTree, CHRouter< E, V, PF >::mySVC, CHRouter< E, V, PF >::myUpdateCount, CHRouter< E, V, PF >::myValidUntil, CHRouter< E, V, PF >::myWeightPeriod, CHRouter< E, V, PF >::CHConnection::permissions, CHRouter< E, V, PF >::CHInfo::permissions, CHRouter< E, V, PF >::CHInfo::priority, PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, CHRouter< E, V, PF >::EdgeInfo::rank, CHRouter< E, V, PF >::CHInfo::rank, CHRouter< E, V, PF >::Unidirectional::reset(), CHRouter< E, V, PF >::CHInfo::shortcuts, STEPS2TIME, SUMOReal, SumoVehicleClassStrings, CHRouter< E, V, PF >::synchronize(), CHRouter< E, V, PF >::CHConnection::target, time2string(), toString(), CHRouter< E, V, PF >::tryUpdateFront(), CHRouter< E, V, PF >::CHInfo::updatePriority(), CHRouter< E, V, PF >::EdgeInfo::upward, and WRITE_MESSAGE.
Referenced by CHRouter< E, V, PF >::compute().
template<class E, class V, class PF> void CHRouter< E, V, PF >::buildPathFromMeeting (Meeting meeting, Result & into) inline
normal routing methods
Builds the path from marked edges
Definition at line 416 of file CHRouter.h.
References CHRouter< E, V, PF >::EdgeInfo::edge, CHRouter< E, V, PF >::getVia(), and CHRouter< E, V, PF >::EdgeInfo::prev.
Referenced by CHRouter< E, V, PF >::compute().
template<class E, class V, class PF> virtual SUMOAbstractRouter<E, V>* CHRouter< E, V, PF >::clone () inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 346 of file CHRouter.h.
References MsgHandler::getWarningInstance(), CHRouter< E, V, PF >::myEdges, CHRouter< E, V, PF >::myErrorMsgHandler, SUMOAbstractRouter< E, V >::myOperation, CHRouter< E, V, PF >::mySPTree, CHRouter< E, V, PF >::mySVC, and CHRouter< E, V, PF >::myWeightPeriod.
template<class E, class V> virtual bool SUMOAbstractRouter< E, V >::compute (const E * from, const E * to, const V *const vehicle, SUMOTime msTime, std::vector< const E * > & into) pure virtual inherited
Builds the route between the given edges using the minimum effort at the given time The definition of the effort depends on the wished routing scheme.
Implemented in IntermodalRouter< E, L, N, V, INTERNALROUTER >, IntermodalRouter< E, L, N, V >, AStarRouter< E, V, PF >, AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >, DijkstraRouterEffort< E, V, PF >, DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >, DijkstraRouterTT< E, V, PF >, DijkstraRouterTT< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > >, DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >, PedestrianRouter< E, L, N, V, INTERNALROUTER >, PedestrianRouter< E, L, N, V, DijkstraRouterTT< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V >, prohibited_withPermissions< IntermodalEdge< E, L, N, V >, IntermodalTrip< E, N, V > > > >, and CHRouterWrapper< E, V, PF >.
Referenced by TraCIServerAPI_Simulation::commandDistanceRequest(), ROMAAssignments::getKPaths(), ROMAAssignments::incremental(), MSTriggeredRerouter::notifyEnter(), TraCIServerAPI_Vehicle::processSet(), RORouteDef::repairCurrentRoute(), MSBaseVehicle::reroute(), ROMAAssignments::sue(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::~SUMOAbstractRouter().
template<class E, class V, class PF> virtual bool CHRouter< E, V, PF >::compute (const E * from, const E * to, const V *const vehicle, SUMOTime msTime, Result & into) inline virtual
Builds the route between the given edges using the minimum traveltime in the contracted graph.
Note
: since the contracted graph is static (weights averaged over time) the computed routes only approximated shortest paths in the real graph
Definition at line 355 of file CHRouter.h.
References CHRouter< E, V, PF >::buildContractionHierarchy(), CHRouter< E, V, PF >::buildPathFromMeeting(), SUMOAbstractRouter< E, V >::endQuery(), MsgHandler::inform(), CHRouter< E, V, PF >::Unidirectional::init(), max, CHRouter< E, V, PF >::myBackwardSearch, CHRouter< E, V, PF >::myErrorMsgHandler, CHRouter< E, V, PF >::myForwardSearch, CHRouter< E, V, PF >::mySPTree, CHRouter< E, V, PF >::mySVC, CHRouter< E, V, PF >::myValidUntil, CHRouter< E, V, PF >::myWeightPeriod, SUMOAbstractRouter< E, V >::startQuery(), CHRouter< E, V, PF >::Unidirectional::step(), SUMOReal, SVC_IGNORING, and toString().
template<class E, class V, class PF> void CHRouter< E, V, PF >::debugPrintQueue (std::vector< CHInfo * > & queue) inline private
Definition at line 829 of file CHRouter.h.
References CHRouter< E, V, PF >::CHInfo::edge, and CHRouter< E, V, PF >::CHInfo::priority.
Referenced by CHRouter< E, V, PF >::tryUpdateFront().
template<class E, class V, class PF> void CHRouter< E, V, PF >::disconnect (CHConnections & connections, CHInfo * other) inline private
remove all connections to/from the given edge (assume it exists only once)
Definition at line 691 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy().
template<class E, class V> void SUMOAbstractRouter< E, V >::endQuery (int visits) inline inherited
Definition at line 96 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and CHRouter< E, V, PF >::compute().
template<class E, class V, class PF> CHInfo* CHRouter< E, V, PF >::getCHInfo (const E *const edge) inline private
Definition at line 656 of file CHRouter.h.
References CHRouter< E, V, PF >::myCHInfos.
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy(), and CHRouter< E, V, PF >::synchronize().
template<class E, class V> SUMOReal SUMOAbstractRouter< E, V >::getEffort (const E *const e, const V *const v, SUMOReal t) const inline inherited
Definition at line 87 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), CHRouterWrapper< E, V, PF >::recomputeCosts(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::recomputeCosts(), CHRouter< E, V, PF >::recomputeCosts(), and CHRouter< E, V, PF >::synchronize().
template<class E, class V, class PF> const E* CHRouter< E, V, PF >::getVia (const E * forwardFrom, const E * forwardTo) inline private
Definition at line 798 of file CHRouter.h.
References CHRouter< E, V, PF >::myShortcuts.
Referenced by CHRouter< E, V, PF >::buildPathFromMeeting().
template<class E, class V, class PF> SUMOReal CHRouter< E, V, PF >::recomputeCosts (const std::vector< const E * > & edges, const V *const v, SUMOTime msTime) const inline virtual
Implements SUMOAbstractRouter< E, V >.
Definition at line 401 of file CHRouter.h.
References SUMOAbstractRouter< E, V >::getEffort(), STEPS2TIME, and SUMOReal.
template<class E, class V> void SUMOAbstractRouter< E, V >::setBulkMode (const bool mode) inline inherited
Definition at line 101 of file SUMOAbstractRouter.h.
Referenced by ROMAAssignments::incremental().
template<class E, class V> void SUMOAbstractRouter< E, V >::startQuery () inline inherited
Definition at line 91 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and CHRouter< E, V, PF >::compute().
template<class E, class V, class PF> void CHRouter< E, V, PF >::synchronize (CHInfo & info, SUMOReal time, const V *const vehicle) inline private
copy connections from the original net (modified destructively during contraction)
Definition at line 662 of file CHRouter.h.
References CHRouter< E, V, PF >::CHInfo::approaching, CHRouter< E, V, PF >::Connection::cost, CHRouter< E, V, PF >::CHInfo::edge, CHRouter< E, V, PF >::CHInfo::followers, CHRouter< E, V, PF >::getCHInfo(), SUMOAbstractRouter< E, V >::getEffort(), CHRouter< E, V, PF >::mySPTree, CHRouter< E, V, PF >::mySVC, CHRouter< E, V, PF >::Connection::permissions, and SUMOReal.
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy().
template<class E, class V, class PF> bool CHRouter< E, V, PF >::tryUpdateFront (std::vector< CHInfo * > & queue) inline private
tries to update the priority of the first edge
Returns
wether updating changed the first edge
Definition at line 812 of file CHRouter.h.
References CHRouter< E, V, PF >::debugPrintQueue(), CHRouter< E, V, PF >::CHInfo::edge, max, CHRouter< E, V, PF >::myCmp, CHRouter< E, V, PF >::mySPTree, CHRouter< E, V, PF >::myUpdateCount, and CHRouter< E, V, PF >::CHInfo::updatePriority().
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy().
Field Documentation
template<class E, class V, class PF> Unidirectional CHRouter< E, V, PF >::myBackwardSearch private
Definition at line 846 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy(), and CHRouter< E, V, PF >::compute().
template<class E, class V> bool SUMOAbstractRouter< E, V >::myBulkMode protected inherited
whether we are currently operating several route queries in a bulk
Definition at line 110 of file SUMOAbstractRouter.h.
Referenced by DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::compute(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::setBulkMode().
template<class E, class V, class PF> std::vector<CHInfo> CHRouter< E, V, PF >::myCHInfos private
static vector for lookup
Definition at line 852 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy(), CHRouter< E, V, PF >::CHRouter(), and CHRouter< E, V, PF >::getCHInfo().
template<class E, class V, class PF> CHInfoComparator CHRouter< E, V, PF >::myCmp private
Comparator for contraction priority.
Definition at line 855 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy(), and CHRouter< E, V, PF >::tryUpdateFront().
template<class E, class V, class PF> const std::vector<E*>& CHRouter< E, V, PF >::myEdges private
all edges with numerical ids
Definition at line 839 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::clone().
template<class E, class V, class PF> MsgHandler* const CHRouter< E, V, PF >::myErrorMsgHandler private
the handler for routing errors
Definition at line 842 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::clone(), and CHRouter< E, V, PF >::compute().
template<class E, class V, class PF> Unidirectional CHRouter< E, V, PF >::myForwardSearch private
the unidirectional search queues
Definition at line 845 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy(), and CHRouter< E, V, PF >::compute().
template<class E, class V> Operation SUMOAbstractRouter< E, V >::myOperation protected inherited
The object's operation to perform.
Definition at line 107 of file SUMOAbstractRouter.h.
Referenced by CHRouterWrapper< E, V, PF >::clone(), DijkstraRouterEffort< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), DijkstraRouterTT< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), AStarRouter< MSEdge, SUMOVehicle, prohibited_withPermissions< MSEdge, SUMOVehicle > >::clone(), CHRouter< E, V, PF >::clone(), and SUMOAbstractRouter< E, IntermodalTrip< E, N, V > >::getEffort().
template<class E, class V, class PF> ShortcutVia CHRouter< E, V, PF >::myShortcuts private
map from (forward) shortcut to via-Edge
Definition at line 849 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy(), and CHRouter< E, V, PF >::getVia().
template<class E, class V, class PF> SPTree<CHInfo, CHConnection>* CHRouter< E, V, PF >::mySPTree private
the shortest path tree to use when searching for shortcuts
Definition at line 858 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy(), CHRouter< E, V, PF >::clone(), CHRouter< E, V, PF >::compute(), CHRouter< E, V, PF >::synchronize(), CHRouter< E, V, PF >::tryUpdateFront(), and CHRouter< E, V, PF >::~CHRouter().
template<class E, class V, class PF> SUMOVehicleClass CHRouter< E, V, PF >::mySVC private
the permissions for which the hierarchy was constructed
Definition at line 867 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy(), CHRouter< E, V, PF >::clone(), CHRouter< E, V, PF >::compute(), and CHRouter< E, V, PF >::synchronize().
template<class E, class V, class PF> int CHRouter< E, V, PF >::myUpdateCount private
counters for performance logging
Definition at line 870 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy(), and CHRouter< E, V, PF >::tryUpdateFront().
template<class E, class V, class PF> SUMOTime CHRouter< E, V, PF >::myValidUntil private
the validity duration of the current hierarchy (exclusive)
Definition at line 864 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy(), and CHRouter< E, V, PF >::compute().
template<class E, class V, class PF> const SUMOTime CHRouter< E, V, PF >::myWeightPeriod private
the validity duration of one weight interval
Definition at line 861 of file CHRouter.h.
Referenced by CHRouter< E, V, PF >::buildContractionHierarchy(), CHRouter< E, V, PF >::clone(), and CHRouter< E, V, PF >::compute().
The documentation for this class was generated from the following file:
CHRouter.h