SUMO - Simulation of Urban MObility: NWWriter_MATSim Class Reference
NWWriter_MATSim Class Reference
Exporter writing networks using the MATSim format.
#include <NWWriter_MATSim.h>
Static Public Member Functions
static void writeNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Writes the network into a MATSim-file.
Detailed Description
Exporter writing networks using the MATSim format.
Definition at line 61 of file NWWriter_MATSim.h.
Member Function Documentation
void NWWriter_MATSim::writeNetwork (const OptionsCont & oc, NBNetBuilder & nb) static
Writes the network into a MATSim-file.
Parameters
[in] oc The options to use
[in] nb The network builder to fill
Definition at line 54 of file NWWriter_MATSim.cpp.
References NBNodeCont::begin(), NBEdgeCont::begin(), NBNodeCont::end(), NBEdgeCont::end(), OutputDevice::getDevice(), NBNetBuilder::getEdgeCont(), OptionsCont::getFloat(), NBNetBuilder::getNodeCont(), OptionsCont::getString(), and OptionsCont::isSet().
Referenced by NWFrame::writeNetwork().
The documentation for this class was generated from the following files:
NWWriter_MATSim.h
NWWriter_MATSim.cpp