SUMO - Simulation of Urban MObility: AbstractPoly Class Reference
AbstractPoly Class Reference abstract
#include <AbstractPoly.h>
Public Member Functions
AbstractPoly ()
AbstractPoly (const AbstractPoly &)
virtual bool around (const Position &p, SUMOReal offset=0) const =0
virtual bool crosses (const Position &p1, const Position &p2) const =0
virtual bool overlapsWith (const AbstractPoly &poly, SUMOReal offset=0) const =0
virtual bool partialWithin (const AbstractPoly &poly, SUMOReal offset=0) const =0
virtual ~AbstractPoly ()
Detailed Description
Definition at line 43 of file AbstractPoly.h.
Constructor & Destructor Documentation
AbstractPoly::AbstractPoly () inline
Definition at line 45 of file AbstractPoly.h.
AbstractPoly::AbstractPoly (const AbstractPoly &) inline
Definition at line 46 of file AbstractPoly.h.
virtual AbstractPoly::~AbstractPoly () inline virtual
Definition at line 47 of file AbstractPoly.h.
References around(), crosses(), overlapsWith(), partialWithin(), and SUMOReal.
Member Function Documentation
virtual bool AbstractPoly::around (const Position & p, SUMOReal offset = 0) const pure virtual
Implemented in PositionVector, and Boundary.
Referenced by PositionVector::overlapsWith(), Boundary::partialWithin(), PositionVector::partialWithin(), and ~AbstractPoly().
virtual bool AbstractPoly::crosses (const Position & p1, const Position & p2) const pure virtual
Implemented in PositionVector, and Boundary.
Referenced by Boundary::overlapsWith(), and ~AbstractPoly().
virtual bool AbstractPoly::overlapsWith (const AbstractPoly & poly, SUMOReal offset = 0) const pure virtual
Implemented in PositionVector, and Boundary.
Referenced by ~AbstractPoly().
virtual bool AbstractPoly::partialWithin (const AbstractPoly & poly, SUMOReal offset = 0) const pure virtual
Implemented in PositionVector, and Boundary.
Referenced by Boundary::overlapsWith(), and ~AbstractPoly().
The documentation for this class was generated from the following file:
AbstractPoly.h