SUMO - Simulation of Urban MObility: FX::FXRealSpinDialBtn Class Reference
FX::FXRealSpinDialBtn Class Reference
Public Types
enum { ID_AUTOSPIN = FXDial::ID_LAST, ID_LAST }
Public Member Functions
FXRealSpinDialBtn (FXComposite *p, FXObject *tgt=NULL, FXSelector sel=0, FXuint opts=ARROW_NORMAL, FXint x=0, FXint y=0, FXint w=0, FXint h=0, FXint pl=DEFAULT_PAD, FXint pr=DEFAULT_PAD, FXint pt=DEFAULT_PAD, FXint pb=DEFAULT_PAD)
Construct a dial widget.
long onButtonPress (FXObject *, FXSelector, void *)
long onButtonRelease (FXObject *, FXSelector, void *)
long onKey (FXObject *, FXSelector, void *)
Protected Member Functions
FXRealSpinDialBtn ()
Private Member Functions
FXRealSpinDialBtn (const FXRealSpinDialBtn &)
FXRealSpinDialBtn & operator= (const FXRealSpinDialBtn &)
Detailed Description
Definition at line 262 of file FXRealSpinDial.cpp.
Member Enumeration Documentation
anonymous enum
Enumerator
ID_AUTOSPIN
ID_LAST
Definition at line 274 of file FXRealSpinDial.cpp.
Constructor & Destructor Documentation
FX::FXRealSpinDialBtn::FXRealSpinDialBtn () inline protected
Definition at line 265 of file FXRealSpinDial.cpp.
References FX::FXRealSpinDialDial::onButtonPress(), FX::FXRealSpinDialDial::onButtonRelease(), FX::FXRealSpinDialDial::onKey(), and FX::FXRealSpinDialDial::operator=().
FX::FXRealSpinDialBtn::FXRealSpinDialBtn (const FXRealSpinDialBtn &) private
FX::FXRealSpinDialBtn::FXRealSpinDialBtn (FXComposite * p, FXObject * tgt = NULL, FXSelector sel = 0, FXuint opts = ARROW_NORMAL, FXint x = 0, FXint y = 0, FXint w = 0, FXint h = 0, FXint pl = DEFAULT_PAD, FXint pr = DEFAULT_PAD, FXint pt = DEFAULT_PAD, FXint pb = DEFAULT_PAD) inline
Construct a dial widget.
Definition at line 281 of file FXRealSpinDial.cpp.
References FX::FXDEFMAP(), onButtonPress(), onButtonRelease(), and onKey().
Member Function Documentation
long FX::FXRealSpinDialBtn::onButtonPress (FXObject * o, FXSelector s, void * p)
Definition at line 314 of file FXRealSpinDial.cpp.
Referenced by FXRealSpinDialBtn().
long FX::FXRealSpinDialBtn::onButtonRelease (FXObject * o, FXSelector s, void * p)
Definition at line 318 of file FXRealSpinDial.cpp.
Referenced by FXRealSpinDialBtn().
long FX::FXRealSpinDialBtn::onKey (FXObject * o, FXSelector s, void * p)
Definition at line 308 of file FXRealSpinDial.cpp.
Referenced by FXRealSpinDialBtn().
FXRealSpinDialBtn& FX::FXRealSpinDialBtn::operator= (const FXRealSpinDialBtn &) private
The documentation for this class was generated from the following file:
FXRealSpinDial.cpp