SUMO - Simulation of Urban MObility: PHEMlightdll.Start Class Reference
PHEMlightdll.Start Class Reference
Public Member Functions
bool CALC_Array (string VEH, List< double > Time, List< double > Velocity, List< double > Gradient, out List< VehicleResult > VehicleResultsOrg, bool fleetMix=false, string PHEMDataV="V4", string CommentPref="c")
bool CALC_Single (string VEH, double Time, double Velocity, double acc, double Gradient, out List< VehicleResult > VehicleResultsOrg, bool fleetMix=false, string PHEMDataV="V4", string CommentPref="c")
bool ExportData (string path, string vehicle, List< VehicleResult > _VehicleResult)
bool ExportSumData (string path, string vehicle, string cycle, VehicleResult _VehicleResult)
VehicleResult GenerateSumData (List< VehicleResult > _VehicleResult)
Data Fields
Helpers Helper = new Helpers()
Private Attributes
string _DataPath
CEPHandler DataInput
Detailed Description
Definition at line 13 of file Start.cs.
Member Function Documentation
bool PHEMlightdll.Start.CALC_Array (string VEH, List< double > Time, List< double > Velocity, List< double > Gradient, out List< VehicleResult > VehicleResultsOrg, bool fleetMix = false, string PHEMDataV = "V4", string CommentPref = "c") inline
Definition at line 51 of file Start.cs.
References PHEMlightdll::CEPHandler.CEPS, PHEMlightdll::Helpers.CommentPrefix, PHEMlightdll.PHEMLight.CreateVehicleStateData(), PHEMlightdll::Helpers.ErrMsg, FLEET, PHEMlightdll::Helpers.gClass, PHEMlightdll::CEPHandler.GetCEP(), PHEMlightdll::CEPHandler.GetFleetCEP(), PHEMlightdll::Helpers.PHEMDataV, PHEMlightdll::CEPHandler.ReadFleetShares(), and PHEMlightdll::Helpers.setclass().
bool PHEMlightdll.Start.CALC_Single (string VEH, double Time, double Velocity, double acc, double Gradient, out List< VehicleResult > VehicleResultsOrg, bool fleetMix = false, string PHEMDataV = "V4", string CommentPref = "c") inline
Definition at line 144 of file Start.cs.
References PHEMlightdll::CEPHandler.CEPS, PHEMlightdll::Helpers.CommentPrefix, PHEMlightdll.PHEMLight.CreateVehicleStateData(), FLEET, PHEMlightdll::Helpers.gClass, PHEMlightdll::CEPHandler.GetCEP(), PHEMlightdll::CEPHandler.GetFleetCEP(), PHEMlightdll::Helpers.PHEMDataV, PHEMlightdll::CEPHandler.ReadFleetShares(), and PHEMlightdll::Helpers.setclass().
bool PHEMlightdll.Start.ExportData (string path, string vehicle, List< VehicleResult > _VehicleResult) inline
Definition at line 223 of file Start.cs.
References PHEMlightdll.VehicleResult.Accelaration, PHEMlightdll.EmissionData.CO, PHEMlightdll.EmissionData.CO2, PHEMlightdll.VehicleResult.EmissionData, PHEMlightdll.EmissionData.FC, PHEMlightdll.EmissionData.FCel, PHEMlightdll.VehicleResult.Grad, PHEMlightdll.EmissionData.HC, PHEMlightdll.EmissionData.NOx, PHEMlightdll.EmissionData.PM, PHEMlightdll.VehicleResult.PNormDrive, PHEMlightdll.VehicleResult.PNormRated, PHEMlightdll.VehicleResult.Power, PHEMlightdll.VehicleResult.PPos, PHEMlightdll.VehicleResult.Speed, and PHEMlightdll.VehicleResult.Time.
bool PHEMlightdll.Start.ExportSumData (string path, string vehicle, string cycle, VehicleResult _VehicleResult) inline
Definition at line 273 of file Start.cs.
References PHEMlightdll.VehicleResult.Accelaration, PHEMlightdll.EmissionData.CO, PHEMlightdll.EmissionData.CO2, PHEMlightdll.VehicleResult.EmissionData, PHEMlightdll.EmissionData.FC, PHEMlightdll.EmissionData.FCel, PHEMlightdll.VehicleResult.Grad, PHEMlightdll.EmissionData.HC, PHEMlightdll.EmissionData.NOx, PHEMlightdll.EmissionData.PM, PHEMlightdll.VehicleResult.PNormDrive, PHEMlightdll.VehicleResult.PNormRated, PHEMlightdll.VehicleResult.Power, PHEMlightdll.VehicleResult.PPos, PHEMlightdll.VehicleResult.Speed, and PHEMlightdll.VehicleResult.Time.
VehicleResult PHEMlightdll.Start.GenerateSumData (List< VehicleResult > _VehicleResult) inline
Definition at line 325 of file Start.cs.
References PHEMlightdll.VehicleResult.Accelaration, PHEMlightdll.EmissionData.CO, PHEMlightdll.EmissionData.CO2, PHEMlightdll.VehicleResult.EmissionData, PHEMlightdll.EmissionData.FC, PHEMlightdll.EmissionData.FCel, PHEMlightdll.VehicleResult.Grad, PHEMlightdll.EmissionData.HC, PHEMlightdll.EmissionData.NOx, PHEMlightdll.EmissionData.PM, PHEMlightdll.VehicleResult.PNormDrive, PHEMlightdll.VehicleResult.PNormRated, PHEMlightdll.VehicleResult.Power, PHEMlightdll.VehicleResult.PPos, and PHEMlightdll.VehicleResult.Speed.
Field Documentation
string PHEMlightdll.Start._DataPath private
Definition at line 15 of file Start.cs.
CEPHandler PHEMlightdll.Start.DataInput private
Definition at line 16 of file Start.cs.
Helpers PHEMlightdll.Start.Helper = new Helpers()
Definition at line 17 of file Start.cs.
Referenced by PHEMlightdll.PHEMLight.CreateVehicleStateData().
The documentation for this class was generated from the following file:
Start.cs