SUMO - Simulation of Urban MObility: TraCIAPI::InductionLoopScope Class Reference
TraCIAPI::InductionLoopScope Class Reference
Scope for interaction with inductive loops.
#include <TraCIAPI.h>
Data Structures
struct VehicleData
Public Member Functions
std::vector< std::string > getIDList () const
std::string getLaneID (const std::string &loopID) const
SUMOReal getLastStepMeanLength (const std::string &loopID) const
SUMOReal getLastStepMeanSpeed (const std::string &loopID) const
SUMOReal getLastStepOccupancy (const std::string &loopID) const
std::vector< std::string > getLastStepVehicleIDs (const std::string &loopID) const
int getLastStepVehicleNumber (const std::string &loopID) const
SUMOReal getPosition (const std::string &loopID) const
SUMOReal getTimeSinceDetection (const std::string &loopID) const
std::vector< VehicleData > getVehicleData (const std::string &loopID) const
InductionLoopScope (TraCIAPI &parent)
virtual ~InductionLoopScope ()
Protected Attributes
TraCIAPI & myParent
The parent TraCI client which offers the connection.
Private Member Functions
InductionLoopScope (const InductionLoopScope &src)
invalidated copy constructor
InductionLoopScope & operator= (const InductionLoopScope &src)
invalidated assignment operator
Detailed Description
Scope for interaction with inductive loops.
Definition at line 303 of file TraCIAPI.h.
Constructor & Destructor Documentation
TraCIAPI::InductionLoopScope::InductionLoopScope (TraCIAPI & parent) inline
Definition at line 305 of file TraCIAPI.h.
virtual TraCIAPI::InductionLoopScope::~InductionLoopScope () inline virtual
Definition at line 306 of file TraCIAPI.h.
TraCIAPI::InductionLoopScope::InductionLoopScope (const InductionLoopScope & src) private
invalidated copy constructor
Member Function Documentation
std::vector< std::string > TraCIAPI::InductionLoopScope::getIDList () const
Definition at line 773 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, ID_LIST, and SUMOReal.
Referenced by TraCITestClient::testAPI().
std::string TraCIAPI::InductionLoopScope::getLaneID (const std::string & loopID) const
Definition at line 783 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, and VAR_LANE_ID.
SUMOReal TraCIAPI::InductionLoopScope::getLastStepMeanLength (const std::string & loopID) const
Definition at line 808 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, LAST_STEP_LENGTH, and SUMOReal.
SUMOReal TraCIAPI::InductionLoopScope::getLastStepMeanSpeed (const std::string & loopID) const
Definition at line 793 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, and LAST_STEP_MEAN_SPEED.
SUMOReal TraCIAPI::InductionLoopScope::getLastStepOccupancy (const std::string & loopID) const
Definition at line 803 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, LAST_STEP_OCCUPANCY, and SUMOReal.
std::vector< std::string > TraCIAPI::InductionLoopScope::getLastStepVehicleIDs (const std::string & loopID) const
Definition at line 798 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, LAST_STEP_VEHICLE_ID_LIST, and SUMOReal.
int TraCIAPI::InductionLoopScope::getLastStepVehicleNumber (const std::string & loopID) const
Definition at line 788 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, LAST_STEP_VEHICLE_NUMBER, and SUMOReal.
SUMOReal TraCIAPI::InductionLoopScope::getPosition (const std::string & loopID) const
Definition at line 778 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, and VAR_POSITION.
SUMOReal TraCIAPI::InductionLoopScope::getTimeSinceDetection (const std::string & loopID) const
Definition at line 813 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, and LAST_STEP_TIME_SINCE_DETECTION.
std::vector< TraCIAPI::InductionLoopScope::VehicleData > TraCIAPI::InductionLoopScope::getVehicleData (const std::string & loopID) const
Definition at line 818 of file TraCIAPI.cpp.
References CMD_GET_INDUCTIONLOOP_VARIABLE, TraCIAPI::InductionLoopScope::VehicleData::entryTime, TraCIAPI::InductionLoopScope::VehicleData::id, LAST_STEP_VEHICLE_DATA, TraCIAPI::InductionLoopScope::VehicleData::leaveTime, TraCIAPI::InductionLoopScope::VehicleData::length, tcpip::Storage::readDouble(), tcpip::Storage::readInt(), tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), TYPE_COMPOUND, and TraCIAPI::InductionLoopScope::VehicleData::typeID.
Referenced by TraCITestClient::testAPI().
InductionLoopScope& TraCIAPI::InductionLoopScope::operator= (const InductionLoopScope & src) private
invalidated assignment operator
Field Documentation
TraCIAPI& TraCIAPI::TraCIScopeWrapper::myParent protected inherited
The parent TraCI client which offers the connection.
Definition at line 206 of file TraCIAPI.h.
The documentation for this class was generated from the following files:
TraCIAPI.h
TraCIAPI.cpp