SUMO - Simulation of Urban MObility: ROPerson::TripItem Class Reference
ROPerson::TripItem Class Reference abstract
A TripItem is part of a trip, e.g., go from here to here by car.
#include <ROPerson.h>
Public Member Functions
virtual const ROEdge * getDestination () const =0
virtual const ROEdge * getOrigin () const =0
virtual void saveAsXML (OutputDevice &os) const =0
virtual ~TripItem ()
Destructor.
Detailed Description
A TripItem is part of a trip, e.g., go from here to here by car.
Definition at line 141 of file ROPerson.h.
Constructor & Destructor Documentation
virtual ROPerson::TripItem::~TripItem () inline virtual
Destructor.
Definition at line 144 of file ROPerson.h.
References ROPerson::PlanItem::getDestination(), ROPerson::PlanItem::getOrigin(), and ROPerson::PlanItem::saveAsXML().
Member Function Documentation
virtual const ROEdge* ROPerson::TripItem::getDestination () const pure virtual
Implemented in ROPerson::Walk, and ROPerson::Ride.
virtual const ROEdge* ROPerson::TripItem::getOrigin () const pure virtual
Implemented in ROPerson::Walk, and ROPerson::Ride.
virtual void ROPerson::TripItem::saveAsXML (OutputDevice & os) const pure virtual
Implemented in ROPerson::Walk, and ROPerson::Ride.
The documentation for this class was generated from the following file:
ROPerson.h