SUMO - Simulation of Urban MObility: AbstractMutex Class Reference
AbstractMutex Class Reference abstract
An abstract class for encapsulating mutex implementations.
#include <AbstractMutex.h>
Data Structures
class ScopedLocker
A mutex encapsulator which locks/unlocks the given mutex on construction/destruction, respectively.
Public Member Functions
AbstractMutex ()
Constructor.
virtual void lock ()=0
Locks the mutex.
virtual void unlock ()=0
Unlocks the mutex.
virtual ~AbstractMutex ()
Destructor.
Detailed Description
An abstract class for encapsulating mutex implementations.
This class defines access to a mutex. The implementation may differ.
Within gui-applications, FXMutexes may be used while this is improper for command-line applications. Normally, they do not need mutexes unless a synchronized communication with an external application is established. In these cases, a further class should be implemented.
Definition at line 49 of file AbstractMutex.h.
Constructor & Destructor Documentation
AbstractMutex::AbstractMutex () inline
Constructor.
Definition at line 52 of file AbstractMutex.h.
virtual AbstractMutex::~AbstractMutex () inline virtual
Destructor.
Definition at line 56 of file AbstractMutex.h.
References lock(), and unlock().
Member Function Documentation
virtual void AbstractMutex::lock () pure virtual
Locks the mutex.
Implemented in MFXMutex.
Referenced by MsgHandler::addRetriever(), MsgHandler::beginProcessMsg(), MsgHandler::cleanupOnEnd(), MsgHandler::clear(), MsgHandler::endProcessMsg(), MsgHandler::inform(), MsgHandler::removeRetriever(), AbstractMutex::ScopedLocker::ScopedLocker(), and ~AbstractMutex().
virtual void AbstractMutex::unlock () pure virtual
Unlocks the mutex.
Implemented in MFXMutex.
Referenced by MsgHandler::addRetriever(), MsgHandler::beginProcessMsg(), MsgHandler::cleanupOnEnd(), MsgHandler::clear(), MsgHandler::endProcessMsg(), MsgHandler::inform(), MsgHandler::removeRetriever(), ~AbstractMutex(), and AbstractMutex::ScopedLocker::~ScopedLocker().
The documentation for this class was generated from the following file:
AbstractMutex.h