SUMO - Simulation of Urban MObility: NIImporter_OpenStreetMap Class Reference
NIImporter_OpenStreetMap Class Reference
Importer for networks stored in OpenStreetMap format.
#include <NIImporter_OpenStreetMap.h>
Data Structures
class CompareEdges
Functor which compares two Edges.
class CompareNodes
Functor which compares two NIOSMNodes according to their coordinates.
struct Edge
An internal definition of a loaded edge.
class EdgesHandler
A class which extracts OSM-edges from a parsed OSM-file.
struct NIOSMNode
An internal representation of an OSM-node.
class NodesHandler
A class which extracts OSM-nodes from a parsed OSM-file.
class RelationHandler
A class which extracts relevant relation information from a parsed OSM-file.
Static Public Member Functions
static void loadNetwork (const OptionsCont &oc, NBNetBuilder &nb)
Loads content of the optionally given OSM file.
Protected Types
enum WayType {
WAY_NONE = 0, WAY_FORWARD = 1, WAY_BACKWARD = 2, WAY_BOTH = WAY_FORWARD | WAY_BACKWARD,
WAY_UNKNOWN = 4
}
Protected Member Functions
void load (const OptionsCont &oc, NBNetBuilder &nb)
NIImporter_OpenStreetMap ()
~NIImporter_OpenStreetMap ()
Static Protected Attributes
static const long long int INVALID_ID = std::numeric_limits<long long int>::max()
static const SUMOReal MAXSPEED_UNGIVEN = -1
Private Member Functions
std::map< NBNode *, SUMOReal > getNeighboringNodes (NBNode *node, SUMOReal maxDist)
collect neighboring nodes with their road distance
int insertEdge (Edge *e, int index, NBNode *from, NBNode *to, const std::vector< long long int > &passed, NBNetBuilder &nb)
Builds an NBEdge.
NBNode * insertNodeChecking (long long int id, NBNodeCont &nc, NBTrafficLightLogicCont &tlsc)
Builds an NBNode.
void reconstructLayerElevation (SUMOReal layerElevation, NBNetBuilder &nb)
reconstruct elevation from layer info
Private Attributes
std::map< long long int, Edge * > myEdges
the map from OSM way ids to edge objects
std::map< std::string, std::string > myKnownCompoundTypes
The compound types that have already been mapped to other known types.
std::map< long long int, NIOSMNode * > myOSMNodes
the map from OSM node ids to actual nodes
std::set< NIOSMNode *, CompareNodes > myUniqueNodes
the set of unique nodes used in NodesHandler, used when freeing memory
std::set< std::string > myUnusableTypes
The compounds types that do not contain known types.
Static Private Attributes
static const std::string compoundTypeSeparator
The separator within newly created compound type names.
Friends
class NodesHandler
Detailed Description
Importer for networks stored in OpenStreetMap format.
Definition at line 63 of file NIImporter_OpenStreetMap.h.
Member Enumeration Documentation
enum NIImporter_OpenStreetMap::WayType protected
Enumerator
WAY_NONE
WAY_FORWARD
WAY_BACKWARD
WAY_BOTH
WAY_UNKNOWN
Definition at line 108 of file NIImporter_OpenStreetMap.h.
Constructor & Destructor Documentation
NIImporter_OpenStreetMap::NIImporter_OpenStreetMap () protected
Definition at line 117 of file NIImporter_OpenStreetMap.cpp.
NIImporter_OpenStreetMap::~NIImporter_OpenStreetMap () protected
Definition at line 120 of file NIImporter_OpenStreetMap.cpp.
References myEdges, and myUniqueNodes.
Member Function Documentation
std::map< NBNode *, SUMOReal > NIImporter_OpenStreetMap::getNeighboringNodes (NBNode * node, SUMOReal maxDist) private
collect neighboring nodes with their road distance
Definition at line 1251 of file NIImporter_OpenStreetMap.cpp.
References NBNode::getEdges(), NBEdge::getFromNode(), NBEdge::getGeometry(), NBEdge::getToNode(), NBNode::hasIncoming(), PositionVector::length2D(), MIN2(), and SUMOReal.
Referenced by reconstructLayerElevation().
int NIImporter_OpenStreetMap::insertEdge (Edge * e, int index, NBNode * from, NBNode * to, const std::vector< long long int > & passed, NBNetBuilder & nb) private
Builds an NBEdge.
Parameters
[in] e The definition of the edge
[in] index The index of the edge (in the case it is split along her nodes)
[in] from The origin node of the edge
[in] to The destination node of the edge
[in] passed The list of passed nodes (geometry information)
[in] osmNodes Container of node definitions for getting information about nodes from
[in,out] The NetBuilder instance
Returns
the new index if the edge is split
Exceptions
ProcessError If the edge could not be added to the container
Definition at line 297 of file NIImporter_OpenStreetMap.cpp.
References NBEdge::addBikeLane(), NBEdge::addSidewalk(), compoundTypeSeparator, NBTypeCont::copyRestrictionsAndAttrs(), NIImporter_OpenStreetMap::NIOSMNode::ele, StringUtils::escapeXML(), NBTypeCont::getBikeLaneWidth(), NBNetBuilder::getEdgeCont(), NBTypeCont::getIsOneWay(), NBNetBuilder::getNodeCont(), NBTypeCont::getNumLanes(), NBTypeCont::getPermissions(), NBNode::getPosition(), NBTypeCont::getPriority(), NBTypeCont::getShallBeDiscarded(), NBTypeCont::getSidewalkWidth(), NBTypeCont::getSpeed(), NBNetBuilder::getTLLogicCont(), NBNetBuilder::getTypeCont(), NBTypeCont::getWidth(), StringTokenizer::hasNext(), NIImporter_OpenStreetMap::Edge::id, NBTypeCont::insert(), NBEdgeCont::insert(), insertNodeChecking(), joinToString(), NBTypeCont::knows(), LANESPREAD_CENTER, LANESPREAD_RIGHT, NIImporter_OpenStreetMap::NIOSMNode::lat, NIImporter_OpenStreetMap::NIOSMNode::lon, MAX2(), MAXSPEED_UNGIVEN, NIImporter_OpenStreetMap::Edge::myBuswayType, NIImporter_OpenStreetMap::Edge::myCyclewayType, NIImporter_OpenStreetMap::Edge::myHighWayType, NIImporter_OpenStreetMap::Edge::myIsOneWay, myKnownCompoundTypes, NIImporter_OpenStreetMap::Edge::myMaxSpeed, NIImporter_OpenStreetMap::Edge::myNoLanes, NIImporter_OpenStreetMap::Edge::myNoLanesForward, myOSMNodes, myUnusableTypes, StringTokenizer::next(), PositionVector::push_back_noDoublePos(), PositionVector::reverse(), NBEdge::setPermissions(), StringTokenizer::size(), NIImporter_OpenStreetMap::Edge::streetName, SUMO_const_laneWidth, SUMOReal, SVC_BICYCLE, SVC_BUS, toString(), NBNetBuilder::transformCoordinates(), NBEdge::UNSPECIFIED_OFFSET, NBEdge::UNSPECIFIED_WIDTH, WAY_BACKWARD, WAY_FORWARD, WAY_UNKNOWN, WRITE_ERROR, WRITE_MESSAGE, and WRITE_WARNING.
Referenced by load().
NBNode * NIImporter_OpenStreetMap::insertNodeChecking (long long int id, NBNodeCont & nc, NBTrafficLightLogicCont & tlsc) private
Builds an NBNode.
If a node with the given id is already known, nothing is done. Otherwise, the position and other information of the node is retrieved from the given node map, the node is built and added to the given node container. If the node is controlled by a tls, the according tls is built and added to the tls container.
Parameters
[in] id The id of the node to build
[in] osmNodes Map of node ids to information about these
[in,out] nc The node container to add the built node to
[in,out] tlsc The traffic lights logic container to add the built tls to
Returns
The built/found node
Exceptions
ProcessError If the tls could not be added to the container
Definition at line 263 of file NIImporter_OpenStreetMap.cpp.
References NIImporter_OpenStreetMap::NIOSMNode::ele, StringBijection< T >::get(), OptionsCont::getOptions(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NIImporter_OpenStreetMap::NIOSMNode::lat, NIImporter_OpenStreetMap::NIOSMNode::lon, myOSMNodes, NIImporter_OpenStreetMap::NIOSMNode::node, NBNodeCont::retrieve(), NIImporter_OpenStreetMap::NIOSMNode::tlsControlled, toString(), SUMOXMLDefinitions::TrafficLightTypes, NBNetBuilder::transformCoordinates(), and WRITE_ERROR.
Referenced by insertEdge(), and load().
void NIImporter_OpenStreetMap::load (const OptionsCont & oc, NBNetBuilder & nb) protected
Definition at line 133 of file NIImporter_OpenStreetMap.cpp.
References OptionsCont::getBool(), OptionsCont::getFloat(), NBNetBuilder::getNodeCont(), OptionsCont::getStringVector(), NBNetBuilder::getTLLogicCont(), NIImporter_OpenStreetMap::Edge::id, insertEdge(), insertNodeChecking(), FileHelpers::isReadable(), OptionsCont::isSet(), NIImporter_OpenStreetMap::Edge::myCurrentIsRoad, NIImporter_OpenStreetMap::Edge::myCurrentNodes, myEdges, myOSMNodes, myUniqueNodes, PROGRESS_BEGIN_MESSAGE, PROGRESS_DONE_MESSAGE, reconstructLayerElevation(), XMLSubSys::runParser(), GenericSAXHandler::setFileName(), SUMOReal, toString(), WRITE_ERROR, WRITE_MESSAGE, and WRITE_WARNING.
Referenced by loadNetwork().
void NIImporter_OpenStreetMap::loadNetwork (const OptionsCont & oc, NBNetBuilder & nb) static
Loads content of the optionally given OSM file.
If the option "osm-files" is set, the file(s) stored therein is read and the network definition stored therein is stored within the given network builder.
If the option "osm-files" is not set, this method simply returns.
Parameters
[in] oc The options to use
[in,out] nb The network builder to fill
Definition at line 111 of file NIImporter_OpenStreetMap.cpp.
References load().
Referenced by NILoader::load().
void NIImporter_OpenStreetMap::reconstructLayerElevation (SUMOReal layerElevation, NBNetBuilder & nb) private
reconstruct elevation from layer info
Definition at line 1109 of file NIImporter_OpenStreetMap.cpp.
References NBEdgeCont::begin(), NBEdgeCont::end(), NBNetBuilder::getEdgeCont(), NBEdge::getFromNode(), NBEdge::getGeometry(), Named::getID(), getNeighboringNodes(), NBNetBuilder::getNodeCont(), NBNode::getPosition(), NBEdge::getToNode(), NBNode::getType(), PositionVector::length2D(), max, MAX2(), NIImporter_OpenStreetMap::Edge::myCurrentNodes, myEdges, NIImporter_OpenStreetMap::Edge::myLayer, POSITION_EPS, NBNode::reinit(), NBNodeCont::retrieve(), NBEdge::setGeometry(), SUMOReal, and toString().
Referenced by load().
Friends And Related Function Documentation
friend class NodesHandler friend
Definition at line 247 of file NIImporter_OpenStreetMap.h.
Field Documentation
const std::string NIImporter_OpenStreetMap::compoundTypeSeparator static private
The separator within newly created compound type names.
Definition at line 179 of file NIImporter_OpenStreetMap.h.
Referenced by insertEdge(), NIImporter_OpenStreetMap::EdgesHandler::myStartElement(), and NIImporter_OpenStreetMap::CompareEdges::operator()().
const long long int NIImporter_OpenStreetMap::INVALID_ID = std::numeric_limits<long long int>::max() static protected
Definition at line 241 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::RelationHandler::applyRestriction(), NIImporter_OpenStreetMap::RelationHandler::myEndElement(), NIImporter_OpenStreetMap::RelationHandler::myStartElement(), and NIImporter_OpenStreetMap::RelationHandler::resetValues().
const SUMOReal NIImporter_OpenStreetMap::MAXSPEED_UNGIVEN = -1 static protected
Definition at line 240 of file NIImporter_OpenStreetMap.h.
Referenced by NIImporter_OpenStreetMap::EdgesHandler::EdgesHandler(), and insertEdge().
std::map<long long int, Edge*> NIImporter_OpenStreetMap::myEdges private
the map from OSM way ids to edge objects
Definition at line 193 of file NIImporter_OpenStreetMap.h.
Referenced by load(), reconstructLayerElevation(), and ~NIImporter_OpenStreetMap().
std::map<std::string, std::string> NIImporter_OpenStreetMap::myKnownCompoundTypes private
The compound types that have already been mapped to other known types.
Definition at line 199 of file NIImporter_OpenStreetMap.h.
Referenced by insertEdge().
std::map<long long int, NIOSMNode*> NIImporter_OpenStreetMap::myOSMNodes private
the map from OSM node ids to actual nodes
Note
: NIOSMNodes may appear multiple times due to substition
Definition at line 181 of file NIImporter_OpenStreetMap.h.
Referenced by insertEdge(), insertNodeChecking(), and load().
std::set<NIOSMNode*, CompareNodes> NIImporter_OpenStreetMap::myUniqueNodes private
the set of unique nodes used in NodesHandler, used when freeing memory
Definition at line 189 of file NIImporter_OpenStreetMap.h.
Referenced by load(), and ~NIImporter_OpenStreetMap().
std::set<std::string> NIImporter_OpenStreetMap::myUnusableTypes private
The compounds types that do not contain known types.
Definition at line 196 of file NIImporter_OpenStreetMap.h.
Referenced by insertEdge().
The documentation for this class was generated from the following files:
NIImporter_OpenStreetMap.h
NIImporter_OpenStreetMap.cpp