SUMO - Simulation of Urban MObility: NBNodeTypeComputer Class Reference
NBNodeTypeComputer Class Reference
#include <NBAlgorithms.h>
Static Public Member Functions
static void computeNodeTypes (NBNodeCont &nc)
Computes node types.
Detailed Description
Definition at line 205 of file NBAlgorithms.h.
Member Function Documentation
void NBNodeTypeComputer::computeNodeTypes (NBNodeCont & nc) static
Computes node types.
Parameters
[in] nc The container of nodes to loop along
Definition at line 227 of file NBAlgorithms.cpp.
References NBNodeCont::begin(), NBNodeCont::end(), NBNode::getEdges(), NBNode::getOppositeIncoming(), NBNode::isSimpleContinuation(), isWaterway(), MAX2(), NBNode::myIncomingEdges, NBNode::myType, NODETYPE_NOJUNCTION, NODETYPE_PRIORITY, NODETYPE_RIGHT_BEFORE_LEFT, NODETYPE_UNKNOWN, and SUMOReal.
Referenced by NBNetBuilder::compute().
The documentation for this class was generated from the following files:
NBAlgorithms.h
NBAlgorithms.cpp