SUMO - Simulation of Urban MObility: GNEAdditionalFrame::editorParameters Class Reference
GNEAdditionalFrame::editorParameters Class Reference
#include <GNEAdditionalFrame.h>
Public Types
enum additionalReferencePoint { GNE_ADDITIONALREFERENCEPOINT_LEFT, GNE_ADDITIONALREFERENCEPOINT_RIGHT, GNE_ADDITIONALREFERENCEPOINT_CENTER }
FOX-declaration.
Public Member Functions
editorParameters (FXComposite *parent, FXObject *tgt)
constructor
additionalReferencePoint getActualReferencePoint ()
get actual reference point
SUMOReal getLenght ()
get value of lenght
void hideLengthField ()
hide length field
void hideReferencePoint ()
hide refence point comboBox
bool isBlockEnabled ()
check if block is enabled
bool isForcePositionEnabled ()
check if force position is enabled
void showLengthField ()
show length field
void showReferencePoint ()
show refence point comboBox
~editorParameters ()
destructor
FOX-callbacks
Called when the user enters another reference point
long onCmdSelectReferencePoint (FXObject *, FXSelector, void *)
long onCmdHelp (FXObject *, FXSelector, void *)
Called when help button is pressed.
Protected Member Functions
editorParameters ()
FOX needs this.
Private Attributes
FXButton * helpReferencePoint
Button for help about the reference point.
additionalReferencePoint myActualAdditionalReferencePoint
actual additional reference point selected in the match Box
FXMenuCheck * myCheckBlock
checkBox for blocking movement
FXMenuCheck * myCheckForcePosition
checkBox for the option "force position"
FXLabel * myLengthLabel
Label for lenght.
FXTextField * myLengthTextField
textField for lenght
FXComboBox * myReferencePointMatchBox
match box with the list of reference points
Detailed Description
Definition at line 249 of file GNEAdditionalFrame.h.
Member Enumeration Documentation
enum GNEAdditionalFrame::editorParameters::additionalReferencePoint
FOX-declaration.
list of the reference points
Enumerator
GNE_ADDITIONALREFERENCEPOINT_LEFT
GNE_ADDITIONALREFERENCEPOINT_RIGHT
GNE_ADDITIONALREFERENCEPOINT_CENTER
Definition at line 255 of file GNEAdditionalFrame.h.
Constructor & Destructor Documentation
GNEAdditionalFrame::editorParameters::editorParameters (FXComposite * parent, FXObject * tgt)
constructor
Definition at line 936 of file GNEAdditionalFrame.cpp.
References helpReferencePoint, MID_GNE_MODE_ADDITIONAL_CHANGEPARAMETER_TEXT, MID_GNE_MODE_ADDITIONAL_FORCEPOSITION, MID_GNE_MODE_ADDITIONAL_REFERENCEPOINT, MID_GNE_SET_BLOCKING, MID_HELP, myCheckBlock, myCheckForcePosition, myLengthLabel, myLengthTextField, and myReferencePointMatchBox.
GNEAdditionalFrame::editorParameters::~editorParameters ()
destructor
Definition at line 976 of file GNEAdditionalFrame.cpp.
GNEAdditionalFrame::editorParameters::editorParameters () inline protected
FOX needs this.
Definition at line 304 of file GNEAdditionalFrame.h.
Member Function Documentation
GNEAdditionalFrame::editorParameters::additionalReferencePoint GNEAdditionalFrame::editorParameters::getActualReferencePoint ()
get actual reference point
Definition at line 1008 of file GNEAdditionalFrame.cpp.
References myActualAdditionalReferencePoint, and SUMOReal.
Referenced by GNEAdditionalFrame::setEndPosition(), and GNEAdditionalFrame::setStartPosition().
SUMOReal GNEAdditionalFrame::editorParameters::getLenght ()
get value of lenght
Definition at line 1014 of file GNEAdditionalFrame.cpp.
References myLengthTextField.
Referenced by GNEAdditionalFrame::addAdditional().
void GNEAdditionalFrame::editorParameters::hideLengthField ()
hide length field
Definition at line 987 of file GNEAdditionalFrame.cpp.
References myLengthLabel, and myLengthTextField.
Referenced by GNEAdditionalFrame::setParametersOfAdditional().
void GNEAdditionalFrame::editorParameters::hideReferencePoint ()
hide refence point comboBox
Definition at line 1001 of file GNEAdditionalFrame.cpp.
References myCheckForcePosition, and myReferencePointMatchBox.
Referenced by GNEAdditionalFrame::setParametersOfAdditional().
bool GNEAdditionalFrame::editorParameters::isBlockEnabled ()
check if block is enabled
Definition at line 1020 of file GNEAdditionalFrame.cpp.
References myCheckBlock.
Referenced by GNEAdditionalFrame::addAdditional().
bool GNEAdditionalFrame::editorParameters::isForcePositionEnabled ()
check if force position is enabled
Definition at line 1026 of file GNEAdditionalFrame.cpp.
References myCheckForcePosition.
Referenced by GNEAdditionalFrame::setEndPosition(), and GNEAdditionalFrame::setStartPosition().
long GNEAdditionalFrame::editorParameters::onCmdHelp (FXObject * , FXSelector , void *)
Called when help button is pressed.
Definition at line 1040 of file GNEAdditionalFrame.cpp.
long GNEAdditionalFrame::editorParameters::onCmdSelectReferencePoint (FXObject * , FXSelector , void *)
Definition at line 1032 of file GNEAdditionalFrame.cpp.
References myActualAdditionalReferencePoint, and myReferencePointMatchBox.
void GNEAdditionalFrame::editorParameters::showLengthField ()
show length field
Definition at line 980 of file GNEAdditionalFrame.cpp.
References myLengthLabel, and myLengthTextField.
Referenced by GNEAdditionalFrame::setParametersOfAdditional().
void GNEAdditionalFrame::editorParameters::showReferencePoint ()
show refence point comboBox
Definition at line 994 of file GNEAdditionalFrame.cpp.
References myCheckForcePosition, and myReferencePointMatchBox.
Referenced by GNEAdditionalFrame::setParametersOfAdditional().
Field Documentation
FXButton* GNEAdditionalFrame::editorParameters::helpReferencePoint private
Button for help about the reference point.
Definition at line 311 of file GNEAdditionalFrame.h.
Referenced by editorParameters().
additionalReferencePoint GNEAdditionalFrame::editorParameters::myActualAdditionalReferencePoint private
actual additional reference point selected in the match Box
Definition at line 314 of file GNEAdditionalFrame.h.
Referenced by getActualReferencePoint(), and onCmdSelectReferencePoint().
FXMenuCheck* GNEAdditionalFrame::editorParameters::myCheckBlock private
checkBox for blocking movement
Definition at line 326 of file GNEAdditionalFrame.h.
Referenced by editorParameters(), and isBlockEnabled().
FXMenuCheck* GNEAdditionalFrame::editorParameters::myCheckForcePosition private
checkBox for the option "force position"
Definition at line 323 of file GNEAdditionalFrame.h.
Referenced by editorParameters(), hideReferencePoint(), isForcePositionEnabled(), and showReferencePoint().
FXLabel* GNEAdditionalFrame::editorParameters::myLengthLabel private
Label for lenght.
Definition at line 317 of file GNEAdditionalFrame.h.
Referenced by editorParameters(), hideLengthField(), and showLengthField().
FXTextField* GNEAdditionalFrame::editorParameters::myLengthTextField private
textField for lenght
Definition at line 320 of file GNEAdditionalFrame.h.
Referenced by editorParameters(), getLenght(), hideLengthField(), and showLengthField().
FXComboBox* GNEAdditionalFrame::editorParameters::myReferencePointMatchBox private
match box with the list of reference points
Definition at line 308 of file GNEAdditionalFrame.h.
Referenced by editorParameters(), hideReferencePoint(), onCmdSelectReferencePoint(), and showReferencePoint().
The documentation for this class was generated from the following files:
GNEAdditionalFrame.h
GNEAdditionalFrame.cpp