SUMO - Simulation of Urban MObility: MSMeanData_Emissions::MSLaneMeanDataValues Class Reference
MSMeanData_Emissions::MSLaneMeanDataValues Class Reference
Data structure for mean (aggregated) edge/lane values.
#include <MSMeanData_Emissions.h>
Public Types
enum Notification {
NOTIFICATION_DEPARTED, NOTIFICATION_JUNCTION, NOTIFICATION_SEGMENT, NOTIFICATION_LANE_CHANGE,
NOTIFICATION_TELEPORT, NOTIFICATION_PARKING, NOTIFICATION_ARRIVED, NOTIFICATION_VAPORIZED,
NOTIFICATION_TELEPORT_ARRIVED
}
Definition of a vehicle state.
Public Member Functions
void addTo (MSMeanData::MeanDataValues &val) const
Add the values of this to the given one and store them there.
const std::string & getDescription () const
const MSLane * getLane () const
Returns the lane the reminder works on.
virtual SUMOReal getSamples () const
Returns the number of collected sample seconds.
virtual bool isEmpty () const
Returns whether any data was collected.
MSLaneMeanDataValues (MSLane *const lane, const SUMOReal length, const bool doAdd, const std::set< std::string > *const vTypes=0, const MSMeanData_Emissions *parent=0)
Constructor.
virtual bool notifyEnter (SUMOVehicle &veh, MSMoveReminder::Notification reason)
Called if the vehicle enters the reminder's lane.
virtual bool notifyLeave (SUMOVehicle &veh, SUMOReal lastPos, MSMoveReminder::Notification reason)
Called if the vehicle leaves the reminder's lane.
bool notifyMove (SUMOVehicle &veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed)
Checks whether the reminder still has to be notified about the vehicle moves.
void reset (bool afterWrite=false)
Resets values so they may be used for the next interval.
void setDescription (const std::string &description)
virtual void update ()
Called if a per timestep update is needed. Default does nothing.
bool vehicleApplies (const SUMOVehicle &veh) const
Tests whether the vehicles type is to be regarded.
void write (OutputDevice &dev, const SUMOTime period, const SUMOReal numLanes, const SUMOReal defaultTravelTime, const int numVehicles=-1) const
Writes output values into the given stream.
virtual ~MSLaneMeanDataValues ()
Destructor.
Interface methods, to be derived by subclasses
void updateDetector (SUMOVehicle &veh, SUMOReal entryPos, SUMOReal leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp)
Protected Member Functions
void notifyMoveInternal (SUMOVehicle &veh, SUMOReal timeOnLane, SUMOReal speed)
Internal notification about the vehicle moves.
void removeFromVehicleUpdateValues (SUMOVehicle &veh)
Protected Attributes
std::string myDescription
a description of this moveReminder
MSLane *const myLane
Lane on which the reminder works.
const SUMOReal myLaneLength
The length of the lane / edge the data collector is on.
const std::set< std::string > *const myVehicleTypes
The vehicle types to look for (0 or empty means all)
Private Attributes
PollutantsInterface::Emissions myEmissions
Collected values.
const MSMeanData_Emissions * myParent
The meandata parent.
Collected values
The number of sampled vehicle movements (in s)
SUMOReal sampleSeconds
SUMOReal travelledDistance
The sum of the distances the vehicles travelled.
Detailed Description
Data structure for mean (aggregated) edge/lane values.
Structure holding values that describe the emissions aggregated over some seconds.
Definition at line 72 of file MSMeanData_Emissions.h.
Member Enumeration Documentation
enum MSMoveReminder::Notification inherited
Definition of a vehicle state.
Enumerator
NOTIFICATION_DEPARTED
The vehicle has departed (was inserted into the network)
NOTIFICATION_JUNCTION
The vehicle arrived at a junction.
NOTIFICATION_SEGMENT
The vehicle changes the segment (meso only)
NOTIFICATION_LANE_CHANGE
The vehicle changes lanes (micro only)
NOTIFICATION_TELEPORT
The vehicle is being teleported.
NOTIFICATION_PARKING
The vehicle starts or ends parking.
NOTIFICATION_ARRIVED
The vehicle arrived at its destination (is deleted)
NOTIFICATION_VAPORIZED
The vehicle got vaporized.
NOTIFICATION_TELEPORT_ARRIVED
The vehicle was teleported out of the net.
Definition at line 95 of file MSMoveReminder.h.
Constructor & Destructor Documentation
MSMeanData_Emissions::MSLaneMeanDataValues::MSLaneMeanDataValues (MSLane *const lane, const SUMOReal length, const bool doAdd, const std::set< std::string > *const vTypes = 0, const MSMeanData_Emissions * parent = 0)
Constructor.
Definition at line 53 of file MSMeanData_Emissions.cpp.
MSMeanData_Emissions::MSLaneMeanDataValues::~MSLaneMeanDataValues () virtual
Destructor.
Definition at line 61 of file MSMeanData_Emissions.cpp.
Member Function Documentation
void MSMeanData_Emissions::MSLaneMeanDataValues::addTo (MSMeanData::MeanDataValues & val) const virtual
Add the values of this to the given one and store them there.
Parameters
[in] val The meandata to add to
Implements MSMeanData::MeanDataValues.
Definition at line 74 of file MSMeanData_Emissions.cpp.
References PollutantsInterface::Emissions::addScaled(), myEmissions, MSMeanData::MeanDataValues::sampleSeconds, and MSMeanData::MeanDataValues::travelledDistance.
const std::string& MSMoveReminder::getDescription () const inline inherited
Definition at line 213 of file MSMoveReminder.h.
References MSMoveReminder::myDescription, and MSMoveReminder::removeFromVehicleUpdateValues().
Referenced by MSBaseVehicle::addStops().
const MSLane* MSMoveReminder::getLane () const inline inherited
Returns the lane the reminder works on.
Returns
The lane the reminder works on.
Definition at line 89 of file MSMoveReminder.h.
References MSMoveReminder::myLane.
Referenced by MSDevice_Tripinfo::computeLengthAndDuration(), MSE2Collector::detectorUpdate(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), TraCIServerAPI_InductionLoop::getPosition(), TraCIServerAPI_InductionLoop::getTree(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSMeanData::MeanDataValues::notifyMove(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_ArealDetector::processGet(), and MSMeanData::writeEdge().
SUMOReal MSMeanData::MeanDataValues::getSamples () const virtual inherited
Returns the number of collected sample seconds.
Returns
the number of collected sample seconds
Reimplemented in MSMeanData::MeanDataValueTracker.
Definition at line 138 of file MSMeanData.cpp.
References MSMeanData::MeanDataValues::sampleSeconds.
Referenced by MSMeanData::writePrefix(), MEInductLoop::writeXMLOutput(), and MSCalibrator::writeXMLOutput().
bool MSMeanData::MeanDataValues::isEmpty () const virtual inherited
Returns whether any data was collected.
Returns
whether no data was collected
Reimplemented in MSMeanData::MeanDataValueTracker, MSMeanData_Net::MSLaneMeanDataValues, and MSMeanData_Amitran::MSLaneMeanDataValues.
Definition at line 127 of file MSMeanData.cpp.
References MSMeanData::MeanDataValues::sampleSeconds.
Referenced by MSMeanData_Amitran::writePrefix(), and MSMeanData::writePrefix().
bool MSMeanData::MeanDataValues::notifyEnter (SUMOVehicle & veh, MSMoveReminder::Notification reason) virtual inherited
Called if the vehicle enters the reminder's lane.
Parameters
[in] veh The entering vehicle.
[in] reason how the vehicle enters the lane
See also
MSMoveReminder
MSMoveReminder::notifyEnter
MSMoveReminder::Notification
Reimplemented from MSMoveReminder.
Reimplemented in MSMeanData::MeanDataValueTracker, MSMeanData_Net::MSLaneMeanDataValues, MSMeanData_Amitran::MSLaneMeanDataValues, and MSMeanData_Harmonoise::MSLaneMeanDataValues.
Definition at line 76 of file MSMeanData.cpp.
References UNUSED_PARAMETER, and MSMeanData::MeanDataValues::vehicleApplies().
bool MSMeanData::MeanDataValues::notifyLeave (SUMOVehicle & veh, SUMOReal lastPos, MSMoveReminder::Notification reason) virtual inherited
Called if the vehicle leaves the reminder's lane.
Parameters
veh The leaving vehicle.
[in] lastPos Position on the lane when leaving.
[in] reason how the vehicle leaves the lane
See also
MSMoveReminder
MSMoveReminder::notifyLeave
Reimplemented from MSMoveReminder.
Reimplemented in MSMeanData::MeanDataValueTracker, and MSMeanData_Net::MSLaneMeanDataValues.
Definition at line 111 of file MSMeanData.cpp.
References MSGlobals::gUseMesoSim, and MSMoveReminder::NOTIFICATION_JUNCTION.
bool MSMeanData::MeanDataValues::notifyMove (SUMOVehicle & veh, SUMOReal oldPos, SUMOReal newPos, SUMOReal newSpeed) virtual inherited
Checks whether the reminder still has to be notified about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] oldPos Position before move.
[in] newPos Position after move with newSpeed.
[in] newSpeed Moving speed.
Returns
True if vehicle hasn't passed the reminder completely.
Reimplemented from MSMoveReminder.
Definition at line 83 of file MSMeanData.cpp.
References Named::getID(), SUMOVehicle::getID(), MSMoveReminder::getLane(), MSVehicleType::getLength(), SUMOVehicle::getVehicleType(), SUMOVehicle::hasArrived(), MSMeanData::MeanDataValues::myLaneLength, MSMoveReminder::notifyMoveInternal(), SUMOReal, TS, and WRITE_ERROR.
void MSMeanData_Emissions::MSLaneMeanDataValues::notifyMoveInternal (SUMOVehicle & veh, SUMOReal timeOnLane, SUMOReal speed) protected virtual
Internal notification about the vehicle moves.
Indicator if the reminders is still active for the passed vehicle/parameters. If false, the vehicle will erase this reminder from it's reminder-container.
Parameters
[in] veh Vehicle that asks this reminder.
[in] timeOnLane time the vehicle spent on the lane.
[in] speed Moving speed.
Reimplemented from MSMoveReminder.
Definition at line 83 of file MSMeanData_Emissions.cpp.
References PollutantsInterface::Emissions::addScaled(), PollutantsInterface::computeAll(), SUMOVehicle::getAcceleration(), MSVehicleType::getEmissionClass(), SUMOVehicle::getSlope(), SUMOVehicle::getVehicleType(), myEmissions, MSMeanData::MeanDataValues::sampleSeconds, and MSMeanData::MeanDataValues::travelledDistance.
void MSMoveReminder::removeFromVehicleUpdateValues (SUMOVehicle & veh) protected inherited
Definition at line 94 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues.
Referenced by MSMoveReminder::getDescription(), MSMeanData_Net::MSLaneMeanDataValues::notifyLeave(), and MSMoveReminder::updateDetector().
void MSMeanData_Emissions::MSLaneMeanDataValues::reset (bool afterWrite = false) virtual
Resets values so they may be used for the next interval.
Implements MSMeanData::MeanDataValues.
Definition at line 66 of file MSMeanData_Emissions.cpp.
References myEmissions, MSMeanData::MeanDataValues::sampleSeconds, and MSMeanData::MeanDataValues::travelledDistance.
void MSMoveReminder::setDescription (const std::string & description) inline inherited
Definition at line 209 of file MSMoveReminder.h.
References MSMoveReminder::myDescription.
Referenced by MSMeanData::init(), MEInductLoop::MEInductLoop(), METriggeredCalibrator::METriggeredCalibrator(), and MSCalibrator::MSCalibrator().
void MSMeanData::MeanDataValues::update () virtual inherited
Called if a per timestep update is needed. Default does nothing.
Reimplemented in MSMeanData_Harmonoise::MSLaneMeanDataValues.
Definition at line 133 of file MSMeanData.cpp.
References SUMOReal.
void MSMoveReminder::updateDetector (SUMOVehicle & veh, SUMOReal entryPos, SUMOReal leavePos, SUMOTime entryTime, SUMOTime currentTime, SUMOTime leaveTime, bool cleanUp) inherited
Definition at line 51 of file MSMoveReminder.cpp.
References MSMoveReminder::myLastVehicleUpdateValues, MSMoveReminder::notifyMoveInternal(), MSMoveReminder::removeFromVehicleUpdateValues(), STEPS2TIME, and SUMOReal.
Referenced by MSMoveReminder::notifyLeave(), and MEVehicle::updateDetectorForWriting().
bool MSMeanData::MeanDataValues::vehicleApplies (const SUMOVehicle & veh) const inherited
Tests whether the vehicles type is to be regarded.
Parameters
[in] veh The regarded vehicle
Returns
whether the type of the vehicle is in the set of regarded types
Definition at line 120 of file MSMeanData.cpp.
References MSVehicleType::getID(), SUMOVehicle::getVehicleType(), and MSMeanData::MeanDataValues::myVehicleTypes.
Referenced by MSMeanData::MeanDataValues::notifyEnter(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyEnter(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyEnter(), MSMeanData_Net::MSLaneMeanDataValues::notifyEnter(), MSMeanData::MeanDataValueTracker::notifyEnter(), and MSMeanData_Net::MSLaneMeanDataValues::notifyLeave().
void MSMeanData_Emissions::MSLaneMeanDataValues::write (OutputDevice & dev, const SUMOTime period, const SUMOReal numLanes, const SUMOReal defaultTravelTime, const int numVehicles = -1) const virtual
Writes output values into the given stream.
Parameters
[in] dev The output device to write the data into
[in] prefix The xml prefix to write (mostly the lane / edge id)
[in] numLanes The total number of lanes for which the data was collected
[in] length The length of the object for which the data was collected
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSMeanData::MeanDataValues.
Definition at line 92 of file MSMeanData_Emissions.cpp.
References OutputDevice::closeTag(), PollutantsInterface::CO, PollutantsInterface::Emissions::CO, PollutantsInterface::CO2, PollutantsInterface::Emissions::CO2, PollutantsInterface::computeDefault(), PollutantsInterface::ELEC, PollutantsInterface::Emissions::electricity, PollutantsInterface::FUEL, PollutantsInterface::Emissions::fuel, MSVehicleType::getCarFollowModel(), MSVehicleType::getEmissionClass(), MSNet::getInstance(), MSCFModel::getMaxAccel(), MSVehicleType::getMaxSpeed(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), PollutantsInterface::HC, PollutantsInterface::Emissions::HC, MIN2(), myEmissions, MSMeanData::MeanDataValues::myLaneLength, MSMeanData::myMaxTravelTime, MSMeanData::myMinSamples, myParent, PollutantsInterface::NO_X, PollutantsInterface::Emissions::NOx, PollutantsInterface::PM_X, PollutantsInterface::Emissions::PMx, OutputDevice::realString(), MSMeanData::MeanDataValues::sampleSeconds, STEPS2TIME, SUMOReal, and MSMeanData::MeanDataValues::travelledDistance.
Field Documentation
std::string MSMoveReminder::myDescription protected inherited
a description of this moveReminder
Definition at line 225 of file MSMoveReminder.h.
Referenced by MSMoveReminder::getDescription(), and MSMoveReminder::setDescription().
PollutantsInterface::Emissions MSMeanData_Emissions::MSLaneMeanDataValues::myEmissions private
Collected values.
Definition at line 125 of file MSMeanData_Emissions.h.
Referenced by addTo(), notifyMoveInternal(), reset(), and write().
MSLane* const MSMoveReminder::myLane protected inherited
Lane on which the reminder works.
Definition at line 223 of file MSMoveReminder.h.
Referenced by MSE2Collector::detectorUpdate(), MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSMoveReminder::getLane(), MSE2Collector::MSE2Collector(), MSMoveReminder::MSMoveReminder(), MSE2Collector::notifyEnter(), MSE2Collector::notifyMove(), MSE2Collector::by_vehicle_position_sorter::operator()(), and MSMeanData::MeanDataValueTracker::reset().
const SUMOReal MSMeanData::MeanDataValues::myLaneLength protected inherited
The length of the lane / edge the data collector is on.
Definition at line 173 of file MSMeanData.h.
Referenced by MSMeanData::MeanDataValues::notifyMove(), MSMeanData::MeanDataValueTracker::reset(), write(), MSMeanData_Harmonoise::MSLaneMeanDataValues::write(), MSMeanData_Amitran::MSLaneMeanDataValues::write(), and MSMeanData_Net::MSLaneMeanDataValues::write().
const MSMeanData_Emissions* MSMeanData_Emissions::MSLaneMeanDataValues::myParent private
The meandata parent.
Definition at line 127 of file MSMeanData_Emissions.h.
Referenced by write().
const std::set<std::string>* const MSMeanData::MeanDataValues::myVehicleTypes protected inherited
The vehicle types to look for (0 or empty means all)
Definition at line 186 of file MSMeanData.h.
Referenced by MSMeanData::MeanDataValues::vehicleApplies(), and MSMeanData_Amitran::MSLaneMeanDataValues::write().
SUMOReal MSMeanData::MeanDataValues::sampleSeconds protected inherited
Definition at line 178 of file MSMeanData.h.
Referenced by MSMeanData_Harmonoise::MSLaneMeanDataValues::addTo(), addTo(), MSMeanData_Amitran::MSLaneMeanDataValues::addTo(), MSMeanData_Net::MSLaneMeanDataValues::addTo(), MSMeanData::MeanDataValues::getSamples(), MSMeanData_Amitran::MSLaneMeanDataValues::isEmpty(), MSMeanData_Net::MSLaneMeanDataValues::isEmpty(), MSMeanData::MeanDataValues::isEmpty(), notifyMoveInternal(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::reset(), reset(), MSMeanData_Net::MSLaneMeanDataValues::reset(), write(), MSMeanData_Harmonoise::MSLaneMeanDataValues::write(), MSMeanData_Amitran::MSLaneMeanDataValues::write(), and MSMeanData_Net::MSLaneMeanDataValues::write().
SUMOReal MSMeanData::MeanDataValues::travelledDistance inherited
The sum of the distances the vehicles travelled.
Definition at line 181 of file MSMeanData.h.
Referenced by MSMeanData_Harmonoise::MSLaneMeanDataValues::addTo(), addTo(), MSMeanData_Amitran::MSLaneMeanDataValues::addTo(), MSMeanData_Net::MSLaneMeanDataValues::addTo(), notifyMoveInternal(), MSMeanData_Amitran::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::reset(), reset(), MSMeanData_Net::MSLaneMeanDataValues::reset(), write(), MSMeanData_Amitran::MSLaneMeanDataValues::write(), MSMeanData_Harmonoise::MSLaneMeanDataValues::write(), MSMeanData_Net::MSLaneMeanDataValues::write(), and MSCalibrator::writeXMLOutput().
The documentation for this class was generated from the following files:
MSMeanData_Emissions.h
MSMeanData_Emissions.cpp