SUMO - Simulation of Urban MObility: GUIShapeContainer Class Reference
GUIShapeContainer Class Reference
Storage for geometrical objects extended by mutexes.
#include <GUIShapeContainer.h>
Public Types
typedef NamedObjectCont< PointOfInterest * > POIs
typedef NamedObjectCont< SUMO::Polygon * > Polygons
Public Member Functions
virtual bool addPOI (const std::string &id, const std::string &type, const RGBColor &color, SUMOReal layer, SUMOReal angle, const std::string &imgFile, const Position &pos, SUMOReal width, SUMOReal height, bool ignorePruning=false)
Builds a POI using the given values and adds it to the container.
virtual bool addPolygon (const std::string &id, const std::string &type, const RGBColor &color, SUMOReal layer, SUMOReal angle, const std::string &imgFile, const PositionVector &shape, bool fill, bool ignorePruning=false)
Builds a polygon using the given values and adds it to the container.
std::vector< GUIGlID > getPOIIds () const
Returns the gl-ids of all pois.
const POIs & getPOIs () const
Returns all pois.
std::vector< GUIGlID > getPolygonIDs () const
Returns the gl-ids of all polygons.
const Polygons & getPolygons () const
Returns all polygons.
GUIShapeContainer (SUMORTree &vis)
Constructor.
virtual void movePOI (const std::string &id, const Position &pos)
Assigns a new position to the named PoI.
virtual bool removePOI (const std::string &id)
Removes a PoI from the container.
virtual bool removePolygon (const std::string &id)
Removes a polygon from the container.
virtual void reshapePolygon (const std::string &id, const PositionVector &shape)
Assigns a shape to the named polygon.
virtual ~GUIShapeContainer ()
Destructor.
Protected Member Functions
virtual bool add (SUMO::Polygon *poly, bool ignorePruning=false)
virtual bool add (PointOfInterest *poi, bool ignorePruning=false)
Protected Attributes
POIs myPOIs
stored POIs
Polygons myPolygons
stored Polygons
Private Attributes
MFXMutex myLock
The mutex for adding/removing operations.
SUMORTree & myVis
The RTree structure to add and remove visualization elements.
Detailed Description
Storage for geometrical objects extended by mutexes.
See also
ShapeContainer
Definition at line 55 of file GUIShapeContainer.h.
Member Typedef Documentation
typedef NamedObjectCont< PointOfInterest*> ShapeContainer::POIs inherited
Definition at line 58 of file ShapeContainer.h.
typedef NamedObjectCont< SUMO::Polygon* > ShapeContainer::Polygons inherited
Definition at line 57 of file ShapeContainer.h.
Constructor & Destructor Documentation
GUIShapeContainer::GUIShapeContainer (SUMORTree & vis)
Constructor.
Definition at line 48 of file GUIShapeContainer.cpp.
GUIShapeContainer::~GUIShapeContainer () virtual
Destructor.
Definition at line 52 of file GUIShapeContainer.cpp.
Member Function Documentation
bool ShapeContainer::add (SUMO::Polygon * poly, bool ignorePruning = false) protected virtual inherited
Reimplemented in PCPolyContainer.
Definition at line 110 of file ShapeContainer.cpp.
References NamedObjectCont< T >::add(), Named::getID(), and ShapeContainer::myPolygons.
Referenced by PCPolyContainer::add(), ShapeContainer::addPOI(), ShapeContainer::addPolygon(), and ShapeContainer::getPOIs().
bool ShapeContainer::add (PointOfInterest * poi, bool ignorePruning = false) protected virtual inherited
Reimplemented in PCPolyContainer.
Definition at line 120 of file ShapeContainer.cpp.
References NamedObjectCont< T >::add(), Named::getID(), and ShapeContainer::myPOIs.
bool GUIShapeContainer::addPOI (const std::string & id, const std::string & type, const RGBColor & color, SUMOReal layer, SUMOReal angle, const std::string & imgFile, const Position & pos, SUMOReal width, SUMOReal height, bool ignorePruning = false) virtual
Builds a POI using the given values and adds it to the container.
Parameters
[in] id The name of the POI
[in] type The (abstract) type of the POI
[in] color The color of the POI
[in] layer The layer of the POI
[in] angle The rotation of the POI
[in] imgFile The raster image of the POI
[in] pos The position of the POI
[in] width The width of the POI image
[in] height The height of the POI image
Returns
whether the poi could be added
Reimplemented from ShapeContainer.
Definition at line 56 of file GUIShapeContainer.cpp.
References NamedObjectCont< T >::add(), SUMORTree::addAdditionalGLObject(), myLock, ShapeContainer::myPOIs, and myVis.
bool GUIShapeContainer::addPolygon (const std::string & id, const std::string & type, const RGBColor & color, SUMOReal layer, SUMOReal angle, const std::string & imgFile, const PositionVector & shape, bool fill, bool ignorePruning = false) virtual
Builds a polygon using the given values and adds it to the container.
Parameters
[in] id The name of the polygon
[in] type The (abstract) type of the polygon
[in] color The color of the polygon
[in] layer The layer of the polygon
[in] angle The rotation of the polygon
[in] imgFile The raster image of the polygon
[in] shape The shape of the polygon
[in] fill Whether the polygon shall be filled
Returns
whether the polygon could be added
Reimplemented from ShapeContainer.
Definition at line 72 of file GUIShapeContainer.cpp.
References NamedObjectCont< T >::add(), SUMORTree::addAdditionalGLObject(), myLock, ShapeContainer::myPolygons, and myVis.
std::vector< GUIGlID > GUIShapeContainer::getPOIIds () const
Returns the gl-ids of all pois.
Definition at line 138 of file GUIShapeContainer.cpp.
References NamedObjectCont< T >::getMyMap(), ShapeContainer::getPOIs(), and myLock.
const POIs& ShapeContainer::getPOIs () const inline inherited
Returns all pois.
Definition at line 133 of file ShapeContainer.h.
References ShapeContainer::add(), and ShapeContainer::myPOIs.
Referenced by TraCIServerAPI_POI::getPoI(), getPOIIds(), TraCIServerAPI_POI::getTree(), and TraCIServerAPI_POI::processGet().
std::vector< GUIGlID > GUIShapeContainer::getPolygonIDs () const
Returns the gl-ids of all polygons.
Definition at line 150 of file GUIShapeContainer.cpp.
References NamedObjectCont< T >::getMyMap(), ShapeContainer::getPolygons(), and myLock.
const Polygons& ShapeContainer::getPolygons () const inline inherited
Returns all polygons.
Definition at line 127 of file ShapeContainer.h.
References ShapeContainer::myPolygons.
Referenced by TraCIServerAPI_Polygon::getPolygon(), getPolygonIDs(), TraCIServerAPI_Polygon::getTree(), PCLoaderDlrNavteq::loadPolyFile(), and TraCIServerAPI_Polygon::processGet().
void GUIShapeContainer::movePOI (const std::string & id, const Position & pos) virtual
Assigns a new position to the named PoI.
Parameters
[in] id The id of the PoI to move
[in] pos The PoI's new position
Reimplemented from ShapeContainer.
Definition at line 113 of file GUIShapeContainer.cpp.
References SUMORTree::addAdditionalGLObject(), NamedObjectCont< T >::get(), myLock, ShapeContainer::myPOIs, myVis, and SUMORTree::removeAdditionalGLObject().
bool GUIShapeContainer::removePOI (const std::string & id) virtual
Removes a PoI from the container.
Parameters
[in] id The id of the PoI
Returns
Whether the poi could be removed
Reimplemented from ShapeContainer.
Definition at line 101 of file GUIShapeContainer.cpp.
References NamedObjectCont< T >::get(), myLock, ShapeContainer::myPOIs, myVis, NamedObjectCont< T >::remove(), and SUMORTree::removeAdditionalGLObject().
bool GUIShapeContainer::removePolygon (const std::string & id) virtual
Removes a polygon from the container.
Parameters
[in] id The id of the polygon
Returns
Whether the polygon could be removed
Reimplemented from ShapeContainer.
Definition at line 89 of file GUIShapeContainer.cpp.
References NamedObjectCont< T >::get(), myLock, ShapeContainer::myPolygons, myVis, NamedObjectCont< T >::remove(), and SUMORTree::removeAdditionalGLObject().
void GUIShapeContainer::reshapePolygon (const std::string & id, const PositionVector & shape) virtual
Assigns a shape to the named polygon.
Parameters
[in] id The id of the polygon to reshape
[in] shape The polygon's new shape
Reimplemented from ShapeContainer.
Definition at line 125 of file GUIShapeContainer.cpp.
References SUMORTree::addAdditionalGLObject(), NamedObjectCont< T >::get(), myLock, ShapeContainer::myPolygons, myVis, SUMORTree::removeAdditionalGLObject(), and GUIPolygon::setShape().
Field Documentation
MFXMutex GUIShapeContainer::myLock mutable private
The mutex for adding/removing operations.
Definition at line 137 of file GUIShapeContainer.h.
Referenced by addPOI(), addPolygon(), getPOIIds(), getPolygonIDs(), movePOI(), removePOI(), removePolygon(), and reshapePolygon().
POIs ShapeContainer::myPOIs protected inherited
stored POIs
Definition at line 148 of file ShapeContainer.h.
Referenced by ShapeContainer::add(), addPOI(), ShapeContainer::getPOIs(), ShapeContainer::movePOI(), movePOI(), ShapeContainer::removePOI(), removePOI(), PCPolyContainer::save(), and PCPolyContainer::~PCPolyContainer().
Polygons ShapeContainer::myPolygons protected inherited
stored Polygons
Definition at line 145 of file ShapeContainer.h.
Referenced by ShapeContainer::add(), addPolygon(), ShapeContainer::getPolygons(), ShapeContainer::removePolygon(), removePolygon(), ShapeContainer::reshapePolygon(), reshapePolygon(), PCPolyContainer::save(), and PCPolyContainer::~PCPolyContainer().
SUMORTree& GUIShapeContainer::myVis private
The RTree structure to add and remove visualization elements.
Definition at line 140 of file GUIShapeContainer.h.
Referenced by addPOI(), addPolygon(), movePOI(), removePOI(), removePolygon(), and reshapePolygon().
The documentation for this class was generated from the following files:
GUIShapeContainer.h
GUIShapeContainer.cpp