SUMO - Simulation of Urban MObility: ROPerson::PersonTrip Class Reference
ROPerson::PersonTrip Class Reference
A planItem can be a Trip which contains multiple tripItems.
#include <ROPerson.h>
Public Member Functions
virtual void addTripItem (TripItem *tripIt)
void addVehicle (ROVehicle *veh)
SUMOReal getArrivalPos () const
SUMOReal getDepartPos () const
const ROEdge * getDestination () const
SVCPermissions getModes () const
const ROEdge * getOrigin () const
std::vector< ROVehicle * > & getVehicles ()
virtual bool isStop () const
virtual bool needsRouting () const
PersonTrip ()
PersonTrip (const ROEdge *const from, const ROEdge *const to, const SVCPermissions modeSet, const SUMOReal departPos, const SUMOReal arrivalPos, const std::string &busStop)
void saveAsXML (OutputDevice &os) const
void saveVehicles (OutputDevice &os, OutputDevice *const typeos, bool asAlternatives, OptionsCont &options) const
virtual ~PersonTrip ()
Destructor.
Private Member Functions
PersonTrip & operator= (const PersonTrip &src)
Invalidated assignment operator.
Private Attributes
const SUMOReal arr
const std::string busStop
const SUMOReal dep
const ROEdge * from
const SVCPermissions modes
std::vector< TripItem * > myTripItems
the fully specified trips
std::vector< ROVehicle * > myVehicles
the vehicles which may be used for routing
const ROEdge * to
Detailed Description
A planItem can be a Trip which contains multiple tripItems.
Definition at line 215 of file ROPerson.h.
Constructor & Destructor Documentation
ROPerson::PersonTrip::PersonTrip () inline
Definition at line 217 of file ROPerson.h.
ROPerson::PersonTrip::PersonTrip (const ROEdge *const from, const ROEdge *const to, const SVCPermissions modeSet, const SUMOReal departPos, const SUMOReal arrivalPos, const std::string & busStop) inline
Definition at line 219 of file ROPerson.h.
virtual ROPerson::PersonTrip::~PersonTrip () inline virtual
Destructor.
Definition at line 223 of file ROPerson.h.
Member Function Documentation
virtual void ROPerson::PersonTrip::addTripItem (TripItem * tripIt) inline virtual
Reimplemented from ROPerson::PlanItem.
Definition at line 233 of file ROPerson.h.
Referenced by ROPerson::computeIntermodal().
void ROPerson::PersonTrip::addVehicle (ROVehicle * veh) inline
Definition at line 236 of file ROPerson.h.
Referenced by ROPerson::addTrip().
SUMOReal ROPerson::PersonTrip::getArrivalPos () const inline
Definition at line 251 of file ROPerson.h.
Referenced by ROPerson::computeIntermodal().
SUMOReal ROPerson::PersonTrip::getDepartPos () const inline
Definition at line 248 of file ROPerson.h.
Referenced by ROPerson::computeIntermodal().
const ROEdge* ROPerson::PersonTrip::getDestination () const inline virtual
Implements ROPerson::PlanItem.
Definition at line 245 of file ROPerson.h.
Referenced by ROPerson::computeIntermodal().
SVCPermissions ROPerson::PersonTrip::getModes () const inline
Definition at line 254 of file ROPerson.h.
Referenced by ROPerson::computeIntermodal().
const ROEdge* ROPerson::PersonTrip::getOrigin () const inline virtual
Implements ROPerson::PlanItem.
Definition at line 242 of file ROPerson.h.
Referenced by ROPerson::computeIntermodal().
std::vector<ROVehicle*>& ROPerson::PersonTrip::getVehicles () inline
Definition at line 239 of file ROPerson.h.
Referenced by ROPerson::addTrip(), and ROPerson::computeRoute().
virtual bool ROPerson::PlanItem::isStop () const inline virtual inherited
Reimplemented in ROPerson::Stop.
Definition at line 98 of file ROPerson.h.
virtual bool ROPerson::PersonTrip::needsRouting () const inline virtual
Reimplemented from ROPerson::PlanItem.
Definition at line 257 of file ROPerson.h.
References ROPerson::PlanItem::saveVehicles().
PersonTrip& ROPerson::PersonTrip::operator= (const PersonTrip & src) private
Invalidated assignment operator.
void ROPerson::PersonTrip::saveAsXML (OutputDevice & os) const inline virtual
Implements ROPerson::PlanItem.
Definition at line 261 of file ROPerson.h.
void ROPerson::PersonTrip::saveVehicles (OutputDevice & os, OutputDevice *const typeos, bool asAlternatives, OptionsCont & options) const virtual
Reimplemented from ROPerson::PlanItem.
Definition at line 162 of file ROPerson.cpp.
Field Documentation
const SUMOReal ROPerson::PersonTrip::arr private
Definition at line 271 of file ROPerson.h.
const std::string ROPerson::PersonTrip::busStop private
Definition at line 272 of file ROPerson.h.
const SUMOReal ROPerson::PersonTrip::dep private
Definition at line 271 of file ROPerson.h.
const ROEdge* ROPerson::PersonTrip::from private
Definition at line 268 of file ROPerson.h.
const SVCPermissions ROPerson::PersonTrip::modes private
Definition at line 270 of file ROPerson.h.
std::vector<TripItem*> ROPerson::PersonTrip::myTripItems private
the fully specified trips
Definition at line 274 of file ROPerson.h.
std::vector<ROVehicle*> ROPerson::PersonTrip::myVehicles private
the vehicles which may be used for routing
Definition at line 276 of file ROPerson.h.
const ROEdge* ROPerson::PersonTrip::to private
Definition at line 269 of file ROPerson.h.
The documentation for this class was generated from the following files:
ROPerson.h
ROPerson.cpp