SUMO - Simulation of Urban MObility: FileHelpers Class Reference
FileHelpers Class Reference
Functions for an easier usage of files and paths.
#include <FileHelpers.h>
Static Public Member Functions
file access functions
static bool isReadable (std::string path)
Checks whether the given file is readable.
file path evaluating functions
static std::string getFilePath (const std::string &path)
Removes the file information from the given path.
static std::string getConfigurationRelative (const std::string &configPath, const std::string &path)
Returns the second path as a relative path to the first file.
static bool isSocket (const std::string &name)
Returns the information whether the given name represents a socket.
static bool isAbsolute (const std::string &path)
Returns the information whether the given path is absolute.
static std::string checkForRelativity (const std::string &filename, const std::string &basePath)
Returns the path from a configuration so that it is accessable from the current working directory.
static std::string prependToLastPathComponent (const std::string &prefix, const std::string &path)
prepend the given prefix to the last path component of the given file path
binary writing functions
static std::ostream & writeInt (std::ostream &strm, int value)
Writes an integer binary.
static std::ostream & writeUInt (std::ostream &strm, int value)
Writes an integer binary.
static std::ostream & writeFloat (std::ostream &strm, SUMOReal value)
Writes a float binary.
static std::ostream & writeByte (std::ostream &strm, unsigned char value)
Writes a byte binary.
static std::ostream & writeString (std::ostream &strm, const std::string &value)
Writes a string binary.
static std::ostream & writeTime (std::ostream &strm, SUMOTime value)
Writes a time description binary.
template<typename E >
static std::ostream & writeEdgeVector (std::ostream &os, const std::vector< E > &edges)
Writes an edge vector binary.
template<typename E >
static void readEdgeVector (std::istream &in, std::vector< const E * > &edges, const std::string &rid)
Reads an edge vector binary.
Detailed Description
Functions for an easier usage of files and paths.
Definition at line 49 of file FileHelpers.h.
Member Function Documentation
std::string FileHelpers::checkForRelativity (const std::string & filename, const std::string & basePath) static
Returns the path from a configuration so that it is accessable from the current working directory.
If the path is absolute, it is returned. Otherwise, the file's position is computed regarding the configuration path (see getConfigurationRelative).
See also
isAbsolute
getConfigurationRelative
Parameters
[in] filename The path to the file to be examined
[in] basePath The path the configuration file (including the config's file name)
Returns
The file's position
Definition at line 124 of file FileHelpers.cpp.
References getConfigurationRelative(), isAbsolute(), and isSocket().
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), NLDiscreteEventBuilder::buildSaveTLStateCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchesCommand(), NLDiscreteEventBuilder::buildSaveTLSwitchStatesCommand(), and MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic().
std::string FileHelpers::getConfigurationRelative (const std::string & configPath, const std::string & path) static
Returns the second path as a relative path to the first file.
Given the position of the configuration file, and the information where a second file is relative to the configuration file's position, we want to known where this second file can be found. This method gets the path to the configuration file (including the configuration file name) and the path to get the relative position of and returns this relative position.
Parameters
[in] configPath The path the configuration file (including the config's file name)
[in] path The path to the references file (relativ to configuration path)
Returns
The file's position (relative to curent working directory)
Definition at line 86 of file FileHelpers.cpp.
References getFilePath().
Referenced by ShapeHandler::addPOI(), ShapeHandler::addPoly(), SUMOVehicleParserHelper::beginVTypeParsing(), checkForRelativity(), NWFrame::checkOptions(), NLTriggerBuilder::getFileName(), GNEAdditionalHandler::getFileName(), GUISettingsHandler::myStartElement(), OptionsCont::relocateFiles(), and GenericSAXHandler::startElement().
std::string FileHelpers::getFilePath (const std::string & path) static
Removes the file information from the given path.
Parameters
[in] path The path to the file to return the folder it is located in
Returns
The directory of the named file
Definition at line 76 of file FileHelpers.cpp.
Referenced by getConfigurationRelative(), TraCIServer::processCommandsUntilSimStep(), RODFDetectorCon::writeEmitters(), and RODFDetectorCon::writeSpeedTrigger().
bool FileHelpers::isAbsolute (const std::string & path) static
Returns the information whether the given path is absolute.
A path is meant to be absolute, if
it is a socket
it starts with a "/" (Linux)
it has a ':' at the second position (Windows)
Parameters
[in] path The path to examine
Returns
Whether the path is absolute
Definition at line 101 of file FileHelpers.cpp.
References isSocket().
Referenced by ShapeHandler::addPOI(), ShapeHandler::addPoly(), SUMOVehicleParserHelper::beginVTypeParsing(), checkForRelativity(), NLTriggerBuilder::getFileName(), GNEAdditionalHandler::getFileName(), GUISettingsHandler::myStartElement(), OptionsCont::relocateFiles(), and GenericSAXHandler::startElement().
bool FileHelpers::isReadable (std::string path) static
Checks whether the given file is readable.
Parameters
[in] path The path to the file that shall be examined
Returns
Whether the named file is readable
Definition at line 58 of file FileHelpers.cpp.
Referenced by NIImporter_SUMO::_loadNetwork(), NLBuilder::buildRouteLoaderControl(), OptionsCont::isUsableFileList(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), OptionsIO::loadConfiguration(), ODDistrictCont::loadDistricts(), PCLoaderVisum::loadIfSet(), PCLoaderOSM::loadIfSet(), PCLoaderXML::loadIfSet(), ODMatrix::loadMatrix(), loadNet(), ROLoader::loadNet(), NIImporter_RobocupRescue::loadNetwork(), NIImporter_ArcView::loadNetwork(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_OpenDrive::loadNetwork(), PCLoaderDlrNavteq::loadPOIFiles(), PCLoaderDlrNavteq::loadPolyFiles(), ODMatrix::loadRoutes(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), GUIApplicationWindow::onCmdNetedit(), readDetectorFlows(), readDetectors(), and SUMOSAXReader::LocalSchemaResolver::resolveEntity().
bool FileHelpers::isSocket (const std::string & name) static
Returns the information whether the given name represents a socket.
A file name is meant to describe a socket address if a colon is found at a position larger than one.
Parameters
[in] name The name of a file
Returns
Whether the name names a socket
Definition at line 94 of file FileHelpers.cpp.
Referenced by checkForRelativity(), OutputDevice::getDevice(), and isAbsolute().
std::string FileHelpers::prependToLastPathComponent (const std::string & prefix, const std::string & path) static
prepend the given prefix to the last path component of the given file path
Definition at line 143 of file FileHelpers.cpp.
Referenced by OutputDevice::getDevice().
template<typename E > void FileHelpers::readEdgeVector (std::istream & in, std::vector< const E * > & edges, const std::string & rid) static
Reads an edge vector binary.
Parameters
[in] is The stream to read from
[out] edges The edge vector to write into
Returns
Reference to the stream
Definition at line 283 of file FileHelpers.h.
Referenced by RORouteHandler::parseEdges(), and MSEdge::parseEdgesList().
std::ostream & FileHelpers::writeByte (std::ostream & strm, unsigned char value) static
Writes a byte binary.
Parameters
[in,out] strm The stream to write into
[in] value The byte to write
Returns
Reference to the stream
Definition at line 177 of file FileHelpers.cpp.
Referenced by BinaryFormatter::closeTag(), BinaryFormatter::openTag(), SUMOSAXAttributesImpl_Binary::SUMOSAXAttributesImpl_Binary(), BinaryFormatter::writeAttr(), BinaryFormatter::writeAttrHeader(), BinaryFormatter::writeHeader(), BinaryFormatter::writePosition(), BinaryFormatter::writeStaticHeader(), BinaryFormatter::writeStringList(), and BinaryFormatter::writeXMLHeader().
template<typename E > std::ostream & FileHelpers::writeEdgeVector (std::ostream & os, const std::vector< E > & edges) static
Writes an edge vector binary.
Parameters
[in,out] os The stream to write into
[in] edges The edges to write
Returns
Reference to the stream
Definition at line 227 of file FileHelpers.h.
References writeInt(), and writeUInt().
Referenced by BinaryFormatter::writeAttr().
std::ostream & FileHelpers::writeFloat (std::ostream & strm, SUMOReal value) static
Writes a float binary.
This method behaves differently depending on the definition of SUMOReal at compile time.
Parameters
[in,out] strm The stream to write into
[in] value The float to write
Returns
Reference to the stream
Definition at line 170 of file FileHelpers.cpp.
References SUMOReal.
Referenced by computeAllPairs(), BinaryFormatter::writeAttr(), and BinaryFormatter::writePosition().
std::ostream & FileHelpers::writeInt (std::ostream & strm, int value) static
Writes an integer binary.
Parameters
[in,out] strm The stream to write into
[in] value The integer to write
Returns
Reference to the stream
Definition at line 156 of file FileHelpers.cpp.
Referenced by SUMOSAXAttributesImpl_Binary::SUMOSAXAttributesImpl_Binary(), BinaryFormatter::writeAttr(), writeEdgeVector(), BinaryFormatter::writeHeader(), BinaryFormatter::writePosition(), and BinaryFormatter::writeStringList().
std::ostream & FileHelpers::writeString (std::ostream & strm, const std::string & value) static
Writes a string binary.
Writes the length of the string, first, using writeInt. Writes then the string's characters.
See also
writeInt
Parameters
[in,out] strm The stream to write into
[in] value The string to write
Returns
Reference to the stream
Definition at line 184 of file FileHelpers.cpp.
References writeUInt().
Referenced by BinaryFormatter::writeAttr(), BinaryFormatter::writeHeader(), BinaryFormatter::writePreformattedTag(), BinaryFormatter::writeStaticHeader(), BinaryFormatter::writeStringList(), and BinaryFormatter::writeXMLHeader().
std::ostream & FileHelpers::writeTime (std::ostream & strm, SUMOTime value) static
Writes a time description binary.
This method behaves differently depending on the definition of SUMOTime at compile time, which in turn depends on the enabling of subsecond timesteps.
Parameters
[in,out] strm The stream to write into
[in] value The time to write
Returns
Reference to the stream
Definition at line 194 of file FileHelpers.cpp.
std::ostream & FileHelpers::writeUInt (std::ostream & strm, int value) static
Writes an integer binary.
Parameters
[in,out] strm The stream to write into
[in] value The integer to write
Returns
Reference to the stream
Definition at line 163 of file FileHelpers.cpp.
Referenced by writeEdgeVector(), and writeString().
The documentation for this class was generated from the following files:
FileHelpers.h
FileHelpers.cpp