SUMO - Simulation of Urban MObility: GUIEvent Class Reference
GUIEvent Class Reference
#include <GUIEvent.h>
Public Member Functions
GUIEventType getOwnType () const
returns the event type
virtual ~GUIEvent ()
destructor
Protected Member Functions
GUIEvent (GUIEventType ownType)
constructor
Protected Attributes
GUIEventType myType
the type of the event
Detailed Description
GUIEvent
Definition at line 81 of file GUIEvent.h.
Constructor & Destructor Documentation
virtual GUIEvent::~GUIEvent () inline virtual
destructor
Definition at line 89 of file GUIEvent.h.
GUIEvent::GUIEvent (GUIEventType ownType) inline protected
constructor
Definition at line 93 of file GUIEvent.h.
Member Function Documentation
GUIEventType GUIEvent::getOwnType () const inline
returns the event type
Definition at line 84 of file GUIEvent.h.
References myType.
Referenced by GNEApplicationWindow::eventOccured(), GUIApplicationWindow::eventOccured(), GNEApplicationWindow::handleEvent_Message(), and GUIApplicationWindow::handleEvent_Message().
Field Documentation
GUIEventType GUIEvent::myType protected
the type of the event
Definition at line 99 of file GUIEvent.h.
Referenced by getOwnType(), and GUIEvent_Message::GUIEvent_Message().
The documentation for this class was generated from the following file:
GUIEvent.h