SUMO - Simulation of Urban MObility: TraCIAPI::EdgeScope Class Reference
TraCIAPI::EdgeScope Class Reference
Scope for interaction with edges.
#include <TraCIAPI.h>
Public Member Functions
void adaptTraveltime (const std::string &edgeID, SUMOReal time) const
EdgeScope (TraCIAPI &parent)
SUMOReal getAdaptedTraveltime (const std::string &edgeID, SUMOTime time) const
SUMOReal getCO2Emission (const std::string &edgeID) const
SUMOReal getCOEmission (const std::string &edgeID) const
SUMOReal getEffort (const std::string &edgeID, SUMOTime time) const
SUMOReal getElectricityConsumption (const std::string &edgeID) const
SUMOReal getFuelConsumption (const std::string &edgeID) const
SUMOReal getHCEmission (const std::string &edgeID) const
int getIDCount () const
std::vector< std::string > getIDList () const
SUMOReal getLastStepHaltingNumber (const std::string &edgeID) const
SUMOReal getLastStepLength (const std::string &edgeID) const
SUMOReal getLastStepMeanSpeed (const std::string &edgeID) const
SUMOReal getLastStepOccupancy (const std::string &edgeID) const
std::vector< std::string > getLastStepVehicleIDs (const std::string &edgeID) const
int getLastStepVehicleNumber (const std::string &edgeID) const
SUMOReal getNoiseEmission (const std::string &edgeID) const
SUMOReal getNOxEmission (const std::string &edgeID) const
SUMOReal getPMxEmission (const std::string &edgeID) const
SUMOReal getTraveltime (const std::string &edgeID) const
void setEffort (const std::string &edgeID, SUMOReal effort) const
void setMaxSpeed (const std::string &edgeID, SUMOReal speed) const
virtual ~EdgeScope ()
Protected Attributes
TraCIAPI & myParent
The parent TraCI client which offers the connection.
Private Member Functions
EdgeScope (const EdgeScope &src)
invalidated copy constructor
EdgeScope & operator= (const EdgeScope &src)
invalidated assignment operator
Detailed Description
Scope for interaction with edges.
Definition at line 225 of file TraCIAPI.h.
Constructor & Destructor Documentation
TraCIAPI::EdgeScope::EdgeScope (TraCIAPI & parent) inline
Definition at line 227 of file TraCIAPI.h.
virtual TraCIAPI::EdgeScope::~EdgeScope () inline virtual
Definition at line 228 of file TraCIAPI.h.
References SUMOReal.
TraCIAPI::EdgeScope::EdgeScope (const EdgeScope & src) private
invalidated copy constructor
Member Function Documentation
void TraCIAPI::EdgeScope::adaptTraveltime (const std::string & edgeID, SUMOReal time) const
Definition at line 645 of file TraCIAPI.cpp.
References CMD_SET_EDGE_VARIABLE, VAR_EDGE_TRAVELTIME, and tcpip::Storage::writeDouble().
SUMOReal TraCIAPI::EdgeScope::getAdaptedTraveltime (const std::string & edgeID, SUMOTime time) const
Definition at line 554 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, SUMOReal, VAR_CO2EMISSION, and tcpip::Storage::writeInt().
SUMOReal TraCIAPI::EdgeScope::getCO2Emission (const std::string & edgeID) const
Definition at line 568 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, SUMOReal, and VAR_CO2EMISSION.
SUMOReal TraCIAPI::EdgeScope::getCOEmission (const std::string & edgeID) const
Definition at line 573 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, SUMOReal, and VAR_COEMISSION.
SUMOReal TraCIAPI::EdgeScope::getEffort (const std::string & edgeID, SUMOTime time) const
Definition at line 561 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, SUMOReal, VAR_CO2EMISSION, and tcpip::Storage::writeInt().
SUMOReal TraCIAPI::EdgeScope::getElectricityConsumption (const std::string & edgeID) const
Definition at line 603 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, SUMOReal, and VAR_ELECTRICITYCONSUMPTION.
SUMOReal TraCIAPI::EdgeScope::getFuelConsumption (const std::string & edgeID) const
Definition at line 593 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, SUMOReal, and VAR_FUELCONSUMPTION.
SUMOReal TraCIAPI::EdgeScope::getHCEmission (const std::string & edgeID) const
Definition at line 578 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, SUMOReal, and VAR_HCEMISSION.
int TraCIAPI::EdgeScope::getIDCount () const
Definition at line 549 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, ID_COUNT, and SUMOReal.
Referenced by TraCITestClient::testAPI().
std::vector< std::string > TraCIAPI::EdgeScope::getIDList () const
Definition at line 544 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, and ID_LIST.
Referenced by TraCITestClient::testAPI().
SUMOReal TraCIAPI::EdgeScope::getLastStepHaltingNumber (const std::string & edgeID) const
Definition at line 633 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, and LAST_STEP_VEHICLE_HALTING_NUMBER.
SUMOReal TraCIAPI::EdgeScope::getLastStepLength (const std::string & edgeID) const
Definition at line 618 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, LAST_STEP_LENGTH, and SUMOReal.
SUMOReal TraCIAPI::EdgeScope::getLastStepMeanSpeed (const std::string & edgeID) const
Definition at line 608 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, LAST_STEP_MEAN_SPEED, and SUMOReal.
SUMOReal TraCIAPI::EdgeScope::getLastStepOccupancy (const std::string & edgeID) const
Definition at line 613 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, LAST_STEP_OCCUPANCY, and SUMOReal.
std::vector< std::string > TraCIAPI::EdgeScope::getLastStepVehicleIDs (const std::string & edgeID) const
Definition at line 638 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, and LAST_STEP_VEHICLE_ID_LIST.
int TraCIAPI::EdgeScope::getLastStepVehicleNumber (const std::string & edgeID) const
Definition at line 628 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, LAST_STEP_VEHICLE_NUMBER, and SUMOReal.
SUMOReal TraCIAPI::EdgeScope::getNoiseEmission (const std::string & edgeID) const
Definition at line 598 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, SUMOReal, and VAR_NOISEEMISSION.
SUMOReal TraCIAPI::EdgeScope::getNOxEmission (const std::string & edgeID) const
Definition at line 588 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, SUMOReal, and VAR_NOXEMISSION.
SUMOReal TraCIAPI::EdgeScope::getPMxEmission (const std::string & edgeID) const
Definition at line 583 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, SUMOReal, and VAR_PMXEMISSION.
SUMOReal TraCIAPI::EdgeScope::getTraveltime (const std::string & edgeID) const
Definition at line 623 of file TraCIAPI.cpp.
References CMD_GET_EDGE_VARIABLE, and VAR_CURRENT_TRAVELTIME.
EdgeScope& TraCIAPI::EdgeScope::operator= (const EdgeScope & src) private
invalidated assignment operator
void TraCIAPI::EdgeScope::setEffort (const std::string & edgeID, SUMOReal effort) const
Definition at line 654 of file TraCIAPI.cpp.
References CMD_SET_EDGE_VARIABLE, VAR_EDGE_EFFORT, and tcpip::Storage::writeDouble().
void TraCIAPI::EdgeScope::setMaxSpeed (const std::string & edgeID, SUMOReal speed) const
Definition at line 663 of file TraCIAPI.cpp.
References CMD_SET_EDGE_VARIABLE, VAR_MAXSPEED, and tcpip::Storage::writeDouble().
Field Documentation
TraCIAPI& TraCIAPI::TraCIScopeWrapper::myParent protected inherited
The parent TraCI client which offers the connection.
Definition at line 206 of file TraCIAPI.h.
The documentation for this class was generated from the following files:
TraCIAPI.h
TraCIAPI.cpp