SUMO - Simulation of Urban MObility: AGStreet::Builder Class Reference
AGStreet::Builder Class Reference
#include <AGStreet.h>
Public Member Functions
ROEdge * buildEdge (const std::string &name, RONode *from, RONode *to, const int priority)
Builds an edge with the given name.
Protected Member Functions
int getNextIndex ()
Returns the index of the edge to built.
Detailed Description
Definition at line 62 of file AGStreet.h.
Member Function Documentation
ROEdge* AGStreet::Builder::buildEdge (const std::string & name, RONode * from, RONode * to, const int priority) inline virtual
Builds an edge with the given name.
Parameters
[in] name The name of the edge
[in] from The node the edge begins at
[in] to The node the edge ends at
[in] priority The edge priority (road class)
Returns
A proper instance of the named edge
Implements ROAbstractEdgeBuilder.
Definition at line 72 of file AGStreet.h.
References AGStreet::AGStreet(), AGStreet::allows(), ROAbstractEdgeBuilder::getNextIndex(), AGStreet::getPopulation(), AGStreet::getWorkplaceNumber(), AGStreet::print(), AGStreet::setPopulation(), AGStreet::setWorkplaceNumber(), and SUMOReal.
int ROAbstractEdgeBuilder::getNextIndex () inline protected inherited
Returns the index of the edge to built.
Returns
Next valid edge index
Definition at line 90 of file ROAbstractEdgeBuilder.h.
References ROAbstractEdgeBuilder::myCurrentIndex.
Referenced by buildEdge(), ROJTREdgeBuilder::buildEdge(), RODFEdgeBuilder::buildEdge(), ROMAEdgeBuilder::buildEdge(), and RODUAEdgeBuilder::buildEdge().
The documentation for this class was generated from the following file:
AGStreet.h