SUMO - Simulation of Urban MObility: ShapeContainer Class Reference
ShapeContainer Class Reference
Storage for geometrical objects.
#include <ShapeContainer.h>
Public Types
typedef NamedObjectCont< PointOfInterest * > POIs
typedef NamedObjectCont< SUMO::Polygon * > Polygons
Public Member Functions
virtual bool addPOI (const std::string &id, const std::string &type, const RGBColor &color, SUMOReal layer, SUMOReal angle, const std::string &imgFile, const Position &pos, SUMOReal width, SUMOReal height, bool ignorePruning=false)
Builds a POI using the given values and adds it to the container.
virtual bool addPolygon (const std::string &id, const std::string &type, const RGBColor &color, SUMOReal layer, SUMOReal angle, const std::string &imgFile, const PositionVector &shape, bool fill, bool ignorePruning=false)
Builds a polygon using the given values and adds it to the container.
const POIs & getPOIs () const
Returns all pois.
const Polygons & getPolygons () const
Returns all polygons.
virtual void movePOI (const std::string &id, const Position &pos)
Assigns a new position to the named PoI.
virtual bool removePOI (const std::string &id)
Removes a PoI from the container.
virtual bool removePolygon (const std::string &id)
Removes a polygon from the container.
virtual void reshapePolygon (const std::string &id, const PositionVector &shape)
Assigns a shape to the named polygon.
ShapeContainer ()
Constructor.
virtual ~ShapeContainer ()
Destructor.
Protected Member Functions
virtual bool add (SUMO::Polygon *poly, bool ignorePruning=false)
virtual bool add (PointOfInterest *poi, bool ignorePruning=false)
Protected Attributes
POIs myPOIs
stored POIs
Polygons myPolygons
stored Polygons
Detailed Description
Storage for geometrical objects.
Definition at line 48 of file ShapeContainer.h.
Member Typedef Documentation
typedef NamedObjectCont< PointOfInterest*> ShapeContainer::POIs
Definition at line 58 of file ShapeContainer.h.
typedef NamedObjectCont< SUMO::Polygon* > ShapeContainer::Polygons
Definition at line 57 of file ShapeContainer.h.
Constructor & Destructor Documentation
ShapeContainer::ShapeContainer ()
Constructor.
Definition at line 57 of file ShapeContainer.cpp.
ShapeContainer::~ShapeContainer () virtual
Destructor.
Definition at line 59 of file ShapeContainer.cpp.
Member Function Documentation
bool ShapeContainer::add (SUMO::Polygon * poly, bool ignorePruning = false) protected virtual
Reimplemented in PCPolyContainer.
Definition at line 110 of file ShapeContainer.cpp.
References NamedObjectCont< T >::add(), Named::getID(), and myPolygons.
Referenced by PCPolyContainer::add(), addPOI(), addPolygon(), and getPOIs().
bool ShapeContainer::add (PointOfInterest * poi, bool ignorePruning = false) protected virtual
Reimplemented in PCPolyContainer.
Definition at line 120 of file ShapeContainer.cpp.
References NamedObjectCont< T >::add(), Named::getID(), and myPOIs.
bool ShapeContainer::addPOI (const std::string & id, const std::string & type, const RGBColor & color, SUMOReal layer, SUMOReal angle, const std::string & imgFile, const Position & pos, SUMOReal width, SUMOReal height, bool ignorePruning = false) virtual
Builds a POI using the given values and adds it to the container.
Parameters
[in] id The name of the POI
[in] type The (abstract) type of the POI
[in] color The color of the POI
[in] layer The layer of the POI
[in] angle The rotation of the POI
[in] imgFile The raster image of the POI
[in] pos The position of the POI
[in] width The width of the POI image
[in] height The height of the POI image
Returns
whether the poi could be added
Reimplemented in GUIShapeContainer.
Definition at line 71 of file ShapeContainer.cpp.
References add().
Referenced by ShapeHandler::addPOI(), and TraCIServerAPI_POI::processSet().
bool ShapeContainer::addPolygon (const std::string & id, const std::string & type, const RGBColor & color, SUMOReal layer, SUMOReal angle, const std::string & imgFile, const PositionVector & shape, bool fill, bool ignorePruning = false) virtual
Builds a polygon using the given values and adds it to the container.
Parameters
[in] id The name of the polygon
[in] type The (abstract) type of the polygon
[in] color The color of the polygon
[in] layer The layer of the polygon
[in] angle The rotation of the polygon
[in] imgFile The raster image of the polygon
[in] shape The shape of the polygon
[in] fill Whether the polygon shall be filled
Returns
whether the polygon could be added
Reimplemented in GUIShapeContainer.
Definition at line 62 of file ShapeContainer.cpp.
References add().
Referenced by NLHandler::addDistrict(), ShapeHandler::addPoly(), and TraCIServerAPI_Polygon::processSet().
const POIs& ShapeContainer::getPOIs () const inline
Returns all pois.
Definition at line 133 of file ShapeContainer.h.
References add(), and myPOIs.
Referenced by TraCIServerAPI_POI::getPoI(), GUIShapeContainer::getPOIIds(), TraCIServerAPI_POI::getTree(), and TraCIServerAPI_POI::processGet().
const Polygons& ShapeContainer::getPolygons () const inline
Returns all polygons.
Definition at line 127 of file ShapeContainer.h.
References myPolygons.
Referenced by TraCIServerAPI_Polygon::getPolygon(), GUIShapeContainer::getPolygonIDs(), TraCIServerAPI_Polygon::getTree(), PCLoaderDlrNavteq::loadPolyFile(), and TraCIServerAPI_Polygon::processGet().
void ShapeContainer::movePOI (const std::string & id, const Position & pos) virtual
Assigns a new position to the named PoI.
Parameters
[in] id The id of the PoI to move
[in] pos The PoI's new position
Reimplemented in GUIShapeContainer.
Definition at line 92 of file ShapeContainer.cpp.
References NamedObjectCont< T >::get(), and myPOIs.
Referenced by TraCIServerAPI_POI::processSet().
bool ShapeContainer::removePOI (const std::string & id) virtual
Removes a PoI from the container.
Parameters
[in] id The id of the PoI
Returns
Whether the poi could be removed
Reimplemented in GUIShapeContainer.
Definition at line 85 of file ShapeContainer.cpp.
References myPOIs, and NamedObjectCont< T >::remove().
Referenced by GNEViewNet::onLeftBtnPress(), and TraCIServerAPI_POI::processSet().
bool ShapeContainer::removePolygon (const std::string & id) virtual
Removes a polygon from the container.
Parameters
[in] id The id of the polygon
Returns
Whether the polygon could be removed
Reimplemented in GUIShapeContainer.
Definition at line 79 of file ShapeContainer.cpp.
References myPolygons, and NamedObjectCont< T >::remove().
Referenced by TraCIServerAPI_Polygon::processSet().
void ShapeContainer::reshapePolygon (const std::string & id, const PositionVector & shape) virtual
Assigns a shape to the named polygon.
Parameters
[in] id The id of the polygon to reshape
[in] shape The polygon's new shape
Reimplemented in GUIShapeContainer.
Definition at line 101 of file ShapeContainer.cpp.
References NamedObjectCont< T >::get(), myPolygons, and SUMO::Polygon::setShape().
Referenced by TraCIServerAPI_Polygon::processSet().
Field Documentation
POIs ShapeContainer::myPOIs protected
stored POIs
Definition at line 148 of file ShapeContainer.h.
Referenced by add(), GUIShapeContainer::addPOI(), getPOIs(), movePOI(), GUIShapeContainer::movePOI(), removePOI(), GUIShapeContainer::removePOI(), PCPolyContainer::save(), and PCPolyContainer::~PCPolyContainer().
Polygons ShapeContainer::myPolygons protected
stored Polygons
Definition at line 145 of file ShapeContainer.h.
Referenced by add(), GUIShapeContainer::addPolygon(), getPolygons(), removePolygon(), GUIShapeContainer::removePolygon(), reshapePolygon(), GUIShapeContainer::reshapePolygon(), PCPolyContainer::save(), and PCPolyContainer::~PCPolyContainer().
The documentation for this class was generated from the following files:
ShapeContainer.h
ShapeContainer.cpp