SUMO - Simulation of Urban MObility: sumo_main.cpp File Reference
sumo_main.cpp File Reference
#include <config.h>
#include <version.h>
#include <ctime>
#include <string>
#include <iostream>
#include <microsim/MSGlobals.h>
#include <microsim/MSNet.h>
#include <microsim/MSRoute.h>
#include <microsim/MSVehicleControl.h>
#include <netload/NLBuilder.h>
#include <netload/NLHandler.h>
#include <netload/NLTriggerBuilder.h>
#include <netload/NLEdgeControlBuilder.h>
#include <netload/NLJunctionControlBuilder.h>
#include <netload/NLDetectorBuilder.h>
#include <utils/options/OptionsCont.h>
#include <utils/options/OptionsIO.h>
#include <utils/common/MsgHandler.h>
#include <utils/common/SystemFrame.h>
#include <utils/common/UtilExceptions.h>
#include <utils/common/FileHelpers.h>
#include <utils/common/StringTokenizer.h>
#include <utils/common/ToString.h>
#include <utils/xml/XMLSubSys.h>
#include <microsim/MSFrame.h>
#include <microsim/output/MSDetectorControl.h>
#include <utils/iodevices/OutputDevice.h>
#include <mesosim/MEVehicleControl.h>
#include <traci-server/TraCIServer.h>
Functions
MSNet * load (OptionsCont &oc)
int main (int argc, char **argv)
Detailed Description
Author
Daniel Krajzewicz
Jakob Erdmann
Axel Wegener
Thimor Bohn
Michael Behrisch
Date
Tue, 20 Nov 2001
Version
Id
sumo_main.cpp 20433 2016-04-13 08:00:14Z behrisch
Definition in file sumo_main.cpp.
Function Documentation
MSNet* load (OptionsCont & oc)
loads the net, additional routes and the detectors
Definition at line 86 of file sumo_main.cpp.
References NLBuilder::build(), MSGlobals::gUseMesoSim, TraCIServer::openSocket(), NLTriggerBuilder::setHandler(), and MSFrame::setMSGlobals().
Referenced by FXEX::FXBaseObject::destroy(), FXEX::FXSevenSegment::getGroove(), FXEX::FXLCDLabel::getText(), FXEX::FXLCDLabel::load(), FXEX::FXSevenSegment::load(), FXEX::FXBaseObject::load(), FX::FXRealSpinDial::load(), and main().
int main (int argc, char ** argv)
Definition at line 120 of file sumo_main.cpp.
References MSFrame::checkOptions(), SystemFrame::close(), MSFrame::fillOptions(), MsgHandler::getErrorInstance(), OptionsIO::getOptions(), OptionsCont::getOptions(), MSRouteHandler::getParsingRNG(), OptionsCont::getString(), MsgHandler::inform(), XMLSubSys::init(), MsgHandler::initOutputOptions(), RandHelper::initRandGlobal(), load(), OptionsCont::processMetaOptions(), OptionsCont::setApplicationDescription(), OptionsCont::setApplicationName(), OptionsIO::setArgs(), XMLSubSys::setValidation(), MSNet::simulate(), string2time(), VERSION_STRING, and WRITE_ERROR.