SUMO - Simulation of Urban MObility: MSXMLRawOut Class Reference
MSXMLRawOut Class Reference
Realises dumping the complete network state.
#include <MSXMLRawOut.h>
Static Public Member Functions
static void write (OutputDevice &of, const MSEdgeControl &ec, SUMOTime timestep, int precision)
Writes the complete network state of the given edges into the given device.
static void writeVehicle (OutputDevice &of, const MSBaseVehicle &veh)
Writes the dump of the given vehicle into the given device.
Private Member Functions
MSXMLRawOut (const MSXMLRawOut &)
Invalidated copy constructor.
MSXMLRawOut & operator= (const MSXMLRawOut &)
Invalidated assignment operator.
Static Private Member Functions
static void writeEdge (OutputDevice &of, const MSEdge &edge, SUMOTime timestep)
Writes the dump of the given edge into the given device.
static void writeLane (OutputDevice &of, const MSLane &lane)
Writes the dump of the given lane into the given device.
static void writeTransportable (OutputDevice &of, const MSTransportable *p, SumoXMLTag tag)
write transportable
Detailed Description
Realises dumping the complete network state.
The class offers a static method, which writes the complete dump of the given network into the given OutputDevice.
Todo:
consider error-handling on write (using IOError)
Definition at line 62 of file MSXMLRawOut.h.
Constructor & Destructor Documentation
MSXMLRawOut::MSXMLRawOut (const MSXMLRawOut &) private
Invalidated copy constructor.
Member Function Documentation
MSXMLRawOut& MSXMLRawOut::operator= (const MSXMLRawOut &) private
Invalidated assignment operator.
void MSXMLRawOut::write (OutputDevice & of, const MSEdgeControl & ec, SUMOTime timestep, int precision) static
Writes the complete network state of the given edges into the given device.
Opens the current time step, goes through the edges and writes each using writeEdge.
Parameters
[in] of The output device to use
[in] ec The EdgeControl which holds the edges to write
[in] timestep The current time step
[in] precision The output precision
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 59 of file MSXMLRawOut.cpp.
References OutputDevice::closeTag(), MSEdgeControl::getEdges(), OutputDevice::openTag(), OUTPUT_ACCURACY, OutputDevice::setPrecision(), time2string(), and writeEdge().
Referenced by MSNet::writeOutput().
void MSXMLRawOut::writeEdge (OutputDevice & of, const MSEdge & edge, SUMOTime timestep) static private
Writes the dump of the given edge into the given device.
If the edge is not empty or also empty edges shall be dumped, the edge description is opened and writeLane is called for each lane.
Parameters
[in] of The output device to use
[in] edge The edge to dump
Todo:
MSGlobals::gOmitEmptyEdgesOnDump should not be used; rather the according option read in write
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 73 of file MSXMLRawOut.cpp.
References OutputDevice::closeTag(), MESegment::getCarNumber(), Named::getID(), MSEdge::getLanes(), MESegment::getNextSegment(), MELoop::getSegmentForEdge(), MSEdge::getSortedContainers(), MSEdge::getSortedPersons(), MSGlobals::gMesoNet, MSGlobals::gOmitEmptyEdgesOnDump, MSGlobals::gUseMesoSim, OutputDevice::openTag(), SUMO_TAG_CONTAINER, SUMO_TAG_PERSON, writeLane(), writeTransportable(), and MESegment::writeVehicles().
Referenced by write().
void MSXMLRawOut::writeLane (OutputDevice & of, const MSLane & lane) static private
Writes the dump of the given lane into the given device.
Opens the lane description and goes through all vehicles, calling writeVehicle for each.
Parameters
[in] of The output device to use
[in] lane The lane to dump
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 129 of file MSXMLRawOut.cpp.
References OutputDevice::closeTag(), MSLane::getVehicleNumber(), Named::myID, MSLane::myVehBuffer, MSLane::myVehicles, OutputDevice::openTag(), and writeVehicle().
Referenced by writeEdge().
void MSXMLRawOut::writeTransportable (OutputDevice & of, const MSTransportable * p, SumoXMLTag tag) static private
write transportable
Definition at line 182 of file MSXMLRawOut.cpp.
References OutputDevice::closeTag(), MSTransportable::getAngle(), MSTransportable::getCurrentStageDescription(), MSTransportable::getEdgePos(), MSTransportable::getID(), GeomHelper::naviDegree(), OutputDevice::openTag(), SUMO_ATTR_ANGLE, SUMO_ATTR_ID, SUMO_ATTR_POSITION, and OutputDevice::writeAttr().
Referenced by writeEdge(), and writeVehicle().
void MSXMLRawOut::writeVehicle (OutputDevice & of, const MSBaseVehicle & veh) static
Writes the dump of the given vehicle into the given device.
Parameters
[in] of The output device to use
[in] veh The vehicle to dump
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 146 of file MSXMLRawOut.cpp.
References OutputDevice::closeTag(), MSVehicle::getContainerNumber(), MSVehicle::getContainers(), MSBaseVehicle::getID(), MSVehicle::getLateralPositionOnLane(), MSVehicle::getPersonNumber(), MSVehicle::getPersons(), SUMOVehicle::getPositionOnLane(), SUMOVehicle::getSpeed(), MSGlobals::gLateralResolution, MSGlobals::gUseMesoSim, MSBaseVehicle::isOnRoad(), OutputDevice::openTag(), SUMO_ATTR_CONTAINER_NUMBER, SUMO_ATTR_ID, SUMO_ATTR_PERSON_NUMBER, SUMO_ATTR_POSITION, SUMO_ATTR_POSITION_LAT, SUMO_ATTR_SPEED, SUMO_TAG_CONTAINER, SUMO_TAG_PERSON, SUMOReal, OutputDevice::writeAttr(), and writeTransportable().
Referenced by writeLane(), and MESegment::writeVehicles().
The documentation for this class was generated from the following files:
MSXMLRawOut.h
MSXMLRawOut.cpp