SUMO - Simulation of Urban MObility: GawronCalculator< R, E, V > Class Template Reference
GawronCalculator< R, E, V > Class Template Reference
Cost calculation with Gawron's method.
#include <GawronCalculator.h>
Public Member Functions
void calculateProbabilities (std::vector< R * > alternatives, const V *const , const SUMOTime)
calculate the probabilities
GawronCalculator (const SUMOReal beta, const SUMOReal a)
Constructor.
int getMaxRouteNumber () const
bool keepRoutes () const
void setCosts (R *route, const SUMOReal costs, const bool isActive=false) const
bool skipRouteCalculation () const
virtual ~GawronCalculator ()
Destructor.
Static Public Member Functions
static void cleanup ()
static RouteCostCalculator< R, E, V > & getCalculator ()
Private Member Functions
SUMOReal gawronF (const SUMOReal pdr, const SUMOReal pds, const SUMOReal x) const
Performs the gawron - f() function From "Dynamic User Equilibria...".
SUMOReal gawronG (const SUMOReal a, const SUMOReal x) const
Performs the gawron - g() function From "Dynamic User Equilibria...".
GawronCalculator & operator= (const GawronCalculator &s)
invalidated assignment operator
Private Attributes
const SUMOReal myA
gawron a - value
const SUMOReal myBeta
gawron beta - value
Detailed Description
template<class R, class E, class V>
class GawronCalculator< R, E, V >
Cost calculation with Gawron's method.
Definition at line 47 of file GawronCalculator.h.
Constructor & Destructor Documentation
template<class R, class E, class V> GawronCalculator< R, E, V >::GawronCalculator (const SUMOReal beta, const SUMOReal a) inline
Constructor.
Definition at line 50 of file GawronCalculator.h.
template<class R, class E, class V> virtual GawronCalculator< R, E, V >::~GawronCalculator () inline virtual
Destructor.
Definition at line 53 of file GawronCalculator.h.
Member Function Documentation
template<class R, class E, class V> void GawronCalculator< R, E, V >::calculateProbabilities (std::vector< R * > alternatives, const V * const, const SUMOTime) inline virtual
calculate the probabilities
Implements RouteCostCalculator< R, E, V >.
Definition at line 64 of file GawronCalculator.h.
References GawronCalculator< R, E, V >::gawronF(), ISNAN(), MAX2(), MIN2(), and SUMOReal.
template<class R, class E, class V> static void RouteCostCalculator< R, E, V >::cleanup () inline static inherited
Definition at line 55 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::calculateProbabilities(), RouteCostCalculator< R, E, V >::myInstance, RouteCostCalculator< R, E, V >::setCosts(), and SUMOReal.
Referenced by RONet::cleanup().
template<class R, class E, class V> SUMOReal GawronCalculator< R, E, V >::gawronF (const SUMOReal pdr, const SUMOReal pds, const SUMOReal x) const inline private
Performs the gawron - f() function From "Dynamic User Equilibria...".
Definition at line 93 of file GawronCalculator.h.
References GawronCalculator< R, E, V >::gawronG(), max, and GawronCalculator< R, E, V >::myA.
Referenced by GawronCalculator< R, E, V >::calculateProbabilities().
template<class R, class E, class V> SUMOReal GawronCalculator< R, E, V >::gawronG (const SUMOReal a, const SUMOReal x) const inline private
Performs the gawron - g() function From "Dynamic User Equilibria...".
Definition at line 103 of file GawronCalculator.h.
References max, and SUMOReal.
Referenced by GawronCalculator< R, E, V >::gawronF().
template<class R , class E , class V > RouteCostCalculator< R, E, V > & RouteCostCalculator< R, E, V >::getCalculator () static inherited
Definition at line 115 of file RouteCostCalculator.h.
References OptionsCont::getFloat(), OptionsCont::getOptions(), OptionsCont::getString(), and RouteCostCalculator< R, E, V >::myInstance.
Referenced by RORouteDef::addAlternative(), and ROMAAssignments::sue().
template<class R, class E, class V> int RouteCostCalculator< R, E, V >::getMaxRouteNumber () const inline inherited
Definition at line 65 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::myMaxRouteNumber.
template<class R, class E, class V> bool RouteCostCalculator< R, E, V >::keepRoutes () const inline inherited
Definition at line 69 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::myKeepRoutes.
Referenced by RORouteDef::addAlternative().
template<class R, class E, class V> GawronCalculator& GawronCalculator< R, E, V >::operator= (const GawronCalculator< R, E, V > & s) private
invalidated assignment operator
template<class R, class E, class V> void GawronCalculator< R, E, V >::setCosts (R * route, const SUMOReal costs, const bool isActive = false) const inline virtual
Implements RouteCostCalculator< R, E, V >.
Definition at line 55 of file GawronCalculator.h.
References GawronCalculator< R, E, V >::myBeta, and SUMOReal.
template<class R, class E, class V> bool RouteCostCalculator< R, E, V >::skipRouteCalculation () const inline inherited
Definition at line 73 of file RouteCostCalculator.h.
References RouteCostCalculator< R, E, V >::mySkipRouteCalculation.
Field Documentation
template<class R, class E, class V> const SUMOReal GawronCalculator< R, E, V >::myA private
gawron a - value
Definition at line 115 of file GawronCalculator.h.
Referenced by GawronCalculator< R, E, V >::gawronF().
template<class R, class E, class V> const SUMOReal GawronCalculator< R, E, V >::myBeta private
gawron beta - value
Definition at line 112 of file GawronCalculator.h.
Referenced by GawronCalculator< R, E, V >::setCosts().
The documentation for this class was generated from the following file:
GawronCalculator.h