SUMO - Simulation of Urban MObility: RODFDetectorFlows Class Reference
RODFDetectorFlows Class Reference
A container for flows.
#include <RODFDetectorFlow.h>
Public Member Functions
void addFlow (const std::string &detector_id, SUMOTime timestamp, const FlowDef &fd)
const std::vector< FlowDef > & getFlowDefs (const std::string &id) const
SUMOReal getFlowSumSecure (const std::string &id) const
SUMOReal getMaxDetectorFlow () const
bool knows (const std::string &det_id) const
void mesoJoin (const std::string &nid, const std::vector< std::string > &oldids)
void printAbsolute () const
void removeFlow (const std::string &detector_id)
RODFDetectorFlows (SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
void setFlows (const std::string &detector_id, std::vector< FlowDef > &)
~RODFDetectorFlows ()
Protected Attributes
SUMOTime myBeginTime
SUMOTime myEndTime
std::map< std::string, std::vector< FlowDef > > myFastAccessFlows
SUMOReal myMaxDetectorFlow
SUMOTime myStepOffset
Private Member Functions
RODFDetectorFlows & operator= (const RODFDetectorFlows &src)
Invalidated assignment operator.
RODFDetectorFlows (const RODFDetectorFlows &src)
Invalidated copy constructor.
Detailed Description
A container for flows.
Definition at line 75 of file RODFDetectorFlow.h.
Constructor & Destructor Documentation
RODFDetectorFlows::RODFDetectorFlows (SUMOTime startTime, SUMOTime endTime, SUMOTime stepOffset)
Definition at line 46 of file RODFDetectorFlow.cpp.
RODFDetectorFlows::~RODFDetectorFlows ()
Definition at line 52 of file RODFDetectorFlow.cpp.
RODFDetectorFlows::RODFDetectorFlows (const RODFDetectorFlows & src) private
Invalidated copy constructor.
Member Function Documentation
void RODFDetectorFlows::addFlow (const std::string & detector_id, SUMOTime timestamp, const FlowDef & fd)
!! mean value?
!! mean value?
Definition at line 56 of file RODFDetectorFlow.cpp.
References FlowDef::firstSet, FlowDef::fLKW, FlowDef::isLKW, myBeginTime, myEndTime, myFastAccessFlows, myStepOffset, FlowDef::qLKW, FlowDef::qPKW, FlowDef::vLKW, and FlowDef::vPKW.
Referenced by mesoJoin(), and RODFDetFlowLoader::read().
const std::vector< FlowDef > & RODFDetectorFlows::getFlowDefs (const std::string & id) const
Definition at line 123 of file RODFDetectorFlow.cpp.
References myFastAccessFlows, and SUMOReal.
Referenced by RODFNet::buildEdgeFlowMap(), getFlowSumSecure(), RODFNet::revalidateFlows(), RODFDetector::writeEmitterDefinition(), and RODFDetector::writeSingleSpeedTrigger().
SUMOReal RODFDetectorFlows::getFlowSumSecure (const std::string & id) const
Definition at line 131 of file RODFDetectorFlow.cpp.
References getFlowDefs(), knows(), and SUMOReal.
Referenced by RODFDetectorCon::writeEmitterPOIs().
SUMOReal RODFDetectorFlows::getMaxDetectorFlow () const
Definition at line 145 of file RODFDetectorFlow.cpp.
References max, myFastAccessFlows, myMaxDetectorFlow, and SUMOReal.
Referenced by RODFDetectorCon::writeEmitterPOIs().
bool RODFDetectorFlows::knows (const std::string & det_id) const
Definition at line 117 of file RODFDetectorFlow.cpp.
References myFastAccessFlows.
Referenced by RODFNet::buildEdgeFlowMap(), getFlowSumSecure(), RODFDetectorCon::guessEmptyFlows(), mesoJoin(), RODFNet::removeEmptyDetectors(), RODFNet::reportEmptyDetectors(), RODFNet::revalidateFlows(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitters(), and RODFDetectorCon::writeSpeedTrigger().
void RODFDetectorFlows::mesoJoin (const std::string & nid, const std::vector< std::string > & oldids)
Definition at line 167 of file RODFDetectorFlow.cpp.
References addFlow(), knows(), myBeginTime, myEndTime, myFastAccessFlows, and myStepOffset.
Referenced by RODFNet::mesoJoin().
RODFDetectorFlows& RODFDetectorFlows::operator= (const RODFDetectorFlows & src) private
Invalidated assignment operator.
void RODFDetectorFlows::printAbsolute () const
Definition at line 184 of file RODFDetectorFlow.cpp.
References myFastAccessFlows, and SUMOReal.
Referenced by startComputation().
void RODFDetectorFlows::removeFlow (const std::string & detector_id)
Definition at line 111 of file RODFDetectorFlow.cpp.
References myFastAccessFlows.
Referenced by RODFNet::removeEmptyDetectors().
void RODFDetectorFlows::setFlows (const std::string & detector_id, std::vector< FlowDef > & flows)
Definition at line 96 of file RODFDetectorFlow.cpp.
References FlowDef::fLKW, myFastAccessFlows, FlowDef::qLKW, and FlowDef::qPKW.
Referenced by RODFNet::revalidateFlows().
Field Documentation
SUMOTime RODFDetectorFlows::myBeginTime protected
Definition at line 95 of file RODFDetectorFlow.h.
Referenced by addFlow(), and mesoJoin().
SUMOTime RODFDetectorFlows::myEndTime protected
Definition at line 95 of file RODFDetectorFlow.h.
Referenced by addFlow(), and mesoJoin().
std::map<std::string, std::vector<FlowDef> > RODFDetectorFlows::myFastAccessFlows protected
Definition at line 94 of file RODFDetectorFlow.h.
Referenced by addFlow(), getFlowDefs(), getMaxDetectorFlow(), knows(), mesoJoin(), printAbsolute(), removeFlow(), and setFlows().
SUMOReal RODFDetectorFlows::myMaxDetectorFlow mutable protected
Definition at line 96 of file RODFDetectorFlow.h.
Referenced by getMaxDetectorFlow().
SUMOTime RODFDetectorFlows::myStepOffset protected
Definition at line 95 of file RODFDetectorFlow.h.
Referenced by addFlow(), and mesoJoin().
The documentation for this class was generated from the following files:
RODFDetectorFlow.h
RODFDetectorFlow.cpp