SUMO - Simulation of Urban MObility: TraCIAPI::LaneScope Class Reference
TraCIAPI::LaneScope Class Reference
Scope for interaction with lanes.
#include <TraCIAPI.h>
Public Member Functions
std::vector< std::string > getAllowed (const std::string &laneID) const
SUMOReal getCO2Emission (const std::string &laneID) const
SUMOReal getCOEmission (const std::string &laneID) const
std::vector< std::string > getDisallowed (const std::string &laneID) const
std::string getEdgeID (const std::string &laneID) const
SUMOReal getElectricityConsumption (const std::string &laneID) const
SUMOReal getFuelConsumption (const std::string &laneID) const
SUMOReal getHCEmission (const std::string &laneID) const
std::vector< std::string > getIDList () const
int getLastStepHaltingNumber (const std::string &laneID) const
SUMOReal getLastStepLength (const std::string &laneID) const
SUMOReal getLastStepMeanSpeed (const std::string &laneID) const
SUMOReal getLastStepOccupancy (const std::string &laneID) const
std::vector< std::string > getLastStepVehicleIDs (const std::string &laneID) const
int getLastStepVehicleNumber (const std::string &laneID) const
SUMOReal getLength (const std::string &laneID) const
int getLinkNumber (const std::string &laneID) const
SUMOReal getMaxSpeed (const std::string &laneID) const
SUMOReal getNoiseEmission (const std::string &laneID) const
SUMOReal getNOxEmission (const std::string &laneID) const
SUMOReal getPMxEmission (const std::string &laneID) const
TraCIPositionVector getShape (const std::string &laneID) const
SUMOReal getTraveltime (const std::string &laneID) const
SUMOReal getWidth (const std::string &laneID) const
LaneScope (TraCIAPI &parent)
void setAllowed (const std::string &laneID, const std::vector< std::string > &allowedClasses) const
void setDisallowed (const std::string &laneID, const std::vector< std::string > &disallowedClasses) const
void setLength (const std::string &laneID, SUMOReal length) const
void setMaxSpeed (const std::string &laneID, SUMOReal speed) const
virtual ~LaneScope ()
Protected Attributes
TraCIAPI & myParent
The parent TraCI client which offers the connection.
Private Member Functions
LaneScope (const LaneScope &src)
invalidated copy constructor
LaneScope & operator= (const LaneScope &src)
invalidated assignment operator
Detailed Description
Scope for interaction with lanes.
Definition at line 376 of file TraCIAPI.h.
Constructor & Destructor Documentation
TraCIAPI::LaneScope::LaneScope (TraCIAPI & parent) inline
Definition at line 378 of file TraCIAPI.h.
virtual TraCIAPI::LaneScope::~LaneScope () inline virtual
Definition at line 379 of file TraCIAPI.h.
References SUMOReal.
TraCIAPI::LaneScope::LaneScope (const LaneScope & src) private
invalidated copy constructor
Member Function Documentation
std::vector< std::string > TraCIAPI::LaneScope::getAllowed (const std::string & laneID) const
Definition at line 893 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and LANE_ALLOWED.
SUMOReal TraCIAPI::LaneScope::getCO2Emission (const std::string & laneID) const
Definition at line 918 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, SUMOReal, and VAR_CO2EMISSION.
SUMOReal TraCIAPI::LaneScope::getCOEmission (const std::string & laneID) const
Definition at line 923 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, SUMOReal, and VAR_COEMISSION.
std::vector< std::string > TraCIAPI::LaneScope::getDisallowed (const std::string & laneID) const
Definition at line 898 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and LANE_DISALLOWED.
std::string TraCIAPI::LaneScope::getEdgeID (const std::string & laneID) const
Definition at line 913 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, LANE_EDGE_ID, and SUMOReal.
SUMOReal TraCIAPI::LaneScope::getElectricityConsumption (const std::string & laneID) const
Definition at line 953 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, SUMOReal, and VAR_ELECTRICITYCONSUMPTION.
SUMOReal TraCIAPI::LaneScope::getFuelConsumption (const std::string & laneID) const
Definition at line 943 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, SUMOReal, and VAR_FUELCONSUMPTION.
SUMOReal TraCIAPI::LaneScope::getHCEmission (const std::string & laneID) const
Definition at line 928 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, SUMOReal, and VAR_HCEMISSION.
std::vector< std::string > TraCIAPI::LaneScope::getIDList () const
Definition at line 873 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, ID_LIST, and SUMOReal.
int TraCIAPI::LaneScope::getLastStepHaltingNumber (const std::string & laneID) const
Definition at line 983 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and LAST_STEP_VEHICLE_HALTING_NUMBER.
SUMOReal TraCIAPI::LaneScope::getLastStepLength (const std::string & laneID) const
Definition at line 968 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, LAST_STEP_LENGTH, and SUMOReal.
SUMOReal TraCIAPI::LaneScope::getLastStepMeanSpeed (const std::string & laneID) const
Definition at line 958 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, LAST_STEP_MEAN_SPEED, and SUMOReal.
SUMOReal TraCIAPI::LaneScope::getLastStepOccupancy (const std::string & laneID) const
Definition at line 963 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, LAST_STEP_OCCUPANCY, and SUMOReal.
std::vector< std::string > TraCIAPI::LaneScope::getLastStepVehicleIDs (const std::string & laneID) const
Definition at line 988 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and LAST_STEP_VEHICLE_ID_LIST.
int TraCIAPI::LaneScope::getLastStepVehicleNumber (const std::string & laneID) const
Definition at line 978 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and LAST_STEP_VEHICLE_NUMBER.
SUMOReal TraCIAPI::LaneScope::getLength (const std::string & laneID) const
Definition at line 878 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, SUMOReal, and VAR_LENGTH.
int TraCIAPI::LaneScope::getLinkNumber (const std::string & laneID) const
Definition at line 903 of file TraCIAPI.cpp.
SUMOReal TraCIAPI::LaneScope::getMaxSpeed (const std::string & laneID) const
Definition at line 883 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, SUMOReal, and VAR_MAXSPEED.
SUMOReal TraCIAPI::LaneScope::getNoiseEmission (const std::string & laneID) const
Definition at line 948 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, SUMOReal, and VAR_NOISEEMISSION.
SUMOReal TraCIAPI::LaneScope::getNOxEmission (const std::string & laneID) const
Definition at line 938 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, SUMOReal, and VAR_NOXEMISSION.
SUMOReal TraCIAPI::LaneScope::getPMxEmission (const std::string & laneID) const
Definition at line 933 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, SUMOReal, and VAR_PMXEMISSION.
TraCIAPI::TraCIPositionVector TraCIAPI::LaneScope::getShape (const std::string & laneID) const
Definition at line 908 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and VAR_SHAPE.
SUMOReal TraCIAPI::LaneScope::getTraveltime (const std::string & laneID) const
Definition at line 973 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and VAR_CURRENT_TRAVELTIME.
SUMOReal TraCIAPI::LaneScope::getWidth (const std::string & laneID) const
Definition at line 888 of file TraCIAPI.cpp.
References CMD_GET_LANE_VARIABLE, and VAR_WIDTH.
LaneScope& TraCIAPI::LaneScope::operator= (const LaneScope & src) private
invalidated assignment operator
void TraCIAPI::LaneScope::setAllowed (const std::string & laneID, const std::vector< std::string > & allowedClasses) const
Definition at line 994 of file TraCIAPI.cpp.
References CMD_SET_LANE_VARIABLE, LANE_ALLOWED, TYPE_STRINGLIST, tcpip::Storage::writeInt(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
void TraCIAPI::LaneScope::setDisallowed (const std::string & laneID, const std::vector< std::string > & disallowedClasses) const
Definition at line 1007 of file TraCIAPI.cpp.
References CMD_SET_LANE_VARIABLE, LANE_DISALLOWED, TYPE_STRINGLIST, tcpip::Storage::writeInt(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
void TraCIAPI::LaneScope::setLength (const std::string & laneID, SUMOReal length) const
Definition at line 1030 of file TraCIAPI.cpp.
References CMD_SET_LANE_VARIABLE, TYPE_DOUBLE, VAR_LENGTH, tcpip::Storage::writeDouble(), and tcpip::Storage::writeUnsignedByte().
void TraCIAPI::LaneScope::setMaxSpeed (const std::string & laneID, SUMOReal speed) const
Definition at line 1020 of file TraCIAPI.cpp.
References CMD_SET_LANE_VARIABLE, TYPE_DOUBLE, VAR_MAXSPEED, tcpip::Storage::writeDouble(), and tcpip::Storage::writeUnsignedByte().
Field Documentation
TraCIAPI& TraCIAPI::TraCIScopeWrapper::myParent protected inherited
The parent TraCI client which offers the connection.
Definition at line 206 of file TraCIAPI.h.
The documentation for this class was generated from the following files:
TraCIAPI.h
TraCIAPI.cpp