SUMO - Simulation of Urban MObility: GUITexturesHelper Class Reference
GUITexturesHelper Class Reference
Global storage for textures; manages and draws them.
#include <GUITexturesHelper.h>
Static Public Member Functions
static GUIGlID add (FXImage *i)
Adds a texture to use.
static void allowTextures (const bool val)
switch texture drawing on and off
static void clearTextures ()
clears loaded textures
static void drawTexturedBox (int which, SUMOReal size)
Draws a named texture as a box with the given size.
static void drawTexturedBox (int which, SUMOReal sizeX1, SUMOReal sizeY1, SUMOReal sizeX2, SUMOReal sizeY2)
Draws a named texture as a rectangle with the given sizes.
static int getMaxTextureSize ()
return maximum number of pixels in x and y direction
static int getTextureID (const std::string &filename, const bool mirrorX=false)
return texture id for the given filename (initialize on first use)
static bool texturesAllowed ()
ask whether texture drawing is enabled
Static Private Attributes
static bool myAllowTextures = true
whether textures are drawn
static std::map< std::string, int > myTextures
mapping from image paths to decals (initialization on first use)
Detailed Description
Global storage for textures; manages and draws them.
Definition at line 46 of file GUITexturesHelper.h.
Member Function Documentation
GUIGlID GUITexturesHelper::add (FXImage * i) static
Adds a texture to use.
Definition at line 67 of file GUITexturesHelper.cpp.
Referenced by GUISUMOAbstractView::drawDecals(), GUITextureSubSys::getGif(), and getTextureID().
static void GUITexturesHelper::allowTextures (const bool val) inline static
switch texture drawing on and off
Definition at line 69 of file GUITexturesHelper.h.
References myAllowTextures.
Referenced by GUIDialog_AppSettings::onCmdOk(), and GUILoadThread::run().
void GUITexturesHelper::clearTextures () static
clears loaded textures
Definition at line 146 of file GUITexturesHelper.cpp.
References myTextures.
Referenced by GUIApplicationWindow::closeAllWindows().
void GUITexturesHelper::drawTexturedBox (int which, SUMOReal size) static
Draws a named texture as a box with the given size.
Definition at line 84 of file GUITexturesHelper.cpp.
Referenced by GUIContainer::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsImage(), GUIBaseVehicle::drawAction_drawVehicleAsImage(), GUISUMOAbstractView::drawDecals(), GNEDetector::drawDetectorIcon(), GNEDetectorE3::drawGL(), GNEJunction::drawGL(), GNEVaporizer::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIPointOfInterest::drawGL(), GNERouteProbe::drawGL(), GNERerouter::drawGL(), and GNEAdditional::drawLockIcon().
void GUITexturesHelper::drawTexturedBox (int which, SUMOReal sizeX1, SUMOReal sizeY1, SUMOReal sizeX2, SUMOReal sizeY2) static
Draws a named texture as a rectangle with the given sizes.
Definition at line 90 of file GUITexturesHelper.cpp.
References myAllowTextures.
int GUITexturesHelper::getMaxTextureSize () static
return maximum number of pixels in x and y direction
Definition at line 59 of file GUITexturesHelper.cpp.
References max.
Referenced by GUISUMOAbstractView::drawDecals(), and getTextureID().
int GUITexturesHelper::getTextureID (const std::string & filename, const bool mirrorX = false) static
return texture id for the given filename (initialize on first use)
Definition at line 125 of file GUITexturesHelper.cpp.
References add(), GUIMainWindow::getInstance(), getMaxTextureSize(), MFXImageHelper::loadImage(), myTextures, MFXImageHelper::scalePower2(), and WRITE_ERROR.
Referenced by GUIContainer::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsImage(), GUIBaseVehicle::drawAction_drawVehicleAsImage(), GUIPolygon::drawGL(), and GUIPointOfInterest::drawGL().
static bool GUITexturesHelper::texturesAllowed () inline static
ask whether texture drawing is enabled
Definition at line 74 of file GUITexturesHelper.h.
References myAllowTextures.
Field Documentation
bool GUITexturesHelper::myAllowTextures = true static private
whether textures are drawn
Definition at line 83 of file GUITexturesHelper.h.
Referenced by allowTextures(), drawTexturedBox(), and texturesAllowed().
std::map< std::string, int > GUITexturesHelper::myTextures static private
mapping from image paths to decals (initialization on first use)
Definition at line 80 of file GUITexturesHelper.h.
Referenced by clearTextures(), and getTextureID().
The documentation for this class was generated from the following files:
GUITexturesHelper.h
GUITexturesHelper.cpp