SUMO - Simulation of Urban MObility: GUIMainWindow Class Reference
GUIMainWindow Class Reference abstract
#include <GUIMainWindow.h>
Public Member Functions
void addChild (FXMDIChild *child, bool updateOnSimStep=true)
Adds a further child window to the list.
void addChild (FXMainWindow *child, bool updateOnSimStep=true)
GUISUMOAbstractView * getActiveView () const
get the active view or 0
FXFont * getBoldFont ()
virtual FXGLCanvas * getBuildGLCanvas () const =0
FXLabel & getCartesianLabel ()
virtual SUMOTime getCurrentSimTime () const =0
virtual SUMOReal getDelay () const
Returns the delay (should be overwritten by subclasses if applicable)
FXLabel & getGeoLabel ()
FXGLVisual * getGLVisual () const
FXMDIChild * getViewByID (const std::string &id) const
std::vector< std::string > getViewIDs () const
GUIMainWindow (FXApp *a)
bool isGaming () const
return whether the gui is in gaming mode
bool listInternal () const
return whether to list internal structures
void removeChild (FXMDIChild *child)
removes the given child window from the list
void removeChild (FXMainWindow *child)
virtual void sendBlockingEvent (GUIEvent *event)
Sends an event from the application thread to the GUI and waits until it is handled.
virtual void setDelay (SUMOReal)
Sets the delay of the parent application.
virtual void setStatusBarText (const std::string &)
void updateChildren ()
virtual ~GUIMainWindow ()
Static Public Member Functions
static GUIMainWindow * getInstance ()
Protected Member Functions
GUIMainWindow ()
Protected Attributes
bool myAmGaming
information whether the gui is currently in gaming mode
FXFont * myBoldFont
Font used for popup-menu titles.
FXDockSite * myBottomDock
FXLabel * myCartesianCoordinate
Labels for the current cartesian and geo-coordinate.
FXHorizontalFrame * myCartesianFrame
FXLabel * myGeoCoordinate
FXHorizontalFrame * myGeoFrame
FXGLVisual * myGLVisual
The gl-visual used.
FXDockSite * myLeftDock
bool myListInternal
information whether the locator should list internal structures
FXMDIClient * myMDIClient
The multi view panel.
FXDockSite * myRightDock
FXStatusBar * myStatusbar
The status bar.
std::vector< FXMDIChild * > mySubWindows
FXDockSite * myTopDock
MFXMutex myTrackerLock
A lock to make the removal and addition of trackers secure.
std::vector< FXMainWindow * > myTrackerWindows
Static Protected Attributes
static GUIMainWindow * myInstance = 0
the singleton window instance
Detailed Description
Definition at line 54 of file GUIMainWindow.h.
Constructor & Destructor Documentation
GUIMainWindow::GUIMainWindow (FXApp * a)
Definition at line 58 of file GUIMainWindow.cpp.
References myBoldFont, myBottomDock, myInstance, myLeftDock, myRightDock, and myTopDock.
GUIMainWindow::~GUIMainWindow () virtual
Definition at line 80 of file GUIMainWindow.cpp.
References myBoldFont, myBottomDock, myLeftDock, myRightDock, and myTopDock.
GUIMainWindow::GUIMainWindow () inline protected
Definition at line 151 of file GUIMainWindow.h.
Member Function Documentation
void GUIMainWindow::addChild (FXMDIChild * child, bool updateOnSimStep = true)
Adds a further child window to the list.
Definition at line 91 of file GUIMainWindow.cpp.
References mySubWindows.
Referenced by GUIParameterTableWindow::closeBuilding(), and GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow().
void GUIMainWindow::addChild (FXMainWindow * child, bool updateOnSimStep = true)
Definition at line 106 of file GUIMainWindow.cpp.
References MFXMutex::lock(), myTrackerLock, myTrackerWindows, and MFXMutex::unlock().
GUISUMOAbstractView * GUIMainWindow::getActiveView () const
get the active view or 0
Definition at line 190 of file GUIMainWindow.cpp.
References GUIGlChildWindow::getView(), and myMDIClient.
Referenced by GUIVehicle::drawOutsideNetwork(), and sendBlockingEvent().
FXFont * GUIMainWindow::getBoldFont ()
Definition at line 144 of file GUIMainWindow.cpp.
References myBoldFont.
Referenced by GUIGlObject::buildPopupHeader().
virtual FXGLCanvas* GUIMainWindow::getBuildGLCanvas () const pure virtual
Implemented in GNEApplicationWindow, and GUIApplicationWindow.
FXLabel & GUIMainWindow::getCartesianLabel ()
Definition at line 169 of file GUIMainWindow.cpp.
References myCartesianCoordinate.
Referenced by setStatusBarText(), and GUISUMOAbstractView::updatePositionInformation().
virtual SUMOTime GUIMainWindow::getCurrentSimTime () const pure virtual
Implemented in GNEApplicationWindow, and GUIApplicationWindow.
Referenced by GUIParam_PopupMenuInterface::onCmdOpenTracker().
virtual SUMOReal GUIMainWindow::getDelay () const inline virtual
Returns the delay (should be overwritten by subclasses if applicable)
Returns
parsed delay in milliseconds
Reimplemented in GUIApplicationWindow.
Definition at line 99 of file GUIMainWindow.h.
Referenced by GUISUMOAbstractView::getDelay(), and GUIViewTraffic::saveFrame().
FXLabel & GUIMainWindow::getGeoLabel ()
Definition at line 175 of file GUIMainWindow.cpp.
References myGeoCoordinate.
Referenced by setStatusBarText(), and GUISUMOAbstractView::updatePositionInformation().
FXGLVisual * GUIMainWindow::getGLVisual () const
Definition at line 163 of file GUIMainWindow.cpp.
References myGLVisual.
Referenced by GUISUMOViewParent::init().
GUIMainWindow * GUIMainWindow::getInstance (void) static
Definition at line 181 of file GUIMainWindow.cpp.
References myInstance.
Referenced by GUIVehicle::drawOutsideNetwork(), TraCIServerAPI_GUI::getNamedView(), GUITexturesHelper::getTextureID(), listInternal(), TraCIServerAPI_GUI::processGet(), TraCIServerAPI_GUI::processSet(), and GUIMessageWindow::setCursorPos().
FXMDIChild * GUIMainWindow::getViewByID (const std::string & id) const
Definition at line 133 of file GUIMainWindow.cpp.
References mySubWindows.
Referenced by TraCIServerAPI_GUI::getNamedView(), and GUIMessageWindow::setCursorPos().
std::vector< std::string > GUIMainWindow::getViewIDs () const
Definition at line 123 of file GUIMainWindow.cpp.
References mySubWindows.
Referenced by TraCIServerAPI_GUI::processGet(), and GUIMessageWindow::setCursorPos().
bool GUIMainWindow::isGaming () const inline
return whether the gui is in gaming mode
Definition at line 85 of file GUIMainWindow.h.
References myAmGaming.
Referenced by GUIApplicationWindow::handleEvent_SimulationLoaded(), GUISUMOViewParent::init(), GUISUMOAbstractView::onLeftBtnRelease(), GUISUMOAbstractView::onMouseWheel(), GUISUMOAbstractView::onRightBtnRelease(), and GUIViewTraffic::setColorScheme().
bool GUIMainWindow::listInternal () const inline
return whether to list internal structures
Definition at line 90 of file GUIMainWindow.h.
References getInstance(), and myListInternal.
Referenced by GUISUMOViewParent::onCmdLocate().
void GUIMainWindow::removeChild (FXMDIChild * child)
removes the given child window from the list
Definition at line 97 of file GUIMainWindow.cpp.
References mySubWindows.
Referenced by GNEViewParent::~GNEViewParent(), GUIDialog_Breakpoints::~GUIDialog_Breakpoints(), GUIDialog_GLChosenEditor::~GUIDialog_GLChosenEditor(), GUIDialog_GLObjChooser::~GUIDialog_GLObjChooser(), GUIParameterTableWindow::~GUIParameterTableWindow(), GUIParameterTracker::~GUIParameterTracker(), GUISUMOViewParent::~GUISUMOViewParent(), and GUITLLogicPhasesTrackerWindow::~GUITLLogicPhasesTrackerWindow().
void GUIMainWindow::removeChild (FXMainWindow * child)
Definition at line 114 of file GUIMainWindow.cpp.
References MFXMutex::lock(), myTrackerLock, myTrackerWindows, and MFXMutex::unlock().
virtual void GUIMainWindow::sendBlockingEvent (GUIEvent * event) inline virtual
Sends an event from the application thread to the GUI and waits until it is handled.
Parameters
event the event to send
Reimplemented in GUIApplicationWindow.
Definition at line 110 of file GUIMainWindow.h.
References getActiveView(), and UNUSED_PARAMETER.
Referenced by TraCIServerAPI_GUI::processSet().
virtual void GUIMainWindow::setDelay (SUMOReal) inline virtual
Sets the delay of the parent application.
Reimplemented in GUIApplicationWindow.
Definition at line 105 of file GUIMainWindow.h.
Referenced by GUISUMOAbstractView::setDelay().
virtual void GUIMainWindow::setStatusBarText (const std::string &) inline virtual
Reimplemented in GUIApplicationWindow, and GNEApplicationWindow.
Definition at line 79 of file GUIMainWindow.h.
References getCartesianLabel(), and getGeoLabel().
Referenced by GUISUMOAbstractView::getObjectsInBoundary(), and GNEViewNet::setStatusBarText().
void GUIMainWindow::updateChildren ()
Definition at line 150 of file GUIMainWindow.cpp.
References MFXMutex::lock(), MID_SIMSTEP, myMDIClient, myTrackerLock, myTrackerWindows, and MFXMutex::unlock().
Referenced by GUIApplicationWindow::handleEvent_SimulationStep(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdChangeOption(), GUITriggeredRerouter::GUIManip_TriggeredRerouter::onCmdChangeOption(), GUIDialog_GLChosenEditor::onCmdClear(), GUIDialog_GLChosenEditor::onCmdDeselect(), GUIApplicationWindow::onCmdEditChosen(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdPreDef(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onCmdUserDef(), GUITriggeredRerouter::GUIManip_TriggeredRerouter::onCmdUserDef(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onUpdPreDef(), GUICalibrator::GUIManip_Calibrator::onUpdPreDef(), GUILaneSpeedTrigger::GUIManip_LaneSpeedTrigger::onUpdUserDef(), GUICalibrator::GUIManip_Calibrator::onUpdUserDef(), and GUITriggeredRerouter::GUIManip_TriggeredRerouter::onUpdUserDef().
Field Documentation
bool GUIMainWindow::myAmGaming protected
information whether the gui is currently in gaming mode
Definition at line 142 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::handleEvent_SimulationStep(), isGaming(), GUIApplicationWindow::onCmdFullScreen(), GUIApplicationWindow::onCmdGaming(), and GUIApplicationWindow::updateTimeLCD().
FXFont* GUIMainWindow::myBoldFont protected
Font used for popup-menu titles.
Definition at line 124 of file GUIMainWindow.h.
Referenced by getBoldFont(), GUIMainWindow(), and ~GUIMainWindow().
FXDockSite * GUIMainWindow::myBottomDock protected
Definition at line 139 of file GUIMainWindow.h.
Referenced by GUIMainWindow(), and ~GUIMainWindow().
FXLabel* GUIMainWindow::myCartesianCoordinate protected
Labels for the current cartesian and geo-coordinate.
Definition at line 133 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::closeAllWindows(), GNEApplicationWindow::closeAllWindows(), GNEApplicationWindow::dependentBuild(), GUIApplicationWindow::dependentBuild(), and getCartesianLabel().
FXHorizontalFrame* GUIMainWindow::myCartesianFrame protected
Definition at line 134 of file GUIMainWindow.h.
Referenced by GNEApplicationWindow::create(), GUIApplicationWindow::create(), GNEApplicationWindow::dependentBuild(), and GUIApplicationWindow::dependentBuild().
FXLabel * GUIMainWindow::myGeoCoordinate protected
Definition at line 133 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::closeAllWindows(), GNEApplicationWindow::closeAllWindows(), GNEApplicationWindow::dependentBuild(), GUIApplicationWindow::dependentBuild(), and getGeoLabel().
FXHorizontalFrame * GUIMainWindow::myGeoFrame protected
Definition at line 134 of file GUIMainWindow.h.
Referenced by GNEApplicationWindow::create(), GUIApplicationWindow::create(), GNEApplicationWindow::dependentBuild(), and GUIApplicationWindow::dependentBuild().
FXGLVisual* GUIMainWindow::myGLVisual protected
The gl-visual used.
Definition at line 137 of file GUIMainWindow.h.
Referenced by getGLVisual(), GNEApplicationWindow::~GNEApplicationWindow(), and GUIApplicationWindow::~GUIApplicationWindow().
GUIMainWindow * GUIMainWindow::myInstance = 0 static protected
the singleton window instance
Definition at line 148 of file GUIMainWindow.h.
Referenced by getInstance(), and GUIMainWindow().
FXDockSite * GUIMainWindow::myLeftDock protected
Definition at line 139 of file GUIMainWindow.h.
Referenced by GUIMainWindow(), and ~GUIMainWindow().
bool GUIMainWindow::myListInternal protected
information whether the locator should list internal structures
Definition at line 145 of file GUIMainWindow.h.
Referenced by listInternal(), and GUIApplicationWindow::onCmdListInternal().
FXMDIClient* GUIMainWindow::myMDIClient protected
The multi view panel.
Definition at line 127 of file GUIMainWindow.h.
Referenced by GNEApplicationWindow::dependentBuild(), GUIApplicationWindow::dependentBuild(), GUIApplicationWindow::fillMenuBar(), getActiveView(), GUIApplicationWindow::getBuildGLCanvas(), GNEApplicationWindow::getBuildGLCanvas(), GUIApplicationWindow::onCmdEditChosen(), GUIApplicationWindow::onCmdFullScreen(), GUIApplicationWindow::onCmdGaming(), GNEApplicationWindow::onCmdLocate(), GUIApplicationWindow::onCmdLocate(), GUIApplicationWindow::onCmdShowStats(), GNEApplicationWindow::onKeyPress(), GUIApplicationWindow::onKeyPress(), GNEApplicationWindow::onKeyRelease(), GUIApplicationWindow::onKeyRelease(), GUIApplicationWindow::openNewView(), GNEApplicationWindow::openNewView(), and updateChildren().
FXDockSite * GUIMainWindow::myRightDock protected
Definition at line 139 of file GUIMainWindow.h.
Referenced by GUIMainWindow(), and ~GUIMainWindow().
FXStatusBar* GUIMainWindow::myStatusbar protected
The status bar.
Definition at line 130 of file GUIMainWindow.h.
Referenced by GNEApplicationWindow::dependentBuild(), GUIApplicationWindow::dependentBuild(), GNEApplicationWindow::fillMenuBar(), GUIApplicationWindow::fillMenuBar(), GUIApplicationWindow::onCmdFullScreen(), GUIApplicationWindow::onCmdGaming(), GNEApplicationWindow::onCmdOpenRecent(), GUIApplicationWindow::onCmdOpenRecent(), GUIApplicationWindow::onCmdStart(), GUIApplicationWindow::onCmdStep(), GUIApplicationWindow::openNewView(), GNEApplicationWindow::setStatusBarText(), and GUIApplicationWindow::setStatusBarText().
std::vector<FXMDIChild*> GUIMainWindow::mySubWindows protected
Definition at line 118 of file GUIMainWindow.h.
Referenced by addChild(), GUIApplicationWindow::closeAllWindows(), GNEApplicationWindow::closeAllWindows(), GNEApplicationWindow::getView(), getViewByID(), getViewIDs(), GUIApplicationWindow::onCmdNetedit(), and removeChild().
FXDockSite* GUIMainWindow::myTopDock protected
Definition at line 139 of file GUIMainWindow.h.
Referenced by GUIApplicationWindow::buildToolBars(), GNEApplicationWindow::dependentBuild(), GUIApplicationWindow::dependentBuild(), GUIMainWindow(), and ~GUIMainWindow().
MFXMutex GUIMainWindow::myTrackerLock protected
A lock to make the removal and addition of trackers secure.
Definition at line 121 of file GUIMainWindow.h.
Referenced by addChild(), GUIApplicationWindow::closeAllWindows(), GNEApplicationWindow::closeAllWindows(), removeChild(), and updateChildren().
std::vector<FXMainWindow*> GUIMainWindow::myTrackerWindows protected
Definition at line 119 of file GUIMainWindow.h.
Referenced by addChild(), GUIApplicationWindow::closeAllWindows(), GNEApplicationWindow::closeAllWindows(), removeChild(), and updateChildren().
The documentation for this class was generated from the following files:
GUIMainWindow.h
GUIMainWindow.cpp