SUMO - Simulation of Urban MObility: MS_E2_ZS_CollectorOverLanes Class Reference
MS_E2_ZS_CollectorOverLanes Class Reference
A detector which joins E2Collectors over consecutive lanes (backward)
#include <MS_E2_ZS_CollectorOverLanes.h>
Public Types
typedef std::vector< MSE2Collector * > CollectorCont
Definition of a E2 collector storage.
Public Member Functions
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
const std::string & getID () const
Returns the id.
SUMOReal getLength () const
Returns this detector's length [m].
const std::string & getStartLaneID () const
Returns the id of the lane this detector starts at.
void init (MSLane *lane, SUMOReal detLength)
Builds the consecutive E2 detectors.
MS_E2_ZS_CollectorOverLanes (const std::string &id, DetectorUsage usage, MSLane *lane, SUMOReal startPos, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold)
Constructor.
void setID (const std::string &newID)
resets the id
virtual ~MS_E2_ZS_CollectorOverLanes ()
Destructor.
Methods inherited from MSDetectorFileOutput.
void writeXMLOutput (OutputDevice &dev, SUMOTime startTime, SUMOTime stopTime)
Writes collected values into the given stream.
void writeXMLDetectorProlog (OutputDevice &dev) const
Opens the XML-output using "detector" as root element.
Virtual methods to implement by derived classes
virtual void reset ()
Resets collected values.
virtual void detectorUpdate (const SUMOTime step)
Updates the detector (computes values)
virtual GUIDetectorWrapper * buildDetectorGUIRepresentation ()
Builds the graphical representation.
Static Public Member Functions
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
Protected Types
typedef std::vector< MSE2Collector * > DetectorVector
Definition of a detector storage.
typedef std::vector< DetectorVector > DetectorVectorVector
Definition of a storage for detector vectors.
typedef std::map< MSLane *, MSE2Collector * > LaneDetMap
Definition of a map from a lane to the detector lying on it.
typedef std::vector< MSLane * > LaneVector
Definition of a lane storage.
typedef std::vector< LaneVector > LaneVectorVector
Definition of a storage for lane vectors.
typedef std::vector< SUMOReal > LengthVector
Definition of a storage for SUMOReal vectors.
Protected Member Functions
virtual MSE2Collector * buildCollector (int c, int r, MSLane *l, SUMOReal start, SUMOReal end)
Builds a single collector.
void extendTo (SUMOReal length)
This method extends the current length up to the given.
std::vector< MSLane * > getLanePredeccessorLanes (MSLane *l)
Returns the list of lanes predecessing the given one.
std::string makeID (const std::string &baseID, int c, int r) const
Builds an id for one of the E2 collectors this detector uses.
Protected Attributes
SUMOReal haltingSpeedThresholdM
Describes how slow a vehicle must be before being assigned to a jam.
SUMOTime haltingTimeThresholdM
Describes how long a vehicle shall stay before being assigned to a jam.
SUMOReal jamDistThresholdM
Describes how long a jam must be before being recognized.
LaneDetMap myAlreadyBuild
Storage for detectors which already have been build for a single lane.
DetectorVectorVector myDetectorCombinations
Storage for detector combinations.
std::string myID
The name of the object.
LaneVectorVector myLaneCombinations
Storage for lane combinations.
SUMOReal myLength
The length of the collector.
LengthVector myLengths
Storage for length combinations.
std::string myStartLaneID
The id of the lane this detector starts at.
DetectorUsage myUsage
Information about how this detector is used.
SUMOReal startPosM
The position the collector starts at.
Private Member Functions
MS_E2_ZS_CollectorOverLanes (const MS_E2_ZS_CollectorOverLanes &)
Invalidated copy constructor.
MS_E2_ZS_CollectorOverLanes & operator= (const MS_E2_ZS_CollectorOverLanes &)
Invalidated assignment operator.
Detailed Description
A detector which joins E2Collectors over consecutive lanes (backward)
This class is somekind of a wrapper over several MSE2Collectors.
For some reasons it may be necessary to use MSE2Collectors that are longer than the lane they begin at. In this case, this class should be used. MSE2Collectors are laid on consecutive lanes backwards, building a virtual detector for each lane combination.
There are still some problems with it: we do not know how the different combinations shall be treated.
Definition at line 64 of file MS_E2_ZS_CollectorOverLanes.h.
Member Typedef Documentation
typedef std::vector< MSE2Collector* > MS_E2_ZS_CollectorOverLanes::CollectorCont
Definition of a E2 collector storage.
Definition at line 67 of file MS_E2_ZS_CollectorOverLanes.h.
typedef std::vector<MSE2Collector*> MS_E2_ZS_CollectorOverLanes::DetectorVector protected
Definition of a detector storage.
Definition at line 207 of file MS_E2_ZS_CollectorOverLanes.h.
typedef std::vector<DetectorVector> MS_E2_ZS_CollectorOverLanes::DetectorVectorVector protected
Definition of a storage for detector vectors.
Definition at line 210 of file MS_E2_ZS_CollectorOverLanes.h.
typedef std::map<MSLane*, MSE2Collector*> MS_E2_ZS_CollectorOverLanes::LaneDetMap protected
Definition of a map from a lane to the detector lying on it.
Definition at line 238 of file MS_E2_ZS_CollectorOverLanes.h.
typedef std::vector<MSLane*> MS_E2_ZS_CollectorOverLanes::LaneVector protected
Definition of a lane storage.
Definition at line 201 of file MS_E2_ZS_CollectorOverLanes.h.
typedef std::vector<LaneVector> MS_E2_ZS_CollectorOverLanes::LaneVectorVector protected
Definition of a storage for lane vectors.
Definition at line 204 of file MS_E2_ZS_CollectorOverLanes.h.
typedef std::vector<SUMOReal> MS_E2_ZS_CollectorOverLanes::LengthVector protected
Definition of a storage for SUMOReal vectors.
Definition at line 213 of file MS_E2_ZS_CollectorOverLanes.h.
Constructor & Destructor Documentation
MS_E2_ZS_CollectorOverLanes::MS_E2_ZS_CollectorOverLanes (const std::string & id, DetectorUsage usage, MSLane * lane, SUMOReal startPos, SUMOTime haltingTimeThreshold, SUMOReal haltingSpeedThreshold, SUMOReal jamDistThreshold)
Constructor.
Parameters
[in] id The id of the detector
[in] usage Information how the detector is used
[in] lane The lane the detector starts at
[in] startPos Begin position of the detector
[in] detLength Length of the detector
[in] haltingTimeThreshold The time a vehicle's speed must be below haltingSpeedThreshold to be assigned as jammed
[in] haltingSpeedThreshold The speed a vehicle's speed must be below to be assigned as jammed
[in] jamDistThreshold The distance between two vehicles in order to not count them to one jam
Todo:
The lane should not be given as a pointer
Definition at line 47 of file MS_E2_ZS_CollectorOverLanes.cpp.
MS_E2_ZS_CollectorOverLanes::~MS_E2_ZS_CollectorOverLanes () virtual
Destructor.
Definition at line 83 of file MS_E2_ZS_CollectorOverLanes.cpp.
MS_E2_ZS_CollectorOverLanes::MS_E2_ZS_CollectorOverLanes (const MS_E2_ZS_CollectorOverLanes &) private
Invalidated copy constructor.
Member Function Documentation
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
MSE2Collector * MS_E2_ZS_CollectorOverLanes::buildCollector (int c, int r, MSLane * l, SUMOReal start, SUMOReal end) protected virtual
Builds a single collector.
Parameters
[in] c !!!
[in] r !!!
[in] start !!!
[in] end !!!
Todo:
Describe!
Reimplemented in GUI_E2_ZS_CollectorOverLanes.
Definition at line 200 of file MS_E2_ZS_CollectorOverLanes.cpp.
References Named::getID(), getLength(), MSLane::getLength(), haltingSpeedThresholdM, haltingTimeThresholdM, jamDistThresholdM, makeID(), myUsage, and SUMOReal.
Referenced by extendTo(), getLength(), and init().
virtual GUIDetectorWrapper* MSDetectorFileOutput::buildDetectorGUIRepresentation () inline virtual inherited
Builds the graphical representation.
Meant to be overridden by graphical versions of the detectors
Returns
A wrapper for the detector which performs the user I/O within the GUI
Reimplemented in GUI_E2_ZS_Collector, GUIInductLoop, GUIE3Collector, GUI_E2_ZS_CollectorOverLanes, GUIInstantInductLoop, and GUIMEInductLoop.
Definition at line 123 of file MSDetectorFileOutput.h.
References MSDetectorFileOutput::MSDetectorFileOutput(), and MSDetectorFileOutput::operator=().
virtual void MSDetectorFileOutput::detectorUpdate (const SUMOTime step) inline virtual inherited
Updates the detector (computes values)
Parameters
[in] step The current time step
Reimplemented in MSMeanData, MSE3Collector, MSMeanData_Harmonoise, and MSE2Collector.
Definition at line 113 of file MSDetectorFileOutput.h.
References UNUSED_PARAMETER.
void MS_E2_ZS_CollectorOverLanes::extendTo (SUMOReal length) protected
This method extends the current length up to the given.
This method is called consecutively until all paths have the desired length
Parameters
[in] length !!!
Todo:
Describe length's usage
Definition at line 87 of file MS_E2_ZS_CollectorOverLanes.cpp.
References buildCollector(), MSLane::getEdge(), getLanePredeccessorLanes(), MSEdge::getLanes(), MSLane::getLength(), myAlreadyBuild, myDetectorCombinations, myLaneCombinations, myLengths, and SUMOReal.
Referenced by getLength(), and init().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciBusOrContainerStop(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), buildCollector(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNEConnectorFrame::buildIinternalLanes(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), NLDetectorBuilder::convUncontE2PosLength(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSVehicle::getBackPosition(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), GNEEdge::getDest(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), MSE2Collector::getEstimateQueueLength(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), getLanePredeccessorLanes(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), GNEEdge::getSource(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_BTsender::notifyMove(), MSE2Collector::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_SL2015::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_LC2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_ArealDetector::processGet(), TraCIServerAPI_Lane::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), MSBaseVehicle::reroute(), MSLane::resetPartialOccupation(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), MSLane::saveState(), MSDevice_Battery::setAirDragCoefficient(), NBNodeCont::setAsTLControlled(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), MSDevice_Battery::setConstantPowerIntake(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), MSDevice_Battery::setFrontSurfaceArea(), MSDevice_Battery::setInternalMomentOfInertia(), GNEJunction::setLogicValid(), MSDevice_Battery::setMass(), MSDevice_Battery::setMaximumBatteryCapacity(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSDevice_Battery::setPropulsionEfficiency(), MSDevice_Battery::setRadialDragCoefficient(), MSDevice_Battery::setRecuperationEfficiency(), MSLink::setRequestInformation(), MSDevice_Battery::setRollDragCoefficient(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), operator<<(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
std::vector< MSLane * > MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes (MSLane * l) protected
Returns the list of lanes predecessing the given one.
Parameters
[in] l The lane to return predecessors of
Returns
List of lanes predecessing the given one
Definition at line 170 of file MS_E2_ZS_CollectorOverLanes.cpp.
References MSEdge::allowedLanes(), MSLane::getEdge(), Named::getID(), MSEdge::getIncomingEdges(), and SVC_IGNORING.
Referenced by extendTo(), and getLength().
SUMOReal MS_E2_ZS_CollectorOverLanes::getLength () const inline
Returns this detector's length [m].
Returns
This detector's length in meters
Definition at line 140 of file MS_E2_ZS_CollectorOverLanes.h.
References buildCollector(), extendTo(), getLanePredeccessorLanes(), makeID(), myLength, and SUMOReal.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), buildCollector(), and GUI_E2_ZS_CollectorOverLanes::MyWrapper::getParameterWindow().
const std::string & MS_E2_ZS_CollectorOverLanes::getStartLaneID () const
Returns the id of the lane this detector starts at.
Returns
The id of the lane this detector starts at
Todo:
Check whether this is needed
Definition at line 261 of file MS_E2_ZS_CollectorOverLanes.cpp.
References myStartLaneID.
void MS_E2_ZS_CollectorOverLanes::init (MSLane * lane, SUMOReal detLength)
Builds the consecutive E2 detectors.
This is not done within the constructor to allow overriding of most functions but the building of detectors itself which in fact is depending on whether the normal or the gui-version is used
Parameters
[in] lane The lane the detector starts at
[in] startPos Begin position of the detector
Definition at line 61 of file MS_E2_ZS_CollectorOverLanes.cpp.
References buildCollector(), extendTo(), MSLane::getLength(), myAlreadyBuild, myDetectorCombinations, myLaneCombinations, myLength, myLengths, startPosM, and SUMOReal.
std::string MS_E2_ZS_CollectorOverLanes::makeID (const std::string & baseID, int c, int r) const protected
Builds an id for one of the E2 collectors this detector uses.
Parameters
[in] baseID The id of the parent detector
[in] c !!!
[in] r !!!
Todo:
Describe!
Definition at line 239 of file MS_E2_ZS_CollectorOverLanes.cpp.
References bla, DU_SUMO_INTERNAL, DU_TL_CONTROL, DU_USER_DEFINED, and myUsage.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), buildCollector(), and getLength().
MS_E2_ZS_CollectorOverLanes& MS_E2_ZS_CollectorOverLanes::operator= (const MS_E2_ZS_CollectorOverLanes &) private
Invalidated assignment operator.
virtual void MSDetectorFileOutput::reset () inline virtual inherited
Resets collected values.
Please note that this is only a "hack" for coupled-tls-outputs.
See also
Command_SaveTLCoupledLaneDet
Todo:
Reckeck/refactor
Reimplemented in MSE2Collector, MSE3Collector, MSInductLoop, and GUIInductLoop.
Definition at line 106 of file MSDetectorFileOutput.h.
Referenced by Command_SaveTLCoupledLaneDet::execute().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
void MS_E2_ZS_CollectorOverLanes::writeXMLDetectorProlog (OutputDevice & dev) const virtual
Opens the XML-output using "detector" as root element.
Parameters
[in] dev The output device to write the root into
See also
MSDetectorFileOutput::writeXMLDetectorProlog
Todo:
What happens with the additional information if several detectors use the same output?
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSDetectorFileOutput.
Definition at line 231 of file MS_E2_ZS_CollectorOverLanes.cpp.
References OutputDevice::writeXMLHeader().
void MS_E2_ZS_CollectorOverLanes::writeXMLOutput (OutputDevice & dev, SUMOTime startTime, SUMOTime stopTime) virtual
Writes collected values into the given stream.
Parameters
[in] dev The output device to write the data into
[in] startTime First time step the data were gathered
[in] stopTime Last time step the data were gathered
See also
MSDetectorFileOutput::writeXMLOutput
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Implements MSDetectorFileOutput.
Definition at line 213 of file MS_E2_ZS_CollectorOverLanes.cpp.
Field Documentation
SUMOReal MS_E2_ZS_CollectorOverLanes::haltingSpeedThresholdM protected
Describes how slow a vehicle must be before being assigned to a jam.
Definition at line 195 of file MS_E2_ZS_CollectorOverLanes.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), and buildCollector().
SUMOTime MS_E2_ZS_CollectorOverLanes::haltingTimeThresholdM protected
Describes how long a vehicle shall stay before being assigned to a jam.
Definition at line 192 of file MS_E2_ZS_CollectorOverLanes.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), and buildCollector().
SUMOReal MS_E2_ZS_CollectorOverLanes::jamDistThresholdM protected
Describes how long a jam must be before being recognized.
Definition at line 198 of file MS_E2_ZS_CollectorOverLanes.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), and buildCollector().
LaneDetMap MS_E2_ZS_CollectorOverLanes::myAlreadyBuild protected
Storage for detectors which already have been build for a single lane.
Definition at line 241 of file MS_E2_ZS_CollectorOverLanes.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildDetectorGUIRepresentation(), extendTo(), and init().
DetectorVectorVector MS_E2_ZS_CollectorOverLanes::myDetectorCombinations protected
Storage for detector combinations.
Each detector combination is a vector of consecutive lanes (backwards)
Definition at line 225 of file MS_E2_ZS_CollectorOverLanes.h.
Referenced by extendTo(), and init().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
LaneVectorVector MS_E2_ZS_CollectorOverLanes::myLaneCombinations protected
Storage for lane combinations.
Each lane combination is a vector of consecutive lanes (backwards)
Definition at line 219 of file MS_E2_ZS_CollectorOverLanes.h.
Referenced by extendTo(), and init().
SUMOReal MS_E2_ZS_CollectorOverLanes::myLength protected
The length of the collector.
Definition at line 189 of file MS_E2_ZS_CollectorOverLanes.h.
Referenced by getLength(), and init().
LengthVector MS_E2_ZS_CollectorOverLanes::myLengths protected
Storage for length combinations.
Each length combination is a vector of consecutive lanes (backwards)
Definition at line 231 of file MS_E2_ZS_CollectorOverLanes.h.
Referenced by extendTo(), and init().
std::string MS_E2_ZS_CollectorOverLanes::myStartLaneID protected
The id of the lane this detector starts at.
Definition at line 235 of file MS_E2_ZS_CollectorOverLanes.h.
Referenced by getStartLaneID().
DetectorUsage MS_E2_ZS_CollectorOverLanes::myUsage protected
Information about how this detector is used.
Definition at line 244 of file MS_E2_ZS_CollectorOverLanes.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), buildCollector(), and makeID().
SUMOReal MS_E2_ZS_CollectorOverLanes::startPosM protected
The position the collector starts at.
Definition at line 186 of file MS_E2_ZS_CollectorOverLanes.h.
Referenced by init().
The documentation for this class was generated from the following files:
MS_E2_ZS_CollectorOverLanes.h
MS_E2_ZS_CollectorOverLanes.cpp