SUMO - Simulation of Urban MObility: TraCIAPI::PersonScope Class Reference
TraCIAPI::PersonScope Class Reference
Scope for interaction with vehicles.
#include <TraCIAPI.h>
Public Member Functions
int getIDCount () const
std::vector< std::string > getIDList () const
std::string getNextEdge (const std::string &typeID) const
TraCIPosition getPosition (const std::string &typeID) const
std::string getRoadID (const std::string &typeID) const
SUMOReal getSpeed (const std::string &typeID) const
std::string getTypeID (const std::string &typeID) const
SUMOReal getWaitingTime (const std::string &typeID) const
PersonScope (TraCIAPI &parent)
virtual ~PersonScope ()
Protected Attributes
TraCIAPI & myParent
The parent TraCI client which offers the connection.
Private Member Functions
PersonScope & operator= (const PersonScope &src)
invalidated assignment operator
PersonScope (const PersonScope &src)
invalidated copy constructor
Detailed Description
Scope for interaction with vehicles.
Definition at line 806 of file TraCIAPI.h.
Constructor & Destructor Documentation
TraCIAPI::PersonScope::PersonScope (TraCIAPI & parent) inline
Definition at line 808 of file TraCIAPI.h.
virtual TraCIAPI::PersonScope::~PersonScope () inline virtual
Definition at line 809 of file TraCIAPI.h.
References TraCIAPI::getPosition(), and SUMOReal.
TraCIAPI::PersonScope::PersonScope (const PersonScope & src) private
invalidated copy constructor
Member Function Documentation
int TraCIAPI::PersonScope::getIDCount () const
Definition at line 2105 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, ID_COUNT, and SUMOReal.
std::vector< std::string > TraCIAPI::PersonScope::getIDList () const
Definition at line 2100 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, and ID_LIST.
Referenced by TraCITestClient::testAPI().
std::string TraCIAPI::PersonScope::getNextEdge (const std::string & typeID) const
Definition at line 2135 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, and VAR_NEXT_EDGE.
Referenced by TraCITestClient::testAPI().
TraCIAPI::TraCIPosition TraCIAPI::PersonScope::getPosition (const std::string & typeID) const
Definition at line 2115 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, and VAR_POSITION.
std::string TraCIAPI::PersonScope::getRoadID (const std::string & typeID) const
Definition at line 2120 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, and VAR_ROAD_ID.
Referenced by TraCITestClient::testAPI().
SUMOReal TraCIAPI::PersonScope::getSpeed (const std::string & typeID) const
Definition at line 2110 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, and VAR_SPEED.
std::string TraCIAPI::PersonScope::getTypeID (const std::string & typeID) const
Definition at line 2125 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, SUMOReal, and VAR_TYPE.
Referenced by TraCITestClient::testAPI().
SUMOReal TraCIAPI::PersonScope::getWaitingTime (const std::string & typeID) const
Definition at line 2130 of file TraCIAPI.cpp.
References CMD_GET_PERSON_VARIABLE, and VAR_WAITING_TIME.
Referenced by TraCITestClient::testAPI().
PersonScope& TraCIAPI::PersonScope::operator= (const PersonScope & src) private
invalidated assignment operator
Field Documentation
TraCIAPI& TraCIAPI::TraCIScopeWrapper::myParent protected inherited
The parent TraCI client which offers the connection.
Definition at line 206 of file TraCIAPI.h.
The documentation for this class was generated from the following files:
TraCIAPI.h
TraCIAPI.cpp