SUMO - Simulation of Urban MObility: MSCFModel_IDM Class Reference
MSCFModel_IDM Class Reference
The Intelligent Driver Model (IDM) car-following model.
#include <MSCFModel_IDM.h>
Data Structures
class VehicleVariables
Public Member Functions
VehicleVariables * createVehicleVariables () const
Returns model specific values which are stored inside a vehicle and must be used with casting.
MSCFModel * duplicate (const MSVehicleType *vtype) const
Duplicates the car-following model.
SUMOReal getMaxAccel () const
Get the vehicle type's maximum acceleration [m/s^2].
SUMOReal getMaxDecel () const
Get the vehicle type's maximum deceleration [m/s^2].
MSCFModel_IDM (const MSVehicleType *vtype, SUMOReal accel, SUMOReal decel, SUMOReal headwayTime, SUMOReal delta, SUMOReal internalStepping)
Constructor.
MSCFModel_IDM (const MSVehicleType *vtype, SUMOReal accel, SUMOReal decel, SUMOReal headwayTime, SUMOReal adaptationFactor, SUMOReal adaptationTime, SUMOReal internalStepping)
Constructor.
~MSCFModel_IDM ()
Destructor.
Implementations of the MSCFModel interface
SUMOReal moveHelper (MSVehicle *const veh, SUMOReal vPos) const
Applies interaction with stops and lane changing model influences.
SUMOReal followSpeed (const MSVehicle *const veh, SUMOReal speed, SUMOReal gap2pred, SUMOReal predSpeed, SUMOReal predMaxDecel) const
Computes the vehicle's safe speed (no dawdling)
SUMOReal stopSpeed (const MSVehicle *const veh, const SUMOReal speed, SUMOReal gap2pred) const
Computes the vehicle's safe speed for approaching a non-moving obstacle (no dawdling)
SUMOReal interactionGap (const MSVehicle *const , SUMOReal vL) const
Returns the maximum gap at which an interaction between both vehicles occurs.
int getModelID () const
Returns the model's name.
Methods to override by model implementation
virtual SUMOReal freeSpeed (const MSVehicle *const veh, SUMOReal speed, SUMOReal seen, SUMOReal maxSpeed, const bool onInsertion=false) const
Computes the vehicle's safe speed without a leader.
virtual SUMOReal insertionFollowSpeed (const MSVehicle *const veh, SUMOReal speed, SUMOReal gap2pred, SUMOReal predSpeed, SUMOReal predMaxDecel) const
Computes the vehicle's safe speed (no dawdling) This method is used during the insertion stage. Whereas the method followSpeed returns the desired speed which may be lower than the safe speed, this method only considers safety constraints.
Virtual methods with default implementation
virtual SUMOReal getImperfection () const
Get the driver's imperfection.
virtual SUMOReal getHeadwayTime () const
Get the driver's reaction time [s].
Setter methods
virtual void setMaxAccel (SUMOReal accel)
Sets a new value for maximum acceleration [m/s^2].
virtual void setMaxDecel (SUMOReal decel)
Sets a new value for maximum deceleration [m/s^2].
virtual void setImperfection (SUMOReal imperfection)
Sets a new value for driver imperfection.
virtual void setHeadwayTime (SUMOReal headwayTime)
Sets a new value for driver reaction time [s].
Protected Member Functions
SUMOReal maximumSafeFollowSpeed (SUMOReal gap, SUMOReal predSpeed, SUMOReal predMaxDecel) const
Returns the maximum safe velocity for following the given leader.
SUMOReal maximumSafeStopSpeed (SUMOReal gap) const
Returns the maximum velocity for stopping within gap This depends stronlgy on the position update model.
Protected Attributes
SUMOReal myAccel
The vehicle's maximum acceleration [m/s^2].
SUMOReal myDecel
The vehicle's maximum deceleration [m/s^2].
SUMOReal myHeadwayTime
The driver's desired time headway (aka reaction time tau) [s].
const MSVehicleType * myType
The type to which this model definition belongs to.
Private Member Functions
SUMOReal _v (const MSVehicle *const veh, const SUMOReal gap2pred, const SUMOReal mySpeed, const SUMOReal predSpeed, const SUMOReal desSpeed, const bool respectMinGap=true) const
MSCFModel_IDM & operator= (const MSCFModel_IDM &s)
Invalidated assignment operator.
Private Attributes
const SUMOReal myAdaptationFactor
The IDMM adaptation factor beta.
const SUMOReal myAdaptationTime
The IDMM adaptation time tau.
const SUMOReal myDelta
The IDM delta exponent.
const int myIterations
The number of iterations in speed calculations.
const SUMOReal myTwoSqrtAccelDecel
A computational shortcut.
Currently fixed methods
virtual SUMOReal maxNextSpeed (SUMOReal speed, const MSVehicle *const veh) const
Returns the maximum speed given the current speed.
SUMOReal brakeGap (const SUMOReal speed) const
Returns the distance the vehicle needs to halt including driver's reaction time.
SUMOReal getSecureGap (const SUMOReal speed, const SUMOReal leaderSpeed, const SUMOReal leaderMaxDecel) const
Returns the minimum gap to reserve if the leader is braking at maximum.
SUMOReal getSpeedAfterMaxDecel (SUMOReal v) const
Returns the velocity after maximum deceleration.
static SUMOReal freeSpeed (const SUMOReal decel, const SUMOReal seen, const SUMOReal maxSpeed, const bool onInsertion)
static SUMOReal brakeGap (const SUMOReal speed, const SUMOReal decel, const SUMOReal headwayTime)
Detailed Description
The Intelligent Driver Model (IDM) car-following model.
See also
MSCFModel
Definition at line 48 of file MSCFModel_IDM.h.
Constructor & Destructor Documentation
MSCFModel_IDM::MSCFModel_IDM (const MSVehicleType * vtype, SUMOReal accel, SUMOReal decel, SUMOReal headwayTime, SUMOReal delta, SUMOReal internalStepping)
Constructor.
Parameters
[in] accel The maximum acceleration
[in] decel The maximum deceleration
[in] headwayTime the headway gap
[in] delta a model constant
[in] internalStepping internal time step size
Definition at line 43 of file MSCFModel_IDM.cpp.
Referenced by duplicate().
MSCFModel_IDM::MSCFModel_IDM (const MSVehicleType * vtype, SUMOReal accel, SUMOReal decel, SUMOReal headwayTime, SUMOReal adaptationFactor, SUMOReal adaptationTime, SUMOReal internalStepping)
Constructor.
Parameters
[in] accel The maximum acceleration
[in] decel The maximum deceleration
[in] headwayTime the headway gap
[in] adaptationFactor a model constant
[in] adaptationTime a model constant
[in] internalStepping internal time step size
Definition at line 54 of file MSCFModel_IDM.cpp.
MSCFModel_IDM::~MSCFModel_IDM ()
Destructor.
Definition at line 66 of file MSCFModel_IDM.cpp.
References SUMOReal.
Member Function Documentation
SUMOReal MSCFModel_IDM::_v (const MSVehicle *const veh, const SUMOReal gap2pred, const SUMOReal mySpeed, const SUMOReal predSpeed, const SUMOReal desSpeed, const bool respectMinGap = true) const private
Definition at line 111 of file MSCFModel_IDM.cpp.
References ACCEL2SPEED, MSVehicle::getCarFollowVariables(), MSVehicleType::getMinGap(), MSCFModel_IDM::VehicleVariables::levelOfService, MAX2(), MSCFModel::myAccel, myAdaptationFactor, myDelta, MSCFModel::myHeadwayTime, myIterations, myTwoSqrtAccelDecel, MSCFModel::myType, SPEED2DIST, and SUMOReal.
Referenced by followSpeed(), and stopSpeed().
SUMOReal MSCFModel::brakeGap (const SUMOReal speed) const inline inherited
Returns the distance the vehicle needs to halt including driver's reaction time.
Parameters
[in] speed The vehicle's current speed
Returns
The distance needed to halt
Definition at line 234 of file MSCFModel.h.
References MSCFModel::myDecel, and MSCFModel::myHeadwayTime.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), MSLane::checkFailure(), MSVehicle::checkRewindLinkLanes(), MSVehicle::executeMove(), MSLane::getCriticalLeader(), MSLane::getLeader(), MSVehicle::getLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLaneChanger::getRealLeader(), MSVehicle::getRerouteOrigin(), MSCFModel::getSecureGap(), MSLCM_JE2013::informLeader(), MSLCM_SL2015::informLeader(), MSLane::isInsertionSuccess(), MSCFModel::maximumSafeFollowSpeed(), MSVehicle::planMoveInternal(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), and MSVehicle::unsafeLinkAhead().
static SUMOReal MSCFModel::brakeGap (const SUMOReal speed, const SUMOReal decel, const SUMOReal headwayTime) inline static inherited
Definition at line 239 of file MSCFModel.h.
References ACCEL2SPEED, SPEED2DIST, and SUMOReal.
VehicleVariables* MSCFModel_IDM::createVehicleVariables () const inline virtual
Returns model specific values which are stored inside a vehicle and must be used with casting.
Reimplemented from MSCFModel.
Definition at line 140 of file MSCFModel_IDM.h.
References myAdaptationFactor.
MSCFModel * MSCFModel_IDM::duplicate (const MSVehicleType * vtype) const virtual
Duplicates the car-following model.
Parameters
[in] vtype The vehicle type this model belongs to (1:1)
Returns
A duplicate of this car-following model
Implements MSCFModel.
Definition at line 140 of file MSCFModel_IDM.cpp.
References MSCFModel_IDM(), MSCFModel::myAccel, MSCFModel::myDecel, myDelta, MSCFModel::myHeadwayTime, myIterations, and TS.
Referenced by getModelID().
SUMOReal MSCFModel_IDM::followSpeed (const MSVehicle *const veh, SUMOReal speed, SUMOReal gap2pred, SUMOReal predSpeed, SUMOReal predMaxDecel) const virtual
Computes the vehicle's safe speed (no dawdling)
Parameters
[in] veh The vehicle (EGO)
[in] speed The vehicle's speed
[in] gap2pred The (netto) distance to the LEADER
[in] predSpeed The speed of LEADER
Returns
EGO's safe speed
See also
MSCFModel::ffeV
Implements MSCFModel.
Definition at line 81 of file MSCFModel_IDM.cpp.
References _v(), MSVehicle::getLane(), MSLane::getVehicleMaxSpeed(), and SUMOReal.
SUMOReal MSCFModel::freeSpeed (const MSVehicle *const veh, SUMOReal speed, SUMOReal seen, SUMOReal maxSpeed, const bool onInsertion = false) const virtual inherited
Computes the vehicle's safe speed without a leader.
Returns the velocity of the vehicle in dependence to the length of the free street and the target velocity at the end of the free range. If onInsertion is true, the vehicle may still brake before the next movement.
Parameters
[in] veh The vehicle (EGO)
[in] speed The vehicle's speed
[in] seen The look ahead distance
[in] maxSpeed The maximum allowed speed
[in] onInsertion whether speed at insertion is asked for
Returns
EGO's safe speed
Definition at line 95 of file MSCFModel.cpp.
References MSCFModel::myDecel, and SUMOReal.
Referenced by MSLane::isInsertionSuccess(), and MSVehicle::planMoveInternal().
static SUMOReal MSCFModel::freeSpeed (const SUMOReal decel, const SUMOReal seen, const SUMOReal maxSpeed, const bool onInsertion) inline static inherited
Definition at line 248 of file MSCFModel.h.
References ACCEL2DIST, ACCEL2SPEED, DIST2SPEED, MAX2(), SPEED2DIST, and SUMOReal.
virtual SUMOReal MSCFModel::getHeadwayTime () const inline virtual inherited
Get the driver's reaction time [s].
Returns
The reaction time of this class' drivers in s
Definition at line 205 of file MSCFModel.h.
References MSCFModel::maxNextSpeed(), MSCFModel::myHeadwayTime, and SUMOReal.
Referenced by MSVehicle::checkRewindLinkLanes(), MSVehicle::executeMove(), TraCIServerAPI_VehicleType::getVariable(), MSVehicle::planMoveInternal(), and MSCalibrator::remainingVehicleCapacity().
virtual SUMOReal MSCFModel::getImperfection () const inline virtual inherited
Get the driver's imperfection.
Returns
The imperfection of drivers of this class
Reimplemented in MSCFModel_KraussOrig1, MSCFModel_PWag2009, MSCFModel_SmartSK, and MSCFModel_Daniel1.
Definition at line 197 of file MSCFModel.h.
Referenced by TraCIServerAPI_VehicleType::getVariable().
SUMOReal MSCFModel::getMaxAccel () const inline inherited
Get the vehicle type's maximum acceleration [m/s^2].
Returns
The maximum acceleration (in m/s^2) of vehicles of this class
Definition at line 178 of file MSCFModel.h.
References MSCFModel::myAccel.
Referenced by MSLCM_JE2013::_wantsChange(), MSLaneChanger::computeOvertakingTime(), MEVehicle::estimateLeaveSpeed(), MSVehicle::estimateLeaveSpeed(), TraCIServerAPI_VehicleType::getVariable(), MSCFModel_KraussPS::maxNextSpeed(), MSCFModel::maxNextSpeed(), MSVehicle::planMoveInternal(), and MSMeanData_Emissions::MSLaneMeanDataValues::write().
SUMOReal MSCFModel::getMaxDecel () const inline inherited
Get the vehicle type's maximum deceleration [m/s^2].
Returns
The maximum deceleration (in m/s^2) of vehicles of this class
Definition at line 186 of file MSCFModel.h.
References MSCFModel::myDecel.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSCriticalFollowerDistanceInfo::addFollower(), MSLink::blockedByFoe(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), MSVehicle::checkRewindLinkLanes(), MSLCM_SL2015::checkStrategicChange(), MSLink::couldBrakeForLeader(), MSVehicle::executeMove(), MSLane::freeInsertion(), MSLane::getCriticalLeader(), MSLane::getFollower(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLaneChanger::getRealFollower(), TraCIServerAPI_VehicleType::getVariable(), MSLink::getZipperSpeed(), MSLCM_DK2008::informBlocker(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLane::isInsertionSuccess(), MESegment::isOpen(), MSLane::lastInsertion(), MSLink::maybeOccupied(), MSVehicle::planMoveInternal(), MSLane::safeInsertionSpeed(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), GUIVehicle::selectBlockingFoes(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSVehicleControl::vehicleDeparted(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
int MSCFModel_IDM::getModelID () const inline virtual
Returns the model's name.
Returns
The model's name
See also
MSCFModel::getModelName
Implements MSCFModel.
Definition at line 126 of file MSCFModel_IDM.h.
References duplicate(), myAdaptationFactor, SUMO_TAG_CF_IDM, and SUMO_TAG_CF_IDMM.
SUMOReal MSCFModel::getSecureGap (const SUMOReal speed, const SUMOReal leaderSpeed, const SUMOReal leaderMaxDecel) const inline inherited
Returns the minimum gap to reserve if the leader is braking at maximum.
Parameters
[in] speed EGO's speed
[in] leaderSpeed LEADER's speed
[in] leaderMaxDecel LEADER's max. deceleration rate
Definition at line 272 of file MSCFModel.h.
References MSCFModel::brakeGap(), MAX2(), MIN2(), MSCFModel::myDecel, MSCFModel::myHeadwayTime, and SUMOReal.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSCriticalFollowerDistanceInfo::addFollower(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlockingVehicles(), MSLaneChanger::checkChange(), MSLane::freeInsertion(), MSLane::getMissingRearGap(), MSLCM_DK2008::informBlocker(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLane::isInsertionSuccess(), and MSLane::lastInsertion().
SUMOReal MSCFModel::getSpeedAfterMaxDecel (SUMOReal v) const inline inherited
Returns the velocity after maximum deceleration.
Parameters
[in] v The velocity
Returns
The velocity after maximum deceleration
Definition at line 285 of file MSCFModel.h.
References ACCEL2SPEED, MAX2(), MSCFModel::myDecel, and SUMOReal.
Referenced by MSCFModel_SmartSK::followSpeed(), MSCFModel_Daniel1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel::moveHelper(), MSVehicle::planMoveInternal(), MSCFModel_SmartSK::stopSpeed(), and MSCFModel_Wiedemann::stopSpeed().
SUMOReal MSCFModel::insertionFollowSpeed (const MSVehicle *const veh, SUMOReal speed, SUMOReal gap2pred, SUMOReal predSpeed, SUMOReal predMaxDecel) const virtual inherited
Computes the vehicle's safe speed (no dawdling) This method is used during the insertion stage. Whereas the method followSpeed returns the desired speed which may be lower than the safe speed, this method only considers safety constraints.
Returns the velocity of the vehicle in dependence to the vehicle's and its leader's values and the distance between them.
Parameters
[in] veh The vehicle (EGO)
[in] speed The vehicle's speed
[in] gap2pred The (netto) distance to the LEADER
[in] predSpeed The speed of LEADER
Returns
EGO's safe speed
Reimplemented in MSCFModel_KraussOrig1.
Definition at line 101 of file MSCFModel.cpp.
References MSCFModel::maximumSafeFollowSpeed(), and SUMOReal.
Referenced by MSLane::freeInsertion(), MSLane::getCriticalLeader(), MSLane::isInsertionSuccess(), and MSLane::safeInsertionSpeed().
SUMOReal MSCFModel_IDM::interactionGap (const MSVehicle * const veh, SUMOReal vL) const virtual
Returns the maximum gap at which an interaction between both vehicles occurs.
"interaction" means that the LEADER influences EGO's speed.
Parameters
[in] veh The EGO vehicle
[in] vL LEADER's speed
Returns
The interaction gap
Todo:
evaluate signature
See also
MSCFModel::interactionGap
Todo:
update interactionGap logic to IDM
Reimplemented from MSCFModel.
Definition at line 97 of file MSCFModel_IDM.cpp.
References MSVehicle::getLane(), MSVehicle::getSpeed(), MSLane::getVehicleMaxSpeed(), MAX2(), MSCFModel::myAccel, MSCFModel::myDecel, myDelta, SPEED2DIST, and SUMOReal.
SUMOReal MSCFModel::maximumSafeFollowSpeed (SUMOReal gap, SUMOReal predSpeed, SUMOReal predMaxDecel) const protected inherited
Returns the maximum safe velocity for following the given leader.
Parameters
[in] gap2pred The (netto) distance to the LEADER
[in] predSpeed The LEADER's speed
[in] predMaxDecel The LEADER's maximum deceleration
Returns
the safe velocity
Returns the SK-vsafe.
Definition at line 138 of file MSCFModel.cpp.
References MSCFModel::brakeGap(), ISNAN(), MAX2(), MSCFModel::maximumSafeStopSpeed(), MSCFModel::myDecel, and SUMOReal.
Referenced by MSCFModel_Krauss::followSpeed(), MSCFModel::insertionFollowSpeed(), and MSCFModel::setHeadwayTime().
SUMOReal MSCFModel::maximumSafeStopSpeed (SUMOReal gap) const protected inherited
Returns the maximum velocity for stopping within gap This depends stronlgy on the position update model.
Parameters
[in] gap The (netto) distance to the LEADER
Definition at line 108 of file MSCFModel.cpp.
References ACCEL2SPEED, DIST2SPEED, MIN2(), MSCFModel::myDecel, MSCFModel::myHeadwayTime, NUMERICAL_EPS, SUMOReal, and TS.
Referenced by MSCFModel::maximumSafeFollowSpeed(), MSCFModel::setHeadwayTime(), and MSCFModel_Krauss::stopSpeed().
SUMOReal MSCFModel::maxNextSpeed (SUMOReal speed, const MSVehicle *const veh) const virtual inherited
Returns the maximum speed given the current speed.
The implementation of this method must take into account the time step duration.
Justification: Due to air brake or other influences, the vehicle's next maximum speed may depend on the vehicle's current speed (given).
Parameters
[in] speed The vehicle's current speed
[in] speed The vehicle itself, for obtaining other values
Returns
The maximum possible speed for the next step
Reimplemented in MSCFModel_KraussPS.
Definition at line 89 of file MSCFModel.cpp.
References ACCEL2SPEED, MSCFModel::getMaxAccel(), MSVehicleType::getMaxSpeed(), MIN2(), MSCFModel::myType, and SUMOReal.
Referenced by MSVehicle::executeMove(), MSCFModel_Kerner::followSpeed(), MSCFModel_Daniel1::followSpeed(), MSCFModel_KraussOrig1::followSpeed(), MSCFModel_SmartSK::followSpeed(), MSCFModel_Krauss::followSpeed(), MSCFModel::getHeadwayTime(), MSCFModel::interactionGap(), MSCFModel_Daniel1::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel::moveHelper(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSCFModel_Krauss::stopSpeed(), MSCFModel_Kerner::stopSpeed(), MSCFModel_Daniel1::stopSpeed(), MSCFModel_KraussOrig1::stopSpeed(), MSCFModel_SmartSK::stopSpeed(), and MSCFModel_Wiedemann::stopSpeed().
SUMOReal MSCFModel_IDM::moveHelper (MSVehicle *const veh, SUMOReal vPos) const virtual
Applies interaction with stops and lane changing model influences.
Parameters
[in] veh The ego vehicle
[in] vPos The possible velocity
Returns
The velocity after applying interactions with stops and lane change model influences
Reimplemented from MSCFModel.
Definition at line 70 of file MSCFModel_IDM.cpp.
References MSVehicle::getCarFollowVariables(), MSVehicle::getLane(), MSLane::getVehicleMaxSpeed(), MSCFModel_IDM::VehicleVariables::levelOfService, MSCFModel::moveHelper(), myAdaptationFactor, myAdaptationTime, SUMOReal, and TS.
MSCFModel_IDM& MSCFModel_IDM::operator= (const MSCFModel_IDM & s) private
Invalidated assignment operator.
virtual void MSCFModel::setHeadwayTime (SUMOReal headwayTime) inline virtual inherited
Sets a new value for driver reaction time [s].
Parameters
[in] headwayTime The new driver reaction time (in s)
Reimplemented in MSCFModel_KraussOrig1, MSCFModel_SmartSK, and MSCFModel_Daniel1.
Definition at line 321 of file MSCFModel.h.
References MSCFModel::maximumSafeFollowSpeed(), MSCFModel::maximumSafeStopSpeed(), MSCFModel::myHeadwayTime, and SUMOReal.
Referenced by TraCIServerAPI_VehicleType::setVariable().
virtual void MSCFModel::setImperfection (SUMOReal imperfection) inline virtual inherited
Sets a new value for driver imperfection.
Parameters
[in] accel The new driver imperfection
Reimplemented in MSCFModel_KraussOrig1, MSCFModel_SmartSK, and MSCFModel_Daniel1.
Definition at line 313 of file MSCFModel.h.
References UNUSED_PARAMETER.
Referenced by TraCIServerAPI_VehicleType::setVariable().
virtual void MSCFModel::setMaxAccel (SUMOReal accel) inline virtual inherited
Sets a new value for maximum acceleration [m/s^2].
Parameters
[in] accel The new acceleration in m/s^2
Definition at line 297 of file MSCFModel.h.
References MSCFModel::myAccel.
Referenced by TraCIServerAPI_VehicleType::setVariable().
virtual void MSCFModel::setMaxDecel (SUMOReal decel) inline virtual inherited
Sets a new value for maximum deceleration [m/s^2].
Parameters
[in] accel The new deceleration in m/s^2
Reimplemented in MSCFModel_KraussOrig1, MSCFModel_SmartSK, and MSCFModel_Daniel1.
Definition at line 305 of file MSCFModel.h.
References MSCFModel::myDecel.
Referenced by TraCIServerAPI_VehicleType::setVariable().
SUMOReal MSCFModel_IDM::stopSpeed (const MSVehicle *const veh, const SUMOReal speed, SUMOReal gap2pred) const virtual
Computes the vehicle's safe speed for approaching a non-moving obstacle (no dawdling)
Parameters
[in] veh The vehicle (EGO)
[in] gap2pred The (netto) distance to the the obstacle
Returns
EGO's safe speed for approaching a non-moving obstacle
See also
MSCFModel::ffeS
Todo:
generic Interface, models can call for the values they need
Implements MSCFModel.
Definition at line 87 of file MSCFModel_IDM.cpp.
References _v(), MSVehicle::getLane(), MSLane::getVehicleMaxSpeed(), and SUMOReal.
Field Documentation
SUMOReal MSCFModel::myAccel protected inherited
The vehicle's maximum acceleration [m/s^2].
Definition at line 347 of file MSCFModel.h.
Referenced by MSCFModel_Kerner::_v(), MSCFModel_Wiedemann::_v(), _v(), MSCFModel_Krauss::dawdle(), MSCFModel_Daniel1::dawdle(), MSCFModel_SmartSK::dawdle(), MSCFModel_KraussOrig1::dawdle(), MSCFModel_KraussPS::duplicate(), MSCFModel_Krauss::duplicate(), MSCFModel_Kerner::duplicate(), MSCFModel_PWag2009::duplicate(), MSCFModel_Wiedemann::duplicate(), duplicate(), MSCFModel_Daniel1::duplicate(), MSCFModel_SmartSK::duplicate(), MSCFModel_KraussOrig1::duplicate(), MSCFModel_PWag2009::followSpeed(), MSCFModel_Wiedemann::fullspeed(), MSCFModel::getMaxAccel(), interactionGap(), MSCFModel_SmartSK::MSCFModel_SmartSK(), MSCFModel::setMaxAccel(), and MSCFModel_PWag2009::stopSpeed().
const SUMOReal MSCFModel_IDM::myAdaptationFactor private
The IDMM adaptation factor beta.
Definition at line 167 of file MSCFModel_IDM.h.
Referenced by _v(), createVehicleVariables(), getModelID(), and moveHelper().
const SUMOReal MSCFModel_IDM::myAdaptationTime private
The IDMM adaptation time tau.
Definition at line 170 of file MSCFModel_IDM.h.
Referenced by moveHelper().
SUMOReal MSCFModel::myDecel protected inherited
The vehicle's maximum deceleration [m/s^2].
Definition at line 350 of file MSCFModel.h.
Referenced by MSCFModel_Kerner::_v(), MSCFModel_Wiedemann::_v(), MSCFModel_Daniel1::_vsafe(), MSCFModel_SmartSK::_vsafe(), MSCFModel::brakeGap(), MSCFModel_KraussPS::duplicate(), MSCFModel_Krauss::duplicate(), MSCFModel_Kerner::duplicate(), MSCFModel_PWag2009::duplicate(), MSCFModel_Wiedemann::duplicate(), duplicate(), MSCFModel_Daniel1::duplicate(), MSCFModel_SmartSK::duplicate(), MSCFModel_KraussOrig1::duplicate(), MSCFModel_Wiedemann::emergency(), MSCFModel_PWag2009::followSpeed(), MSCFModel::freeSpeed(), MSCFModel::getMaxDecel(), MSCFModel::getSecureGap(), MSCFModel::getSpeedAfterMaxDecel(), interactionGap(), MSCFModel::interactionGap(), MSCFModel_Wiedemann::krauss_vsafe(), MSCFModel::maximumSafeFollowSpeed(), MSCFModel::maximumSafeStopSpeed(), MSCFModel_SmartSK::MSCFModel_SmartSK(), MSCFModel_Daniel1::setHeadwayTime(), MSCFModel_SmartSK::setHeadwayTime(), MSCFModel_KraussOrig1::setHeadwayTime(), MSCFModel_Daniel1::setMaxDecel(), MSCFModel_SmartSK::setMaxDecel(), MSCFModel_KraussOrig1::setMaxDecel(), MSCFModel::setMaxDecel(), MSCFModel_PWag2009::stopSpeed(), and MSCFModel_KraussOrig1::vsafe().
const SUMOReal MSCFModel_IDM::myDelta private
The IDM delta exponent.
Definition at line 164 of file MSCFModel_IDM.h.
Referenced by _v(), duplicate(), and interactionGap().
SUMOReal MSCFModel::myHeadwayTime protected inherited
The driver's desired time headway (aka reaction time tau) [s].
Definition at line 353 of file MSCFModel.h.
Referenced by _v(), MSCFModel::brakeGap(), MSCFModel_SmartSK::createVehicleVariables(), MSCFModel_KraussPS::duplicate(), MSCFModel_Krauss::duplicate(), MSCFModel_Kerner::duplicate(), MSCFModel_PWag2009::duplicate(), duplicate(), MSCFModel_Daniel1::duplicate(), MSCFModel_SmartSK::duplicate(), MSCFModel_KraussOrig1::duplicate(), MSCFModel_PWag2009::followSpeed(), MSCFModel::getHeadwayTime(), MSCFModel::getSecureGap(), MSCFModel::interactionGap(), MSCFModel_Wiedemann::krauss_vsafe(), MSCFModel::maximumSafeStopSpeed(), MSCFModel_Daniel1::setHeadwayTime(), MSCFModel_SmartSK::setHeadwayTime(), MSCFModel_KraussOrig1::setHeadwayTime(), MSCFModel::setHeadwayTime(), MSCFModel_Daniel1::setMaxDecel(), MSCFModel_SmartSK::setMaxDecel(), MSCFModel_KraussOrig1::setMaxDecel(), MSCFModel_PWag2009::stopSpeed(), and MSCFModel_SmartSK::updateMyHeadway().
const int MSCFModel_IDM::myIterations private
The number of iterations in speed calculations.
Definition at line 173 of file MSCFModel_IDM.h.
Referenced by _v(), and duplicate().
const SUMOReal MSCFModel_IDM::myTwoSqrtAccelDecel private
A computational shortcut.
Definition at line 176 of file MSCFModel_IDM.h.
Referenced by _v().
const MSVehicleType* MSCFModel::myType protected inherited
The type to which this model definition belongs to.
Definition at line 344 of file MSCFModel.h.
Referenced by MSCFModel_Wiedemann::_v(), _v(), MSCFModel_KraussPS::maxNextSpeed(), and MSCFModel::maxNextSpeed().
The documentation for this class was generated from the following files:
MSCFModel_IDM.h
MSCFModel_IDM.cpp