SUMO - Simulation of Urban MObility: NLHandler Class Reference
NLHandler Class Reference
The XML-Handler for network loading.
#include <NLHandler.h>
Public Types
typedef std::vector< MSLane * > LaneVector
Definition of a lane vector.
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
SUMOTime getFirstDepart () const
returns the first departure time that was ever read
SUMOTime getLastDepart () const
Returns the last loaded depart time.
bool haveSeenInternalEdge () const
bool haveSeenNeighs () const
bool lefthand () const
SUMOReal networkVersion () const
NLHandler (const std::string &file, MSNet &net, NLDetectorBuilder &detBuilder, NLTriggerBuilder &triggerBuilder, NLEdgeControlBuilder &edgeBuilder, NLJunctionControlBuilder &junctionBuilder)
Constructor.
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
virtual ~NLHandler ()
Destructor.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Static Public Member Functions
static bool checkStopPos (SUMOReal &startPos, SUMOReal &endPos, const SUMOReal laneLength, const SUMOReal minLength, const bool friendlyPos)
check start and end position of a stop
static MTRand * getParsingRNG ()
Protected Types
typedef std::map< std::string, std::pair< std::string, std::string > > JunctionGraph
temporary data for building the junction graph after network parsing is finished
Protected Member Functions
virtual void addE1Detector (const SUMOSAXAttributes &attrs)
Builds an e1 detector using the given specification.
virtual void addE2Detector (const SUMOSAXAttributes &attrs)
Builds an e2 detector using the given specification.
void addE3Entry (const SUMOSAXAttributes &attrs)
Adds an entry to the currently processed e3 detector.
void addE3Exit (const SUMOSAXAttributes &attrs)
Adds an exit to the currently processed e3 detector.
virtual void addEdgeLaneMeanData (const SUMOSAXAttributes &attrs, int objecttype)
Builds edge or lane base mean data collector using the given specification.
virtual void addInstantE1Detector (const SUMOSAXAttributes &attrs)
Builds an e1 detector using the given specification.
void addParam (const SUMOSAXAttributes &attrs)
virtual void addRouteProbeDetector (const SUMOSAXAttributes &attrs)
Builds a routeProbe-detector using the given specification.
void addStop (const SUMOSAXAttributes &attrs)
Processing of a stop.
virtual void addVTypeProbeDetector (const SUMOSAXAttributes &attrs)
Builds a vtype-detector using the given specification.
void beginE3Detector (const SUMOSAXAttributes &attrs)
Starts building of an e3 detector using the given specification.
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
bool checkLastDepart ()
Checks whether the route file is sorted by departure time if needed.
void closeContainer ()
Ends the processing of a container.
virtual void closeEdge ()
Closes the process of building an edge.
void closeFlow ()
Ends the processing of a flow.
void closePerson ()
Ends the processing of a person.
void closeRoute (const bool mayBeDisconnected=false)
void closeRouteDistribution ()
void closeVehicle ()
Ends the processing of a vehicle.
void closeVehicleTypeDistribution ()
virtual void endE3Detector ()
Builds of an e3 detector using collected values.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
void openRoute (const SUMOSAXAttributes &attrs)
void openRouteDistribution (const SUMOSAXAttributes &attrs)
void openVehicleTypeDistribution (const SUMOSAXAttributes &attrs)
void parseFromViaTo (std::string element, const SUMOSAXAttributes &attrs)
Called for parsing from and to and the corresponding taz attributes.
bool parseStop (SUMOVehicleParameter::Stop &stop, const SUMOSAXAttributes &attrs, std::string errorSuffix, MsgHandler *const errorOutput)
parses attributes common to all stops
SUMOReal parseWalkPos (SumoXMLAttr attr, const std::string &id, const MSEdge *edge, const std::string &val)
void parseWalkPositions (const SUMOSAXAttributes &attrs, const std::string &personID, const MSEdge *fromEdge, const MSEdge *&toEdge, SUMOReal &departPos, SUMOReal &arrivalPos, MSStoppingPlace *&bs, bool &ok)
@ brief parse depart- and arrival positions of a walk
void registerLastDepart ()
save last depart (only to be used if vehicle is not discarded)
inherited from GenericSAXHandler
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
virtual void myEndElement (int element)
Called when a closing tag occurs.
Protected Attributes
NLDiscreteEventBuilder myActionBuilder
A builder for object actions.
MSTransportable::MSTransportablePlan * myActiveContainerPlan
The plan of the current container.
MSTransportable::MSTransportablePlan * myActivePlan
The plan of the current person.
ConstMSEdgeVector myActiveRoute
The current route.
const RGBColor * myActiveRouteColor
The currently parsed route's color.
std::string myActiveRouteID
The id of the current route.
SUMOReal myActiveRouteProbability
The probability of the current route.
std::string myActiveRouteRefID
The id of the route the current route references to.
std::vector< SUMOVehicleParameter::Stop > myActiveRouteStops
List of the stops on the parsed route.
bool myAddVehiclesDirectly
Information whether vehicles shall be directly added to the network or kept within the buffer.
bool myAmInTLLogicMode
internal information whether a tls-logic is currently read
SUMOTime myBeginDefault
The default value for flow begins.
Boundary myConvBoundary
SUMOReal myCurrentCosts
The currently parsed route costs.
std::string myCurrentDistrictID
The id of the current district.
bool myCurrentIsBroken
bool myCurrentIsInternalToSkip
Information whether the currently parsed edge is internal and not wished, here.
RandomDistributor< const MSRoute * > * myCurrentRouteDistribution
The currently parsed distribution of routes (probability->route)
std::string myCurrentRouteDistributionID
The id of the currently parsed route distribution.
std::string myCurrentTypeID
The id of the currently processed edge type.
SUMOVTypeParameter * myCurrentVType
The currently parsed vehicle type.
RandomDistributor< MSVehicleType * > * myCurrentVTypeDistribution
The currently parsed distribution of vehicle types (probability->vehicle type)
std::string myCurrentVTypeDistributionID
The id of the currently parsed vehicle type distribution.
std::string myCurrentWAUTID
The id of the currently processed WAUT.
NLDetectorBuilder & myDetectorBuilder
The detector builder to use.
NLEdgeControlBuilder & myEdgeControlBuilder
The edge builder to use.
SUMOTime myEndDefault
The default value for flow ends.
SUMOTime myFirstDepart
the first read departure time
bool myHaveSeenInternalEdge
whether the loaded network contains internal lanes
bool myHaveSeenNeighs
whether the loaded network contains explicit neighbor lanes
bool myHaveWarnedAboutDeprecatedLanes
IDSupplier myIdSupplier
generates numerical ids
int myInsertStopEdgesAt
where stop edges can be inserted into the current route (-1 means no insertion)
NLJunctionControlBuilder & myJunctionControlBuilder
The junction builder to use.
JunctionGraph myJunctionGraph
SUMOTime myLastDepart
The insertion time of the vehicle read last.
Parameterised * myLastParameterised
bool myLefthand
whether the loaded network was built for left hand traffic
MSNet & myNet
The net to fill (preinitialised)
bool myNetIsLoaded
whether the location element was already loadee
Position myNetworkOffset
The network offset.
SUMOReal myNetworkVersion
the loaded network version
Boundary myOrigBoundary
The network's boundaries.
NLTriggerBuilder & myTriggerBuilder
The trigger builder to use.
SUMOVehicleParameter * myVehicleParameter
Parameter of the current vehicle, trip, person, container or flow.
Static Protected Attributes
static MTRand myParsingRNG
A random number generator used to choose from vtype/route distributions and computing the speed factors.
Private Member Functions
void addConnection (const SUMOSAXAttributes &attrs)
adds a connection
void addDistrict (const SUMOSAXAttributes &attrs)
void addDistrictEdge (const SUMOSAXAttributes &attrs, bool isSource)
void addLane (const SUMOSAXAttributes &attrs)
adds a lane to the previously opened edge
void addPhase (const SUMOSAXAttributes &attrs)
adds a phase to the traffic lights logic currently build
void addPOI (const SUMOSAXAttributes &attrs)
adds a polygon
void addPoly (const SUMOSAXAttributes &attrs)
adds a polygon
void addRequest (const SUMOSAXAttributes &attrs)
adds a request item to the current junction logic
void addRoundabout (const SUMOSAXAttributes &attrs)
void addWAUTJunction (const SUMOSAXAttributes &attrs)
void addWAUTSwitch (const SUMOSAXAttributes &attrs)
void beginEdgeParsing (const SUMOSAXAttributes &attrs)
begins the processing of an edge
void closeWAUT ()
void initJunctionLogic (const SUMOSAXAttributes &attrs)
begins the reading of a junction row logic
void initTrafficLightLogic (const SUMOSAXAttributes &attrs)
begins the reading of a traffic lights logic
NLHandler (const NLHandler &s)
virtual void openJunction (const SUMOSAXAttributes &attrs)
opens a junction for processing
virtual void openWAUT (const SUMOSAXAttributes &attrs)
NLHandler & operator= (const NLHandler &s)
void parseLanes (const std::string &junctionID, const std::string &def, std::vector< MSLane * > &into, bool &ok)
LinkDirection parseLinkDir (const std::string &dir)
Parses the given character into an enumeration typed link direction.
LinkState parseLinkState (const std::string &state)
Parses the given character into an enumeration typed link state.
void setLocation (const SUMOSAXAttributes &attrs)
Parses network location description.
Detailed Description
The XML-Handler for network loading.
The SAX2-handler responsible for parsing networks and routes to load. This is an extension of the MSRouteHandler as routes and vehicles may also be loaded from network descriptions.
Definition at line 84 of file NLHandler.h.
Member Typedef Documentation
typedef std::map<std::string, std::pair<std::string, std::string> > NLHandler::JunctionGraph protected
temporary data for building the junction graph after network parsing is finished
Definition at line 352 of file NLHandler.h.
typedef std::vector<MSLane*> NLHandler::LaneVector
Definition of a lane vector.
Definition at line 87 of file NLHandler.h.
Constructor & Destructor Documentation
NLHandler::NLHandler (const std::string & file, MSNet & net, NLDetectorBuilder & detBuilder, NLTriggerBuilder & triggerBuilder, NLEdgeControlBuilder & edgeBuilder, NLJunctionControlBuilder & junctionBuilder)
Constructor.
Parameters
[in] file Name of the parsed file
[in,out] net The network to fill
[in] detBuilder The detector builder to use
[in] triggerBuilder The trigger builder to use
[in] edgeBuilder The builder of edges to use
[in] junctionBuilder The builder of junctions to use
Definition at line 68 of file NLHandler.cpp.
NLHandler::~NLHandler () virtual
Destructor.
Definition at line 89 of file NLHandler.cpp.
NLHandler::NLHandler (const NLHandler & s) private
invalid copy constructor
Member Function Documentation
void NLHandler::addConnection (const SUMOSAXAttributes & attrs) private
adds a connection
Definition at line 998 of file NLHandler.cpp.
References MSLane::addApproachingLane(), MSLane::addIncomingLane(), MSTLLogicControl::TLSLogicVariants::addLink(), MSLane::addLink(), MSLane::dictionary(), MSEdge::dictionary(), SUMOSAXAttributes::get(), MSTLLogicControl::TLSLogicVariants::getActive(), Named::getID(), MSEdge::getLanes(), MSLane::getLength(), SUMOSAXAttributes::getOpt(), MSLane::getShape(), NLJunctionControlBuilder::getTLLogic(), MSGlobals::gUsingInternalLanes, myJunctionControlBuilder, myNetworkVersion, parseLinkDir(), parseLinkState(), SUMO_ATTR_DIR, SUMO_ATTR_FROM, SUMO_ATTR_FROM_LANE, SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_STATE, SUMO_ATTR_TLID, SUMO_ATTR_TLLINKINDEX, SUMO_ATTR_TO, SUMO_ATTR_TO_LANE, SUMO_ATTR_VIA, SUMOReal, toString(), and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addDistrict (const SUMOSAXAttributes & attrs) private
Parses a district and creates a pseudo edge for it
Called on the occurence of a "district" element, this method retrieves the id of the district and creates a district type edge with this id.
Parameters
[in] attrs The attributes (of the "district"-element) to parse
Exceptions
ProcessError If an edge given in district is not known
Definition at line 1145 of file NLHandler.cpp.
References ShapeContainer::addPolygon(), MSEdge::addSuccessor(), NLEdgeControlBuilder::buildEdge(), MSEdge::dictionary(), MSEdge::EDGEFUNCTION_DISTRICT, SUMOSAXAttributes::get(), MSNet::getShapeContainer(), SUMOSAXAttributes::getStringVector(), SUMOSAXAttributes::hasAttribute(), MSEdge::initialize(), myCurrentDistrictID, myCurrentIsBroken, myEdgeControlBuilder, myNet, RGBColor::parseColor(), SUMO_ATTR_EDGES, SUMO_ATTR_ID, SUMO_ATTR_SHAPE, WRITE_ERROR, and WRITE_WARNING.
Referenced by myStartElement().
void NLHandler::addDistrictEdge (const SUMOSAXAttributes & attrs, bool isSource) private
Parses a district edge and connects it to the district
Called on the occurence of a "dsource" or "dsink" element, this method retrieves the id of the approachable edge. If this edge is known and valid, the approaching edge is informed about it.
Parameters
[in] attrs The attributes to parse
[in] isSource whether a "dsource or a "dsink" was given
Todo:
No exception?
Definition at line 1195 of file NLHandler.cpp.
References MSEdge::dictionary(), SUMOSAXAttributes::get(), myCurrentDistrictID, myCurrentIsBroken, SUMO_ATTR_ID, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addE1Detector (const SUMOSAXAttributes & attrs) protected virtual
Builds an e1 detector using the given specification.
Parameters
[in] attrs The attributes that define the detector
Definition at line 764 of file NLHandler.cpp.
References NLDetectorBuilder::buildInductLoop(), FileHelpers::checkForRelativity(), SUMOSAXAttributes::get(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getSUMOTimeReporting(), myDetectorBuilder, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_SPLIT_VTYPE, SUMOReal, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addE2Detector (const SUMOSAXAttributes & attrs) protected virtual
Builds an e2 detector using the given specification.
Parameters
[in] attrs The attributes that define the detector
Definition at line 861 of file NLHandler.cpp.
References NLDetectorBuilder::buildE2Detector(), FileHelpers::checkForRelativity(), SUMOSAXAttributes::get(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getSUMOTimeReporting(), NLJunctionControlBuilder::getTLLogic(), myDetectorBuilder, myJunctionControlBuilder, SUMO_ATTR_CONT, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_JAM_DIST_THRESHOLD, SUMO_ATTR_LANE, SUMO_ATTR_LENGTH, SUMO_ATTR_POSITION, SUMO_ATTR_TLID, SUMO_ATTR_TO, SUMOReal, TIME2STEPS, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addE3Entry (const SUMOSAXAttributes & attrs) protected
Adds an entry to the currently processed e3 detector.
Parameters
[in] attrs The attributes that define the entry
Definition at line 937 of file NLHandler.cpp.
References NLDetectorBuilder::addE3Entry(), SUMOSAXAttributes::get(), NLDetectorBuilder::getCurrentE3ID(), SUMOSAXAttributes::getOpt(), myDetectorBuilder, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, and SUMOReal.
Referenced by myStartElement().
void NLHandler::addE3Exit (const SUMOSAXAttributes & attrs) protected
Adds an exit to the currently processed e3 detector.
Parameters
[in] attrs The attributes that define the exit
Definition at line 950 of file NLHandler.cpp.
References NLDetectorBuilder::addE3Exit(), SUMOSAXAttributes::get(), NLDetectorBuilder::getCurrentE3ID(), SUMOSAXAttributes::getOpt(), myDetectorBuilder, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, and SUMOReal.
Referenced by myStartElement().
void NLHandler::addEdgeLaneMeanData (const SUMOSAXAttributes & attrs, int objecttype) protected virtual
Builds edge or lane base mean data collector using the given specification.
Parameters
[in] attrs The attributes that define the detector
[in] objecttype The type (lane/edge) of the parsed mean data definition
Definition at line 963 of file NLHandler.cpp.
References FileHelpers::checkForRelativity(), NLDetectorBuilder::createEdgeLaneMeanData(), SUMOSAXAttributes::get(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOpt(), OptionsCont::getOptions(), SUMOSAXAttributes::getOptSUMOTimeReporting(), myDetectorBuilder, POSITION_EPS, string2time(), SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_ATTR_EXCLUDE_EMPTY, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_ID, SUMO_ATTR_MAX_TRAVELTIME, SUMO_ATTR_MIN_SAMPLES, SUMO_ATTR_TRACK_VEHICLES, SUMO_ATTR_TYPE, SUMO_ATTR_VTYPES, SUMO_ATTR_WITH_INTERNAL, SUMO_TAG_MEANDATA_LANE, SUMOReal, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addInstantE1Detector (const SUMOSAXAttributes & attrs) protected virtual
Builds an e1 detector using the given specification.
Parameters
[in] attrs The attributes that define the detector
Definition at line 793 of file NLHandler.cpp.
References NLDetectorBuilder::buildInstantInductLoop(), FileHelpers::checkForRelativity(), SUMOSAXAttributes::get(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOpt(), myDetectorBuilder, SUMO_ATTR_FILE, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMOReal, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addLane (const SUMOSAXAttributes & attrs) private
adds a lane to the previously opened edge
Definition at line 402 of file NLHandler.cpp.
References NLEdgeControlBuilder::addLane(), MSLane::dictionary(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), myCurrentIsBroken, myCurrentIsInternalToSkip, myEdgeControlBuilder, myLastParameterised, myNet, parseVehicleClasses(), MSNet::setPermissionsFound(), SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMO_ATTR_ID, SUMO_ATTR_INDEX, SUMO_ATTR_LENGTH, SUMO_ATTR_SHAPE, SUMO_ATTR_SPEED, SUMO_ATTR_WIDTH, SUMO_const_laneWidth, SUMOReal, SVCAll, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addParam (const SUMOSAXAttributes & attrs) protected
Definition at line 520 of file NLHandler.cpp.
References NLJunctionControlBuilder::addParam(), Parameterised::addParameter(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getString(), SUMOSAXAttributes::hasAttribute(), myAmInTLLogicMode, myJunctionControlBuilder, myLastParameterised, SUMO_ATTR_KEY, and SUMO_ATTR_VALUE.
Referenced by myStartElement().
void NLHandler::addPhase (const SUMOSAXAttributes & attrs) private
adds a phase to the traffic lights logic currently build
Todo:
: the following should be moved to StringTok
Definition at line 673 of file NLHandler.cpp.
References NLJunctionControlBuilder::addPhase(), SUMOSAXAttributes::get(), NLJunctionControlBuilder::getActiveKey(), NLJunctionControlBuilder::getActiveSubKey(), MsgHandler::getErrorInstance(), NLJunctionControlBuilder::getNumberOfLoadedPhases(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getStringSecure(), SUMOSAXAttributes::getSUMOTimeReporting(), MsgHandler::getWarningInstance(), SUMOSAXAttributes::hasAttribute(), MsgHandler::inform(), myJunctionControlBuilder, SUMO_ATTR_DURATION, SUMO_ATTR_MAXDURATION, SUMO_ATTR_MINDURATION, SUMO_ATTR_STATE, SUMO_ATTR_TARGETLANE, SUMO_ATTR_TYPE, toString(), and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addPOI (const SUMOSAXAttributes & attrs) private
adds a polygon
void NLHandler::addPoly (const SUMOSAXAttributes & attrs) private
adds a polygon
void NLHandler::addRequest (const SUMOSAXAttributes & attrs) private
adds a request item to the current junction logic
Definition at line 605 of file NLHandler.cpp.
References NLJunctionControlBuilder::addLogicItem(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), myCurrentIsBroken, myJunctionControlBuilder, SUMO_ATTR_CONT, SUMO_ATTR_FOES, SUMO_ATTR_INDEX, SUMO_ATTR_RESPONSE, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addRoundabout (const SUMOSAXAttributes & attrs) private
Parses a roundabout and sets flags for the edges
Parameters
[in] attrs The attributes to parse
Definition at line 1217 of file NLHandler.cpp.
References MSEdge::dictionary(), SUMOSAXAttributes::getStringVector(), SUMOSAXAttributes::hasAttribute(), MSEdge::markAsRoundabout(), SUMO_ATTR_EDGES, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addRouteProbeDetector (const SUMOSAXAttributes & attrs) protected virtual
Builds a routeProbe-detector using the given specification.
Parameters
[in] attrs The attributes that define the detector
Definition at line 838 of file NLHandler.cpp.
References NLDetectorBuilder::buildRouteProbe(), FileHelpers::checkForRelativity(), SUMOSAXAttributes::get(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getSUMOTimeReporting(), myDetectorBuilder, SUMO_ATTR_BEGIN, SUMO_ATTR_EDGE, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, and WRITE_ERROR.
Referenced by myStartElement().
void MSRouteHandler::addStop (const SUMOSAXAttributes & attrs) protected virtual inherited
Processing of a stop.
Implements SUMORouteHandler.
Definition at line 900 of file MSRouteHandler.cpp.
References SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, SUMORouteHandler::checkStopPos(), SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::depart, SUMOVehicleParameter::departPos, MSLane::dictionary(), SUMOVehicleParameter::Stop::duration, SUMOVehicleParameter::Stop::endPos, MSStoppingPlace::getBeginLanePosition(), MSNet::getBusStop(), MSNet::getChargingStation(), MSNet::getContainerStop(), MSLane::getEdge(), MSStoppingPlace::getEndLanePosition(), MsgHandler::getErrorInstance(), Named::getID(), MSNet::getInstance(), MSStoppingPlace::getLane(), MSEdge::getLanes(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, SUMOVehicleParameter::Stop::lane, MAX2(), MSRouteHandler::myActiveContainerPlan, MSRouteHandler::myActivePlan, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteStops, SUMORouteHandler::myInsertStopEdgesAt, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::parseStop(), POSITION_EPS, SUMOVehicleParameter::Stop::startPos, SUMOVehicleParameter::stops, SUMO_ATTR_ACTTYPE, SUMO_ATTR_ENDPOS, SUMO_ATTR_FRIENDLY_POS, SUMO_ATTR_LANE, SUMO_ATTR_POSITION, SUMO_ATTR_STARTPOS, SUMOReal, SUMOVehicleParameter::Stop::until, WRITE_ERROR, and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG().
void NLHandler::addVTypeProbeDetector (const SUMOSAXAttributes & attrs) protected virtual
Builds a vtype-detector using the given specification.
Parameters
[in] attrs The attributes that define the detector
Definition at line 818 of file NLHandler.cpp.
References NLDetectorBuilder::buildVTypeProbe(), FileHelpers::checkForRelativity(), SUMOSAXAttributes::get(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getStringSecure(), SUMOSAXAttributes::getSUMOTimeReporting(), myDetectorBuilder, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_ID, SUMO_ATTR_TYPE, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addWAUTJunction (const SUMOSAXAttributes & attrs) private
Definition at line 584 of file NLHandler.cpp.
References MSTLLogicControl::addWAUTJunction(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), NLJunctionControlBuilder::getTLLogicControlToUse(), myCurrentIsBroken, myJunctionControlBuilder, SUMO_ATTR_JUNCTION_ID, SUMO_ATTR_PROCEDURE, SUMO_ATTR_SYNCHRON, SUMO_ATTR_WAUT_ID, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::addWAUTSwitch (const SUMOSAXAttributes & attrs) private
Definition at line 565 of file NLHandler.cpp.
References MSTLLogicControl::addWAUTSwitch(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getSUMOTimeReporting(), NLJunctionControlBuilder::getTLLogicControlToUse(), myCurrentIsBroken, myCurrentWAUTID, myJunctionControlBuilder, SUMO_ATTR_TIME, SUMO_ATTR_TO, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::beginE3Detector (const SUMOSAXAttributes & attrs) protected
Starts building of an e3 detector using the given specification.
Parameters
[in] attrs The attributes that define the detector
Definition at line 914 of file NLHandler.cpp.
References NLDetectorBuilder::beginE3Detector(), FileHelpers::checkForRelativity(), SUMOSAXAttributes::get(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::getSUMOTimeReporting(), myDetectorBuilder, SUMO_ATTR_FILE, SUMO_ATTR_FREQUENCY, SUMO_ATTR_HALTING_SPEED_THRESHOLD, SUMO_ATTR_HALTING_TIME_THRESHOLD, SUMO_ATTR_ID, SUMOReal, TIME2STEPS, and WRITE_ERROR.
Referenced by myStartElement().
void NLHandler::beginEdgeParsing (const SUMOSAXAttributes & attrs) private
begins the processing of an edge
Definition at line 297 of file NLHandler.cpp.
References NLEdgeControlBuilder::addCrossingEdges(), NLEdgeControlBuilder::beginEdgeParsing(), EDGEFUNC_CONNECTOR, EDGEFUNC_CROSSING, EDGEFUNC_INTERNAL, EDGEFUNC_NORMAL, EDGEFUNC_SINK, EDGEFUNC_SOURCE, EDGEFUNC_WALKINGAREA, MSEdge::EDGEFUNCTION_CONNECTOR, MSEdge::EDGEFUNCTION_CROSSING, MSEdge::EDGEFUNCTION_INTERNAL, MSEdge::EDGEFUNCTION_NORMAL, MSEdge::EDGEFUNCTION_UNKNOWN, MSEdge::EDGEFUNCTION_WALKINGAREA, SUMOSAXAttributes::get(), SUMOSAXAttributes::getEdgeFunc(), SUMOXMLDefinitions::getJunctionIDFromInternalEdge(), SUMOSAXAttributes::getOpt(), MSGlobals::gUsingInternalLanes, SUMOSAXAttributes::hasAttribute(), StringTokenizer::hasNext(), myCurrentIsBroken, myCurrentIsInternalToSkip, myEdgeControlBuilder, myHaveSeenInternalEdge, myJunctionGraph, StringTokenizer::next(), SUMO_ATTR_CROSSING_EDGES, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_NAME, SUMO_ATTR_PRIORITY, SUMO_ATTR_TO, SUMO_ATTR_TYPE, and WRITE_ERROR.
Referenced by myStartElement().
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 192 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 175 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
bool SUMORouteHandler::checkLastDepart () protected inherited
Checks whether the route file is sorted by departure time if needed.
Definition at line 78 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, SUMOVehicleParameter::id, SUMORouteHandler::myLastDepart, SUMORouteHandler::myVehicleParameter, and WRITE_WARNING.
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeVehicle(), and SUMORouteHandler::getFirstDepart().
bool SUMORouteHandler::checkStopPos (SUMOReal & startPos, SUMOReal & endPos, const SUMOReal laneLength, const SUMOReal minLength, const bool friendlyPos) static inherited
check start and end position of a stop
Definition at line 211 of file SUMORouteHandler.cpp.
Referenced by NLTriggerBuilder::addAccess(), MSRouteHandler::addStop(), RORouteHandler::addStop(), NLTriggerBuilder::parseAndBuildChargingStation(), NLTriggerBuilder::parseAndBuildStoppingPlace(), and RONetHandler::parseStoppingPlace().
void MSRouteHandler::closeContainer () protected virtual inherited
Ends the processing of a container.
Implements SUMORouteHandler.
Definition at line 831 of file MSRouteHandler.cpp.
References MSTransportableControl::buildContainer(), SUMORouteHandler::checkLastDepart(), GenericSAXHandler::error(), MSNet::getContainerControl(), MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOVehicleParameter::id, MSRouteHandler::myActiveContainerPlan, MSRouteHandler::myAddVehiclesDirectly, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), and SUMOVehicleParameter::vtypeid.
Referenced by MSRouteHandler::getParsingRNG().
void NLHandler::closeEdge () protected virtual
Closes the process of building an edge.
Definition at line 386 of file NLHandler.cpp.
References NLEdgeControlBuilder::closeEdge(), MSEdge::dictionary(), Named::getID(), myCurrentIsBroken, myCurrentIsInternalToSkip, myEdgeControlBuilder, and WRITE_ERROR.
Referenced by myEndElement().
void MSRouteHandler::closeFlow () protected virtual inherited
Ends the processing of a flow.
Implements SUMORouteHandler.
Definition at line 858 of file MSRouteHandler.cpp.
References SUMORouteHandler::checkLastDepart(), MSRouteHandler::closeRoute(), SUMOVehicleParameter::depart, MSRoute::dictionary(), MSNet::getInstance(), OptionsCont::getOptions(), SUMOVehicleParameter::id, SUMORouteHandler::myActiveRouteID, MSRouteHandler::myAddVehiclesDirectly, SUMORouteHandler::myInsertStopEdgesAt, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), SUMOVehicleParameter::repetitionNumber, SUMOVehicleParameter::repetitionOffset, SUMOVehicleParameter::repetitionProbability, SUMOVehicleParameter::repetitionsDone, SUMOVehicleParameter::routeid, SUMOVehicleParameter::setParameter, string2time(), VEHPARS_FORCE_REROUTE, and SUMOVehicleParameter::vtypeid.
Referenced by MSRouteHandler::getParsingRNG().
void MSRouteHandler::closePerson () protected virtual inherited
Ends the processing of a person.
Implements SUMORouteHandler.
Definition at line 797 of file MSRouteHandler.cpp.
References MSTransportableControl::buildPerson(), SUMORouteHandler::checkLastDepart(), MSRouteHandler::deleteActivePlans(), GenericSAXHandler::error(), MSNet::getInstance(), MSNet::getPersonControl(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOVehicleParameter::id, MSRouteHandler::myActivePlan, MSRouteHandler::myAddVehiclesDirectly, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), and SUMOVehicleParameter::vtypeid.
Referenced by MSRouteHandler::getParsingRNG().
void MSRouteHandler::closeRoute (const bool mayBeDisconnected = false) protected virtual inherited
closes (ends) the building of a route. Afterwards no edges may be added to it; this method may throw exceptions when a) the route is empty or b) another route with the same id already exists
Implements SUMORouteHandler.
Definition at line 533 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), MSRoute::addReference(), MSRoute::dictionary(), MSEdge::EDGEFUNCTION_DISTRICT, MSNet::getInstance(), MSGlobals::gStateLoaded, SUMOVehicleParameter::id, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteColor, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteProbability, SUMORouteHandler::myActiveRouteRefID, SUMORouteHandler::myActiveRouteStops, SUMORouteHandler::myCurrentCosts, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMOVehicleParameter::repetitionNumber, and MSRoute::setCosts().
Referenced by MSRouteHandler::closeFlow(), MSRouteHandler::getParsingRNG(), and MSRouteHandler::myEndElement().
void MSRouteHandler::closeRouteDistribution () protected virtual inherited
closes (ends) the building of a distribution
Implements SUMORouteHandler.
Definition at line 650 of file MSRouteHandler.cpp.
References MSRoute::dictionary(), RandomDistributor< T >::getOverallProb(), MSGlobals::gStateLoaded, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myCurrentRouteDistributionID, MSRouteHandler::myParsingRNG, and SUMORouteHandler::myVehicleParameter.
Referenced by MSRouteHandler::getParsingRNG().
void MSRouteHandler::closeVehicle () protected virtual inherited
Ends the processing of a vehicle.
Implements SUMORouteHandler.
Definition at line 672 of file MSRouteHandler.cpp.
References MSInsertionControl::add(), MSRoute::addReference(), MSVehicleControl::addVehicle(), MSVehicleControl::addWaiting(), MSRoute::begin(), MSVehicleControl::buildVehicle(), SUMORouteHandler::checkLastDepart(), DEFAULT_VTYPE_ID, MSVehicleControl::deleteVehicle(), SUMOVehicleParameter::depart, DEPART_CONTAINER_TRIGGERED, DEPART_GIVEN, DEPART_TRIGGERED, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departProcedure, MSRoute::dictionary(), MSGlobals::gCheckRoutes, MSRoute::getEdges(), MSNet::getInsertionControl(), MSNet::getInstance(), MSEdge::getLanes(), OptionsCont::getOptions(), SUMOVehicle::getParameter(), MSVehicleControl::getQuota(), SUMOVehicle::getRoute(), MSVehicleControl::getVehicle(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), MSGlobals::gStateLoaded, MSGlobals::gUseMesoSim, SUMOVehicleParameter::id, SUMORouteHandler::myActiveRouteID, MSRouteHandler::myAddVehiclesDirectly, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, SUMORouteHandler::registerLastDepart(), MSVehicleControl::registerOneWaitingForContainer(), MSVehicleControl::registerOneWaitingForPerson(), MSRoute::release(), SUMOVehicleParameter::routeid, string2time(), toString(), SUMOVehicleParameter::vtypeid, and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG(), and MSRouteHandler::myEndElement().
void MSRouteHandler::closeVehicleTypeDistribution () protected virtual inherited
closes (ends) the building of a distribution
Implements SUMORouteHandler.
Definition at line 434 of file MSRouteHandler.cpp.
References MSNet::getInstance(), RandomDistributor< T >::getOverallProb(), MSGlobals::gStateLoaded, MSRouteHandler::myCurrentVTypeDistribution, and MSRouteHandler::myCurrentVTypeDistributionID.
Referenced by MSRouteHandler::getParsingRNG().
void NLHandler::closeWAUT () private
Definition at line 1246 of file NLHandler.cpp.
References MSTLLogicControl::closeWAUT(), NLJunctionControlBuilder::getTLLogicControlToUse(), myCurrentIsBroken, myCurrentWAUTID, myJunctionControlBuilder, and WRITE_ERROR.
Referenced by myEndElement().
void NLHandler::endE3Detector () protected virtual
Builds of an e3 detector using collected values.
Definition at line 1236 of file NLHandler.cpp.
References NLDetectorBuilder::endE3Detector(), myDetectorBuilder, and WRITE_ERROR.
Referenced by myEndElement().
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 211 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), MSRouteHandler::myStartElement(), and MSRouteHandler::parseWalkPos().
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 217 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by addE1Detector(), addE2Detector(), addEdgeLaneMeanData(), addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), addRouteProbeDetector(), addVTypeProbeDetector(), beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), MSStateHandler::myStartElement(), SUMORouteHandler::myStartElement(), myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
SUMOTime SUMORouteHandler::getFirstDepart () const inline inherited
returns the first departure time that was ever read
Definition at line 74 of file SUMORouteHandler.h.
References SUMORouteHandler::addParam(), SUMORouteHandler::addStop(), SUMORouteHandler::checkLastDepart(), SUMORouteHandler::closeContainer(), SUMORouteHandler::closeFlow(), SUMORouteHandler::closePerson(), SUMORouteHandler::closeRoute(), SUMORouteHandler::closeRouteDistribution(), SUMORouteHandler::closeVehicle(), SUMORouteHandler::closeVehicleTypeDistribution(), SUMORouteHandler::myEndElement(), SUMORouteHandler::myFirstDepart, SUMORouteHandler::myStartElement(), SUMORouteHandler::openRoute(), SUMORouteHandler::openRouteDistribution(), SUMORouteHandler::openVehicleTypeDistribution(), SUMORouteHandler::parseStop(), and SUMORouteHandler::registerLastDepart().
Referenced by SUMORouteLoader::getFirstDepart().
SUMOTime SUMORouteHandler::getLastDepart () const inherited
Returns the last loaded depart time.
Definition at line 72 of file SUMORouteHandler.cpp.
References SUMORouteHandler::myLastDepart.
Referenced by SUMORouteLoader::loadUntil().
static MTRand* MSRouteHandler::getParsingRNG () inline static inherited
Definition at line 70 of file MSRouteHandler.h.
References MSRouteHandler::addStop(), MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::closeVehicle(), MSRouteHandler::closeVehicleTypeDistribution(), MSRouteHandler::myEndElement(), MSRouteHandler::myParsingRNG, MSRouteHandler::myStartElement(), MSRouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), MSRouteHandler::openVehicleTypeDistribution(), MSRouteHandler::parseFromViaTo(), MSRouteHandler::parseWalkPos(), MSRouteHandler::parseWalkPositions(), and SUMOReal.
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), MSVehicleControl::computeRandomDepartOffset(), MSInsertionControl::determineCandidates(), main(), and GUILoadThread::run().
bool NLHandler::haveSeenInternalEdge () const inline
Definition at line 108 of file NLHandler.h.
Referenced by NLBuilder::build(), and NLBuilder::buildNet().
bool NLHandler::haveSeenNeighs () const inline
Definition at line 112 of file NLHandler.h.
Referenced by NLBuilder::build(), and NLBuilder::buildNet().
void NLHandler::initJunctionLogic (const SUMOSAXAttributes & attrs) private
begins the reading of a junction row logic
Definition at line 632 of file NLHandler.cpp.
References SUMOSAXAttributes::get(), NLJunctionControlBuilder::initJunctionLogic(), myCurrentIsBroken, myJunctionControlBuilder, and SUMO_ATTR_ID.
Referenced by myStartElement().
void NLHandler::initTrafficLightLogic (const SUMOSAXAttributes & attrs) private
begins the reading of a traffic lights logic
Definition at line 646 of file NLHandler.cpp.
References SUMOSAXAttributes::get(), StringBijection< T >::get(), MSTLLogicControl::get(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), NLJunctionControlBuilder::getTLLogicControlToUse(), NLJunctionControlBuilder::initTrafficLightLogic(), myAmInTLLogicMode, myJunctionControlBuilder, SUMO_ATTR_ID, SUMO_ATTR_OFFSET, SUMO_ATTR_PROGRAMID, SUMO_ATTR_TYPE, TLTYPE_STATIC, SUMOXMLDefinitions::TrafficLightTypes, and WRITE_ERROR.
Referenced by myStartElement().
bool NLHandler::lefthand () const inline
Definition at line 116 of file NLHandler.h.
Referenced by NLBuilder::buildNet().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 227 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void NLHandler::myEndElement (int element) protected virtual
Called when a closing tag occurs.
Parameters
[in] element ID of the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myEndElement
Todo:
Refactor/describe
Reimplemented from MSRouteHandler.
Definition at line 240 of file NLHandler.cpp.
References MSJunction::addIncoming(), MSJunction::addOutgoing(), closeEdge(), NLJunctionControlBuilder::closeJunction(), NLJunctionControlBuilder::closeJunctionLogic(), NLJunctionControlBuilder::closeTrafficLightLogic(), closeWAUT(), MSEdge::dictionary(), endE3Detector(), GenericSAXHandler::getFileName(), myAmInTLLogicMode, myCurrentIsBroken, MSRouteHandler::myEndElement(), myJunctionControlBuilder, myJunctionGraph, myLastParameterised, myNetIsLoaded, NLJunctionControlBuilder::retrieve(), MSEdge::setJunctions(), SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_ENTRY_EXIT_DETECTOR, SUMO_TAG_JUNCTION, SUMO_TAG_NET, SUMO_TAG_PARAM, SUMO_TAG_TLLOGIC, SUMO_TAG_WAUT, and WRITE_ERROR.
void NLHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Todo:
Refactor/describe
Reimplemented from MSRouteHandler.
Definition at line 93 of file NLHandler.cpp.
References NLTriggerBuilder::addAccess(), NLDiscreteEventBuilder::addAction(), addConnection(), addDistrict(), addDistrictEdge(), addE1Detector(), addE2Detector(), addE3Entry(), addE3Exit(), addEdgeLaneMeanData(), addInstantE1Detector(), addLane(), NLEdgeControlBuilder::addNeigh(), addParam(), addPhase(), addRequest(), MSNet::addRestriction(), addRoundabout(), addRouteProbeDetector(), addVTypeProbeDetector(), addWAUTJunction(), addWAUTSwitch(), beginE3Detector(), beginEdgeParsing(), NLTriggerBuilder::buildVaporizer(), SUMOSAXAttributes::get(), GenericSAXHandler::getFileName(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getString(), getVehicleClassID(), initJunctionLogic(), initTrafficLightLogic(), myActionBuilder, myCurrentTypeID, myEdgeControlBuilder, myHaveSeenNeighs, myLefthand, myNet, myNetworkVersion, MSRouteHandler::myStartElement(), myTriggerBuilder, openJunction(), openWAUT(), NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildChargingStation(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), NLTriggerBuilder::parseAndBuildRerouter(), NLTriggerBuilder::parseAndBuildStoppingPlace(), setLocation(), SUMO_ATTR_ID, SUMO_ATTR_LANE, SUMO_ATTR_LEFTHAND, SUMO_ATTR_SPEED, SUMO_ATTR_VCLASS, SUMO_ATTR_VERSION, SUMO_TAG_ACCESS, SUMO_TAG_BUS_STOP, SUMO_TAG_CALIBRATOR, SUMO_TAG_CHARGING_STATION, SUMO_TAG_CONNECTION, SUMO_TAG_CONTAINER_STOP, SUMO_TAG_DET_ENTRY, SUMO_TAG_DET_EXIT, SUMO_TAG_E1DETECTOR, SUMO_TAG_E2DETECTOR, SUMO_TAG_E3DETECTOR, SUMO_TAG_EDGE, SUMO_TAG_ENTRY_EXIT_DETECTOR, SUMO_TAG_INDUCTION_LOOP, SUMO_TAG_INSTANT_INDUCTION_LOOP, SUMO_TAG_JUNCTION, SUMO_TAG_LANE, SUMO_TAG_LANE_AREA_DETECTOR, SUMO_TAG_LOCATION, SUMO_TAG_MEANDATA_EDGE, SUMO_TAG_MEANDATA_LANE, SUMO_TAG_NEIGH, SUMO_TAG_NET, SUMO_TAG_PARAM, SUMO_TAG_PHASE, SUMO_TAG_REQUEST, SUMO_TAG_REROUTER, SUMO_TAG_RESTRICTION, SUMO_TAG_ROUNDABOUT, SUMO_TAG_ROUTEPROBE, SUMO_TAG_TAZ, SUMO_TAG_TAZSINK, SUMO_TAG_TAZSOURCE, SUMO_TAG_TIMEDEVENT, SUMO_TAG_TLLOGIC, SUMO_TAG_TRAIN_STOP, SUMO_TAG_TYPE, SUMO_TAG_VAPORIZER, SUMO_TAG_VSS, SUMO_TAG_VTYPEPROBE, SUMO_TAG_WAUT, SUMO_TAG_WAUT_JUNCTION, SUMO_TAG_WAUT_SWITCH, SUMOReal, and WRITE_ERROR.
SUMOReal NLHandler::networkVersion () const inline
Definition at line 120 of file NLHandler.h.
References GenericSAXHandler::myEndElement(), and ShapeHandler::myStartElement().
Referenced by NLBuilder::buildNet().
void NLHandler::openJunction (const SUMOSAXAttributes & attrs) private virtual
opens a junction for processing
Definition at line 450 of file NLHandler.cpp.
References PositionVector::closePolygon(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getNodeType(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getStringSecure(), MSGlobals::gUsingInternalLanes, SUMOSAXAttributes::hasAttribute(), myCurrentIsBroken, myJunctionControlBuilder, NLJunctionControlBuilder::openJunction(), parseLanes(), SUMO_ATTR_ID, SUMO_ATTR_INCLANES, SUMO_ATTR_INTLANES, SUMO_ATTR_KEY, SUMO_ATTR_SHAPE, SUMO_ATTR_X, SUMO_ATTR_Y, SUMOReal, and WRITE_ERROR.
Referenced by myStartElement().
void MSRouteHandler::openRoute (const SUMOSAXAttributes & attrs) protected virtual inherited
opens a route for reading
Implements SUMORouteHandler.
Definition at line 454 of file MSRouteHandler.cpp.
References DEFAULT_VEH_PROB, MSRoute::dictionary(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), RandomDistributor< T >::getProbs(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteColor, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myActiveRouteProbability, SUMORouteHandler::myActiveRouteRefID, SUMORouteHandler::myCurrentCosts, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myCurrentRouteDistributionID, SUMORouteHandler::myInsertStopEdgesAt, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, MSEdge::parseEdgesList(), SUMO_ATTR_COLOR, SUMO_ATTR_COST, SUMO_ATTR_EDGES, SUMO_ATTR_ID, SUMO_ATTR_PROB, SUMO_ATTR_REFID, SUMOReal, toString(), WRITE_ERROR, and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG().
void MSRouteHandler::openRouteDistribution (const SUMOSAXAttributes & attrs) protected virtual inherited
opens a route distribution for reading
Implements SUMORouteHandler.
Definition at line 603 of file MSRouteHandler.cpp.
References TplConvert::_2SUMORealSec(), RandomDistributor< T >::add(), MSRoute::addReference(), MSRoute::dictionary(), SUMOSAXAttributes::get(), SUMOSAXAttributes::hasAttribute(), StringTokenizer::hasNext(), SUMOVehicleParameter::id, MSRouteHandler::myCurrentRouteDistribution, MSRouteHandler::myCurrentRouteDistributionID, MSRouteHandler::myParsingRNG, SUMORouteHandler::myVehicleParameter, StringTokenizer::next(), SUMO_ATTR_ID, SUMO_ATTR_PROBS, SUMO_ATTR_ROUTES, SUMOReal, toString(), and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG().
void MSRouteHandler::openVehicleTypeDistribution (const SUMOSAXAttributes & attrs) protected virtual inherited
opens a type distribution for reading
Implements SUMORouteHandler.
Definition at line 412 of file MSRouteHandler.cpp.
References RandomDistributor< T >::add(), SUMOSAXAttributes::get(), MSVehicleType::getDefaultProbability(), MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicleControl::getVType(), SUMOSAXAttributes::hasAttribute(), MSRouteHandler::myCurrentVTypeDistribution, MSRouteHandler::myCurrentVTypeDistributionID, MSRouteHandler::myParsingRNG, SUMO_ATTR_ID, and SUMO_ATTR_VTYPES.
Referenced by MSRouteHandler::getParsingRNG().
void NLHandler::openWAUT (const SUMOSAXAttributes & attrs) private virtual
Definition at line 538 of file NLHandler.cpp.
References MSTLLogicControl::addWAUT(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getOptSUMOTimeReporting(), NLJunctionControlBuilder::getTLLogicControlToUse(), myCurrentIsBroken, myCurrentWAUTID, myJunctionControlBuilder, SUMO_ATTR_ID, SUMO_ATTR_REF_TIME, SUMO_ATTR_START_PROG, and WRITE_ERROR.
Referenced by myStartElement().
NLHandler& NLHandler::operator= (const NLHandler & s) private
invalid assignment operator
void MSRouteHandler::parseFromViaTo (std::string element, const SUMOSAXAttributes & attrs) protected inherited
Called for parsing from and to and the corresponding taz attributes.
Parameters
[in] element description of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
Definition at line 110 of file MSRouteHandler.cpp.
References MSEdge::dictionary(), SUMOVehicleParameter::fromTaz, OptionsCont::getBool(), MSEdge::getNumPredecessors(), MSEdge::getNumSuccessors(), SUMOSAXAttributes::getOpt(), OptionsCont::getOptions(), StringTokenizer::getVector(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::id, MSRouteHandler::myActiveRoute, SUMORouteHandler::myActiveRouteID, SUMORouteHandler::myInsertStopEdgesAt, SUMORouteHandler::myVehicleParameter, MSEdge::parseEdgesList(), SUMOVehicleParameter::routeid, SUMO_ATTR_FROM, SUMO_ATTR_ROUTE, SUMO_ATTR_TO, SUMO_ATTR_VIA, SUMOVehicleParameter::toTaz, VEHPARS_FROM_TAZ_SET, VEHPARS_TO_TAZ_SET, SUMOVehicleParameter::via, SUMOVehicleParameter::wasSet(), and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG(), and MSRouteHandler::myStartElement().
void NLHandler::parseLanes (const std::string & junctionID, const std::string & def, std::vector< MSLane * > & into, bool & ok) private
Definition at line 500 of file NLHandler.cpp.
References MSLane::dictionary(), MSGlobals::gUsingInternalLanes, StringTokenizer::hasNext(), StringTokenizer::next(), and WRITE_ERROR.
Referenced by openJunction().
LinkDirection NLHandler::parseLinkDir (const std::string & dir) private
Parses the given character into an enumeration typed link direction.
Definition at line 1098 of file NLHandler.cpp.
References StringBijection< T >::get(), and SUMOXMLDefinitions::LinkDirections.
Referenced by addConnection().
LinkState NLHandler::parseLinkState (const std::string & state) private
Parses the given character into an enumeration typed link state.
Definition at line 1108 of file NLHandler.cpp.
References StringBijection< T >::get(), LINKSTATE_TL_OFF_BLINKING, and SUMOXMLDefinitions::LinkStates.
Referenced by addConnection().
bool SUMORouteHandler::parseStop (SUMOVehicleParameter::Stop & stop, const SUMOSAXAttributes & attrs, std::string errorSuffix, MsgHandler *const errorOutput) protected inherited
parses attributes common to all stops
Definition at line 263 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::Stop::awaitedContainers, SUMOVehicleParameter::Stop::awaitedPersons, SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::Stop::index, MsgHandler::inform(), SUMOVehicleParameter::Stop::lane, SUMOVehicleParameter::Stop::parking, SUMOSAXAttributes::parseStringSet(), SUMOVehicleParameter::Stop::setParameter, STOP_CONTAINER_TRIGGER_SET, STOP_END_SET, STOP_EXPECTED_CONTAINERS_SET, STOP_EXPECTED_SET, STOP_INDEX_END, STOP_INDEX_FIT, STOP_PARKING_SET, STOP_START_SET, STOP_TRIGGER_SET, SUMO_ATTR_BUS_STOP, SUMO_ATTR_CHARGING_STATION, SUMO_ATTR_CONTAINER_STOP, SUMO_ATTR_CONTAINER_TRIGGERED, SUMO_ATTR_DURATION, SUMO_ATTR_ENDPOS, SUMO_ATTR_EXPECTED, SUMO_ATTR_EXPECTED_CONTAINERS, SUMO_ATTR_INDEX, SUMO_ATTR_PARKING, SUMO_ATTR_STARTPOS, SUMO_ATTR_TRIGGERED, SUMO_ATTR_UNTIL, SUMOVehicleParameter::Stop::triggered, and SUMOVehicleParameter::Stop::until.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), and SUMORouteHandler::getFirstDepart().
SUMOReal MSRouteHandler::parseWalkPos (SumoXMLAttr attr, const std::string & id, const MSEdge * edge, const std::string & val) protected inherited
Definition at line 1085 of file MSRouteHandler.cpp.
References ARRIVAL_POS_MAX, ARRIVAL_POS_RANDOM, GenericSAXHandler::error(), MSEdge::getLength(), SUMOVehicleParameter::interpretEdgePos(), MSRouteHandler::myParsingRNG, SUMOVehicleParameter::parseArrivalPos(), MTRand::rand(), SUMO_TAG_WALK, SUMOReal, and toString().
Referenced by MSRouteHandler::getParsingRNG(), and MSRouteHandler::parseWalkPositions().
void MSRouteHandler::parseWalkPositions (const SUMOSAXAttributes & attrs, const std::string & personID, const MSEdge * fromEdge, const MSEdge *& toEdge, SUMOReal & departPos, SUMOReal & arrivalPos, MSStoppingPlace *& bs, bool & ok) protected inherited
@ brief parse depart- and arrival positions of a walk
Definition at line 1039 of file MSRouteHandler.cpp.
References SUMOSAXAttributes::get(), MSStoppingPlace::getBeginLanePosition(), MSNet::getBusStop(), MSLane::getEdge(), MSStoppingPlace::getEndLanePosition(), Named::getID(), MSNet::getInstance(), MSStoppingPlace::getLane(), SUMOSAXAttributes::getOpt(), MSStoppingPlace::hasAccess(), SUMOSAXAttributes::hasAttribute(), NUMERICAL_EPS, MSRouteHandler::parseWalkPos(), SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_BUS_STOP, SUMO_ATTR_DEPARTPOS, SUMOReal, toString(), and WRITE_WARNING.
Referenced by MSRouteHandler::getParsingRNG(), and MSRouteHandler::myStartElement().
void SUMORouteHandler::registerLastDepart () protected inherited
save last depart (only to be used if vehicle is not discarded)
Definition at line 90 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, SUMOVehicleParameter::line, SUMORouteHandler::myFirstDepart, SUMORouteHandler::myLastDepart, and SUMORouteHandler::myVehicleParameter.
Referenced by MSRouteHandler::closeContainer(), RORouteHandler::closeContainer(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closePerson(), RORouteHandler::closePerson(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), and SUMORouteHandler::getFirstDepart().
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 167 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
void NLHandler::setLocation (const SUMOSAXAttributes & attrs) private
Parses network location description.
Definition at line 1124 of file NLHandler.cpp.
References SUMOSAXAttributes::get(), GeoConvHelper::getFinal(), OptionsCont::getOptions(), GeoConvHelper::init(), myNetIsLoaded, SUMO_ATTR_CONV_BOUNDARY, SUMO_ATTR_NET_OFFSET, SUMO_ATTR_ORIG_BOUNDARY, SUMO_ATTR_ORIG_PROJ, and WRITE_WARNING.
Referenced by myStartElement().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 205 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
NLDiscreteEventBuilder NLHandler::myActionBuilder protected
A builder for object actions.
Definition at line 294 of file NLHandler.h.
Referenced by myStartElement().
MSTransportable::MSTransportablePlan* MSRouteHandler::myActiveContainerPlan protected inherited
The plan of the current container.
Definition at line 160 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addStop(), MSRouteHandler::closeContainer(), MSRouteHandler::deleteActivePlans(), and MSRouteHandler::myStartElement().
MSTransportable::MSTransportablePlan* MSRouteHandler::myActivePlan protected inherited
The plan of the current person.
Definition at line 157 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addStop(), MSRouteHandler::closePerson(), MSRouteHandler::deleteActivePlans(), and MSRouteHandler::myStartElement().
ConstMSEdgeVector MSRouteHandler::myActiveRoute protected inherited
The current route.
Definition at line 154 of file MSRouteHandler.h.
Referenced by MSRouteHandler::addStop(), MSRouteHandler::closeRoute(), MSRouteHandler::MSRouteHandler(), MSRouteHandler::myStartElement(), MSRouteHandler::openRoute(), and MSRouteHandler::parseFromViaTo().
const RGBColor* SUMORouteHandler::myActiveRouteColor protected inherited
The currently parsed route's color.
Definition at line 169 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
std::string SUMORouteHandler::myActiveRouteID protected inherited
The id of the current route.
Definition at line 160 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::closeVehicle(), MSRouteHandler::myStartElement(), SUMORouteHandler::myStartElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::parseFromViaTo(), and RORouteHandler::parseFromViaTo().
SUMOReal SUMORouteHandler::myActiveRouteProbability protected inherited
The probability of the current route.
Definition at line 166 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), RORouteHandler::myStartElement(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
std::string SUMORouteHandler::myActiveRouteRefID protected inherited
The id of the route the current route references to.
Definition at line 163 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
std::vector<SUMOVehicleParameter::Stop> SUMORouteHandler::myActiveRouteStops protected inherited
List of the stops on the parsed route.
Definition at line 175 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::closeRoute(), and RORouteHandler::closeRoute().
bool MSRouteHandler::myAddVehiclesDirectly protected inherited
Information whether vehicles shall be directly added to the network or kept within the buffer.
Definition at line 163 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), and MSRouteHandler::closeVehicle().
bool NLHandler::myAmInTLLogicMode protected
internal information whether a tls-logic is currently read
Definition at line 316 of file NLHandler.h.
Referenced by addParam(), initTrafficLightLogic(), and myEndElement().
SUMOTime SUMORouteHandler::myBeginDefault protected inherited
The default value for flow begins.
Definition at line 184 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myEndElement(), and SUMORouteHandler::myStartElement().
Boundary NLHandler::myConvBoundary protected
Definition at line 328 of file NLHandler.h.
SUMOReal SUMORouteHandler::myCurrentCosts protected inherited
The currently parsed route costs.
Definition at line 172 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
std::string NLHandler::myCurrentDistrictID protected
The id of the current district.
Definition at line 313 of file NLHandler.h.
Referenced by addDistrict(), and addDistrictEdge().
bool NLHandler::myCurrentIsBroken protected
Definition at line 330 of file NLHandler.h.
Referenced by addDistrict(), addDistrictEdge(), addLane(), addRequest(), addWAUTJunction(), addWAUTSwitch(), beginEdgeParsing(), closeEdge(), closeWAUT(), initJunctionLogic(), myEndElement(), openJunction(), and openWAUT().
bool NLHandler::myCurrentIsInternalToSkip protected
Information whether the currently parsed edge is internal and not wished, here.
Definition at line 297 of file NLHandler.h.
Referenced by addLane(), beginEdgeParsing(), and closeEdge().
RandomDistributor<const MSRoute*>* MSRouteHandler::myCurrentRouteDistribution protected inherited
The currently parsed distribution of routes (probability->route)
Definition at line 172 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::openRoute(), and MSRouteHandler::openRouteDistribution().
std::string MSRouteHandler::myCurrentRouteDistributionID protected inherited
The id of the currently parsed route distribution.
Definition at line 175 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeRouteDistribution(), MSRouteHandler::openRoute(), and MSRouteHandler::openRouteDistribution().
std::string NLHandler::myCurrentTypeID protected
The id of the currently processed edge type.
Definition at line 322 of file NLHandler.h.
Referenced by myStartElement().
SUMOVTypeParameter* SUMORouteHandler::myCurrentVType protected inherited
The currently parsed vehicle type.
Definition at line 178 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::addParam(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), SUMORouteHandler::myEndElement(), MSRouteHandler::myStartElement(), RORouteHandler::myStartElement(), SUMORouteHandler::myStartElement(), and SUMORouteHandler::~SUMORouteHandler().
RandomDistributor<MSVehicleType*>* MSRouteHandler::myCurrentVTypeDistribution protected inherited
The currently parsed distribution of vehicle types (probability->vehicle type)
Definition at line 166 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeVehicleTypeDistribution(), MSRouteHandler::myEndElement(), and MSRouteHandler::openVehicleTypeDistribution().
std::string MSRouteHandler::myCurrentVTypeDistributionID protected inherited
The id of the currently parsed vehicle type distribution.
Definition at line 169 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeVehicleTypeDistribution(), and MSRouteHandler::openVehicleTypeDistribution().
std::string NLHandler::myCurrentWAUTID protected
The id of the currently processed WAUT.
Definition at line 319 of file NLHandler.h.
Referenced by addWAUTSwitch(), closeWAUT(), and openWAUT().
NLDetectorBuilder& NLHandler::myDetectorBuilder protected
The detector builder to use.
Definition at line 301 of file NLHandler.h.
Referenced by addE1Detector(), addE2Detector(), addE3Entry(), addE3Exit(), addEdgeLaneMeanData(), addInstantE1Detector(), addRouteProbeDetector(), addVTypeProbeDetector(), beginE3Detector(), and endE3Detector().
NLEdgeControlBuilder& NLHandler::myEdgeControlBuilder protected
The edge builder to use.
Definition at line 307 of file NLHandler.h.
Referenced by addDistrict(), addLane(), beginEdgeParsing(), closeEdge(), and myStartElement().
SUMOTime SUMORouteHandler::myEndDefault protected inherited
The default value for flow ends.
Definition at line 187 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myEndElement(), and SUMORouteHandler::myStartElement().
SUMOTime SUMORouteHandler::myFirstDepart protected inherited
the first read departure time
Definition at line 190 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::getFirstDepart(), and SUMORouteHandler::registerLastDepart().
bool NLHandler::myHaveSeenInternalEdge protected
whether the loaded network contains internal lanes
Definition at line 337 of file NLHandler.h.
Referenced by beginEdgeParsing().
bool NLHandler::myHaveSeenNeighs protected
whether the loaded network contains explicit neighbor lanes
Definition at line 340 of file NLHandler.h.
Referenced by myStartElement().
bool NLHandler::myHaveWarnedAboutDeprecatedLanes protected
Definition at line 332 of file NLHandler.h.
IDSupplier SUMORouteHandler::myIdSupplier protected inherited
generates numerical ids
Definition at line 181 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::myStartElement().
int SUMORouteHandler::myInsertStopEdgesAt protected inherited
where stop edges can be inserted into the current route (-1 means no insertion)
Definition at line 193 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::parseFromViaTo(), and RORouteHandler::parseFromViaTo().
NLJunctionControlBuilder& NLHandler::myJunctionControlBuilder protected
The junction builder to use.
Definition at line 310 of file NLHandler.h.
Referenced by addConnection(), addE2Detector(), addParam(), addPhase(), addRequest(), addWAUTJunction(), addWAUTSwitch(), closeWAUT(), initJunctionLogic(), initTrafficLightLogic(), myEndElement(), openJunction(), and openWAUT().
JunctionGraph NLHandler::myJunctionGraph protected
Definition at line 353 of file NLHandler.h.
Referenced by beginEdgeParsing(), and myEndElement().
SUMOTime SUMORouteHandler::myLastDepart protected inherited
The insertion time of the vehicle read last.
Definition at line 157 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::checkLastDepart(), SUMORouteHandler::getLastDepart(), and SUMORouteHandler::registerLastDepart().
Parameterised* NLHandler::myLastParameterised protected
Definition at line 334 of file NLHandler.h.
Referenced by addLane(), addParam(), and myEndElement().
bool NLHandler::myLefthand protected
whether the loaded network was built for left hand traffic
Definition at line 343 of file NLHandler.h.
Referenced by myStartElement().
MSNet& NLHandler::myNet protected
The net to fill (preinitialised)
Definition at line 209 of file NLHandler.h.
Referenced by addDistrict(), addLane(), and myStartElement().
bool NLHandler::myNetIsLoaded protected
whether the location element was already loadee
Definition at line 349 of file NLHandler.h.
Referenced by myEndElement(), and setLocation().
Position NLHandler::myNetworkOffset protected
The network offset.
Definition at line 325 of file NLHandler.h.
SUMOReal NLHandler::myNetworkVersion protected
the loaded network version
Definition at line 346 of file NLHandler.h.
Referenced by addConnection(), and myStartElement().
Boundary NLHandler::myOrigBoundary protected
The network's boundaries.
Definition at line 328 of file NLHandler.h.
MTRand MSRouteHandler::myParsingRNG static protected inherited
A random number generator used to choose from vtype/route distributions and computing the speed factors.
Definition at line 178 of file MSRouteHandler.h.
Referenced by MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::closeVehicle(), MSRouteHandler::getParsingRNG(), MSRouteHandler::myStartElement(), MSRouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), MSRouteHandler::openVehicleTypeDistribution(), and MSRouteHandler::parseWalkPos().
NLTriggerBuilder& NLHandler::myTriggerBuilder protected
The trigger builder to use.
Definition at line 304 of file NLHandler.h.
Referenced by myStartElement().
SUMOVehicleParameter* SUMORouteHandler::myVehicleParameter protected inherited
Parameter of the current vehicle, trip, person, container or flow.
Definition at line 154 of file SUMORouteHandler.h.
Referenced by SUMORouteHandler::addParam(), RORouteHandler::addPersonTrip(), MSRouteHandler::addStop(), RORouteHandler::addStop(), SUMORouteHandler::checkLastDepart(), MSRouteHandler::closeContainer(), RORouteHandler::closeContainer(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closePerson(), RORouteHandler::closePerson(), MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), SUMORouteHandler::myEndElement(), MSRouteHandler::myStartElement(), RORouteHandler::myStartElement(), SUMORouteHandler::myStartElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), RORouteHandler::openRouteDistribution(), MSRouteHandler::parseFromViaTo(), RORouteHandler::parseFromViaTo(), and SUMORouteHandler::registerLastDepart().
The documentation for this class was generated from the following files:
NLHandler.h
NLHandler.cpp