SUMO - Simulation of Urban MObility: TraCIServerAPI_Polygon Class Reference
TraCIServerAPI_Polygon Class Reference
APIs for getting/setting polygon values via TraCI.
#include <TraCIServerAPI_Polygon.h>
Static Public Member Functions
static bool getShape (const std::string &id, PositionVector &shape)
Returns the named polygons's shape.
static NamedRTree * getTree ()
Returns a tree filled with polygon instances.
static bool processGet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a get value command (Command 0xa8: Get Polygon Variable)
static bool processSet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a set value command (Command 0xc8: Change Polygon State)
Private Member Functions
TraCIServerAPI_Polygon & operator= (const TraCIServerAPI_Polygon &s)
invalidated assignment operator
TraCIServerAPI_Polygon (const TraCIServerAPI_Polygon &s)
invalidated copy constructor
Static Private Member Functions
static SUMO::Polygon * getPolygon (const std::string &id)
Returns the named polygon.
Detailed Description
APIs for getting/setting polygon values via TraCI.
Definition at line 48 of file TraCIServerAPI_Polygon.h.
Constructor & Destructor Documentation
TraCIServerAPI_Polygon::TraCIServerAPI_Polygon (const TraCIServerAPI_Polygon & s) private
invalidated copy constructor
Member Function Documentation
SUMO::Polygon * TraCIServerAPI_Polygon::getPolygon (const std::string & id) static private
Returns the named polygon.
Parameters
[in] id The id of the searched polygon
Returns
The named polygon, or 0 if it is not known
Definition at line 265 of file TraCIServerAPI_Polygon.cpp.
References NamedObjectCont< T >::get(), MSNet::getInstance(), ShapeContainer::getPolygons(), and MSNet::getShapeContainer().
Referenced by getShape(), processGet(), and processSet().
bool TraCIServerAPI_Polygon::getShape (const std::string & id, PositionVector & shape) static
Returns the named polygons's shape.
Parameters
[in] id The id of the searched polygon
[out] shape The shape, if the polygon is known
Returns
Whether the polygon is known
Definition at line 254 of file TraCIServerAPI_Polygon.cpp.
References getPolygon(), and SUMO::Polygon::getShape().
Referenced by TraCIServer::findObjectShape().
NamedRTree * TraCIServerAPI_Polygon::getTree () static
Returns a tree filled with polygon instances.
Returns
The rtree of polygons
Definition at line 271 of file TraCIServerAPI_Polygon.cpp.
References MSNet::getInstance(), NamedObjectCont< T >::getMyMap(), ShapeContainer::getPolygons(), MSNet::getShapeContainer(), NamedRTree::Insert(), Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by TraCIServer::collectObjectsInRange().
TraCIServerAPI_Polygon& TraCIServerAPI_Polygon::operator= (const TraCIServerAPI_Polygon & s) private
invalidated assignment operator
bool TraCIServerAPI_Polygon::processGet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a get value command (Command 0xa8: Get Polygon Variable)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 53 of file TraCIServerAPI_Polygon.cpp.
References RGBColor::alpha(), RGBColor::blue(), CMD_GET_POLYGON_VARIABLE, Shape::getColor(), SUMO::Polygon::getFill(), MSNet::getInstance(), Parameterised::getParameter(), getPolygon(), ShapeContainer::getPolygons(), SUMO::Polygon::getShape(), MSNet::getShapeContainer(), Shape::getType(), RGBColor::green(), ID_COUNT, ID_LIST, NamedObjectCont< T >::insertIDs(), MIN2(), tcpip::Storage::readString(), TraCIServer::readTypeCheckingString(), tcpip::Storage::readUnsignedByte(), RGBColor::red(), RESPONSE_GET_POLYGON_VARIABLE, RTYPE_OK, toHex(), TYPE_COLOR, TYPE_INTEGER, TYPE_POLYGON, TYPE_STRING, TYPE_STRINGLIST, TYPE_UBYTE, VAR_COLOR, VAR_FILL, VAR_PARAMETER, VAR_SHAPE, VAR_TYPE, tcpip::Storage::writeDouble(), TraCIServer::writeErrorStatusCmd(), tcpip::Storage::writeInt(), TraCIServer::writeResponseWithLength(), TraCIServer::writeStatusCmd(), tcpip::Storage::writeString(), tcpip::Storage::writeStringList(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCIServer::TraCIServer().
bool TraCIServerAPI_Polygon::processSet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a set value command (Command 0xc8: Change Polygon State)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 130 of file TraCIServerAPI_Polygon.cpp.
References ADD, Parameterised::addParameter(), ShapeContainer::addPolygon(), CMD_SET_POLYGON_VARIABLE, Shape::DEFAULT_ANGLE, Shape::DEFAULT_IMG_FILE, MSNet::getInstance(), getPolygon(), MSNet::getShapeContainer(), tcpip::Storage::readInt(), tcpip::Storage::readString(), TraCIServer::readTypeCheckingColor(), TraCIServer::readTypeCheckingInt(), TraCIServer::readTypeCheckingPolygon(), TraCIServer::readTypeCheckingString(), TraCIServer::readTypeCheckingUnsignedByte(), tcpip::Storage::readUnsignedByte(), REMOVE, ShapeContainer::removePolygon(), ShapeContainer::reshapePolygon(), RTYPE_OK, Shape::setColor(), SUMO::Polygon::setFill(), Shape::setType(), SUMOReal, toHex(), TYPE_COMPOUND, VAR_COLOR, VAR_FILL, VAR_PARAMETER, VAR_SHAPE, VAR_TYPE, TraCIServer::writeErrorStatusCmd(), and TraCIServer::writeStatusCmd().
Referenced by TraCIServer::TraCIServer().
The documentation for this class was generated from the following files:
TraCIServerAPI_Polygon.h
TraCIServerAPI_Polygon.cpp