SUMO - Simulation of Urban MObility: TraCIServerAPI_ArealDetector Class Reference
TraCIServerAPI_ArealDetector Class Reference
#include <TraCIServerAPI_ArealDetector.h>
Static Public Member Functions
static bool processGet (TraCIServer &server, tcpip::Storage &inputStorage, tcpip::Storage &outputStorage)
Processes a get value command (Command 0xa1: Get AreaDetector Variable)
Private Member Functions
TraCIServerAPI_ArealDetector & operator= (const TraCIServerAPI_ArealDetector &s)
invalidated assignment operator
TraCIServerAPI_ArealDetector (const TraCIServerAPI_ArealDetector &s)
invalidated copy constructor
Detailed Description
Definition at line 52 of file TraCIServerAPI_ArealDetector.h.
Constructor & Destructor Documentation
TraCIServerAPI_ArealDetector::TraCIServerAPI_ArealDetector (const TraCIServerAPI_ArealDetector & s) private
invalidated copy constructor
Member Function Documentation
TraCIServerAPI_ArealDetector& TraCIServerAPI_ArealDetector::operator= (const TraCIServerAPI_ArealDetector & s) private
invalidated assignment operator
bool TraCIServerAPI_ArealDetector::processGet (TraCIServer & server, tcpip::Storage & inputStorage, tcpip::Storage & outputStorage) static
Processes a get value command (Command 0xa1: Get AreaDetector Variable)
Parameters
[in] server The TraCI-server-instance which schedules this request
[in] inputStorage The storage to read the command from
[out] outputStorage The storage to write the result to
Definition at line 50 of file TraCIServerAPI_ArealDetector.cpp.
References CMD_GET_AREAL_DETECTOR_VARIABLE, NamedObjectCont< T >::get(), MSE2Collector::getCurrentHaltingNumber(), MSE2Collector::getCurrentJamLengthInMeters(), MSE2Collector::getCurrentJamLengthInVehicles(), MSE2Collector::getCurrentMeanSpeed(), MSE2Collector::getCurrentOccupancy(), MSE2Collector::getCurrentVehicleIDs(), MSE2Collector::getCurrentVehicleNumber(), MSNet::getDetectorControl(), MSE2Collector::getEndPos(), Named::getID(), MSNet::getInstance(), MSMoveReminder::getLane(), MSE2Collector::getStartPos(), MSDetectorControl::getTypedDetectors(), ID_COUNT, ID_LIST, NamedObjectCont< T >::insertIDs(), JAM_LENGTH_METERS, JAM_LENGTH_VEHICLE, LAST_STEP_MEAN_SPEED, LAST_STEP_OCCUPANCY, LAST_STEP_VEHICLE_HALTING_NUMBER, LAST_STEP_VEHICLE_ID_LIST, LAST_STEP_VEHICLE_NUMBER, tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), RESPONSE_GET_AREAL_DETECTOR_VARIABLE, RTYPE_OK, SUMO_TAG_LANE_AREA_DETECTOR, toHex(), TYPE_DOUBLE, TYPE_INTEGER, TYPE_STRING, TYPE_STRINGLIST, VAR_LANE_ID, VAR_LENGTH, VAR_POSITION, tcpip::Storage::writeDouble(), TraCIServer::writeErrorStatusCmd(), tcpip::Storage::writeInt(), TraCIServer::writeResponseWithLength(), TraCIServer::writeStatusCmd(), tcpip::Storage::writeString(), tcpip::Storage::writeStringList(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCIServer::TraCIServer().
The documentation for this class was generated from the following files:
TraCIServerAPI_ArealDetector.h
TraCIServerAPI_ArealDetector.cpp