SUMO - Simulation of Urban MObility: MFXUtils Class Reference
MFXUtils Class Reference
Some helper functions for FOX.
#include <MFXUtils.h>
Static Public Member Functions
static FXString assureExtension (const FXString &filename, const FXString &defaultExtension)
Corrects missing extension.
static void deleteChildren (FXWindow *w)
Deletes all children of the given window.
static FXString getDocumentName (const FXString &filename)
Returns the document name.
static FXString getFilename2Write (FXWindow *parent, const FXString &header, const FXString &extension, FXIcon *icon, FXString &currentFolder)
Returns the file name to write.
static FXColor getFXColor (const RGBColor &col)
converts FXColor to RGBColor
static RGBColor getRGBColor (FXColor col)
converts FXColor to RGBColor
static FXString getTitleText (const FXString &appname, FXString filename="")
Returns the title text in dependance to an optional file name.
static FXbool userPermitsOverwritingWhenFileExists (FXWindow *const parent, const FXString &file)
Returns true if either the file given by its name does not exist or the user allows overwriting it.
Detailed Description
Some helper functions for FOX.
Definition at line 47 of file MFXUtils.h.
Member Function Documentation
FXString MFXUtils::assureExtension (const FXString & filename, const FXString & defaultExtension) static
Corrects missing extension.
At first, the extension is determined. If there is none, the given default extension is appended to the file name/path. Otherwise the file name/path remains as is. The so obtained correct file name is returned.
Parameters
[in] filename The filename to evaluate
[in] defaultExtension The default extension to use
Returns
The corrected filename (with extension if no one was given
Definition at line 82 of file MFXUtils.cpp.
Referenced by getFilename2Write().
void MFXUtils::deleteChildren (FXWindow * w) static
Deletes all children of the given window.
Parameters
[in] w The window to delete all of his children
Definition at line 43 of file MFXUtils.cpp.
Referenced by GUIDialog_ViewSettings::rebuildColorMatrix(), and GUIDialog_ViewSettings::rebuildScaleMatrix().
FXString MFXUtils::getDocumentName (const FXString & filename) static
Returns the document name.
Removes the path first. Then, returns the part before the first '.' occurence of the so obtained string.
Parameters
[in] filename The file name (including the path) to obtain the name of
Returns
The name (without the path and the extension)
Definition at line 67 of file MFXUtils.cpp.
Referenced by getTitleText().
FXString MFXUtils::getFilename2Write (FXWindow * parent, const FXString & header, const FXString & extension, FXIcon * icon, FXString & currentFolder) static
Returns the file name to write.
A somehow complete procedure for determining the file name of a file to write. Builds a file dialog, checks whether a file was chosen, if so, checks whether it's not existing or the user allows to overwrite it etc.
Returns an empty string if the file shall not be created, the filename if it shall.
Parameters
[in] parent The window needed to display dialogs
[in] header Title of the save-dialog
[in] extension The extension the file should have (must be in the form '.xxx'
[in] icon The icon the dialog should have
[in] currentFolder The string into which the information about the current folder shall be saved
Returns
The name of the file to write
Definition at line 95 of file MFXUtils.cpp.
References assureExtension(), text(), and userPermitsOverwritingWhenFileExists().
Referenced by GUIDialog_ViewSettings::onCmdExportSetting(), GUIDialog_Breakpoints::onCmdSave(), GNESelectorFrame::onCmdSave(), GUIDialog_EditViewport::onCmdSave(), GUIParameterTracker::onCmdSave(), GUIDialog_GLChosenEditor::onCmdSave(), GNEApplicationWindow::onCmdSaveAdditionals(), GNEApplicationWindow::onCmdSaveAsNetwork(), GNEApplicationWindow::onCmdSaveAsPlainXML(), GUIDialog_ViewSettings::onCmdSaveDecals(), GNEApplicationWindow::onCmdSaveJoined(), and GNEApplicationWindow::onCmdSavePois().
FXColor MFXUtils::getFXColor (const RGBColor & col) static
converts FXColor to RGBColor
Definition at line 125 of file MFXUtils.cpp.
References RGBColor::alpha(), RGBColor::blue(), RGBColor::green(), and RGBColor::red().
Referenced by GNEInternalLane::getPopUpMenu(), GNELane::getPopUpMenu(), GNEConnectorFrame::GNEConnectorFrame(), GUIDialog_ViewSettings::GUIDialog_ViewSettings(), GUIDialog_ViewSettings::NamePanel::NamePanel(), GUIApplicationWindow::onCmdGaming(), GUIDialog_ViewSettings::onCmdNameChange(), GUIDialog_ViewSettings::rebuildColorMatrix(), and GUIDialog_ViewSettings::NamePanel::update().
RGBColor MFXUtils::getRGBColor (FXColor col) static
converts FXColor to RGBColor
Definition at line 119 of file MFXUtils.cpp.
Referenced by GUIDialog_ViewSettings::NamePanel::getSettings(), GUIDialog_ViewSettings::onCmdColorChange(), and GUIDialog_ViewSettings::updateColorRanges().
FXString MFXUtils::getTitleText (const FXString & appname, FXString filename = "") static
Returns the title text in dependance to an optional file name.
The title is computed as default on windows: The application name only if no file name is given. If a file name is given, it is used without the extension, extended by the application name.
Parameters
[in] appname The name of the application to return the title of
[in] appname The name of the file loaded by the application
Returns
The built title
Definition at line 73 of file MFXUtils.cpp.
References getDocumentName().
Referenced by GUIApplicationWindow::closeAllWindows(), GUIApplicationWindow::dependentBuild(), GNEApplicationWindow::handleEvent_NetworkLoaded(), GUIApplicationWindow::handleEvent_SimulationLoaded(), and GNEApplicationWindow::onCmdSaveAsNetwork().
FXbool MFXUtils::userPermitsOverwritingWhenFileExists (FXWindow *const parent, const FXString & file) static
Returns true if either the file given by its name does not exist or the user allows overwriting it.
If the named file does not exist, true is returned. Otherwise, a message box is prompted that asks whether the file may be replaced. If the user answers "yes" in this case, true is returned. In any other cases ("no"/"cancel"), false.
Parameters
[in] parent A parent window needed to prompt the dialog box
[in] file The file to check whether it may be generated
Returns
Whether the named file may be written
Definition at line 52 of file MFXUtils.cpp.
Referenced by getFilename2Write(), GUISUMOViewParent::onCmdMakeSnapshot(), and GNEViewParent::onCmdMakeSnapshot().
The documentation for this class was generated from the following files:
MFXUtils.h
MFXUtils.cpp