SUMO - Simulation of Urban MObility: SUMORouteHandler Class Reference
SUMORouteHandler Class Reference abstract
Parser for routes during their loading.
#include <SUMORouteHandler.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
SUMOTime getFirstDepart () const
returns the first departure time that was ever read
SUMOTime getLastDepart () const
Returns the last loaded depart time.
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
SUMORouteHandler (const std::string &file)
standard constructor
virtual ~SUMORouteHandler ()
standard destructor
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Static Public Member Functions
static bool checkStopPos (SUMOReal &startPos, SUMOReal &endPos, const SUMOReal laneLength, const SUMOReal minLength, const bool friendlyPos)
check start and end position of a stop
Protected Member Functions
void addParam (const SUMOSAXAttributes &attrs)
assign arbitrary vehicle parameters
virtual void addStop (const SUMOSAXAttributes &attrs)=0
Processing of a stop.
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
bool checkLastDepart ()
Checks whether the route file is sorted by departure time if needed.
virtual void closeContainer ()=0
Ends the processing of a container.
virtual void closeFlow ()=0
Ends the processing of a flow.
virtual void closePerson ()=0
Ends the processing of a person.
virtual void closeRoute (const bool mayBeDisconnected=false)=0
virtual void closeRouteDistribution ()=0
virtual void closeVehicle ()=0
Ends the processing of a vehicle.
virtual void closeVehicleTypeDistribution ()=0
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
virtual void openRoute (const SUMOSAXAttributes &attrs)=0
virtual void openRouteDistribution (const SUMOSAXAttributes &attrs)=0
virtual void openVehicleTypeDistribution (const SUMOSAXAttributes &attrs)=0
bool parseStop (SUMOVehicleParameter::Stop &stop, const SUMOSAXAttributes &attrs, std::string errorSuffix, MsgHandler *const errorOutput)
parses attributes common to all stops
void registerLastDepart ()
save last depart (only to be used if vehicle is not discarded)
inherited from GenericSAXHandler
virtual void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
virtual void myEndElement (int element)
Called when a closing tag occurs.
Protected Attributes
const RGBColor * myActiveRouteColor
The currently parsed route's color.
std::string myActiveRouteID
The id of the current route.
SUMOReal myActiveRouteProbability
The probability of the current route.
std::string myActiveRouteRefID
The id of the route the current route references to.
std::vector< SUMOVehicleParameter::Stop > myActiveRouteStops
List of the stops on the parsed route.
SUMOTime myBeginDefault
The default value for flow begins.
SUMOReal myCurrentCosts
The currently parsed route costs.
SUMOVTypeParameter * myCurrentVType
The currently parsed vehicle type.
SUMOTime myEndDefault
The default value for flow ends.
SUMOTime myFirstDepart
the first read departure time
IDSupplier myIdSupplier
generates numerical ids
int myInsertStopEdgesAt
where stop edges can be inserted into the current route (-1 means no insertion)
SUMOTime myLastDepart
The insertion time of the vehicle read last.
SUMOVehicleParameter * myVehicleParameter
Parameter of the current vehicle, trip, person, container or flow.
Private Member Functions
SUMORouteHandler & operator= (const SUMORouteHandler &s)
Invalidated assignment operator.
SUMORouteHandler (const SUMORouteHandler &s)
Invalidated copy constructor.
Detailed Description
Parser for routes during their loading.
SUMORouteHandler is the abstract super class for routers and simulation loading routes.
Definition at line 58 of file SUMORouteHandler.h.
Constructor & Destructor Documentation
SUMORouteHandler::SUMORouteHandler (const std::string & file)
standard constructor
Definition at line 54 of file SUMORouteHandler.cpp.
SUMORouteHandler::~SUMORouteHandler () virtual
standard destructor
Definition at line 66 of file SUMORouteHandler.cpp.
References myCurrentVType.
SUMORouteHandler::SUMORouteHandler (const SUMORouteHandler & s) private
Invalidated copy constructor.
Member Function Documentation
void SUMORouteHandler::addParam (const SUMOSAXAttributes & attrs) protected
assign arbitrary vehicle parameters
Definition at line 249 of file SUMORouteHandler.cpp.
References Parameterised::addParameter(), SUMOSAXAttributes::get(), SUMOSAXAttributes::getString(), SUMOSAXAttributes::hasAttribute(), myCurrentVType, myVehicleParameter, SUMO_ATTR_KEY, and SUMO_ATTR_VALUE.
Referenced by getFirstDepart(), and myStartElement().
virtual void SUMORouteHandler::addStop (const SUMOSAXAttributes & attrs) protected pure virtual
Processing of a stop.
Implemented in RORouteHandler, and MSRouteHandler.
Referenced by getFirstDepart(), and myStartElement().
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 192 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 175 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
bool SUMORouteHandler::checkLastDepart () protected
Checks whether the route file is sorted by departure time if needed.
Definition at line 78 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, SUMOVehicleParameter::id, myLastDepart, myVehicleParameter, and WRITE_WARNING.
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closeFlow(), MSRouteHandler::closePerson(), MSRouteHandler::closeVehicle(), and getFirstDepart().
bool SUMORouteHandler::checkStopPos (SUMOReal & startPos, SUMOReal & endPos, const SUMOReal laneLength, const SUMOReal minLength, const bool friendlyPos) static
check start and end position of a stop
Definition at line 211 of file SUMORouteHandler.cpp.
Referenced by NLTriggerBuilder::addAccess(), MSRouteHandler::addStop(), RORouteHandler::addStop(), NLTriggerBuilder::parseAndBuildChargingStation(), NLTriggerBuilder::parseAndBuildStoppingPlace(), and RONetHandler::parseStoppingPlace().
virtual void SUMORouteHandler::closeContainer () protected pure virtual
Ends the processing of a container.
Implemented in RORouteHandler, and MSRouteHandler.
Referenced by getFirstDepart(), and myEndElement().
virtual void SUMORouteHandler::closeFlow () protected pure virtual
Ends the processing of a flow.
Implemented in RORouteHandler, and MSRouteHandler.
Referenced by getFirstDepart(), and myEndElement().
virtual void SUMORouteHandler::closePerson () protected pure virtual
Ends the processing of a person.
Implemented in RORouteHandler, and MSRouteHandler.
Referenced by getFirstDepart(), and myEndElement().
virtual void SUMORouteHandler::closeRoute (const bool mayBeDisconnected = false) protected pure virtual
closes (ends) the building of a route. Afterwards no edges may be added to it; this method may throw exceptions when a) the route is empty or b) another route with the same id already exists
Implemented in RORouteHandler, and MSRouteHandler.
Referenced by getFirstDepart(), and myEndElement().
virtual void SUMORouteHandler::closeRouteDistribution () protected pure virtual
closes (ends) the building of a distribution
Implemented in RORouteHandler, and MSRouteHandler.
Referenced by getFirstDepart(), and myEndElement().
virtual void SUMORouteHandler::closeVehicle () protected pure virtual
Ends the processing of a vehicle.
Implemented in RORouteHandler, and MSRouteHandler.
Referenced by getFirstDepart(), and myEndElement().
virtual void SUMORouteHandler::closeVehicleTypeDistribution () protected pure virtual
closes (ends) the building of a distribution
Implemented in RORouteHandler, and MSRouteHandler.
Referenced by getFirstDepart(), and myEndElement().
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 211 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), MSRouteHandler::myStartElement(), and MSRouteHandler::parseWalkPos().
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 217 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), MSStateHandler::myStartElement(), myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
SUMOTime SUMORouteHandler::getFirstDepart () const inline
returns the first departure time that was ever read
Definition at line 74 of file SUMORouteHandler.h.
References addParam(), addStop(), checkLastDepart(), closeContainer(), closeFlow(), closePerson(), closeRoute(), closeRouteDistribution(), closeVehicle(), closeVehicleTypeDistribution(), myEndElement(), myFirstDepart, myStartElement(), openRoute(), openRouteDistribution(), openVehicleTypeDistribution(), parseStop(), and registerLastDepart().
Referenced by SUMORouteLoader::getFirstDepart().
SUMOTime SUMORouteHandler::getLastDepart () const
Returns the last loaded depart time.
Definition at line 72 of file SUMORouteHandler.cpp.
References myLastDepart.
Referenced by SUMORouteLoader::loadUntil().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 227 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void SUMORouteHandler::myEndElement (int element) protected virtual
Called when a closing tag occurs.
Parameters
[in] element ID of the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myEndElement
Reimplemented from GenericSAXHandler.
Reimplemented in NLHandler, MSCalibrator, RORouteHandler, and MSRouteHandler.
Definition at line 163 of file SUMORouteHandler.cpp.
References closeContainer(), closeFlow(), closePerson(), closeRoute(), closeRouteDistribution(), closeVehicle(), closeVehicleTypeDistribution(), SUMOVehicleParserHelper::closeVTypeParsing(), OptionsCont::getOptions(), myBeginDefault, myCurrentVType, myEndDefault, myVehicleParameter, SUMOVehicleParameter::repetitionNumber, string2time(), SUMO_TAG_CONTAINER, SUMO_TAG_FLOW, SUMO_TAG_INTERVAL, SUMO_TAG_PERSON, SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_DISTRIBUTION, SUMO_TAG_VEHICLE, SUMO_TAG_VTYPE, and SUMO_TAG_VTYPE_DISTRIBUTION.
Referenced by getFirstDepart(), MSRouteHandler::myEndElement(), and RORouteHandler::myEndElement().
void SUMORouteHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails
See also
GenericSAXHandler::myStartElement
Reimplemented from GenericSAXHandler.
Reimplemented in NLHandler, MSCalibrator, RORouteHandler, and MSRouteHandler.
Definition at line 103 of file SUMORouteHandler.cpp.
References addParam(), addStop(), SUMOVehicleParserHelper::beginVTypeParsing(), GenericSAXHandler::getFileName(), IDSupplier::getNext(), SUMOSAXAttributes::getSUMOTimeReporting(), SUMOVehicleParameter::id, myActiveRouteID, myBeginDefault, myCurrentVType, myEndDefault, myIdSupplier, myVehicleParameter, openRoute(), openRouteDistribution(), openVehicleTypeDistribution(), SUMOVehicleParserHelper::parseFlowAttributes(), SUMOVehicleParserHelper::parseVehicleAttributes(), SUMOVehicleParameter::setParameter, SUMO_ATTR_BEGIN, SUMO_ATTR_END, SUMO_TAG_CONTAINER, SUMO_TAG_FLOW, SUMO_TAG_INTERVAL, SUMO_TAG_PARAM, SUMO_TAG_PERSON, SUMO_TAG_ROUTE, SUMO_TAG_ROUTE_DISTRIBUTION, SUMO_TAG_STOP, SUMO_TAG_TRIP, SUMO_TAG_VEHICLE, SUMO_TAG_VTYPE, SUMO_TAG_VTYPE_DISTRIBUTION, and VEHPARS_FORCE_REROUTE.
Referenced by getFirstDepart(), MSRouteHandler::myStartElement(), and RORouteHandler::myStartElement().
virtual void SUMORouteHandler::openRoute (const SUMOSAXAttributes & attrs) protected pure virtual
opens a route for reading
Implemented in RORouteHandler, and MSRouteHandler.
Referenced by getFirstDepart(), and myStartElement().
virtual void SUMORouteHandler::openRouteDistribution (const SUMOSAXAttributes & attrs) protected pure virtual
opens a route distribution for reading
Implemented in RORouteHandler, and MSRouteHandler.
Referenced by getFirstDepart(), and myStartElement().
virtual void SUMORouteHandler::openVehicleTypeDistribution (const SUMOSAXAttributes & attrs) protected pure virtual
opens a type distribution for reading
Implemented in RORouteHandler, and MSRouteHandler.
Referenced by getFirstDepart(), and myStartElement().
SUMORouteHandler& SUMORouteHandler::operator= (const SUMORouteHandler & s) private
Invalidated assignment operator.
bool SUMORouteHandler::parseStop (SUMOVehicleParameter::Stop & stop, const SUMOSAXAttributes & attrs, std::string errorSuffix, MsgHandler *const errorOutput) protected
parses attributes common to all stops
Definition at line 263 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::Stop::awaitedContainers, SUMOVehicleParameter::Stop::awaitedPersons, SUMOVehicleParameter::Stop::busstop, SUMOVehicleParameter::Stop::chargingStation, SUMOVehicleParameter::Stop::containerstop, SUMOVehicleParameter::Stop::containerTriggered, SUMOVehicleParameter::Stop::duration, SUMOSAXAttributes::get(), SUMOSAXAttributes::getOpt(), SUMOSAXAttributes::getOptSUMOTimeReporting(), SUMOSAXAttributes::hasAttribute(), SUMOVehicleParameter::Stop::index, MsgHandler::inform(), SUMOVehicleParameter::Stop::lane, SUMOVehicleParameter::Stop::parking, SUMOSAXAttributes::parseStringSet(), SUMOVehicleParameter::Stop::setParameter, STOP_CONTAINER_TRIGGER_SET, STOP_END_SET, STOP_EXPECTED_CONTAINERS_SET, STOP_EXPECTED_SET, STOP_INDEX_END, STOP_INDEX_FIT, STOP_PARKING_SET, STOP_START_SET, STOP_TRIGGER_SET, SUMO_ATTR_BUS_STOP, SUMO_ATTR_CHARGING_STATION, SUMO_ATTR_CONTAINER_STOP, SUMO_ATTR_CONTAINER_TRIGGERED, SUMO_ATTR_DURATION, SUMO_ATTR_ENDPOS, SUMO_ATTR_EXPECTED, SUMO_ATTR_EXPECTED_CONTAINERS, SUMO_ATTR_INDEX, SUMO_ATTR_PARKING, SUMO_ATTR_STARTPOS, SUMO_ATTR_TRIGGERED, SUMO_ATTR_UNTIL, SUMOVehicleParameter::Stop::triggered, and SUMOVehicleParameter::Stop::until.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), and getFirstDepart().
void SUMORouteHandler::registerLastDepart () protected
save last depart (only to be used if vehicle is not discarded)
Definition at line 90 of file SUMORouteHandler.cpp.
References SUMOVehicleParameter::depart, DEPART_GIVEN, SUMOVehicleParameter::departProcedure, SUMOVehicleParameter::line, myFirstDepart, myLastDepart, and myVehicleParameter.
Referenced by MSRouteHandler::closeContainer(), RORouteHandler::closeContainer(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closePerson(), RORouteHandler::closePerson(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), and getFirstDepart().
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 167 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 205 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
const RGBColor* SUMORouteHandler::myActiveRouteColor protected
The currently parsed route's color.
Definition at line 169 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
std::string SUMORouteHandler::myActiveRouteID protected
The id of the current route.
Definition at line 160 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::closeVehicle(), MSRouteHandler::myStartElement(), myStartElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::parseFromViaTo(), and RORouteHandler::parseFromViaTo().
SUMOReal SUMORouteHandler::myActiveRouteProbability protected
The probability of the current route.
Definition at line 166 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), RORouteHandler::myStartElement(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
std::string SUMORouteHandler::myActiveRouteRefID protected
The id of the route the current route references to.
Definition at line 163 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
std::vector<SUMOVehicleParameter::Stop> SUMORouteHandler::myActiveRouteStops protected
List of the stops on the parsed route.
Definition at line 175 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::closeRoute(), and RORouteHandler::closeRoute().
SUMOTime SUMORouteHandler::myBeginDefault protected
The default value for flow begins.
Definition at line 184 of file SUMORouteHandler.h.
Referenced by myEndElement(), and myStartElement().
SUMOReal SUMORouteHandler::myCurrentCosts protected
The currently parsed route costs.
Definition at line 172 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::openRoute(), and RORouteHandler::openRoute().
SUMOVTypeParameter* SUMORouteHandler::myCurrentVType protected
The currently parsed vehicle type.
Definition at line 178 of file SUMORouteHandler.h.
Referenced by addParam(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), myEndElement(), MSRouteHandler::myStartElement(), RORouteHandler::myStartElement(), myStartElement(), and ~SUMORouteHandler().
SUMOTime SUMORouteHandler::myEndDefault protected
The default value for flow ends.
Definition at line 187 of file SUMORouteHandler.h.
Referenced by myEndElement(), and myStartElement().
SUMOTime SUMORouteHandler::myFirstDepart protected
the first read departure time
Definition at line 190 of file SUMORouteHandler.h.
Referenced by getFirstDepart(), and registerLastDepart().
IDSupplier SUMORouteHandler::myIdSupplier protected
generates numerical ids
Definition at line 181 of file SUMORouteHandler.h.
Referenced by myStartElement().
int SUMORouteHandler::myInsertStopEdgesAt protected
where stop edges can be inserted into the current route (-1 means no insertion)
Definition at line 193 of file SUMORouteHandler.h.
Referenced by MSRouteHandler::addStop(), RORouteHandler::addStop(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::parseFromViaTo(), and RORouteHandler::parseFromViaTo().
SUMOTime SUMORouteHandler::myLastDepart protected
The insertion time of the vehicle read last.
Definition at line 157 of file SUMORouteHandler.h.
Referenced by checkLastDepart(), getLastDepart(), and registerLastDepart().
SUMOVehicleParameter* SUMORouteHandler::myVehicleParameter protected
Parameter of the current vehicle, trip, person, container or flow.
Definition at line 154 of file SUMORouteHandler.h.
Referenced by addParam(), RORouteHandler::addPersonTrip(), MSRouteHandler::addStop(), RORouteHandler::addStop(), checkLastDepart(), MSRouteHandler::closeContainer(), RORouteHandler::closeContainer(), MSRouteHandler::closeFlow(), RORouteHandler::closeFlow(), MSRouteHandler::closePerson(), RORouteHandler::closePerson(), MSRouteHandler::closeRoute(), RORouteHandler::closeRoute(), MSRouteHandler::closeRouteDistribution(), MSRouteHandler::closeVehicle(), RORouteHandler::closeVehicle(), MSRouteHandler::myEndElement(), RORouteHandler::myEndElement(), myEndElement(), MSRouteHandler::myStartElement(), RORouteHandler::myStartElement(), myStartElement(), MSRouteHandler::openRoute(), RORouteHandler::openRoute(), MSRouteHandler::openRouteDistribution(), RORouteHandler::openRouteDistribution(), MSRouteHandler::parseFromViaTo(), RORouteHandler::parseFromViaTo(), and registerLastDepart().
The documentation for this class was generated from the following files:
SUMORouteHandler.h
SUMORouteHandler.cpp