SUMO - Simulation of Urban MObility: NBHelpers Class Reference
NBHelpers Class Reference
#include <NBHelpers.h>
Static Public Member Functions
static SUMOReal distance (NBNode *node1, NBNode *node2)
static void loadEdgesFromFile (const std::string &file, std::set< std::string > &into)
Add edge ids defined in file (either ID or edge::ID per line) into the given set.
static std::string normalIDRepresentation (const std::string &id)
static SUMOReal normRelAngle (SUMOReal angle1, SUMOReal angle2)
ensure that reverse relAngles (>=179.999) always count as turnarounds (-180)
static SUMOReal relAngle (SUMOReal angle1, SUMOReal angle2)
Detailed Description
Some mathmatical methods for the computation of angles
Definition at line 54 of file NBHelpers.h.
Member Function Documentation
SUMOReal NBHelpers::distance (NBNode * node1, NBNode * node2) static
returns the distance between both nodes
Definition at line 91 of file NBHelpers.cpp.
References Position::distanceTo(), and NBNode::getPosition().
void NBHelpers::loadEdgesFromFile (const std::string & file, std::set< std::string > & into) static
Add edge ids defined in file (either ID or edge::ID per line) into the given set.
Definition at line 97 of file NBHelpers.cpp.
References StringUtils::startsWith().
Referenced by NBEdgeCont::applyOptions(), and NBNodeCont::removeUnwishedNodes().
std::string NBHelpers::normalIDRepresentation (const std::string & id) static
converts the numerical id to its "normal" string representation
Definition at line 80 of file NBHelpers.cpp.
References SUMOReal.
Referenced by NIImporter_VISUM::getNamedEdge(), NIImporter_VISUM::getNamedEdgeContinuating(), NIImporter_VISUM::getNamedFloat(), NIImporter_VISUM::getNamedNode(), NIImporter_VISUM::getNamedString(), NIImporter_VISUM::parse_Connectors(), NIImporter_VISUM::parse_Districts(), NIImporter_VISUM::parse_Edges(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Nodes(), NIImporter_VISUM::parse_Phases(), NIImporter_VISUM::parse_SignalGroups(), NIImporter_VISUM::parse_SignalGroupsToPhases(), NIImporter_VISUM::parse_TrafficLights(), and NIImporter_VISUM::parse_Types().
SUMOReal NBHelpers::normRelAngle (SUMOReal angle1, SUMOReal angle2) static
ensure that reverse relAngles (>=179.999) always count as turnarounds (-180)
Definition at line 69 of file NBHelpers.cpp.
References NUMERICAL_EPS, relAngle(), and SUMOReal.
Referenced by NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NBNode::getDirection(), NBContHelper::same_connection_edge_sorter::getMinMaxRelAngles(), NBContHelper::relative_outgoing_edge_sorter::operator()(), NBContHelper::straightness_sorter::operator()(), and NBContHelper::relative_incoming_edge_sorter::operator()().
SUMOReal NBHelpers::relAngle (SUMOReal angle1, SUMOReal angle2) static
computes the relative angle between the two angles
Definition at line 56 of file NBHelpers.cpp.
References SUMOReal.
Referenced by NBNode::buildCrossings(), NBOwnTLDef::computeLogicAndConts(), NBNode::geometryLike(), NBEdgeCont::guessRoundabouts(), NBRequest::laneConflict(), and normRelAngle().
The documentation for this class was generated from the following files:
NBHelpers.h
NBHelpers.cpp