SUMO - Simulation of Urban MObility: GNEInspectorFrame::AttrEditor Class Reference
GNEInspectorFrame::AttrEditor Class Reference
#include <GNEInspectorFrame.h>
Public Member Functions
AttrEditor (AttrInput *attrInputParent, FXTextField *textFieldAttr)
FOX-declaration.
long onCmdReset (FXObject *, FXSelector, void *)
call when user press button reset
~AttrEditor ()
destructor
Protected Member Functions
AttrEditor ()
FOX needs this.
Private Attributes
FXHorizontalFrame * frameButtons
frame for the buttons
FXButton * myAcceptButton
Button Accept.
AttrInput * myAttrInputParent
Pointer to AttrInput parent.
FXButton * myCancelButton
Button Cancel.
FXMatrix * myCheckBoxMatrix
FXButton * myResetButton
Button Reset.
FXTextField * myTextFieldAttr
std::vector< FXCheckButton * > myVectorOfCheckBox
vector of CheckBoxs
Detailed Description
Definition at line 132 of file GNEInspectorFrame.h.
Constructor & Destructor Documentation
GNEInspectorFrame::AttrEditor::AttrEditor (AttrInput * attrInputParent, FXTextField * textFieldAttr)
FOX-declaration.
constructor
Definition at line 542 of file GNEInspectorFrame.cpp.
References GNEAttributeCarrier::discreteChoices(), frameButtons, GNEInspectorFrame::AttrInput::getAttr(), GNEInspectorFrame::AttrInput::getTag(), joinToString(), MID_GNE_MODE_INSPECT_RESET, myAcceptButton, myAttrInputParent, myCancelButton, myCheckBoxMatrix, myResetButton, myTextFieldAttr, myVectorOfCheckBox, and GNEInspectorFrame::AttrInput::onCmdSetAttribute().
GNEInspectorFrame::AttrEditor::~AttrEditor ()
destructor
Definition at line 601 of file GNEInspectorFrame.cpp.
GNEInspectorFrame::AttrEditor::AttrEditor () inline protected
FOX needs this.
Definition at line 148 of file GNEInspectorFrame.h.
Member Function Documentation
long GNEInspectorFrame::AttrEditor::onCmdReset (FXObject * , FXSelector , void *)
call when user press button reset
Definition at line 604 of file GNEInspectorFrame.cpp.
References GNEAttributeCarrier::discreteChoices(), GNEInspectorFrame::AttrInput::getAttr(), GNEInspectorFrame::AttrInput::getTag(), myAttrInputParent, myTextFieldAttr, and myVectorOfCheckBox.
Field Documentation
FXHorizontalFrame* GNEInspectorFrame::AttrEditor::frameButtons private
frame for the buttons
Definition at line 164 of file GNEInspectorFrame.h.
Referenced by AttrEditor().
FXButton* GNEInspectorFrame::AttrEditor::myAcceptButton private
Button Accept.
Definition at line 167 of file GNEInspectorFrame.h.
Referenced by AttrEditor().
AttrInput* GNEInspectorFrame::AttrEditor::myAttrInputParent private
Pointer to AttrInput parent.
Definition at line 152 of file GNEInspectorFrame.h.
Referenced by AttrEditor(), and onCmdReset().
FXButton* GNEInspectorFrame::AttrEditor::myCancelButton private
Button Cancel.
Definition at line 170 of file GNEInspectorFrame.h.
Referenced by AttrEditor().
FXMatrix* GNEInspectorFrame::AttrEditor::myCheckBoxMatrix private
Definition at line 158 of file GNEInspectorFrame.h.
Referenced by AttrEditor().
FXButton* GNEInspectorFrame::AttrEditor::myResetButton private
Button Reset.
Definition at line 173 of file GNEInspectorFrame.h.
Referenced by AttrEditor().
FXTextField* GNEInspectorFrame::AttrEditor::myTextFieldAttr private
Definition at line 155 of file GNEInspectorFrame.h.
Referenced by AttrEditor(), and onCmdReset().
std::vector<FXCheckButton*> GNEInspectorFrame::AttrEditor::myVectorOfCheckBox private
vector of CheckBoxs
Definition at line 161 of file GNEInspectorFrame.h.
Referenced by AttrEditor(), and onCmdReset().
The documentation for this class was generated from the following files:
GNEInspectorFrame.h
GNEInspectorFrame.cpp