SUMO - Simulation of Urban MObility: MSActuatedTrafficLightLogic Class Reference
MSActuatedTrafficLightLogic Class Reference
An actuated (adaptive) traffic light logic.
#include <MSActuatedTrafficLightLogic.h>
Public Types
typedef std::map< MSLane *, MSDetectorFileOutput * > InductLoopMap
Definition of a map from lanes to induct loops lying on them.
Structure definitions
typedef std::vector< MSPhaseDefinition * > Phases
Definition of a list of phases, being the junction logic.
typedef std::vector< MSLink * > LinkVector
Definition of the list of links that participate in this tl-light.
typedef std::vector< LinkVector > LinkVectorVector
Definition of a list that holds lists of links that do have the same attribute.
typedef std::vector< MSLane * > LaneVector
Definition of the list of links that participate in this tl-light.
typedef std::vector< LaneVector > LaneVectorVector
Definition of a list that holds lists of links that do have the same attribute.
Public Member Functions
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
void clearParameter ()
Clears the parameter map.
const std::string & getID () const
Returns the id.
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
void init (NLDetectorBuilder &nb)
Initialises the tls with information about incoming lanes.
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
MSActuatedTrafficLightLogic (MSTLLogicControl &tlcontrol, const std::string &id, const std::string &programID, const MSSimpleTrafficLightLogic::Phases &phases, int step, SUMOTime delay, const std::map< std::string, std::string > &parameter, const std::string &basePath)
Constructor.
void setID (const std::string &newID)
resets the id
~MSActuatedTrafficLightLogic ()
Destructor.
Switching and setting current rows
SUMOTime trySwitch ()
Switches to the next phase.
Static Information Retrieval
int getPhaseNumber () const
Returns the number of phases.
const Phases & getPhases () const
Returns the phases of this tls program.
Phases & getPhases ()
Returns the phases of this tls program.
const MSPhaseDefinition & getPhase (int givenstep) const
Returns the definition of the phase from the given position within the plan.
const std::string getLogicType () const
Returns the type of the logic as a string.
Dynamic Information Retrieval
int getCurrentPhaseIndex () const
Returns the current index within the program.
const MSPhaseDefinition & getCurrentPhaseDef () const
Returns the definition of the current phase.
Conversion between time and phase
SUMOTime getPhaseIndexAtTime (SUMOTime simStep) const
Returns the index of the logic at the given simulation step.
SUMOTime getOffsetFromIndex (int index) const
Returns the position (start of a phase during a cycle) from of a given step.
int getIndexFromOffset (SUMOTime offset) const
Returns the step (the phasenumber) of a given position of the cycle.
Changing phases and phase durations
void changeStepAndDuration (MSTLLogicControl &tlcontrol, SUMOTime simStep, int step, SUMOTime stepDuration)
Changes the current phase and her duration.
void setPhases (const Phases &phases, int index)
Replaces the phases and set the phase index.
Handling of controlled links
virtual void addLink (MSLink *link, MSLane *lane, int pos)
Adds a link on building.
virtual void adaptLinkInformationFrom (const MSTrafficLightLogic &logic)
Applies information about controlled links and lanes from the given logic.
std::map< MSLink *, LinkState > collectLinkStates () const
Returns the (uncontrolled) states of the controlled links.
void resetLinkStates (const std::map< MSLink *, LinkState > &vals) const
Resets the states of controlled links.
Switching and setting current rows
bool setTrafficLightSignals (SUMOTime t) const
Applies the current signal states to controlled links.
Static Information Retrieval
const std::string & getProgramID () const
Returns this tl-logic's id.
const LaneVectorVector & getLaneVectors () const
Returns the list of lists of all lanes controlled by this tls.
const LaneVector & getLanesAt (int i) const
Returns the list of lanes that are controlled by the signals at the given position.
const LinkVectorVector & getLinks () const
Returns the list of lists of all affected links.
const LinkVector & getLinksAt (int i) const
Returns the list of links that are controlled by the signals at the given position.
int getLinkIndex (const MSLink *const link) const
Returns the index of the given link.
Dynamic Information Retrieval
SUMOTime getDefaultCycleTime () const
Returns the cycle time (in ms)
SUMOTime getNextSwitchTime () const
Returns the assumed next switch time.
Changing phases and phase durations
void addOverridingDuration (SUMOTime duration)
Changes the duration of the next phase.
void setCurrentDurationIncrement (SUMOTime delay)
Delays current phase by the given delay.
Static Public Member Functions
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
Protected Member Functions
"actuated" algorithm methods
SUMOTime duration (const SUMOReal detectionGap) const
Returns the minimum duration of the current phase.
SUMOReal gapControl ()
Return the minimum detection gap of all detectors if the current phase should be extended and SUMOReal::max otherwise.
Protected Attributes
SUMOTime myCurrentDurationIncrement
A value for enlarge the current duration.
SUMOTime myDefaultCycleTime
The cycle time (without changes)
SUMOReal myDetectorGap
The detector distance in seconds.
std::string myFile
The output file for generated detectors.
SUMOTime myFreq
The frequency for aggregating detector output.
std::string myID
The name of the object.
InductLoopMap myInductLoops
A map from lanes to induct loops lying on them.
LaneVectorVector myLanes
The list of LaneVectors; each vector contains the incoming lanes that belong to the same link index.
LinkVectorVector myLinks
The list of LinkVectors; each vector contains the links that belong to the same link index.
SUMOReal myMaxGap
The maximum gap to check in seconds.
std::vector< SUMOTime > myOverridingTimes
A list of duration overrides.
SUMOReal myPassingTime
The passing time used in seconds.
Phases myPhases
The list of phases this logic uses.
std::string myProgramID
The id of the logic.
bool myShowDetectors
Whether the detectors shall be shown in the GUI.
bool mySplitByType
Whether detector output separates by vType.
int myStep
The current step.
SwitchCommand * mySwitchCommand
The current switch command.
Static Protected Attributes
static const LaneVector myEmptyLaneVector
An empty lane vector.
Detailed Description
An actuated (adaptive) traffic light logic.
Definition at line 58 of file MSActuatedTrafficLightLogic.h.
Member Typedef Documentation
typedef std::map<MSLane*, MSDetectorFileOutput*> MSActuatedTrafficLightLogic::InductLoopMap
Definition of a map from lanes to induct loops lying on them.
Definition at line 61 of file MSActuatedTrafficLightLogic.h.
typedef std::vector<MSLane*> MSTrafficLightLogic::LaneVector inherited
Definition of the list of links that participate in this tl-light.
Definition at line 78 of file MSTrafficLightLogic.h.
typedef std::vector<LaneVector> MSTrafficLightLogic::LaneVectorVector inherited
Definition of a list that holds lists of links that do have the same attribute.
Definition at line 81 of file MSTrafficLightLogic.h.
typedef std::vector<MSLink*> MSTrafficLightLogic::LinkVector inherited
Definition of the list of links that participate in this tl-light.
Definition at line 72 of file MSTrafficLightLogic.h.
typedef std::vector<LinkVector> MSTrafficLightLogic::LinkVectorVector inherited
Definition of a list that holds lists of links that do have the same attribute.
Definition at line 75 of file MSTrafficLightLogic.h.
typedef std::vector<MSPhaseDefinition*> MSTrafficLightLogic::Phases inherited
Definition of a list of phases, being the junction logic.
Definition at line 69 of file MSTrafficLightLogic.h.
Constructor & Destructor Documentation
MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic (MSTLLogicControl & tlcontrol, const std::string & id, const std::string & programID, const MSSimpleTrafficLightLogic::Phases & phases, int step, SUMOTime delay, const std::map< std::string, std::string > & parameter, const std::string & basePath)
Constructor.
Parameters
[in] tlcontrol The tls control responsible for this tls
[in] id This tls' id
[in] programID This tls' sub-id (program id)
[in] phases Definitions of the phases
[in] step The initial phase index
[in] delay The time to wait before the first switch
[in] parameter The parameter to use for tls set-up
Definition at line 66 of file MSActuatedTrafficLightLogic.cpp.
References TplConvert::_2bool(), TplConvert::_2SUMOReal(), FileHelpers::checkForRelativity(), DEFAULT_DETECTOR_GAP, DEFAULT_MAX_GAP, DEFAULT_PASSING_TIME, Parameterised::getParameter(), myDetectorGap, myFile, myFreq, myMaxGap, myPassingTime, myShowDetectors, mySplitByType, and TIME2STEPS.
MSActuatedTrafficLightLogic::~MSActuatedTrafficLightLogic ()
Destructor.
Definition at line 116 of file MSActuatedTrafficLightLogic.cpp.
Member Function Documentation
void MSTrafficLightLogic::adaptLinkInformationFrom (const MSTrafficLightLogic & logic) virtual inherited
Applies information about controlled links and lanes from the given logic.
If we load a logic after the network has been loaded, we do not get the information about controlled links afterwards. We have to copy them from a previously loaded logic.
Parameters
[in] logic The logic to use the information about controlled links/lanes from
Reimplemented in MSRailSignal, MSRailCrossing, and MSOffTrafficLightLogic.
Definition at line 205 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myLanes, and MSTrafficLightLogic::myLinks.
Referenced by MSOffTrafficLightLogic::adaptLinkInformationFrom(), MSRailCrossing::adaptLinkInformationFrom(), MSRailSignal::adaptLinkInformationFrom(), and MSTLLogicControl::TLSLogicVariants::addLogic().
void MSTrafficLightLogic::addLink (MSLink * link, MSLane * lane, int pos) virtual inherited
Adds a link on building.
Parameters
[in] link The controlled link
[in] lane The lane this link starts at
[in] pos The link's index (signal group) within this program
Reimplemented in MSRailCrossing.
Definition at line 187 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::getCurrentPhaseDef(), MSNet::getInstance(), MSTrafficLightLogic::myLanes, MSTrafficLightLogic::myLinks, and MSLink::setTLState().
Referenced by MSRailCrossing::addLink().
void MSTrafficLightLogic::addOverridingDuration (SUMOTime duration) inherited
Changes the duration of the next phase.
Parameters
[in] duration The new duration
Definition at line 278 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myOverridingTimes.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::cutLogic(), MSTrafficLightLogic::getDefaultCycleTime(), and MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic().
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 53 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NBTrafficLightDefinition::compute(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::EdgesHandler::myStartElement(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_TLS::processSet(), TraCIServerAPI_Polygon::processSet(), and TraCIServerAPI_Lane::processSet().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 59 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 67 of file Parameterised.cpp.
References Parameterised::myMap.
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
void MSSimpleTrafficLightLogic::changeStepAndDuration (MSTLLogicControl & tlcontrol, SUMOTime simStep, int step, SUMOTime stepDuration) virtual inherited
Changes the current phase and her duration.
Parameters
[in] tlcontrol The responsible traffic lights control
[in] simStep The current simulation step
[in] step Index of the phase to use
[in] stepDuration The left duration of the phase
See also
MSTrafficLightLogic::changeStepAndDuration
Implements MSTrafficLightLogic.
Definition at line 195 of file MSSimpleTrafficLightLogic.cpp.
References MSEventControl::ADAPT_AFTER_EXECUTION, MSEventControl::addEvent(), MSTrafficLightLogic::SwitchCommand::deschedule(), MSTLLogicControl::TLSLogicVariants::executeOnSwitchActions(), MSTLLogicControl::get(), MSNet::getBeginOfTimestepEvents(), Named::getID(), MSNet::getInstance(), MSSimpleTrafficLightLogic::myStep, MSTrafficLightLogic::mySwitchCommand, and MSTrafficLightLogic::setTrafficLightSignals().
Referenced by MSSimpleTrafficLightLogic::getLogicType(), and GUIViewTraffic::onGamingClick().
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 91 of file Parameterised.cpp.
References Parameterised::myMap.
std::map< MSLink *, LinkState > MSTrafficLightLogic::collectLinkStates () const inherited
Returns the (uncontrolled) states of the controlled links.
Returns
The controlled link's states
Definition at line 212 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myLinks.
Referenced by MSTLLogicControl::TLSLogicVariants::saveInitialStates().
SUMOTime MSActuatedTrafficLightLogic::duration (const SUMOReal detectionGap) const protected
Returns the minimum duration of the current phase.
Parameters
[in] detectionGap The minimum detection gap for the current phase
Returns
The minimum duration of the current phase
Definition at line 145 of file MSActuatedTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::getCurrentPhaseDef(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), MAX3(), MIN2(), MSPhaseDefinition::minDuration, myDetectorGap, MSSimpleTrafficLightLogic::myPhases, MSSimpleTrafficLightLogic::myStep, SUMOReal, and TIME2STEPS.
Referenced by trySwitch().
SUMOReal MSActuatedTrafficLightLogic::gapControl () protected
Return the minimum detection gap of all detectors if the current phase should be extended and SUMOReal::max otherwise.
Definition at line 165 of file MSActuatedTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::getCurrentPhaseDef(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), MSTrafficLightLogic::getLanesAt(), MSPhaseDefinition::getState(), MSInductLoop::getTimestepsSinceLastDetection(), MSGlobals::gUseMesoSim, LINKSTATE_TL_GREEN_MAJOR, LINKSTATE_TL_GREEN_MINOR, max, MIN2(), myInductLoops, myMaxGap, MSSimpleTrafficLightLogic::myPhases, MSSimpleTrafficLightLogic::myStep, and SUMOReal.
Referenced by trySwitch().
const MSPhaseDefinition & MSSimpleTrafficLightLogic::getCurrentPhaseDef () const virtual inherited
Returns the definition of the current phase.
Returns
The current phase
See also
MSTrafficLightLogic::getCurrentPhaseDef
Implements MSTrafficLightLogic.
Definition at line 137 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::myPhases, and MSSimpleTrafficLightLogic::myStep.
Referenced by duration(), gapControl(), MSSimpleTrafficLightLogic::getLogicType(), and trySwitch().
int MSSimpleTrafficLightLogic::getCurrentPhaseIndex () const virtual inherited
Returns the current index within the program.
Returns
The index of the current phase within the tls
See also
MSTrafficLightLogic::getCurrentPhaseIndex
Implements MSTrafficLightLogic.
Definition at line 131 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::myStep.
Referenced by MSSimpleTrafficLightLogic::getLogicType().
SUMOTime MSTrafficLightLogic::getDefaultCycleTime () const inline inherited
Returns the cycle time (in ms)
Returns
The (maybe changing) cycle time of this tls
Definition at line 267 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::addOverridingDuration(), MSTrafficLightLogic::changeStepAndDuration(), MSTrafficLightLogic::getIndexFromOffset(), MSTrafficLightLogic::getNextSwitchTime(), MSTrafficLightLogic::getOffsetFromIndex(), MSTrafficLightLogic::getPhaseIndexAtTime(), MSTrafficLightLogic::myDefaultCycleTime, and MSTrafficLightLogic::setCurrentDurationIncrement().
Referenced by MSTLLogicControl::WAUTSwitchProcedure_GSP::adaptLogic(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), NLJunctionControlBuilder::closeTrafficLightLogic(), and MSTLLogicControl::WAUTSwitchProcedure::isPosAtGSP().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciBusOrContainerStop(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNEConnectorFrame::buildIinternalLanes(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), NLDetectorBuilder::convUncontE2PosLength(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSVehicle::getBackPosition(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), GNEEdge::getDest(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), MSE2Collector::getEstimateQueueLength(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), GNEEdge::getSource(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSE2Collector::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_SL2015::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_LC2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_ArealDetector::processGet(), TraCIServerAPI_Lane::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), MSBaseVehicle::reroute(), MSLane::resetPartialOccupation(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), MSLane::saveState(), MSDevice_Battery::setAirDragCoefficient(), NBNodeCont::setAsTLControlled(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), MSDevice_Battery::setConstantPowerIntake(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), MSDevice_Battery::setFrontSurfaceArea(), MSDevice_Battery::setInternalMomentOfInertia(), GNEJunction::setLogicValid(), MSDevice_Battery::setMass(), MSDevice_Battery::setMaximumBatteryCapacity(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSDevice_Battery::setPropulsionEfficiency(), MSDevice_Battery::setRadialDragCoefficient(), MSDevice_Battery::setRecuperationEfficiency(), MSLink::setRequestInformation(), MSDevice_Battery::setRollDragCoefficient(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), operator<<(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
int MSSimpleTrafficLightLogic::getIndexFromOffset (SUMOTime offset) const virtual inherited
Returns the step (the phasenumber) of a given position of the cycle.
Parameters
[in] offset The offset (time) for which the according phase shall be returned
Returns
The according phase
See also
MSTrafficLightLogic::getIndexFromOffset
Implements MSTrafficLightLogic.
Definition at line 173 of file MSSimpleTrafficLightLogic.cpp.
References MSPhaseDefinition::duration, MSSimpleTrafficLightLogic::getPhase(), MSTrafficLightLogic::myDefaultCycleTime, and MSSimpleTrafficLightLogic::myPhases.
Referenced by MSSimpleTrafficLightLogic::getLogicType().
const LaneVector& MSTrafficLightLogic::getLanesAt (int i) const inline inherited
Returns the list of lanes that are controlled by the signals at the given position.
Parameters
[in] i The index of the signal
Returns
The lanes controlled by the signal at the given index
Definition at line 190 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myEmptyLaneVector, and MSTrafficLightLogic::myLanes.
Referenced by GUITrafficLightLogicWrapper::drawGL(), Command_SaveTLSSwitches::execute(), gapControl(), and GUIViewTraffic::onGamingClick().
const LaneVectorVector& MSTrafficLightLogic::getLaneVectors () const inline inherited
Returns the list of lists of all lanes controlled by this tls.
Returns
All lanes controlled by this tls, sorted by the signal index
Definition at line 181 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myLanes.
Referenced by MSSOTLWaveTrafficLightLogic::countVehicles(), GUITrafficLightLogicWrapper::getCenteringBoundary(), MSSOTLTrafficLightLogic::init(), TraCIServerAPI_TLS::processGet(), and MSFullExport::writeTLS().
int MSTrafficLightLogic::getLinkIndex (const MSLink *const link) const inherited
Returns the index of the given link.
Parameters
[in] link The link to retrieve the index for
Returns
The index of the given link (-1 if it is not controlled by this tls)
Definition at line 254 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myLinks.
Referenced by GUITrafficLightLogicWrapper::getLinkIndex(), and MSTrafficLightLogic::getLinksAt().
const LinkVectorVector& MSTrafficLightLogic::getLinks () const inline inherited
Returns the list of lists of all affected links.
Returns
All links controlled by this tls, sorted by the signal index
Definition at line 202 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myLinks.
Referenced by MSTLLogicControl::TLSLogicVariants::addLogic(), GUINet::createTLWrapper(), GUITLLogicPhasesTrackerWindow::drawValues(), Command_SaveTLSSwitches::execute(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSDeterministicHiLevelTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), TraCIServerAPI_TLS::processGet(), and MSOffTrafficLightLogic::rebuildPhase().
const LinkVector& MSTrafficLightLogic::getLinksAt (int i) const inline inherited
Returns the list of links that are controlled by the signals at the given position.
Parameters
[in] i The index of the signal
Returns
The links controlled by the signal at the given index
Definition at line 211 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::getCurrentPhaseDef(), MSTrafficLightLogic::getCurrentPhaseIndex(), MSTrafficLightLogic::getLinkIndex(), MSTrafficLightLogic::getLogicType(), MSTrafficLightLogic::getPhase(), MSTrafficLightLogic::getPhaseNumber(), MSTrafficLightLogic::getPhases(), and MSTrafficLightLogic::myLinks.
Referenced by MSDeterministicHiLevelTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), and MSSwarmTrafficLightLogic::init().
const std::string MSSimpleTrafficLightLogic::getLogicType () const inline virtual inherited
Returns the type of the logic as a string.
Returns
The type of the logic
Implements MSTrafficLightLogic.
Definition at line 127 of file MSSimpleTrafficLightLogic.h.
References MSSimpleTrafficLightLogic::changeStepAndDuration(), MSSimpleTrafficLightLogic::getCurrentPhaseDef(), MSSimpleTrafficLightLogic::getCurrentPhaseIndex(), MSSimpleTrafficLightLogic::getIndexFromOffset(), MSSimpleTrafficLightLogic::getOffsetFromIndex(), MSSimpleTrafficLightLogic::getPhaseIndexAtTime(), and MSSimpleTrafficLightLogic::setPhases().
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 107 of file Parameterised.h.
References Parameterised::myMap.
Referenced by NBTrafficLightDefinition::compute(), MSDevice_Vehroutes::generateOutput(), GUIPerson::getParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), TraCIServerAPI_TLS::processGet(), ROVehicle::saveAsXML(), ROPerson::saveAsXML(), SUMOVTypeParameter::write(), PointOfInterest::writeXML(), and SUMO::Polygon::writeXML().
SUMOTime MSTrafficLightLogic::getNextSwitchTime () const inherited
Returns the assumed next switch time.
The time may change in case of adaptive/actuated traffic lights.
Returns
The assumed next switch time (simulation time)
Definition at line 271 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::SwitchCommand::getNextSwitchTime(), and MSTrafficLightLogic::mySwitchCommand.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_GSP::adaptLogic(), MSTrafficLightLogic::getDefaultCycleTime(), MSTLLogicControl::WAUTSwitchProcedure::isPosAtGSP(), and TraCIServerAPI_TLS::processGet().
SUMOTime MSSimpleTrafficLightLogic::getOffsetFromIndex (int index) const virtual inherited
Returns the position (start of a phase during a cycle) from of a given step.
Parameters
[in] index The index of the phase to return the begin of
Returns
The begin time of the phase
See also
MSTrafficLightLogic::getOffsetFromIndex
Implements MSTrafficLightLogic.
Definition at line 159 of file MSSimpleTrafficLightLogic.cpp.
References MSPhaseDefinition::duration, MSSimpleTrafficLightLogic::getPhase(), and MSSimpleTrafficLightLogic::myPhases.
Referenced by MSSimpleTrafficLightLogic::getLogicType().
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 81 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), MSActuatedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), MSSOTLPolicyDesirability::readParameter(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), and TraCIServerAPI_Vehicle::vtdMap().
const MSPhaseDefinition & MSSimpleTrafficLightLogic::getPhase (int givenstep) const virtual inherited
Returns the definition of the phase from the given position within the plan.
Parameters
[in] givenstep The index of the phase within the plan
Returns
The definition of the phase at the given position
See also
MSTrafficLightLogic::getPhase
Implements MSTrafficLightLogic.
Definition at line 123 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::myPhases.
Referenced by MSSimpleTrafficLightLogic::getIndexFromOffset(), MSSimpleTrafficLightLogic::getOffsetFromIndex(), MSSimpleTrafficLightLogic::getPhaseIndexAtTime(), and GUIViewTraffic::onGamingClick().
SUMOTime MSSimpleTrafficLightLogic::getPhaseIndexAtTime (SUMOTime simStep) const virtual inherited
Returns the index of the logic at the given simulation step.
Returns
The (estimated) index of the tls at the given simulation time step
See also
MSTrafficLightLogic::getPhaseIndexAtTime
Implements MSTrafficLightLogic.
Definition at line 144 of file MSSimpleTrafficLightLogic.cpp.
References MSPhaseDefinition::duration, MSSimpleTrafficLightLogic::getPhase(), MSTrafficLightLogic::myDefaultCycleTime, MSPhaseDefinition::myLastSwitch, and MSSimpleTrafficLightLogic::myStep.
Referenced by MSSimpleTrafficLightLogic::getLogicType().
int MSSimpleTrafficLightLogic::getPhaseNumber () const virtual inherited
Returns the number of phases.
Returns
The number of this tls program's phases
See also
MSTrafficLightLogic::getPhaseNumber
Implements MSTrafficLightLogic.
Definition at line 105 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::myPhases.
const MSSimpleTrafficLightLogic::Phases & MSSimpleTrafficLightLogic::getPhases () const virtual inherited
Returns the phases of this tls program.
Returns
The phases of this tls program
See also
MSTrafficLightLogic::getPhases
Implements MSTrafficLightLogic.
Definition at line 111 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::myPhases.
MSSimpleTrafficLightLogic::Phases & MSSimpleTrafficLightLogic::getPhases () inherited
Returns the phases of this tls program.
Returns
The phases of this tls program
Todo:
Recheck!
Definition at line 117 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::myPhases.
const std::string& MSTrafficLightLogic::getProgramID () const inline inherited
Returns this tl-logic's id.
Returns
This program's id
Definition at line 173 of file MSTrafficLightLogic.h.
References MSTrafficLightLogic::myProgramID.
Referenced by Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSTrafficLightLogic::init(), GUIViewTraffic::onGamingClick(), and TraCIServerAPI_TLS::processGet().
void MSActuatedTrafficLightLogic::init (NLDetectorBuilder & nb) virtual
Initialises the tls with information about incoming lanes.
Parameters
[in] nb The detector builder
Exceptions
ProcessError If something fails on initialisation
Reimplemented from MSTrafficLightLogic.
Definition at line 85 of file MSActuatedTrafficLightLogic.cpp.
References MSDetectorControl::add(), NLDetectorBuilder::createInductLoop(), MSNet::getDetectorControl(), Named::getID(), MSNet::getInstance(), MSLane::getLength(), MSLane::getSpeedLimit(), MSTrafficLightLogic::init(), myDetectorGap, myFile, myFreq, Named::myID, myInductLoops, MSTrafficLightLogic::myLanes, MSTrafficLightLogic::myProgramID, myShowDetectors, mySplitByType, SUMO_TAG_INDUCTION_LOOP, and SUMOReal.
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 75 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), and MSDevice::equippedByDefaultAssignmentOptions().
void MSTrafficLightLogic::resetLinkStates (const std::map< MSLink *, LinkState > & vals) const inherited
Resets the states of controlled links.
Parameters
[in] vals The state of controlled links to use
Definition at line 241 of file MSTrafficLightLogic.cpp.
References MSNet::getCurrentTimeStep(), MSNet::getInstance(), and MSTrafficLightLogic::myLinks.
void MSTrafficLightLogic::setCurrentDurationIncrement (SUMOTime delay) inherited
Delays current phase by the given delay.
Parameters
[in] delay The time by which the current phase shall be delayed
Definition at line 284 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::myCurrentDurationIncrement.
Referenced by MSTrafficLightLogic::getDefaultCycleTime().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
void MSSimpleTrafficLightLogic::setPhases (const Phases & phases, int index) inherited
Replaces the phases and set the phase index.
Definition at line 211 of file MSSimpleTrafficLightLogic.cpp.
References MSSimpleTrafficLightLogic::deletePhases(), MSSimpleTrafficLightLogic::myPhases, and MSSimpleTrafficLightLogic::myStep.
Referenced by MSSimpleTrafficLightLogic::getLogicType().
bool MSTrafficLightLogic::setTrafficLightSignals (SUMOTime t) const inherited
Applies the current signal states to controlled links.
Parameters
[in] t The current time
Returns
Always true
See also
LinkState
MSLink::setTLState
Definition at line 225 of file MSTrafficLightLogic.cpp.
References MSTrafficLightLogic::getCurrentPhaseDef(), MSPhaseDefinition::getState(), and MSTrafficLightLogic::myLinks.
Referenced by MSTLLogicControl::TLSLogicVariants::addLogic(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSTrafficLightLogic::SwitchCommand::execute(), MSRailCrossing::init(), MSRailSignal::init(), MSTLLogicControl::TLSLogicVariants::switchTo(), MSRailCrossing::trySwitch(), and MSRailSignal::trySwitch().
SUMOTime MSActuatedTrafficLightLogic::trySwitch () virtual
Switches to the next phase.
Returns
The time of the next switch
See also
MSTrafficLightLogic::trySwitch
Reimplemented from MSSimpleTrafficLightLogic.
Definition at line 121 of file MSActuatedTrafficLightLogic.cpp.
References duration(), gapControl(), MSSimpleTrafficLightLogic::getCurrentPhaseDef(), MSNet::getCurrentTimeStep(), MSNet::getInstance(), max, MSPhaseDefinition::minDuration, MSSimpleTrafficLightLogic::myPhases, MSSimpleTrafficLightLogic::myStep, and SUMOReal.
Field Documentation
SUMOTime MSTrafficLightLogic::myCurrentDurationIncrement protected inherited
A value for enlarge the current duration.
Definition at line 411 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::setCurrentDurationIncrement(), and MSSimpleTrafficLightLogic::trySwitch().
SUMOTime MSTrafficLightLogic::myDefaultCycleTime protected inherited
The cycle time (without changes)
Definition at line 417 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::getDefaultCycleTime(), MSPhasedTrafficLightLogic::getIndexFromOffset(), MSSimpleTrafficLightLogic::getIndexFromOffset(), MSPhasedTrafficLightLogic::getPhaseIndexAtTime(), MSSimpleTrafficLightLogic::getPhaseIndexAtTime(), MSOffTrafficLightLogic::MSOffTrafficLightLogic(), MSPhasedTrafficLightLogic::MSPhasedTrafficLightLogic(), MSRailSignal::MSRailSignal(), and MSSimpleTrafficLightLogic::MSSimpleTrafficLightLogic().
SUMOReal MSActuatedTrafficLightLogic::myDetectorGap protected
The detector distance in seconds.
Definition at line 132 of file MSActuatedTrafficLightLogic.h.
Referenced by duration(), init(), and MSActuatedTrafficLightLogic().
const MSTrafficLightLogic::LaneVector MSTrafficLightLogic::myEmptyLaneVector static protected inherited
An empty lane vector.
Definition at line 420 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::getLanesAt().
std::string MSActuatedTrafficLightLogic::myFile protected
The output file for generated detectors.
Definition at line 138 of file MSActuatedTrafficLightLogic.h.
Referenced by init(), and MSActuatedTrafficLightLogic().
SUMOTime MSActuatedTrafficLightLogic::myFreq protected
The frequency for aggregating detector output.
Definition at line 141 of file MSActuatedTrafficLightLogic.h.
Referenced by init(), and MSActuatedTrafficLightLogic().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
InductLoopMap MSActuatedTrafficLightLogic::myInductLoops protected
A map from lanes to induct loops lying on them.
Definition at line 123 of file MSActuatedTrafficLightLogic.h.
Referenced by gapControl(), and init().
LaneVectorVector MSTrafficLightLogic::myLanes protected inherited
The list of LaneVectors; each vector contains the incoming lanes that belong to the same link index.
Definition at line 405 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::adaptLinkInformationFrom(), MSTrafficLightLogic::addLink(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSTrafficLightLogic::getLanesAt(), MSTrafficLightLogic::getLaneVectors(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), and MSSwarmTrafficLightLogic::resetLaneCheck().
LinkVectorVector MSTrafficLightLogic::myLinks protected inherited
The list of LinkVectors; each vector contains the links that belong to the same link index.
Definition at line 402 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::adaptLinkInformationFrom(), MSTrafficLightLogic::addLink(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSTrafficLightLogic::collectLinkStates(), MSRailSignal::getAppropriateState(), MSTrafficLightLogic::getLinkIndex(), MSTrafficLightLogic::getLinks(), MSTrafficLightLogic::getLinksAt(), MSRailCrossing::init(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSTrafficLightLogic::initMesoTLSPenalties(), MSSwarmTrafficLightLogic::resetLaneCheck(), MSTrafficLightLogic::resetLinkStates(), and MSTrafficLightLogic::setTrafficLightSignals().
SUMOReal MSActuatedTrafficLightLogic::myMaxGap protected
The maximum gap to check in seconds.
Definition at line 126 of file MSActuatedTrafficLightLogic.h.
Referenced by gapControl(), and MSActuatedTrafficLightLogic().
std::vector<SUMOTime> MSTrafficLightLogic::myOverridingTimes protected inherited
A list of duration overrides.
Definition at line 408 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::addOverridingDuration(), and MSSimpleTrafficLightLogic::trySwitch().
SUMOReal MSActuatedTrafficLightLogic::myPassingTime protected
The passing time used in seconds.
Definition at line 129 of file MSActuatedTrafficLightLogic.h.
Referenced by MSActuatedTrafficLightLogic().
Phases MSSimpleTrafficLightLogic::myPhases protected inherited
The list of phases this logic uses.
Definition at line 202 of file MSSimpleTrafficLightLogic.h.
Referenced by MSSimpleTrafficLightLogic::deletePhases(), duration(), gapControl(), MSSimpleTrafficLightLogic::getCurrentPhaseDef(), MSSimpleTrafficLightLogic::getIndexFromOffset(), MSSimpleTrafficLightLogic::getOffsetFromIndex(), MSSimpleTrafficLightLogic::getPhase(), MSSimpleTrafficLightLogic::getPhaseNumber(), MSSimpleTrafficLightLogic::getPhases(), MSRailCrossing::init(), MSRailCrossing::MSRailCrossing(), MSSimpleTrafficLightLogic::MSSimpleTrafficLightLogic(), MSSimpleTrafficLightLogic::setPhases(), MSSimpleTrafficLightLogic::trySwitch(), and trySwitch().
std::string MSTrafficLightLogic::myProgramID protected inherited
The id of the logic.
Definition at line 399 of file MSTrafficLightLogic.h.
Referenced by MSTrafficLightLogic::getProgramID(), and init().
bool MSActuatedTrafficLightLogic::myShowDetectors protected
Whether the detectors shall be shown in the GUI.
Definition at line 135 of file MSActuatedTrafficLightLogic.h.
Referenced by init(), and MSActuatedTrafficLightLogic().
bool MSActuatedTrafficLightLogic::mySplitByType protected
Whether detector output separates by vType.
Definition at line 144 of file MSActuatedTrafficLightLogic.h.
Referenced by init(), and MSActuatedTrafficLightLogic().
int MSSimpleTrafficLightLogic::myStep protected inherited
The current step.
Definition at line 205 of file MSSimpleTrafficLightLogic.h.
Referenced by MSSimpleTrafficLightLogic::changeStepAndDuration(), duration(), gapControl(), MSSimpleTrafficLightLogic::getCurrentPhaseDef(), MSSimpleTrafficLightLogic::getCurrentPhaseIndex(), MSSimpleTrafficLightLogic::getPhaseIndexAtTime(), MSSimpleTrafficLightLogic::setPhases(), MSSimpleTrafficLightLogic::trySwitch(), trySwitch(), and MSRailCrossing::updateCurrentPhase().
SwitchCommand* MSTrafficLightLogic::mySwitchCommand protected inherited
The current switch command.
Definition at line 414 of file MSTrafficLightLogic.h.
Referenced by MSPhasedTrafficLightLogic::changeStepAndDuration(), MSSimpleTrafficLightLogic::changeStepAndDuration(), MSTrafficLightLogic::getNextSwitchTime(), and MSTrafficLightLogic::MSTrafficLightLogic().
The documentation for this class was generated from the following files:
MSActuatedTrafficLightLogic.h
MSActuatedTrafficLightLogic.cpp