SUMO - Simulation of Urban MObility: MSSOTLPolicy3DStimulus Class Reference
MSSOTLPolicy3DStimulus Class Reference
#include <MSSOTLPolicy3DStimulus.h>
Public Member Functions
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
void clearParameter ()
Clears the parameter map.
virtual SUMOReal computeDesirability (SUMOReal vehInMeasure, SUMOReal vehOutMeasure)
Computes stimulus function stimulus = cox * exp(-pow(pheroIn - offsetIn, 2)/divisor -pow(pheroOut - offsetOut, 2)/divisor);.
virtual SUMOReal computeDesirability (SUMOReal vehInMeasure, SUMOReal vehOutMeasure, SUMOReal vehInDispersionMeasure, SUMOReal vehOutDispersionMeasure)
Calculates the desirability of the policy.
std::string getKeyPrefix ()
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
std::string getMessage ()
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
SUMOReal getStimCox ()
SUMOReal getStimCoxExpDispersionIn ()
SUMOReal getStimCoxExpDispersionOut ()
SUMOReal getStimCoxExpIn ()
SUMOReal getStimCoxExpOut ()
SUMOReal getStimDivisorDispersionIn ()
SUMOReal getStimDivisorDispersionOut ()
SUMOReal getStimDivisorIn ()
SUMOReal getStimDivisorOut ()
SUMOReal getStimOffsetDispersionIn ()
SUMOReal getStimOffsetDispersionOut ()
SUMOReal getStimOffsetIn ()
SUMOReal getStimOffsetOut ()
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
MSSOTLPolicy3DStimulus (std::string keyPrefix, const std::map< std::string, std::string > &parameters)
void setKeyPrefix (std::string val)
void setStimCoxDefVal (SUMOReal defVal)
void setStimCoxExpDispersionInDefVal (SUMOReal defVal)
void setStimCoxExpDispersionOutDefVal (SUMOReal defVal)
void setStimCoxExpInDefVal (SUMOReal defVal)
void setStimCoxExpOutDefVal (SUMOReal defVal)
void setStimDivisorDispersionInDefVal (SUMOReal defVal)
void setStimDivisorDispersionOutDefVal (SUMOReal defVal)
void setStimDivisorInDefVal (SUMOReal defVal)
void setStimDivisorOutDefVal (SUMOReal defVal)
void setStimOffsetDispersionInDefVal (SUMOReal defVal)
void setStimOffsetDispersionOutDefVal (SUMOReal defVal)
void setStimOffsetInDefVal (SUMOReal defVal)
void setStimOffsetOutDefVal (SUMOReal defVal)
Protected Member Functions
SUMOReal readParameter (std::string parName, SUMOReal defValue)
Detailed Description
Definition at line 47 of file MSSOTLPolicy3DStimulus.h.
Constructor & Destructor Documentation
MSSOTLPolicy3DStimulus::MSSOTLPolicy3DStimulus (std::string keyPrefix, const std::map< std::string, std::string > & parameters)
Definition at line 23 of file MSSOTLPolicy3DStimulus.cpp.
References MSSOTLPolicy5DStimulus::setStimCoxExpDispersionInDefVal(), and MSSOTLPolicy5DStimulus::setStimCoxExpDispersionOutDefVal().
Member Function Documentation
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 53 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NBTrafficLightDefinition::compute(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::EdgesHandler::myStartElement(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_TLS::processSet(), TraCIServerAPI_Polygon::processSet(), and TraCIServerAPI_Lane::processSet().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 59 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 67 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 91 of file Parameterised.cpp.
References Parameterised::myMap.
SUMOReal MSSOTLPolicy5DStimulus::computeDesirability (SUMOReal vehInMeasure, SUMOReal vehOutMeasure) virtual inherited
Computes stimulus function stimulus = cox * exp(-pow(pheroIn - offsetIn, 2)/divisor -pow(pheroOut - offsetOut, 2)/divisor);.
Implements MSSOTLPolicyDesirability.
Definition at line 81 of file MSSOTLPolicy5DStimulus.cpp.
Referenced by MSSOTLPolicy5DStimulus::setStimCoxExpDispersionOutDefVal().
SUMOReal MSSOTLPolicy5DStimulus::computeDesirability (SUMOReal vehInMeasure, SUMOReal vehOutMeasure, SUMOReal vehInDispersionMeasure, SUMOReal vehOutDispersionMeasure) virtual inherited
Calculates the desirability of the policy.
Implements MSSOTLPolicyDesirability.
Definition at line 43 of file MSSOTLPolicy5DStimulus.cpp.
References DBG, MSSOTLPolicy5DStimulus::getStimCox(), MSSOTLPolicy5DStimulus::getStimCoxExpDispersionIn(), MSSOTLPolicy5DStimulus::getStimCoxExpDispersionOut(), MSSOTLPolicy5DStimulus::getStimCoxExpIn(), MSSOTLPolicy5DStimulus::getStimCoxExpOut(), MSSOTLPolicy5DStimulus::getStimDivisorDispersionIn(), MSSOTLPolicy5DStimulus::getStimDivisorDispersionOut(), MSSOTLPolicy5DStimulus::getStimDivisorIn(), MSSOTLPolicy5DStimulus::getStimDivisorOut(), MSSOTLPolicy5DStimulus::getStimOffsetDispersionIn(), MSSOTLPolicy5DStimulus::getStimOffsetDispersionOut(), MSSOTLPolicy5DStimulus::getStimOffsetIn(), MSSOTLPolicy5DStimulus::getStimOffsetOut(), SUMOReal, WRITE_ERROR, and WRITE_MESSAGE.
std::string MSSOTLPolicyDesirability::getKeyPrefix () inline inherited
Definition at line 74 of file MSSOTLPolicyDesirability.h.
References MSSOTLPolicyDesirability::myKeyPrefix.
Referenced by MSSOTLPolicy5DStimulus::getStimCox(), MSSOTLPolicy5DStimulus::getStimCoxExpDispersionIn(), MSSOTLPolicy5DStimulus::getStimCoxExpDispersionOut(), MSSOTLPolicy5DStimulus::getStimCoxExpIn(), MSSOTLPolicy5DStimulus::getStimCoxExpOut(), MSSOTLPolicy5DStimulus::getStimDivisorDispersionIn(), MSSOTLPolicy5DStimulus::getStimDivisorDispersionOut(), MSSOTLPolicy5DStimulus::getStimDivisorIn(), MSSOTLPolicy5DStimulus::getStimDivisorOut(), MSSOTLPolicy5DStimulus::getStimOffsetDispersionIn(), MSSOTLPolicy5DStimulus::getStimOffsetDispersionOut(), MSSOTLPolicy5DStimulus::getStimOffsetIn(), and MSSOTLPolicy5DStimulus::getStimOffsetOut().
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 107 of file Parameterised.h.
References Parameterised::myMap.
Referenced by NBTrafficLightDefinition::compute(), MSDevice_Vehroutes::generateOutput(), GUIPerson::getParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), TraCIServerAPI_TLS::processGet(), ROVehicle::saveAsXML(), ROPerson::saveAsXML(), SUMOVTypeParameter::write(), PointOfInterest::writeXML(), and SUMO::Polygon::writeXML().
std::string MSSOTLPolicy5DStimulus::getMessage () virtual inherited
Implements MSSOTLPolicyDesirability.
Definition at line 85 of file MSSOTLPolicy5DStimulus.cpp.
References MSSOTLPolicy5DStimulus::getStimCox(), MSSOTLPolicy5DStimulus::getStimCoxExpIn(), MSSOTLPolicy5DStimulus::getStimCoxExpOut(), MSSOTLPolicy5DStimulus::getStimDivisorIn(), MSSOTLPolicy5DStimulus::getStimDivisorOut(), MSSOTLPolicy5DStimulus::getStimOffsetIn(), and MSSOTLPolicy5DStimulus::getStimOffsetOut().
Referenced by MSSOTLPolicy5DStimulus::setStimCoxExpDispersionOutDefVal().
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 81 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), MSSOTLPolicyDesirability::readParameter(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), and TraCIServerAPI_Vehicle::vtdMap().
SUMOReal MSSOTLPolicy5DStimulus::getStimCox () inline inherited
Definition at line 61 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by MSSOTLPolicy5DStimulus::computeDesirability(), and MSSOTLPolicy5DStimulus::getMessage().
SUMOReal MSSOTLPolicy5DStimulus::getStimCoxExpDispersionIn () inline inherited
Definition at line 147 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by MSSOTLPolicy5DStimulus::computeDesirability().
SUMOReal MSSOTLPolicy5DStimulus::getStimCoxExpDispersionOut () inline inherited
Definition at line 154 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by MSSOTLPolicy5DStimulus::computeDesirability().
SUMOReal MSSOTLPolicy5DStimulus::getStimCoxExpIn () inline inherited
Definition at line 132 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by MSSOTLPolicy5DStimulus::computeDesirability(), and MSSOTLPolicy5DStimulus::getMessage().
SUMOReal MSSOTLPolicy5DStimulus::getStimCoxExpOut () inline inherited
Definition at line 139 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by MSSOTLPolicy5DStimulus::computeDesirability(), and MSSOTLPolicy5DStimulus::getMessage().
SUMOReal MSSOTLPolicy5DStimulus::getStimDivisorDispersionIn () inline inherited
Definition at line 116 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by MSSOTLPolicy5DStimulus::computeDesirability().
SUMOReal MSSOTLPolicy5DStimulus::getStimDivisorDispersionOut () inline inherited
Definition at line 124 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by MSSOTLPolicy5DStimulus::computeDesirability().
SUMOReal MSSOTLPolicy5DStimulus::getStimDivisorIn () inline inherited
Definition at line 98 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by MSSOTLPolicy5DStimulus::computeDesirability(), and MSSOTLPolicy5DStimulus::getMessage().
SUMOReal MSSOTLPolicy5DStimulus::getStimDivisorOut () inline inherited
Definition at line 107 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by MSSOTLPolicy5DStimulus::computeDesirability(), and MSSOTLPolicy5DStimulus::getMessage().
SUMOReal MSSOTLPolicy5DStimulus::getStimOffsetDispersionIn () inline inherited
Definition at line 84 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by MSSOTLPolicy5DStimulus::computeDesirability().
SUMOReal MSSOTLPolicy5DStimulus::getStimOffsetDispersionOut () inline inherited
Definition at line 91 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by MSSOTLPolicy5DStimulus::computeDesirability().
SUMOReal MSSOTLPolicy5DStimulus::getStimOffsetIn () inline inherited
Definition at line 68 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by MSSOTLPolicy5DStimulus::computeDesirability(), and MSSOTLPolicy5DStimulus::getMessage().
SUMOReal MSSOTLPolicy5DStimulus::getStimOffsetOut () inline inherited
Definition at line 75 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicyDesirability::getKeyPrefix(), and MSSOTLPolicyDesirability::readParameter().
Referenced by MSSOTLPolicy5DStimulus::computeDesirability(), and MSSOTLPolicy5DStimulus::getMessage().
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 75 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), and MSDevice::equippedByDefaultAssignmentOptions().
SUMOReal MSSOTLPolicyDesirability::readParameter (std::string parName, SUMOReal defValue) inline protected inherited
Definition at line 49 of file MSSOTLPolicyDesirability.h.
References TplConvert::_2SUMORealSec(), MSSOTLPolicyDesirability::computeDesirability(), MSSOTLPolicyDesirability::getMessage(), Parameterised::getParameter(), MSSOTLPolicyDesirability::MSSOTLPolicyDesirability(), SUMOReal, and MSSOTLPolicyDesirability::~MSSOTLPolicyDesirability().
Referenced by MSSOTLPolicy5DStimulus::getStimCox(), MSSOTLPolicy5DStimulus::getStimCoxExpDispersionIn(), MSSOTLPolicy5DStimulus::getStimCoxExpDispersionOut(), MSSOTLPolicy5DStimulus::getStimCoxExpIn(), MSSOTLPolicy5DStimulus::getStimCoxExpOut(), MSSOTLPolicy5DStimulus::getStimDivisorDispersionIn(), MSSOTLPolicy5DStimulus::getStimDivisorDispersionOut(), MSSOTLPolicy5DStimulus::getStimDivisorIn(), MSSOTLPolicy5DStimulus::getStimDivisorOut(), MSSOTLPolicy5DStimulus::getStimOffsetDispersionIn(), MSSOTLPolicy5DStimulus::getStimOffsetDispersionOut(), MSSOTLPolicy5DStimulus::getStimOffsetIn(), MSSOTLPolicy5DStimulus::getStimOffsetOut(), and MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus().
void MSSOTLPolicyDesirability::setKeyPrefix (std::string val) inline inherited
Definition at line 71 of file MSSOTLPolicyDesirability.h.
Referenced by MSSOTLCongestionPolicy::MSSOTLCongestionPolicy(), MSSOTLMarchingPolicy::MSSOTLMarchingPolicy(), MSSOTLPhasePolicy::MSSOTLPhasePolicy(), MSSOTLPlatoonPolicy::MSSOTLPlatoonPolicy(), and MSSOTLRequestPolicy::MSSOTLRequestPolicy().
void MSSOTLPolicy5DStimulus::setStimCoxDefVal (SUMOReal defVal) inline inherited
Definition at line 65 of file MSSOTLPolicy5DStimulus.h.
void MSSOTLPolicy5DStimulus::setStimCoxExpDispersionInDefVal (SUMOReal defVal) inline inherited
Definition at line 151 of file MSSOTLPolicy5DStimulus.h.
Referenced by MSSOTLPolicy3DStimulus().
void MSSOTLPolicy5DStimulus::setStimCoxExpDispersionOutDefVal (SUMOReal defVal) inline inherited
Definition at line 158 of file MSSOTLPolicy5DStimulus.h.
References MSSOTLPolicy5DStimulus::computeDesirability(), MSSOTLPolicy5DStimulus::getMessage(), and SUMOReal.
Referenced by MSSOTLPolicy3DStimulus().
void MSSOTLPolicy5DStimulus::setStimCoxExpInDefVal (SUMOReal defVal) inline inherited
Definition at line 136 of file MSSOTLPolicy5DStimulus.h.
void MSSOTLPolicy5DStimulus::setStimCoxExpOutDefVal (SUMOReal defVal) inline inherited
Definition at line 143 of file MSSOTLPolicy5DStimulus.h.
void MSSOTLPolicy5DStimulus::setStimDivisorDispersionInDefVal (SUMOReal defVal) inline inherited
Definition at line 121 of file MSSOTLPolicy5DStimulus.h.
void MSSOTLPolicy5DStimulus::setStimDivisorDispersionOutDefVal (SUMOReal defVal) inline inherited
Definition at line 129 of file MSSOTLPolicy5DStimulus.h.
void MSSOTLPolicy5DStimulus::setStimDivisorInDefVal (SUMOReal defVal) inline inherited
Definition at line 103 of file MSSOTLPolicy5DStimulus.h.
void MSSOTLPolicy5DStimulus::setStimDivisorOutDefVal (SUMOReal defVal) inline inherited
Definition at line 112 of file MSSOTLPolicy5DStimulus.h.
void MSSOTLPolicy5DStimulus::setStimOffsetDispersionInDefVal (SUMOReal defVal) inline inherited
Definition at line 88 of file MSSOTLPolicy5DStimulus.h.
void MSSOTLPolicy5DStimulus::setStimOffsetDispersionOutDefVal (SUMOReal defVal) inline inherited
Definition at line 95 of file MSSOTLPolicy5DStimulus.h.
void MSSOTLPolicy5DStimulus::setStimOffsetInDefVal (SUMOReal defVal) inline inherited
Definition at line 72 of file MSSOTLPolicy5DStimulus.h.
void MSSOTLPolicy5DStimulus::setStimOffsetOutDefVal (SUMOReal defVal) inline inherited
Definition at line 80 of file MSSOTLPolicy5DStimulus.h.
The documentation for this class was generated from the following files:
MSSOTLPolicy3DStimulus.h
MSSOTLPolicy3DStimulus.cpp