SUMO - Simulation of Urban MObility: GNEAdditionalFrame::additionalParameter Class Reference
GNEAdditionalFrame::additionalParameter Class Reference
FOX-declaration.
#include <GNEAdditionalFrame.h>
Public Member Functions
additionalParameter (FXComposite *parent, FXObject *tgt)
constructor
SumoXMLAttr getAttr () const
return Attr
std::string getValue () const
return value
void hideParameter ()
hide all parameters
void showParameter (SumoXMLAttr attr, std::string value)
show name and value of attribute of type string
void showParameter (SumoXMLAttr attr, int value)
show name and value of parameters of type int
void showParameter (SumoXMLAttr attr, SUMOReal value)
show name and value of parameters of type float/real
void showParameter (SumoXMLAttr attr, bool value)
show name and value of parameters of type bool
~additionalParameter ()
destructor
Private Attributes
SumoXMLAttr myAttr
XML attribute.
FXLabel * myLabel
lael with the name of the parameter
FXMenuCheck * myMenuCheck
menuCheck to enable/disable the value of parameter
FXTextField * myTextField
textField to modify the value of parameter
Detailed Description
FOX-declaration.
Definition at line 60 of file GNEAdditionalFrame.h.
Constructor & Destructor Documentation
GNEAdditionalFrame::additionalParameter::additionalParameter (FXComposite * parent, FXObject * tgt)
constructor
Definition at line 505 of file GNEAdditionalFrame.cpp.
References hideParameter(), MID_GNE_MODE_ADDITIONAL_CHANGEPARAMETER_BOOL, MID_GNE_MODE_ADDITIONAL_CHANGEPARAMETER_TEXT, myLabel, myMenuCheck, and myTextField.
GNEAdditionalFrame::additionalParameter::~additionalParameter ()
destructor
Definition at line 519 of file GNEAdditionalFrame.cpp.
Member Function Documentation
SumoXMLAttr GNEAdditionalFrame::additionalParameter::getAttr () const
return Attr
Definition at line 577 of file GNEAdditionalFrame.cpp.
References myAttr.
std::string GNEAdditionalFrame::additionalParameter::getValue () const
return value
Definition at line 583 of file GNEAdditionalFrame.cpp.
References GNEAttributeCarrier::isBool(), myAttr, myMenuCheck, and myTextField.
void GNEAdditionalFrame::additionalParameter::hideParameter ()
hide all parameters
Definition at line 567 of file GNEAdditionalFrame.cpp.
References GNEAdditionalFrame::hide(), myAttr, myLabel, myMenuCheck, myTextField, and SUMO_ATTR_NOTHING.
Referenced by additionalParameter().
void GNEAdditionalFrame::additionalParameter::showParameter (SumoXMLAttr attr, std::string value)
show name and value of attribute of type string
Definition at line 523 of file GNEAdditionalFrame.cpp.
References myAttr, myLabel, myTextField, GNEAdditionalFrame::show(), and toString().
void GNEAdditionalFrame::additionalParameter::showParameter (SumoXMLAttr attr, int value)
show name and value of parameters of type int
Definition at line 534 of file GNEAdditionalFrame.cpp.
References myAttr, myLabel, myTextField, GNEAdditionalFrame::show(), and toString().
void GNEAdditionalFrame::additionalParameter::showParameter (SumoXMLAttr attr, SUMOReal value)
show name and value of parameters of type float/real
Definition at line 545 of file GNEAdditionalFrame.cpp.
References myAttr, myLabel, myTextField, GNEAdditionalFrame::show(), and toString().
void GNEAdditionalFrame::additionalParameter::showParameter (SumoXMLAttr attr, bool value)
show name and value of parameters of type bool
Definition at line 556 of file GNEAdditionalFrame.cpp.
References myAttr, myLabel, myMenuCheck, GNEAdditionalFrame::show(), and toString().
Field Documentation
SumoXMLAttr GNEAdditionalFrame::additionalParameter::myAttr private
XML attribute.
Definition at line 92 of file GNEAdditionalFrame.h.
Referenced by getAttr(), getValue(), hideParameter(), and showParameter().
FXLabel* GNEAdditionalFrame::additionalParameter::myLabel private
lael with the name of the parameter
Definition at line 95 of file GNEAdditionalFrame.h.
Referenced by additionalParameter(), hideParameter(), and showParameter().
FXMenuCheck* GNEAdditionalFrame::additionalParameter::myMenuCheck private
menuCheck to enable/disable the value of parameter
Definition at line 101 of file GNEAdditionalFrame.h.
Referenced by additionalParameter(), getValue(), hideParameter(), and showParameter().
FXTextField* GNEAdditionalFrame::additionalParameter::myTextField private
textField to modify the value of parameter
Definition at line 98 of file GNEAdditionalFrame.h.
Referenced by additionalParameter(), getValue(), hideParameter(), and showParameter().
The documentation for this class was generated from the following files:
GNEAdditionalFrame.h
GNEAdditionalFrame.cpp