SUMO - Simulation of Urban MObility: GUIGlObjectStorage Class Reference
GUIGlObjectStorage Class Reference
A storage for of displayed objects via their numerical id.
#include <GUIGlObjectStorage.h>
Public Member Functions
void clear ()
Clears this container.
std::set< GUIGlID > getAllIDs () const
Returns the set of all known ids.
GUIGlObject * getNetObject () const
Returns the network object.
GUIGlObject * getObjectBlocking (GUIGlID id)
Returns the object from the container locking it.
GUIGlObject * getObjectBlocking (const std::string &fullName)
Returns the object from the container locking it.
GUIGlObjectStorage ()
Constructor.
GUIGlID registerObject (GUIGlObject *object, const std::string &fullName)
Registers an object.
bool remove (GUIGlID id)
Removes the named object from this container.
void setNetObject (GUIGlObject *object)
Sets the given object as the "network" object.
void unblockObject (GUIGlID id)
Marks an object as unblocked.
~GUIGlObjectStorage ()
Destructor.
Static Public Attributes
static GUIGlObjectStorage gIDStorage
A single static instance of this class.
Private Types
typedef std::map< GUIGlID, GUIGlObject * > ObjectMap
Definition of a container from numerical ids to objects.
Private Member Functions
GUIGlObjectStorage (const GUIGlObjectStorage &s)
invalidated copy constructor
GUIGlObjectStorage & operator= (const GUIGlObjectStorage &s)
invalidate assignment operator
Private Attributes
ObjectMap my2Delete
Objects to delete.
GUIGlID myAktID
The next id to give; initially zero, increased by one with each object registration.
ObjectMap myBlocked
The currently accessed objects.
std::map< std::string, GUIGlObject * > myFullNameMap
MFXMutex myLock
A lock to avoid parallel access on the storages.
ObjectMap myMap
The known objects which are not accessed currently.
GUIGlObject * myNetObject
The network object.
Detailed Description
A storage for of displayed objects via their numerical id.
This is a container for GUIGlObject - objects, which may be displayed and due to this may generate tooltips or be grapped in other ways.
As in case of vehicles (other, later implemented objects may have this property, too) they may be deleted by the simulation while being accessed
for example using a property window or something like that - this container posesses three storages: one containing all objects that are not accessed at all, one for objects currently accessed and one for objects that are accessed but shall be deleted.
Definition at line 60 of file GUIGlObjectStorage.h.
Member Typedef Documentation
typedef std::map<GUIGlID, GUIGlObject*> GUIGlObjectStorage::ObjectMap private
Definition of a container from numerical ids to objects.
Definition at line 158 of file GUIGlObjectStorage.h.
Constructor & Destructor Documentation
GUIGlObjectStorage::GUIGlObjectStorage ()
Constructor.
Definition at line 54 of file GUIGlObjectStorage.cpp.
GUIGlObjectStorage::~GUIGlObjectStorage ()
Destructor.
Definition at line 58 of file GUIGlObjectStorage.cpp.
GUIGlObjectStorage::GUIGlObjectStorage (const GUIGlObjectStorage & s) private
invalidated copy constructor
Member Function Documentation
void GUIGlObjectStorage::clear ()
Clears this container.
The objects are not deleted.
Definition at line 121 of file GUIGlObjectStorage.cpp.
References myAktID, myLock, and myMap.
Referenced by GUIRunThread::deleteSim().
std::set< GUIGlID > GUIGlObjectStorage::getAllIDs () const
Returns the set of all known ids.
Definition at line 142 of file GUIGlObjectStorage.cpp.
References myLock, and myMap.
GUIGlObject* GUIGlObjectStorage::getNetObject () const inline
Returns the network object.
Returns
The network object
Definition at line 142 of file GUIGlObjectStorage.h.
References myNetObject.
Referenced by GUISUMOAbstractView::openObjectDialog().
GUIGlObject * GUIGlObjectStorage::getObjectBlocking (GUIGlID id)
Returns the object from the container locking it.
The lock prevents the object from being deleted while it is accessed. The object is moved from "myMap" to "myBlocked".
Parameters
[in] id The id of the object to return
Returns
The object with the given id or 0 if no such object is known
Definition at line 72 of file GUIGlObjectStorage.cpp.
References myBlocked, myLock, and myMap.
Referenced by GUISUMOAbstractView::centerTo(), GUISelectedStorage::deselect(), GUIMessageWindow::getActiveStringObject(), GNEViewNet::getEdgeAtCursorPosition(), GNEViewNet::getEdgesAtCursorPosition(), GNEViewNet::getJunctionAtCursorPosition(), GNEViewNet::getLaneAtCurserPosition(), GUIViewTraffic::getLaneUnderCursor(), GNESelectorFrame::getMatches(), GUISUMOAbstractView::getObjectAtPosition(), getObjectBlocking(), GUISUMOAbstractView::getObjectsAtPosition(), GNESelectorFrame::handleIDs(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GNEConnectorFrame::onCmdClearSelectedConnections(), GNEConnectorFrame::onCmdResetSelectedConnections(), GNEViewNet::onDoubleClicked(), GNEViewNet::onLeftBtnPress(), GUISUMOAbstractView::openObjectDialog(), GUIDialog_GLChosenEditor::rebuildList(), GNENet::retrieveAttributeCarriers(), GUISelectedStorage::save(), GUISelectedStorage::select(), GUISUMOAbstractView::showToolTipFor(), and GUISelectedStorage::toggleSelection().
GUIGlObject * GUIGlObjectStorage::getObjectBlocking (const std::string & fullName)
Returns the object from the container locking it.
The lock prevents the object from being deleted while it is accessed. The object is moved from "myMap" to "myBlocked".
Parameters
[in] id The id of the object to return
Returns
The object with the given id or 0 if no such object is known
Definition at line 91 of file GUIGlObjectStorage.cpp.
References getObjectBlocking(), myFullNameMap, and myLock.
GUIGlObjectStorage& GUIGlObjectStorage::operator= (const GUIGlObjectStorage & s) private
invalidate assignment operator
GUIGlID GUIGlObjectStorage::registerObject (GUIGlObject * object, const std::string & fullName)
Registers an object.
This done within the constructor of the GUIGlObject; The object's "setGLID" method is called giving the next free id.
Parameters
[in] object The object to register
[in] fullName The full name of the object to register
Returns
the GUIGlObject under which the object has been registered
Definition at line 62 of file GUIGlObjectStorage.cpp.
References myAktID, myFullNameMap, myLock, and myMap.
Referenced by GUIGlObject::GUIGlObject().
bool GUIGlObjectStorage::remove (GUIGlID id)
Removes the named object from this container.
This function returns true if the object may be deleted; otherwise it's kept in an internal storage (for visualisation etc.) and will be removed by this class
Parameters
[in] id The id of the object to remove
Returns
Whether the object could be removed (and may be deleted)
Definition at line 102 of file GUIGlObjectStorage.cpp.
References my2Delete, myBlocked, myFullNameMap, myLock, and myMap.
Referenced by GUIGlObject::~GUIGlObject().
void GUIGlObjectStorage::setNetObject (GUIGlObject * object) inline
Sets the given object as the "network" object.
Parameters
[in] object The object to set as network object
Definition at line 134 of file GUIGlObjectStorage.h.
References myNetObject.
Referenced by GNENet::GNENet(), and GUINet::GUINet().
void GUIGlObjectStorage::unblockObject (GUIGlID id)
Marks an object as unblocked.
The object is moved from "myBlocked" to "myMap".
Parameters
[in] id The id of the object to unblock
Definition at line 129 of file GUIGlObjectStorage.cpp.
References myBlocked, myLock, and myMap.
Referenced by GUIMessageWindow::appendMsg(), GUISUMOAbstractView::centerTo(), GUISelectedStorage::deselect(), GNEViewNet::getEdgeAtCursorPosition(), GNEViewNet::getEdgesAtCursorPosition(), GNEViewNet::getJunctionAtCursorPosition(), GNEViewNet::getLaneAtCurserPosition(), GNESelectorFrame::getMatches(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GNESelectorFrame::handleIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onDoubleClicked(), GNEViewNet::onLeftBtnPress(), GUISUMOAbstractView::openObjectDialog(), GUIDialog_GLChosenEditor::rebuildList(), GNENet::retrieveAttributeCarriers(), GUISelectedStorage::save(), GUISelectedStorage::select(), GUIMessageWindow::setCursorPos(), GUISUMOAbstractView::showToolTipFor(), and GUISelectedStorage::toggleSelection().
Field Documentation
GUIGlObjectStorage GUIGlObjectStorage::gIDStorage static
A single static instance of this class.
Definition at line 149 of file GUIGlObjectStorage.h.
Referenced by GUIMessageWindow::appendMsg(), GUISUMOAbstractView::centerTo(), GUIRunThread::deleteSim(), GUISelectedStorage::deselect(), GUIMessageWindow::getActiveStringObject(), GNEViewNet::getEdgeAtCursorPosition(), GNEViewNet::getEdgesAtCursorPosition(), GNEViewNet::getJunctionAtCursorPosition(), GNEViewNet::getLaneAtCurserPosition(), GUIViewTraffic::getLaneUnderCursor(), GNESelectorFrame::getMatches(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GNENet::GNENet(), GUIGlObject::GUIGlObject(), GUINet::GUINet(), GNESelectorFrame::handleIDs(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GUISUMOViewParent::onCmdLocate(), GNEViewParent::onCmdLocate(), GNEConnectorFrame::onCmdResetSelectedConnections(), GNEViewNet::onDoubleClicked(), GNEViewNet::onLeftBtnPress(), GUISUMOAbstractView::openObjectDialog(), GUIDialog_GLChosenEditor::rebuildList(), GNENet::retrieveAttributeCarriers(), GUISelectedStorage::save(), GUISelectedStorage::select(), GUIMessageWindow::setCursorPos(), GUISUMOAbstractView::showToolTipFor(), GUISelectedStorage::toggleSelection(), and GUIGlObject::~GUIGlObject().
ObjectMap GUIGlObjectStorage::my2Delete private
Objects to delete.
Definition at line 171 of file GUIGlObjectStorage.h.
Referenced by remove().
GUIGlID GUIGlObjectStorage::myAktID private
The next id to give; initially zero, increased by one with each object registration.
Definition at line 174 of file GUIGlObjectStorage.h.
Referenced by clear(), and registerObject().
ObjectMap GUIGlObjectStorage::myBlocked private
The currently accessed objects.
Definition at line 168 of file GUIGlObjectStorage.h.
Referenced by getObjectBlocking(), remove(), and unblockObject().
std::map<std::string, GUIGlObject*> GUIGlObjectStorage::myFullNameMap private
Definition at line 165 of file GUIGlObjectStorage.h.
Referenced by getObjectBlocking(), registerObject(), and remove().
MFXMutex GUIGlObjectStorage::myLock mutable private
A lock to avoid parallel access on the storages.
Definition at line 177 of file GUIGlObjectStorage.h.
Referenced by clear(), getAllIDs(), getObjectBlocking(), registerObject(), remove(), and unblockObject().
ObjectMap GUIGlObjectStorage::myMap private
The known objects which are not accessed currently.
Definition at line 161 of file GUIGlObjectStorage.h.
Referenced by clear(), getAllIDs(), getObjectBlocking(), registerObject(), remove(), and unblockObject().
GUIGlObject* GUIGlObjectStorage::myNetObject private
The network object.
Definition at line 180 of file GUIGlObjectStorage.h.
Referenced by getNetObject(), and setNetObject().
The documentation for this class was generated from the following files:
GUIGlObjectStorage.h
GUIGlObjectStorage.cpp