SUMO - Simulation of Urban MObility: AGBusLine Class Reference
AGBusLine Class Reference
#include <AGBusLine.h>
Public Member Functions
AGBusLine (std::string lineNr)
void generateBuses (int start, int stop, int rate)
void locateRevStation (AGPosition pos)
void locateStation (AGPosition pos)
int nbrBuses ()
void printBuses ()
void setBusNames ()
void setMaxTripTime (int time)
Data Fields
std::list< AGBus > buses
std::list< AGBus > revBuses
std::list< AGPosition > revStations
std::list< AGPosition > stations
Private Member Functions
std::string createName ()
int getReady (int time)
Private Attributes
int busNbr
std::string lineNumber
int maxTripTime
Detailed Description
Definition at line 48 of file AGBusLine.h.
Constructor & Destructor Documentation
AGBusLine::AGBusLine (std::string lineNr) inline
Definition at line 50 of file AGBusLine.h.
References generateBuses(), locateRevStation(), locateStation(), nbrBuses(), printBuses(), setBusNames(), and setMaxTripTime().
Member Function Documentation
std::string AGBusLine::createName () private
Returns
: a name for a new Bus. unique for the city.
Definition at line 119 of file AGBusLine.cpp.
References busNbr, and lineNumber.
Referenced by setBusNames().
void AGBusLine::generateBuses (int start, int stop, int rate)
Definition at line 150 of file AGBusLine.cpp.
References buses, and revBuses.
Referenced by AGBusLine(), and AGActivityGenHandler::parseFrequency().
int AGBusLine::getReady (int time) private
Parameters
time time of departure of the bus in one direction (current time)
Returns
: time at which it will be ready for going in the opposite direction
Definition at line 127 of file AGBusLine.cpp.
References AGTime::addMinutes(), AGTime::addSeconds(), AGTime::getTime(), maxTripTime, and PAUSE_TIME.
Referenced by setBusNames().
void AGBusLine::locateRevStation (AGPosition pos)
Definition at line 145 of file AGBusLine.cpp.
References revStations.
Referenced by AGBusLine(), and AGActivityGenHandler::parseStation().
void AGBusLine::locateStation (AGPosition pos)
Definition at line 140 of file AGBusLine.cpp.
References stations.
Referenced by AGBusLine(), and AGActivityGenHandler::parseStation().
int AGBusLine::nbrBuses ()
Definition at line 135 of file AGBusLine.cpp.
References buses.
Referenced by AGBusLine().
void AGBusLine::printBuses ()
Definition at line 161 of file AGBusLine.cpp.
References buses, lineNumber, and revBuses.
Referenced by AGBusLine().
void AGBusLine::setBusNames ()
Definition at line 60 of file AGBusLine.cpp.
References buses, busNbr, createName(), getReady(), and revBuses.
Referenced by AGBusLine().
void AGBusLine::setMaxTripTime (int time)
Definition at line 55 of file AGBusLine.cpp.
References maxTripTime.
Referenced by AGBusLine(), and AGActivityGenHandler::parseBusLine().
Field Documentation
std::list<AGBus> AGBusLine::buses
Definition at line 62 of file AGBusLine.h.
Referenced by generateBuses(), AGActivities::generateBusTraffic(), nbrBuses(), printBuses(), and setBusNames().
int AGBusLine::busNbr private
Definition at line 79 of file AGBusLine.h.
Referenced by createName(), and setBusNames().
std::string AGBusLine::lineNumber private
Definition at line 77 of file AGBusLine.h.
Referenced by createName(), and printBuses().
int AGBusLine::maxTripTime private
Definition at line 78 of file AGBusLine.h.
Referenced by getReady(), and setMaxTripTime().
std::list<AGBus> AGBusLine::revBuses
Definition at line 63 of file AGBusLine.h.
Referenced by generateBuses(), AGActivities::generateBusTraffic(), printBuses(), and setBusNames().
std::list<AGPosition> AGBusLine::revStations
Definition at line 61 of file AGBusLine.h.
Referenced by AGActivities::generateBusTraffic(), and locateRevStation().
std::list<AGPosition> AGBusLine::stations
Definition at line 60 of file AGBusLine.h.
Referenced by AGActivities::generateBusTraffic(), and locateStation().
The documentation for this class was generated from the following files:
AGBusLine.h
AGBusLine.cpp