SUMO - Simulation of Urban MObility: fast_mutex Class Reference
fast_mutex Class Reference
#include <fast_mutex.h>
Public Member Functions
fast_mutex ()
void lock ()
void unlock ()
~fast_mutex ()
Private Member Functions
fast_mutex (const fast_mutex &)
fast_mutex & operator= (const fast_mutex &)
Detailed Description
Class for non-reentrant fast mutexes. This is the null implementation for single-threaded environments.
Definition at line 355 of file fast_mutex.h.
Constructor & Destructor Documentation
fast_mutex::fast_mutex () inline
Definition at line 361 of file fast_mutex.h.
Referenced by unlock().
fast_mutex::~fast_mutex () inline
Definition at line 367 of file fast_mutex.h.
References _FAST_MUTEX_ASSERT.
fast_mutex::fast_mutex (const fast_mutex &) private
Member Function Documentation
void fast_mutex::lock () inline
Definition at line 371 of file fast_mutex.h.
References _FAST_MUTEX_ASSERT.
Referenced by fast_mutex_autolock::fast_mutex_autolock().
fast_mutex& fast_mutex::operator= (const fast_mutex &) private
Referenced by unlock(), and fast_mutex_autolock::~fast_mutex_autolock().
void fast_mutex::unlock () inline
Definition at line 378 of file fast_mutex.h.
References _FAST_MUTEX_ASSERT, fast_mutex(), NVWA_NAMESPACE_BEGIN, NVWA_NAMESPACE_END, and operator=().
Referenced by fast_mutex_autolock::~fast_mutex_autolock().
The documentation for this class was generated from the following file:
fast_mutex.h