SUMO - Simulation of Urban MObility: TraCITestClient Class Reference
TraCITestClient Class Reference
A test execution class.
#include <TraCITestClient.h>
Public Types
typedef std::map< std::string, SubscribedValues > SubscribedContextValues
typedef std::map< std::string, TraCIValues > SubscribedValues
typedef std::map< int, TraCIValue > TraCIValues
{object->{variable->value}}
Structures definitions
typedef std::vector< TraCIPosition > TraCIPositionVector
Public Member Functions
bool run (std::string fileName, int port, std::string host="localhost")
Runs a test.
void simulationStep (SUMOTime time=0)
Advances by one step (or up to the given time)
TraCITestClient (std::string outputFileName="testclient_result.out")
Constructor.
~TraCITestClient ()
Destructor.
Connection handling
void connect (const std::string &host, int port)
Connects to the specified SUMO server.
void close ()
Closes the connection.
Atomar getter
SUMOTime getSUMOTime (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
int getUnsignedByte (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
int getByte (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
int getInt (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
SUMOReal getFloat (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
SUMOReal getDouble (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
TraCIBoundary getBoundingBox (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
TraCIPositionVector getPolygon (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
TraCIPosition getPosition (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
std::string getString (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
std::vector< std::string > getStringVector (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
TraCIColor getColor (int cmd, int var, const std::string &id, tcpip::Storage *add=0)
Data Fields
EdgeScope edge
Scope for interaction with edges.
GUIScope gui
Scope for interaction with the gui.
InductionLoopScope inductionloop
Scope for interaction with inductive loops.
JunctionScope junction
Scope for interaction with junctions.
LaneScope lane
Scope for interaction with lanes.
MeMeScope multientryexit
Scope for interaction with multi-entry/-exit detectors.
PersonScope person
Scope for interaction with persons.
POIScope poi
Scope for interaction with POIs.
PolygonScope polygon
Scope for interaction with polygons.
RouteScope route
Scope for interaction with routes.
SimulationScope simulation
Scope for interaction with the simulation.
TrafficLightScope trafficlights
Scope for interaction with traffic lights.
VehicleScope vehicle
Scope for interaction with vehicles.
VehicleTypeScope vehicletype
Scope for interaction with vehicle types.
Protected Member Functions
void readContextSubscription (tcpip::Storage &inMsg)
void readVariables (tcpip::Storage &inMsg, const std::string &objectID, int variableCount, SubscribedValues &into)
void readVariableSubscription (tcpip::Storage &inMsg)
void send_commandMoveToXY (const std::string &vehicleID, const std::string &edgeID, const int lane, const SUMOReal x, const SUMOReal y, const SUMOReal angle, const int keepRoute) const
Commands handling
void commandSimulationStep (SUMOTime time)
Sends and validates a simulation step command.
void commandClose ()
Sends and validates a Close command.
void commandGetVariable (int domID, int varID, const std::string &objID, tcpip::Storage *addData=0)
Sends and validates a GetVariable command.
void commandSetValue (int domID, int varID, const std::string &objID, std::ifstream &defFile)
Sends and validates a SetVariable command.
void commandSubscribeObjectVariable (int domID, const std::string &objID, SUMOTime beginTime, SUMOTime endTime, int varNo, std::ifstream &defFile)
Sends and validates a SubscribeVariable command.
void commandSubscribeContextVariable (int domID, const std::string &objID, SUMOTime beginTime, SUMOTime endTime, int domain, SUMOReal range, int varNo, std::ifstream &defFile)
Sends and validates a SubscribeContext command.
Command sending methods
void send_commandSimulationStep (SUMOTime time) const
Sends a SimulationStep command.
void send_commandClose () const
Sends a Close command.
void send_commandGetVariable (int domID, int varID, const std::string &objID, tcpip::Storage *add=0) const
Sends a GetVariable request.
void send_commandSetValue (int domID, int varID, const std::string &objID, tcpip::Storage &content) const
Sends a SetVariable request.
void send_commandSubscribeObjectVariable (int domID, const std::string &objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > &vars) const
Sends a SubscribeVariable request.
void send_commandSubscribeObjectContext (int domID, const std::string &objID, SUMOTime beginTime, SUMOTime endTime, int domain, SUMOReal range, const std::vector< int > &vars) const
Sends a SubscribeContext request.
void check_resultState (tcpip::Storage &inMsg, int command, bool ignoreCommandId=false, std::string *acknowledgement=0) const
Validates the result state of a command.
int check_commandGetResult (tcpip::Storage &inMsg, int command, int expectedType=-1, bool ignoreCommandId=false) const
Validates the result state of a command.
void processGET (tcpip::Storage &inMsg, int command, int expectedType, bool ignoreCommandId=false) const
Static Protected Member Functions
template<class T >
static std::string toString (const T &t, std::streamsize accuracy=OUTPUT_ACCURACY)
Protected Attributes
tcpip::Socket * mySocket
The socket.
SubscribedContextValues mySubscribedContextValues
SubscribedValues mySubscribedValues
Private Member Functions
void testAPI ()
call all API methods once
Report helper
void writeResult ()
Writes the results file.
void errorMsg (std::stringstream &msg)
Writes an error message.
Results validation methods
bool validateSimulationStep2 (tcpip::Storage &inMsg)
Validates whether the given message is a valid answer to CMD_SIMSTEP2.
bool validateSubscription (tcpip::Storage &inMsg)
Validates whether the given message is a valid subscription return message.
Conversion helper
int setValueTypeDependant (tcpip::Storage &into, std::ifstream &defFile, std::stringstream &msg)
Parses the next value type / value pair from the stream and inserts it into the storage.
void readAndReportTypeDependent (tcpip::Storage &inMsg, int valueDataType)
Reads a value of the given type from the given storage and reports it.
Private Attributes
std::stringstream answerLog
Stream containing the log.
std::string outputFileName
The name of the file to write the results log into.
Detailed Description
A test execution class.
Reads a program file and executes the actions stored within it
Definition at line 53 of file TraCITestClient.h.
Member Typedef Documentation
typedef std::map<std::string, SubscribedValues> TraCIAPI::SubscribedContextValues inherited
Definition at line 560 of file TraCIAPI.h.
typedef std::map<std::string, TraCIValues> TraCIAPI::SubscribedValues inherited
Definition at line 559 of file TraCIAPI.h.
typedef std::vector<TraCIPosition> TraCIAPI::TraCIPositionVector inherited
Definition at line 83 of file TraCIAPI.h.
typedef std::map<int, TraCIValue> TraCIAPI::TraCIValues inherited
{object->{variable->value}}
Definition at line 558 of file TraCIAPI.h.
Constructor & Destructor Documentation
TraCITestClient::TraCITestClient (std::string outputFileName = "testclient_result.out")
Constructor.
Parameters
[in] outputFileName The name of the file the outputs will be written into
Definition at line 59 of file TraCITestClient.cpp.
References answerLog.
TraCITestClient::~TraCITestClient ()
Destructor.
Definition at line 67 of file TraCITestClient.cpp.
References writeResult().
Member Function Documentation
int TraCIAPI::check_commandGetResult (tcpip::Storage & inMsg, int command, int expectedType = -1, bool ignoreCommandId = false) const protected inherited
Validates the result state of a command.
Returns
The command Id
Definition at line 280 of file TraCIAPI.cpp.
References tcpip::Storage::position(), tcpip::Storage::readInt(), tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), and TraCIAPI::toString().
Referenced by commandGetVariable(), TraCIAPI::processGET(), and TraCIAPI::simulationStep().
void TraCIAPI::check_resultState (tcpip::Storage & inMsg, int command, bool ignoreCommandId = false, std::string * acknowledgement = 0) const protected inherited
Validates the result state of a command.
Parameters
[in] inMsg The buffer to read the message from
[in] command The original command id
[in] ignoreCommandId Whether the returning command id shall be validated
[in] acknowledgement Pointer to an existing string into which the acknowledgement message shall be inserted
Definition at line 241 of file TraCIAPI.cpp.
References TraCIAPI::mySocket, tcpip::Storage::position(), tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), tcpip::Socket::receiveExact(), RTYPE_ERR, RTYPE_NOTIMPLEMENTED, RTYPE_OK, and TraCIAPI::toString().
Referenced by commandClose(), commandGetVariable(), commandSetValue(), commandSimulationStep(), commandSubscribeContextVariable(), commandSubscribeObjectVariable(), TraCIAPI::processGET(), and TraCIAPI::simulationStep().
void TraCIAPI::close () inherited
Closes the connection.
Definition at line 80 of file TraCIAPI.cpp.
References tcpip::Socket::close(), and TraCIAPI::mySocket.
Referenced by run().
void TraCITestClient::commandClose () protected
Sends and validates a Close command.
Definition at line 199 of file TraCITestClient.cpp.
References answerLog, TraCIAPI::check_resultState(), CMD_CLOSE, TraCIAPI::send_commandClose(), and tcpip::SocketException::what().
Referenced by run().
void TraCITestClient::commandGetVariable (int domID, int varID, const std::string & objID, tcpip::Storage * addData = 0) protected
Sends and validates a GetVariable command.
Parameters
[in] domID The ID of the domain the addressed object belongs to
[in] varID The ID of the variable one asks for
[in] objID The ID of the object a variable shall be retrieved from
[in] addData Storage to read additional data from, if needed
Definition at line 214 of file TraCITestClient.cpp.
References answerLog, TraCIAPI::check_commandGetResult(), TraCIAPI::check_resultState(), errorMsg(), readAndReportTypeDependent(), tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), TraCIAPI::send_commandGetVariable(), and tcpip::SocketException::what().
Referenced by run().
void TraCITestClient::commandSetValue (int domID, int varID, const std::string & objID, std::ifstream & defFile) protected
Sends and validates a SetVariable command.
Parameters
[in] domID The ID of the domain the addressed object belongs to
[in] varID The ID of the variable to set
[in] objID The ID of the object which shall be changed
[in] defFile Storage to read additional data from
Definition at line 247 of file TraCITestClient.cpp.
References answerLog, TraCIAPI::check_resultState(), errorMsg(), TraCIAPI::send_commandSetValue(), setValueTypeDependant(), and tcpip::SocketException::what().
Referenced by run().
void TraCITestClient::commandSimulationStep (SUMOTime time) protected
Sends and validates a simulation step command.
Parameters
[in] time The time step to send
Definition at line 183 of file TraCITestClient.cpp.
References answerLog, TraCIAPI::check_resultState(), CMD_SIMSTEP2, TraCIAPI::send_commandSimulationStep(), validateSimulationStep2(), and tcpip::SocketException::what().
Referenced by run().
void TraCITestClient::commandSubscribeContextVariable (int domID, const std::string & objID, SUMOTime beginTime, SUMOTime endTime, int domain, SUMOReal range, int varNo, std::ifstream & defFile) protected
Sends and validates a SubscribeContext command.
Parameters
[in] domID The ID of the domain the addressed object belongs to
[in] objID The ID of the object a variable shall be subscribed from
[in] beginTime The time the subscription shall begin at
[in] endTime The time the subscription shall end at
[in] domain The domain of the objects which shall be reported
[in] range The range within which objects shall be for being reported
[in] varNo The number of subscribed variables
[in] defFile The stream to read variable values from
Definition at line 294 of file TraCITestClient.cpp.
References answerLog, TraCIAPI::check_resultState(), TraCIAPI::send_commandSubscribeObjectContext(), validateSubscription(), and tcpip::SocketException::what().
Referenced by run().
void TraCITestClient::commandSubscribeObjectVariable (int domID, const std::string & objID, SUMOTime beginTime, SUMOTime endTime, int varNo, std::ifstream & defFile) protected
Sends and validates a SubscribeVariable command.
Parameters
[in] domID The ID of the domain the addressed object belongs to
[in] objID The ID of the object a variable shall be subscribed from
[in] beginTime The time the subscription shall begin at
[in] endTime The time the subscription shall end at
[in] varNo The number of subscribed variables
[in] defFile The stream to read variable values from
Definition at line 270 of file TraCITestClient.cpp.
References answerLog, TraCIAPI::check_resultState(), TraCIAPI::send_commandSubscribeObjectVariable(), validateSubscription(), and tcpip::SocketException::what().
Referenced by run().
void TraCIAPI::connect (const std::string & host, int port) inherited
Connects to the specified SUMO server.
Parameters
[in] host The name of the host to connect to
[in] port The port to connect to
Exceptions
tcpip::SocketException if the connection fails
Definition at line 67 of file TraCIAPI.cpp.
References tcpip::Socket::connect(), and TraCIAPI::mySocket.
Referenced by run().
void TraCITestClient::errorMsg (std::stringstream & msg) private
Writes an error message.
Parameters
[in] msg The message to write
Definition at line 337 of file TraCITestClient.cpp.
References answerLog.
Referenced by commandGetVariable(), commandSetValue(), and run().
TraCIAPI::TraCIBoundary TraCIAPI::getBoundingBox (int cmd, int var, const std::string & id, tcpip::Storage * add = 0) inherited
Definition at line 367 of file TraCIAPI.cpp.
References TraCIAPI::processGET(), tcpip::Storage::readDouble(), TraCIAPI::send_commandGetVariable(), TYPE_BOUNDINGBOX, TraCIAPI::TraCIBoundary::xMax, TraCIAPI::TraCIBoundary::xMin, TraCIAPI::TraCIBoundary::yMax, TraCIAPI::TraCIBoundary::yMin, TraCIAPI::TraCIBoundary::zMax, and TraCIAPI::TraCIBoundary::zMin.
int TraCIAPI::getByte (int cmd, int var, const std::string & id, tcpip::Storage * add = 0) inherited
Definition at line 331 of file TraCIAPI.cpp.
References TraCIAPI::processGET(), tcpip::Storage::readByte(), TraCIAPI::send_commandGetVariable(), and TYPE_BYTE.
TraCIAPI::TraCIColor TraCIAPI::getColor (int cmd, int var, const std::string & id, tcpip::Storage * add = 0) inherited
Definition at line 437 of file TraCIAPI.cpp.
References TraCIAPI::TraCIColor::a, TraCIAPI::TraCIColor::b, TraCIAPI::TraCIColor::g, TraCIAPI::processGET(), TraCIAPI::TraCIColor::r, tcpip::Storage::readUnsignedByte(), TraCIAPI::send_commandGetVariable(), and TYPE_COLOR.
Referenced by TraCIAPI::POIScope::~POIScope(), TraCIAPI::PolygonScope::~PolygonScope(), and TraCIAPI::VehicleTypeScope::~VehicleTypeScope().
SUMOReal TraCIAPI::getDouble (int cmd, int var, const std::string & id, tcpip::Storage * add = 0) inherited
Definition at line 358 of file TraCIAPI.cpp.
References TraCIAPI::processGET(), tcpip::Storage::readDouble(), TraCIAPI::send_commandGetVariable(), and TYPE_DOUBLE.
SUMOReal TraCIAPI::getFloat (int cmd, int var, const std::string & id, tcpip::Storage * add = 0) inherited
Definition at line 349 of file TraCIAPI.cpp.
References TraCIAPI::processGET(), tcpip::Storage::readFloat(), TraCIAPI::send_commandGetVariable(), SUMOReal, and TYPE_FLOAT.
int TraCIAPI::getInt (int cmd, int var, const std::string & id, tcpip::Storage * add = 0) inherited
Definition at line 340 of file TraCIAPI.cpp.
References TraCIAPI::processGET(), tcpip::Storage::readInt(), TraCIAPI::send_commandGetVariable(), SUMOReal, and TYPE_INTEGER.
TraCIAPI::TraCIPositionVector TraCIAPI::getPolygon (int cmd, int var, const std::string & id, tcpip::Storage * add = 0) inherited
Definition at line 383 of file TraCIAPI.cpp.
References TraCIAPI::processGET(), tcpip::Storage::readDouble(), tcpip::Storage::readInt(), TraCIAPI::send_commandGetVariable(), TYPE_POLYGON, TraCIAPI::TraCIPosition::x, TraCIAPI::TraCIPosition::y, and TraCIAPI::TraCIPosition::z.
TraCIAPI::TraCIPosition TraCIAPI::getPosition (int cmd, int var, const std::string & id, tcpip::Storage * add = 0) inherited
Definition at line 401 of file TraCIAPI.cpp.
References POSITION_2D, TraCIAPI::processGET(), tcpip::Storage::readDouble(), TraCIAPI::send_commandGetVariable(), TraCIAPI::TraCIPosition::x, TraCIAPI::TraCIPosition::y, and TraCIAPI::TraCIPosition::z.
Referenced by TraCIAPI::JunctionScope::~JunctionScope(), TraCIAPI::PersonScope::~PersonScope(), and TraCIAPI::POIScope::~POIScope().
std::string TraCIAPI::getString (int cmd, int var, const std::string & id, tcpip::Storage * add = 0) inherited
Definition at line 414 of file TraCIAPI.cpp.
References TraCIAPI::processGET(), tcpip::Storage::readString(), TraCIAPI::send_commandGetVariable(), and TYPE_STRING.
std::vector< std::string > TraCIAPI::getStringVector (int cmd, int var, const std::string & id, tcpip::Storage * add = 0) inherited
Definition at line 423 of file TraCIAPI.cpp.
References TraCIAPI::processGET(), tcpip::Storage::readInt(), tcpip::Storage::readString(), TraCIAPI::send_commandGetVariable(), and TYPE_STRINGLIST.
SUMOTime TraCIAPI::getSUMOTime (int cmd, int var, const std::string & id, tcpip::Storage * add = 0) inherited
Definition at line 313 of file TraCIAPI.cpp.
References TraCIAPI::processGET(), tcpip::Storage::readInt(), TraCIAPI::send_commandGetVariable(), and TYPE_INTEGER.
int TraCIAPI::getUnsignedByte (int cmd, int var, const std::string & id, tcpip::Storage * add = 0) inherited
Definition at line 322 of file TraCIAPI.cpp.
References TraCIAPI::processGET(), tcpip::Storage::readUnsignedByte(), TraCIAPI::send_commandGetVariable(), and TYPE_UBYTE.
void TraCIAPI::processGET (tcpip::Storage & inMsg, int command, int expectedType, bool ignoreCommandId = false) const protected inherited
Definition at line 304 of file TraCIAPI.cpp.
References TraCIAPI::check_commandGetResult(), and TraCIAPI::check_resultState().
Referenced by TraCIAPI::getBoundingBox(), TraCIAPI::getByte(), TraCIAPI::getColor(), TraCIAPI::getDouble(), TraCIAPI::getFloat(), TraCIAPI::getInt(), TraCIAPI::getPolygon(), TraCIAPI::getPosition(), TraCIAPI::getString(), TraCIAPI::getStringVector(), TraCIAPI::getSUMOTime(), and TraCIAPI::getUnsignedByte().
void TraCITestClient::readAndReportTypeDependent (tcpip::Storage & inMsg, int valueDataType) private
Reads a value of the given type from the given storage and reports it.
Parameters
[in] inMsg The storage to read the value from
[in] valueDataType The type of the expected value
Definition at line 559 of file TraCITestClient.cpp.
References answerLog, POSITION_2D, POSITION_3D, POSITION_ROADMAP, tcpip::Storage::readByte(), tcpip::Storage::readDouble(), tcpip::Storage::readFloat(), tcpip::Storage::readInt(), tcpip::Storage::readString(), tcpip::Storage::readStringList(), tcpip::Storage::readUnsignedByte(), SUMOReal, TLPHASE_GREEN, TLPHASE_RED, TLPHASE_YELLOW, TYPE_BOUNDINGBOX, TYPE_BYTE, TYPE_COLOR, TYPE_COMPOUND, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INTEGER, TYPE_POLYGON, TYPE_STRING, TYPE_STRINGLIST, TYPE_TLPHASELIST, and TYPE_UBYTE.
Referenced by commandGetVariable(), and validateSubscription().
void TraCIAPI::readContextSubscription (tcpip::Storage & inMsg) protected inherited
Definition at line 506 of file TraCIAPI.cpp.
References TraCIAPI::mySubscribedContextValues, tcpip::Storage::readInt(), tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), and TraCIAPI::readVariables().
Referenced by TraCIAPI::simulationStep().
void TraCIAPI::readVariables (tcpip::Storage & inMsg, const std::string & objectID, int variableCount, SubscribedValues & into) protected inherited
Definition at line 450 of file TraCIAPI.cpp.
References TraCIAPI::TraCIColor::a, TraCIAPI::TraCIColor::b, TraCIAPI::TraCIValue::color, TraCIAPI::TraCIColor::g, TraCIAPI::TraCIValue::position, POSITION_3D, TraCIAPI::TraCIColor::r, tcpip::Storage::readDouble(), tcpip::Storage::readInt(), tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), RTYPE_OK, TraCIAPI::TraCIValue::scalar, TraCIAPI::TraCIValue::string, TraCIAPI::toString(), TYPE_COLOR, TYPE_DOUBLE, TYPE_INTEGER, TYPE_STRING, TraCIAPI::TraCIPosition::x, TraCIAPI::TraCIPosition::y, and TraCIAPI::TraCIPosition::z.
Referenced by TraCIAPI::readContextSubscription(), and TraCIAPI::readVariableSubscription().
void TraCIAPI::readVariableSubscription (tcpip::Storage & inMsg) protected inherited
Definition at line 499 of file TraCIAPI.cpp.
References TraCIAPI::mySubscribedValues, tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), and TraCIAPI::readVariables().
Referenced by TraCIAPI::simulationStep().
bool TraCITestClient::run (std::string fileName, int port, std::string host = "localhost")
Runs a test.
Parameters
[in] fileName The name of the file containing the test script
[in] port The server port to connect to
[in] host The server name to connect to
Definition at line 73 of file TraCITestClient.cpp.
References TraCIAPI::close(), commandClose(), commandGetVariable(), commandSetValue(), commandSimulationStep(), commandSubscribeContextVariable(), commandSubscribeObjectVariable(), TraCIAPI::connect(), errorMsg(), setValueTypeDependant(), string2time(), SUMOReal, testAPI(), and tcpip::SocketException::what().
Referenced by main().
void TraCIAPI::send_commandClose () const protected inherited
Sends a Close command.
Definition at line 104 of file TraCIAPI.cpp.
References CMD_CLOSE, TraCIAPI::mySocket, tcpip::Socket::sendExact(), and tcpip::Storage::writeUnsignedByte().
Referenced by commandClose().
void TraCIAPI::send_commandGetVariable (int domID, int varID, const std::string & objID, tcpip::Storage * add = 0) const protected inherited
Sends a GetVariable request.
Parameters
[in] domID The domain of the variable
[in] varID The variable to retrieve
[in] objID The object to retrieve the variable from
[in] add Optional additional parameter
Definition at line 115 of file TraCIAPI.cpp.
References TraCIAPI::mySocket, tcpip::Socket::sendExact(), tcpip::Storage::size(), tcpip::Storage::writeStorage(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by commandGetVariable(), TraCIAPI::getBoundingBox(), TraCIAPI::getByte(), TraCIAPI::getColor(), TraCIAPI::getDouble(), TraCIAPI::getFloat(), TraCIAPI::getInt(), TraCIAPI::getPolygon(), TraCIAPI::getPosition(), TraCIAPI::getString(), TraCIAPI::getStringVector(), TraCIAPI::getSUMOTime(), and TraCIAPI::getUnsignedByte().
void TraCIAPI::send_commandMoveToXY (const std::string & vehicleID, const std::string & edgeID, const int lane, const SUMOReal x, const SUMOReal y, const SUMOReal angle, const int keepRoute) const protected inherited
Definition at line 221 of file TraCIAPI.cpp.
References CMD_SET_VEHICLE_VARIABLE, TraCIAPI::send_commandSetValue(), TYPE_BYTE, TYPE_COMPOUND, TYPE_DOUBLE, TYPE_INTEGER, TYPE_STRING, VAR_MOVE_TO_VTD, tcpip::Storage::writeByte(), tcpip::Storage::writeDouble(), tcpip::Storage::writeInt(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
void TraCIAPI::send_commandSetValue (int domID, int varID, const std::string & objID, tcpip::Storage & content) const protected inherited
Sends a SetVariable request.
Parameters
[in] domID The domain of the variable
[in] varID The variable to set
[in] objID The object to change
[in] content The value of the variable
Definition at line 142 of file TraCIAPI.cpp.
References TraCIAPI::mySocket, tcpip::Socket::sendExact(), tcpip::Storage::size(), tcpip::Storage::writeStorage(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by commandSetValue(), and TraCIAPI::send_commandMoveToXY().
void TraCIAPI::send_commandSimulationStep (SUMOTime time) const protected inherited
Sends a SimulationStep command.
Definition at line 91 of file TraCIAPI.cpp.
References CMD_SIMSTEP2, TraCIAPI::mySocket, tcpip::Socket::sendExact(), tcpip::Storage::writeInt(), and tcpip::Storage::writeUnsignedByte().
Referenced by commandSimulationStep(), and TraCIAPI::simulationStep().
void TraCIAPI::send_commandSubscribeObjectContext (int domID, const std::string & objID, SUMOTime beginTime, SUMOTime endTime, int domain, SUMOReal range, const std::vector< int > & vars) const protected inherited
Sends a SubscribeContext request.
Parameters
[in] domID The domain of the variable
[in] objID The object to subscribe the variables from
[in] beginTime The begin time step of subscriptions
[in] endTime The end time step of subscriptions
[in] domain The domain of the objects which values shall be returned
[in] range The range around the obj to investigate
[in] vars The variables to subscribe
Definition at line 191 of file TraCIAPI.cpp.
References TraCIAPI::mySocket, tcpip::Socket::sendExact(), tcpip::Storage::size(), tcpip::Storage::writeDouble(), tcpip::Storage::writeInt(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by commandSubscribeContextVariable().
void TraCIAPI::send_commandSubscribeObjectVariable (int domID, const std::string & objID, SUMOTime beginTime, SUMOTime endTime, const std::vector< int > & vars) const protected inherited
Sends a SubscribeVariable request.
Parameters
[in] domID The domain of the variable
[in] objID The object to subscribe the variables from
[in] beginTime The begin time step of subscriptions
[in] endTime The end time step of subscriptions
[in] vars The variables to subscribe
Definition at line 163 of file TraCIAPI.cpp.
References TraCIAPI::mySocket, tcpip::Socket::sendExact(), tcpip::Storage::size(), tcpip::Storage::writeInt(), tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by commandSubscribeObjectVariable().
int TraCITestClient::setValueTypeDependant (tcpip::Storage & into, std::ifstream & defFile, std::stringstream & msg) private
Parses the next value type / value pair from the stream and inserts it into the storage.
Parameters
[out] into The storage to add the value type and the value into
[in] defFile The file to read the values from
[out] msg If any error occurs, this should be filled
Returns
The number of written bytes
Definition at line 423 of file TraCITestClient.cpp.
References POSITION_2D, POSITION_3D, POSITION_ROADMAP, REQUEST_AIRDIST, REQUEST_DRIVINGDIST, TYPE_BYTE, TYPE_COLOR, TYPE_COMPOUND, TYPE_DOUBLE, TYPE_FLOAT, TYPE_INTEGER, TYPE_POLYGON, TYPE_STRING, TYPE_STRINGLIST, TYPE_UBYTE, tcpip::Storage::writeByte(), tcpip::Storage::writeDouble(), tcpip::Storage::writeFloat(), tcpip::Storage::writeInt(), tcpip::Storage::writeString(), tcpip::Storage::writeStringList(), and tcpip::Storage::writeUnsignedByte().
Referenced by commandSetValue(), and run().
void TraCIAPI::simulationStep (SUMOTime time = 0) inherited
Advances by one step (or up to the given time)
Definition at line 520 of file TraCIAPI.cpp.
References TraCIAPI::check_commandGetResult(), TraCIAPI::check_resultState(), CMD_SIMSTEP2, TraCIAPI::mySubscribedContextValues, TraCIAPI::mySubscribedValues, TraCIAPI::readContextSubscription(), tcpip::Storage::readInt(), TraCIAPI::readVariableSubscription(), RESPONSE_SUBSCRIBE_INDUCTIONLOOP_VARIABLE, RESPONSE_SUBSCRIBE_PERSON_VARIABLE, and TraCIAPI::send_commandSimulationStep().
Referenced by testAPI().
void TraCITestClient::testAPI () private
call all API methods once
Definition at line 675 of file TraCITestClient.cpp.
References TraCIAPI::RouteScope::add(), TraCIAPI::VehicleScope::add(), answerLog, CMD_GET_VEHICLE_VARIABLE, CMD_SUBSCRIBE_EDGE_CONTEXT, CMD_SUBSCRIBE_VEHICLE_VARIABLE, TraCIAPI::edge, TraCIAPI::SimulationScope::getContextSubscriptionResults(), TraCIAPI::SimulationScope::getCurrentTime(), TraCIAPI::EdgeScope::getIDCount(), TraCIAPI::VehicleScope::getIDCount(), TraCIAPI::EdgeScope::getIDList(), TraCIAPI::InductionLoopScope::getIDList(), TraCIAPI::RouteScope::getIDList(), TraCIAPI::VehicleScope::getIDList(), TraCIAPI::PersonScope::getIDList(), TraCIAPI::VehicleScope::getLaneID(), TraCIAPI::PersonScope::getNextEdge(), TraCIAPI::VehicleScope::getNextTLS(), TraCIAPI::VehicleScope::getRoadID(), TraCIAPI::PersonScope::getRoadID(), TraCIAPI::GUIScope::getSchema(), TraCIAPI::VehicleScope::getSlope(), TraCIAPI::VehicleScope::getSpeedMode(), TraCIAPI::SimulationScope::getSubscriptionResults(), TraCIAPI::PersonScope::getTypeID(), TraCIAPI::InductionLoopScope::getVehicleData(), TraCIAPI::VehicleScope::getWaitingTime(), TraCIAPI::PersonScope::getWaitingTime(), TraCIAPI::gui, TraCIAPI::inductionloop, joinToString(), TraCIAPI::VehicleScope::moveToXY(), TraCIAPI::person, TraCIAPI::VehicleScope::remove(), TraCIAPI::route, TraCIAPI::GUIScope::screenshot(), TraCIAPI::GUIScope::setSchema(), TraCIAPI::simulation, TraCIAPI::simulationStep(), TraCIAPI::SimulationScope::subscribe(), TraCIAPI::SimulationScope::subscribeContext(), TIME2STEPS, VAR_LANEPOSITION, VAR_ROAD_ID, and TraCIAPI::vehicle.
Referenced by run().
template<class T > static std::string TraCIAPI::toString (const T & t, std::streamsize accuracy = OUTPUT_ACCURACY) inline static protected inherited
Definition at line 945 of file TraCIAPI.h.
Referenced by TraCIAPI::VehicleScope::add(), TraCIAPI::check_commandGetResult(), TraCIAPI::check_resultState(), and TraCIAPI::readVariables().
bool TraCITestClient::validateSimulationStep2 (tcpip::Storage & inMsg) private
Validates whether the given message is a valid answer to CMD_SIMSTEP2.
Parameters
[in] inMsg The storage contain the message to validate
Returns
Whether the message is valid
Definition at line 348 of file TraCITestClient.cpp.
References answerLog, tcpip::Storage::readInt(), and validateSubscription().
Referenced by commandSimulationStep().
bool TraCITestClient::validateSubscription (tcpip::Storage & inMsg) private
Validates whether the given message is a valid subscription return message.
Parameters
[in] inMsg The storage contain the message to validate
Returns
Whether the message is valid
Definition at line 365 of file TraCITestClient.cpp.
References answerLog, readAndReportTypeDependent(), tcpip::Storage::readInt(), tcpip::Storage::readString(), tcpip::Storage::readUnsignedByte(), RESPONSE_SUBSCRIBE_GUI_CONTEXT, RESPONSE_SUBSCRIBE_GUI_VARIABLE, RESPONSE_SUBSCRIBE_INDUCTIONLOOP_CONTEXT, RESPONSE_SUBSCRIBE_INDUCTIONLOOP_VARIABLE, and RTYPE_OK.
Referenced by commandSubscribeContextVariable(), commandSubscribeObjectVariable(), and validateSimulationStep2().
void TraCITestClient::writeResult () private
Writes the results file.
Definition at line 321 of file TraCITestClient.cpp.
References answerLog, and outputFileName.
Referenced by ~TraCITestClient().
Field Documentation
std::stringstream TraCITestClient::answerLog private
Stream containing the log.
Definition at line 197 of file TraCITestClient.h.
Referenced by commandClose(), commandGetVariable(), commandSetValue(), commandSimulationStep(), commandSubscribeContextVariable(), commandSubscribeObjectVariable(), errorMsg(), readAndReportTypeDependent(), testAPI(), TraCITestClient(), validateSimulationStep2(), validateSubscription(), and writeResult().
EdgeScope TraCIAPI::edge inherited
Scope for interaction with edges.
Definition at line 832 of file TraCIAPI.h.
Referenced by testAPI().
GUIScope TraCIAPI::gui inherited
Scope for interaction with the gui.
Definition at line 834 of file TraCIAPI.h.
Referenced by testAPI().
InductionLoopScope TraCIAPI::inductionloop inherited
Scope for interaction with inductive loops.
Definition at line 836 of file TraCIAPI.h.
Referenced by testAPI().
JunctionScope TraCIAPI::junction inherited
Scope for interaction with junctions.
Definition at line 838 of file TraCIAPI.h.
LaneScope TraCIAPI::lane inherited
Scope for interaction with lanes.
Definition at line 840 of file TraCIAPI.h.
MeMeScope TraCIAPI::multientryexit inherited
Scope for interaction with multi-entry/-exit detectors.
Definition at line 842 of file TraCIAPI.h.
tcpip::Socket* TraCIAPI::mySocket protected inherited
The socket.
Definition at line 955 of file TraCIAPI.h.
Referenced by TraCIAPI::check_resultState(), TraCIAPI::close(), TraCIAPI::connect(), TraCIAPI::send_commandClose(), TraCIAPI::send_commandGetVariable(), TraCIAPI::send_commandSetValue(), TraCIAPI::send_commandSimulationStep(), TraCIAPI::send_commandSubscribeObjectContext(), TraCIAPI::send_commandSubscribeObjectVariable(), and TraCIAPI::~TraCIAPI().
SubscribedContextValues TraCIAPI::mySubscribedContextValues protected inherited
Definition at line 958 of file TraCIAPI.h.
Referenced by TraCIAPI::readContextSubscription(), and TraCIAPI::simulationStep().
SubscribedValues TraCIAPI::mySubscribedValues protected inherited
Definition at line 957 of file TraCIAPI.h.
Referenced by TraCIAPI::readVariableSubscription(), and TraCIAPI::simulationStep().
std::string TraCITestClient::outputFileName private
The name of the file to write the results log into.
Definition at line 194 of file TraCITestClient.h.
Referenced by writeResult().
PersonScope TraCIAPI::person inherited
Scope for interaction with persons.
Definition at line 858 of file TraCIAPI.h.
Referenced by testAPI().
POIScope TraCIAPI::poi inherited
Scope for interaction with POIs.
Definition at line 844 of file TraCIAPI.h.
PolygonScope TraCIAPI::polygon inherited
Scope for interaction with polygons.
Definition at line 846 of file TraCIAPI.h.
RouteScope TraCIAPI::route inherited
Scope for interaction with routes.
Definition at line 848 of file TraCIAPI.h.
Referenced by testAPI().
SimulationScope TraCIAPI::simulation inherited
Scope for interaction with the simulation.
Definition at line 850 of file TraCIAPI.h.
Referenced by testAPI().
TrafficLightScope TraCIAPI::trafficlights inherited
Scope for interaction with traffic lights.
Definition at line 852 of file TraCIAPI.h.
VehicleScope TraCIAPI::vehicle inherited
Scope for interaction with vehicles.
Definition at line 856 of file TraCIAPI.h.
Referenced by testAPI().
VehicleTypeScope TraCIAPI::vehicletype inherited
Scope for interaction with vehicle types.
Definition at line 854 of file TraCIAPI.h.
The documentation for this class was generated from the following files:
TraCITestClient.h
TraCITestClient.cpp