SUMO - Simulation of Urban MObility: PHEMlightdll::CEP Class Reference
PHEMlightdll::CEP Class Reference
#include <CEP.h>
Public Types
enum NormalizingType { NormalizingType_RatedPower, NormalizingType_DrivingPower, NormalizingType.RatedPower, NormalizingType.DrivingPower }
enum NormalizingType { NormalizingType_RatedPower, NormalizingType_DrivingPower, NormalizingType.RatedPower, NormalizingType.DrivingPower }
Public Member Functions
double CalcEngPower (double power)
double CalcEngPower (double power)
double CalcPower (double speed, double acc, double gradient)
double CalcPower (double speed, double acc, double gradient)
CEP (bool heavyVehicle, double vehicleMass, double vehicleLoading, double vehicleMassRot, double crossArea, double cWValue, double f0, double f1, double f2, double f3, double f4, double axleRatio, List< double > transmissionGearRatios, double auxPower, double ratedPower, double engineIdlingSpeed, double engineRatedSpeed, double effictiveWheelDiameter, double pNormV0, double pNormP0, double pNormV1, double pNormP1, string vehicelFuelType, List< List< double >> matrixFC, List< string > headerLinePollutants, List< List< double >> matrixPollutants, List< List< double >> matrixSpeedRotational, List< List< double >> normedDragTable, double idlingFC, List< double > idlingPollutants)
CEP (bool heavyVehicle, double vehicleMass, double vehicleLoading, double vehicleMassRot, double crossArea, double cWValue, double f0, double f1, double f2, double f3, double f4, double axleRatio, std::vector< double > &transmissionGearRatios, double auxPower, double ratedPower, double engineIdlingSpeed, double engineRatedSpeed, double effictiveWheelDiameter, double pNormV0, double pNormP0, double pNormV1, double pNormP1, const std::string &vehicelFuelType, std::vector< std::vector< double > > &matrixFC, std::vector< std::string > &headerLinePollutants, std::vector< std::vector< double > > &matrixPollutants, std::vector< std::vector< double > > &matrixSpeedRotational, std::vector< std::vector< double > > &normedDragTable, double idlingFC, std::vector< double > &idlingPollutants)
double GetCO2Emission (double _FC, double _CO, double _HC, Helpers *VehicleClass)
double GetCO2Emission (double _FC, double _CO, double _HC, Helpers VehicleClass)
double GetDecelCoast (double speed, double acc, double gradient)
double GetDecelCoast (double speed, double acc, double gradient)
double GetDragCoeffecient (double nNorm)
const double & getDrivingPower () const
double GetEmission (const std::string &pollutant, double power, double speed, Helpers *VehicleClass)
double GetEmission (string pollutant, double power, double speed, Helpers VehicleClass)
const std::string & getFuelType () const
double GetGearCoeffecient (double speed)
const bool & getHeavyVehicle () const
const double & getNormalizingPower () const
const NormalizingType & getNormalizingTypeX () const
double GetNormedEmission (string pollutant, double power, double speed, Helpers VehicleClass)
const double & getRatedPower () const
double GetRotationalCoeffecient (double speed)
double GetRotationalCoeffecient (double speed)
void setDrivingPower (const double &value)
void setRatedPower (const double &value)
Static Public Member Functions
static CEP AddRangeCeps (CEP[] cps, Helpers Helper)
static List< double > CreatePattern (double min, double max, double increment)
static CEP operator* (CEP cp1, double d)
Protected Attributes
double _auxPower
double _axleRatio
std::vector< double > _cepCurveFC
List< double > _cepCurveFC
std::map< std::string, std::vector< double > > _cepCurvePollutants
Dictionary< string, List< double > > _cepCurvePollutants
std::map< std::string, std::vector< double > > _cepNormalizedCurvePollutants
Dictionary< string, List< double > > _cepNormalizedCurvePollutants
double _crossSectionalArea
double _cWValue
std::vector< double > _dragNormTable
List< double > _dragNormTable
double _effectiveWheelDiameter
double _engineIdlingSpeed
double _engineRatedSpeed
std::vector< double > _gearTransmissionCurve
List< double > _gearTransmissionCurve
double _idlingValueFC
std::map< std::string, double > _idlingValuesPollutants
Dictionary< string, double > _idlingValuesPollutants
double _massVehicle
std::vector< double > _nNormTable
List< double > _nNormTable
std::vector< double > _normailzedPowerPatternPollutants
List< double > _normailzedPowerPatternPollutants
std::vector< double > _normalizedPowerPatternFC
List< double > _normalizedPowerPatternFC
std::vector< double > _normedCepCurveFC
List< double > _normedCepCurveFC
double _pNormP0
double _pNormP1
double _pNormV0
double _pNormV1
std::vector< double > _powerPatternFC
List< double > _powerPatternFC
std::vector< double > _powerPatternPollutants
List< double > _powerPatternPollutants
double _resistanceF0
double _resistanceF1
double _resistanceF2
double _resistanceF3
double _resistanceF4
std::vector< double > _speedCurveRotational
List< double > _speedCurveRotational
std::vector< double > _speedPatternRotational
List< double > _speedPatternRotational
double _vehicleLoading
double _vehicleMassRot
Properties
double DrivingPower [get, set]
string FuelType [get]
bool HeavyVehicle [get]
double NormalizingPower [get]
NormalizingType NormalizingTypeX [get]
double RatedPower [get, set]
Private Member Functions
CEP (bool heavyVehicle, double vehicleMass, double vehicleLoading, double vehicleMassRot, double crossArea, double cWValue, double f0, double f1, double f2, double f3, double f4, double axleRatio, double auxPower, double ratedPower, double engineIdlingSpeed, double engineRatedSpeed, double effictiveWheelDiameter, double pNormV0, double pNormP0, double pNormV1, double pNormP1)
void FindLowerUpperInPattern (int &lowerIndex, int &upperIndex, std::vector< double > &pattern, double value)
void FindLowerUpperInPattern (out int lowerIndex, out int upperIndex, List< double > pattern, double value)
void InitializeInstanceFields ()
double Interpolate (double px, double p1, double p2, double e1, double e2)
double Interpolate (double px, double p1, double p2, double e1, double e2)
Private Attributes
double _drivingPower
std::string _fuelType
string _fuelType
bool _heavyVehicle
double _normalizingPower
NormalizingType _normalizingType
double _ratedPower
Detailed Description
Definition at line 16 of file CEP.h.
Member Enumeration Documentation
enum PHEMlightdll::CEP::NormalizingType
Enumerator
NormalizingType_RatedPower
NormalizingType_DrivingPower
RatedPower
DrivingPower
Definition at line 40 of file CEP.h.
enum PHEMlightdll.CEP.NormalizingType strong
Enumerator
NormalizingType_RatedPower
NormalizingType_DrivingPower
RatedPower
DrivingPower
Definition at line 270 of file CEP.cs.
Constructor & Destructor Documentation
PHEMlightdll::CEP::CEP (bool heavyVehicle, double vehicleMass, double vehicleLoading, double vehicleMassRot, double crossArea, double cWValue, double f0, double f1, double f2, double f3, double f4, double axleRatio, std::vector< double > & transmissionGearRatios, double auxPower, double ratedPower, double engineIdlingSpeed, double engineRatedSpeed, double effictiveWheelDiameter, double pNormV0, double pNormP0, double pNormV1, double pNormP1, const std::string & vehicelFuelType, std::vector< std::vector< double > > & matrixFC, std::vector< std::string > & headerLinePollutants, std::vector< std::vector< double > > & matrixPollutants, std::vector< std::vector< double > > & matrixSpeedRotational, std::vector< std::vector< double > > & normedDragTable, double idlingFC, std::vector< double > & idlingPollutants)
Definition at line 8 of file CEP.cpp.
References _auxPower, _axleRatio, _cepCurveFC, _cepCurvePollutants, _cepNormalizedCurvePollutants, _crossSectionalArea, _cWValue, _dragNormTable, _drivingPower, _effectiveWheelDiameter, _engineIdlingSpeed, _engineRatedSpeed, _fuelType, _gearTransmissionCurve, _heavyVehicle, _idlingValueFC, _idlingValuesPollutants, _massVehicle, _nNormTable, _normailzedPowerPatternPollutants, _normalizedPowerPatternFC, _normalizingPower, _normalizingType, _normedCepCurveFC, _pNormP0, _pNormP1, _pNormV0, _pNormV1, _powerPatternFC, _powerPatternPollutants, _ratedPower, _resistanceF0, _resistanceF1, _resistanceF2, _resistanceF3, _resistanceF4, _speedCurveRotational, _speedPatternRotational, _vehicleLoading, _vehicleMassRot, CalcPower(), getNormalizingPower(), InitializeInstanceFields(), PHEMlightdll::Constants::NORMALIZING_ACCELARATION, PHEMlightdll::Constants::NORMALIZING_SPEED, NormalizingType_DrivingPower, and NormalizingType_RatedPower.
Referenced by AddRangeCeps(), and operator*().
PHEMlightdll.CEP.CEP (bool heavyVehicle, double vehicleMass, double vehicleLoading, double vehicleMassRot, double crossArea, double cWValue, double f0, double f1, double f2, double f3, double f4, double axleRatio, List< double > transmissionGearRatios, double auxPower, double ratedPower, double engineIdlingSpeed, double engineRatedSpeed, double effictiveWheelDiameter, double pNormV0, double pNormP0, double pNormV1, double pNormP1, string vehicelFuelType, List< List< double >> matrixFC, List< string > headerLinePollutants, List< List< double >> matrixPollutants, List< List< double >> matrixSpeedRotational, List< List< double >> normedDragTable, double idlingFC, List< double > idlingPollutants) inline
Definition at line 17 of file CEP.cs.
References _auxPower, _axleRatio, _cepCurveFC, _cepCurvePollutants, _cepNormalizedCurvePollutants, _crossSectionalArea, _cWValue, _dragNormTable, _drivingPower, _effectiveWheelDiameter, _engineIdlingSpeed, _engineRatedSpeed, _fuelType, _gearTransmissionCurve, _heavyVehicle, _idlingValueFC, _idlingValuesPollutants, _massVehicle, _nNormTable, _normailzedPowerPatternPollutants, _normalizedPowerPatternFC, _normalizingPower, _normalizingType, _normedCepCurveFC, _pNormP0, _pNormP1, _pNormV0, _pNormV1, _powerPatternFC, _powerPatternPollutants, _ratedPower, _resistanceF0, _resistanceF1, _resistanceF2, _resistanceF3, _resistanceF4, _speedCurveRotational, _speedPatternRotational, _vehicleLoading, _vehicleMassRot, CalcPower(), PHEMlightdll::Constants.NORMALIZING_ACCELARATION, PHEMlightdll::Constants.NORMALIZING_SPEED, and NormalizingPower.
PHEMlightdll.CEP.CEP (bool heavyVehicle, double vehicleMass, double vehicleLoading, double vehicleMassRot, double crossArea, double cWValue, double f0, double f1, double f2, double f3, double f4, double axleRatio, double auxPower, double ratedPower, double engineIdlingSpeed, double engineRatedSpeed, double effictiveWheelDiameter, double pNormV0, double pNormP0, double pNormV1, double pNormP1) inline private
Definition at line 192 of file CEP.cs.
References _auxPower, _axleRatio, _crossSectionalArea, _cWValue, _effectiveWheelDiameter, _engineIdlingSpeed, _engineRatedSpeed, _heavyVehicle, _massVehicle, _pNormP0, _pNormP1, _pNormV0, _pNormV1, _ratedPower, _resistanceF0, _resistanceF1, _resistanceF2, _resistanceF3, _resistanceF4, _vehicleLoading, _vehicleMassRot, and HeavyVehicle.
Member Function Documentation
static CEP PHEMlightdll.CEP.AddRangeCeps (CEP[] cps, Helpers Helper) inline static
Definition at line 737 of file CEP.cs.
References CEP(), CreatePattern(), Max, Min, PHEMlightdll::Constants.NNORM_INCREMENT, PHEMlightdll::Constants.NORMALIZING_ACCELARATION, PHEMlightdll::Constants.NORMALIZING_SPEED, PHEMlightdll::Constants.POWER_FC_INCREMENT, PHEMlightdll::Constants.POWER_POLLUTANT_INCREMENT, and PHEMlightdll::Constants.SPEED_ROTATIONAL_INCREMENT.
Referenced by PHEMlightdll::CEPHandler.GetFleetCEP().
double PHEMlightdll::CEP::CalcEngPower (double power)
Definition at line 195 of file CEP.cpp.
References _powerPatternFC.
Referenced by PHEMlightdll.PHEMLight::CreateVehicleStateData().
double PHEMlightdll.CEP.CalcEngPower (double power) inline
Definition at line 397 of file CEP.cs.
double PHEMlightdll::CEP::CalcPower (double speed, double acc, double gradient)
Definition at line 176 of file CEP.cpp.
References _auxPower, _crossSectionalArea, _cWValue, PHEMlightdll::Constants::_DRIVE_TRAIN_EFFICIENCY, _massVehicle, _ratedPower, _resistanceF0, _resistanceF1, _resistanceF4, _vehicleLoading, _vehicleMassRot, PHEMlightdll::Constants::AIR_DENSITY_CONST, GetRotationalCoeffecient(), and PHEMlightdll::Constants::GRAVITY_CONST.
Referenced by CEP(), HelpersPHEMlight::compute(), and PHEMlightdll.PHEMLight::CreateVehicleStateData().
double PHEMlightdll.CEP.CalcPower (double speed, double acc, double gradient) inline
Definition at line 375 of file CEP.cs.
References PHEMlightdll::Constants._DRIVE_TRAIN_EFFICIENCY, _ratedPower, _vehicleLoading, PHEMlightdll::Constants.AIR_DENSITY_CONST, GetRotationalCoeffecient(), and PHEMlightdll::Constants.GRAVITY_CONST.
static List<double> PHEMlightdll.CEP.CreatePattern (double min, double max, double increment) inline static
Definition at line 981 of file CEP.cs.
References max, and min.
Referenced by AddRangeCeps().
void PHEMlightdll::CEP::FindLowerUpperInPattern (int & lowerIndex, int & upperIndex, std::vector< double > & pattern, double value) private
Definition at line 341 of file CEP.cpp.
Referenced by GetDecelCoast(), GetDragCoeffecient(), GetEmission(), GetGearCoeffecient(), GetNormedEmission(), and GetRotationalCoeffecient().
void PHEMlightdll.CEP.FindLowerUpperInPattern (out int lowerIndex, out int upperIndex, List< double > pattern, double value) inline private
Definition at line 670 of file CEP.cs.
double PHEMlightdll::CEP::GetCO2Emission (double _FC, double _CO, double _HC, Helpers * VehicleClass)
Definition at line 267 of file CEP.cpp.
References _fuelType, PHEMlightdll::Helpers::setErrMsg(), PHEMlightdll::Constants::strCNG, PHEMlightdll::Constants::strDiesel, and PHEMlightdll::Constants::strGasoline.
Referenced by HelpersPHEMlight::compute(), and PHEMlightdll.PHEMLight::CreateVehicleStateData().
double PHEMlightdll.CEP.GetCO2Emission (double _FC, double _CO, double _HC, Helpers VehicleClass) inline
Definition at line 538 of file CEP.cs.
References PHEMlightdll::Helpers.ErrMsg, PHEMlightdll::Constants.strCNG, PHEMlightdll::Constants.strDiesel, and PHEMlightdll::Constants.strGasoline.
double PHEMlightdll::CEP::GetDecelCoast (double speed, double acc, double gradient)
Definition at line 297 of file CEP.cpp.
References _axleRatio, _crossSectionalArea, _cWValue, _dragNormTable, _effectiveWheelDiameter, _engineIdlingSpeed, _engineRatedSpeed, _gearTransmissionCurve, _massVehicle, _nNormTable, _ratedPower, _resistanceF0, _resistanceF1, _resistanceF2, _resistanceF3, _resistanceF4, _speedPatternRotational, _vehicleLoading, FindLowerUpperInPattern(), GetRotationalCoeffecient(), PHEMlightdll::Constants::GRAVITY_CONST, Interpolate(), M_PI, and PHEMlightdll::Constants::SPEED_DCEL_MIN.
Referenced by PHEMlightdll.PHEMLight::CreateVehicleStateData(), and GetDecelCoast().
double PHEMlightdll.CEP.GetDecelCoast (double speed, double acc, double gradient) inline
Definition at line 568 of file CEP.cs.
References _axleRatio, _engineIdlingSpeed, _vehicleLoading, FindLowerUpperInPattern(), GetDecelCoast(), GetRotationalCoeffecient(), PHEMlightdll::Constants.GRAVITY_CONST, Interpolate(), and PHEMlightdll::Constants.SPEED_DCEL_MIN.
double PHEMlightdll.CEP.GetDragCoeffecient (double nNorm) inline
Definition at line 653 of file CEP.cs.
References FindLowerUpperInPattern(), and Interpolate().
const double & PHEMlightdll::CEP::getDrivingPower () const
Definition at line 168 of file CEP.cpp.
References _drivingPower.
double PHEMlightdll::CEP::GetEmission (const std::string & pollutant, double power, double speed, Helpers * VehicleClass)
Definition at line 206 of file CEP.cpp.
References _cepCurveFC, _cepCurvePollutants, _fuelType, _idlingValueFC, _idlingValuesPollutants, _powerPatternFC, _powerPatternPollutants, abs, FindLowerUpperInPattern(), Interpolate(), PHEMlightdll::Helpers::setErrMsg(), PHEMlightdll::Constants::strBEV, and PHEMlightdll::Constants::ZERO_SPEED_ACCURACY.
Referenced by PHEMlightdll.PHEMLight::CreateVehicleStateData(), and HelpersPHEMlight::getEmission().
double PHEMlightdll.CEP.GetEmission (string pollutant, double power, double speed, Helpers VehicleClass) inline
Definition at line 407 of file CEP.cs.
References _cepCurveFC, _idlingValueFC, _powerPatternFC, _powerPatternPollutants, PHEMlightdll::Helpers.ErrMsg, FindLowerUpperInPattern(), Interpolate(), PHEMlightdll::Constants.strBEV, PHEMlightdll::Helpers.tClass, and PHEMlightdll::Constants.ZERO_SPEED_ACCURACY.
const std::string & PHEMlightdll::CEP::getFuelType () const
Definition at line 148 of file CEP.cpp.
References _fuelType.
Referenced by HelpersPHEMlight::compute().
double PHEMlightdll.CEP.GetGearCoeffecient (double speed) inline
Definition at line 637 of file CEP.cs.
References FindLowerUpperInPattern(), and Interpolate().
const bool & PHEMlightdll::CEP::getHeavyVehicle () const
Definition at line 144 of file CEP.cpp.
References _heavyVehicle.
const double & PHEMlightdll::CEP::getNormalizingPower () const
Definition at line 164 of file CEP.cpp.
References _normalizingPower.
Referenced by CEP().
const CEP::NormalizingType & PHEMlightdll::CEP::getNormalizingTypeX () const
Definition at line 152 of file CEP.cpp.
References _normalizingType.
double PHEMlightdll.CEP.GetNormedEmission (string pollutant, double power, double speed, Helpers VehicleClass) inline
Definition at line 484 of file CEP.cs.
References _normailzedPowerPatternPollutants, _normalizedPowerPatternFC, _normedCepCurveFC, PHEMlightdll::Helpers.ErrMsg, FindLowerUpperInPattern(), and Interpolate().
const double & PHEMlightdll::CEP::getRatedPower () const
Definition at line 156 of file CEP.cpp.
References _ratedPower.
double PHEMlightdll::CEP::GetRotationalCoeffecient (double speed)
Definition at line 332 of file CEP.cpp.
References _speedCurveRotational, _speedPatternRotational, FindLowerUpperInPattern(), and Interpolate().
Referenced by CalcPower(), and GetDecelCoast().
double PHEMlightdll.CEP.GetRotationalCoeffecient (double speed) inline
Definition at line 620 of file CEP.cs.
References FindLowerUpperInPattern(), and Interpolate().
void PHEMlightdll::CEP::InitializeInstanceFields () private
Definition at line 391 of file CEP.cpp.
References _auxPower, _axleRatio, _crossSectionalArea, _cWValue, _drivingPower, _effectiveWheelDiameter, _engineIdlingSpeed, _engineRatedSpeed, _heavyVehicle, _idlingValueFC, _massVehicle, _normalizingPower, _normalizingType, _pNormP0, _pNormP1, _pNormV0, _pNormV1, _ratedPower, _resistanceF0, _resistanceF1, _resistanceF2, _resistanceF3, _resistanceF4, _vehicleLoading, and _vehicleMassRot.
Referenced by CEP().
double PHEMlightdll::CEP::Interpolate (double px, double p1, double p2, double e1, double e2) private
Definition at line 383 of file CEP.cpp.
Referenced by GetDecelCoast(), GetDragCoeffecient(), GetEmission(), GetGearCoeffecient(), GetNormedEmission(), and GetRotationalCoeffecient().
double PHEMlightdll.CEP.Interpolate (double px, double p1, double p2, double e1, double e2) inline private
Definition at line 722 of file CEP.cs.
static CEP PHEMlightdll.CEP.operator* (CEP cp1, double d) inline static
Definition at line 892 of file CEP.cs.
References CEP(), PHEMlightdll::Constants.NORMALIZING_ACCELARATION, and PHEMlightdll::Constants.NORMALIZING_SPEED.
void PHEMlightdll::CEP::setDrivingPower (const double & value)
Definition at line 172 of file CEP.cpp.
References _drivingPower.
void PHEMlightdll::CEP::setRatedPower (const double & value)
Definition at line 160 of file CEP.cpp.
References _ratedPower.
Field Documentation
double PHEMlightdll::CEP::_auxPower protected
Definition at line 80 of file CEP.h.
Referenced by CalcPower(), CEP(), and InitializeInstanceFields().
double PHEMlightdll::CEP::_axleRatio protected
Definition at line 79 of file CEP.h.
Referenced by CEP(), GetDecelCoast(), and InitializeInstanceFields().
std::vector<double> PHEMlightdll::CEP::_cepCurveFC protected
Definition at line 96 of file CEP.h.
Referenced by CEP(), and GetEmission().
List<double> PHEMlightdll.CEP._cepCurveFC protected
Definition at line 356 of file CEP.cs.
std::map<std::string, std::vector<double> > PHEMlightdll::CEP::_cepCurvePollutants protected
Definition at line 100 of file CEP.h.
Referenced by CEP(), and GetEmission().
Dictionary<string, List<double> > PHEMlightdll.CEP._cepCurvePollutants protected
Definition at line 360 of file CEP.cs.
std::map<std::string, std::vector<double> > PHEMlightdll::CEP::_cepNormalizedCurvePollutants protected
Definition at line 101 of file CEP.h.
Referenced by CEP().
Dictionary<string, List<double> > PHEMlightdll.CEP._cepNormalizedCurvePollutants protected
Definition at line 361 of file CEP.cs.
double PHEMlightdll::CEP::_crossSectionalArea protected
Definition at line 72 of file CEP.h.
Referenced by CalcPower(), CEP(), GetDecelCoast(), and InitializeInstanceFields().
double PHEMlightdll::CEP::_cWValue protected
Definition at line 73 of file CEP.h.
Referenced by CalcPower(), CEP(), GetDecelCoast(), and InitializeInstanceFields().
std::vector<double> PHEMlightdll::CEP::_dragNormTable protected
Definition at line 106 of file CEP.h.
Referenced by CEP(), and GetDecelCoast().
List<double> PHEMlightdll.CEP._dragNormTable protected
Definition at line 366 of file CEP.cs.
double PHEMlightdll::CEP::_drivingPower private
Definition at line 61 of file CEP.h.
Referenced by CEP(), getDrivingPower(), InitializeInstanceFields(), and setDrivingPower().
double PHEMlightdll::CEP::_effectiveWheelDiameter protected
Definition at line 88 of file CEP.h.
Referenced by CEP(), GetDecelCoast(), and InitializeInstanceFields().
double PHEMlightdll::CEP::_engineIdlingSpeed protected
Definition at line 87 of file CEP.h.
Referenced by CEP(), GetDecelCoast(), and InitializeInstanceFields().
double PHEMlightdll::CEP::_engineRatedSpeed protected
Definition at line 86 of file CEP.h.
Referenced by CEP(), GetDecelCoast(), and InitializeInstanceFields().
std::string PHEMlightdll::CEP::_fuelType private
Definition at line 35 of file CEP.h.
Referenced by CEP(), GetCO2Emission(), GetEmission(), and getFuelType().
string PHEMlightdll.CEP._fuelType private
Definition at line 259 of file CEP.cs.
std::vector<double> PHEMlightdll::CEP::_gearTransmissionCurve protected
Definition at line 98 of file CEP.h.
Referenced by CEP(), and GetDecelCoast().
List<double> PHEMlightdll.CEP._gearTransmissionCurve protected
Definition at line 358 of file CEP.cs.
bool PHEMlightdll::CEP::_heavyVehicle private
Definition at line 30 of file CEP.h.
Referenced by CEP(), getHeavyVehicle(), and InitializeInstanceFields().
double PHEMlightdll::CEP::_idlingValueFC protected
Definition at line 102 of file CEP.h.
Referenced by CEP(), GetEmission(), and InitializeInstanceFields().
std::map<std::string, double> PHEMlightdll::CEP::_idlingValuesPollutants protected
Definition at line 103 of file CEP.h.
Referenced by CEP(), and GetEmission().
Dictionary<string, double> PHEMlightdll.CEP._idlingValuesPollutants protected
Definition at line 363 of file CEP.cs.
double PHEMlightdll::CEP::_massVehicle protected
Definition at line 69 of file CEP.h.
Referenced by CalcPower(), CEP(), GetDecelCoast(), and InitializeInstanceFields().
std::vector<double> PHEMlightdll::CEP::_nNormTable protected
Definition at line 105 of file CEP.h.
Referenced by CEP(), and GetDecelCoast().
List<double> PHEMlightdll.CEP._nNormTable protected
Definition at line 365 of file CEP.cs.
std::vector<double> PHEMlightdll::CEP::_normailzedPowerPatternPollutants protected
Definition at line 93 of file CEP.h.
Referenced by CEP(), and GetNormedEmission().
List<double> PHEMlightdll.CEP._normailzedPowerPatternPollutants protected
Definition at line 353 of file CEP.cs.
std::vector<double> PHEMlightdll::CEP::_normalizedPowerPatternFC protected
Definition at line 92 of file CEP.h.
Referenced by CEP(), and GetNormedEmission().
List<double> PHEMlightdll.CEP._normalizedPowerPatternFC protected
Definition at line 352 of file CEP.cs.
double PHEMlightdll::CEP::_normalizingPower private
Definition at line 56 of file CEP.h.
Referenced by CEP(), getNormalizingPower(), and InitializeInstanceFields().
NormalizingType PHEMlightdll::CEP::_normalizingType private
Definition at line 45 of file CEP.h.
Referenced by CEP(), getNormalizingTypeX(), and InitializeInstanceFields().
std::vector<double> PHEMlightdll::CEP::_normedCepCurveFC protected
Definition at line 97 of file CEP.h.
Referenced by CEP(), and GetNormedEmission().
List<double> PHEMlightdll.CEP._normedCepCurveFC protected
Definition at line 357 of file CEP.cs.
double PHEMlightdll::CEP::_pNormP0 protected
Definition at line 82 of file CEP.h.
Referenced by CEP(), and InitializeInstanceFields().
double PHEMlightdll::CEP::_pNormP1 protected
Definition at line 84 of file CEP.h.
Referenced by CEP(), and InitializeInstanceFields().
double PHEMlightdll::CEP::_pNormV0 protected
Definition at line 81 of file CEP.h.
Referenced by CEP(), and InitializeInstanceFields().
double PHEMlightdll::CEP::_pNormV1 protected
Definition at line 83 of file CEP.h.
Referenced by CEP(), and InitializeInstanceFields().
std::vector<double> PHEMlightdll::CEP::_powerPatternFC protected
Definition at line 91 of file CEP.h.
Referenced by CalcEngPower(), CEP(), and GetEmission().
List<double> PHEMlightdll.CEP._powerPatternFC protected
Definition at line 351 of file CEP.cs.
std::vector<double> PHEMlightdll::CEP::_powerPatternPollutants protected
Definition at line 94 of file CEP.h.
Referenced by CEP(), and GetEmission().
List<double> PHEMlightdll.CEP._powerPatternPollutants protected
Definition at line 354 of file CEP.cs.
double PHEMlightdll::CEP::_ratedPower private
Definition at line 50 of file CEP.h.
Referenced by CalcPower(), CEP(), GetDecelCoast(), getRatedPower(), InitializeInstanceFields(), and setRatedPower().
double PHEMlightdll::CEP::_resistanceF0 protected
Definition at line 74 of file CEP.h.
Referenced by CalcPower(), CEP(), GetDecelCoast(), and InitializeInstanceFields().
double PHEMlightdll::CEP::_resistanceF1 protected
Definition at line 75 of file CEP.h.
Referenced by CalcPower(), CEP(), GetDecelCoast(), and InitializeInstanceFields().
double PHEMlightdll::CEP::_resistanceF2 protected
Definition at line 76 of file CEP.h.
Referenced by CEP(), GetDecelCoast(), and InitializeInstanceFields().
double PHEMlightdll::CEP::_resistanceF3 protected
Definition at line 77 of file CEP.h.
Referenced by CEP(), GetDecelCoast(), and InitializeInstanceFields().
double PHEMlightdll::CEP::_resistanceF4 protected
Definition at line 78 of file CEP.h.
Referenced by CalcPower(), CEP(), GetDecelCoast(), and InitializeInstanceFields().
std::vector<double> PHEMlightdll::CEP::_speedCurveRotational protected
Definition at line 99 of file CEP.h.
Referenced by CEP(), and GetRotationalCoeffecient().
List<double> PHEMlightdll.CEP._speedCurveRotational protected
Definition at line 359 of file CEP.cs.
std::vector<double> PHEMlightdll::CEP::_speedPatternRotational protected
Definition at line 90 of file CEP.h.
Referenced by CEP(), GetDecelCoast(), and GetRotationalCoeffecient().
List<double> PHEMlightdll.CEP._speedPatternRotational protected
Definition at line 350 of file CEP.cs.
double PHEMlightdll::CEP::_vehicleLoading protected
Definition at line 70 of file CEP.h.
Referenced by CalcPower(), CEP(), GetDecelCoast(), and InitializeInstanceFields().
double PHEMlightdll::CEP::_vehicleMassRot protected
Definition at line 71 of file CEP.h.
Referenced by CalcPower(), CEP(), and InitializeInstanceFields().
Property Documentation
double PHEMlightdll.CEP.DrivingPower get set
Definition at line 314 of file CEP.cs.
Referenced by PHEMlightdll.PHEMLight.CreateVehicleStateData().
string PHEMlightdll.CEP.FuelType get
Definition at line 261 of file CEP.cs.
bool PHEMlightdll.CEP.HeavyVehicle get
Definition at line 250 of file CEP.cs.
Referenced by CEP().
double PHEMlightdll.CEP.NormalizingPower get
Definition at line 303 of file CEP.cs.
Referenced by CEP().
NormalizingType PHEMlightdll.CEP.NormalizingTypeX get
Definition at line 277 of file CEP.cs.
double PHEMlightdll.CEP.RatedPower get set
Definition at line 288 of file CEP.cs.
Referenced by PHEMlightdll.PHEMLight.CreateVehicleStateData().
The documentation for this class was generated from the following files:
CEP.h
CEP.cs
CEP.cpp