SUMO - Simulation of Urban MObility: PHEMCEP Class Reference
PHEMCEP Class Reference
Data Handler for a single CEP emission data set.
#include <PHEMCEP.h>
Public Member Functions
double CalcPower (double v, double a, double slope, double vehicleLoading=0) const
Returns the power of used for a vehicle at state v,a, slope and loading.
double GetCdValue () const
Getter function to recieve vehicle data from CEP.
double GetCrossSectionalArea () const
Getter function to recieve vehicle data from CEP.
double GetDecelCoast (double speed, double acc, double gradient, double vehicleLoading) const
double GetEmission (const std::string &pollutantIdentifier, double power, double speed, bool normalized=false) const
Returns a emission measure for power[kW] level.
SUMOEmissionClass GetEmissionClass () const
Getter function to recieve vehicle data from CEP.
double GetMassRot () const
Getter function to recieve vehicle data from CEP.
double GetMassVehicle () const
Getter function to recieve vehicle data from CEP.
double GetMaxAccel (double v, double a, double gradient, double vehicleLoading=0) const
Returns the maximum accelaration for a vehicle at state v,a, slope and loading.
double GetRatedPower () const
Getter function to recieve vehicle data from CEP.
double GetResistanceF0 () const
Getter function to recieve vehicle data from CEP.
double GetResistanceF1 () const
Getter function to recieve vehicle data from CEP.
double GetResistanceF2 () const
Getter function to recieve vehicle data from CEP.
double GetResistanceF3 () const
Getter function to recieve vehicle data from CEP.
double GetResistanceF4 () const
Getter function to recieve vehicle data from CEP.
const std::string & GetVehicleFuelType () const
Getter function to recieve vehicle data from CEP.
double GetVehicleLoading () const
Getter function to recieve vehicle data from CEP.
PHEMCEP (bool heavyVehicel, SUMOEmissionClass emissionClass, const std::string &emissionClassIdentifier, double vehicleMass, double vehicleLoading, double vehicleMassRot, double crossArea, double cdValue, double f0, double f1, double f2, double f3, double f4, double ratedPower, double pNormV0, double pNormP0, double pNormV1, double pNormP1, double axleRatio, double engineIdlingSpeed, double engineRatedSpeed, double effectiveWheelDiameter, double idlingFC, const std::string &vehicleFuelType, const std::vector< std::vector< double > > &matrixFC, const std::vector< std::string > &headerLinePollutants, const std::vector< std::vector< double > > &matrixPollutants, const std::vector< std::vector< double > > &matrixSpeedRotational, const std::vector< std::vector< double > > &normedDragTable, const std::vector< double > &idlingValuesPollutants)
~PHEMCEP ()
Destructor.
Private Member Functions
void FindLowerUpperInPattern (int &lowerIndex, int &upperIndex, const std::vector< double > &pattern, double value) const
Finds bounding upper and lower index in pattern for value.
double GetDragCoeffecient (double nNorm) const
double GetGearCoeffecient (double speed) const
double GetPMaxNorm (double speed) const
Calculates maximum available rated power for speed.
double GetRotationalCoeffecient (double speed) const
Calculates rotational index for speed.
double Interpolate (double px, double p1, double p2, double e1, double e2) const
Interpolates emission linearly between two known power-emission pairs.
Private Attributes
double _axleRatio
double _cdValue
Cw value.
std::vector< double > _cepCurveFC
StringBijection< std::vector< double > > _cepCurvePollutants
double _crossSectionalArea
crosssectional area of vehicle
std::vector< double > _dragNormTable
double _drivingPower
double _effictiveWheelDiameter
SUMOEmissionClass _emissionClass
PHEM emission class of vehicle.
double _engineIdlingSpeed
double _engineRatedSpeed
std::vector< double > _gearTransmissionCurve
bool _heavyVehicle
double _idlingFC
StringBijection< double > _idlingValuesPollutants
double _massRot
rotational mass of vehicle
double _massVehicle
vehicle mass
std::vector< double > _nNormTable
std::vector< double > _normailzedPowerPatternPollutants
StringBijection< std::vector< double > > _normalizedCepCurvePollutants
std::vector< double > _normalizedPowerPatternFC
double _normalizingPower
NormalizingType _normalizingType
std::vector< double > _normedCepCurveFC
double _pNormP0
Step functions parameter for maximum rated power.
double _pNormP1
Step functions parameter for maximum rated power.
double _pNormV0
Step functions parameter for maximum rated power.
double _pNormV1
Step functions parameter for maximum rated power.
std::vector< double > _powerPatternFC
std::vector< double > _powerPatternPollutants
double _ratedPower
rated power of vehicle
double _resistanceF0
Rolling resistance f0.
double _resistanceF1
Rolling resistance f1.
double _resistanceF2
Rolling resistance f2.
double _resistanceF3
Rolling resistance f3.
double _resistanceF4
Rolling resistance f4.
int _sizeOfPatternFC
int _sizeOfPatternPollutants
std::vector< double > _speedCurveRotational
std::vector< double > _speedPatternRotational
std::string _vehicleFuelType
double _vehicleLoading
vehicle loading
Detailed Description
Data Handler for a single CEP emission data set.
Definition at line 59 of file PHEMCEP.h.
Constructor & Destructor Documentation
PHEMCEP::PHEMCEP (bool heavyVehicel, SUMOEmissionClass emissionClass, const std::string & emissionClassIdentifier, double vehicleMass, double vehicleLoading, double vehicleMassRot, double crossArea, double cdValue, double f0, double f1, double f2, double f3, double f4, double ratedPower, double pNormV0, double pNormP0, double pNormV1, double pNormP1, double axleRatio, double engineIdlingSpeed, double engineRatedSpeed, double effectiveWheelDiameter, double idlingFC, const std::string & vehicleFuelType, const std::vector< std::vector< double > > & matrixFC, const std::vector< std::string > & headerLinePollutants, const std::vector< std::vector< double > > & matrixPollutants, const std::vector< std::vector< double > > & matrixSpeedRotational, const std::vector< std::vector< double > > & normedDragTable, const std::vector< double > & idlingValuesPollutants)
Definition at line 49 of file PHEMCEP.cpp.
References _axleRatio, _cdValue, _cepCurveFC, _cepCurvePollutants, _crossSectionalArea, _dragNormTable, _drivingPower, _effictiveWheelDiameter, _emissionClass, _engineIdlingSpeed, _engineRatedSpeed, _gearTransmissionCurve, _heavyVehicle, _idlingFC, _idlingValuesPollutants, _massRot, _massVehicle, _nNormTable, _normailzedPowerPatternPollutants, _normalizedCepCurvePollutants, _normalizedPowerPatternFC, _normalizingPower, _normalizingType, _normedCepCurveFC, _pNormP0, _pNormP1, _pNormV0, _pNormV1, _powerPatternFC, _powerPatternPollutants, _ratedPower, _resistanceF0, _resistanceF1, _resistanceF2, _resistanceF3, _resistanceF4, _sizeOfPatternFC, _sizeOfPatternPollutants, _speedCurveRotational, _speedPatternRotational, _vehicleFuelType, _vehicleLoading, CalcPower(), DrivingPower, StringBijection< T >::insert(), NORMALIZING_ACCELARATION, NORMALIZING_SPEED, and RatedPower.
PHEMCEP::~PHEMCEP ()
Destructor.
Definition at line 197 of file PHEMCEP.cpp.
References _cepCurveFC, _powerPatternFC, _powerPatternPollutants, _speedCurveRotational, and _speedPatternRotational.
Member Function Documentation
double PHEMCEP::CalcPower (double v, double a, double slope, double vehicleLoading = 0) const
Returns the power of used for a vehicle at state v,a, slope and loading.
Parameters
[in] v The vehicle's average velocity
[in] a The vehicle's average acceleration
[in] slope The road's slope at vehicle's position [deg]
Definition at line 411 of file PHEMCEP.cpp.
References _cdValue, _crossSectionalArea, _massRot, _massVehicle, _resistanceF0, _resistanceF1, _resistanceF4, _vehicleLoading, AIR_DENSITY_CONST, GetRotationalCoeffecient(), and GRAVITY_CONST.
Referenced by HelpersPHEMlight::compute(), GetMaxAccel(), and PHEMCEP().
void PHEMCEP::FindLowerUpperInPattern (int & lowerIndex, int & upperIndex, const std::vector< double > & pattern, double value) const private
Finds bounding upper and lower index in pattern for value.
Parameters
[out] lowerIndex out variable for lower index
[out] upperIndex out variable for lower index
[in] pattern to search
[in] value to search
Definition at line 369 of file PHEMCEP.cpp.
Referenced by GetDecelCoast(), GetDragCoeffecient(), GetEmission(), GetGearCoeffecient(), GetRotationalCoeffecient(), and GetVehicleFuelType().
double PHEMCEP::GetCdValue () const inline
Getter function to recieve vehicle data from CEP.
Returns
Cw value
Todo:
: Why is it named "cdValue", here?
Definition at line 185 of file PHEMCEP.h.
References _cdValue.
double PHEMCEP::GetCrossSectionalArea () const inline
Getter function to recieve vehicle data from CEP.
Returns
crosssectional area of vehicle
Definition at line 192 of file PHEMCEP.h.
References _crossSectionalArea.
double PHEMCEP::GetDecelCoast (double speed, double acc, double gradient, double vehicleLoading) const
Definition at line 290 of file PHEMCEP.cpp.
References _axleRatio, _cdValue, _crossSectionalArea, _effictiveWheelDiameter, _engineIdlingSpeed, _engineRatedSpeed, _massVehicle, _nNormTable, _ratedPower, _resistanceF0, _resistanceF1, _resistanceF2, _resistanceF3, _resistanceF4, _vehicleLoading, FindLowerUpperInPattern(), GetDragCoeffecient(), GetGearCoeffecient(), GetRotationalCoeffecient(), GRAVITY_CONST, M_PI2, and SPEED_DCEL_MIN.
double PHEMCEP::GetDragCoeffecient (double nNorm) const private
Definition at line 356 of file PHEMCEP.cpp.
References _dragNormTable, _nNormTable, FindLowerUpperInPattern(), and Interpolate().
Referenced by GetDecelCoast(), and GetVehicleFuelType().
double PHEMCEP::GetEmission (const std::string & pollutantIdentifier, double power, double speed, bool normalized = false) const
Returns a emission measure for power[kW] level.
Parameters
[in] pollutantIdentifier Desired pollutant, e.g. NOx
[in] power in [kW]
Returns
emission in [g/h]
Definition at line 208 of file PHEMCEP.cpp.
References _cepCurveFC, _cepCurvePollutants, _idlingFC, _idlingValuesPollutants, _normailzedPowerPatternPollutants, _normalizedCepCurvePollutants, _normalizedPowerPatternFC, _normedCepCurveFC, _powerPatternFC, _powerPatternPollutants, FindLowerUpperInPattern(), StringBijection< T >::get(), StringBijection< T >::hasString(), Interpolate(), and ZERO_SPEED_ACCURACY.
Referenced by HelpersPHEMlight::getEmission().
SUMOEmissionClass PHEMCEP::GetEmissionClass () const inline
Getter function to recieve vehicle data from CEP.
Returns
PHEM emission class of vehicle
Definition at line 136 of file PHEMCEP.h.
References _emissionClass.
double PHEMCEP::GetGearCoeffecient (double speed) const private
Definition at line 343 of file PHEMCEP.cpp.
References _gearTransmissionCurve, _speedPatternRotational, FindLowerUpperInPattern(), and Interpolate().
Referenced by GetDecelCoast(), and GetVehicleFuelType().
double PHEMCEP::GetMassRot () const inline
Getter function to recieve vehicle data from CEP.
Returns
rotational mass of vehicle
Definition at line 215 of file PHEMCEP.h.
References _massRot.
double PHEMCEP::GetMassVehicle () const inline
Getter function to recieve vehicle data from CEP.
Returns
vehicle mass
Definition at line 200 of file PHEMCEP.h.
References _massVehicle.
double PHEMCEP::GetMaxAccel (double v, double a, double gradient, double vehicleLoading = 0) const
Returns the maximum accelaration for a vehicle at state v,a, slope and loading.
Parameters
[in] v The vehicle's average velocity
[in] a The vehicle's average acceleration
[in] slope The road's slope at vehicle's position [deg]
Definition at line 422 of file PHEMCEP.cpp.
References _massRot, _massVehicle, _ratedPower, _vehicleLoading, CalcPower(), GetPMaxNorm(), GetRotationalCoeffecient(), and UNUSED_PARAMETER.
double PHEMCEP::GetPMaxNorm (double speed) const private
Calculates maximum available rated power for speed.
Parameters
[in] speed desired speed
Definition at line 431 of file PHEMCEP.cpp.
References _pNormP0, _pNormP1, _pNormV0, _pNormV1, and Interpolate().
Referenced by GetMaxAccel(), and GetVehicleFuelType().
double PHEMCEP::GetRatedPower () const inline
Getter function to recieve vehicle data from CEP.
Returns
rated power of vehicle
Definition at line 223 of file PHEMCEP.h.
References _ratedPower.
double PHEMCEP::GetResistanceF0 () const inline
Getter function to recieve vehicle data from CEP.
Returns
Rolling resistance f0
Definition at line 144 of file PHEMCEP.h.
References _resistanceF0.
double PHEMCEP::GetResistanceF1 () const inline
Getter function to recieve vehicle data from CEP.
Returns
Rolling resistance f1
Definition at line 152 of file PHEMCEP.h.
References _resistanceF1.
double PHEMCEP::GetResistanceF2 () const inline
Getter function to recieve vehicle data from CEP.
Returns
Rolling resistance f2
Definition at line 160 of file PHEMCEP.h.
References _resistanceF2.
double PHEMCEP::GetResistanceF3 () const inline
Getter function to recieve vehicle data from CEP.
Returns
Rolling resistance f3
Definition at line 168 of file PHEMCEP.h.
References _resistanceF3.
double PHEMCEP::GetResistanceF4 () const inline
Getter function to recieve vehicle data from CEP.
Returns
Rolling resistance f4
Definition at line 176 of file PHEMCEP.h.
References _resistanceF4.
double PHEMCEP::GetRotationalCoeffecient (double speed) const private
Calculates rotational index for speed.
Parameters
[in] speed desired speed
Definition at line 330 of file PHEMCEP.cpp.
References _speedCurveRotational, _speedPatternRotational, FindLowerUpperInPattern(), and Interpolate().
Referenced by CalcPower(), GetDecelCoast(), GetMaxAccel(), and GetVehicleFuelType().
const std::string& PHEMCEP::GetVehicleFuelType () const inline
Getter function to recieve vehicle data from CEP.
Returns
fuel type of vehicle
Definition at line 230 of file PHEMCEP.h.
References _vehicleFuelType, FindLowerUpperInPattern(), GetDragCoeffecient(), GetGearCoeffecient(), GetPMaxNorm(), GetRotationalCoeffecient(), and Interpolate().
Referenced by HelpersPHEMlight::compute().
double PHEMCEP::GetVehicleLoading () const inline
Getter function to recieve vehicle data from CEP.
Returns
vehicle loading
Definition at line 207 of file PHEMCEP.h.
References _vehicleLoading.
double PHEMCEP::Interpolate (double px, double p1, double p2, double e1, double e2) const private
Interpolates emission linearly between two known power-emission pairs.
Parameters
[in] px power-value to interpolate
[in] p1 first known power value
[in] p2 second known power value
[in] e1 emission value for p1
[in] e2 emission value for p2
Returns
emission value for px
Definition at line 282 of file PHEMCEP.cpp.
Referenced by GetDragCoeffecient(), GetEmission(), GetGearCoeffecient(), GetPMaxNorm(), GetRotationalCoeffecient(), and GetVehicleFuelType().
Field Documentation
double PHEMCEP::_axleRatio private
Definition at line 299 of file PHEMCEP.h.
Referenced by GetDecelCoast(), and PHEMCEP().
double PHEMCEP::_cdValue private
Cw value.
Definition at line 280 of file PHEMCEP.h.
Referenced by CalcPower(), GetCdValue(), GetDecelCoast(), and PHEMCEP().
std::vector<double> PHEMCEP::_cepCurveFC private
Todo:
describe
Definition at line 319 of file PHEMCEP.h.
Referenced by GetEmission(), PHEMCEP(), and ~PHEMCEP().
StringBijection< std::vector<double> > PHEMCEP::_cepCurvePollutants private
Definition at line 326 of file PHEMCEP.h.
Referenced by GetEmission(), and PHEMCEP().
double PHEMCEP::_crossSectionalArea private
crosssectional area of vehicle
Definition at line 282 of file PHEMCEP.h.
Referenced by CalcPower(), GetCrossSectionalArea(), GetDecelCoast(), and PHEMCEP().
std::vector<double> PHEMCEP::_dragNormTable private
Definition at line 325 of file PHEMCEP.h.
Referenced by GetDragCoeffecient(), and PHEMCEP().
double PHEMCEP::_drivingPower private
Definition at line 309 of file PHEMCEP.h.
Referenced by PHEMCEP().
double PHEMCEP::_effictiveWheelDiameter private
Definition at line 302 of file PHEMCEP.h.
Referenced by GetDecelCoast(), and PHEMCEP().
SUMOEmissionClass PHEMCEP::_emissionClass private
PHEM emission class of vehicle.
Definition at line 267 of file PHEMCEP.h.
Referenced by GetEmissionClass(), and PHEMCEP().
double PHEMCEP::_engineIdlingSpeed private
Definition at line 300 of file PHEMCEP.h.
Referenced by GetDecelCoast(), and PHEMCEP().
double PHEMCEP::_engineRatedSpeed private
Definition at line 301 of file PHEMCEP.h.
Referenced by GetDecelCoast(), and PHEMCEP().
std::vector<double> PHEMCEP::_gearTransmissionCurve private
Definition at line 323 of file PHEMCEP.h.
Referenced by GetGearCoeffecient(), and PHEMCEP().
bool PHEMCEP::_heavyVehicle private
Definition at line 310 of file PHEMCEP.h.
Referenced by PHEMCEP().
double PHEMCEP::_idlingFC private
Definition at line 303 of file PHEMCEP.h.
Referenced by GetEmission(), and PHEMCEP().
StringBijection<double> PHEMCEP::_idlingValuesPollutants private
Definition at line 328 of file PHEMCEP.h.
Referenced by GetEmission(), and PHEMCEP().
double PHEMCEP::_massRot private
rotational mass of vehicle
Definition at line 288 of file PHEMCEP.h.
Referenced by CalcPower(), GetMassRot(), GetMaxAccel(), and PHEMCEP().
double PHEMCEP::_massVehicle private
vehicle mass
Definition at line 284 of file PHEMCEP.h.
Referenced by CalcPower(), GetDecelCoast(), GetMassVehicle(), GetMaxAccel(), and PHEMCEP().
std::vector<double> PHEMCEP::_nNormTable private
Definition at line 324 of file PHEMCEP.h.
Referenced by GetDecelCoast(), GetDragCoeffecient(), and PHEMCEP().
std::vector<double> PHEMCEP::_normailzedPowerPatternPollutants private
Definition at line 317 of file PHEMCEP.h.
Referenced by GetEmission(), and PHEMCEP().
StringBijection<std::vector<double> > PHEMCEP::_normalizedCepCurvePollutants private
Definition at line 327 of file PHEMCEP.h.
Referenced by GetEmission(), and PHEMCEP().
std::vector<double> PHEMCEP::_normalizedPowerPatternFC private
Definition at line 316 of file PHEMCEP.h.
Referenced by GetEmission(), and PHEMCEP().
double PHEMCEP::_normalizingPower private
Definition at line 308 of file PHEMCEP.h.
Referenced by PHEMCEP().
NormalizingType PHEMCEP::_normalizingType private
Definition at line 268 of file PHEMCEP.h.
Referenced by PHEMCEP().
std::vector<double> PHEMCEP::_normedCepCurveFC private
Todo:
describe
Definition at line 321 of file PHEMCEP.h.
Referenced by GetEmission(), and PHEMCEP().
double PHEMCEP::_pNormP0 private
Step functions parameter for maximum rated power.
Definition at line 294 of file PHEMCEP.h.
Referenced by GetPMaxNorm(), and PHEMCEP().
double PHEMCEP::_pNormP1 private
Step functions parameter for maximum rated power.
Definition at line 298 of file PHEMCEP.h.
Referenced by GetPMaxNorm(), and PHEMCEP().
double PHEMCEP::_pNormV0 private
Step functions parameter for maximum rated power.
Definition at line 292 of file PHEMCEP.h.
Referenced by GetPMaxNorm(), and PHEMCEP().
double PHEMCEP::_pNormV1 private
Step functions parameter for maximum rated power.
Definition at line 296 of file PHEMCEP.h.
Referenced by GetPMaxNorm(), and PHEMCEP().
std::vector<double> PHEMCEP::_powerPatternFC private
Todo:
describe
Definition at line 313 of file PHEMCEP.h.
Referenced by GetEmission(), PHEMCEP(), and ~PHEMCEP().
std::vector<double> PHEMCEP::_powerPatternPollutants private
Todo:
describe
Definition at line 315 of file PHEMCEP.h.
Referenced by GetEmission(), PHEMCEP(), and ~PHEMCEP().
double PHEMCEP::_ratedPower private
rated power of vehicle
Definition at line 290 of file PHEMCEP.h.
Referenced by GetDecelCoast(), GetMaxAccel(), GetRatedPower(), and PHEMCEP().
double PHEMCEP::_resistanceF0 private
Rolling resistance f0.
Definition at line 270 of file PHEMCEP.h.
Referenced by CalcPower(), GetDecelCoast(), GetResistanceF0(), and PHEMCEP().
double PHEMCEP::_resistanceF1 private
Rolling resistance f1.
Definition at line 272 of file PHEMCEP.h.
Referenced by CalcPower(), GetDecelCoast(), GetResistanceF1(), and PHEMCEP().
double PHEMCEP::_resistanceF2 private
Rolling resistance f2.
Definition at line 274 of file PHEMCEP.h.
Referenced by GetDecelCoast(), GetResistanceF2(), and PHEMCEP().
double PHEMCEP::_resistanceF3 private
Rolling resistance f3.
Definition at line 276 of file PHEMCEP.h.
Referenced by GetDecelCoast(), GetResistanceF3(), and PHEMCEP().
double PHEMCEP::_resistanceF4 private
Rolling resistance f4.
Definition at line 278 of file PHEMCEP.h.
Referenced by CalcPower(), GetDecelCoast(), GetResistanceF4(), and PHEMCEP().
int PHEMCEP::_sizeOfPatternFC private
Definition at line 305 of file PHEMCEP.h.
Referenced by PHEMCEP().
int PHEMCEP::_sizeOfPatternPollutants private
Todo:
describe
Definition at line 307 of file PHEMCEP.h.
Referenced by PHEMCEP().
std::vector<double> PHEMCEP::_speedCurveRotational private
Definition at line 322 of file PHEMCEP.h.
Referenced by GetRotationalCoeffecient(), PHEMCEP(), and ~PHEMCEP().
std::vector<double> PHEMCEP::_speedPatternRotational private
Definition at line 311 of file PHEMCEP.h.
Referenced by GetGearCoeffecient(), GetRotationalCoeffecient(), PHEMCEP(), and ~PHEMCEP().
std::string PHEMCEP::_vehicleFuelType private
Definition at line 304 of file PHEMCEP.h.
Referenced by GetVehicleFuelType(), and PHEMCEP().
double PHEMCEP::_vehicleLoading private
vehicle loading
Definition at line 286 of file PHEMCEP.h.
Referenced by CalcPower(), GetDecelCoast(), GetMaxAccel(), GetVehicleLoading(), and PHEMCEP().
The documentation for this class was generated from the following files:
PHEMCEP.h
PHEMCEP.cpp