SUMO - Simulation of Urban MObility: MSVehicle::DriveProcessItem Struct Reference
MSVehicle::DriveProcessItem Struct Reference
#include <MSVehicle.h>
Public Member Functions
void adaptLeaveSpeed (const SUMOReal v)
DriveProcessItem (MSLink *link, SUMOReal vPass, SUMOReal vWait, bool setRequest, SUMOTime arrivalTime, SUMOReal arrivalSpeed, SUMOTime arrivalTimeBraking, SUMOReal arrivalSpeedBraking, SUMOReal distance, SUMOReal leaveSpeed=-1.)
DriveProcessItem (SUMOReal vWait, SUMOReal distance)
constructor if the link shall not be passed
SUMOReal getLeaveSpeed () const
Data Fields
SUMOReal accelV
SUMOReal availableSpace
bool hadVehicle
SUMOReal myArrivalSpeed
SUMOReal myArrivalSpeedBraking
SUMOTime myArrivalTime
SUMOTime myArrivalTimeBraking
SUMOReal myDistance
MSLink * myLink
bool mySetRequest
SUMOReal myVLinkPass
SUMOReal myVLinkWait
Detailed Description
Definition at line 1433 of file MSVehicle.h.
Constructor & Destructor Documentation
MSVehicle::DriveProcessItem::DriveProcessItem (MSLink * link, SUMOReal vPass, SUMOReal vWait, bool setRequest, SUMOTime arrivalTime, SUMOReal arrivalSpeed, SUMOTime arrivalTimeBraking, SUMOReal arrivalSpeedBraking, SUMOReal distance, SUMOReal leaveSpeed = -1.) inline
Definition at line 1447 of file MSVehicle.h.
MSVehicle::DriveProcessItem::DriveProcessItem (SUMOReal vWait, SUMOReal distance) inline
constructor if the link shall not be passed
Definition at line 1463 of file MSVehicle.h.
Member Function Documentation
void MSVehicle::DriveProcessItem::adaptLeaveSpeed (const SUMOReal v) inline
Definition at line 1473 of file MSVehicle.h.
References MIN2().
Referenced by MSVehicle::adaptToLeader(), and MSVehicle::planMoveInternal().
SUMOReal MSVehicle::DriveProcessItem::getLeaveSpeed () const inline
Definition at line 1480 of file MSVehicle.h.
Referenced by MSVehicle::checkRewindLinkLanes(), and GUIVehicle::selectBlockingFoes().
Field Documentation
SUMOReal MSVehicle::DriveProcessItem::accelV
Definition at line 1443 of file MSVehicle.h.
SUMOReal MSVehicle::DriveProcessItem::availableSpace
Definition at line 1445 of file MSVehicle.h.
Referenced by MSVehicle::checkRewindLinkLanes().
bool MSVehicle::DriveProcessItem::hadVehicle
Definition at line 1444 of file MSVehicle.h.
Referenced by MSVehicle::checkRewindLinkLanes().
SUMOReal MSVehicle::DriveProcessItem::myArrivalSpeed
Definition at line 1439 of file MSVehicle.h.
Referenced by MSVehicle::checkRewindLinkLanes(), and GUIVehicle::selectBlockingFoes().
SUMOReal MSVehicle::DriveProcessItem::myArrivalSpeedBraking
Definition at line 1441 of file MSVehicle.h.
SUMOTime MSVehicle::DriveProcessItem::myArrivalTime
Definition at line 1438 of file MSVehicle.h.
Referenced by MSVehicle::checkRewindLinkLanes(), and GUIVehicle::selectBlockingFoes().
SUMOTime MSVehicle::DriveProcessItem::myArrivalTimeBraking
Definition at line 1440 of file MSVehicle.h.
SUMOReal MSVehicle::DriveProcessItem::myDistance
Definition at line 1442 of file MSVehicle.h.
MSLink* MSVehicle::DriveProcessItem::myLink
Definition at line 1434 of file MSVehicle.h.
Referenced by MSVehicle::checkRewindLinkLanes(), and GUIVehicle::selectBlockingFoes().
bool MSVehicle::DriveProcessItem::mySetRequest
Definition at line 1437 of file MSVehicle.h.
SUMOReal MSVehicle::DriveProcessItem::myVLinkPass
Definition at line 1435 of file MSVehicle.h.
SUMOReal MSVehicle::DriveProcessItem::myVLinkWait
Definition at line 1436 of file MSVehicle.h.
Referenced by MSVehicle::planMoveInternal().
The documentation for this struct was generated from the following file:
MSVehicle.h