SUMO - Simulation of Urban MObility: RORoutable Class Reference
RORoutable Class Reference abstract
A routable thing such as a vehicle or person.
#include <RORoutable.h>
Public Member Functions
virtual void computeRoute (const RORouterProvider &provider, const bool removeLoops, MsgHandler *errorHandler)=0
SUMOTime getDepart () const
Returns the time the vehicle starts at, -1 for triggered vehicles.
virtual const ROEdge * getDepartEdge () const =0
const std::string & getID () const
Returns the id of the vehicle.
SUMOReal getMaxSpeed () const
Returns the vehicle's maximum speed.
bool getRoutingSuccess () const
const SUMOVTypeParameter * getType () const
Returns the type of the vehicle.
SUMOVehicleClass getVClass () const
RORoutable (const SUMOVehicleParameter &pars, const SUMOVTypeParameter *type)
Constructor.
void write (OutputDevice &os, OutputDevice *const altos, OutputDevice *const typeos, OptionsCont &options) const
Saves the routable including the vehicle type (if it was not saved before).
virtual ~RORoutable ()
Destructor.
Protected Member Functions
virtual void saveAsXML (OutputDevice &os, OutputDevice *const typeos, bool asAlternatives, OptionsCont &options) const =0
Saves the complete routable description.
Protected Attributes
SUMOVehicleParameter myParameter
The vehicle's parameter.
bool myRoutingSuccess
Whether the last routing was successful.
const SUMOVTypeParameter *const myType
The type of the vehicle.
Private Member Functions
RORoutable & operator= (const RORoutable &src)
Invalidated assignment operator.
RORoutable (const RORoutable &src)
Invalidated copy constructor.
Detailed Description
A routable thing such as a vehicle or person.
Definition at line 62 of file RORoutable.h.
Constructor & Destructor Documentation
RORoutable::RORoutable (const SUMOVehicleParameter & pars, const SUMOVTypeParameter * type) inline
Constructor.
Parameters
[in] pars Parameter of this routable
[in] type The type of the routable
Definition at line 69 of file RORoutable.h.
virtual RORoutable::~RORoutable () inline virtual
Destructor.
Definition at line 74 of file RORoutable.h.
RORoutable::RORoutable (const RORoutable & src) private
Invalidated copy constructor.
Member Function Documentation
virtual void RORoutable::computeRoute (const RORouterProvider & provider, const bool removeLoops, MsgHandler * errorHandler) pure virtual
Implemented in ROPerson, and ROVehicle.
Referenced by RONet::createBulkRouteRequests(), getMaxSpeed(), and RONet::saveAndRemoveRoutesUntil().
SUMOTime RORoutable::getDepart () const inline
Returns the time the vehicle starts at, -1 for triggered vehicles.
Returns
The vehicle's depart time
Definition at line 101 of file RORoutable.h.
References SUMOVehicleParameter::depart, and myParameter.
Referenced by RONet::addPerson(), RONet::addVehicle(), and ROVehicleByDepartureComperator::operator()().
virtual const ROEdge* RORoutable::getDepartEdge () const pure virtual
Implemented in ROPerson, and ROVehicle.
Referenced by RONet::createBulkRouteRequests(), and getMaxSpeed().
const std::string& RORoutable::getID () const inline
Returns the id of the vehicle.
Returns
The id of the vehicle
Definition at line 92 of file RORoutable.h.
References SUMOVehicleParameter::id, and myParameter.
Referenced by RORouteDef::addAlternative(), RONet::addPerson(), ROVehicle::addStop(), ROPerson::addTrip(), ROPerson::computeIntermodal(), ROVehicle::computeRoute(), RONet::createBulkRouteRequests(), ROVehicleByDepartureComperator::operator()(), RORouteDef::preComputeCurrentRoute(), and RORouteDef::repairCurrentRoute().
SUMOReal RORoutable::getMaxSpeed () const inline
Returns the vehicle's maximum speed.
Definition at line 112 of file RORoutable.h.
References computeRoute(), getDepartEdge(), SUMOVTypeParameter::maxSpeed, and myType.
Referenced by RONet::createBulkRouteRequests().
bool RORoutable::getRoutingSuccess () const inline
Definition at line 144 of file RORoutable.h.
References myRoutingSuccess, and saveAsXML().
Referenced by RONet::saveAndRemoveRoutesUntil().
const SUMOVTypeParameter* RORoutable::getType () const inline
Returns the type of the vehicle.
Returns
The vehicle's type
Todo:
Why not return a reference?
Definition at line 83 of file RORoutable.h.
References myType.
Referenced by ROVehicle::getChosenSpeedFactor(), ROEdge::getEffort(), ROEdge::getEmissionEffort(), ROEdge::getMinimumTravelTime(), ROEdge::getNoiseEffort(), ROEdge::getTravelTime(), and getVClass().
SUMOVehicleClass RORoutable::getVClass () const inline
Definition at line 106 of file RORoutable.h.
References getType(), SVC_IGNORING, and SUMOVTypeParameter::vehicleClass.
Referenced by RONet::createBulkRouteRequests(), ROEdge::isConnectedTo(), and ROEdge::prohibits().
RORoutable& RORoutable::operator= (const RORoutable & src) private
Invalidated assignment operator.
virtual void RORoutable::saveAsXML (OutputDevice & os, OutputDevice *const typeos, bool asAlternatives, OptionsCont & options) const protected pure virtual
Saves the complete routable description.
Saves the routable itself including the route and stops.
Parameters
[in] os The routes or alternatives output device to store the routable's description into
[in] typeos The types - output device to store additional types into
[in] asAlternatives Whether the route shall be saved as route alternatives
[in] options to find out about defaults and whether exit times for the edges shall be written
Exceptions
IOError If something fails (not yet implemented)
Implemented in ROPerson, and ROVehicle.
Referenced by getRoutingSuccess(), and write().
void RORoutable::write (OutputDevice & os, OutputDevice *const altos, OutputDevice *const typeos, OptionsCont & options) const inline
Saves the routable including the vehicle type (if it was not saved before).
Parameters
[in] os The routes - output device to store the vehicle's description into
[in] altos The route alternatives - output device to store the vehicle's description into
[in] typeos The types - output device to store the vehicle types into
Exceptions
IOError If something fails (not yet implemented)
Definition at line 131 of file RORoutable.h.
References saveAsXML().
Referenced by RONet::saveAndRemoveRoutesUntil().
Field Documentation
SUMOVehicleParameter RORoutable::myParameter protected
The vehicle's parameter.
Definition at line 165 of file RORoutable.h.
Referenced by ROVehicle::addStop(), getDepart(), ROVehicle::getDepartureTime(), getID(), ROVehicle::getParameter(), ROVehicle::ROVehicle(), ROVehicle::saveAsXML(), and ROPerson::saveAsXML().
bool RORoutable::myRoutingSuccess protected
Whether the last routing was successful.
Definition at line 171 of file RORoutable.h.
Referenced by ROPerson::computeIntermodal(), ROVehicle::computeRoute(), ROPerson::computeRoute(), and getRoutingSuccess().
const SUMOVTypeParameter* const RORoutable::myType protected
The type of the vehicle.
Definition at line 168 of file RORoutable.h.
Referenced by ROPerson::computeIntermodal(), getMaxSpeed(), getType(), ROVehicle::saveAsXML(), and ROPerson::saveAsXML().
The documentation for this class was generated from the following file:
RORoutable.h