SUMO - Simulation of Urban MObility: ROLoader::EdgeFloatTimeLineRetriever_EdgeWeight Class Reference
ROLoader::EdgeFloatTimeLineRetriever_EdgeWeight Class Reference
Obtains edge weights from a weights handler and stores them within the edges.
#include <ROLoader.h>
Public Member Functions
void addEdgeWeight (const std::string &id, SUMOReal val, SUMOReal beg, SUMOReal end) const
Adds an effort for a given edge and time period.
EdgeFloatTimeLineRetriever_EdgeWeight (RONet &net)
Constructor.
~EdgeFloatTimeLineRetriever_EdgeWeight ()
Destructor.
Private Attributes
RONet & myNet
The network edges shall be obtained from.
Detailed Description
Obtains edge weights from a weights handler and stores them within the edges.
See also
SAXWeightsHandler::EdgeFloatTimeLineRetriever
Definition at line 121 of file ROLoader.h.
Constructor & Destructor Documentation
ROLoader::EdgeFloatTimeLineRetriever_EdgeWeight::EdgeFloatTimeLineRetriever_EdgeWeight (RONet & net) inline
Constructor.
Definition at line 124 of file ROLoader.h.
ROLoader::EdgeFloatTimeLineRetriever_EdgeWeight::~EdgeFloatTimeLineRetriever_EdgeWeight () inline
Destructor.
Definition at line 127 of file ROLoader.h.
References addEdgeWeight(), and SUMOReal.
Member Function Documentation
void ROLoader::EdgeFloatTimeLineRetriever_EdgeWeight::addEdgeWeight (const std::string & id, SUMOReal val, SUMOReal beg, SUMOReal end) const virtual
Adds an effort for a given edge and time period.
Parameters
[in] id The id of the object to add a weight for
[in] val The weight
[in] beg The begin of the interval the weight is valid for
[in] end The end of the interval the weight is valid for
See also
SAXWeightsHandler::EdgeFloatTimeLineRetriever::addEdgeWeight
Implements SAXWeightsHandler::EdgeFloatTimeLineRetriever.
Definition at line 91 of file ROLoader.cpp.
References ROEdge::addEffort(), RONet::getEdge(), OptionsCont::getOptions(), ROLoader::EdgeFloatTimeLineRetriever_EdgeTravelTime::myNet, WRITE_ERROR, and WRITE_WARNING.
Referenced by ROLoader::EdgeFloatTimeLineRetriever_EdgeTravelTime::~EdgeFloatTimeLineRetriever_EdgeTravelTime(), and ~EdgeFloatTimeLineRetriever_EdgeWeight().
Field Documentation
RONet& ROLoader::EdgeFloatTimeLineRetriever_EdgeWeight::myNet private
The network edges shall be obtained from.
Definition at line 142 of file ROLoader.h.
The documentation for this class was generated from the following files:
ROLoader.h
ROLoader.cpp