SUMO - Simulation of Urban MObility: PointOfInterest Class Reference
PointOfInterest Class Reference
A point-of-interest.
#include <PointOfInterest.h>
Public Member Functions
void add (const Position &pos)
Adds the given position to this one.
void add (SUMOReal dx, SUMOReal dy)
Adds the given position to this one.
void add (SUMOReal dx, SUMOReal dy, SUMOReal dz)
Adds the given position to this one.
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
bool almostSame (const Position &p2, SUMOReal maxDiv=POSITION_EPS) const
SUMOReal angleTo2D (const Position &other) const
returns the angle in the plane of the vector pointing from here to the other position
void clearParameter ()
Clears the parameter map.
Position crossProduct (const Position &pos)
returns the cross product between this point and the second one
SUMOReal distanceSquaredTo (const Position &p2) const
SUMOReal distanceSquaredTo2D (const Position &p2) const
SUMOReal distanceTo (const Position &p2) const
returns the euclidean distance in 3 dimension
SUMOReal distanceTo2D (const Position &p2) const
returns the euclidean distance in the x-y-plane
SUMOReal dotProduct (const Position &pos)
returns the dot product (scalar product) between this point and the second one
const std::string & getID () const
Returns the id.
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
void mul (SUMOReal val)
Multiplies both positions with the given value.
void mul (SUMOReal mx, SUMOReal my)
Multiplies position with the given values.
void mul (SUMOReal mx, SUMOReal my, SUMOReal mz)
Multiplies position with the given values.
void norm2d ()
bool operator!= (const Position &p2) const
Position operator* (SUMOReal scalar) const
keep the direction but modify the length of the (location) vector to length * scalar
Position operator+ (const Position &p2) const
Position operator+ (SUMOReal offset) const
keep the direction but modify the length of the (location) vector to length + scalar
Position operator- (const Position &p2) const
bool operator< (const Position &p2) const
lexicographical sorting for use in maps and sets
bool operator== (const Position &p2) const
PointOfInterest (const std::string &id, const std::string &type, const RGBColor &color, const Position &pos, SUMOReal layer=DEFAULT_LAYER, SUMOReal angle=DEFAULT_ANGLE, const std::string &imgFile=DEFAULT_IMG_FILE, SUMOReal width=DEFAULT_IMG_WIDTH, SUMOReal height=DEFAULT_IMG_HEIGHT)
Constructor.
void set (SUMOReal x, SUMOReal y)
void set (SUMOReal x, SUMOReal y, SUMOReal z)
void set (const Position &pos)
void setID (const std::string &newID)
resets the id
void sub (SUMOReal dx, SUMOReal dy)
Substracts the given position from this one.
void sub (SUMOReal dx, SUMOReal dy, SUMOReal dz)
Substracts the given position from this one.
void sub (const Position &pos)
Substracts the given position from this one.
void writeXML (OutputDevice &out, const bool geo=false, const SUMOReal zOffset=0., const std::string laneID="", const SUMOReal pos=0.)
SUMOReal x () const
Returns the x-position.
SUMOReal y () const
Returns the y-position.
SUMOReal z () const
Returns the z-position.
virtual ~PointOfInterest ()
Destructor.
Getter
SUMOReal getWidth () const
Returns the image width of the POI.
SUMOReal getHeight () const
Returns the image height of the POI.
Setter
void setWidth (SUMOReal width)
set the image width of the POI
void setHeight (SUMOReal height)
set the image height of the POI
Getter
const std::string & getType () const
Returns the (abstract) type of the Shape.
const RGBColor & getColor () const
Returns the color of the Shape.
SUMOReal getLayer () const
Returns the layer of the Shape.
SUMOReal getNaviDegree () const
Returns the angle of the Shape in navigational degrees.
const std::string & getImgFile () const
Returns the imgFile of the Shape.
Setter
void setType (const std::string &type)
Sets a new type.
void setColor (const RGBColor &col)
Sets a new color.
void setLayer (const SUMOReal layer)
Sets a new layer.
void setNaviDegree (const SUMOReal angle)
Sets a new angle in navigational degrees.
void setImgFile (const std::string &imgFile)
Sets a new imgFile.
Static Public Member Functions
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
Static Public Attributes
static const SUMOReal DEFAULT_ANGLE = 0
static const std::string DEFAULT_IMG_FILE = ""
static const SUMOReal DEFAULT_IMG_HEIGHT = 1
static const SUMOReal DEFAULT_IMG_WIDTH = 1
static const SUMOReal DEFAULT_LAYER = 128
static const std::string DEFAULT_TYPE = ""
static const Position INVALID
Protected Attributes
RGBColor myColor
The color of the Shape.
SUMOReal myHalfImgHeight
The half height of the image when rendering this POI.
SUMOReal myHalfImgWidth
The half width of the image when rendering this POI.
std::string myID
The name of the object.
std::string myImgFile
The angle of the Shape.
SUMOReal myLayer
The layer of the Shape.
SUMOReal myNaviDegreeAngle
The angle of the Shape.
std::string myType
The type of the Shape.
Detailed Description
A point-of-interest.
Definition at line 51 of file PointOfInterest.h.
Constructor & Destructor Documentation
PointOfInterest::PointOfInterest (const std::string & id, const std::string & type, const RGBColor & color, const Position & pos, SUMOReal layer = DEFAULT_LAYER, SUMOReal angle = DEFAULT_ANGLE, const std::string & imgFile = DEFAULT_IMG_FILE, SUMOReal width = DEFAULT_IMG_WIDTH, SUMOReal height = DEFAULT_IMG_HEIGHT) inline
Constructor.
Parameters
[in] id The name of the POI
[in] type The (abstract) type of the POI
[in] color The color of the POI
[in] layer The layer of the POI
[in] angle The rotation of the POI
[in] imgFile The raster image of the shape
[in] pos The position of the POI
[in] width The width of the POI image
[in] height The height of the POI image
Definition at line 64 of file PointOfInterest.h.
virtual PointOfInterest::~PointOfInterest () inline virtual
Destructor.
Definition at line 79 of file PointOfInterest.h.
Member Function Documentation
void Position::add (const Position & pos) inline inherited
Adds the given position to this one.
Definition at line 119 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
Referenced by NBNodeCont::analyzeCluster(), AGPosition::compute2dPosition(), NBNodeShapeComputer::computeNodeShapeDefault(), NIVissimDistrictConnection::dict_BuildDistrictNodes(), GNEEdge::drawGL(), GUIEdge::drawGL(), GLHelper::drawTextBox(), PositionVector::extrapolate(), PositionVector::extrapolate2D(), NBNode::getEmptyDir(), GeoConvHelper::moveConvertedBy(), NBDistrict::reshiftPosition(), NBNode::reshiftPosition(), GUISUMOAbstractView::showToolTipFor(), and GeoConvHelper::x2cartesian_const().
void Position::add (SUMOReal dx, SUMOReal dy) inline inherited
Adds the given position to this one.
Definition at line 126 of file Position.h.
References Position::myX, and Position::myY.
void Position::add (SUMOReal dx, SUMOReal dy, SUMOReal dz) inline inherited
Adds the given position to this one.
Definition at line 132 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 53 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NBTrafficLightDefinition::compute(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::EdgesHandler::myStartElement(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_TLS::processSet(), TraCIServerAPI_Polygon::processSet(), and TraCIServerAPI_Lane::processSet().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 59 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 67 of file Parameterised.cpp.
References Parameterised::myMap.
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
bool Position::almostSame (const Position & p2, SUMOReal maxDiv = POSITION_EPS) const inline inherited
Definition at line 215 of file Position.h.
References Position::distanceTo().
Referenced by AGPosition::operator==(), PositionVector::push_back_noDoublePos(), and PositionVector::push_front_noDoublePos().
SUMOReal Position::angleTo2D (const Position & other) const inline inherited
returns the angle in the plane of the vector pointing from here to the other position
Definition at line 243 of file Position.h.
References Position::myX, and Position::myY.
Referenced by NBNode::bezierControlPoints(), MSVehicle::computeAngle(), NBEdge::computeAngle(), GUIBusStop::drawGL(), GLHelper::drawTriangleAtEnd(), NBContHelper::relative_outgoing_edge_sorter::operator()(), NBContHelper::relative_incoming_edge_sorter::operator()(), PositionVector::rotationAtOffset(), GNEAdditionalSet::updateConnections(), and NWWriter_OpenDrive::writeGeomSmooth().
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 91 of file Parameterised.cpp.
References Parameterised::myMap.
Position Position::crossProduct (const Position & pos) inline inherited
returns the cross product between this point and the second one
Definition at line 249 of file Position.h.
References Position::myX, Position::myY, Position::myZ, and Position::Position().
Referenced by NBHeightMapper::Triangle::normalVector().
SUMOReal Position::distanceSquaredTo (const Position & p2) const inline inherited
Definition at line 226 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
Referenced by Position::distanceTo().
SUMOReal Position::distanceSquaredTo2D (const Position & p2) const inline inherited
Definition at line 237 of file Position.h.
References Position::myX, and Position::myY.
Referenced by Position::distanceTo2D().
SUMOReal Position::distanceTo (const Position & p2) const inline inherited
returns the euclidean distance in 3 dimension
Definition at line 221 of file Position.h.
References Position::distanceSquaredTo().
Referenced by Position::almostSame(), TraCIServerAPI_Vehicle::commandDistanceRequest(), TraCIServerAPI_Simulation::commandDistanceRequest(), NBHelpers::distance(), AGPosition::distanceTo(), GLHelper::drawBoxLines(), GLHelper::drawTriangleAtEnd(), PositionVector::extrapolate(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), PositionVector::indexOfClosest(), NBEdge::init(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), GUIViewTraffic::onGamingClick(), Position::operator+(), PositionVector::positionAtOffset(), NIVissimEdge::remapOneOfNodes(), PositionVector::rotationAtOffset(), GUIBaseVehicle::setFunctionalColor(), PositionVector::slopeDegreeAtOffset(), GUILane::splitAtSegments(), GNEChargingStation::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEContainerStop::updateGeometry(), GNEBusStop::updateGeometry(), and MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility().
SUMOReal Position::distanceTo2D (const Position & p2) const inline inherited
returns the euclidean distance in the x-y-plane
Definition at line 232 of file Position.h.
References Position::distanceSquaredTo2D().
Referenced by NBNode::bezierControlPoints(), NBNode::buildWalkingAreas(), NGRandomNetBuilder::canConnect(), NBNode::checkCrossing(), GUIVehicle::computeSeats(), PositionVector::distance2D(), GUIVehicle::drawAction_drawRailCarriages(), GUIBusStop::drawGL(), PositionVector::extrapolate2D(), ROEdge::getDistanceTo(), MSEdge::getDistanceTo(), GNEInternalLane::GNEInternalLane(), GUILane::GUILane(), MSVehicle::Influencer::implicitDeltaPosVTD(), MSVehicle::Influencer::implicitSpeedVTD(), MSPModel_Striping::initWalkingAreaPaths(), PositionVector::insertAtClosest(), PositionVector::intersects(), PositionVector::intersectsAtLengths2D(), PositionVector::move2side(), GeomHelper::nearest_offset_on_line_to_point2D(), PositionVector::nearest_offset_to_point2D(), PositionVector::positionAtOffset2D(), PositionVector::removeClosest(), GNEEdge::resetEndpoint(), GNEEdge::setEndpoint(), PositionVector::sideOffset(), PositionVector::slopeDegreeAtOffset(), PositionVector::transformToVectorCoordinates(), GNEAdditionalSet::updateConnections(), GNEConnection::updateGeometry(), GNECrossing::updateGeometry(), GNELane::updateGeometry(), TraCIServerAPI_Vehicle::vtdMap(), NWWriter_OpenDrive::writeGeomLines(), and NWWriter_OpenDrive::writeGeomSmooth().
SUMOReal Position::dotProduct (const Position & pos) inline inherited
returns the dot product (scalar product) between this point and the second one
Definition at line 257 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
Referenced by NBHeightMapper::Triangle::getZ().
const RGBColor& Shape::getColor () const inline inherited
Returns the color of the Shape.
Returns
The Shape's color
Definition at line 79 of file Shape.h.
References Shape::myColor.
Referenced by GUIPolygon::drawGL(), GUIPointOfInterest::drawGL(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), writeXML(), and SUMO::Polygon::writeXML().
SUMOReal PointOfInterest::getHeight () const inline
Returns the image height of the POI.
Definition at line 92 of file PointOfInterest.h.
References myHalfImgHeight.
Referenced by writeXML().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciBusOrContainerStop(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNEConnectorFrame::buildIinternalLanes(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), NLDetectorBuilder::convUncontE2PosLength(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSVehicle::getBackPosition(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), GNEEdge::getDest(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), MSE2Collector::getEstimateQueueLength(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), GNEEdge::getSource(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_BTsender::notifyMove(), MSE2Collector::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_SL2015::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_LC2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_ArealDetector::processGet(), TraCIServerAPI_Lane::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), MSBaseVehicle::reroute(), MSLane::resetPartialOccupation(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), MSLane::saveState(), MSDevice_Battery::setAirDragCoefficient(), NBNodeCont::setAsTLControlled(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), MSDevice_Battery::setConstantPowerIntake(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), MSDevice_Battery::setFrontSurfaceArea(), MSDevice_Battery::setInternalMomentOfInertia(), GNEJunction::setLogicValid(), MSDevice_Battery::setMass(), MSDevice_Battery::setMaximumBatteryCapacity(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSDevice_Battery::setPropulsionEfficiency(), MSDevice_Battery::setRadialDragCoefficient(), MSDevice_Battery::setRecuperationEfficiency(), MSLink::setRequestInformation(), MSDevice_Battery::setRollDragCoefficient(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), operator<<(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
const std::string& Shape::getImgFile () const inline inherited
Returns the imgFile of the Shape.
Returns
The Shape's rotation imgFile
Definition at line 101 of file Shape.h.
References Shape::myImgFile.
Referenced by GUIPolygon::drawGL(), writeXML(), and SUMO::Polygon::writeXML().
SUMOReal Shape::getLayer () const inline inherited
Returns the layer of the Shape.
Returns
The Shape's layer
Definition at line 87 of file Shape.h.
References Shape::myLayer.
Referenced by GUIPolygon::drawGL(), GUIPointOfInterest::drawGL(), writeXML(), and SUMO::Polygon::writeXML().
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 107 of file Parameterised.h.
References Parameterised::myMap.
Referenced by NBTrafficLightDefinition::compute(), MSDevice_Vehroutes::generateOutput(), GUIPerson::getParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), TraCIServerAPI_TLS::processGet(), ROVehicle::saveAsXML(), ROPerson::saveAsXML(), SUMOVTypeParameter::write(), writeXML(), and SUMO::Polygon::writeXML().
SUMOReal Shape::getNaviDegree () const inline inherited
Returns the angle of the Shape in navigational degrees.
Returns
The Shape's rotation angle
Definition at line 94 of file Shape.h.
References Shape::myNaviDegreeAngle.
Referenced by GUIPolygon::drawGL(), GUIPointOfInterest::drawGL(), writeXML(), and SUMO::Polygon::writeXML().
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 81 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), MSSOTLPolicyDesirability::readParameter(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), and TraCIServerAPI_Vehicle::vtdMap().
const std::string& Shape::getType () const inline inherited
Returns the (abstract) type of the Shape.
Returns
The Shape's (abstract) type
Definition at line 71 of file Shape.h.
References Shape::myType.
Referenced by GNEPOI::getAttribute(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_POI::processGet(), writeXML(), and SUMO::Polygon::writeXML().
SUMOReal PointOfInterest::getWidth () const inline
Returns the image width of the POI.
Definition at line 87 of file PointOfInterest.h.
References myHalfImgWidth.
Referenced by writeXML().
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 75 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), and MSDevice::equippedByDefaultAssignmentOptions().
void Position::mul (SUMOReal val) inline inherited
Multiplies both positions with the given value.
Definition at line 99 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
Referenced by NIXMLNodesHandler::addNode(), NBNodeCont::analyzeCluster(), AGPosition::compute2dPosition(), GeoConvHelper::computeFinal(), NBNodeShapeComputer::computeNodeShapeDefault(), GNEEdge::drawGL(), GUIEdge::drawGL(), NBNode::getEmptyDir(), NBDistrict::mirrorX(), NBNode::mirrorX(), NWWriter_DlrNavteq::writeNodesUnsplitted(), and NWWriter_DlrNavteq::writeTrafficSignals().
void Position::mul (SUMOReal mx, SUMOReal my) inline inherited
Multiplies position with the given values.
Definition at line 106 of file Position.h.
References Position::myX, and Position::myY.
void Position::mul (SUMOReal mx, SUMOReal my, SUMOReal mz) inline inherited
Multiplies position with the given values.
Definition at line 112 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
void Position::norm2d () inline inherited
Definition at line 158 of file Position.h.
References Position::myX, Position::myY, and SUMOReal.
Referenced by NBNode::getEmptyDir().
bool Position::operator!= (const Position & p2) const inline inherited
Definition at line 200 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
Position Position::operator* (SUMOReal scalar) const inline inherited
keep the direction but modify the length of the (location) vector to length * scalar
Definition at line 182 of file Position.h.
References Position::myX, Position::myY, Position::myZ, and Position::Position().
Position Position::operator+ (const Position & p2) const inline inherited
Definition at line 173 of file Position.h.
References Position::myX, Position::myY, Position::myZ, and Position::Position().
Position Position::operator+ (SUMOReal offset) const inline inherited
keep the direction but modify the length of the (location) vector to length + scalar
Definition at line 187 of file Position.h.
References Position::distanceTo(), Position::myX, Position::myY, Position::myZ, Position::Position(), and SUMOReal.
Position Position::operator- (const Position & p2) const inline inherited
Definition at line 177 of file Position.h.
References Position::myX, Position::myY, Position::myZ, and Position::Position().
bool Position::operator< (const Position & p2) const inline inherited
lexicographical sorting for use in maps and sets
Definition at line 205 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
bool Position::operator== (const Position & p2) const inline inherited
Definition at line 196 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
void Position::set (SUMOReal x, SUMOReal y) inline inherited
Definition at line 78 of file Position.h.
References Position::myX, Position::myY, Position::x(), and Position::y().
Referenced by NIXMLNodesHandler::addNode(), ShapeHandler::addPOI(), NBNode::bezierControlPoints(), GeoConvHelper::cartesian2geo(), TraCIServerAPI_Vehicle::commandDistanceRequest(), TraCIServerAPI_Simulation::commandDistanceRequest(), TraCIServerAPI_Simulation::commandPositionConversion(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), GNEApplicationWindow::handleEvent_NetworkLoaded(), GUICompleteSchemeStorage::init(), NBHeightMapper::loadTiff(), GUISettingsHandler::myStartElement(), GNEViewNet::onLeftBtnPress(), GNEViewNet::onMouseMove(), NLJunctionControlBuilder::openJunction(), operator>>(), TraCIServerAPI_GUI::processSet(), TraCIServer::readTypeCheckingPosition2D(), GUICompleteSchemeStorage::saveViewport(), NGNode::setX(), NGNode::setY(), GeoConvHelper::x2cartesian(), and GeoConvHelper::x2cartesian_const().
void Position::set (SUMOReal x, SUMOReal y, SUMOReal z) inline inherited
Definition at line 84 of file Position.h.
References Position::myX, Position::myY, Position::myZ, Position::x(), Position::y(), and Position::z().
void Position::set (const Position & pos) inline inherited
Definition at line 91 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
void Shape::setColor (const RGBColor & col) inline inherited
Sets a new color.
Parameters
[in] col The new color to use
Definition at line 121 of file Shape.h.
References Shape::myColor.
Referenced by TraCIServerAPI_POI::processSet(), and TraCIServerAPI_Polygon::processSet().
void PointOfInterest::setHeight (SUMOReal height) inline
set the image height of the POI
Definition at line 108 of file PointOfInterest.h.
References myHalfImgHeight.
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
void Shape::setImgFile (const std::string & imgFile) inline inherited
Sets a new imgFile.
Parameters
[in] imgFile The new imgFile to use
Definition at line 144 of file Shape.h.
References Shape::myImgFile.
void Shape::setLayer (const SUMOReal layer) inline inherited
Sets a new layer.
Parameters
[in] layer The new layer to use
Definition at line 129 of file Shape.h.
References Shape::myLayer.
void Shape::setNaviDegree (const SUMOReal angle) inline inherited
Sets a new angle in navigational degrees.
Parameters
[in] layer The new angle to use
Definition at line 137 of file Shape.h.
References Shape::myNaviDegreeAngle.
void Shape::setType (const std::string & type) inline inherited
Sets a new type.
Parameters
[in] type The new type to use
Definition at line 113 of file Shape.h.
References Shape::myType.
Referenced by TraCIServerAPI_POI::processSet(), and TraCIServerAPI_Polygon::processSet().
void PointOfInterest::setWidth (SUMOReal width) inline
set the image width of the POI
Definition at line 103 of file PointOfInterest.h.
References myHalfImgWidth.
void Position::sub (SUMOReal dx, SUMOReal dy) inline inherited
Substracts the given position from this one.
Definition at line 139 of file Position.h.
References Position::myX, and Position::myY.
Referenced by NBNode::bezierControlPoints(), GeoConvHelper::cartesian2geo(), AGPosition::compute2dPosition(), GLHelper::drawTextBox(), PositionVector::extrapolate(), PositionVector::extrapolate2D(), NBNode::getEmptyDir(), and NBHeightMapper::Triangle::getZ().
void Position::sub (SUMOReal dx, SUMOReal dy, SUMOReal dz) inline inherited
Substracts the given position from this one.
Definition at line 145 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
void Position::sub (const Position & pos) inline inherited
Substracts the given position from this one.
Definition at line 152 of file Position.h.
References Position::myX, Position::myY, and Position::myZ.
void PointOfInterest::writeXML (OutputDevice & out, const bool geo = false, const SUMOReal zOffset = 0., const std::string laneID = "", const SUMOReal pos = 0.) inline
Definition at line 117 of file PointOfInterest.h.
References GeoConvHelper::cartesian2geo(), OutputDevice::closeTag(), Shape::DEFAULT_ANGLE, Shape::DEFAULT_IMG_FILE, Shape::DEFAULT_IMG_HEIGHT, Shape::DEFAULT_IMG_WIDTH, StringUtils::escapeXML(), Shape::getColor(), GeoConvHelper::getFinal(), getHeight(), Named::getID(), Shape::getImgFile(), Shape::getLayer(), Parameterised::getMap(), Shape::getNaviDegree(), Shape::getType(), getWidth(), OutputDevice::openTag(), SUMO_ATTR_ANGLE, SUMO_ATTR_COLOR, SUMO_ATTR_HEIGHT, SUMO_ATTR_ID, SUMO_ATTR_IMGFILE, SUMO_ATTR_KEY, SUMO_ATTR_LANE, SUMO_ATTR_LAT, SUMO_ATTR_LAYER, SUMO_ATTR_LON, SUMO_ATTR_POSITION, SUMO_ATTR_TYPE, SUMO_ATTR_VALUE, SUMO_ATTR_WIDTH, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_TAG_PARAM, SUMO_TAG_POI, OutputDevice::writeAttr(), Position::x(), and Position::y().
Referenced by GNEPOI::saveToFile().
SUMOReal Position::x () const inline inherited
Returns the x-position.
Definition at line 63 of file Position.h.
References Position::myX.
Referenced by Boundary::add(), PositionVector::add(), NIXMLNodesHandler::addNode(), GeomHelper::angle2D(), GUISettingsHandler::applyViewport(), Boundary::around(), PositionVector::around(), bezier(), NBNode::bezierControlPoints(), NIImporter_OpenDrive::calculateStraightEndPoint(), GeoConvHelper::cartesian2geo(), GUIDanielPerspectiveChanger::centerTo(), NGRandomNetBuilder::checkAngles(), GUISUMOAbstractView::checkGDALImage(), TraCIServerAPI_Simulation::commandPositionConversion(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), NGRandomNetBuilder::createNewNode(), GNEViewNet::doPaintGL(), GUIVehicle::drawAction_drawRailCarriages(), GNELane::drawArrows(), GUILane::drawArrows(), GLHelper::drawBoxLine(), GLHelper::drawBoxLines(), GNEDetector::drawDetectorIcon(), GLHelper::drawFilledPoly(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEJunction::drawGL(), GUITrafficLightLogicWrapper::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GUIPerson::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GNEEdge::drawGL(), GNEChargingStation::drawGL(), GUIChargingStation::drawGL(), GUIContainerStop::drawGL(), GNECalibrator::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GNELane::drawLane2LaneConnections(), GUILane::drawLane2LaneConnections(), GLHelper::drawLine(), GUIBaseVehicle::drawLinkItem(), GUILane::drawLinkRule(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GUIE3Collector::MyWrapper::drawSingleCrossing(), GLHelper::drawText(), GUILane::drawTextAtEnd(), GLHelper::drawTextBox(), GLHelper::drawTriangleAtEnd(), MSVTypeProbe::execute(), NBNodeCont::extract(), GeomHelper::findLineCircleIntersections(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorE2::getAttribute(), GNECalibrator::getAttribute(), GUIPointOfInterest::getCenteringBoundary(), NBNode::getEmptyDir(), MSPModel_Striping::getNextLaneObstacles(), GNEAdditional::getPopUpMenu(), GNEDetectorEntry::getPositionInView(), GNEDetectorExit::getPositionInView(), GNEDetectorE1::getPositionInView(), GNEStoppingPlace::getPositionInView(), GNEVaporizer::getPositionInView(), GNERouteProbe::getPositionInView(), GNEDetectorE2::getPositionInView(), GNEDetector::getPositionOverLane(), MSVTKExport::getPositions(), TraCIServerAPI_InductionLoop::getTree(), GUIDanielPerspectiveChanger::getXPos(), NBHeightMapper::getZ(), GNEInternalLane::GNEInternalLane(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), GUIJunctionWrapper::GUIJunctionWrapper(), GUILane::GUILane(), NBNodeCont::insert(), PositionVector::intersects(), isLeft(), PositionVector::isLeft(), NBHeightMapper::loadTiff(), GNEDetector::moveAdditional(), GNEEdge::moveGeometry(), MSPModel_Striping::moveInDirection(), GUISettingsHandler::myStartElement(), GUIMEInductLoop::MyWrapper::MyWrapper(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), GeomHelper::nearest_offset_on_line_to_point2D(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), GNEViewNet::onMouseMove(), PositionVector::as_poly_cw_sorter::operator()(), PositionVector::increasing_x_y_sorter::operator()(), TraCIServerAPI_Junction::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_GUI::processSet(), NBNodeCont::retrieve(), Position::set(), GNEAdditional::setBlockIconRotation(), GUIBaseVehicle::setFunctionalColor(), GNEJunction::setPosition(), GUIDialog_EditViewport::setValues(), GUICompleteSchemeStorage::setViewport(), GUISUMOAbstractView::setViewportFromTo(), NGNode::setY(), PositionVector::sideOffset(), NBEdge::startShapeAt(), NBNetBuilder::transformCoordinates(), GNEAdditionalSet::updateConnections(), GNEDetectorEntry::updateGeometry(), GNEDetectorExit::updateGeometry(), GNEDetectorE1::updateGeometry(), GNEConnection::updateGeometry(), GNECrossing::updateGeometry(), GNEChargingStation::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEContainerStop::updateGeometry(), GNEBusStop::updateGeometry(), GNECalibrator::updateGeometry(), GNEJunction::updateGeometry(), GNELane::updateGeometry(), GUISUMOAbstractView::updatePositionInformation(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), GNEDetectorEntry::writeAdditional(), GNEDetectorExit::writeAdditional(), GNEDetectorE1::writeAdditional(), GNEDetectorE2::writeAdditional(), GNEVariableSpeedSignal::writeAdditional(), GNEDetectorE3::writeAdditional(), GNECalibrator::writeAdditional(), GNERerouter::writeAdditional(), NBSign::writeAsPOI(), NWWriter_OpenDrive::writeGeomLines(), NWWriter_DlrNavteq::writeNodesUnsplitted(), BinaryFormatter::writePosition(), NWFrame::writePositionLong(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSFullExport::writeVehicles(), writeXML(), GeoConvHelper::x2cartesian(), GeoConvHelper::x2cartesian_const(), and GUIDanielPerspectiveChanger::zoom().
SUMOReal Position::y () const inline inherited
Returns the y-position.
Definition at line 68 of file Position.h.
References Position::myY.
Referenced by Boundary::add(), PositionVector::add(), NIXMLNodesHandler::addNode(), GeomHelper::angle2D(), GUISettingsHandler::applyViewport(), Boundary::around(), PositionVector::around(), bezier(), NBNode::bezierControlPoints(), NIImporter_OpenDrive::calculateStraightEndPoint(), GeoConvHelper::cartesian2geo(), GUIDanielPerspectiveChanger::centerTo(), NGRandomNetBuilder::checkAngles(), GUISUMOAbstractView::checkGDALImage(), TraCIServerAPI_Simulation::commandPositionConversion(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), NGRandomNetBuilder::createNewNode(), GNEViewNet::doPaintGL(), GUIVehicle::drawAction_drawRailCarriages(), GNELane::drawArrows(), GUILane::drawArrows(), GLHelper::drawBoxLine(), GLHelper::drawBoxLines(), GNEDetector::drawDetectorIcon(), GLHelper::drawFilledPoly(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEJunction::drawGL(), GUITrafficLightLogicWrapper::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GUIPerson::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GNEEdge::drawGL(), GNEChargingStation::drawGL(), GUIChargingStation::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GNELane::drawLane2LaneConnections(), GUILane::drawLane2LaneConnections(), GLHelper::drawLine(), GUIBaseVehicle::drawLinkItem(), GUILane::drawLinkRule(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GUIE3Collector::MyWrapper::drawSingleCrossing(), GLHelper::drawText(), GUILane::drawTextAtEnd(), GLHelper::drawTextBox(), GLHelper::drawTriangleAtEnd(), MSVTypeProbe::execute(), NBNodeCont::extract(), GeomHelper::findLineCircleIntersections(), GUIPointOfInterest::getCenteringBoundary(), NBNode::getEmptyDir(), MSPModel_Striping::getNextLaneObstacles(), GNEAdditional::getPopUpMenu(), GNEVaporizer::getPositionInView(), GNERouteProbe::getPositionInView(), MSVTKExport::getPositions(), TraCIServerAPI_InductionLoop::getTree(), GUIDanielPerspectiveChanger::getYPos(), NBHeightMapper::getZ(), GNEInternalLane::GNEInternalLane(), GUIBusStop::GUIBusStop(), GUIChargingStation::GUIChargingStation(), GUIContainerStop::GUIContainerStop(), GUIJunctionWrapper::GUIJunctionWrapper(), GUILane::GUILane(), NBNodeCont::insert(), PositionVector::intersects(), isLeft(), PositionVector::isLeft(), NBHeightMapper::loadTiff(), GNEEdge::moveGeometry(), MSPModel_Striping::moveInDirection(), GUISettingsHandler::myStartElement(), GUIMEInductLoop::MyWrapper::MyWrapper(), GUIInstantInductLoop::MyWrapper::MyWrapper(), GUI_E2_ZS_Collector::MyWrapper::MyWrapper(), GUIInductLoop::MyWrapper::MyWrapper(), GeomHelper::nearest_offset_on_line_to_point2D(), GUIGLObjectPopupMenu::onCmdCopyCursorGeoPosition(), PositionVector::as_poly_cw_sorter::operator()(), PositionVector::increasing_x_y_sorter::operator()(), TraCIServerAPI_Junction::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_GUI::processSet(), NBNodeCont::retrieve(), Position::set(), GUIBaseVehicle::setFunctionalColor(), GNEJunction::setPosition(), GUIDialog_EditViewport::setValues(), GUICompleteSchemeStorage::setViewport(), GUISUMOAbstractView::setViewportFromTo(), NGNode::setX(), PositionVector::sideOffset(), NBEdge::startShapeAt(), NBNetBuilder::transformCoordinates(), GNEAdditionalSet::updateConnections(), GNEConnection::updateGeometry(), GNECrossing::updateGeometry(), GNEChargingStation::updateGeometry(), GNEDetectorE2::updateGeometry(), GNEContainerStop::updateGeometry(), GNEBusStop::updateGeometry(), GNEJunction::updateGeometry(), GNELane::updateGeometry(), GUISUMOAbstractView::updatePositionInformation(), MSEmissionExport::write(), MSBatteryExport::write(), MSFCDExport::write(), GNEVariableSpeedSignal::writeAdditional(), GNEDetectorE3::writeAdditional(), GNERerouter::writeAdditional(), NBSign::writeAsPOI(), NWWriter_OpenDrive::writeGeomLines(), NWWriter_DlrNavteq::writeNodesUnsplitted(), BinaryFormatter::writePosition(), NWFrame::writePositionLong(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSFullExport::writeVehicles(), writeXML(), GeoConvHelper::x2cartesian(), GeoConvHelper::x2cartesian_const(), and GUIDanielPerspectiveChanger::zoom().
SUMOReal Position::z () const inline inherited
Returns the z-position.
Definition at line 73 of file Position.h.
References Position::myZ.
Referenced by PositionVector::add(), GUISettingsHandler::applyViewport(), NBNode::bezierControlPoints(), TraCIServerAPI_Simulation::commandPositionConversion(), NBNodeShapeComputer::computeNodeShapeDefault(), NBNodeShapeComputer::computeNodeShapeSmall(), NBNode::computeSmoothShape(), MSVTypeProbe::execute(), GNELane::getPopUpMenu(), GUILane::getPopUpMenu(), MSVTKExport::getPositions(), PositionVector::move2side(), GNEEdge::moveGeometry(), GUISettingsHandler::myStartElement(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), GNENet::registerJunction(), Position::set(), GUIDialog_EditViewport::setValues(), GUICompleteSchemeStorage::setViewport(), GUISUMOAbstractView::setViewportFromTo(), PositionVector::slopeDegreeAtOffset(), NBEdge::startShapeAt(), MSFCDExport::write(), NWWriter_OpenDrive::writeGeomLines(), BinaryFormatter::writePosition(), NWFrame::writePositionLong(), and MSFCDExport::writeTransportable().
Field Documentation
const SUMOReal Shape::DEFAULT_ANGLE = 0 static inherited
Definition at line 151 of file Shape.h.
Referenced by ShapeHandler::addPOI(), ShapeHandler::addPoly(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_Polygon::processSet(), writeXML(), and SUMO::Polygon::writeXML().
const std::string Shape::DEFAULT_IMG_FILE = "" static inherited
Definition at line 152 of file Shape.h.
Referenced by ShapeHandler::addPOI(), ShapeHandler::addPoly(), GUIPointOfInterest::drawGL(), GUIPointOfInterest::getCenteringBoundary(), TraCIServerAPI_Polygon::processSet(), TraCIServerAPI_POI::processSet(), writeXML(), and SUMO::Polygon::writeXML().
const SUMOReal Shape::DEFAULT_IMG_HEIGHT = 1 static inherited
Definition at line 154 of file Shape.h.
Referenced by ShapeHandler::addPOI(), TraCIServerAPI_POI::processSet(), and writeXML().
const SUMOReal Shape::DEFAULT_IMG_WIDTH = 1 static inherited
Definition at line 153 of file Shape.h.
Referenced by ShapeHandler::addPOI(), TraCIServerAPI_POI::processSet(), and writeXML().
const SUMOReal Shape::DEFAULT_LAYER = 128 static inherited
Definition at line 150 of file Shape.h.
Referenced by ShapeHandler::myStartElement().
const std::string Shape::DEFAULT_TYPE = "" static inherited
Definition at line 149 of file Shape.h.
Referenced by ShapeHandler::addPoly().
const Position Position::INVALID static inherited
Definition at line 261 of file Position.h.
Referenced by NBNode::bezierControlPoints(), MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::enterLaneAtMove(), MSVehicle::executeMove(), NLShapeHandler::getLanePos(), PCLoaderXML::getLanePos(), GNEApplicationWindow::GNEShapeHandler::getLanePos(), MSPModel_Striping::PState::getPosition(), MSTransportable::Stage_Driving::getPosition(), MSVehicle::getPosition(), PositionVector::intersectionPosition2D(), PositionVector::move2side(), MSPModel_Striping::moveInDirection(), GUIDialog_EditViewport::onCmdChanged(), GUIDialog_EditViewport::onCmdOk(), PositionVector::positionAtOffset(), PositionVector::positionAtOffset2D(), MSPerson::MSPersonStage_Driving::proceed(), GUISUMOAbstractView::showViewportEditor(), MSLaneChangerSublane::startChangeSublane(), and PositionVector::transformToVectorCoordinates().
RGBColor Shape::myColor protected inherited
The color of the Shape.
Definition at line 161 of file Shape.h.
Referenced by Shape::getColor(), and Shape::setColor().
SUMOReal PointOfInterest::myHalfImgHeight protected
The half height of the image when rendering this POI.
Definition at line 164 of file PointOfInterest.h.
Referenced by GUIPointOfInterest::drawGL(), GUIPointOfInterest::getCenteringBoundary(), getHeight(), and setHeight().
SUMOReal PointOfInterest::myHalfImgWidth protected
The half width of the image when rendering this POI.
Definition at line 161 of file PointOfInterest.h.
Referenced by GUIPointOfInterest::drawGL(), GUIPointOfInterest::getCenteringBoundary(), getWidth(), and setWidth().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
std::string Shape::myImgFile protected inherited
The angle of the Shape.
Definition at line 170 of file Shape.h.
Referenced by GUIPointOfInterest::drawGL(), GUIPointOfInterest::getCenteringBoundary(), Shape::getImgFile(), and Shape::setImgFile().
SUMOReal Shape::myLayer protected inherited
The layer of the Shape.
Definition at line 164 of file Shape.h.
Referenced by Shape::getLayer(), and Shape::setLayer().
SUMOReal Shape::myNaviDegreeAngle protected inherited
The angle of the Shape.
Definition at line 167 of file Shape.h.
Referenced by Shape::getNaviDegree(), and Shape::setNaviDegree().
std::string Shape::myType protected inherited
The type of the Shape.
Definition at line 158 of file Shape.h.
Referenced by GUIPolygon::drawGL(), GUIPointOfInterest::drawGL(), GUIPolygon::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), Shape::getType(), and Shape::setType().
The documentation for this class was generated from the following file:
PointOfInterest.h