SUMO - Simulation of Urban MObility: GNEVariableSpeedSignalDialog Class Reference
GNEVariableSpeedSignalDialog Class Reference
#include <GNEVariableSpeedSignalDialog.h>
Public Member Functions
GNEVariableSpeedSignalDialog (GNEVariableSpeedSignal *variableSpeedSignalParent)
FOX-declaration.
~GNEVariableSpeedSignalDialog ()
FOX-callbacks
event called after press add row button
long onCmdAddRow (FXObject *, FXSelector, void *)
long onCmdRemoveRow (FXObject *, FXSelector, void *)
event called after press remove row
long onCmdAccept (FXObject *, FXSelector, void *)
event called after press accept button
long onCmdCancel (FXObject *, FXSelector, void *)
event called after press cancel button
long onCmdReset (FXObject *, FXSelector, void *)
event called after press cancel button
Protected Member Functions
void execute ()
Invalidated execute dialog for external calls.
GNEVariableSpeedSignalDialog ()
FOX needs this.
void hide ()
Invalidated show dialog for external calls.
void show ()
Invalidated show dialog for external calls.
Protected Attributes
FXButton * myAcceptButton
accept button
FXButton * myAddRow
Button for insert row.
FXButton * myCancelButton
cancel button
FXVerticalFrame * myContentFrame
frame for contents
FXTable * myDataList
Table with the data.
FXButton * myResetButton
cancel button
FXHorizontalFrame * myRowFrame
Horizontal frame for row elements.
FXTextField * myRowSpeed
Text field with speed.
FXTextField * myRowStep
Text field with step
GNEVariableSpeedSignal * myVariableSpeedSignalParent
Pointer to Variable Speed Signal.
std::map< SUMOTime, SUMOReal > myVSSValues
Map with the temporal VSSValues.
Private Member Functions
GNEVariableSpeedSignalDialog (const GNEVariableSpeedSignalDialog &)
Invalidated copy constructor.
GNEVariableSpeedSignalDialog & operator= (const GNEVariableSpeedSignalDialog &)
Invalidated assignment operator.
void updateTable ()
update data table
Detailed Description
Definition at line 52 of file GNEVariableSpeedSignalDialog.h.
Constructor & Destructor Documentation
GNEVariableSpeedSignalDialog::GNEVariableSpeedSignalDialog (GNEVariableSpeedSignal * variableSpeedSignalParent)
FOX-declaration.
Definition at line 62 of file GNEVariableSpeedSignalDialog.cpp.
References MID_GNE_VARIABLESPEEDSIGNAL_ADDROW, MID_GNE_VARIABLESPEEDSIGNAL_CHANGEVALUE, and MID_GNE_VARIABLESPEEDSIGNAL_REMOVEROW.
GNEVariableSpeedSignalDialog::~GNEVariableSpeedSignalDialog ()
Definition at line 92 of file GNEVariableSpeedSignalDialog.cpp.
GNEVariableSpeedSignalDialog::GNEVariableSpeedSignalDialog () inline protected
FOX needs this.
Definition at line 83 of file GNEVariableSpeedSignalDialog.h.
GNEVariableSpeedSignalDialog::GNEVariableSpeedSignalDialog (const GNEVariableSpeedSignalDialog &) private
Invalidated copy constructor.
Member Function Documentation
void GNEAdditionalDialog::execute () protected inherited
Invalidated execute dialog for external calls.
Definition at line 88 of file GNEAdditionalDialog.cpp.
Referenced by GNEAdditionalDialog::GNEAdditionalDialog().
void GNEAdditionalDialog::hide () protected inherited
Invalidated show dialog for external calls.
Definition at line 82 of file GNEAdditionalDialog.cpp.
Referenced by GNEAdditionalDialog::GNEAdditionalDialog().
long GNEVariableSpeedSignalDialog::onCmdAccept (FXObject * , FXSelector , void *) virtual
event called after press accept button
Implements GNEAdditionalDialog.
Definition at line 149 of file GNEVariableSpeedSignalDialog.cpp.
References myVariableSpeedSignalParent, myVSSValues, and GNEVariableSpeedSignal::setVariableSpeedSignalSteps().
long GNEVariableSpeedSignalDialog::onCmdAddRow (FXObject * , FXSelector , void *)
Definition at line 97 of file GNEVariableSpeedSignalDialog.cpp.
References TplConvert::_str2int(), TplCheck::_str2SUMOReal(), TplConvert::_str2SUMOReal(), TplCheck::_str2SUMOTime(), myRowSpeed, myRowStep, myVSSValues, SUMOReal, and updateTable().
long GNEVariableSpeedSignalDialog::onCmdCancel (FXObject * , FXSelector , void *) virtual
event called after press cancel button
Implements GNEAdditionalDialog.
Definition at line 159 of file GNEVariableSpeedSignalDialog.cpp.
long GNEVariableSpeedSignalDialog::onCmdRemoveRow (FXObject * , FXSelector , void *)
event called after press remove row
Definition at line 131 of file GNEVariableSpeedSignalDialog.cpp.
References TplConvert::_2int(), myDataList, myVSSValues, and updateTable().
long GNEVariableSpeedSignalDialog::onCmdReset (FXObject * , FXSelector , void *) virtual
event called after press cancel button
Implements GNEAdditionalDialog.
Definition at line 167 of file GNEVariableSpeedSignalDialog.cpp.
References GNEVariableSpeedSignal::getVariableSpeedSignalSteps(), myVariableSpeedSignalParent, myVSSValues, and updateTable().
GNEVariableSpeedSignalDialog& GNEVariableSpeedSignalDialog::operator= (const GNEVariableSpeedSignalDialog &) private
Invalidated assignment operator.
void GNEAdditionalDialog::show () protected inherited
Invalidated show dialog for external calls.
Definition at line 76 of file GNEAdditionalDialog.cpp.
Referenced by GNEAdditionalDialog::GNEAdditionalDialog().
void GNEVariableSpeedSignalDialog::updateTable () private virtual
update data table
Implements GNEAdditionalDialog.
Definition at line 176 of file GNEVariableSpeedSignalDialog.cpp.
References GUIIconSubSys::getIcon(), ICON_REMOVE, myDataList, myVSSValues, and toString().
Referenced by onCmdAddRow(), onCmdRemoveRow(), and onCmdReset().
Field Documentation
FXButton* GNEAdditionalDialog::myAcceptButton protected inherited
accept button
Definition at line 90 of file GNEAdditionalDialog.h.
FXButton* GNEVariableSpeedSignalDialog::myAddRow protected
Button for insert row.
Definition at line 104 of file GNEVariableSpeedSignalDialog.h.
FXButton* GNEAdditionalDialog::myCancelButton protected inherited
cancel button
Definition at line 93 of file GNEAdditionalDialog.h.
FXVerticalFrame* GNEAdditionalDialog::myContentFrame protected inherited
frame for contents
Definition at line 87 of file GNEAdditionalDialog.h.
FXTable* GNEVariableSpeedSignalDialog::myDataList protected
Table with the data.
Definition at line 92 of file GNEVariableSpeedSignalDialog.h.
Referenced by onCmdRemoveRow(), and updateTable().
FXButton* GNEAdditionalDialog::myResetButton protected inherited
cancel button
Definition at line 96 of file GNEAdditionalDialog.h.
FXHorizontalFrame* GNEVariableSpeedSignalDialog::myRowFrame protected
Horizontal frame for row elements.
Definition at line 95 of file GNEVariableSpeedSignalDialog.h.
FXTextField* GNEVariableSpeedSignalDialog::myRowSpeed protected
Text field with speed.
Definition at line 101 of file GNEVariableSpeedSignalDialog.h.
Referenced by onCmdAddRow().
FXTextField* GNEVariableSpeedSignalDialog::myRowStep protected
Text field with step
Definition at line 98 of file GNEVariableSpeedSignalDialog.h.
Referenced by onCmdAddRow().
GNEVariableSpeedSignal* GNEVariableSpeedSignalDialog::myVariableSpeedSignalParent protected
Pointer to Variable Speed Signal.
Definition at line 86 of file GNEVariableSpeedSignalDialog.h.
Referenced by onCmdAccept(), and onCmdReset().
std::map<SUMOTime, SUMOReal> GNEVariableSpeedSignalDialog::myVSSValues protected
Map with the temporal VSSValues.
Definition at line 89 of file GNEVariableSpeedSignalDialog.h.
Referenced by onCmdAccept(), onCmdAddRow(), onCmdRemoveRow(), onCmdReset(), and updateTable().
The documentation for this class was generated from the following files:
GNEVariableSpeedSignalDialog.h
GNEVariableSpeedSignalDialog.cpp