SUMO - Simulation of Urban MObility: NIXMLNodesHandler Class Reference
NIXMLNodesHandler Class Reference
Importer for network nodes stored in XML.
#include <NIXMLNodesHandler.h>
Public Member Functions
void characters (const XMLCh *const chars, const XERCES3_SIZE_t length)
The inherited method called when characters occured.
void endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname)
The inherited method called when a tag is being closed.
const std::string & getFileName () const
returns the current file name
NIXMLNodesHandler (NBNodeCont &nc, NBTrafficLightLogicCont &tlc, OptionsCont &options)
Constructor.
void registerParent (const int tag, GenericSAXHandler *handler)
Assigning a parent handler which is enabled when the specified tag is closed.
void setFileName (const std::string &name)
Sets the current file name.
void startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes &attrs)
The inherited method called when a new tag opens.
~NIXMLNodesHandler ()
Destructor.
SAX ErrorHandler callbacks
void warning (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-warnings.
void error (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
void fatalError (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Handler for XML-errors.
Static Public Member Functions
static void processNodeType (const SUMOSAXAttributes &attrs, NBNode *node, const std::string &nodeID, const Position &position, bool updateEdgeGeometries, NBNodeCont &nc, NBTrafficLightLogicCont &tlc)
parses node attributes (not related to positioning)
Protected Member Functions
std::string buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException &exception)
Builds an error message.
virtual void myCharacters (int element, const std::string &chars)
Callback method for characters to implement by derived classes.
virtual void myEndElement (int element)
Callback method for a closing tag to implement by derived classes.
inherited from GenericSAXHandler
void myStartElement (int element, const SUMOSAXAttributes &attrs)
Called on the opening of a tag;.
Private Member Functions
void addJoinCluster (const SUMOSAXAttributes &attrs)
void addJoinExclusion (const SUMOSAXAttributes &attrs)
void addNode (const SUMOSAXAttributes &attrs)
void deleteNode (const SUMOSAXAttributes &attrs)
NIXMLNodesHandler (const NIXMLNodesHandler &s)
invalid copy constructor
NIXMLNodesHandler & operator= (const NIXMLNodesHandler &s)
invalid assignment operator
Static Private Member Functions
static void processTrafficLightDefinitions (const SUMOSAXAttributes &attrs, NBNode *currentNode, NBTrafficLightLogicCont &tlc)
Builds the defined traffic light or adds a node to it.
Private Attributes
std::string myID
The id of the currently parsed node.
GeoConvHelper * myLocation
The coordinate transformation which was used compute the node coordinates.
NBNodeCont & myNodeCont
The node container to add built nodes to.
OptionsCont & myOptions
A reference to the program's options.
Position myPosition
The position of the currently parsed node.
NBTrafficLightLogicCont & myTLLogicCont
The traffic lights container to add built tls to.
Detailed Description
Importer for network nodes stored in XML.
This SAX-handler parses node information and stores it in the given node container. Additionally, the given tls-container may be filled with additional information.
Definition at line 60 of file NIXMLNodesHandler.h.
Constructor & Destructor Documentation
NIXMLNodesHandler::NIXMLNodesHandler (NBNodeCont & nc, NBTrafficLightLogicCont & tlc, OptionsCont & options)
Constructor.
Parameters
Definition at line 63 of file NIXMLNodesHandler.cpp.
NIXMLNodesHandler::~NIXMLNodesHandler ()
Destructor.
Definition at line 74 of file NIXMLNodesHandler.cpp.
References myLocation.
NIXMLNodesHandler::NIXMLNodesHandler (const NIXMLNodesHandler & s) private
invalid copy constructor
Member Function Documentation
void NIXMLNodesHandler::addJoinCluster (const SUMOSAXAttributes & attrs) private
Definition at line 235 of file NIXMLNodesHandler.cpp.
References NBNodeCont::addCluster2Join(), SUMOSAXAttributes::get(), StringTokenizer::getVector(), myNodeCont, and SUMO_ATTR_NODES.
Referenced by myStartElement().
void NIXMLNodesHandler::addJoinExclusion (const SUMOSAXAttributes & attrs) private
Definition at line 246 of file NIXMLNodesHandler.cpp.
References NBNodeCont::addJoinExclusion(), SUMOSAXAttributes::get(), StringTokenizer::getVector(), myNodeCont, and SUMO_ATTR_NODES.
Referenced by myStartElement().
void NIXMLNodesHandler::addNode (const SUMOSAXAttributes & attrs) private
Definition at line 105 of file NIXMLNodesHandler.cpp.
References SUMOSAXAttributes::get(), OptionsCont::getBool(), NBNode::getPosition(), SUMOSAXAttributes::hasAttribute(), Position::mul(), myID, myLocation, myNodeCont, myOptions, myPosition, myTLLogicCont, processNodeType(), NBNodeCont::retrieve(), Position::set(), SUMO_ATTR_ID, SUMO_ATTR_X, SUMO_ATTR_Y, SUMO_ATTR_Z, SUMOReal, NBNetBuilder::transformCoordinates(), WRITE_ERROR, Position::x(), and Position::y().
Referenced by myStartElement().
std::string GenericSAXHandler::buildErrorMessage (const XERCES_CPP_NAMESPACE::SAXParseException & exception) protected inherited
Builds an error message.
The error message includes the file name and the line/column information as supported by the given SAXParseException
Parameters
[in] exception The name of the currently processed file
Returns
A string describing the given exception
Definition at line 192 of file GenericSAXHandler.cpp.
References GenericSAXHandler::getFileName().
Referenced by GenericSAXHandler::error(), GenericSAXHandler::fatalError(), and GenericSAXHandler::warning().
void GenericSAXHandler::characters (const XMLCh *const chars, const XERCES3_SIZE_t length) inherited
The inherited method called when characters occured.
The retrieved characters are converted into a string and appended into a private buffer. They are reported as soon as the element ends.
Todo:
recheck/describe what happens with characters when a new element is opened
describe characters processing in the class' head
Definition at line 175 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), and GenericSAXHandler::myCharactersVector.
void NIXMLNodesHandler::deleteNode (const SUMOSAXAttributes & attrs) private
Definition at line 216 of file NIXMLNodesHandler.cpp.
References NBNodeCont::extract(), SUMOSAXAttributes::get(), myID, myNodeCont, NBNodeCont::retrieve(), SUMO_ATTR_ID, SUMO_TAG_DELETE, toString(), and WRITE_WARNING.
Referenced by myStartElement().
void GenericSAXHandler::endElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname) inherited
The inherited method called when a tag is being closed.
This method calls the user-implemented methods myCharacters with the previously collected and converted characters.
Then, myEndElement is called, supplying it the qname converted to its enum- and string-representations.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 126 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), GenericSAXHandler::myCharacters(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myEndElement(), GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, XMLSubSys::setHandler(), SUMO_TAG_INCLUDE, and SUMO_TAG_NOTHING.
void GenericSAXHandler::error (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Parameters
[in] exception The occured exception to process
Exceptions
ProcessError On any call
Definition at line 211 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), NIImporter_OpenDrive::geomFromSpiral(), MSRouteHandler::myStartElement(), and MSRouteHandler::parseWalkPos().
void GenericSAXHandler::fatalError (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-errors.
The message is built using buildErrorMessage and thrown within a ProcessError.
Exceptions
ProcessError On any call
Parameters
[in] exception The occured exception to process
Definition at line 217 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage().
const std::string & GenericSAXHandler::getFileName () const inherited
returns the current file name
Returns
The name of the currently processed file
Definition at line 86 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NLHandler::addE1Detector(), NLHandler::addE2Detector(), NLHandler::addEdgeLaneMeanData(), NLHandler::addInstantE1Detector(), ShapeHandler::addPOI(), ShapeHandler::addPoly(), NLHandler::addRouteProbeDetector(), NLHandler::addVTypeProbeDetector(), NLHandler::beginE3Detector(), GenericSAXHandler::buildErrorMessage(), PCNetProjectionLoader::load(), NILoader::loadXMLType(), NLHandler::myEndElement(), RODFDetectorHandler::myStartElement(), GUISettingsHandler::myStartElement(), MSStateHandler::myStartElement(), SUMORouteHandler::myStartElement(), NLHandler::myStartElement(), NIImporter_OpenDrive::myStartElement(), XMLSubSys::runParser(), GenericSAXHandler::startElement(), and SUMORouteLoader::SUMORouteLoader().
void GenericSAXHandler::myCharacters (int element, const std::string & chars) protected virtual inherited
Callback method for characters to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The opened element, given as a int
[in] chars The complete embedded character string ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_ITSUMO::Handler.
Definition at line 227 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement().
void GenericSAXHandler::myEndElement (int element) protected virtual inherited
Callback method for a closing tag to implement by derived classes.
Called by "endElement" (see there).
Parameters
[in] element The closed element, given as a int ProcessError These method may throw a ProcessError if something fails
Reimplemented in NIImporter_OpenDrive, NIImporter_OpenStreetMap::RelationHandler, NIImporter_Vissim::NIVissimXMLHandler_Routenentscheidungsdefinition, NIImporter_Vissim::NIVissimXMLHandler_Geschwindigkeitsverteilungsdefinition, NIImporter_OpenStreetMap::EdgesHandler, PCLoaderOSM::EdgesHandler, NIImporter_Vissim::NIVissimXMLHandler_VWunschentscheidungsdefinition, NIImporter_OpenStreetMap::NodesHandler, NIImporter_Vissim::NIVissimXMLHandler_Fahrzeugklassendefinition, PCLoaderOSM::RelationsHandler, MSTriggeredRerouter, SAXWeightsHandler, PCLoaderOSM::NodesHandler, NLHandler, NIImporter_ITSUMO::Handler, MSLaneSpeedTrigger, NIImporter_SUMO, NIImporter_Vissim::NIVissimXMLHandler_Streckendefinition, NIXMLEdgesHandler, MSCalibrator, SUMORouteHandler, RORouteHandler, ODDistrictHandler, MSRouteHandler, RONetHandler, MSStateHandler, NIXMLTrafficLightsHandler, GUITriggeredRerouter, GNEPoly::GNEPolyHandler, and ROMARouteHandler.
Definition at line 231 of file GenericSAXHandler.cpp.
Referenced by GenericSAXHandler::endElement(), NLHandler::networkVersion(), and SUMOSAXReader::parseNext().
void NIXMLNodesHandler::myStartElement (int element, const SUMOSAXAttributes & attrs) protected virtual
Called on the opening of a tag;.
In dependence to the obtained type, an appropriate parsing method is called.
Parameters
[in] element ID of the currently opened element
[in] attrs Attributes within the currently opened element
Exceptions
ProcessError If something fails (not used herein)
Note
policy is to throw no exception in order to allow further processing
Todo:
ProcessErrors are thrown when parsing traffic lights!?
Reimplemented from GenericSAXHandler.
Definition at line 80 of file NIXMLNodesHandler.cpp.
References addJoinCluster(), addJoinExclusion(), addNode(), deleteNode(), NIImporter_SUMO::loadLocation(), myLocation, SUMO_TAG_DELETE, SUMO_TAG_JOIN, SUMO_TAG_JOINEXCLUDE, SUMO_TAG_LOCATION, and SUMO_TAG_NODE.
NIXMLNodesHandler& NIXMLNodesHandler::operator= (const NIXMLNodesHandler & s) private
invalid assignment operator
void NIXMLNodesHandler::processNodeType (const SUMOSAXAttributes & attrs, NBNode * node, const std::string & nodeID, const Position & position, bool updateEdgeGeometries, NBNodeCont & nc, NBTrafficLightLogicCont & tlc) static
parses node attributes (not related to positioning)
Definition at line 154 of file NIXMLNodesHandler.cpp.
References PositionVector::closePolygon(), SUMOSAXAttributes::get(), StringBijection< T >::get(), NBNode::getControllingTLS(), SUMOSAXAttributes::getOpt(), NBNode::getType(), SUMOSAXAttributes::hasAttribute(), NBNodeCont::insert(), NBNode::isTrafficLight(), NODETYPE_DEAD_END, NODETYPE_DEAD_END_DEPRECATED, NODETYPE_UNKNOWN, SUMOXMLDefinitions::NodeTypes, processTrafficLightDefinitions(), NBNode::reinit(), NBTrafficLightLogicCont::removeFully(), NBNode::setCustomShape(), NBNode::setKeepClear(), NBNode::setRadius(), SUMO_ATTR_KEEP_CLEAR, SUMO_ATTR_RADIUS, SUMO_ATTR_SHAPE, SUMO_ATTR_TYPE, and SUMOReal.
Referenced by addNode(), and NIXMLEdgesHandler::addSplit().
void NIXMLNodesHandler::processTrafficLightDefinitions (const SUMOSAXAttributes & attrs, NBNode * currentNode, NBTrafficLightLogicCont & tlc) static private
Builds the defined traffic light or adds a node to it.
Parameters
[in] attrs Attributes within the currently opened node
[in] currentNode The built node to add the tls information to
Definition at line 257 of file NIXMLNodesHandler.cpp.
References StringBijection< T >::get(), NBNode::getControllingTLS(), Named::getID(), SUMOSAXAttributes::getOpt(), OptionsCont::getOptions(), NBTrafficLightLogicCont::getPrograms(), OptionsCont::getString(), NBTrafficLightDefinition::getType(), NBTrafficLightLogicCont::insert(), NBNode::isTLControlled(), SUMOSAXAttributes::parseStringVector(), NBNode::removeTrafficLights(), SUMO_ATTR_CONTROLLED_INNER, SUMO_ATTR_TLID, SUMO_ATTR_TLTYPE, toString(), SUMOXMLDefinitions::TrafficLightTypes, and WRITE_ERROR.
Referenced by processNodeType().
void GenericSAXHandler::registerParent (const int tag, GenericSAXHandler * handler) inherited
Assigning a parent handler which is enabled when the specified tag is closed.
Definition at line 167 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myParentHandler, GenericSAXHandler::myParentIndicator, and XMLSubSys::setHandler().
Referenced by NLTriggerBuilder::parseAndBuildCalibrator(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), and NLTriggerBuilder::parseAndBuildRerouter().
void GenericSAXHandler::setFileName (const std::string & name) inherited
Sets the current file name.
Parameters
[in] name The name of the currently processed file
Todo:
Hmmm - this is as unsafe as having a direct access to the variable; recheck
Definition at line 80 of file GenericSAXHandler.cpp.
References GenericSAXHandler::myFileName.
Referenced by NIImporter_SUMO::_loadNetwork(), GUISettingsHandler::GUISettingsHandler(), PCNetProjectionLoader::load(), NIImporter_OpenStreetMap::load(), loadNet(), ROLoader::loadNet(), NIImporter_ITSUMO::loadNetwork(), NIImporter_MATSim::loadNetwork(), NIImporter_Vissim::loadXML(), NILoader::loadXMLType(), main(), and XMLSubSys::runParser().
void GenericSAXHandler::startElement (const XMLCh *const uri, const XMLCh *const localname, const XMLCh *const qname, const XERCES_CPP_NAMESPACE::Attributes & attrs) inherited
The inherited method called when a new tag opens.
The method parses the supplied XMLCh*-qname using the internal name/enum-map to obtain the enum representation of the attribute name.
Then, "myStartElement" is called supplying the enumeration value, the string-representation of the name and the attributes.
Todo:
recheck/describe encoding of the string-representation
do not generate and report the string-representation
Definition at line 105 of file GenericSAXHandler.cpp.
References TplConvert::_2str(), GenericSAXHandler::convertTag(), FileHelpers::getConfigurationRelative(), GenericSAXHandler::getFileName(), SUMOSAXAttributesImpl_Xerces::getString(), FileHelpers::isAbsolute(), GenericSAXHandler::myCharactersVector, GenericSAXHandler::myPredefinedTags, GenericSAXHandler::myPredefinedTagsMML, GenericSAXHandler::myStartElement(), XMLSubSys::runParser(), SUMO_ATTR_HREF, and SUMO_TAG_INCLUDE.
void GenericSAXHandler::warning (const XERCES_CPP_NAMESPACE::SAXParseException & exception) inherited
Handler for XML-warnings.
The message is built using buildErrorMessage and reported to the warning-instance of the MsgHandler.
Parameters
[in] exception The occured exception to process
Definition at line 205 of file GenericSAXHandler.cpp.
References GenericSAXHandler::buildErrorMessage(), and WRITE_WARNING.
Field Documentation
std::string NIXMLNodesHandler::myID private
The id of the currently parsed node.
Definition at line 142 of file NIXMLNodesHandler.h.
Referenced by addNode(), and deleteNode().
GeoConvHelper* NIXMLNodesHandler::myLocation private
The coordinate transformation which was used compute the node coordinates.
Definition at line 154 of file NIXMLNodesHandler.h.
Referenced by addNode(), myStartElement(), and ~NIXMLNodesHandler().
NBNodeCont& NIXMLNodesHandler::myNodeCont private
The node container to add built nodes to.
Definition at line 148 of file NIXMLNodesHandler.h.
Referenced by addJoinCluster(), addJoinExclusion(), addNode(), and deleteNode().
OptionsCont& NIXMLNodesHandler::myOptions private
A reference to the program's options.
Definition at line 139 of file NIXMLNodesHandler.h.
Referenced by addNode().
Position NIXMLNodesHandler::myPosition private
The position of the currently parsed node.
Definition at line 145 of file NIXMLNodesHandler.h.
Referenced by addNode().
NBTrafficLightLogicCont& NIXMLNodesHandler::myTLLogicCont private
The traffic lights container to add built tls to.
Definition at line 151 of file NIXMLNodesHandler.h.
Referenced by addNode().
The documentation for this class was generated from the following files:
NIXMLNodesHandler.h
NIXMLNodesHandler.cpp