SUMO - Simulation of Urban MObility: MSE2Collector::by_vehicle_position_sorter Class Reference
MSE2Collector::by_vehicle_position_sorter Class Reference
A class used to sort known vehicles by their position.
#include <MSE2Collector.h>
Public Member Functions
by_vehicle_position_sorter (const MSLane *const lane)
constructor
by_vehicle_position_sorter (const by_vehicle_position_sorter &s)
copy constructor
int operator() (const SUMOVehicle *v1, const SUMOVehicle *v2)
Comparison funtcion.
Private Member Functions
by_vehicle_position_sorter & operator= (const by_vehicle_position_sorter &)
Private Attributes
const MSLane *const myLane
The lane the detector is placed at.
Detailed Description
A class used to sort known vehicles by their position.
Sorting is needed, because the order may change if a vehicle has entered the lane by lane changing.
We need to have the lane, because the vehicle's position - used for the sorting - may be beyond the lane's end (the vehicle may be on a new lane) and we have to ask for the vehicle's position using this information.
Definition at line 333 of file MSE2Collector.h.
Constructor & Destructor Documentation
MSE2Collector::by_vehicle_position_sorter::by_vehicle_position_sorter (const MSLane *const lane) inline
constructor
Parameters
[in] lane The lane the detector is placed at
Definition at line 339 of file MSE2Collector.h.
MSE2Collector::by_vehicle_position_sorter::by_vehicle_position_sorter (const by_vehicle_position_sorter & s) inline
copy constructor
Parameters
[in] s The instance to copy
Definition at line 347 of file MSE2Collector.h.
References MSE2Collector::operator=().
Member Function Documentation
int MSE2Collector::by_vehicle_position_sorter::operator() (const SUMOVehicle * v1, const SUMOVehicle * v2)
Comparison funtcion.
Parameters
[in] v1 First vehicle to compare
[in] v2 Second vehicle to compare
Returns
Whether the position of the first vehicles is smaller than the one of the second
Definition at line 571 of file MSE2Collector.cpp.
References SUMOVehicle::getPositionOnLane(), SUMOVehicle::isFrontOnLane(), and MSMoveReminder::myLane.
by_vehicle_position_sorter& MSE2Collector::by_vehicle_position_sorter::operator= (const by_vehicle_position_sorter &) private
Field Documentation
const MSLane* const MSE2Collector::by_vehicle_position_sorter::myLane private
The lane the detector is placed at.
Definition at line 363 of file MSE2Collector.h.
The documentation for this class was generated from the following files:
MSE2Collector.h
MSE2Collector.cpp