SUMO - Simulation of Urban MObility: GUIEdge Class Reference
GUIEdge Class Reference
A road/street connecting two junctions (gui-version)
#include <GUIEdge.h>
Public Types
typedef std::map< const MSEdge *, std::vector< MSLane * > * > AllowedLanesCont
Suceeding edges (keys) and allowed lanes to reach these edges (values).
typedef std::map< SUMOVehicleClass, AllowedLanesCont > ClassedAllowedLanesCont
Map from vehicle types to lanes that may be used to reach one of the next edges.
enum EdgeBasicFunction {
EDGEFUNCTION_UNKNOWN = -1, EDGEFUNCTION_NORMAL = 0, EDGEFUNCTION_CONNECTOR = 1, EDGEFUNCTION_INTERNAL = 2,
EDGEFUNCTION_DISTRICT = 3, EDGEFUNCTION_CROSSING = 4, EDGEFUNCTION_WALKINGAREA = 5
}
Defines possible edge types.
Public Member Functions
void addContainer (MSTransportable *c) const
Add a container to myContainers.
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
void addPerson (MSTransportable *p) const
void addRerouter ()
add a rerouter
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
bool allowsLaneChanging ()
void buildLaneChanger ()
Has to be called after all sucessors and predecessors have been set (after closeBuilding())
bool canChangeToOpposite ()
whether this edge allows changing to the opposite direction edge
virtual void changeLanes (SUMOTime t)
Performs lane changing on this edge.
void clearParameter ()
Clears the parameter map.
void closeBuilding ()
void closeTraffic (const GUILane *lane)
close this edge for traffic
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawMesoVehicles (const GUIVisualizationSettings &s) const
void drawName (const Position &pos, const SUMOReal scale, const GUIVisualizationTextSettings &settings, const SUMOReal angle=0) const
draw name of item
SUMOReal getAllowedSpeed () const
Boundary getBoundary () const
Returns the street's geometry.
SUMOReal getBruttoOccupancy () const
SUMOReal getColorValue (int activeScheme) const
gets the color value according to the current scheme index
const std::vector< std::string > & getCrossingEdges () const
Gets the crossed edge ids.
SUMOReal getCurrentTravelTime (const SUMOReal minSpeed=NUMERICAL_EPS) const
Computes and returns the current travel time for this edge.
SUMOReal getDistanceTo (const MSEdge *other) const
optimistic air distance heuristic for use in routing
SUMOReal getFlow () const
return flow based on meanSpead
const std::string & getID () const
Returns the id.
MSLane & getLane (int laneNo)
returns the enumerated lane (!!! why not private with a friend?)
SUMOReal getLength () const
return the length of the edge
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
SUMOReal getMeanSpeed () const
get the mean speed
SUMOReal getMinimumTravelTime (const SUMOVehicle *const veh) const
returns the minimum travel time for the given vehicle
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
SVCPermissions getPermissions () const
SUMOReal getRelativeSpeed () const
return meanSpead divided by allowedSpeed
SUMOReal getRoutingSpeed () const
Returns the averaged speed used by the routing device.
SUMOReal getScaleValue (int activeScheme) const
gets the scaling value according to the current scheme index
MESegment * getSegmentAtPosition (const Position &pos)
returns the segment closest to the given position
const std::vector< RGBColor > & getSegmentColors () const
return segment colors (meso)
SUMOReal getSpeedLimit () const
Returns the speed limit of the edge The speed limit of the first lane is retured; should probably be the fastest edge.
const std::vector< SUMOReal > getSubLaneSides () const
Returns the right side offsets of this edge's sublanes.
std::string getVehicleIDs () const
SUMOReal getVehicleMaxSpeed (const SUMOVehicle *const veh) const
Returns the maximum speed the vehicle may use on this edge.
int getVehicleNo () const
SUMOReal getWidth () const
Returns the edges's width (sum over all lanes)
GUIEdge (const std::string &id, int numericalID, const EdgeBasicFunction function, const std::string &streetName, const std::string &edgeType, int priority)
Constructor.
bool hasLaneChanger () const
void initialize (const std::vector< MSLane * > *lanes)
Initialize the edge.
bool isRoundabout () const
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
void lock () const
grant exclusive access to the mesoscopic state
void markAsRoundabout ()
void markDelayed () const
bool prohibits (const SUMOVehicle *const vehicle) const
Returns whether the vehicle (class) is not allowed on the edge.
void rebuildAllowedLanes ()
void recalcCache ()
Recalculates the cached values.
void removeContainer (MSTransportable *c) const
Remove container from myContainers.
void removePerson (MSTransportable *p) const
void setColor (const GUIVisualizationSettings &s) const
sets the color according to the currente settings
void setCrossingEdges (const std::vector< std::string > &crossingEdges)
Sets the crossed edge ids for a crossing edge.
bool setFunctionalColor (int activeScheme) const
sets the color according to the current scheme index and some edge function
void setID (const std::string &newID)
resets the id
void setMaxSpeed (SUMOReal val) const
Sets a new maximum speed for all lanes (used by TraCI and MSCalibrator)
bool setMultiColor (const GUIColorer &c) const
sets multiple colors according to the current scheme index and edge function
void unlock () const
release exclusive access to the mesoscopic state
~GUIEdge ()
Destructor.
inherited from GUIGlObject
virtual GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
virtual GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
Access to the edge's lanes
MSLane * leftLane (const MSLane *const lane) const
Returns the lane left to the one given, 0 if the given lane is leftmost.
MSLane * rightLane (const MSLane *const lane) const
Returns the lane right to the one given, 0 if the given lane is rightmost.
MSLane * parallelLane (const MSLane *const lane, int offset) const
Returns the lane with the given offset parallel to the given lane one or 0 if it does not exist.
const std::vector< MSLane * > & getLanes () const
Returns this edge's lanes.
const std::set< MSTransportable * > & getPersons () const
Returns this edge's persons set.
std::vector< MSTransportable * > getSortedPersons (SUMOTime timestep) const
Returns this edge's persons sorted by pos.
std::vector< MSTransportable * > getSortedContainers (SUMOTime timestep) const
Returns this edge's containers sorted by pos.
const std::vector< MSLane * > * allowedLanes (const MSEdge &destination, SUMOVehicleClass vclass=SVC_IGNORING) const
Get the allowed lanes to reach the destination-edge.
const std::vector< MSLane * > * allowedLanes (SUMOVehicleClass vclass=SVC_IGNORING) const
Get the allowed lanes for the given vehicle class.
Access to other edge attributes
EdgeBasicFunction getPurpose () const
Returns the edge type (EdgeBasicFunction)
bool isInternal () const
return whether this edge is an internal edge
bool isCrossing () const
return whether this edge is a pedestrian crossing
bool isWalkingArea () const
return whether this edge is walking area
int getNumericalID () const
Returns the numerical id of the edge.
const std::string & getStreetName () const
Returns the street name of the edge.
const std::string & getEdgeType () const
Returns the type of the edge.
int getPriority () const
Returns the priority of the edge.
Access to succeeding/predecessing edges
void addSuccessor (MSEdge *edge)
Adds an edge to the list of edges which may be reached from this edge and to the incoming of the other edge.
const MSEdgeVector & getIncomingEdges () const
Returns the list of edges from which this edge may be reached.
const std::vector< MSEdge * > & getOutgoingEdges () const
Returns the list of edges that may be reached from this edge.
int getNumSuccessors () const
Returns the number of edges that may be reached from this edge.
const MSEdgeVector & getSuccessors () const
Returns the following edges.
const MSEdgeVector & getSuccessors (SUMOVehicleClass vClass) const
Returns the following edges, restricted by vClass.
int getNumPredecessors () const
Returns the number of edges this edge is connected to.
const MSEdgeVector & getPredecessors () const
Returns the edge at the given position from the list of reachable edges.
const MSJunction * getFromJunction () const
const MSJunction * getToJunction () const
void setJunctions (MSJunction *from, MSJunction *to)
Access to vaporizing interface
bool isVaporizing () const
Returns whether vehicles on this edge shall be vaporized.
SUMOTime incVaporization (SUMOTime t)
Enables vaporization.
SUMOTime decVaporization (SUMOTime t)
Disables vaporization.
Methods releated to vehicle insertion
bool insertVehicle (SUMOVehicle &v, SUMOTime time, const bool checkOnly=false) const
Tries to insert the given vehicle into the network.
MSLane * getFreeLane (const std::vector< MSLane * > *allowed, const SUMOVehicleClass vclass) const
Finds the emptiest lane allowing the vehicle class.
MSLane * getDepartLane (MSVehicle &veh) const
Finds a depart lane for the given vehicle parameters.
SUMOTime getLastFailedInsertionTime () const
Returns the last time a vehicle could not be inserted.
void setLastFailedInsertionTime (SUMOTime time) const
Sets the last time a vehicle could not be inserted.
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
virtual const std::string & getParentName () const
Returns the name of the parent object (if any)
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window (optional)
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static void clear ()
Clears the dictionary.
static bool dictionary (const std::string &id, MSEdge *edge)
Inserts edge into the static dictionary Returns true if the key id isn't already in the dictionary. Otherwise returns false.
static MSEdge * dictionary (const std::string &id)
Returns the MSEdge associated to the key id if exists, otherwise returns 0.
static int dictSize ()
Returns the number of edges.
static void fill (std::vector< GUIEdge * > &netsWrappers)
static const MSEdgeVector & getAllEdges ()
Returns all edges with a numerical id.
static std::vector< GUIGlID > getIDs (bool includeInternal)
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
static std::pair< SUMOReal, SUMOReal > getLaneOffsets (SUMOReal x1, SUMOReal y1, SUMOReal x2, SUMOReal y2, SUMOReal prev, SUMOReal wanted)
static SUMOReal getTotalLength (bool includeInternal, bool eachLane)
static SUMOReal getTravelTimeStatic (const MSEdge *const edge, const SUMOVehicle *const veh, SUMOReal time)
Returns the travel time for the given edge.
static void insertIDs (std::vector< std::string > &into)
Inserts IDs of all known edges into the given vector.
Static parser helper
static void parseEdgesList (const std::string &desc, ConstMSEdgeVector &into, const std::string &rid)
Parses the given string assuming it contains a list of edge ids divided by spaces.
static void parseEdgesList (const std::vector< std::string > &desc, ConstMSEdgeVector &into, const std::string &rid)
Parses the given string vector assuming it edge ids.
Data Fields
std::vector< RGBColor > mySegmentColors
The color of the segments (cached)
Static Public Attributes
static const GUIGlID INVALID_ID = 0
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Member Functions
const std::vector< MSLane * > * allowedLanes (const MSEdge *destination, SUMOVehicleClass vclass=SVC_IGNORING) const
Get the allowed lanes to reach the destination-edge.
const std::vector< MSLane * > * getAllowedLanesWithDefault (const AllowedLanesCont &c, const MSEdge *dest) const
lookup in map and return 0 if not found
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
bool myAmDelayed
whether this edge had a vehicle with less than max speed on it
bool myAmRoundabout
whether this edge belongs to a roundabout
std::map< SUMOVehicleClass, MSEdgeVector > myClassesSuccessorMap
The successors available for a given vClass.
std::set< MSTransportable * > myContainers
Containers on the edge.
std::vector< std::string > myCrossingEdges
The crossed edges id for a crossing edge. On not crossing edges it is empty.
std::string myEdgeType
the type of the edge (optionally used during network creation)
SUMOReal myEmptyTraveltime
the traveltime on the empty edge (cached value for speedup)
MSJunction * myFromJunction
the junctions for this edge
const EdgeBasicFunction myFunction
the purpose of the edge
std::string myID
The name of the object.
MSLaneChanger * myLaneChanger
This member will do the lane-change.
const std::vector< MSLane * > * myLanes
Container for the edge's lane; should be sorted: (right-hand-traffic) the more left the lane, the higher the container-index.
SUMOTime myLastFailedInsertionTime
The time of last insertion failure.
SUMOReal myLength
the length of the edge (cached value for speedup)
const int myNumericalID
This edge's numerical id.
std::set< MSTransportable * > myPersons
Persons on the edge for drawing and pushbutton.
MSEdgeVector myPredecessors
The preceeding edges.
const int myPriority
the priority of the edge (used during network creation)
std::string myStreetName
the real-world name of this edge (need not be unique)
std::vector< SUMOReal > mySublaneSides
the right side for each sublane on this edge
MSEdgeVector mySuccessors
The succeeding edges.
MSJunction * myToJunction
int myVaporizationRequests
Vaporizer counter.
SUMOReal myWidth
Edge width [m].
Storages for allowed lanes (depending on vehicle classes)
AllowedLanesCont myAllowed
Associative container from destination-edge to allowed-lanes.
ClassedAllowedLanesCont myClassedAllowed
From vehicle class to lanes allowed to be used by it.
SVCPermissions myMinimumPermissions
The intersection of lane permissions for this edge.
SVCPermissions myCombinedPermissions
The union of lane permissions for this edge.
Private Member Functions
GUIEdge (const GUIEdge &s)
invalidated copy constructor
GUIEdge & operator= (const GUIEdge &s)
invalidated assignment operator
Private Attributes
MFXMutex myLock
The mutex used to avoid concurrent updates of myPersons/ myContainers.
Static edge container
typedef std::map< std::string, MSEdge * > DictType
definition of the static dictionary type
static DictType myDict
Static dictionary to associate string-ids with objects.
static MSEdgeVector myEdges
Static list of edges.
Detailed Description
A road/street connecting two junctions (gui-version)
See also
MSEdge
Definition at line 60 of file GUIEdge.h.
Member Typedef Documentation
typedef std::map< const MSEdge*, std::vector<MSLane*>* > MSEdge::AllowedLanesCont inherited
Suceeding edges (keys) and allowed lanes to reach these edges (values).
Definition at line 108 of file MSEdge.h.
typedef std::map< SUMOVehicleClass, AllowedLanesCont > MSEdge::ClassedAllowedLanesCont inherited
Map from vehicle types to lanes that may be used to reach one of the next edges.
Definition at line 111 of file MSEdge.h.
typedef std::map< std::string, MSEdge* > MSEdge::DictType protected inherited
definition of the static dictionary type
Definition at line 840 of file MSEdge.h.
Member Enumeration Documentation
enum MSEdge::EdgeBasicFunction inherited
Defines possible edge types.
For different purposes, it is necessary to know whether the edge is a normal street or something special.
Enumerator
EDGEFUNCTION_UNKNOWN
The purpose of the edge is not known.
EDGEFUNCTION_NORMAL
The edge is a normal street.
EDGEFUNCTION_CONNECTOR
The edge is a macroscopic connector (source/sink)
EDGEFUNCTION_INTERNAL
The edge is an internal edge.
EDGEFUNCTION_DISTRICT
The edge is a district edge.
EDGEFUNCTION_CROSSING
The edge is a pedestrian crossing (a special type of internal edge)
EDGEFUNCTION_WALKINGAREA
The edge is a pedestrian walking area (a special type of internal edge)
Definition at line 89 of file MSEdge.h.
Constructor & Destructor Documentation
GUIEdge::GUIEdge (const std::string & id, int numericalID, const EdgeBasicFunction function, const std::string & streetName, const std::string & edgeType, int priority)
Constructor.
Parameters
[in] id The id of the edge
[in] numericalID The numerical id (index) of the edge
See also
MSEdge
Definition at line 78 of file GUIEdge.cpp.
GUIEdge::~GUIEdge ()
Destructor.
Definition at line 85 of file GUIEdge.cpp.
References MFXMutex::locked(), myLock, and MFXMutex::unlock().
GUIEdge::GUIEdge (const GUIEdge & s) private
invalidated copy constructor
Member Function Documentation
void GUIEdge::addContainer (MSTransportable * container) const inline virtual
Add a container to myContainers.
Reimplemented from MSEdge.
Definition at line 157 of file GUIEdge.h.
References MSEdge::addContainer(), and myLock.
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 53 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NBTrafficLightDefinition::compute(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::EdgesHandler::myStartElement(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_TLS::processSet(), TraCIServerAPI_Polygon::processSet(), and TraCIServerAPI_Lane::processSet().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 59 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 67 of file Parameterised.cpp.
References Parameterised::myMap.
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 258 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
void GUIEdge::addPerson (MSTransportable * p) const inline virtual
Reimplemented from MSEdge.
Definition at line 146 of file GUIEdge.h.
References MSEdge::addPerson(), and myLock.
void GUIEdge::addRerouter ()
add a rerouter
Definition at line 552 of file GUIEdge.cpp.
References RandomDistributor< T >::add(), MSTriggeredRerouter::RerouteInterval::begin, MSTriggeredRerouter::RerouteInterval::edgeProbs, MSTriggeredRerouter::RerouteInterval::end, MSNet::getCurrentTimeStep(), GUINet::getGUIInstance(), Named::getID(), MSNet::getInstance(), MSEdge::getLanes(), MSTriggeredRerouter::myIntervals, MSTriggeredRerouter::mySpecialDest_keepDestination, MSMoveReminder::NOTIFICATION_JUNCTION, MSTriggeredRerouter::notifyEnter(), and SUMOTime_MAX.
Referenced by unlock().
void MSEdge::addSuccessor (MSEdge * edge) inline inherited
Adds an edge to the list of edges which may be reached from this edge and to the incoming of the other edge.
This is mainly used by the taz (district) parsing
Parameters
[in] edge The edge to add
Definition at line 319 of file MSEdge.h.
References MSEdge::myPredecessors, and MSEdge::mySuccessors.
Referenced by NLHandler::addDistrict().
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
const std::vector< MSLane * > * MSEdge::allowedLanes (const MSEdge & destination, SUMOVehicleClass vclass = SVC_IGNORING) const inherited
Get the allowed lanes to reach the destination-edge.
If there is no such edge, get 0. Then you are on the wrong edge.
Parameters
[in] destination The edge to reach
[in] vclass The vehicle class for which this information shall be returned
Returns
The lanes that may be used to reach the given edge, 0 if no such lanes exist
Definition at line 301 of file MSEdge.cpp.
Referenced by MSEdge::allowedLanes(), MSVehicleTransfer::checkInsertions(), MSEdge::getDepartLane(), MSEdge::getFreeLane(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSEdge::getPersons(), MSEdge::getSuccessors(), MESegment::MESegment(), MSLane::by_connections_to_sorter::operator()(), MSBaseVehicle::reroute(), and MSVehicle::updateBestLanes().
const std::vector< MSLane * > * MSEdge::allowedLanes (SUMOVehicleClass vclass = SVC_IGNORING) const inherited
Get the allowed lanes for the given vehicle class.
If there is no such edge, get 0. Then you are on the wrong edge.
Parameters
[in] vclass The vehicle class for which this information shall be returned
Returns
The lanes that may be used by the given vclass
Definition at line 307 of file MSEdge.cpp.
References MSEdge::allowedLanes().
const std::vector< MSLane * > * MSEdge::allowedLanes (const MSEdge * destination, SUMOVehicleClass vclass = SVC_IGNORING) const protected inherited
Get the allowed lanes to reach the destination-edge.
If there is no such edge, get 0. Then you are on the wrong edge.
Parameters
[in] destination The edge to reach
[in] vclass The vehicle class for which this information shall be returned
Returns
The lanes that may be used to reach the given edge, 0 if no such lanes exist
Definition at line 323 of file MSEdge.cpp.
References MSLane::allowsVehicleClass(), MSEdge::getAllowedLanesWithDefault(), MSLane::getEdge(), MSEdge::myAllowed, MSEdge::myClassedAllowed, and MSEdge::myMinimumPermissions.
bool MSEdge::allowsLaneChanging () inherited
Definition at line 229 of file MSEdge.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSLinkContHelper::getConnectingLink(), MSLane::getLogicalPredecessorLane(), MSLink::getState(), LINKSTATE_ALLWAY_STOP, LINKSTATE_DEADEND, LINKSTATE_EQUAL, LINKSTATE_MINOR, LINKSTATE_STOP, MSEdge::myFunction, and MSEdge::myLanes.
Referenced by MSEdge::buildLaneChanger().
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 187 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void MSEdge::buildLaneChanger () inherited
Has to be called after all sucessors and predecessors have been set (after closeBuilding())
Definition at line 210 of file MSEdge.cpp.
References MSEdge::allowsLaneChanging(), MSEdge::canChangeToOpposite(), OptionsCont::getBool(), OptionsCont::getOptions(), MSGlobals::gLaneChangeDuration, MSGlobals::gLateralResolution, MSEdge::myLaneChanger, and MSEdge::myLanes.
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 196 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 177 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GNECrossing::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 237 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 206 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 249 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 219 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and GUILane::getPopUpMenu().
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 228 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIBaseVehicle::getPopUpMenu().
bool MSEdge::canChangeToOpposite () inherited
whether this edge allows changing to the opposite direction edge
Definition at line 850 of file MSEdge.cpp.
References MSEdge::myLanes.
Referenced by MSEdge::buildLaneChanger(), MSLaneChanger::changeOpposite(), and MSEdge::hasLaneChanger().
void MSEdge::changeLanes (SUMOTime t) virtual inherited
Performs lane changing on this edge.
Definition at line 571 of file MSEdge.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSLinkContHelper::getConnectingLink(), MSLane::getEdge(), MSLink::getLane(), MSLane::getLinkCont(), MSLane::getLogicalPredecessorLane(), MSLink::getState(), MSLaneChanger::laneChange(), LINKSTATE_ALLWAY_STOP, LINKSTATE_DEADEND, LINKSTATE_EQUAL, LINKSTATE_MINOR, LINKSTATE_STOP, LINKSTATE_ZIPPER, MSEdge::myFunction, MSEdge::myLaneChanger, MSEdge::myLanes, and SUMOReal.
Referenced by MSEdgeControl::changeLanes(), and MSEdge::setLastFailedInsertionTime().
void MSEdge::clear () static inherited
Clears the dictionary.
Definition at line 705 of file MSEdge.cpp.
References MSEdge::myDict.
Referenced by MSNet::clearAll(), MSEdge::unlock(), and MSVehicle::updateBestLanes().
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 91 of file Parameterised.cpp.
References Parameterised::myMap.
void MSEdge::closeBuilding () inherited
Todo:
Has to be called after all edges were built and all connections were set...; Still, is not very nice
Definition at line 166 of file MSEdge.cpp.
References MELoop::buildSegmentsFor(), MSLane::getEdge(), OptionsCont::getOptions(), MSGlobals::gMesoNet, MSGlobals::gUseMesoSim, MSEdge::myAllowed, MSEdge::myLanes, MSEdge::myPredecessors, MSEdge::mySuccessors, and MSEdge::rebuildAllowedLanes().
void GUIEdge::closeTraffic (const GUILane * lane)
close this edge for traffic
Definition at line 538 of file GUIEdge.cpp.
References GUILane::closeTraffic(), MSEdge::getLanes(), GUILane::isClosed(), and MSEdge::rebuildAllowedLanes().
Referenced by unlock().
SUMOTime MSEdge::decVaporization (SUMOTime t) inherited
Disables vaporization.
The internal vaporization counter is decreased what disables the vaporization if it was only once enabled. Called from the event handler.
Parameters
[in] t The current time (unused)
Returns
Time to next call (always 0)
Exceptions
ProcessError not thrown by this method, just derived
Definition at line 391 of file MSEdge.cpp.
References MSEdge::myVaporizationRequests.
Referenced by NLTriggerBuilder::buildVaporizer(), and MSEdge::isVaporizing().
bool MSEdge::dictionary (const std::string & id, MSEdge * edge) static inherited
Inserts edge into the static dictionary Returns true if the key id isn't already in the dictionary. Otherwise returns false.
Definition at line 666 of file MSEdge.cpp.
References MSEdge::getNumericalID(), MSEdge::myDict, and MSEdge::myEdges.
Referenced by NLHandler::addConnection(), NLHandler::addDistrict(), NLHandler::addDistrictEdge(), NLBuilder::EdgeFloatTimeLineRetriever_EdgeEffort::addEdgeWeight(), NLBuilder::EdgeFloatTimeLineRetriever_EdgeTravelTime::addEdgeWeight(), NLHandler::addRoundabout(), MEVehicle::addStop(), NLEdgeControlBuilder::beginEdgeParsing(), NLTriggerBuilder::buildVaporizer(), NLHandler::closeEdge(), TraCIServerAPI_Simulation::convertCartesianToRoadMap(), NLDetectorBuilder::getEdgeChecking(), TraCIServerAPI_Simulation::getLaneChecking(), TraCIServerAPI_Edge::getShape(), MSPedestrianPushButton::loadPushButtons(), NLHandler::myEndElement(), MSRouteHandler::myStartElement(), MSTriggeredRerouter::myStartElement(), NLTriggerBuilder::parseAndBuildRerouter(), MSEdge::parseEdgesList(), MSRouteHandler::parseFromViaTo(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_Route::processSet(), TraCIServerAPI_Vehicle::processSet(), MSBaseVehicle::reroute(), MSEdge::unlock(), and TraCIServerAPI_Vehicle::vtdMap().
MSEdge * MSEdge::dictionary (const std::string & id) static inherited
Returns the MSEdge associated to the key id if exists, otherwise returns 0.
Definition at line 682 of file MSEdge.cpp.
References MSEdge::myDict.
int MSEdge::dictSize () static inherited
Returns the number of edges.
Definition at line 693 of file MSEdge.cpp.
References MSEdge::myDict.
Referenced by fill(), MSStateHandler::saveState(), and MSEdge::unlock().
void GUIEdge::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 230 of file GUIEdge.cpp.
References Position::add(), GUIVisualizationTextSettings::color, GUIVisualizationSettings::containerSize, GUIVisualizationSettings::cwaEdgeName, GUIContainer::drawGL(), GUIPerson::drawGL(), GUILane::drawGL(), drawMesoVehicles(), GUIGlObject::drawName(), GLHelper::drawText(), MSEdge::EDGEFUNCTION_CONNECTOR, MSEdge::EDGEFUNCTION_CROSSING, MSEdge::EDGEFUNCTION_INTERNAL, MSEdge::EDGEFUNCTION_NORMAL, MSEdge::EDGEFUNCTION_WALKINGAREA, GUIVisualizationSettings::edgeName, GUIVisualizationSizeSettings::getExaggeration(), GUIGlObject::getGlID(), GUILane::getShape(), MSEdge::getStreetName(), GLO_MAX, MSGlobals::gUseMesoSim, GUIVisualizationSettings::hideConnectors, GUIVisualizationSettings::internalEdgeName, PositionVector::length(), MFXMutex::lock(), GUIVisualizationSizeSettings::minSize, Position::mul(), MSEdge::myContainers, MSEdge::myFunction, MSEdge::myLanes, myLock, MSEdge::myPersons, MSEdge::myStreetName, GUIVisualizationSettings::personSize, PositionVector::positionAtOffset(), PositionVector::rotationDegreeAtOffset(), GUIVisualizationSettings::scale, setColor(), GUIVisualizationTextSettings::show, GUIVisualizationTextSettings::size, GUIVisualizationSettings::streetName, SUMOReal, MFXMutex::unlock(), and GUIVisualizationSettings::vehicleSize.
void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIBaseVehicle, GUIPerson, and GUIContainer.
Definition at line 156 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
void GUIEdge::drawMesoVehicles (const GUIVisualizationSettings & s) const
Definition at line 303 of file GUIEdge.cpp.
References GUIBaseVehicle::drawOnPos(), MSLane::geometryPositionAtOffset(), GUINet::getGUIInstance(), GUINet::getGUIMEVehicleControl(), MSVehicleType::getLengthWithGap(), GUILane::getShape(), MSBaseVehicle::getVehicleType(), MSGlobals::gMesoNet, MSLane::interpolateLanePosToGeometryPos(), MSEdge::myLanes, myLock, GUIMEVehicleControl::releaseVehicles(), PositionVector::rotationAtOffset(), GUIMEVehicleControl::secureVehicles(), and SUMOReal.
Referenced by drawGL(), and removeContainer().
void GUIGlObject::drawName (const Position & pos, const SUMOReal scale, const GUIVisualizationTextSettings & settings, const SUMOReal angle = 0) const inherited
draw name of item
Definition at line 286 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE3::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GUIPolygon::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GNERouteProbe::drawGL(), GNEEdge::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), drawGL(), GUIInductLoop::MyWrapper::drawGL(), GNERerouter::drawGL(), and GUIBaseVehicle::drawOnPos().
void GUIEdge::fill (std::vector< GUIEdge * > & netsWrappers) static
Definition at line 158 of file GUIEdge.cpp.
References MSEdge::dictSize(), MSEdge::EDGEFUNCTION_DISTRICT, and MSEdge::myDict.
Referenced by GUINet::initGUIStructures().
const MSEdgeVector & MSEdge::getAllEdges () static inherited
Returns all edges with a numerical id.
Definition at line 699 of file MSEdge.cpp.
References MSEdge::myEdges.
Referenced by MSNet::getRouterEffort(), MSDevice_Routing::getRouterTT(), MSNet::getRouterTT(), MSPModel_Striping::initWalkingAreaPaths(), MSPedestrianPushButton::loadCrossingEdgeMap(), MSStateHandler::myStartElement(), GUIApplicationWindow::onCmdEditChosen(), MSDevice_Routing::reroute(), MSStateHandler::saveState(), and MSEdge::unlock().
const std::vector< MSLane * > * MSEdge::getAllowedLanesWithDefault (const AllowedLanesCont & c, const MSEdge * dest) const protected inherited
lookup in map and return 0 if not found
Definition at line 313 of file MSEdge.cpp.
Referenced by MSEdge::allowedLanes().
SUMOReal GUIEdge::getAllowedSpeed () const
Definition at line 397 of file GUIEdge.cpp.
References MSEdge::myLanes, and SUMOReal.
Referenced by getColorValue(), getParameterWindow(), getRelativeSpeed(), getScaleValue(), removeContainer(), and setMultiColor().
Boundary GUIEdge::getBoundary () const
Returns the street's geometry.
Definition at line 130 of file GUIEdge.cpp.
References Boundary::add(), MSEdge::EDGEFUNCTION_DISTRICT, MSEdge::getPurpose(), Boundary::grow(), MSEdge::myLanes, MSEdge::myPredecessors, and MSEdge::mySuccessors.
Referenced by getCenteringBoundary().
SUMOReal GUIEdge::getBruttoOccupancy () const
Definition at line 387 of file GUIEdge.cpp.
References MSGlobals::gMesoNet, MSEdge::myLanes, and SUMOReal.
Referenced by getColorValue(), getParameterWindow(), getScaleValue(), and removeContainer().
Boundary GUIEdge::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 220 of file GUIEdge.cpp.
References getBoundary(), and Boundary::grow().
SUMOReal GUIEdge::getColorValue (int activeScheme) const
gets the color value according to the current scheme index
Definition at line 481 of file GUIEdge.cpp.
References getAllowedSpeed(), getBruttoOccupancy(), getFlow(), GUIGlObject::getGlID(), MSNet::getInsertionControl(), MSNet::getInstance(), MSEdge::getLanes(), MSEdge::getMeanSpeed(), MSInsertionControl::getPendingEmits(), MSEdge::getPurpose(), getRelativeSpeed(), MSEdge::getRoutingSpeed(), GUIGlObject::getType(), gSelected, GUISelectedStorage::isSelected(), and SUMOReal.
Referenced by removeContainer(), and setColor().
const std::vector<std::string>& MSEdge::getCrossingEdges () const inline inherited
Gets the crossed edge ids.
Returns
The list of crossed edge ids in a crossing edge or an empty vector
Definition at line 306 of file MSEdge.h.
References MSEdge::myCrossingEdges.
Referenced by MSPedestrianPushButton::loadCrossingEdgeMap().
SUMOReal MSEdge::getCurrentTravelTime (const SUMOReal minSpeed = NUMERICAL_EPS) const inherited
Computes and returns the current travel time for this edge.
The mean speed of all lanes is used to compute the travel time. To avoid infinite travel times, the given minimum speed is used.
Parameters
[in] minSpeed The minimumSpeed to assume if traffic on this edge is stopped
Returns
The current effort (travel time) to pass the edge
Definition at line 649 of file MSEdge.cpp.
References MSEdge::getLength(), MSEdge::getMeanSpeed(), MAX2(), MSEdge::myAmDelayed, MSEdge::myEmptyTraveltime, and SUMOReal.
Referenced by MSVehicleTransfer::add(), MSVehicleTransfer::checkInsertions(), MSEdge::isVaporizing(), TraCIServerAPI_Edge::processGet(), and MSFullExport::writeEdge().
MSLane * MSEdge::getDepartLane (MSVehicle & veh) const inherited
Finds a depart lane for the given vehicle parameters.
Depending on the depart lane procedure a depart lane is chosen. Repeated calls with the same vehicle may return different results if the procedure is "random" or "free". In case no appropriate lane was found, 0 is returned.
Parameters
[in] veh The vehicle to get the depart lane for
Returns
a possible/chosen depart lane, 0 if no lane can be used
Definition at line 418 of file MSEdge.cpp.
References MSEdge::allowedLanes(), MSRoute::begin(), DEPART_LANE_ALLOWED_FREE, DEPART_LANE_BEST_FREE, DEPART_LANE_DEFAULT, DEPART_LANE_FIRST_ALLOWED, DEPART_LANE_FREE, DEPART_LANE_GIVEN, DEPART_LANE_RANDOM, SUMOVehicleParameter::departLane, SUMOVehicleParameter::departLaneProcedure, MSVehicle::getBestLanes(), MSEdge::getFreeLane(), MSBaseVehicle::getParameter(), RandHelper::getRandomFrom(), MSBaseVehicle::getRoute(), MSVehicleType::getVehicleClass(), MSBaseVehicle::getVehicleType(), MSEdge::myLanes, MSRoute::size(), SUMOReal, and MSVehicle::updateBestLanes().
Referenced by MSEdge::getTravelTimeStatic(), and MSEdge::insertVehicle().
SUMOReal MSEdge::getDistanceTo (const MSEdge * other) const inherited
optimistic air distance heuristic for use in routing
Parameters
[in] other The edge to which the distance shall be returned
Returns
The distance to the other edge
Definition at line 752 of file MSEdge.cpp.
References Position::distanceTo2D(), MSEdge::getFromJunction(), MSEdge::getLanes(), MSJunction::getPosition(), MSEdge::getToJunction(), and SUMOReal.
Referenced by MSEdge::getSubLaneSides().
const std::string& MSEdge::getEdgeType () const inline inherited
Returns the type of the edge.
Definition at line 284 of file MSEdge.h.
References MSEdge::myEdgeType.
Referenced by GUILane::getParameterWindow(), and MSLane::MSLane().
SUMOReal GUIEdge::getFlow () const
return flow based on meanSpead
Note
: may produced incorrect results when jammed
Definition at line 377 of file GUIEdge.cpp.
References MSGlobals::gMesoNet, and SUMOReal.
Referenced by getColorValue(), getParameterWindow(), getScaleValue(), and removeContainer().
MSLane * MSEdge::getFreeLane (const std::vector< MSLane * > * allowed, const SUMOVehicleClass vclass) const inherited
Finds the emptiest lane allowing the vehicle class.
The emptiest lane is the one with the fewest vehicles on. If there is more than one, the first according to its index in the lane container is chosen.
If allowed==0, the lanes allowed for the given vehicle class will be used.
Parameters
[in] allowed The lanes to choose from
[in] vclass The vehicle class to look for
Returns
the least occupied lane
See also
allowedLanes
Definition at line 398 of file MSEdge.cpp.
References MSEdge::allowedLanes(), max, and SUMOReal.
Referenced by MSVehicleTransfer::checkInsertions(), MSEdge::getDepartLane(), and MSEdge::getTravelTimeStatic().
const MSJunction* MSEdge::getFromJunction () const inline inherited
Definition at line 379 of file MSEdge.h.
References MSEdge::myFromJunction.
Referenced by MSPModel::canTraverse(), MSPModel_NonInteracting::PState::computeWalkingTime(), MSEdge::getDistanceTo(), MSPModel_Striping::getNextLane(), MSPModel_Striping::PState::PState(), and MSLink::setRequestInformation().
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 111 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 123 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GUIVehicle::drawAction_drawPersonsAndContainers(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE3::drawGL(), GNEInternalLane::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GNERouteProbe::drawGL(), GNELane::drawGL(), GNEEdge::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), drawGL(), GNEConnection::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GNERerouter::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GUILane::drawLinkRule(), GUIBaseVehicle::drawOnPos(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), getColorValue(), GUIContainer::getColorValue(), GNEJunction::getColorValue(), GUIPerson::getColorValue(), GNELane::getColorValue(), GUILane::getColorValue(), getIDs(), GNEEdge::getLaneGlIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), getScaleValue(), GUILane::getScaleValue(), GNECalibrator::GNECalibrator(), GNERouteProbe::GNERouteProbe(), GNEVaporizer::GNEVaporizer(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onLeftBtnPress(), GUISUMOAbstractView::removeAdditionalGLVisualisation(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUIVehicle::selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), and GUIGlObject::~GUIGlObject().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciBusOrContainerStop(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNEConnectorFrame::buildIinternalLanes(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), NLDetectorBuilder::convUncontE2PosLength(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSVehicle::getBackPosition(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), GNEEdge::getDest(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), MSE2Collector::getEstimateQueueLength(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), GNEEdge::getSource(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSDevice_BTsender::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSE2Collector::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_SL2015::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_LC2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_ArealDetector::processGet(), TraCIServerAPI_Lane::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), MSBaseVehicle::reroute(), MSLane::resetPartialOccupation(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), MSLane::saveState(), MSDevice_Battery::setAirDragCoefficient(), NBNodeCont::setAsTLControlled(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), MSDevice_Battery::setConstantPowerIntake(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), MSDevice_Battery::setFrontSurfaceArea(), MSDevice_Battery::setInternalMomentOfInertia(), GNEJunction::setLogicValid(), MSDevice_Battery::setMass(), MSDevice_Battery::setMaximumBatteryCapacity(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSDevice_Battery::setPropulsionEfficiency(), MSDevice_Battery::setRadialDragCoefficient(), MSDevice_Battery::setRecuperationEfficiency(), MSLink::setRequestInformation(), MSDevice_Battery::setRollDragCoefficient(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
std::vector< GUIGlID > GUIEdge::getIDs (bool includeInternal) static
Definition at line 101 of file GUIEdge.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, GUIGlObject::getGlID(), MSEdge::getPurpose(), MSEdge::myDict, and SUMOReal.
Referenced by GUINet::getParameterWindow(), and GUISUMOViewParent::onCmdLocate().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), operator<<(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
const MSEdgeVector& MSEdge::getIncomingEdges () const inline inherited
Returns the list of edges from which this edge may be reached.
Returns
Edges from which this edge may be reached
Definition at line 328 of file MSEdge.h.
References MSEdge::myPredecessors.
Referenced by NLEdgeControlBuilder::build(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSLane::getLogicalPredecessorLane(), getWalkingAreas(), and MSPModel_Striping::initWalkingAreaPaths().
MSLane & GUIEdge::getLane (int laneNo)
returns the enumerated lane (!!! why not private with a friend?)
Definition at line 94 of file GUIEdge.cpp.
References MSEdge::myLanes.
static std::pair<SUMOReal, SUMOReal> GUIEdge::getLaneOffsets (SUMOReal x1, SUMOReal y1, SUMOReal x2, SUMOReal y2, SUMOReal prev, SUMOReal wanted) static
returns the position on the line given by the coordinates where "prev" is the length of the line and "wanted" the distance from the begin !!! should be within another class
const std::vector<MSLane*>& MSEdge::getLanes () const inline inherited
Returns this edge's lanes.
Returns
This edge's lanes
Definition at line 192 of file MSEdge.h.
References MSEdge::myLanes.
Referenced by MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSVehicleTransfer::add(), NLHandler::addConnection(), addRerouter(), MSRouteHandler::addStop(), MELoop::buildSegmentsFor(), MSBaseVehicle::calculateArrivalParams(), MSEdgeControl::changeLanes(), MSVehicleTransfer::checkInsertions(), closeTraffic(), MSRouteHandler::closeVehicle(), MSLCM_SL2015::computeSublaneShift(), CState::computeTranshipTime(), GUILane::drawMarkings(), MS_E2_ZS_CollectorOverLanes::extendTo(), TraCIServerAPI_Vehicle::findCloserLane(), MEVehicle::getAngle(), getColorValue(), MSEdge::getDistanceTo(), MSTransportable::Stage::getEdgeAngle(), GUILane::getEdgeLaneNumber(), MSTransportable::Stage::getEdgePosition(), TraCIServerAPI_Simulation::getLaneChecking(), MSVehicle::getLaneIndex(), MESegment::getLink(), MSInsertionControl::getPendingEmits(), getPopUpMenu(), MEVehicle::getPosition(), GUIContainer::getPosition(), MSVehicle::getPosition(), getScaleValue(), getSegmentAtPosition(), TraCIServerAPI_Edge::getShape(), MEVehicle::getSlope(), MSEdge::getSpeedLimit(), getTotalLength(), MSEdge::getVehicleMaxSpeed(), GUICalibrator::GUICalibrator(), GUITriggeredRerouter::GUITriggeredRerouterEdge::GUITriggeredRerouterEdge(), MSVehicle::Influencer::influenceChangeDecision(), GUINet::initGUIStructures(), MSCalibrator::invalidJam(), MSPedestrianPushButton::isActiveForEdge(), GUISUMOViewParent::isSelected(), MESegment::MESegment(), MSCalibrator::MSCalibrator(), MSRouteProbe::MSRouteProbe(), GUIMEInductLoop::MyWrapper::MyWrapper(), MSLCM_DK2008::patchSpeed(), MSLCM_SL2015::prepareStep(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_Vehicle::processSet(), MSCalibrator::remainingVehicleCapacity(), setFunctionalColor(), MSVehicle::updateBestLanes(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), TraCIServerAPI_Vehicle::vtdMap(), MSQueueExport::writeEdge(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), MSMeanData::writeEdge(), MSFCDExport::writeTransportable(), and MEInductLoop::writeXMLOutput().
SUMOTime MSEdge::getLastFailedInsertionTime () const inline inherited
Returns the last time a vehicle could not be inserted.
Returns
The current value
Definition at line 524 of file MSEdge.h.
References MSEdge::myLastFailedInsertionTime.
Referenced by MSInsertionControl::checkCandidates().
SUMOReal MSEdge::getLength () const inline inherited
return the length of the edge
Returns
The edge's length
Definition at line 585 of file MSEdge.h.
References MSEdge::getSpeedLimit(), MSEdge::getVehicleMaxSpeed(), MSEdge::myLength, MSEdge::setMaxSpeed(), and SUMOReal.
Referenced by NLTriggerBuilder::buildCalibrator(), MELoop::buildSegmentsFor(), MSDevice_Tripinfo::computeLengthAndDuration(), MSPModel_NonInteracting::PState::computeWalkingTime(), MSDevice_Routing::getAssumedSpeed(), MSEdge::getCurrentTravelTime(), MSRoute::getDistanceBetween(), MSTransportable::Stage_Driving::getEdgePos(), MSDevice_Routing::getEffort(), MSEdge::getMeanSpeed(), MSEdge::getMinimumTravelTime(), MSPModel_Striping::getNextLane(), getParameterWindow(), getTotalLength(), MSEdge::insertVehicle(), MSCalibrator::MSCalibrator(), MSRouteHandler::parseWalkPos(), MSCalibrator::remainingVehicleCapacity(), MELoop::teleportVehicle(), MSVehicle::updateBestLanes(), TraCIServerAPI_Vehicle::vtdMap(), and MSMeanData::writeEdge().
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 107 of file Parameterised.h.
References Parameterised::myMap.
Referenced by NBTrafficLightDefinition::compute(), MSDevice_Vehroutes::generateOutput(), GUIPerson::getParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), TraCIServerAPI_TLS::processGet(), ROVehicle::saveAsXML(), ROPerson::saveAsXML(), SUMOVTypeParameter::write(), PointOfInterest::writeXML(), and SUMO::Polygon::writeXML().
SUMOReal MSEdge::getMeanSpeed () const inherited
get the mean speed
Definition at line 622 of file MSEdge.cpp.
References MSEdge::getLength(), MSEdge::getSpeedLimit(), MSGlobals::gMesoNet, MSGlobals::gUseMesoSim, MSEdge::myEmptyTraveltime, MSEdge::myLanes, and SUMOReal.
Referenced by getColorValue(), MSEdge::getCurrentTravelTime(), getParameterWindow(), getRelativeSpeed(), getScaleValue(), MSEdge::hasLaneChanger(), and TraCIServerAPI_Edge::processGet().
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 137 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNEPOI::getAttribute(), GNECrossing::getAttribute(), GNEJunction::getAttribute(), GNEPoly::getAttribute(), GNEEdge::getAttribute(), GNELane::getAttribute(), GNELane::getParentName(), GNENetElement::getParentName(), GNEDetectorE3::getParentName(), GNEVaporizer::getParentName(), GNEVariableSpeedSignal::getParentName(), GNERouteProbe::getParentName(), GNEStoppingPlace::getParentName(), GNECalibrator::getParentName(), GNEDetector::getParentName(), GNEAdditional::getParentName(), GNERerouter::getParentName(), GNEAdditional::getPopUpMenu(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GNEEdge::moveGeometry(), GNEPoly::moveGeometry(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEViewNet::onCmdNodeShape(), GNEViewNet::onLeftBtnPress(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNENet::replaceJunctionByGeometry(), GNENet::retrieveAttributeCarriers(), GNEAdditional::setAdditionalID(), GNEEdge::setAttribute(), GNENet::splitEdge(), and GNEConnectorFrame::updateDescription().
SUMOReal MSEdge::getMinimumTravelTime (const SUMOVehicle *const veh) const inline inherited
returns the minimum travel time for the given vehicle
Definition at line 444 of file MSEdge.h.
References MSEdge::getLength(), MSEdge::getSpeedLimit(), and MSEdge::getVehicleMaxSpeed().
Referenced by MSDevice_Routing::getEffort(), and MSNet::getTravelTime().
int MSEdge::getNumericalID () const inline inherited
Returns the numerical id of the edge.
Returns
This edge's numerical id
Definition at line 271 of file MSEdge.h.
References MSEdge::myNumericalID.
Referenced by MELoop::buildSegmentsFor(), MSEdgeControl::changeLanes(), MELoop::changeSegment(), MSEdge::dictionary(), MSMeanData_Amitran::getEdgeID(), MSDevice_Routing::getEffort(), MELoop::getSegmentForEdge(), MSStateHandler::myStartElement(), and MELoop::nextSegment().
int MSEdge::getNumPredecessors () const inline inherited
Returns the number of edges this edge is connected to.
Returns
The number of edges following this edge
Definition at line 365 of file MSEdge.h.
References MSEdge::myPredecessors.
Referenced by MSRouteHandler::parseFromViaTo().
int MSEdge::getNumSuccessors () const inline inherited
Returns the number of edges that may be reached from this edge.
Returns
The number of following edges
Definition at line 342 of file MSEdge.h.
References MSEdge::mySuccessors.
Referenced by NLEdgeControlBuilder::build(), MESegment::MESegment(), and MSRouteHandler::parseFromViaTo().
const std::vector<MSEdge*>& MSEdge::getOutgoingEdges () const inline inherited
Returns the list of edges that may be reached from this edge.
Returns
Edges that may be reached from this edge
Definition at line 335 of file MSEdge.h.
References MSEdge::mySuccessors.
Referenced by getWalkingAreas().
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 81 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), MSSOTLPolicyDesirability::readParameter(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), and TraCIServerAPI_Vehicle::vtdMap().
GUIParameterTableWindow * GUIEdge::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 188 of file GUIEdge.cpp.
References GUIParameterTableWindow::closeBuilding(), getAllowedSpeed(), getBruttoOccupancy(), MESegment::getCarNumber(), MESegment::getEdge(), MESegment::getEventTimeSeconds(), getFlow(), MESegment::getFlow(), MESegment::getIndex(), MESegment::getLength(), MSEdge::getLength(), MESegment::getMeanSpeed(), MSEdge::getMeanSpeed(), GUISUMOAbstractView::getPositionInformation(), MESegment::getRelativeJamThreshold(), MESegment::getRelativeOccupancy(), MSEdge::getRoutingSpeed(), getSegmentAtPosition(), MSEdge::getSpeedLimit(), getVehicleIDs(), getVehicleNo(), GUIParameterTableWindow::mkItem(), and MSEdge::myLanes.
const std::string & GUIGlObject::getParentName () const virtual inherited
Returns the name of the parent object (if any)
Returns
This object's parent id
Reimplemented in GNERerouter, GNEAdditional, GNEAdditionalSet, GNEDetector, GNECalibrator, GNEStoppingPlace, GNERouteProbe, GNEVariableSpeedSignal, GNEVaporizer, GUILane, GNEDetectorE3, GNENetElement, and GNELane.
Definition at line 117 of file GUIGlObject.cpp.
References StringUtils::emptyString.
Referenced by GUIGLObjectPopupMenu::onCmdCopyEdgeName().
SVCPermissions MSEdge::getPermissions () const inline inherited
Definition at line 556 of file MSEdge.h.
References MSEdge::myCombinedPermissions.
Referenced by getWalking(), and MSPedestrianPushButton::MSPedestrianPushButton().
const std::set<MSTransportable*>& MSEdge::getPersons () const inline inherited
Returns this edge's persons set.
Avoids the creation of new vector as in getSortedPersons
Returns
This edge's persons.
Definition at line 201 of file MSEdge.h.
References MSEdge::allowedLanes(), MSEdge::getSortedContainers(), MSEdge::getSortedPersons(), MSEdge::myPersons, and SVC_IGNORING.
Referenced by MSPedestrianPushButton::isActiveForEdge().
GUIGLObjectPopupMenu * GUIEdge::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 171 of file GUIEdge.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), GUIGlObject::buildShowParamsPopupEntry(), MSEdge::getLanes(), GUISUMOAbstractView::getPositionInformation(), MSGlobals::gUseMesoSim, SUMOReal, and toString().
const MSEdgeVector& MSEdge::getPredecessors () const inline inherited
Returns the edge at the given position from the list of reachable edges.
Parameters
[in] pos The position of the list within the list of approached
Returns
The following edge, stored at position pos
Definition at line 374 of file MSEdge.h.
References MSEdge::myPredecessors.
Referenced by MSPedestrianPushButton::isActiveForEdge().
int MSEdge::getPriority () const inline inherited
Returns the priority of the edge.
Definition at line 290 of file MSEdge.h.
References MSEdge::myPriority.
Referenced by GUILane::getColorValue(), GUILane::getParameterWindow(), and GUILane::getScaleValue().
EdgeBasicFunction MSEdge::getPurpose () const inline inherited
Returns the edge type (EdgeBasicFunction)
Returns
This edge's EdgeBasicFunction
See also
EdgeBasicFunction
Definition at line 249 of file MSEdge.h.
References MSEdge::myFunction.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLane::addApproachingLane(), MSLane::appropriate(), MSVehicle::checkRewindLinkLanes(), MSDevice_Routing::cleanup(), GUILane::drawGL(), MSVehicle::enterLaneAtMove(), MSVehicle::getBestLanesContinuation(), getBoundary(), getColorValue(), getIDs(), MSLane::getInternalFollower(), getTotalLength(), MSEdge::insertVehicle(), MSLink::lastWasContMajor(), MSPModel_Striping::PState::moveToNextLane(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSDevice_Routing::preInsertionReroute(), MSLane::succLinkSec(), MSVehicle::updateBestLanes(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), and MSLink::writeApproaching().
SUMOReal GUIEdge::getRelativeSpeed () const
return meanSpead divided by allowedSpeed
Definition at line 403 of file GUIEdge.cpp.
References getAllowedSpeed(), and MSEdge::getMeanSpeed().
Referenced by getColorValue(), getScaleValue(), and removeContainer().
SUMOReal MSEdge::getRoutingSpeed () const inherited
Returns the averaged speed used by the routing device.
Definition at line 659 of file MSEdge.cpp.
References MSDevice_Routing::getAssumedSpeed().
Referenced by getColorValue(), GUILane::getColorValue(), getParameterWindow(), GUILane::getParameterWindow(), and MSEdge::getTravelTimeStatic().
SUMOReal GUIEdge::getScaleValue (int activeScheme) const
gets the scaling value according to the current scheme index
Definition at line 507 of file GUIEdge.cpp.
References getAllowedSpeed(), getBruttoOccupancy(), getFlow(), GUIGlObject::getGlID(), MSNet::getInsertionControl(), MSNet::getInstance(), MSEdge::getLanes(), MSEdge::getMeanSpeed(), MSInsertionControl::getPendingEmits(), getRelativeSpeed(), GUIGlObject::getType(), gSelected, and GUISelectedStorage::isSelected().
Referenced by GUILane::drawGL(), and removeContainer().
MESegment * GUIEdge::getSegmentAtPosition (const Position & pos)
returns the segment closest to the given position
Definition at line 529 of file GUIEdge.cpp.
References MSEdge::getLanes(), MELoop::getSegmentForEdge(), MSGlobals::gMesoNet, PositionVector::nearest_offset_to_point2D(), and SUMOReal.
Referenced by getParameterWindow(), and removeContainer().
const std::vector<RGBColor>& GUIEdge::getSegmentColors () const inline
return segment colors (meso)
Definition at line 213 of file GUIEdge.h.
References mySegmentColors.
std::vector< MSTransportable * > MSEdge::getSortedContainers (SUMOTime timestep) const inherited
Returns this edge's containers sorted by pos.
Returns
This edge's containers sorted by pos
Definition at line 795 of file MSEdge.cpp.
References MSEdge::myContainers.
Referenced by MSEdge::getPersons(), and MSXMLRawOut::writeEdge().
std::vector< MSTransportable * > MSEdge::getSortedPersons (SUMOTime timestep) const inherited
Returns this edge's persons sorted by pos.
Returns
This edge's persons sorted by pos
Definition at line 787 of file MSEdge.cpp.
References MSEdge::myPersons.
Referenced by MSEdge::getPersons(), TraCIServerAPI_Edge::processGet(), and MSXMLRawOut::writeEdge().
SUMOReal MSEdge::getSpeedLimit () const inherited
Returns the speed limit of the edge The speed limit of the first lane is retured; should probably be the fastest edge.
Returns
The maximum speed allowed on this edge
Definition at line 762 of file MSEdge.cpp.
References MSEdge::getLanes(), and SUMOReal.
Referenced by GUIApplicationWindow::checkGamingEvents(), METriggeredCalibrator::execute(), MSEdge::getLength(), MESegment::getMeanSpeed(), MSEdge::getMeanSpeed(), MSEdge::getMinimumTravelTime(), MESegment::getNextInsertionTime(), getParameterWindow(), MSEdge::insertVehicle(), METriggeredCalibrator::invalidJam(), MSCalibrator::invalidJam(), MSEdge::recalcCache(), MESegment::recomputeJamThreshold(), MSCalibrator::remainingVehicleCapacity(), MELoop::teleportVehicle(), and MSMeanData::writeEdge().
const std::string& MSEdge::getStreetName () const inline inherited
Returns the street name of the edge.
Definition at line 278 of file MSEdge.h.
References MSEdge::myStreetName.
Referenced by drawGL(), and GUILane::getParameterWindow().
const std::vector<SUMOReal> MSEdge::getSubLaneSides () const inline inherited
Returns the right side offsets of this edge's sublanes.
Definition at line 568 of file MSEdge.h.
References MSEdge::getDistanceTo(), MSEdge::mySublaneSides, MSEdge::rebuildAllowedLanes(), and SUMOReal.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), and MSLCM_SL2015::prepareStep().
const MSEdgeVector& MSEdge::getSuccessors () const inline inherited
Returns the following edges.
Definition at line 349 of file MSEdge.h.
References MSEdge::mySuccessors.
Referenced by NLEdgeControlBuilder::build(), MSLane::getInternalFollower(), MSPModel_Striping::initWalkingAreaPaths(), MSPedestrianPushButton::isActiveForEdge(), MESegment::MESegment(), and TraCIServerAPI_Vehicle::vtdMap().
const MSEdgeVector & MSEdge::getSuccessors (SUMOVehicleClass vClass) const inherited
Returns the following edges, restricted by vClass.
Parameters
[in] vClass The vClass for which to restrict the successors
Returns
The eligible following edges
Definition at line 813 of file MSEdge.cpp.
References MSEdge::allowedLanes(), MSEdge::EDGEFUNCTION_DISTRICT, MSNet::getInstance(), MSEdge::myClassesSuccessorMap, MSEdge::myFunction, MSEdge::mySuccessors, and SVC_IGNORING.
const MSJunction* MSEdge::getToJunction () const inline inherited
Definition at line 383 of file MSEdge.h.
References MSEdge::myToJunction.
Referenced by MSPModel::canTraverse(), MSPModel_NonInteracting::PState::computeWalkingTime(), MSEdge::getDistanceTo(), MSPModel_Striping::getNextLane(), MSRailSignal::init(), MSJunction::isLeader(), and MSPModel_Striping::PState::PState().
SUMOReal GUIEdge::getTotalLength (bool includeInternal, bool eachLane) static
Definition at line 116 of file GUIEdge.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSEdge::getLanes(), MSEdge::getLength(), MSEdge::getPurpose(), MSEdge::myDict, and SUMOReal.
Referenced by GUINet::getParameterWindow().
static SUMOReal MSEdge::getTravelTimeStatic (const MSEdge *const edge, const SUMOVehicle *const veh, SUMOReal time) inline static inherited
Returns the travel time for the given edge.
Parameters
[in] edge The edge for which the travel time shall be retrieved
[in] veh The vehicle for which the travel time on this edge shall be retrieved
[in] time The time for which the travel time shall be returned [s]
Returns
The traveltime needed by the given vehicle to pass the edge at the given time
Definition at line 460 of file MSEdge.h.
References MSEdge::getDepartLane(), MSEdge::getFreeLane(), MSNet::getInstance(), MSEdge::getRoutingSpeed(), MSNet::getTravelTime(), MSEdge::insertVehicle(), and SUMOReal.
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 150 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEAdditionalSet::drawConnections(), GNEDetector::drawDetectorIcon(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE3::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GNELane::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), GUILane::drawGL(), GNERerouter::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorE2::getAttribute(), GNEContainerStop::getAttribute(), GNEBusStop::getAttribute(), GNEDetectorE3::getAttribute(), GNEVaporizer::getAttribute(), GNEVariableSpeedSignal::getAttribute(), GNERouteProbe::getAttribute(), GNEChargingStation::getAttribute(), GNECalibrator::getAttribute(), GNERerouter::getAttribute(), GUIJunctionWrapper::getColorValue(), getColorValue(), GNEJunction::getColorValue(), GNELane::getColorValue(), GUILane::getColorValue(), GNEViewNet::getEdgeAtCursorPosition(), GNEViewNet::getEdgesAtCursorPosition(), GNEViewNet::getJunctionAtCursorPosition(), GNEViewNet::getLaneAtCurserPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), getScaleValue(), GUILane::getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEDetectorE1::isValid(), GNEDetectorE2::isValid(), GNEContainerStop::isValid(), GNEBusStop::isValid(), GNEDetectorE3::isValid(), GNEVaporizer::isValid(), GNEVariableSpeedSignal::isValid(), GNERouteProbe::isValid(), GNEChargingStation::isValid(), GNECalibrator::isValid(), GNERerouter::isValid(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onDoubleClicked(), GNEViewNet::onLeftBtnPress(), LayeredRTree::selectLayer(), GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEDetectorE1::setAttribute(), GNEDetectorE2::setAttribute(), GNEBusStop::setAttribute(), GNEContainerStop::setAttribute(), GNEDetectorE3::setAttribute(), GNEVaporizer::setAttribute(), GNEVariableSpeedSignal::setAttribute(), GNERouteProbe::setAttribute(), GNEChargingStation::setAttribute(), GNECalibrator::setAttribute(), GNERerouter::setAttribute(), GNEJunction::setColor(), and GUISelectedStorage::toggleSelection().
GUIParameterTableWindow * GUIGlObject::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own type parameter window (optional)
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Reimplemented in GUIVehicle, GUIBaseVehicle, and GUIMEVehicle.
Definition at line 129 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
Referenced by GUIGLObjectPopupMenu::onCmdShowTypePars().
std::string GUIEdge::getVehicleIDs () const
Definition at line 362 of file GUIEdge.cpp.
References MSGlobals::gMesoNet, and SUMOReal.
Referenced by getParameterWindow(), and removeContainer().
SUMOReal MSEdge::getVehicleMaxSpeed (const SUMOVehicle *const veh) const inherited
Returns the maximum speed the vehicle may use on this edge.
Only the first lane is considered
Returns
The maximum velocity on this edge for the given vehicle
Definition at line 769 of file MSEdge.cpp.
References MSEdge::getLanes().
Referenced by GUIMEVehicle::getColorValue(), MSEdge::getLength(), MSEdge::getMinimumTravelTime(), MSEdge::insertVehicle(), MSDevice_Tripinfo::notifyMove(), MSDevice_Tripinfo::notifyMoveInternal(), and MESegment::receive().
int GUIEdge::getVehicleNo () const
Definition at line 352 of file GUIEdge.cpp.
References MSGlobals::gMesoNet.
Referenced by getParameterWindow(), and removeContainer().
SUMOReal MSEdge::getWidth () const inline inherited
Returns the edges's width (sum over all lanes)
Returns
This edges's width
Definition at line 563 of file MSEdge.h.
References MSEdge::myWidth.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSLCM_SL2015::checkBlocking(), and MSLCM_SL2015::keepLatGap().
bool MSEdge::hasLaneChanger () const inline inherited
Definition at line 644 of file MSEdge.h.
References MSEdge::canChangeToOpposite(), MSEdge::getMeanSpeed(), MSEdge::myLaneChanger, and SUMOReal.
Referenced by MSLCM_JE2013::_patchSpeed().
SUMOTime MSEdge::incVaporization (SUMOTime t) inherited
Enables vaporization.
The internal vaporization counter is increased enabling the vaporization. Called from the event handler.
Parameters
[in] t The current time (unused)
Returns
Time to next call (always 0)
Exceptions
ProcessError not thrown by this method, just derived
Definition at line 384 of file MSEdge.cpp.
References MSEdge::myVaporizationRequests.
Referenced by NLTriggerBuilder::buildVaporizer(), and MSEdge::isVaporizing().
void MSEdge::initialize (const std::vector< MSLane * > * lanes) inherited
Initialize the edge.
Parameters
[in] allowed Information which edges may be reached from which lanes
[in] lanes List of this edge's lanes
Definition at line 110 of file MSEdge.cpp.
References MSEdge::EDGEFUNCTION_DISTRICT, MSGlobals::gLaneChangeDuration, MSGlobals::gLateralResolution, MSEdge::myCombinedPermissions, MSEdge::myFunction, MSEdge::myLanes, MSEdge::mySublaneSides, MSEdge::myWidth, MSLeaderInfo::numSublanes(), MSEdge::recalcCache(), SUMOReal, and SVCAll.
Referenced by NLHandler::addDistrict(), and NLEdgeControlBuilder::closeEdge().
void MSEdge::insertIDs (std::vector< std::string > & into) static inherited
Inserts IDs of all known edges into the given vector.
Definition at line 714 of file MSEdge.cpp.
References MSEdge::myDict.
Referenced by TraCIServerAPI_Edge::processGet(), and MSEdge::unlock().
bool MSEdge::insertVehicle (SUMOVehicle & v, SUMOTime time, const bool checkOnly = false) const inherited
Tries to insert the given vehicle into the network.
The procedure for choosing the proper lane is determined, first. In dependance to this, the proper lane is chosen.
Insertion itself is done by calling the chose lane's "insertVehicle" method but only if the checkOnly argument is false. The check needs to be certain only in the negative case (if false is returned, there is no way this vehicle would be inserted).
Parameters
[in] v The vehicle to insert
[in] time The current simulation time
[in] checkOnly whether we perform only the check without actually inserting
Returns
Whether the vehicle could be inserted
See also
MSLane::insertVehicle
Definition at line 473 of file MSEdge.cpp.
References MSVehicleType::computeChosenSpeedDeviation(), DEPART_LANE_DEFAULT, DEPART_LANE_FIRST_ALLOWED, DEPART_LANE_GIVEN, DEPART_POS_FREE, DEPART_POS_GIVEN, DEPART_POS_RANDOM, DEPART_POS_RANDOM_FREE, DEPART_SPEED_GIVEN, SUMOVehicleParameter::departLaneProcedure, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosProcedure, SUMOVehicleParameter::departSpeed, SUMOVehicleParameter::departSpeedProcedure, MSInsertionControl::descheduleDeparture(), MSEdge::EDGEFUNCTION_DISTRICT, MSGlobals::gCheckRoutes, MSLane::getBruttoOccupancy(), MSEdge::getDepartLane(), SUMOVehicle::getEdge(), Named::getID(), SUMOVehicle::getID(), MSNet::getInsertionControl(), MSNet::getInstance(), MSEdge::getLength(), MSVehicleType::getLengthWithGap(), MESegment::getNextSegment(), SUMOVehicle::getParameter(), MSEdge::getPurpose(), MELoop::getSegmentForEdge(), MSVehicleType::getSpeedDeviation(), MSVehicleType::getSpeedFactor(), MSEdge::getSpeedLimit(), MSEdge::getVehicleMaxSpeed(), SUMOVehicle::getVehicleType(), MSGlobals::gMesoNet, MSGlobals::gUseMesoSim, MESegment::hasSpaceFor(), SUMOVehicle::hasValidRoute(), SUMOVehicleParameter::id, MESegment::initialise(), MSLane::insertVehicle(), MSEdge::isVaporizing(), MSEdge::myLanes, MSEdge::myLength, RandHelper::rand(), SUMOVehicle::setChosenSpeedFactor(), SUMOReal, toString(), and WRITE_WARNING.
Referenced by MSInsertionControl::checkCandidates(), MSCalibrator::execute(), and MSEdge::getTravelTimeStatic().
bool MSEdge::isCrossing () const inline inherited
return whether this edge is a pedestrian crossing
Definition at line 259 of file MSEdge.h.
References MSEdge::EDGEFUNCTION_CROSSING, and MSEdge::myFunction.
Referenced by MSSwarmTrafficLightLogic::allowLine(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildSensorForLane(), MSPModel_Striping::getNextLane(), MSPedestrianPushButton::loadCrossingEdgeMap(), and MSPedestrianPushButton::MSPedestrianPushButton().
bool MSEdge::isInternal () const inline inherited
return whether this edge is an internal edge
Definition at line 254 of file MSEdge.h.
References MSEdge::EDGEFUNCTION_INTERNAL, and MSEdge::myFunction.
Referenced by NLEdgeControlBuilder::build(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildSensorForLane(), MSLaneChanger::checkChange(), MSDevice_Tripinfo::computeLengthAndDuration(), MSLane::detectCollisions(), MSPModel_Striping::getNextLane(), MSVehicle::planMoveInternal(), TraCIServerAPI_Vehicle::processGet(), MSVehicle::replaceRoute(), MSLink::setRequestInformation(), and MSVehicle::unsafeLinkAhead().
bool MSEdge::isRoundabout () const inline inherited
Definition at line 632 of file MSEdge.h.
References MSEdge::myAmRoundabout.
Referenced by MSVehicle::checkRewindLinkLanes(), and MSVehicle::executeMove().
bool MSEdge::isVaporizing () const inline inherited
Returns whether vehicles on this edge shall be vaporized.
Returns
Whether no vehicle shall be on this edge
Definition at line 402 of file MSEdge.h.
References MSEdge::decVaporization(), MSEdge::getCurrentTravelTime(), MSEdge::incVaporization(), MSEdge::myVaporizationRequests, NUMERICAL_EPS, and SUMOReal.
Referenced by MSVehicle::executeMove(), MSLane::executeMovements(), and MSEdge::insertVehicle().
bool MSEdge::isWalkingArea () const inline inherited
return whether this edge is walking area
Definition at line 264 of file MSEdge.h.
References MSEdge::EDGEFUNCTION_WALKINGAREA, and MSEdge::myFunction.
Referenced by MSSwarmTrafficLightLogic::allowLine(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildSensorForLane(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextLaneObstacles(), getWalking(), MSPModel_Striping::initWalkingAreaPaths(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::PState::moveToNextLane(), MSPedestrianPushButton::MSPedestrianPushButton(), and MSPModel_Striping::PState::PState().
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 75 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), and MSDevice::equippedByDefaultAssignmentOptions().
MSLane * MSEdge::leftLane (const MSLane *const lane) const inherited
Returns the lane left to the one given, 0 if the given lane is leftmost.
Parameters
[in] lane The lane right to the one to be returned
Returns
The lane left to the given, 0 if no such lane exists
Todo:
This method searches for the given in the container; probably, this could be done faster
Definition at line 274 of file MSEdge.cpp.
References MSEdge::parallelLane().
void GUIEdge::lock () const inline virtual
grant exclusive access to the mesoscopic state
Reimplemented from MSEdge.
Definition at line 197 of file GUIEdge.h.
References MFXMutex::lock(), and myLock.
void MSEdge::markAsRoundabout () inline inherited
Definition at line 636 of file MSEdge.h.
References MSEdge::myAmRoundabout.
Referenced by NLHandler::addRoundabout(), and NLEdgeControlBuilder::build().
void MSEdge::markDelayed () const inline inherited
Definition at line 640 of file MSEdge.h.
References MSEdge::myAmDelayed.
Referenced by MSLane::incorporateVehicle(), MSLane::integrateNewVehicle(), and MEVehicle::setEventTime().
GUIEdge& GUIEdge::operator= (const GUIEdge & s) private
invalidated assignment operator
MSLane * MSEdge::parallelLane (const MSLane *const lane, int offset) const inherited
Returns the lane with the given offset parallel to the given lane one or 0 if it does not exist.
Parameters
[in] lane The base lane
[in] offset The offset of the result lane
Todo:
This method searches for the given in the container; probably, this could be done faster
Definition at line 286 of file MSEdge.cpp.
References MSEdge::myLanes.
Referenced by MSLane::getParallelLane(), MSEdge::leftLane(), and MSEdge::rightLane().
void MSEdge::parseEdgesList (const std::string & desc, ConstMSEdgeVector & into, const std::string & rid) static inherited
Parses the given string assuming it contains a list of edge ids divided by spaces.
Splits the string at spaces, uses polymorph method to generate edge vector.
Parameters
[in] desc The string containing space-separated edge ids
[out] into The vector to fill
[in] rid The id of the route these description belongs to; used for error message generation
Exceptions
ProcessError If one of the strings contained is not a known edge id
Definition at line 722 of file MSEdge.cpp.
References BinaryFormatter::BF_ROUTE, StringTokenizer::getVector(), and FileHelpers::readEdgeVector().
Referenced by MSStateHandler::myStartElement(), MSRouteHandler::myStartElement(), MSRouteHandler::openRoute(), MSRouteHandler::parseFromViaTo(), TraCIServerAPI_Vehicle::processSet(), and MSEdge::unlock().
void MSEdge::parseEdgesList (const std::vector< std::string > & desc, ConstMSEdgeVector & into, const std::string & rid) static inherited
Parses the given string vector assuming it edge ids.
Parameters
[in] desc The string vector containing edge ids
[out] into The vector to fill
[in] rid The id of the route these description belongs to; used for error message generation
Exceptions
ProcessError If one of the strings contained is not a known edge id
Definition at line 737 of file MSEdge.cpp.
References MSEdge::dictionary(), and SUMOReal.
bool MSEdge::prohibits (const SUMOVehicle *const vehicle) const inline inherited
Returns whether the vehicle (class) is not allowed on the edge.
Definition at line 548 of file MSEdge.h.
References MSVehicleType::getVehicleClass(), SUMOVehicle::getVehicleType(), and MSEdge::myCombinedPermissions.
void MSEdge::rebuildAllowedLanes () inherited
Definition at line 252 of file MSEdge.cpp.
References MSEdge::myClassedAllowed, MSEdge::myClassesSuccessorMap, MSEdge::myCombinedPermissions, MSEdge::myLanes, MSEdge::myMinimumPermissions, and SVCAll.
Referenced by MSEdge::closeBuilding(), closeTraffic(), GUILane::closeTraffic(), MSEdge::getSubLaneSides(), TraCIServerAPI_Edge::processSet(), and TraCIServerAPI_Lane::processSet().
void MSEdge::recalcCache () inherited
Recalculates the cached values.
Definition at line 136 of file MSEdge.cpp.
References MSLane::getLinkCont(), MSLink::getMesoTLSPenalty(), MSEdge::getSpeedLimit(), MSGlobals::gMesoTLSPenalty, MAX2(), MIN2(), MSEdge::myEmptyTraveltime, MSEdge::myLanes, MSEdge::myLength, NUMERICAL_EPS, and STEPS2TIME.
Referenced by MSEdge::initialize(), MSTrafficLightLogic::initMesoTLSPenalties(), MSLane::setLength(), and MSLane::setMaxSpeed().
void GUIEdge::removeContainer (MSTransportable * container) const inline virtual
Remove container from myContainers.
Reimplemented from MSEdge.
Definition at line 162 of file GUIEdge.h.
References drawMesoVehicles(), getAllowedSpeed(), getBruttoOccupancy(), getColorValue(), getFlow(), getRelativeSpeed(), getScaleValue(), getSegmentAtPosition(), getVehicleIDs(), getVehicleNo(), myLock, MSEdge::removeContainer(), setColor(), setFunctionalColor(), setMultiColor(), and SUMOReal.
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 264 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
void GUIEdge::removePerson (MSTransportable * p) const inline virtual
Reimplemented from MSEdge.
Definition at line 151 of file GUIEdge.h.
References myLock, and MSEdge::removePerson().
MSLane * MSEdge::rightLane (const MSLane *const lane) const inherited
Returns the lane right to the one given, 0 if the given lane is rightmost.
Parameters
[in] lane The lane left to the one to be returned
Returns
The lane right to the given, 0 if no such lane exists
Todo:
This method searches for the given in the container; probably, this could be done faster
Definition at line 280 of file MSEdge.cpp.
References MSEdge::parallelLane().
void GUIEdge::setColor (const GUIVisualizationSettings & s) const
sets the color according to the currente settings
Definition at line 409 of file GUIEdge.cpp.
References GUIVisualizationSettings::edgeColorer, GUIPropertySchemeStorage< T >::getActive(), GUIPropertyScheme< T >::getColor(), getColorValue(), GUIPropertySchemeStorage< T >::getScheme(), GLHelper::setColor(), setFunctionalColor(), and setMultiColor().
Referenced by drawGL(), and removeContainer().
void MSEdge::setCrossingEdges (const std::vector< std::string > & crossingEdges) inline inherited
Sets the crossed edge ids for a crossing edge.
Definition at line 298 of file MSEdge.h.
References MSEdge::myCrossingEdges.
Referenced by NLEdgeControlBuilder::addCrossingEdges().
bool GUIEdge::setFunctionalColor (int activeScheme) const
sets the color according to the current scheme index and some edge function
Definition at line 418 of file GUIEdge.cpp.
References PositionVector::beginEndAngle(), RGBColor::fromHSV(), MSEdge::getLanes(), GeomHelper::naviDegree(), GLHelper::setColor(), and SUMOReal.
Referenced by removeContainer(), and setColor().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
void MSEdge::setJunctions (MSJunction * from, MSJunction * to) inline inherited
Definition at line 388 of file MSEdge.h.
References MSEdge::myFromJunction, and MSEdge::myToJunction.
Referenced by NLHandler::myEndElement().
void MSEdge::setLastFailedInsertionTime (SUMOTime time) const inline inherited
Sets the last time a vehicle could not be inserted.
Parameters
[in] time the new value
Definition at line 532 of file MSEdge.h.
References MSEdge::changeLanes(), and MSEdge::myLastFailedInsertionTime.
void MSEdge::setMaxSpeed (SUMOReal val) const inherited
Sets a new maximum speed for all lanes (used by TraCI and MSCalibrator)
Parameters
[in] val the new speed in m/s
Definition at line 776 of file MSEdge.cpp.
References MSEdge::myLanes.
Referenced by METriggeredCalibrator::execute(), MSCalibrator::execute(), and MSEdge::getLength().
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 143 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNENet::renameJunction(), GNEAdditional::setAdditionalID(), GNELane::setIndex(), and GNEEdge::setMicrosimID().
bool GUIEdge::setMultiColor (const GUIColorer & c) const
sets multiple colors according to the current scheme index and edge function
Definition at line 433 of file GUIEdge.cpp.
References GUIPropertySchemeStorage< T >::getActive(), getAllowedSpeed(), GUIPropertyScheme< T >::getColor(), GUIPropertySchemeStorage< T >::getScheme(), MSGlobals::gMesoNet, mySegmentColors, and SUMOReal.
Referenced by removeContainer(), and setColor().
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 273 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
void GUIEdge::unlock () const inline virtual
release exclusive access to the mesoscopic state
Reimplemented from MSEdge.
Definition at line 202 of file GUIEdge.h.
References addRerouter(), closeTraffic(), myLock, and MFXMutex::unlock().
Field Documentation
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 77 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
AllowedLanesCont MSEdge::myAllowed protected inherited
Associative container from destination-edge to allowed-lanes.
Definition at line 797 of file MSEdge.h.
Referenced by MSEdge::allowedLanes(), MSEdge::closeBuilding(), and MSEdge::~MSEdge().
bool MSEdge::myAmDelayed mutable protected inherited
whether this edge had a vehicle with less than max speed on it
Definition at line 828 of file MSEdge.h.
Referenced by MSEdge::getCurrentTravelTime(), and MSEdge::markDelayed().
bool MSEdge::myAmRoundabout protected inherited
whether this edge belongs to a roundabout
Definition at line 831 of file MSEdge.h.
Referenced by MSEdge::isRoundabout(), and MSEdge::markAsRoundabout().
ClassedAllowedLanesCont MSEdge::myClassedAllowed mutable protected inherited
From vehicle class to lanes allowed to be used by it.
Definition at line 801 of file MSEdge.h.
Referenced by MSEdge::allowedLanes(), MSEdge::rebuildAllowedLanes(), and MSEdge::~MSEdge().
std::map<SUMOVehicleClass, MSEdgeVector> MSEdge::myClassesSuccessorMap mutable protected inherited
The successors available for a given vClass.
Definition at line 855 of file MSEdge.h.
Referenced by MSEdge::getSuccessors(), and MSEdge::rebuildAllowedLanes().
SVCPermissions MSEdge::myCombinedPermissions protected inherited
The union of lane permissions for this edge.
Definition at line 806 of file MSEdge.h.
Referenced by MSEdge::getPermissions(), MSEdge::initialize(), MSEdge::prohibits(), and MSEdge::rebuildAllowedLanes().
std::set<MSTransportable*> MSEdge::myContainers mutable protected inherited
Containers on the edge.
Definition at line 791 of file MSEdge.h.
Referenced by MSEdge::addContainer(), drawGL(), MSEdge::getSortedContainers(), and MSEdge::removeContainer().
std::vector<std::string> MSEdge::myCrossingEdges protected inherited
The crossed edges id for a crossing edge. On not crossing edges it is empty.
Definition at line 775 of file MSEdge.h.
Referenced by MSEdge::getCrossingEdges(), and MSEdge::setCrossingEdges().
MSEdge::DictType MSEdge::myDict static protected inherited
Static dictionary to associate string-ids with objects.
Deprecated:
Move to MSEdgeControl, make non-static
Definition at line 845 of file MSEdge.h.
Referenced by MSEdge::clear(), MSEdge::dictionary(), MSEdge::dictSize(), fill(), getIDs(), getTotalLength(), and MSEdge::insertIDs().
MSEdgeVector MSEdge::myEdges static protected inherited
Static list of edges.
Deprecated:
Move to MSEdgeControl, make non-static
Definition at line 850 of file MSEdge.h.
Referenced by MSEdge::dictionary(), and MSEdge::getAllEdges().
std::string MSEdge::myEdgeType protected inherited
the type of the edge (optionally used during network creation)
Definition at line 813 of file MSEdge.h.
Referenced by MSEdge::getEdgeType().
SUMOReal MSEdge::myEmptyTraveltime protected inherited
the traveltime on the empty edge (cached value for speedup)
Definition at line 825 of file MSEdge.h.
Referenced by MSEdge::getCurrentTravelTime(), MSEdge::getMeanSpeed(), and MSEdge::recalcCache().
MSJunction* MSEdge::myFromJunction protected inherited
the junctions for this edge
Definition at line 784 of file MSEdge.h.
Referenced by MSEdge::getFromJunction(), and MSEdge::setJunctions().
const EdgeBasicFunction MSEdge::myFunction protected inherited
the purpose of the edge
Definition at line 766 of file MSEdge.h.
Referenced by MSEdge::allowsLaneChanging(), MSEdge::changeLanes(), drawGL(), MSEdge::getPurpose(), MSEdge::getSuccessors(), MSEdge::initialize(), MSEdge::isCrossing(), MSEdge::isInternal(), and MSEdge::isWalkingArea().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
MSLaneChanger* MSEdge::myLaneChanger protected inherited
This member will do the lane-change.
Definition at line 763 of file MSEdge.h.
Referenced by MSEdge::buildLaneChanger(), MSEdge::changeLanes(), MSEdge::hasLaneChanger(), and MSEdge::~MSEdge().
const std::vector<MSLane*>* MSEdge::myLanes protected inherited
Container for the edge's lane; should be sorted: (right-hand-traffic) the more left the lane, the higher the container-index.
Definition at line 760 of file MSEdge.h.
Referenced by MSEdge::allowsLaneChanging(), MSEdge::buildLaneChanger(), MSEdge::canChangeToOpposite(), MSEdge::changeLanes(), MSEdge::closeBuilding(), drawGL(), drawMesoVehicles(), getAllowedSpeed(), getBoundary(), getBruttoOccupancy(), MSEdge::getDepartLane(), getLane(), MSEdge::getLanes(), MSEdge::getMeanSpeed(), getParameterWindow(), MSEdge::initialize(), MSEdge::insertVehicle(), MSEdge::parallelLane(), MSEdge::rebuildAllowedLanes(), MSEdge::recalcCache(), MSEdge::setMaxSpeed(), and MSEdge::~MSEdge().
SUMOTime MSEdge::myLastFailedInsertionTime mutable protected inherited
The time of last insertion failure.
Definition at line 772 of file MSEdge.h.
Referenced by MSEdge::getLastFailedInsertionTime(), and MSEdge::setLastFailedInsertionTime().
SUMOReal MSEdge::myLength protected inherited
the length of the edge (cached value for speedup)
Definition at line 822 of file MSEdge.h.
Referenced by MSEdge::getLength(), MSEdge::insertVehicle(), and MSEdge::recalcCache().
MFXMutex GUIEdge::myLock mutable private
The mutex used to avoid concurrent updates of myPersons/ myContainers.
Definition at line 230 of file GUIEdge.h.
Referenced by addContainer(), addPerson(), drawGL(), drawMesoVehicles(), lock(), removeContainer(), removePerson(), unlock(), and ~GUIEdge().
SVCPermissions MSEdge::myMinimumPermissions protected inherited
The intersection of lane permissions for this edge.
Definition at line 804 of file MSEdge.h.
Referenced by MSEdge::allowedLanes(), and MSEdge::rebuildAllowedLanes().
const int MSEdge::myNumericalID protected inherited
This edge's numerical id.
Definition at line 757 of file MSEdge.h.
Referenced by MSEdge::getNumericalID().
std::set<MSTransportable*> MSEdge::myPersons mutable protected inherited
Persons on the edge for drawing and pushbutton.
Definition at line 788 of file MSEdge.h.
Referenced by MSEdge::addPerson(), drawGL(), MSEdge::getPersons(), MSEdge::getSortedPersons(), and MSEdge::removePerson().
MSEdgeVector MSEdge::myPredecessors protected inherited
The preceeding edges.
Definition at line 781 of file MSEdge.h.
Referenced by MSEdge::addSuccessor(), MSEdge::closeBuilding(), getBoundary(), MSEdge::getIncomingEdges(), MSEdge::getNumPredecessors(), and MSEdge::getPredecessors().
const int MSEdge::myPriority protected inherited
the priority of the edge (used during network creation)
Definition at line 816 of file MSEdge.h.
Referenced by MSEdge::getPriority().
std::vector<RGBColor> GUIEdge::mySegmentColors mutable
The color of the segments (cached)
Definition at line 218 of file GUIEdge.h.
Referenced by getSegmentColors(), and setMultiColor().
std::string MSEdge::myStreetName protected inherited
the real-world name of this edge (need not be unique)
Definition at line 810 of file MSEdge.h.
Referenced by drawGL(), and MSEdge::getStreetName().
std::vector<SUMOReal> MSEdge::mySublaneSides protected inherited
the right side for each sublane on this edge
Definition at line 834 of file MSEdge.h.
Referenced by MSEdge::getSubLaneSides(), and MSEdge::initialize().
MSEdgeVector MSEdge::mySuccessors protected inherited
The succeeding edges.
Definition at line 778 of file MSEdge.h.
Referenced by MSEdge::addSuccessor(), MSEdge::closeBuilding(), getBoundary(), MSEdge::getNumSuccessors(), MSEdge::getOutgoingEdges(), and MSEdge::getSuccessors().
MSJunction* MSEdge::myToJunction protected inherited
Definition at line 785 of file MSEdge.h.
Referenced by MSEdge::getToJunction(), and MSEdge::setJunctions().
int MSEdge::myVaporizationRequests protected inherited
Vaporizer counter.
Definition at line 769 of file MSEdge.h.
Referenced by MSEdge::decVaporization(), MSEdge::incVaporization(), and MSEdge::isVaporizing().
SUMOReal MSEdge::myWidth protected inherited
Edge width [m].
Definition at line 819 of file MSEdge.h.
Referenced by MSEdge::getWidth(), and MSEdge::initialize().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 76 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUIEdge.h
GUIEdge.cpp