SUMO - Simulation of Urban MObility: MSQueueExport Class Reference
MSQueueExport Class Reference
Export the queueing length in front of a junction (very experimental!)
#include <MSQueueExport.h>
Static Public Member Functions
static void write (OutputDevice &of, SUMOTime timestep)
Export the queueing length in front of a junction (very experimental!)
Private Member Functions
MSQueueExport (const MSQueueExport &)
Invalidated copy constructor.
MSQueueExport & operator= (const MSQueueExport &)
Invalidated assignment operator.
Static Private Member Functions
static void writeEdge (OutputDevice &of)
Iterates through all the edges and extract the lanes.
static void writeLane (OutputDevice &of, const MSLane &lane)
Iterates through the lanes and check for available vehicle queues.
Detailed Description
Export the queueing length in front of a junction (very experimental!)
The class offers a static method, which writes the actual queueing length of the network into the given OutputDevice.
Todo:
consider error-handling on write (using IOError)
Definition at line 57 of file MSQueueExport.h.
Constructor & Destructor Documentation
MSQueueExport::MSQueueExport (const MSQueueExport &) private
Invalidated copy constructor.
Member Function Documentation
MSQueueExport& MSQueueExport::operator= (const MSQueueExport &) private
Invalidated assignment operator.
void MSQueueExport::write (OutputDevice & of, SUMOTime timestep) static
Export the queueing length in front of a junction (very experimental!)
Opens the current time step, goes through the lanes check for a traffic jam in front of a junction
Parameters
[in] of The output device to use
[in] timestep The current time step
Exceptions
IOError If an error on writing occurs (!!! not yet implemented)
Definition at line 57 of file MSQueueExport.cpp.
References OutputDevice::closeTag(), OutputDevice::openTag(), time2string(), OutputDevice::writeAttr(), and writeEdge().
Referenced by MSNet::writeOutput().
void MSQueueExport::writeEdge (OutputDevice & of) static private
Iterates through all the edges and extract the lanes.
Definition at line 65 of file MSQueueExport.cpp.
References OutputDevice::closeTag(), MSNet::getEdgeControl(), MSEdgeControl::getEdges(), MSNet::getInstance(), MSEdge::getLanes(), OutputDevice::openTag(), and writeLane().
Referenced by write().
void MSQueueExport::writeLane (OutputDevice & of, const MSLane & lane) static private
Iterates through the lanes and check for available vehicle queues.
Definition at line 81 of file MSQueueExport.cpp.
References OutputDevice::closeTag(), MSLane::empty(), Named::getID(), MSVehicle::getLane(), MSVehicleType::getLength(), MSLane::getLength(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSVehicle::getWaitingSeconds(), MSVehicle::isOnRoad(), MAX2(), MSLane::myVehicles, OutputDevice::openTag(), SUMOReal, and OutputDevice::writeAttr().
Referenced by writeEdge().
The documentation for this class was generated from the following files:
MSQueueExport.h
MSQueueExport.cpp