SUMO - Simulation of Urban MObility: Option_Integer Class Reference
Option_Integer Class Reference
An integer-option.
#include <Option.h>
Public Member Functions
virtual bool getBool () const
Returns the stored boolean value.
const std::string & getDescription () const
Returns the description of what this option does.
virtual SUMOReal getFloat () const
Returns the stored SUMOReal value.
int getInt () const
Returns the stored integer value.
virtual const IntVector & getIntVector () const
Returns the stored integer vector.
virtual std::string getString () const
Returns the stored string value.
virtual const std::string & getTypeName () const
Returns the mml-type name of this option.
std::string getValueString () const
Returns the string-representation of the value.
virtual bool isBool () const
Returns the information whether the option is a bool option.
virtual bool isDefault () const
Returns the information whether the option holds the default value.
virtual bool isFileName () const
Returns the information whether this option is a file name.
bool isSet () const
returns the information whether this options holds a valid value
bool isWriteable () const
Returns the information whether the option may be set a further time.
Option_Integer & operator= (const Option_Integer &s)
Assignment operator.
Option_Integer ()
Constructor for an option with no default value.
Option_Integer (int value)
Constructor for an option with a default value.
Option_Integer (const Option_Integer &s)
Copy constructor.
void resetDefault ()
Resets the option to be on its default value.
void resetWritable ()
Resets the option to be writeable.
bool set (const std::string &v)
Stores the given value after parsing it into an integer.
void setDescription (const std::string &desc)
Sets the description of what this option does.
void unSet ()
marks this option as unset
~Option_Integer ()
Destructor.
Protected Member Functions
bool markSet ()
Marks the information as set.
Protected Attributes
std::string myTypeName
A type name for this option (has presets, but may be overwritten)
Private Attributes
int myValue
Detailed Description
An integer-option.
Definition at line 313 of file Option.h.
Constructor & Destructor Documentation
Option_Integer::Option_Integer ()
Constructor for an option with no default value.
Calls Option(false)
Definition at line 191 of file Option.cpp.
References Option::myTypeName.
Option_Integer::Option_Integer (int value)
Constructor for an option with a default value.
Calls Option(true)
Parameters
[in] value This option's default value
Definition at line 197 of file Option.cpp.
References Option::myTypeName.
Option_Integer::Option_Integer (const Option_Integer & s)
Copy constructor.
Definition at line 206 of file Option.cpp.
References myValue.
Option_Integer::~Option_Integer ()
Destructor.
Definition at line 203 of file Option.cpp.
Member Function Documentation
bool Option::getBool () const virtual inherited
Returns the stored boolean value.
Option_Bool returns the stored boolean in this method's reimplementation. All other option classes do not override this method which throws an InvalidArgument-exception.
Returns
Returns the stored boolean if being an instance of Option_Bool
Exceptions
InvalidArgument If the class is not an instance of Option_Bool
Reimplemented in Option_Bool.
Definition at line 104 of file Option.cpp.
Referenced by OptionsCont::getBool().
const std::string & Option::getDescription () const inherited
Returns the description of what this option does.
The description stored in myDescription is returned.
Returns
The description of this option's purpose
Definition at line 169 of file Option.cpp.
References Option::myDescription.
Referenced by OptionsCont::printHelp(), and OptionsCont::writeConfiguration().
SUMOReal Option::getFloat () const virtual inherited
Returns the stored SUMOReal value.
Option_Float returns the stored real number in this method's reimplementation. All other option classes do not override this method which throws an InvalidArgument-exception.
Returns
Returns the stored real number if being an instance of Option_Float
Exceptions
InvalidArgument If the class is not an instance of Option_Float
Reimplemented in Option_Float.
Definition at line 86 of file Option.cpp.
Referenced by OptionsCont::getFloat().
int Option_Integer::getInt () const virtual
Returns the stored integer value.
See also
Option::getInt()
Returns
Returns the stored integer number
Reimplemented from Option.
Definition at line 224 of file Option.cpp.
References myValue.
const IntVector & Option::getIntVector () const virtual inherited
Returns the stored integer vector.
Option_IntVector returns the stored integer vector in this method's reimplementation. All other option classes do not override this method which throws an InvalidArgument-exception.
Returns
Returns the stored integer vector if being an instance of Option_IntVector
Exceptions
InvalidArgument If the class is not an instance of Option_IntVector
Reimplemented in Option_IntVector.
Definition at line 110 of file Option.cpp.
Referenced by OptionsCont::getIntVector().
std::string Option::getString () const virtual inherited
Returns the stored string value.
Option_String and Option_FileName return the stored string in this method's reimplementation. All other option classes do not override this method which throws an InvalidArgument-exception.
Returns
Returns the stored string if being an instance of Option_String
Exceptions
InvalidArgument If the class is not an instance of Option_String
Reimplemented in Option_String.
Definition at line 98 of file Option.cpp.
Referenced by OptionsCont::getString(), and OptionsCont::getStringVector().
const std::string & Option::getTypeName () const virtual inherited
Returns the mml-type name of this option.
The type name stored in myTypeName is returned.
Returns
The man-readable type name
Definition at line 181 of file Option.cpp.
References Option::myTypeName.
Referenced by OptionsCont::getTypeName(), OptionsCont::printHelp(), OptionsCont::writeConfiguration(), and OptionsCont::writeSchema().
std::string Option_Integer::getValueString () const virtual
Returns the string-representation of the value.
The stored value is encoded into a string and returned.
See also
std::string Option::getValueString()
Returns
The stored value encoded into a string
Implements Option.
Definition at line 242 of file Option.cpp.
References myValue.
bool Option::isBool () const virtual inherited
Returns the information whether the option is a bool option.
Returns false. Only Option_Bool overrides this method returning true.
Returns
true if the Option is an Option_Bool, false otherwise
Reimplemented in Option_Bool.
Definition at line 133 of file Option.cpp.
Referenced by OptionsCont::isBool(), and OptionsCont::printHelp().
bool Option::isDefault () const virtual inherited
Returns the information whether the option holds the default value.
Returns
true if the option was not set from command line / configuration, false otherwise
Definition at line 139 of file Option.cpp.
References Option::myHaveTheDefaultValue.
Referenced by OptionsCont::writeConfiguration().
bool Option::isFileName () const virtual inherited
Returns the information whether this option is a file name.
Returns false. Only Option_FileName overrides this method returning true.
Returns
true if the Option is an Option_FileName, false otherwise
Reimplemented in Option_FileName.
Definition at line 145 of file Option.cpp.
bool Option::isSet () const inherited
returns the information whether this options holds a valid value
Returns
Whether a value has been set
Definition at line 80 of file Option.cpp.
References Option::myAmSet, and SUMOReal.
Referenced by OptionsCont::checkDependingSuboptions(), OptionsCont::isUsableFileList(), and OptionsCont::writeConfiguration().
bool Option::isWriteable () const inherited
Returns the information whether the option may be set a further time.
This method returns whether the option was not already set using command line options / configuration. This is done by returning the value of myAmWritable.
Returns
Whether the option may be set from the command line / configuration
Definition at line 151 of file Option.cpp.
References Option::myAmWritable.
Referenced by OptionsCont::isWriteable(), and OptionsCont::set().
bool Option::markSet () protected inherited
Marks the information as set.
Sets the "myAmSet" - information. Returns whether the option was writeable before.
Returns
Whether the option was not set before.
Definition at line 116 of file Option.cpp.
References Option::myAmSet, Option::myAmWritable, and Option::myHaveTheDefaultValue.
Referenced by set(), Option_String::set(), Option_Float::set(), Option_Bool::set(), and Option_IntVector::set().
Option_Integer & Option_Integer::operator= (const Option_Integer & s)
Assignment operator.
Definition at line 213 of file Option.cpp.
References myValue, and Option::operator=().
void Option::resetDefault () inherited
Resets the option to be on its default value.
An option is on its default after initialisation with a value, but as soon as it gets set, it is no longer. This method resets the default-flag.
Definition at line 163 of file Option.cpp.
References Option::myHaveTheDefaultValue.
Referenced by OptionsCont::setDefault().
void Option::resetWritable () inherited
Resets the option to be writeable.
An option is writable after initialisation, but as soon as it gets set, it is no longer writeable. This method resets the writable-flag.
Definition at line 157 of file Option.cpp.
References Option::myAmWritable.
bool Option_Integer::set (const std::string & v) virtual
Stores the given value after parsing it into an integer.
The value is converted into an integer and stored in "myValue". Then, "markSet" is called in order to know that a value has been set.
The method returns whether the value could be set (the return value from "markSet").
If the string could not be converted into an integer, an InvalidArgument is thrown.
See also
bool Option::set(std::string v)
Returns
Whether the new value could be set
Exceptions
InvalidArgument If the value could not be converted into an integer
Implements Option.
Definition at line 230 of file Option.cpp.
References TplConvert::_2int(), Option::markSet(), and myValue.
void Option::setDescription (const std::string & desc) inherited
Sets the description of what this option does.
The description stored in myDescription is returned.
Returns
The description of this option's purpose
Definition at line 175 of file Option.cpp.
References Option::myDescription.
Referenced by OptionsCont::addDescription().
void Option::unSet () inherited
marks this option as unset
Definition at line 126 of file Option.cpp.
References Option::myAmSet, and Option::myAmWritable.
Field Documentation
std::string Option::myTypeName protected inherited
A type name for this option (has presets, but may be overwritten)
Definition at line 287 of file Option.h.
Referenced by Option::getTypeName(), Option_Bool::Option_Bool(), Option_FileName::Option_FileName(), Option_Float::Option_Float(), Option_Integer(), Option_IntVector::Option_IntVector(), and Option_String::Option_String().
int Option_Integer::myValue private
the value, valid only when the base-classes "myAmSet"-member is true
Definition at line 380 of file Option.h.
Referenced by getInt(), getValueString(), operator=(), Option_Integer(), and set().
The documentation for this class was generated from the following files:
Option.h
Option.cpp