SUMO - Simulation of Urban MObility: ROPerson::Walk Class Reference
ROPerson::Walk Class Reference
A walk is part of a trip, e.g., go from here to here by foot.
#include <ROPerson.h>
Public Member Functions
const ROEdge * getDestination () const
const ROEdge * getOrigin () const
void saveAsXML (OutputDevice &os) const
Walk (const ConstROEdgeVector &_edges, const std::string &_destStop="")
Walk (const ConstROEdgeVector &edges, const SUMOReal duration, const SUMOReal speed, const SUMOReal departPos, const SUMOReal arrivalPos, const std::string &_destStop)
Private Member Functions
Walk & operator= (const Walk &src)
Invalidated assignment operator.
Private Attributes
const SUMOReal arr
const SUMOReal dep
const std::string destStop
const SUMOReal dur
const ConstROEdgeVector edges
const SUMOReal v
Detailed Description
A walk is part of a trip, e.g., go from here to here by foot.
Definition at line 185 of file ROPerson.h.
Constructor & Destructor Documentation
ROPerson::Walk::Walk (const ConstROEdgeVector & _edges, const std::string & _destStop = "") inline
Definition at line 187 of file ROPerson.h.
ROPerson::Walk::Walk (const ConstROEdgeVector & edges, const SUMOReal duration, const SUMOReal speed, const SUMOReal departPos, const SUMOReal arrivalPos, const std::string & _destStop) inline
Definition at line 189 of file ROPerson.h.
Member Function Documentation
const ROEdge* ROPerson::Walk::getDestination () const inline virtual
Implements ROPerson::TripItem.
Definition at line 195 of file ROPerson.h.
References ROPerson::PlanItem::saveAsXML().
const ROEdge* ROPerson::Walk::getOrigin () const inline virtual
Implements ROPerson::TripItem.
Definition at line 192 of file ROPerson.h.
Walk& ROPerson::Walk::operator= (const Walk & src) private
Invalidated assignment operator.
void ROPerson::Walk::saveAsXML (OutputDevice & os) const virtual
Implements ROPerson::TripItem.
Definition at line 139 of file ROPerson.cpp.
References OutputDevice::closeTag(), OutputDevice::openTag(), SUMO_ATTR_ARRIVALPOS, SUMO_ATTR_BUS_STOP, SUMO_ATTR_DEPARTPOS, SUMO_ATTR_DURATION, SUMO_ATTR_EDGES, SUMO_ATTR_SPEED, SUMO_TAG_WALK, and OutputDevice::writeAttr().
Field Documentation
const SUMOReal ROPerson::Walk::arr private
Definition at line 202 of file ROPerson.h.
const SUMOReal ROPerson::Walk::dep private
Definition at line 202 of file ROPerson.h.
const std::string ROPerson::Walk::destStop private
Definition at line 203 of file ROPerson.h.
const SUMOReal ROPerson::Walk::dur private
Definition at line 202 of file ROPerson.h.
const ConstROEdgeVector ROPerson::Walk::edges private
Definition at line 201 of file ROPerson.h.
const SUMOReal ROPerson::Walk::v private
Definition at line 202 of file ROPerson.h.
The documentation for this class was generated from the following files:
ROPerson.h
ROPerson.cpp