SUMO - Simulation of Urban MObility: Helper_ConvexHull.h File Reference
Helper_ConvexHull.h File Reference
#include <config.h>
#include "Position.h"
#include "PositionVector.h"
#include <vector>
Functions
SUMOReal isLeft (const Position &P0, const Position &P1, const Position &P2)
PositionVector simpleHull_2D (const PositionVector &V)
Detailed Description
Author
Daniel Krajzewicz
Michael Behrisch
Date
Fri, 29.04.2005
Version
Id
Helper_ConvexHull.h 20433 2016-04-13 08:00:14Z behrisch
Definition in file Helper_ConvexHull.h.
Function Documentation
SUMOReal isLeft (const Position & P0, const Position & P1, const Position & P2) inline
Definition at line 62 of file Helper_ConvexHull.h.
References simpleHull_2D(), Position::x(), and Position::y().
Referenced by simpleHull_2D().
PositionVector simpleHull_2D (const PositionVector & V)
Definition at line 51 of file Helper_ConvexHull.cpp.
References isLeft(), and PositionVector::push_back_noDoublePos().
Referenced by PositionVector::convexHull(), and isLeft().