SUMO - Simulation of Urban MObility: GUIParameterTableWindow Class Reference
GUIParameterTableWindow Class Reference
A window containing a gl-object's parameter.
#include <GUIParameterTableWindow.h>
Public Member Functions
void closeBuilding ()
Closes the building of the table.
GUIParameterTableWindow (GUIMainWindow &app, GUIGlObject &o, int noRows)
Constructor.
void removeObject (GUIGlObject *const o)
Lets this window know the object shown is being deleted.
~GUIParameterTableWindow ()
Destructor.
Row adding functions
void mkItem (const char *name, bool dynamic, ValueSource< unsigned > *src)
Adds a row which obtains its value from an unsigned-ValueSource.
void mkItem (const char *name, bool dynamic, ValueSource< int > *src)
Adds a row which obtains its value from an integer-ValueSource.
void mkItem (const char *name, bool dynamic, ValueSource< SUMOReal > *src)
Adds a row which obtains its value from an SUMOReal-ValueSource.
void mkItem (const char *name, bool dynamic, std::string value)
Adds a row which shows a string-value.
void mkItem (const char *name, bool dynamic, unsigned value)
Adds a row which shows a unsigned-value.
void mkItem (const char *name, bool dynamic, int value)
Adds a row which shows a integer-value.
void mkItem (const char *name, bool dynamic, long long int value)
Adds a row which shows a 64 bit integer-value.
void mkItem (const char *name, bool dynamic, SUMOReal value)
Adds a row which shows a SUMOReal-value.
FOX-callbacks
long onSimStep (FXObject *, FXSelector, void *)
Updates the table due to a simulation step.
long onTableSelected (FXObject *, FXSelector, void *)
Does nothing.
long onTableDeselected (FXObject *, FXSelector, void *)
Does nothing.
long onRightButtonPress (FXObject *, FXSelector, void *)
Shows a popup.
Static Public Member Functions
static void updateAll ()
Updates all instances.
Protected Member Functions
GUIParameterTableWindow ()
FOX needs this.
void updateTable ()
Updates the table.
Static Protected Attributes
static std::vector< GUIParameterTableWindow * > myContainer
The container of items that shall be updated.
static MFXMutex myGlobalContainerLock
The mutex used to avoid concurrent updates of the instance container.
Private Attributes
GUIMainWindow * myApplication
The main application window.
unsigned myCurrentPos
The index of the next row to add - used while building.
std::vector< GUIParameterTableItemInterface * > myItems
The list of table rows.
MFXMutex myLock
A lock assuring save updates in case of object deletion.
GUIGlObject * myObject
The object to get the information from.
FXTable * myTable
The table to display the information in.
Detailed Description
A window containing a gl-object's parameter.
This class realises a view on some parameter of a gl-object. The gl-object itself is responsible for filling this table.
After allocating such a table, the object should fill the rows by calling one of the mkItem-methods for each. The building is closed using closeBuilding what forces the table to be displayed.
Each row is represented using an instance of GUIParameterTableItemInterface.
Definition at line 69 of file GUIParameterTableWindow.h.
Constructor & Destructor Documentation
GUIParameterTableWindow::GUIParameterTableWindow (GUIMainWindow & app, GUIGlObject & o, int noRows)
Constructor.
Parameters
[in] app The application this window belongs to
[in] o The gl-object this table describes
[in] noRows Number of rows to allocate
Definition at line 72 of file GUIParameterTableWindow.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_TABLE.
GUIParameterTableWindow::~GUIParameterTableWindow ()
Destructor.
Definition at line 103 of file GUIParameterTableWindow.cpp.
References MFXMutex::lock(), myApplication, myContainer, myGlobalContainerLock, myItems, myLock, myObject, GUIMainWindow::removeChild(), GUIGlObject::removeParameterTable(), and MFXMutex::unlock().
GUIParameterTableWindow::GUIParameterTableWindow () inline protected
FOX needs this.
Definition at line 259 of file GUIParameterTableWindow.h.
Member Function Documentation
void GUIParameterTableWindow::closeBuilding ()
Closes the building of the table.
Adds the table to the list of child windows of the applications also telling the application that the window should be updated in each simulation step. Shows the table.
See also
GUIMainWindow::addChild
Definition at line 258 of file GUIParameterTableWindow.cpp.
References GUIMainWindow::addChild(), and myApplication.
Referenced by GNEInternalLane::getParameterWindow(), GNECrossing::getParameterWindow(), GUIContainer::getParameterWindow(), GUIPerson::getParameterWindow(), GUILaneSpeedTrigger::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUICalibrator::getParameterWindow(), GNELane::getParameterWindow(), GUI_E2_ZS_CollectorOverLanes::MyWrapper::getParameterWindow(), GUIE3Collector::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIChargingStation::getParameterWindow(), GUIContainerStop::getParameterWindow(), GUIBusStop::getParameterWindow(), GUIMEVehicle::getParameterWindow(), GUIEdge::getParameterWindow(), GUIVehicle::getParameterWindow(), GUINet::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GNEAdditional::getParameterWindow(), GUILane::getParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), and GUIVehicle::getTypeParameterWindow().
void GUIParameterTableWindow::mkItem (const char * name, bool dynamic, ValueSource< unsigned > * src)
Adds a row which obtains its value from an unsigned-ValueSource.
Parameters
[in] name The name of the row entry
[in] dynamic Information whether the entry is dynamic
[in] src The value source to use
Definition at line 181 of file GUIParameterTableWindow.cpp.
References myCurrentPos, myItems, and myTable.
Referenced by GUIContainer::getParameterWindow(), GUIPerson::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUILaneSpeedTrigger::getParameterWindow(), GUICalibrator::getParameterWindow(), GNELane::getParameterWindow(), GUI_E2_ZS_CollectorOverLanes::MyWrapper::getParameterWindow(), GUIE3Collector::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIContainerStop::getParameterWindow(), GUIChargingStation::getParameterWindow(), GUIBusStop::getParameterWindow(), GUIMEVehicle::getParameterWindow(), GUIEdge::getParameterWindow(), GUIVehicle::getParameterWindow(), GUINet::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), GNEAdditional::getParameterWindow(), GUILane::getParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), and GUIVehicle::getTypeParameterWindow().
void GUIParameterTableWindow::mkItem (const char * name, bool dynamic, ValueSource< int > * src)
Adds a row which obtains its value from an integer-ValueSource.
Parameters
[in] name The name of the row entry
[in] dynamic Information whether the entry is dynamic
[in] src The value source to use
Definition at line 189 of file GUIParameterTableWindow.cpp.
References myCurrentPos, myItems, and myTable.
void GUIParameterTableWindow::mkItem (const char * name, bool dynamic, ValueSource< SUMOReal > * src)
Adds a row which obtains its value from an SUMOReal-ValueSource.
Parameters
[in] name The name of the row entry
[in] dynamic Information whether the entry is dynamic
[in] src The value source to use
Definition at line 197 of file GUIParameterTableWindow.cpp.
References myCurrentPos, myItems, and myTable.
void GUIParameterTableWindow::mkItem (const char * name, bool dynamic, std::string value)
Adds a row which shows a string-value.
Parameters
[in] name The name of the row entry
[in] dynamic Information whether the entry is dynamic
[in] value The value to show
Todo:
the dynamic-parameter is obsolete(?)
Definition at line 205 of file GUIParameterTableWindow.cpp.
References myCurrentPos, myItems, and myTable.
void GUIParameterTableWindow::mkItem (const char * name, bool dynamic, unsigned value)
Adds a row which shows a unsigned-value.
Parameters
[in] name The name of the row entry
[in] dynamic Information whether the entry is dynamic
[in] value The value to show
Todo:
the dynamic-parameter is obsolete
Definition at line 222 of file GUIParameterTableWindow.cpp.
References myCurrentPos, myItems, and myTable.
void GUIParameterTableWindow::mkItem (const char * name, bool dynamic, int value)
Adds a row which shows a integer-value.
Parameters
[in] name The name of the row entry
[in] dynamic Information whether the entry is dynamic
[in] value The value to show
Todo:
the dynamic-parameter is obsolete
Definition at line 230 of file GUIParameterTableWindow.cpp.
References myCurrentPos, myItems, and myTable.
void GUIParameterTableWindow::mkItem (const char * name, bool dynamic, long long int value)
Adds a row which shows a 64 bit integer-value.
Parameters
[in] name The name of the row entry
[in] dynamic Information whether the entry is dynamic
[in] value The value to show
Todo:
the dynamic-parameter is obsolete
Definition at line 238 of file GUIParameterTableWindow.cpp.
References myCurrentPos, myItems, and myTable.
void GUIParameterTableWindow::mkItem (const char * name, bool dynamic, SUMOReal value)
Adds a row which shows a SUMOReal-value.
Parameters
[in] name The name of the row entry
[in] dynamic Information whether the entry is dynamic
[in] value The value to show
Todo:
the dynamic-parameter is obsolete
Definition at line 214 of file GUIParameterTableWindow.cpp.
References myCurrentPos, myItems, and myTable.
long GUIParameterTableWindow::onRightButtonPress (FXObject * sender, FXSelector sel, void * data)
Shows a popup.
Callback for right-mouse-button pressing event. Obtains the selected row and determines whether it is dynamic. If so, a popup-menu which allows to open a tracker for this value is built and shown.
See also
GUIParameterTableItemInterface
GUIParam_PopupMenuInterface
Definition at line 150 of file GUIParameterTableWindow.cpp.
References GUIParameterTableItemInterface::dynamic(), GUIParameterTableItemInterface::getName(), GUIParameterTableItemInterface::getSUMORealSourceCopy(), MID_OPENTRACKER, myApplication, myItems, myObject, and myTable.
long GUIParameterTableWindow::onSimStep (FXObject * , FXSelector , void *)
Updates the table due to a simulation step.
Definition at line 129 of file GUIParameterTableWindow.cpp.
References updateTable().
long GUIParameterTableWindow::onTableDeselected (FXObject * , FXSelector , void *)
Does nothing.
Todo:
Recheck whether this is needed (to override FXTable-behaviour?)
Definition at line 144 of file GUIParameterTableWindow.cpp.
long GUIParameterTableWindow::onTableSelected (FXObject * , FXSelector , void *)
Does nothing.
Todo:
Recheck whether this is needed (to override FXTable-behaviour?)
Definition at line 138 of file GUIParameterTableWindow.cpp.
void GUIParameterTableWindow::removeObject (GUIGlObject *const o)
Lets this window know the object shown is being deleted.
Parameters
[in] o The deleted (shown) object
Definition at line 122 of file GUIParameterTableWindow.cpp.
References myLock, and myObject.
static void GUIParameterTableWindow::updateAll () inline static
Updates all instances.
Definition at line 218 of file GUIParameterTableWindow.h.
References myContainer, myGlobalContainerLock, and updateTable().
void GUIParameterTableWindow::updateTable () protected
Updates the table.
Goes through all entries and updates them using GUIParameterTableItemInterface::update.
See also
GUIParameterTableItemInterface::update
Definition at line 246 of file GUIParameterTableWindow.cpp.
References myItems, myLock, and myObject.
Referenced by onSimStep(), and updateAll().
Field Documentation
GUIMainWindow* GUIParameterTableWindow::myApplication private
The main application window.
Definition at line 246 of file GUIParameterTableWindow.h.
Referenced by closeBuilding(), onRightButtonPress(), and ~GUIParameterTableWindow().
std::vector< GUIParameterTableWindow * > GUIParameterTableWindow::myContainer static protected
The container of items that shall be updated.
Definition at line 236 of file GUIParameterTableWindow.h.
Referenced by updateAll(), and ~GUIParameterTableWindow().
unsigned GUIParameterTableWindow::myCurrentPos private
The index of the next row to add - used while building.
Definition at line 252 of file GUIParameterTableWindow.h.
Referenced by mkItem().
MFXMutex GUIParameterTableWindow::myGlobalContainerLock static protected
The mutex used to avoid concurrent updates of the instance container.
Definition at line 233 of file GUIParameterTableWindow.h.
Referenced by updateAll(), and ~GUIParameterTableWindow().
std::vector<GUIParameterTableItemInterface*> GUIParameterTableWindow::myItems private
The list of table rows.
Definition at line 249 of file GUIParameterTableWindow.h.
Referenced by mkItem(), onRightButtonPress(), updateTable(), and ~GUIParameterTableWindow().
MFXMutex GUIParameterTableWindow::myLock mutable private
A lock assuring save updates in case of object deletion.
Definition at line 255 of file GUIParameterTableWindow.h.
Referenced by removeObject(), updateTable(), and ~GUIParameterTableWindow().
GUIGlObject* GUIParameterTableWindow::myObject private
The object to get the information from.
Definition at line 240 of file GUIParameterTableWindow.h.
Referenced by onRightButtonPress(), removeObject(), updateTable(), and ~GUIParameterTableWindow().
FXTable* GUIParameterTableWindow::myTable private
The table to display the information in.
Definition at line 243 of file GUIParameterTableWindow.h.
Referenced by mkItem(), and onRightButtonPress().
The documentation for this class was generated from the following files:
GUIParameterTableWindow.h
GUIParameterTableWindow.cpp