SUMO - Simulation of Urban MObility: MSLCM_DK2008 Class Reference
MSLCM_DK2008 Class Reference
A lane change model developed by D. Krajzewicz between 2004 and 2010.
#include <MSLCM_DK2008.h>
Public Types
enum MyLCAEnum {
LCA_AMBLOCKINGLEADER = 1 << 16, LCA_AMBLOCKINGFOLLOWER = 1 << 17, LCA_MRIGHT = 1 << 18, LCA_MLEFT = 1 << 19,
LCA_AMBLOCKINGFOLLOWER_DONTBRAKE = 1 << 21, LCA_AMBACKBLOCKER = 1 << 26, LCA_AMBACKBLOCKER_STANDING = 1 << 27
}
Public Member Functions
bool alreadyChanged () const
reset the flag whether a vehicle already moved to false
virtual void changed ()
void changedToOpposite ()
called when a vehicle changes between lanes in opposite directions
void cleanupShadowLane ()
virtual bool debugVehicle () const
whether the current vehicles shall be debugged
virtual StateAndDist decideDirection (StateAndDist sd1, StateAndDist sd2) const
decide in which direction to move in case both directions are desirable
void endLaneChangeManeuver (const MSMoveReminder::Notification reason=MSMoveReminder::NOTIFICATION_LANE_CHANGE)
SUMOReal getAngleOffset () const
return the angle offset during a continuous change maneuver
int getLaneChangeDirection () const
return the direction of the current lane change maneuver
SUMOTime getLastLaneChangeOffset () const
SUMOReal getLateralSpeed () const
return the lateral speed of the current lane change maneuver
int getOwnState () const
int getShadowDirection () const
return the direction in which the current shadow lane lies
const std::vector< MSLane * > & getShadowFurtherLanes () const
const std::vector< SUMOReal > & getShadowFurtherLanesPosLat () const
MSLane * getShadowLane () const
Returns the lane the vehicles shadow is on during continuous/sublane lane change.
MSLane * getShadowLane (const MSLane *lane) const
return the shadow lane for the given lane
virtual void * inform (void *info, MSVehicle *sender)
bool isChangingLanes () const
return true if the vehicle currently performs a lane change maneuver
bool isOpposite () const
MSLCM_DK2008 (MSVehicle &v)
bool pastMidpoint () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
virtual SUMOReal patchSpeed (const SUMOReal min, const SUMOReal wanted, const SUMOReal max, const MSCFModel &cfModel)
Called to adapt the speed in order to allow a lane change.
virtual void prepareStep ()
void primaryLaneChanged (MSLane *source, MSLane *target, int direction)
called once when the vehicles primary lane changes
SUMOTime remainingTime () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
void removeShadowApproachingInformation () const
void resetChanged ()
reset the flag whether a vehicle already moved to false
virtual void saveBlockerLength (SUMOReal length)
reserve space at the end of the lane to avoid dead locks
void setNoShadowPartialOccupator (MSLane *lane)
virtual void setOwnState (int state)
void setShadowApproachingInformation (MSLink *link) const
set approach information for the shadow vehicle
void setShadowLane (MSLane *lane)
set the shadow lane
void setShadowPartialOccupator (MSLane *lane)
bool startLaneChangeManeuver (MSLane *source, MSLane *target, int direction)
start the lane change maneuver and return whether it continues
void unchanged ()
bool updateCompletion ()
virtual void updateExpectedSublaneSpeeds (const MSLeaderInfo &ahead, int sublaneOffset, int laneIndex)
update expected speeds for each sublane of the current edge
void updateShadowLane ()
int wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > &leader, const std::pair< MSVehicle *, SUMOReal > &neighLead, const std::pair< MSVehicle *, SUMOReal > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked)
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
virtual int wantsChangeSublane (int laneOffset, const MSLeaderDistanceInfo &leaders, const MSLeaderDistanceInfo &followers, const MSLeaderDistanceInfo &blockers, const MSLeaderDistanceInfo &neighLeaders, const MSLeaderDistanceInfo &neighFollowers, const MSLeaderDistanceInfo &neighBlockers, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked, SUMOReal &latDist, int &blocked)
virtual ~MSLCM_DK2008 ()
Static Public Member Functions
static MSAbstractLaneChangeModel * build (LaneChangeModel lcm, MSVehicle &vehicle)
Factory method for instantiating new lane changing models.
static void initGlobalOptions (const OptionsCont &oc)
init global model parameters
Protected Types
typedef std::pair< SUMOReal, int > Info
Protected Member Functions
bool amBlockingFollower ()
bool amBlockingFollowerNB ()
bool amBlockingFollowerPlusNB ()
bool amBlockingLeader ()
bool cancelRequest (int state)
whether the influencer cancels the given request
virtual bool congested (const MSVehicle *const neighLeader)
bool currentDistAllows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist)
bool currentDistDisallows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist)
void informBlocker (MSAbstractLaneChangeModel::MSLCMessager &msgPass, int &blocked, int dir, const std::pair< MSVehicle *, SUMOReal > &neighLead, const std::pair< MSVehicle *, SUMOReal > &neighFollow)
void initLastLaneChangeOffset (int dir)
virtual bool predInteraction (const std::pair< MSVehicle *, SUMOReal > &leader)
virtual int wantsChangeToLeft (MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > &leader, const std::pair< MSVehicle *, SUMOReal > &neighLead, const std::pair< MSVehicle *, SUMOReal > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked)
Called to examine whether the vehicle wants to change to left This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
virtual int wantsChangeToRight (MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > &leader, const std::pair< MSVehicle *, SUMOReal > &neighLead, const std::pair< MSVehicle *, SUMOReal > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked)
Called to examine whether the vehicle wants to change to right This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
Protected Attributes
bool myAlreadyChanged
whether the vehicle has already moved this step
const MSCFModel & myCarFollowModel
The vehicle's car following model.
SUMOReal myChangeProbability
bool myDontBrake
SUMOReal myLaneChangeCompletion
progress of the lane change maneuver 0:started, 1:complete
int myLaneChangeDirection
direction of the lane change maneuver -1 means right, 1 means left
SUMOReal myLateralspeed
The lateral offset during a continuous LaneChangeManeuver.
SUMOReal myLeadingBlockerLength
SUMOReal myLeftSpace
const LaneChangeModel myModel
the type of this model
std::vector< MSLane * > myNoPartiallyOccupatedByShadow
int myOwnState
The current state of the vehicle.
std::vector< MSLane * > myPartiallyOccupatedByShadow
list of lanes where the shadow vehicle is partial occupator
std::vector< MSLane * > myShadowFurtherLanes
std::vector< SUMOReal > myShadowFurtherLanesPosLat
MSLane * myShadowLane
A lane that is partially occupied by the front of the vehicle but that is not the primary lane.
MSVehicle & myVehicle
The vehicle this lane-changer belongs to.
std::vector< SUMOReal > myVSafes
Static Protected Attributes
static bool myAllowOvertakingRight
whether overtaking on the right is permitted
static bool myLCOutput
whether to record lane-changing
Detailed Description
A lane change model developed by D. Krajzewicz between 2004 and 2010.
Definition at line 47 of file MSLCM_DK2008.h.
Member Typedef Documentation
typedef std::pair<SUMOReal, int> MSLCM_DK2008::Info protected
Definition at line 153 of file MSLCM_DK2008.h.
Member Enumeration Documentation
enum MSLCM_DK2008::MyLCAEnum
Enumerator
LCA_AMBLOCKINGLEADER
LCA_AMBLOCKINGFOLLOWER
LCA_MRIGHT
LCA_MLEFT
LCA_AMBLOCKINGFOLLOWER_DONTBRAKE
LCA_AMBACKBLOCKER
LCA_AMBACKBLOCKER_STANDING
Definition at line 50 of file MSLCM_DK2008.h.
Constructor & Destructor Documentation
MSLCM_DK2008::MSLCM_DK2008 (MSVehicle & v)
Definition at line 66 of file MSLCM_DK2008.cpp.
MSLCM_DK2008::~MSLCM_DK2008 () virtual
Definition at line 71 of file MSLCM_DK2008.cpp.
References changed().
Member Function Documentation
bool MSAbstractLaneChangeModel::alreadyChanged () const inline inherited
reset the flag whether a vehicle already moved to false
Definition at line 324 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myAlreadyChanged.
Referenced by MSLaneChanger::change().
bool MSLCM_DK2008::amBlockingFollower () inline protected
Definition at line 137 of file MSLCM_DK2008.h.
References LCA_AMBLOCKINGFOLLOWER, and MSAbstractLaneChangeModel::myOwnState.
bool MSLCM_DK2008::amBlockingFollowerNB () inline protected
Definition at line 140 of file MSLCM_DK2008.h.
References LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, and MSAbstractLaneChangeModel::myOwnState.
bool MSLCM_DK2008::amBlockingFollowerPlusNB () inline protected
Definition at line 143 of file MSLCM_DK2008.h.
References LCA_AMBLOCKINGFOLLOWER, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, and MSAbstractLaneChangeModel::myOwnState.
Referenced by wantsChangeToLeft(), and wantsChangeToRight().
bool MSLCM_DK2008::amBlockingLeader () inline protected
Definition at line 134 of file MSLCM_DK2008.h.
References LCA_AMBLOCKINGLEADER, and MSAbstractLaneChangeModel::myOwnState.
MSAbstractLaneChangeModel * MSAbstractLaneChangeModel::build (LaneChangeModel lcm, MSVehicle & vehicle) static inherited
Factory method for instantiating new lane changing models.
Parameters
[in] lcm The type of model to build
[in] vehicle The vehicle for which this model shall be built
Definition at line 63 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLateralResolution, LCM_DEFAULT, LCM_DK2008, LCM_JE2013, LCM_LC2013, LCM_SL2015, and toString().
Referenced by MSVehicle::MSVehicle(), and MSAbstractLaneChangeModel::StateAndDist::StateAndDist().
bool MSAbstractLaneChangeModel::cancelRequest (int state) protected inherited
whether the influencer cancels the given request
Definition at line 244 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::influenceChangeDecision(), and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), and MSAbstractLaneChangeModel::isOpposite().
void MSLCM_DK2008::changed () virtual
Implements MSAbstractLaneChangeModel.
Definition at line 620 of file MSLCM_DK2008.cpp.
References myChangeProbability, myDontBrake, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, and myVSafes.
Referenced by patchSpeed(), and ~MSLCM_DK2008().
void MSAbstractLaneChangeModel::changedToOpposite () inherited
called when a vehicle changes between lanes in opposite directions
Definition at line 350 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myAlreadyChanged, and MSAbstractLaneChangeModel::myAmOpposite.
Referenced by MSAbstractLaneChangeModel::debugVehicle(), MSVehicle::executeMove(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
void MSAbstractLaneChangeModel::cleanupShadowLane () inherited
Definition at line 224 of file MSAbstractLaneChangeModel.cpp.
References MSBaseVehicle::getID(), MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::myShadowFurtherLanes, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, MSLane::resetPartialOccupation(), and SIMTIME.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::resetChanged(), and MSVehicle::~MSVehicle().
bool MSAbstractLaneChangeModel::congested (const MSVehicle *const neighLeader) protected virtual inherited
Definition at line 108 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::congested(), MSVehicle::getLane(), MSLane::getSpeedLimit(), and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSAbstractLaneChangeModel::isOpposite(), wantsChangeToLeft(), and wantsChangeToRight().
bool MSLCM_DK2008::currentDistAllows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist) inline protected
Definition at line 149 of file MSLCM_DK2008.h.
References abs.
Referenced by wantsChangeToLeft(), and wantsChangeToRight().
bool MSLCM_DK2008::currentDistDisallows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist) inline protected
Definition at line 146 of file MSLCM_DK2008.h.
References abs.
Referenced by wantsChangeToLeft(), and wantsChangeToRight().
virtual bool MSAbstractLaneChangeModel::debugVehicle () const inline virtual inherited
whether the current vehicles shall be debugged
Reimplemented in MSLCM_JE2013, MSLCM_SL2015, and MSLCM_LC2013.
Definition at line 251 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::changedToOpposite().
Referenced by MSLaneChangerSublane::change().
virtual StateAndDist MSAbstractLaneChangeModel::decideDirection (StateAndDist sd1, StateAndDist sd2) const inline virtual inherited
decide in which direction to move in case both directions are desirable
Reimplemented in MSLCM_SL2015.
Definition at line 223 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::changed(), MSAbstractLaneChangeModel::inform(), max, min, MSAbstractLaneChangeModel::myModel, MSAbstractLaneChangeModel::patchSpeed(), SUMOReal, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::change().
void MSAbstractLaneChangeModel::endLaneChangeManeuver (const MSMoveReminder::Notification reason = MSMoveReminder::NOTIFICATION_LANE_CHANGE) inherited
Definition at line 191 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::cleanupShadowLane(), MSVehicle::fixPosition(), MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::myVehicle, MSVehicle::switchOffSignal(), UNUSED_PARAMETER, MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSVehicleTransfer::add(), MSLaneChanger::continueChange(), MSVehicle::executeMove(), MSAbstractLaneChangeModel::resetChanged(), and MSAbstractLaneChangeModel::updateShadowLane().
SUMOReal MSAbstractLaneChangeModel::getAngleOffset () const inherited
return the angle offset during a continuous change maneuver
Definition at line 321 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::pastMidpoint(), STEPS2TIME, and SUMOReal.
Referenced by MSAbstractLaneChangeModel::getLaneChangeDirection().
int MSAbstractLaneChangeModel::getLaneChangeDirection () const inline inherited
return the direction of the current lane change maneuver
Definition at line 308 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::myLaneChangeDirection, and SUMOReal.
Referenced by MSLaneChanger::continueChange().
SUMOTime MSAbstractLaneChangeModel::getLastLaneChangeOffset () const inline inherited
Definition at line 289 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLastLaneChangeOffset.
SUMOReal MSAbstractLaneChangeModel::getLateralSpeed () const inline inherited
return the lateral speed of the current lane change maneuver
Definition at line 319 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLateralspeed.
Referenced by MSLaneChanger::continueChange().
int MSAbstractLaneChangeModel::getOwnState () const inline inherited
Definition at line 148 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myOwnState.
Referenced by MSLaneChanger::change(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), and MSVehicle::setBlinkerInformation().
int MSAbstractLaneChangeModel::getShadowDirection () const inherited
return the direction in which the current shadow lane lies
Definition at line 304 of file MSAbstractLaneChangeModel.cpp.
References MSLane::getEdge(), MSLane::getIndex(), MSVehicle::getLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, MSAbstractLaneChangeModel::pastMidpoint(), and SUMOReal.
Referenced by MSLaneChanger::continueChange(), MSVehicle::executeMove(), MSAbstractLaneChangeModel::getLaneChangeDirection(), and GUIVehicle::selectBlockingFoes().
const std::vector<MSLane*>& MSAbstractLaneChangeModel::getShadowFurtherLanes () const inline inherited
Definition at line 281 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowFurtherLanes.
Referenced by MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), and MSVehicle::getLatOffset().
const std::vector<SUMOReal>& MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat () const inline inherited
Definition at line 285 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat.
Referenced by MSVehicle::getCenterOnEdge(), and MSVehicle::getLatOffset().
MSLane* MSAbstractLaneChangeModel::getShadowLane () const inline inherited
Returns the lane the vehicles shadow is on during continuous/sublane lane change.
Returns
The vehicle's shadow lane
Definition at line 269 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowLane.
Referenced by MSVehicle::checkRewindLinkLanes(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::executeMove(), MSVehicle::getBackPosition(), MSVehicle::getCenterOnEdge(), GUIVehicle::getParameterWindow(), MSVehicle::isFrontOnLane(), MSVehicle::planMoveInternal(), GUIVehicle::selectBlockingFoes(), MSLaneChangerSublane::startChangeSublane(), MSLaneChangerSublane::updateChanger(), and MSAbstractLaneChangeModel::updateShadowLane().
MSLane * MSAbstractLaneChangeModel::getShadowLane (const MSLane * lane) const inherited
return the shadow lane for the given lane
Definition at line 202 of file MSAbstractLaneChangeModel.cpp.
References MSBaseVehicle::getID(), MSVehicle::getLateralOverlap(), MSVehicle::getLateralPositionOnLane(), MSLane::getParallelLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, SIMTIME, and SUMOReal.
void * MSLCM_DK2008::inform (void * info, MSVehicle * sender) virtual
Implements MSAbstractLaneChangeModel.
Definition at line 610 of file MSLCM_DK2008.cpp.
References MSAbstractLaneChangeModel::myOwnState.
void MSLCM_DK2008::informBlocker (MSAbstractLaneChangeModel::MSLCMessager & msgPass, int & blocked, int dir, const std::pair< MSVehicle *, SUMOReal > & neighLead, const std::pair< MSVehicle *, SUMOReal > & neighFollow) protected
Definition at line 631 of file MSLCM_DK2008.cpp.
References ACCEL2DIST, MSCFModel::followSpeed(), MSVehicle::getCarFollowModel(), MSCFModel::getMaxDecel(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSAbstractLaneChangeModel::MSLCMessager::informNeighFollower(), MSAbstractLaneChangeModel::MSLCMessager::informNeighLeader(), LCA_AMBLOCKINGFOLLOWER, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, LCA_AMBLOCKINGLEADER, LCA_BLOCKED_BY_FOLLOWER, LCA_BLOCKED_BY_LEADER, MAX2(), MSAbstractLaneChangeModel::myCarFollowModel, MSAbstractLaneChangeModel::myVehicle, SPEED2DIST, and SUMOReal.
Referenced by wantsChangeToLeft(), and wantsChangeToRight().
void MSAbstractLaneChangeModel::initGlobalOptions (const OptionsCont & oc) static inherited
init global model parameters
Definition at line 56 of file MSAbstractLaneChangeModel.cpp.
References OptionsCont::getBool(), OptionsCont::isSet(), MSAbstractLaneChangeModel::myAllowOvertakingRight, and MSAbstractLaneChangeModel::myLCOutput.
Referenced by MSFrame::setMSGlobals(), and MSAbstractLaneChangeModel::StateAndDist::StateAndDist().
void MSAbstractLaneChangeModel::initLastLaneChangeOffset (int dir) protected inherited
Definition at line 251 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myLastLaneChangeOffset.
Referenced by MSAbstractLaneChangeModel::primaryLaneChanged().
bool MSAbstractLaneChangeModel::isChangingLanes () const inline inherited
return true if the vehicle currently performs a lane change maneuver
Definition at line 303 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeCompletion, and NUMERICAL_EPS.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), MSVehicle::computeAngle(), MSLaneChanger::continueChange(), MSLane::detectCollisionBetween(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::getBackPosition(), MSVehicle::getPosition(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), and MSAbstractLaneChangeModel::updateShadowLane().
bool MSAbstractLaneChangeModel::isOpposite () const inline inherited
Definition at line 372 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::cancelRequest(), MSAbstractLaneChangeModel::congested(), MSAbstractLaneChangeModel::myAmOpposite, and MSAbstractLaneChangeModel::predInteraction().
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLaneChanger::changeOpposite(), MSVehicle::checkRewindLinkLanes(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), and MSVehicle::planMoveInternal().
bool MSAbstractLaneChangeModel::pastMidpoint () const inline inherited
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 295 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeCompletion, and MSAbstractLaneChangeModel::remainingTime().
Referenced by MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getShadowDirection(), and MSAbstractLaneChangeModel::updateCompletion().
SUMOReal MSLCM_DK2008::patchSpeed (const SUMOReal min, const SUMOReal wanted, const SUMOReal max, const MSCFModel & cfModel) virtual
Called to adapt the speed in order to allow a lane change.
Parameters
min The minimum resulting speed
wanted The aspired speed of the car following model
max The maximum resulting speed
cfModel The model used
Returns
the new speed of the vehicle as proposed by the lane changer
Implements MSAbstractLaneChangeModel.
Definition at line 517 of file MSLCM_DK2008.cpp.
References bla, changed(), MSEdge::EDGEFUNCTION_INTERNAL, gDebugSelectedVehicle, MSVehicle::getCarFollowModel(), MSLane::getEdge(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSEdge::getLanes(), MSVehicleType::getMinGap(), MSEdge::getPurpose(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), LCA_AMBACKBLOCKER, LCA_AMBACKBLOCKER_STANDING, LCA_AMBLOCKINGFOLLOWER, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, LCA_AMBLOCKINGLEADER, LCA_BLOCKED, LCA_BLOCKED_BY_FOLLOWER, LCA_BLOCKED_BY_LEADER, LCA_WANTS_LANECHANGE, MAX2(), MSCFModel::maxNextSpeed(), min, MIN2(), myDontBrake, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, myVSafes, MSCFModel::stopSpeed(), and SUMOReal.
bool MSAbstractLaneChangeModel::predInteraction (const std::pair< MSVehicle *, SUMOReal > & leader) protected virtual inherited
Definition at line 128 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getSpeed(), MSCFModel::interactionGap(), MSAbstractLaneChangeModel::myCarFollowModel, and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSAbstractLaneChangeModel::isOpposite(), wantsChangeToLeft(), and wantsChangeToRight().
void MSLCM_DK2008::prepareStep () virtual
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 660 of file MSLCM_DK2008.cpp.
References myChangeProbability, myDontBrake, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, and myVSafes.
void MSAbstractLaneChangeModel::primaryLaneChanged (MSLane * source, MSLane * target, int direction) inherited
called once when the vehicles primary lane changes
Definition at line 160 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changed(), OutputDevice::closeTag(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtLaneChange(), OutputDevice::getDeviceByOption(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getSpeed(), MSAbstractLaneChangeModel::initLastLaneChangeOffset(), LCA_LEFT, LCA_RIGHT, MSVehicle::leaveLane(), MSLane::leftByLaneChange(), MSAbstractLaneChangeModel::myLCOutput, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, MSMoveReminder::NOTIFICATION_LANE_CHANGE, OutputDevice::openTag(), SUMO_ATTR_DIR, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_SPEED, SUMO_ATTR_TIME, SUMO_ATTR_TO, time2string(), toString(), and OutputDevice::writeAttr().
Referenced by MSLaneChanger::continueChange(), MSAbstractLaneChangeModel::setNoShadowPartialOccupator(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
SUMOTime MSAbstractLaneChangeModel::remainingTime () const inherited
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 328 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLaneChangeDuration, and MSAbstractLaneChangeModel::myLaneChangeCompletion.
Referenced by MSAbstractLaneChangeModel::pastMidpoint().
void MSAbstractLaneChangeModel::removeShadowApproachingInformation () const inherited
Definition at line 340 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myApproachedByShadow, and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSVehicle::removeApproachingInformation(), and MSAbstractLaneChangeModel::setNoShadowPartialOccupator().
void MSAbstractLaneChangeModel::resetChanged () inline inherited
reset the flag whether a vehicle already moved to false
Definition at line 329 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::myAlreadyChanged, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSAbstractLaneChangeModel::startLaneChangeManeuver(), MSAbstractLaneChangeModel::updateCompletion(), and MSAbstractLaneChangeModel::updateShadowLane().
Referenced by MSVehicle::planMove().
virtual void MSAbstractLaneChangeModel::saveBlockerLength (SUMOReal length) inline virtual inherited
reserve space at the end of the lane to avoid dead locks
Reimplemented in MSLCM_SL2015, MSLCM_LC2013, and MSLCM_JE2013.
Definition at line 353 of file MSAbstractLaneChangeModel.h.
References UNUSED_PARAMETER.
Referenced by MSLCM_JE2013::saveBlockerLength(), and MSLCM_LC2013::saveBlockerLength().
void MSAbstractLaneChangeModel::setNoShadowPartialOccupator (MSLane * lane) inline inherited
Definition at line 361 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::primaryLaneChanged(), MSAbstractLaneChangeModel::removeShadowApproachingInformation(), and MSAbstractLaneChangeModel::setShadowApproachingInformation().
Referenced by MSVehicle::enterLaneAtLaneChange().
virtual void MSAbstractLaneChangeModel::setOwnState (int state) inline virtual inherited
Reimplemented in MSLCM_SL2015.
Definition at line 152 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myOwnState.
Referenced by MSLaneChangerSublane::change(), and MSLaneChanger::change().
void MSAbstractLaneChangeModel::setShadowApproachingInformation (MSLink * link) const inherited
set approach information for the shadow vehicle
Definition at line 334 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myApproachedByShadow.
Referenced by MSVehicle::checkRewindLinkLanes(), and MSAbstractLaneChangeModel::setNoShadowPartialOccupator().
void MSAbstractLaneChangeModel::setShadowLane (MSLane * lane) inline inherited
set the shadow lane
Definition at line 277 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowLane.
void MSAbstractLaneChangeModel::setShadowPartialOccupator (MSLane * lane) inline inherited
Definition at line 357 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myPartiallyOccupatedByShadow.
bool MSAbstractLaneChangeModel::startLaneChangeManeuver (MSLane * source, MSLane * target, int direction) inherited
start the lane change maneuver and return whether it continues
Definition at line 141 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changedToOpposite(), DELTA_T, MSLane::getCenterOnEdge(), MSLane::getEdge(), MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::myLateralspeed, MSAbstractLaneChangeModel::myVehicle, MSAbstractLaneChangeModel::primaryLaneChanged(), SUMOReal, MSVehicle::switchOffSignal(), MSVehicle::switchOnSignal(), MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSLaneChanger::changeOpposite(), MSAbstractLaneChangeModel::resetChanged(), MSLaneChanger::startChange(), and MSLaneChangerSublane::startChangeSublane().
void MSAbstractLaneChangeModel::unchanged () inline inherited
Definition at line 258 of file MSAbstractLaneChangeModel.h.
References DELTA_T, and MSAbstractLaneChangeModel::myLastLaneChangeOffset.
Referenced by MSLaneChanger::registerUnchanged().
bool MSAbstractLaneChangeModel::updateCompletion () inherited
Definition at line 183 of file MSAbstractLaneChangeModel.cpp.
References DELTA_T, MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::pastMidpoint(), and SUMOReal.
Referenced by MSLaneChanger::continueChange(), and MSAbstractLaneChangeModel::resetChanged().
virtual void MSAbstractLaneChangeModel::updateExpectedSublaneSpeeds (const MSLeaderInfo & ahead, int sublaneOffset, int laneIndex) inline virtual inherited
update expected speeds for each sublane of the current edge
Reimplemented in MSLCM_SL2015.
Definition at line 215 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::change().
void MSAbstractLaneChangeModel::updateShadowLane () inherited
Definition at line 260 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::endLaneChangeManeuver(), gDebugFlag4, MSVehicle::getFurtherLanes(), MSVehicle::getFurtherLanesPosLat(), MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getLateralOverlap(), MSVehicle::getLateralPositionOnLane(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::myShadowFurtherLanes, MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, MSLane::resetPartialOccupation(), MSLane::setPartialOccupation(), SIMTIME, time2string(), toString(), MSVehicle::updateFurtherLanes(), and WRITE_WARNING.
Referenced by MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), MSAbstractLaneChangeModel::resetChanged(), and MSLaneChangerSublane::startChangeSublane().
int MSLCM_DK2008::wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > & leader, const std::pair< MSVehicle *, SUMOReal > & neighLead, const std::pair< MSVehicle *, SUMOReal > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked) virtual
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 76 of file MSLCM_DK2008.cpp.
References UNUSED_PARAMETER, wantsChangeToLeft(), and wantsChangeToRight().
virtual int MSAbstractLaneChangeModel::wantsChangeSublane (int laneOffset, const MSLeaderDistanceInfo & leaders, const MSLeaderDistanceInfo & followers, const MSLeaderDistanceInfo & blockers, const MSLeaderDistanceInfo & neighLeaders, const MSLeaderDistanceInfo & neighFollowers, const MSLeaderDistanceInfo & neighBlockers, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked, SUMOReal & latDist, int & blocked) inline virtual inherited
Reimplemented in MSLCM_SL2015.
Definition at line 185 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChangerSublane::checkChangeSublane().
int MSLCM_DK2008::wantsChangeToLeft (MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > & leader, const std::pair< MSVehicle *, SUMOReal > & neighLead, const std::pair< MSVehicle *, SUMOReal > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked) protected virtual
Called to examine whether the vehicle wants to change to left This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
!!
Definition at line 307 of file MSLCM_DK2008.cpp.
References ACCEL2SPEED, amBlockingFollowerPlusNB(), MSVehicle::LaneQ::bestLaneOffset, bla, MSAbstractLaneChangeModel::congested(), currentDistAllows(), currentDistDisallows(), MSEdge::EDGEFUNCTION_INTERNAL, MSCFModel::followSpeed(), gDebugSelectedVehicle, MSVehicle::getCarFollowModel(), MSLane::getEdge(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSLane::getLength(), MSVehicleType::getLengthWithGap(), MSLane::getLinkCont(), MSCFModel::getMaxDecel(), MSVehicleType::getMaxSpeed(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSEdge::getPurpose(), MSVehicle::getSpeed(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), informBlocker(), JAM_FACTOR2, MSVehicle::LaneQ::lane, LCA_AMBACKBLOCKER, LCA_AMBACKBLOCKER_STANDING, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, LCA_BLOCKED, LCA_COOPERATIVE, LCA_LEFT, LCA_MLEFT, LCA_RIGHT, LCA_SPEEDGAIN, LCA_STAY, LCA_STRATEGIC, LCA_URGENT, MSVehicle::LaneQ::length, LOOK_FORWARD_FAR, LOOK_FORWARD_NEAR, LOOK_FORWARD_SPEED_DIVIDER, MAX2(), MIN2(), MSAbstractLaneChangeModel::myCarFollowModel, myChangeProbability, myDontBrake, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, myVSafes, MSVehicle::LaneQ::occupation, MSAbstractLaneChangeModel::predInteraction(), SUMO_const_haltingSpeed, SUMOReal, TS, and UNUSED_PARAMETER.
Referenced by wantsChange().
int MSLCM_DK2008::wantsChangeToRight (MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > & leader, const std::pair< MSVehicle *, SUMOReal > & neighLead, const std::pair< MSVehicle *, SUMOReal > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked) protected virtual
Called to examine whether the vehicle wants to change to right This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
!!
Definition at line 95 of file MSLCM_DK2008.cpp.
References ACCEL2SPEED, amBlockingFollowerPlusNB(), MSVehicle::LaneQ::bestLaneOffset, bla, MSAbstractLaneChangeModel::congested(), currentDistAllows(), currentDistDisallows(), MSEdge::EDGEFUNCTION_INTERNAL, MSCFModel::followSpeed(), gDebugSelectedVehicle, MSVehicle::getCarFollowModel(), MSLane::getEdge(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSLane::getLength(), MSVehicleType::getLengthWithGap(), MSLane::getLinkCont(), MSCFModel::getMaxDecel(), MSVehicleType::getMaxSpeed(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSEdge::getPurpose(), MSVehicle::getSpeed(), MSLane::getSpeedLimit(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), informBlocker(), JAM_FACTOR2, MSVehicle::LaneQ::lane, LCA_AMBACKBLOCKER, LCA_AMBACKBLOCKER_STANDING, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, LCA_BLOCKED, LCA_COOPERATIVE, LCA_LEFT, LCA_MRIGHT, LCA_RIGHT, LCA_SPEEDGAIN, LCA_STAY, LCA_STRATEGIC, LCA_URGENT, MSVehicle::LaneQ::length, LOOK_FORWARD_FAR, LOOK_FORWARD_NEAR, LOOK_FORWARD_SPEED_DIVIDER, MAX2(), MIN2(), MSAbstractLaneChangeModel::myCarFollowModel, myChangeProbability, myDontBrake, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, myVSafes, MSVehicle::LaneQ::occupation, MSAbstractLaneChangeModel::predInteraction(), SUMO_const_haltingSpeed, SUMOReal, TS, and UNUSED_PARAMETER.
Referenced by wantsChange().
Field Documentation
bool MSAbstractLaneChangeModel::myAllowOvertakingRight static protected inherited
whether overtaking on the right is permitted
Definition at line 430 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::checkStrategicChange(), MSLCM_JE2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), and MSAbstractLaneChangeModel::initGlobalOptions().
bool MSAbstractLaneChangeModel::myAlreadyChanged protected inherited
whether the vehicle has already moved this step
Definition at line 402 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::alreadyChanged(), MSAbstractLaneChangeModel::changedToOpposite(), and MSAbstractLaneChangeModel::resetChanged().
const MSCFModel& MSAbstractLaneChangeModel::myCarFollowModel protected inherited
The vehicle's car following model.
Definition at line 413 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::checkStrategicChange(), informBlocker(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSAbstractLaneChangeModel::predInteraction(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), wantsChangeToLeft(), and wantsChangeToRight().
SUMOReal MSLCM_DK2008::myChangeProbability protected
Definition at line 158 of file MSLCM_DK2008.h.
Referenced by changed(), prepareStep(), wantsChangeToLeft(), and wantsChangeToRight().
bool MSLCM_DK2008::myDontBrake protected
Definition at line 164 of file MSLCM_DK2008.h.
Referenced by changed(), patchSpeed(), prepareStep(), wantsChangeToLeft(), and wantsChangeToRight().
SUMOReal MSAbstractLaneChangeModel::myLaneChangeCompletion protected inherited
progress of the lane change maneuver 0:started, 1:complete
Definition at line 393 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::pastMidpoint(), MSAbstractLaneChangeModel::remainingTime(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), and MSAbstractLaneChangeModel::updateCompletion().
int MSAbstractLaneChangeModel::myLaneChangeDirection protected inherited
direction of the lane change maneuver -1 means right, 1 means left
Definition at line 396 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getLaneChangeDirection(), MSAbstractLaneChangeModel::getShadowDirection(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
SUMOReal MSAbstractLaneChangeModel::myLateralspeed protected inherited
The lateral offset during a continuous LaneChangeManeuver.
Definition at line 399 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getLateralSpeed(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
bool MSAbstractLaneChangeModel::myLCOutput static protected inherited
whether to record lane-changing
Definition at line 433 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::initGlobalOptions(), and MSAbstractLaneChangeModel::primaryLaneChanged().
SUMOReal MSLCM_DK2008::myLeadingBlockerLength protected
Definition at line 160 of file MSLCM_DK2008.h.
Referenced by changed(), patchSpeed(), prepareStep(), wantsChangeToLeft(), and wantsChangeToRight().
SUMOReal MSLCM_DK2008::myLeftSpace protected
Definition at line 161 of file MSLCM_DK2008.h.
Referenced by changed(), patchSpeed(), prepareStep(), wantsChangeToLeft(), and wantsChangeToRight().
const LaneChangeModel MSAbstractLaneChangeModel::myModel protected inherited
the type of this model
Definition at line 416 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::decideDirection(), MSAbstractLaneChangeModel::updateExpectedSublaneSpeeds(), MSAbstractLaneChangeModel::wantsChange(), and MSAbstractLaneChangeModel::wantsChangeSublane().
std::vector<MSLane*> MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow protected inherited
Definition at line 423 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getShadowLane(), and MSAbstractLaneChangeModel::setNoShadowPartialOccupator().
int MSAbstractLaneChangeModel::myOwnState protected inherited
The current state of the vehicle.
Definition at line 390 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), amBlockingFollower(), MSLCM_JE2013::amBlockingFollower(), MSLCM_LC2013::amBlockingFollower(), MSLCM_SL2015::amBlockingFollower(), amBlockingFollowerNB(), MSLCM_JE2013::amBlockingFollowerNB(), MSLCM_LC2013::amBlockingFollowerNB(), MSLCM_SL2015::amBlockingFollowerNB(), amBlockingFollowerPlusNB(), MSLCM_JE2013::amBlockingFollowerPlusNB(), MSLCM_LC2013::amBlockingFollowerPlusNB(), MSLCM_SL2015::amBlockingFollowerPlusNB(), amBlockingLeader(), MSLCM_JE2013::amBlockingLeader(), MSLCM_LC2013::amBlockingLeader(), MSLCM_SL2015::amBlockingLeader(), changed(), MSLCM_SL2015::changed(), MSLCM_JE2013::changed(), MSLCM_LC2013::changed(), MSAbstractLaneChangeModel::getOwnState(), inform(), MSLCM_JE2013::inform(), MSLCM_SL2015::inform(), MSLCM_LC2013::inform(), patchSpeed(), prepareStep(), MSLCM_SL2015::prepareStep(), MSLCM_JE2013::prepareStep(), MSLCM_LC2013::prepareStep(), MSAbstractLaneChangeModel::primaryLaneChanged(), MSLCM_SL2015::setOwnState(), MSAbstractLaneChangeModel::setOwnState(), wantsChangeToLeft(), and wantsChangeToRight().
std::vector<MSLane*> MSAbstractLaneChangeModel::myPartiallyOccupatedByShadow protected inherited
list of lanes where the shadow vehicle is partial occupator
Definition at line 419 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::setShadowPartialOccupator().
std::vector<MSLane*> MSAbstractLaneChangeModel::myShadowFurtherLanes protected inherited
Definition at line 409 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::getShadowFurtherLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
std::vector<SUMOReal> MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat protected inherited
Definition at line 410 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat(), and MSAbstractLaneChangeModel::updateShadowLane().
MSLane* MSAbstractLaneChangeModel::myShadowLane protected inherited
A lane that is partially occupied by the front of the vehicle but that is not the primary lane.
Definition at line 405 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::setShadowLane(), and MSAbstractLaneChangeModel::updateShadowLane().
MSVehicle& MSAbstractLaneChangeModel::myVehicle protected inherited
The vehicle this lane-changer belongs to.
Definition at line 387 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSAbstractLaneChangeModel::cancelRequest(), MSLCM_JE2013::changed(), MSLCM_SL2015::changed(), MSLCM_LC2013::changed(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::checkStrategicChange(), MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::congested(), MSLCM_SL2015::decideDirection(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), MSLCM_JE2013::inform(), MSLCM_SL2015::inform(), MSLCM_LC2013::inform(), informBlocker(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLCM_SL2015::informLeaders(), MSLCM_SL2015::keepLatGap(), MSLCM_SL2015::msg(), MSLCM_JE2013::MSLCM_JE2013(), MSLCM_LC2013::MSLCM_LC2013(), patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_SL2015::patchSpeed(), MSLCM_LC2013::patchSpeed(), MSAbstractLaneChangeModel::predInteraction(), MSLCM_SL2015::prepareStep(), MSAbstractLaneChangeModel::primaryLaneChanged(), MSAbstractLaneChangeModel::removeShadowApproachingInformation(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_SL2015::updateGaps(), MSAbstractLaneChangeModel::updateShadowLane(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), wantsChangeToLeft(), and wantsChangeToRight().
std::vector<SUMOReal> MSLCM_DK2008::myVSafes protected
Definition at line 163 of file MSLCM_DK2008.h.
Referenced by changed(), patchSpeed(), prepareStep(), wantsChangeToLeft(), and wantsChangeToRight().
The documentation for this class was generated from the following files:
MSLCM_DK2008.h
MSLCM_DK2008.cpp