SUMO - Simulation of Urban MObility: GUILane Class Reference
GUILane Class Reference
Representation of a lane in the micro simulation (gui-version)
#include <GUILane.h>
Public Types
enum CollisionAction { COLLISION_ACTION_NONE, COLLISION_ACTION_WARN, COLLISION_ACTION_TELEPORT, COLLISION_ACTION_REMOVE }
typedef std::vector< MSVehicle * > VehCont
Container for vehicles.
Public Member Functions
void addApproachingLane (MSLane *lane, bool warnMultiCon)
void addIncomingLane (MSLane *lane, MSLink *viaLink)
void addParameter (const std::string &key, const std::string &value)
Adds a parameter.
void addParameter (const std::map< std::string, std::string > &mapArg)
Adds all given parameter.
void addParameter (const Parameterised &p)
Adds all given parameter.
void addTo (const StoringVisitor &cont) const
Adds this object to the given container.
bool allowsVehicleClass (SUMOVehicleClass vclass) const
virtual bool appropriate (const MSVehicle *veh)
void clearParameter ()
Clears the parameter map.
void closeTraffic (bool rebuildAllowed=true)
close this lane for traffic
void detectCollisions (SUMOTime timestep, const std::string &stage)
void drawBikeMarkings () const
bike lane markings on top of an intersection
void drawCrossties (SUMOReal length, SUMOReal spacing, SUMOReal halfWidth) const
draw crossties for railroads or pedestrian crossings
void drawDirectionIndicators () const
direction indicators for lanes
virtual void drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings &s) const
Draws additional, user-triggered visualisations.
void drawMarkings (const GUIVisualizationSettings &s, SUMOReal scale) const
draw lane borders and white markings
void drawName (const Position &pos, const SUMOReal scale, const GUIVisualizationTextSettings &settings, const SUMOReal angle=0) const
draw name of item
bool empty () const
Returns true if there is not a single vehicle on the lane.
void enteredByLaneChange (MSVehicle *v)
SUMOReal firstWaitingTime () const
SUMOReal getCenterOnEdge () const
std::pair< MSVehicle *const, SUMOReal > getCriticalLeader (SUMOReal dist, SUMOReal seen, SUMOReal speed, const MSVehicle &veh) const
Returns the most dangerous leader and the distance to him.
int getCrossingIndex () const
return the index of the link to the next crossing if this is walkingArea, else -1
MSEdge & getEdge () const
Returns the lane's edge.
SUMOReal getEdgeLaneNumber () const
MSVehicle * getFirstAnyVehicle () const
returns the first vehicle that is fully or partially on this lane
MSVehicle * getFirstFullVehicle () const
returns the first vehicle for which this lane is responsible or 0
std::pair< MSVehicle *const, SUMOReal > getFollower (const MSVehicle *ego, SUMOReal egoPos, SUMOReal dist) const
Find follower vehicle for the given ego vehicle (which may be on the opposite direction lane)
std::pair< MSVehicle *const, SUMOReal > getFollowerOnConsecutive (SUMOReal backOffset, SUMOReal leaderSpeed, SUMOReal leaderMaxDecel, SUMOReal dist=-1) const
return the follower with the largest missing rear gap among all predecessor lanes (within dist)
MSLeaderDistanceInfo getFollowersOnConsecutive (const MSVehicle *ego, bool allSublanes) const
return the sublane followers with the largest missing rear gap among all predecessor lanes (within dist)
const std::string & getID () const
Returns the id.
const std::vector< IncomingLaneInfo > & getIncomingLanes () const
LinkState getIncomingLinkState () const
get the state of the link from the logical predecessor to this lane
const MSEdge * getInternalFollower () const
Returns the lane's follower if it is an internal lane, the edge of the lane otherwise.
MSVehicle * getLastAnyVehicle () const
returns the last vehicle that is fully or partially on this lane
MSVehicle * getLastFullVehicle () const
returns the last vehicle for which this lane is responsible or 0
std::pair< MSVehicle *const, SUMOReal > getLeader (const MSVehicle *veh, const SUMOReal vehPos, const std::vector< MSLane * > &bestLaneConts, SUMOReal dist=-1, bool checkTmpVehicles=false) const
Returns the immediate leader of veh and the distance to veh starting on this lane.
std::pair< MSVehicle *const, SUMOReal > getLeaderOnConsecutive (SUMOReal dist, SUMOReal seen, SUMOReal speed, const MSVehicle &veh, const std::vector< MSLane * > &bestLaneConts) const
Returns the immediate leader and the distance to him.
void getLeadersOnConsecutive (SUMOReal dist, SUMOReal seen, SUMOReal speed, const MSVehicle *ego, const std::vector< MSLane * > &bestLaneConts, MSLeaderDistanceInfo &result) const
Returns the immediate leaders and the distance to them (as getLeaderOnConsecutive but for the sublane case)
const MSLinkCont & getLinkCont () const
returns the container with all links !!!
SUMOReal getLoadedEdgeWeight () const
Returns the loaded weight (effort) for the edge of this lane.
MSLane * getLogicalPredecessorLane () const
get the most likely precedecessor lane (sorted using by_connections_to_sorter). The result is cached in myLogicalPredecessorLane
MSLane * getLogicalPredecessorLane (const MSEdge &fromEdge) const
return the (first) predecessor lane from the given edge
const std::map< std::string, std::string > & getMap () const
Returns the inner key/value map.
SUMOReal getMissingRearGap (SUMOReal backOffset, SUMOReal leaderSpeed, SUMOReal leaderMaxDecel) const
return by how much further the leader must be inserted to avoid rear end collisions
MSLane * getOpposite () const
return the opposite direction lane for lane changing or 0
std::pair< MSVehicle *const, SUMOReal > getOppositeFollower (const MSVehicle *ego) const
std::pair< MSVehicle *const, SUMOReal > getOppositeLeader (const MSVehicle *ego, SUMOReal dist) const
SUMOReal getOppositePos (SUMOReal pos) const
return the corresponding position on the opposite lane
std::vector< const MSLane * > getOutgoingLanes () const
get the list of outgoing lanes
MSLane * getParallelLane (int offset) const
Returns the lane with the given offset parallel to this one or 0 if it does not exist.
const std::string & getParameter (const std::string &key, const std::string &defaultValue) const
Returns the value for a given key.
const std::string & getParentName () const
Returns the name of the parent object (if any)
MSVehicle * getPartialBehind (const MSVehicle *ego) const
int getRightmostSublane () const
SUMOReal getRightSideOnEdge () const
const PositionVector & getShape () const
const std::vector< SUMOReal > & getShapeLengths () const
const std::vector< SUMOReal > & getShapeRotations () const
SUMOReal getStoredEdgeTravelTime () const
Returns the stored traveltime for the edge of this lane.
GUILane (const std::string &id, SUMOReal maxSpeed, SUMOReal length, MSEdge *const edge, int numericalID, const PositionVector &shape, SUMOReal width, SVCPermissions permissions, int index)
Constructor.
bool isApproachedFrom (MSEdge *const edge)
bool isApproachedFrom (MSEdge *const edge, MSLane *const lane)
bool isClosed () const
bool isEmpty () const
bool isLinkEnd (MSLinkCont::const_iterator &i) const
bool isLinkEnd (MSLinkCont::iterator &i)
bool knowsParameter (const std::string &key) const
Returns whether the parameter is known.
void leftByLaneChange (MSVehicle *v)
MSVehicle * removeVehicle (MSVehicle *remVehicle, MSMoveReminder::Notification notification, bool notify)
void resetPartialOccupation (MSVehicle *v)
Removes the information about a vehicle lapping into this lane.
void setID (const std::string &newID)
resets the id
void setLength (SUMOReal val)
Sets a new length for the lane (used by TraCI only)
void setMaxSpeed (SUMOReal val)
Sets a new maximum speed for the lane (used by TraCI and MSCalibrator)
SUMOReal setPartialOccupation (MSVehicle *v)
Sets the information about a vehicle lapping into this lane.
void setPermissions (SVCPermissions permissions)
void setRightSideOnEdge (SUMOReal value, int rightmostSublane)
void sortPartialVehicles ()
sorts myPartialVehicles
void visit (const TraCIServerAPI_Lane::StoringVisitor &cont) const
Callback for visiting the lane when traversing an RTree.
~GUILane ()
Destructor.
Access to vehicles
const VehCont & getVehiclesSecure () const
Returns the vehicles container; locks it for microsimulation.
void releaseVehicles () const
Allows to use the container for microsimulation again.
Vehicle movement (longitudinal)
void planMovements (const SUMOTime t)
bool executeMovements (SUMOTime t, std::vector< MSLane * > &into)
bool integrateNewVehicle (SUMOTime t)
inherited from GUIGlObject
GUIGLObjectPopupMenu * getPopUpMenu (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own popup-menu.
GUIParameterTableWindow * getParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own parameter window.
Boundary getCenteringBoundary () const
Returns the boundary to which the view shall be centered in order to show the object.
void drawGL (const GUIVisualizationSettings &s) const
Draws the object.
Additional initialisation
void addLink (MSLink *link)
Delayed initialization.
void addNeigh (const std::string &id)
Adds a neighbor to this lane.
interaction with MSMoveReminder
virtual void addMoveReminder (MSMoveReminder *rem)
Add a move-reminder to move-reminder container.
const std::vector< MSMoveReminder * > & getMoveReminders () const
Return the list of this lane's move reminders.
Vehicle insertion
bool insertVehicle (MSVehicle &v)
Tries to insert the given vehicle.
bool isInsertionSuccess (MSVehicle *vehicle, SUMOReal speed, SUMOReal pos, SUMOReal posLat, bool recheckNextLanes, MSMoveReminder::Notification notification)
Tries to insert the given vehicle with the given state (speed and pos)
bool checkFailure (MSVehicle *aVehicle, SUMOReal &speed, SUMOReal &dist, const SUMOReal nspeed, const bool patchSpeed, const std::string errorMsg) const
bool lastInsertion (MSVehicle &veh, SUMOReal mspeed)
bool freeInsertion (MSVehicle &veh, SUMOReal speed, MSMoveReminder::Notification notification=MSMoveReminder::NOTIFICATION_DEPARTED)
Tries to insert the given vehicle on any place.
void forceVehicleInsertion (MSVehicle *veh, SUMOReal pos, MSMoveReminder::Notification notification, SUMOReal posLat=0)
Inserts the given vehicle at the given position.
Handling vehicles lapping into lanes
const MSLeaderInfo & getLastVehicleInformation (const MSVehicle *ego, SUMOReal latOffset, SUMOReal minPos=0, bool allowCached=true) const
Returns the last vehicles on the lane.
const MSLeaderInfo & getFirstVehicleInformation (const MSVehicle *ego, SUMOReal latOffset, bool onlyFrontOnLane, SUMOReal maxPos=std::numeric_limits< SUMOReal >::max(), bool allowCached=true) const
analogue to getLastVehicleInformation but in the upstream direction
Access to vehicles
int getVehicleNumber () const
Returns the number of vehicles on this lane (for which this lane is responsible)
int getVehicleNumberWithPartials () const
Returns the number of vehicles on this lane (including partial occupators)
int getPartialVehicleNumber () const
Returns the number of vehicles partially on this lane (for which this lane is not responsible)
AnyVehicleIterator anyVehiclesBegin () const
begin iterator for iterating over all vehicles touching this lane in downstream direction
AnyVehicleIterator anyVehiclesEnd () const
end iterator for iterating over all vehicles touching this lane in downstream direction
AnyVehicleIterator anyVehiclesUpstreamBegin () const
begin iterator for iterating over all vehicles touching this lane in upstream direction
AnyVehicleIterator anyVehiclesUpstreamEnd () const
end iterator for iterating over all vehicles touching this lane in upstream direction
Atomar value getter
int getNumericalID () const
Returns this lane's numerical id.
SUMOReal getLengthGeometryFactor () const
return shape.length() / myLength
SUMOReal interpolateLanePosToGeometryPos (SUMOReal lanePos) const
const Position geometryPositionAtOffset (SUMOReal offset, SUMOReal lateralOffset=0) const
SUMOReal interpolateGeometryPosToLanePos (SUMOReal geometryPos) const
SUMOReal getVehicleMaxSpeed (const SUMOVehicle *const veh) const
Returns the lane's maximum speed, given a vehicle's speed limit adaptation.
SUMOReal getSpeedLimit () const
Returns the lane's maximum allowed speed.
SUMOReal getLength () const
Returns the lane's length.
SVCPermissions getPermissions () const
Returns the vehicle class permissions for this lane.
SUMOReal getWidth () const
Returns the lane's width.
int getIndex () const
Returns the lane's index.
Current state retrieval
SUMOReal getMeanSpeed () const
Returns the mean speed on this lane.
SUMOReal getWaitingSeconds () const
Returns the overall waiting time on this lane.
SUMOReal getBruttoOccupancy () const
Returns the brutto (including minGaps) occupancy of this lane during the last step.
SUMOReal getNettoOccupancy () const
Returns the netto (excluding minGaps) occupancy of this lane during the last step (including minGaps)
SUMOReal getBruttoVehLenSum () const
Returns the sum of lengths of vehicles, including their minGaps, which were on the lane during the last step.
SUMOReal getCO2Emissions () const
Returns the sum of last step CO2 emissions.
SUMOReal getCOEmissions () const
Returns the sum of last step CO emissions.
SUMOReal getPMxEmissions () const
Returns the sum of last step PMx emissions.
SUMOReal getNOxEmissions () const
Returns the sum of last step NOx emissions.
SUMOReal getHCEmissions () const
Returns the sum of last step HC emissions.
SUMOReal getFuelConsumption () const
Returns the sum of last step fuel consumption.
SUMOReal getElectricityConsumption () const
Returns the sum of last step electricity consumption.
SUMOReal getHarmonoise_NoiseEmissions () const
Returns the sum of last step noise emissions.
State saving/loading
void saveState (OutputDevice &out)
Saves the state of this lane into the given stream.
void loadState (std::vector< std::string > &vehIDs, MSVehicleControl &vc)
Loads the state of this segment with the given parameters.
Atomar getter methods
Returns the full name appearing in the tool tip
Returns
This object's typed id
const std::string & getFullName () const
GUIGlID getGlID () const
Returns the numerical id of the object.
interfaces to be implemented by derived classes
virtual GUIParameterTableWindow * getTypeParameterWindow (GUIMainWindow &app, GUISUMOAbstractView &parent)
Returns an own type parameter window (optional)
virtual const std::string & getMicrosimID () const
Returns the id of the object as known to microsim.
virtual void setMicrosimID (const std::string &newID)
Changes the microsimID of the object.
GUIGlObjectType getType () const
Returns the type of the object as coded in GUIGlObjectType.
Parameter table window I/O
Lets this object know a parameter window showing the object's values was opened
Parameters
[in] w The opened parameter window
void addParameterTable (GUIParameterTableWindow *w)
void removeParameterTable (GUIParameterTableWindow *w)
Lets this object know a parameter window showing the object's values was closed.
Static Public Member Functions
static void clear ()
Clears the dictionary.
static bool dictionary (const std::string &id, MSLane *lane)
Static (sic!) container methods {.
static MSLane * dictionary (const std::string &id)
Returns the MSLane associated to the key id.
static int dictSize ()
Returns the number of stored lanes.
template<class RTREE >
static void fill (RTREE &into)
Fills the given RTree with lane instances.
template<class T >
static std::string getIDSecure (const T *obj, const std::string &fallBack="NULL")
get an identifier for Named-like object which may be Null
static void initCollisionOptions (const OptionsCont &oc)
static void insertIDs (std::vector< std::string > &into)
Adds the ids of all stored lanes into the given vector.
static MSLinkCont::const_iterator succLinkSec (const SUMOVehicle &veh, int nRouteSuccs, const MSLane &succLinkSource, const std::vector< MSLane * > &conts)
static bool teleportOnCollision ()
Static Public Attributes
static const GUIGlID INVALID_ID = 0
static StringBijection< GUIGlObjectType > TypeNames
associates object types with strings
Protected Types
typedef std::map< std::string, MSLane * > DictType
definition of the static dictionary type
Protected Member Functions
SUMOReal basePos (const MSVehicle &veh) const
departure position where the vehicle fits fully onto the lane (if possible)
bool detectCollisionBetween (SUMOTime timestep, const std::string &stage, const MSVehicle *collider, const MSVehicle *victim, std::set< const MSVehicle *, SUMOVehicle::ComparatorIdLess > &toRemove, std::set< const MSVehicle * > &toTeleport) const
detect whether there is a collision between the two vehicles
SUMOReal getDepartSpeed (const MSVehicle &veh, bool &patchSpeed)
SUMOReal getMaximumBrakeDist () const
compute maximum braking distance on this lane
void handleCollisionBetween (SUMOTime timestep, const std::string &stage, const MSVehicle *collider, const MSVehicle *victim, SUMOReal gap, SUMOReal latGap, std::set< const MSVehicle *, SUMOVehicle::ComparatorIdLess > &toRemove, std::set< const MSVehicle * > &toTeleport) const
take action upon collision
virtual void incorporateVehicle (MSVehicle *veh, SUMOReal pos, SUMOReal speed, SUMOReal posLat, const MSLane::VehCont::iterator &at, MSMoveReminder::Notification notification=MSMoveReminder::NOTIFICATION_DEPARTED)
Inserts the vehicle into this lane, and informs it about entering the network.
SUMOReal safeInsertionSpeed (const MSVehicle *veh, const MSLeaderInfo &leaders, SUMOReal speed)
return the maximum safe speed for insertion behind leaders (a negative value indicates that safe insertion is impossible)
void setPrefix (const std::string &prefix)
usually names are prefixed by a type-specific string. this method can be used to change the default
void swapAfterLaneChange (SUMOTime t)
moves myTmpVehicles int myVehicles after a lane change procedure
helper methods for building popup-menus
void buildPopupHeader (GUIGLObjectPopupMenu *ret, GUIMainWindow &app, bool addSeparator=true)
Builds the header.
void buildCenterPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to center to the object.
void buildNameCopyPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds entries which allow to copy the name / typed name into the clipboard.
void buildSelectionPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to (de)select the object.
void buildShowParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the parameter window.
void buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the type parameter window.
void buildPositionCopyEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
void buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu *ret, bool addSeparator=true)
Builds an entry which allows to open the manipulator window.
Protected Attributes
std::map< MSEdge *, std::vector< MSLane * > > myApproachingLanes
SUMOReal myBruttoVehicleLengthSum
The current length of all vehicles on this lane, including their minGaps.
MSEdge *const myEdge
The lane's edge, for routing only.
MSLeaderInfo myFollowerInfo
followers on all sublanes as seen by vehicles on consecutive lanes (cached)
SUMOTime myFollowerInfoTime
time step for which myFollowerInfo was last updated
std::string myID
The name of the object.
std::vector< IncomingLaneInfo > myIncomingLanes
int myIndex
The lane index.
MSLeaderInfo myLeaderInfo
leaders on all sublanes as seen by approaching vehicles (cached)
SUMOTime myLeaderInfoTime
time step for which myLeaderInfo was last updated
MSLeaderInfo myLeaderInfoTmp
SUMOReal myLength
Lane length [m].
const SUMOReal myLengthGeometryFactor
precomputed myShape.length / myLength
MSLinkCont myLinks
MSLane * myLogicalPredecessorLane
SUMOReal myMaxSpeed
Lane-wide speedlimit [m/s].
std::vector< std::string > myNeighs
SUMOReal myNettoVehicleLengthSum
The current length of all vehicles on this lane, excluding their minGaps.
int myNumericalID
Unique numerical ID (set on reading by netload)
VehCont myPartialVehicles
The lane's partial vehicles. This container holds all vehicles that are partially on this lane but which are in myVehicles of another lane. Reasons for partial occupancie include the following.
SVCPermissions myPermissions
The vClass permissions for this lane.
const std::map< SUMOVehicleClass, SUMOReal > * myRestrictions
The vClass speed restrictions for this lane.
int myRightmostSublane
the index of the rightmost sublane of this lane on myEdge
SUMOReal myRightSideOnEdge
the combined width of all lanes with lower index on myEdge
PositionVector myShape
The shape of the lane.
VehCont myTmpVehicles
Container for lane-changing vehicles. After completion of lane-change- process, the containers will be swapped with myVehicles.
VehCont myVehBuffer
Buffer for vehicles that moved from their previous lane onto this one. Integrated after all vehicles executed their moves.
VehCont myVehicles
The lane's vehicles. This container holds all vehicles that have their front (longitudinally) and their center (laterally) on this lane. These are the vehicles that this lane is 'responsibly' for (i.e. when executing movements)
const SUMOReal myWidth
Lane width [m].
Static Protected Attributes
static DictType myDict
Static dictionary to associate string-ids with objects.
Private Member Functions
void drawArrows () const
bool drawAsRailway (const GUIVisualizationSettings &s) const
whether to draw this lane as a railway
bool drawAsWaterway (const GUIVisualizationSettings &s) const
whether to draw this lane as a waterway
void drawLane2LaneConnections () const
void drawLinkNo (const GUIVisualizationSettings &s) const
helper methods
void drawLinkRule (const GUIVisualizationSettings &s, const GUINet &net, MSLink *link, const PositionVector &shape, SUMOReal x1, SUMOReal x2) const
void drawLinkRules (const GUIVisualizationSettings &s, const GUINet &net) const
void drawTextAtEnd (const std::string &text, const PositionVector &shape, SUMOReal x, const GUIVisualizationTextSettings &settings) const
void drawTLSLinkNo (const GUIVisualizationSettings &s, const GUINet &net) const
SUMOReal getColorValue (int activeScheme) const
gets the color value according to the current scheme index
SUMOReal getScaleValue (int activeScheme) const
gets the scaling value according to the current scheme index
void setColor (const GUIVisualizationSettings &s) const
sets the color according to the currente settings
bool setFunctionalColor (int activeScheme) const
sets the color according to the current scheme index and some lane function
bool setMultiColor (const GUIColorer &c) const
sets multiple colors according to the current scheme index and some lane function
PositionVector splitAtSegments (const PositionVector &shape)
add intermediate points at segment borders
Private Attributes
bool myAmClosed
state for dynamic lane closings
SUMOReal myHalfLaneWidth
Half of lane width, for speed-up.
MFXMutex myLock
The mutex used to avoid concurrent updates of the vehicle buffer.
SVCPermissions myOriginalPermissions
SUMOReal myQuarterLaneWidth
Quarter of lane width, for speed-up.
std::vector< RGBColor > myShapeColors
The color of the shape parts (cached)
std::vector< SUMOReal > myShapeLengths
The lengths of the shape parts.
std::vector< SUMOReal > myShapeRotations
The rotations of the shape parts.
std::vector< int > myShapeSegments
the meso segment index for each geometry segment
Detailed Description
Representation of a lane in the micro simulation (gui-version)
An extended MSLane. A mechanism to avoid concurrent visualisation and simulation what may cause problems when vehicles disappear is implemented using a mutex.
Definition at line 70 of file GUILane.h.
Member Typedef Documentation
typedef std::map< std::string, MSLane* > MSLane::DictType protected inherited
definition of the static dictionary type
Definition at line 1115 of file MSLane.h.
typedef std::vector<MSVehicle*> MSLane::VehCont inherited
Container for vehicles.
Definition at line 91 of file MSLane.h.
Member Enumeration Documentation
enum MSLane::CollisionAction inherited
Enumerator
COLLISION_ACTION_NONE
COLLISION_ACTION_WARN
COLLISION_ACTION_TELEPORT
COLLISION_ACTION_REMOVE
Definition at line 162 of file MSLane.h.
Constructor & Destructor Documentation
GUILane::GUILane (const std::string & id, SUMOReal maxSpeed, SUMOReal length, MSEdge *const edge, int numericalID, const PositionVector & shape, SUMOReal width, SVCPermissions permissions, int index)
Constructor.
Parameters
[in] id The lane's id
[in] maxSpeed The speed allowed on this lane
[in] length The lane's length
[in] edge The edge this lane belongs to
[in] numericalID The numerical id of the lane
[in] shape The shape of the lane
[in] width The width of the lane
[in] permissions Encoding of vehicle classes that may drive on this lane
See also
SUMOVehicleClass
MSLane
Definition at line 78 of file GUILane.cpp.
References Position::distanceTo2D(), MSGlobals::gUseMesoSim, PositionVector::length(), myHalfLaneWidth, myQuarterLaneWidth, MSLane::myShape, myShapeColors, myShapeLengths, myShapeRotations, myShapeSegments, MSLane::myWidth, POSITION_EPS, RAD2DEG, splitAtSegments(), SUMOReal, Position::x(), and Position::y().
GUILane::~GUILane ()
Destructor.
Definition at line 106 of file GUILane.cpp.
References MFXMutex::locked(), myLock, and MFXMutex::unlock().
Member Function Documentation
void MSLane::addApproachingLane (MSLane * lane, bool warnMultiCon) inherited
Definition at line 1510 of file MSLane.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSLane::getEdge(), Named::getID(), MSEdge::getPurpose(), MSLane::myApproachingLanes, and WRITE_WARNING.
Referenced by NLHandler::addConnection(), and MSLane::getIncomingLanes().
void MSLane::addIncomingLane (MSLane * lane, MSLink * viaLink) inherited
Definition at line 1500 of file MSLane.cpp.
References MSLane::getLength(), MSLane::IncomingLaneInfo::lane, MSLane::IncomingLaneInfo::length, MSLane::myIncomingLanes, and MSLane::IncomingLaneInfo::viaLink.
Referenced by NLHandler::addConnection(), and MSLane::allowsVehicleClass().
void MSLane::addLink (MSLink * link) inherited
Delayed initialization.
Not all lane-members are known at the time the lane is born, above all the pointers to other lanes, so we have to add them later.
Parameters
[in] link An outgoing link
Definition at line 189 of file MSLane.cpp.
References MSLane::myLinks.
Referenced by NLHandler::addConnection().
void MSLane::addMoveReminder (MSMoveReminder * rem) virtual inherited
Add a move-reminder to move-reminder container.
The move reminder will not be deleted by the lane.
Parameters
[in] rem The move reminder to add
Definition at line 202 of file MSLane.cpp.
References MSLane::myMoveReminders, MSLane::myVehicles, and SUMOReal.
Referenced by MSMoveReminder::MSMoveReminder().
void MSLane::addNeigh (const std::string & id) inherited
Adds a neighbor to this lane.
Parameters
[in] id The lane's id
Definition at line 195 of file MSLane.cpp.
References MSLane::myNeighs.
void Parameterised::addParameter (const std::string & key, const std::string & value) inherited
Adds a parameter.
Parameters
[in] key The parameter's name
[in] value The parameter's value
Definition at line 53 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by SUMORouteHandler::addParam(), NLHandler::addParam(), PCLoaderOSM::addPOI(), PCLoaderOSM::addPolygon(), NBTrafficLightDefinition::compute(), NIImporter_OpenDrive::loadNetwork(), NIImporter_MATSim::EdgesHandler::myStartElement(), TraCIServerAPI_Edge::processSet(), TraCIServerAPI_TLS::processSet(), TraCIServerAPI_POI::processSet(), TraCIServerAPI_Polygon::processSet(), and TraCIServerAPI_Lane::processSet().
void Parameterised::addParameter (const std::map< std::string, std::string > & mapArg) inherited
Adds all given parameter.
Parameters
[in] mapArg The keys/values to insert
Definition at line 59 of file Parameterised.cpp.
References Parameterised::myMap.
void Parameterised::addParameter (const Parameterised & p) inherited
Adds all given parameter.
Parameters
[in] p The keys/values to insert
Definition at line 67 of file Parameterised.cpp.
References Parameterised::myMap.
void GUIGlObject::addParameterTable (GUIParameterTableWindow * w) inherited
Definition at line 258 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
void Named::addTo (const StoringVisitor & cont) const inline inherited
Adds this object to the given container.
Parameters
Definition at line 129 of file Named.h.
References Named::StoringVisitor::add().
bool MSLane::allowsVehicleClass (SUMOVehicleClass vclass) const inline inherited
Definition at line 684 of file MSLane.h.
References MSLane::addIncomingLane(), and MSLane::myPermissions.
Referenced by MSVehicle::addStop(), MSEdge::allowedLanes(), MSPModel_NonInteracting::PState::getPosition(), MSVehicle::updateBestLanes(), and MSLCM_SL2015::updateExpectedSublaneSpeeds().
AnyVehicleIterator MSLane::anyVehiclesBegin () const inline inherited
begin iterator for iterating over all vehicles touching this lane in downstream direction
Definition at line 381 of file MSLane.h.
References MSLane::AnyVehicleIterator, MSLane::myPartialVehicles, and MSLane::myVehicles.
Referenced by MSLane::detectCollisions(), MSLane::getFollowersOnConsecutive(), MSLane::getLastVehicleInformation(), MSLane::getLeader(), and MSLink::writeApproaching().
AnyVehicleIterator MSLane::anyVehiclesEnd () const inline inherited
end iterator for iterating over all vehicles touching this lane in downstream direction
Definition at line 386 of file MSLane.h.
References MSLane::AnyVehicleIterator, MSLane::myPartialVehicles, and MSLane::myVehicles.
Referenced by MSLane::detectCollisions(), MSLane::getFollowersOnConsecutive(), MSLane::getLeader(), and MSLink::writeApproaching().
AnyVehicleIterator MSLane::anyVehiclesUpstreamBegin () const inline inherited
begin iterator for iterating over all vehicles touching this lane in upstream direction
Definition at line 391 of file MSLane.h.
References MSLane::AnyVehicleIterator, MSLane::myPartialVehicles, and MSLane::myVehicles.
Referenced by MSLane::getFirstVehicleInformation(), and MSLane::getFollower().
AnyVehicleIterator MSLane::anyVehiclesUpstreamEnd () const inline inherited
end iterator for iterating over all vehicles touching this lane in upstream direction
Definition at line 396 of file MSLane.h.
References MSLane::AnyVehicleIterator.
Referenced by MSLane::getFollower().
bool MSLane::appropriate (const MSVehicle * veh) virtual inherited
Returns the information whether this lane may be used to continue the current route
Definition at line 1284 of file MSLane.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSVehicle::getBestLanes(), MSVehicle::getBestLanesContinuation(), MSVehicle::getLaneIndex(), MSEdge::getPurpose(), MSLane::myEdge, MSLane::myLinks, MSBaseVehicle::succEdge(), and MSLane::succLinkSec().
Referenced by MSLane::executeMovements(), and MSLane::getIndex().
SUMOReal MSLane::basePos (const MSVehicle & veh) const protected inherited
departure position where the vehicle fits fully onto the lane (if possible)
Definition at line 482 of file MSLane.cpp.
References MSVehicleType::getLength(), MSBaseVehicle::getVehicleType(), MIN2(), MSLane::myLength, and POSITION_EPS.
Referenced by MSLane::insertVehicle(), MSLane::lastInsertion(), and MSLane::teleportOnCollision().
void GUIGlObject::buildCenterPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to center to the object.
Parameters
Definition at line 187 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_RECENTERVIEW, and MID_CENTER.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and getPopUpMenu().
void GUIGlObject::buildNameCopyPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds entries which allow to copy the name / typed name into the clipboard.
Parameters
Definition at line 196 of file GUIGlObject.cpp.
References MID_COPY_NAME, and MID_COPY_TYPED_NAME.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), and getPopUpMenu().
void GUIGlObject::buildPopupHeader (GUIGLObjectPopupMenu * ret, GUIMainWindow & app, bool addSeparator = true) protected inherited
Builds the header.
Parameters
Definition at line 177 of file GUIGlObject.cpp.
References GUIMainWindow::getBoldFont(), and GUIGlObject::getFullName().
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEInternalLane::getPopUpMenu(), GNECrossing::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and getPopUpMenu().
void GUIGlObject::buildPositionCopyEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to copy the cursor position if geo projection is used, also builds an entry for copying the geo-position.
Parameters
Definition at line 237 of file GUIGlObject.cpp.
References GeoConvHelper::getFinal(), MID_COPY_CURSOR_GEOPOSITION, and MID_COPY_CURSOR_POSITION.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GNENet::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and getPopUpMenu().
void GUIGlObject::buildSelectionPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to (de)select the object.
Parameters
Definition at line 206 of file GUIGlObject.cpp.
References GUIGlObject::getGlID(), GUIIconSubSys::getIcon(), GUIGlObject::getType(), gSelected, ICON_FLAG_MINUS, ICON_FLAG_PLUS, GUISelectedStorage::isSelected(), MID_ADDSELECT, and MID_REMOVESELECT.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUITrafficLightLogicWrapper::getPopUpMenu(), GNEJunction::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPolygon::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIPointOfInterest::getPopUpMenu(), GNELane::getPopUpMenu(), GUIJunctionWrapper::getPopUpMenu(), GNEEdge::getPopUpMenu(), GUITriggeredRerouter::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and getPopUpMenu().
void GUIGlObject::buildShowManipulatorPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the manipulator window.
Parameters
Definition at line 249 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_MANIP, and MID_MANIP.
Referenced by GUILaneSpeedTrigger::getPopUpMenu(), and GUITriggeredRerouter::getPopUpMenu().
void GUIGlObject::buildShowParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the parameter window.
Parameters
Definition at line 219 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWPARS.
Referenced by GUIDetectorWrapper::getPopUpMenu(), GUIContainer::getPopUpMenu(), GUIPerson::getPopUpMenu(), GUILaneSpeedTrigger::getPopUpMenu(), GUICalibrator::getPopUpMenu(), GUIContainerStop::getPopUpMenu(), GUIChargingStation::getPopUpMenu(), GUIBusStop::getPopUpMenu(), GUIEdge::getPopUpMenu(), GUINet::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GNEAdditional::getPopUpMenu(), and getPopUpMenu().
void GUIGlObject::buildShowTypeParamsPopupEntry (GUIGLObjectPopupMenu * ret, bool addSeparator = true) protected inherited
Builds an entry which allows to open the type parameter window.
Parameters
Definition at line 228 of file GUIGlObject.cpp.
References GUIIconSubSys::getIcon(), ICON_APP_TABLE, and MID_SHOWTYPEPARS.
Referenced by GUIBaseVehicle::getPopUpMenu().
bool MSLane::checkFailure (MSVehicle * aVehicle, SUMOReal & speed, SUMOReal & dist, const SUMOReal nspeed, const bool patchSpeed, const std::string errorMsg) const inherited
Definition at line 487 of file MSLane.cpp.
References MSCFModel::brakeGap(), MSInsertionControl::descheduleDeparture(), MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), MSNet::getInsertionControl(), MSNet::getInstance(), MSVehicleType::getMinGap(), MSBaseVehicle::getVehicleType(), MIN2(), and WRITE_ERROR.
Referenced by MSLane::getMoveReminders(), and MSLane::isInsertionSuccess().
void MSLane::clear () static inherited
Clears the dictionary.
Definition at line 1249 of file MSLane.cpp.
References MSLane::myDict.
Referenced by MSNet::clearAll(), and MSLane::getEdge().
void Parameterised::clearParameter () inherited
Clears the parameter map.
Definition at line 91 of file Parameterised.cpp.
References Parameterised::myMap.
void GUILane::closeTraffic (bool rebuildAllowed = true)
close this lane for traffic
Definition at line 1098 of file GUILane.cpp.
References MSGlobals::gCheckRoutes, MSLane::getEdge(), myAmClosed, myOriginalPermissions, MSLane::myPermissions, MSEdge::rebuildAllowedLanes(), and SVC_AUTHORITY.
Referenced by GUIEdge::closeTraffic(), and GUIViewTraffic::onCmdCloseLane().
bool MSLane::detectCollisionBetween (SUMOTime timestep, const std::string & stage, const MSVehicle * collider, const MSVehicle * victim, std::set< const MSVehicle *, SUMOVehicle::ComparatorIdLess > & toRemove, std::set< const MSVehicle * > & toTeleport) const protected inherited
detect whether there is a collision between the two vehicles
Definition at line 1023 of file MSLane.cpp.
References MSLane::COLLISION_ACTION_TELEPORT, DELTA_T, MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSVehicle::getInfluencer(), MSVehicle::getLane(), MSVehicle::getLaneChangeModel(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSGlobals::gLaneChangeDuration, MSGlobals::gLateralResolution, MSLane::handleCollisionBetween(), MSVehicle::hasInfluencer(), MSAbstractLaneChangeModel::isChangingLanes(), MSVehicle::isFrontOnLane(), MSVehicle::Influencer::isVTDAffected(), MSLane::myCollisionAction, NUMERICAL_EPS, and SUMOReal.
Referenced by MSLane::detectCollisions(), and MSLane::teleportOnCollision().
void GUILane::detectCollisions (SUMOTime timestep, const std::string & stage) virtual
the same as in MSLane, but locks the access for the visualisation first; the access will be granted at the end of this method
Reimplemented from MSLane.
Definition at line 174 of file GUILane.cpp.
References MSLane::detectCollisions(), myLock, and SUMOReal.
bool MSLane::dictionary (const std::string & id, MSLane * lane) static inherited
Static (sic!) container methods {.
Inserts a MSLane into the static dictionary
Returns true if the key id isn't already in the dictionary. Otherwise returns false.
Parameters
[in] id The id of the lane
[in] lane The lane itself
Returns
Whether the lane was added
Todo:
make non-static
why is the id given? The lane is named
Definition at line 1226 of file MSLane.cpp.
References MSLane::myDict.
Referenced by NLHandler::addConnection(), NLHandler::addLane(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSLane::getEdge(), NLTriggerBuilder::getLane(), NLDetectorBuilder::getLaneChecking(), NLShapeHandler::getLanePos(), MSLane::getOpposite(), TraCIServerAPI_Lane::getShape(), MSPedestrianPushButton::loadPushButtons(), NLTriggerBuilder::parseAndBuildLaneSpeedTrigger(), NLHandler::parseLanes(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), and TraCIServerAPI_Lane::processSet().
MSLane * MSLane::dictionary (const std::string & id) static inherited
Returns the MSLane associated to the key id.
The lane is returned if exists, otherwise 0 is returned.
Parameters
[in] id The id of the lane
Returns
The lane
Definition at line 1238 of file MSLane.cpp.
References MSLane::myDict.
static int MSLane::dictSize () inline static inherited
Returns the number of stored lanes.
Returns
The number of stored lanes
Definition at line 610 of file MSLane.h.
References MSLane::enteredByLaneChange(), MSLane::fill(), MSLane::getFirstAnyVehicle(), MSLane::getFirstFullVehicle(), MSLane::getLastAnyVehicle(), MSLane::getLastFullVehicle(), MSLane::getParallelLane(), MSLane::insertIDs(), MSLane::isEmpty(), MSLane::isLinkEnd(), MSLane::leftByLaneChange(), MSLane::myDict, MSLane::removeVehicle(), and MSLane::succLinkSec().
void GUILane::drawArrows () const private
Definition at line 355 of file GUILane.cpp.
References GLHelper::drawBoxLine(), GLHelper::drawTriangleAtEnd(), getShape(), LINKDIR_LEFT, LINKDIR_NODIR, LINKDIR_PARTLEFT, LINKDIR_PARTRIGHT, LINKDIR_RIGHT, LINKDIR_STRAIGHT, LINKDIR_TURN, LINKDIR_TURN_LEFTHAND, LINKSTATE_TL_OFF_NOSIGNAL, MSLane::myLinks, MSLane::myWidth, RAD2DEG, SUMO_const_laneWidth, SUMOReal, Position::x(), and Position::y().
Referenced by drawGL().
bool GUILane::drawAsRailway (const GUIVisualizationSettings & s) const private
whether to draw this lane as a railway
Definition at line 1075 of file GUILane.cpp.
References isRailway(), MSLane::myPermissions, and GUIVisualizationSettings::showRails.
Referenced by drawGL(), and drawLinkRule().
bool GUILane::drawAsWaterway (const GUIVisualizationSettings & s) const private
whether to draw this lane as a waterway
Definition at line 1081 of file GUILane.cpp.
References RGBColor::alpha(), RGBColor::blue(), GUIPropertySchemeStorage< T >::getActive(), GUIPropertyScheme< T >::getColor(), getColorValue(), GUIPropertySchemeStorage< T >::getScheme(), RGBColor::green(), isWaterway(), GUIVisualizationSettings::laneColorer, MSLane::myPermissions, RGBColor::red(), and GUIVisualizationSettings::showRails.
Referenced by drawGL(), and drawLinkRule().
void GUILane::drawBikeMarkings () const
bike lane markings on top of an intersection
Definition at line 653 of file GUILane.cpp.
References getShape(), GLO_JUNCTION, myHalfLaneWidth, myShapeLengths, myShapeRotations, SUMO_const_laneOffset, and SUMOReal.
Referenced by drawGL().
void GUILane::drawCrossties (SUMOReal length, SUMOReal spacing, SUMOReal halfWidth) const
draw crossties for railroads or pedestrian crossings
Definition at line 678 of file GUILane.cpp.
References getShape(), myShapeLengths, myShapeRotations, and SUMOReal.
Referenced by drawGL().
void GUILane::drawDirectionIndicators () const
direction indicators for lanes
Definition at line 702 of file GUILane.cpp.
References getShape(), GLO_EDGE, MIN2(), myHalfLaneWidth, myQuarterLaneWidth, myShapeLengths, myShapeRotations, MSLane::myWidth, and SUMOReal.
Referenced by drawGL().
void GUILane::drawGL (const GUIVisualizationSettings & s) const virtual
Draws the object.
Parameters
[in] s The settings for the current view (may influence drawing)
See also
GUIGlObject::drawGL
Implements GUIGlObject.
Definition at line 441 of file GUILane.cpp.
References GLHelper::debugVertices(), drawArrows(), drawAsRailway(), drawAsWaterway(), drawBikeMarkings(), GLHelper::drawBoxLines(), GUIVisualizationSettings::drawCrossingsAndWalkingareas, drawCrossties(), drawDirectionIndicators(), GLHelper::drawFilledPoly(), GLHelper::drawFilledPolyTesselated(), GUIBaseVehicle::drawGL(), drawLane2LaneConnections(), GLHelper::drawLine(), GUIVisualizationSettings::drawLinkJunctionIndex, drawLinkNo(), drawLinkRules(), GUIVisualizationSettings::drawLinkTLIndex, drawMarkings(), drawTLSLinkNo(), MSEdge::EDGEFUNCTION_CROSSING, MSEdge::EDGEFUNCTION_INTERNAL, MSEdge::EDGEFUNCTION_WALKINGAREA, GUIVisualizationSettings::edgeScaler, GUIPropertySchemeStorage< T >::getActive(), GUIPropertyScheme< T >::getColor(), GLHelper::getColor(), MSLinkContHelper::getConnectingLink(), GUIVisualizationSizeSettings::getExaggeration(), GUIGlObject::getGlID(), MSVehicleTransfer::getInstance(), MSNet::getInstance(), GUINet::getLinkTLIndex(), MSLane::getLogicalPredecessorLane(), MSVehicleTransfer::getParkingVehicles(), MSEdge::getPurpose(), GUIEdge::getScaleValue(), getScaleValue(), GUIPropertySchemeStorage< T >::getScheme(), GUIGlObject::getType(), getVehiclesSecure(), MSLane::getWidth(), MSGlobals::gLateralResolution, GLO_JUNCTION, MSGlobals::gUseMesoSim, MSLink::havePriority(), isWaterway(), GUIVisualizationSettings::laneMinSize, GUIVisualizationSettings::laneScaler, GUIVisualizationSettings::laneWidthExaggeration, MAX2(), GUIVisualizationSizeSettings::minSize, MSLane::myEdge, myHalfLaneWidth, MSLane::myPermissions, myQuarterLaneWidth, MSLane::myShape, myShapeColors, myShapeLengths, myShapeRotations, myShapeSegments, releaseVehicles(), GUIVisualizationSettings::scale, GLHelper::setColor(), setColor(), GUIVisualizationTextSettings::show, GUIVisualizationSettings::showLane2Lane, GUIVisualizationSettings::showLaneDirection, GUIVisualizationSettings::showLinkDecals, GUIVisualizationSettings::showSublanes, SUMOReal, SVC_BICYCLE, SVC_PEDESTRIAN, and GUIVisualizationSettings::vehicleSize.
Referenced by GUIEdge::drawGL().
void GUIGlObject::drawGLAdditional (GUISUMOAbstractView *const parent, const GUIVisualizationSettings & s) const virtual inherited
Draws additional, user-triggered visualisations.
Parameters
[in] parent The view
[in] s The settings for the current view (may influence drawing)
Reimplemented in GUIBaseVehicle, GUIPerson, and GUIContainer.
Definition at line 156 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
void GUILane::drawLane2LaneConnections () const private
Definition at line 422 of file GUILane.cpp.
References GLHelper::drawTriangleAtEnd(), getLinkColor(), getShape(), MSLane::getShape(), MSLane::myLinks, GLHelper::setColor(), SUMOReal, Position::x(), and Position::y().
Referenced by drawGL().
void GUILane::drawLinkNo (const GUIVisualizationSettings & s) const private
helper methods
Definition at line 196 of file GUILane.cpp.
References GUIVisualizationSettings::drawLinkJunctionIndex, drawTextAtEnd(), PositionVector::extrapolate(), MSLinkContHelper::getConnectingLink(), MSLane::getEdge(), MSLink::getIndex(), MSLane::getIndex(), MSNet::getInstance(), MSLane::getLogicalPredecessorLane(), getShape(), MSNet::lefthand(), myHalfLaneWidth, MSLane::myLinks, MSLane::myWidth, PositionVector::reverse(), SUMOReal, and toString().
Referenced by drawGL().
void GUILane::drawLinkRule (const GUIVisualizationSettings & s, const GUINet & net, MSLink * link, const PositionVector & shape, SUMOReal x1, SUMOReal x2) const private
Definition at line 299 of file GUILane.cpp.
References drawAsRailway(), drawAsWaterway(), GUIGlObject::getGlID(), getLinkColor(), GUINet::getLinkTLID(), MSLink::getState(), LINKSTATE_DEADEND, LINKSTATE_EQUAL, LINKSTATE_MAJOR, LINKSTATE_MINOR, LINKSTATE_TL_GREEN_MAJOR, LINKSTATE_TL_GREEN_MINOR, LINKSTATE_TL_OFF_BLINKING, LINKSTATE_TL_OFF_NOSIGNAL, LINKSTATE_TL_RED, LINKSTATE_TL_REDYELLOW, LINKSTATE_TL_YELLOW_MAJOR, LINKSTATE_TL_YELLOW_MINOR, myHalfLaneWidth, RAD2DEG, GLHelper::setColor(), SUMOReal, Position::x(), and Position::y().
Referenced by drawLinkRules().
void GUILane::drawLinkRules (const GUIVisualizationSettings & s, const GUINet & net) const private
Definition at line 271 of file GUILane.cpp.
References drawLinkRule(), PositionVector::extrapolate(), MSLinkContHelper::getConnectingLink(), MSLane::getEdge(), MSNet::getInstance(), MSLane::getLogicalPredecessorLane(), getShape(), MSNet::lefthand(), MSLane::myLinks, MSLane::myWidth, PositionVector::reverse(), and SUMOReal.
Referenced by drawGL().
void GUILane::drawMarkings (const GUIVisualizationSettings & s, SUMOReal scale) const
draw lane borders and white markings
Definition at line 615 of file GUILane.cpp.
References GLHelper::drawBoxLines(), MSNet::getInstance(), MSEdge::getLanes(), getShape(), getShapeLengths(), getShapeRotations(), GLO_EDGE, MSGlobals::gUseMesoSim, MSNet::lefthand(), MIN2(), MSLane::myEdge, myHalfLaneWidth, MSLane::myIndex, MSLane::myPermissions, myQuarterLaneWidth, myShapeLengths, myShapeRotations, setColor(), SUMO_const_laneOffset, and SUMOReal.
Referenced by drawGL().
void GUIGlObject::drawName (const Position & pos, const SUMOReal scale, const GUIVisualizationTextSettings & settings, const SUMOReal angle = 0) const inherited
draw name of item
Definition at line 286 of file GUIGlObject.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), GUIGlObject::getMicrosimID(), GLO_MAX, GUIVisualizationTextSettings::show, and GUIVisualizationTextSettings::size.
Referenced by GNEDetectorEntry::drawGL(), GNEDetectorExit::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEBusStop::drawGL(), GNEContainerStop::drawGL(), GNEDetectorE3::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GUIPolygon::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GNERouteProbe::drawGL(), GNEEdge::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIEdge::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GNERerouter::drawGL(), and GUIBaseVehicle::drawOnPos().
void GUILane::drawTextAtEnd (const std::string & text, const PositionVector & shape, SUMOReal x, const GUIVisualizationTextSettings & settings) const private
Definition at line 258 of file GUILane.cpp.
References GUIVisualizationTextSettings::color, GLHelper::drawText(), RAD2DEG, GUIVisualizationTextSettings::size, SUMOReal, Position::x(), and Position::y().
Referenced by drawLinkNo(), and drawTLSLinkNo().
void GUILane::drawTLSLinkNo (const GUIVisualizationSettings & s, const GUINet & net) const private
Definition at line 224 of file GUILane.cpp.
References GUIVisualizationSettings::drawLinkTLIndex, drawTextAtEnd(), PositionVector::extrapolate(), MSLinkContHelper::getConnectingLink(), MSLane::getEdge(), MSNet::getInstance(), GUINet::getLinkTLIndex(), MSLane::getLogicalPredecessorLane(), getShape(), MSNet::lefthand(), myHalfLaneWidth, MSLane::myLinks, MSLane::myWidth, PositionVector::reverse(), SUMOReal, and toString().
Referenced by drawGL().
bool MSLane::empty () const inline inherited
Returns true if there is not a single vehicle on the lane.
Definition at line 549 of file MSLane.h.
References MSLane::myVehBuffer, MSLane::myVehicles, MSLane::setLength(), MSLane::setMaxSpeed(), and SUMOReal.
Referenced by MSQueueExport::writeLane().
void MSLane::enteredByLaneChange (MSVehicle * v) inherited
Definition at line 1952 of file MSLane.cpp.
References MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), MSLane::myBruttoVehicleLengthSum, and MSLane::myNettoVehicleLengthSum.
Referenced by MSLane::dictSize(), and MSAbstractLaneChangeModel::primaryLaneChanged().
bool GUILane::executeMovements (SUMOTime t, std::vector< MSLane * > & into) virtual
the same as in MSLane, but locks the access for the visualisation first; the access will be granted at the end of this method
Reimplemented from MSLane.
Definition at line 146 of file GUILane.cpp.
References MSLane::executeMovements(), and myLock.
template<class RTREE > template void MSLane::fill< LANE_RTREE_QUAL > (RTREE & into) static inherited
Fills the given RTree with lane instances.
Parameters
Definition at line 1266 of file MSLane.cpp.
References PositionVector::getBoxBoundary(), MSLane::getShape(), Boundary::grow(), LANE_RTREE_QUAL, MSLane::myDict, Boundary::xmax(), Boundary::xmin(), Boundary::ymax(), and Boundary::ymin().
Referenced by TraCIServer::collectObjectsInRange(), MSLane::dictSize(), and MSNet::getLanesRTree().
SUMOReal GUILane::firstWaitingTime () const
Definition at line 818 of file GUILane.cpp.
References MSLane::myVehicles, and SUMOReal.
Referenced by getColorValue(), and getScaleValue().
void MSLane::forceVehicleInsertion (MSVehicle * veh, SUMOReal pos, MSMoveReminder::Notification notification, SUMOReal posLat = 0) inherited
Inserts the given vehicle at the given position.
No checks are done, vehicle insertion using this method may generate collisions (possibly delayed).
Parameters
[in] veh The vehicle to insert
[in] pos The position at which the vehicle shall be inserted
[in] notification The cause of insertion (i.e. departure, teleport, parking) defaults to departure
[in] posLat The lateral position at which the vehicle shall be inserted
Definition at line 743 of file MSLane.cpp.
References MSLane::getDepartSpeed(), MSVehicle::getSpeed(), MSBaseVehicle::hasDeparted(), MSLane::incorporateVehicle(), MSLane::myVehicles, SUMOReal, and MSVehicle::updateBestLanes().
Referenced by MSLaneChanger::changeOpposite(), MSLane::getMoveReminders(), MSVehicle::Influencer::postProcessVTD(), and TraCIServerAPI_Vehicle::processSet().
bool MSLane::freeInsertion (MSVehicle & veh, SUMOReal speed, MSMoveReminder::Notification notification = MSMoveReminder::NOTIFICATION_DEPARTED) inherited
Tries to insert the given vehicle on any place.
Parameters
[in] veh The vehicle to insert
[in] speed The maximum insertion speed
[in] notification The cause of insertion (i.e. departure, teleport, parking) defaults to departure
Returns
Whether the vehicle could be inserted
Definition at line 283 of file MSLane.cpp.
References MSVehicle::getBackPositionOnLane(), MSVehicle::getCarFollowModel(), MSLane::getFirstFullVehicle(), MSVehicleType::getLength(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSLane::getMissingRearGap(), MSVehicle::getPositionOnLane(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSCFModel::insertionFollowSpeed(), MSLane::isInsertionSuccess(), MIN2(), MSLane::myLength, MSLane::myPartialVehicles, MSLane::myVehicles, MSMoveReminder::NOTIFICATION_TELEPORT, POSITION_EPS, and SUMOReal.
Referenced by MSVehicleTransfer::checkInsertions(), MSLane::getMoveReminders(), and MSLane::insertVehicle().
const Position MSLane::geometryPositionAtOffset (SUMOReal offset, SUMOReal lateralOffset = 0) const inline inherited
Definition at line 439 of file MSLane.h.
References MSLane::interpolateLanePosToGeometryPos(), MSLane::myShape, and PositionVector::positionAtOffset().
Referenced by GUIE3Collector::MyWrapper::buildDefinition(), MSVehicle::computeAngle(), GUIVehicle::drawAction_drawRailCarriages(), GUIEdge::drawMesoVehicles(), GUIBaseVehicle::drawOnPos(), MSVehicle::getBackPosition(), NLShapeHandler::getLanePos(), MEVehicle::getPosition(), MSVehicle::getPosition(), GUIMEInductLoop::MyWrapper::MyWrapper(), GUIInstantInductLoop::MyWrapper::MyWrapper(), and GUIInductLoop::MyWrapper::MyWrapper().
SUMOReal MSLane::getBruttoOccupancy () const inherited
Returns the brutto (including minGaps) occupancy of this lane during the last step.
Returns
The occupancy during the last step
Definition at line 1970 of file MSLane.cpp.
References MSVehicleType::getLength(), MSVehicle::getPositionOnLane(), MSLane::getVehiclesSecure(), MSBaseVehicle::getVehicleType(), MSLane::myBruttoVehicleLengthSum, MSLane::myLength, MSLane::myPartialVehicles, MSLane::myVehicles, MSLane::releaseVehicles(), and SUMOReal.
Referenced by getColorValue(), MSLane::getIncomingLanes(), getParameterWindow(), getScaleValue(), and MSEdge::insertVehicle().
SUMOReal MSLane::getBruttoVehLenSum () const inline inherited
Returns the sum of lengths of vehicles, including their minGaps, which were on the lane during the last step.
Returns
The sum of vehicle lengths of vehicles in the last step
Definition at line 828 of file MSLane.h.
References MSLane::getCO2Emissions(), MSLane::getCOEmissions(), MSLane::getElectricityConsumption(), MSLane::getFuelConsumption(), MSLane::getHarmonoise_NoiseEmissions(), MSLane::getHCEmissions(), MSLane::getNOxEmissions(), MSLane::getPMxEmissions(), MSLane::myBruttoVehicleLengthSum, and SUMOReal.
Referenced by MSVehicle::checkRewindLinkLanes().
Boundary GUILane::getCenteringBoundary () const virtual
Returns the boundary to which the view shall be centered in order to show the object.
Returns
The boundary the object is within
See also
GUIGlObject::getCenteringBoundary
Implements GUIGlObject.
Definition at line 783 of file GUILane.cpp.
References Boundary::add(), Boundary::grow(), and MSLane::myShape.
SUMOReal MSLane::getCenterOnEdge () const inline inherited
Definition at line 894 of file MSLane.h.
References MSLane::getFollower(), MSLane::getOpposite(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), MSLane::loadState(), MSLane::myRightSideOnEdge, MSLane::myWidth, MSLane::saveState(), MSLane::sortPartialVehicles(), and SUMOReal.
Referenced by MSVehicle::getCenterOnEdge(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
SUMOReal MSLane::getCO2Emissions () const inherited
Returns the sum of last step CO2 emissions.
Returns
CO2 emissions of vehicles on this lane during the last step
Definition at line 2029 of file MSLane.cpp.
References MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), and SUMOReal.
Referenced by MSLane::getBruttoVehLenSum(), getColorValue(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
SUMOReal MSLane::getCOEmissions () const inherited
Returns the sum of last step CO emissions.
Returns
CO emissions of vehicles on this lane during the last step
Definition at line 2041 of file MSLane.cpp.
References MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), and SUMOReal.
Referenced by MSLane::getBruttoVehLenSum(), getColorValue(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
SUMOReal GUILane::getColorValue (int activeScheme) const private
gets the color value according to the current scheme index
Definition at line 901 of file GUILane.cpp.
References firstWaitingTime(), MSLane::getBruttoOccupancy(), MSLane::getCO2Emissions(), MSLane::getCOEmissions(), getEdgeLaneNumber(), MSLane::getElectricityConsumption(), MSLane::getFuelConsumption(), GUIGlObject::getGlID(), MSLane::getHarmonoise_NoiseEmissions(), MSLane::getHCEmissions(), MSNet::getInsertionControl(), MSNet::getInstance(), MSLane::getLength(), getLoadedEdgeWeight(), MSLane::getMeanSpeed(), MSLane::getNettoOccupancy(), MSLane::getNOxEmissions(), MSInsertionControl::getPendingEmits(), MSLane::getPMxEmissions(), MSEdge::getPriority(), MSEdge::getRoutingSpeed(), getShape(), MSLane::getSpeedLimit(), getStoredEdgeTravelTime(), GUIGlObject::getType(), MSNet::getWeightsStorage(), GLO_EDGE, gSelected, isRailway(), GUISelectedStorage::isSelected(), MSEdgeWeightsStorage::knowsTravelTime(), MSLane::myEdge, MSLane::myLength, MSLane::myLengthGeometryFactor, MSLane::myMaxSpeed, MSLane::myPermissions, MSEdgeWeightsStorage::retrieveExistingTravelTime(), SUMOReal, SVC_AUTHORITY, SVC_BICYCLE, SVC_PASSENGER, SVC_PEDESTRIAN, and SVC_SHIP.
Referenced by drawAsWaterway(), and setColor().
std::pair< MSVehicle *const, SUMOReal > MSLane::getCriticalLeader (SUMOReal dist, SUMOReal seen, SUMOReal speed, const MSVehicle & veh) const inherited
Returns the most dangerous leader and the distance to him.
Goes along the vehicle's estimated used lanes (bestLaneConts). For each link, it is determined whether the ego vehicle will pass it. If so, the subsequent lane is investigated. Check all lanes up to the stopping distance of ego. Return the leader vehicle (and the gap) which puts the biggest speed constraint on ego.
If no leading vehicle was found, <0, -1> is returned.
Pretty slow, as it has to go along lanes.
Parameters
[in] dist The distance to investigate
[in] seen The already seen place (normally the place in front on own lane)
[in] speed The speed of the vehicle used for determining whether a subsequent link will be opened at arrival time
[in] veh The (ego) vehicle for which the information shall be computed
Returns
Definition at line 1814 of file MSLane.cpp.
References MSCFModel::brakeGap(), MSVehicle::getBackPositionOnLane(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), MSBaseVehicle::getImpatience(), MSNet::getInstance(), MSLane::getLastAnyVehicle(), MSVehicle::getLateralPositionOnLane(), MSVehicleType::getLength(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSVehicle::getSafeFollowSpeed(), MSVehicle::getSpeed(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSCFModel::insertionFollowSpeed(), MSLane::isLinkEnd(), max, MAX2(), NUMERICAL_EPS, MSLane::succLinkSec(), SUMOReal, and TIME2STEPS.
Referenced by MSLaneChanger::checkChange(), and MSLane::getIncomingLanes().
int MSLane::getCrossingIndex () const inherited
return the index of the link to the next crossing if this is walkingArea, else -1
Definition at line 1959 of file MSLane.cpp.
References MSLane::myLinks, and SUMOReal.
Referenced by MSLane::getIndex().
SUMOReal MSLane::getDepartSpeed (const MSVehicle & veh, bool & patchSpeed) protected inherited
Definition at line 371 of file MSLane.cpp.
References DEPART_SPEED_DEFAULT, DEPART_SPEED_GIVEN, DEPART_SPEED_MAX, DEPART_SPEED_RANDOM, SUMOVehicleParameter::departSpeed, SUMOVehicleParameter::departSpeedProcedure, MSBaseVehicle::getParameter(), MSLane::getVehicleMaxSpeed(), RandHelper::rand(), and SUMOReal.
Referenced by MSLane::forceVehicleInsertion(), MSLane::insertVehicle(), and MSLane::teleportOnCollision().
MSEdge& MSLane::getEdge () const inline inherited
Returns the lane's edge.
Returns
This lane's edge
Definition at line 567 of file MSLane.h.
References MSLane::clear(), MSLane::dictionary(), MSLane::getInternalFollower(), and MSLane::myEdge.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), TraCIServerAPI_Lane::StoringVisitor::add(), MSLane::addApproachingLane(), MSRouteHandler::addStop(), MSVehicle::addStop(), MSEdge::allowedLanes(), MSSwarmTrafficLightLogic::allowLine(), MSSOTLE2Sensors::buildSensorForLane(), MSEdge::changeLanes(), MSLaneChanger::changeOpposite(), MSLCM_SL2015::checkBlocking(), MSLaneChanger::checkChange(), MSVehicle::checkRewindLinkLanes(), MSEdge::closeBuilding(), closeTraffic(), MSDevice_Tripinfo::computeLengthAndDuration(), GUIDetectorBuilder::createInductLoop(), NLDetectorBuilder::createInductLoop(), drawLinkNo(), drawLinkRules(), drawTLSLinkNo(), MSVehicle::enterLaneAtMove(), MSVehicle::executeMove(), MSLane::executeMovements(), MS_E2_ZS_CollectorOverLanes::extendTo(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCenterOnEdge(), MSVehicle::getDistanceToPosition(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLaneIndex(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSVehicle::getLatOffset(), MSLane::getLogicalPredecessorLane(), MSPModel_Striping::PState::getNextEdge(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextLaneObstacles(), MSVehicle::getPosition(), MSAbstractLaneChangeModel::getShadowDirection(), MSStoppingPlace::hasAccess(), MSVehicle::Influencer::implicitDeltaPosVTD(), MSVehicle::Influencer::implicitSpeedVTD(), MSVehicle::influenceChangeDecision(), MSRailSignal::init(), MSLane::isInsertionSuccess(), MSJunction::isLeader(), MSLCM_SL2015::keepLatGap(), MSLink::lastWasContMajor(), MESegment::limitedControlOverride(), MSPedestrianPushButton::loadPushButtons(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), MSPModel_Striping::PState::moveToNextLane(), GUIViewTraffic::onCmdAddRerouter(), GUIViewTraffic::onCmdCloseEdge(), MSLane::edge_finder::operator()(), NLTriggerBuilder::parseAndBuildCalibrator(), MSRouteHandler::parseWalkPositions(), MSLCM_DK2008::patchSpeed(), MSVehicle::planMoveInternal(), MSLCM_SL2015::prepareStep(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Lane::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_Lane::processSet(), MSPModel_Striping::PState::PState(), MSVehicle::replaceRoute(), MSVehicle::resumeFromStopping(), MSLink::setRequestInformation(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), MSLane::succLinkSec(), MSVehicle::unsafeLinkAhead(), MSVehicle::updateBestLanes(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSFCDExport::write(), and MSLink::writeApproaching().
SUMOReal GUILane::getEdgeLaneNumber () const
Definition at line 824 of file GUILane.cpp.
References MSEdge::getLanes(), MSLane::myEdge, and SUMOReal.
Referenced by getColorValue(), and getScaleValue().
SUMOReal MSLane::getElectricityConsumption () const inherited
Returns the sum of last step electricity consumption.
Returns
electricity consumption of vehicles on this lane during the last step
Definition at line 2101 of file MSLane.cpp.
References MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), and SUMOReal.
Referenced by MSLane::getBruttoVehLenSum(), getColorValue(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
MSVehicle * MSLane::getFirstAnyVehicle () const inherited
returns the first vehicle that is fully or partially on this lane
Definition at line 1382 of file MSLane.cpp.
References MSVehicle::getPositionOnLane(), MSLane::myPartialVehicles, and MSLane::myVehicles.
Referenced by MSLane::dictSize(), and MSLane::getFollowerOnConsecutive().
MSVehicle * MSLane::getFirstFullVehicle () const inherited
returns the first vehicle for which this lane is responsible or 0
Definition at line 1359 of file MSLane.cpp.
References MSLane::myVehicles.
Referenced by MSLane::dictSize(), MSLane::freeInsertion(), and MSLane::getFollowerOnConsecutive().
const MSLeaderInfo & MSLane::getFirstVehicleInformation (const MSVehicle * ego, SUMOReal latOffset, bool onlyFrontOnLane, SUMOReal maxPos = std::numeric_limits<SUMOReal>::max(), bool allowCached = true) const inherited
analogue to getLastVehicleInformation but in the upstream direction
Definition at line 822 of file MSLane.cpp.
References MSLeaderInfo::addLeader(), MSLane::anyVehiclesUpstreamBegin(), DEBUG_COND2, MSNet::getCurrentTimeStep(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLatOffset(), MSVehicle::getPositionOnLane(), MSVehicle::isFrontOnLane(), max, MSLane::myFollowerInfo, MSLane::myFollowerInfoTime, MSLane::myLeaderInfoTmp, and SUMOReal.
Referenced by MSLane::getFollowersOnConsecutive(), and MSLane::getMoveReminders().
std::pair< MSVehicle *const, SUMOReal > MSLane::getFollower (const MSVehicle * ego, SUMOReal egoPos, SUMOReal dist) const inherited
Find follower vehicle for the given ego vehicle (which may be on the opposite direction lane)
Parameters
[in] ego The ego vehicle
[in] egoPos The ego position mapped to the current lane
[in] dist The look-back distance when looking at consecutive lanes
Returns
the follower vehicle and it's gap to ego
Definition at line 2450 of file MSLane.cpp.
References MSLane::anyVehiclesUpstreamBegin(), MSLane::anyVehiclesUpstreamEnd(), DEBUG_COND2, MSVehicle::getCarFollowModel(), MSLane::getFollowerOnConsecutive(), Named::getID(), MSBaseVehicle::getID(), MSVehicleType::getLength(), MSCFModel::getMaxDecel(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), and MSBaseVehicle::getVehicleType().
Referenced by MSLane::getCenterOnEdge(), MSLane::getOppositeFollower(), and MSLane::getOppositeLeader().
std::pair< MSVehicle *const, SUMOReal > MSLane::getFollowerOnConsecutive (SUMOReal backOffset, SUMOReal leaderSpeed, SUMOReal leaderMaxDecel, SUMOReal dist = -1) const inherited
return the follower with the largest missing rear gap among all predecessor lanes (within dist)
XXX dubious term. here for backwards compatibility
Definition at line 1573 of file MSLane.cpp.
References DEBUG_COND, MSLane::getFirstAnyVehicle(), MSLane::getFirstFullVehicle(), Named::getID(), Named::getIDSecure(), MSLane::getIncomingLanes(), MSLane::getLength(), MSLane::getMaximumBrakeDist(), MSVehicle::getPositionOnLane(), MSLane::IncomingLaneInfo::lane, MSLane::IncomingLaneInfo::length, max, MAX2(), MSLane::myIncomingLanes, SIMTIME, SUMOReal, and MSLane::IncomingLaneInfo::viaLink.
Referenced by MSLane::getFollower(), MSLane::getIncomingLanes(), and MSLane::getMissingRearGap().
MSLeaderDistanceInfo MSLane::getFollowersOnConsecutive (const MSVehicle * ego, bool allSublanes) const inherited
return the sublane followers with the largest missing rear gap among all predecessor lanes (within dist)
XXX iterate in reverse and abort when there are no more freeSublanes
XXX dubious term. here for backwards compatibility
Definition at line 2197 of file MSLane.cpp.
References MSCriticalFollowerDistanceInfo::addFollower(), MSLane::anyVehiclesBegin(), MSLane::anyVehiclesEnd(), DEBUG_COND2, MSLane::getEdge(), MSLane::getFirstVehicleInformation(), Named::getID(), MSBaseVehicle::getID(), Named::getIDSecure(), MSLane::getIncomingLanes(), MSVehicle::getLane(), MSVehicle::getLatOffset(), MSLane::getLength(), MSLane::getMaximumBrakeDist(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSLane::getRightSideOnEdge(), MSBaseVehicle::getVehicleType(), MSVehicle::isFrontOnLane(), MSLane::IncomingLaneInfo::lane, MSLane::IncomingLaneInfo::length, MAX2(), MSLane::myIncomingLanes, MSLeaderInfo::numFreeSublanes(), SIMTIME, SUMOReal, MSLeaderInfo::toString(), MSCriticalFollowerDistanceInfo::toString(), and MSLane::IncomingLaneInfo::viaLink.
Referenced by MSLane::getIncomingLanes(), and MSLane::isInsertionSuccess().
SUMOReal MSLane::getFuelConsumption () const inherited
Returns the sum of last step fuel consumption.
Returns
fuel consumption of vehicles on this lane during the last step
Definition at line 2089 of file MSLane.cpp.
References MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), and SUMOReal.
Referenced by MSLane::getBruttoVehLenSum(), getColorValue(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
const std::string & GUIGlObject::getFullName () const inherited
Definition at line 111 of file GUIGlObject.cpp.
References GUIGlObject::myFullName.
Referenced by GUIGlObject::buildPopupHeader(), GUIGlObject_AbstractAdd::GUIGlObject_AbstractAdd(), GUIGLObjectPopupMenu::onCmdCopyTypedName(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), GUILaneSpeedTrigger::openManipulator(), GUICalibrator::openManipulator(), GUITriggeredRerouter::openManipulator(), GUIDialog_GLChosenEditor::rebuildList(), GUIGlObject_AbstractAdd::remove(), GUISelectedStorage::save(), and GUISUMOAbstractView::showToolTipFor().
GUIGlID GUIGlObject::getGlID () const inherited
Returns the numerical id of the object.
Returns
This object's gl-id
Definition at line 123 of file GUIGlObject.cpp.
References GUIGlObject::myGlID.
Referenced by GNENet::addReversedEdge(), GUIMessageWindow::appendMsg(), GUIGlObject::buildSelectionPopupEntry(), GUINet::createTLWrapper(), GNENet::deleteEdge(), GNENet::deleteJunction(), GNENet::deleteLane(), GUIVehicle::drawAction_drawPersonsAndContainers(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE3::drawGL(), GNEInternalLane::drawGL(), GNECrossing::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIPolygon::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GUIPointOfInterest::drawGL(), GNERouteProbe::drawGL(), GNELane::drawGL(), GNEEdge::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GNEPoly::drawGL(), GUIBusStop::drawGL(), GUIEdge::drawGL(), GNEConnection::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), drawGL(), GNERerouter::drawGL(), GUIContainer::drawGLAdditional(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), drawLinkRule(), GUIBaseVehicle::drawOnPos(), GUIMEVehicle::getColorValue(), GUIVehicle::getColorValue(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GUIContainer::getColorValue(), GNEJunction::getColorValue(), GUIPerson::getColorValue(), GNELane::getColorValue(), getColorValue(), GUIEdge::getIDs(), GNEEdge::getLaneGlIDs(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIPerson::getPopUpMenu(), GNELane::getPopUpMenu(), GUIBaseVehicle::getPopUpMenu(), GUIEdge::getScaleValue(), getScaleValue(), GNECalibrator::GNECalibrator(), GNERouteProbe::GNERouteProbe(), GNEVaporizer::GNEVaporizer(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNESelectorFrame::handleIDs(), GNETLSEditorFrame::handleMultiChange(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUIViewTraffic::onCmdAddRerouter(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCenter(), GUIViewTraffic::onCmdCloseEdge(), GUIViewTraffic::onCmdCloseLane(), GNEViewNet::onCmdDuplicateLane(), GUIApplicationWindow::onCmdEditChosen(), GUIGLObjectPopupMenu::onCmdRemoveSelected(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GNEViewNet::onCmdStraightenEdges(), GNEViewNet::onLeftBtnPress(), GUISUMOAbstractView::removeAdditionalGLVisualisation(), GLObjectValuePassConnector< std::pair< SUMOTime, MSPhaseDefinition > >::removeObject(), GUIVehicle::selectBlockingFoes(), GNEJunction::setColor(), GUIMessageWindow::setCursorPos(), and GUIGlObject::~GUIGlObject().
SUMOReal MSLane::getHarmonoise_NoiseEmissions () const inherited
Returns the sum of last step noise emissions.
Returns
noise emissions of vehicles on this lane during the last step
Definition at line 2113 of file MSLane.cpp.
References MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), HelpersHarmonoise::sum(), and SUMOReal.
Referenced by MSLane::getBruttoVehLenSum(), getColorValue(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
SUMOReal MSLane::getHCEmissions () const inherited
Returns the sum of last step HC emissions.
Returns
HC emissions of vehicles on this lane during the last step
Definition at line 2077 of file MSLane.cpp.
References MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), and SUMOReal.
Referenced by MSLane::getBruttoVehLenSum(), getColorValue(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
const std::string& Named::getID () const inline inherited
Returns the id.
Returns
The stored id
Definition at line 66 of file Named.h.
References Named::myID.
Referenced by NIImporter_SUMO::_loadNetwork(), MSVehicle::adaptToLeader(), MSVehicle::adaptToLeaders(), PCPolyContainer::add(), MSVehicleTransfer::add(), TraCIServerAPI_Lane::StoringVisitor::add(), MSDetectorControl::add(), Named::StoringVisitor::add(), ShapeContainer::add(), IntermodalRouter< E, L, N, V >::addAccess(), NLTriggerBuilder::addAccess(), RORouteDef::addAlternative(), MSLane::addApproachingLane(), MSNet::addBusStop(), MSNet::addChargingStation(), NBLoadedSUMOTLDef::addConnection(), NLHandler::addConnection(), MSNet::addContainerStop(), NIXMLConnectionsHandler::addCrossing(), RODFDetectorCon::addDetector(), RONet::addEdge(), ROJTREdge::addFollowerProbability(), MSTLLogicControl::TLSLogicVariants::addLogic(), RONet::addNode(), NIImporter_SUMO::addPhase(), GUIEdge::addRerouter(), NBEdge::addRestrictedLane(), RONet::addRouteDef(), NBDistrict::addSink(), NBDistrict::addSource(), NIXMLEdgesHandler::addSplit(), NBTrafficLightLogic::addStep(), MSRouteHandler::addStop(), ROVehicle::addStop(), MSVehicle::addStop(), NBEdge::addStraightConnections(), NIXMLTrafficLightsHandler::addTlConnection(), NIVissimDisturbance::addToNode(), MSVehicle::addTraciBusOrContainerStop(), MSVehicle::addTraciStop(), AGActivityTripWriter::addTrip(), GUITrafficLightLogicWrapper::begin2TrackPhases(), MSTransportable::Stage_Waiting::beginEventOutput(), MSTransportable::Stage_Driving::beginEventOutput(), NLEdgeControlBuilder::build(), NIVisumTL::build(), RODFNet::buildApproachList(), MS_E2_ZS_CollectorOverLanes::buildCollector(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), NBNode::buildCrossings(), NBNode::buildCrossingsAndWalkingAreas(), NIImporter_VISUM::buildDistrictNode(), NIVissimConnection::buildEdgeConnections(), RODFNet::buildEdgeFlowMap(), GNEConnectorFrame::buildIinternalLanes(), GNETLSEditorFrame::buildIinternalLanes(), NBEdge::buildInnerEdges(), NGEdge::buildNBEdge(), NIVissimEdge::buildNBEdge(), NBRampsComputer::buildOffRamp(), NBRampsComputer::buildOnRamp(), MELoop::buildSegmentsFor(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), NBNode::buildWalkingAreas(), MSBaseVehicle::calculateArrivalParams(), MSSwarmTrafficLightLogic::calculateEtaDiff(), MSSwarmTrafficLightLogic::calculateEtaRatio(), MSSOTLPolicyBasedTrafficLightLogic::canRelease(), MSLaneChanger::changeOpposite(), MELoop::changeSegment(), MSSimpleTrafficLightLogic::changeStepAndDuration(), NBEdge::checkGeometry(), MSVehicleTransfer::checkInsertions(), MSVehicle::checkRewindLinkLanes(), MSSwarmTrafficLightLogic::choosePolicy(), ODDistrictHandler::closeDistrict(), NLHandler::closeEdge(), RORouteHandler::closeRouteDistribution(), RORouteHandler::closeVehicle(), NBTrafficLightDefinition::collectAllLinks(), NBLoadedSUMOTLDef::collectEdges(), NBTrafficLightDefinition::collectEdges(), NBLoadedSUMOTLDef::collectEdgeVectors(), NBLoadedTLDef::collectLinks(), ROJTRRouter::compute(), NBTrafficLightDefinition::compute(), NBNode::computeInternalLaneShape(), NBEdge::computeLaneShapes(), NBNode::computeLogic(), NBOwnTLDef::computeLogicAndConts(), NBNode::computeNodeShape(), RODFNet::computeRoutesFor(), NBTrafficLightLogicCont::computeSingleLogic(), NBNode::computeSmoothShape(), NBTurningDirectionsComputer::computeTurnDirectionsForNode(), NGNet::connect(), NLDetectorBuilder::convUncontE2PosLength(), MSSOTLWaveTrafficLightLogic::countVehicles(), MSSOTLE2Sensors::countVehicles(), GUINet::createTLWrapper(), MSDeterministicHiLevelTrafficLightLogic::decideNextPhase(), MSSOTLPolicyBasedTrafficLightLogic::decideNextPhase(), MSSwarmTrafficLightLogic::decideNextPhase(), MSDeterministicHiLevelTrafficLightLogic::decidePolicy(), MSSwarmTrafficLightLogic::decidePolicy(), NIVissimDistrictConnection::dict_BuildDistricts(), NBEdge::divideOnEdges(), NBEdge::divideSelectedLanesOnEdges(), MSTransportable::Stage_Waiting::endEventOutput(), MSTransportable::Stage_Driving::endEventOutput(), MSE3Collector::enter(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Command_SaveTLSState::execute(), Command_SaveTLSSwitchStates::execute(), Command_SaveTLSSwitches::execute(), MSVTypeProbe::execute(), MSPModel_Striping::MovePedestrians::execute(), MSTrafficLightLogic::SwitchCommand::execute(), MSVehicle::executeMove(), MSLane::executeMovements(), NBNodeCont::extract(), NBTrafficLightLogicCont::extract(), NBEdgeCont::extract(), TraCIServerAPI_Vehicle::findCloserLane(), NBRampsComputer::fulfillsRampConstraints(), RODFDetectorCon::getAggFlowFor(), RODFDetectorCon::getAnyDetectorForEdge(), MSVehicle::getBackPosition(), MSNet::getBusStopID(), MSVehicle::getCenterOnEdge(), MSDevice_Battery::getChargingStationID(), MSNet::getChargingStationID(), NBEdge::getConnection(), MSNet::getContainerStopID(), NBEdge::getCrossingAngle(), GNEEdge::getDest(), RODFNet::getDetectorEdge(), MSMeanData::getEdgeID(), MSE2Collector::getEstimateQueueLength(), NBEdge::getFirstNonPedestrianLane(), MSLane::getFollower(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MS_E2_ZS_CollectorOverLanes::getLanePredeccessorLanes(), MSLane::getLastVehicleInformation(), MSVehicle::getLatOffset(), MSLane::getLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSTLLogicControl::TLSLogicVariants::getLogicInstantiatingOff(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForInputLanes(), MSDeterministicHiLevelTrafficLightLogic::getMeanSpeedForOutputLanes(), NIImporter_VISUM::getNamedEdgeContinuating(), MSPerson::getNextEdge(), MSPModel_Striping::getNextLane(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), MSLane::getOppositePos(), GUIInstantInductLoop::MyWrapper::getParameterWindow(), GUIMEInductLoop::MyWrapper::getParameterWindow(), GUI_E2_ZS_Collector::MyWrapper::getParameterWindow(), GUIVehicle::getParameterWindow(), GUIInductLoop::MyWrapper::getParameterWindow(), MSLane::getPartialBehind(), MSSOTLTrafficLightLogic::getPhaseIndexWithMaxCTS(), MSSwarmTrafficLightLogic::getPheromoneForInputLanes(), MSSwarmTrafficLightLogic::getPheromoneForOutputLanes(), GUITrafficLightLogicWrapper::getPopUpMenu(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), NBNode::getPossiblySplittedIncoming(), NBNode::getPossiblySplittedOutgoing(), NIImporter_VISUM::getReversedContinuating(), GNEEdge::getSource(), MSVehicleControl::getWaitingVehicle(), MSLink::getZipperSpeed(), NBNode::guessCrossings(), RODFDetectorCon::guessEmptyFlows(), NBEdgeCont::guessSidewalks(), NBNodeCont::guessTLs(), GUITLLogicPhasesTrackerWindow::GUITLLogicPhasesTrackerWindow(), MSLane::handleCollisionBetween(), NBEdgeCont::ignoreFilterMatch(), MSDeterministicHiLevelTrafficLightLogic::init(), MSRailSignal::init(), MSActuatedTrafficLightLogic::init(), MSTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), NIImporter_SUMO::initTrafficLightLogic(), NIXMLTrafficLightsHandler::initTrafficLightLogic(), NBDistrictCont::insert(), NBNodeCont::insert(), NBTrafficLightLogicCont::insert(), NBEdgeCont::insert(), MSEdge::insertVehicle(), IntermodalNetwork< E, L, N, V >::IntermodalNetwork(), GNEJunction::invalidateTLS(), NBNode::invalidateTLS(), MSTLLogicControl::isActive(), MSPedestrianPushButton::isActiveForEdge(), MSPedestrianPushButton::isActiveOnAnySideOfTheRoad(), RODFNet::isDestination(), RODFNet::isFalseSource(), MSLane::isInsertionSuccess(), RODFNet::isSource(), MSSOTLTrafficLightLogic::isThresholdPassed(), NBNodeCont::joinJunctions(), NBEdgeCont::joinSameNodeConnectingEdges(), MSE3Collector::leave(), MSDevice_BTreceiver::BTreceiverUpdate::leaveRange(), MSPedestrianPushButton::loadCrossingEdgeMap(), NIImporter_OpenDrive::loadNetwork(), MSPedestrianPushButton::loadPushButtons(), NBEdge::MainDirections::MainDirections(), ODDistrictCont::makeDistricts(), NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), MSSOTLE2Sensors::meanVehiclesSpeed(), METriggeredCalibrator::METriggeredCalibrator(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::moveInDirectionOnLane(), NBRampsComputer::moveRampRight(), MSPModel_Striping::PState::moveToNextLane(), MSCalibrator::MSCalibrator(), MSChargingStation::MSChargingStation(), MSDevice_Battery::MSDevice_Battery(), NBLoadedTLDef::myCompute(), NIXMLEdgesHandler::myEndElement(), NIImporter_SUMO::myEndElement(), NIXMLConnectionsHandler::myStartElement(), MSLaneSpeedTrigger::myStartElement(), MSTriggeredRerouter::myStartElement(), NBConnection::NBConnection(), NBRequest::NBRequest(), MSDevice_BTreceiver::notifyEnter(), MSDevice_BTsender::notifyEnter(), MSDevice_Example::notifyEnter(), MSDevice_Tripinfo::notifyEnter(), MSTriggeredRerouter::notifyEnter(), MSE2Collector::notifyEnter(), MSDevice_Transportable::notifyLeave(), MSE3Collector::MSE3EntryReminder::notifyLeave(), MSDevice_Example::notifyLeave(), MSDevice_Tripinfo::notifyLeave(), MSDevice_BTreceiver::notifyLeave(), MSDevice_BTsender::notifyLeave(), MSDevice_Example::notifyMove(), MSDevice_BTreceiver::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSDevice_BTsender::notifyMove(), MSE2Collector::notifyMove(), GUIViewTraffic::onGamingClick(), GNEViewNet::onLeftBtnPress(), RORouteHandler::openRoute(), Named::ComparatorIdLess::operator()(), NBTurningDirectionsComputer::combination_by_angle_sorter::operator()(), RODFNet::idComp::operator()(), NBNetBuilder::by_id_sorter::operator()(), NBOwnTLDef::edge_by_incoming_priority_sorter::operator()(), NBContHelper::same_connection_edge_sorter::operator()(), NBContHelper::edge_by_angle_to_nodeShapeCentroid_sorter::operator()(), NBNode::nodes_by_id_sorter::operator()(), MSEdge::by_id_sorter::operator()(), NIImporter_VISUM::parse_EdgePolys(), NIImporter_VISUM::parse_Lanes(), NIImporter_VISUM::parse_LanesConnections(), NIImporter_VISUM::parse_Turns(), NIImporter_VISUM::parse_TurnsToSignalGroups(), NIXMLConnectionsHandler::parseDeprecatedLaneDefinition(), NIXMLConnectionsHandler::parseLaneBound(), MSRouteHandler::parseWalkPositions(), NBLoadedSUMOTLDef::patchIfCrossingsAdded(), MSLCM_SL2015::patchSpeed(), MSLCM_JE2013::patchSpeed(), MSLCM_LC2013::patchSpeed(), NBLoadedTLDef::SignalGroup::patchTYellow(), MSVehicle::planMove(), MSLane::planMovements(), MSRightOfWayJunction::postloadInit(), NBEdge::prepareEdgePriorities(), MSAbstractLaneChangeModel::primaryLaneChanged(), AGStreet::print(), TraCIServerAPI_InductionLoop::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_ArealDetector::processGet(), TraCIServerAPI_Lane::processGet(), MSVehicle::processNextStop(), TraCIServerAPI_Vehicle::processSet(), NIXMLNodesHandler::processTrafficLightDefinitions(), NWWriter_SUMO::prohibitionConnection(), MSPModel_Striping::PState::PState(), NBEdgeCont::recheckPostProcessConnections(), NIImporter_OpenStreetMap::reconstructLayerElevation(), NBLoadedTLDef::SignalGroup::remapIncoming(), NBLoadedTLDef::SignalGroup::remapOutgoing(), NBLoadedSUMOTLDef::removeConnection(), NBNodeCont::removeIsolatedRoads(), MSCalibrator::removePending(), NBNode::removeSelfLoops(), NBEdgeCont::removeUnwishedEdges(), NBNodeCont::rename(), NBEdgeCont::rename(), GNENet::renameEdge(), GNENet::renameJunction(), RORouteDef::repairCurrentRoute(), NBConnection::replaceFrom(), MSBaseVehicle::replaceRouteEdges(), NBConnection::replaceTo(), NIImporter_DlrNavteq::TrafficlightsHandler::report(), MSBaseVehicle::reroute(), MSLane::resetPartialOccupation(), NIXMLTrafficLightsHandler::retrieveLaneIndex(), RODFNet::revalidateFlows(), RONet::saveAndRemoveRoutesUntil(), MSBaseVehicle::saveState(), MSLane::saveState(), MSDevice_Battery::setAirDragCoefficient(), NBNodeCont::setAsTLControlled(), MSChargingStation::setChargeDelay(), MSChargingStation::setChargingPower(), MSDevice_Battery::setConstantPowerIntake(), NBEdge::setControllingTLInformation(), MSChargingStation::setEfficency(), MSDevice_Battery::setFrontSurfaceArea(), MSDevice_Battery::setInternalMomentOfInertia(), GNEJunction::setLogicValid(), MSDevice_Battery::setMass(), MSDevice_Battery::setMaximumBatteryCapacity(), NIXMLEdgesHandler::setNodes(), MSLane::setPartialOccupation(), MSDevice_Battery::setPowerMax(), MSDevice_Battery::setPropulsionEfficiency(), MSDevice_Battery::setRadialDragCoefficient(), MSDevice_Battery::setRecuperationEfficiency(), MSLink::setRequestInformation(), MSDevice_Battery::setRollDragCoefficient(), MSTLLogicControl::TLSLogicVariants::setStateInstantiatingOnline(), NBLoadedSUMOTLDef::setTLControllingInformation(), NBOwnTLDef::setTLControllingInformation(), NBTrafficLightLogicCont::setTLControllingInformation(), NBLoadedTLDef::setTLControllingInformation(), NBEdge::shiftPositionAtNode(), NBEdgeCont::splitAt(), MSLane::succLinkSec(), GUITrafficLightLogicWrapper::switchTLSLogic(), MELoop::teleportVehicle(), METriggeredCalibrator::tryEmit(), MSSOTLTrafficLightLogic::trySwitch(), MSVehicle::updateBestLanes(), MSSOTLTrafficLightLogic::updateCTS(), GNETLSEditorFrame::updateDescription(), MSSwarmTrafficLightLogic::updatePheromoneLevels(), MSSwarmTrafficLightLogic::updateSensitivities(), MSDevice_BTreceiver::BTreceiverUpdate::updateVisibility(), TraCIServerAPI_Vehicle::vtdMap(), MSPModel_Striping::PState::walk(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), MSLCM_SL2015::wantsChangeSublane(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSLink::writeApproaching(), NBSign::writeAsPOI(), NWWriter_SUMO::writeConnection(), NWWriter_SUMO::writeDistrict(), MSFullExport::writeEdge(), MSXMLRawOut::writeEdge(), NWWriter_SUMO::writeEdge(), MSMeanData::writeEdge(), NWWriter_XML::writeEdgesAndConnections(), RODFDetector::writeEmitterDefinition(), RODFDetectorCon::writeEmitterPOIs(), RODFDetectorCon::writeEmitters(), RODFDetectorCon::writeEndRerouterDetectors(), NWWriter_SUMO::writeInternalConnections(), writeInterval(), NWWriter_SUMO::writeJunction(), MSQueueExport::writeLane(), MSFullExport::writeLane(), NWWriter_DlrNavteq::writeLinksUnsplitted(), NWWriter_OpenDrive::writeNetwork(), NWWriter_XML::writeNodes(), NWWriter_DlrNavteq::writeNodesUnsplitted(), NWWriter_SUMO::writeRoundabout(), RODFDetectorCon::writeSpeedTrigger(), NWWriter_DlrNavteq::writeTrafficSignals(), MSFCDExport::writeTransportable(), MSInductLoop::writeTypedXMLOutput(), RODFDetectorCon::writeValidationDetectors(), MSFullExport::writeVehicles(), PointOfInterest::writeXML(), SUMO::Polygon::writeXML(), MSRouteProbe::writeXMLOutput(), MSE2Collector::writeXMLOutput(), and RONet::~RONet().
template<class T > static std::string Named::getIDSecure (const T * obj, const std::string & fallBack = "NULL") inline static inherited
get an identifier for Named-like object which may be Null
Definition at line 59 of file Named.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::continueChange(), MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), operator<<(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLaneChangerSublane::startChangeSublane(), MSLeaderInfo::toString(), MSLeaderDistanceInfo::toString(), toString(), MSCriticalFollowerDistanceInfo::toString(), MSVehicle::updateBestLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
const std::vector<IncomingLaneInfo>& MSLane::getIncomingLanes () const inline inherited
Definition at line 697 of file MSLane.h.
References MSLane::addApproachingLane(), MSLane::getBruttoOccupancy(), MSLane::getCriticalLeader(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MSLane::getIncomingLinkState(), MSLane::getLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLane::getLogicalPredecessorLane(), MSLane::getMeanSpeed(), MSLane::getMissingRearGap(), MSLane::getNettoOccupancy(), MSLane::getOutgoingLanes(), MSLane::getPartialBehind(), MSLane::getWaitingSeconds(), MSLane::isApproachedFrom(), MSLane::myIncomingLanes, and SUMOReal.
Referenced by MSLink::getApproachingLane(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MSPModel_Striping::getNextWalkingArea(), MSRailSignal::init(), and MSLink::setRequestInformation().
LinkState MSLane::getIncomingLinkState () const inherited
get the state of the link from the logical predecessor to this lane
Definition at line 1923 of file MSLane.cpp.
References MSLinkContHelper::getConnectingLink(), MSLane::getLogicalPredecessorLane(), MSLink::getState(), and LINKSTATE_DEADEND.
Referenced by MSLane::getIncomingLanes().
int MSLane::getIndex () const inline inherited
Returns the lane's index.
Returns
This lane's index
Definition at line 498 of file MSLane.h.
References MSLane::appropriate(), MSLane::detectCollisions(), MSLane::executeMovements(), MSLane::getCrossingIndex(), MSLane::getLinkCont(), MSLane::integrateNewVehicle(), MSLane::myIndex, and MSLane::planMovements().
Referenced by MSLCM_SL2015::_wantsChangeSublane(), drawLinkNo(), MSAbstractLaneChangeModel::getShadowDirection(), MSLink::getZipperSpeed(), MSLink::opened(), MSLaneChangerSublane::startChangeSublane(), and MSLaneChangerSublane::updateChanger().
const MSEdge * MSLane::getInternalFollower () const inherited
Returns the lane's follower if it is an internal lane, the edge of the lane otherwise.
Returns
This lane's follower
Definition at line 1215 of file MSLane.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSEdge::getPurpose(), MSEdge::getSuccessors(), and MSLane::myEdge.
Referenced by MSLane::getEdge(), MSVehicle::getRerouteOrigin(), and MSVehicle::updateBestLanes().
MSVehicle * MSLane::getLastAnyVehicle () const inherited
returns the last vehicle that is fully or partially on this lane
Definition at line 1368 of file MSLane.cpp.
References MSLane::myPartialVehicles, and MSLane::myVehicles.
Referenced by MSVehicle::checkRewindLinkLanes(), MSLane::dictSize(), MSLane::getCriticalLeader(), MSLane::isInsertionSuccess(), and MSLink::maybeOccupied().
MSVehicle * MSLane::getLastFullVehicle () const inherited
returns the last vehicle for which this lane is responsible or 0
Definition at line 1350 of file MSLane.cpp.
References MSLane::myVehicles.
Referenced by MSLane::dictSize().
const MSLeaderInfo & MSLane::getLastVehicleInformation (const MSVehicle * ego, SUMOReal latOffset, SUMOReal minPos = 0, bool allowCached = true) const inherited
Returns the last vehicles on the lane.
The information about the last vehicles in this lanes in all sublanes occupied by ego are returned. Partial occupators are included
Parameters
[in] ego The vehicle for which to restrict the returned leaderInfo
[in] minPos The minimum position from which to start search for leaders
[in] allowCached Whether the cached value may be used
Returns
Information about the last vehicles
Definition at line 771 of file MSLane.cpp.
References MSLeaderInfo::addLeader(), MSLane::anyVehiclesBegin(), DEBUG_COND2, MSNet::getCurrentTimeStep(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLatOffset(), MSVehicle::getPositionOnLane(), MSLane::myLeaderInfo, MSLane::myLeaderInfoTime, MSLane::myLeaderInfoTmp, SUMOReal, and MSLeaderInfo::toString().
Referenced by MSLane::detectCollisions(), MSLane::getLeadersOnConsecutive(), MSLane::getMoveReminders(), MSLane::isInsertionSuccess(), and MSVehicle::planMoveInternal().
std::pair< MSVehicle *const, SUMOReal > MSLane::getLeader (const MSVehicle * veh, const SUMOReal vehPos, const std::vector< MSLane * > & bestLaneConts, SUMOReal dist = -1, bool checkTmpVehicles = false) const inherited
Returns the immediate leader of veh and the distance to veh starting on this lane.
Iterates over the current lane to find a leader and then uses getLeaderOnConsecutive()
Parameters
[in] veh The vehicle for which the information shall be computed
[in] vehPos The vehicle position relative to this lane (may be negative)
[in] bestLaneConts The succeding lanes that shall be checked (if any)
[in] dist Optional distance to override default (ego stopDist)
[in] checkTmpVehicles Whether myTmpVehicles should be used instead of myVehicles
Returns
Definition at line 1664 of file MSLane.cpp.
References MSLane::anyVehiclesBegin(), MSLane::anyVehiclesEnd(), MSCFModel::brakeGap(), DEBUG_COND2, MSVehicle::getBackPositionOnLane(), MSVehicle::getCarFollowModel(), Named::getID(), MSBaseVehicle::getID(), MSLane::getLeaderOnConsecutive(), MSLane::getLength(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSLane::myTmpVehicles, MSLane::myVehicles, NUMERICAL_EPS, SUMOReal, and toString().
Referenced by MSLaneChanger::checkChange(), MSLane::getIncomingLanes(), MSLane::getOppositeFollower(), and MSLane::getOppositeLeader().
std::pair< MSVehicle *const, SUMOReal > MSLane::getLeaderOnConsecutive (SUMOReal dist, SUMOReal seen, SUMOReal speed, const MSVehicle & veh, const std::vector< MSLane * > & bestLaneConts) const inherited
Returns the immediate leader and the distance to him.
Goes along the vehicle's estimated used lanes (bestLaneConts). For each link, it is determined whether the vehicle will pass it. If so, the subsequent lane is investigated. If a vehicle (leader) is found, it is returned, together with the length of the investigated lanes until this vehicle's end, including the already seen place (seen).
If no leading vehicle was found, <0, -1> is returned.
Pretty slow, as it has to go along lanes.
Todo:
: There are some oddities:
what about crossing a link at red, or if a link is closed? Has a following vehicle to be regarded or not?
Parameters
[in] dist The distance to investigate
[in] seen The already seen place (normally the place in front on own lane)
[in] speed The speed of the vehicle used for determining whether a subsequent link will be opened at arrival time
[in] veh The vehicle for which the information shall be computed
[in] bestLaneConts The lanes the vehicle will use in future
Returns
Definition at line 1722 of file MSLane.cpp.
References MSCFModel::brakeGap(), DEBUG_COND2, MSVehicle::getBackPositionOnLane(), MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getImpatience(), MSNet::getInstance(), MSVehicle::getLateralPositionOnLane(), MSVehicleType::getLength(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSBaseVehicle::getVehicleType(), MAX2(), MSLane::myPartialVehicles, NUMERICAL_EPS, MSLane::succLinkSec(), SUMOReal, TIME2STEPS, and toString().
Referenced by MSLane::getIncomingLanes(), MSLane::getLeader(), and MSVehicle::getLeader().
void MSLane::getLeadersOnConsecutive (SUMOReal dist, SUMOReal seen, SUMOReal speed, const MSVehicle * ego, const std::vector< MSLane * > & bestLaneConts, MSLeaderDistanceInfo & result) const inherited
Returns the immediate leaders and the distance to them (as getLeaderOnConsecutive but for the sublane case)
Definition at line 2314 of file MSLane.cpp.
References MSLeaderDistanceInfo::addLeader(), MSCFModel::brakeGap(), DEBUG_COND2, MSVehicle::getBackPositionOnLane(), MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getImpatience(), MSNet::getInstance(), MSLane::getLastVehicleInformation(), MSVehicle::getLateralPositionOnLane(), MSVehicleType::getLength(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSVehicle::isFrontOnLane(), MSLane::isLinkEnd(), MAX2(), MIN2(), MSLane::myPartialVehicles, NUMERICAL_EPS, MSLeaderInfo::numFreeSublanes(), MSLeaderInfo::numSublanes(), SIMTIME, MSLane::succLinkSec(), TIME2STEPS, MSLeaderInfo::toString(), and MSLink::LinkLeader::vehAndGap.
Referenced by MSLane::getIncomingLanes().
SUMOReal MSLane::getLength () const inline inherited
Returns the lane's length.
Returns
This lane's length
Definition at line 475 of file MSLane.h.
References MSLane::myLength.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSVehicle::adaptLaneEntering2MoveReminder(), MSVehicle::adaptToLeaders(), NLTriggerBuilder::addAccess(), NLHandler::addConnection(), MSLane::addIncomingLane(), MSVehicle::addStop(), GUI_E2_ZS_CollectorOverLanes::buildCollector(), MS_E2_ZS_CollectorOverLanes::buildCollector(), MSSOTLE2Sensors::buildContinueSensior(), MSSOTLE2Sensors::buildCountSensorForLane(), MSSOTLE2Sensors::buildCountSensorForOutLane(), MSSOTLE2Sensors::buildSensorForLane(), MSSOTLE2Sensors::buildSensorForOutLane(), MSLaneChanger::changeOpposite(), MSLaneChanger::checkChange(), MSVehicle::checkRewindLinkLanes(), NLDetectorBuilder::convUncontE2PosLength(), MSE2Collector::detectorUpdate(), MSPModel_Striping::PState::distToLaneEnd(), GUIVehicle::drawAction_drawRailCarriages(), MSVehicle::executeMove(), MSLane::executeMovements(), MS_E2_ZS_CollectorOverLanes::extendTo(), MSLane::freeInsertion(), getColorValue(), MSLane::getCriticalLeader(), MSVehicle::getDistanceToPosition(), MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), TraCIServerAPI_Simulation::getLaneChecking(), NLShapeHandler::getLanePos(), MSLane::getLeader(), MSVehicle::getLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSLane::getOppositePos(), NLTriggerBuilder::getPosition(), NLDetectorBuilder::getPositionChecking(), MSDevice_Battery::getPropEnergy(), MSVehicle::getRerouteOrigin(), MSVehicle::getSafeFollowSpeed(), MSVehicle::getSpaceTillLastStanding(), MSActuatedTrafficLightLogic::init(), MS_E2_ZS_CollectorOverLanes::init(), MSLane::insertVehicle(), MSLane::isInsertionSuccess(), MSLink::maybeOccupied(), MSPModel_Striping::moveInDirectionOnLane(), MSPModel_Striping::PState::moveToNextLane(), NLTriggerBuilder::parseAndBuildChargingStation(), NLTriggerBuilder::parseAndBuildStoppingPlace(), MSVehicle::planMoveInternal(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Lane::processGet(), GUIVehicle::selectBlockingFoes(), MSVehicle::setBlinkerInformation(), MSLink::setRequestInformation(), MSVehicle::unsafeLinkAhead(), MSVehicle::updateBestLanes(), TraCIServerAPI_Vehicle::vtdMap(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), MSLink::writeApproaching(), MSMeanData::writeEdge(), and MSQueueExport::writeLane().
SUMOReal MSLane::getLengthGeometryFactor () const inline inherited
return shape.length() / myLength
Definition at line 427 of file MSLane.h.
References MSLane::myLengthGeometryFactor.
const MSLinkCont & MSLane::getLinkCont () const inherited
returns the container with all links !!!
Definition at line 1445 of file MSLane.cpp.
References MSLane::myLinks.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSEdge::changeLanes(), MSLCM_SL2015::computeSublaneShift(), MSLink::getApproachingLane(), MSVehicle::getBestLanesContinuation(), MSLinkContHelper::getConnectingLink(), MSLane::getIndex(), MESegment::getLink(), MSPModel_Striping::getNextLane(), MSPModel_Striping::getNextWalkingArea(), MSRailSignal::init(), MSRightOfWayJunction::postloadInit(), TraCIServerAPI_Lane::processGet(), MSEdge::recalcCache(), MSVehicle::setBlinkerInformation(), MSLink::setRequestInformation(), MSVehicle::updateBestLanes(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), and MSLink::writeApproaching().
SUMOReal GUILane::getLoadedEdgeWeight () const
Returns the loaded weight (effort) for the edge of this lane.
Definition at line 843 of file GUILane.cpp.
References MSNet::getInstance(), MSNet::getWeightsStorage(), MSEdgeWeightsStorage::knowsEffort(), MSLane::myEdge, MSEdgeWeightsStorage::retrieveExistingEffort(), STEPS2TIME, and SUMOReal.
Referenced by getColorValue(), getParameterWindow(), and getScaleValue().
MSLane * MSLane::getLogicalPredecessorLane () const inherited
get the most likely precedecessor lane (sorted using by_connections_to_sorter). The result is cached in myLogicalPredecessorLane
Definition at line 1883 of file MSLane.cpp.
References MSLane::getEdge(), MSEdge::getIncomingEdges(), MSLane::myEdge, MSLane::myIncomingLanes, and MSLane::myLogicalPredecessorLane.
Referenced by MSEdge::allowsLaneChanging(), MSEdge::changeLanes(), drawGL(), drawLinkNo(), drawLinkRules(), drawTLSLinkNo(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSLane::getIncomingLanes(), MSLane::getIncomingLinkState(), MSPModel_Striping::getNextLane(), MSLink::lastWasContMajor(), MSVehicle::planMoveInternal(), MSLink::setRequestInformation(), MSVehicle::updateBestLanes(), TraCIServerAPI_Vehicle::vtdMap(), and MSLink::writeApproaching().
MSLane * MSLane::getLogicalPredecessorLane (const MSEdge & fromEdge) const inherited
return the (first) predecessor lane from the given edge
Definition at line 1911 of file MSLane.cpp.
References MSLane::getEdge(), and MSLane::myIncomingLanes.
const std::map<std::string, std::string>& Parameterised::getMap () const inline inherited
Returns the inner key/value map.
Returns
the inner map
Definition at line 107 of file Parameterised.h.
References Parameterised::myMap.
Referenced by NBTrafficLightDefinition::compute(), MSDevice_Vehroutes::generateOutput(), GUIPerson::getParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), TraCIServerAPI_TLS::processGet(), ROVehicle::saveAsXML(), ROPerson::saveAsXML(), SUMOVTypeParameter::write(), PointOfInterest::writeXML(), and SUMO::Polygon::writeXML().
SUMOReal MSLane::getMaximumBrakeDist () const protected inherited
compute maximum braking distance on this lane
Definition at line 1564 of file MSLane.cpp.
References MSNet::getInstance(), MSVehicleControl::getMaxSpeedFactor(), MSVehicleControl::getMinDeceleration(), MSLane::getSpeedLimit(), MSNet::getVehicleControl(), and SUMOReal.
Referenced by MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), and MSLane::teleportOnCollision().
SUMOReal MSLane::getMeanSpeed () const inherited
Returns the mean speed on this lane.
Returns
The average speed of vehicles during the last step; default speed if no vehicle was on this lane
Definition at line 2013 of file MSLane.cpp.
References MSLane::getVehiclesSecure(), MSLane::myMaxSpeed, MSLane::myVehicles, MSLane::releaseVehicles(), and SUMOReal.
Referenced by getColorValue(), MSLane::getIncomingLanes(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
const std::string & GUIGlObject::getMicrosimID () const virtual inherited
Returns the id of the object as known to microsim.
Definition at line 137 of file GUIGlObject.cpp.
References GUIGlObject::myMicrosimID.
Referenced by GNETLSEditorFrame::controlsEdge(), GUIGlObject::createFullName(), GNENet::deleteSingleEdge(), GNENet::deleteSingleJunction(), GUIGlObject::drawName(), GNEAdditional::getAdditionalID(), GNEPOI::getAttribute(), GNECrossing::getAttribute(), GNEJunction::getAttribute(), GNEPoly::getAttribute(), GNEEdge::getAttribute(), GNELane::getAttribute(), GNELane::getParentName(), GNENetElement::getParentName(), GNEDetectorE3::getParentName(), GNEVaporizer::getParentName(), GNEVariableSpeedSignal::getParentName(), GNERouteProbe::getParentName(), GNEStoppingPlace::getParentName(), GNECalibrator::getParentName(), GNEDetector::getParentName(), GNEAdditional::getParentName(), GNERerouter::getParentName(), GNEAdditional::getPopUpMenu(), GUIDialog_GLObjChooser::GUIDialog_GLObjChooser(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEEdge::isValid(), GNEViewNet::mergeJunctions(), GNEEdge::moveGeometry(), GNEPoly::moveGeometry(), GUIGLObjectPopupMenu::onCmdAddSelected(), GUIGLObjectPopupMenu::onCmdCopyName(), GNEViewNet::onCmdNodeShape(), GNEViewNet::onLeftBtnPress(), GNEInspectorFrame::onUpdCopyTemplate(), GNENet::registerEdge(), GNENet::registerJunction(), GNENet::remapEdge(), GNEEdge::removeConnection(), GNENet::replaceJunctionByGeometry(), GNENet::retrieveAttributeCarriers(), GNEAdditional::setAdditionalID(), GNEEdge::setAttribute(), GNENet::splitEdge(), and GNEConnectorFrame::updateDescription().
SUMOReal MSLane::getMissingRearGap (SUMOReal backOffset, SUMOReal leaderSpeed, SUMOReal leaderMaxDecel) const inherited
return by how much further the leader must be inserted to avoid rear end collisions
Definition at line 1548 of file MSLane.cpp.
References MSVehicle::getCarFollowModel(), MSLane::getFollowerOnConsecutive(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), and SUMOReal.
Referenced by MSLane::freeInsertion(), MSLane::getIncomingLanes(), and MSLane::isInsertionSuccess().
const std::vector< MSMoveReminder* >& MSLane::getMoveReminders () const inline inherited
Return the list of this lane's move reminders.
Returns
Previously added move reminder
Definition at line 228 of file MSLane.h.
References MSLane::checkFailure(), MSLane::forceVehicleInsertion(), MSLane::freeInsertion(), MSLane::getFirstVehicleInformation(), MSLane::getLastVehicleInformation(), MSLane::insertVehicle(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), max, MSLane::myMoveReminders, MSMoveReminder::NOTIFICATION_DEPARTED, MSLane::resetPartialOccupation(), MSLane::setPartialOccupation(), and SUMOReal.
Referenced by MSVehicle::adaptLaneEntering2MoveReminder(), MSVehicle::enterLaneAtInsertion(), and MSVehicle::enterLaneAtLaneChange().
SUMOReal MSLane::getNettoOccupancy () const inherited
Returns the netto (excluding minGaps) occupancy of this lane during the last step (including minGaps)
Returns
The occupancy during the last step
Definition at line 1985 of file MSLane.cpp.
References MSVehicleType::getLength(), MSVehicle::getPositionOnLane(), MSLane::getVehiclesSecure(), MSBaseVehicle::getVehicleType(), MSLane::myLength, MSLane::myNettoVehicleLengthSum, MSLane::myPartialVehicles, MSLane::myVehicles, MSLane::releaseVehicles(), and SUMOReal.
Referenced by getColorValue(), MSLane::getIncomingLanes(), getParameterWindow(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
SUMOReal MSLane::getNOxEmissions () const inherited
Returns the sum of last step NOx emissions.
Returns
NOx emissions of vehicles on this lane during the last step
Definition at line 2065 of file MSLane.cpp.
References MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), and SUMOReal.
Referenced by MSLane::getBruttoVehLenSum(), getColorValue(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
int MSLane::getNumericalID () const inline inherited
Returns this lane's numerical id.
Returns
This lane's numerical id
Definition at line 414 of file MSLane.h.
References MSLane::myNumericalID.
Referenced by MSPModel_Striping::lane_by_numid_sorter::operator()(), and MSPModel_Striping::walkingarea_path_sorter::operator()().
MSLane * MSLane::getOpposite () const inherited
return the opposite direction lane for lane changing or 0
Definition at line 2429 of file MSLane.cpp.
References MSLane::dictionary(), MSLane::myNeighs, and SUMOReal.
Referenced by MSLaneChanger::changeOpposite(), MSVehicle::executeMove(), MSLane::getCenterOnEdge(), MSLane::getOppositePos(), and MSVehicle::planMoveInternal().
std::pair< MSVehicle *const, SUMOReal > MSLane::getOppositeFollower (const MSVehicle * ego) const inherited
Definition at line 2490 of file MSLane.cpp.
References DEBUG_COND2, MSVehicle::getBackPositionOnLane(), MSLane::getFollower(), Named::getID(), MSBaseVehicle::getID(), MSVehicle::getLaneChangeModel(), MSLane::getLeader(), MSVehicleType::getLength(), MSLane::getOppositePos(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getVehicleType(), MSAbstractLaneChangeModel::isOpposite(), and SIMTIME.
Referenced by MSLaneChanger::changeOpposite(), and MSLane::getCenterOnEdge().
std::pair< MSVehicle *const, SUMOReal > MSLane::getOppositeLeader (const MSVehicle * ego, SUMOReal dist) const inherited
Definition at line 2469 of file MSLane.cpp.
References DEBUG_COND2, MSVehicle::getBestLanesContinuation(), MSLane::getFollower(), Named::getID(), MSBaseVehicle::getID(), MSVehicle::getLaneChangeModel(), MSLane::getLeader(), MSVehicleType::getLength(), MSVehicleType::getMinGap(), MSLane::getOppositePos(), MSVehicle::getPositionOnLane(), MSBaseVehicle::getVehicleType(), MSAbstractLaneChangeModel::isOpposite(), SIMTIME, and SUMOReal.
Referenced by MSLaneChanger::changeOpposite(), and MSLane::getCenterOnEdge().
SUMOReal MSLane::getOppositePos (SUMOReal pos) const inherited
return the corresponding position on the opposite lane
Definition at line 2438 of file MSLane.cpp.
References Named::getID(), MSLane::getLength(), and MSLane::getOpposite().
Referenced by MSLaneChanger::changeOpposite(), MSVehicle::executeMove(), MSLane::getCenterOnEdge(), MSLane::getOppositeFollower(), and MSLane::getOppositeLeader().
std::vector< const MSLane * > MSLane::getOutgoingLanes () const inherited
get the list of outgoing lanes
Definition at line 1934 of file MSLane.cpp.
References MSLane::myLinks.
Referenced by MSLane::getIncomingLanes(), MSRailSignal::init(), and MSVehicle::replaceRoute().
MSLane * MSLane::getParallelLane (int offset) const inherited
Returns the lane with the given offset parallel to this one or 0 if it does not exist.
Parameters
[in] offset The offset of the result lane
Definition at line 1494 of file MSLane.cpp.
References MSLane::myEdge, and MSEdge::parallelLane().
Referenced by MSLaneChanger::checkChange(), MSLink::computeParallelLink(), MSLane::dictSize(), MSAbstractLaneChangeModel::getShadowLane(), and MSVehicle::planMoveInternal().
const std::string & Parameterised::getParameter (const std::string & key, const std::string & defaultValue) const inherited
Returns the value for a given key.
Parameters
[in] key The key to ask for
[in] defaultValue The default value to return if no value is stored under the key
Returns
The value stored under the key
Definition at line 81 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSTLLogicControl::WAUTSwitchProcedure_Stretch::adaptLogic(), MSDevice_Battery::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), MSSOTLTrafficLightLogic::getDecayConstant(), MSTLLogicControl::WAUTSwitchProcedure::getGSPValue(), MSSOTLTrafficLightLogic::getInputSensorsLength(), MSSOTLRequestPolicy::getMinDecisionalPhaseDuration(), MSSOTLRequestTrafficLightLogic::getMinDecisionalPhaseDuration(), MSSOTLTrafficLightLogic::getMode(), MSSOTLTrafficLightLogic::getOutputSensorsLength(), MSSOTLTrafficLightLogic::getSpeedThreshold(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchAreaNo(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::getStretchBereichDef(), MSSOTLTrafficLightLogic::getThreshold(), PushButtonLogic::init(), MSSOTLPhasePolicy::init(), SigmoidLogic::init(), MSSOTLTrafficLightLogic::init(), MSSwarmTrafficLightLogic::init(), MSSOTLTrafficLightLogic::isDecayThresholdActivated(), MSSOTLTrafficLightLogic::isPushButtonPressed(), MSActuatedTrafficLightLogic::MSActuatedTrafficLightLogic(), MSSOTLPolicy::MSSOTLPolicy(), MSSOTLPolicy5DFamilyStimulus::MSSOTLPolicy5DFamilyStimulus(), MSSwarmTrafficLightLogic::MSSwarmTrafficLightLogic(), TraCIServerAPI_Edge::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_TLS::processGet(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_Route::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Lane::processGet(), MSSOTLPolicyDesirability::readParameter(), MSTLLogicControl::WAUTSwitchProcedure_Stretch::stretchLogic(), and TraCIServerAPI_Vehicle::vtdMap().
GUIParameterTableWindow * GUILane::getParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own parameter window.
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
See also
GUIGlObject::getParameterWindow
Implements GUIGlObject.
Definition at line 758 of file GUILane.cpp.
References GUIParameterTableWindow::closeBuilding(), MSLane::getBruttoOccupancy(), MSEdge::getEdgeType(), getLoadedEdgeWeight(), MSLane::getNettoOccupancy(), MSEdge::getPriority(), MSEdge::getRoutingSpeed(), MSLane::getSpeedLimit(), getStoredEdgeTravelTime(), MSEdge::getStreetName(), getVehicleClassNames(), GUIParameterTableWindow::mkItem(), MSLane::myEdge, MSLane::myLength, MSLane::myPermissions, and MSLane::myWidth.
const std::string& GUILane::getParentName () const inline virtual
Returns the name of the parent object (if any)
Note
Inherited from GUIGlObject
Returns
This object's parent id
Reimplemented from GUIGlObject.
Definition at line 98 of file GUILane.h.
References SUMOReal.
MSVehicle * MSLane::getPartialBehind (const MSVehicle * ego) const inherited
Definition at line 2405 of file MSLane.cpp.
References DEBUG_COND2, Named::getID(), MSBaseVehicle::getID(), MSVehicle::getPositionOnLane(), MSVehicle::isFrontOnLane(), MSLane::myPartialVehicles, SIMTIME, and toString().
Referenced by MSLane::getIncomingLanes().
int MSLane::getPartialVehicleNumber () const inline inherited
Returns the number of vehicles partially on this lane (for which this lane is not responsible)
Returns
The number of vehicles touching this lane but with their front on another lane
Definition at line 364 of file MSLane.h.
References MSLane::myPartialVehicles.
SVCPermissions MSLane::getPermissions () const inline inherited
Returns the vehicle class permissions for this lane.
Returns
This lane's allowed vehicle classes
Definition at line 483 of file MSLane.h.
References MSLane::myPermissions.
Referenced by MSSwarmTrafficLightLogic::allowLine(), GUIApplicationWindow::onCmdEditChosen(), and TraCIServerAPI_Lane::processGet().
SUMOReal MSLane::getPMxEmissions () const inherited
Returns the sum of last step PMx emissions.
Returns
PMx emissions of vehicles on this lane during the last step
Definition at line 2053 of file MSLane.cpp.
References MSLane::getVehiclesSecure(), MSLane::releaseVehicles(), and SUMOReal.
Referenced by MSLane::getBruttoVehLenSum(), getColorValue(), getScaleValue(), TraCIServerAPI_Lane::processGet(), and MSFullExport::writeLane().
GUIGLObjectPopupMenu * GUILane::getPopUpMenu (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual
Returns an own popup-menu.
Parameters
[in] app The application needed to build the popup-menu
[in] parent The parent window needed to build the popup-menu
Returns
The built popup-menu
See also
GUIGlObject::getPopUpMenu
Implements GUIGlObject.
Definition at line 728 of file GUILane.cpp.
References GUIGlObject::buildCenterPopupEntry(), GUIGlObject::buildNameCopyPopupEntry(), GUIGlObject::buildPopupHeader(), GUIGlObject::buildPositionCopyEntry(), GUIGlObject::buildSelectionPopupEntry(), GUIGlObject::buildShowParamsPopupEntry(), GUISUMOAbstractView::getPositionInformation(), MSLane::interpolateGeometryPosToLanePos(), MID_ADD_REROUTER, MID_CLOSE_EDGE, MID_CLOSE_LANE, MID_COPY_EDGE_NAME, myAmClosed, MSLane::myShape, PositionVector::nearest_offset_to_point2D(), PositionVector::positionAtOffset2D(), SUMOReal, toString(), and Position::z().
int MSLane::getRightmostSublane () const inline inherited
Definition at line 890 of file MSLane.h.
References MSLane::myRightmostSublane.
Referenced by MSLCM_SL2015::_wantsChangeSublane().
SUMOReal MSLane::getRightSideOnEdge () const inline inherited
Definition at line 886 of file MSLane.h.
References MSLane::myRightSideOnEdge.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSLCM_SL2015::checkBlocking(), MSLaneChangerSublane::checkChangeSublane(), MSLane::detectCollisions(), MSVehicle::getCenterOnEdge(), MSLane::getFollowersOnConsecutive(), MSVehicle::getLatOffset(), MSLCM_SL2015::keepLatGap(), MSVehicle::planMoveInternal(), MSLaneChangerSublane::startChangeSublane(), and MSLaneChangerSublane::updateChanger().
SUMOReal GUILane::getScaleValue (int activeScheme) const private
gets the scaling value according to the current scheme index
Definition at line 1004 of file GUILane.cpp.
References firstWaitingTime(), MSLane::getBruttoOccupancy(), MSLane::getCO2Emissions(), MSLane::getCOEmissions(), getEdgeLaneNumber(), MSLane::getElectricityConsumption(), MSLane::getFuelConsumption(), GUIGlObject::getGlID(), MSLane::getHarmonoise_NoiseEmissions(), MSLane::getHCEmissions(), MSNet::getInsertionControl(), MSNet::getInstance(), getLoadedEdgeWeight(), MSLane::getMeanSpeed(), MSLane::getNettoOccupancy(), MSLane::getNOxEmissions(), MSInsertionControl::getPendingEmits(), MSLane::getPMxEmissions(), MSEdge::getPriority(), MSLane::getSpeedLimit(), getStoredEdgeTravelTime(), GUIGlObject::getType(), MSNet::getWeightsStorage(), GLO_EDGE, gSelected, GUISelectedStorage::isSelected(), MSEdgeWeightsStorage::knowsTravelTime(), MSLane::myEdge, MSLane::myLength, MSLane::myLengthGeometryFactor, MSLane::myMaxSpeed, MSEdgeWeightsStorage::retrieveExistingTravelTime(), and SUMOReal.
Referenced by drawGL().
const PositionVector & GUILane::getShape () const
Definition at line 800 of file GUILane.cpp.
References MSLane::myShape.
Referenced by drawArrows(), drawBikeMarkings(), drawCrossties(), drawDirectionIndicators(), GUIEdge::drawGL(), GUIPerson::drawGLAdditional(), drawLane2LaneConnections(), drawLinkNo(), drawLinkRules(), drawMarkings(), GUIEdge::drawMesoVehicles(), GUIVehicle::drawRouteHelper(), GUIMEVehicle::drawRouteHelper(), drawTLSLinkNo(), and getColorValue().
const std::vector< SUMOReal > & GUILane::getShapeLengths () const
Definition at line 812 of file GUILane.cpp.
References myShapeLengths, and SUMOReal.
Referenced by GUIPerson::drawGLAdditional(), drawMarkings(), GUIVehicle::drawRouteHelper(), and GUIMEVehicle::drawRouteHelper().
const std::vector< SUMOReal > & GUILane::getShapeRotations () const
Definition at line 806 of file GUILane.cpp.
References myShapeRotations.
Referenced by GUIPerson::drawGLAdditional(), drawMarkings(), GUIVehicle::drawRouteHelper(), and GUIMEVehicle::drawRouteHelper().
SUMOReal MSLane::getSpeedLimit () const inline inherited
Returns the lane's maximum allowed speed.
Returns
This lane's maximum allowed speed
Definition at line 467 of file MSLane.h.
References MSLane::myMaxSpeed.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSVehicleTransfer::checkInsertions(), MSLCM_SL2015::checkStrategicChange(), MSAbstractLaneChangeModel::congested(), MSLane::executeMovements(), getColorValue(), MSE2Collector::getEstimatedCurrentVehicleNumber(), MSLane::getMaximumBrakeDist(), getParameterWindow(), getScaleValue(), MSActuatedTrafficLightLogic::init(), TraCIServerAPI_Lane::processGet(), MSLCM_DK2008::wantsChangeToRight(), MSMeanData::writeEdge(), and MSFullExport::writeLane().
SUMOReal GUILane::getStoredEdgeTravelTime () const
Returns the stored traveltime for the edge of this lane.
Definition at line 830 of file GUILane.cpp.
References MSNet::getInstance(), MSNet::getWeightsStorage(), MSEdgeWeightsStorage::knowsTravelTime(), MSLane::myEdge, MSEdgeWeightsStorage::retrieveExistingTravelTime(), STEPS2TIME, and SUMOReal.
Referenced by getColorValue(), getParameterWindow(), and getScaleValue().
GUIGlObjectType GUIGlObject::getType () const inherited
Returns the type of the object as coded in GUIGlObjectType.
See also
GUIGlObjectType
Definition at line 150 of file GUIGlObject.cpp.
References GUIGlObject::myGLObjectType.
Referenced by GUIGlObject::buildSelectionPopupEntry(), GUIVehicle::drawAction_drawPersonsAndContainers(), GUIVehicle::drawAction_drawRailCarriages(), GUIPerson::drawAction_drawWalkingareaPath(), GNEAdditionalSet::drawConnections(), GNEDetector::drawDetectorIcon(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GNEDetectorE1::drawGL(), GNEDetectorE2::drawGL(), GNEContainerStop::drawGL(), GNEBusStop::drawGL(), GNEDetectorE3::drawGL(), GNEJunction::drawGL(), GUIMEInductLoop::MyWrapper::drawGL(), GUIContainer::drawGL(), GNEVaporizer::drawGL(), GUIPerson::drawGL(), GNEVariableSpeedSignal::drawGL(), GUIInstantInductLoop::MyWrapper::drawGL(), GUILaneSpeedTrigger::drawGL(), GUICalibrator::drawGL(), GNERouteProbe::drawGL(), GNELane::drawGL(), GUIJunctionWrapper::drawGL(), GNEChargingStation::drawGL(), GUIE3Collector::MyWrapper::drawGL(), GUIChargingStation::drawGL(), GUI_E2_ZS_Collector::MyWrapper::drawGL(), GNECalibrator::drawGL(), GUIContainerStop::drawGL(), GUIBusStop::drawGL(), GUIInductLoop::MyWrapper::drawGL(), GUITriggeredRerouter::GUITriggeredRerouterEdge::drawGL(), drawGL(), GNERerouter::drawGL(), GUIPerson::drawGLAdditional(), GUIBaseVehicle::drawGLAdditional(), GNEAdditional::drawLockIcon(), GUIBaseVehicle::drawOnPos(), GNEDetectorEntry::getAttribute(), GNEDetectorExit::getAttribute(), GNEDetectorE1::getAttribute(), GNEDetectorE2::getAttribute(), GNEContainerStop::getAttribute(), GNEBusStop::getAttribute(), GNEDetectorE3::getAttribute(), GNEVaporizer::getAttribute(), GNEVariableSpeedSignal::getAttribute(), GNERouteProbe::getAttribute(), GNEChargingStation::getAttribute(), GNECalibrator::getAttribute(), GNERerouter::getAttribute(), GUIJunctionWrapper::getColorValue(), GUIEdge::getColorValue(), GNEJunction::getColorValue(), GNELane::getColorValue(), getColorValue(), GNEViewNet::getEdgeAtCursorPosition(), GNEViewNet::getEdgesAtCursorPosition(), GNEViewNet::getJunctionAtCursorPosition(), GNEViewNet::getLaneAtCurserPosition(), GUISUMOAbstractView::getObjectAtPosition(), GUISUMOAbstractView::getObjectsAtPosition(), GUIEdge::getScaleValue(), getScaleValue(), GNESelectorFrame::handleIDs(), GNEAdditional::isAdditionalSelected(), GUIGlChildWindow::isSelected(), GUISUMOViewParent::isSelected(), GNEViewParent::isSelected(), GNEDetectorEntry::isValid(), GNEDetectorExit::isValid(), GNEDetectorE1::isValid(), GNEDetectorE2::isValid(), GNEContainerStop::isValid(), GNEBusStop::isValid(), GNEDetectorE3::isValid(), GNEVaporizer::isValid(), GNEVariableSpeedSignal::isValid(), GNERouteProbe::isValid(), GNEChargingStation::isValid(), GNECalibrator::isValid(), GNERerouter::isValid(), GUISelectedStorage::loadIDs(), GNEViewNet::mergeJunctions(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdBegin2TrackPhases(), GNEConnectorFrame::onCmdClearSelectedConnections(), GUIGLObjectPopupMenu::onCmdCopyEdgeName(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdHideLFLinkItems(), GUIPerson::GUIPersonPopupMenu::onCmdHideWalkingareaPath(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowAllRoutes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowBestLanes(), GUIPerson::GUIPersonPopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowCurrentRoute(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowFoes(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdShowLFLinkItems(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdShowPhases(), GUIPerson::GUIPersonPopupMenu::onCmdShowWalkingareaPath(), GUIPerson::GUIPersonPopupMenu::onCmdStartTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStartTrack(), GUIPerson::GUIPersonPopupMenu::onCmdStopTrack(), GUIBaseVehicle::GUIBaseVehiclePopupMenu::onCmdStopTrack(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLS2Off(), GUITrafficLightLogicWrapper::GUITrafficLightLogicWrapperPopupMenu::onCmdSwitchTLSLogic(), GNEViewNet::onDoubleClicked(), GNEViewNet::onLeftBtnPress(), LayeredRTree::selectLayer(), GNEDetectorEntry::setAttribute(), GNEDetectorExit::setAttribute(), GNEDetectorE1::setAttribute(), GNEDetectorE2::setAttribute(), GNEBusStop::setAttribute(), GNEContainerStop::setAttribute(), GNEDetectorE3::setAttribute(), GNEVaporizer::setAttribute(), GNEVariableSpeedSignal::setAttribute(), GNERouteProbe::setAttribute(), GNEChargingStation::setAttribute(), GNECalibrator::setAttribute(), GNERerouter::setAttribute(), GNEJunction::setColor(), and GUISelectedStorage::toggleSelection().
GUIParameterTableWindow * GUIGlObject::getTypeParameterWindow (GUIMainWindow & app, GUISUMOAbstractView & parent) virtual inherited
Returns an own type parameter window (optional)
Parameters
[in] app The application needed to build the parameter window
[in] parent The parent window needed to build the parameter window
Returns
The built parameter window
Reimplemented in GUIVehicle, GUIBaseVehicle, and GUIMEVehicle.
Definition at line 129 of file GUIGlObject.cpp.
References UNUSED_PARAMETER.
Referenced by GUIGLObjectPopupMenu::onCmdShowTypePars().
SUMOReal MSLane::getVehicleMaxSpeed (const SUMOVehicle *const veh) const inline inherited
Returns the lane's maximum speed, given a vehicle's speed limit adaptation.
Parameters
[in] The vehicle to return the adapted speed limit for
Returns
This lane's resulting max. speed
Definition at line 453 of file MSLane.h.
References SUMOVehicle::getChosenSpeedFactor(), SUMOVehicle::getMaxSpeed(), SUMOVehicle::getVClass(), MIN2(), MSLane::myMaxSpeed, and MSLane::myRestrictions.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::changeOpposite(), MSLaneChanger::computeOvertakingTime(), MEVehicle::estimateLeaveSpeed(), MSVehicle::estimateLeaveSpeed(), MSCFModel_IDM::followSpeed(), GUIVehicle::getColorValue(), MSLane::getCriticalLeader(), MSLane::getDepartSpeed(), MSLane::getLeadersOnConsecutive(), MSCFModel_IDM::interactionGap(), MSCFModel::interactionGap(), MSLane::isInsertionSuccess(), MSCFModel_Daniel1::moveHelper(), MSCFModel_KraussOrig1::moveHelper(), MSCFModel_SmartSK::moveHelper(), MSCFModel::moveHelper(), MSCFModel_IDM::moveHelper(), MSVehicle::planMoveInternal(), TraCIServerAPI_Vehicle::processGet(), MSVehicle::setBlinkerInformation(), MSCFModel_IDM::stopSpeed(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
int MSLane::getVehicleNumber () const inline inherited
Returns the number of vehicles on this lane (for which this lane is responsible)
Returns
The number of vehicles with their front on this lane
Definition at line 348 of file MSLane.h.
References MSLane::myVehicles.
Referenced by MSVehicle::checkRewindLinkLanes(), TraCIServerAPI_Lane::processGet(), MSFullExport::writeLane(), and MSXMLRawOut::writeLane().
int MSLane::getVehicleNumberWithPartials () const inline inherited
Returns the number of vehicles on this lane (including partial occupators)
Returns
The number of vehicles with intersecting this lane
Definition at line 356 of file MSLane.h.
References MSLane::myPartialVehicles, and MSLane::myVehicles.
const MSLane::VehCont & GUILane::getVehiclesSecure () const virtual
Returns the vehicles container; locks it for microsimulation.
Locks "myLock" preventing usage by microsimulation.
Please note that it is necessary to release the vehicles container afterwards using "releaseVehicles".
Returns
The vehicles on this lane
See also
MSLane::getVehiclesSecure
Reimplemented from MSLane.
Definition at line 126 of file GUILane.cpp.
References MFXMutex::lock(), myLock, and MSLane::myVehicles.
Referenced by drawGL().
SUMOReal MSLane::getWaitingSeconds () const inherited
Returns the overall waiting time on this lane.
Returns
The sum of the waiting time of all vehicles during the last step;
Definition at line 2000 of file MSLane.cpp.
References MSLane::myVehicles, and SUMOReal.
Referenced by MSLane::getIncomingLanes(), and TraCIServerAPI_Lane::processGet().
SUMOReal MSLane::getWidth () const inline inherited
Returns the lane's width.
Returns
This lane's width
Definition at line 491 of file MSLane.h.
References MSLane::myWidth.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::continueChange(), drawGL(), MSVehicle::executeMove(), MSVehicle::getCenterOnEdge(), MSVehicle::getLateralOverlap(), MSPModel_Striping::getNextLaneObstacles(), MSPModel_Striping::PState::getPosition(), MSVehicle::getRightSideOnLane(), MSPModel_Striping::initWalkingAreaPaths(), MSLane::insertVehicle(), MSLCM_SL2015::keepLatGap(), MSPModel_Striping::moveInDirection(), MSPModel_Striping::PState::moveToNextLane(), MSPModel_Striping::numStripes(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Lane::processGet(), TraCIServerAPI_Vehicle::processSet(), GUIVehicle::selectBlockingFoes(), MSLink::setRequestInformation(), MSLaneChangerSublane::startChangeSublane(), and MSLink::writeApproaching().
void MSLane::handleCollisionBetween (SUMOTime timestep, const std::string & stage, const MSVehicle * collider, const MSVehicle * victim, SUMOReal gap, SUMOReal latGap, std::set< const MSVehicle *, SUMOVehicle::ComparatorIdLess > & toRemove, std::set< const MSVehicle * > & toTeleport) const protected inherited
take action upon collision
Definition at line 1069 of file MSLane.cpp.
References MSLane::COLLISION_ACTION_REMOVE, MSLane::COLLISION_ACTION_TELEPORT, MSLane::COLLISION_ACTION_WARN, Named::getID(), MSBaseVehicle::getID(), MSVehicle::getInfluencer(), MSNet::getInstance(), MSNet::getVehicleControl(), MSVehicle::hasInfluencer(), MSVehicle::Influencer::isVTDAffected(), MSLane::myCollisionAction, MSVehicleControl::registerCollision(), time2string(), toString(), and WRITE_WARNING.
Referenced by MSLane::detectCollisionBetween(), MSLane::detectCollisions(), and MSLane::teleportOnCollision().
void GUILane::incorporateVehicle (MSVehicle * veh, SUMOReal pos, SUMOReal speed, SUMOReal posLat, const MSLane::VehCont::iterator & at, MSMoveReminder::Notification notification = MSMoveReminder::NOTIFICATION_DEPARTED) protected virtual
Inserts the vehicle into this lane, and informs it about entering the network.
Calls the vehicles enterLaneAtInsertion function, updates statistics and modifies the active state as needed
Parameters
[in] veh The vehicle to be incorporated
[in] pos The position of the vehicle
[in] speed The speed of the vehicle
[in] posLat The lateral position of the vehicle
[in] at
[in] notification The cause of insertion (i.e. departure, teleport, parking) defaults to departure
See also
MSLane::incorporateVehicle
Reimplemented from MSLane.
Definition at line 116 of file GUILane.cpp.
References MSLane::incorporateVehicle(), and myLock.
void MSLane::initCollisionOptions (const OptionsCont & oc) static inherited
Definition at line 2514 of file MSLane.cpp.
References MSLane::COLLISION_ACTION_NONE, MSLane::COLLISION_ACTION_REMOVE, MSLane::COLLISION_ACTION_TELEPORT, MSLane::COLLISION_ACTION_WARN, OptionsCont::getBool(), OptionsCont::getString(), MSLane::myCheckJunctionCollisions, and MSLane::myCollisionAction.
Referenced by MSFrame::setMSGlobals(), and MSLane::visit().
void MSLane::insertIDs (std::vector< std::string > & into) static inherited
Adds the ids of all stored lanes into the given vector.
Parameters
Definition at line 1258 of file MSLane.cpp.
References MSLane::myDict.
Referenced by MSLane::dictSize(), and TraCIServerAPI_Lane::processGet().
bool MSLane::insertVehicle (MSVehicle & v) inherited
Tries to insert the given vehicle.
The insertion position and speed are determined in dependence to the vehicle's departure definition, first.
Then, the vehicle is tried to be inserted into the lane using these values by a call to "isInsertionSuccess". The result of "isInsertionSuccess" is returned.
Parameters
[in] v The vehicle to insert
Returns
Whether the vehicle could be inserted
See also
isInsertionSuccess
MSVehicle::getDepartureDefinition
MSVehicle::DepartArrivalDefinition
Definition at line 398 of file MSLane.cpp.
References MSLane::basePos(), DEPART_POS_BASE, DEPART_POS_DEFAULT, DEPART_POS_FREE, DEPART_POS_GIVEN, DEPART_POS_LAST, DEPART_POS_RANDOM, DEPART_POS_RANDOM_FREE, DEPART_POSLAT_CENTER, DEPART_POSLAT_FREE, DEPART_POSLAT_GIVEN, DEPART_POSLAT_LEFT, DEPART_POSLAT_RANDOM, DEPART_POSLAT_RANDOM_FREE, DEPART_POSLAT_RIGHT, SUMOVehicleParameter::departPos, SUMOVehicleParameter::departPosLat, SUMOVehicleParameter::departPosLatProcedure, SUMOVehicleParameter::departPosProcedure, MSLane::freeInsertion(), MSLane::getDepartSpeed(), MSLane::getLength(), MSBaseVehicle::getParameter(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSLane::getWidth(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSLane::myLength, MSMoveReminder::NOTIFICATION_DEPARTED, RandHelper::rand(), and SUMOReal.
Referenced by MSLane::getMoveReminders(), and MSEdge::insertVehicle().
bool GUILane::integrateNewVehicle (SUMOTime t) virtual
the same as in MSLane, but locks the access for the visualisation first; the access will be granted at the end of this method
Reimplemented from MSLane.
Definition at line 167 of file GUILane.cpp.
References MSLane::integrateNewVehicle(), and myLock.
SUMOReal MSLane::interpolateGeometryPosToLanePos (SUMOReal geometryPos) const inline inherited
Definition at line 445 of file MSLane.h.
References MSLane::myLengthGeometryFactor.
Referenced by getPopUpMenu(), and MSLink::setRequestInformation().
SUMOReal MSLane::interpolateLanePosToGeometryPos (SUMOReal lanePos) const inline inherited
Definition at line 433 of file MSLane.h.
References MSLane::myLengthGeometryFactor.
Referenced by MSVehicle::computeAngle(), GUIEdge::drawMesoVehicles(), MSLane::geometryPositionAtOffset(), MEVehicle::getAngle(), MSTransportable::Stage::getLanePosition(), MSVehicle::getPosition(), MEVehicle::getSlope(), MSVehicle::getSlope(), and MSStoppingPlace::getWaitPosition().
bool MSLane::isApproachedFrom (MSEdge *const edge) inherited
Definition at line 1524 of file MSLane.cpp.
References MSLane::myApproachingLanes.
Referenced by MSLane::getIncomingLanes().
bool MSLane::isApproachedFrom (MSEdge *const edge, MSLane *const lane) inherited
Definition at line 1530 of file MSLane.cpp.
References MSLane::myApproachingLanes.
bool GUILane::isClosed () const inline
Definition at line 252 of file GUILane.h.
References MSMoveReminder::NOTIFICATION_DEPARTED, SUMOReal, and text().
Referenced by GUIEdge::closeTraffic().
bool MSLane::isEmpty () const inherited
Returns the information whether the lane is has no vehicle and no partial occupation
Definition at line 1345 of file MSLane.cpp.
References MSLane::myPartialVehicles, and MSLane::myVehicles.
Referenced by MSLane::dictSize().
bool MSLane::isInsertionSuccess (MSVehicle * vehicle, SUMOReal speed, SUMOReal pos, SUMOReal posLat, bool recheckNextLanes, MSMoveReminder::Notification notification) inherited
Tries to insert the given vehicle with the given state (speed and pos)
Checks whether the vehicle can be inserted at the given position with the given speed so that no collisions with leader/follower occur and the speed does not cause unexpected behaviour on consecutive lanes. Returns false if the vehicle can not be inserted.
If the insertion can take place, incorporateVehicleis called and true is returned.
Parameters
[in] vehicle The vehicle to insert
[in] speed The speed with which it shall be inserted
[in] pos The position at which it shall be inserted
[in] posLat The lateral position at which it shall be inserted
[in] recheckNextLanes Forces patching the speed for not being too fast on next lanes
[in] notification The cause of insertion (i.e. departure, teleport, parking) defaults to departure
Returns
Whether the vehicle could be inserted
See also
MSVehicle::enterLaneAtInsertion
Definition at line 505 of file MSLane.cpp.
References ARRIVAL_SPEED_GIVEN, SUMOVehicleParameter::arrivalSpeed, SUMOVehicleParameter::arrivalSpeedProcedure, MSRoute::begin(), MSCFModel::brakeGap(), MSLane::checkFailure(), DEBUG_COND2, MSInsertionControl::descheduleDeparture(), MSCFModel::freeSpeed(), MSVehicle::getBackPositionOnLane(), MSVehicle::getBestLanesContinuation(), MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), MSLane::getEdge(), MSLane::getFollowersOnConsecutive(), Named::getID(), MSBaseVehicle::getID(), MSBaseVehicle::getImpatience(), MSNet::getInsertionControl(), MSNet::getInstance(), MSLane::getLastAnyVehicle(), MSRoute::getLastEdge(), MSLane::getLastVehicleInformation(), MSVehicleType::getLength(), MSLane::getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSLane::getMissingRearGap(), MSBaseVehicle::getParameter(), MSBaseVehicle::getRoute(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSLane::incorporateVehicle(), MSCFModel::insertionFollowSpeed(), MSLane::isLinkEnd(), LINKSTATE_ALLWAY_STOP, LINKSTATE_EQUAL, LINKSTATE_MINOR, LINKSTATE_STOP, MAX2(), MSLane::myLength, MSLane::myVehicles, NUMERICAL_EPS, MSLeaderInfo::numFreeSublanes(), MSLeaderInfo::numSublanes(), MSLane::safeInsertionSpeed(), MSVehicle::setTentativeLaneAndPosition(), SIMTIME, MSCFModel::stopSpeed(), MSLane::succLinkSec(), SUMO_const_haltingSpeed, SUMOReal, TIME2STEPS, toString(), MSLeaderInfo::toString(), MSVehicle::updateBestLanes(), WRITE_ERROR, and WRITE_WARNING.
Referenced by MSVehicleTransfer::checkInsertions(), MSLane::freeInsertion(), MSLane::getMoveReminders(), MSLane::insertVehicle(), and MSLane::lastInsertion().
bool MSLane::isLinkEnd (MSLinkCont::const_iterator & i) const inherited
Returns the information whether the given link shows at the end of the list of links (is not valid)
Definition at line 1334 of file MSLane.cpp.
References MSLane::myLinks.
Referenced by MSLaneChanger::checkChange(), MSLane::dictSize(), MSLane::getCriticalLeader(), MSLane::getLeadersOnConsecutive(), MSLane::isInsertionSuccess(), MSVehicle::planMoveInternal(), TraCIServerAPI_Vehicle::processGet(), and MSVehicle::unsafeLinkAhead().
bool MSLane::isLinkEnd (MSLinkCont::iterator & i) inherited
Returns the information whether the given link shows at the end of the list of links (is not valid)
Definition at line 1340 of file MSLane.cpp.
References MSLane::myLinks.
bool Parameterised::knowsParameter (const std::string & key) const inherited
Returns whether the parameter is known.
Parameters
[in] key The key to ask for
Returns
Whether the key is known
Definition at line 75 of file Parameterised.cpp.
References Parameterised::myMap.
Referenced by MSDevice_Example::buildVehicleDevices(), and MSDevice::equippedByDefaultAssignmentOptions().
bool MSLane::lastInsertion (MSVehicle & veh, SUMOReal mspeed) inherited
Definition at line 264 of file MSLane.cpp.
References MSLane::basePos(), MSVehicle::getCarFollowModel(), MSVehicleType::getLength(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSLane::isInsertionSuccess(), MSLane::myVehicles, MSMoveReminder::NOTIFICATION_DEPARTED, POSITION_EPS, and SUMOReal.
Referenced by MSLane::getMoveReminders(), and MSLane::insertVehicle().
void MSLane::leftByLaneChange (MSVehicle * v) inherited
Definition at line 1945 of file MSLane.cpp.
References MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSBaseVehicle::getVehicleType(), MSLane::myBruttoVehicleLengthSum, and MSLane::myNettoVehicleLengthSum.
Referenced by MSLane::dictSize(), and MSAbstractLaneChangeModel::primaryLaneChanged().
void MSLane::loadState (std::vector< std::string > & vehIDs, MSVehicleControl & vc) inherited
Loads the state of this segment with the given parameters.
This method is called for every internal que the segment has. Every vehicle is retrieved from the given MSVehicleControl and added to this lane.
Parameters
[in] vehIDs The vehicle ids for the current que
[in] vc The vehicle control to retrieve references vehicles from
Todo:
What about throwing an IOError?
What about throwing an error if something else fails (a vehicle can not be referenced)?
Definition at line 2185 of file MSLane.cpp.
References MSVehicle::getLateralPositionOnLane(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSVehicleControl::getVehicle(), MSLane::incorporateVehicle(), MSLane::myVehicles, MSMoveReminder::NOTIFICATION_JUNCTION, and MSVehicle::updateBestLanes().
Referenced by MSLane::getCenterOnEdge().
void GUILane::planMovements (const SUMOTime t) virtual
the same as in MSLane, but locks the access for the visualisation first; the access will be granted at the end of this method
Reimplemented from MSLane.
Definition at line 139 of file GUILane.cpp.
References myLock, and MSLane::planMovements().
void GUILane::releaseVehicles () const virtual
Allows to use the container for microsimulation again.
Unlocks "myLock" preventing usage by microsimulation.
See also
MSLane::releaseVehicles
Reimplemented from MSLane.
Definition at line 133 of file GUILane.cpp.
References myLock, and MFXMutex::unlock().
Referenced by drawGL().
void GUIGlObject::removeParameterTable (GUIParameterTableWindow * w) inherited
Lets this object know a parameter window showing the object's values was closed.
Parameters
[in] w The closed parameter window
Definition at line 264 of file GUIGlObject.cpp.
References GUIGlObject::myParamWindows.
Referenced by GUIParameterTableWindow::~GUIParameterTableWindow().
MSVehicle * GUILane::removeVehicle (MSVehicle * remVehicle, MSMoveReminder::Notification notification, bool notify) virtual
the same as in MSLane, but locks the access for the visualisation first; the access will be granted at the end of this method
Reimplemented from MSLane.
Definition at line 153 of file GUILane.cpp.
References myLock, and MSLane::removeVehicle().
void GUILane::resetPartialOccupation (MSVehicle * v) virtual
Removes the information about a vehicle lapping into this lane.
Parameters
[in] v The vehicle which laps into this lane
Reimplemented from MSLane.
Definition at line 188 of file GUILane.cpp.
References myLock, and MSLane::resetPartialOccupation().
SUMOReal MSLane::safeInsertionSpeed (const MSVehicle * veh, const MSLeaderInfo & leaders, SUMOReal speed) protected inherited
return the maximum safe speed for insertion behind leaders (a negative value indicates that safe insertion is impossible)
Definition at line 752 of file MSLane.cpp.
References MSVehicle::getBackPositionOnLane(), MSVehicle::getCarFollowModel(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSCFModel::insertionFollowSpeed(), MIN2(), MSLeaderInfo::numSublanes(), and SUMOReal.
Referenced by MSLane::isInsertionSuccess(), and MSLane::teleportOnCollision().
void MSLane::saveState (OutputDevice & out) inherited
Saves the state of this lane into the given stream.
Basically, a list of vehicle ids
Parameters
Definition at line 2174 of file MSLane.cpp.
References OutputDevice::closeTag(), Named::getID(), MSLane::myVehicles, OutputDevice::openTag(), SUMO_ATTR_VALUE, SUMO_TAG_LANE, SUMO_TAG_VIEWSETTINGS_VEHICLES, and OutputDevice::writeAttr().
Referenced by MSLane::getCenterOnEdge().
void GUILane::setColor (const GUIVisualizationSettings & s) const private
sets the color according to the currente settings
Definition at line 856 of file GUILane.cpp.
References GUIPropertySchemeStorage< T >::getActive(), GUIPropertyScheme< T >::getColor(), getColorValue(), GUIPropertySchemeStorage< T >::getScheme(), GUIVisualizationSettings::laneColorer, GLHelper::setColor(), setFunctionalColor(), and setMultiColor().
Referenced by drawGL(), and drawMarkings().
bool GUILane::setFunctionalColor (int activeScheme) const private
sets the color according to the current scheme index and some lane function
Definition at line 865 of file GUILane.cpp.
References PositionVector::beginEndAngle(), RGBColor::fromHSV(), MSLane::myShape, GeomHelper::naviDegree(), GLHelper::setColor(), and SUMOReal.
Referenced by setColor().
void Named::setID (const std::string & newID) inline inherited
resets the id
Parameters
[in] newID The new id of this object
Definition at line 74 of file Named.h.
References Named::myID.
Referenced by NBNodeCont::mapToNumericalIDs(), NBEdgeCont::mapToNumericalIDs(), NBNodeCont::rename(), and NBEdgeCont::rename().
void MSLane::setLength (SUMOReal val) inherited
Sets a new length for the lane (used by TraCI only)
Parameters
[in] val the new length in m
Definition at line 1458 of file MSLane.cpp.
References MSLane::myEdge, and MSEdge::recalcCache().
Referenced by MSLane::empty(), and TraCIServerAPI_Lane::processSet().
void MSLane::setMaxSpeed (SUMOReal val) inherited
Sets a new maximum speed for the lane (used by TraCI and MSCalibrator)
Parameters
[in] val the new speed in m/s
Definition at line 1451 of file MSLane.cpp.
References MSLane::myEdge, MSLane::myMaxSpeed, and MSEdge::recalcCache().
Referenced by MSLane::empty(), and TraCIServerAPI_Lane::processSet().
void GUIGlObject::setMicrosimID (const std::string & newID) virtual inherited
Changes the microsimID of the object.
Note
happens in NETEDIT
Reimplemented in GNEEdge.
Definition at line 143 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myMicrosimID.
Referenced by GNENet::renameJunction(), GNEAdditional::setAdditionalID(), GNELane::setIndex(), and GNEEdge::setMicrosimID().
bool GUILane::setMultiColor (const GUIColorer & c) const private
sets multiple colors according to the current scheme index and some lane function
Definition at line 879 of file GUILane.cpp.
References GUIPropertySchemeStorage< T >::getActive(), GUIPropertyScheme< T >::getColor(), GUIPropertySchemeStorage< T >::getScheme(), MAX2(), MSLane::myShape, myShapeColors, POSITION_EPS, and SUMOReal.
Referenced by setColor().
SUMOReal GUILane::setPartialOccupation (MSVehicle * v) virtual
Sets the information about a vehicle lapping into this lane.
This vehicle is added to myVehicles and may be distinguished from regular vehicles by the disparity between this lane and v->getLane()
Parameters
[in] v The vehicle which laps into this lane
Returns
This lane's length
Reimplemented from MSLane.
Definition at line 181 of file GUILane.cpp.
References myLock, and MSLane::setPartialOccupation().
void MSLane::setPermissions (SVCPermissions permissions) inline inherited
Definition at line 679 of file MSLane.h.
References MSLane::myPermissions.
Referenced by TraCIServerAPI_Lane::processSet().
void GUIGlObject::setPrefix (const std::string & prefix) protected inherited
usually names are prefixed by a type-specific string. this method can be used to change the default
Definition at line 273 of file GUIGlObject.cpp.
References GUIGlObject::createFullName(), GUIGlObject::myFullName, and GUIGlObject::myPrefix.
void MSLane::setRightSideOnEdge (SUMOReal value, int rightmostSublane) inline inherited
Definition at line 881 of file MSLane.h.
References MSLane::myRightmostSublane, and MSLane::myRightSideOnEdge.
void MSLane::sortPartialVehicles () inherited
sorts myPartialVehicles
Definition at line 1327 of file MSLane.cpp.
References MSLane::myPartialVehicles.
Referenced by MSLane::getCenterOnEdge(), MSLane::integrateNewVehicle(), and MSLane::swapAfterLaneChange().
PositionVector GUILane::splitAtSegments (const PositionVector & shape) private
add intermediate points at segment borders
Definition at line 1114 of file GUILane.cpp.
References Position::distanceTo(), OptionsCont::getOptions(), MSGlobals::gUseMesoSim, PositionVector::indexOfClosest(), PositionVector::insertAtClosest(), MSLane::myLength, myShapeSegments, MELoop::numSegmentsFor(), POSITION_EPS, PositionVector::positionAtOffset(), and SUMOReal.
Referenced by GUILane().
MSLinkCont::const_iterator MSLane::succLinkSec (const SUMOVehicle & veh, int nRouteSuccs, const MSLane & succLinkSource, const std::vector< MSLane * > & conts) static inherited
Same as succLink, but does not throw any assertions when the succeeding link could not be found; Returns the myLinks.end() instead; Further, the number of edges to look forward may be given
Definition at line 1396 of file MSLane.cpp.
References MSEdge::EDGEFUNCTION_INTERNAL, MSLane::getEdge(), Named::getID(), SUMOVehicle::getID(), MSNet::getInstance(), MSEdge::getPurpose(), MSVehicleType::getVehicleClass(), SUMOVehicle::getVehicleType(), MSLane::myLinks, SUMOVehicle::succEdge(), time2string(), and WRITE_WARNING.
Referenced by MSLane::appropriate(), MSLaneChanger::checkChange(), MSLane::dictSize(), MSLane::executeMovements(), MSLane::getCriticalLeader(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLane::isInsertionSuccess(), MSVehicle::planMoveInternal(), TraCIServerAPI_Vehicle::processGet(), MSVehicle::setBlinkerInformation(), and MSVehicle::unsafeLinkAhead().
void GUILane::swapAfterLaneChange (SUMOTime t) protected virtual
moves myTmpVehicles int myVehicles after a lane change procedure
Reimplemented from MSLane.
Definition at line 160 of file GUILane.cpp.
References myLock, and MSLane::swapAfterLaneChange().
static bool MSLane::teleportOnCollision () inline static inherited
Definition at line 962 of file MSLane.h.
References MSLane::basePos(), MSLane::COLLISION_ACTION_TELEPORT, MSLane::detectCollisionBetween(), MSLane::getDepartSpeed(), MSLane::getMaximumBrakeDist(), MSLane::handleCollisionBetween(), MSLane::incorporateVehicle(), MSLane::myCollisionAction, MSMoveReminder::NOTIFICATION_DEPARTED, MSLane::safeInsertionSpeed(), SUMOReal, and MSLane::swapAfterLaneChange().
Referenced by MSVehicleControl::getTeleportCount().
void MSLane::visit (const TraCIServerAPI_Lane::StoringVisitor & cont) const inline inherited
Callback for visiting the lane when traversing an RTree.
This is used in the TraCIServerAPI_Lane for context subscriptions.
Parameters
[in] cont The context doing all the work
See also
TraCIServerAPI_Lane::StoringVisitor::add
Definition at line 955 of file MSLane.h.
References TraCIServerAPI_Lane::StoringVisitor::add(), and MSLane::initCollisionOptions().
Referenced by TraCIServer::collectObjectsInRange().
Field Documentation
const GUIGlID GUIGlObject::INVALID_ID = 0 static inherited
Definition at line 77 of file GUIGlObject.h.
Referenced by GUISUMOAbstractView::getTrackedID(), GUISUMOAbstractView::paintGL(), and GUIViewTraffic::stopTrack().
bool GUILane::myAmClosed private
state for dynamic lane closings
Definition at line 335 of file GUILane.h.
Referenced by closeTraffic(), and getPopUpMenu().
std::map<MSEdge*, std::vector<MSLane*> > MSLane::myApproachingLanes protected inherited
Definition at line 1089 of file MSLane.h.
Referenced by MSLane::addApproachingLane(), and MSLane::isApproachedFrom().
SUMOReal MSLane::myBruttoVehicleLengthSum protected inherited
The current length of all vehicles on this lane, including their minGaps.
Definition at line 1080 of file MSLane.h.
Referenced by MSLane::enteredByLaneChange(), MSLane::executeMovements(), MSLane::getBruttoOccupancy(), MSLane::getBruttoVehLenSum(), MSLane::incorporateVehicle(), MSLane::integrateNewVehicle(), MSLane::leftByLaneChange(), and MSLane::removeVehicle().
MSLane::DictType MSLane::myDict static protected inherited
Static dictionary to associate string-ids with objects.
Definition at line 1118 of file MSLane.h.
Referenced by MSLane::clear(), MSLane::dictionary(), MSLane::dictSize(), MSLane::fill(), and MSLane::insertIDs().
MSEdge* const MSLane::myEdge protected inherited
The lane's edge, for routing only.
Definition at line 1064 of file MSLane.h.
Referenced by MSLane::appropriate(), MSLane::detectCollisions(), drawGL(), drawMarkings(), getColorValue(), MSLane::getEdge(), getEdgeLaneNumber(), MSLane::getInternalFollower(), getLoadedEdgeWeight(), MSLane::getLogicalPredecessorLane(), MSLane::getParallelLane(), getParameterWindow(), getScaleValue(), getStoredEdgeTravelTime(), MSLane::incorporateVehicle(), MSLane::integrateNewVehicle(), MSLane::setLength(), and MSLane::setMaxSpeed().
MSLeaderInfo MSLane::myFollowerInfo mutable protected inherited
followers on all sublanes as seen by vehicles on consecutive lanes (cached)
Definition at line 1094 of file MSLane.h.
Referenced by MSLane::getFirstVehicleInformation().
SUMOTime MSLane::myFollowerInfoTime mutable protected inherited
time step for which myFollowerInfo was last updated
Definition at line 1101 of file MSLane.h.
Referenced by MSLane::getFirstVehicleInformation().
SUMOReal GUILane::myHalfLaneWidth private
Half of lane width, for speed-up.
Definition at line 325 of file GUILane.h.
Referenced by drawBikeMarkings(), drawDirectionIndicators(), drawGL(), drawLinkNo(), drawLinkRule(), drawMarkings(), drawTLSLinkNo(), and GUILane().
std::string Named::myID protected inherited
The name of the object.
Definition at line 136 of file Named.h.
Referenced by GUI_E2_ZS_CollectorOverLanes::buildCollector(), RODFDetector::buildDestinationDistribution(), NGEdge::buildNBEdge(), NGNode::buildNBNode(), MSSOTLTrafficLightLogic::checkPhases(), NBNode::computeNodeShape(), METriggeredCalibrator::execute(), MSCalibrator::execute(), Named::getID(), NBEdge::getLaneID(), NBEdge::getLaneIDInsecure(), ROEdge::getStoredEffort(), ROEdge::getTravelTime(), MSActuatedTrafficLightLogic::init(), MSSOTLTrafficLightLogic::init(), MSCalibrator::init(), NBEdge::init(), MSCalibrator::myStartElement(), MSMeanData::openInterval(), RORouteDef::preComputeCurrentRoute(), NBEdge::reinitNodes(), MSRoute::release(), Named::setID(), MSSOTLTrafficLightLogic::setToATargetPhase(), NBEdge::splitGeometry(), RODFDetector::writeEmitterDefinition(), MSXMLRawOut::writeLane(), NBNode::writeLogic(), RODFDetector::writeSingleSpeedTrigger(), MEInductLoop::writeXMLOutput(), MSCalibrator::writeXMLOutput(), and MSE3Collector::writeXMLOutput().
std::vector<IncomingLaneInfo> MSLane::myIncomingLanes protected inherited
Definition at line 1075 of file MSLane.h.
Referenced by MSLane::addIncomingLane(), MSLane::getFollowerOnConsecutive(), MSLane::getFollowersOnConsecutive(), MSLane::getIncomingLanes(), and MSLane::getLogicalPredecessorLane().
int MSLane::myIndex protected inherited
The lane index.
Definition at line 1021 of file MSLane.h.
Referenced by drawMarkings(), and MSLane::getIndex().
MSLeaderInfo MSLane::myLeaderInfo mutable protected inherited
leaders on all sublanes as seen by approaching vehicles (cached)
Definition at line 1092 of file MSLane.h.
Referenced by MSLane::getLastVehicleInformation().
SUMOTime MSLane::myLeaderInfoTime mutable protected inherited
time step for which myLeaderInfo was last updated
Definition at line 1099 of file MSLane.h.
Referenced by MSLane::getLastVehicleInformation().
MSLeaderInfo MSLane::myLeaderInfoTmp mutable protected inherited
Definition at line 1096 of file MSLane.h.
Referenced by MSLane::getFirstVehicleInformation(), and MSLane::getLastVehicleInformation().
SUMOReal MSLane::myLength protected inherited
Lane length [m].
Definition at line 1058 of file MSLane.h.
Referenced by MSLane::basePos(), MSLane::freeInsertion(), MSLane::getBruttoOccupancy(), getColorValue(), MSLane::getLength(), MSLane::getNettoOccupancy(), getParameterWindow(), getScaleValue(), MSLane::incorporateVehicle(), MSLane::insertVehicle(), MSLane::isInsertionSuccess(), MSLane::setPartialOccupation(), and splitAtSegments().
const SUMOReal MSLane::myLengthGeometryFactor protected inherited
precomputed myShape.length / myLength
Definition at line 1104 of file MSLane.h.
Referenced by getColorValue(), MSLane::getLengthGeometryFactor(), getScaleValue(), MSLane::interpolateGeometryPosToLanePos(), and MSLane::interpolateLanePosToGeometryPos().
MSLinkCont MSLane::myLinks protected inherited
The lane's Links to it's succeeding lanes and the default right-of-way rule, i.e. blocked or not blocked.
Definition at line 1087 of file MSLane.h.
Referenced by MSLane::addLink(), MSLane::appropriate(), MSLane::detectCollisions(), drawArrows(), drawLane2LaneConnections(), drawLinkNo(), drawLinkRules(), drawTLSLinkNo(), MSLane::executeMovements(), MSLane::getCrossingIndex(), MSLane::getLinkCont(), MSLane::getOutgoingLanes(), MSLane::isLinkEnd(), MSLane::succLinkSec(), and MSLane::~MSLane().
MFXMutex GUILane::myLock mutable private
The mutex used to avoid concurrent updates of the vehicle buffer.
Definition at line 340 of file GUILane.h.
Referenced by detectCollisions(), executeMovements(), getVehiclesSecure(), incorporateVehicle(), integrateNewVehicle(), planMovements(), releaseVehicles(), removeVehicle(), resetPartialOccupation(), setPartialOccupation(), swapAfterLaneChange(), and ~GUILane().
MSLane* MSLane::myLogicalPredecessorLane mutable protected inherited
Definition at line 1076 of file MSLane.h.
Referenced by MSLane::getLogicalPredecessorLane().
SUMOReal MSLane::myMaxSpeed protected inherited
Lane-wide speedlimit [m/s].
Definition at line 1067 of file MSLane.h.
Referenced by getColorValue(), MSLane::getMeanSpeed(), getScaleValue(), MSLane::getSpeedLimit(), MSLane::getVehicleMaxSpeed(), and MSLane::setMaxSpeed().
std::vector<std::string> MSLane::myNeighs protected inherited
Definition at line 1112 of file MSLane.h.
Referenced by MSLane::addNeigh(), and MSLane::getOpposite().
SUMOReal MSLane::myNettoVehicleLengthSum protected inherited
The current length of all vehicles on this lane, excluding their minGaps.
Definition at line 1083 of file MSLane.h.
Referenced by MSLane::enteredByLaneChange(), MSLane::executeMovements(), MSLane::getNettoOccupancy(), MSLane::incorporateVehicle(), MSLane::integrateNewVehicle(), MSLane::leftByLaneChange(), and MSLane::removeVehicle().
int MSLane::myNumericalID protected inherited
Unique numerical ID (set on reading by netload)
Definition at line 1015 of file MSLane.h.
Referenced by MSLane::getNumericalID().
SVCPermissions GUILane::myOriginalPermissions private
Definition at line 336 of file GUILane.h.
Referenced by closeTraffic().
VehCont MSLane::myPartialVehicles protected inherited
The lane's partial vehicles. This container holds all vehicles that are partially on this lane but which are in myVehicles of another lane. Reasons for partial occupancie include the following.
the back is still on this lane during regular movement
the vehicle is performing a continuous lane-change maneuver
sub-lane simulation where vehicles can freely move laterally among the lanes of an edge
The entering vehicles are inserted at the front of this container and the leaving ones leave from the back.
Definition at line 1046 of file MSLane.h.
Referenced by MSLane::anyVehiclesBegin(), MSLane::anyVehiclesEnd(), MSLane::anyVehiclesUpstreamBegin(), MSLane::detectCollisions(), MSLane::freeInsertion(), MSLane::getBruttoOccupancy(), MSLane::getFirstAnyVehicle(), MSLane::getLastAnyVehicle(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSLane::getNettoOccupancy(), MSLane::getPartialBehind(), MSLane::getPartialVehicleNumber(), MSLaneChanger::getRealLeader(), MSLane::getVehicleNumberWithPartials(), MSLane::isEmpty(), MSLane::AnyVehicleIterator::nextIsMyVehicles(), MSLane::AnyVehicleIterator::operator*(), MSLane::planMovements(), MSLane::resetPartialOccupation(), MSLane::setPartialOccupation(), and MSLane::sortPartialVehicles().
SVCPermissions MSLane::myPermissions protected inherited
The vClass permissions for this lane.
Definition at line 1070 of file MSLane.h.
Referenced by MSLane::allowsVehicleClass(), closeTraffic(), drawAsRailway(), drawAsWaterway(), drawGL(), drawMarkings(), getColorValue(), getParameterWindow(), MSLane::getPermissions(), and MSLane::setPermissions().
SUMOReal GUILane::myQuarterLaneWidth private
Quarter of lane width, for speed-up.
Definition at line 328 of file GUILane.h.
Referenced by drawDirectionIndicators(), drawGL(), drawMarkings(), and GUILane().
const std::map<SUMOVehicleClass, SUMOReal>* MSLane::myRestrictions protected inherited
The vClass speed restrictions for this lane.
Definition at line 1073 of file MSLane.h.
Referenced by MSLane::getVehicleMaxSpeed(), and MSLane::MSLane().
int MSLane::myRightmostSublane protected inherited
the index of the rightmost sublane of this lane on myEdge
Definition at line 1109 of file MSLane.h.
Referenced by MSLane::getRightmostSublane(), and MSLane::setRightSideOnEdge().
SUMOReal MSLane::myRightSideOnEdge protected inherited
the combined width of all lanes with lower index on myEdge
Definition at line 1107 of file MSLane.h.
Referenced by MSLane::getCenterOnEdge(), MSLane::getRightSideOnEdge(), and MSLane::setRightSideOnEdge().
PositionVector MSLane::myShape protected inherited
The shape of the lane.
Definition at line 1018 of file MSLane.h.
Referenced by drawGL(), MSLane::geometryPositionAtOffset(), getCenteringBoundary(), getPopUpMenu(), getShape(), MSLane::getShape(), GUILane(), setFunctionalColor(), and setMultiColor().
std::vector<RGBColor> GUILane::myShapeColors mutable private
The color of the shape parts (cached)
Definition at line 319 of file GUILane.h.
Referenced by drawGL(), GUILane(), and setMultiColor().
std::vector<SUMOReal> GUILane::myShapeLengths private
The lengths of the shape parts.
Definition at line 316 of file GUILane.h.
Referenced by drawBikeMarkings(), drawCrossties(), drawDirectionIndicators(), drawGL(), drawMarkings(), getShapeLengths(), and GUILane().
std::vector<SUMOReal> GUILane::myShapeRotations private
The rotations of the shape parts.
Definition at line 313 of file GUILane.h.
Referenced by drawBikeMarkings(), drawCrossties(), drawDirectionIndicators(), drawGL(), drawMarkings(), getShapeRotations(), and GUILane().
std::vector<int> GUILane::myShapeSegments private
the meso segment index for each geometry segment
Definition at line 322 of file GUILane.h.
Referenced by drawGL(), GUILane(), and splitAtSegments().
VehCont MSLane::myTmpVehicles protected inherited
Container for lane-changing vehicles. After completion of lane-change- process, the containers will be swapped with myVehicles.
Definition at line 1050 of file MSLane.h.
Referenced by MSLane::getLeader(), and MSLane::swapAfterLaneChange().
VehCont MSLane::myVehBuffer protected inherited
Buffer for vehicles that moved from their previous lane onto this one. Integrated after all vehicles executed their moves.
Definition at line 1054 of file MSLane.h.
Referenced by MSLane::empty(), MSLane::executeMovements(), MSLane::integrateNewVehicle(), and MSXMLRawOut::writeLane().
VehCont MSLane::myVehicles protected inherited
The lane's vehicles. This container holds all vehicles that have their front (longitudinally) and their center (laterally) on this lane. These are the vehicles that this lane is 'responsibly' for (i.e. when executing movements)
The entering vehicles are inserted at the front of this container and the leaving ones leave from the back, e.g. the vehicle in front of the junction (often called first) is myVehicles.back() (if it exists). And if it is an iterator at a vehicle, ++it points to the vehicle in front. This is the interaction vehicle.
Definition at line 1034 of file MSLane.h.
Referenced by MSLane::addMoveReminder(), MSLane::anyVehiclesBegin(), MSLane::anyVehiclesEnd(), MSLane::anyVehiclesUpstreamBegin(), MSLane::detectCollisions(), MSLane::empty(), MSLane::executeMovements(), firstWaitingTime(), MSLane::forceVehicleInsertion(), MSLane::freeInsertion(), MSLane::getBruttoOccupancy(), MSLane::getFirstAnyVehicle(), MSLane::getFirstFullVehicle(), MSLane::getLastAnyVehicle(), MSLane::getLastFullVehicle(), MSLane::getLeader(), MSLane::getMeanSpeed(), MSLane::getNettoOccupancy(), MSLane::getVehicleNumber(), MSLane::getVehicleNumberWithPartials(), getVehiclesSecure(), MSLane::getVehiclesSecure(), MSLane::getWaitingSeconds(), MSLane::incorporateVehicle(), MSLane::integrateNewVehicle(), MSLane::isEmpty(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSLane::loadState(), MSLane::AnyVehicleIterator::nextIsMyVehicles(), MSLane::AnyVehicleIterator::operator*(), MSLane::planMovements(), MSLane::removeVehicle(), MSLane::saveState(), MSLane::swapAfterLaneChange(), MSQueueExport::writeLane(), and MSXMLRawOut::writeLane().
const SUMOReal MSLane::myWidth protected inherited
Lane width [m].
Definition at line 1061 of file MSLane.h.
Referenced by drawArrows(), drawDirectionIndicators(), drawLinkNo(), drawLinkRules(), drawTLSLinkNo(), MSLane::getCenterOnEdge(), getParameterWindow(), MSLane::getWidth(), and GUILane().
StringBijection< GUIGlObjectType > GUIGlObject::TypeNames static inherited
associates object types with strings
Definition at line 76 of file GUIGlObject.h.
The documentation for this class was generated from the following files:
GUILane.h
GUILane.cpp