SUMO - Simulation of Urban MObility: MSLCM_SL2015 Class Reference
MSLCM_SL2015 Class Reference
A lane change model developed by J. Erdmann.
#include <MSLCM_SL2015.h>
Public Types
enum MyLCAEnum {
LCA_MNone = 0, LCA_AMBLOCKINGLEADER = 1 << 16, LCA_AMBLOCKINGFOLLOWER = 1 << 17, LCA_MRIGHT = 1 << 18,
LCA_MLEFT = 1 << 19, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE = 1 << 21, LCA_CHANGE_TO_HELP = 1 << 23, LCA_AMBACKBLOCKER = 1 << 26,
LCA_AMBACKBLOCKER_STANDING = 1 << 27
}
Public Member Functions
SUMOReal _patchSpeed (const SUMOReal min, const SUMOReal wanted, const SUMOReal max, const MSCFModel &cfModel)
bool alreadyChanged () const
reset the flag whether a vehicle already moved to false
void changed ()
void changedToOpposite ()
called when a vehicle changes between lanes in opposite directions
void cleanupShadowLane ()
bool debugVehicle () const
whether the current vehicles shall be debugged
void endLaneChangeManeuver (const MSMoveReminder::Notification reason=MSMoveReminder::NOTIFICATION_LANE_CHANGE)
SUMOReal getAngleOffset () const
return the angle offset during a continuous change maneuver
int getLaneChangeDirection () const
return the direction of the current lane change maneuver
SUMOTime getLastLaneChangeOffset () const
SUMOReal getLateralSpeed () const
return the lateral speed of the current lane change maneuver
int getOwnState () const
int getShadowDirection () const
return the direction in which the current shadow lane lies
const std::vector< MSLane * > & getShadowFurtherLanes () const
const std::vector< SUMOReal > & getShadowFurtherLanesPosLat () const
MSLane * getShadowLane () const
Returns the lane the vehicles shadow is on during continuous/sublane lane change.
MSLane * getShadowLane (const MSLane *lane) const
return the shadow lane for the given lane
void * inform (void *info, MSVehicle *sender)
bool isChangingLanes () const
return true if the vehicle currently performs a lane change maneuver
bool isOpposite () const
MSLCM_SL2015 (MSVehicle &v)
bool pastMidpoint () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
SUMOReal patchSpeed (const SUMOReal min, const SUMOReal wanted, const SUMOReal max, const MSCFModel &cfModel)
Called to adapt the speed in order to allow a lane change.
void prepareStep ()
void primaryLaneChanged (MSLane *source, MSLane *target, int direction)
called once when the vehicles primary lane changes
SUMOTime remainingTime () const
return whether the vehicle passed the midpoint of a continuous lane change maneuver
void removeShadowApproachingInformation () const
void resetChanged ()
reset the flag whether a vehicle already moved to false
void setNoShadowPartialOccupator (MSLane *lane)
void setOwnState (int state)
void setShadowApproachingInformation (MSLink *link) const
set approach information for the shadow vehicle
void setShadowLane (MSLane *lane)
set the shadow lane
void setShadowPartialOccupator (MSLane *lane)
bool startLaneChangeManeuver (MSLane *source, MSLane *target, int direction)
start the lane change maneuver and return whether it continues
void unchanged ()
bool updateCompletion ()
void updateShadowLane ()
virtual int wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager &msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > &leader, const std::pair< MSVehicle *, SUMOReal > &neighLead, const std::pair< MSVehicle *, SUMOReal > &neighFollow, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked)
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
int wantsChangeSublane (int laneOffset, const MSLeaderDistanceInfo &leaders, const MSLeaderDistanceInfo &followers, const MSLeaderDistanceInfo &blockers, const MSLeaderDistanceInfo &neighLeaders, const MSLeaderDistanceInfo &neighFollowers, const MSLeaderDistanceInfo &neighBlockers, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked, SUMOReal &latDist, int &blocked)
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
virtual ~MSLCM_SL2015 ()
Static Public Member Functions
static MSAbstractLaneChangeModel * build (LaneChangeModel lcm, MSVehicle &vehicle)
Factory method for instantiating new lane changing models.
static void initGlobalOptions (const OptionsCont &oc)
init global model parameters
Protected Types
typedef std::pair< SUMOReal, int > Info
information regarding save velocity (unused) and state flags of the ego vehicle
Protected Member Functions
int _wantsChangeSublane (int laneOffset, const MSLeaderDistanceInfo &leaders, const MSLeaderDistanceInfo &followers, const MSLeaderDistanceInfo &blockers, const MSLeaderDistanceInfo &neighLeaders, const MSLeaderDistanceInfo &neighFollowers, const MSLeaderDistanceInfo &neighBlockers, const MSLane &neighLane, const std::vector< MSVehicle::LaneQ > &preb, MSVehicle **lastBlocked, MSVehicle **firstBlocked, SUMOReal &latDist, int &blocked)
helper function for doing the actual work
bool amBlockingFollower ()
bool amBlockingFollowerNB ()
bool amBlockingFollowerPlusNB ()
bool amBlockingLeader ()
bool cancelRequest (int state)
whether the influencer cancels the given request
int checkBlocking (const MSLane &neighLane, SUMOReal &latDist, int laneOffset, const MSLeaderDistanceInfo &leaders, const MSLeaderDistanceInfo &followers, const MSLeaderDistanceInfo &blockers, const MSLeaderDistanceInfo &neighLeaders, const MSLeaderDistanceInfo &neighFollowers, const MSLeaderDistanceInfo &neighBlockers, std::vector< CLeaderDist > *collectLeadBlockers=0, std::vector< CLeaderDist > *collectFollowBlockers=0, bool saveOriginalLatDist=true)
restrict latDist to permissible speed and determine blocking state depending on that distance
int checkStrategicChange (int ret, int laneOffset, const std::vector< MSVehicle::LaneQ > &preb, const MSLeaderDistanceInfo &leaders, const MSLeaderDistanceInfo &neighLeaders, int currIdx, int bestLaneOffset, bool changeToBest, int lcaCounter, SUMOReal currentDist, SUMOReal neighDist, SUMOReal laDist, int roundaboutEdgesAhead)
compute strategic lane change actions
int computeSublaneShift (const MSEdge *prevEdge, const MSEdge *curEdge)
compute shift so that prevSublane + shift = newSublane
virtual bool congested (const MSVehicle *const neighLeader)
bool currentDistAllows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist)
bool currentDistDisallows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist)
StateAndDist decideDirection (StateAndDist sd1, StateAndDist sd2) const
decide in which direction to move in case both directions are desirable
void informFollower (int blocked, int dir, const CLeaderDist &neighFollow, SUMOReal remainingSeconds, SUMOReal plannedSpeed)
decide whether we will try cut in before the follower or allow to be overtaken
void informFollowers (int blocked, int dir, const std::vector< CLeaderDist > &blockers, SUMOReal remainingSeconds, SUMOReal plannedSpeed)
call informFollower for multiple followers
SUMOReal informLeader (int blocked, int dir, const CLeaderDist &neighLead, SUMOReal remainingSeconds)
SUMOReal informLeaders (int blocked, int dir, const std::vector< CLeaderDist > &blockers, SUMOReal remainingSeconds)
void initLastLaneChangeOffset (int dir)
int keepLatGap (int state, const MSLeaderDistanceInfo &leaders, const MSLeaderDistanceInfo &followers, const MSLeaderDistanceInfo &blockers, const MSLeaderDistanceInfo &neighLeaders, const MSLeaderDistanceInfo &neighFollowers, const MSLeaderDistanceInfo &neighBlockers, const MSLane &neighLane, int laneOffset, SUMOReal &latDist, int &blocked)
check whether lateral gap requirements are met override the current maneuver if necessary
void msg (const CLeaderDist &cld, SUMOReal speed, int state)
send a speed recommendation to the given vehicle
virtual bool predInteraction (const std::pair< MSVehicle *, SUMOReal > &leader)
void saveBlockerLength (const MSVehicle *blocker, int lcaCounter)
save space for vehicles which need to counter-lane-change
void saveBlockerLength (SUMOReal length)
reserve space at the end of the lane to avoid dead locks
int slowDownForBlocked (MSVehicle **blocked, int state)
compute useful slowdowns for blocked vehicles
void updateExpectedSublaneSpeeds (const MSLeaderInfo &ahead, int sublaneOffset, int laneIndex)
update expected speeds for each sublane of the current edge
void updateGaps (const MSLeaderDistanceInfo &others, SUMOReal foeOffset, SUMOReal newCenter, SUMOReal gapFactor, SUMOReal &surplusGapRight, SUMOReal &surplusGapLeft) const
check remaining lateral gaps for the given foe vehicles
Static Protected Member Functions
static int checkBlockingVehicles (const MSVehicle *ego, const MSLeaderDistanceInfo &vehicles, SUMOReal latDist, SUMOReal foeOffset, bool leaders, LaneChangeAction blockType, std::vector< CLeaderDist > *collectBlockers=0)
check whether any of the vehicles overlaps with ego
static LaneChangeAction getLCA (int state, SUMOReal latDist)
compute lane change action from desired lateral distance
static CLeaderDist getLongest (const MSLeaderDistanceInfo &ldi)
get the longest vehicle in the given info
static CLeaderDist getSlowest (const MSLeaderDistanceInfo &ldi)
get the slowest vehicle in the given info
static bool overlap (SUMOReal right, SUMOReal left, SUMOReal right2, SUMOReal left2)
return whether the given intervals overlap
Protected Attributes
bool myAlreadyChanged
whether the vehicle has already moved this step
bool myCanChangeFully
whether the current lane changing meneuver can be finished in a single step
const MSCFModel & myCarFollowModel
The vehicle's car following model.
bool myDontBrake
flag to prevent speed adaptation by slowing down
std::vector< SUMOReal > myExpectedSublaneSpeeds
expected travel speeds on all sublanes on the current edge(!)
SUMOReal myKeepRightProbability
SUMOReal myLaneChangeCompletion
progress of the lane change maneuver 0:started, 1:complete
int myLaneChangeDirection
direction of the lane change maneuver -1 means right, 1 means left
const MSEdge * myLastEdge
expected travel speeds on all sublanes on the current edge(!)
SUMOReal myLateralspeed
The lateral offset during a continuous LaneChangeManeuver.
SUMOReal myLeadingBlockerLength
SUMOReal myLeftSpace
SUMOReal myLookAheadSpeed
const LaneChangeModel myModel
the type of this model
std::vector< MSLane * > myNoPartiallyOccupatedByShadow
SUMOReal myOrigLatDist
the complete lateral distance the vehicle wants to travel to finish its maneuver
int myOwnState
The current state of the vehicle.
std::vector< MSLane * > myPartiallyOccupatedByShadow
list of lanes where the shadow vehicle is partial occupator
int myPreviousState
lane changing state from the previous simulation step
std::vector< MSLane * > myShadowFurtherLanes
std::vector< SUMOReal > myShadowFurtherLanesPosLat
MSLane * myShadowLane
A lane that is partially occupied by the front of the vehicle but that is not the primary lane.
SUMOReal mySpeedGainProbabilityLeft
a value for tracking the probability that a change to the left is beneficial
SUMOReal mySpeedGainProbabilityRight
a value for tracking the probability that a change to the right is beneficial
MSVehicle & myVehicle
The vehicle this lane-changer belongs to.
std::vector< SUMOReal > myVSafes
speed adaptation requests by ego and surrounding vehicles
user configurable model parameters
const SUMOReal myStrategicParam
const SUMOReal myCooperativeParam
const SUMOReal mySpeedGainParam
const SUMOReal myKeepRightParam
const SUMOReal mySublaneParam
const SUMOReal myPushy
derived parameters
const SUMOReal myChangeProbThresholdRight
const SUMOReal myChangeProbThresholdLeft
const SUMOReal mySpeedLossProbThreshold
Static Protected Attributes
static bool myAllowOvertakingRight
whether overtaking on the right is permitted
static bool myLCOutput
whether to record lane-changing
Detailed Description
A lane change model developed by J. Erdmann.
Definition at line 44 of file MSLCM_SL2015.h.
Member Typedef Documentation
typedef std::pair<SUMOReal, int> MSLCM_SL2015::Info protected
information regarding save velocity (unused) and state flags of the ego vehicle
Definition at line 191 of file MSLCM_SL2015.h.
Member Enumeration Documentation
enum MSLCM_SL2015::MyLCAEnum
Enumerator
LCA_MNone
LCA_AMBLOCKINGLEADER
LCA_AMBLOCKINGFOLLOWER
LCA_MRIGHT
LCA_MLEFT
LCA_AMBLOCKINGFOLLOWER_DONTBRAKE
LCA_CHANGE_TO_HELP
LCA_AMBACKBLOCKER
LCA_AMBACKBLOCKER_STANDING
Definition at line 47 of file MSLCM_SL2015.h.
Constructor & Destructor Documentation
MSLCM_SL2015::MSLCM_SL2015 (MSVehicle & v)
Definition at line 102 of file MSLCM_SL2015.cpp.
References MSGlobals::gLateralResolution.
MSLCM_SL2015::~MSLCM_SL2015 () virtual
Definition at line 128 of file MSLCM_SL2015.cpp.
References changed().
Member Function Documentation
SUMOReal MSLCM_SL2015::_patchSpeed (const SUMOReal min, const SUMOReal wanted, const SUMOReal max, const MSCFModel & cfModel)
helper function which contains the actual logic
Definition at line 233 of file MSLCM_SL2015.cpp.
References changed(), gDebugFlag2, MSLane::getEdge(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSEdge::getLanes(), MSVehicleType::getMinGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, LCA_AMBLOCKINGLEADER, LCA_BLOCKED, LCA_BLOCKED_BY_FOLLOWER, LCA_BLOCKED_BY_LEADER, LCA_COOPERATIVE, LCA_STRATEGIC, LCA_WANTS_LANECHANGE, MAX2(), MIN2(), myDontBrake, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, myVSafes, NUMERICAL_EPS, STEPS2TIME, MSCFModel::stopSpeed(), and SUMOReal.
Referenced by patchSpeed().
int MSLCM_SL2015::_wantsChangeSublane (int laneOffset, const MSLeaderDistanceInfo & leaders, const MSLeaderDistanceInfo & followers, const MSLeaderDistanceInfo & blockers, const MSLeaderDistanceInfo & neighLeaders, const MSLeaderDistanceInfo & neighFollowers, const MSLeaderDistanceInfo & neighBlockers, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked, SUMOReal & latDist, int & blocked) protected
helper function for doing the actual work
determine the leftmost and rightmost sublanes currently occupied
Definition at line 796 of file MSLCM_SL2015.cpp.
References abs, amBlockingFollowerPlusNB(), MSVehicle::LaneQ::bestContinuations, MSCFModel::brakeGap(), MSAbstractLaneChangeModel::cancelRequest(), MSVehicle::Influencer::changeRequestRemainingSeconds(), checkBlocking(), checkStrategicChange(), currentDistAllows(), DELTA_T, MSEdge::EDGEFUNCTION_INTERNAL, GAIN_PERCEPTION_THRESHOLD, gDebugFlag2, MSVehicle::getCarFollowModel(), MSNet::getCurrentTimeStep(), MSLane::getEdge(), MSBaseVehicle::getID(), Named::getIDSecure(), MSLane::getIndex(), MSVehicle::getInfluencer(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getLateralPositionOnLane(), MSVehicleType::getLengthWithGap(), MSLane::getLinkCont(), getLongest(), MSVehicle::getPositionOnLane(), MSVehicleType::getPreferredLateralAlignment(), MSEdge::getPurpose(), MSLane::getRightmostSublane(), MSVehicle::getRightSideOnEdge(), MSLane::getRightSideOnEdge(), MSCFModel::getSecureGap(), getSlowest(), MSVehicle::getSpeed(), MSLane::getSpeedLimit(), MSEdge::getSubLaneSides(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSLane::getWidth(), MSEdge::getWidth(), MSLeaderInfo::hasStoppedVehicle(), informFollowers(), informLeaders(), KEEP_RIGHT_ACCEPTANCE, KEEP_RIGHT_TIME, LATALIGN_ARBITRARY, LATALIGN_CENTER, LATALIGN_COMPACT, LATALIGN_LEFT, LATALIGN_NICE, LATALIGN_RIGHT, LCA_COOPERATIVE, LCA_KEEPRIGHT, LCA_LEFT, LCA_MLEFT, LCA_MRIGHT, LCA_NONE, LCA_RIGHT, LCA_SPEEDGAIN, LCA_STAY, LCA_SUBLANE, LCA_TRACI, LCA_URGENT, MSVehicle::LaneQ::length, LOOK_AHEAD_MIN_SPEED, LOOK_AHEAD_SPEED_MEMORY, LOOK_FORWARD_LEFT, LOOK_FORWARD_RIGHT, max, MAX2(), MIN2(), myCanChangeFully, myChangeProbThresholdLeft, myChangeProbThresholdRight, myCooperativeParam, myExpectedSublaneSpeeds, myKeepRightParam, myKeepRightProbability, myLeadingBlockerLength, myLeftSpace, myLookAheadSpeed, MSAbstractLaneChangeModel::myOwnState, myPreviousState, mySpeedGainProbabilityLeft, mySpeedGainProbabilityRight, mySpeedLossProbThreshold, myStrategicParam, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, RELGAIN_NORMALIZATION_MIN_SPEED, ROUNDABOUT_DIST_BONUS, saveBlockerLength(), SIMTIME, slowDownForBlocked(), SPEED_GAIN_MIN_SECONDS, STEPS2TIME, SUMOReal, toString(), MSLeaderDistanceInfo::toString(), TS, and URGENCY.
Referenced by setOwnState(), and wantsChangeSublane().
bool MSAbstractLaneChangeModel::alreadyChanged () const inline inherited
reset the flag whether a vehicle already moved to false
Definition at line 324 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myAlreadyChanged.
Referenced by MSLaneChanger::change().
bool MSLCM_SL2015::amBlockingFollower () inline protected
Definition at line 174 of file MSLCM_SL2015.h.
References LCA_AMBLOCKINGFOLLOWER, and MSAbstractLaneChangeModel::myOwnState.
bool MSLCM_SL2015::amBlockingFollowerNB () inline protected
Definition at line 177 of file MSLCM_SL2015.h.
References LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, and MSAbstractLaneChangeModel::myOwnState.
bool MSLCM_SL2015::amBlockingFollowerPlusNB () inline protected
Definition at line 180 of file MSLCM_SL2015.h.
References LCA_AMBLOCKINGFOLLOWER, LCA_AMBLOCKINGFOLLOWER_DONTBRAKE, and MSAbstractLaneChangeModel::myOwnState.
Referenced by _wantsChangeSublane().
bool MSLCM_SL2015::amBlockingLeader () inline protected
Definition at line 171 of file MSLCM_SL2015.h.
References LCA_AMBLOCKINGLEADER, and MSAbstractLaneChangeModel::myOwnState.
MSAbstractLaneChangeModel * MSAbstractLaneChangeModel::build (LaneChangeModel lcm, MSVehicle & vehicle) static inherited
Factory method for instantiating new lane changing models.
Parameters
[in] lcm The type of model to build
[in] vehicle The vehicle for which this model shall be built
Definition at line 63 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLateralResolution, LCM_DEFAULT, LCM_DK2008, LCM_JE2013, LCM_LC2013, LCM_SL2015, and toString().
Referenced by MSVehicle::MSVehicle(), and MSAbstractLaneChangeModel::StateAndDist::StateAndDist().
bool MSAbstractLaneChangeModel::cancelRequest (int state) protected inherited
whether the influencer cancels the given request
Definition at line 244 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::influenceChangeDecision(), and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), _wantsChangeSublane(), and MSAbstractLaneChangeModel::isOpposite().
void MSLCM_SL2015::changed () virtual
Implements MSAbstractLaneChangeModel.
Definition at line 766 of file MSLCM_SL2015.cpp.
References DEBUG_COND, MSVehicle::getBestLaneOffset(), MSBaseVehicle::getID(), LOOK_AHEAD_MIN_SPEED, myCanChangeFully, myDontBrake, myKeepRightProbability, myLeadingBlockerLength, myLeftSpace, myLookAheadSpeed, MSAbstractLaneChangeModel::myOwnState, mySpeedGainProbabilityLeft, mySpeedGainProbabilityRight, MSAbstractLaneChangeModel::myVehicle, myVSafes, and SIMTIME.
Referenced by _patchSpeed(), and ~MSLCM_SL2015().
void MSAbstractLaneChangeModel::changedToOpposite () inherited
called when a vehicle changes between lanes in opposite directions
Definition at line 350 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myAlreadyChanged, and MSAbstractLaneChangeModel::myAmOpposite.
Referenced by MSAbstractLaneChangeModel::debugVehicle(), MSVehicle::executeMove(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
int MSLCM_SL2015::checkBlocking (const MSLane & neighLane, SUMOReal & latDist, int laneOffset, const MSLeaderDistanceInfo & leaders, const MSLeaderDistanceInfo & followers, const MSLeaderDistanceInfo & blockers, const MSLeaderDistanceInfo & neighLeaders, const MSLeaderDistanceInfo & neighFollowers, const MSLeaderDistanceInfo & neighBlockers, std::vector< CLeaderDist > * collectLeadBlockers = 0, std::vector< CLeaderDist > * collectFollowBlockers = 0, bool saveOriginalLatDist = true) protected
restrict latDist to permissible speed and determine blocking state depending on that distance
Definition at line 1574 of file MSLCM_SL2015.cpp.
References checkBlockingVehicles(), gDebugFlag2, MSVehicle::getCenterOnEdge(), MSLane::getEdge(), MSVehicle::getLane(), MSVehicleType::getMaxSpeedLat(), MSLane::getRightSideOnEdge(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSEdge::getWidth(), LCA_BLOCKED_BY_FOLLOWER, LCA_BLOCKED_BY_LEADER, LCA_BLOCKED_BY_LEFT_FOLLOWER, LCA_BLOCKED_BY_LEFT_LEADER, LCA_BLOCKED_BY_RIGHT_FOLLOWER, LCA_BLOCKED_BY_RIGHT_LEADER, LCA_BLOCKED_LEFT, LCA_BLOCKED_RIGHT, LCA_OVERLAPPING, MAX2(), MIN2(), myCanChangeFully, myOrigLatDist, myPushy, MSAbstractLaneChangeModel::myVehicle, SPEED2DIST, SUMOReal, and updateGaps().
Referenced by _wantsChangeSublane(), and keepLatGap().
int MSLCM_SL2015::checkBlockingVehicles (const MSVehicle * ego, const MSLeaderDistanceInfo & vehicles, SUMOReal latDist, SUMOReal foeOffset, bool leaders, LaneChangeAction blockType, std::vector< CLeaderDist > * collectBlockers = 0) static protected
check whether any of the vehicles overlaps with ego
Definition at line 1673 of file MSLCM_SL2015.cpp.
References gDebugFlag2, MSVehicle::getCarFollowModel(), MSCFModel::getMaxDecel(), MSVehicle::getRightSideOnEdge(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSGlobals::gLateralResolution, LCA_OVERLAPPING, MAX2(), MIN2(), MSLeaderInfo::numSublanes(), overlap(), and SUMOReal.
Referenced by checkBlocking().
int MSLCM_SL2015::checkStrategicChange (int ret, int laneOffset, const std::vector< MSVehicle::LaneQ > & preb, const MSLeaderDistanceInfo & leaders, const MSLeaderDistanceInfo & neighLeaders, int currIdx, int bestLaneOffset, bool changeToBest, int lcaCounter, SUMOReal currentDist, SUMOReal neighDist, SUMOReal laDist, int roundaboutEdgesAhead) protected
compute strategic lane change actions
we urgently need to change lanes to follow our route
Definition at line 1826 of file MSLCM_SL2015.cpp.
References abs, MSVehicle::LaneQ::bestContinuations, MSVehicle::LaneQ::bestLaneOffset, MSVehicle::congested(), currentDistDisallows(), MSCFModel::followSpeed(), gDebugFlag2, MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), MSVehicle::getLane(), MSCFModel::getMaxDecel(), MSVehicle::getPositionOnLane(), getSlowest(), MSVehicle::getSpeed(), MSLane::getSpeedLimit(), MSLeaderInfo::hasStoppedVehicle(), MSLeaderInfo::hasVehicles(), MSVehicle::influenceChangeDecision(), JAM_FACTOR, LCA_STAY, LCA_STRATEGIC, LCA_TRACI, LCA_URGENT, MSVehicle::LaneQ::length, MAX2(), MSAbstractLaneChangeModel::myAllowOvertakingRight, MSAbstractLaneChangeModel::myCarFollowModel, myChangeProbThresholdLeft, myLookAheadSpeed, mySpeedGainProbabilityRight, MSAbstractLaneChangeModel::myVehicle, myVSafes, MSVehicle::LaneQ::occupation, SIMTIME, SUMO_const_haltingSpeed, SUMOReal, TS, and TURN_LANE_DIST.
Referenced by _wantsChangeSublane().
void MSAbstractLaneChangeModel::cleanupShadowLane () inherited
Definition at line 224 of file MSAbstractLaneChangeModel.cpp.
References MSBaseVehicle::getID(), MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::myShadowFurtherLanes, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, MSLane::resetPartialOccupation(), and SIMTIME.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::resetChanged(), and MSVehicle::~MSVehicle().
int MSLCM_SL2015::computeSublaneShift (const MSEdge * prevEdge, const MSEdge * curEdge) protected
compute shift so that prevSublane + shift = newSublane
Definition at line 736 of file MSLCM_SL2015.cpp.
References MSEdge::getLanes(), MSLane::getLinkCont(), max, and MSLeaderInfo::numSublanes().
Referenced by prepareStep().
bool MSAbstractLaneChangeModel::congested (const MSVehicle *const neighLeader) protected virtual inherited
Definition at line 108 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::congested(), MSVehicle::getLane(), MSLane::getSpeedLimit(), and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSAbstractLaneChangeModel::isOpposite(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
bool MSLCM_SL2015::currentDistAllows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist) inline protected
Definition at line 186 of file MSLCM_SL2015.h.
References abs.
Referenced by _wantsChangeSublane().
bool MSLCM_SL2015::currentDistDisallows (SUMOReal dist, int laneOffset, SUMOReal lookForwardDist) inline protected
Definition at line 183 of file MSLCM_SL2015.h.
References abs.
Referenced by checkStrategicChange().
bool MSLCM_SL2015::debugVehicle () const virtual
whether the current vehicles shall be debugged
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 134 of file MSLCM_SL2015.cpp.
References DEBUG_COND.
MSLCM_SL2015::StateAndDist MSLCM_SL2015::decideDirection (StateAndDist sd1, StateAndDist sd2) const protected virtual
decide in which direction to move in case both directions are desirable
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 1760 of file MSLCM_SL2015.cpp.
References DEBUG_COND, MSAbstractLaneChangeModel::StateAndDist::dir, MSBaseVehicle::getID(), MSAbstractLaneChangeModel::StateAndDist::latDist, LCA_BLOCKED, LCA_CHANGE_REASONS, LCA_STAY, LCA_SUBLANE, LCA_WANTS_LANECHANGE, MSAbstractLaneChangeModel::myVehicle, SIMTIME, MSAbstractLaneChangeModel::StateAndDist::state, and toString().
void MSAbstractLaneChangeModel::endLaneChangeManeuver (const MSMoveReminder::Notification reason = MSMoveReminder::NOTIFICATION_LANE_CHANGE) inherited
Definition at line 191 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::cleanupShadowLane(), MSVehicle::fixPosition(), MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::myVehicle, MSVehicle::switchOffSignal(), UNUSED_PARAMETER, MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSVehicleTransfer::add(), MSLaneChanger::continueChange(), MSVehicle::executeMove(), MSAbstractLaneChangeModel::resetChanged(), and MSAbstractLaneChangeModel::updateShadowLane().
SUMOReal MSAbstractLaneChangeModel::getAngleOffset () const inherited
return the angle offset during a continuous change maneuver
Definition at line 321 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::pastMidpoint(), STEPS2TIME, and SUMOReal.
Referenced by MSAbstractLaneChangeModel::getLaneChangeDirection().
int MSAbstractLaneChangeModel::getLaneChangeDirection () const inline inherited
return the direction of the current lane change maneuver
Definition at line 308 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::myLaneChangeDirection, and SUMOReal.
Referenced by MSLaneChanger::continueChange().
SUMOTime MSAbstractLaneChangeModel::getLastLaneChangeOffset () const inline inherited
Definition at line 289 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLastLaneChangeOffset.
SUMOReal MSAbstractLaneChangeModel::getLateralSpeed () const inline inherited
return the lateral speed of the current lane change maneuver
Definition at line 319 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLateralspeed.
Referenced by MSLaneChanger::continueChange().
LaneChangeAction MSLCM_SL2015::getLCA (int state, SUMOReal latDist) static protected
compute lane change action from desired lateral distance
Definition at line 1819 of file MSLCM_SL2015.cpp.
References LCA_CHANGE_REASONS, LCA_LEFT, LCA_NONE, and LCA_RIGHT.
Referenced by wantsChangeSublane().
CLeaderDist MSLCM_SL2015::getLongest (const MSLeaderDistanceInfo & ldi) static protected
get the longest vehicle in the given info
Definition at line 1540 of file MSLCM_SL2015.cpp.
References MSLeaderInfo::numSublanes(), and SUMOReal.
Referenced by _wantsChangeSublane().
int MSAbstractLaneChangeModel::getOwnState () const inline inherited
Definition at line 148 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myOwnState.
Referenced by MSLaneChanger::change(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), saveBlockerLength(), and MSVehicle::setBlinkerInformation().
int MSAbstractLaneChangeModel::getShadowDirection () const inherited
return the direction in which the current shadow lane lies
Definition at line 304 of file MSAbstractLaneChangeModel.cpp.
References MSLane::getEdge(), MSLane::getIndex(), MSVehicle::getLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, MSAbstractLaneChangeModel::pastMidpoint(), and SUMOReal.
Referenced by MSLaneChanger::continueChange(), MSVehicle::executeMove(), MSAbstractLaneChangeModel::getLaneChangeDirection(), and GUIVehicle::selectBlockingFoes().
const std::vector<MSLane*>& MSAbstractLaneChangeModel::getShadowFurtherLanes () const inline inherited
Definition at line 281 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowFurtherLanes.
Referenced by MSVehicle::getBackPositionOnLane(), MSVehicle::getCenterOnEdge(), and MSVehicle::getLatOffset().
const std::vector<SUMOReal>& MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat () const inline inherited
Definition at line 285 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat.
Referenced by MSVehicle::getCenterOnEdge(), and MSVehicle::getLatOffset().
MSLane* MSAbstractLaneChangeModel::getShadowLane () const inline inherited
Returns the lane the vehicles shadow is on during continuous/sublane lane change.
Returns
The vehicle's shadow lane
Definition at line 269 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowLane.
Referenced by MSVehicle::checkRewindLinkLanes(), MSLaneChanger::continueChange(), MSLane::detectCollisions(), MSVehicle::executeMove(), MSVehicle::getBackPosition(), MSVehicle::getCenterOnEdge(), GUIVehicle::getParameterWindow(), MSVehicle::isFrontOnLane(), MSVehicle::planMoveInternal(), GUIVehicle::selectBlockingFoes(), MSLaneChangerSublane::startChangeSublane(), MSLaneChangerSublane::updateChanger(), and MSAbstractLaneChangeModel::updateShadowLane().
MSLane * MSAbstractLaneChangeModel::getShadowLane (const MSLane * lane) const inherited
return the shadow lane for the given lane
Definition at line 202 of file MSAbstractLaneChangeModel.cpp.
References MSBaseVehicle::getID(), MSVehicle::getLateralOverlap(), MSVehicle::getLateralPositionOnLane(), MSLane::getParallelLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, SIMTIME, and SUMOReal.
CLeaderDist MSLCM_SL2015::getSlowest (const MSLeaderDistanceInfo & ldi) static protected
get the slowest vehicle in the given info
Definition at line 1557 of file MSLCM_SL2015.cpp.
References max, MSLeaderInfo::numSublanes(), and SUMOReal.
Referenced by _wantsChangeSublane(), and checkStrategicChange().
void * MSLCM_SL2015::inform (void * info, MSVehicle * sender) virtual
Implements MSAbstractLaneChangeModel.
Definition at line 379 of file MSLCM_SL2015.cpp.
References DEBUG_COND, gDebugFlag2, MSBaseVehicle::getID(), MSNet::getInstance(), MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, myVSafes, and STEPS2TIME.
void MSLCM_SL2015::informFollower (int blocked, int dir, const CLeaderDist & neighFollow, SUMOReal remainingSeconds, SUMOReal plannedSpeed) protected
decide whether we will try cut in before the follower or allow to be overtaken
Definition at line 519 of file MSLCM_SL2015.cpp.
References ACCEL2SPEED, MSVehicle::congested(), CUT_IN_LEFT_SPEED_THRESHOLD, MSCFModel::followSpeed(), gDebugFlag2, MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSVehicle::getWaitingSeconds(), HELP_DECEL_FACTOR, HELP_OVERTAKE, LCA_AMBLOCKINGFOLLOWER, LCA_BLOCKED_BY_FOLLOWER, LCA_MLEFT, LCA_MRIGHT, LCA_RIGHT_IMPATIENCE, MAX2(), MAX_ONRAMP_LENGTH, msg(), MSAbstractLaneChangeModel::myAllowOvertakingRight, myLeftSpace, MSAbstractLaneChangeModel::myVehicle, myVSafes, POSITION_EPS, SPEED2DIST, STEPS2TIME, and SUMOReal.
Referenced by informFollowers(), and setOwnState().
void MSLCM_SL2015::informFollowers (int blocked, int dir, const std::vector< CLeaderDist > & blockers, SUMOReal remainingSeconds, SUMOReal plannedSpeed) protected
call informFollower for multiple followers
Definition at line 674 of file MSLCM_SL2015.cpp.
References informFollower().
Referenced by _wantsChangeSublane(), and setOwnState().
SUMOReal MSLCM_SL2015::informLeader (int blocked, int dir, const CLeaderDist & neighLead, SUMOReal remainingSeconds) protected
Definition at line 407 of file MSLCM_SL2015.cpp.
References ACCEL2SPEED, MSCFModel::brakeGap(), MSVehicle::congested(), MSCFModel::followSpeed(), gDebugFlag2, MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicleType::getLength(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSCFModel::getSecureGap(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), HELP_OVERTAKE, LCA_AMBLOCKINGLEADER, LCA_BLOCKED_BY_LEADER, LCA_MLEFT, MAX2(), MIN2(), MIN_FALLBEHIND, msg(), MSAbstractLaneChangeModel::myAllowOvertakingRight, MSAbstractLaneChangeModel::myCarFollowModel, myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myVehicle, myVSafes, SPEED2DIST, STEPS2TIME, MSCFModel::stopSpeed(), and SUMOReal.
Referenced by informLeaders(), and setOwnState().
SUMOReal MSLCM_SL2015::informLeaders (int blocked, int dir, const std::vector< CLeaderDist > & blockers, SUMOReal remainingSeconds) protected
Definition at line 662 of file MSLCM_SL2015.cpp.
References MSVehicle::getSpeed(), informLeader(), MIN2(), MSAbstractLaneChangeModel::myVehicle, and SUMOReal.
Referenced by _wantsChangeSublane(), and setOwnState().
void MSAbstractLaneChangeModel::initGlobalOptions (const OptionsCont & oc) static inherited
init global model parameters
Definition at line 56 of file MSAbstractLaneChangeModel.cpp.
References OptionsCont::getBool(), OptionsCont::isSet(), MSAbstractLaneChangeModel::myAllowOvertakingRight, and MSAbstractLaneChangeModel::myLCOutput.
Referenced by MSFrame::setMSGlobals(), and MSAbstractLaneChangeModel::StateAndDist::StateAndDist().
void MSAbstractLaneChangeModel::initLastLaneChangeOffset (int dir) protected inherited
Definition at line 251 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myLastLaneChangeOffset.
Referenced by MSAbstractLaneChangeModel::primaryLaneChanged().
bool MSAbstractLaneChangeModel::isChangingLanes () const inline inherited
return true if the vehicle currently performs a lane change maneuver
Definition at line 303 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeCompletion, and NUMERICAL_EPS.
Referenced by MSLaneChangerSublane::change(), MSLaneChanger::change(), MSVehicle::computeAngle(), MSLaneChanger::continueChange(), MSLane::detectCollisionBetween(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::getBackPosition(), MSVehicle::getPosition(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), and MSAbstractLaneChangeModel::updateShadowLane().
bool MSAbstractLaneChangeModel::isOpposite () const inline inherited
Definition at line 372 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::cancelRequest(), MSAbstractLaneChangeModel::congested(), MSAbstractLaneChangeModel::myAmOpposite, and MSAbstractLaneChangeModel::predInteraction().
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLaneChanger::changeOpposite(), MSVehicle::checkRewindLinkLanes(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), and MSVehicle::planMoveInternal().
int MSLCM_SL2015::keepLatGap (int state, const MSLeaderDistanceInfo & leaders, const MSLeaderDistanceInfo & followers, const MSLeaderDistanceInfo & blockers, const MSLeaderDistanceInfo & neighLeaders, const MSLeaderDistanceInfo & neighFollowers, const MSLeaderDistanceInfo & neighBlockers, const MSLane & neighLane, int laneOffset, SUMOReal & latDist, int & blocked) protected
check whether lateral gap requirements are met override the current maneuver if necessary
XXX to be made configurable
XXX todo
Definition at line 1959 of file MSLCM_SL2015.cpp.
References checkBlocking(), gDebugFlag2, MSVehicle::getCenterOnEdge(), MSLane::getEdge(), MSVehicle::getLane(), MSVehicle::getLateralPositionOnLane(), MSVehicleType::getMaxSpeedLat(), MSLane::getRightSideOnEdge(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSLane::getWidth(), MSEdge::getWidth(), LCA_BLOCKED_LEFT, LCA_BLOCKED_RIGHT, LCA_OVERLAPPING, LCA_STAY, LCA_STRATEGIC, MAX3(), MIN2(), MIN3(), MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, SPEED2DIST, SUMOReal, toString(), and updateGaps().
Referenced by wantsChangeSublane().
void MSLCM_SL2015::msg (const CLeaderDist & cld, SUMOReal speed, int state) protected
send a speed recommendation to the given vehicle
Definition at line 400 of file MSLCM_SL2015.cpp.
References MSAbstractLaneChangeModel::myVehicle, and SUMOReal.
Referenced by informFollower(), and informLeader().
bool MSLCM_SL2015::overlap (SUMOReal right, SUMOReal left, SUMOReal right2, SUMOReal left2) static protected
return whether the given intervals overlap
Definition at line 1752 of file MSLCM_SL2015.cpp.
References NUMERICAL_EPS.
Referenced by checkBlockingVehicles().
bool MSAbstractLaneChangeModel::pastMidpoint () const inline inherited
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 295 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myLaneChangeCompletion, and MSAbstractLaneChangeModel::remainingTime().
Referenced by MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getShadowDirection(), and MSAbstractLaneChangeModel::updateCompletion().
SUMOReal MSLCM_SL2015::patchSpeed (const SUMOReal min, const SUMOReal wanted, const SUMOReal max, const MSCFModel & cfModel) virtual
Called to adapt the speed in order to allow a lane change.
Parameters
min The minimum resulting speed
wanted The aspired speed of the car following model
max The maximum resulting speed
cfModel The model used
Returns
the new speed of the vehicle as proposed by the lane changer
Implements MSAbstractLaneChangeModel.
Definition at line 212 of file MSLCM_SL2015.cpp.
References _patchSpeed(), DEBUG_COND, gDebugFlag2, Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSAbstractLaneChangeModel::myVehicle, STEPS2TIME, SUMOReal, and toString().
bool MSAbstractLaneChangeModel::predInteraction (const std::pair< MSVehicle *, SUMOReal > & leader) protected virtual inherited
Definition at line 128 of file MSAbstractLaneChangeModel.cpp.
References MSVehicle::getSpeed(), MSCFModel::interactionGap(), MSAbstractLaneChangeModel::myCarFollowModel, and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSAbstractLaneChangeModel::isOpposite(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
void MSLCM_SL2015::prepareStep () virtual
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 685 of file MSLCM_SL2015.cpp.
References computeSublaneShift(), MSLane::getEdge(), MSVehicle::getLane(), MSEdge::getLanes(), MSEdge::getSubLaneSides(), MSGlobals::gLateralResolution, LCA_STRATEGIC, LCA_WANTS_LANECHANGE, max, MAX2(), myCanChangeFully, myDontBrake, myExpectedSublaneSpeeds, myKeepRightProbability, myLastEdge, myLeadingBlockerLength, myLeftSpace, myOrigLatDist, MSAbstractLaneChangeModel::myOwnState, mySpeedGainProbabilityLeft, mySpeedGainProbabilityRight, MSAbstractLaneChangeModel::myVehicle, and myVSafes.
void MSAbstractLaneChangeModel::primaryLaneChanged (MSLane * source, MSLane * target, int direction) inherited
called once when the vehicles primary lane changes
Definition at line 160 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changed(), OutputDevice::closeTag(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtLaneChange(), OutputDevice::getDeviceByOption(), Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getSpeed(), MSAbstractLaneChangeModel::initLastLaneChangeOffset(), LCA_LEFT, LCA_RIGHT, MSVehicle::leaveLane(), MSLane::leftByLaneChange(), MSAbstractLaneChangeModel::myLCOutput, MSAbstractLaneChangeModel::myOwnState, MSAbstractLaneChangeModel::myVehicle, MSMoveReminder::NOTIFICATION_LANE_CHANGE, OutputDevice::openTag(), SUMO_ATTR_DIR, SUMO_ATTR_FROM, SUMO_ATTR_ID, SUMO_ATTR_SPEED, SUMO_ATTR_TIME, SUMO_ATTR_TO, time2string(), toString(), and OutputDevice::writeAttr().
Referenced by MSLaneChanger::continueChange(), MSAbstractLaneChangeModel::setNoShadowPartialOccupator(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
SUMOTime MSAbstractLaneChangeModel::remainingTime () const inherited
return whether the vehicle passed the midpoint of a continuous lane change maneuver
Definition at line 328 of file MSAbstractLaneChangeModel.cpp.
References MSGlobals::gLaneChangeDuration, and MSAbstractLaneChangeModel::myLaneChangeCompletion.
Referenced by MSAbstractLaneChangeModel::pastMidpoint().
void MSAbstractLaneChangeModel::removeShadowApproachingInformation () const inherited
Definition at line 340 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myApproachedByShadow, and MSAbstractLaneChangeModel::myVehicle.
Referenced by MSVehicle::removeApproachingInformation(), and MSAbstractLaneChangeModel::setNoShadowPartialOccupator().
void MSAbstractLaneChangeModel::resetChanged () inline inherited
reset the flag whether a vehicle already moved to false
Definition at line 329 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::myAlreadyChanged, MSMoveReminder::NOTIFICATION_LANE_CHANGE, MSAbstractLaneChangeModel::startLaneChangeManeuver(), MSAbstractLaneChangeModel::updateCompletion(), and MSAbstractLaneChangeModel::updateShadowLane().
Referenced by MSVehicle::planMove().
void MSLCM_SL2015::saveBlockerLength (const MSVehicle * blocker, int lcaCounter) protected
save space for vehicles which need to counter-lane-change
Definition at line 1466 of file MSLCM_SL2015.cpp.
References MSCFModel::brakeGap(), gDebugFlag2, MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInstance(), MSVehicle::getLaneChangeModel(), MSVehicleType::getLengthWithGap(), MSCFModel::getMaxDecel(), MSAbstractLaneChangeModel::getOwnState(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MAX2(), myLeadingBlockerLength, myLeftSpace, MSAbstractLaneChangeModel::myVehicle, STEPS2TIME, SUMOReal, and toString().
Referenced by _wantsChangeSublane(), and setOwnState().
void MSLCM_SL2015::saveBlockerLength (SUMOReal length) inline protected virtual
reserve space at the end of the lane to avoid dead locks
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 167 of file MSLCM_SL2015.h.
References MAX2(), and myLeadingBlockerLength.
void MSAbstractLaneChangeModel::setNoShadowPartialOccupator (MSLane * lane) inline inherited
Definition at line 361 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow, MSAbstractLaneChangeModel::primaryLaneChanged(), MSAbstractLaneChangeModel::removeShadowApproachingInformation(), and MSAbstractLaneChangeModel::setShadowApproachingInformation().
Referenced by MSVehicle::enterLaneAtLaneChange().
void MSLCM_SL2015::setOwnState (int state) inline virtual
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 108 of file MSLCM_SL2015.h.
References _wantsChangeSublane(), informFollower(), informFollowers(), informLeader(), informLeaders(), MSAbstractLaneChangeModel::myOwnState, myPreviousState, saveBlockerLength(), slowDownForBlocked(), and SUMOReal.
void MSAbstractLaneChangeModel::setShadowApproachingInformation (MSLink * link) const inherited
set approach information for the shadow vehicle
Definition at line 334 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::myApproachedByShadow.
Referenced by MSVehicle::checkRewindLinkLanes(), and MSAbstractLaneChangeModel::setNoShadowPartialOccupator().
void MSAbstractLaneChangeModel::setShadowLane (MSLane * lane) inline inherited
set the shadow lane
Definition at line 277 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myShadowLane.
void MSAbstractLaneChangeModel::setShadowPartialOccupator (MSLane * lane) inline inherited
Definition at line 357 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myPartiallyOccupatedByShadow.
int MSLCM_SL2015::slowDownForBlocked (MSVehicle ** blocked, int state) protected
compute useful slowdowns for blocked vehicles
Definition at line 1430 of file MSLCM_SL2015.cpp.
References ACCEL2SPEED, MSCFModel::followSpeed(), gDebugFlag2, MSVehicle::getCarFollowModel(), MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInstance(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), LCA_AMBACKBLOCKER, LCA_AMBACKBLOCKER_STANDING, MSAbstractLaneChangeModel::myCarFollowModel, MSAbstractLaneChangeModel::myVehicle, myVSafes, POSITION_EPS, STEPS2TIME, SUMO_const_haltingSpeed, and SUMOReal.
Referenced by _wantsChangeSublane(), and setOwnState().
bool MSAbstractLaneChangeModel::startLaneChangeManeuver (MSLane * source, MSLane * target, int direction) inherited
start the lane change maneuver and return whether it continues
Definition at line 141 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::changedToOpposite(), DELTA_T, MSLane::getCenterOnEdge(), MSLane::getEdge(), MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::myLaneChangeDirection, MSAbstractLaneChangeModel::myLateralspeed, MSAbstractLaneChangeModel::myVehicle, MSAbstractLaneChangeModel::primaryLaneChanged(), SUMOReal, MSVehicle::switchOffSignal(), MSVehicle::switchOnSignal(), MSVehicle::VEH_SIGNAL_BLINKER_LEFT, and MSVehicle::VEH_SIGNAL_BLINKER_RIGHT.
Referenced by MSLaneChanger::changeOpposite(), MSAbstractLaneChangeModel::resetChanged(), MSLaneChanger::startChange(), and MSLaneChangerSublane::startChangeSublane().
void MSAbstractLaneChangeModel::unchanged () inline inherited
Definition at line 258 of file MSAbstractLaneChangeModel.h.
References DELTA_T, and MSAbstractLaneChangeModel::myLastLaneChangeOffset.
Referenced by MSLaneChanger::registerUnchanged().
bool MSAbstractLaneChangeModel::updateCompletion () inherited
Definition at line 183 of file MSAbstractLaneChangeModel.cpp.
References DELTA_T, MSGlobals::gLaneChangeDuration, MSAbstractLaneChangeModel::myLaneChangeCompletion, MSAbstractLaneChangeModel::pastMidpoint(), and SUMOReal.
Referenced by MSLaneChanger::continueChange(), and MSAbstractLaneChangeModel::resetChanged().
void MSLCM_SL2015::updateExpectedSublaneSpeeds (const MSLeaderInfo & ahead, int sublaneOffset, int laneIndex) protected virtual
update expected speeds for each sublane of the current edge
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 1506 of file MSLCM_SL2015.cpp.
References MSLane::allowsVehicleClass(), MSCFModel::followSpeed(), MSVehicle::getBackPositionOnLane(), MSVehicle::getBestLanes(), MSVehicle::getCarFollowModel(), MSLane::getEdge(), MSVehicle::getLane(), MSEdge::getLanes(), MSCFModel::getMaxDecel(), MSVehicleType::getMinGap(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), MSVehicleType::getVehicleClass(), MSLane::getVehicleMaxSpeed(), MSBaseVehicle::getVehicleType(), MIN2(), MSAbstractLaneChangeModel::myCarFollowModel, myExpectedSublaneSpeeds, MSAbstractLaneChangeModel::myVehicle, MSLeaderInfo::numSublanes(), and SUMOReal.
void MSLCM_SL2015::updateGaps (const MSLeaderDistanceInfo & others, SUMOReal foeOffset, SUMOReal newCenter, SUMOReal gapFactor, SUMOReal & surplusGapRight, SUMOReal & surplusGapLeft) const protected
check remaining lateral gaps for the given foe vehicles
foe vehicle occupies full sublanes
Definition at line 2071 of file MSLCM_SL2015.cpp.
References gDebugFlag2, MSBaseVehicle::getID(), MSVehicleType::getMinGapLat(), MSVehicle::getSpeed(), MSBaseVehicle::getVehicleType(), MSVehicleType::getWidth(), MSGlobals::gLateralResolution, MSLeaderInfo::hasVehicles(), MAX2(), MIN2(), MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, MSLeaderInfo::numSublanes(), and SUMOReal.
Referenced by checkBlocking(), and keepLatGap().
void MSAbstractLaneChangeModel::updateShadowLane () inherited
Definition at line 260 of file MSAbstractLaneChangeModel.cpp.
References MSAbstractLaneChangeModel::endLaneChangeManeuver(), gDebugFlag4, MSVehicle::getFurtherLanes(), MSVehicle::getFurtherLanesPosLat(), MSBaseVehicle::getID(), Named::getIDSecure(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getLateralOverlap(), MSVehicle::getLateralPositionOnLane(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::myShadowFurtherLanes, MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat, MSAbstractLaneChangeModel::myShadowLane, MSAbstractLaneChangeModel::myVehicle, NUMERICAL_EPS, MSLane::resetPartialOccupation(), MSLane::setPartialOccupation(), SIMTIME, time2string(), toString(), MSVehicle::updateFurtherLanes(), and WRITE_WARNING.
Referenced by MSLaneChanger::continueChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::executeMove(), MSAbstractLaneChangeModel::resetChanged(), and MSLaneChangerSublane::startChangeSublane().
virtual int MSAbstractLaneChangeModel::wantsChange (int laneOffset, MSAbstractLaneChangeModel::MSLCMessager & msgPass, int blocked, const std::pair< MSVehicle *, SUMOReal > & leader, const std::pair< MSVehicle *, SUMOReal > & neighLead, const std::pair< MSVehicle *, SUMOReal > & neighFollow, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked) inline virtual inherited
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
Reimplemented in MSLCM_LC2013, MSLCM_JE2013, and MSLCM_DK2008.
Definition at line 162 of file MSAbstractLaneChangeModel.h.
References MSAbstractLaneChangeModel::myModel, toString(), and UNUSED_PARAMETER.
Referenced by MSLaneChanger::checkChange().
int MSLCM_SL2015::wantsChangeSublane (int laneOffset, const MSLeaderDistanceInfo & leaders, const MSLeaderDistanceInfo & followers, const MSLeaderDistanceInfo & blockers, const MSLeaderDistanceInfo & neighLeaders, const MSLeaderDistanceInfo & neighFollowers, const MSLeaderDistanceInfo & neighBlockers, const MSLane & neighLane, const std::vector< MSVehicle::LaneQ > & preb, MSVehicle ** lastBlocked, MSVehicle ** firstBlocked, SUMOReal & latDist, int & blocked) virtual
Called to examine whether the vehicle wants to change using the given laneOffset. This method gets the information about the surrounding vehicles and whether another lane may be more preferable.
Reimplemented from MSAbstractLaneChangeModel.
Definition at line 140 of file MSLCM_SL2015.cpp.
References _wantsChangeSublane(), DEBUG_COND, gDebugFlag2, Named::getID(), MSBaseVehicle::getID(), MSNet::getInstance(), MSVehicle::getLane(), MSVehicle::getLateralPositionOnLane(), getLCA(), MSVehicle::getPositionOnLane(), MSVehicle::getSpeed(), keepLatGap(), LCA_BLOCKED, LCA_OVERLAPPING, LCA_STAY, LCA_WANTS_LANECHANGE, myCanChangeFully, myOrigLatDist, MSAbstractLaneChangeModel::myVehicle, STEPS2TIME, SUMOReal, and toString().
Field Documentation
bool MSAbstractLaneChangeModel::myAllowOvertakingRight static protected inherited
whether overtaking on the right is permitted
Definition at line 430 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), checkStrategicChange(), MSLCM_JE2013::informFollower(), informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), informLeader(), and MSAbstractLaneChangeModel::initGlobalOptions().
bool MSAbstractLaneChangeModel::myAlreadyChanged protected inherited
whether the vehicle has already moved this step
Definition at line 402 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::alreadyChanged(), MSAbstractLaneChangeModel::changedToOpposite(), and MSAbstractLaneChangeModel::resetChanged().
bool MSLCM_SL2015::myCanChangeFully protected
whether the current lane changing meneuver can be finished in a single step
Definition at line 302 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), changed(), checkBlocking(), prepareStep(), and wantsChangeSublane().
const MSCFModel& MSAbstractLaneChangeModel::myCarFollowModel protected inherited
The vehicle's car following model.
Definition at line 413 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), checkStrategicChange(), MSLCM_DK2008::informBlocker(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), informLeader(), MSAbstractLaneChangeModel::predInteraction(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), slowDownForBlocked(), updateExpectedSublaneSpeeds(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
const SUMOReal MSLCM_SL2015::myChangeProbThresholdLeft protected
Definition at line 325 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), and checkStrategicChange().
const SUMOReal MSLCM_SL2015::myChangeProbThresholdRight protected
Definition at line 324 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane().
const SUMOReal MSLCM_SL2015::myCooperativeParam protected
Definition at line 313 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane().
bool MSLCM_SL2015::myDontBrake protected
flag to prevent speed adaptation by slowing down
Definition at line 299 of file MSLCM_SL2015.h.
Referenced by _patchSpeed(), changed(), and prepareStep().
std::vector<SUMOReal> MSLCM_SL2015::myExpectedSublaneSpeeds protected
expected travel speeds on all sublanes on the current edge(!)
Definition at line 293 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), prepareStep(), and updateExpectedSublaneSpeeds().
const SUMOReal MSLCM_SL2015::myKeepRightParam protected
Definition at line 315 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane().
SUMOReal MSLCM_SL2015::myKeepRightProbability protected
Definition at line 280 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), changed(), and prepareStep().
SUMOReal MSAbstractLaneChangeModel::myLaneChangeCompletion protected inherited
progress of the lane change maneuver 0:started, 1:complete
Definition at line 393 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::isChangingLanes(), MSAbstractLaneChangeModel::pastMidpoint(), MSAbstractLaneChangeModel::remainingTime(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), and MSAbstractLaneChangeModel::updateCompletion().
int MSAbstractLaneChangeModel::myLaneChangeDirection protected inherited
direction of the lane change maneuver -1 means right, 1 means left
Definition at line 396 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getAngleOffset(), MSAbstractLaneChangeModel::getLaneChangeDirection(), MSAbstractLaneChangeModel::getShadowDirection(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
const MSEdge* MSLCM_SL2015::myLastEdge protected
expected travel speeds on all sublanes on the current edge(!)
Definition at line 296 of file MSLCM_SL2015.h.
Referenced by prepareStep().
SUMOReal MSAbstractLaneChangeModel::myLateralspeed protected inherited
The lateral offset during a continuous LaneChangeManeuver.
Definition at line 399 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getLateralSpeed(), and MSAbstractLaneChangeModel::startLaneChangeManeuver().
bool MSAbstractLaneChangeModel::myLCOutput static protected inherited
whether to record lane-changing
Definition at line 433 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::initGlobalOptions(), and MSAbstractLaneChangeModel::primaryLaneChanged().
SUMOReal MSLCM_SL2015::myLeadingBlockerLength protected
Definition at line 282 of file MSLCM_SL2015.h.
Referenced by _patchSpeed(), _wantsChangeSublane(), changed(), informLeader(), prepareStep(), and saveBlockerLength().
SUMOReal MSLCM_SL2015::myLeftSpace protected
Definition at line 283 of file MSLCM_SL2015.h.
Referenced by _patchSpeed(), _wantsChangeSublane(), changed(), informFollower(), informLeader(), prepareStep(), and saveBlockerLength().
SUMOReal MSLCM_SL2015::myLookAheadSpeed protected
Definition at line 287 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), changed(), and checkStrategicChange().
const LaneChangeModel MSAbstractLaneChangeModel::myModel protected inherited
the type of this model
Definition at line 416 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::decideDirection(), MSAbstractLaneChangeModel::updateExpectedSublaneSpeeds(), MSAbstractLaneChangeModel::wantsChange(), and MSAbstractLaneChangeModel::wantsChangeSublane().
std::vector<MSLane*> MSAbstractLaneChangeModel::myNoPartiallyOccupatedByShadow protected inherited
Definition at line 423 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getShadowLane(), and MSAbstractLaneChangeModel::setNoShadowPartialOccupator().
SUMOReal MSLCM_SL2015::myOrigLatDist protected
the complete lateral distance the vehicle wants to travel to finish its maneuver
Definition at line 308 of file MSLCM_SL2015.h.
Referenced by checkBlocking(), prepareStep(), and wantsChangeSublane().
int MSAbstractLaneChangeModel::myOwnState protected inherited
The current state of the vehicle.
Definition at line 390 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_JE2013::_patchSpeed(), _patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), _wantsChangeSublane(), MSLCM_DK2008::amBlockingFollower(), MSLCM_JE2013::amBlockingFollower(), MSLCM_LC2013::amBlockingFollower(), amBlockingFollower(), MSLCM_DK2008::amBlockingFollowerNB(), MSLCM_JE2013::amBlockingFollowerNB(), MSLCM_LC2013::amBlockingFollowerNB(), amBlockingFollowerNB(), MSLCM_DK2008::amBlockingFollowerPlusNB(), MSLCM_JE2013::amBlockingFollowerPlusNB(), MSLCM_LC2013::amBlockingFollowerPlusNB(), amBlockingFollowerPlusNB(), MSLCM_DK2008::amBlockingLeader(), MSLCM_JE2013::amBlockingLeader(), MSLCM_LC2013::amBlockingLeader(), amBlockingLeader(), MSLCM_DK2008::changed(), changed(), MSLCM_JE2013::changed(), MSLCM_LC2013::changed(), MSAbstractLaneChangeModel::getOwnState(), MSLCM_DK2008::inform(), inform(), MSLCM_JE2013::inform(), MSLCM_LC2013::inform(), MSLCM_DK2008::patchSpeed(), MSLCM_DK2008::prepareStep(), MSLCM_JE2013::prepareStep(), prepareStep(), MSLCM_LC2013::prepareStep(), MSAbstractLaneChangeModel::primaryLaneChanged(), setOwnState(), MSAbstractLaneChangeModel::setOwnState(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
std::vector<MSLane*> MSAbstractLaneChangeModel::myPartiallyOccupatedByShadow protected inherited
list of lanes where the shadow vehicle is partial occupator
Definition at line 419 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::setShadowPartialOccupator().
int MSLCM_SL2015::myPreviousState protected
lane changing state from the previous simulation step
Definition at line 305 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), and setOwnState().
const SUMOReal MSLCM_SL2015::myPushy protected
Definition at line 318 of file MSLCM_SL2015.h.
Referenced by checkBlocking().
std::vector<MSLane*> MSAbstractLaneChangeModel::myShadowFurtherLanes protected inherited
Definition at line 409 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::getShadowFurtherLanes(), and MSAbstractLaneChangeModel::updateShadowLane().
std::vector<SUMOReal> MSAbstractLaneChangeModel::myShadowFurtherLanesPosLat protected inherited
Definition at line 410 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::getShadowFurtherLanesPosLat(), and MSAbstractLaneChangeModel::updateShadowLane().
MSLane* MSAbstractLaneChangeModel::myShadowLane protected inherited
A lane that is partially occupied by the front of the vehicle but that is not the primary lane.
Definition at line 405 of file MSAbstractLaneChangeModel.h.
Referenced by MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), MSAbstractLaneChangeModel::setShadowLane(), and MSAbstractLaneChangeModel::updateShadowLane().
const SUMOReal MSLCM_SL2015::mySpeedGainParam protected
Definition at line 314 of file MSLCM_SL2015.h.
SUMOReal MSLCM_SL2015::mySpeedGainProbabilityLeft protected
a value for tracking the probability that a change to the left is beneficial
Definition at line 275 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), changed(), and prepareStep().
SUMOReal MSLCM_SL2015::mySpeedGainProbabilityRight protected
a value for tracking the probability that a change to the right is beneficial
Definition at line 273 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane(), changed(), checkStrategicChange(), and prepareStep().
const SUMOReal MSLCM_SL2015::mySpeedLossProbThreshold protected
Definition at line 326 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane().
const SUMOReal MSLCM_SL2015::myStrategicParam protected
Definition at line 312 of file MSLCM_SL2015.h.
Referenced by _wantsChangeSublane().
const SUMOReal MSLCM_SL2015::mySublaneParam protected
Definition at line 316 of file MSLCM_SL2015.h.
MSVehicle& MSAbstractLaneChangeModel::myVehicle protected inherited
The vehicle this lane-changer belongs to.
Definition at line 387 of file MSAbstractLaneChangeModel.h.
Referenced by MSLCM_JE2013::_patchSpeed(), _patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), _wantsChangeSublane(), MSAbstractLaneChangeModel::cancelRequest(), MSLCM_JE2013::changed(), changed(), MSLCM_LC2013::changed(), checkBlocking(), checkStrategicChange(), MSAbstractLaneChangeModel::cleanupShadowLane(), MSAbstractLaneChangeModel::congested(), decideDirection(), MSAbstractLaneChangeModel::endLaneChangeManeuver(), MSAbstractLaneChangeModel::getShadowDirection(), MSAbstractLaneChangeModel::getShadowLane(), MSLCM_JE2013::inform(), inform(), MSLCM_LC2013::inform(), MSLCM_DK2008::informBlocker(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), informLeader(), informLeaders(), keepLatGap(), msg(), MSLCM_JE2013::MSLCM_JE2013(), MSLCM_LC2013::MSLCM_LC2013(), MSLCM_DK2008::patchSpeed(), MSLCM_JE2013::patchSpeed(), patchSpeed(), MSLCM_LC2013::patchSpeed(), MSAbstractLaneChangeModel::predInteraction(), prepareStep(), MSAbstractLaneChangeModel::primaryLaneChanged(), MSAbstractLaneChangeModel::removeShadowApproachingInformation(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), saveBlockerLength(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), slowDownForBlocked(), MSAbstractLaneChangeModel::startLaneChangeManeuver(), updateExpectedSublaneSpeeds(), updateGaps(), MSAbstractLaneChangeModel::updateShadowLane(), MSLCM_JE2013::wantsChange(), MSLCM_LC2013::wantsChange(), wantsChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
std::vector<SUMOReal> MSLCM_SL2015::myVSafes protected
speed adaptation requests by ego and surrounding vehicles
Definition at line 290 of file MSLCM_SL2015.h.
Referenced by _patchSpeed(), changed(), checkStrategicChange(), inform(), informFollower(), informLeader(), prepareStep(), and slowDownForBlocked().
The documentation for this class was generated from the following files:
MSLCM_SL2015.h
MSLCM_SL2015.cpp