SUMO - Simulation of Urban MObility: MSVehicleType Class Reference
MSVehicleType Class Reference
The car-following model and parameter.
#include <MSVehicleType.h>
Public Member Functions
bool amVehicleSpecific () const
Returns whether this type belongs to a single vehicle only (was modified)
const SUMOVTypeParameter & getParameter () const
MSVehicleType (const SUMOVTypeParameter &parameter)
Constructor.
bool wasSet (int what) const
Returns whether the given parameter was set.
virtual ~MSVehicleType ()
Destructor.
Atomar getter for simulation
const std::string & getID () const
Returns the name of the vehicle type.
int getNumericalID () const
Returns the running index of the vehicle type.
SUMOReal getLength () const
Get vehicle's length [m].
SUMOReal getLengthWithGap () const
Get vehicle's length including the minimum gap [m].
SUMOReal getMinGap () const
Get the free space in front of vehicles of this class.
SUMOReal getMinGapLat () const
Get the minimum lateral gap that vehicles of this type maintain.
const MSCFModel & getCarFollowModel () const
Returns the vehicle type's car following model definition (const version)
MSCFModel & getCarFollowModel ()
Returns the vehicle type's car following model definition (non-const version)
LaneChangeModel getLaneChangeModel () const
SUMOReal getMaxSpeed () const
Get vehicle's maximum speed [m/s].
SUMOReal computeChosenSpeedDeviation (MTRand *rng, const SUMOReal minDevFactor=0.2) const
Computes and returns the speed deviation.
SUMOReal getDefaultProbability () const
Get the default probability of this vehicle type.
SUMOVehicleClass getVehicleClass () const
Get this vehicle type's vehicle class.
SUMOEmissionClass getEmissionClass () const
Get this vehicle type's emission class.
const RGBColor & getColor () const
Returns this type's color.
SUMOReal getSpeedFactor () const
Returns this type's speed factor.
SUMOReal getSpeedDeviation () const
Returns this type's speed deviation.
SUMOReal getImpatience () const
Returns this type's impatience.
Atomar getter for visualization
SUMOReal getWidth () const
Get the width which vehicles of this class shall have when being drawn.
SUMOReal getHeight () const
Get the height which vehicles of this class shall have when being drawn.
SUMOVehicleShape getGuiShape () const
Get this vehicle type's shape.
std::string getOSGFile () const
Get this vehicle type's 3D model file name.
std::string getImgFile () const
Get this vehicle type's raster model file name.
int getPersonCapacity () const
Get this vehicle type's person capacity.
int getContainerCapacity () const
Get this vehicle type's container capacity.
SUMOTime getBoardingDuration () const
Get this vehicle type's boarding duration.
SUMOTime getLoadingDuration () const
Get this vehicle type's loading duration.
SUMOReal getMaxSpeedLat () const
Get vehicle's maximum lateral speed [m/s].
LateralAlignment getPreferredLateralAlignment () const
Get vehicle's preferred lateral alignment.
Setter methods
void setLength (const SUMOReal &length)
Set a new value for this type's length.
void setMinGap (const SUMOReal &minGap)
Set a new value for this type's minimum gap.
void setMaxSpeed (const SUMOReal &maxSpeed)
Set a new value for this type's maximum speed.
void setVClass (SUMOVehicleClass vclass)
Set a new value for this type's vehicle class.
void setDefaultProbability (const SUMOReal &prob)
Set a new value for this type's default probability.
void setSpeedFactor (const SUMOReal &factor)
Set a new value for this type's speed factor.
void setSpeedDeviation (const SUMOReal &dev)
Set a new value for this type's speed deviation.
void setEmissionClass (SUMOEmissionClass eclass)
Set a new value for this type's emission class.
void setColor (const RGBColor &color)
Set a new value for this type's color.
void setWidth (const SUMOReal &width)
Set a new value for this type's width.
void setShape (SUMOVehicleShape shape)
Set a new value for this type's shape.
void setImpatience (const SUMOReal impatience)
Set a new value for this type's impatience.
Static Public Member Functions
Static methods for building vehicle types
static MSVehicleType * build (SUMOVTypeParameter &from)
Builds the microsim vehicle type described by the given parameter.
static MSVehicleType * build (const std::string &id, const MSVehicleType *from)
Duplicates the microsim vehicle type giving it a the given id.
Private Member Functions
MSVehicleType (const MSVehicleType &)
Invalidated copy constructor.
MSVehicleType & operator= (const MSVehicleType &)
Invalidated assignment operator.
Private Attributes
MSCFModel * myCarFollowModel
instance of the car following model.
const int myIndex
the running index
const MSVehicleType * myOriginalType
The original type.
SUMOVTypeParameter myParameter
the parameter container
Static Private Attributes
static int myNextIndex = 0
next value for the running index
Detailed Description
The car-following model and parameter.
MSVehicleType stores the parameter of a single vehicle type and methods that use these for computing the vehicle's car-following behavior
It is assumed that within the simulation many vehicles are using the same vehicle type, quite common is using only one vehicle type for all vehicles.
You can think of it like of having a vehicle type for each VW Golf or Ford Mustang in your simulation while the car instances just refer to it.
Definition at line 74 of file MSVehicleType.h.
Constructor & Destructor Documentation
MSVehicleType::MSVehicleType (const SUMOVTypeParameter & parameter)
Constructor.
Parameters
[in] parameter The vehicle type's parameter
Definition at line 66 of file MSVehicleType.cpp.
References getLength(), and getMaxSpeed().
Referenced by build().
MSVehicleType::~MSVehicleType () virtual
Destructor.
Definition at line 73 of file MSVehicleType.cpp.
References myCarFollowModel, and SUMOReal.
MSVehicleType::MSVehicleType (const MSVehicleType &) private
Invalidated copy constructor.
Member Function Documentation
bool MSVehicleType::amVehicleSpecific () const inline
Returns whether this type belongs to a single vehicle only (was modified)
Returns
Whether this vehicle type is based on a differen one, and belongs to one vehicle only
Definition at line 455 of file MSVehicleType.h.
References myOriginalType.
Referenced by MSVehicle::replaceVehicleType(), and MSVehicle::~MSVehicle().
MSVehicleType * MSVehicleType::build (SUMOVTypeParameter & from) static
Builds the microsim vehicle type described by the given parameter.
Parameters
[in] from The vehicle type description
Returns
The built vehicle type
Exceptions
ProcessError on false values (not et used)
Definition at line 198 of file MSVehicleType.cpp.
References SUMOVTypeParameter::cfModel, SUMOVTypeParameter::getCFParam(), SUMOVTypeParameter::getDefaultAccel(), SUMOVTypeParameter::getDefaultDecel(), SUMOVTypeParameter::getDefaultImperfection(), MSVehicleType(), myCarFollowModel, SUMO_ATTR_ACCEL, SUMO_ATTR_CF_IDM_DELTA, SUMO_ATTR_CF_IDM_STEPPING, SUMO_ATTR_CF_IDMM_ADAPT_FACTOR, SUMO_ATTR_CF_IDMM_ADAPT_TIME, SUMO_ATTR_CF_KERNER_PHI, SUMO_ATTR_CF_PWAGNER2009_APPROB, SUMO_ATTR_CF_PWAGNER2009_TAULAST, SUMO_ATTR_CF_WIEDEMANN_ESTIMATION, SUMO_ATTR_CF_WIEDEMANN_SECURITY, SUMO_ATTR_DECEL, SUMO_ATTR_K, SUMO_ATTR_SIGMA, SUMO_ATTR_TAU, SUMO_ATTR_TMP1, SUMO_ATTR_TMP2, SUMO_ATTR_TMP3, SUMO_ATTR_TMP4, SUMO_ATTR_TMP5, SUMO_TAG_CF_BKERNER, SUMO_TAG_CF_DANIEL1, SUMO_TAG_CF_IDM, SUMO_TAG_CF_IDMM, SUMO_TAG_CF_KRAUSS, SUMO_TAG_CF_KRAUSS_ORIG1, SUMO_TAG_CF_KRAUSS_PLUS_SLOPE, SUMO_TAG_CF_PWAGNER2009, SUMO_TAG_CF_SMART_SK, SUMO_TAG_CF_WIEDEMANN, SUMOReal, and SUMOVTypeParameter::vehicleClass.
Referenced by getPreferredLateralAlignment(), TraCIServerAPI_Vehicle::getSingularType(), MSVehicleControl::MSVehicleControl(), MSStateHandler::myEndElement(), and MSRouteHandler::myEndElement().
MSVehicleType * MSVehicleType::build (const std::string & id, const MSVehicleType * from) static
Duplicates the microsim vehicle type giving it a the given id.
Parameters
[in] id The new id of the type
[in] from The vehicle type
Returns
The built vehicle type
Definition at line 263 of file MSVehicleType.cpp.
References MSCFModel::duplicate(), SUMOVTypeParameter::id, MSVehicleType(), myCarFollowModel, myOriginalType, and myParameter.
SUMOReal MSVehicleType::computeChosenSpeedDeviation (MTRand * rng, const SUMOReal minDevFactor = 0.2) const
Computes and returns the speed deviation.
Returns
A new, random speed deviation
Definition at line 79 of file MSVehicleType.cpp.
References MAX2(), MIN2(), myParameter, RandHelper::randNorm(), SUMOVTypeParameter::speedDev, SUMOVTypeParameter::speedFactor, and SUMOReal.
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), MSVehicleControl::buildVehicle(), getMaxSpeed(), and MSEdge::insertVehicle().
SUMOTime MSVehicleType::getBoardingDuration () const inline
Get this vehicle type's boarding duration.
Returns
The time a person needs to board a vehicle of this type
Definition at line 300 of file MSVehicleType.h.
References SUMOVTypeParameter::boardingDuration, and myParameter.
Referenced by MSTransportableControl::boardAnyWaiting().
const MSCFModel& MSVehicleType::getCarFollowModel () const inline
Returns the vehicle type's car following model definition (const version)
Returns
The vehicle type's car following model definition
Definition at line 149 of file MSVehicleType.h.
References myCarFollowModel.
Referenced by MSLink::blockedByFoe(), MEVehicle::estimateLeaveSpeed(), MSVehicle::estimateLeaveSpeed(), MSVehicle::executeMove(), MSVehicle::getCarFollowModel(), TraCIServerAPI_VehicleType::getVariable(), MESegment::isOpen(), MSVehicle::MSVehicle(), MSCalibrator::remainingVehicleCapacity(), TraCIServerAPI_VehicleType::setVariable(), MSVehicleControl::vehicleDeparted(), and MSMeanData_Emissions::MSLaneMeanDataValues::write().
MSCFModel& MSVehicleType::getCarFollowModel () inline
Returns the vehicle type's car following model definition (non-const version)
Returns
The vehicle type's car following model definition
Definition at line 157 of file MSVehicleType.h.
References myCarFollowModel.
const RGBColor& MSVehicleType::getColor () const inline
Returns this type's color.
Returns
The color of this type
Definition at line 210 of file MSVehicleType.h.
References SUMOVTypeParameter::color, and myParameter.
Referenced by TraCIServerAPI_VehicleType::getVariable(), and GUIBaseVehicle::setFunctionalColor().
int MSVehicleType::getContainerCapacity () const inline
Get this vehicle type's container capacity.
Returns
The container capacity of this vehicle type
Definition at line 293 of file MSVehicleType.h.
References SUMOVTypeParameter::containerCapacity, and myParameter.
Referenced by GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), and MSTransportableControl::loadAnyWaiting().
SUMOReal MSVehicleType::getDefaultProbability () const inline
Get the default probability of this vehicle type.
Returns
The probability to use this type
Definition at line 184 of file MSVehicleType.h.
References SUMOVTypeParameter::defaultProbability, and myParameter.
Referenced by MSRouteHandler::myEndElement(), MSRouteHandler::openVehicleTypeDistribution(), and setDefaultProbability().
SUMOEmissionClass MSVehicleType::getEmissionClass () const inline
Get this vehicle type's emission class.
Returns
The emission class of this vehicle type
See also
SUMOEmissionClass
Definition at line 202 of file MSVehicleType.h.
References SUMOVTypeParameter::emissionClass, and myParameter.
Referenced by MSVehicle::getCO2Emissions(), MSVehicle::getCOEmissions(), MSVehicle::getElectricityConsumption(), MSVehicle::getFuelConsumption(), MSVehicle::getHarmonoise_NoiseEmissions(), MSVehicle::getHCEmissions(), MSVehicle::getNOxEmissions(), MSVehicle::getPMxEmissions(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), TraCIServerAPI_VehicleType::getVariable(), MSDevice_Emissions::notifyMove(), MSMeanData_Emissions::MSLaneMeanDataValues::notifyMoveInternal(), MSMeanData_Harmonoise::MSLaneMeanDataValues::notifyMoveInternal(), MSEmissionExport::write(), MSMeanData_Emissions::MSLaneMeanDataValues::write(), MSAmitranTrajectories::writeVehicle(), and MSFullExport::writeVehicles().
SUMOVehicleShape MSVehicleType::getGuiShape () const inline
Get this vehicle type's shape.
Returns
The shape of this vehicle type
See also
SUMOVehicleShape
Definition at line 262 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::shape.
Referenced by GUIBaseVehicle::drawAction_drawVehicleAsPoly(), GUIBaseVehicle::drawOnPos(), MSVehicle::getBoundingPoly(), and TraCIServerAPI_VehicleType::getVariable().
SUMOReal MSVehicleType::getHeight () const inline
Get the height which vehicles of this class shall have when being drawn.
Returns
The height of this type's vehicles
Definition at line 254 of file MSVehicleType.h.
References SUMOVTypeParameter::height, and myParameter.
const std::string& MSVehicleType::getID () const inline
Returns the name of the vehicle type.
Returns
This type's id
Definition at line 102 of file MSVehicleType.h.
References SUMOVTypeParameter::id, and myParameter.
Referenced by MSVehicleControl::addVType(), MSInductLoop::collectVehiclesOnDet(), MSVTypeProbe::execute(), MSDevice_Vehroutes::generateOutput(), MSDevice_Tripinfo::generateOutput(), GUIPerson::getParameterWindow(), TraCIServerAPI_Vehicle::getSingularType(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), MSInductLoop::leaveDetectorByMove(), MEVehicle::MEVehicle(), MSVehicle::MSVehicle(), MSRouteHandler::myEndElement(), MSE2Collector::notifyEnter(), MSE2Collector::notifyMove(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), MSBaseVehicle::saveState(), MSMeanData::MeanDataValues::vehicleApplies(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSInstantInductLoop::write(), MSAmitranTrajectories::writeVehicle(), and MSFullExport::writeVehicles().
std::string MSVehicleType::getImgFile () const inline
Get this vehicle type's raster model file name.
Returns
The raster file name of this vehicle type
Definition at line 277 of file MSVehicleType.h.
References SUMOVTypeParameter::imgFile, and myParameter.
Referenced by GUIContainer::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsImage(), and GUIBaseVehicle::drawAction_drawVehicleAsImage().
SUMOReal MSVehicleType::getImpatience () const inline
Returns this type's impatience.
Returns
The impatience of this type
Definition at line 234 of file MSVehicleType.h.
References SUMOVTypeParameter::impatience, and myParameter.
Referenced by MSPModel_Striping::PState::getImpatience(), and setImpatience().
LaneChangeModel MSVehicleType::getLaneChangeModel () const inline
Definition at line 162 of file MSVehicleType.h.
References SUMOVTypeParameter::lcModel, and myParameter.
Referenced by MSVehicle::MSVehicle().
SUMOReal MSVehicleType::getLength () const inline
Get vehicle's length [m].
Returns
The length vehicles of this type have in m
Definition at line 118 of file MSVehicleType.h.
References SUMOVTypeParameter::length, and myParameter.
Referenced by MSCFModel_Wiedemann::_v(), MSVehicle::addStop(), MSStoppingPlace::addTransportable(), MSLane::basePos(), MSVehicle::checkRewindLinkLanes(), MSInductLoop::collectVehiclesOnDet(), MSE2Collector::detectorUpdate(), GUIContainer::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsImage(), GUIVehicle::drawAction_drawLinkItems(), GUIVehicle::drawAction_drawRailCarriages(), GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus(), GUIBaseVehicle::drawAction_drawVehicleAsImage(), GUIBaseVehicle::drawAction_drawVehicleAsPoly(), GUIBaseVehicle::drawAction_drawVehicleAsTrianglePlus(), GUIBaseVehicle::drawOnPos(), MSLane::enteredByLaneChange(), MSVehicle::enterLaneAtInsertion(), MSVehicle::enterLaneAtLaneChange(), MSVehicle::executeMove(), MSLane::executeMovements(), MSLane::freeInsertion(), MSVehicle::getBackPosition(), MEVehicle::getBackPositionOnLane(), MSVehicle::getBackPositionOnLane(), MSLane::getBruttoOccupancy(), GUIBaseVehicle::getCenteringBoundary(), MSLane::getCriticalLeader(), MSLane::getFollower(), MSLane::getLeaderOnConsecutive(), MSLane::getLeadersOnConsecutive(), MSPModel_Striping::PState::getLength(), MSLane::getNettoOccupancy(), MSLane::getOppositeFollower(), MSLane::getOppositeLeader(), GUIPerson::getParameterWindow(), MSVehicle::getPositionOnLane(), MSLaneChanger::getRealFollower(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), TraCIServerAPI_VehicleType::getVariable(), MSLink::getZipperSpeed(), MSLane::incorporateVehicle(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSLane::integrateNewVehicle(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSInductLoop::leaveDetectorByMove(), MSLane::leftByLaneChange(), MSVehicleType(), MSInductLoop::notifyEnter(), MSE2Collector::notifyEnter(), MSE2Collector::notifyLeave(), MSInstantInductLoop::notifyMove(), MSMeanData::MeanDataValues::notifyMove(), MSInductLoop::notifyMove(), MSE2Collector::notifyMove(), MSMeanData_Net::MSLaneMeanDataValues::notifyMoveInternal(), MSVehicle::planMoveInternal(), MSVehicle::processNextStop(), MSStoppingPlace::removeTransportable(), MSLane::removeVehicle(), GUIVehicle::selectBlockingFoes(), MSLink::setApproaching(), setLength(), MSVehicle::setTentativeLaneAndPosition(), MSVehicle::unsafeLinkAhead(), MSVehicle::updateFurtherLanes(), MSInstantInductLoop::write(), and MSQueueExport::writeLane().
SUMOReal MSVehicleType::getLengthWithGap () const inline
Get vehicle's length including the minimum gap [m].
Returns
The length vehicles of this type have (including the minimum gap in m
Definition at line 126 of file MSVehicleType.h.
References SUMOVTypeParameter::length, SUMOVTypeParameter::minGap, and myParameter.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), MSLCM_SL2015::_wantsChangeSublane(), MSLaneChanger::change(), MSLaneChanger::changeOpposite(), MSVehicle::checkRewindLinkLanes(), MSLaneChanger::computeOvertakingTime(), MSLaneChanger::continueChange(), GUIEdge::drawMesoVehicles(), MSLane::enteredByLaneChange(), MSLane::executeMovements(), MSE2Collector::getEstimatedCurrentVehicleNumber(), MSE2Collector::getEstimateQueueLength(), MESegment::hasSpaceFor(), MSLane::incorporateVehicle(), MSLCM_JE2013::informFollower(), MSLCM_LC2013::informFollower(), MSLCM_SL2015::informFollower(), MSLCM_JE2013::informLeader(), MSLCM_LC2013::informLeader(), MSLCM_SL2015::informLeader(), MSEdge::insertVehicle(), MSLane::integrateNewVehicle(), MESegment::isOpen(), MSLane::leftByLaneChange(), MESegment::loadState(), MSVehicle::overlap(), MESegment::receive(), MSLaneChanger::registerUnchanged(), METriggeredCalibrator::remainingVehicleCapacity(), MSCalibrator::remainingVehicleCapacity(), MESegment::removeCar(), MSLane::removeVehicle(), MSLCM_JE2013::saveBlockerLength(), MSLCM_LC2013::saveBlockerLength(), MSLCM_SL2015::saveBlockerLength(), MESegment::send(), MSLaneChanger::startChange(), MSLaneChangerSublane::startChangeSublane(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
SUMOTime MSVehicleType::getLoadingDuration () const inline
Get this vehicle type's loading duration.
Returns
The time a container needs to get laoded on a vehicle of this type
Definition at line 307 of file MSVehicleType.h.
References SUMOVTypeParameter::loadingDuration, and myParameter.
Referenced by MSTransportableControl::loadAnyWaiting().
SUMOReal MSVehicleType::getMaxSpeed () const inline
Get vehicle's maximum speed [m/s].
Returns
The maximum speed (in m/s) of vehicles of this class
Definition at line 170 of file MSVehicleType.h.
References computeChosenSpeedDeviation(), SUMOVTypeParameter::maxSpeed, myParameter, and SUMOReal.
Referenced by MSLCM_JE2013::_wantsChange(), MSLCM_LC2013::_wantsChange(), GUIApplicationWindow::checkGamingEvents(), MSBaseVehicle::getMaxSpeed(), GUIPerson::getParameterWindow(), TraCIServerAPI_VehicleType::getVariable(), MSCFModel_KraussPS::maxNextSpeed(), MSCFModel::maxNextSpeed(), MEVehicle::MEVehicle(), MSVehicle::MSVehicle(), MSVehicleType(), MSRouteHandler::myStartElement(), setMaxSpeed(), MSLCM_DK2008::wantsChangeToLeft(), MSLCM_DK2008::wantsChangeToRight(), and MSMeanData_Emissions::MSLaneMeanDataValues::write().
SUMOReal MSVehicleType::getMaxSpeedLat () const inline
Get vehicle's maximum lateral speed [m/s].
Returns
The maximum lateral speed (in m/s) of vehicles of this class
Definition at line 314 of file MSVehicleType.h.
References SUMOVTypeParameter::maxSpeedLat, and myParameter.
Referenced by MSLCM_SL2015::checkBlocking(), and MSLCM_SL2015::keepLatGap().
SUMOReal MSVehicleType::getMinGap () const inline
Get the free space in front of vehicles of this class.
Returns
The place before the vehicle
Definition at line 134 of file MSVehicleType.h.
References SUMOVTypeParameter::minGap, and myParameter.
Referenced by MSLCM_JE2013::_patchSpeed(), MSLCM_SL2015::_patchSpeed(), MSLCM_LC2013::_patchSpeed(), MSCFModel_IDM::_v(), MSVehicle::adaptToLeaders(), MSLaneChanger::checkChange(), MSLane::checkFailure(), MSVehicle::checkRewindLinkLanes(), MSLaneChanger::computeOvertakingTime(), MSLane::detectCollisionBetween(), GUIBaseVehicle::drawOnPos(), MSLane::freeInsertion(), MSLane::getCriticalLeader(), MSLane::getFollowersOnConsecutive(), MSStoppingPlace::getLastFreePos(), MSLane::getLeader(), MSVehicle::getLeader(), MSLane::getLeaderOnConsecutive(), MSLaneChangerSublane::getLeaders(), MSLane::getLeadersOnConsecutive(), MSPModel_Striping::PState::getMinGap(), MSLane::getOppositeLeader(), GUIPerson::getParameterWindow(), MSLaneChanger::getRealLeader(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), TraCIServerAPI_VehicleType::getVariable(), MSLink::getZipperSpeed(), MSLane::isInsertionSuccess(), MSLane::lastInsertion(), MSLCM_DK2008::patchSpeed(), MSVehicle::processNextStop(), MSLane::safeInsertionSpeed(), GUIVehicle::selectBlockingFoes(), setMinGap(), MSLCM_JE2013::slowDownForBlocked(), MSLCM_LC2013::slowDownForBlocked(), MSLCM_SL2015::slowDownForBlocked(), MSLCM_SL2015::updateExpectedSublaneSpeeds(), MSLCM_DK2008::wantsChangeToLeft(), and MSLCM_DK2008::wantsChangeToRight().
SUMOReal MSVehicleType::getMinGapLat () const inline
Get the minimum lateral gap that vehicles of this type maintain.
Returns
The place before the vehicle
Definition at line 141 of file MSVehicleType.h.
References SUMOVTypeParameter::minGapLat, and myParameter.
Referenced by MSLCM_SL2015::updateGaps().
int MSVehicleType::getNumericalID () const inline
Returns the running index of the vehicle type.
Returns
This type's numerical id
Definition at line 110 of file MSVehicleType.h.
References myIndex.
Referenced by MSAmitranTrajectories::writeVehicle().
std::string MSVehicleType::getOSGFile () const inline
Get this vehicle type's 3D model file name.
Returns
The model file name of this vehicle type
Definition at line 269 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::osgFile.
const SUMOVTypeParameter& MSVehicleType::getParameter () const inline
Definition at line 460 of file MSVehicleType.h.
References myParameter.
Referenced by MSDevice_Battery::buildVehicleDevices(), MSDevice_Example::buildVehicleDevices(), MSDevice::equippedByDefaultAssignmentOptions(), GUIPerson::getParameterWindow(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), MSBaseVehicle::getVClass(), TraCIServerAPI_VehicleType::processGet(), and TraCIServerAPI_VehicleType::setVariable().
int MSVehicleType::getPersonCapacity () const inline
Get this vehicle type's person capacity.
Returns
The person capacity of this vehicle type
Definition at line 285 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::personCapacity.
Referenced by MSTransportableControl::boardAnyWaiting(), GUIMEVehicle::getTypeParameterWindow(), and GUIVehicle::getTypeParameterWindow().
LateralAlignment MSVehicleType::getPreferredLateralAlignment () const inline
Get vehicle's preferred lateral alignment.
Returns
The vehicle's preferred lateral alignment
Definition at line 321 of file MSVehicleType.h.
References build(), SUMOVTypeParameter::latAlignment, myParameter, setColor(), setDefaultProbability(), setEmissionClass(), setImpatience(), setLength(), setMaxSpeed(), setMinGap(), setShape(), setSpeedDeviation(), setSpeedFactor(), setVClass(), setWidth(), and SUMOReal.
Referenced by MSLCM_SL2015::_wantsChangeSublane().
SUMOReal MSVehicleType::getSpeedDeviation () const inline
Returns this type's speed deviation.
Returns
The speed deviation of this type
Definition at line 226 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::speedDev.
Referenced by TraCIServerAPI_VehicleType::getVariable(), MSEdge::insertVehicle(), and setSpeedDeviation().
SUMOReal MSVehicleType::getSpeedFactor () const inline
Returns this type's speed factor.
Returns
The speed factor of this type
Definition at line 218 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::speedFactor.
Referenced by TraCIServerAPI_VehicleType::getVariable(), MSEdge::insertVehicle(), and setSpeedFactor().
SUMOVehicleClass MSVehicleType::getVehicleClass () const inline
Get this vehicle type's vehicle class.
Returns
The class of this vehicle type
See also
SUMOVehicleClass
Definition at line 193 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::vehicleClass.
Referenced by MSVehicle::addStop(), MSBaseVehicle::calculateArrivalParams(), MSVehicleTransfer::checkInsertions(), MSVehicle::executeMove(), MSEdge::getDepartLane(), GUIMEVehicle::getTypeParameterWindow(), GUIVehicle::getTypeParameterWindow(), TraCIServerAPI_VehicleType::getVariable(), MSBaseVehicle::hasValidRoute(), MEVehicle::MEVehicle(), MSVehicle::MSVehicle(), MSEdge::prohibits(), MSLane::succLinkSec(), MSVehicle::updateBestLanes(), and MSLCM_SL2015::updateExpectedSublaneSpeeds().
SUMOReal MSVehicleType::getWidth () const inline
Get the width which vehicles of this class shall have when being drawn.
Returns
The width of this type's vehicles
Definition at line 247 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::width.
Referenced by MSLCM_SL2015::_wantsChangeSublane(), MSLCM_SL2015::checkBlocking(), MSLCM_SL2015::checkBlockingVehicles(), MSLane::detectCollisionBetween(), GUIContainer::drawAction_drawAsImage(), GUIPerson::drawAction_drawAsImage(), GUIVehicle::drawAction_drawRailCarriages(), GUIBaseVehicle::drawAction_drawVehicleAsBoxPlus(), GUIBaseVehicle::drawAction_drawVehicleAsImage(), GUIBaseVehicle::drawAction_drawVehicleAsPoly(), GUIBaseVehicle::drawAction_drawVehicleAsTrianglePlus(), MSVehicle::getBoundingBox(), MSVehicle::getBoundingPoly(), MSPModel_Striping::getNextLaneObstacles(), MSVehicle::getRightSideOnEdge(), MSVehicle::getRightSideOnLane(), MSLeaderInfo::getSubLanes(), GUIVehicle::getTypeParameterWindow(), TraCIServerAPI_VehicleType::getVariable(), MSLane::insertVehicle(), MSLCM_SL2015::keepLatGap(), MSPModel_Striping::PState::otherStripe(), MSVehicle::Influencer::postProcessVTD(), TraCIServerAPI_Vehicle::processSet(), setWidth(), and MSLCM_SL2015::updateGaps().
MSVehicleType& MSVehicleType::operator= (const MSVehicleType &) private
Invalidated assignment operator.
void MSVehicleType::setColor (const RGBColor & color)
Set a new value for this type's color.
Parameters
[in] color The new color of this type
Definition at line 164 of file MSVehicleType.cpp.
References SUMOVTypeParameter::color, and myParameter.
Referenced by getPreferredLateralAlignment(), and TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setDefaultProbability (const SUMOReal & prob)
Set a new value for this type's default probability.
If the given value<0 then the one from the original type will be used.
Parameters
[in] prob The new default probability of this type
Definition at line 128 of file MSVehicleType.cpp.
References SUMOVTypeParameter::defaultProbability, getDefaultProbability(), myOriginalType, and myParameter.
Referenced by getPreferredLateralAlignment().
void MSVehicleType::setEmissionClass (SUMOEmissionClass eclass)
Set a new value for this type's emission class.
Parameters
[in] eclass The new emission class of this type
Definition at line 158 of file MSVehicleType.cpp.
References SUMOVTypeParameter::emissionClass, and myParameter.
Referenced by getPreferredLateralAlignment(), and TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setImpatience (const SUMOReal impatience)
Set a new value for this type's impatience.
Parameters
[in] impatience The new impatience of this type
Definition at line 180 of file MSVehicleType.cpp.
References getImpatience(), SUMOVTypeParameter::impatience, myOriginalType, and myParameter.
Referenced by getPreferredLateralAlignment().
void MSVehicleType::setLength (const SUMOReal & length)
Set a new value for this type's length.
If the given value<0 then the one from the original type will be used.
Parameters
[in] length The new length of this type
Definition at line 92 of file MSVehicleType.cpp.
References getLength(), SUMOVTypeParameter::length, myOriginalType, and myParameter.
Referenced by getPreferredLateralAlignment(), and TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setMaxSpeed (const SUMOReal & maxSpeed)
Set a new value for this type's maximum speed.
If the given value<0 then the one from the original type will be used.
Parameters
[in] maxSpeed The new maximum speed of this type
Definition at line 112 of file MSVehicleType.cpp.
References getMaxSpeed(), SUMOVTypeParameter::maxSpeed, myOriginalType, and myParameter.
Referenced by getPreferredLateralAlignment(), and TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setMinGap (const SUMOReal & minGap)
Set a new value for this type's minimum gap.
If the given value<0 then the one from the original type will be used.
Parameters
[in] minGap The new minimum gap of this type
Definition at line 102 of file MSVehicleType.cpp.
References getMinGap(), SUMOVTypeParameter::minGap, myOriginalType, and myParameter.
Referenced by getPreferredLateralAlignment(), and TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setShape (SUMOVehicleShape shape)
Set a new value for this type's shape.
Parameters
[in] shape The new shape of this type
Definition at line 190 of file MSVehicleType.cpp.
References myParameter, and SUMOVTypeParameter::shape.
Referenced by getPreferredLateralAlignment(), and TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setSpeedDeviation (const SUMOReal & dev)
Set a new value for this type's speed deviation.
If the given value<0 then the one from the original type will be used.
Parameters
[in] dev The new speed deviation of this type
Definition at line 148 of file MSVehicleType.cpp.
References getSpeedDeviation(), myOriginalType, myParameter, and SUMOVTypeParameter::speedDev.
Referenced by getPreferredLateralAlignment(), and TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setSpeedFactor (const SUMOReal & factor)
Set a new value for this type's speed factor.
If the given value<0 then the one from the original type will be used.
Parameters
[in] factor The new speed factor of this type
Definition at line 138 of file MSVehicleType.cpp.
References getSpeedFactor(), myOriginalType, myParameter, and SUMOVTypeParameter::speedFactor.
Referenced by getPreferredLateralAlignment(), and TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setVClass (SUMOVehicleClass vclass)
Set a new value for this type's vehicle class.
Parameters
[in] vclass The new vehicle class of this type
Definition at line 122 of file MSVehicleType.cpp.
References myParameter, and SUMOVTypeParameter::vehicleClass.
Referenced by getPreferredLateralAlignment(), and TraCIServerAPI_VehicleType::setVariable().
void MSVehicleType::setWidth (const SUMOReal & width)
Set a new value for this type's width.
If the given value<0 then the one from the original type will be used.
Parameters
[in] width The new width of this type
Definition at line 170 of file MSVehicleType.cpp.
References getWidth(), myOriginalType, myParameter, and SUMOVTypeParameter::width.
Referenced by getPreferredLateralAlignment(), and TraCIServerAPI_VehicleType::setVariable().
bool MSVehicleType::wasSet (int what) const inline
Returns whether the given parameter was set.
Parameters
[in] what The parameter which one asks for
Returns
Whether the given parameter was set
Definition at line 91 of file MSVehicleType.h.
References myParameter, and SUMOVTypeParameter::setParameter.
Referenced by MSRouteHandler::myStartElement(), and GUIBaseVehicle::setFunctionalColor().
Field Documentation
MSCFModel* MSVehicleType::myCarFollowModel private
instance of the car following model.
Definition at line 473 of file MSVehicleType.h.
Referenced by build(), getCarFollowModel(), and ~MSVehicleType().
const int MSVehicleType::myIndex private
the running index
Definition at line 470 of file MSVehicleType.h.
Referenced by getNumericalID().
int MSVehicleType::myNextIndex = 0 static private
next value for the running index
Definition at line 479 of file MSVehicleType.h.
const MSVehicleType* MSVehicleType::myOriginalType private
The original type.
Definition at line 476 of file MSVehicleType.h.
Referenced by amVehicleSpecific(), build(), setDefaultProbability(), setImpatience(), setLength(), setMaxSpeed(), setMinGap(), setSpeedDeviation(), setSpeedFactor(), and setWidth().
SUMOVTypeParameter MSVehicleType::myParameter private
the parameter container
Definition at line 467 of file MSVehicleType.h.
Referenced by build(), computeChosenSpeedDeviation(), getBoardingDuration(), getColor(), getContainerCapacity(), getDefaultProbability(), getEmissionClass(), getGuiShape(), getHeight(), getID(), getImgFile(), getImpatience(), getLaneChangeModel(), getLength(), getLengthWithGap(), getLoadingDuration(), getMaxSpeed(), getMaxSpeedLat(), getMinGap(), getMinGapLat(), getOSGFile(), getParameter(), getPersonCapacity(), getPreferredLateralAlignment(), getSpeedDeviation(), getSpeedFactor(), getVehicleClass(), getWidth(), setColor(), setDefaultProbability(), setEmissionClass(), setImpatience(), setLength(), setMaxSpeed(), setMinGap(), setShape(), setSpeedDeviation(), setSpeedFactor(), setVClass(), setWidth(), and wasSet().
The documentation for this class was generated from the following files:
MSVehicleType.h
MSVehicleType.cpp