SUMO - Simulation of Urban MObility: MSTransportable::Stage Class Reference
MSTransportable::Stage Class Reference abstract
#include <MSTransportable.h>
Public Member Functions
virtual void beginEventOutput (const MSTransportable &transportable, SUMOTime t, OutputDevice &os) const =0
Called for writing the events output (begin of an action)
virtual void endEventOutput (const MSTransportable &transportable, SUMOTime t, OutputDevice &os) const =0
Called for writing the events output (end of an action)
virtual SUMOReal getAngle (SUMOTime now) const =0
returns the angle of the transportable
SUMOReal getArrivalPos () const
const MSEdge & getDestination () const
returns the destination edge
const MSStoppingPlace * getDestinationStop () const
returns the destination stop (if any)
virtual const MSEdge * getEdge () const =0
Returns the current edge.
SUMOReal getEdgeAngle (const MSEdge *e, SUMOReal at) const
get angle of the edge at a certain position
virtual SUMOReal getEdgePos (SUMOTime now) const =0
Position getEdgePosition (const MSEdge *e, SUMOReal at, SUMOReal offset) const
get position on edge e at length at with orthogonal offset
virtual const MSEdge * getFromEdge () const =0
Position getLanePosition (const MSLane *lane, SUMOReal at, SUMOReal offset) const
get position on lane at length at with orthogonal offset
virtual Position getPosition (SUMOTime now) const =0
returns the position of the transportable
virtual SUMOReal getSpeed () const =0
the speed of the transportable
virtual std::string getStageDescription () const =0
return string representation of the current stage
StageType getStageType () const
virtual SUMOVehicle * getVehicle () const
Whether the transportable waits for a vehicle.
virtual SUMOTime getWaitingTime (SUMOTime now) const =0
the time this transportable spent waiting
virtual bool isWaiting4Vehicle () const
Whether the transportable waits for a vehicle.
virtual bool isWaitingFor (const std::string &line) const
Whether the transportable waits for a vehicle of the line specified.
virtual void proceed (MSNet *net, MSTransportable *transportable, SUMOTime now, Stage *previous)=0
proceeds to the next step
virtual void routeOutput (OutputDevice &os) const =0
Called on writing vehroute output.
void setArrived (SUMOTime now)
logs end of the step
void setDeparted (SUMOTime now)
logs end of the step
Stage (const MSEdge &destination, MSStoppingPlace *toStop, const SUMOReal arrivalPos, StageType type)
constructor
virtual void tripInfoOutput (OutputDevice &os) const =0
Called on writing tripinfo output.
virtual ~Stage ()
destructor
Protected Attributes
SUMOReal myArrivalPos
the position at which we want to arrive
SUMOTime myArrived
the time at which this stage ended
SUMOTime myDeparted
the time at which this stage started
const MSEdge & myDestination
the next edge to reach by getting transported
MSStoppingPlace *const myDestinationStop
the stop to reach by getting transported (if any)
StageType myType
The type of this stage.
Private Member Functions
Stage & operator= (const Stage &)
Invalidated assignment operator.
Stage (const Stage &)
Invalidated copy constructor.
Detailed Description
The "abstract" class for a single stage of a movement Contains the destination of the current movement step
Definition at line 71 of file MSTransportable.h.
Constructor & Destructor Documentation
MSTransportable::Stage::Stage (const MSEdge & destination, MSStoppingPlace * toStop, const SUMOReal arrivalPos, StageType type)
constructor
Definition at line 57 of file MSTransportable.cpp.
MSTransportable::Stage::~Stage () virtual
destructor
Definition at line 60 of file MSTransportable.cpp.
MSTransportable::Stage::Stage (const Stage &) private
Invalidated copy constructor.
Member Function Documentation
virtual void MSTransportable::Stage::beginEventOutput (const MSTransportable & transportable, SUMOTime t, OutputDevice & os) const pure virtual
Called for writing the events output (begin of an action)
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by MSTransportable::Stage_Waiting::getStageDescription(), getVehicle(), and MSTransportable::Stage_Driving::setVehicle().
virtual void MSTransportable::Stage::endEventOutput (const MSTransportable & transportable, SUMOTime t, OutputDevice & os) const pure virtual
Called for writing the events output (end of an action)
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by MSTransportable::Stage_Waiting::getStageDescription(), getVehicle(), and MSTransportable::Stage_Driving::setVehicle().
virtual SUMOReal MSTransportable::Stage::getAngle (SUMOTime now) const pure virtual
returns the angle of the transportable
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by getArrivalPos(), and MSTransportable::getFromEdge().
SUMOReal MSTransportable::Stage::getArrivalPos () const inline
Definition at line 87 of file MSTransportable.h.
References getAngle(), getEdge(), getEdgePos(), getFromEdge(), getPosition(), myArrivalPos, and SUMOReal.
const MSEdge & MSTransportable::Stage::getDestination () const
returns the destination edge
Definition at line 63 of file MSTransportable.cpp.
References myDestination.
Referenced by MSPModel_Striping::moveInDirectionOnLane(), MSContainer::MSContainerStage_Driving::routeOutput(), MSTransportable::Stage_Waiting::routeOutput(), and MSPerson::MSPersonStage_Driving::routeOutput().
const MSStoppingPlace* MSTransportable::Stage::getDestinationStop () const inline
returns the destination stop (if any)
Definition at line 83 of file MSTransportable.h.
References myDestinationStop.
Referenced by MSPModel_Striping::moveInDirectionOnLane(), MSContainer::MSContainerStage_Driving::proceed(), and MSPerson::MSPersonStage_Driving::proceed().
virtual const MSEdge* MSTransportable::Stage::getEdge () const pure virtual
Returns the current edge.
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by getArrivalPos(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Walking::proceed(), MSContainer::MSContainerStage_Tranship::proceed(), MSPerson::MSPersonStage_Driving::proceed(), MSTransportable::Stage_Waiting::proceed(), MSContainer::proceed(), and MSPerson::proceed().
SUMOReal MSTransportable::Stage::getEdgeAngle (const MSEdge * e, SUMOReal at) const
get angle of the edge at a certain position
Definition at line 96 of file MSTransportable.cpp.
References MSEdge::getLanes().
Referenced by MSPModel_NonInteracting::PState::getAngle(), CState::getAngle(), MSTransportable::Stage_Waiting::getAngle(), MSTransportable::Stage_Driving::getAngle(), and getVehicle().
virtual SUMOReal MSTransportable::Stage::getEdgePos (SUMOTime now) const pure virtual
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by getArrivalPos(), MSTransportable::getFromEdge(), MSEdge::transportable_by_position_sorter::operator()(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Walking::proceed(), MSContainer::MSContainerStage_Tranship::proceed(), and MSPerson::MSPersonStage_Driving::proceed().
Position MSTransportable::Stage::getEdgePosition (const MSEdge * e, SUMOReal at, SUMOReal offset) const
get position on edge e at length at with orthogonal offset
Definition at line 86 of file MSTransportable.cpp.
References getLanePosition(), and MSEdge::getLanes().
Referenced by MSTransportable::Stage_Waiting::getPosition(), MSTransportable::Stage_Driving::getPosition(), and getVehicle().
virtual const MSEdge* MSTransportable::Stage::getFromEdge () const pure virtual
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by getArrivalPos().
Position MSTransportable::Stage::getLanePosition (const MSLane * lane, SUMOReal at, SUMOReal offset) const
get position on lane at length at with orthogonal offset
Definition at line 91 of file MSTransportable.cpp.
References MSLane::getShape(), MSLane::interpolateLanePosToGeometryPos(), PositionVector::positionAtOffset(), and SUMOReal.
Referenced by CState::computeTranshipTime(), getEdgePosition(), MSPModel_NonInteracting::PState::getPosition(), MSPModel_Striping::PState::getPosition(), and getVehicle().
virtual Position MSTransportable::Stage::getPosition (SUMOTime now) const pure virtual
returns the position of the transportable
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by getArrivalPos(), and MSTransportable::getFromEdge().
virtual SUMOReal MSTransportable::Stage::getSpeed () const pure virtual
the speed of the transportable
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by MSTransportable::getFromEdge(), getVehicle(), and MSTransportable::Stage_Driving::getVehicle().
virtual std::string MSTransportable::Stage::getStageDescription () const pure virtual
return string representation of the current stage
Implemented in MSPerson::MSPersonStage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, MSPerson::MSPersonStage_Walking, and MSContainer::MSContainerStage_Driving.
Referenced by getStageType().
StageType MSTransportable::Stage::getStageType () const inline
Definition at line 103 of file MSTransportable.h.
References getStageDescription(), isWaitingFor(), myType, proceed(), setArrived(), and setDeparted().
virtual SUMOVehicle* MSTransportable::Stage::getVehicle () const inline virtual
Whether the transportable waits for a vehicle.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 128 of file MSTransportable.h.
References beginEventOutput(), endEventOutput(), getEdgeAngle(), getEdgePosition(), getLanePosition(), getSpeed(), getWaitingTime(), routeOutput(), SUMOReal, and tripInfoOutput().
virtual SUMOTime MSTransportable::Stage::getWaitingTime (SUMOTime now) const pure virtual
the time this transportable spent waiting
Implemented in MSTransportable::Stage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, and MSPerson::MSPersonStage_Walking.
Referenced by getVehicle(), and MSTransportable::Stage_Driving::getVehicle().
virtual bool MSTransportable::Stage::isWaiting4Vehicle () const inline virtual
Whether the transportable waits for a vehicle.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 123 of file MSTransportable.h.
bool MSTransportable::Stage::isWaitingFor (const std::string & line) const virtual
Whether the transportable waits for a vehicle of the line specified.
Reimplemented in MSTransportable::Stage_Driving.
Definition at line 81 of file MSTransportable.cpp.
Referenced by getStageType().
Stage& MSTransportable::Stage::operator= (const Stage &) private
Invalidated assignment operator.
virtual void MSTransportable::Stage::proceed (MSNet * net, MSTransportable * transportable, SUMOTime now, Stage * previous) pure virtual
proceeds to the next step
Implemented in MSTransportable::Stage_Waiting, MSPerson::MSPersonStage_Driving, MSContainer::MSContainerStage_Tranship, MSPerson::MSPersonStage_Walking, and MSContainer::MSContainerStage_Driving.
Referenced by MSTransportable::Stage_Waiting::getStageDescription(), and getStageType().
virtual void MSTransportable::Stage::routeOutput (OutputDevice & os) const pure virtual
Called on writing vehroute output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implemented in MSPerson::MSPersonStage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, MSPerson::MSPersonStage_Walking, and MSContainer::MSContainerStage_Driving.
Referenced by MSTransportable::getCurrentStage(), MSTransportable::Stage_Waiting::getStageDescription(), and getVehicle().
void MSTransportable::Stage::setArrived (SUMOTime now)
logs end of the step
Definition at line 76 of file MSTransportable.cpp.
References myArrived.
Referenced by getStageType(), MSContainer::proceed(), and MSPerson::proceed().
void MSTransportable::Stage::setDeparted (SUMOTime now)
logs end of the step
Definition at line 69 of file MSTransportable.cpp.
References myDeparted.
Referenced by getStageType(), and MSTransportable::getVehicleType().
virtual void MSTransportable::Stage::tripInfoOutput (OutputDevice & os) const pure virtual
Called on writing tripinfo output.
Parameters
[in] os The stream to write the information into
Exceptions
IOError not yet implemented
Implemented in MSPerson::MSPersonStage_Driving, MSTransportable::Stage_Waiting, MSContainer::MSContainerStage_Tranship, MSPerson::MSPersonStage_Walking, and MSContainer::MSContainerStage_Driving.
Referenced by MSTransportable::getCurrentStage(), MSTransportable::Stage_Waiting::getStageDescription(), and getVehicle().
Field Documentation
SUMOReal MSTransportable::Stage::myArrivalPos protected
the position at which we want to arrive
Definition at line 179 of file MSTransportable.h.
Referenced by MSPerson::MSPersonStage_Walking::computeAverageSpeed(), MSTransportable::Stage_Waiting::getAngle(), getArrivalPos(), MSPerson::MSPersonStage_Walking::getArrivalPos(), MSContainer::MSContainerStage_Tranship::getArrivalPos(), MSTransportable::Stage_Waiting::getEdgePos(), and MSTransportable::Stage_Waiting::getPosition().
SUMOTime MSTransportable::Stage::myArrived protected
the time at which this stage ended
Definition at line 185 of file MSTransportable.h.
Referenced by setArrived(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), MSPerson::MSPersonStage_Walking::tripInfoOutput(), MSContainer::MSContainerStage_Tranship::tripInfoOutput(), MSTransportable::Stage_Waiting::tripInfoOutput(), and MSPerson::MSPersonStage_Driving::tripInfoOutput().
SUMOTime MSTransportable::Stage::myDeparted protected
the time at which this stage started
Definition at line 182 of file MSTransportable.h.
Referenced by setDeparted(), MSContainer::MSContainerStage_Driving::tripInfoOutput(), and MSPerson::MSPersonStage_Driving::tripInfoOutput().
const MSEdge& MSTransportable::Stage::myDestination protected
the next edge to reach by getting transported
Definition at line 173 of file MSTransportable.h.
Referenced by MSTransportable::Stage_Waiting::getAngle(), getDestination(), MSTransportable::Stage_Waiting::getEdge(), MSTransportable::Stage_Waiting::getFromEdge(), and MSTransportable::Stage_Waiting::getPosition().
MSStoppingPlace* const MSTransportable::Stage::myDestinationStop protected
the stop to reach by getting transported (if any)
Definition at line 176 of file MSTransportable.h.
Referenced by getDestinationStop(), MSPerson::MSPersonStage_Walking::moveToNextEdge(), and MSContainer::MSContainerStage_Tranship::moveToNextEdge().
StageType MSTransportable::Stage::myType protected
The type of this stage.
Definition at line 188 of file MSTransportable.h.
Referenced by getStageType(), MSTransportable::Stage_Waiting::routeOutput(), and MSTransportable::Stage_Waiting::tripInfoOutput().
The documentation for this class was generated from the following files:
MSTransportable.h
MSTransportable.cpp