SUMO - Simulation of Urban MObility: AGChild Class Reference
AGChild Class Reference
#include <AGChild.h>
Public Member Functions
AGChild (int age)
bool allocateASchool (std::list< AGSchool > *schools, AGPosition housePos)
virtual bool decide (SUMOReal probability) const
Lets the person make a decision.
virtual int getAge () const
Provides the age of the person.
int getSchoolClosing () const
AGPosition getSchoolLocation () const
int getSchoolOpening () const
bool haveASchool () const
bool leaveSchool ()
void print () const
Puts out a summary of the class properties.
bool setSchool (AGSchool *school)
Protected Attributes
int age
Private Attributes
AGSchool * school
Detailed Description
Definition at line 48 of file AGChild.h.
Constructor & Destructor Documentation
AGChild::AGChild (int age) inline
Definition at line 50 of file AGChild.h.
References allocateASchool(), getSchoolClosing(), getSchoolLocation(), getSchoolOpening(), haveASchool(), leaveSchool(), print(), school, and setSchool().
Member Function Documentation
bool AGChild::allocateASchool (std::list< AGSchool > * schools, AGPosition housePos)
Parameters
schools school vector from City object
housepos Position of the households habitation
Returns
if a school was found corresponding to the child's age.
Definition at line 65 of file AGChild.cpp.
References AGPerson::age, AGPosition::distanceTo(), setSchool(), and SUMOReal.
Referenced by AGChild().
bool AGPerson::decide (SUMOReal probability) const virtual inherited
Lets the person make a decision.
The higher the degree of belief is, the more likely this method returns true.
Parameters
[in] degreeOfBelief how strong the person beliefs the proposition
Returns
whether the person agrees with the proposition
Definition at line 63 of file AGPerson.cpp.
References RandHelper::rand().
Referenced by AGAdult::tryToWork().
int AGPerson::getAge () const virtual inherited
Provides the age of the person.
Returns
the age in years
Definition at line 57 of file AGPerson.cpp.
References AGPerson::age.
int AGChild::getSchoolClosing () const
Definition at line 103 of file AGChild.cpp.
References AGSchool::getClosingHour(), and school.
Referenced by AGChild().
AGPosition AGChild::getSchoolLocation () const
Definition at line 98 of file AGChild.cpp.
References AGSchool::getPosition(), and school.
Referenced by AGChild().
int AGChild::getSchoolOpening () const
Definition at line 108 of file AGChild.cpp.
References AGSchool::getOpeningHour(), and school.
Referenced by AGChild().
bool AGChild::haveASchool () const
Definition at line 93 of file AGChild.cpp.
References school.
Referenced by AGChild().
bool AGChild::leaveSchool ()
Returns
if the child is now without any school
Definition at line 83 of file AGChild.cpp.
References AGSchool::removeChild(), and school.
Referenced by AGChild().
void AGChild::print () const virtual
Puts out a summary of the class properties.
Reimplemented from AGPerson.
Definition at line 48 of file AGChild.cpp.
References AGPerson::age, and school.
Referenced by AGChild().
bool AGChild::setSchool (AGSchool * school)
Definition at line 53 of file AGChild.cpp.
References AGSchool::addNewChild(), and school.
Referenced by AGChild(), and allocateASchool().
Field Documentation
int AGPerson::age protected inherited
Definition at line 72 of file AGPerson.h.
Referenced by allocateASchool(), AGPerson::getAge(), print(), AGAdult::print(), and AGPerson::print().
AGSchool* AGChild::school private
Definition at line 71 of file AGChild.h.
Referenced by AGChild(), getSchoolClosing(), getSchoolLocation(), getSchoolOpening(), haveASchool(), leaveSchool(), print(), and setSchool().
The documentation for this class was generated from the following files:
AGChild.h
AGChild.cpp