SUMO - Simulation of Urban MObility: RGBColor Class Reference
RGBColor Class Reference
#include <RGBColor.h>
Public Member Functions
unsigned char alpha () const
Returns the alpha-amount of the color.
unsigned char blue () const
Returns the blue-amount of the color.
RGBColor changedBrightness (int change, int toChange=3) const
Returns a new color with altered brightness.
unsigned char green () const
Returns the green-amount of the color.
bool operator!= (const RGBColor &c) const
bool operator== (const RGBColor &c) const
unsigned char red () const
Returns the red-amount of the color.
RGBColor ()
Constructor.
RGBColor (unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha=255)
Constructor.
RGBColor (const RGBColor &col)
Copy constructor.
void set (unsigned char r, unsigned char g, unsigned char b, unsigned char a)
assigns new values
~RGBColor ()
Destructor.
Static Public Member Functions
static RGBColor fromHSV (SUMOReal h, SUMOReal s, SUMOReal v)
Converts the given hsv-triplet to rgb.
static RGBColor interpolate (const RGBColor &minColor, const RGBColor &maxColor, SUMOReal weight)
Interpolates between two colors.
static RGBColor parseColor (std::string coldef)
Parses a color information.
static RGBColor parseColorReporting (const std::string &coldef, const std::string &objecttype, const char *objectid, bool report, bool &ok)
Parses a color information.
Static Public Attributes
static const RGBColor BLACK = RGBColor(0, 0, 0, 255)
static const RGBColor BLUE = RGBColor(0, 0, 255, 255)
static const RGBColor CYAN = RGBColor(0, 255, 255, 255)
static const RGBColor DEFAULT_COLOR = RGBColor::YELLOW
The default color (for vehicle types and vehicles)
static const std::string DEFAULT_COLOR_STRING = toString(RGBColor::DEFAULT_COLOR)
The string description of the default color.
static const RGBColor GREEN = RGBColor(0, 255, 0, 255)
static const RGBColor GREY = RGBColor(128, 128, 128, 255)
static const RGBColor MAGENTA = RGBColor(255, 0, 255, 255)
static const RGBColor ORANGE = RGBColor(255, 128, 0, 255)
static const RGBColor RED = RGBColor(255, 0, 0, 255)
static const RGBColor WHITE = RGBColor(255, 255, 255, 255)
static const RGBColor YELLOW = RGBColor(255, 255, 0, 255)
Private Attributes
unsigned char myAlpha
unsigned char myBlue
unsigned char myGreen
unsigned char myRed
The color amounts.
Friends
std::ostream & operator<< (std::ostream &os, const RGBColor &col)
Writes the color to the given stream.
Detailed Description
The definition of a color in the RGB-space with an alpha channel. The cube is meant to lie between (0, 0, 0) and (255, 255, 255)
Definition at line 47 of file RGBColor.h.
Constructor & Destructor Documentation
RGBColor::RGBColor ()
Constructor.
Definition at line 71 of file RGBColor.cpp.
Referenced by fromHSV(), interpolate(), parseColor(), and parseColorReporting().
RGBColor::RGBColor (unsigned char red, unsigned char green, unsigned char blue, unsigned char alpha = 255)
Constructor.
Parameters
[in] red The red component's value
[in] green The green component's value
[in] blue The blue component's value
Definition at line 75 of file RGBColor.cpp.
RGBColor::RGBColor (const RGBColor & col)
Copy constructor.
Definition at line 79 of file RGBColor.cpp.
RGBColor::~RGBColor ()
Destructor.
Definition at line 83 of file RGBColor.cpp.
Member Function Documentation
unsigned char RGBColor::alpha () const inline
Returns the alpha-amount of the color.
Returns
The alpha component's value
Definition at line 99 of file RGBColor.h.
References changedBrightness(), fromHSV(), interpolate(), myAlpha, operator!=(), operator<<, operator==(), parseColor(), parseColorReporting(), and SUMOReal.
Referenced by GUILane::drawAsWaterway(), GUIJunctionWrapper::getColorValue(), MFXUtils::getFXColor(), TraCIServerAPI_VehicleType::getVariable(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::onConfigure(), GUISUMOAbstractView::paintGL(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Vehicle::processSet(), GLHelper::setColor(), and BinaryFormatter::writeAttr().
unsigned char RGBColor::blue () const inline
Returns the blue-amount of the color.
Returns
The blue component's value
Definition at line 91 of file RGBColor.h.
References myBlue.
Referenced by changedBrightness(), GUILane::drawAsWaterway(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GUIParameterTracker::GUIParameterTrackerPanel::drawValue(), GUIJunctionWrapper::getColorValue(), MFXUtils::getFXColor(), TraCIServerAPI_VehicleType::getVariable(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::onConfigure(), GUISUMOAbstractView::paintGL(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Vehicle::processSet(), GLHelper::setColor(), and BinaryFormatter::writeAttr().
RGBColor RGBColor::changedBrightness (int change, int toChange = 3) const
Returns a new color with altered brightness.
Parameters
[in] change The absolute change applied to all channels (within bounds)
[in] change The number of colors to change
Returns
The new color
Definition at line 150 of file RGBColor.cpp.
References blue(), changedBrightness(), green(), MAX2(), MIN2(), myAlpha, myBlue, myGreen, myRed, and red().
Referenced by alpha(), changedBrightness(), GUIPerson::drawAction_drawAsPoly(), GUIVehicle::drawAction_drawRailCarriages(), GUIBaseVehicle::drawAction_drawVehicleAsPoly(), GNEPoly::drawGL(), and GUIPerson::drawGLAdditional().
RGBColor RGBColor::fromHSV (SUMOReal h, SUMOReal s, SUMOReal v) static
Converts the given hsv-triplet to rgb.
Parameters
[in] h Hue (0-360)
[in] s Saturation (0-1)
[in] v Value (0-1)
Returns
The color as RGB
Author
Alvy Ray Smith (http://www.alvyray.com/default.htm)
Definition at line 294 of file RGBColor.cpp.
References RGBColor(), and SUMOReal.
Referenced by alpha(), GLHelper::debugVertices(), GUIEdge::setFunctionalColor(), GUIContainer::setFunctionalColor(), GUIPerson::setFunctionalColor(), GNELane::setFunctionalColor(), GUILane::setFunctionalColor(), and GUIBaseVehicle::setFunctionalColor().
unsigned char RGBColor::green () const inline
Returns the green-amount of the color.
Returns
The green component's value
Definition at line 83 of file RGBColor.h.
References myGreen.
Referenced by changedBrightness(), GUILane::drawAsWaterway(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GUIParameterTracker::GUIParameterTrackerPanel::drawValue(), GUIJunctionWrapper::getColorValue(), MFXUtils::getFXColor(), TraCIServerAPI_VehicleType::getVariable(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::onConfigure(), GUISUMOAbstractView::paintGL(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Vehicle::processSet(), GLHelper::setColor(), and BinaryFormatter::writeAttr().
RGBColor RGBColor::interpolate (const RGBColor & minColor, const RGBColor & maxColor, SUMOReal weight) static
Interpolates between two colors.
The interpolated color is calculated as a weighted average of the RGB values of minColor and maxColor, giving weight to maxColor and 1-weight to minColor.
Parameters
[in] minColor The color to interpolate from
[in] maxColor The color to interpolate to
[in] weight The weight of the first color
Returns
The interpolated color
Definition at line 278 of file RGBColor.cpp.
References myAlpha, myBlue, myGreen, myRed, and RGBColor().
Referenced by alpha(), and GUIPropertyScheme< T >::interpolate().
bool RGBColor::operator!= (const RGBColor & c) const
Definition at line 144 of file RGBColor.cpp.
References myAlpha, myBlue, myGreen, and myRed.
Referenced by alpha().
bool RGBColor::operator== (const RGBColor & c) const
Definition at line 138 of file RGBColor.cpp.
References myAlpha, myBlue, myGreen, and myRed.
Referenced by alpha().
RGBColor RGBColor::parseColor (std::string coldef) static
Parses a color information.
It is assumed that the color is stored as "<RED>,<GREEN>,<BLUE>" and each color is represented as a SUMOReal. Alternatively the color can be stored as "<RED>,<GREEN>,<BLUE>,<ALPHA>" and each color is represented as an unsigned byte.
Parameters
[in] coldef The color definition to parse
Returns
The parsed color
Exceptions
EmptyData If the definition has less than three entries
NumberFormatException If one of the components is not numeric
Definition at line 172 of file RGBColor.cpp.
References TplConvert::_2int(), TplConvert::_2SUMOReal(), TplConvert::_hex2int(), BLACK, BLUE, CYAN, StringTokenizer::getVector(), GREEN, GREY, MAGENTA, ORANGE, RED, RGBColor(), WHITE, and YELLOW.
Referenced by PCTypeMap::add(), NLHandler::addDistrict(), alpha(), SUMOSAXAttributesImpl_Xerces::getColor(), PCLoaderVisum::load(), PCLoaderArcView::load(), PCLoaderDlrNavteq::loadPOIFile(), PCLoaderDlrNavteq::loadPolyFile(), PCLoaderXML::myStartElement(), parseColorReporting(), and PCTypeMap::PCTypeMap().
RGBColor RGBColor::parseColorReporting (const std::string & coldef, const std::string & objecttype, const char * objectid, bool report, bool & ok) static
Parses a color information.
It is assumed that the color is stored as "<RED>,<GREEN>,<BLUE>" and each color is represented as a SUMOReal. Alternatively the color can be stored as "<RED>,<GREEN>,<BLUE>,<ALPHA>" and each color is represented as an unsigned byte.
Parameters
[in] coldef The color definition to parse
[in] objecttype The type of the currently parsed object
[in] objectid The id of the currently parsed object
[in] report Whether errors shall be reported
[in,out] ok Whether parsing was successful
Returns
The parsed color
Exceptions
EmptyData If the definition has less than three entries
NumberFormatException If one of the components is not numeric
Definition at line 252 of file RGBColor.cpp.
References parseColor(), RGBColor(), UNUSED_PARAMETER, and WRITE_ERROR.
Referenced by alpha(), GUISettingsHandler::myStartElement(), and GUISettingsHandler::parseTextSettings().
unsigned char RGBColor::red () const inline
Returns the red-amount of the color.
Returns
The red component's value
Definition at line 75 of file RGBColor.h.
References myRed.
Referenced by changedBrightness(), GUILane::drawAsWaterway(), GNEDetectorExit::drawGL(), GNEDetectorEntry::drawGL(), GUIParameterTracker::GUIParameterTrackerPanel::drawValue(), GUIJunctionWrapper::getColorValue(), MFXUtils::getFXColor(), TraCIServerAPI_VehicleType::getVariable(), GUISUMOAbstractView::makeSnapshot(), GUISUMOAbstractView::onConfigure(), GUISUMOAbstractView::paintGL(), TraCIServerAPI_Polygon::processGet(), TraCIServerAPI_POI::processGet(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Person::processGet(), TraCIServerAPI_Vehicle::processSet(), GLHelper::setColor(), and BinaryFormatter::writeAttr().
void RGBColor::set (unsigned char r, unsigned char g, unsigned char b, unsigned char a)
assigns new values
Parameters
[in] r The red component's value
[in] g The green component's value
[in] b The blue component's value
[in] a The alpha component's value
Definition at line 87 of file RGBColor.cpp.
References myAlpha, myBlue, myGreen, and myRed.
Referenced by TraCIServerAPI_Vehicle::processSet(), and TraCIServer::readTypeCheckingColor().
Friends And Related Function Documentation
std::ostream& operator<< (std::ostream & os, const RGBColor & col) friend
Writes the color to the given stream.
Parameters
[out] os The stream to write to
[in] col The color to write
Returns
The stream
Definition at line 96 of file RGBColor.cpp.
Referenced by alpha().
Field Documentation
const RGBColor RGBColor::BLACK = RGBColor(0, 0, 0, 255) static
Definition at line 197 of file RGBColor.h.
Referenced by GNEViewNet::GNEViewNet(), GUIVisualizationSettings::GUIVisualizationSettings(), NIImporter_Vissim::NIImporter_Vissim(), GUIParam_PopupMenuInterface::onCmdOpenTracker(), parseColor(), and GUISUMOAbstractView::showToolTipFor().
const RGBColor RGBColor::BLUE = RGBColor(0, 0, 255, 255) static
Definition at line 191 of file RGBColor.h.
Referenced by AGActivityTripWriter::AGActivityTripWriter(), GNEViewNet::GNEViewNet(), GUIVisualizationSettings::GUIVisualizationSettings(), parseColor(), RODFDetectorCon::saveAsPOIs(), and NBSign::writeAsPOI().
const RGBColor RGBColor::CYAN = RGBColor(0, 255, 255, 255) static
Definition at line 193 of file RGBColor.h.
Referenced by GNEConnectorFrame::GNEConnectorFrame(), GNEViewNet::GNEViewNet(), GUIVisualizationSettings::GUIVisualizationSettings(), NIImporter_Vissim::NIImporter_Vissim(), and parseColor().
const RGBColor RGBColor::DEFAULT_COLOR = RGBColor::YELLOW static
The default color (for vehicle types and vehicles)
Definition at line 200 of file RGBColor.h.
Referenced by MSRoute::getColor(), SUMOVehicleParserHelper::parseCommonAttributes(), MSBaseVehicle::replaceRouteEdges(), and GUIBaseVehicle::setFunctionalColor().
const std::string RGBColor::DEFAULT_COLOR_STRING = toString(RGBColor::DEFAULT_COLOR) static
The string description of the default color.
Definition at line 204 of file RGBColor.h.
const RGBColor RGBColor::GREEN = RGBColor(0, 255, 0, 255) static
Definition at line 190 of file RGBColor.h.
Referenced by AGActivityTripWriter::AGActivityTripWriter(), GUIBaseVehicle::drawLinkItem(), GNEConnectorFrame::GNEConnectorFrame(), GNEViewNet::GNEViewNet(), GUIVisualizationSettings::GUIVisualizationSettings(), NIImporter_Vissim::NIImporter_Vissim(), GUIApplicationWindow::onCmdGaming(), GNEViewNet::onCmdNodeShape(), parseColor(), and RODFDetectorCon::saveAsPOIs().
const RGBColor RGBColor::GREY = RGBColor(128, 128, 128, 255) static
Definition at line 198 of file RGBColor.h.
Referenced by GUIBaseVehicle::drawAction_drawVehicleAsPoly(), GNEViewNet::GNEViewNet(), GUIVisualizationSettings::GUIVisualizationSettings(), NIImporter_Vissim::NIImporter_Vissim(), parseColor(), and NBSign::writeAsPOI().
const RGBColor RGBColor::MAGENTA = RGBColor(255, 0, 255, 255) static
Definition at line 194 of file RGBColor.h.
Referenced by GNEConnectorFrame::GNEConnectorFrame(), GNEViewNet::GNEViewNet(), GUIVisualizationSettings::GUIVisualizationSettings(), NIImporter_Vissim::NIImporter_Vissim(), and parseColor().
unsigned char RGBColor::myAlpha private
Definition at line 209 of file RGBColor.h.
Referenced by alpha(), changedBrightness(), interpolate(), operator!=(), operator<<(), operator==(), and set().
unsigned char RGBColor::myBlue private
Definition at line 209 of file RGBColor.h.
Referenced by blue(), changedBrightness(), interpolate(), operator!=(), operator<<(), operator==(), and set().
unsigned char RGBColor::myGreen private
Definition at line 209 of file RGBColor.h.
Referenced by changedBrightness(), green(), interpolate(), operator!=(), operator<<(), operator==(), and set().
unsigned char RGBColor::myRed private
The color amounts.
Definition at line 209 of file RGBColor.h.
Referenced by changedBrightness(), interpolate(), operator!=(), operator<<(), operator==(), red(), and set().
const RGBColor RGBColor::ORANGE = RGBColor(255, 128, 0, 255) static
Definition at line 195 of file RGBColor.h.
Referenced by GNEViewNet::GNEViewNet(), GUIVisualizationSettings::GUIVisualizationSettings(), and parseColor().
const RGBColor RGBColor::RED = RGBColor(255, 0, 0, 255) static
Definition at line 189 of file RGBColor.h.
Referenced by AGActivityTripWriter::AGActivityTripWriter(), GNEViewNet::GNEViewNet(), GUIVisualizationSettings::GUIVisualizationSettings(), NIImporter_Vissim::NIImporter_Vissim(), GUIApplicationWindow::onCmdGaming(), parseColor(), RODFDetectorCon::saveAsPOIs(), and NBSign::writeAsPOI().
const RGBColor RGBColor::WHITE = RGBColor(255, 255, 255, 255) static
Definition at line 196 of file RGBColor.h.
Referenced by GUIVisualizationSettings::GUIVisualizationSettings(), NIImporter_Vissim::NIImporter_Vissim(), and parseColor().
const RGBColor RGBColor::YELLOW = RGBColor(255, 255, 0, 255) static
Definition at line 192 of file RGBColor.h.
Referenced by SUMOVehicleParserHelper::beginVTypeParsing(), GNEConnectorFrame::GNEConnectorFrame(), GNEViewNet::GNEViewNet(), GUIVisualizationSettings::GUIVisualizationSettings(), NIImporter_Vissim::NIImporter_Vissim(), parseColor(), and NBSign::writeAsPOI().
The documentation for this class was generated from the following files:
RGBColor.h
RGBColor.cpp