SUMO - Simulation of Urban MObility: MSVehicleControl Class Reference
MSVehicleControl Class Reference
The class responsible for building and deletion of vehicles.
#include <MSVehicleControl.h>
Public Types
typedef std::map< std::string, SUMOVehicle * >::const_iterator constVehIt
Definition of the internal vehicles map iterator.
Public Member Functions
void abortWaiting ()
informes about all waiting vehicles (deletion in destructor)
void addWaiting (const MSEdge *const edge, SUMOVehicle *vehicle)
Adds a vehicle to the list of waiting vehiclse to a given edge.
SUMOTime computeRandomDepartOffset () const
compute (optional) random offset to the departure time
void discountStateLoaded ()
avoid counting a vehicle twice if it was loaded from state and route input
SUMOReal getMaxSpeedFactor () const
return the maximum speed factor for all vehicles that ever entered the network
SUMOReal getMinDeceleration () const
return the minimum deceleration capability for all vehicles that ever entered the network
SUMOVehicle * getWaitingVehicle (const MSEdge *const edge, const std::set< std::string > &lines, const SUMOReal position, const std::string ridingID)
MSVehicleControl ()
Constructor.
void registerCollision ()
registers one collision-related teleport
void registerEmergencyStop ()
register emergency stop
void registerOneWaitingForContainer ()
increases the count of vehicles waiting for a container to allow recogniztion of container related deadlocks
void registerOneWaitingForPerson ()
increases the count of vehicles waiting for a person to allow recogniztion of person related deadlocks
void registerTeleportJam ()
register one non-collision-related teleport
void registerTeleportWrongLane ()
register one non-collision-related teleport
void registerTeleportYield ()
register one non-collision-related teleport
void removeWaiting (const MSEdge *const edge, SUMOVehicle *vehicle)
Removes a vehicle from the list of waiting vehicles to a given edge.
void unregisterOneWaitingForContainer ()
decreases the count of vehicles waiting for a container to allow recogniztion of container related deadlocks
void unregisterOneWaitingForPerson ()
decreases the count of vehicles waiting for a person to allow recogniztion of person related deadlocks
virtual ~MSVehicleControl ()
Destructor.
Vehicle creation
virtual SUMOVehicle * buildVehicle (SUMOVehicleParameter *defs, const MSRoute *route, const MSVehicleType *type, const bool ignoreStopErrors, const bool fromRouteFile=true)
Builds a vehicle, increases the number of built vehicles.
Insertion, deletion and retrieval of vehicles
virtual bool addVehicle (const std::string &id, SUMOVehicle *v)
Tries to insert the vehicle into the internal vehicle container.
SUMOVehicle * getVehicle (const std::string &id) const
Returns the vehicle with the given id.
virtual void deleteVehicle (SUMOVehicle *v, bool discard=false)
Deletes the vehicle.
void scheduleVehicleRemoval (SUMOVehicle *veh)
Removes a vehicle after it has ended.
constVehIt loadedVehBegin () const
Returns the begin of the internal vehicle map.
constVehIt loadedVehEnd () const
Returns the end of the internal vehicle map.
Setting vehicle statistics
void vehicleDeparted (const SUMOVehicle &v)
Informs this control about a vehicle's departure.
Retrieval of vehicle statistics (always accessable)
int getLoadedVehicleNo () const
Returns the number of build vehicles.
int getEndedVehicleNo () const
Returns the number of removed vehicles.
int getRunningVehicleNo () const
Returns the number of build and inserted, but not yet deleted vehicles.
int getDepartedVehicleNo () const
Returns the number of inserted vehicles.
int getQuota (SUMOReal frac=-1) const
Returns the number of instances of the current vehicle that shall be emitted considering that "frac" of all vehicles shall be emitted overall if a negative fraction is given the demand scaling factor is used (–scale)
int getActiveVehicleCount () const
Returns the number of build vehicles that have not been removed or need to wait for a passenger or a container.
int getCollisionCount () const
return the number of collisions
int getTeleportsJam () const
return the number of teleports due to jamming
int getTeleportsYield () const
return the number of teleports due to vehicles stuck on a minor road
int getTeleportsWrongLane () const
return the number of teleports due to vehicles stuck on the wrong lane
int getTeleportCount () const
return the number of teleports (including collisions)
int getEmergencyStops () const
return the number of emergency stops
SUMOReal getTotalDepartureDelay () const
Returns the total departure delay.
SUMOReal getTotalTravelTime () const
Returns the total travel time.
Insertion and retrieval of vehicle types
bool addVType (MSVehicleType *vehType)
Adds a vehicle type.
bool addVTypeDistribution (const std::string &id, RandomDistributor< MSVehicleType * > *vehTypeDistribution)
Adds a vehicle type distribution.
bool hasVTypeDistribution (const std::string &id) const
Asks for a vehicle type distribution.
MSVehicleType * getVType (const std::string &id=DEFAULT_VTYPE_ID, MTRand *rng=0)
Returns the named vehicle type or a sample from the named distribution.
void insertVTypeIDs (std::vector< std::string > &into) const
Inserts ids of all known vehicle types and vehicle type distributions to the given vector.
State I/O
void setState (int runningVehNo, int loadedVehNo, int endedVehNo, SUMOReal totalDepartureDelay, SUMOReal totalTravelTime)
Sets the current state variables as loaded from the stream.
void saveState (OutputDevice &out)
Saves the current state into the given stream.
Protected Attributes
Vehicle statistics (always accessable)
int myLoadedVehNo
The number of build vehicles.
int myRunningVehNo
The number of vehicles within the network (build and inserted but not removed)
int myEndedVehNo
The number of removed vehicles.
int myDiscarded
The number of vehicles which were discarded while loading.
int myCollisions
The number of collisions.
int myTeleportsJam
The number of teleports due to jam.
int myTeleportsYield
The number of teleports due to vehicles stuck on a minor road.
int myTeleportsWrongLane
The number of teleports due to vehicles stuck on the wrong lane.
int myEmergencyStops
The number of emergency stops.
Vehicle statistics
SUMOReal myTotalDepartureDelay
The aggregated time vehicles had to wait for departure (in seconds)
SUMOReal myTotalTravelTime
The aggregated time vehicles needed to aacomplish their route (in seconds)
Private Member Functions
bool checkVType (const std::string &id)
Checks whether the vehicle type (distribution) may be added.
Vehicle container
typedef std::map< std::string, SUMOVehicle * > VehicleDictType
Vehicle dictionary type.
VehicleDictType myVehicleDict
Dictionary of vehicles.
Vehicle type container
typedef std::map< std::string, MSVehicleType * > VTypeDictType
Vehicle type dictionary type.
typedef std::map< std::string, RandomDistributor< MSVehicleType * > * > VTypeDistDictType
Vehicle type distribution dictionary type.
VTypeDictType myVTypeDict
Dictionary of vehicle types.
VTypeDistDictType myVTypeDistDict
A distribution of vehicle types (probability->vehicle type)
bool myDefaultVTypeMayBeDeleted
Whether no vehicle type was loaded.
bool myDefaultPedTypeMayBeDeleted
Whether no pedestrian type was loaded.
std::map< const MSEdge *const, std::vector< SUMOVehicle * > > myWaiting
the lists of waiting vehicles to a given edge
int myWaitingForPerson
the number of vehicles wainting for persons contained in myWaiting which can only continue by being triggered
int myWaitingForContainer
the number of vehicles wainting for containers contained in myWaiting which can only continue by being triggered
SUMOReal myScale
The scaling factor (especially for inc-dua)
SUMOTime myMaxRandomDepartOffset
The maximum random offset to be added to vehicles departure times (non-negative)
SUMOReal myMaxSpeedFactor
The maximum speed factor for all vehicles in the network.
SUMOReal myMinDeceleration
The minimum deceleration capability for all vehicles in the network.
MSVehicleControl (const MSVehicleControl &s)
invalidated copy constructor
MSVehicleControl & operator= (const MSVehicleControl &s)
invalidated assignment operator
Detailed Description
The class responsible for building and deletion of vehicles.
This class is responsible for vehicle building and deletion. It stores vehicle types, vehicles and statistics about the last.
This class also realizes the tripinfos and the vehroutes - outputs, both generated when a vehicle is removed from the simulation, see scheduleVehicleRemoval.
Use this class for the pure microsim and GUIVehicleControl within the gui.
See also
GUIVehicleControl
Definition at line 74 of file MSVehicleControl.h.
Member Typedef Documentation
typedef std::map<std::string, SUMOVehicle*>::const_iterator MSVehicleControl::constVehIt
Definition of the internal vehicles map iterator.
Definition at line 77 of file MSVehicleControl.h.
typedef std::map< std::string, SUMOVehicle* > MSVehicleControl::VehicleDictType protected
Vehicle dictionary type.
Definition at line 508 of file MSVehicleControl.h.
typedef std::map< std::string, MSVehicleType* > MSVehicleControl::VTypeDictType protected
Vehicle type dictionary type.
Definition at line 518 of file MSVehicleControl.h.
typedef std::map< std::string, RandomDistributor<MSVehicleType*>* > MSVehicleControl::VTypeDistDictType protected
Vehicle type distribution dictionary type.
Definition at line 523 of file MSVehicleControl.h.
Constructor & Destructor Documentation
MSVehicleControl::MSVehicleControl ()
Constructor.
Definition at line 55 of file MSVehicleControl.cpp.
References MSVehicleType::build(), DEFAULT_PEDTYPE_ID, DEFAULT_VTYPE_ID, OptionsCont::getFloat(), OptionsCont::getOptions(), OptionsCont::getString(), OptionsCont::isSet(), myMaxRandomDepartOffset, myScale, myVTypeDict, SUMOVTypeParameter::setParameter, string2time(), SVC_PASSENGER, SVC_PEDESTRIAN, and VTYPEPARS_VEHICLECLASS_SET.
MSVehicleControl::~MSVehicleControl () virtual
Destructor.
Definition at line 87 of file MSVehicleControl.cpp.
References myVehicleDict, myVTypeDict, and myVTypeDistDict.
MSVehicleControl::MSVehicleControl (const MSVehicleControl & s) private
invalidated copy constructor
Member Function Documentation
void MSVehicleControl::abortWaiting ()
informes about all waiting vehicles (deletion in destructor)
Definition at line 364 of file MSVehicleControl.cpp.
References myVehicleDict, and WRITE_WARNING.
Referenced by discountStateLoaded(), and MSNet::simulationState().
bool MSVehicleControl::addVehicle (const std::string & id, SUMOVehicle * v) virtual
Tries to insert the vehicle into the internal vehicle container.
Checks whether another vehicle with the same id exists; returns false if so. Otherwise, the vehicle is added to "myVehicleDict" and true is returned.
The vehicle control gets responsible for vehicle deletion.
Parameters
[in] id The id of the vehicle
[in] v The vehicle
Returns
Whether the vehicle could be inserted (no other vehicle with the same id was inserted before)
Reimplemented in GUIVehicleControl, and GUIMEVehicleControl.
Definition at line 193 of file MSVehicleControl.cpp.
References myVehicleDict.
Referenced by GUIMEVehicleControl::addVehicle(), GUIVehicleControl::addVehicle(), MSRouteHandler::closeVehicle(), MSInsertionControl::determineCandidates(), MSCalibrator::execute(), MSStateHandler::myStartElement(), TraCIServerAPI_Vehicle::processSet(), and METriggeredCalibrator::tryEmit().
bool MSVehicleControl::addVType (MSVehicleType * vehType)
Adds a vehicle type.
If another vehicle type (or distribution) with the same id exists, false is returned. Otherwise, the vehicle type is added to the internal vehicle type container "myVTypeDict".
This control get responsible for deletion of the added vehicle type.
Parameters
[in] vehType The vehicle type to add
Returns
Whether the vehicle type could be added
Definition at line 254 of file MSVehicleControl.cpp.
References checkVType(), MSVehicleType::getID(), and myVTypeDict.
Referenced by getTotalTravelTime(), and MSStateHandler::myEndElement().
bool MSVehicleControl::addVTypeDistribution (const std::string & id, RandomDistributor< MSVehicleType * > * vehTypeDistribution)
Adds a vehicle type distribution.
If another vehicle type (or distribution) with the same id exists, false is returned. Otherwise, the vehicle type distribution is added to the internal vehicle type distribution container "myVTypeDistDict".
This control get responsible for deletion of the added vehicle type distribution.
Parameters
[in] id The id of the distribution to add
[in] vehTypeDistribution The vehicle type distribution to add
Returns
Whether the vehicle type could be added
Definition at line 264 of file MSVehicleControl.cpp.
References checkVType(), and myVTypeDistDict.
Referenced by getTotalTravelTime(), and MSStateHandler::myStartElement().
void MSVehicleControl::addWaiting (const MSEdge *const edge, SUMOVehicle * vehicle)
Adds a vehicle to the list of waiting vehiclse to a given edge.
Definition at line 311 of file MSVehicleControl.cpp.
References myWaiting.
Referenced by MSRouteHandler::closeVehicle(), getTotalTravelTime(), and MSVehicle::processNextStop().
SUMOVehicle * MSVehicleControl::buildVehicle (SUMOVehicleParameter * defs, const MSRoute * route, const MSVehicleType * type, const bool ignoreStopErrors, const bool fromRouteFile = true) virtual
Builds a vehicle, increases the number of built vehicles.
Builds a MSVehicle instance using the given parameter. Increases the number of loaded vehicles ("myLoadedVehNo").
Parameters
[in] defs The parameter defining the vehicle
[in] route The route of this vehicle
[in] type The type of this vehicle
[in] ignoreStopErrors whether invalid stops trigger a warning only
[in] fromRouteFile whether we are just reading the route file or creating via trigger, traci, ...
Returns
The built vehicle (MSVehicle instance)
Reimplemented in GUIVehicleControl, GUIMEVehicleControl, and MEVehicleControl.
Definition at line 116 of file MSVehicleControl.cpp.
References MSBaseVehicle::addStops(), MSVehicleType::computeChosenSpeedDeviation(), computeRandomDepartOffset(), SUMOVehicleParameter::depart, MSNet::getInstance(), MSRouteHandler::getParsingRNG(), MSNet::informVehicleStateListener(), myLoadedVehNo, and MSNet::VEHICLE_STATE_BUILT.
Referenced by MSRouteHandler::closeVehicle(), MSInsertionControl::determineCandidates(), METriggeredCalibrator::execute(), MSCalibrator::execute(), MSStateHandler::myStartElement(), and TraCIServerAPI_Vehicle::processSet().
bool MSVehicleControl::checkVType (const std::string & id) private
Checks whether the vehicle type (distribution) may be added.
This method checks also whether the default type may still be replaced
Parameters
[in] id The id of the vehicle type (distribution) to add
Returns
Whether the type (distribution) may be added
Definition at line 228 of file MSVehicleControl.cpp.
References DEFAULT_PEDTYPE_ID, DEFAULT_VTYPE_ID, myDefaultPedTypeMayBeDeleted, myDefaultVTypeMayBeDeleted, myVTypeDict, and myVTypeDistDict.
Referenced by addVType(), addVTypeDistribution(), and getMinDeceleration().
SUMOTime MSVehicleControl::computeRandomDepartOffset () const
compute (optional) random offset to the departure time
Definition at line 106 of file MSVehicleControl.cpp.
References DELTA_T, MSRouteHandler::getParsingRNG(), and myMaxRandomDepartOffset.
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), buildVehicle(), and discountStateLoaded().
void MSVehicleControl::deleteVehicle (SUMOVehicle * v, bool discard = false) virtual
Deletes the vehicle.
Parameters
[in] v The vehicle to delete
Reimplemented in GUIVehicleControl, and GUIMEVehicleControl.
Definition at line 215 of file MSVehicleControl.cpp.
References SUMOVehicle::getID(), myDiscarded, myEndedVehNo, and myVehicleDict.
Referenced by MSInsertionControl::clearPendingVehicles(), MSRouteHandler::closeVehicle(), GUIMEVehicleControl::deleteVehicle(), GUIVehicleControl::deleteVehicle(), MSInsertionControl::determineCandidates(), METriggeredCalibrator::execute(), MSCalibrator::execute(), scheduleVehicleRemoval(), and MSInsertionControl::tryInsert().
void MSVehicleControl::discountStateLoaded () inline
avoid counting a vehicle twice if it was loaded from state and route input
Definition at line 428 of file MSVehicleControl.h.
References abortWaiting(), computeRandomDepartOffset(), and myLoadedVehNo.
Referenced by MSInsertionControl::determineCandidates(), and MSStateHandler::myStartElement().
int MSVehicleControl::getActiveVehicleCount () const inline
Returns the number of build vehicles that have not been removed or need to wait for a passenger or a container.
Returns
Number of active vehicles
Definition at line 243 of file MSVehicleControl.h.
References myEndedVehNo, myLoadedVehNo, myWaitingForContainer, and myWaitingForPerson.
Referenced by MSNet::simulationState().
int MSVehicleControl::getCollisionCount () const inline
return the number of collisions
Definition at line 249 of file MSVehicleControl.h.
References myCollisions.
Referenced by GUIApplicationWindow::checkGamingEvents(), MSNet::closeSimulation(), and GUINet::getParameterWindow().
int MSVehicleControl::getDepartedVehicleNo () const inline
Returns the number of inserted vehicles.
Returns
The number of vehicles that have entered the simulation so far
Definition at line 225 of file MSVehicleControl.h.
References getQuota(), myDiscarded, myEndedVehNo, myRunningVehNo, and SUMOReal.
Referenced by MSNet::closeSimulation(), GUINet::getParameterWindow(), MSNet::postSimStepOutput(), and MSNet::writeOutput().
int MSVehicleControl::getEmergencyStops () const inline
return the number of emergency stops
Definition at line 272 of file MSVehicleControl.h.
References myEmergencyStops.
Referenced by MSNet::closeSimulation().
int MSVehicleControl::getEndedVehicleNo () const inline
Returns the number of removed vehicles.
Returns
The number of vehicles that have left the simulation
Definition at line 209 of file MSVehicleControl.h.
References myEndedVehNo.
Referenced by GUINet::getParameterWindow(), and MSNet::writeOutput().
int MSVehicleControl::getLoadedVehicleNo () const inline
Returns the number of build vehicles.
Returns
The number of loaded (build) vehicles
Definition at line 201 of file MSVehicleControl.h.
References myLoadedVehNo.
Referenced by MSNet::closeSimulation(), GUINet::getParameterWindow(), and MSNet::writeOutput().
SUMOReal MSVehicleControl::getMaxSpeedFactor () const inline
return the maximum speed factor for all vehicles that ever entered the network
Definition at line 441 of file MSVehicleControl.h.
References myMaxSpeedFactor.
Referenced by MSLane::getMaximumBrakeDist().
SUMOReal MSVehicleControl::getMinDeceleration () const inline
return the minimum deceleration capability for all vehicles that ever entered the network
Definition at line 446 of file MSVehicleControl.h.
References checkVType(), and myMinDeceleration.
Referenced by MSLane::getMaximumBrakeDist().
int MSVehicleControl::getQuota (SUMOReal frac = -1) const
Returns the number of instances of the current vehicle that shall be emitted considering that "frac" of all vehicles shall be emitted overall if a negative fraction is given the demand scaling factor is used (–scale)
Returns
the number of vehicles to create (something between 0 and ceil(frac))
Definition at line 372 of file MSVehicleControl.cpp.
References myLoadedVehNo, and myScale.
Referenced by MSRouteHandler::closeVehicle(), MSInsertionControl::determineCandidates(), MSDevice::equippedByDefaultAssignmentOptions(), and getDepartedVehicleNo().
int MSVehicleControl::getRunningVehicleNo () const inline
Returns the number of build and inserted, but not yet deleted vehicles.
Returns
The number simulated vehicles (including those in teleporter)
Definition at line 217 of file MSVehicleControl.h.
References myRunningVehNo.
Referenced by MSNet::closeSimulation(), GUINet::getParameterWindow(), GUIApplicationWindow::handleEvent_SimulationStep(), MSNet::postSimStepOutput(), GUINet::setSimDuration(), MSNet::simulationStep(), and MSNet::writeOutput().
int MSVehicleControl::getTeleportCount () const
return the number of teleports (including collisions)
Definition at line 390 of file MSVehicleControl.cpp.
References myCollisions, myTeleportsJam, myTeleportsWrongLane, myTeleportsYield, and MSLane::teleportOnCollision().
Referenced by MSNet::closeSimulation(), GUINet::getParameterWindow(), and getTeleportsWrongLane().
int MSVehicleControl::getTeleportsJam () const inline
return the number of teleports due to jamming
Definition at line 254 of file MSVehicleControl.h.
References myTeleportsJam.
Referenced by MSNet::closeSimulation().
int MSVehicleControl::getTeleportsWrongLane () const inline
return the number of teleports due to vehicles stuck on the wrong lane
Definition at line 264 of file MSVehicleControl.h.
References getTeleportCount(), and myTeleportsWrongLane.
Referenced by MSNet::closeSimulation().
int MSVehicleControl::getTeleportsYield () const inline
return the number of teleports due to vehicles stuck on a minor road
Definition at line 259 of file MSVehicleControl.h.
References myTeleportsYield.
Referenced by MSNet::closeSimulation().
SUMOReal MSVehicleControl::getTotalDepartureDelay () const inline
Returns the total departure delay.
Returns
Sum of steps vehicles had to wait until being inserted
Definition at line 280 of file MSVehicleControl.h.
References myTotalDepartureDelay.
Referenced by MSNet::writeOutput().
SUMOReal MSVehicleControl::getTotalTravelTime () const inline
Returns the total travel time.
Returns
Sum of travel times of arrived vehicles
Definition at line 288 of file MSVehicleControl.h.
References addVType(), addVTypeDistribution(), addWaiting(), DEFAULT_VTYPE_ID, getVType(), getWaitingVehicle(), hasVTypeDistribution(), insertVTypeIDs(), myTotalTravelTime, removeWaiting(), and SUMOReal.
Referenced by MSNet::writeOutput().
SUMOVehicle * MSVehicleControl::getVehicle (const std::string & id) const
Returns the vehicle with the given id.
If no vehicle with the given id is store din "myVehicleDict", 0 is returned.
Parameters
[in] id The id of the vehicle to retrieve
Returns
The vehicle with the given id, 0 if no such vehicle exists
Definition at line 205 of file MSVehicleControl.cpp.
References myVehicleDict.
Referenced by MSRouteHandler::closeVehicle(), MSInsertionControl::determineCandidates(), TraCIServerAPI_Vehicle::getPosition(), MESegment::loadState(), MSLane::loadState(), MSStateHandler::myStartElement(), TraCIServer::postProcessVTD(), TraCIServerAPI_Vehicle::processGet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_GUI::processSet(), MSCalibrator::removePending(), and GUINet::vehicleExists().
MSVehicleType * MSVehicleControl::getVType (const std::string & id = DEFAULT_VTYPE_ID, MTRand * rng = 0)
Returns the named vehicle type or a sample from the named distribution.
Parameters
[in] id The id of the vehicle type to return. If left out, the default type is returned.
Returns
The named vehicle type, or 0 if no such type exists
Definition at line 280 of file MSVehicleControl.cpp.
References DEFAULT_PEDTYPE_ID, DEFAULT_VTYPE_ID, myDefaultPedTypeMayBeDeleted, myDefaultVTypeMayBeDeleted, myVTypeDict, and myVTypeDistDict.
Referenced by MSRouteHandler::closeContainer(), MSRouteHandler::closePerson(), MSRouteHandler::closeVehicle(), MSInsertionControl::determineCandidates(), METriggeredCalibrator::execute(), MSCalibrator::execute(), getTotalTravelTime(), MSStateHandler::myStartElement(), MSRouteHandler::myStartElement(), MSCalibrator::myStartElement(), MSRouteHandler::openVehicleTypeDistribution(), TraCIServerAPI_VehicleType::processGet(), TraCIServerAPI_Vehicle::processSet(), TraCIServerAPI_VehicleType::processSet(), METriggeredCalibrator::remainingVehicleCapacity(), MSCalibrator::remainingVehicleCapacity(), and MSMeanData_Emissions::MSLaneMeanDataValues::write().
SUMOVehicle * MSVehicleControl::getWaitingVehicle (const MSEdge *const edge, const std::set< std::string > & lines, const SUMOReal position, const std::string ridingID)
Definition at line 331 of file MSVehicleControl.cpp.
References DEPART_TRIGGERED, Named::getID(), SUMOVehicle::getParameter(), MSVehicle::isStoppedInRange(), SUMOVehicleParameter::line, myWaiting, SUMOReal, toString(), and WRITE_WARNING.
Referenced by getTotalTravelTime(), MSContainer::MSContainerStage_Driving::proceed(), and MSPerson::MSPersonStage_Driving::proceed().
bool MSVehicleControl::hasVTypeDistribution (const std::string & id) const
Asks for a vehicle type distribution.
If vehicle type distribution with the id exists, true is returned, false otherwise.
Parameters
[in] id The id of the distribution
Returns
Whether the vehicle type distribution exists
Definition at line 274 of file MSVehicleControl.cpp.
References myVTypeDistDict.
Referenced by MSInsertionControl::add(), and getTotalTravelTime().
void MSVehicleControl::insertVTypeIDs (std::vector< std::string > & into) const
Inserts ids of all known vehicle types and vehicle type distributions to the given vector.
Parameters
[in] into The vector to fill with ids
Definition at line 299 of file MSVehicleControl.cpp.
References myVTypeDict, and myVTypeDistDict.
Referenced by getTotalTravelTime(), and TraCIServerAPI_VehicleType::processGet().
constVehIt MSVehicleControl::loadedVehBegin () const inline
Returns the begin of the internal vehicle map.
Returns
The begin of the internal vehicle map
Definition at line 165 of file MSVehicleControl.h.
References myVehicleDict.
Referenced by GUIApplicationWindow::checkGamingEvents(), MSVTypeProbe::execute(), MSVTKExport::getPositions(), MSVTKExport::getSpeed(), TraCIServerAPI_Vehicle::processGet(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSAmitranTrajectories::write(), and MSFullExport::writeVehicles().
constVehIt MSVehicleControl::loadedVehEnd () const inline
Returns the end of the internal vehicle map.
Returns
The end of the internal vehicle map
Definition at line 173 of file MSVehicleControl.h.
References myVehicleDict, and vehicleDeparted().
Referenced by GUIApplicationWindow::checkGamingEvents(), MSVTypeProbe::execute(), MSVTKExport::getPositions(), MSVTKExport::getSpeed(), TraCIServerAPI_Vehicle::processGet(), MSBatteryExport::write(), MSEmissionExport::write(), MSFCDExport::write(), MSAmitranTrajectories::write(), and MSFullExport::writeVehicles().
MSVehicleControl& MSVehicleControl::operator= (const MSVehicleControl & s) private
invalidated assignment operator
void MSVehicleControl::registerCollision () inline
registers one collision-related teleport
Definition at line 391 of file MSVehicleControl.h.
References myCollisions.
Referenced by MSLane::executeMovements(), and MSLane::handleCollisionBetween().
void MSVehicleControl::registerEmergencyStop () inline
register emergency stop
Definition at line 411 of file MSVehicleControl.h.
References myEmergencyStops, saveState(), setState(), and SUMOReal.
Referenced by MSVehicle::executeMove().
void MSVehicleControl::registerOneWaitingForContainer () inline
increases the count of vehicles waiting for a container to allow recogniztion of container related deadlocks
Definition at line 380 of file MSVehicleControl.h.
References myWaitingForContainer.
Referenced by MSRouteHandler::closeVehicle(), and MSVehicle::processNextStop().
void MSVehicleControl::registerOneWaitingForPerson () inline
increases the count of vehicles waiting for a person to allow recogniztion of person related deadlocks
Definition at line 368 of file MSVehicleControl.h.
References myWaitingForPerson.
Referenced by MSRouteHandler::closeVehicle(), and MSVehicle::processNextStop().
void MSVehicleControl::registerTeleportJam () inline
register one non-collision-related teleport
Definition at line 396 of file MSVehicleControl.h.
References myTeleportsJam.
Referenced by MSLane::executeMovements(), and MELoop::teleportVehicle().
void MSVehicleControl::registerTeleportWrongLane () inline
register one non-collision-related teleport
Definition at line 406 of file MSVehicleControl.h.
References myTeleportsWrongLane.
Referenced by MSLane::executeMovements().
void MSVehicleControl::registerTeleportYield () inline
register one non-collision-related teleport
Definition at line 401 of file MSVehicleControl.h.
References myTeleportsYield.
Referenced by MSLane::executeMovements().
void MSVehicleControl::removeWaiting (const MSEdge *const edge, SUMOVehicle * vehicle)
Removes a vehicle from the list of waiting vehicles to a given edge.
Definition at line 320 of file MSVehicleControl.cpp.
References myWaiting.
Referenced by getTotalTravelTime(), MSContainer::MSContainerStage_Driving::proceed(), MSPerson::MSPersonStage_Driving::proceed(), and MSVehicle::resumeFromStopping().
void MSVehicleControl::saveState (OutputDevice & out)
Saves the current state into the given stream.
Definition at line 169 of file MSVehicleControl.cpp.
References OutputDevice::closeTag(), myEndedVehNo, myLoadedVehNo, myRunningVehNo, myTotalDepartureDelay, myTotalTravelTime, myVehicleDict, myVTypeDict, myVTypeDistDict, OutputDevice::openTag(), SUMO_ATTR_BEGIN, SUMO_ATTR_DEPART, SUMO_ATTR_END, SUMO_ATTR_ID, SUMO_ATTR_NUMBER, SUMO_ATTR_PROBS, SUMO_ATTR_TIME, SUMO_ATTR_VTYPES, SUMO_TAG_DELAY, SUMO_TAG_VTYPE_DISTRIBUTION, and OutputDevice::writeAttr().
Referenced by registerEmergencyStop(), and MSStateHandler::saveState().
void MSVehicleControl::scheduleVehicleRemoval (SUMOVehicle * veh)
Removes a vehicle after it has ended.
Writes output to tripinfos and vehroutes if wished; decrements the number of running vehicles and increments the number of ended vehicles. Then deletes the vehicle using "deleteVehicle".
This method should be called for each vehicle that was inserted into the network and quits its ride.
Parameters
[in] veh The vehicle to remove
Definition at line 132 of file MSVehicleControl.cpp.
References OutputDevice::closeTag(), deleteVehicle(), SUMOVehicle::getDeparture(), OutputDevice::getDeviceByOption(), SUMOVehicle::getDevices(), MSNet::getInstance(), OptionsCont::getOptions(), MSNet::informVehicleStateListener(), myRunningVehNo, myTotalTravelTime, STEPS2TIME, and MSNet::VEHICLE_STATE_ARRIVED.
Referenced by MSVehicleTransfer::add(), MELoop::changeSegment(), MSVehicleTransfer::checkInsertions(), MSLane::detectCollisions(), MSLane::executeMovements(), TraCIServerAPI_Vehicle::processSet(), MESegment::receive(), and MSCalibrator::removePending().
void MSVehicleControl::setState (int runningVehNo, int loadedVehNo, int endedVehNo, SUMOReal totalDepartureDelay, SUMOReal totalTravelTime)
Sets the current state variables as loaded from the stream.
Definition at line 159 of file MSVehicleControl.cpp.
References myEndedVehNo, myLoadedVehNo, myRunningVehNo, myTotalDepartureDelay, and myTotalTravelTime.
Referenced by MSStateHandler::myStartElement(), and registerEmergencyStop().
void MSVehicleControl::unregisterOneWaitingForContainer () inline
decreases the count of vehicles waiting for a container to allow recogniztion of container related deadlocks
Definition at line 386 of file MSVehicleControl.h.
References myWaitingForContainer.
Referenced by MSContainer::MSContainerStage_Driving::proceed(), MSVehicle::processNextStop(), and MSVehicle::resumeFromStopping().
void MSVehicleControl::unregisterOneWaitingForPerson () inline
decreases the count of vehicles waiting for a person to allow recogniztion of person related deadlocks
Definition at line 374 of file MSVehicleControl.h.
References myWaitingForPerson.
Referenced by MSPerson::MSPersonStage_Driving::proceed(), MSVehicle::processNextStop(), and MSVehicle::resumeFromStopping().
void MSVehicleControl::vehicleDeparted (const SUMOVehicle & v)
Informs this control about a vehicle's departure.
If the mean waiting time shall be computed (f.e. for summary-output), the absolut waiting time is increased by the waiting time of the given vehicle.
Parameters
[in] v The inserted vehicle
Definition at line 149 of file MSVehicleControl.cpp.
References SUMOVehicleParameter::depart, MSVehicleType::getCarFollowModel(), SUMOVehicle::getChosenSpeedFactor(), SUMOVehicle::getDeparture(), MSNet::getInstance(), MSCFModel::getMaxDecel(), SUMOVehicle::getParameter(), SUMOVehicle::getVehicleType(), MSNet::informVehicleStateListener(), MAX2(), MIN2(), myMaxSpeedFactor, myMinDeceleration, myRunningVehNo, myTotalDepartureDelay, STEPFLOOR, STEPS2TIME, and MSNet::VEHICLE_STATE_DEPARTED.
Referenced by loadedVehEnd(), and MSBaseVehicle::onDepart().
Field Documentation
int MSVehicleControl::myCollisions protected
The number of collisions.
Definition at line 476 of file MSVehicleControl.h.
Referenced by getCollisionCount(), getTeleportCount(), and registerCollision().
bool MSVehicleControl::myDefaultPedTypeMayBeDeleted protected
Whether no pedestrian type was loaded.
Definition at line 531 of file MSVehicleControl.h.
Referenced by checkVType(), and getVType().
bool MSVehicleControl::myDefaultVTypeMayBeDeleted protected
Whether no vehicle type was loaded.
Definition at line 528 of file MSVehicleControl.h.
Referenced by checkVType(), and getVType().
int MSVehicleControl::myDiscarded protected
The number of vehicles which were discarded while loading.
Definition at line 473 of file MSVehicleControl.h.
Referenced by deleteVehicle(), and getDepartedVehicleNo().
int MSVehicleControl::myEmergencyStops protected
The number of emergency stops.
Definition at line 488 of file MSVehicleControl.h.
Referenced by getEmergencyStops(), and registerEmergencyStop().
int MSVehicleControl::myEndedVehNo protected
The number of removed vehicles.
Definition at line 470 of file MSVehicleControl.h.
Referenced by deleteVehicle(), getActiveVehicleCount(), getDepartedVehicleNo(), getEndedVehicleNo(), saveState(), and setState().
int MSVehicleControl::myLoadedVehNo protected
The number of build vehicles.
Definition at line 464 of file MSVehicleControl.h.
Referenced by MEVehicleControl::buildVehicle(), GUIMEVehicleControl::buildVehicle(), GUIVehicleControl::buildVehicle(), buildVehicle(), discountStateLoaded(), getActiveVehicleCount(), getLoadedVehicleNo(), getQuota(), saveState(), and setState().
SUMOTime MSVehicleControl::myMaxRandomDepartOffset protected
The maximum random offset to be added to vehicles departure times (non-negative)
Definition at line 546 of file MSVehicleControl.h.
Referenced by computeRandomDepartOffset(), and MSVehicleControl().
SUMOReal MSVehicleControl::myMaxSpeedFactor protected
The maximum speed factor for all vehicles in the network.
Definition at line 549 of file MSVehicleControl.h.
Referenced by getMaxSpeedFactor(), and vehicleDeparted().
SUMOReal MSVehicleControl::myMinDeceleration protected
The minimum deceleration capability for all vehicles in the network.
Definition at line 552 of file MSVehicleControl.h.
Referenced by getMinDeceleration(), and vehicleDeparted().
int MSVehicleControl::myRunningVehNo protected
The number of vehicles within the network (build and inserted but not removed)
Definition at line 467 of file MSVehicleControl.h.
Referenced by getDepartedVehicleNo(), getRunningVehicleNo(), saveState(), scheduleVehicleRemoval(), setState(), and vehicleDeparted().
SUMOReal MSVehicleControl::myScale protected
The scaling factor (especially for inc-dua)
Definition at line 543 of file MSVehicleControl.h.
Referenced by getQuota(), and MSVehicleControl().
int MSVehicleControl::myTeleportsJam protected
The number of teleports due to jam.
Definition at line 479 of file MSVehicleControl.h.
Referenced by getTeleportCount(), getTeleportsJam(), and registerTeleportJam().
int MSVehicleControl::myTeleportsWrongLane protected
The number of teleports due to vehicles stuck on the wrong lane.
Definition at line 485 of file MSVehicleControl.h.
Referenced by getTeleportCount(), getTeleportsWrongLane(), and registerTeleportWrongLane().
int MSVehicleControl::myTeleportsYield protected
The number of teleports due to vehicles stuck on a minor road.
Definition at line 482 of file MSVehicleControl.h.
Referenced by getTeleportCount(), getTeleportsYield(), and registerTeleportYield().
SUMOReal MSVehicleControl::myTotalDepartureDelay protected
The aggregated time vehicles had to wait for departure (in seconds)
Definition at line 497 of file MSVehicleControl.h.
Referenced by getTotalDepartureDelay(), saveState(), setState(), and vehicleDeparted().
SUMOReal MSVehicleControl::myTotalTravelTime protected
The aggregated time vehicles needed to aacomplish their route (in seconds)
Definition at line 500 of file MSVehicleControl.h.
Referenced by getTotalTravelTime(), saveState(), scheduleVehicleRemoval(), and setState().
VehicleDictType MSVehicleControl::myVehicleDict protected
Dictionary of vehicles.
Definition at line 510 of file MSVehicleControl.h.
Referenced by abortWaiting(), addVehicle(), deleteVehicle(), getVehicle(), GUIMEVehicleControl::insertVehicleIDs(), GUIVehicleControl::insertVehicleIDs(), loadedVehBegin(), loadedVehEnd(), saveState(), and ~MSVehicleControl().
VTypeDictType MSVehicleControl::myVTypeDict protected
Dictionary of vehicle types.
Definition at line 520 of file MSVehicleControl.h.
Referenced by addVType(), checkVType(), getVType(), insertVTypeIDs(), MSVehicleControl(), saveState(), and ~MSVehicleControl().
VTypeDistDictType MSVehicleControl::myVTypeDistDict protected
A distribution of vehicle types (probability->vehicle type)
Definition at line 525 of file MSVehicleControl.h.
Referenced by addVTypeDistribution(), checkVType(), getVType(), hasVTypeDistribution(), insertVTypeIDs(), saveState(), and ~MSVehicleControl().
std::map<const MSEdge* const, std::vector<SUMOVehicle*> > MSVehicleControl::myWaiting protected
the lists of waiting vehicles to a given edge
Definition at line 534 of file MSVehicleControl.h.
Referenced by addWaiting(), getWaitingVehicle(), and removeWaiting().
int MSVehicleControl::myWaitingForContainer protected
the number of vehicles wainting for containers contained in myWaiting which can only continue by being triggered
Definition at line 540 of file MSVehicleControl.h.
Referenced by getActiveVehicleCount(), registerOneWaitingForContainer(), and unregisterOneWaitingForContainer().
int MSVehicleControl::myWaitingForPerson protected
the number of vehicles wainting for persons contained in myWaiting which can only continue by being triggered
Definition at line 537 of file MSVehicleControl.h.
Referenced by getActiveVehicleCount(), registerOneWaitingForPerson(), and unregisterOneWaitingForPerson().
The documentation for this class was generated from the following files:
MSVehicleControl.h
MSVehicleControl.cpp