SUMO - Simulation of Urban MObility: GNESelectorFrame Class Reference
GNESelectorFrame Class Reference
#include <GNESelectorFrame.h>
Public Types
enum SetOperation {
SET_ADD = 1, SET_SUB = 2, SET_RESTRICT = 3, SET_REPLACE = 4,
SET_DEFAULT = 5
}
FOX-declaration.
Public Member Functions
FXFont * getFrameHeaderFont () const
get font of the header's frame
FXLabel * getFrameHeaderLabel () const
get the label for the frame's header
GNEViewNet * getViewNet () const
get view net
GNESelectorFrame (FXComposite *parent, GNEViewNet *viewNet)
Constructor.
void handleIDs (std::vector< GUIGlID > ids, bool selectEdges, SetOperation setop=SET_DEFAULT)
apply list of ids to the current selection according to SetOperation,
void hide ()
hide Frame
void selectionUpdated ()
called if currently registered for updates for changes of global selection
void show ()
show Frame
~GNESelectorFrame ()
Destructor.
FOX-callbacks
Called when the user presses the Load-button
Note
Opens a file dialog and forces the parent to load the list of selected objects when a file was chosen. Rebuilds the list, then, and redraws itself.
long onCmdLoad (FXObject *, FXSelector, void *)
long onCmdSave (FXObject *, FXSelector, void *)
Called when the user presses the Save-button.
long onCmdClear (FXObject *, FXSelector, void *)
Called when the user presses the Clear-button.
long onCmdInvert (FXObject *, FXSelector, void *)
Called when the user presses the Invert-button.
long onCmdSelMBTag (FXObject *, FXSelector, void *)
Called when the user selectes a tag in the match box.
long onCmdSelMBString (FXObject *, FXSelector, void *)
Called when the user enters a new selection expression.
long onCmdHelp (FXObject *, FXSelector, void *)
Called when the user clicks the help button.
long onCmdScaleSelection (FXObject *, FXSelector, void *)
Called when the user changes visual scaling.
Protected Member Functions
GNESelectorFrame ()
FOX needs this.
Protected Attributes
FXVerticalFrame * myContentFrame
the panel to hold all member widgets
FXFont * myFrameHeaderFont
Font for the Header.
FXLabel * myFrameHeaderLabel
the label for the frame's header
GNEViewNet * myViewNet
the window to inform when the tls is modfied
Private Member Functions
std::vector< GUIGlID > getMatches (SumoXMLTag tag, SumoXMLAttr attr, char compOp, SUMOReal val, const std::string &expr)
return objects of the given type with matching attrs
std::string getStats () const
get stats
Private Attributes
const std::string ALL_VCLASS_NAMES_MATCH_STRING
the string that should be matched against if attr 'allowed' or 'disalloed' are set to "all"
FXListBox * myMatchAttrBox
attributes of the match box
FXTextField * myMatchString
string of the match
FXListBox * myMatchTagBox
tag of the match box
FXRealSpinDial * mySelectionScaling
selection scaling
FXuint mySetOperation
how to modify selection
FXDataTarget mySetOperationTarget
target of modify selection
Detailed Description
The Widget for modifying selections of network-elements
Definition at line 47 of file GNESelectorFrame.h.
Member Enumeration Documentation
enum GNESelectorFrame::SetOperation
FOX-declaration.
operations of selector
Enumerator
SET_ADD
SET_SUB
SET_RESTRICT
SET_REPLACE
SET_DEFAULT
Definition at line 53 of file GNESelectorFrame.h.
Constructor & Destructor Documentation
GNESelectorFrame::GNESelectorFrame (FXComposite * parent, GNEViewNet * viewNet)
Constructor.
parent FXFrame in which this GNEFrame is placed viewNet viewNet that uses this GNEFrame
Definition at line 81 of file GNESelectorFrame.cpp.
References GNEAttributeCarrier::allowedTags(), MID_CHOOSEN_CLEAR, MID_CHOOSEN_INVERT, MID_CHOOSEN_LOAD, MID_CHOOSEN_SAVE, MID_GNE_SELECT_SCALE, MID_GNE_SELMB_STRING, MID_GNE_SELMB_TAG, MID_HELP, and toString().
GNESelectorFrame::~GNESelectorFrame ()
Destructor.
Definition at line 152 of file GNESelectorFrame.cpp.
References gSelected, and GUISelectedStorage::remove2Update().
GNESelectorFrame::GNESelectorFrame () inline protected
FOX needs this.
Definition at line 121 of file GNESelectorFrame.h.
Member Function Documentation
FXFont * GNEFrame::getFrameHeaderFont () const inherited
get font of the header's frame
Definition at line 94 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderFont.
FXLabel * GNEFrame::getFrameHeaderLabel () const inherited
get the label for the frame's header
Definition at line 88 of file GNEFrame.cpp.
References GNEFrame::myFrameHeaderLabel.
Referenced by GNEInspectorFrame::inspect().
std::vector< GUIGlID > GNESelectorFrame::getMatches (SumoXMLTag tag, SumoXMLAttr attr, char compOp, SUMOReal val, const std::string & expr) private
return objects of the given type with matching attrs
Parameters
[in] compOp One of {<,>,=} for matching against val or '@' for matching against expr
Definition at line 455 of file GNESelectorFrame.cpp.
References ALL_VCLASS_NAMES_MATCH_STRING, GNEAttributeCarrier::getAttribute(), GNENet::getGlIDs(), GNEViewNet::getNet(), GUIGlObjectStorage::getObjectBlocking(), GNEAttributeCarrier::getTag(), GUIGlObjectStorage::gIDStorage, GNEAttributeCarrier::isNumerical(), GNEFrame::myViewNet, SUMO_ATTR_ALLOW, SUMO_ATTR_DISALLOW, SUMOReal, toString(), and GUIGlObjectStorage::unblockObject().
Referenced by onCmdSelMBString().
std::string GNESelectorFrame::getStats () const private
get stats
Definition at line 364 of file GNESelectorFrame.cpp.
References GUISelectedStorage::getSelected(), GLO_ADDITIONAL, GLO_EDGE, GLO_JUNCTION, GLO_LANE, gSelected, and toString().
Referenced by selectionUpdated().
GNEViewNet * GNEFrame::getViewNet () const inherited
get view net
Definition at line 82 of file GNEFrame.cpp.
References GNEFrame::myViewNet.
Referenced by GNEInspectorFrame::AttrInput::onCmdSetAttribute().
void GNESelectorFrame::handleIDs (std::vector< GUIGlID > ids, bool selectEdges, SetOperation setop = SET_DEFAULT)
apply list of ids to the current selection according to SetOperation,
Note
if setop==SET_DEFAULT than the currently set mode (mySetOperation) is used
Definition at line 381 of file GNESelectorFrame.cpp.
References GNEViewNet::autoSelectNodes(), GNEEdge::getDest(), GUIGlObject::getGlID(), GUIGlObjectStorage::getObjectBlocking(), GUISelectedStorage::getSelected(), GNEEdge::getSource(), GUIGlObject::getType(), GNEViewNet::getUndoList(), GUIGlObjectStorage::gIDStorage, GLO_LANE, gSelected, mySetOperation, GNEFrame::myViewNet, GNEUndoList::p_begin(), GNEUndoList::p_end(), SET_ADD, SET_DEFAULT, SET_REPLACE, SET_RESTRICT, SET_SUB, and GUIGlObjectStorage::unblockObject().
Referenced by onCmdLoad(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), onCmdSelMBString(), and GNEViewNet::onLeftBtnRelease().
void GNESelectorFrame::hide () virtual
hide Frame
Implements GNEFrame.
Definition at line 355 of file GNESelectorFrame.cpp.
References GNEViewNet::getViewParent(), gSelected, GNEViewParent::hideFramesArea(), GNEFrame::myViewNet, and GUISelectedStorage::remove2Update().
Referenced by GNEViewNet::updateModeSpecificControls().
long GNESelectorFrame::onCmdClear (FXObject * , FXSelector , void *)
Called when the user presses the Clear-button.
Note
Clear the internal list and calls GUISelectedStorage::clear and repaints itself
Definition at line 199 of file GNESelectorFrame.cpp.
References GUISelectedStorage::getSelected(), GNEViewNet::getUndoList(), gSelected, and GNEFrame::myViewNet.
long GNESelectorFrame::onCmdHelp (FXObject * , FXSelector , void *)
Called when the user clicks the help button.
Note
pop up help window
Definition at line 301 of file GNESelectorFrame.cpp.
long GNESelectorFrame::onCmdInvert (FXObject * , FXSelector , void *)
Called when the user presses the Invert-button.
Note
invert the selection and repaints itself
Definition at line 207 of file GNESelectorFrame.cpp.
References GNENet::getGlIDs(), GNEViewNet::getNet(), GLO_ADDITIONAL, GLO_EDGE, GLO_JUNCTION, GLO_LANE, gSelected, GNEFrame::myViewNet, GNEViewNet::selectEdges(), and GUISelectedStorage::toggleSelection().
long GNESelectorFrame::onCmdLoad (FXObject * , FXSelector , void *)
Definition at line 157 of file GNESelectorFrame.cpp.
References gCurrentFolder, GUIIconSubSys::getIcon(), gSelected, handleIDs(), ICON_EMPTY, GUISelectedStorage::loadIDs(), and GNEFrame::myViewNet.
long GNESelectorFrame::onCmdSave (FXObject * , FXSelector , void *)
Called when the user presses the Save-button.
Note
Opens a file dialog and forces the selection container to save the list of selected objects when a file was chosen. If the saveing failed, a message window is shown.
Definition at line 183 of file GNESelectorFrame.cpp.
References gCurrentFolder, MFXUtils::getFilename2Write(), GUIIconSubSys::getIcon(), gSelected, ICON_EMPTY, and GUISelectedStorage::save().
long GNESelectorFrame::onCmdScaleSelection (FXObject * , FXSelector , void *)
Called when the user changes visual scaling.
Definition at line 337 of file GNESelectorFrame.cpp.
References FX::FXRealSpinDial::getValue(), mySelectionScaling, GNEFrame::myViewNet, and GNEViewNet::setSelectionScaling().
long GNESelectorFrame::onCmdSelMBString (FXObject * , FXSelector , void *)
Called when the user enters a new selection expression.
Note
validates expression and modifies current selection
Definition at line 243 of file GNESelectorFrame.cpp.
References GNEAttributeCarrier::allowedAttributes(), GNEAttributeCarrier::allowedTags(), getMatches(), handleIDs(), GNEAttributeCarrier::isNumerical(), myMatchAttrBox, myMatchString, myMatchTagBox, and SUMOReal.
long GNESelectorFrame::onCmdSelMBTag (FXObject * , FXSelector , void *)
Called when the user selectes a tag in the match box.
Note
updates the attr listbox and repaints itself
Definition at line 226 of file GNESelectorFrame.cpp.
References GNEAttributeCarrier::allowedAttributes(), GNEAttributeCarrier::allowedTags(), myMatchAttrBox, myMatchTagBox, and toString().
void GNESelectorFrame::selectionUpdated () virtual
called if currently registered for updates for changes of global selection
Implements GUISelectedStorage::UpdateTarget.
Definition at line 374 of file GNESelectorFrame.cpp.
References getStats(), and GNEFrame::myFrameHeaderLabel.
Referenced by show().
void GNESelectorFrame::show () virtual
show Frame
Implements GNEFrame.
Definition at line 345 of file GNESelectorFrame.cpp.
References GUISelectedStorage::add2Update(), GNEViewNet::getViewParent(), gSelected, GNEFrame::myViewNet, selectionUpdated(), and GNEViewParent::showFramesArea().
Referenced by GNEViewNet::updateModeSpecificControls().
Field Documentation
const std::string GNESelectorFrame::ALL_VCLASS_NAMES_MATCH_STRING private
the string that should be matched against if attr 'allowed' or 'disalloed' are set to "all"
Definition at line 151 of file GNESelectorFrame.h.
Referenced by getMatches().
FXVerticalFrame* GNEFrame::myContentFrame protected inherited
the panel to hold all member widgets
Definition at line 94 of file GNEFrame.h.
Referenced by GNEFrame::GNEFrame().
FXFont* GNEFrame::myFrameHeaderFont protected inherited
Font for the Header.
Definition at line 88 of file GNEFrame.h.
Referenced by GNEFrame::getFrameHeaderFont(), GNEFrame::GNEFrame(), and GNEFrame::~GNEFrame().
FXLabel* GNEFrame::myFrameHeaderLabel protected inherited
the label for the frame's header
Definition at line 91 of file GNEFrame.h.
Referenced by GNEFrame::getFrameHeaderLabel(), GNEFrame::GNEFrame(), and selectionUpdated().
FXListBox* GNESelectorFrame::myMatchAttrBox private
attributes of the match box
Definition at line 134 of file GNESelectorFrame.h.
Referenced by onCmdSelMBString(), and onCmdSelMBTag().
FXTextField* GNESelectorFrame::myMatchString private
string of the match
Definition at line 137 of file GNESelectorFrame.h.
Referenced by onCmdSelMBString().
FXListBox* GNESelectorFrame::myMatchTagBox private
tag of the match box
Definition at line 131 of file GNESelectorFrame.h.
Referenced by onCmdSelMBString(), and onCmdSelMBTag().
FXRealSpinDial* GNESelectorFrame::mySelectionScaling private
selection scaling
Definition at line 140 of file GNESelectorFrame.h.
Referenced by onCmdScaleSelection().
FXuint GNESelectorFrame::mySetOperation private
how to modify selection
Definition at line 125 of file GNESelectorFrame.h.
Referenced by handleIDs().
FXDataTarget GNESelectorFrame::mySetOperationTarget private
target of modify selection
Definition at line 128 of file GNESelectorFrame.h.
GNEViewNet* GNEFrame::myViewNet protected inherited
the window to inform when the tls is modfied
Definition at line 85 of file GNEFrame.h.
Referenced by GNEAdditionalFrame::addAdditional(), GNEConnectorFrame::buildIinternalLanes(), GNETLSEditorFrame::buildIinternalLanes(), GNETLSEditorFrame::editJunction(), GNEAdditionalFrame::generateID(), getMatches(), GNEFrame::getViewNet(), GNETLSEditorFrame::handleChange(), handleIDs(), GNEConnectorFrame::handleLaneClick(), GNETLSEditorFrame::handleMultiChange(), GNEConnectorFrame::hide(), GNETLSEditorFrame::hide(), hide(), GNEInspectorFrame::hide(), GNEAdditionalFrame::hide(), GNEConnectorFrame::initTargets(), GNEConnectorFrame::onCmdCancel(), GNETLSEditorFrame::onCmdCancel(), onCmdClear(), GNEConnectorFrame::onCmdClearSelectedConnections(), GNEInspectorFrame::onCmdCopyTemplate(), GNETLSEditorFrame::onCmdDefCreate(), GNETLSEditorFrame::onCmdDefDelete(), GNETLSEditorFrame::onCmdDefSwitch(), onCmdInvert(), onCmdLoad(), GNEConnectorFrame::onCmdOK(), GNETLSEditorFrame::onCmdOK(), GNETLSEditorFrame::onCmdPhaseSwitch(), GNEConnectorFrame::onCmdResetSelectedConnections(), onCmdScaleSelection(), GNEConnectorFrame::onCmdSelectConflicts(), GNEConnectorFrame::onCmdSelectDeadEnds(), GNEConnectorFrame::onCmdSelectDeadStarts(), GNEConnectorFrame::onCmdSelectPass(), GNEInspectorFrame::onCmdSetBlocking(), GNEAdditionalFrame::removeAdditional(), GNEConnectorFrame::show(), GNETLSEditorFrame::show(), show(), GNEInspectorFrame::show(), and GNEAdditionalFrame::show().
The documentation for this class was generated from the following files:
GNESelectorFrame.h
GNESelectorFrame.cpp