SUMO - Simulation of Urban MObility: TraCIAPI::GUIScope Class Reference
TraCIAPI::GUIScope Class Reference
Scope for interaction with the gui.
#include <TraCIAPI.h>
Public Member Functions
TraCIBoundary getBoundary (const std::string &viewID=DEFAULT_VIEW) const
std::vector< std::string > getIDList () const
TraCIPosition getOffset (const std::string &viewID=DEFAULT_VIEW) const
std::string getSchema (const std::string &viewID=DEFAULT_VIEW) const
SUMOReal getZoom (const std::string &viewID=DEFAULT_VIEW) const
GUIScope (TraCIAPI &parent)
void screenshot (const std::string &viewID, const std::string &filename) const
void setBoundary (const std::string &viewID, SUMOReal xmin, SUMOReal ymin, SUMOReal xmax, SUMOReal ymax) const
void setOffset (const std::string &viewID, SUMOReal x, SUMOReal y) const
void setSchema (const std::string &viewID, const std::string &schemeName) const
void setZoom (const std::string &viewID, SUMOReal zoom) const
void trackVehicle (const std::string &viewID, const std::string &vehID) const
virtual ~GUIScope ()
Protected Attributes
TraCIAPI & myParent
The parent TraCI client which offers the connection.
Private Member Functions
GUIScope (const GUIScope &src)
invalidated copy constructor
GUIScope & operator= (const GUIScope &src)
invalidated assignment operator
Detailed Description
Scope for interaction with the gui.
Definition at line 270 of file TraCIAPI.h.
Constructor & Destructor Documentation
TraCIAPI::GUIScope::GUIScope (TraCIAPI & parent) inline
Definition at line 272 of file TraCIAPI.h.
virtual TraCIAPI::GUIScope::~GUIScope () inline virtual
Definition at line 273 of file TraCIAPI.h.
References DEFAULT_VIEW, SUMOReal, TraCIAPI::TraCIPosition::x, and TraCIAPI::TraCIPosition::y.
TraCIAPI::GUIScope::GUIScope (const GUIScope & src) private
invalidated copy constructor
Member Function Documentation
TraCIAPI::TraCIBoundary TraCIAPI::GUIScope::getBoundary (const std::string & viewID = DEFAULT_VIEW) const
Definition at line 698 of file TraCIAPI.cpp.
References CMD_GET_GUI_VARIABLE, and VAR_VIEW_BOUNDARY.
std::vector< std::string > TraCIAPI::GUIScope::getIDList () const
Definition at line 678 of file TraCIAPI.cpp.
References CMD_GET_GUI_VARIABLE, ID_LIST, and SUMOReal.
TraCIAPI::TraCIPosition TraCIAPI::GUIScope::getOffset (const std::string & viewID = DEFAULT_VIEW) const
Definition at line 688 of file TraCIAPI.cpp.
References CMD_GET_GUI_VARIABLE, and VAR_VIEW_OFFSET.
std::string TraCIAPI::GUIScope::getSchema (const std::string & viewID = DEFAULT_VIEW) const
Definition at line 693 of file TraCIAPI.cpp.
References CMD_GET_GUI_VARIABLE, and VAR_VIEW_SCHEMA.
Referenced by TraCITestClient::testAPI().
SUMOReal TraCIAPI::GUIScope::getZoom (const std::string & viewID = DEFAULT_VIEW) const
Definition at line 683 of file TraCIAPI.cpp.
References CMD_GET_GUI_VARIABLE, and VAR_VIEW_ZOOM.
GUIScope& TraCIAPI::GUIScope::operator= (const GUIScope & src) private
invalidated assignment operator
void TraCIAPI::GUIScope::screenshot (const std::string & viewID, const std::string & filename) const
Definition at line 747 of file TraCIAPI.cpp.
References CMD_SET_GUI_VARIABLE, TYPE_STRING, VAR_SCREENSHOT, tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::testAPI().
void TraCIAPI::GUIScope::setBoundary (const std::string & viewID, SUMOReal xmin, SUMOReal ymin, SUMOReal xmax, SUMOReal ymax) const
Definition at line 734 of file TraCIAPI.cpp.
References CMD_SET_GUI_VARIABLE, TYPE_BOUNDINGBOX, VAR_VIEW_BOUNDARY, tcpip::Storage::writeDouble(), and tcpip::Storage::writeUnsignedByte().
void TraCIAPI::GUIScope::setOffset (const std::string & viewID, SUMOReal x, SUMOReal y) const
Definition at line 713 of file TraCIAPI.cpp.
References CMD_SET_GUI_VARIABLE, POSITION_2D, VAR_VIEW_OFFSET, tcpip::Storage::writeDouble(), and tcpip::Storage::writeUnsignedByte().
void TraCIAPI::GUIScope::setSchema (const std::string & viewID, const std::string & schemeName) const
Definition at line 724 of file TraCIAPI.cpp.
References CMD_SET_GUI_VARIABLE, TYPE_STRING, VAR_VIEW_SCHEMA, tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Referenced by TraCITestClient::testAPI().
void TraCIAPI::GUIScope::setZoom (const std::string & viewID, SUMOReal zoom) const
Definition at line 704 of file TraCIAPI.cpp.
References CMD_SET_GUI_VARIABLE, VAR_VIEW_ZOOM, and tcpip::Storage::writeDouble().
void TraCIAPI::GUIScope::trackVehicle (const std::string & viewID, const std::string & vehID) const
Definition at line 757 of file TraCIAPI.cpp.
References CMD_SET_GUI_VARIABLE, TYPE_STRING, VAR_TRACK_VEHICLE, tcpip::Storage::writeString(), and tcpip::Storage::writeUnsignedByte().
Field Documentation
TraCIAPI& TraCIAPI::TraCIScopeWrapper::myParent protected inherited
The parent TraCI client which offers the connection.
Definition at line 206 of file TraCIAPI.h.
The documentation for this class was generated from the following files:
TraCIAPI.h
TraCIAPI.cpp