SUMO - Simulation of Urban MObility: GNEAdditionalFrame::additionalSet Class Reference
GNEAdditionalFrame::additionalSet Class Reference
#include <GNEAdditionalFrame.h>
Public Member Functions
additionalSet (FXComposite *parent, FXObject *tgt, GNEViewNet *viewNet)
FOX-declaration.
SumoXMLTag getCurrentlyTag () const
get current tag
std::string getIdSelected () const
get if currently additional Set
void hideList ()
hide additionalSet
void showList (SumoXMLTag type)
Show list of additionalSet.
~additionalSet ()
destructor
FOX-callbacks
called when user select an additionalSet of the list
long onCmdSelectAdditionalSet (FXObject *, FXSelector, void *)
long onCmdHelp (FXObject *, FXSelector, void *)
Called when help button is pressed.
Protected Member Functions
additionalSet ()
FOX needs this.
Private Attributes
FXButton * helpAdditionalSet
button for help
FXList * myList
List of additional sets.
FXLabel * mySetLabel
Label with the name of Set.
SumoXMLTag myType
current type
GNEViewNet * myViewNet
viewNet associated to GNEAdditionalFrame
Detailed Description
Definition at line 333 of file GNEAdditionalFrame.h.
Constructor & Destructor Documentation
GNEAdditionalFrame::additionalSet::additionalSet (FXComposite * parent, FXObject * tgt, GNEViewNet * viewNet)
FOX-declaration.
constructor
Definition at line 1089 of file GNEAdditionalFrame.cpp.
References helpAdditionalSet, hideList(), MID_GNE_SELECTADDITIONALSET, MID_HELP, myList, and mySetLabel.
GNEAdditionalFrame::additionalSet::~additionalSet ()
destructor
Definition at line 1108 of file GNEAdditionalFrame.cpp.
GNEAdditionalFrame::additionalSet::additionalSet () inline protected
FOX needs this.
Definition at line 367 of file GNEAdditionalFrame.h.
Member Function Documentation
SumoXMLTag GNEAdditionalFrame::additionalSet::getCurrentlyTag () const
get current tag
Definition at line 1123 of file GNEAdditionalFrame.cpp.
References myType.
Referenced by GNEAdditionalFrame::addAdditional().
std::string GNEAdditionalFrame::additionalSet::getIdSelected () const
get if currently additional Set
Definition at line 1112 of file GNEAdditionalFrame.cpp.
References myList.
Referenced by GNEAdditionalFrame::addAdditional().
void GNEAdditionalFrame::additionalSet::hideList ()
hide additionalSet
Definition at line 1142 of file GNEAdditionalFrame.cpp.
References GNEAdditionalFrame::hide(), myType, and SUMO_TAG_NOTHING.
Referenced by additionalSet(), and GNEAdditionalFrame::setParametersOfAdditional().
long GNEAdditionalFrame::additionalSet::onCmdHelp (FXObject * , FXSelector , void *)
Called when help button is pressed.
Definition at line 1155 of file GNEAdditionalFrame.cpp.
long GNEAdditionalFrame::additionalSet::onCmdSelectAdditionalSet (FXObject * , FXSelector , void *)
Definition at line 1149 of file GNEAdditionalFrame.cpp.
void GNEAdditionalFrame::additionalSet::showList (SumoXMLTag type)
Show list of additionalSet.
Definition at line 1129 of file GNEAdditionalFrame.cpp.
References GNENet::getAdditionals(), GNEViewNet::getNet(), myList, mySetLabel, myType, myViewNet, GNEAdditionalFrame::show(), and toString().
Referenced by GNEAdditionalFrame::setParametersOfAdditional().
Field Documentation
FXButton* GNEAdditionalFrame::additionalSet::helpAdditionalSet private
button for help
Definition at line 380 of file GNEAdditionalFrame.h.
Referenced by additionalSet().
FXList* GNEAdditionalFrame::additionalSet::myList private
List of additional sets.
Definition at line 374 of file GNEAdditionalFrame.h.
Referenced by additionalSet(), getIdSelected(), and showList().
FXLabel* GNEAdditionalFrame::additionalSet::mySetLabel private
Label with the name of Set.
Definition at line 377 of file GNEAdditionalFrame.h.
Referenced by additionalSet(), and showList().
SumoXMLTag GNEAdditionalFrame::additionalSet::myType private
current type
Definition at line 371 of file GNEAdditionalFrame.h.
Referenced by getCurrentlyTag(), hideList(), and showList().
GNEViewNet* GNEAdditionalFrame::additionalSet::myViewNet private
viewNet associated to GNEAdditionalFrame
Definition at line 383 of file GNEAdditionalFrame.h.
Referenced by showList().
The documentation for this class was generated from the following files:
GNEAdditionalFrame.h
GNEAdditionalFrame.cpp